### ISSUE TITLE
Reader deep link opening incorrectly on iPad

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#10014]
### Expected behavior
Clicking a deep link that opens Reader (the given example came from a swarm email notification) on an iPad should load the post correctly on the right hand side of the split view.

### Actual behavior
The post is loaded on the left side of the split view.

### Steps to reproduce the behavior
Click on a deep reader link in an iPad.

**Comment by frosty** [comment]
Fixed by #10027.
