### ISSUE TITLE
Link photos to original

### ISSUE THREAD

**Issue by gryden1976** [wordpress-mobile/WordPress-iOS#10029]
When you upload a photo into the editor it's not linked to original photo. It used to be in earlier version of the iOS app (a year ago or more), but not anymore.

In the web editor photos are automatically linked to the original photo.

It would be nice to have consistency between platforms. My suggestion is to link photos in the iOS app as well, or at least give users an general option to do so.

**Comment by rachelmcr** [comment]
Thanks for the report! We are tracking this enhancement request here: https://github.com/wordpress-mobile/WordPress-iOS/issues/7596
