### ISSUE TITLE
Add support for password generation APIs

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#10031]
It would be good to help the user generate a secure password when creating a new WordPress.com account.

There are APIs available to do this:
- [ ] The 1Password SDK we already use [supports password generation](
https://href.li/?https://github.com/agilebits/onepassword-app-extension#use-case-2-new-user-registration)
- [x] iOS 12 also has a [password generator](
https://href.li/?https://robopress.robotsandpencils.com/strong-passwords-in-ios-12-8ec819b3b99)

Ideally we can detect when either of these APIs is available, and present them to the user.

_Note:_
LastPass [also has a similar SDK](https://github.com/lastpass/generic-password-app-extension), but adding support for more password managers feels like a business decision, cc @elibud

**Comment by elibud** [comment]
Thanks for the ping @nheagy, @SiobhyB @charliescheer @nellofb have you received requests for integrations with LastPass?

**Comment by SiobhyB** [comment]
I haven't come across requests like this but, on a personal level, it's something that I'd like to see! It'd make life a lot easier for me, but I also log out of the app and back in more than the average user.

**Comment by charliescheer** [comment]
I have never come across someone asking for lastpass either, but it would be good to add I think

**Comment by danielebogo** [comment]
Password generator for iOS 12 has been added on #10802 in _Me -> Settings -> Change Password_

**Comment by rachelmcr** [comment]
Closing this issue since the new Unified Login/Signup project plans to remove the option to add a password from signup altogether.
