### ISSUE TITLE
Add support for logging out from a self-hosted site

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-iOS#10045]
Logging out from a self-hosted site is not currently supported. It's supported on Android, but the feature is a bit hard to find. 
(My Site -> Switch Site -> long press on a self-hosted site)
![logout](https://user-images.githubusercontent.com/2261188/44644608-03b32380-a9d5-11e8-8dc3-8a586bccae6b.gif)
 

@nozomimimi Wdyt? Should it be implemented on iOS with Force Touch or should we rather come up with another solution?

**Comment by rachelmcr** [comment]
This is possible on iOS in two ways:

1. Select "Remove Site" at the bottom of the My Sites > Site detail screen.
2. Swipe to remove the site on the My Sites > Site list screen.

<img src="https://user-images.githubusercontent.com/8658164/76858793-122f8d00-6850-11ea-9711-5166e9679018.png" width="40%">
<img src="https://user-images.githubusercontent.com/8658164/76858786-0fcd3300-6850-11ea-8555-176656a0289a.png" width="40%">
