### ISSUE TITLE
WordPress.com Auth: No 2FA Support

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#10049]
### Steps:
1. Start logged out of the app.
2. Log in to a WordPress.com account, stopping when you get to the post-login screen (with Continue/Connect another site buttons).
3. Select “Connect another site.”
4. Enter the URL for a site connected to a different WordPress.com account with 2FA.
5. Enter the username and password for your other WordPress.com account with 2FA and tap Next.

Result: You get a message “This account has two step authentication enabled. Please configure an application-specific password to use with this application.”

Thanks @rachelmcr for the repro steps!!!

**Comment by nheagy** [comment]
Interesting. What's the solution here? If we do allow them to immediately login with a wordpress.com account, they'll replace the one they just added. Do we fix the 2FA issue, or do we disallow a second wordpress.com login?

Or do we just take a few months and add multiple wpcom account support? 😜

**Comment by rachelmcr** [comment]
When I was testing this flow, my main concern was that the user may not know the impact of trying to log in to another WordPress.com account here. From p4a5px-2ft-p2:

> This flow is meant for adding a non-Jetpack self-hosted site to the app. It might be helpful to have some kind of check in this flow to see if a user is trying to log in to a WordPress.com site owned by a different WordPress.com account, and to provide appropriate messaging/help in that case, since you can’t be logged in to two WordPress.com accounts at the same time.

Whatever we do to resolve this, if we don't add multiple wpcom account support it would be great to handle both of these cases:

- Educate users who really want multiple wpcom account support that we don't currently support it and direct them to information about managing multiple sites from a single account, e.g. this doc: https://en.support.wordpress.com/adding-users/
- Help users who just logged in to the wrong account (and don't really need multiple wpcom account support) log out and log back in to the correct account/site.

**Comment by jleandroperez** [comment]
@nheagy historically speaking, the app did support this scenario.

Single issue detailing this i could spot [dates from 2016](https://github.com/wordpress-mobile/WordPress-iOS/issues/4618) (check out it's repro steps).

The way this worked was:

1. You had a main WordPress.com account (Notifications, Blogs List)
2. You had a site, that happened to belong to another wpcom account (in your blog list)
3. You weren't getting Notifications for that "Other" wpcom account

I'm not really sure what happened along the way, but the behavior was never to "replace" the main wpcom account. Sounds like something was changed in the service layer, either on purpose or by accident.

The fix IMO either involves restoring this original behavior ^ (preferred!!), or adding some sort of alert?
