### ISSUE TITLE
Comments no results view obscures reply bar / text area

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#10062]
I just noticed that the new No Results view controller in the comments area obscures the reply / new comment bar. Not only is there the obvious visual issue, but it actually swallows any touches on that area, meaning you can't press the Reply button when you've finished typing. Sorry, I should've spotted this one when reviewing the PR!

![img_0265](https://user-images.githubusercontent.com/4780/44754198-ceafe980-ab18-11e8-954e-c6b45a5d133d.jpeg)

cc @ScoutHarris

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/10063
