### ISSUE TITLE
Differentiate between Scheduled and Published Post in Local Notification

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#10068]
### Expected behavior
When scheduling a post and waiting for it to upload in the background, I expect the notification to tell me a post has been scheduled instead of published.

### Actual behavior
Regardless of whether a post was scheduled or published the notification says it was published which is confusing.

### Steps to reproduce the behavior
Create a post, set it to be scheduled for later, and tap the Schedule button, then read the alert about the task proceeding in the background.

**Comment by frosty** [comment]
@kwonye Can you provide any more information about this one? I've just tested myself, and the notifications I see (both in the app and when the app is backgrounded) refer to the post being 'scheduled', not 'published'. Thanks!

**Comment by frosty** [comment]
Ah, guessing you mean the promo alert? 

![img_fd1b9492e110-1](https://user-images.githubusercontent.com/4780/45311593-7e298a80-b521-11e8-8c91-01abf273c741.jpeg)

**Comment by kwonye** [comment]
Thanks @frosty, yes, just that pop up then.
