### ISSUE TITLE
Add autosave for drafts

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#10069]
As a user is writing a blog post, there are many scenarios that could interrupt them before saving it themselves. Automatically saving in-progress posts as drafts would reduce lost posts.

### Proposed implementation

- As a user is creating/editing a post, automatically save a local draft frequently (say every few seconds)
- When the post is published, remove it from drafts

### Note:
This is distinct from #9287, though obviously both improve similar problems.

**Comment by yaelirub** [comment]
Closing as this was solved in: https://github.com/wordpress-mobile/WordPress-iOS/pull/10160
