### ISSUE TITLE
WPImageViewController has broken layout on rotation

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#10099]
Edit: This isn't just limited to gifs, and happens for any images viewed full screen.

When previewing gifs in `WPImageViewController`, the image doesn't remain fixed to the centre of the view if you rotate the device:

![](https://user-images.githubusercontent.com/154014/45043853-f67ce100-b033-11e8-97ed-66d58924e413.gif)

This affects the new Giphy integration, as well as simply previewing gifs that are already present in your media library.

**To reproduce**

Either:

* Upload a gif to the site via your computer
* Open the Media Library for a site
* Find the gif you uploaded, and tap to view its details
* Tap the gif preview to view it full screen
* Rotate the device

Or

* Open the Media Library for a site
* Tap +
* Choose Giphy
* Tap one or more gifs to preview
* Tap Preview in the bottom toolbar
* Rotate the device

Tested on iPhone X (device) and iPhone 8 (simulator), iOS 11.4 and iOS 12, WPiOS 10.8

**Comment by cameronvoell** [comment]
This seems to happen when previewing any image in the app (not just Gifs). See Video of previewing an image from an article in the Reader. (tested on latest develop 11/20/19 on emulator iPhone X: iOS 12.2, and App Store 13.6 on iPhone XR, iOS 12.4.1.

**Comment by frosty** [comment]
I think this is also related: https://github.com/wordpress-mobile/WordPress-iOS/issues/13757
