### ISSUE TITLE
Giphy: Apply for production API key

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#10093]
Use of the Giphy API requires an API key. While we're building the feature, we're using a development API key which is rate limited. We'll need to apply for a production key before we launch the feature fully.

Here's the relevant snippet from the [Giphy API docs](https://developers.giphy.com/docs/):

> Once you're ready to use the GIPHY API in production, please visit your dashboard to request a production API key for your application. In your submission, please be prepared to provide the following:
>
> * Your app name with brief description, web / app store links, etc.
> * The 'live date' of the app and feature that integrates with the API. Briefly describe how the GIPHY API integrates with your app and provide screenshots of the implementation.
> * As per our section 5 A of our terms of service, we require all apps that use the GIPHY API to conspicuously display "Powered By GIPHY" attribution marks where the API is utilized. Please provide screenshots of your attribution placement.

**Comment by frosty** [comment]
After looking into this, it looks like we're going to need to include the Giphy logo somewhere. The terms of service state:

> You shall (i) conspicuously label any Application with the words "Powered by Giphy," and the Giphy logo

@nozomimimi would you be able to provide some guidance on where will be best for us to include the logo? You can download the current attribution marks here: http://giphymedia.s3.amazonaws.com/giphy-attribution-marks.zip

I guess on the 'no results' screen makes the most sense:

![simulator screen shot - iphone 8 - 2018-09-04 at 14 31 26](https://user-images.githubusercontent.com/4780/45034974-c6900680-b050-11e8-9ed3-c2f677650bf5.png)

* Technically easiest would be replacing the existing 'no results' image that's there
* Replacing the current 'powered by giphy' footer text that's there would maybe fit best, but requires more changes
* Putting it in the navigation bar in place of the 'Giphy' title is also possible.

**Comment by iamthomasbishop** [comment]
My vote would be to replace the `no results` image with the Giphy logo. I would imagine we'll need to keep it slightly smaller, but I think that's probably the best bet.

**Comment by frosty** [comment]
Added the attribution image in https://github.com/wordpress-mobile/WordPress-iOS/pull/10109

**Comment by kwonye** [comment]
We got the API key!
