### ISSUE TITLE
Rich Notifications : Add custom actions to authentication flow notifications

### ISSUE THREAD

**Issue by ghost** [wordpress-mobile/WordPress-iOS#10097]
When executing the 2FA flow via the WP app, the user is presented with a basic push notification. 

The notification displayed on the phone provides no interactivity - the user must tap the notification to open the app. Upon doing so, the user is present with a static [alert](https://developer.apple.com/design/human-interface-guidelines/ios/views/alerts/) that [offers two options](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Utility/PushAuthenticationManager.swift#L137-L150): **Approve** or **Ignore**. 

**Note**: _a similar request is noted in #10023, with an emphasis on Apple Watch behavior._

**Comment by aerych** [comment]
Closed with #15253
