### ISSUE TITLE
Rich Notifications : New Post notifications

### ISSUE THREAD

**Issue by ghost** [wordpress-mobile/WordPress-iOS#10102]
In addition to _Comment_ notifications, we'd like to vend rich _New Post_ notifications.

With the server-side support in place, we should need to make the following client-side changes:

- Modify service extension to support the notifications of `type` : `new_post`
- Modify service extension to set `categoryIdentifier` to a value allowed by the content extension
- Modify content extension to vend a content view appropriate for that type
- Implement content view appropriate for `new_post` type

Additionally some `FormattableContent` work may be necessary to detect and/or add the banner image

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
