### ISSUE TITLE
Media Library not updating immediately

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#10100]
### Expected behavior
After uploading a picture it should be immediately available in the Media Library.

### Actual behavior
I can see the thumbnail on the list of available media sources, but once I navigate to the Media Library the image is not there.

### Steps to reproduce the behavior
1. Create a new post.
2. Upload a picture
3. Go to Post Settings, Set Featured Image.
4. Check the thumbnail for the Media Library, the uploaded image is there. 
5. Navigate to the library, the uploaded is not available.

![ezgif-2-fe0ff36797](https://user-images.githubusercontent.com/5558824/45096709-83d53980-b0f7-11e8-80b8-3bd9bc87b372.gif)

**Comment by joashrajin** [comment]
I've tested this out in JP Mobile and WP Mobile 22.4 but cannot replicate the issue. Looks like the bug is already fixed.
