### ISSUE TITLE
Reader: Enhanced reading settings

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10125]
We should consider enhanced reading settings in the Reader, such as:

- A Safari-style toggle to switch between the web and reader view
- Pocket/Kindle-style text controls in the reader view

Example of how this is done in Robinhood:

![image](https://user-images.githubusercontent.com/8658164/45228602-44137b00-b2cc-11e8-9ceb-367d980a6a00.png)

(Previous discussion for internal ref: p4a5px-2gl-p2)

**Comment by kean** [comment]
It is tracked in a dedicated project.
