### ISSUE TITLE
Edits to Gutenberg posts on WordPress.com sites are stripped

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10135]
### Expected behavior

I expect to be able to edit Gutenberg posts in the app, unless editing is prevented for now as suggested in https://github.com/wordpress-mobile/WordPress-iOS/issues/9191.

### Actual behavior

When I try to edit a post made in Gutenberg on a WordPress.com site (simple or atomic), any edits I make are stripped from the post when I update the draft.

### Steps to reproduce the behavior

1. Create a new draft in Gutenberg on a WordPress.com simple or atomic site.
2. Open the post in the app editor.
3. Add new text at the bottom of the draft.
4. Tap "Update" to save the changes.

Result: Changes made in the app are stripped from the post.

##### Tested on iPhone 6, iOS 11.4.1, WPiOS 10.8.0.20180903

**Comment by diegoreymendez** [comment]
Confirmed.  A fix is coming up soon.

**Comment by diegoreymendez** [comment]
A second PR includes a related fix: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1054

**Comment by diegoreymendez** [comment]
[This is the PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/10139) that will bring these fixes into WPiOS 10.8.

**Comment by diegoreymendez** [comment]
Resolved.
