### ISSUE TITLE
Tags search: on iPad, search bar moves when selected

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#10145]
### Expected behavior
Search bar remains.

### Actual behavior
Search bar moves to the right when selected.

### Steps to reproduce the behavior
- On an iPad
- Go to Site > Tags > search.
- Tap on the search bar.
- Notice it moves to the right.

<img width="650" alt="search_bar" src="https://user-images.githubusercontent.com/1816888/45381512-b92fca80-b5c2-11e8-96ff-ebc239526464.png">

**Comment by kean** [comment]
Outdated.
