### ISSUE TITLE
Plans: Plans never loads full description of plan features

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10164]
### Expected behavior

In the Plans section, I expect to see a full description of all the features of each plan.

### Actual behavior

When I first open the Plans section for my site, only the first feature in each plan loads.

Every time after that, when I open the Plans section I see all of the plan features but only the first line of the feature's description loads.

### Steps to reproduce the behavior

1. Go to My Sites.
2. Select Plans.
3. Select a plan.
4. Scroll through each plan.
5. Close the plan description.
6. Select a plan again.

### Screenshots

First time I opened the plan details: 

![2018-09-18 12 31 16](https://user-images.githubusercontent.com/8658164/45684888-9e6bd180-bb3f-11e8-8e5e-5a9c42715e54.png)

Screenshots of each plan (first time): https://cloudup.com/cKzuO7jCiFZ

Second time I opened the plan details: 

![2018-09-18 12 31 34](https://user-images.githubusercontent.com/8658164/45684894-a592df80-bb3f-11e8-9008-db62ab74343b.png)

Screenshots of each plan (second time): https://cloudup.com/cJI9FlCqtuy

**Comment by aerych** [comment]
The syncing issue that causes this should be sorted when we switch to a new endpoint. I'll loop back to confirm.

**Comment by thehenrybyrd** [comment]
I'm still seeing this, following Rachel's steps to reproduce above.
When viewing a plan for the first time, only the first feature appears.

**Tested on iPhone SE, iOS 12.1, WPiOS 11.1.**

**Comment by aerych** [comment]
Yep yep. We have not yet switched to the new endpoint, but its in the works!

**Comment by aerych** [comment]
Closing now that we're using the new endpoint.
