### ISSUE TITLE
Publicize: Remove Path sharing option

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10162]
Path is [closing on 18 October 2018](https://path.com/about).

We need to remove it as a connection option for Publicize (My Sites > Sharing).

**Comment by aerych** [comment]
Once Path is no longer returned from the REST API the apps should automatically stop showing Path as one of the available sharing options.  
We can confirm this in advance by editing the `meta/external-services` API endpoint response to remove path.

**Comment by lancewillett** [comment]
Deployed REST API change to remove Path, see D18492-code.
