### ISSUE TITLE
Posts: User unable to sync published posts

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10168]
A user reported being unable to load posts in the app that they published prior to installing the app on their device. The user has a WordPress.com Atomic site and is using an iPad Pro 12.9″, 2018.

I reproduced the issue on this user's site in a simulator — posts with other statuses (draft, scheduled, trashed) load as expected in the app, but the published posts filter never loads. Pulling to refresh the posts list results in the error "Unable to Sync" with this in the logs:

```
wp.com API error: :
Showing alert with title: Unable to Sync and message
```

Posts load as expected in Calypso web, so there's an issue here specific to the app and this site.

Internal ref: p4a5px-2ey-p2

**Comment by SiobhyB** [comment]
We're seeing another case of this in 1736293-zen. The user has a WP.com Atomic site and are seeing an "Unable to Sync" error when attempting to manage the posts from the app, the posts load correctly in Calypso.
