### ISSUE TITLE
Reader Comments: @ mentions seem to not be working

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#10177]
Sometime ago we added support for @ mentions to reader comments via #2707 (props @allendav).  Its been a rather hidden feature that probably not many are aware of, however @charliescheer has shared a report from a user that this feature no longer appears to work.   I performed a quick test on a blog I admin and also did not see the @ mention feature invoked. 

Let's investigate to determine if this is an accidental regression, or if the feature has certain requirements that just aren't likely to be met (e.g. blog must support mentions, user must be an admin, etc.).

**Comment by lancewillett** [comment]
This came up again recently via Monica O (Automattic):

She was trying to @ name mention in the iOS mobile app Reader view comments section, and nothing happened when typing the `@` sign.

(I also noted in the app editor view, the @ name mentions also don't work — when composing a post or page.)

**Comment by lancewillett** [comment]
Internal ref: p1P4aZ-3VH-p2

**Comment by frosty** [comment]
This should be fixed now, and is working for me on the latest build of the app.

**Comment by lancewillett** [comment]
Tested this today in version 14.1 of iOS app. Using "Automattic" Reader view on my iPhone XS was able to see the @ name mention list, click a name, and see it inserted into the comment field.

Yay!
