### ISSUE TITLE
Editor: Word count

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10176]
A number of users have requested a word/character count in the editor.

Currently in Calypso web this appears in the bottom right corner of the editor:

![2018-09-19 11 48 36](https://user-images.githubusercontent.com/8658164/45748985-3b8f3e80-bc02-11e8-8454-92dbe5ad0087.png)

Previous issue here: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/606

**Comment by yaelirub** [comment]
Hey @rachelmcr , I was going over the issues and this seems like a fun thing to work on, so I took this on. Hope thats ok. 😺
