### ISSUE TITLE
Files limit 2M

### ISSUE THREAD

**Issue by exrector** [wordpress-mobile/WordPress-iOS#10191]
please turn off or increase the limit for uploading files. On my server, I removed this restriction.

**Comment by rachelmcr** [comment]
Could you please share the exact message you received in the app? Thanks!

**Comment by joashrajin** [comment]
I've spent some time testing this out and can confirm this isn't happening on my end. I have a 512MB Upload Limit in WordPress and could upload large files with no problem using JP Mobile 22.4 & WPMobile 22.4
