### ISSUE TITLE
Reader cropping image in iPhone 7

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#10214]
### Expected behavior
Reader should display the full image on all devices.

### Actual behavior
In the user's iPhone 7 some images are cropped -verified that they are displayed correctly on 7plus and X-.

iPhone 7 
![image1](https://user-images.githubusercontent.com/5558824/46435045-6493f100-c723-11e8-987f-bddbdb19e369.png)
iPhone X
![img_1514](https://user-images.githubusercontent.com/5558824/46434961-24cd0980-c723-11e8-83a6-72dc3b40711b.PNG)|

### Steps to reproduce the behavior

1451169-zen

##### Tested on iPhone X/7plus, iOS 12, WPiOS 10.9

**Comment by designsimply** [comment]
I tested with my iPhone 6S device and found that the horse image on the Echo Bluff State Park post from `djsepicadventure.com` (pictured in the original issue) is cut off.

<img src="https://user-images.githubusercontent.com/1119271/66164744-94086280-e5f0-11e9-8792-385500558c0c.PNG" width="270" alt="IMG_3131">
<sup>Tested with WPiOS 13.3.0.0 (TestFlight) on iPhone 6S iOS 13.1.2.</sup>

**Comment by leandroalonso** [comment]
Fixed after the Reader Detail refactor.
