### ISSUE TITLE
Data for Segmented Control in Notifications Contains Translation

### ISSUE THREAD

**Issue by theck13** [wordpress-mobile/WordPress-iOS#10226]
The analytics data used for tracking the segmented control usage on the ***Notifications*** screen contains the filter title, which is translated into the user's selected language.  See [this code](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController.swift#L847-L848) for details.  The track should follow the naming convention below.

| Event | Property | Value |
|-|-|-|
| `notification_tapped_segmented_control` | `selected_filter` | `all`
| | | `comment` |
| | | `follow` |
| | | `like` |
| | | `unread` |

The associated Android pull request is https://github.com/wordpress-mobile/WordPress-Android/pull/8406.

**Comment by jkmassel** [comment]
Notifications no longer uses a segmented control – closing.
