### ISSUE TITLE
Textview formatbar disappear when select header button or listbutton items

### ISSUE THREAD

**Issue by CivelXu** [wordpress-mobile/WordPress-iOS#10221]
### Expected behavior

Textview formatbar show
### Actual behavior
Textview formatbar disappear

### Steps
1.  click formatbar header button or listbutton
2. click  header button or listbutton select items

### Screenshot
![image](https://user-images.githubusercontent.com/19768199/46591242-f5841700-caeb-11e8-919b-160a211f00da.png)

**Comment by rachelmcr** [comment]
Thank you for reporting this issue! I have moved it to our Aztec editor repo for further investigation: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/1067
