### ISSUE TITLE
Reader: Breaking constraints on post cards

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#10236]
When scrolling through the reader stream and changing orientation from portrait to landscape and back I'm seeing a *lot* of breaking constraints logged to the console.  

It would be nice to tidy these up as it seems they could be contributing to some occasional layout weirdness:
![simulator screen shot - iphone 8 - 2018-10-10 at 18 18 53](https://user-images.githubusercontent.com/1435271/46771921-3d0ccd80-ccbb-11e8-8594-0d06aa61c39b.png)

**Comment by leandroalonso** [comment]
Doesn't happen anymore.
