### ISSUE TITLE
View Site: Tapping a link or refresh button twice results in error

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10233]
### Expected behavior

I expect to be able to view my site and navigate around it to see how it looks.

### Actual behavior

If I double-tap a link or the refresh button while viewing my site, I get this error:

> Error
> The operation couldn't be completed.
> (NSURLErrorDomain error -999.)

At the very least I'd expect a clearer message that helps me avoid that error.

### Steps to reproduce the behavior

1. Go to My Sites.
2. Select View Site to open the site in the app.
3. Double tap the refresh button in the top right.

##### Tested on iPhone 6, iOS 12, WPiOS 10.9.0.20180914

We have received several recent reports from users, suggesting this is a new issue. (Internal ref: p4a5px-2hG-p2)

**Comment by eduardozulian** [comment]
Another report on 3894157-zen

Just noting that this happens with all links, not just the refresh icon/button.

**Comment by eduardozulian** [comment]
Also in 3926628-zen

**Comment by rachelmcr** [comment]
I just tested in WPiOS 19.7.0.2 and can no longer reproduce this issue. Closing as it seems to be resolved.
