### ISSUE TITLE
Reader: Keyboard on Manage screen covers the empty state CTA

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10260]
### Expected behavior

When I'm not following any sites, and I visit Reader > Followed Sites > Manage Sites, I expect to be able to either manually enter a site to follow or select the CTA button on the screen.

### Actual behavior

If I tap in the “Enter the URL …” field at the top of the page, the keyboard covers the CTA button on that screen and as far as I can tell there’s no way to dismiss the keyboard.

![image](https://user-images.githubusercontent.com/8658164/47010233-4e7c2c80-d136-11e8-8b5d-2385be360a8d.png)

### Steps to reproduce the behavior

1. Log in to the app with an account that follows no sites (or unfollow all sites).
2. Open the Reader.
3. Open the Followed Sites section.
4. Open the Manage Sites section. Note that there's an empty state message ("No followed sites") with a call to action.
5. Tap in the "Enter the URL ..." field at the top of the screen. The keyboard comes up so you can type in the URL of a site to follow.
6. Try to dismiss the keyboard to get back to the call to action button near the bottom of the screen.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/10266
