### ISSUE TITLE
Editor: Posts submitted by contributors not set as "Pending Review"

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10261]
Moved from https://github.com/wordpress-mobile/WordPress-iOS/issues/7600#issuecomment-385938355 cc @SiobhyB 

### Expected behavior

When a contributor creates a post and selects "Submit for Review" (the action on the top right of the editor), it should be set as "Pending Review."

### Actual behavior

As a Contributor, after you tap the option to "Submit for Review" in the app, it doesn't actually get set as "Pending Review". Instead, you're given a prompt to publish the post and it's saved as a draft. You have to then tap the "Publish" option to set it as "Pending Review", which is not intuitive. (Alternately, you have to open the Post Settings and manually change the status to "Pending Review.")

### Steps to reproduce the behavior

1. Log in to the app as a contributor on a site.
2. Start a new post on that site and enter a title and content.
3. Tap "Submit for Review."
4. Check the Blog Posts list for the post status. Note that it is saved as a draft with no "Pending Review" label.
5. Tap the "Publish" action on the post card in the post list. Note that now it is saved as pending review.

##### Tested on iPhone XS, iOS 12.0.1, WPiOS 11.0.0.20181010

Also reported in 278467-h.

**Comment by ceyhun** [comment]
I was not able reproduce this. The post has the "Pending Review" label in my case.

<p style="clear:both;"><sup>Tested with iPhone 11 Pro, iOS 14.4, WPiOS 17.0.0.20210329</sup></p>

**Comment by ceyhun** [comment]
Closing this as non reproducible but, please feel free to reopen if it still occurs, thanks!
