### ISSUE TITLE
Status in notifications list doesn't update after actions are performed

### ISSUE THREAD

**Issue by mikejohnstn** [wordpress-mobile/WordPress-iOS#1027]
If you reply to a comment via a notification, then return to the notifications list, the "Replied" status should be visible for that notification. It isn't visible until the list is forced to refresh.

**Comment by jleandroperez** [comment]
The WordPress.com hook is now adding a special range in the Notification's subject, containing the location + noticon character to be rendered if a comment was replied to.

This should look as follows:

![9t7yvfa-ly-3000x3000](https://cloud.githubusercontent.com/assets/1195260/5964453/f7a352fc-a7d2-11e4-8103-285396f77405.png)
