### ISSUE TITLE
Cleanup `splitViewControllerIsHorizontallyCompact` and `isViewHorizontallyCompact`

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#10281]
In #5158 we removed a duplicate definition of `isViewHorizontallyCompact`. Since then the project has been reorganized a few times, with the result that `isViewHorizontallyCompact` now resides inside `WordPressComStatsiOS` with the second implementation named `hasHorizontallyCompactView()` existing inside the `WordPressUI-iOS` pod.

An example is in `splitViewControllerIsHorizontallyCompact`:

```swift
extension UIViewController {
    @objc var splitViewControllerIsHorizontallyCompact: Bool {
        return splitViewController?.isViewHorizontallyCompact() ?? isViewHorizontallyCompact()
    }
}
```

This should probably change to using `hasHorizontallyCompactView()`, which is defined in `WordPressUI-iOS` which is probably a more appropriate location for it, and we should consider removing `isViewHorizontallyCompact` entirely, since stats has the UI pod as a dependency.

**Comment by megmil** [comment]
I searched `isViewHorizontallyCompact` in the project and didn't see any results. Should this be closed?

<img width="270" alt="Screenshot 2024-04-23 at 1 17 45 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/101139170/9b091cfb-5104-4829-ae6c-d4754982577a">

**Comment by kean** [comment]
The referenced code was removed in one of the earlier version and the Split View enable/disable logic simplified – closing.
