### ISSUE TITLE
Quick Start: table layout on iPad

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#10282]
### Expected behavior
I would expect the table to look good. 😄 

### Actual behavior
1) There are empty rows:
![portrait](https://user-images.githubusercontent.com/1816888/47179767-24fd0580-d2dc-11e8-9223-63c0a6efd16a.png)

2) In landscape, the row separators are indented:
![landscape](https://user-images.githubusercontent.com/1816888/47179783-35ad7b80-d2dc-11e8-968f-0e7fd79b1f6a.png)

### Steps to reproduce the behavior
- On an iPad, create a new site.
- Select 'Yes' on the Quick Start prompt.
- Go to Quick Start.

**Comment by danielebogo** [comment]
I'll close this since we introduced the new layout with QS V2
