### ISSUE TITLE
Post Preview: Videos don't load correctly in post previews

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10286]
### Expected behavior

I expect all media uploaded to or embedded in a post to appear in the post preview.

### Actual behavior

Videos added to a post never load correctly in the post preview.

VideoPress videos uploaded to the post show an error ("Unknown Error") in WPiOS 10.9 and an endless loading message ("Loading...") in WPiOS 11.0 beta.

Other video embeds (e.g. YouTube) in the post just show a blank space where the video should be.

### Steps to reproduce the behavior

1. Start a new post.
2. Upload a video and insert it in the post.
3. Save the post as a draft or publish it.
4. Preview the post.

##### Tested on iPhone XS, iOS 12.0.1, WPiOS 10.9 & 11.0.0.20181016

Also reported by a user with iPhone X, iOS 12, WPiOS 10.9 (internal ref: p4a5px-2i1-p2)

**Comment by thehenrybyrd** [comment]
Doing some testing of the new [Video Block](https://github.com/wordpress-mobile/gutenberg-mobile/issues/687), and I'm unable to play videos while previewing.

To reproduce:
1. Create a new post
2. Add a video block and add a video from media library
3. Preview the post and note that you can't play the video.

![IMG_1766](https://user-images.githubusercontent.com/15107387/59765837-9d6ef880-92a7-11e9-968b-2372ed0aefea.PNG)

**Comment by ceyhun** [comment]
I was not able reproduce this. I tested this using a Video block and uploading a video from the device.

<p style="clear:both;"><sup>Tested with iPhone 11 Pro, iOS 14.4, WPiOS 17.0.0.20210329</sup></p>

**Comment by ceyhun** [comment]
Closing this as non reproducible but, please feel free to reopen if it still occurs, thanks!
