### ISSUE TITLE
Confusing/Unhelpful Error at Login When XML-RPC Is Blocked

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#10293]
### Expected behavior

If I enter the URL for a WordPress site that blocks XML-RPC, I expect to receive a helpful error message that informs me why I'm not able to log into that site via the app.

### Actual behavior

The following error appears when a URL for a WordPress site that blocks XML-RPC is entered:

"We're sure this is a great site - but it's not a WordPress site, so you can't connect to it with the app."

Screenshot:

![img_0047 2](https://user-images.githubusercontent.com/2998162/47272220-69a5cc80-d57a-11e8-9223-ec95f1e316cf.PNG)

### Steps to reproduce the behavior

1. Navigate to the app's login screen and select the "Log in by entering site address" option.
2. Submit the URL to a site that blocks XML-RPC.

##### Tested on iPad mini, 10.9 of WordPress for iOS

cc-ing @etoledom, who worked on these error messages during a hack week in March: 

https://a8c.slack.com/archives/C9JMWK5HQ/p1520333424000220-slack-happier-hes

I've also opened https://github.com/wordpress-mobile/WordPress-Android/issues/8459 for Android.

**Comment by aerych** [comment]
A few thoughts: 
- We need to harmonize the messages shown between WPAndroid and WPiOS.
- This might be a good time to switch from our current self-hosted discovery logic to querying `public-api.wordpress.com/rest/v1.1/connect/site-info` or use this call as a fall back.
- When all else fails we might check for the [presence of the WP REST API](https://developer.wordpress.org/rest-api/using-the-rest-api/discovery/) to confirm we're dealing with a self-hosted site.
- In cases where we can't identify a WordPress site it would be nice if we could tweak the message shown to allow for cases the apps are wrong.
