### ISSUE TITLE
Quick Start: Suppress web tours

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#10297]
Now that we have Quick Start, the web's introductory tours can be confusing for users. For example, during the "View Site" step of QS it is possible to see this web tour:

![img_0155](https://user-images.githubusercontent.com/517257/47309490-63026e00-d5e9-11e8-975b-802e25be1c01.PNG)

However, if we add the param `?hide_tours=1` to the end of our request, those will be suppressed. (`1` can be anything that evaluated to `true`)

**Comment by frosty** [comment]
I think this is no longer an issue as we hide the masterbar on site previews. I just ran through creating a site and previewing it, and I didn't see the tour or masterbar.
