### ISSUE TITLE
Tracks: WPAnalyticsStatSignedIn may not be properly deanonymized 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#10300]
Some analytics investigation with @charlescearl has shown that the WPAnalyticsStatSignedIn (`wpios_signed_in`) event is being bumped in a way that makes it unclear if its coming from a wpcom or jetpack (or even a self-hosted) user.

Investigate how we're handling WPAnalyticsStatSignedIn and ensure that we A) have good account information and B) are properly refreshing tracks meta data prior to bumping the stat.

**Comment by ScoutHarris** [comment]
I think this has been resolved. We now have these tracks for the different scenarios:
- WPAnalyticsStatSignedIn (`signed_in`)
- WPAnalyticsStatSignedInToJetpack (`signed_into_jetpack`)
- WPAnalyticsStatAddedSelfHostedSiteButJetpackNotConnectedToWPCom (`self_hosted_blog_added_jetpack_not_connected`)
- WPAnalyticsStatAddedSelfHostedSite (`self_hosted_blog_added`)

**Comment by ScoutHarris** [comment]
FWIW, this did lead me to notice Apple & Google tracks weren't consistent (https://github.com/wordpress-mobile/WordPress-iOS/pull/12803).
