### ISSUE TITLE
[Site creation] VerticalsService: protocol and model objects

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10314]
We need a service to present the categories & verticals available for a given site type. Ideally this service will support UI "typeahead" querying

Project master thread: `p9wMUP-bk-p2`

Plan proposal: `p9wMUP-bs-p2`

**Comment by ctarda** [comment]
First draft implementation in the same PR as #10313, because it depends on it

**Comment by stevebaranski** [comment]
This issue can be closed, as the Site Creation project is complete.
