### ISSUE TITLE
[Site creation] SiteOptionsService: protocol and model objects

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10317]
A service to present the configurable information for a given site type, category & vertical. For example, the wireframes allow a business owner to include a map on her site. This may correspond to applicable `site_options`

Project master thread: `p9wMUP-bk-p2`

Plan proposal: `p9wMUP-bs-p2`

**Comment by stevebaranski** [comment]
This has been removed from scope.
