### ISSUE TITLE
[Site creation] SiteTypesService: protocol and model objects

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10313]
We need a service to vend the site types available. In the current experience, the three existing types are hard-coded

Project master thread: `p9wMUP-bk-p2`

Plan proposal: `p9wMUP-bs-p2`

**Comment by ctarda** [comment]
@stevebaranski I believe this might not be necessary anymore, what do you think?

**Comment by stevebaranski** [comment]
This issue is no longer necessary, as the Site Creation project is complete.
