### ISSUE TITLE
[Site creation] Remove feature flag & legacy site creation code

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10329]
In #10312, we introduced the feature flag for site creation. In #10341, we'll activate it for all build configurations in anticipation of launching the feature.

Post-release, we'll make a determination that site creation is successful, and it will emerge as the sole experience. At that time, we can remove the feature flag altogether. We can also remove the existing site creation code.

Project master thread: `p9wMUP-bk-p2`

Plan proposal: `p9wMUP-bs-p2`

**Comment by diegoreymendez** [comment]
@ctarda - I noticed this isn't done yet in `develop`.  I've taken the liberty of assigning this to me, as it was unassigned, but if you're already working on this, or want to work on this let me know.

**Comment by ctarda** [comment]
@diegoreymendez all yours!
