### ISSUE TITLE
[Site creation] [UI] Bottom sheet

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10325]
The wireframes depict a "bottom sheet" component, akin to the one used in the iOS Maps app. Unfortunately, however, this does not yet exist in the public `UIKit` API.

This task will consist of the following:

- [X] Evaluate available OSS implementations of a "bottom sheet", including : vitality of the project, permissiveness of the license, and expected behavior on both iPhone & iPad. Is it worth adoption such a third-party component, or can one be built internally with reuse in mind?
- [X] Report findings : should we incorporate an existing component or build our own?
- [X] With the chosen component, construct a prototype that displays existing behavior.

This task should precede both #10326 & #10327.

Project master thread: `p9wMUP-bk-p2`

Plan proposal: `p9wMUP-bs-p2`

**Comment by stevebaranski** [comment]
P2 post : `p9wMUP-bZ-p2`
