### ISSUE TITLE
[Site creation] [UI] Site Information Wizard Step

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10324]
Project master thread: `p9wMUP-bk-p2`

Plan proposal: `p9wMUP-bs-p2`

There will be two items to fill out for the user:

1. Business name (if business), Site title if another segment
2. Tagline

Skip button allows them to skip. Turns into a next button once any of the fields are filled.

**Comment by stevebaranski** [comment]
This issue can be closed, as the Site Creation project is complete.
