### ISSUE TITLE
[Site creation] [UI] Wizard and WizardStep protocols

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10321]
- `WizardStep` is a protocol that exposes id, and a header (view controller) and content (also a view controller)
- There would be a different implementation of WizardStep for each step.
- Those implementations of `WizardStep` would aggregate a reference to the service that they need to use ion order to fetch the information necessary to render themselves

Project master thread: `p9wMUP-bk-p2`

Plan proposal: `p9wMUP-bs-p2`

**Comment by stevebaranski** [comment]
This issue can be closed, as the Site Creation project is complete.
