### ISSUE TITLE
[Site creation] [UI] Model object: SiteCreatorOutput and SiteCreator

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10328]
An implementation of the builder pattern (`SiteBuilder`) that keeps track of the temporary state of the result that the wizard yields.

Project master thread: `p9wMUP-bk-p2`

Plan proposal: `p9wMUP-bs-p2`

**Comment by stevebaranski** [comment]
As discussed in today's grooming session, I will assume ownership of this ask, as it will be influenced by the ongoing API discussion as well as #10429.
