### ISSUE TITLE
[Site creation] Analytics

### ISSUE THREAD

**Issue by stevebaranski** [wordpress-mobile/WordPress-iOS#10335]
This issue is intended to capture the need for proper analytics support. Such support should:

- [x] Maintain parity with both the existing Site Creation flow (i.e., log the same events, perhaps with additional metadata) and the Android implementation.
- [x] Capture additional analytics events, particularly with regard to new steps in the flow.

We'll also want to ensure parity the Android implementation, captured by this [counterpart issue](
https://github.com/wordpress-mobile/WordPress-Android/issues/8509).

**Final scope** : `p9wMUP-eo-p2`
~**The preliminary scope of this task is being discussed here** : `p9wMUP-dZ-p2`~

Project master thread : `p9wMUP-bk-p2`
Plan proposal : `p9wMUP-bs-p2`

**Comment by kwonye** [comment]
We also want to make sure our internal analytics doc is updated

**Comment by stevebaranski** [comment]
> We also want to make sure our internal analytics doc is updated

Can you please share a link to this document for clarity?

**Comment by kwonye** [comment]
@stevebaranski good call! Adding to Android too.

 [Aggregate doc of all our tracks events](https://docs.google.com/spreadsheets/d/1sWo5K6GsaLzojBewS25o05XAqWAnyyRBNZ2S9wfjG2w/edit#gid=0)

**Comment by kwonye** [comment]
Sorry @stevebaranski I thought I wrote this, but I deleted the link to the private google doc due to feedback that we shouldn't be putting private links up here.

**Comment by kwonye** [comment]
This is very close to being done. With #10927 done, all that's left is fixing the verticals and domains screen buttons and I can open up a PR.
