### ISSUE TITLE
New post - text overlapping

### ISSUE THREAD

**Issue by Stojdza** [wordpress-mobile/WordPress-iOS#10342]
### Expected behavior
When I paste text while creating new post I expect placeholder "Share your story here…" to disappear

### Actual behavior
Text is overlapping with placeholder "Share your story here…"

### Steps to reproduce the behavior
- Start new post
- Placeholder "Share your story here…" is present
- Paste some text here

Result: Texts are overlapping. 

Screenshot:

![img_9179](https://user-images.githubusercontent.com/7116222/47509453-6e1dfe00-d876-11e8-89dd-46e10c59bf4f.png)

**Comment by elibud** [comment]
@diegoreymendez or @etoledom can you please take a look?

**Comment by diegoreymendez** [comment]
Will do @elibud

**Comment by diegoreymendez** [comment]
From what I could test today, this is no longer an issue.  Closing.
