### ISSUE TITLE
Privacy Settings: Crash reporting option

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#10344]
### Background
Currently the way our app works is that crash reporting is invisibly turned off when the user turns off analytics tracking. It is an "all or nothing" option. This is found under Me > App Settings > Privacy Settings > Collect information.

In order to encourage as many users as possible to participate in crash reporting, we should make it a separate option in the UI.

### Feature request
Change the privacy settings screen to the new design. Please substitute WordPress branding colors.
<img width="361" alt="screen shot 2018-10-29 at 9 09 50 am" src="https://user-images.githubusercontent.com/1062444/47655180-71590880-db5a-11e8-8169-943618933de3.png">

**Comment by mindgraffiti** [comment]
Hi @varun989! Apologies for the late reply, I had extended AFK. 

To get started, please check out the [project ReadMe](https://github.com/wordpress-mobile/WordPress-iOS). Once you're able to build and run the app in Xcode, set up your own branch and create a PR. You can ping me anyone else for a review. 

The icons should be available in the Gridicons pod, and the colors should be the usual WordPress brand colors. If you have any questions about this task, feel free to ask here or [join the WordPress Slack](https://make.wordpress.org/chat/), and visit the `#mobile` channel.

**Comment by varun989** [comment]
Thanks!
