### ISSUE TITLE
Editor: Character count includes newlines and media

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10343]
### Expected behavior

I expect the word/character count to only count text.

### Actual behavior

I created a post with the word “Test,” a new line, and a photo. The count correctly shows 1 word but it seems to count the new line as 1 character and the photo as 1 character, for a total of 1 word and 6 characters:

![image](https://user-images.githubusercontent.com/8658164/47511791-dbc82b00-d872-11e8-80e3-9d6ec62bad1c.png)

### Steps to reproduce the behavior

1. Create a new post.
2. Add text to the post editor.
3. Pull up the action sheet and confirm the word/character count is correct.
4. Add a new line and check the word/character count.
5. Add a photo and check the word/character count.

Result: The character count goes up as you add new lines and photos.

##### Tested on iPhone XS, iOS 12.0.1, WPiOS 11.1.0.20181023

**Comment by madhumithap** [comment]
@rachelmcr 
Do we intend to count the punctuations or omit them too in character count?

**Comment by stevebaranski** [comment]
In my testing, word count appears to be working correctly. Character count, on the other hand, is failing to exclude some special characters. 

The fix requires a small change to the `charactersCount` computed property in `AztecPostViewController`.
