### ISSUE TITLE
Bug: 'Send' button colour conflict when sharing to What's App.

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-iOS#10352]
### Expected behavior

I would expect the button to Send to display white on the blue background.

### Actual behavior

The button shows a different shade of blue which makes it almost impossible to see. 
![img_e330072c7b5e-1](https://user-images.githubusercontent.com/10325627/47621240-e68df480-daec-11e8-86d6-8777832b37be.jpeg)

### Steps to reproduce the behavior

1. From the My Sites tab, click on View Site.
2. Click on the Share button at the bottom of the screen and select What's App.
3. Select a contact and click on Next.
4. The option to share appears with the 'share' button very light in the top bar as shown in the screenshot.

**Comment by rachelmcr** [comment]
Thanks for the report! I'm going to close this issue as it's also being tracked in https://github.com/wordpress-mobile/WordPress-iOS/issues/8912.
