### ISSUE TITLE
Editing: App strips spacer blocks from Gutenberg posts

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10362]
### Expected behavior

I expect the app to retain all Gutenberg blocks, even if I can't edit them visually in the app.

### Actual behavior

The app strips Spacer blocks from Gutenberg posts.

### Steps to reproduce the behavior

1. Create a new post in Gutenberg web.
2. Add content with at least one Spacer block.
3. Save the post.
4. Open the post in the iOS app.
5. Edit the post (e.g. change the title) and update it.

Result: The Spacer blocks are stripped.

##### Tested on iPhone XS, iOS 12.0.1, WPiOS 11.1.0.20181023
(I also tested this in WPAndroid alpha-133 but it wasn't an issue there.)

**Comment by rachelmcr** [comment]
cc @diegoreymendez - We don't have any user reports of this issue yet but I wanted to put it on your radar in case there's an easy fix for Aztec.

**Comment by diegoreymendez** [comment]
A fix was submitted for review: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1079
