### ISSUE TITLE
Editor: Editing a Gutenberg post in Aztec breaks embeds

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10361]
### Expected behavior

I expect any embeds in a Gutenberg post to remain intact when editing the post in the app.

### Actual behavior

Editing the post in the app breaks embeds, e.g. YouTube, Twitter, Instagram, or Facebook Gutenberg blocks. This is related to https://github.com/wordpress-mobile/AztecEditor-iOS/issues/589.

Even if you don't change the post content, editing the post in the app converts the embeds into links.

### Steps to reproduce the behavior

1. Create a new post in Gutenberg web.
2. Add at least one embed block, e.g. a YouTube block.
3. Save the post.
4. Open the post in the iOS app.
5. Edit the post (e.g. change the title) and update it.
6. View the post on the web.

Result: The embeds are converted to links.

Note that editing the post in Gutenberg will fix the embeds, but if you don't do this the embeds will remain broken.

##### Tested on iPhone XS, iOS 12.0.1, WPiOS 11.1.0.20181023
(I also tested this in WPAndroid alpha-133 but it wasn't an issue there.)

**Comment by rachelmcr** [comment]
cc @diegoreymendez / @jkmassel - We don't have any user reports of this yet but I wanted to put it on your radar given the work being done in https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1070. I'd predict this to be one of the bigger issues we see with Gutenberg & Aztec compatibility.

**Comment by ceyhun** [comment]
Issue still happens for me if I select "Switch to classic editor" after opening the post in Gutenberg editor in the app.

<p style="clear:both;"><sup>Tested with iPhone 11 Pro, iOS 14.4, WPiOS 17.0.0.20210329</sup></p>

**Comment by ceyhun** [comment]
Closing this Classic editor issue since the Classic editor is being deprecated on mobile at the time of writing. That said, if you find the issue occurring in the block editor as well, please feel free to open and repurpose, thanks!
