### ISSUE TITLE
Authors can not publish posts on self hosted sites

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#10370]
Hey y'all, I was doing some testing with the iOS app and I noticed that if you are connected to a self hosted site, not through jetpack, on an account that is set as an author, publishing posts fail.

I poked around a few different possibilities in this and these are what I found:
Self hosted site – no jetpack – user account set to author (upload failed)
self hosted site – jetpack – user account not connected to wpcom set to author (upload failed)
self hosted site – jetpack – wpcom account set as author (upload succeeded)

To test this:
1. Create an account on a self hosted site with or with out Jetpack installed, make sure to set that account as an author and do not connect it to a WordPress.com account via jetpack.
2. Use the "site address" login flow to connect directly to that account
3. Try to publish a post from that account you will get this error
<img src='http://cld.wthms.co/ArVqSn+'>

Tested on WPiOS 11
iOS 12.0.1
iPhone 6s

**Comment by charliescheer** [comment]
Update on this I just tried the same thing as a contributor and had the same problem occur.  In at least one ticket we have seen this problem reported, when the user changed to the account being an admin the problem was resolved.  I  converted the same account I've been using to test this to an admin and it did work, but did not as contributor or author.

**Comment by charliescheer** [comment]
#1517909-zen

**Comment by donalirl** [comment]
Another case of a user who is an author on two self-hosted sites, one with Jetpack connected and one without. More details in #1560518-zen.

**Comment by SiobhyB** [comment]
This came up again in 1559135-z, tested and confirmed.

**Comment by SiobhyB** [comment]
Again in 1568960-z, the owner of that site has more than author facing this problem.
