### ISSUE TITLE
[Stats Refresh] Period stats: show loading view

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#10380]
On the Stats Period data views, show a loading view while the data is loading.

Currently, the Period view is shown with no data:

![period_loading](https://user-images.githubusercontent.com/1816888/47866329-1296c780-ddc4-11e8-8aeb-648388f8b5be.png)

We should show the typical loading view. For example (from Activities):

![loading](https://user-images.githubusercontent.com/1816888/47866222-c186d380-ddc3-11e8-83b5-925c9d187be1.png)

**Comment by danielebogo** [comment]
Done in #11634 and #11711
