### ISSUE TITLE
Undo option on the editor

### ISSUE THREAD

**Issue by gemmagarner** [wordpress-mobile/WordPress-iOS#10397]
### Expected behavior
A user was expecting to see an Undo option on the editor in the iOS app.

### Actual behavior
There is no message about using the native "shake to undo" functionality, so the user didn't think it was possible to undo the change they made to a post.

### Steps to reproduce the behavior
1. Go to Blog Posts
2. Select an existing post
3. Make a change to the existing text

Unless you know about the native "shake to undo" functionality, it's not easy to see the change can be undone.

##### Tested on iPhone 6, iOS 12.1, WPiOS 11.0

User report [on Twitter](https://twitter.com/bicted/status/1059388899477340160)

Internal ref: p1541432363027600-slack-cellular-happiness

**Comment by wargcm** [comment]
This issue is mentioned in this app review: p1714368922461489-slack-C06AJCED8EN

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by twstokes** [comment]
We have undo functionality in the top toolbar on both iOS and iPadOS. Shake functionality is also enabled on both.

![Undo](https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/c04cc6d5-8dbc-4f24-b790-dbb095bd0236)
