### ISSUE TITLE
Reader: Ellipsis menu in Reader is non-functional on Jetpack posts

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10394]
### Expected behavior

I expect to be able to tap the ellipsis menu on any post in the Reader to bring up a contextual action sheet (e.g. to share the post, follow/unfollow the site).

### Actual behavior

The ellipsis menu is non-functional on posts from Jetpack sites. Tapping on the ellipsis menu only brings up an action sheet if the site is hosted on WordPress.com (Simple or Atomic).

### Steps to reproduce the behavior

1. Find a post from a WordPress.com site in the app Reader.
2. Tap the ellipsis menu on the post; note the action sheet that appears.
3. Find a post from a Jetpack site in the Reader.
4. Tap the ellipsis menu on the post; note that nothing happens.

The results are the same whether you tap the ellipsis on the Reader feed view or individual post detail view.

##### Tested on iOS XS, iOS 12.0.1, WPiOS 11.1.0.20181103 & 11.0

**Comment by daniloercoli** [comment]
Closing this issue since I cannot replicate it on the latest Jetpack version (24.2).
