### ISSUE TITLE
Privacy: Add explanation to Remove Location from Media feature

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#10407]
For more context see p77Llu-bgA-p2

The purpose of the Remove Location from Media feature might not be obvious.  Let's add some clarifying descriptive text to clarify that it removes location exif data from any  uploaded images.   Exact wording tbd.
![simulator screen shot - iphone 8 - 2018-11-06 at 11 45 15](https://user-images.githubusercontent.com/1435271/48083221-3ee28780-e1ba-11e8-9710-a4d84c272aff.png)

**Comment by ScoutHarris** [comment]
@aerych @iamthomasbishop - the App Settings page now looks like this (note the additions to the Privacy section). Unless anyone objects, I'll still just move `Remove Location From Media` to the bottom as @aerych suggested so we can add the new descriptive section footer.

![app_settings](https://user-images.githubusercontent.com/1816888/49603172-bdf8e600-f947-11e8-9536-ff2d35234c27.png)

**Comment by aerych** [comment]
Doh!  I must have had an old branch.  Thanks for clarifying the current state.
