### ISSUE TITLE
My Sites : Resolve visual defect after editing visible sites

### ISSUE THREAD

**Issue by ghost** [wordpress-mobile/WordPress-iOS#10422]
### Expected behavior
After editing the list of visible sites, committing the changes should properly reset the view.

### Actual behavior
After editing the list of visible sites, a large region of empty space is visible at the top of the screen. The space disappears after pull-to-refresh.

### Steps to reproduce the behavior

1. As a user with multiple sites associated with an account, navigate to _My Sites_ tab.
1. Tap _Edit_ and scroll the list.
1. No changes (i.e. switch-toggling) is necessary; just scroll.
1. Tap _Done_ and observe the empty space visible at the top of the table.

![mysites](https://user-images.githubusercontent.com/221062/48145672-3052a980-e268-11e8-9aa0-fdd6819ece73.png)

##### Tested on [device], iOS [version], WPiOS [version]
iPhone XS, iOS 12.1 (16B92), WPiOS v11.1

**Comment by joashrajin** [comment]
I've tested this behaviour out in JP Mobile 22.4 but cannot replicate the issue anymore. I am linked to over 30 sites in Jetpack. Please feel free to re-open this if you have any updated steps to replicate the issue. 

<img width="426" alt="Markup 2023-06-08 at 15 59 24" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/16253818/e2f4eeec-fbe5-43fe-ad1c-c691c846aa5c">
