### ISSUE TITLE
Media: Giphy search never returns results

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10424]
### Expected behavior

I expect to be able to search Giphy for GIFs to upload to my media library or post.

### Actual behavior

My Giphy searches always return no results with this message: `No media matching your search`

![2018-11-07 17 13 00](https://user-images.githubusercontent.com/8658164/48148405-8ac42800-e2b1-11e8-9088-7364d9252444.png)

### Steps to reproduce the behavior

1. Start a new post in the app.
2. Tap the "+" add media icon.
3. Tap the "..." menu and select Giphy as the media source.
4. Enter a keyword in the search box. Result: No matches

You can also repeat the search from a site's Media section, tapping the "+" icon and selecting Giphy as the media source. Same result.

**Comment by kwonye** [comment]
@loremattei is the giphy production key inside our app ok? I've verified it works fine on my WP Internal 11.2.

**Comment by kwonye** [comment]
Another crazy thought... Giphy isn't location-restricted is it? They work around the world?

**Comment by kwonye** [comment]
@rachelmcr verified with @loremattei that there was an errant build sent out without the correct Giphy key. The latest hockeyapp/testflight version has giphy working (which I've verified).
