### ISSUE TITLE
Media: Update the Giphy search prompt in editor for that context

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10425]
### Expected behavior

I expect the Giphy search prompt to be tailored to the context where I see it (either in my site's Media section or the editor).

### Actual behavior

In both places, the Giphy search prompt refers to my media library:

> Search to find GIFs to add to your Media Library!

When I'm adding GIFs directly to a post in the editor, that prompt feels a bit off.

<img src="https://user-images.githubusercontent.com/8658164/48148595-12aa3200-e2b2-11e8-9fa4-3d4fe0670967.png" width="200" alt="2018-11-07 17 12 52">

### Steps to reproduce the behavior

1. Start a new post in the app.
2. Tap the "+" add media icon.
3. Tap "..." and select Giphy as the media source.

**Comment by rachelmcr** [comment]
While we're at it, I noticed the same messaging for the Free Photo Library and would suggest a similar enhancement there.

**Comment by designsimply** [comment]
Closing because Giphy was removed in https://github.com/wordpress-mobile/WordPress-iOS/pull/14302. Props @ScoutHarris. 🎉

**Comment by designsimply** [comment]
Adding an additional note to say, discussed this in Slack and, even if you are adding an image from the Free GIF Library or the Free Photo Library it's true that it will add a copy of the image to the Media Library so the note is technically correct and might be worth mentioning to users that images added with those options will be available in the Media Library (and also take up space there).

That said, if you feel strongly, we can re-open this issue for a larger discussion!
