### ISSUE TITLE
Stats: Summary Data missing for a single day in-app

### ISSUE THREAD

**Issue by stevebaranski** [wordpress-mobile/WordPress-iOS#10421]
### Expected behavior
As a user, I should be able to see all of my stats for a given site. This data should be consistent across platforms.

### Actual behavior
For a Brazilian user noted in `p1541539436037700-slack-cellular-happiness`, she does not see here stats on November 4. These stats are visible on the web.

### Steps to reproduce the behavior
_This is a user-reported issue. We believe the locale is set to `pt-BR` right. It's noteworthy that this was observed after a daylight savings time transition._

##### Tested on [device], iOS [version], WPiOS [version]
iPhone, v11.0 ("up to date"), WP v11.0 ("up to date")

**Comment by stevebaranski** [comment]
I asked internally in `p1541622742023000-slack-portuguese-support`, and another use is experiencing the same issue. In this case, however, the user's device language is set to English.

iPhone settings for second user with this issue.
![10421a](https://user-images.githubusercontent.com/221062/48171062-17b9b200-e2af-11e8-8dbc-d6f367c64b3d.png)
![10421b](https://user-images.githubusercontent.com/221062/48171063-17b9b200-e2af-11e8-9fed-2925cbe443c1.png)

**Comment by stevebaranski** [comment]
I took some time to research the iOS implementation:

- `StatsViewController` uses `uses -[BlogService timeZoneForBlog:]`
- The value returned (e.g., `GMT` or `America/Los Angeles` is set on `WPStatsViewController` and injected into `WPStatsService`).
- `WPStatsService` is injected into `InsightsTableViewController`, where the service is invoked.
- The time zone value appears to be injected properly, but is never used in practice within `WPStatsServiceRemote`. 
- The uses of time zone appear to be either `[NSTimeZone localTimeZone]` or `[NSTimeZone timeZoneForSecondsFromGMT:0]`.
- This likely skews the parameters for `before`, `after` and `date` passed in requests.

cc: @ScoutHarris - for consideration while working on the _Full Stats Refresh_ project.

**Comment by stevebaranski** [comment]
Additional impact:
![10421c](https://user-images.githubusercontent.com/221062/48172099-5cdfe300-e2b3-11e8-8072-13832f848824.png)

**Comment by ScoutHarris** [comment]
Thanks for doing the research @stevebaranski ! We'll keep this in mind.

cc @jklausa

**Comment by jamiepalatnik** [comment]
Reported in #1545121-zen

**Comment by ScoutHarris** [comment]
Fixed with Stats Refresh.
