### ISSUE TITLE
Editor: Previous media selection from Giphy/Free Photo Library isn't cleared

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10439]
### Expected behavior

I expect that any time I add media from Giphy or the Free Photo Library I can select and add different media.

### Actual behavior

If I add media from Giphy or the Free Photo Library to a post, and then try to add more media without starting a new search, the selector gets stuck and I can only add the same media I added the first time.

### Steps to reproduce the behavior

1. Start a new post in the app.
2. Tap the "+" add media icon.
3. Tap the "..." ellipsis menu and select Free Photo Library.
4. Search for a keyword.
5. Select one image and add it to the post.
6. Tap the "..." ellipsis menu and select Free Photo Library again. Note that the previous search is still visible.
7. Select several images. Note that this time the selected images have a blue dot but no number, and the prompts at the bottom of the screen are stuck at "Preview 1" and "Add 1" no matter how many images are selected.
8. Select "Preview 1." Note that the preview shows the first image you added to the post.
9. Go back and select "Add 1." Note that the first image you added to the post is added again.

**Comment by rachelmcr** [comment]
I don't see the Free Photo Library as a media source in the editor, but it is an option when adding media directly to the site's media library (under My Sites > Media) and this issue is still visible there:

1. Open a site's media library under My Sites > Media.
2. Tap the "+" add media icon.
3. Select Free Photo Library.
4. Search for a keyword.
5. Select one image and add it to the media library.
6. Tap the "+" icon and select Free Photo Library again.
7. Select several images. Note that this time the selected images have a blue dot but no number, and the prompts at the bottom of the screen are stuck at "Preview 1" and "Add 1" no matter how many images are selected.

I also noticed another variation: If you do a search but don't don't select any images at step 5 (just close the media picker screen) then when you reopen it there's no bottom bar with "Preview" and "Add" buttons.

**Comment by guarani** [comment]
> Please comment with an update if you believe this issue is still valid or if it can be closed. 

I think this can be closed because I can only reproduce from within the classic editor, which is [now deprecated](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3209) and not receiving updates or regular bug fixes as I understand it. I **cannot reproduce** within the block editor or the site media screen.
Please feel free to re-open if you think this should stay open.
cc @mchowning
