### ISSUE TITLE
History / Revisions: Build revisions list UI

### ISSUE THREAD

**Issue by danielebogo** [wordpress-mobile/WordPress-iOS#10436]
Refs #10304

Build the revisions list UI:
- UITableView style (colours + header style)
- UITableViewCell (colours + cell style + operation views)
- UITableView footer

**Comment by jkmassel** [comment]
@danielebogo – given that this is in the "done" pile, can we close it? 😃

**Comment by jkmassel** [comment]
Closed in #10304
