### ISSUE TITLE
Quick Start: No scroll guide on iPad

### ISSUE THREAD

**Issue by naokomc** [wordpress-mobile/WordPress-iOS#10446]
Tapping an item of the Quick Start list doesn't show the mentioned control by automatically scrolling to the location.

### Steps to reproduce the behavior

1. Create a new site
2. Open the site using a horizontal layout on an iPad.
2. tap "Yes" on the Quick Start prompt.
3. Tap "View your Site", "Share your site", or "Follow other sites"

Video: 
https://cldup.com/e-XyDEF0Uv.mp4

**Comment by rachelmcr** [comment]
cc @nheagy

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
