### ISSUE TITLE
i18n: Long strings are partially hidden

### ISSUE THREAD

**Issue by naokomc** [wordpress-mobile/WordPress-iOS#10453]
On some screens, translated strings are cut off or truncated. Users will not understand what they supposed to mean in these cases.

1. Theme selection screen (e.g. French, Japanese)

![image](https://user-images.githubusercontent.com/34067/48388926-ad858f00-e73e-11e8-8380-21ad19a6f508.png)

The French translation is [here](https://translate.wordpress.org/projects/apps/ios/dev/fr/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5456660&filters%5Btranslation_id%5D=53213513).
Suggestion: Allow more lines for the space. The text could be shortened too.

e.g. "Get started fast with one of our popular themes. Once your site is created, you can browse and choose from hundreds more." -> "Get started fast with one of our popular themes. You can browse and choose from hundreds more later."

2. The screen to enter new WordPress.com site title & tagline (e.g. Russian, Japanese)

![image](https://user-images.githubusercontent.com/34067/48388786-fa1c9a80-e73d-11e8-94ba-774907323758.png)

Suggestion: shorten the orginal text so that the translation will also be shorter.

- "Site Title" -> "Title"
- "Site Tagline" -> "Tagline"
- "Optional tagline" -> "Optional"

2. "Type a keyword for more ideas" in the domain selection screen (e.g. French, Japanese)

![image](https://user-images.githubusercontent.com/34067/48388840-3ea83600-e73e-11e8-95c2-e7d0e23f1d0d.png)

Suggestion: either shorten the orignal text or provide Translator's Comment to limit the number of charcters

##### 1, 2, 3: Tested on iPhone, iOS 12.1, WPiOS 11.1

**Comment by stevebaranski** [comment]
This issue can be closed, as the issue was filed against the prior implementation (i.e., circa 2018) of Site Creation.
