### ISSUE TITLE
Scheduled posts not updated to published

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-iOS#10456]
### Expected behavior
When a scheduled post's date has passed and a post list is refreshed, the post's status should be updated to **Published**.

### Actual behavior
The post's status stays as **Scheduled** even after a REST API request. Only when a particular site is visited on the web (logged out or in Calypso), the scheduled publish is triggered. After this the post's status is correctly loaded as **Published** in the app, as well.

The gist of the problem seems to be that the RESP API call does not trigger a cron/scheduled publish job, only a web visit does.

### Steps to reproduce the behavior

1. Open the Blog posts screen
2. Create a post and schedule it in the future
3. Wait for the schedule date to pass
4. Refresh the post list in the app
5. Notice the post's status stays as **Scheduled**
6. Visit the site on the web
7. Notice the post's status is updated to **Published**
8. Refresh the post list in the app
9. Notice the post's status is now updated to **Published**, as well

**Comment by ovitrif** [comment]
I also saw this reproducing on [WordPress-Android](https://github.com/wordpress-mobile/WordPress-Android/) ;)

**Comment by antonis** [comment]
Searching on how the scheduled posts work I found the [following notice on the documentation](https://wordpress.com/support/schedule-a-post-or-page/):

> Scheduled posts will be triggered by the first visit to your blog on or after the exact date/time you set. If you see that the scheduled time has come and gone and your post or page has not published, log out of WordPress.com and view your blog’s front page. Your visit should cause the post or page to appear.

I believe that this indicates the the client app works as expected. A fix would require a change on how the server works and I'm closing this issue.
