### ISSUE TITLE
[Site creation] UI finalising and review

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10458]
Finalise the UI.

So far, the UI is barely more than an scaffold, built so that we can start plugin in actual integrations with the backend.

The scope of this story would be finalising the UI, taking it a state where it can be released

Table headers:
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/10479

SiteSegmentsWizardContent: 
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/10483

VerticalsWizardContent
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/10482

SiteInformationWizardContent
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/10481

WebAddressWizardContent
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/10480

**Comment by kwonye** [comment]
One thing we want to do as well is have a final PR with the Needs Design Review label on it 👌
