### ISSUE TITLE
Editor: Can't break out of Gutenberg quote block at end of post

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10465]
### Expected behavior

When a post ends with a blockquote, I should be able to break out of the quote to start a new paragraph.

### Actual behavior

If a Gutenberg posts ends with a blockquote, you can't start a new paragraph block after it.

In visual mode it looks like you're starting a new paragraph, but it's absorbed into the quote block:

```
<!-- wp:quote -->
<blockquote class="wp-block-quote">
  <p>This is a quote.</p>
</blockquote>
<p>More text.</p>
<!-- /wp:quote -->
```

And if the quote includes a citation, your new paragraph ends up in `cite` tags:

```
<!-- wp:quote -->
<blockquote class="wp-block-quote">
  <p>This is a quote.</p>
<cite>And a citation.</cite>
</blockquote>
<cite>More text.</cite><!-- /wp:quote -->
```

This issue can be easily resolved if you edit the post in Gutenberg (the "Resolve" button there correctly moves the paragraphs into paragraph blocks) but it can cause front-end formatting problems if no changes are made to the post after saving it in the app.

### Steps to reproduce the behavior

1. Create a new post in Gutenberg web.
2. Add a quote block (with or without a citation).
3. Save the post and open it in the app.
4. Try to start a new paragraph after the quote. (With the cursor at the end of the quote, hit Enter twice and then type new text.)
5. Switch to HTML mode and view the output.

##### Tested on iPhone XS, iOS 12.0.1, WPiOS 11.2.0.2018110701 & iPhone XS simulator, WPiOS develop branch

Original report: https://ios.forums.wordpress.org/topic/create-new-block-after-blockquote

cc @diegoreymendez

**Comment by guarani** [comment]
I tested this and can't reproduce so I think this has been fixed sometime after this was reported. 

When adding a paragraph to a post that ends in a quote, I got the expected HTML:
```
<!-- wp:quote -->
<blockquote class="wp-block-quote"><p>This is a quote.</p></blockquote>
<!-- /wp:quote -->
<!-- wp:paragraph -->
<p>Hello world!</p>
<!-- /wp:paragraph -->
```
I also tried with a quote that includes a citation and again got the expected HTML:
```
<!-- wp:quote -->
<blockquote class="wp-block-quote"><p>This is a quote.</p><cite>This is a citation.</cite></blockquote>
<!-- /wp:quote -->
<!-- wp:paragraph -->
<p>Hello world!</p>
<!-- /wp:paragraph -->
```

I'll close this, but feel free to re-open it if you think there's still an issue.
It looks like the thread on the original report in the iOS forums is closed, so it doesn't look like a follow up there is needed.
