### ISSUE TITLE
Notifications: Crash after receiving a repeat like notification

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#10476]
This is a bit of an edge case, but I think I've found a scenario where the app will crash opening after receiving a repeat like notification.  I can repeat it consistently. Here are the steps:

- Be logged into the app on a wpcom account. 
- Have the app on the notifications tab, then background the app.  This might be optional. 
- On a different wpcom account, like a comment from the original wpcom account. 
- Note that you get a push notification about the like.  Open the app and confirm.  No problem so far.
- Background the app again. 
- Now unlike the comment, then like it again. 
- Another like notification will be received.  Use it to open the app. 
- 💥 

The exception is:
```
2018-11-16 17:54:34:221 WordPress[320:23026] Running Notifications Background Fetch...
Assertion failed: Notification Timestamp should not be nil []: file /Users/Sandbox/xcode_ws/automattic/wpios/WordPress/Classes/Models/Notifications/Notification.swift, line 272
2018-11-16 17:55:10.897192-0600 WordPress[320:23026] Assertion failed: Notification Timestamp should not be nil []: file /Users/Sandbox/xcode_ws/automattic/wpios/WordPress/Classes/Models/Notifications/Notification.swift, line 272
```

<img width="1392" alt="screen shot 2018-11-16 at 5 54 58 pm" src="https://user-images.githubusercontent.com/1435271/48653166-e769c600-e9c8-11e8-9510-6d9452ba315f.png">

**Comment by designsimply** [comment]
@aerych are you still able to replicate this crash? We did ship a fix for a crash that was happening when tapping on certain notifications in https://github.com/wordpress-mobile/WordPress-iOS/pull/13158 but I am not sure if the certain notifications are the same certain notifications you were having trouble with. 🙂

**Comment by aerych** [comment]
Just tried and I was unable to reproduce the crash. :) Let's close it.
