### ISSUE TITLE
Code Cleanup: update EditorSettings for Swift 4

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#10474]
Here's a comment in `EditorSettings.swift` on [line 80](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Services/EditorSettings.swift#L80)

```swift
// We can't return a type that's both a PostEditor and a UIViewController, so using
// a configure block as a hack.
// In Swift 4, we'll be able to do `instantiateEditor() -> UIViewController & PostEditor`,
// and then let the caller configure the editor.
```

Well, we use Swift 4 now, it's time to do this! 🎉

**Comment by designsimply** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/10557. Props @diegoreymendez. 🎉
