### ISSUE TITLE
[Site creation] Style WebAddressWizardContent

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10480]
- [ ] Update styles of cells
- [ ] Scroll header up when textfield in focus

Edited on January 14th. 

The scope is reduced to applying style to the cells, according to the UI designs.

**Comment by stevebaranski** [comment]
@ctarda in reference to the second item above, @SylvesterWilmott noted something during [this PR review](https://github.com/wordpress-mobile/WordPress-iOS/pull/10784) that I wanted to raise here for visibility.

> I think I mentioned this in slack but just wanted to add it here as well in case it was missed. The title/subtitle hide/show behaviour should depend on if there is text in the text field and not whether the field is focused or not. So:
>
> IF there is 1 or more characters in the text field
> THEN hide title/subtitle

I hope this proves useful.

**Comment by stevebaranski** [comment]
@ctarda also, during review of [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/10786), @frosty noted the following that I believe will be addressed as part of the resolution of this issue:

> When I've performed a search and the software keyboard is visible, I can't scroll to the last item or so in the table of suggestions – they're hidden behind the keyboard.

Please advise if this **will not** be covered by this issue, and we can create a separate defect to resolve it.

**Comment by ctarda** [comment]
@stevebaranski Yes, I think we should have a separate issue for that.

**Comment by stevebaranski** [comment]
@ctarda okay - would you mind creating that, then? 

If this issue doesn't cover that case, then as @kwonye noted above, it's not exactly clear what this issue does cover.

**Comment by ctarda** [comment]
I updated the story description with the scope as of today
