### ISSUE TITLE
History / Revision: History button won't show up when a post is restored

### ISSUE THREAD

**Issue by danielebogo** [wordpress-mobile/WordPress-iOS#10522]
If I create a draft -> save several revisions -> trash the draft -> restore, I don’t see History initially under the menu. However, when I save the draft again, I see History plus all my previous revisions. So, the revisions are still there, but I initially don’t see them when I restore a post from trash.

**Comment by jkmassel** [comment]
@danielebogo – is this resolved by #10523?

If so, we can close it! 🎉

**Comment by jkmassel** [comment]
Resolved by #10523 – closing.
