### ISSUE TITLE
News Card: Update news item linked in news card to latest en.blog post

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10525]
### Expected behavior

I expect the Reader news card to promote the latest en.blog post relevant to the iOS app, e.g. this one: https://en.blog.wordpress.com/2018/11/20/improving-mobile-site-setup-with-quick-start/

### Actual behavior

The news card still links to this post from March: https://en.blog.wordpress.com/2018/03/28/new-and-improved-ios-sharing-extensions/

We should probably come up with a process to regularly update this news card (either automated or part of the process when a news post is published), but for now it would be great to at least manually update it to a more recent post.

##### Tested on iPhone XS, iOS 12.1, WPiOS 11.3.0.20181119

cc @ctarda

**Comment by ctarda** [comment]
@rachelmcr I'm looking into scripting this, it'll be a fun little project for me. Thanks for pointing it out!

**Comment by designsimply** [comment]
I checked the Reader after a fresh install of the app and found a Reader news card pointing to [a post dated 2019-07-16 about stats](https://en.blog.wordpress.com/2019/07/16/more-stats-better-stats-faster-stats-a-whole-new-mobile-experience/).

<img src="https://user-images.githubusercontent.com/1119271/70759929-3afe2e80-1d05-11ea-964c-3f68b2697b54.PNG" width="270" alt="IMG_3206">
<sup>Tested with WPiOS 13.8.0.0 TestFlight beta on iPhone 6S iOS 13.2.3.</sup>

**Comment by ScoutHarris** [comment]
I believe @yaelirub is going to update it for Offline Support.

**Comment by yaelirub** [comment]
Thanks @designsimply , @ScoutHarris . I'm going to work with editorial to update the News card once we publish the en.blog post on offline support.
