### ISSUE TITLE
Domain Registration: Visual layout issues on domain search & registration screens

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10531]
When I switch to landscape mode on the domain search screen and the screen to enter my registration details, there are some layout issues:

1. Not all fields span the full width of the screen.

![image](https://user-images.githubusercontent.com/8658164/48937943-98132080-ef07-11e8-80bb-1c30da0a7dc0.png)

2. The text under the domain privacy selection is too far left (it is overlapped by the iPhone tab).

![image](https://user-images.githubusercontent.com/8658164/48937931-8e89b880-ef07-11e8-815f-682155ac12af.png)

3. The Register Domain button only spans half the screen.

![registerdomainbuttonwidth](https://user-images.githubusercontent.com/8658164/48937979-be38c080-ef07-11e8-9c62-58a1c65c49fd.png)

**Comment by jklausa** [comment]
This was fixed in #10503, closing :)
