### ISSUE TITLE
Domain Registration: Labels & placeholders cut off on smaller screens

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10534]
As reported by @thehenrybyrd for the domain registration flow on a business site:

Because I’m on a smaller screen (iPhone SE), a few things are cut off or on multiple lines:
“Register Privately with Privacy Pro…”

![image](https://user-images.githubusercontent.com/8658164/48938692-dc072500-ef09-11e8-8a43-ab993efe5e72.png)

“Organization”

![registerdomainsmallscreen](https://user-images.githubusercontent.com/8658164/48938749-0658e280-ef0a-11e8-86d3-ac43b1d6ed1b.png)

**Comment by jklausa** [comment]
This was fixed in #10503, closing :)
