### ISSUE TITLE
Domain Registration: Validation errors = endless spinner

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10532]
While registering a new domain, I triggered a validation error by entering unacceptable characters in the postal code field. However, a spinner then appeared that I could not dismiss without navigating away from the screen and back again. This spinner appears with any validation error in the registration form.

I was able to type in the field even while the spinner was on the screen, but I still couldn’t do anything else (e.g. fix the validation error and then try to register the domain again).

![registerdomainspinner](https://user-images.githubusercontent.com/8658164/48938236-82522b00-ef08-11e8-8e49-ab839be4de9e.png)

**Comment by rachelmcr** [comment]
Testing feedback from @thehenrybyrd:

> When triggering a validation error, I get a persistent spinner, and can type and navigate, but can’t fix the validation error, and the “register domain” button doesn’t re-load.

> In addition, after clicking “register domain” (with correct information), I got that same persistent spinner, and was able to navigate and type while registration was ongoing.

**Comment by jklausa** [comment]
This was fixed in #10503, closing :)
