### ISSUE TITLE
Domain Search: Return exact match at top of search results

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10530]
If there’s an exact match for the domain I entered, I’d expect it to be at the top of the list. I almost missed that there was an exact match in the search results:

![image](https://user-images.githubusercontent.com/8658164/48937820-3357c600-ef07-11e8-84c3-4276436c609a.png)

**Comment by designsimply** [comment]
Tested and confirmed using WP Internal 11.9.0.20190226 on iPad Mini 4 (WiFi) (iPad5,1) iOS 12.1.4. I also found it difficult to find the exact match for the domains I search for during site creation.

**Comment by designsimply** [comment]
Tested and confirmed this still happens in WP Internal 12.0.0.20190311 on iPhone 6S iOS 12.1.4.

**Comment by elibud** [comment]
Closing since @frosty fixed it in https://github.com/wordpress-mobile/WordPress-iOS/pull/11290
