### ISSUE TITLE
Enormous images while viewing Gutenberg-created post gallery

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-iOS#10541]
I created a post in Gutenberg that has some galleries in it:

https://roundhill.blog/2018/11/22/restoring-a-donkey-kong-arcade-cocktail-table/

When viewing the post in the iOS reader, the images aren't displaying properly:

![img_8481](https://user-images.githubusercontent.com/789137/48954788-d3115600-eeff-11e8-8d6e-62a32f74e148.PNG)

It looks like Gutenberg uses an unordered list for galleries.. you can see the bullet point rendered in the screenshot ^

**To Reproduce**
1. Create a Gutenberg post.
2. Drag two or more images into the post to create a gallery.
3. Publish the post and view it in the iOS reader.
4. Observe giant images!

**Comment by rachelmcr** [comment]
Thanks for the report!

Related issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/10206

This is resolved by https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/165 in 11.3 (currently in beta).
