### ISSUE TITLE
Gutenberg - mobile Editor opt-in for Alpha

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-iOS#10554]
Comes from https://github.com/wordpress-mobile/gutenberg-mobile/issues/222#issuecomment-442074545

> We'll have a simple switch on Me > Settings that replaces what the -gutenberg command line argument does now. This setting (and Gutenberg) should only be visible on debug and internal builds. Below, it should have some explanation that this is an experimental feature.

As discussed elsewhere with @koke  and @elibud, this manual switch is a need for showcasing the feature and giving the user full control (at their own risk)  just for internal testing (alpha).

ToDo:
- [ ] show new (persistent) switch in Me > Settings
- [ ] the switch should only be visible on debug and internal builds (alpha)
- [ ] below, show an explanation that this is an experimental feature.
```
*EXPERIMENTAL*
💣 This is still an experimental version of Gutenberg 🙈
```

~- [ ] add Tracking~
- [ ] if the setting is enabled:
- launch Gutenberg when it's a Gutenberg Post
- launch Aztec for existing non-Gutenberg Posts
- launch Gutenberg for new posts
- [ ] if the setting is disabled:
- launch the editor of their choice according to existing settings

**Comment by mzorz** [comment]
Android counterpart: https://github.com/wordpress-mobile/WordPress-Android/issues/8684

**Comment by mzorz** [comment]
Updated description of issue as we don't need tracking, reflecting  https://github.com/wordpress-mobile/WordPress-Android/issues/8684#issuecomment-442107473

**Comment by diegoreymendez** [comment]
Reopening since there's some more work to do.

**Comment by diegoreymendez** [comment]
On top of what's mentioned here we added an option to be able to switch between Aztec and Gutenberg following this logic:

- If Gutenberg is enabled:
  - When in Aztec:
    - Show the option to switch to Gutenberg only if the post has blocks or is empty.
  - When in Gutenberg:
    - Show the option to switch to Aztec for all posts.
- If Gutenberg is not enabled:
  - Don't show the option
