### ISSUE TITLE
[News card] Content is not localised

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10618]
### Expected behavior
The content of the news card should be localised
![img_2925](https://user-images.githubusercontent.com/2722505/49629362-2917ea80-fa24-11e8-9fa9-0bd9ef722ff9.PNG)

### Actual behavior
The content is not localised. The "Read more" button is.

### Steps to reproduce the behavior
Navigate to Reader. Check the News Card, if available

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 6s, iOS 12.1, WPiOS 11.4

**Comment by ScoutHarris** [comment]
The News Card has been removed.
