### ISSUE TITLE
[Reader > Discover] Title is not localised

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10619]
### Expected behavior
The title of the Discover section of Reader should be localised

<img src="https://user-images.githubusercontent.com/2722505/49629603-37b2d180-fa25-11e8-9047-bcb7b530c98f.jpeg" width="270" alt="img_c12c737cffb8-1">

### Actual behavior
The title of the Discover section of Reader is in English

### Steps to reproduce the behaviour
on a device setup to a language other than English, navigate to Reader > Discover. Notice the title

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 6s+, iOS 12.1, WPiOS 11.4

**Comment by designsimply** [comment]
Still valid.

<img src="https://user-images.githubusercontent.com/1119271/70758293-c248a380-1cff-11ea-9982-51b72958688b.PNG" width="270" alt="IMG_3203">
<sup>Tested with WPiOS 13.8.0.0 TestFlight beta on iPhone 6S iOS 13.2.3.</sup>

**Comment by designsimply** [comment]
Note: if https://github.com/wordpress-mobile/WordPress-iOS/issues/10620 goes through (removing Discover for non-English locales) then I think it would invalidate this issue.

**Comment by ScoutHarris** [comment]
The Reader has been refactored, and `Discover` is now translated.

| ![discover_english](https://user-images.githubusercontent.com/1816888/98180891-55ae3880-1ebf-11eb-8156-fb6ebb2c264f.jpg) | ![discover_spanish](https://user-images.githubusercontent.com/1816888/98180906-5c3cb000-1ebf-11eb-9430-1671ce676f23.jpg) |
|--------|-------|
