### ISSUE TITLE
[Reader > Discover] Header (description) is not localised

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10620]
### Expected behavior
The description of the content presented in the Discover section is not localised

<img src="https://user-images.githubusercontent.com/2722505/49629667-95471e00-fa25-11e8-90e2-64a440a7ef61.jpeg" width="270" alt="img_c12c737cffb8-1">

### Actual behavior
The text describing what this section is about should be localised

### Steps to reproduce the behavior
On a device setup to a language other than English, navigate to Reader > Discover

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 6s+, iOS 12.1, WPiOS 11.4

**Comment by rachelmcr** [comment]
Regarding this and https://github.com/wordpress-mobile/WordPress-iOS/issues/10619, these are the title and tagline of the [Discover blog](https://discover.wordpress.com/), so I wouldn't expect them to be localized.

However, Calypso web hides the Discover section in the Reader for non-English account languages, since Discover is only published in English. We could do something similar in the app.

**Comment by ctarda** [comment]
@rachelmcr Thanks for your comment. I was about to implement the suggested solution (hiding Discover for non-english locales) but I am a bit concerned about removing something from the app that has been there for a long time and some users might expect to continue being there. 

So, just to double check, should I go ahead and remove Discover for non-english locales?

**Comment by rachelmcr** [comment]
Removing Discover for non-English locales would match web behavior, but I wasn't a part of implementing it in the app Reader and I'm not sure if there were explicit decisions to have it in the app for all locales, or what the design perspective is on this. Paging @aerych @iamthomasbishop for input on that!

**Comment by iamthomasbishop** [comment]
I agree w/ @rachelmcr – I wouldn't expect a site tagline to be translated, as it is a "user-generated" thing, and also agree that maybe we should remove it (in non-English scenarios) as Calypso does.

**Comment by aerych** [comment]
I've no objections, but please check with Editorial and get their blessing first as Discover is content they "own".

**Comment by michelleweber** [comment]
No reason no to match the web behavior, go ahead and remove.

**Comment by ctarda** [comment]
For completeness, here is the p2 discussion: p2JRYi-3Ss-p2

**Comment by ScoutHarris** [comment]
Hey @ctarda . It looks like this was resolved with the Reader refactor. Discover now looks like this:

| ![discover_english](https://user-images.githubusercontent.com/1816888/98180891-55ae3880-1ebf-11eb-8156-fb6ebb2c264f.jpg) | ![discover_spanish](https://user-images.githubusercontent.com/1816888/98180906-5c3cb000-1ebf-11eb-9430-1671ce676f23.jpg) |
|--------|-------|

If you disagree, feel free to reopen.
