### ISSUE TITLE
History / Revisions: Revisions list footer not translated in Italian

### ISSUE THREAD

**Issue by danielebogo** [wordpress-mobile/WordPress-iOS#10621]
![revisions-footer](https://user-images.githubusercontent.com/912252/49644877-cfa6c000-fa11-11e8-99ff-5340f83ee78b.jpg)

### Actual behavior
The footer title _Post created on_ is still in English when the selected language is Italian.

### Steps to reproduce the behavior
- On the device select Italian as language
- Select a post, open a revisions list and scroll to the bottom of the list

**Comment by rachelmcr** [comment]
I checked today and [this Italian string](https://translate.wordpress.org/projects/apps/ios/dev/it/default?filters%5Bterm%5D=post+created+on&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) is now appearing on this screen (tested in WPiOS 11.4 internal with device language set to Italian). Closing as resolved.
