### ISSUE TITLE
Update README to be more clear

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#10624]
We want to update the README to be more easily understood.

**Comment by kwonye** [comment]
Add @jkmassel as a reviewer

**Comment by apeatling** [comment]
```rake dependencies``` installs all the dependencies from cocoapods, so there's no need to include the ```pod install``` step.

**Comment by apeatling** [comment]
There's no step to handle the scary red signing/provisioning profile errors you see when opening Xcode for the first time. I think this is only needed for an actual device though, but still important to mention it.

![Uploading Screen Shot 2018-12-09 at 10.51.48 AM.png…]()

**Comment by kwonye** [comment]
Good point, let me look into if we can fix this. You should be able to build to a simulator without it however.

**Comment by apeatling** [comment]
It would be good to make the instructions short and a bulleted/numbered list. It'll be easier to follow each step.

**Comment by apeatling** [comment]
Also, setup credentials section is easy to miss. Once I built the app and it ran in the simulator, I would have missed that part unless @kwonye told me about it.

**Comment by jblz** [comment]
Is it worth mentioning that development happens in the `develop` branch? Some might find it confusing it's not in `master`.

**Comment by apeatling** [comment]
"Then edit the ~/.wpcom_app_credentials file and change the WPCOM_APP_ID and WPCOM_APP_SECRET fields to the values you got for your app."

It's not clear hat "values you got for your app" means.

**Comment by kwonye** [comment]
Specify you need to create a new client AND a developer account vs just an account.

**Comment by jblz** [comment]
Is `rake` installed by default on MacOS or should we add a step to install it?

**Comment by apeatling** [comment]
> Then edit the ~/.wpcom_app_credentials

this is not pointing to the right file based on previous steps.

**Comment by tcn33** [comment]
Suggested revision:

### Third party tools
We use a few tools to help with development. To install or update the required dependencies, run the follow commands on the command line:

```
gem install bundler
bundle install
rake dependencies
```

**Comment by apeatling** [comment]
There's a mismatch in terminology. Client ID vs WPCOM_APP_ID and Client Secret vs WPCOM_APP_SECRET. It would be good to be clear about the exact mapping.

**Comment by apeatling** [comment]
You need to clean the build folder in order for the credentials to take.

**Comment by kwonye** [comment]
Make more 
explicit that you should use the same email as the developer account

**Comment by kwonye** [comment]
Make clear that you can't create an account in the app without the production client_id and app_secret

**Comment by tcn33** [comment]
> `rake dependencies` installs all the dependencies from cocoapods, so there's no need to include the `pod install` step.

Is it possible to add `rake git:install_hooks` and `rake lint` or `rake lint:autocorrect` into `rake dependencies` as well?

**Comment by tcn33** [comment]
Warn that `pod install` might take a while. Like, quite a while.

**Comment by kwonye** [comment]
From @apeatling: keep first issues up to date.

**Comment by tcn33** [comment]
Warn that xcode is a dependency for `pod install` in case people try to leap ahead.

**Comment by kwonye** [comment]
@apeatling ran into an issue with cocoapods-repo-update where he didn't have it installed initially. Maybe the `rake dependencies` install script isn't installing it right?

**Comment by tcn33** [comment]
> > Then edit the ~/.wpcom_app_credentials
> 
> this is not pointing to the right file based on previous steps.

Should be ~/.mobile-secrets/iOS/WPiOS/wpcom_app_credentials.

**Comment by tcn33** [comment]
>Then you can compile and run the app on a device or an emulator and log in with a WordPress.com account. 

This is a little bit "then draw the rest of the owl". Needs more steps.

**Comment by jblz** [comment]
There's an asterisk (`*`) at the end of the [top / XCode section](https://github.com/wordpress-mobile/WordPress-iOS/blob/61be546e6d47a29b13438e4e3cd65071ea0b2587/README.md#download-xcode) that currently says:

> At the moment WordPress for iOS uses Swift 4.2 and requires Xcode 10 or newer. Previous versions of Xcode can be downloaded from Apple.*

I would expect that there would be some additional context in a footnote or something, but that doesn't seem to be the case.

**Comment by apeatling** [comment]
@designsimply Did all of these issues get addressed? There's a lot of simple readme updates here that would significantly help external contributors to the apps (or increase the number of them from near zero).

**Comment by kwonye** [comment]
@apeatling I say close it 😉 Going through it, it looks pretty damn good.

Hope y'all are doing well!
