### ISSUE TITLE
Apparently the app can't connect to non standard port numbers

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#1063]
Got this report from a user

>I used to love the iPhone version of this app, but I can't log in on my iPad because it apparently doesn't support non-standard port numbers. I run my site on a different port, which is appended to the URL (ie: moosefuel.org:8888). It would be nice if I could connect.

**Comment by koke** [comment]
It actually works, but you have to type the full URL in the login screen:
- `http://example.com:8888` works
- `example.com:8888` detects `example.com` as the protocol and `8888` as the path.

We could improve the URL detection algorithm a bit, but given this is such a rare case, and there's an easy workaround, I lean towards wontfix.
