### ISSUE TITLE
Post Settings: Adjust layout on iPad for larger screen size

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10664]
@m pointed out that the layout and interactions in post settings seem more optimized for a phone/small screen. We should review the post settings to see how the iPad experience could be improved, e.g. with columns or a "card" style.

Example from editing the publicize message:

![image from ios 5](https://user-images.githubusercontent.com/8658164/50021264-6d7d2a80-ffd0-11e8-821f-0a2e942b5833.png)

Note that the screenshot does not show the cursor, which is not aligned all the way to the left on iPad.

cc @iamthomasbishop

**Comment by iamthomasbishop** [comment]
Definitely agreed here. I think we might want to do a full sweep of the app in terms of readability/container widths during the upcoming Hack Week in January. IIRC, container widths is something @SylvesterWilmott has been working on formalizing. Any thoughts, Sylvester?

**Comment by nheagy** [comment]
I thought I'd add another screenshot to illustrate how awkward some screens are: 
![image](https://user-images.githubusercontent.com/517257/50120940-16639980-020c-11e9-9924-82ba0105a88f.png)

**Comment by SylvesterWilmott** [comment]
@nheagy @iamthomasbishop This is something I've been working on and some hard containers have been added to some recent projects. I think, as you said Thomas we can tackle this in one go. I feel like it would be smoother to have one engineer per platform work on a project like this to clean up all of our tablet layouts.
