### ISSUE TITLE
Share Extension: Sharing Spotify URL resulted as active link instead of embedded content

### ISSUE THREAD

**Issue by retnonindya** [wordpress-mobile/WordPress-iOS#10738]
### Expected behavior
1. Play music on Spotify.
2. Click 'Share' from Spotify app.
3. Choose 'WordPress for iOS' app.
4. Spotify URL appeared.
5. Click 'Publish'.
6. The Spotify player is embedded and active (able to play the song/music) in the website/blog.

### Actual behavior
The link turned as active link and didn't published as embedded player. 

This is on the editor window:

![active link](https://cldup.com/JuC09R1679.PNG)

After published; on home page. Somehow the link is not active/not clickable; but it's still in link form/not as embedded content:

![home page](https://cldup.com/CNzAKpVesO.jpg)

This is on single post page (after I clicked the blog title). The link is active:

![single post](https://cldup.com/BYyD7VmL8h.jpg)

I tried to remove the link -- as I initially thought the non-active link might work and display the player, but it didn't appear as embedded player either. Removing the link will remove the "https://"-part too, so I guess it's the reason why (?)

![remove link](https://cldup.com/XPv2d39nBT.PNG)

### Steps to reproduce the behavior
1. Open Spotify app.
2. Choose/play song.
3. Click the three dots (. . .) to open Options.
4. Click 'Share'.
5. Click 'More'.
6. Choose 'WordPress' extension.
7. Editor window popped up with Spotify URL.
8. Click 'Next'.
9. Choose post category and tags; choose blog for the post to publish (if there are more than one blogs listed).
10. Click 'Publish'.

I have my workaround, though. I usually choose 'Copy Link' on Spotify (Share > Copy Link), open WordPress for iOS app, and pasted the Spotify URL there.

**Comment by rachelmcr** [comment]
Thanks for the report! I'm going to combine this with https://github.com/wordpress-mobile/WordPress-iOS/issues/10694 as I think we'll need to audit the share extension behavior to see if there's a solution for sharing embedded content (e.g. YouTube, Spotify) versus text/link content.
