### ISSUE TITLE
Share Extension: Images are not uploaded at full size, EXIF data lost

### ISSUE THREAD

**Issue by codebykat** [wordpress-mobile/WordPress-iOS#10736]
### Expected behavior

When I have the WP app set to upload images at full size and create a post using "Save as Draft", the image should not be resized to a smaller size.

### Actual behavior

Images are resized to a width of 3000px and all EXIF data is deleted.

### Steps to reproduce the behavior

1. In the WP app, choose to upload images at "original" size:

![screen shot 2019-01-02 at 3 58 23 pm](https://user-images.githubusercontent.com/52152/50618389-41561a80-0ea7-11e9-88d7-0cb52181b16f.png)

1. Choose a large image from the Camera Roll
![img_2659](https://user-images.githubusercontent.com/52152/50618368-1d92d480-0ea7-11e9-8b3a-3f9d00efaf6a.jpg)

2. Share -> Save as Draft

3. Inspect the uploaded image in the media library and note that it has been reduced to 3000px wide.

4. Download it to inspect the EXIF and note that all EXIF data is now gone.

##### Tested on [device], iOS [version], WPiOS [version]

iOS 12.1.1, WPiOS 11.5 (internal beta)

**Comment by nheagy** [comment]
We should retest this issue. I now have misgivings that it has been fixed.

**Comment by sla8c** [comment]
I've re-tested and this looks resolved in WPiOS v19.0

Steps:
1.  Original size setting chosen and Share -> Save as draft
2. The original image size = 4032 x 3024 (s/shot from Photos on iPhone).  Wordpress.com shows the same size
 
![image](https://user-images.githubusercontent.com/88816724/151121349-3b4c14c4-ebfc-4412-ab32-306c58532aae.png)

![image](https://user-images.githubusercontent.com/88816724/151121240-dd8ccb9d-7aa5-4537-9528-445abc42a545.png)

3. downloaded image from Wordpress.com media onto desktop + checked EXIF and it looks good
![image](https://user-images.githubusercontent.com/88816724/151121552-cf613d70-40f0-4915-897f-d946d7c29347.png)
