### ISSUE TITLE
Feature request: Passslock code and Touch ID

### ISSUE THREAD

**Issue by gpfister** [wordpress-mobile/WordPress-iOS#10741]
### Expected behavior

Allow user to set a passcode to access the app content, and use Touch ID if they want. This is an additional security layer to prevent somebody from posting potentially liable content if he/she gains access to the device.

**Comment by rachelmcr** [comment]
Thanks for the suggestion! We have some past discussion in https://github.com/wordpress-mobile/WordPress-iOS/issues/65. I'm going to close this issue and make a note on that issue, which we'll reopen if we add this to the roadmap.
