### ISSUE TITLE
Editor: "Done" and "Remove" buttons seem flipped in Add Location UI

### ISSUE THREAD

**Issue by codebykat** [wordpress-mobile/WordPress-iOS#10767]
### Expected behavior

Okay so I was thinking this feels weird because everything else in the app has "proceed/confirm" on the right and "go back/cancel" on the left. But I do see that all the tap-in menus (like the date) use the top left to close them again and return to Post Settings.

Also! The button to add featured image actually has "Done" on the left and "Remove" on the right as well, which still seems weird, BUT one big difference is that here, when you select an image, it automatically closes out of that menu ("Done" is assumed).

Anyway maybe this is a won't-fix, but I keep wanting to tap the right side to save the location I just searched for, and it feels "off". To me.

### Actual behavior

When you add a location to a post, you have to click "Done" on the left (the right-hand option is "Remove").

![img_2702](https://user-images.githubusercontent.com/52152/50812869-3ea15e00-12c9-11e9-950b-1c65e2be41bb.PNG)

### Steps to reproduce the behavior

1. Create a new post in the app
2. Tap the ellipsis and open Post Settings
3. Tap on "Set location"
4. Note that the "Done" button is at the top left and the "Remove" button is at the top right.

##### Tested on [device], iOS [version], WPiOS [version]

iOS 12.1.2, WPiOS 11.5.2019010200 [beta]

**Comment by stevebaranski** [comment]
@codebykat this issue was addressed by an external contributor, and is slated for inclusion in the v12.0 release. Thank you @blewjy!
