### ISSUE TITLE
[Site Creation] Reset hidden headers (title & prompt) when navigating to/from a wizard step

### ISSUE THREAD

**Issue by stevebaranski** [wordpress-mobile/WordPress-iOS#10791]
@frosty noted the following during [this PR review](https://github.com/wordpress-mobile/WordPress-iOS/pull/10784)

> There's no way to ever seen the original title or prompt after I've selected the search field. Even if I go back to the previous step, or forward to the next and then back again, the text field remains focussed and the title / prompt hidden. I wonder if we should reset this at any point (It's possible a user might forget what they were searching for?).

Related issues: #10485, #10494 & #10688

**Comment by jkmassel** [comment]
Hey @stevebaranski – I see several PRs merged that reference this issue (notably #10820). Is this issue resolved, or should we bump it to `11.8`? 🙂

**Comment by stevebaranski** [comment]
Yes @jkmassel - this should be closed, but it doesn't look like the automation picked it up. I'll make a pass through others on this project board.
