### ISSUE TITLE
Invite people: message field doesn't show entire message

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#10795]
### Expected behavior
After entering an invitation message, I expect the full message to display on the `Add a Person` view.

### Actual behavior
After entering an invitation message, the message field does not display then full message.

### Steps to reproduce the behavior
- Go to Site > People
- Select `+` on the nav bar.
- Select the custom message field.
- Enter a message that is more than 2 lines.
- Go back to `Add a Person`.
- Notice the partial message in the custom message field.

Full message:
<img width="300" alt="message" src="https://user-images.githubusercontent.com/1816888/50999648-fad86f80-14e7-11e9-9345-b1fb6a7491cc.png">

Displayed message:
<img width="300" alt="displayed_message" src="https://user-images.githubusercontent.com/1816888/50999653-0035ba00-14e8-11e9-8954-98119df678cc.png">

**Comment by marosios** [comment]
Hey! Is this issue still available? I'd like to fix it. Thanks.
