### ISSUE TITLE
[Site creation] Keyboard covering last row of results in tables with search textfield

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10811]
Noticed in the review of PR #10786.

**Comment by stevebaranski** [comment]
This appears to impact the _Domains_ selection screen, not _Verticals_.

**Comment by stevebaranski** [comment]
This was noted in #10786 because the keyboard handling had not yet been implemented as prescribed in #10822. Preliminary keyboard changes for _Domains_ have been proposed via #10822.

**Comment by stevebaranski** [comment]
Removed assigned and moved back to **Raw Backlog**, pending resolution of both #10821 & #10822.
