### ISSUE TITLE
Verify and modify behaviour of hiding title / subtitle

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#10812]
As discussed during this PR review: #10784 the header should be hidden when there is text in the textfield.

https://github.com/wordpress-mobile/WordPress-iOS/pull/10784#issuecomment-453147111

> I think I mentioned this in slack but just wanted to add it here as well in case it was missed. The title/subtitle hide/show behaviour should depend on if there is text in the text field and not whether the field is focused or not. So:
> 
> IF there is 1 or more characters in the text field
> THEN hide title/subtitle
> 
> So the view will be reset if the field is cleared or all characters are backspaced. This is also true for the domains step.

**Comment by jkmassel** [comment]
@stevebaranski  / @ctarda – it appears a PR (#10822) was merged against this issue – can it be closed?

If not, we'll bump it to `11.8` 🙂

**Comment by stevebaranski** [comment]
This can be closed - thanks.
