### ISSUE TITLE
Reader: Enable Users to Navigate Posts in Their Reader by Swiping Left or Right

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#10836]
### Expected behavior

If you navigate to the Reader and tap on a post to view it in full, I expect for there to be an easy way to view other posts in the Reader's stream. Within the Android app, you can swipe left or right to view older or newer posts in your stream. 

### Actual behavior

It's not possible to navigate to other posts in the stream by swiping left or right. Instead, you need to manually tap the back button to view the full list of posts in your stream again, then tap on the one you want to read. The Android app offers a much nicer experience here and it'd be nice to see it in the iOS app.

This was requested in 1716932-zen.

### Steps to reproduce the behavior

1. Navigate to the Reader section of the app.
2. Tap on a post in your stream of followed sites to view it in full.
3. Swipe left or right to view another post in the stream. At the moment, this has no effect.

**Comment by rachelmcr** [comment]
Note that currently if you are viewing the post detail view and you swipe right, the expected behavior is to go back to the list (stream) view, so enabling left/right swipe to navigate between post detail views would change this behavior.
