### ISSUE TITLE
Reader: Navbar is lost after scrolling on short post

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10835]
### Expected behavior

I expect that if I scroll quickly through a post detail view in the Reader, the navbar will temporarily disappear but will reappear when I start scrolling up again.

### Actual behavior

On some posts, when I scroll quickly down a post detail view, the navbar disappears and doesn't come back. I noticed this on posts exhibiting the issue in https://github.com/wordpress-mobile/WordPress-iOS/issues/10834 and haven't been able to intentionally reproduce it anywhere else, so the two issues might be connected.

The only way to get the navbar back is to tap Reader in the main (bottom) navigation bar, which loses your place in the Reader feed you were viewing.

Screencast here: https://cloudup.com/c_JsGFKc9Ee

### Steps to reproduce the behavior

1. Open the Reader in the app.
2. Find a post exhibiting the issue described in https://github.com/wordpress-mobile/WordPress-iOS/issues/10834 (e.g. [this post](https://rachel-test-domain.com/2019/01/16/photo-post-do-a-little-test/)).
3. Swipe up to scroll quickly down in the post.
4. When the navbar disappears, try to swipe up or down to make it reappear.

**Comment by rachelmcr** [comment]
I confirmed I can still trigger this on certain posts, e.g. the one in the screencast above: https://demet.blog/2019/01/16/how-communication-density-fuels-automattic-data-for-breakfast/

**Comment by leandroalonso** [comment]
The nav bar is not hidden anymore.
