### ISSUE TITLE
News card doesn't play well with bigger fonts and thin screens

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/WordPress-iOS#10843]
### Expected behavior
The UI should adapt to bigger font sizes.

### Actual behavior

![simulator screen shot - iphone 5s - 2019-01-11 at 10 31 02](https://user-images.githubusercontent.com/9772967/51307153-46869e00-1a3f-11e9-8ae3-1b5a9b899a66.png)

Go to:
- iOS Settings
- General
- Accessibility
- Larger Text
- Switch On the `Larger Accessibility Sizes`
- Select a big font size
- Go back to the app, and display the News card from the reader (you might need to re-install the app)

**Comment by ScoutHarris** [comment]
The News Card has been removed.
