### ISSUE TITLE
Extra space around images in comments

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#10848]
### Expected behavior
There shouldn't be any extra space around images in comments.

### Actual behavior
There's extra white space on the top and bottom of the image.
![img_0745](https://user-images.githubusercontent.com/5558824/51331342-4b0b8080-1a58-11e9-9011-6b729b29b6a3.PNG)

### Steps to reproduce the behavior
Notifications-> Load a Post-> Tap on the comments bubble
and possibly also in Reader-> Tap on the comments bubble

##### Tested on iPhone XS, iOS 12, WPiOS 11.5

**Comment by rachelmcr** [comment]
This looks suspiciously similar to the extra space around images in the Reader post detail reported in https://github.com/wordpress-mobile/WordPress-iOS/issues/10834.

**Comment by jkmassel** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/10878
