### ISSUE TITLE
SFHFKeychainUtils issues about -25308 error is also exists after update your great code

### ISSUE THREAD

**Issue by zhoufusong** [wordpress-mobile/WordPress-iOS#10856]
can anyone help me?  my project  also report -25308 error and it is errSecInteractionNotAllowed  keychain problem. but I have update your code in my project.

**Comment by rachelmcr** [comment]
cc @astralbodies @koke Is this something we can help with?

**Comment by astralbodies** [comment]
@zhoufusong Are you seeing this in a simulator or on a physical device? Do you have any steps to reproduce?

**Comment by astralbodies** [comment]
@zhoufusong That's definitely a tricky one to reproduce for me as well. Are you using any corporate policies around data protection on your devices? It's possible that iOS' data protection is turned on that way. Do you know if this possibly came from a push notification while the phone was locked?

**Comment by astralbodies** [comment]
🥳
