### ISSUE TITLE
Reader: Can't swipe back to leave post detail while offline

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#10865]
### Expected behavior

I expect to always be able to swipe back from post details to the list view in the Reader.

### Actual behavior

While offline, you can't swipe back from post details to the list view. From the original report (internal ref: p4a5px-2ke-p2):

> I tried to swipe from left to right to go back to previous screen and kept getting this notification about being offline, which prevented me from going back. The chevron towards left still works, but not the swipe gesture.

### Steps to reproduce the behavior

1. Open the Reader in the app.
2. Tap a post to view the post detail.
3. Swipe to go back to the list view.
4. Tap the post again to view the post detail.
5. Go offline (e.g. enable airplane mode).
6. Try again to swipe to go back to the list view.

Result: An alert pops up with "Unable to Sync / The internet connection appears to be offline" and stops the swipe from taking you back to the list view.

**Comment by leandroalonso** [comment]
The issue doesn't occur anymore.
