### ISSUE TITLE
Gutenberg opt-in API implementation

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-iOS#10870]
For Gutenberg beta, we'll have to implement an API for opt-in that keeps us in sync with the web and other mobile platforms (aka Android). This issue only takes into account the implementation of the API endpoint from the client side itself - will make references to the UI part and flows on other issues where this one in particular is a prerequisite.

#### API description
To query:
```
GET /wpcom/v2/sites/:site/gutenberg?platform=mobile

{
    "editor_mobile":"gutenberg",
    "editor_web":"gutenberg",
    "opt_out":"https:\/\/public-api.wordpress.com\/wpcom\/v2\/sites\/:site\/gutenberg?editor=aztec&platform=mobile"
}
```

If the user wants to opt-in, we'd send something like this:
```
POST /wpcom/v2/sites/:site/gutenberg?platform=mobile&editor=gutenberg

{
    "editor_mobile":"gutenberg",
    "editor_web":"gutenberg",
    "opt_out":"https:\/\/public-api.wordpress.com\/wpcom\/v2\/sites\/:site\/gutenberg?editor=aztec&platform=mobile"
}

```

If the user wants to opt-out instead, we'd send something like this:
```
POST /wpcom/v2/sites/:site/gutenberg?platform=mobile&editor=aztec

{
    "editor_mobile":"aztec",
    "editor_web":"gutenberg",
    "opt_in":"https:\/\/public-api.wordpress.com\/wpcom\/v2\/sites\/:site\/gutenberg?editor=gutenberg&platform=mobile"
}

```
Related backend patches D19975, D20164
sister Android issue https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/1084

**Comment by etoledom** [comment]
Closed via https://github.com/wordpress-mobile/WordPress-iOS/pull/12221 and https://github.com/wordpress-mobile/WordPress-iOS/pull/12276
