### ISSUE TITLE
Conform to Community Standards

### ISSUE THREAD

**Issue by stevebaranski** [wordpress-mobile/WordPress-iOS#10884]
To promote consistency across `WordPress-iOS` frameworks & to conform to [recommended community standards](https://github.com/wordpress-mobile/WordPress-iOS/community), we should update this repository to include all of the following:

- [X] Description
- [X] README
- [X] Code of conduct
- [X] Contributing
- [X] License
- [ ] Issue templates
- [X] Pull request template

**Comment by shiki** [comment]
@designsimply I believe we can close this. We have Issue Templates now.

**Comment by designsimply** [comment]
Thanks! Closing per the recommendation. 👍
