### ISSUE TITLE
invalid client id

### ISSUE THREAD

**Issue by GPX-NSlog** [wordpress-mobile/WordPress-iOS#10882]
### Expected behavior

send magic link,
### Actual behavior

invalid client id
##### Tested on  iOS 

![simulator screen shot - iphone xr - 2019-01-23 at 19 25 25](https://user-images.githubusercontent.com/17864687/51604355-84a42600-1f47-11e9-9ca2-ab3f850086a0.png)

**Comment by rachelmcr** [comment]
If you are developing the app, you can log in using the email address and password linked to the account you used to [set up credentials](https://github.com/wordpress-mobile/WordPress-iOS#setup-credentials) for the app. Other login methods (such as Google login and magic links) rely on undocumented [WordPress.com REST API endpoints](https://developer.wordpress.com/docs/api/) that only accept whitelisted client IDs; you won't be able to log in that way with your developer credentials.

If you encountered this error using the app store version of the WordPress app, please provide steps to reproduce the error and we can investigate!
