### ISSUE TITLE
[Site creation] "Site names can only contain lowercase letters (a-z) and numbers" error

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#10908]
When calling `sites/new` we're running into this error

```
2019-01-28 18:01:59:031 WordPress[24498:392342] Error Domain=WordPressKit.WordPressComRestApiError Code=7 "Site names can only contain lowercase letters (a-z) and numbers." UserInfo={WordPressComRestApiErrorCodeKey=blog_name_only_lowercase_letters_and_numbers, WordPressComRestApiErrorMessageKey=Site names can only contain lowercase letters (a-z) and numbers., NSLocalizedDescription=Site names can only contain lowercase letters (a-z) and numbers.} | Optional(<NSHTTPURLResponse: 0x600001a7ed40> { URL: https://public-api.wordpress.com/rest/v1.1/sites/new?locale=en }
```

The confusing part here is that I've verified this happens even when we request a site with only lowercase letters and numbers in `createWPComSite()`

**Comment by kwonye** [comment]
There's gotta be something going on here... @oguzkocer can you clarify whether or not you do anything special with the `sites/new` call on Android please?

**Comment by stevebaranski** [comment]
This is curious; it did [appear](https://github.com/wordpress-mobile/WordPress-iOS/pull/10760) to be working.

Possibly helpful : 

I can't help think that this could be an issue encoding the [`SiteCreationRequest`](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/develop/WordPressKit/WordPressComServiceRemote%2BSiteCreation.swift#L43-L76). It's worth noting that both the short site title & the URL are being encoded as `blog_title` & `blog_name`, respectively. 

I wouldn't expect that these are being mapped to the wrong keys, but the [response](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/develop/WordPressKitTests/Mock%20Data/site-creation-success.json) uses different keys (i.e., `url` & `blogname`, respectively)...

If it helps, the tests documenting our assumptions can be found [here](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/develop/WordPressKitTests/SiteCreationRequestEncodingTests.swift).

**Comment by stevebaranski** [comment]
_FYI : I retracted a previous comment after gathering additional information._

I think @ctarda is right. 

**Existing Site Creation**

Here is what I see when I use the current experience, which works in production today.

`blog_name` : `10919i.home.blog` & `blog_title` : `10919i`.
`blog_name` : `10919i` & `blog_title` : `10919i` (with the `10919i.wordpress.com` domain selected).

The `wordpress.com` suffix is programmatically removed when detected after selection. [See also](https://github.com/wordpress-mobile/WordPress-iOS/blob/2d4089e965c7db2c3f458873278d3e1b17bf558d/WordPress/Classes/ViewRelated/NUX/SiteCreationDomainsViewController.swift#L96).

**New Experience**

We are currently passing in the full domain when it's returned from the service [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Site%20Creation/Wizard/SiteCreator.swift#L45).

When the change [was merged](https://github.com/wordpress-mobile/WordPress-iOS/pull/10760), we had not yet integrated the Domains suggestion service, and as such, the workaround in-place only passed the slug. That workaround was removed [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/10786).

**Recommendation**

It would be great if the service accounted for this, but if a programmatic change is required, I would apply it in the `SiteCreator.build()` method.

**Comment by oguzkocer** [comment]
It seems like this is already figured out, but I'll reiterate what we do on Android. If the selected domain is `example.wordpress.com`, we send `example` as the `blog_name`, if it's `example.home.blog` we send `example.home.blog`. So, it's full url unless it's a WordPress.com subdomain.
