### ISSUE TITLE
[Site creation] Remove client-side handling of .blog subdomains

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#10919]
The previous Site Creation flow had client-side logic to request specific parameters which resulted in the app receiving .blog subdomains for blog site types.

With our new flow, we want to remove any hard-coded logic for whether a certain segment ID is a blog in case it changes in the future.

I believe we can just revert this [commit](https://github.com/wordpress-mobile/WordPress-iOS/pull/10786/commits/fb0d3ff28a361585ad9b9ba3fde549696aae0f2f).

It's expected that we "lose" functionality by doing this, but it will be temporary as we find a different solution that works for our new Site Creation flow.

Expected: All segments search the DomainsService for exclusively .wordpress.com subdomains.

**Comment by stevebaranski** [comment]
The client-side logic was removed. An discussion of the alternate solution is still being discussed via `paCBwp-F-p2`
