### ISSUE TITLE
<img> tags inside of <video> tags in reader don't work correctly.

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#10930]
### Expected behavior
Viewing a post with a video inside of it that has an `<img>` tag for fallback properly displays the video.

### Actual behavior
It just displays the `<img>` tag.

### Steps to reproduce the behavior
(background: https://github.com/wordpress-mobile/WordPress-iOS/pull/10929)
1. View https://marco.org/2019/01/28/overcast-instant-search
2. Should see the video, instead, we just see the preview image

##### Happens on all devices

**Comment by aerych** [comment]
I think I'm at (or nearly at) the bottom of this.  #10957 will sort the sizing issue which just leaves the question of why the video doesn't play.  Check this out:

Open the [rest console](https://developer.wordpress.com/docs/api/console/), view `v1.2/read/feed/9896797/posts`, and find the post in question. 
Now checkout the source rss feed https://marco.org/rss and find the same post. 
Currently the post is the first result in both feeds. 
Take a careful look at the markup for the `video` tag and try to spot the difference.  Spoiler alert - the version returned from the REST endpoint is missing the `onclick` attribute. 

If I were to hazard a guess, I'd say that we crawled an earlier version of that post that was missing the `onclick` behavior.  If I copy the version from the rss feed into my own test post and view that test post in the reader it just works.  I'm a bit baffled why there'd be a need for the `onclick` event, but I'm thinking the video not playing has more to do with some incomplete markup than anything else.  The `video` tag omits the `controls` attribute so playback depends on the `onclick` attribute.  Thinking we might should force add `controls` to avoid this in the future.

**Comment by jkmassel** [comment]
First off, wow – great detective work.

>Thinking we might should force add `controls` to avoid this in the future.

This makes a ton of sense to me. IMHO, we should never have autoplay videos in the reader, they should always need to be started by user interaction (even if one like this is meant to be more like a gif).

Enforcing the `controls` attribute seems like a great way to do that.
