### ISSUE TITLE
Password font size in NUX smaller when first responder

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#1096]
I'm not sure if this is by design or not, but the password field in the NUX has a smaller font size when the field is first responder.  As soon as that is resigned, then the font gets larger.  Seems a bit jarring to the user - they may mistake the password length as an error on their part.
![passwords](https://f.cloud.github.com/assets/373903/1975626/5f6b3202-837f-11e3-8438-bb95fd9ef840.png)

**Comment by rachelmcr** [comment]
I tested this today in 5.7 and no longer see this issue. There's a small change in alignment when switching between fields, which looks to be related to #4415.

Closing as resolved.
