### ISSUE TITLE
Gutenberg editor is blocking the screen if user taps update during an image upload

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/WordPress-iOS#10971]
### Expected behavior
We need to be able to tap close button or other places as in aztec editor:

![media-upload-block-classic](https://user-images.githubusercontent.com/5032900/52422943-2612a680-2b08-11e9-8456-016b584464f6.gif)

### Actual behavior
Gutenberg editor is blocking the screen if user taps update during an image upload

![media-upload-block](https://user-images.githubusercontent.com/5032900/52422983-3b87d080-2b08-11e9-9e89-2c4ab2624578.gif)

**Comment by SergioEstevao** [comment]
@pinarol thanks for the report and the videos.

So I tested this and now remember the logic behind it. 

So on the first video, on Aztec, you press the X button and then choose Update, this makes the editor close and publish in async mode. 
You can also see that on Aztec the Update button on the top right is disabled while the update is ongoing. The reason for this is that this update option keeps the editor open so before we send anything to the server we need to make sure that media is uploaded so we need to wait for the upload.

On GB for some reason we have that update button enable while the updates are going... this is the bug it should be only be available after the uploads are finished. If you do the same action as you did in Aztec (press the X and tap update) the behavior will be the same.

cc @koke

**Comment by koke** [comment]
Sounds good, we should still disable that Update button as you mention, but no need to worry for 1.0
