### ISSUE TITLE
[Stats Refresh] Activate feature flag

### ISSUE THREAD

**Issue by stevebaranski** [wordpress-mobile/WordPress-iOS#10974]
[Previously](https://github.com/wordpress-mobile/WordPress-iOS/pull/10348) we added a feature flag to control access to the new & improved Stats experience.

In `FeatureFlag.swift`, modify the `enabled` logic to return `true` for all configurations of the ` statsRefresh` case. At present, it's only enabled for the `localDeveloper` configuration.

**Comment by ScoutHarris** [comment]
https://github.com/wordpress-mobile/WordPress-iOS/pull/11826
