### ISSUE TITLE
Add message content for no/weak connectivity error to stats.

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#11004]

**Comment by diegoreymendez** [comment]
Is this change still needed?  Can you add a description to clarify?  Thanks!

**Comment by yaelirub** [comment]
It was a suggestion by Will to add the content of the error message that is received due to no/ weak connectivity. Do you think it's necessary?

**Comment by diegoreymendez** [comment]
@yaelirub - I don't have enough context to be able to answer... add the content of what error message where?

**Comment by diegoreymendez** [comment]
I think part of the problem is that the issue as it is right now doesn't include enough information.

Can we have a full description of what the current situation is and what we want to change?

**Comment by yaelirub** [comment]
Do we want to track the connectivity errors? @shiki, do you think there is value in that?

**Comment by shiki** [comment]
@yaelirub I don't remember this being discussed. But to answer your question, I don't think there's any value to adding those. At least, not right now.

**Comment by yaelirub** [comment]
I agree. I'll close this issue if there's no objection

**Comment by shiki** [comment]
No objection! Closing it for you. 😄

**Comment by diegoreymendez** [comment]
Thanks!
