### ISSUE TITLE
Configure Offline Notice messages according to state and location

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#11034]
This should probably be done after #11035.  

## Possible messages

* "No internet connection. Some posts may be unavailable while offline."
* ” Some pages may be unavailable while offline.
* ” Some media may be unavailable while offline.
* ” Some comments may be unavailable while offline.
* ” Some settings may be unavailable while offline.
* ” Some content/information/data may be unavailable while offline. (for generic use)

**Comment by mikedang** [comment]
These messages make sense and look good to me!
