### ISSUE TITLE
Quick Start V2: Prompt for next step appearing when exiting checklist VC

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#11051]
I think there might be an issue with the way quick start prompts are being displayed / selected. I'm able to recreate this on `develop`:

* Create a new site, agree to quickstart. The first (icon) prompt appears.
* Navigate into one of the checklist view controllers.
* Tap Back to return to blog details
* The prompt for the next tour item will appear. Don't interact with it.
* Go back into a checklist, and back out again.
* The prompt for the next tour item will appear.

And so forth. For me, it cycles through all the tour items this way, without me interacting with them in any way. It feels like this isn't the intended behaviour?

You can see a video here: https://cloudup.com/ckKGTPOHly0

cc @nheagy @danielebogo

**Comment by danielebogo** [comment]
I add @SylvesterWilmott 
The problem is we don't have a skip limit anymore. The new logic says we should re-start to display a notice only if a task is completed.
