### ISSUE TITLE
[Stats Refresh] Add country map to Period Countries card

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#11083]
Add country map to Period Countries card.

Possible library for map: https://github.com/ArthurGuibert/FSInteractiveMap

Design:
<img width="295" alt="countries" src="https://user-images.githubusercontent.com/1816888/52979998-5c1c1a00-3395-11e9-8214-782856e9e53d.png">

**Comment by SylvesterWilmott** [comment]
Looks great!

One small request, can we hide the map if there is no data available?

**Comment by ScoutHarris** [comment]
@danielebogo - when you get to the map, can you keep @SylvesterWilmott 's request in mind please? Thanks!

**Comment by ScoutHarris** [comment]
Done with https://github.com/wordpress-mobile/WordPress-iOS/pull/11929.
