### ISSUE TITLE
Reader is removing too much whitespace

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#11088]
A user reports that some of their Gutenberg posts are missing spaces on the reader. After some debugging, I noticed the HTML source had something like this:

```html
<p>1
Corinthians 13:12- For now we see only a reflection as in a mirror; then we
shall see face to face.&nbsp; Now I know in
part; then I shall know fully, even as I am fully known.&nbsp; </p>
```

There's a `\n` at the end of each line, that normal web rendering would present as a single space, but the native reader seems to be stripping

**Comment by koke** [comment]
We seem to be simply [removing](https://github.com/wordpress-mobile/WordPress-iOS-Shared/blob/develop/WordPressShared/Core/Utility/RichContentFormatter.swift#L172)  any new line outside a `<pre>` tag from post content.

I tried replacing `\n+` with a space, but it's a bit more complicated than that.

According to the specs ([HTML](https://www.w3.org/TR/html4/struct/text.html#h-9.1), [CSS](https://www.w3.org/TR/CSS2/text.html#white-space-model)), the rules for _normal_ whitespace rendering (outside `<pre>`) should be:

* Any tab or newline gets converted to a space
* Any sequence of spaces gets converted into a single space
* Any space at the start or end of a tag gets removed

**Comment by designsimply** [comment]
Possibly related: https://github.com/WordPress/gutenberg/pull/12166

**Comment by leandroalonso** [comment]
Reader Detail now uses a webview, which shouldn't cause this issue.
