### ISSUE TITLE
Fastlane Release Toolkit Broken

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#11123]
### Expected behavior
Checking out a fresh copy of this repo, and running the following should have no errors:

```bash
rake dependencies
cd Scripts
bundle exec fastlane
```

### Actual behavior

When running `fastlane`, there's a console error that reads:

```
[11:52:38]: Error loading plugin 'fastlane-plugin-wpmreleasetoolkit': cannot load such file -- git
[11:52:38]: It seems like you wanted to load some plugins, however they couldn't be loaded
[11:52:38]: Please follow the troubleshooting guide: https://docs.fastlane.tools/plugins/plugins-troubleshooting/
+-----------------------------------+---------+------------------+
|                          Used plugins                          |
+-----------------------------------+---------+------------------+
| Plugin                            | Version | Action           |
+-----------------------------------+---------+------------------+
| fastlane-plugin-wpmreleasetoolkit | 0.1.5   | No actions found |
+-----------------------------------+---------+------------------+
```

### Steps to reproduce the behavior
Documented above

**Comment by jtreanor** [comment]
This error is caused by the fact that `release-toolkit` uses the `git` gem but did not declare it in the gemspec. I fixed this in https://github.com/wordpress-mobile/release-toolkit/pull/29 and I have updated WPiOS to use the new version in https://github.com/wordpress-mobile/WordPress-iOS/pull/11138.
