### ISSUE TITLE
Update Quick Start Notice style to follow Muriel design guidelines

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#11139]
This is a follow up to #11033. The `QuickStartNoticeStyle` was largely left untouched in #11033. It should be updated for consistency. 

Please see: https://murieldesignsystem.blog/components/snackbars/

**Comment by shiki** [comment]
Taking this out of the Offline Messaging project. I think this can be done as an individual task. 

cc @diegoreymendez

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
