### ISSUE TITLE
Quick Start: Don't suggest a tutorial after a checklist item is skipped

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#11149]
If one of the quick start checklist items are skipped (with a left swipe), when the checklist is dismissed the next tutorial after the one skipped will be suggested. There should be no suggestion; suggestions are only for when a tutorial is actually completed by the user.

A related issue is that skipping a tutorial in this way also completes it (firing the analytics event as well).

![qs suggestion bug](https://user-images.githubusercontent.com/517257/53390202-47b4c000-3947-11e9-93bf-f60cf56dc01d.gif)

**Comment by frosty** [comment]
Fixed by #11156
