### ISSUE TITLE
Site Creation: Tagline isn't set

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#11151]
### Expected behavior

When I enter a tagline in the site creation flow, I expect it to be set on the site.

### Actual behavior

The tagline I entered isn't saved or displayed on my site.

### Steps to reproduce the behavior

1. Go to My Sites and create a new WordPress.com site.
2. On the "Basic information" screen, enter a title and tagline.
3. After the site is created, check to see if the tagline is displayed.
4. Go to My Sites > Settings and check to see if the tagline is saved.

Result: The tagline is not saved or displayed.

**Comment by designsimply** [comment]
Tested with WP Internal 12.0.0.20190311 on iPhone 6S iOS 12.1.4 and confirmed the tagline set during site creation is still not saved. ([1m27s](https://cloudup.com/cLRWoPn7CNQ))

<img src="https://user-images.githubusercontent.com/1119271/54394098-82ba3180-4671-11e9-94d3-a56e6ba88171.png" width="270" alt="tagline-set">    <img src="https://user-images.githubusercontent.com/1119271/54394097-82ba3180-4671-11e9-9ee7-ef8aabb8af2c.png" width="270" alt="tagline-was-not-saved">

**Comment by stevebaranski** [comment]
[This comment](https://github.com/wordpress-mobile/WordPress-Android/issues/9342#issuecomment-468344922) from the corresponding Android defect suggests this might be a server-side issue. If so, it would account for the occurrence on both platforms.

**Comment by stevebaranski** [comment]
@designsimply A discussion about this topic is underway via `p1552602073005000-slack-bt-site-creation`, and a resource has been assigned. If confirmed as a server-side issue, the issue should not require a client-side fix. Otherwise, a change will need to be expedited.

cc: @malinajirka @oguzkocer @ctarda @kwonye

**Comment by stevebaranski** [comment]
As for the behavior, I have double-checked the request sent in production (11.9), and can confirm that the tagline is being sent, as noted in the following payload.

```
{
	"validate": false,
	"options": {
		"site_vertical": "p23",
		"site_segment": 2,
		"site_information": {
			"site_tagline": "test"
		}
	},
	"public": 1,
	"blog_title": "11151a",
	"client_id": "11",
	"client_secret": REDACTED,
	"blog_name": "11151a",
	"lang_id": "1"
}
```

For reference, it was tested *before* the services were in place based on the contract `p9wMUP-bH-p2`):

https://github.com/wordpress-mobile/WordPressKit-iOS/blob/develop/WordPressKitTests/SiteCreationRequestEncodingTests.swift

https://github.com/wordpress-mobile/WordPressKit-iOS/blob/develop/WordPressKitTests/SiteCreationResponseDecodingTests.swift

https://github.com/wordpress-mobile/WordPressKit-iOS/blob/develop/WordPressKitTests/WordPressComServiceRemoteTests%2BSiteCreation.swift

And *after* : #10712

**Comment by michaeldcain** [comment]
This was fixed in D25611-code.

**Comment by stevebaranski** [comment]
Confirmed - thank you!
