### ISSUE TITLE
Quick Start: Crash when I start quick start after deleting a site

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#11168]
### Expected behavior

I expect to be able to use Quick Start on any new site.

### Actual behavior

If I delete a site, then create a new site and try to use Quick Start, the app crashes.

### Steps to reproduce the behavior

1. Create a new site in the app.
2. When prompted, choose to start Quick Start.
3. Go to My Sites > Settings and delete that site.
4. Create a second new site in the app.
5. When prompted, choose to start Quick Start.

Result: Crash. (When you open the app after the crash, the Quick Start next steps are there and you can continue to use them.)

##### Tested on [iPhone XS], iOS [12.1.4], WPiOS [11.9.0.20190226]

h/t @stojdza for the original report

**Comment by frosty** [comment]
cc @nheagy

**Comment by designsimply** [comment]
I tested today and was unable to trigger this crash using the steps provided. ([3m26s](https://cloudup.com/ceFdgVOHPdd))
<sup>Tested with WPiOS 14.4 App Store version on iPhone 11 iOS 13.3.1.</sup>

We can re-open if we receive any new reports.
