### ISSUE TITLE
Quick Start: cannot reach customization if you are already on themes

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11178]
### Expected behavior

I expect to be able to get to Customize from any location while using Quick Start

### Actual behavior

For the Customization step, you cannot get to Customization if you are already on Themes.

### Steps to reproduce the behavior

1. Create a new site from an existing account.
1. Select "Yes" when prompted with help getting started.
1. Go to Themes.
1. Tap "Customize Your Site" in the left meu.
1. Tap "Customize your site" in the checklist that pops up.
1. Try tapping the indicator pulsing on the Themes option—it won't work if you're already on the themes page. ([17s](https://cloudup.com/cvIeyCpnaAb))

<img src="https://user-images.githubusercontent.com/1119271/53675023-d7ac7f80-3c4f-11e9-8155-79aa4fe3170c.PNG" width="388" alt="img_0107">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
