### ISSUE TITLE
Stats Refresh: latest post summary only leads to graphs about views and not likes or comments

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11179]
### Expected behavior

I expected that clicking on Likes in the Latest Posts Summary would take me to a graph about Likes.

### Actual behavior

Clicking on Views, Likes, or Comments in the Latest Post Summary card always takes you to a graph of Views.

### Steps to reproduce the behavior

1. Go to Stats > Insights.
1. In the Latest Posts card, click on Views, Likes, and Comments.
1. Observe that clicking on Views, Likes, or Comments always takes you to a graph of Views.

<img src="https://user-images.githubusercontent.com/1119271/53675293-4ee31300-3c52-11e9-8527-daa7ad06b98b.PNG" width="320" atl="img_0020-2"> <img src="https://user-images.githubusercontent.com/1119271/53675292-4e4a7c80-3c52-11e9-9e82-40fe6191848e.PNG" width="320" alt="img_0018-2">

**Comment by ScoutHarris** [comment]
With Stats Refresh, the chart will still always show Views. However, Likes and Comments will no longer be click-able. The design is:

![insights](https://user-images.githubusercontent.com/1816888/53753201-ea040480-3e6d-11e9-8f21-061d786795e3.png)

Closing this as it won't actually be an issue with Stats Refresh.

**Comment by designsimply** [comment]
Thank you for the update!
