### ISSUE TITLE
Editor / Post List: too much extra space between blocks in the Blog Post list

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11177]
### Expected behavior

Normal spacing between blocks for posts in the Blog Posts list.

### Actual behavior

There's too much extra space between blocks for posts in the Blog Posts list.

### Steps to reproduce the behavior

1. Go to Me > Help & Support > App Settings and toggle Use Block Editor on.
1. Go to My Sites > Blog Posts > +.
1. Add a title, a few paragraphs, an image with a caption, a page break, and another paragraph.
1. Publish the post.
1. View the post card in the Blog Posts list.

<img src="https://user-images.githubusercontent.com/1119271/53670789-2a2e7180-3c39-11e9-9d4e-4d7856dd02b4.PNG" width="300" alt="img_0093"> <img src="https://user-images.githubusercontent.com/1119271/53670901-99a46100-3c39-11e9-9521-76bc690597ef.PNG" width="300" alt="img_0093-2">

**Comment by kean** [comment]
This issue is obsolete given the changes to the screen design.
