### ISSUE TITLE
[Stats Refresh] Insights Comments detail list: correct data with new API

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#11182]
With https://github.com/wordpress-mobile/WordPress-iOS/pull/11181, the detail view was added for Insights Comments. However, there is currently no API call to get the full list of Comments, for Authors and Posts & Pages.

When the calls are added to the API, `StatsInsightsStore` and `SiteStatsDetailsViewModel` need to be updated to use the correct data.

cc @jklausa

**Comment by jklausa** [comment]
Closed by #11473
