### ISSUE TITLE
Reader: Get correct subscriber count for sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#11194]
### Expected behavior

I expect the subscriber count on the site Reader feed in the app to match the count I see in the web Reader.

### Actual behavior

The subscriber count doesn't always match what I see in the web Reader.

The discrepancy seems to be from the endpoint used. The web Reader seems to use the `/read/sites/$site` endpoint for sites (although it also [distinguishes between the subscriber counts for sites and feeds](https://href.li/?https://github.com/Automattic/wp-calypso/blob/df8fe9e82dae71d8df9b78fe7a725e04e4067311/client/blocks/reader-feed-header/index.jsx#L39)) whereas the app is using `/read/feed/$feed_url_or_id`. For some reason those endpoints return different subscriber counts for the same site.

### Steps to reproduce the behavior

1. In the web Reader, go to the Search: https://wordpress.com/read/search
2. Search for a site.
3. In the search results, select and view the site feed. Note the subscriber count.
4. In the app, open Reader > Search.
5. Search for the same site.
6. In the search results, select and view the site feed. Note the subscriber count.

For example, the en.blog.wordpress.com web feed: https://wordpress.com/read/feeds/25823

![screenshot 2019-03-06 12 58 34](https://user-images.githubusercontent.com/8658164/53882962-b06aff00-400f-11e9-90c6-2833eb1c481c.png)

Compared to the app feed:

![2019-03-06 12 58 33](https://user-images.githubusercontent.com/8658164/53883006-c7a9ec80-400f-11e9-8520-aa9de59a7b8d.png)

##### Tested on [iPhone XS], iOS [12.1.4], WPiOS [11.9.0.2090226]

h/t @charliescheer for the initial report (internal ref: p4a5px-2lS-p2)
This could also be related to the subscriber count issue reported in https://github.com/wordpress-mobile/WordPress-iOS/issues/6467.

Related Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/9371

**Comment by rachelmcr** [comment]
Interestingly, if you follow the site and open the site feed from your Followed Sites list, the app shows the correct subscriber count. h/t @frosty

**Comment by frosty** [comment]
@rachelmcr Thanks for digging into this! We use /read/sites in some situations and /read/feed in others, so that probably accounts for the discrepancy.

**Comment by bluefuton** [comment]
Good news - this should have been resolved by D31816-code. The `/read/feed` endpoint now returns the blog's subscriber count if the feed has a blog ID set 👍The counts should now be consistent between the site and feed endpoints.

More discussion about this in p5PDj3-4MB-p2. Related Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/9371.
