### ISSUE TITLE
Account Settings: better error messaging for change email flow when address is already in use

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-iOS#11214]
### Expected behavior
While logged into a WordPress.com account on the app, I try to update my email address to one that's used on a different WordPress.com account.
I expect to get an error which explains the email address is already being used on another account.

### Actual behavior
I briefly see the normal "there is a pending change..." message, which then disappears. my initial email address appears in the Email field again, no change is made.

### Steps to reproduce the behavior
You'll need two WordPress.com accounts to test.
1. Logged into account #1, go to Me > Account Settings and tap Email.
2. Change the email address to the email address associated with account #2.
3. See that the change is not made, and no "confirm change" email is sent.

##### Tested on iPhone SE, WPiOS 11.9
Originally from user report, Xiaomi Redmi Note 4X, WP Android 11.6, reported here: https://github.com/wordpress-mobile/WordPress-Android/issues/9384

**Comment by rachelmcr** [comment]
Note that if the email address change fails in this case, the API returns a nice error message we could use:

`{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"invalid_input","message":"That e-mail address is already being used."}}`
