### ISSUE TITLE
[Sharing] Add TextBundle support

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#11223]
As part of our work to [improve sharing](
https://github.com/wordpress-mobile/WordPress-iOS/issues/10955) into the app, we could add support for the [TextBundle file format](http://textbundle.org). TextBundle allows text content and images to be bundled together into a single package format.

We could add the TextBundle UTI (either `org.textbundle.package` or `org.textbundle.compressed`) to be handled by the share extension, and a new Extractor to extract content from it. This would likely involve copying the bundle into our container, extracting the content, setting correct placeholders for any images when they're uploaded, and populating the editor.

The developers of Bear have an Objective-C [TextBundle wrapper](https://github.com/shinyfrog/TextBundle) that we may be able to use.

cc @nheagy @matteorattotti

**Comment by frosty** [comment]
@matteorattotti Would this involve you adding a special case to Bear when sharing to WordPress?

**Comment by matteorattotti** [comment]
Short answer is no, we can just add the TextBundle format to our export formats when an user share the note.

BUT we can add custom metadata to the TextBundle json file to provide the WordPress other informations like tags, title, etc...

If you're going to support the TextBundle you will also gain integration with all the iOS app that support the format.
