### ISSUE TITLE
[Gutenberg] Can’t start a post from the Media section

### ISSUE THREAD

**Issue by marecar3** [wordpress-mobile/WordPress-iOS#11246]
**Expectation**: I’m used to having the option to upload media to My Sites > Media and using the “Write Post” notice/snackbar to start a new post with that media already added to the post.
Actual: When I select “Write Post” after uploading media, I get a new blank Gutenberg post.

**Steps**:
Go to My Sites > Media in the app.
Upload a new image.
When the image finishes uploading, tap “Write post” in the notice/snackbar that appears. Result: A new Gutenberg post opens with no content.

**Comment by designsimply** [comment]
Tested and confirmed using WP Internal 12.0.0.20190314 on iPhone 6S iOS 12.1.4.

<img src="https://user-images.githubusercontent.com/1119271/54636092-3ee97280-4a4b-11e9-8890-c6281c612775.PNG" width="270" alt="IMG_2117"> <img src="https://user-images.githubusercontent.com/1119271/54636060-2b3e0c00-4a4b-11e9-95c3-e010f90ed194.PNG" width="270" alt="IMG_2118">
