### ISSUE TITLE
Crash in Reader after re-authentication prompt appears

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#11249]
### Expected behavior
Does not crash after prompt is presented

### Actual behavior
Crash. See Ref: #11245

### Steps to reproduce the behavior
This can be done in the simulator.
1. Be logged in
2. Navigate to Reader > Manage > (your favorite site) > a post that has comments > view comments
3. In your browser, [revoke](https://wordpress.com/me/security/connected-applications) the WPiOS app
4. Returning to the app, like one of the comments on your screen.
(Crash)

**Comment by designsimply** [comment]
I was unable to reproduce the crash using the testing steps provided. ([42s](https://cloudup.com/cZdoCN-4Ekc))
<sup>Tested with WPiOS 14.4 App Store version on iPhone 11 iOS 13.3.1.</sup>

Please re-open if you find you are still having trouble or if there are any new user reports of this crash.
