### ISSUE TITLE
Visual defect : transparent navigation bar encountered when re-authenticating

### ISSUE THREAD

**Issue by stevebaranski** [wordpress-mobile/WordPress-iOS#11250]
### Expected behavior
When executing the testing steps noted in [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/11245), the visual appearance of the navigation bar is not what one would expect. Presumably, it should be "WordPress blue."

### Actual behavior
The navigation bar is transparent, as observed [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/11245#issuecomment-472130070). This may be due to an issue with configuration via the [appearance proxy](
https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/System/WordPressAppDelegate.m#L386-L387).

### Steps to reproduce the behavior
Repeat the steps noted in the aforementioned PR. Observe the appearance of the login screen.

##### Tested on [device], iOS [version], WPiOS [version]
iPhone XS, WPiOS v11.9 hot fix (& later)

**Comment by SergioEstevao** [comment]
I've tried to fix this with several approaches on the appearance proxy and they all failed, it looks there must be something on the underlying Storyboard for that login screen that overrides the appearance settings, but until now I'm unable to find what is causing this.

**Comment by stevebaranski** [comment]
Thanks for that additional context, @SergioEstevao.

Before creating the issue, I took a cursory pass through issues both here and in `WordPressAuthenticator`. I'm going to make a note to revisit this during the next Groundskeeping rotation and/or HACK Week.
