### ISSUE TITLE
Remove Google Plus from Sharing Buttons

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11274]
The Google+ API has been [shut down](https://developers.google.com/+/api-shutdown), and the service as a whole will shut down in April. 

We can remove any Google+ code.

1. Go to My Site > Sharing > Sharing Buttons > Manage.
1. Toggle "Edit sharing buttons" on.
1. Google+ should be removed.

<img src="https://user-images.githubusercontent.com/1119271/54368537-f80a1000-4639-11e9-88ac-5c695e1347e3.PNG" width="270" alt="IMG_2098">

<sup>Tested with WP Internal 12.0.0.20190311 on iPhone 6S iOS 12.1.4.</sup>

Aside: 😆 https://twitter.com/chriscoyier/status/1105976643099680768

![Screen Shot 2019-03-14 at 9 07 00 AM](https://user-images.githubusercontent.com/1119271/54369158-0c9ad800-463b-11e9-8ad6-1e2f06f18adb.png)

**Comment by jkmassel** [comment]
This has been done for quite a while.
