### ISSUE TITLE
[Stats Refresh] Period Published detail list: correct data with new API

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#11283]
With #11282 , the detail view was added for Period Published. However, there is currently no API call to get the full list of Published.

When the calls are added to the API, `StatsPeriodStore` and `SiteStatsDetailsViewModel` need to be updated to use the correct data.

cc @jklausa

**Comment by jklausa** [comment]
@ScoutHarris I think the API for this is in WPKit already, here are the tests that are excersising it:

https://github.com/wordpress-mobile/WordPressKit-iOS/blob/develop/WordPressKitTests/StatsRemoteV2Tests.swift#L344-L366

The method also takes a `limit` parameter, with default value of 10: if you provide `0` (or `9999999` or whatever) here, I _think_ it should do what you want: https://github.com/wordpress-mobile/WordPressKit-iOS/blob/develop/WordPressKit/StatsServiceRemoteV2.swift#L195

**Comment by ScoutHarris** [comment]
Sorry I missed it. I'll take a look. Thanks!
