### ISSUE TITLE
Placeholder for self-hosted site URL should not include "wordress.com"

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11286]
### Expected behavior

The placeholder URL when adding a self-hosted site should not include "wordress.com".

### Actual behavior

The placeholder URL when adding a self-hosted site says `example.wordpress.com`.

<img src="https://user-images.githubusercontent.com/1119271/54398643-83a68f80-4680-11e9-8998-b990d674f0d2.png" width="270" alt="Screen Shot 2019-03-14 at 3 33 33 PM">

### Steps to reproduce the behavior

1. Go to My Sites.
1. Tap "+" at top right.
1. Select "Add self-hosted site".
1. Check to see if the placeholder says 

##### Tested on WP Internal 12.0.0.20190311 on iPhone 6S iOS 12.1.4.

h/t @keoshi for the original report! 😍

**Comment by keoshi** [comment]
Thanks for creating the issue, @designsimply — you're the best.

**Comment by nheagy** [comment]
Any thoughts on what the replacement URL should be? @RandyMcMillan proposed `example.com` but my feeling is something like `blog.example.com` might give users a bit of extra nudge as to what we're looking for.

Perhaps @Automattic/editorial could offer a suggestion?

**Comment by jkmassel** [comment]
The vast majority of self-hosted sites will be a bare domain (like example.com). IMHO we shouldn't include a subdomain, and it shouldn't include WordPress.com, because that could be confusing to a user. 

example.com _is_ a canonical resource for this sort of thing – it says right on the site 😃 

Unless we want to come up with a sample WordPress.org site to host, I'd suggest going with example.com

`</my-2¢>`

**Comment by elibud** [comment]
FWIW I support using example.com

**Comment by michelleweber** [comment]
+1 for example.com

**Comment by keoshi** [comment]
This has been fixed, presumably by the change on https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/88 (at least that's what I found).

Here's a screenshot from the 14.4.1 version as proof:

![image](https://user-images.githubusercontent.com/390760/79116635-edf89a80-7d80-11ea-84d4-060c275ba6df.png)

**Comment by thehenrybyrd** [comment]
`example.com` is also used in the new unified login&signup flows:

<img src="https://user-images.githubusercontent.com/15107387/132337023-8877f11e-980b-4752-8971-2d6c9cfd8652.jpeg" width="30%">

I'll close this issue as it is no longer relevant.
