### ISSUE TITLE
Comments: comment icon missing from post view accessed via Notifications

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11305]
Steps to reproduce:

1. Create a post with several comments, some threaded all approved.
1. Log in as the post author so you can see notifications of comments on the post.
1. Go to Notifications and tap on any comment.
1. Tap on the post name at the top.
1. Check to see if the comment icon appears at bottom right. It's missing.
1. Tap on the blog name at the top.
1. Tap on the same post to re-open it.
1. Check to see if the comment icon appears at bottom right. It's there now!

<strong>Result:</strong> the comment icon/link is present when you open a post from a Reader but it's missing if you open the post from Notifications. (<a href="https://cloudup.com/c_y3qSHlWdr">54s</a>)

<img src="https://user-images.githubusercontent.com/1119271/54706406-71a37180-4b04-11e9-9bc5-82df718bad79.png" width="270" alt="comment-icon-missing"> <img src="https://user-images.githubusercontent.com/1119271/54706405-71a37180-4b04-11e9-97ea-9e21e195764f.png" width="270" alt="comment-icon-visible">

<sup>Tested with WP Internal 12.0.0.20190314 on iPhone 6S iOS 12.1.4 using a WordPress.com Free site.</sup>

h/t @bisko for the original report at p4a5px-2mf-p2.

**Comment by rachelmcr** [comment]
IIRC this was an intentional decision since when you go from a comment notification you are first taken to the comments on the post and then to the post itself. To view the comments you can go back to the previous screen.

**Comment by designsimply** [comment]
Thank you for the explanation! Speaking personally, I like the idea of a consistent layout but I also understand the decision. Closing as wontfix for now with a note that we can re-open if it keeps coming up in additional end user reports.
