### ISSUE TITLE
Update privacy protection handling during domain registration.

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-iOS#11304]
Because of the recent [changes](https://github.com/Automattic/wp-calypso/pull/30948) to the cart endpoint, we should stop adding privacy protection to the cart as a separate product. Instead, we will add `extra: { privacy: true }` to the domain product object in a cart.

cc @jklausa @pinarol

**Comment by jklausa** [comment]
I'll take care of it today or tomorrow.

**Comment by jklausa** [comment]
Fixed in https://github.com/wordpress-mobile/WordPressKit-iOS/pull/127.
