### ISSUE TITLE
Search screen should show "Unable to load this page right now" when offline

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#11314]
Steps:

- Be offline
- Go to search 
- See "Search WordPress for site of post" with no image
![IMG_3601](https://user-images.githubusercontent.com/1335657/54731436-f7f39e00-4b6c-11e9-8ecc-a5e076f64cde.PNG)

- Search for something 
- See the "Unable to load this page right now" 
![IMG_BB0E3B31C84C-1](https://user-images.githubusercontent.com/1335657/54731441-fc1fbb80-4b6c-11e9-932d-8342e213e9be.jpeg)

**Comment by diegoreymendez** [comment]
I'm removing this issue from the offline messages project.  We'll be tackling this one we work on the reader's offline improvements.

**Comment by majo-bujnak** [comment]
hello, I would like to take this issue -- is this issue free?

**Comment by yaelirub** [comment]
Hey @majo-bujnak , thanks for your interest in this issue. I'm actually not sure what needs to be done here. 

A few months after I created this issue, we release our [offline principals ](https://mobile.blog/2019/06/25/offline-principles/) and according to those, this issue is no longer valid. 

I'm closing this issue but thank you so much for looking into it.
