### ISSUE TITLE
Snack bar is displayed on top of "unable to load this page" view

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#11310]
Steps:
- Be offline
- Go to site pages
We should show one or the other 
![IMG_3597](https://user-images.githubusercontent.com/1335657/54731120-31c3a500-4b6b-11e9-9a72-1158ec5d8eeb.PNG)

**Comment by shiki** [comment]
Thanks for creating this! I fixed it yesterday in this branch: [fix/site-posts-notice-and-empty-screen-shown](https://github.com/wordpress-mobile/WordPress-iOS/tree/fix/site-posts-notice-and-empty-screen-shown). I'll send a PR after #11303 is merged.
