### ISSUE TITLE
Remove Media library alert displayed on top of empty view when no connection.

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#11320]
Steps:
- Be offline
- Go to media 
See alert.
![IMG_3665](https://user-images.githubusercontent.com/1335657/54831569-51f18200-4c99-11e9-89b2-bd799d0405ee.PNG)

**Comment by diegoreymendez** [comment]
I'm removing this issue from the messaging project.  It will be tackled as part of our offline improvements projects once we reach the media section of the App.
