### ISSUE TITLE
Notifications: Display all likes in “Likes” panel

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-iOS#11327]
**I expect:**
To be able to see all likers listed in the Notifications “Likes” panel.

**Instead:**
I can see 10 of the likers, but no more, in the Notifications “Likes” panel.

It can be interesting for some users to see who has liked their post recently - I even like this within my own work, as it gives me a sense of which of my colleagues have seen a particular post. This is **possible when directly viewing the post itself in a web browser**, by tapping “## bloggers like this”, and is also possible within Reader by hovering over the “star” icon.

<img width="637" alt="Screen Shot 2019-03-23 at 10 15 05 AM" src="https://user-images.githubusercontent.com/15107387/54863863-bb839600-4d56-11e9-9773-7729a2a40596.png">

However, in the mobile app this is much harder. 
It _is_ technically possible, but **requires loading the in-app browser/viewport**, for instance by going to My Site > Blog Posts and tapping “View” on one of the posts. From there you can tap “## bloggers like this” once you’ve loaded a post with likes on it.

Here’s what it looks like:

![likevies](https://user-images.githubusercontent.com/15107387/54863985-76f8fa00-4d58-11e9-9486-4980f9f21791.gif)

Within the **Notifications panel itself** (Via Notifications directly, not through viewport), it’s only possible to see 10 of the likes.

![notelikes](https://user-images.githubusercontent.com/15107387/54864000-c5a69400-4d58-11e9-8693-af778206d124.gif)

Would it be possible to allow loading all of the likes within the Notifications likes panel?
Tapping "View likes on your post" from Notifications takes us to the Reader, where we also cannot view all likes, as reported in https://github.com/wordpress-mobile/WordPress-iOS/issues/5611.

**Tested on iPhone SE, iOS 12.1, WPiOS 11.9.1**

**Comment by rfaile313** [comment]
I tested as well on Samsung Galaxy S9+, Android 8.0.0, WP 11.9.0 - Same result.

**Comment by sophiegyo** [comment]
We had a user asking about this in 2758950-zen as well, so I'm adding it here as a request to display all likes.

**Comment by ScoutHarris** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/15662.
