### ISSUE TITLE
Domain Registration: Can't select a state.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11357]
### Expected behavior

When registering a domain, it should be possible to select the state where I work / live.

### Actual behavior

![cantPickState](https://user-images.githubusercontent.com/1836005/55119988-d3e70e00-50d2-11e9-9305-dfc59431a95a.gif)

**Comment by diegoreymendez** [comment]
Ping @jklausa as discussed.

**Comment by rachelmcr** [comment]
I believe this depends on selecting a country that has a list of states. (This came up as a side note from previous testing in https://github.com/wordpress-mobile/WordPress-iOS/issues/10535#issuecomment-441205345.)

**Comment by thehenrybyrd** [comment]
Confirmed in 18.2, selecting a Country such as US or Brazil which contains States makes States clickable and a list of appropriate states appears.
Closing.
