### ISSUE TITLE
Auth: header color bug in 2FA screen

### ISSUE THREAD

**Issue by folletto** [wordpress-mobile/WordPress-iOS#11377]
![UNADJUSTEDNONRAW_thumb_b0a0](https://user-images.githubusercontent.com/4389/55230509-ecad0c00-5217-11e9-837a-44f51d410342.jpg)

A couple days ago I logged in and I noticed the header for the 2FA code was broken (missing color?).

This was on iPhone X.

**Comment by rachelmcr** [comment]
Thanks for the report! This looks like it's probably the same underlying issue as https://github.com/wordpress-mobile/WordPress-iOS/issues/11250 (which appears when you re-authenticate in the app).
