### ISSUE TITLE
Quick Start: Dismiss Notices using clearWithTag

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#11394]
In #11281, we added the ability to dismiss Notices using tags:

```swift
ActionDispatcher.dispatch(NoticeAction.clearWithTag(noticeTag))
```

Using `NoticeAction.clearWithTag` is preferred to `NoticeAction.dismiss`. The `.clearWithTag` helps in avoiding dismissing Notices that the current page _did not create_. 

In #11281, we only changed `QuickStartTourGuide` to use `.dismiss`. This can be improved to use `.clearWithTag`.

**Comment by Reza-Rajabi** [comment]
Hi,
Let me try this one. Thanks.

**Comment by Reza-Rajabi** [comment]
I made a [pull request](https://github.com/wordpress-mobile/WordPress-iOS/pull/12780) for this issue.

**Comment by Reza-Rajabi** [comment]
I have made a pull request, and I am wondering if I could have a review/ feedback ...

**Comment by shiki** [comment]
Thank you, @Reza-Rajabi. We'll look into it.

**Comment by hypest** [comment]
Removed the ticket assignment as the related PR became stale. Please, feel free to pick this up again, thanks!
