### ISSUE TITLE
Credentials not being passed to webviews, requiring users to enter contact info to comment on blogs

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#11414]
When you use a webview to view a post (either from the reader or from the blog posts list) you have the ability to make comments on that post.  With a user who is logged into their WordPress.com account in the app, their login credentials should be passed to the app so they can comment with out logging in, but they do not.   When you try to comment on posts in webviews you are required to enter your email/name as if you were logged out.

<img src="https://user-images.githubusercontent.com/1119271/55661185-8c920900-57c7-11e9-8530-9559d4a217ea.png" width="270" alt="iPhone image on 2019-04-05 at 12_10_39">

To replicate:
1. Go to My Site > Blog Post > View (on any post with comments activated)
2. Swipe down to the comments section, and you will not be shown as logged in.

**Comment by jburciaga0** [comment]
Hey @designsimply - do you know if there is anyone that I can bump to look over this issue, if not you? I know a resolution may not be around the corner but I want to see if we can at least get a better timeframe on this bug.

Thank you!

**Comment by designsimply** [comment]
Hi @jburciaga0! I tested this just now and found that the comment form in an in-app browser on the iOS accessed via the Reader is working for me and the comment form when I look at a Webview accessed via the post list does seem to know who I am but I am unable to submit a comment from that view—which I would prefer to open a separate issue for. ([2m52s](https://cloudup.com/cxqBdHOfbaM))

<sup>Tested with WPiOS 12.5.1 (current app store version) on iPhone 6S iOS 12.3.1.</sup>

May I ask why you're asking? If you received this as a bug report from a user during a support interaction, could you include the zen shorthand link for it (I use those for tracking the top user-reported issues!) and also let me know the app version tested with and which route was using to get to the comment form: Post List to Webview or Reader to in-app browser? It's also super helpful to include a quote from the user describing the problem if you've got one that you can share on GitHub. 😊

**Comment by designsimply** [comment]
@charliescheer could you test this again with the latest app store version (currently 12.5.1) and let me know if the comment form in a Webview on WordPress.com posts still don't recognize you if you are logged in to a WP.com account via the WPiOS app?

**Comment by designsimply** [comment]
Scratch that last test. I figured out how to reproduce the issue. There is a step missing which is that you are not automatically authenticated in a webview if you are viewing a site with a custom domain in the reader. It works normally with a `*.wordpress.com` domain (which happens to be what I tested first).

**Comment by charliescheer** [comment]
Update. I am now not being asked to login when I try to comment, but the comments are not going through.
closing in favor of #11926
