### ISSUE TITLE
Offline Support: Inconsistent Overlay

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11428]
Adding media to a post - you can take a photo to add or insert one from the camera roll. An overlay is displayed over the image “failed to insert media, please tap for options.” Tapping the image brings up an action sheet with the options: remove image, retry, or dismiss. After dismissing the action sheet, the overlay disappears. Tapping on the image again brings up the action sheet. 
Steps:
1. Create new post while offline
2. Select media to upload
3. Tap the media to activate the action sheet
4. Tap outside of the action sheet
5. Return or add characters to the editing space
6. Scroll up and down in the view -- the overlay disappears
--

**Comment by yaelirub** [comment]
@diegoreymendez , what is the expected behavior?

**Comment by yaelirub** [comment]
I'm unable to reproduce. 
When dismissing the action sheet. I still see the overlay.
Tested in Aztec and Gutenberg. 
![image_ overlay](https://user-images.githubusercontent.com/1335657/58127367-10625200-7bca-11e9-87d1-8a7e92cf5164.gif)

I do think however that the notice showing up with "1 post, 1 file not uploaded" is annoying as it is blocking the action sheet and not needed as the user is offered to take action from the action sheet" 

@megsfulton , what do you think about removing the notice in case media upload failed?

![Simulator Screen Shot - iPhone Xs - 2019-05-21 at 13 15 04](https://user-images.githubusercontent.com/1335657/58127563-81096e80-7bca-11e9-9d69-3667ccb3252d.png)

**Comment by megsfulton** [comment]
I'm still able to reproduce this. I have a video I'll share with you in slack. Here are the steps I took:

1) Create new post while offline
2) Select media to upload
3) Tap the media to activate the action sheet
4) Tap outside of the action sheet
5) Return or add characters to the editing space
6) Scroll up and down in the view -- the overlay disappears 

-- 

>what do you think about removing the notice in case media upload failed?

Yeah we should for sure remove that for this case. 

This potentially highlights a new offline issue for discussion -- which is allowing local draft posts to be saved locally with media created or selected while offline. It feels kind of crappy to discard the media that someone tried to upload while they were offline.

**Comment by yaelirub** [comment]
Thank you so much @megsfulton!
It feels kind of crappy to discard the media that someone tried to upload while they were offline.
I agree.
I also noticed that in Gutenberg we don't give the "remove image" option in the action sheet.
![IMG_4141](https://user-images.githubusercontent.com/1335657/58135047-c1beb300-7bdd-11e9-9fd6-a597c8a2fc4f.PNG)

Is that something that we might want to do in Aztec too?

**Comment by diegoreymendez** [comment]
> It feels kind of crappy to discard the media that someone tried to upload while they were offline.  I agree.

Yup.  This is something that we should open a new issue for.

> Is that something that we might want to do in Aztec too?

I think it's best for this to be defined from the UI/UX Design side.  Since we're really close to the editor work, can I ask you @iamthomasbishop for your opinion?

**Comment by iamthomasbishop** [comment]
> It feels kind of crappy to discard the media that someone tried to upload while they were offline. I agree.

I also agree – we probably shouldn't remove the media, at least until the user leaves the editor.

> I also noticed that in Gutenberg we don't give the "remove image" option in the action sheet. ... Is that something that we might want to do in Aztec too?

The `Remove` action should already an option – I can confirm it is on Android, but we must've missed on iOS. I wonder if something shifted as part of the Image/Video block work here: https://github.com/wordpress-mobile/gutenberg-mobile/pull/979 // cc @pinarol any ideas?

**Comment by pinarol** [comment]
@iamthomasbishop Actually there was never a `Remove` option for failed uploads on Gutenberg. User can change the failed media via Edit button from the toolbar or remove the whole block. 

On the other hand on Aztec I can confirm that there is a `Remove` option for failed uploads and it is still there.

**Comment by yaelirub** [comment]
@pinarol , @iamthomasbishop , are we looking to keep the `Remove` option in Aztec?

**Comment by iamthomasbishop** [comment]
@pinarol Interesting, not sure how I missed that – I must've assumed that because it was being implemented on Android that it'd also be there on iOS. Definitely an oversight on my part, apologies! I can create a separate issue for this.

@yaelirub I would prefer to keep it in Aztec, unless there are special reasons for ditching it.
