### ISSUE TITLE
Offline Support: Duplicated Pages

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11424]
While offline, publishing a page from Site -> Pages sometimes causes that page to show up twice on the list.

https://d.pr/free/i/DMsMxK

**Comment by yaelirub** [comment]
Hey @diegoreymendez ,
I recommend closing this issue or providing more details.
* I recognize this was created when we started the project

**Comment by diegoreymendez** [comment]
@yaelirub - Let's close for now and we can reopen if it comes up again.
