### ISSUE TITLE
Implement Offline actions - posting/scheduling/deleting while offline

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11425]
## Description:

When attempting to delete a post while offline a “No Connection” alert shows that blocks the UI.

On top of that the post isn't scheduled for deletion at all.

## Decision
![Offline Actions](https://user-images.githubusercontent.com/50576199/60972383-18af5180-a31e-11e9-8dd8-3cc74432bcb9.jpg)

## Matching Android issue:

https://github.com/wordpress-mobile/WordPress-Android/issues/9555

**Comment by yaelirub** [comment]
Looking at the discussion on the Android ticket seems like we should use a snack bar on iOS . too instead of the blocking alert. 

Fo the implementation details, I think we should mark with changes locally and sync once connectivity is back.  Not sure if we can use hasLocalChanges? @jklausa ?

**Comment by diegoreymendez** [comment]
This was marked as low priority for the time being.  I'm removing the assignment for now and we can re-evaluate later.

**Comment by osullivanchris** [comment]
Made a proposal for this on Android https://github.com/wordpress-mobile/WordPress-Android/issues/9558

Following the logic of a few tasks I've been working on. We would tell the user that it _will be_ deleted when connection returns to set the correct expectation. Then make the update when they return online.

**Comment by shiki** [comment]
@diegoreymendez When @malinajirka, @maxme, and I looked at the scope for Offline Publishing, we considered _Deletion while offline_ as out of scope. I think we should do the same for iOS.

**Comment by shiki** [comment]
I'm gathering the status of the Offline Publishing epic for both iOS and Android together in https://github.com/wordpress-mobile/WordPress-iOS/issues/12227. I'll close this for now since it is similar. We can create more specific sub-issues from the epic if we'd like to.
