### ISSUE TITLE
Offline Support: UI Inconsistency when Updating a Post

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11421]
When editing a published post, pressing the Update button (top right) stops you with a HUD that it failed saving (“Error occurred during saving”). However, pressing X (top left) and tapping on “Update Post” in the action sheet seems to save the post.

**Comment by yaelirub** [comment]
**Updating post by tapping "Update" (top right)**:
1. publishPost (PostEditor)
2. uploadPost (PostEditor)
3. uploadPost (PostService)
Which returns an error if the request failed 

**Updating post by closing the editor**
