### ISSUE TITLE
Offline Support: Add Category showing blocking alert.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11431]
Post Settings > Categories > Add Category - typing in a category and pressing save in upper right displays “Error / The internet connection appears to be offline dialog”

**Comment by yaelirub** [comment]
**In case of no connectivity** 
When saving a new category first we check to see if the category already exist using `categoryService findWithBlogObjectID` if it exists and the blog categories are available, we don't show the network alert.
![same_category](https://user-images.githubusercontent.com/1335657/57056501-d0a5eb80-6c57-11e9-8723-f2efbd2d1d7d.gif)

If the category doesn't exist, we attempt to create a new category by calling `categoryService.createCategoryWithName` (which in turn calls `TaxonomyServiceRemote.createCategory`). When this call fails with an error other than 403, we call ` [WPError showXMLRPCErrorAlert:error];` (not sure why it is called like that) that eventually show a generic error.  
![new_category](https://user-images.githubusercontent.com/1335657/57056506-db608080-6c57-11e9-871e-b2ae6e8f05a0.gif)

A few questions for discussion:
1. Should we try and queue the request and retry until success or timeout? (maybe use something like [AlamoFire RequestRetrier](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md#request-retrier) ?

2. Do want to implement some sort of behavior other than failing and notifying the user for this feature?

3. If the answer to 2 is yes, how do we want to notify the user that their request will be executed when regaining connectivity?

4. If the answer to 2 is no, how do we want to notify the user ? Is snack bar applicable here?

@diegoreymendez , @megsfulton

**Comment by megsfulton** [comment]
What I would assume from a user perspective would be that any post settings are saved and stored the same way modifications to post content would be. 

Is it possible to save the new category locally and handle the creation of the category with the post upload?

**Comment by diegoreymendez** [comment]
My initial expectation would be to match what @megsfulton described above.  Let's see what we need to make that happen and if it's possible for us to do so.
