### ISSUE TITLE
Offline Support: Refreshing Loses Featured Images.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11436]
Refreshing the published post list view with featured images. The images are there, then on pull to refresh they go away and are replaced with endless spinners.

**Comment by shiki** [comment]
I cannot reproduce this. @wordpress-mobile/ravenclaw anyone? 🙂

**Comment by diegoreymendez** [comment]
I could reproduce it back at the time @shiki although I haven't tried in a while.  Will check again.

**Comment by diegoreymendez** [comment]
Can be reopened if we manage to reproduce it.
