### ISSUE TITLE
Offline Support: Row showing actionable alert.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11432]
## Description:

1. Go to a post's settings screen.
2. Go offline.
3. Tap on "Tags".

You'll see that there's a row below the input field with the text "Couldn't load tags. Tap to retry".

As the message states, you can tap on that row to try to reload the contents.

This screen should probably both auto-refresh when a connection is detected, and offer a pull-down to refresh option.  This requires design approval though.

## Screenshots:

![rowOfflineMessage](https://user-images.githubusercontent.com/1836005/55912449-14598800-5bb9-11e9-8b65-62ce807096b3.png)

**Comment by shiki** [comment]
My gut feeling is this is out of scope for the Offline Support: Posting project. If not, probably lower in the backlog? The `PostTagPickerViewController` is also missing some stat tracking. We probably want to add that first.

**Comment by diegoreymendez** [comment]
> My gut feeling is this is out of scope for the Offline Support: Posting project. If not, probably lower in the backlog?

I think a lower priority is good for this.

> The PostTagPickerViewController is also missing some stat tracking. We probably want to add that first.

That sounds to me like another issue, and one that's probably not strictly related to offline support.  Thoughts?

**Comment by shiki** [comment]
Re: Stats. It's a separate issue, yes. I was thinking, if we'd like to invest more on this feature, we should add stats too. Especially since they're not that difficult to add. Who knows, maybe no one is using this feature. 🤷‍♂️ That would be nice to know.

**Comment by diegoreymendez** [comment]
> Re: Stats. It's a separate issue, yes. I was thinking, if we'd like to invest more on this feature, we should add stats too. Especially since they're not that difficult to add. Who knows, maybe no one is using this feature. 🤷‍♂️ That would be nice to know.

I'd like to avoid having the issue as part of the project for clarity, but still work on it and deliver as a related item.

Maybe a separate column where we can keep related issues that are not really within the primary scope?

**Comment by yaelirub** [comment]
> Re: Stats. It's a separate issue, yes. I was thinking, if we'd like to invest more on this feature, we should add stats too. Especially since they're not that difficult to add. Who knows, maybe no one is using this feature. 🤷‍♂️ That would be nice to know.

I totally agree! Adding stats is so easy and we can learn so much from it. I wish we could have it be a part of the development process and the definition of done. 

I also think this is low priority but a nice change to have. Your suggestion sounds reasonable and I don't see any difficulties in implementation, @diegoreymendez

**Comment by yaelirub** [comment]
Tap to retry doesn't seem to work. I wonder if we should remove that and just say "Couldn't load tags".

**Comment by diegoreymendez** [comment]
Ping @megsfulton ^

**Comment by megsfulton** [comment]
>Tap to retry doesn't seem to work. I wonder if we should remove that and just say "Couldn't load tags".

That sounds like a good improvement to the experience.
