### ISSUE TITLE
Investigate and fix inaccurate events tracking

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#11446]
These were found during #11395. These events are tracked way too much and warrant an investigation if we are tracking them correctly. 

- `stats_period_accessed`
- `stats_insights_accessed`
- `notifications_accessed`
- `notifications_notification_details_opened`
- `login_accessed`
- `push_notification_alert_tapped`

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Obsolete.
