### ISSUE TITLE
Drag right from anywhere to go back

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#11466]
iOS provides a nice gesture in navigation controllers to drag from the left bezel to “pop” to the previous view controller. 

I’ve noticed that several other apps let you do that from anywhere on the screen, as long as it doesn’t conflict with other gestures. Some of those apps are Slack, Telegram, or Instagram.

I think this feels much more natural specially since the iPhone X* has accustomed us to dragging and flicking things around

**Comment by designsimply** [comment]
I love that feature tons! Definitely gets a personal vote from me. 

To make this issue more actionable, I think a good next step would be to start with a smaller list of important screens where it would be most useful. For me, the two most-useful areas would be Notifications and Comments.
