### ISSUE TITLE
Use Domain Credit

### ISSUE THREAD

**Issue by danielebogo** [wordpress-mobile/WordPress-iOS#11467]
All _WordPress.com plans_ include a custom domain name. This is given to the users as a _domain credit_, which they can redeem against any valid domain.

The image shows the new flow. The Domain Selection and the Register Domain exist within the Site Creation flow and [Automated Transfer flow](https://github.com/wordpress-mobile/WordPress-iOS/issues/9630). After completing the flow the user should be returned to the site dashboard.
![domain_credits_flow-1](https://user-images.githubusercontent.com/912252/56037253-ba76d080-5d26-11e9-800d-355f22c3b16f.png)

cc: @SylvesterWilmott

**Comment by jaclync** [comment]
subtasks:
- [ ] Create feature flag `domainCredit`
- [ ] Add new subsection UI
- [ ] Add congrats screen UI
- [ ] Add logic that determines whether domain credit can be redeemed + testing
- [ ] Integrate the whole domain registration flow + testing
- [ ] Analytics
