### ISSUE TITLE
[Stats Refresh] Latest Post Summary: rows duplicated after refresh

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#11474]
On Insights, after pull to refresh or scrolling down then back up, the data rows on the Latest Post Summary card are duplicated. And are repeated with every refresh/scroll.

Initial view:
<img width="350" alt="lps_init" src="https://user-images.githubusercontent.com/1816888/56165145-70dcee80-5f8f-11e9-8723-58973e5951b5.png">

After 2 refreshes:
<img width="350" alt="lps_refreshed" src="https://user-images.githubusercontent.com/1816888/56165212-9ff36000-5f8f-11e9-854b-7dfe9234e246.png">

**Comment by ScoutHarris** [comment]
@jklausa , @stevebaranski - maybe one of you knows off-hand what changed recently that may have caused this? If not, I'll take a look when I get a chance.

**Comment by ScoutHarris** [comment]
Hey @jklausa . This looks like it might be related to https://github.com/wordpress-mobile/WordPress-iOS/pull/11465. Thoughts?

**Comment by jklausa** [comment]
Took a quick peek today and came up with a fix :)
