### ISSUE TITLE
Zendesk: Use non-deprecated API

### ISSUE THREAD

**Issue by jtreanor** [wordpress-mobile/WordPress-iOS#11477]
In order to update the project to use Xcode 10.2 (https://github.com/wordpress-mobile/WordPress-iOS/pull/11381), we were required to update Zendesk to 2.3.1. Unfortunately, this means the API we use to configure Zendesk is now deprecated.

I briefly looked at changing it myself but decided against making sweeping changes without full context. I have tested the SDK in the app and it is still working fine. We should update to the new API as soon as possible.

### Actual behavior

Here are the warnings in `ZendeskUtils`:

![image](https://user-images.githubusercontent.com/1773641/56203870-046cf880-603e-11e9-9842-0f19072fcb2d.png)

### Steps to reproduce the behavior

Build `develop` with Xcode 10.2. You will see the new deprecation warnings.

**Comment by ScoutHarris** [comment]
Hey @jtreanor . What was your plan for this? If you would like a dev to look at it, I can add it to my to-do list during HACK week.

**Comment by jtreanor** [comment]
if you could add it to your list for that, it would be perfect! Thanks @ScoutHarris!

**Comment by ScoutHarris** [comment]
You bet. I'll see what I can do.
