### ISSUE TITLE
Sign Up VoiceOver: bottom sheet should not interfere with the sign up buttons overlay

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11488]
Steps to reproduce:

1. Log out of the WPiOS app.
1. Go to Settings > General > Accessibility > VoiceOver and toggle the setting on.
1. Go to WPiOS and double tap the "Sign up for WordPress.com" button.
1. Tap then double tap the hidden view on the bottom sheet (the top of the screen).
1. VoiceOver says, "Button – possible text. Sign up with email, sign up with google”.
1. Double tapping anywhere on the top part of the screen closes the bottom sheet.

Result: I expected to just have the two buttons accessible when viewing the sign up screen without the grayed out bottom sheet tappable in the background. ([17s](https://cloudup.com/c_RhOU48Wg0))

<img src="https://user-images.githubusercontent.com/1119271/56324399-f4cbdd80-612b-11e9-846e-09ff30bd8200.png" width="270" alt="wpios-sign-up-screen">
<p style="clear:both;"><sup>Tested with WP Internal 12.2.0.20190412 on iPhone 6S iOS 12.2.</sup></p>

<p style="clear:both;"><sub>(internal reference: p77Llu-bQ6-p2 h/t @etoledom)</sub></p>

**Comment by stevebaranski** [comment]
This will require a change to `WordPressAuthenticator` to resolve.

It appears that the "Button" being read first by VoiceOver is a subview of `LoginPrologueSignupMethodViewController`'s root view. Looking at [the storyboard](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/blob/ceaffe8664072df3c058c11ea4b92c92102ba5ab/WordPressAuthenticator/Signin/Login.storyboard), that button spans the entire view and dismisses sign-up.

A couple of potential solutions come to mind:

1. Change the `accessibilityLabel` of this button to indicate that tapping here will cancel the sign-up attempt, returning to the preceding view controller (`LoginPrologueViewController`, with "Login" & "Signup" buttons).
1. Modifying this `NUXButtonViewController` to expose an explicit Cancel button that is also accessible. 

Option 1 is probably the most straightforward. 

Option 2 might be more user-friendly, but requires a bit more effort. I believe _Cancel_ buttons are typically assigned the `tertiary` position in a `NUXButtonViewController` instance. Unfortunately, however, the _Terms of Service_ quasi-label is actually a button and is itself [manually installed](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/blob/dec4d5f4905a5e9c713172a7e0e177c86d2bc099/WordPressAuthenticator/Signin/LoginPrologueSignupMethodViewController.swift#L70) into the stack view. That is to say, the `NUXButtonViewController` will essentially need to manage four buttons.

**Comment by shiki** [comment]
The transparent layer on top of the dialog is the Dismiss button and is one of the ways to dismiss the dialog. Along with other improvements (https://github.com/wordpress-mobile/WordPress-iOS/issues/13062), I changed it to say “Dismiss” in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/166.
