### ISSUE TITLE
Tables show empty the first time

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#1148]
When you sign in the first time, you'd likely find every view in the app empty.

Example:
1. Sign out if necessary and relaunch the app
2. Login
3. I land in a blank "Blogs I follow" screen. A few seconds later content appears. No indication of anything happening other than the network indicator in the status bar.
4. Switch to notifications: "No notifications yet". But they appear after a couple seconds
5. Me > Blog > Posts: "You haven't created any posts yet..." Yet there they are a few seconds later
6. Try pages, comments, other blogs,...

There are different issues here:
- [ ] We should preload more content the moment you sign in: Blogs I follow, Notifications, and data from your primary blog
- [x] It should be more obvious when tables are loading data
- [ ] The "no content" messages should never be displayed until we have asked the server for the data and confirmed there's actually no content to display. I can imagine someone freaking out on a slow connection "What do you mean I haven't created any posts?"

**Comment by koke** [comment]
We have loading screens for most things now, but the other problems persist.

**Comment by nheagy** [comment]
@koke can you comment on whether there are still valid concerns here?

Wondering if I can either close this issue or break out specific problems for the no-dead-ends work.

**Comment by koke** [comment]
I don't care about preloading, but the no content message is something I've seen recently. Feel free to reorganize this into other issues for no-dead-ends.

**Comment by yaelirub** [comment]
As there are on going projects to improve sign in, app navigation and landing after onboarding I'm going to close this issue. Please feel free to open one in the future if you feel like this still needs attention
