### ISSUE TITLE
Create Site VoiceOver: none of the types of sites are readable by VoiceOver so this screen is unusable

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11480]
Steps to reproduce:

1. Log out of the WPiOS app.
1. Go to Settings > General > Accessibility > VoiceOver and toggle the setting on.
1. Go to WPiOS and double tap the "Sign up for WordPress.com" button.
1. Follow the prompts until you reach the Create Site screen.
1. Try to select any of the options (Blog, Business, Professional, Education, Blank Canvas).

Result: nothing on the first Create Site screen is announced and is therefore unusable by someone without sight. ([23s](https://cloudup.com/cCr9Zu394Js))

<img src="https://user-images.githubusercontent.com/1119271/56249883-ae627a00-606a-11e9-861b-ec734c3a5bd3.png" width="270" alt="wpios-voiceover-first-create-site-screen-is-not-accessible">
<p style="clear:both;"><sup>Tested with WP Internal 12.2.0.20190412 on iPhone 6S iOS 12.2.</sup></p>

<p style="clear:both;"><sub>(internal reference: p77Llu-bQ6-p2 h/t @etoledom)</sub></p>

**Comment by diegoreymendez** [comment]
@stevebaranski - I've removed my assignment for now, since you already had this one, but let me know if I can assist.

**Comment by stevebaranski** [comment]
You bet @diegoreymendez - I feel strongly that this is a regression rather than an omission. In any case, I agreed to work on a11y issues next week, and want to be accountable for tidying it up.

**Comment by diegoreymendez** [comment]
Yes, let's make sure it's in shape.  Again, ping me for anything you need - even if it's just taking over.
