### ISSUE TITLE
Quick Start v2 VoiceOver: highlighted cell (with that nice dot) is completely missed by VoiceOver

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11494]
Steps to reproduce:

1. Go to Settings > General > Accessibility > VoiceOver and toggle the setting on.
1. If you already have a site with Quick Start setup, go to that site, double tap on "Customize Your Site", and skip to step 7.
1. Log out of the WPiOS app.
1. Go to WPiOS and double tap the "Sign up for WordPress.com" button.
1. Follow the prompts until you reach "Want a little help getting started?"
1. Double tap the "Yes, Help Me" button.
1. Double tap the "Upload a site icon" cell.
1. Look for the pulsing dot indicator. Does VoiceOver acknowledge it?

Result: the highlighted cell (with that nice dot) is completely missed by VoiceOver. It could communicate that the highlighted cell was found. ([6s](url))

<img src="https://user-images.githubusercontent.com/1119271/56328355-d1a92a00-613b-11e9-8f88-dc3024eb6e2b.png" width="270" alt="pulsing-dot">
<p style="clear:both;"><sup>Tested with WP Internal 12.2.0.20190412 on iPhone 6S iOS 12.2.</sup></p>

<p style="clear:both;"><sub>(internal reference: p77Llu-bQ6-p2 h/t @etoledom)</sub></p>

**Comment by mindgraffiti** [comment]
This issue is still valid. It has been noted in ref. pbArwn-Cx-p2.

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
