### ISSUE TITLE
"e>e>" strings appears in the editor after Updating the post

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-iOS#11515]
### Expected behavior
Updating a post should keep the post content in the editor untouched.

### Actual behavior
There's a `e>e>` string added to the post in the editor each time the post is pushed/Updated to the server.

![AztecBug](https://user-images.githubusercontent.com/1032913/56536228-2e567b80-6566-11e9-8ca2-bdbdf78d10b5.gif)

### Steps to reproduce the behavior

1. Open the post that gets created automatically after creating a new site on wordpress.com
2. Notice that the "Update" button is enabled/available to tap
3. Hit the "Update" button
4. After the update finishes, notice that a `e>e>` string is inserted in the editor

Example (HTML) content that seems to trigger the issue:
```html
Thanks for joining me!
<blockquote>Good company in a journey makes the way seem shorter. — Izaak Walton</blockquote>
<img class="size-full wp-image-7" src="https://twentysixteendemo.files.wordpress.com/2015/11/post.png" alt="post" width="1000" height="563" />
```

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 6s, iOS 12.2, WPiOS v12.1.3 DEV (at hash dd99d3e0c1 on `develop`)

First reported and gif'd by @elibud in Slack.

**Comment by elibud** [comment]
This one is pretty bad, we should at least target the frozen bunch if not hot fix when we sort it out.

**Comment by elibud** [comment]
This one is good to close, right?

**Comment by etoledom** [comment]
Right! Fixed via https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1178
Added to WPiOS on https://github.com/wordpress-mobile/WordPress-iOS/pull/11529
