### ISSUE TITLE
Login: Can't add current/former Jetpack site to app as self-hosted site after logging in to WordPress.com

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#11526]
### Expected behavior

I expect to be able to add any self-hosted site to the app (that meets the app requirements) regardless of whether or not I am logged in to a WordPress.com account. Even if the site used Jetpack in the past or currently uses Jetpack, I expect to be able to log in to the app and use it without Jetpack features.

### Actual behavior

If I am logged in to a WordPress.com account, I can't add a self-hosted site that used to be connected to Jetpack or is currently connected to a different WordPress.com account. When I try, I get this message:

> Please log out before connecting to a different wordpress.com site

I confirmed that if I log in to the self-hosted site _first_, and then log in to my WordPress.com account, it works. It seems like whatever check is happening in the app is seeing the Jetpack connection for the self-hosted site and blocking my login attempt.

### Steps to reproduce the behavior

On the web:
1. Set up a self-hosted site.
2. Install Jetpack and connect it to WordPress.com.
3. Disconnect Jetpack from WordPress.com.

In the app:
1. Log in to WordPress.com.
2. Go to My Sites and try to add the self-hosted site. Result: Error as described above.
3. Log out of WordPress.com.
4. Add the self-hosted site to the app.
5. Log in to WordPress.com. Result: You are logged in to both the self-hosted site and your WordPress.com account.

You can also try the same steps in the app with a site that currently has Jetpack connected to a different WordPress.com account, and see the same results.

##### Tested on [iPhone XS], iOS [12.2], WPiOS [12.2.0.20190412]

cc @yaelirub

**Comment by designsimply** [comment]
Possibly related: https://github.com/wordpress-mobile/WordPress-iOS/issues/11505#issuecomment-485567523 cc @diegoreymendez

**Comment by darnelldibbles** [comment]
Another related issue reported here: https://en.forums.wordpress.com/topic/please-check-your-primary-sites-jetpack-connection-3/?view=all#post-3314109

**Comment by yaelirub** [comment]
An attempt to fix was PRed: https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/98

**Comment by mindgraffiti** [comment]
Can confirm, bug was reproducible and was fixed in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/98. Closing this issue.

**Comment by rubelmusicwould8374** [comment]
`<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/300x250-popads_1.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/300x250-propellerads-monetize-traffic.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/300x250_06.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/300x250_03.jpg" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/300x250_02.jpg" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/300x250_01.jpg" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/300x250_05.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/300x250_04.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/250x250_02.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/250x250_01.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/728x90-popads_1.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/728x90-propellerads-monetize-traffic.gif" alt="PropellerAds"></a>
<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/728x90_07.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/728x90_04.jpg" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/728x90_03.jpg" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/728x90_02.jpg" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/728x90_01.jpg" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/728x90_06.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/728x90_05.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/468x60-popads_1.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/468x60-propellerads-monetize-traffic.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/468x60_04.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/468x60_03.jpg" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/468x60_02.jpg" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/468x60_01.jpg" alt="PropellerAds"></a>


<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/160x600-popads_1.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/160x600-propellerads-monetize-traffic.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/160x600_04.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/160x600_03.jpg" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/160x600_02.jpg" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/160x600_01.jpg" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/120x600-propellerads-monetize-traffic.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/120x600_03.gif" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/120x600_02.jpg" alt="PropellerAds"></a>

<a href="https://publishers.propellerads.com/#/pub/auth/signUp?ref_id=Zadk"><img src="http://promo.propellerads.com/120x600_01.jpg" alt="PropellerAds"></a>


<script type="text/javascript" src="https://g.Cash-ADS.com/banner.php?uid=1585&e=0&p=0&s=0&size=1"></script>

<script type="text/javascript" src="https://g.Cash-ADS.com/banner.php?uid=1585&e=0&p=0&s=0&size=2"></script>

<script type="text/javascript" src="https://g.Cash-ADS.com/banner.php?uid=1585&e=0&p=0&s=0&size=3"></script>

<script type="text/javascript" src="https://g.Cash-ADS.com/banner.php?uid=1585&e=0&p=0&s=0&size=4"></script>

<script type="text/javascript" src="https://g.Cash-ADS.com/layer.php?uid=1585&e=0&p=0&s=0"></script>

<script type="text/javascript" src="https://g.Cash-ADS.com/counter.php?uid=1585&e=0&p=0&s=0"></script>

<a href="https://www.traffboost.net?ref=198830" target="_blank"
title="TraffBoost - Bring real visitor to your site">
<img title="TraffBoost.NET" alt="TraffBoost.NET" class="img-rounded" 
src="https://www.traffboost.net/images/traffboost-banner620x90.jpg" />
</a>

<a href="https://www.traffboost.net?ref=198830" target="_blank"
title="TraffBoost - Bring real visitor to your site">
<img title="TraffBoost.NET" alt="TraffBoost.NET" class="img-rounded" 
src="https://www.traffboost.net/images/traffboost-banner620x90-vi.jpg" />
</a>

<a href="https://www.traffboost.net?ref=198830" target="_blank"
title="TraffBoost - Bring real visitor to your site">
<img title="TraffBoost.NET" alt="TraffBoost.NET" class="img-rounded" 
src="https://www.traffboost.net/images/traffboost-banner300x250.jpg" />
</a>

<a href="https://www.traffboost.net?ref=198830" target="_blank"
title="TraffBoost - Bring real visitor to your site">
<img title="TraffBoost.NET" alt="TraffBoost.NET" class="img-rounded" 
src="https://www.traffboost.net/images/traffboost-banner120x600.jpg" />
</a>

<script src="https://cdn.onesignal.com/sdks/OneSignalSDK.js" async=""></script>
<script>
var OneSignal = window.OneSignal || [];
OneSignal.push(function() {
OneSignal.init({
appId: "ebcb29b1-0a00-4bb3-8591-135bc8a6ab8d",
});
});
</script>

<script data-cfasync="false" src="//ds88pc0kw6cvc.cloudfront.net/?kcpsd=845872"></script>`
