### ISSUE TITLE
The copy when installing Jetpack is confusing

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#11525]
### Expected behavior
I expect to understand what I am doing on each Jetpack installation step.

### Actual behavior
After a Jetpack install is completed I get this screen:

![JetpackSetup-1](https://user-images.githubusercontent.com/5558824/56584093-63d48680-65b1-11e9-8339-5a0014c19bb1.png)

And if I tap Continue I land on this one:

![JetpackSetup-99](https://user-images.githubusercontent.com/5558824/56584104-6931d100-65b1-11e9-9d8b-ec05aeae9f58.png)

Which is confusing, since I thought I was done with the Jetpack Setup. @planarvoid how does this look in Android?

@danielebogo  @SylvesterWilmott  can we look into updating the copy so this is less confusing?

### Steps to reproduce the behavior
Trigger a Jetpack install on a self-hosted stie.

**Comment by planarvoid** [comment]
hey @elibud @danielebogo 👋 , this is what it looks like on Android

![Screenshot_1556029672](https://user-images.githubusercontent.com/1079756/56589049-cd21bd00-65e4-11e9-90f0-674d30c00fd0.png)

**Comment by danielebogo** [comment]
Thanks @planarvoid ! @elibud @SylvesterWilmott  can we use this copy?

**Comment by elibud** [comment]
I don't think so, I think we need to be explicit that this is one step, and there's still one remaining one, to manage user expectations, something like:

> Now that Jetpack is installed, let’s set it up, it will only take one minute.

Or something among those lines.

**Comment by planarvoid** [comment]
Let me know what you pick and I can implement it on Android @danielebogo

**Comment by SylvesterWilmott** [comment]
Thanks for the suggestion @elibud 

Minor change just to communicate that the set up is a requirement

Title: `Jetpack installed`
Body: `Now that Jetpack is installed, we just need to get you set up, this will only take a minute`
Button: `Set up Jetpack`

**Comment by danielebogo** [comment]
@elibud @SylvesterWilmott 

![Simulator Screen Shot - iPhone X - 2019-04-24 at 13 59 13](https://user-images.githubusercontent.com/912252/56661229-37943500-6699-11e9-9e1e-f99172a56374.png)

**Comment by planarvoid** [comment]
This PR updates the strings on Android - https://github.com/wordpress-mobile/WordPress-Android/pull/9716
