### ISSUE TITLE
Notifications list inline alerts animation is wonky

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#11531]
When one of the inline alerts on the notifications screen appears (prime for push, app review prompt) the appearance animation is really weird:

![notifications_alert_animation_bug](https://user-images.githubusercontent.com/517257/56617895-e8d19700-65d5-11e9-8308-e06188422e5f.gif)

It used to be much nicer. My _guess_ is this was introduced when the filter bar was added (which I reviewed and approved) but I haven't been able to nail down the commit that changed it. @shiki has also made some changes in this file recently.

So @etoledom or @shiki if one of you get a chance to look at this, that'd be great 🤞

**Comment by kean** [comment]
Closing as obsolete.
