### ISSUE TITLE
Site Creation: Space in the title/tagline doesn't appear until you type the next letter

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#11555]
### Expected behavior

When I enter a site title or tagline, I expect to be able to enter spaces and have them appear as I type.

### Actual behavior

A beta tester observed that typing a space doesn’t show the space character until you type the next letter. This made the tester initially assume they couldn’t have spaces in the site title.

### Steps to reproduce the behavior

1. Go to My Sites in the app and create a new WordPress.com site.
2. Follow the prompts to the "Basic information" (Site Title/Tagline) screen.
3. Enter a site title with spaces in it. Result: The spaces don't appear on screen until the next letter is typed.

**Comment by richardmtl** [comment]
I was coming here to report the same thing; you beat me to it, Rachel!

**Comment by marosios** [comment]
Hey! Can I try to fix this issue and contribute to the project? It's my first issue. Thank you all!

**Comment by elibud** [comment]
Yes of course, go ahead @marosios! Feel free to ping me on your PR once it's up and I'll make sure it gets reviewed.

**Comment by marosios** [comment]
Hey @elibud! My PR is created #12564. Is it okay like that or should I edit something? It's my first PR so I am sorry for the mistakes :/.

**Comment by elibud** [comment]
We'll review it in the next couple of days and we'll let you know, thanks for the ping!
