### ISSUE TITLE
Update the mobile blog link in Me > App Settings > About

### ISSUE THREAD

**Issue by megsfulton** [wordpress-mobile/WordPress-iOS#11587]
In Me > App Settings > About, the "Blog" menu item opens up a URL for a retired mobile blog. 

![IMG_3593](https://user-images.githubusercontent.com/161697/56925561-989a7f00-6a84-11e9-86fc-90bb1a0067aa.PNG)

The link should be updated to go to the WordPress.com Blog and the URL changed in the table cell. 

![About - Blog](https://user-images.githubusercontent.com/161697/56925838-2d9d7800-6a85-11e9-9a86-22bed4b32dba.png)

**Comment by DrBeta** [comment]
Sure! On it!
