### ISSUE TITLE
Login: "Log in with Google" option shows the login prompt a 2nd time after completing that screen and selecting a Google account

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11604]
Noting this as a point of confusion, found during 12.3 beta testing. 

1. Log out.
1. Tap "Log In".
1. Tap "Log in with Google".
1. Tap "Continue".
1. Choose a Google account (or add one).

**Result:** the log in prompt appears again after selecting a Google account, even though there's a spinner at bottom right it's a little confusing to see the log in prompt at that point. ([30s](https://cloudup.com/cRGYXpxTX02))

<img src="https://user-images.githubusercontent.com/1119271/57043793-d1258e80-6c25-11e9-94b1-ac5c38edf0ce.png" width="200" alt="choose-an-account"> &nbsp; <img src="https://user-images.githubusercontent.com/1119271/57344514-caef5080-7104-11e9-9e67-7c0a97cabc14.png" width="200" alt="log-in-prompt-again"> &nbsp; <img src="https://user-images.githubusercontent.com/1119271/57044098-a1c35180-6c26-11e9-9dbc-c508f79cb119.png" width="200" alt="log-in-prompt-with-spinner-highlighted">
<p style="clear:both;"><sub>Tested with WP Internal 12.3.0.20190422 on iPhone 6S iOS 12.2.</sub></p>

**Comment by designsimply** [comment]
This came up again for me in 12.4 beta testing. 😆 ([46s](https://cloudup.com/cBvWn2F7HPW))

**Comment by ScoutHarris** [comment]
[Inquired](https://wp.me/pbArwn-mA/#comment-636) about addressing this in the Unified Auth project.

**Comment by ScoutHarris** [comment]
Hey @designsimply . 

Per the linked P2 discussion, we'll address this in the Unified Auth project.

**Comment by mindgraffiti** [comment]
This one can be marked as fixed once Unified Google has been enabled. Here is the new screen used for logging in / signing up with Google:

<a href="https://user-images.githubusercontent.com/1062444/88933992-b5080700-d245-11ea-83d5-e9ac30840b76.png"><img src="https://user-images.githubusercontent.com/1062444/88933992-b5080700-d245-11ea-83d5-e9ac30840b76.png" width="350" /></a>

**Comment by ScoutHarris** [comment]
Ref https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/282.

**Comment by mindgraffiti** [comment]
Fixed in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/387
