### ISSUE TITLE
Login: Can't log in to self-hosted sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#11617]
### Expected behavior

I expect to be able to use the site address option to log in to self-hosted WordPress sites using my site's domain, without entering any prefix (e.g. `https://`).

### Actual behavior

On the `develop` branch I can't log in to my self-hosted sites without entering the `https://` prefix to my site URL.

After entering my username/password, I get this error:

> Unable to read the WordPress site at that URL. Tap 'Need Help?' to view the FAQ.

I confirmed that I can log in to the same self-hosted sites using the site address login without any prefix in the 12.3 release branch, so this is a new issue. @diegoreymendez looks like this may be related to the URL validation changes you made in https://github.com/wordpress-mobile/WordPress-iOS/pull/11563?

### Steps to reproduce the behavior

1. Make sure you're on the `develop` branch.
2. From the login screen, select the site address login option.
3. Enter your site address with no prefix (e.g. `example.com`).
4. Enter your username and password. Result: The error described above appears.
5. Go back and add a prefix to your site address (e.g. `https://example.com`).
6. Enter your username and password. Result: You can continue logging in.

### Screenshot

![Simulator Screen Shot - iPhone Xs - 2019-05-02 at 17 56 29](https://user-images.githubusercontent.com/8658164/57093749-9e9f9280-6d06-11e9-9e0d-b21f6da96c1f.png)

**Comment by diegoreymendez** [comment]
Most likely @rachelmcr.  I'm on it.
