### ISSUE TITLE
Reader: Gap marker can appear above the last post in a batch.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#11631]
I noticed that the gap marker can sometimes appear above the last post in the most recently fetched batch.  Note how the gap marker is between posts 38 and 37 in the example below.  It should follow post 37.

<img width="372" alt="Screen Shot 2019-05-03 at 2 22 00 PM" src="https://user-images.githubusercontent.com/1435271/57160622-ea0d7b80-6dae-11e9-986b-47e848ae4b33.png">

From a quick test it looks like the reason is the value of `sortRank` is being rounded to an integer rather than respecting a fractional value.   This can lead to the gap marker and the last post in a batch having the same sort rank.  Then its a 50/50 chance which order the two will be returned by core data.

We could probably resolve the issue by just relying on integers (adjusting the sortDate by a single second rather than a single millisecond, and similar for sortRank).

**Comment by peterszeles** [comment]
Hello, Can I contribute this issue?
