### ISSUE TITLE
Media Library and picker do not load on sites using several GB of media storage

### ISSUE THREAD

**Issue by rfaile313** [wordpress-mobile/WordPress-iOS#11644]
* UserReport

Possibly related lines from the app logs sent in by the user:

```
256 2019-05-06 06:54:13:539 🔵 Tracked: application_low_memory_warning 
732 2019-05-06 17:57:14:186 🔵 Tracked: app_settings_opened
733 2019-05-06 17:57:16:207 Media: removed 99 file(s) during cleanup.
```

Ticket: 2009516-zen (more detailed app logs are included in the ticket)

### Expected behavior

Sites should load images in the **media library** pretty quickly, I wasn't able to reproduce this on my iPhone X with the latest version of iOS and WP app, neither was Sheri on her iPhone 6s

### Actual behavior

Media Library takes about 6 minutes or more to load. There are lots of errors in the logs. 

### Steps to reproduce the behavior

- User has an iPhone 6 Plus (WCDMA) iPhone7,1 N56AP iOS 12.2 Build Version 16e227 
- Device Storage 41GB of 64GB used

1) Have a WordPress.com site with a lot of media (the user's site is using 63% of 13GB) 
2) Head to the media library

**Comment by designsimply** [comment]
I noticed the app logs had a `application_low_memory_warning` and only one mention of `Media` at all:

```
256 2019-05-06 06:54:13:539 🔵 Tracked: application_low_memory_warning 
732 2019-05-06 17:57:14:186 🔵 Tracked: app_settings_opened
733 2019-05-06 17:57:16:207 Media: removed 99 file(s) during cleanup.
```

Noteworthy quotes from the user:

> after a logoff from the APP and login again them switch to Media tab which is as expected empty. 
> It takes 6 minutes to refresh and show the first pictures

<blockquote>I did delete the app. 
I rebooted my iPhone 📱 6Plus 
I reinstalled the App 
Logging in to WP 
Press Media and waited 2Min 40sec
</blockquote>

> I tried it with only word press open it doesn’t make a big difference.

I tested the following steps on my iPhone 6S iOS 12.2 using WP Internal 12.5.0.20190520 (12.5 beta) and found that it took a long time (not as long as 6 or 1.5 minutes but still long) for the Media to open on a blog currently using 8.2 GB out of 213.0 GB upload limit (4%). 

Steps to reproduce:

1. Log out.
1. Log in.
1. Go to My Sites and select a blog using several GB of media storage.
1. Time how long it takes to see images.

<strong>Result:</strong> in my case, it took about 38 seconds for images to show up after tapping "Media". ([1m9s](https://cloudup.com/cTLoafW-2at))

I also noticed a flash of the "You don't have any media" screen which the user mentioned—it only appears for a moment:

<img src="https://user-images.githubusercontent.com/1119271/58285544-2b6bc800-7d6a-11e9-89e5-f55162cd97de.png" width="270" alt="you-dont-have-any-meda">
<sup>Tested with WP Internal 12.5.0.20190520 on iPhone 6S iOS 12.2 on `cute.wordpress.com` WordPress.com site with Premium Plan.</sup>

**Comment by designsimply** [comment]
I re-tested using WPiOS 12.8.1 (app store version) on iPhone 6S iOS 12.3.1 and confirmed the Media Library takes quite a long time to load for a site using several GB of storage space. For a site I manage which is using 8.5 GB out of a 213.0 GB upload limit, it took 43s for the page to load after tapping "Media" on the My Site screen and 40s for media to load after tapping the Media Library (WordPress) icon from within the Aztec editor from a fairly fast internet connection speed of [260Mbps](https://user-images.githubusercontent.com/1119271/61670448-eba95a00-aca0-11e9-9fa8-f88e78e56427.PNG). ([1m2s](https://cloudup.com/c4fsFRqkDXl), [1m30s](https://cloudup.com/clGCfeUD5VX))

<sup>(related internal reference: 2175895-zen and p4a5px-2q1-p2) cc @thehenrybyrd @diegoreymendez</sup>

**Comment by designsimply** [comment]
Noting this issue was reported (and re-reported) in a mobile request and Eli mentioned we should prioritize it since the Media Library is one of the core features for the apps. @diegoreymendez can we move this out of Groundskeeping and into a User Expectations queue as a small project?

**Comment by designsimply** [comment]
Noting the report from p4a5px-2q1-p2 and 2175895-zen with follow-up in 2239045-zen:

> I’m getting frustrated with iOS app. It won’t load my media library 😔
> 
> It just says loading media when I click media library and it’s been like that for an hour or so. I’m guessing there must be a limit on the server.
> 
> I uploaded image but it shows in media library but not when I choose to use an image from media library in post.
> 
> None of my media is showing on your side of things and the logs don’t seem to be screaming error. It’s frustrating

In this case, they currently are using 13.5GB of storage on a WordPress.com Business Plan/WordAds site and are able to see media and upload images there but the app times out when they try to access the media picker via Aztec (tracked in the `media_picker_button_tapped` stat).

**Comment by charliescheer** [comment]
Similar problem in 2213729-zen
User is only using 1.2 gig of storage, but has 17000 images in their library 
There are a few sets of logs in that ticket, not very much information in them though.
