### ISSUE TITLE
Stats: Days/Weeks/Months/Years graphs look the same on every screen

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11651]
I had some trouble viewing any graphs in the Stats section while testing 12.4 beta.

Steps to reproduce:

1. Go to Stats.
1. Browse the Days, Weeks, Months, Years sections.
1. Switch to a different site.
1. Browse the Days, Weeks, Months, Years sections.
1. Log out and log in as a different user and go to a different site.
1. Browse the Days, Weeks, Months, Years sections.

<strong>Result:</strong> the graphs look exactly the same in different sites and tapping on the bars doesn't pull up the correct data. Insights screen looks to be working normally. ([5m9s](https://cloudup.com/cmIg5erE4dD))

<img src="https://user-images.githubusercontent.com/1119271/57345791-74d0dc00-7109-11e9-8951-fbb2d2fc40b0.png" width="270" alt="stats-graphs-data-is-the-same-everywhere"> &nbsp; <img src="https://user-images.githubusercontent.com/1119271/57345930-ec9f0680-7109-11e9-9e9d-daff9d43b5c5.png" width="270" alt="imagine-a-pretty-map-here">
<p style="clear:both;"><sub>Tested with WP Internal 12.4.0.20190505 on iPhone 6S iOS 12.2 logged in as `user0313` then `design5279` and tested several different blogs and site types.</sub></p>

**Comment by ScoutHarris** [comment]
Hey @designsimply . Stats Refresh was enabled for internal testing, but it should have been reverted. @jkmassel did https://github.com/wordpress-mobile/WordPress-iOS/pull/11648 make it into a 12.4 release?

**Comment by rachelmcr** [comment]
I installed the latest internal beta release (from HockeyApp - the second 12.4.0.20190506 release) and confirmed Stats Refresh is disabled there.

**Comment by designsimply** [comment]
Looping back to note the 2nd 12.4.0.20190506 release worked for me as well!
