### ISSUE TITLE
[Stats Refresh] investigate Period summary fetch time

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#11657]
As discovered on https://github.com/wordpress-mobile/WordPress-iOS/pull/11342, and discussed on https://github.com/wordpress-mobile/WordPress-iOS/pull/11485#issuecomment-484460569, the Period summary endpoint `sites/stats/visits` can take a long time to return, especially for longer periods.

@jmdodd  provided some valuable information regarding this endpoint.

Backstory: 
First, it was _much_ worse. Jennifer actually was able to cut the fetch time in half back in September: https://mc.a8c.com/grafana/d/000000032/rest-api-calypso?orgId=1&fullscreen&panelId=5&from=now-1y%2Fy&to=now-1y%2Fy. The accompanying post-mortem: https://webperfa8c.wordpress.com/2018/09/05/stats-performance-optimizations-summary/.

However, the root problem remains. That is, each day of visits is stored in a separate table. "So for a site which is 2 months old, we query 60 different tables and assemble the data for the `/stats/visits` endpoint results. For a site which is 6 years old... :grimacing:"

Jennifer suggested two things we could possibly do to increase performance:
1. Use less parameters, specifically `stat_fields=views%2Cvisitors%2Clikes%2Ccomments`. The API finds all the data anyway, and then has to filter it to return only the items specified. What we probably should do is don’t specify those fields, get all the data, and parse it accordingly.

To note, old Stats `WPStatsServiceRemote.m` appears to do do just that, only passing the parameters `quantity`, `unit`, and `date`, and then parses the response. And is noticeably faster.

2. Doing an API request that only asks for the last X days of data.

(She did also suggest caching, but @jklausa 's got that covered. 🎉 )

(cc @0nko @planarvoid in case they have a similar experience)

**Comment by stevebaranski** [comment]
I wanted to share some additional detail; I hope that it's helpful. In my testing, I occasionally see an empty Chart like the one below.

![11657](https://user-images.githubusercontent.com/221062/57650767-63ac2300-7580-11e9-9228-a9eeab63e7e8.png)

Upon inspection, `StatsSummaryTimeIntervalData` is `nil`. I believe this is populated by the aforementioned endpoint.

In any case, when this happens, I've noted the following errors for a number of different requests in the console. Each has a similar disposition.

```
2019-05-13 12:53:57.511014-0700 WordPress[79004:3629132] Task <DAFFF113-E125-48BA-AC03-FE7D46CB3E70>.<1> load failed with error Error Domain=NSURLErrorDomain Code=-999 "cancelled" UserInfo={NSErrorFailingURLStringKey=https://public-api.wordpress.com/rest/v1.1/sites/3584907/stats/visits/?locale=en&date=2019-05-13&max=10&period=week&quantity=10&stat_fields=views%2Cvisitors%2Clikes%2Ccomments&unit=week, NSErrorFailingURLKey=https://public-api.wordpress.com/rest/v1.1/sites/3584907/stats/visits/?locale=en&date=2019-05-13&max=10&period=week&quantity=10&stat_fields=views%2Cvisitors%2Clikes%2Ccomments&unit=week, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <DAFFF113-E125-48BA-AC03-FE7D46CB3E70>.<1>"
), _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <DAFFF113-E125-48BA-AC03-FE7D46CB3E70>.<1>, NSLocalizedDescription=cancelled} [-999]
...
2019-05-13 12:53:57.512349-0700 WordPress[79004:3629144] Task <DAFFF113-E125-48BA-AC03-FE7D46CB3E70>.<1> finished with error - code: -999
```
