### ISSUE TITLE
Define a user-facing vocabulary for post status, user and app initiated actions

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#11676]
As we have defined a vocabulary for internal reference we also need to define a user-facing vocabulary that will clearly communicate the different states of a post and the actions made on it to the user.

This issue is not iOS specific and applies to Android as well.

**Comment by designsimply** [comment]
Are you talking about things like local versus remote drafts?

**Comment by yaelirub** [comment]
@designsimply , yes, that's one example.

**Comment by diegoreymendez** [comment]
For context: this is something @yaelirub and I discussed a while back.

That said, I'd wait for this to become necessary naturally, before doing any work, or even having an issue for it.  My opinion is that we can close this for now.
