### ISSUE TITLE
Site Creation: "Upload a site icon" tutorial step not clear.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11687]
## Description:

The step that explains to the user how to "Upload a site icon" is not explaining clearly to the user what needs to be tapped.

## Images:

This is how it looks in iOS:

![IMG_9C9240FED0E9-1](https://user-images.githubusercontent.com/1836005/57663364-1785d080-75ca-11e9-90b0-f24672916fb9.jpeg)

This is how it looks in Android (notice the blue dot showing where to tap):

![Screenshot_20190513-213714](https://user-images.githubusercontent.com/1836005/57663402-31271800-75ca-11e9-978c-2778bc27295d.png)

**Comment by diegoreymendez** [comment]
We've [recently changed the text to look white](https://github.com/wordpress-mobile/WordPress-iOS/issues/11688), which clarifies that it's not the blue text that you should tap.

@osullivanchris can I ask you for your input on this?  I feel like closing this issue, because there's no available definition of what it'd take to make this better.

@SylvesterWilmott was previously taking care of these I believe, so it may make sense to validate with him

**Comment by SylvesterWilmott** [comment]
Is the blue dot invisible on iOS every time? This is a bug for sure since it *was* added.

On Android, the words: "Your Site Icon" should be in a heavier text weight

**Comment by diegoreymendez** [comment]
> Is the blue dot invisible on iOS every time?

Thanks... that's missing.  I'll look into it.

**Comment by nheagy** [comment]
fwiw, the code that's supposed to add that dot (called a spotlight in code fwiw) is here: https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Blog/BlogDetailHeaderView.m#L102

I'm not sure at what point it stopped working.

@diegoreymendez I'm available to help with this, give me a ping anytime.

**Comment by diegoreymendez** [comment]
Thanks @nheagy, that helps a lot!

I'll give it a brief look to see if it's an easy fix and if it gets tricky I'll ping you.
