### ISSUE TITLE
Cannot copy text from post editor and paste into other apps

### ISSUE THREAD

**Issue by noteeth** [wordpress-mobile/WordPress-iOS#11682]
### Expected behavior
When copying content from the Post editor, I expected to be able to post it into my Notes app.

### Actual behavior
Cannot paste copied content into another app.  The clipboard appears to be empty.

### Steps to reproduce the behavior
1. Open post editor in app.
2. Hold down in text area until Select bar appears.
3. Select desired text and click the Copy button
4. Navigate to Notes app.
5. Tap to view past option.  
6. Select paste.
7. Nothing is pasted into the app.

##### Tested on [device], iOS [version], WPiOS [version]
2028418-zen

User reported issue iPhone 8, iOS 12.2, WpiOS version 12.3
iPhoneXR, iOS 12.2, WpiOS version 12.3
I tested on my device as well :iPhone 6, iOS 12.1.2, WPiOS version 12.3, screen shots below

![WordPress-iOS](https://user-images.githubusercontent.com/16570939/57653905-c94fdd80-7587-11e9-93e3-088707086426.jpg)
![Notes-App](https://user-images.githubusercontent.com/16570939/57653991-0916c500-7588-11e9-81cf-44f5f40b7f5e.jpg)

**Comment by designsimply** [comment]
Tested and confirmed using both Aztec and the block editor that I cannot paste from editor content area into another app such as Notes or Google Docs. I can copy and paste text into the same content area in Aztec but cannot paste any copied text back into the block editor even in the same session. ([1m18s](https://cloudup.com/c2OhhuLamGs))

<sup>Tested using WP Internal 12.4.0.20190506 on iPhone 6S iOS 12.2.</sup>

**Comment by designsimply** [comment]
Also see https://github.com/wordpress-mobile/WordPress-iOS/issues/11670

**Comment by thehenrybyrd** [comment]
Also reproduced in iPhone SE, (iOS 12.2) running **WP Internal 12.4.0.20190506 (latest beta)** as well as **WPiOS 12.3 (latest release)**.

In both cases, and in both editors (Aztec and Block), I can copy text from post editor content. In both cases, with text copied from either editor, I cannot paste into Notes or other apps. Notes gives me the "Paste" option, but nothing appears when tapped. FB Messenger gives me no "Paste" option at all.

**Comment by thehenrybyrd** [comment]
Another report in 2043190-zen.

**Comment by charliescheer** [comment]
user added some device details in 2043190 :
iPhone SE, iOS 12.2, Wordpress app 12.3.1

**Comment by designsimply** [comment]
@thehenrybyrd can you add any additional details from 2043190 such as quoting an explanation of the problem or a note about whether they are attempting to paste into the exact same app (e.g. Notes)?

**Comment by thehenrybyrd** [comment]
Here's another in 2046235-zen. I'm asking them for more details as to what apps they're trying to copy to.
They said:
> When I try and paste nothing happens. I’ve tried to paste on sites that I’ve always done I’m on IOS version 12.4


As for 2043190-zen, they mentioned in their last response:
> I’ve tried pasting both into notepad and into the search bar for safari. The problem is with all of my sites.

Here's how they initially described the problem: 
> How do I get copy and cut of text to work in order to paste text from the WP app for iPhone SE to other apps. When I do this, the paste is blank. Copy and paste works fine between other apps on this phone. I have already power cycled, deleted the app, logged out and back in and reinstalled the newest one.

**Comment by annacmc** [comment]
Have had another note of this in iOS app reviews
>Hard to use as a tool now as this version and the last have this issue. Copy and paste works fine between other apps on the same phone.

**Comment by designsimply** [comment]
@koke I found that this issue is currently assigned in Sprint 32 (v1.6) for the block editor which means if all goes well a fix will be shipped in WPiOS 12.6. May I please also get help assigning someone to work on this for Aztec as well?

**Comment by SergioEstevao** [comment]
I confirmed the bug and it was introduced on version 1.6.0 of Aztec.
We are working on a patch for it at the moment and will try to have it or in the next release or if needed do a hotfix on the current release.

**Comment by koke** [comment]
This was fixed in #11774 for 12.4.1, which should be in staged rollout now.
