### ISSUE TITLE
Site Creation: Improve "creating new site" screen.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11686]
## Description:

When creating a site through our New Site Creation flow, the screen that tells the user the site is being created could use some design improvements.

## Image:

![IMG_93155CCFF54F-1](https://user-images.githubusercontent.com/1836005/57663019-8e21ce80-75c8-11e9-9b8e-abbeff1c52be.jpeg)

## Matching Android Issue:

https://github.com/wordpress-mobile/WordPress-Android/issues/9854

**Comment by mbshakti** [comment]
New site creation loading screen:

Screenshot: https://drive.google.com/open?id=146qrPAHmpCiSkPPhaXo1S10GQlKA056j
Video: https://drive.google.com/file/d/1xq5MBFT3tytj3zqQ0TiFgFdva3oET6GY/view?usp=sharing

Copy:
Hooray! Almost done
Your site will be ready shortly
Grabbing site URL
Adding site features
Setting up theme
Creating dashboard

**Comment by emilylaguna** [comment]
Subtasks: 
- [ ] Update the `SiteAssemblyContentView` UI
  - Add new label for the title/header
  - Add new label for the subtitle
  - Add new image view 
    - Add magicians hat image to the bundle for both dark and light mode
  - Test both iPhone's and iPads in dark/light mode

- [ ] Create a separate view to manage the cycling/rotating messages
  - Add 2 new properties to the Parameters struct to manage how often the message cycles, and the fade in/out durations
  - Add public methods to start/stop the animation
  - Add public method to reset the view
  - Populate the view with the 4 messages from: https://github.com/wordpress-mobile/WordPress-iOS/issues/11686#issuecomment-558860091

- [ ] Replace the existing `SiteAssemblyContentView` status label with the new cycling view.

**Comment by steineron** [comment]
@mbshakti  - I'm working on this one for Android (sorry -  couldn't tag you there for some reason). Could you please specify duration for the fade in/out animations? I think the defaults int he Adnroid project are 200,400 and 500 milliseconds for short, medium long animations.

**Comment by mbshakti** [comment]
Hi @steineron super sorry for the delayed response! Just catching up on this now :( Do you still need input here on the animation time or is the project done?
