### ISSUE TITLE
Site Creation: Blue text in notices can't be tapped.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11688]
## Description:

The blue text shown by the notices in the Site Setup guided steps can't be tapped, but looks like it can be.

## Image:

![IMG_9E2B15E903E0-1](https://user-images.githubusercontent.com/1836005/57663540-c9bd9800-75ca-11e9-9ad5-320fca7ac439.png)

**Comment by diegoreymendez** [comment]
Ping @SylvesterWilmott - Can you validate this requirement?

**Comment by SylvesterWilmott** [comment]
As mentioned [here](https://github.com/wordpress-mobile/WordPress-Android/issues/9853), I think we can use white instead of blue to highlight the actions within snackbars.

<img width="375" alt="Screenshot 2019-05-15 at 09 49 35" src="https://user-images.githubusercontent.com/36532468/57762176-e820b200-76f6-11e9-8b31-9a52d14cd568.png">

**Comment by elibud** [comment]
Is there a corresponding Android issue for this one?

**Comment by elibud** [comment]
Oh found it [linked](https://github.com/wordpress-mobile/WordPress-Android/issues/9853), so Android is done and iOS pending, is that correct @diegoreymendez ?

**Comment by diegoreymendez** [comment]
Yep that’s correct.

**Comment by diegoreymendez** [comment]
I'll add some notes here to make analysis and discussion easier.  Implementing this won't be trivial because there's no relation (and indeed there's quite some separation) between the method where the notification is set-up, and the blog details VC.

This is where the notification is set-up: https://github.com/wordpress-mobile/WordPress-iOS/blob/7d72a3b99c8e5357d0ed6157c94e1fe2b590bf19/WordPress/Classes/ViewRelated/Blog/QuickStartTourGuide.swift#L332

**Comment by diegoreymendez** [comment]
One possible solution to this, could be to create a regular link attribute in the `WayPoint` description, using a link prefixed by the scheme `WPComScheme`.

This would be handled by `WordPressAppDelegate` here: https://github.com/wordpress-mobile/WordPress-iOS/blob/7d72a3b99c8e5357d0ed6157c94e1fe2b590bf19/WordPress/Classes/System/WordPressAppDelegate%2BopenURL.swift#L4-L35

**Comment by nheagy** [comment]
@diegoreymendez I think that @SylvesterWilmott meant to turn all of the Quick Start highlights to white. I created a PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/11857

**Comment by diegoreymendez** [comment]
Yes @nheagy, that's correct.  Removing my comments to reduce the noise a bit.
