### ISSUE TITLE
Site Creation: Fix deep linking in first-post congratulations email.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11693]
## Description:

After creating a WP.com site, and right after publishing the first post, the user is getting a mail in their inbox titled: "Congratulations on your first post!".

This email has a blue button to start a new post.

We need to ensure this link is opened by the App.

## Images:

![IMG_06FCCD794808-1](https://user-images.githubusercontent.com/1836005/57740014-2d5bca00-768c-11e9-83fa-b351e970d2eb.jpeg)

## Corresponding Android issue:

https://github.com/wordpress-mobile/WordPress-Android/issues/9864

**Comment by diegoreymendez** [comment]
### Start a New Post:

As mentioned by @maxme [in our corresponding Android issue](https://github.com/wordpress-mobile/WordPress-Android/issues/9864#issuecomment-492977593), the "Start a new post" link redirects to:

https://wordpress.com/post/ddancestore.wordpress.com

To make these links launch in the app we need to add `/post/*` to the list of paths in [this file](https://wordpress.com/apple-app-site-association).

The good news is WPiOS [can already handle this change](https://github.com/wordpress-mobile/WordPress-iOS/blob/12.4.0.2/WordPress/Classes/Utility/Universal%20Links/Routes+Post.swift#L8) so it should work right out of the box once that file is updated.

### Site URL:

For the site URL the solution is a bit more elusive.  As @maxme pointed out, we can't just match *.wordpress.com because it could have undersired results.

One option we need to explore is to replace the site's URL in the email with a redirect for deep linking.  Something like `wordpress.com/redirect?url=ddancestore.wordpress.com`.

This needs exploring testing.

**Comment by diegoreymendez** [comment]
The link for new posts should be working now, thanks to updates to our AASA file.  I tested this in  the simulator, and managed to get it working.

Unfortunately, though, I can't make it work in my device.  It seems like the AASA file isn't being properly updated there.  This seems to be a [known issue](https://openradar.appspot.com/4999496467480576).

**Comment by diegoreymendez** [comment]
I managed to test the changes to the AASA file by uninstalling WPiOS from my device, rebooting, reinstalling, and opening a link like `https://wordpress.com/post/ddancestore.wordpress.com`.  This type of link works fine.

The email, though, uses a link like the following one (stripped all non-relevant params since they may contain sensitive info):

`https://public-api.wordpress.com/bar/?redirect_to=https%3A%2F%2Fwordpress.com%2Fpost%2Fddancestore.wordpress.com`

which redirects to a link like the above one - but redirect are not supported for this purpose.

We have to either change the link used in the email, or add support for Universal Links for `public-api.wordpress.com`.

**Comment by maxme** [comment]
> This is a redirect which links to `https://wordpress.com/post/ddancestore.wordpress.com` - but redirects are not supported in Universal Links, apparently.

Same thing happens on Android, redirects won't open the app.

**Comment by diegoreymendez** [comment]
Updated the issue description, we only need to ensure "New Post" deep links into the Apps.

**Comment by diegoreymendez** [comment]
I discussed with @maxme last week that while we want to open paths such as this one:

`https://public-api.wordpress.com/bar/?redirect_to=https%3A%2F%2Fwordpress.com%2Fpost%2Fddancestore.wordpress.com`

We don't necessarily want to open all URLs following this pattern:

`https://public-api.wordpress.com/bar/*`

Unfortunately we can't differentiate these URLs before opening the App.  The reason is that the wildcards in the AASA file only work at the URL-subpath level, and don't really work for the URL parameters.

In other words, these patterns don't work:

`/bar/?redirect_to=*`
`/bar/?redirect_to=http*%3A%2F%2Fwordpress.com%2Fpost%2F*`

But this one does:

`/bar/*`

One possibility is to let the App open the URL but if it's not handle, go back to the web browser.  This isn't the most elegant solution, but I'm not sure it's terrible either.

This is an example of how it would look like to open the App and go back to the browser:

![doubleRedirect](https://user-images.githubusercontent.com/1836005/58436275-e95cc200-809a-11e9-9a60-df56ff788427.gif)

Thoughts @maxme ?

**Comment by maxme** [comment]
I tried a few things in Android, and like in iOS, we can't match `/bar/?redirect_to=.*` or `/bar/?redirect_to=https%3A%2F%2Fwordpress.com%2Fpost%2F.*` but we can match `/bar/.*`

> One possibility is to let the App open the URL and if it's not one of the URLs we handle, to go back to the web browser. This isn't the most elegant solution, but I'm not sure it's terrible either.

We can do this as well on Android, I don't like this option much as we have a lot of different links in marketing emails using, all of them are using the `/bar` endpoint, so every click on a marketing email will launch the app and close it. This will probably skew our stats as well (APP_OPENED, etc.).
