### ISSUE TITLE
Site Creation: steps 1 and 2 don't release first responder when pressing "Back".

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11701]
### Description:

This is similar to an issue in the Domain Selection screen: https://github.com/wordpress-mobile/WordPress-iOS/issues/11702

The fields from Steps 1 and 2 in the Site Creation flow don't release first responder when you go back, and re-open them.

### Demo:

![noReleaseFirstResponder](https://user-images.githubusercontent.com/1836005/58131807-f9d1f000-7bf5-11e9-8e69-c588d51e05a4.gif)

**Comment by stevebaranski** [comment]
@SylvesterWilmott the behavior is not a bug, but working as designed, yes?

**Comment by diegoreymendez** [comment]
I'll update this issue shortly with the correct description.

**Comment by diegoreymendez** [comment]
@SylvesterWilmott - The verticals screen is currently maintaining the text you enter when you go back one screen, and reopen it by selecting the same segment as before.

On top of this, the verticals screen is designed so that when the field has text in it, it gets focus right when its shown... which causes the keyboard to be up and the title and subtitle to be hidden from the beginning.

My feeling is that we probably:

1. Don't want this field to have focus, even if there's text in it; and
2. We probably don't want to store the text once you go back.

Android does neither of these things.

Can you review these observations?

Here's an example of how it looks like now, which IMHO feels off:

![gettingFocus](https://user-images.githubusercontent.com/1836005/58147646-e93f6b00-7c31-11e9-92ae-6a3f0a8d730a.gif)

**Comment by SylvesterWilmott** [comment]
Confirmed that the behaviour in the gif **is** the expected behaviour.

**Comment by diegoreymendez** [comment]
Closing this issue as there's apparently nothing to change.
