### ISSUE TITLE
Site Creation: title and subtitle are sometimes transitioned out.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11702]
### Description:

The search field from the Domain Selection step never resigns first responder when going back.  This causes the keyboard to come up, and the headers to be transitioned out (if there's text in the search field or a title was set in the previous screen.

### Steps to Reproduce:

There are two ways to reproduce.

#### Path 1:

1. ...Go through the site creation flow
2. On Step 2 of 3 (basic information) enter a site title
3. Press "Next"
4. Go back one step
5. Press "Next"

Notice that the title and subtitle are transitioned out.  This is because there are search results based on the title AND because the keyboard is up since first responder wasn't properly resigned.

#### Path 2:

1. ...Go through the site creation flow
2. On Step 2 of 3 (basic information) leave the title site empty
3. Press "Next"
4. Enter some text in the search field
5. Go back one step
6. Press "Next"

Notice that the title and subtitle are transitioned out.  This is because there are search results based on the search field AND because the keyboard is up since first responder wasn't properly resigned.

**Comment by stevebaranski** [comment]
@SylvesterWilmott the behavior is not a bug, but working as designed, yes?

**Comment by diegoreymendez** [comment]
@stevebaranski - The report is a misunderstanding on my end, but there's a real issue behind this.  I'll update the issue to explain what the problem is.

**Comment by stevebaranski** [comment]
@diegoreymendez Ah, gotcha. Please don't hesitate to reach out if I can offer assistance.

**Comment by SylvesterWilmott** [comment]
@diegoreymendez The way to reproduce the issues in this screen are:

1. ...Go through the site creation flow
2. On Step 2 of 3 (basic information) enter a site title
3. Press "Next"
4. Go back one step
5. Press "Next"
6. Notice that title and subtitle are transitioned out

and

1. ...Go through the site creation flow
2. On Step 2 of 3 do not enter a site title
3. Press "Skip"
4. Notice that the "Suggestions" heading is visible in the absence of any results

**Comment by diegoreymendez** [comment]
@stevebaranski, @SylvesterWilmott - Updated the issue title and description to reflect the actual issues I'm seeing (based on the comments by @SylvesterWilmott and some extra observations I made).  There are some other issues in this screen which I'll report in a separate issue.
