### ISSUE TITLE
Site Creation: Test the removal of the Education Segment in mobile.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11700]
## Description:

The Education Segment has been removed.  Let's make sure we test this in iOS.

Internal Ref: D28219

**Comment by designsimply** [comment]
Screenshots for reference:

<img src="https://user-images.githubusercontent.com/1119271/57811072-9d1e9300-7726-11e9-854c-548b3a25f260.png" width="200" alt="my-sites"> &nbsp; <img src="https://user-images.githubusercontent.com/1119271/57811149-bf181580-7726-11e9-9049-f74a56a2ffe7.png" width="200" alt="create-wordpress com-site"> &nbsp; <img src="https://user-images.githubusercontent.com/1119271/57810962-4fa22600-7726-11e9-9ff3-fad7a3545620.png" width="200" alt="site-creation-showing-education-segment-in-wpios-12 3">
<p style="clear:both;"><sub>Tested with WPiOS 12.3 (app store version) on iPhone 6S iOS 12.2.</sub></p>

**Comment by diegoreymendez** [comment]
@designsimply - While the issue is up, the changes aren't merged yet in the backend (something that's not clear in this issue's description).  This is actually part of an ongoing process to test upcoming changes for Site Creation.

I'll be iterating on this process to make sure all the info is included properly.

**Comment by diegoreymendez** [comment]
<img width="439" alt="Screen Shot 2019-06-28 at 11 19 19 AM" src="https://user-images.githubusercontent.com/1836005/60348755-97a7a000-9996-11e9-881b-325ad034ecd3.png">
