### ISSUE TITLE
iOS WordPress app, when choose image from Media, the sequence of album is random and not user-friendly

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#11738]
Transferring a bug ticket from WCiOS to WPiOS. https://github.com/woocommerce/woocommerce-ios/issues/978
cc: @kosiew.

**Is your feature request related to a problem? Please describe.**

Customer in #11356242-hc is frustrated that when he wants to choose media from his device that the albums are in random order.

**Describe the solution you'd like**
Customer prefers the album sequence in WordPress app to follow the sequence in Photos app.

**Describe alternatives you've considered**
None

**Additional context**
#11356242-hc
#2039179-zen

**Comment by kean** [comment]
Fixed in the scope of https://github.com/wordpress-mobile/WordPress-iOS/issues/21190
