### ISSUE TITLE
Show stats for all sites on iOS widget

### ISSUE THREAD

**Issue by uncertainquark** [wordpress-mobile/WordPress-iOS#11752]
### Expected behavior
Show stats for all websites on the iOS widget.

### Actual behavior
Shows stats only for the default site.

![IMG_3217](https://user-images.githubusercontent.com/22585732/58190929-26ac0300-7cdb-11e9-86be-36396c380e9d.jpg)

### Steps to reproduce the behavior
Add iOS widget for an account that has multiple websites

##### Tested on [device], iOS [version], WPiOS [version]
iPhone SE, iOS 12.3, Wordpress 12.4

**Comment by ScoutHarris** [comment]
Hi @uncertainquark .

Thank you for requesting this. We are in the process of redesigning the stats widget, so I will pass this along to our designer for consideration.
