### ISSUE TITLE
Widget should allow choosing which website to see stats for 

### ISSUE THREAD

**Issue by uncertainquark** [wordpress-mobile/WordPress-iOS#11751]
### Expected behavior
Option to choose which website stats to see on the iOS widget.

### Actual behavior
Shows stats only for the default site.

![IMG_3217](https://user-images.githubusercontent.com/22585732/58190798-e77db200-7cda-11e9-989c-423f27f984e2.jpg)

### Steps to reproduce the behavior
Add iOS widget for an account that has multiple websites

##### Tested on [device], iOS [version], WPiOS [version]
iPhone SE, iOS 12.3, Wordpress 12.4

**Comment by ScoutHarris** [comment]
Hi @uncertainquark .

Thank you for requesting this. We are in the process of redesigning the stats widget, so I will pass this along to our designer for consideration.

Also, in case you weren't aware, you can change the site displayed on the widget from within the app.

While in the Stats view on the desired site, select `Today` on the nav bar, then `Use this site`.

<img width="576" alt="today_widget" src="https://user-images.githubusercontent.com/1816888/58281919-8cdb6900-7d61-11e9-9499-475a5c890528.png">
