### ISSUE TITLE
Domain Credit: "Register Domain" cell is pre-selected (doesn't respond to tap) on device with split-screen view

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#11772]
### Expected behavior

I expect to open the My Sites section and select "Register Domain" to register a domain for my site with a domain credit.

### Actual behavior

On a device with a split-screen view, when I first open the My Sites section the "Register Domain" cell is pre-selected and doesn't respond to my tap. I have to navigate to another My Sites section and back to open that section.

### Steps to reproduce the behavior

1. Open the My Sites section and select a site with the “Register Domain” prompt.
2. Force-close the app (completely close it, don’t just background it).
3. Open the app again and note that the “Register Domain” cell is selected (has a grey background).
4. Tap on “Register Domain” to try to open it; nothing happens.

### Screenshot

![IMG_0256](https://user-images.githubusercontent.com/8658164/58320507-adfc9200-7e13-11e9-98e5-89d8d37756c0.PNG)

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/11804.
