### ISSUE TITLE
Login: Username & display name never load on login epilogue for certain self-hosted users

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#11771]
### Expected behavior

I expect that any loading spinners on screen will eventually be replaced with content.

Specifically, I expect that the loading spinner below the Gravatar on the login epilogue screen will eventually be replaced with the user's display name and username. (Alternately, I'd expect to see no "Logged in as" section at all, if we can't load any user data.)

### Actual behavior

When a self-hosted user logs in, that loading spinner sometimes never goes away. I believe this happens when the self-hosted account is associated with an email address that isn't registered with a WordPress.com account.

### Steps to reproduce the behavior

1. Log in to the app using the site address login flow.
2. Enter a self-hosted site address.
3. Enter the username/password for an account on the self-hosted site that uses an email address NOT used with a WordPress.com account.
4. On the login epilogue screen, note that the loading spinner never goes away.
5. Remove the self-hosted site from the app.
6. Log in to the same self-hosted site again, but this time log in to an account that uses an email that IS used with a WordPress.com account. (The accounts don't need to be linked in any way, i.e. the site doesn't need to use Jetpack.)
7. On the login epilogue screen, note that the WordPress.com display name (not the display name associated with the self-hosted account) and self-hosted username load, and the Gravatar loads. (If there's no Gravatar set for that email address, a generic Gravatar icon loads.)

### Screenshots

Endless loading spinner:

![2019-05-24 09 34 08](https://user-images.githubusercontent.com/8658164/58315059-b00d2380-7e08-11e9-8e14-f179c4240db1.png)

Self-hosted account using an email address also registered at WordPress.com:

![2019-05-24 09 32 34](https://user-images.githubusercontent.com/8658164/58315066-b26f7d80-7e08-11e9-8d05-20af7478d5d4.png)

**Comment by ScoutHarris** [comment]
Hey @rachelmcr .

I ran across this when implementing the [new login epilogue](https://github.com/wordpress-mobile/WordPress-iOS/issues/13413). Thanks for noting your thoughts on what _should_ happen because I wasn't sure. 😄 

We might as well address this in the [Unified Auth](https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/projects/1) project, so I'm removing it from Groundskeeping.

cc @mindgraffiti
