### ISSUE TITLE
Settings: Add an icon to indicate which items leave the app / app switch 

### ISSUE THREAD

**Issue by megsfulton** [wordpress-mobile/WordPress-iOS#11787]
Within the App Settings and About screens, there are a few items that switch to the iOS Settings app or the iTunes store. The handling of these options is inconsistent and could benefit from some indication that you're going to be leaving the app by tapping the item.  

![IMG_3898](https://user-images.githubusercontent.com/161697/58436347-c0780500-8079-11e9-8f02-fa1e57bda27f.PNG)
![IMG_3899](https://user-images.githubusercontent.com/161697/58436349-c241c880-8079-11e9-81ac-d8c645531b8f.PNG)

**Comment by megsfulton** [comment]
Adding an icon to app settings was addressed in https://github.com/wordpress-mobile/WordPress-iOS/issues/11925

**Comment by iamthomasbishop** [comment]
I'm going to close this one out as it's been addressed in #11925
