### ISSUE TITLE
Support: explore setting expectations / providing guidance on information to provide 

### ISSUE THREAD

**Issue by megsfulton** [wordpress-mobile/WordPress-iOS#11782]
Many customers treat mobile support like chat. Sending off short quick, multiple, and incomplete messages. 

This is likely because the views are more similar to chat composing than email composing. It may be setting the expectation that they’re chatting with someone and expecting a quicker response. This results in Happiness Engineers needing to ask a number of questions to get more information out of the user to resolve the issue. We may benefit from setting expectations around response time or creating a bit more structure to gather more information from the customer before a user submits a support request as we do on the web.

![IMG_3885](https://user-images.githubusercontent.com/161697/58361674-52e39300-7e45-11e9-8ef1-4e0d7e61ba84.PNG)

**Comment by elibud** [comment]
I think on this one we are limited to what the Zendesk SDK provides, right @ScoutHarris? The solution would be to build our own UI and use their API (which we have discussed before but will be a lot of work).

**Comment by ScoutHarris** [comment]
@elibud - yep, you described it exactly!
