### ISSUE TITLE
Images added to an existing draft do not show up in Preview

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#11808]
I can only reproduce this if the image was added while online and the Post was updated while offline. 

### Expected behavior

The Preview should show the added image.

### Actual behavior

The Preview does not show the image.

### Steps to reproduce the behavior

1. Create a draft. Add an image to it.
2. Exit the Editor and save the draft. Make sure that it is uploaded.
3. Edit the draft. 
4. Add another image to it. Wait until the image is uploaded. 
5. Go offline.
6. Exit the Editor and click on _Update Draft_. 
7. In the Post List, go back online. 
8. Click on _Retry_. 
9. Once the Post is uploaded, click on _Preview_. 

Tested on iPhone XS, iOS 12.2, WPiOS develop e8ccef3.

**Comment by yaelirub** [comment]
@jklausa , please take a look at this issue as well https://href.li/?https://github.com/wordpress-mobile/WordPress-iOS/issues/11836 to see if it's related.

**Comment by diegoreymendez** [comment]
@jklausa - Can you assess if this issue impacts both Aztec and Gutenberg?  I think that'll be relevant to figure out if this is within scope.

**Comment by shiki** [comment]
Good news! I can't reproduce this anymore. 

@diegoreymendez @yaelirub Would anyone of you kindly confirm that you can't reproduce it too? Then we can close this. 🙂

**Comment by yaelirub** [comment]
Hey @shiki , I couldn't reproduce either.
I'm fine with closing it

**Comment by shiki** [comment]
Thank you, Yael!
