### ISSUE TITLE
[Stats Refresh] Period Authors: expanded rows should be 44pt

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#11800]
Reported by @SylvesterWilmott - 

"In the block “Authors”, expanded rows should be 44pt"

<img width="450" alt="authors" src="https://user-images.githubusercontent.com/1816888/58513067-dc53d780-815b-11e9-9f7b-93197b180ff0.png">

**Comment by SylvesterWilmott** [comment]
Thanks @ScoutHarris
