### ISSUE TITLE
[Stats Refresh] browsing back from View More shows the wrong set of data

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11815]
Tapping "View More" from any period stats and then browsing back to the previous view results in a wrong set of data. (<a href="https://cloudup.com/cPiLEhbfLb9" rel="nofollow">1m58</a>)

Before (left) and After (right) browsing view more for 2012 stats on my site:

<img src="https://user-images.githubusercontent.com/1119271/58598820-12b45400-823b-11e9-95eb-19c5138bed5e.png" width="270" alt="stats-refresh-2012-example-before-view-more"> <img src="https://user-images.githubusercontent.com/1119271/58598823-15af4480-823b-11e9-9a58-c06231166f8c.png" width="270" alt="stats-refresh-2012-example-after-view-more">

* Site details: WP 5.0.3 Jetpack 7.1.1
* Tested with WP Internal `develop` (6e9ec1ca7a) on iPhone 6S iOS 12.3.1

**Comment by ScoutHarris** [comment]
@danielebogo - this sounds related to what you're working on for #11742, specifically your comment on #11805 `This doesn't fix the problem we still have when a Stats detail is pushed. I'm working separately to improve the PeriodStore loading.`

Is that accurate? If not, please let me know! Thanks!!

**Comment by danielebogo** [comment]
I think the wrong numbers displayed bug is fixed now in #11805 . It's related to `Stats don't update when a different site is selected.` However there's still a problem when a stats detail is pushed. Browsing back, sometimes, the overview results empty.

**Comment by ScoutHarris** [comment]
@danielebogo thank you. I'll leave this open as part of fixing the returning from details problem.
