### ISSUE TITLE
Preview: Previewing a post while uploading image for image block 

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-iOS#11835]
Choosing Preview while image upload is still in progress opens preview with no image and going back to the post and making edits shows only new edits still without the image preview, only a little square

### Expected behavior

Not sure how we'd like to handle the user trying to preview while an image upload in progress, my suggestion is to continue to the preview and show a template image in the interim until the upload is complete

### Actual behavior

![IMG_0019](https://user-images.githubusercontent.com/6520461/58735493-2ccb6f00-83c0-11e9-9af1-8ef9ff41cc9a.PNG)

### Steps to reproduce the behavior

1. Activate the block editor
2. Add an image block
3. Add an image to the image block
4. Preview the post before the image upload is finished(this was easy for me but Network link conditioner might help to do this on a simulator)
5. Optionally, go back to the post and make changes, previewing still shows the image as shown in the screenshot

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 6, iOS 12.1.2, 12.5.0.2

**Comment by yaelirub** [comment]
Hey @JavonDavis , we have an open issue in progress for this : https://github.com/wordpress-mobile/WordPress-iOS/issues/11808

**Comment by JavonDavis** [comment]
Hey @shiki @yaelirub I tested this on develop and I'm still seeing the same issue here

**Comment by yaelirub** [comment]
@JavonDavis , looking into it

**Comment by yaelirub** [comment]
This issue is pure preview issue. Moving this to groundskeeping.

**Comment by erricgunawan** [comment]
Just out of curiosity, is this issue the same or related with #13929 ? That one looks like already have a fixed here: #13974

I came to this (and the issue above) because of a report in 3126988-zen:

> I have been trying to upload a blog post via ipad or iPhone but unfortunately whenever I hit preview the images won’t show only the content is shown. After showing error for uploading images it says Wordpress doesn’t support classic editor but even block editer option is not supporting to show or upload images while previewing.

I know that message might still be confusing so I'm confirming with the user.

But I just wonder if this issue itself already has a fix or this is still an issue at all.

**Comment by yaelirub** [comment]
Hey @erricgunawan , thanks for commenting here! We disabled the option to preview post while uploading media so I think you're right and we can close this one.
