### ISSUE TITLE
Preview: Editing image block causes image to not show in preview

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-iOS#11836]
Editing the Image in an image block causes the image to not show in Preview

### Expected behavior

For the new image to be shown in the preview.

### Actual behavior

No image is shown and if there's a caption on the image the caption will show but now the image. 

### Steps to reproduce the behavior

1. Activate the block editor and create a new post
2. Add an image block 
3. Preview the Post
4. Close the preview 
5. Edit the image and choose to take a photo 
6. Preview post again

##### Tested on [device], iOS [version], WPiOS [version]
 iPhone 6, 12.1.2, 12.5.0.2

**Comment by ghjjkbbh** [comment]
> 在图像块中编辑图像会导致图像无法在预览中显示
> 
> ### 预期的行为
> 用于在预览中显示新图像。
> 
> ### 实际行为
> 没有显示图像，如果图像上有标题，标题将显示但现在显示图像。
> 
> ### 重现行为的步骤
> 1. 激活块编辑器并创建新帖子
> 2. 添加图像块
> 3. 预览帖子
> 4. 关闭预览
> 5. 编辑图像并选择拍照
> 6. 再次预览帖子
> 
> ##### 在[设备]，iOS [版本]，WPiOS [版本]上测试
> iPhone 6,12.1.2,12.5.0.2

**Comment by marecar3** [comment]
Hi @JavonDavis, 
I have tried to reproduce this issue on both public and private site and I didn't have luck.

WPiOS: 12.8
iOS: 12.3
iPhone XS

Are there maybe any extra steps that I should follow? Thanks 😃

**Comment by JavonDavis** [comment]
@marecar3 here's a video run of what I did on WPv12.7.0.201090620 

https://www.dropbox.com/s/svjcqb8fgs58h87/image%20block.MP4?dl=0

**Comment by marecar3** [comment]
Thanks, @JavonDavis. 
From the video, I can see that you went to the Preview screen before the image was uploaded with success. 
Please, can you try to wait for image to be uploaded before you got to the Preview screen?

**Comment by JavonDavis** [comment]
> From the video, I can see that you went to the Preview screen before the image was uploaded with success.
> Please, can you try to wait for image to be uploaded before you got to the Preview screen?

Waiting actually does cause it to work as expected, do you think we should disable the Preview until it's ready then? 

> Btw this ticket should be opened in gutenberg-mobile space as this bug is in Gutenberg editor.

You're right, should I still go ahead and open there since this seems a little preview related instead?

**Comment by marecar3** [comment]
>Waiting actually does cause it to work as expected, do you think we should disable the Preview until it's ready then?

Please, can you compare how it's working with Aztec Editor? and then we can decide about further steps.

**Comment by JavonDavis** [comment]
The behavior is the same with Aztec Editor... Previewing while the image is uploading will lead to the image not showing up in the Preview.

**Comment by JavonDavis** [comment]
Closing as a duplicate of 11835

**Comment by hypest** [comment]
#11835 seems to itself be a duplicate of #11808 which is now closed as not-happening-anymore. @JavonDavis , can you confirm whether this here needs to be reopened or is it fixed for the block editor as well? Thanks!
