### ISSUE TITLE
[Site Pages] Incorrect labels on pages search

### ISSUE THREAD

**Issue by SylvesterWilmott** [wordpress-mobile/WordPress-iOS#11842]
In site pages search, header titles show "Publish" and "Draft"

- "Publish" should be changed to "Published"
- "Draft" should be changed to "Drafts"

**Comment by diegoreymendez** [comment]
I just tested this in the latest WPiOS release and I'm seeing "Published" and "Drafts" when searching for a page in the pages list.

Closing.
