### ISSUE TITLE
Notifications: push notifications for likes on posts sometimes show the wrong name

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11847]
Steps to reproduce:

1. Create and publish a post from the WordPress for iOS app.
1. Remain logged in to the app as the post author and have several other users like the post from elsewhere within a short time frame.
1. Check each push notification received to make sure the correct name shows for each like.

<strong>Result:</strong> I only received a couple push notifications even though I added at least 8 likes to my post from different users. Note: I might be missing something from my testing steps for receiving push notifications (see Question section below).

I created this post on WPiOS while logged in as `designsimply`:

* https://design5279.wordpress.com/2019/06/03/live-in-nyc-butterfly/

I added several likes from other users and got one push notification for the first 2 post likes and none for the rest, so I tried again and tracked where/how I made the next set of likes for reference (in case they're behaving strangely only from one source).

* user157 liked from the Reader using WP Internal 12.5.0.20190530 on iPad Mini 4 iOS 12.3.1
* user9734 liked from the Reader using WPAndroid alpha-171 on Pixel 3 Android 9
* user863 liked from Calypso Reader using Firefox 67.0 on macOS 10.14.5
* user439 liked from the post directly using Safari 12.1.1 on macOS 10.14.5
* user7361 liked from the post directly using Chrome 74.0.3729.169 on macOS 10.14.5

I made sure my Profile > App Settings > Push Notifications were all on before starting:

<img src="https://user-images.githubusercontent.com/1119271/58838818-08b89980-861d-11e9-992d-af73cc31f078.PNG" width="270" alt="IMG_2812"> <img src="https://user-images.githubusercontent.com/1119271/58838819-08b89980-861d-11e9-9c40-86ea304192ce.PNG" width="270" alt="IMG_2813">
<sup>Tested with WP Internal 12.5.0.2019030 on iPhone 6S iOS 12.3.1.</sup>

**Question**

What exactly are the criteria for receiving a push notification for a post like on WPiOS? Do I need to be logged out of all other browsers (i.e. would having notifications or even the masterbar open in another browser window for the same account cause a push notification not to get sent? Does the app have to be in the background for a push notification to appear?

h/t @astralbodies for the original report (internal reference: p4a5px-2oU-p2).

**Comment by salimbraksa** [comment]
I created a [post](https://salimhotel.wordpress.com/2024/03/07/embracing-the-digital-age-the-evolution-of-remote-work/) that received likes from two users. Then, I received two push notifications, and the usernames appeared correctly in them.

Closing this issue as non reproducible.

_Tested on iPhone 14 Pro Max | JPiOS v24.4 | iOS 17_

<video src="https://github.com/wordpress-mobile/WordPress-iOS/assets/9609223/b508732d-43b1-4739-9e8e-f19449facada"></video>
