### ISSUE TITLE
Offline Support: Investigate Reachability issues.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11840]
This issue was spawned off [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/11839).

In that PR I noticed Reachability isn't calling the network availability closures reliably.  In fact they're only called once apparently.

Investigate how this can be resolved.

## Options to Consider:

1. Investigate the different mechanisms we use in the App for reachability.
2. Consider using [this library](https://github.com/ashleymills/Reachability.swift), or another similar library.

## On NWPathMonitor:

We can't exclusively use `NWPathMonitor` because it's only supported in iOS 12+, but we could consider using it conditionally for now so that when we drop support for earlier iOS versions, we can fully switch to it.

**Comment by yaelirub** [comment]
might be helpful: https://www.youtube.com/watch?v=aRsPC2g77es

**Comment by diegoreymendez** [comment]
This issue seems to be known: https://github.com/tonymillion/Reachability/issues/171

**Comment by diegoreymendez** [comment]
I've tested this using a device instead of the simulator, and it's working fine.

Closing this issue for now.
