### ISSUE TITLE
[Stats Refresh] Period Overview: Views & Visitors are incorrect for previous periods

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#11873]
### Expected behavior
The Views count should be accurate for all periods.

### Actual behavior
The Views count is only accurate for the current period (d, w, m, or y). But for weeks, months, and years, selecting a different period from the date bar or the chart, the Views count is always incorrect. Days is sometimes correct, but not always.

Also, Visitors is sometimes incorrect.

For example:

Calypso:
<img width="1168" alt="calpyso" src="https://user-images.githubusercontent.com/1816888/59063817-23ca1a00-8866-11e9-83ec-01dbf9715633.png">

iOS:
<img width="400" alt="ios" src="https://user-images.githubusercontent.com/1816888/59063991-828f9380-8866-11e9-9670-b3ec2570c25d.png">

### Steps to reproduce the behavior
Go to Stats > Period. Change the period using either the date bar or the chart. Compare the numbers with Calypso.

**Comment by jklausa** [comment]
This is weird! I'll take a peek.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/11883.
