### ISSUE TITLE
[Stats Refresh] When charts have no data, show grey bars

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#11876]
Currently, when the charts are empty, they show nothing. They should show short grey bars like Android does. 

This applies to:

- Latest Post Summary
- Period Overview
- Post Stats Overview

Examples:

**iOS:**
<img width="400" alt="ios_empty_chart" src="https://user-images.githubusercontent.com/1816888/59070766-46b1f980-8879-11e9-900a-e1ab85e04451.png">

**Android:**
![android_empty_chart](https://user-images.githubusercontent.com/1816888/59070852-8d075880-8879-11e9-9dd9-66bc2222f842.png)

From @planarvoid in a Slack conversation - "I’m just showing gradient columns with max value of 1. grey to white."

**Comment by planarvoid** [comment]
I'm not sure if it helps in any way but this is the code that build the empty data set on Android
```
private fun buildEmptyDataSet(context: Context, count: Int): BarDataSet {
        val emptyValues = (0 until count).map { index -> BarEntry(index.toFloat(), 1f, "empty") }
        val dataSet = BarDataSet(emptyValues, "Empty")
        dataSet.setGradientColor(
                ContextCompat.getColor(
                        context,
                        R.color.primary_50
                ), ContextCompat.getColor(
                context,
                android.R.color.transparent
        )
        )
        dataSet.formLineWidth = 0f
        dataSet.setDrawValues(false)
        dataSet.isHighlightEnabled = false
        dataSet.highLightAlpha = 255
        return dataSet
    }
```
The value of all the columns is 1F, the color goes from `primary_50` to `transparent`. Let me know if something's not clear!

**Comment by ScoutHarris** [comment]
Thanks @planarvoid ! I'm sure this will come in handy.

**Comment by ScoutHarris** [comment]
In the iOS version of the Charts, bar gradients have not been implemented. With #11887 , light grey bars were added to empty charts while we figure out if we can do gradients.

There are two outstanding PRs attempting to do so in the library, but both are over a year old, and are build off of older version of the library:
https://github.com/danielgindi/Charts/pull/3225
https://github.com/danielgindi/Charts/pull/3533

There are two (rather old) issues that may be useful if we decide to attempt this ourselves. 
https://github.com/danielgindi/Charts/issues/2722 - user modified the library's `BarChartRenderer` directly.
https://github.com/danielgindi/Charts/issues/2515 - user added a `CAGradientLayer` to all the bars (with a few gotchas).

**Comment by ScoutHarris** [comment]
With these changes, we're now showing grey bars:
https://github.com/wordpress-mobile/WordPress-iOS/pull/11887
https://github.com/wordpress-mobile/WordPress-iOS/pull/11971

As stated previously, bar gradients were not implemented in the iOS Charts library. And doing so manually will take a bit of effort.

I'm closing this as Done. If we _really_ have to have gradient bars, we discuss the effort vs benefit with another request.
