### ISSUE TITLE
[Stats Refresh] cannot tap chart bars to change data on first view

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11882]
Steps to reproduce:

1. Go to the Days/Weeks/Months/Years view for Stats on any site.
1. Tap the bars in the first chart you see and check that the data changes in the modules below.
1. Switch to a different site.
1. Go to the Days/Weeks/Months/Years view for Stats.
1. Check to see if tapping the bars changes the data below.
1. Close and re-open the app.
1. Go to the Days/Weeks/Months/Years view for Stats on any site.
1. Check to see if tapping the bars changes the data below.

<strong>Result:</strong> the first time you open stats after closing the app or switching sites, tapping on the bars in the chart does not change the data in the modules. If you use an arrow to change bars or if you change to a different time period (DWMY), then it starts working normally. ([2m29s](https://cloudup.com/c7s7YmxzQ-S))

<img src="https://user-images.githubusercontent.com/1119271/59127372-b9c47a00-8924-11e9-9995-d925b211b304.PNG" width="270" alt="IMG_2822">
<sup>Tested with WP Internal 12.6.0.20190604 on iPhone 6S iOS 12.3.1</sup>

**Comment by ScoutHarris** [comment]
@jklausa believes this is related to #11873.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/11883.

**Comment by designsimply** [comment]
I re-tested with WP Internal 12.6.0.20190604 and develop `d780002de0` (12.6 alpha) on iPhone 6S iOS 12.3.1 and found it is working much better except for the graphs for individual post views such as Stats > Insights > Latest Post Summary > View more. ([21s](https://cloudup.com/crb2m7YNe6q))

<img src="https://user-images.githubusercontent.com/1119271/59248347-5e71e080-8bdf-11e9-9339-de27b6632577.png" width="270" alt="graphs-for-individual-post-details-unresponsive-on-first-view">

Would you like me to file this as a separate issue?

**Comment by jklausa** [comment]
@designsimply ah, yeah — that is a separate issue. If you could file it, I’d super appreciate it :)

**Comment by designsimply** [comment]
Certainly! Filed at https://github.com/wordpress-mobile/WordPress-iOS/issues/11894.

**Comment by jklausa** [comment]
I think @ScoutHarris pre-empted you with fixing this before you got around to filing this :P Should've gotten fixed in #11892 :)
