### ISSUE TITLE
[Stats Refresh] Likes graphs do not appear to be working properly.

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11888]
Steps to reproduce:

1. Open any site that has traffic history.
1. Go to Stats > DWMY and tap "Likes" below the graph.
1. Try changing the selected time period by tapping different parts of the graph or by using the arrows at the top to navigate.

<strong>Result:</strong> graph bars are missing for all likes. ([29s](https://cloudup.com/c8wc7dk-uDs))

<img src="https://user-images.githubusercontent.com/1119271/59247729-8a8c6200-8bdd-11e9-8ff3-6b062b377ee7.png" width="270" alt="chart-bars-missing-for-likes">
<sup>Tested with WP Internal 12.6.0.20190604 and WP Internal develop `d780002de0` (12.6 alpha) on iPhone 6S iOS 12.3.1.</sup>

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/11887.
