### ISSUE TITLE
[Stats Refresh] Jetpack connect step is very slow

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11889]
Steps to reproduce:

1. Open stats for a self-hosted site without Jetpack installed.
1. Go to Stats and click the "Install Jetpack" button.
1. When you get to the connect step, start timing after you tap the "Approve" button and measure how long it takes to connect Jetpack.

<strong>Result:</strong> the Jetpack connect step is very slow—it took 1m17s for me even on a fast connection of [320Mbps](https://user-images.githubusercontent.com/1119271/59250220-e4902600-8be3-11e9-8216-bfb0b9850dd0.PNG). ([1m23s](https://cloudup.com/cCzM9j-XIDT))

<img src="https://user-images.githubusercontent.com/1119271/59250383-56686f80-8be4-11e9-84ab-ebc11ffd4f1a.png" width="270" alt="jetpack-connect-step">
<sup>Tested with WP Internal 12.6.0.20190604 (12.6 alpha) on iPhone 6S iOS 12.3.1.</sup>

**Comment by ScoutHarris** [comment]
Hey @designsimply .

Hrm. We haven't touched anything related to Jetpack install. Would it be possible for you to try that with the old stats, maybe with the current App Store version?

**Comment by designsimply** [comment]
Certainly! Here is a test comparing the Install Jetpack flow on the web, in the current WPiOS app store version 12.5, and 12.6 alpha again: [4m49s](https://cloudup.com/cnoR_LhcsEO).

* Web: ~22s
* WPiOS 12.5: ~9s
* WP Internal 12.6.0.20190604: ~21s

I think we can conclude from this that the timing varies and we should keep a close eye on the speed of the API interaction itself in regard to the approval step in the Jetpack Install flow.

**Comment by ScoutHarris** [comment]
Thanks @designsimply !
