### ISSUE TITLE
[Stats Refresh] Improve x axis labels

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#11880]
The X axis labels on stats period charts always seems to use the format MMM DD (e.g. Jan 12), which isn't particularly useful for the charts with larger timespans like month and year. We should update it to match Android, which has more sensible labels:

![stats1-android](https://user-images.githubusercontent.com/4780/59112501-0ca92c00-893b-11e9-8031-6e1e8ebae124.png)

Here's what's used on Android:

* Insights latest post: MMM DD, YYYY
* Days: MMM DD, YYYY
* Weeks: MMM DD - MMM DD
* Months: MMM, YYYY
* Years: YYYY

**Comment by ScoutHarris** [comment]
Fixed with #11884.
