### ISSUE TITLE
[Stats Refresh] chart bars are unresponsive when the post stats view is first loaded

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11894]
Steps to reproduce:

1. Go to Stats > Days > Posts & Pages and tap a post that has a few days of recent stats.
1. Tap on the different bars in the chart.
1. Check to see if tapping the bars changes the data as expected.

<strong>Result:</strong> tapping the bars in the chart does not change the data only for the first page load, if you refresh or use the arrows at top right to navigate then it starts working. ([58s](https://cloudup.com/cKGwckNKuLl))

<img src="https://user-images.githubusercontent.com/1119271/59312203-7b52f600-8c69-11e9-8b36-2824e541cc4e.png" width="270" alt="data-does-not-update-when-chart-bars-on-the-individual-post-view-are-selected">
<sup>Tested with WP Internal 12.6.0.20190604 on iPhone 6S iOS 12.3.1.</sup>

**Comment by jklausa** [comment]
Fixed (I HOPE) in #11892.
