### ISSUE TITLE
Header in a post created in Bear lose styling when multiple styles are applied

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#11912]
### Expected behavior
Header in WP will preserve all styles created in Bear.

### Actual behavior
The header loses all styles. 

### Steps to reproduce the behavior
1. Create a note in Bear
2. Create a header and make it **bold**
3. publish post on WP using share extension 
4. Notice the header has no styling (normal size font and not bold)

In WP:
![IMG_D3889E38A769-1](https://user-images.githubusercontent.com/1335657/59422061-65b00e80-8dd8-11e9-88bd-ef226155363d.jpeg)

In Bear:
![IMG_4234](https://user-images.githubusercontent.com/1335657/59422083-6f397680-8dd8-11e9-9e63-7f6318782685.PNG)

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 7, 12.2 WPioS 12.5.1

**Comment by nheagy** [comment]
This seems to be an issue in Bear, as it doesn't support styles within a header. So the asterisks are treated as content, and sent through to us in the MD file, where CommonMark does allow asterisks within headers, and `*Tel Aviv*` means to italicize it, so we wrap it in `<em>`.

Our behaviour is correct, but I'll pass it along to the Bear folks that they probably want to convert the asterisks to `&#42;`
