### ISSUE TITLE
Webviews: cannot leave a comment from a webview

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#11926]
Steps to reproduce:

1. Open the WPiOS app and log in to a WP.com account.
1. Go to My Sites > Blog Posts > View on a site with comments allowed.
1. Check the comment form to see if you are recognized as a logged in user (ref: https://github.com/wordpress-mobile/WordPress-iOS/issues/11414).
1. Try to leave a comment and then verify whether or not it was saved.

<strong>Result:</strong> the comment form recognizes that I am logged in but posting a comment does not go through. ([1m5s](https://cloudup.com/c7C2sAiY_Jq))

<img src="https://user-images.githubusercontent.com/1119271/59473104-25fc1d80-8dfe-11e9-9fe7-4495cbf92d4b.png" width="270" alt="comment-test-via-webview-wpios-12 5 1">
<sup>Tested with WPiOS 12.5.1 (currently latest app store version) on iPhone 6S iOS 12.3.1</sup>

**Comment by charliescheer** [comment]
I tested this just now and I can confirm the same thing.

If I try to comment on a post I am seeing that I am logged in but the comments do not go through
<img src="https://cdn-std.dprcdn.net/files/acc_593859/4FdP0J" /> 

@jburciaga0  This is an update of #11414 which you were asking about before.

**Comment by msilbers** [comment]
Regarding the above comment, this was reported in #2107412-zen

**Comment by galakhyati** [comment]
The above issue is reported in #2175267-zen too.

**Comment by designsimply** [comment]
Closing as a duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/10262. 🤦‍♀️
