### ISSUE TITLE
Settings: Clean up and unify table views in App Settings 

### ISSUE THREAD

**Issue by megsfulton** [wordpress-mobile/WordPress-iOS#11925]
This update cleans up and unifies the table view in the Me>App Settings screen. 

![App Settings Update](https://user-images.githubusercontent.com/161697/59466643-aca30180-8de2-11e9-8ce9-85041385d647.png)

What's changed: 
1. Removed the slider for max image upload - tapping the row pushes into a new view where the user can select the max image upload size. This behavior matches the max video upload setting. 
2. Media Cache is one table row with the media cache size on the right. Tapping the row pushes into a new view with a Clear Media Cache row. The styling of the row has changed from a centered red text to a left aligned blue text (#0087BE). 
3. Remove Location From Media - has moved from the privacy section to the media section. The text has been updated to "Include Location Data" which changes the current behavior or the setting but better reflects the usage of the toggle (where on = a confirmation)
4. Clear Siri / Spotlight - the styling of these rows has been updated to be left aligned and using the blue link color (#0087BE).
5. The "Other" section header label has been removed and Open Device Settings and About the WP app are on separate rows. Open Device Settings has an icon to indicate that tapping it will open a new application.

**Comment by mindgraffiti** [comment]
- [ ] Removed the slider for max image upload - tapping the row pushes into a new view where the user can select the max image upload size. This behavior matches the max video upload setting.

- [x] Media Cache is one table row with the media cache size on the right. Tapping the row pushes into a new view with a Clear Media Cache row. The styling of the row has changed from a centered red text to a left aligned blue text (#0087BE).

- [ ] Remove Location From Media - has moved from the privacy section to the media section. The text has been updated to "Include Location Data" which changes the current behavior or the setting but better reflects the usage of the toggle (where on = a confirmation)

- [x] Clear Siri / Spotlight - the styling of these rows has been updated to be left aligned and using the blue link color (#0087BE).

**Comment by mindgraffiti** [comment]
Hey @iamthomasbishop 👋 

The instructions say:

> The "Other" section header label has been removed and Open Device Settings and About the WP app are on separate rows. Open Device Settings has an icon to indicate that tapping it will open a new application.

But I'm not sure that's wise since the "Other" section has several more rows now:

<img src="https://user-images.githubusercontent.com/1062444/166813903-ae603df1-85a6-4204-9228-2ab2be0f2c32.png" width="300" />

**Comment by iamthomasbishop** [comment]
@mindgraffiti Agreed, we can keep the section header.
