### ISSUE TITLE
Image overlay disappears when action sheet is dismissed in Aztec

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#11937]
Spun off of: #11933
And related to: #11749

Steps:
1. Be offline
2. Add image to post in Aztec
3. see failure overlay
4. tap on overlay
5. choose retry or edit in action sheet
6. see overlay disappears when action sheet is dismissed

![overlay_dissapear](https://user-images.githubusercontent.com/1335657/59624976-2d753c80-9106-11e9-8e11-0f087cb0b49e.gif)

**Comment by shiki** [comment]
Adding an additional image. I started creating an issue until I found out that this issue already exists. 😄 

<img src="https://user-images.githubusercontent.com/198826/60622114-bd6ce480-9d9c-11e9-9c6e-da36b3265ca7.gif" width="320">
