### ISSUE TITLE
Notifications toggle should have a label to describe options

### ISSUE THREAD

**Issue by irbrad** [wordpress-mobile/WordPress-iOS#1194]
The "Notifications" setting loads an action sheet with snooze options.  However, the "Manage Notifications" view makes it sound like a simple toggle. We should have a descriptor label to mention that there are settings hidden behind that tap.

![organizer - devices-1](https://f.cloud.github.com/assets/1220715/2114764/07802dce-9043-11e3-800b-4b55ab7f16e7.jpg)

![organizer - devices-2](https://f.cloud.github.com/assets/1220715/2114801/7c45bb4c-9043-11e3-96ee-597f583afef2.jpg)

**Comment by jleandroperez** [comment]
I'm closing this since we're entirely rebuilding the Notification Settings section of the app (Ref: #3807)
