### ISSUE TITLE
Stats Refresh: Stats graph showing formulas in some languages

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#11954]
### Expected behavior
When you go to the Stats view in any language, on the side of the graph you should see the range of number of views appear

### Actual behavior
If you are in some languages (Swedish is the only one I found like this so far) instead of displaying the quantities in the side bar you see formulas for getting the quantity:
<img src="https://cdn-std.dprcdn.net/files/acc_593859/QVXy2Q" />

### Steps to reproduce the behavior
1. Switch your phone to Swedish
2. Open the WordPress app and go to a site with some traffic and view it's stats
3. Go to any of the views with a graph (days, weeks, etc)
4. see all the maths appear

WordPress 12.6
iOS 12.3.1

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/11957.
