### ISSUE TITLE
[Stats Refresh] Show value difference in grey for current period

### ISSUE THREAD

**Issue by SylvesterWilmott** [wordpress-mobile/WordPress-iOS#11976]
On Android, we show the current period value difference in grey because the current period is not complete yet. As a result, this value is far more likely to be coloured red than green which can be demotivating. We should do the same on iOS.

This applies to:

- DWMY tabs
- Post stats

<img width="389" alt="Screenshot 2019-06-24 at 07 40 04" src="https://user-images.githubusercontent.com/36532468/60019361-50967380-9653-11e9-8c47-70c793c1366e.png">

Colour used is `grey`

**Comment by frosty** [comment]
Fixed by #11982
