### ISSUE TITLE
[Stats Refresh] Fix chart heights

### ISSUE THREAD

**Issue by SylvesterWilmott** [wordpress-mobile/WordPress-iOS#11978]
The overall heights of the DWMY charts and post list charts differ from the Latest Post Summary Chart. We should align these heights.

Before being able to give an accurate height, I need to know the current height of the charts in different places.

**Comment by ScoutHarris** [comment]
Hey @SylvesterWilmott .

Yep, they are different. Good catch. The heights are:
Latest Post Summary: 170
Overviews: 150

**Comment by ScoutHarris** [comment]
From Slack convo: the chart heights "should be like DMYW".

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/12086.
