### ISSUE TITLE
[Stats Refresh] Latest Post Summary title doesn't render trailing emoji correctly

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#11972]
On the Latest Post Summary card, if there is one (and only one) trailing emoji, it is not rendered correctly.

<img width="350" alt="Screen Shot 2019-06-21 at 5 37 24 PM" src="https://user-images.githubusercontent.com/1816888/59956150-bdd7b800-944b-11e9-9e9f-e2779249822b.png">

If there are more than one, they render fine. And emojis in any other location are fine as well. Some examples:

<img width="350" alt="Screen Shot 2019-06-21 at 5 36 56 PM" src="https://user-images.githubusercontent.com/1816888/59956168-d9db5980-944b-11e9-9d0f-2ef3053534f0.png">

<img width="350" alt="Screen Shot 2019-06-21 at 5 38 00 PM" src="https://user-images.githubusercontent.com/1816888/59956214-39d20000-944c-11e9-8a9d-9a64c78343fb.png">

<img width="350" alt="Screen Shot 2019-06-21 at 5 38 28 PM" src="https://user-images.githubusercontent.com/1816888/59956215-39d20000-944c-11e9-9c32-d9cd2de56a2a.png">

<img width="350" alt="Screen Shot 2019-06-21 at 5 43 28 PM" src="https://user-images.githubusercontent.com/1816888/59956216-39d20000-944c-11e9-87c9-062fa4e2b9e6.png">

**Comment by staskus** [comment]
Closing the issue. `LatestPostSummaryCell` no longer exists and is replaced by `StatsLatestPostSummaryInsightsCell`. The original issue was related to the usage of the attributed string which is not used in this way anymore on `StatsLatestPostSummaryInsightsCell`

Created PR to remove unused code.
