### ISSUE TITLE
"Create Post" button should be shown when offline too.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#11997]
This issue was spawned from a proposal by @shiki in: https://github.com/wordpress-mobile/WordPress-iOS/issues/11430#issuecomment-481835803

The proposal is that the "Create a Post" button should also be shown when there is no data AND we're offline.

## Decision

Original proposal accepted: **If there is no cached data and the device is offline, we should still show the Create a Post button.**
Headline:
Unable to load posts right now.

Subheading:
Check your network connection and try again. Or draft a post.

Button:
Create post

No punctuation on buttons, naturally, though I feel like our sentences here need terminal punctuation. Also, button text is sentence case per the brand guide.

## Original Proposal

I think this needs some discussion on how empty states should be handled. From what I can see, when loading either _Published_ or _Drafts_:

| Has Cached Data? | Online | Offline |
|--------|-------|-------|
|  NO  |  ![2019-04-10 13 41 03](https://user-images.githubusercontent.com/198826/55908334-60df9c00-5b96-11e9-82b7-fe26f6f0420d.png) |  ![2019-04-10 13 39 31](https://user-images.githubusercontent.com/198826/55908429-b025cc80-5b96-11e9-9b64-5de51e900bc1.png) |
| YES   |  ![2019-04-10 13 40 58](https://user-images.githubusercontent.com/198826/55908478-cd5a9b00-5b96-11e9-8bc6-e54816a47a54.png) | ![2019-04-10 13 39 36](https://user-images.githubusercontent.com/198826/55908495-d51a3f80-5b96-11e9-9e11-fbdd8c963085.png) |

My opinion is that if there is no cached data and the device is offline, we should still show the _Create a Post_ button.

**Comment by jklausa** [comment]
one tiny nitpick to note here too: we're incosistent about whether to include a period on the title of the no results page :

"You don't have any draft posts" / no period vs "Unable to load this page right now." / period

it's a tiny thing, but for some reason my brain notices that _immediately_ — it would be awesome if we could fix that while we're changing this here too.

**Comment by osullivanchris** [comment]
If we are going by the principle that offline should behave similar to online, and not block the user, we should make the offline with no cached data look exactly the same as online with no cached data.

**Assumption I need to check here:**
The error says we cannot load the drafts page because the user is offline. But my understanding is that we **can** load the page, there just happens to be no posts there.

So rather than adding the button to the offline error state, I would kill the error state entirely and have it look the same online/offline to the user.

Let me know if you agree @jklausa @diegoreymendez , and if my assumption is correct.

**Comment by diegoreymendez** [comment]
As a note, there's a task to improve the caching of this data which will probably help a bit make this experience more similar to the online experience: https://github.com/wordpress-mobile/WordPress-iOS/issues/11430

My only concern with saying "You don't have any draft posts" when you're offline, is that this could come up in situations where the user has posts but they're not cached for offline access, probably causing the impression that the user lost his/her data.

**Comment by osullivanchris** [comment]
@diegoreymendez  ok good to highlight that. I didn't know that was the case.

Then I agree with the original proposal to just add the button below the current offline empty state message

**Comment by yaelirub** [comment]
@osullivanchris , should we update the message though?
Imo, it seems a bit weird to have:
```
"Check you network connection and try again"
                  "Create Post"
```

**Comment by osullivanchris** [comment]
@yaelirub thanks for catching that. 

Headline "Unable to load any posts right now"
Subheading "Check your network connection and try again"
Button "Create a Post" (same button as online state)

Or we could go a step further and highlight that you can act offline, and give contect for the button
Headline "Unable to load posts right now"
Subheading "Check your network connection and try again. Or create a post even while offline" (Feels a little long, maybe we could drop some of the first sentence)
Button "Create a Post" 

I'll ask someone on #editorial to do a review

**Comment by kristastevens** [comment]
Hi @osullivanchris, thanks for the ping! I've got some thoughts on modifying the second option you shared, just slightly: 

Original: 
> Or we could go a step further and highlight that you can act offline, and give contect for the button
> Headline "Unable to load posts right now"
> Subheading "Check your network connection and try again. Or create a post even while offline" (Feels a little long, maybe we could drop some of the first sentence)
> Button "Create a Post"

Suggested:

Headline: 
Unable to load posts right now.

Subheading: 
Check your network connection and try again. Or draft a post.

Button:
Create post

No punctuation on buttons, naturally, though I feel like our sentences here need terminal punctuation. Also, button text is sentence case per the brand guide.

**Comment by yaelirub** [comment]
@kristastevens, thank you so much for your fast responses! 🙏 
I like your suggestion and adding it to the decision on implementation.

**Comment by osullivanchris** [comment]
@kristastevens that sounds perfect to me! I'm imagining the answer is yes here - just want to confirm. Should we change the online button from "Create a Post" to "Create post" too?

@yaelirub @diegoreymendez this one has the go ahead from me

**Comment by kristastevens** [comment]
> I'm imagining the answer is yes here - just want to confirm. Should we change the online button from "Create a Post" to "Create post" too?

Yes, definitely -- thanks for asking!

**Comment by yaelirub** [comment]
@jklausa , for the period at the end of the title comment: We are lacking consistency in other places too:
You don't have any tags (no period)
You don't have any media. 
You don't have any draft pages (no period)
No pages matching your search (no period)
You don't have any trashed pages (no period)
You don't have any scheduled pages (no period)
etc'

So I think this should be tackled in a separate PR and we need to decide if we want to update most of the messages to have a period at the end.

**Comment by shiki** [comment]
Heads up! It looks like there will be a significant change coming for the Post List. We might want to limit our changes, if there are any, on it. See https://github.com/wordpress-mobile/WordPress-iOS/issues/11646.

**Comment by diegoreymendez** [comment]
Nice catch @shiki.  That said, the PR is already up, so it may make sense to still move ahead... your call @yaelirub !

**Comment by yaelirub** [comment]
@shiki , @diegoreymendez , not sure what those changes have to do with adding the create post button to the no results view. 
Are they getting rid of the no results view?

**Comment by leandroalonso** [comment]
Hi everyone!

Even with the changes in #11646  the no results view will still be appearing if the user has no connection and/or posts — this behavior will not change.

**Comment by shiki** [comment]
@leandroalonso Thank you! 

@yaelirub Sorry, I did not mean to cause an alarm. I just wanted to make sure everyone is aware of possible conflicts. 🙂

**Comment by yaelirub** [comment]
Thanks @shiki . Seems like no possible conflicts.

**Comment by jklausa** [comment]
>So I think this should be tackled in a separate PR and we need to decide if we want to update most of the messages to have a period at the end.

oh, 100% agreed!

It's just something that was bugging me and I noticed while looking at the screenshots, so thought I'll mention it. Do you want me to file a separate issue for it?

**Comment by yaelirub** [comment]
Yes please, @jklausa and thank you
