### ISSUE TITLE
Improve "Revision Browser" entry in the editor "..." menu

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-iOS#11994]
Currently the menu item to access the "Revision Browser" is "History". It's not clear. Calypso uses a different approach:
<img width="288" alt="Screenshot 2019-06-25 at 09 13 37" src="https://user-images.githubusercontent.com/40213/60077125-89a11780-9729-11e9-8956-b1bd1fe0c791.png">

Solution: replace "History" by "Revisions (N)" in this menu.

### WPAndroid ticket:

https://github.com/wordpress-mobile/WordPress-Android/issues/10102

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Updated in https://github.com/wordpress-mobile/WordPress-iOS/pull/23145
