### ISSUE TITLE
Refine Revisions/History layout on tablet

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/WordPress-iOS#11999]
### Currently

At the moment, I'm seeing a couple of issues with our Revision/History viewer layout: 

* The content container is full-width – should match the active editor
* The container doesn't have the same top-margin (when using GB)
* The previous/next arrows aren't vertically centered

I understand that some of these things are slightly different for Aztec vs. Gutenberg – ideally, the layout of the active editor for the post/page should be respected.

#### HTML mode (default view)

![IMG_0492](https://user-images.githubusercontent.com/1200432/60116376-8879e580-973d-11e9-87fc-84d5d0993147.jpeg)

#### Visual mode (default view)

![IMG_0494](https://user-images.githubusercontent.com/1200432/60116600-fd4d1f80-973d-11e9-8a07-0423ccc553e0.jpeg)

### Steps to reproduce the behavior

* Open a post/page with multiple revisions
* Tap on `•••` to open menu
* Tap on `History` to open History/Revisions viewer
* In History/Revisions viewer, tap `•••`, to switch between HTML/Visual modes

##### Tested on [device], iOS [version], WPiOS [version]

iPad Pro 10.5", iOS 13 beta 2, WPiOS 12.7 beta

// cc @nheagy @danielebogo and we should also cross-check Android tablet to see if these issues also exist there – Unfortunately, I don't have an Android tablet on me to test. cc'ing those who worked on the Android side – @theck13 @khaykov I think?

**Comment by theck13** [comment]
@iamthomasbishop, I was able to confirm similar behavior on WordPress Android 12.7.  See the screenshots below for illustration.

HTML|Visual
-|-
![1562035570](https://user-images.githubusercontent.com/3827611/60478999-8504c380-9c41-11e9-8b9d-10b3bc2aa4a7.png)|![1562035574](https://user-images.githubusercontent.com/3827611/60479007-87ffb400-9c41-11e9-9b45-2d71bc0ee944.png)
