### ISSUE TITLE
Can't publish private post on self hosted sites

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#12009]
### Expected behavior
If you are working on a self hosted site that is XMLRPC connected you should be able to publish a post that is set to be private.

### Actual behavior
However if you try to publish a new post as private you get an error.
<img src="https://cdn-std.dprcdn.net/files/acc_593859/3ZQtP7" />

I checked out the logs and they say:
"Error publishing post: Sorry you cannot stick a private post."

Note this is only a problem on sites that are not connected to jetpack or wpcom

### Steps to reproduce the behavior
1. Log into a self hosted site that does not have jetpack connected to it
2. Start a new post
3. Go to the settings and change the post to private.
4. Publish the post
5. error will appear.

WordPress 12.6.1 and 12.7
iOS 12.3.1

Thanks @jkmassel  for looking into this with me.

**Comment by elibud** [comment]
Thanks for the report @charliescheer, @diegoreymendez can your team look into this please? Thanks

**Comment by diegoreymendez** [comment]
@elibud - Yep.

@jklausa can you look into this issue please?  Thanks!

**Comment by diegoreymendez** [comment]
I added the "High Priority" label to this one considering the nature of the issue, let's give this one full priority.

**Comment by jklausa** [comment]
Should be fixed by #12024

**Comment by diegoreymendez** [comment]
Thanks for the swift work @jklausa !
