### ISSUE TITLE
Post list: table background is white

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#12007]
### Expected behavior
Table background is grey.

### Actual behavior
Table background is white.

### Steps to reproduce the behavior
Go to Blog Posts. It's easy to notice if there is only one post.

From `develop`:

<img width="400" alt="develop" src="https://user-images.githubusercontent.com/1816888/60208039-92224c80-9814-11e9-9890-b7d6a37656b3.png">

From 12.7:

![12_7](https://user-images.githubusercontent.com/1816888/60208246-03fa9600-9815-11e9-8aa8-015b3636ad10.PNG)

**Comment by ScoutHarris** [comment]
@nheagy - is this you by chance?

**Comment by nheagy** [comment]
Yeah, almost certainly a result of changes for #11683. Will look into it!

**Comment by nheagy** [comment]
Fixed in #12077
