### ISSUE TITLE
Allow contributors to connect to WordPress.com

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#1201]
Provide/test a method that lets a non-Automattic contributor to connect to WordPress.com using a secret generated by http://developer.wordpress.com against at least a single blog.  We may have to disable push notifications and such but at least getting to the blog would be useful.

**Comment by jstart** [comment]
@astralbodies this is a great help to us outside developers.  I think this message should be added to the Mobile Handbook here: https://make.wordpress.org/mobile/handbook/pathways/ios/tutorials-guides/

It wasn't clear that the same login had to be used, so some clarification in the handbook might help other people avoid being confused about that.
