### ISSUE TITLE
Stats: Day/Week/Month/Year: Tapping date bars doesn't change data

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-iOS#12037]
### Expected behavior
When looking at stats in Day/Month/Week/Year, tapping each bar should change the stats shown to reflect the day I'm trying to look at.

### Actual behavior
In some cases, tapping the bar changes which bar is highlighted, but doesn't change the stats shown.

For example, this screenshot shows 1 view and 1 visitor, but the bar selected shows close to 30 visitors.
<img width="389" alt="Screen Shot 2019-07-01 at 4 30 12 PM" src="https://user-images.githubusercontent.com/15107387/60440456-88865380-9c1d-11e9-9f95-345030c8ef21.png">

### Steps to reproduce the behavior
This has been tricky to reproduce, but I've had most luck with opening a site I've looked at stats for recently. Sometimes, the app loads the stats (it will give a loading screen between tapping on bars) and everything is fine. Sometimes, it doesn't try to load anything. 
Tapping the < and > arrows seems to work even when tapping the bars doesn't.

Here's a video:
![statsstuck](https://user-images.githubusercontent.com/15107387/60444108-347f6d00-9c25-11e9-8042-05f5a53e4add.gif)

##### Tested on iPhone SE, (iOS 12.2) running WPiOS 12.6 and 12.7
Four user reports so far, #2127720-zen, #2145011-zen, #2142342-zen, #2145194-zen
More detail on all those reports: https://wp.me/p7cLQ7-Da

**Comment by elibud** [comment]
@danielebogo another one for you, thanks for the report @thehenrybyrd .

**Comment by thehenrybyrd** [comment]
Had another report in #2149095-zen. 
It sounds like you're already working on this, so let me know if I should stop reporting and start telling folks to look out for a fix. 😄

**Comment by thehenrybyrd** [comment]
And another in #2148632-zen

> New stats aren’t working in my app. If I tap another day’s bar graph, it continues to display today’s number.

**Comment by thehenrybyrd** [comment]
One of the original reporters came back with another gif for us in #2142342-zen.
In this case, it seems whenever they open the app and go to stats, they see the stats sticking until they use one of the arrows to move to a different day. https://wp.me/p7cLQ7-Da /#comment-1211

**Comment by danielebogo** [comment]
Thanks @thehenrybyrd ! I'm working on it [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/12041).

**Comment by thehenrybyrd** [comment]
@danielebogo I'm still seeing this issue in the 12.8 beta - can you let me know when this will be live for us to try out?

**Comment by danielebogo** [comment]
@thehenrybyrd this has been fixed in the [12.7.1 release](https://github.com/wordpress-mobile/WordPress-iOS/tree/release/12.7.1) but not merged in 12.8 beta yet. 
@jkmassel is working on `12.7.1 hotfix` submission.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/12041.
