### ISSUE TITLE
Stats: Chart bars take a long time to reflect user interaction

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#12048]
### Actual behavior 

Related to #12037, after tapping a bar in a stats chart (for data that has already been cached), there's a long 1 - 2 second delay before the bar is highlighted to show the tap.

![stats-bar-tap-1](https://user-images.githubusercontent.com/4780/60517313-5e916780-9cd7-11e9-8ecb-23f7375c6094.gif)

### Expected behavior

I would expect the bar highlight to update the instant I tap it to show that I did tap it successfully (even if it takes a moment to update the data labels).

**Comment by jkmassel** [comment]
It looks like the UI is updated after the network requests complete. Watching in the log + simulator, it changes as soon as `Stats: All fetching operations finished` appears.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/12055.
