### ISSUE TITLE
Self-Hosted: Push Notifications fail when self-hosted site is connected via a different WP.com account

### ISSUE THREAD

**Issue by kraftbj** [wordpress-mobile/WordPress-iOS#1204]
When adding a self-hosted site, the app asks for JP WP.com creds for "stats and notifications". If the WP.com account is different than the primary one used in the app, notifications aren't pushed.

Steps to Reproduce:
1. Sign in the app with WP.com Account A.
2. Add a self-hosted site that is connect to WP.com via Jetpack using WP.com Account B.
3. Add WP.com Account B creds when requested during the add self-hosted flow.
4. Attempt an act on the site that should trigger a notif (tested by adding a comment in an incognito window without logging into WP.com or the self-hosted site)
5. No notif is pushed.

To confirm:
1. Disconnect/reconnect self-hosted site to WP.com using Account A.
2. Remove and reconnect self-hosted site within the app, using the pre-filled WP.com Account A creds.
3. Repeat step 4 above.
3. Notif pushed.

**Comment by jleandroperez** [comment]
Closing this one for now. We'll revisit (when / if) multiple dotcom account support is added.

Thanks everyone!
