### ISSUE TITLE
Make NoResultsViews consistent in terms of including trailing period in titles

### ISSUE THREAD

**Issue by jklausa** [wordpress-mobile/WordPress-iOS#12042]
As noted in #11997, and expanded by @yaelirub in this comment: https://github.com/wordpress-mobile/WordPress-iOS/issues/11997#issuecomment-506560583 we're incredibly inconsistent when it comes to including trailing periods in No Results Views messages.

We should decide on one style and update it across all the screens.

## Samples

| Location | Screenshot |
|--------|-------|
| Notifications   | <img src="https://user-images.githubusercontent.com/198826/60535656-e40a1d00-9cc1-11e9-9eef-7bd8cda39832.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60535716-013eeb80-9cc2-11e9-9b7f-e65f32d09e79.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60536084-cab5a080-9cc2-11e9-8016-18228cc11d55.png" width="120">| 
| Pages | <img src="https://user-images.githubusercontent.com/198826/60535785-229fd780-9cc2-11e9-909a-08fe13eb7f2d.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60535786-229fd780-9cc2-11e9-80b4-93f14c08afa8.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60535787-229fd780-9cc2-11e9-845e-2b4a46e47a63.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60536383-592a2200-9cc3-11e9-8ea9-c91ff09c9ffc.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60535745-0bf98080-9cc2-11e9-8f53-03daa3689097.png" width="120">  | 
| Posts | <img src="https://user-images.githubusercontent.com/198826/60535807-2df30300-9cc2-11e9-927b-87e8d73013fa.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60535811-2df30300-9cc2-11e9-8c0a-212b60d7142d.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60535813-2e8b9980-9cc2-11e9-9b32-9561b1b363b4.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60535814-2e8b9980-9cc2-11e9-91c5-ab96fec9b9b4.png" width="120"> | 
| Site | <img src="https://user-images.githubusercontent.com/198826/60536109-d608cc00-9cc2-11e9-8b7d-247e03e7518e.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60536223-05b7d400-9cc3-11e9-94ce-cf0c06b56d12.png" width="120"> | 
| Reader | <img src="https://user-images.githubusercontent.com/198826/60536188-f2a50400-9cc2-11e9-9a43-48c2354140b6.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60536189-f2a50400-9cc2-11e9-894d-7517eaf5d1bc.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60536190-f2a50400-9cc2-11e9-985c-82727e95b21d.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60536191-f33d9a80-9cc2-11e9-87f8-ef4f47310376.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60536192-f33d9a80-9cc2-11e9-96ea-644b3499caae.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60536193-f33d9a80-9cc2-11e9-9c59-4dd9ed564ec2.png" width="120"> | 
| Quick Start | <img src="https://user-images.githubusercontent.com/198826/60536236-0e100f00-9cc3-11e9-84b1-be116df89d70.png" width="120"> | 
| Comments | <img src="https://user-images.githubusercontent.com/198826/60536261-1700e080-9cc3-11e9-9467-18b4d110c433.png" width="120"> | 
| Media Library | <img src="https://user-images.githubusercontent.com/198826/60536297-2e3fce00-9cc3-11e9-9799-1a2789f52f55.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60536298-2e3fce00-9cc3-11e9-8b6a-6039ebb06f19.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60536299-2ed86480-9cc3-11e9-9a50-94c979b91926.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60536300-2ed86480-9cc3-11e9-953f-0ba778100a5f.png" width="120"> | 
| Menus | <img src="https://user-images.githubusercontent.com/198826/60536331-3bf55380-9cc3-11e9-8b4e-4203de7ef826.png" width="120"> | 
| Activities | <img src="https://user-images.githubusercontent.com/198826/60536345-444d8e80-9cc3-11e9-9be4-acb1b72c08fa.png" width="120"> | 
| Domain Credit | <img src="https://user-images.githubusercontent.com/198826/60536363-4e6f8d00-9cc3-11e9-998f-2c9eb6061ef6.png" width="120"> | 
| People | <img src="https://user-images.githubusercontent.com/198826/60536396-634c2080-9cc3-11e9-8893-69031c8b120c.png" width="120"> <img src="https://user-images.githubusercontent.com/198826/60536397-634c2080-9cc3-11e9-97f7-77bee227917a.png" width="120"> |

**Comment by yaelirub** [comment]
We need to look at some guidelines.

**Comment by shiki** [comment]
@yaelirub I assumed the decision was already made by https://github.com/wordpress-mobile/WordPress-iOS/issues/11997#issuecomment-506047116:

> No punctuation on buttons, naturally, though I feel like our sentences here need terminal punctuation. Also, button text is sentence case per the brand guide.

I guess I may have misunderstood. How do we proceed with this then?

**Comment by shiki** [comment]
I gathered a big sample of the NoResultsViews and updated the description with screenshots. ☝️ I stopped here because it looked counterproductive to continue. 😄 

### Observation 

Most of them do not have terminal punctuations. Some have periods and exclamation marks. Should we change all of them to have terminal punctuations?

I'll request input from Editorial. I'm sure they can answer this question better than me. 😅

**Comment by michelleweber** [comment]
Okay! So:

- Buttons are sentence case, so there are some that need to have capital letters removed.

- For things like "No comments yet," it depends on whether these are regular copy or headlines. If they're copy, they should all have terminal punctuation. If they're headlines, none of them should have terminal punctuation except for a few with exclamation points. I'm assuming these function like headlines, so I'd say no terminal punctuation. For the few that are longer full sentences, like domain credits, I'd re-do the screen to make them shorter and more in line with the others. 

- Everything between the headline and the button is regular text and gets normal punctuation, including terminal punctuation.

**Comment by shiki** [comment]
Thank you for the response, @michelleweber. 

In the case of search results like this:

<img src="https://user-images.githubusercontent.com/198826/60536383-592a2200-9cc3-11e9-8ea9-c91ff09c9ffc.png" width="180">

Is that still considered as a headline?

> Buttons are sentence case, so there are some that need to have capital letters removed.

Would you be able to point out some of them so I can understand more? 🙂 Thank you!

**Comment by shiki** [comment]
Moving this to _Ready for Dev_. But note that it's a low priority issue. I think we can request for copy review for each piece we work on.

**Comment by michelleweber** [comment]
I'd consider that a headline in this context, yes.

For other screens with long "headlines," specifically the Add a Site and Domain Credit screens, I'd want to see a shorter headline with no punctuation; right now there are full sentences acting as headlines.

REL the button capitalization, it's all the buttons that say Create a Page, Create a Post, Create a Tag -- page, post, and tag aren't proper nouns and wouldn't normally be capitalized in regular text, so they wouldn't be capitalized on buttons, either.
