### ISSUE TITLE
Posts List: cannot search for posts using words from the post body

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12064]
### Expected behavior

I expected to be able to search the posts list using words either from the post title or body.

### Actual behavior

I can only search posts using words from the post titles.

### Steps to reproduce the behavior

1. Go to Blog Posts.
1. Toggle the view to "Everyone" (this will also work if you're just viewing your own posts but only if your search is for a post you authored and the everyone filter should catch everything).
1. Try searching for a word used in a post body that is not also used in the post's title.

<img src="https://user-images.githubusercontent.com/1119271/60631850-f74ee280-9dbe-11e9-86da-503849ce6ff5.PNG" width="270" alt="IMG_2877"> <img src="https://user-images.githubusercontent.com/1119271/60631853-f918a600-9dbe-11e9-8e9f-93321827a825.PNG" width="270" alt="IMG_2876">

<sup>Tested with WP Internal 12.8.0.20190701 on iPhone 6S iOS 12.3.1.</sup>

<sub>(internal note: found while testing p4a5px-2pn-p2, 2096224-zen)</sub>

**Comment by designsimply** [comment]
I ran into this again while testing 14.6 beta. It happens for pages as well.

Posts List search in the app | Posts List search on the web
--- | ---
<img src="https://user-images.githubusercontent.com/1119271/79028000-a50bd080-7b4b-11ea-8101-97c6d21d7dc1.PNG" width="200" alt="IMG_3771"> | <img src="https://user-images.githubusercontent.com/1119271/79028001-a6d59400-7b4b-11ea-8544-9aa471ad5bbc.PNG" width="200" alt="IMG_3772">
<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.1 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

**Comment by eduardozulian** [comment]
Another case in 3617174-zen

**Comment by poojashetty18** [comment]
Another report on 4116891-zen

**Comment by reginabally** [comment]
Another report in 4345076-zd-woothemes

**Comment by kean** [comment]
This has been fixed in the scope of the https://github.com/wordpress-mobile/WordPress-iOS/pull/21744 project. It will now support full-text search. The change is coming in 23.6 (tentatively).
