### ISSUE TITLE
Domain Registration: blogger plan offering non .blog domains

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#12063]
### Expected behavior
When you purchase the blogger plan on a WordPress.com account you are able to register a free .blog domain to your site, but you are not able to use any other TLD.  If you have purchased the blogger plan and try to register your domain from with in the app, I would expect that you would only be given the option to register .blog domains.

### Actual behavior
If you go to the domain registration section of the WordPress app with a blogger plan you are offered multiple different TLDs (in my case I wasn't even offered a .blog domain)  
<img src="https://cdn-std.dprcdn.net/files/acc_593859/5e4Gp7" />

If you select one of the domains that are being suggested by the WordPress app and try to register it you get a non discript error.
<img src="https://cdn-std.dprcdn.net/files/acc_593859/1DNQUL" />

(error translation: A problem when purchasing your domain.  Try again.")

### Steps to reproduce the behavior
1. Get a site with a new blogger plan that still has a domain credit
2. Go to My Site > Claim your free domain
3. See that suggested domains are not .blog
4. Select one of the non .blog domains
5. try to register that domain

##### Tested on [device], iOS [version], WPiOS [version]
WordPress 12.6.1
iOS 12.3.1
iPhone 8

**Comment by elibud** [comment]
@jklausa can you please look into this one?

**Comment by rachelmcr** [comment]
As discussed in Slack last week, this will likely require some backend changes to support only returning the appropriate TLDs for domain searches with the Blogger plan. (Internal discussion: paCL20-dh-p2)

**Comment by rachelmcr** [comment]
I checked and we should be able to resolve this without any backend changes. The domain suggestions endpoint includes a `tlds` parameter we can use to restrict the suggestions to one or more specific TLDs (in this case, the .blog TLD).

cc @jklausa

**Comment by jklausa** [comment]
This should be fixed in 12.9 now :)
