### ISSUE TITLE
Reader posts show grey boxes for images when in airplane mode.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#1207]
If the app is offline and there is no cached image we shoud either have a nice placeholder to display or just not show the images. These are mostly the 'featured' images in the post list and at the top of the post detail in the reader.

**Comment by rachelmcr** [comment]
Tested and confirmed that in beta v. 5.8.0.20151124 we're still showing grey boxes like this in place of images when offline:

![2015-11-26 17 46 17](https://cloud.githubusercontent.com/assets/8658164/11428674/e402b1e0-9465-11e5-8306-4ce37e5e7090.png)

**Comment by kurzee** [comment]
This would be good to revisit for both the cards refresh and detail refresh.

**Comment by bummytime** [comment]
I am going to close this issue for now. The reader does not show these grey boxes in airplane mode anymore: 

<img width="286" alt="card" src="https://user-images.githubusercontent.com/154014/35738065-4bf3a054-07f3-11e8-9c04-99814f4791a0.png">
<img width="286" alt="detail" src="https://user-images.githubusercontent.com/154014/35738069-4ef1a47c-07f3-11e8-8afb-4f05e76e41a5.png">

And as soon as network conn is turned back on, the images are loaded as expected.
