### ISSUE TITLE
Double draft post created when saving as draft after video upload failed

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/WordPress-iOS#12073]
### Expected behavior
Just one draft post is created.

### Actual behavior
Two draft posts are created

### Steps to reproduce the behavior
- Start a new post (Aztec or Gutenberg)
- Add a video from the camera roll
- While it is uploading, turn off network connection to make the upload fail
- With the network off, save the post as Draft without leaving the post
- Turn network connection back on - the video will start uploading again
- When the video finishes uploading, two posts will be created and saved as draft
- Check on web that two posts were created or go back to the post list and pull to refresh.

##### Tested on iPhone XS, iOS 12.3.1, WPiOS 12.8 Internal

**Comment by shiki** [comment]
This could be related to https://github.com/wordpress-mobile/WordPress-Android/issues/9845 where we found that:

1. The post could have been uploaded and received by the server. Hence, a post in the server was created.
2. The client (app) did not receive the server response and assumed the post was not created. 

So, the client will try the upload again, creating another post.

**Comment by kean** [comment]
This system was re-implemented in 24.9 – closing as obsolete.
