### ISSUE TITLE
[Stats Refresh] Posts and Pages > View more: list truncate to 10 posts when switching to landscape

### ISSUE THREAD

**Issue by ersatzpenguin** [wordpress-mobile/WordPress-iOS#12072]
User reported an issue with the post display under Stats in the WordPress.com iOS App.

### Expected behavior
All posts will list correctly in landscape stats view and scroll down as normal.

### Actual behavior
Upon switching to landscape, list is truncated to 10 posts and scrolling past that is not possible without refreshing the page by pulling down from the top.

Switching back to portrait does not fix the issue, and also requires refreshing the page.

Issue does not appear if you start in Landscape mode.

### Steps to reproduce the behavior
1. Go to Stats
2. Switch view to "Days" or another time-based view.
3. Click "View More" to see the full "posts and pages" list.
4. Switch to landscape mode.

**Comment by ScoutHarris** [comment]
Thanks @ersatzpenguin ! We'll take a look.

**Comment by ScoutHarris** [comment]
Fixed with #12083 .
