### ISSUE TITLE
Stats Refresh: top right navigation arrows are sometimes difficult to tap

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12080]
Steps to reproduce:

1. Start with a WordPress.com or Jetpack site that has more than a year's worth of stats.
1. Go to Stats > Insights > This Year > View more to reach the "Annual Sites Stats".
1. Tapp the arrows at top right to navigate.

<strong>Result:</strong> I found the navigation arrows a bit difficult to trigger at times. They do work, it's just you have to tap on them exactly perfectly and for whatever reason I don't always seem to hit the tap target easily. Note: I am not sure if this is user error :) or possibly something to do with my device (it's an older iPhone 6S).

Would it be possible to make the tap targets bigger for the navigation arrows at top right that appear on some stats screens?

<img src="https://user-images.githubusercontent.com/1119271/60842934-90e90c00-a192-11e9-834f-0d0129c258b7.PNG" width="270" alt="IMG_2884">
<sup>Tested with WP Internal 12.8.0.20190701 on iPhone 6S iOS 12.3.1.</sup>

**Comment by ScoutHarris** [comment]
Hey @designsimply . Thanks, we'll take a look.
