### ISSUE TITLE
Logs: Redact magic link tokens from logs.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#12081]
Title has it.  Our logging for when the app is launched via a URL includes the full URL for a magic link: 
`2019-07-08 14:26:02:691 Application launched with URL: wpinternal://magic-login?token=` 

We need to be redacting the token.

**Comment by designsimply** [comment]
Okay, I (sheepishly) admit this was filed because of me 😊 but only for a test user account. Thank you for spotting it and raising the issue @aerych ! @jkmassel can you take a look at this for 12.9 ?
