### ISSUE TITLE
Previewing a draft post with published status, publishes the post.

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#12100]
As part of  the work done on [deprecating local preview,](https://github.com/wordpress-mobile/WordPress-iOS/issues/9282) we are forcing an upload of the post before providing the user with a preview link to view it.

If the user manually updates the post status to published in Post Settings and then asks to preview the post, the upload will end up publishing the post.

## Proposed solution:
Use auto save instead of upload for WPCom posts and check if the post.status  == "draft" like:
```
if post.blog.isWPCom() {
    post.autosave()
} else if post.status == "draft" {
    post.upload()
} else {
    show("preview not supported")
}
```
 cc: @diegoreymendez

**Comment by diegoreymendez** [comment]
This is resolved.
