### ISSUE TITLE
Replace WPUplaodStatusButton with LoadingStatusView

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#12101]
In https://github.com/wordpress-mobile/WordPress-iOS/pull/12031 we have added a new class LoadingStatusView which we are using to display the upload status in the navigation bar using autolayout instead of frames and so easier to customize.

**Comment by chipsnyder** [comment]
Closing this out as I don't see any instances of WPUplaodStatusButton referenced in the Repo https://github.com/wordpress-mobile/WordPress-iOS/search?q=WPUplaodStatusButton
