### ISSUE TITLE
Site Creation: Review "Next" button ambiguity.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#12117]
In step 2 (Basic Info) when the title field has focus, the virtual keyboard is showing a "Next" button, which is the default in iOS for moving the focus to the next field.

This was introduced in: https://github.com/wordpress-mobile/WordPress-iOS/pull/12095

But even if standard, this change brought some ambiguity since we already had a button right above the virtual keyboard named "Next", which would allow the user to move right ahead to the next screen.

This needs some design review to figure out how to resolve this ambiguity.

<img width="439" alt="ambiguousNext" src="https://user-images.githubusercontent.com/1836005/61148785-ef292e00-a4b5-11e9-86c0-e871e15e4380.png">

**Comment by diegoreymendez** [comment]
One suggestion could be to rename the button to "Done" which is what's shown in the virtual keyboard if the last field has focus.

**Comment by yaelirub** [comment]
Would changing the keyboard "next" to "continue" help?
Or possibly changing the copy on the button to be "Next Step"?

**Comment by diegoreymendez** [comment]
Could be!  At this point I'm gathering up several issues to tackle this as part of a next iteration of Site Creation starting with a design review.

**Comment by antonis** [comment]
This screen has been deprecated with the latest changes of the site creation flow
