### ISSUE TITLE
Post "More" menu options are not consistent

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#12113]
Spun off: https://github.com/wordpress-mobile/WordPress-iOS/pull/12087
### Expected behavior
When tapping on the 3 dots menu in the post list when the card is expended will show the following options:
- Stats
- Move to draft
- Move to trash
- Cancel

### Actual behavior
More menu options show:
- Move to draft
- Delete Permanently

### Steps to reproduce the behavior
1. Tap on the list view icon to show the post row (only title and date)
3. Tap on the 3 dots menu
4. Choose "Move to trash"
5. Tap on the list view icon to show the post card (expended post view)
6. Choose Undo on the post you deleted before
7. Tap on the More menu
8. Wrong options come up 

![deleting_in_list](https://user-images.githubusercontent.com/1335657/61094588-b41af200-a404-11e9-9b51-0aab360e9e46.gif)

##### Tested on [device], iOS [version], WPiOS [version]
iPhone Xs simulator 12.2

**Comment by kean** [comment]
This has been address in the scope of https://github.com/wordpress-mobile/WordPress-iOS/pull/21744. The change is coming in 23.6 (tentatively).
