### ISSUE TITLE
Signup: VoiceOver: username edit page could have a description about how it works

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12118]
Steps to reproduce:

1. Log out of the WPiOS app.
1. Go to Settings > General > Accessibility > VoiceOver and toggle the setting on.
1. Go to WPiOS and double tap the "Sign up for WordPress.com" button.
1. Follow the prompts until you reach the "New Account" screen.
1. Tap the "Username" label.
1. ⚠️ It should read: "Username, {the user name}. Button – Double tap to edit."
1. ⚠️ Try to understand how the edit username screen works with eyes closed.

**Result:** the edit username page could have a description about how it works. You have to search with the username you are interested in and then choose one of the proposed usernames. This is difficult to understand when exploring with VoiceOver only. A description could be added as a label or hidden as a hint. ([35s](https://cloudup.com/cOZNHv8DTnJ))

**Note:** also "double tap to edit" is not read out when you tap the "Username" field on the previous screen. When the username field is tapped it should read: "Username, {the user name}. Button – Double tap to edit."

<img src="https://user-images.githubusercontent.com/1119271/61161236-39afa800-a4c0-11e9-8c73-c60146796872.png" width="270" alt="voiceover-new-account-username-field">
<sup>Tested with WP Internal 12.8.0.201907011 on iPhone 6S iOS 12.3.1.</sup>

<p style="clear:both;"><sub>(internal reference: p77Llu-bQ6-p2 h/t @etoledom)</sub></p>

**Comment by ScoutHarris** [comment]
Hey @designsimply . The Signup Epilogue has been refactored. It's been a while, so I don't recall exactly what VO says now. I'll give it a listen though and see how it's doing.

**Comment by mindgraffiti** [comment]
This is fixed as of WPiOS 15.7. See also: https://d.pr/v/geCq52

**Comment by mindgraffiti** [comment]
If you were checking out my droplr link, it was blocked. I updated it so it should work now.
