### ISSUE TITLE
[Auto-upload Published] Safety: Content hash and timeout for offline actions

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#12136]
Parent issue: #12240. 

Came up on: #9555 (comment)

## Goal 

The goal is to avoid auto-uploading posts if the user has not **confirmed** publishing by pressing the _Publish_ button in the editor.

The work should be targeting the master branch, `issue/12240-master-branch`.

## Known Tasks 

- [x] Use content hash code to decide if the user has confirmed publishing/uploading. The example is what @malinajirka prototyped in https://github.com/wordpress-mobile/WordPress-Android/commit/024436d78cf8028247a9f6e62ac7dc21aef78c2d. The code for the content hash code can be seen in this PR https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1328.
- [x] Do not auto-upload if the post's modified date is greater than 2 days.

## Matching Android Issue

https://github.com/wordpress-mobile/WordPress-Android/issues/10214

**Comment by shiki** [comment]
Moving this to Backlog. It's planned as part of #12240. 

To note: 1 idea is to use content hash codes like what @malinajirka prototyped in https://github.com/wordpress-mobile/WordPress-Android/commit/024436d78cf8028247a9f6e62ac7dc21aef78c2d.

**Comment by shiki** [comment]
Completed by #12347 and #12352. Thank you, Jan!
