### ISSUE TITLE
Quick Start v2: VoiceOver: highlighted cells with pulsing dot are missed

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12131]
Steps to reproduce:

1. Go to Settings > General > Accessibility > VoiceOver and toggle the setting on.
1. Open a site in the app which has Quick Start v2 enabled or create a new site and select the option for quick start at the end of Site Creation ([screenshot](https://user-images.githubusercontent.com/1119271/61245040-d95f7700-a708-11e9-84ea-7ad966003389.png)).
1. Double tap any checklist item.
1. Notice there's a pulsating dot that is not recognized by VoiceOver.

**Result:** the highlighted cell (with that nice dot) is completely missed by VoiceOver. It could communicate that the highlighted cell was found. ([9s](https://cloudup.com/cXboKBw2ays))

<img src="https://user-images.githubusercontent.com/1119271/61247716-d2d3fe00-a70e-11e9-8073-4abd5990e0f2.png" width="270" alt="wpios-quick-start-highlighted-cell-with-pulsing-dot">
<sup>Tested with WP Internal 12.8.0.201907011 on iPhone 6S iOS 12.3.1.</sup>

<p style="clear:both;"><sub>(internal reference: p77Llu-bQ6-p2 h/t @etoledom)</sub></p>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
