### ISSUE TITLE
EXC_BREAKPOINT: Attempting to mutate immutable collection! > removeObject: XPC API Misuse (iOS 13 only)

### ISSUE THREAD

**Issue by JavonDavis** [wordpress-mobile/WordPress-iOS#12154]
Sentry Issue: https://sentry.io/share/issue/97123a91aa564239a4a3af7ae4f24712/

```
EXC_BREAKPOINT
Release of last reference on a suspended connection. > XPC API Misuse: %s > XPC API Misuse: Release of last reference on a suspended connection.
```

This issue only happens on iOS 13. **After accessing the Sentry Issue, filter events for those happening on iOS 13, all other events are unrelated to this issue.**

**Comment by JavonDavis** [comment]
It's iOS 13 so this may or may not disappear but just opening this for visibility. The crash happened when playing around with the block editor while editing a post.

**Comment by designsimply** [comment]
**30-day impact:** ~60 per day
**Users affected:** 12 in the last 30d
**First seen in:** 12.5.1
**Last seen in:** 12.8.1

<sup>https://sentry.io/share/issue/97123a91aa564239a4a3af7ae4f24712/</sup>

**Comment by designsimply** [comment]
**90-day impact:** ~4 per day
**Users affected in the last 90 days:** 215

<sup>https://sentry.io/share/issue/97123a91aa564239a4a3af7ae4f24712/</sup>

**Comment by designsimply** [comment]
**Events in the last 90 days:** 487
**Users affected in the last 90 days:** 56

<sup>https://sentry.io/share/issue/97123a91aa564239a4a3af7ae4f24712/</sup>

**Comment by designsimply** [comment]
The crash at https://sentry.io/organizations/a8c/issues/1065702493/?project=1438083 only happened 2 times in the last 30d.

Searching Sentry for `"XPC API Misuse"` or `"Attempting to mutate immutable collection" ` or `"Release of last reference on a suspended connection" ` returned zero results.
