### ISSUE TITLE
Analytics: need more info about the `install_jetpack_remote_failed` stat for debugging Jetapack Install failures

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12158]
We are seeing ~180 failed Jetpack Install requests per day in the `install_jetpack_remote_failed` stat (internal reference: p4a5px-2pQ-p2#comment-9969).

Can we please add add the site URL to the tracks props for success and failure events? This will allow for qualitatively debugging install issues by looking at the actual login screen.

Is there anything else we can add to the error logs to help debug Jetpack Install failures? (also see internal reference: p7cLQ7-Dx-p2#comment-1252).

h/t @gravityrail for the suggestion!

**Comment by frosty** [comment]
cc @danielebogo

**Comment by danielebogo** [comment]
@frosty @designsimply maybe the error message if it does exist?
