### ISSUE TITLE
Stats: Inconsistent borders on backgrounds

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#12152]
While examining some of the new color work I noticed that in the new Stats design, the borders on tops of the "cards" that contain each section are larger than the borders on the bottom. When viewing 3x screenshots, the bottom border is 1 actual px tall, but the top border is 2px. I think in iOS terms that's 0.5px and 1px, but I'm not sure. The smaller border is the correct one, as it's consistent with what's seen in other sections of the app.

As seen on this screen (PII removed):
![Artboard](https://user-images.githubusercontent.com/1396552/61414504-1e77da80-a8bc-11e9-9352-30fab33a959a.png)

Zoomed in with a pixel grid turned on:
<img width="1075" alt="Screen Shot 2019-07-17 at 5 52 08 PM" src="https://user-images.githubusercontent.com/1396552/61414535-35b6c800-a8bc-11e9-83ab-f1cbd4c2114f.png">
<img width="1641" alt="Screen Shot 2019-07-17 at 5 57 24 PM" src="https://user-images.githubusercontent.com/1396552/61414601-5a12a480-a8bc-11e9-8c3a-b899bfea84db.png">

**Comment by ScoutHarris** [comment]
Hey @mattmiklic . @SylvesterWilmott had already mentioned this to us. Thanks for creating an issue (sorry, there wasn't one already). If I don't get to it sooner, it'll be fixed during the upcoming Hack Week.
