### ISSUE TITLE
Scroll Indicator not visible on login epilogue screen

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#12162]
#11791 # Expected behavior
After logging in, if I have a long list of sites, I'd expect to be able to scroll through them and see the scroll indicator fully.

### Actual behavior
The scroll indicator is mostly off-screen. 

### Steps to reproduce the behavior
1) Log into any WordPress.com account.
2) Scroll within the list of sites (only tested on iPhone Xs hardware and simulator)
3) Note the lack of (or very hard to see) scroll indicator

### Potential Solution
I haven't researched this issue deeply, but I wonder if it's related to the site list being pinned to the device edges instead of the safe area insets? 
 
![IMG_7EDAF672F3FF-1](https://user-images.githubusercontent.com/1123407/61481290-2899e780-a955-11e9-8251-96f67e00e030.jpeg)

![Simulator Screen Shot - iPhone Xs - 2019-08-30 at 13 17 35](https://user-images.githubusercontent.com/1123407/64046413-0f29b500-cb29-11e9-9015-6bbfe59ceb9e.png)

^^^ This screenshot is redacted – it only shows the scrollbar. In the original, all rows looked fine.

**Comment by ScoutHarris** [comment]
This view was replaced with the [new Login Epilogue](https://github.com/wordpress-mobile/WordPress-iOS/issues/13413), which resolved this issue.
