### ISSUE TITLE
Update error message when entering an invalid site address

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12188]
In https://github.com/wordpress-mobile/WordPress-Android/pull/10255, we received feedback from Editorial about the error message shown when entering an invalid site address.

## Steps to show the message

1. Log out
2. Click on Login → Log in by entering your site address
3. Enter an invalid site address like "@&%"
4. Wait 2 seconds. The error message should be shown.

## Tasks 

The error message and title should match the Android error message as shown in https://github.com/wordpress-mobile/WordPress-Android/pull/10255#issuecomment-513881507:

<img src="https://user-images.githubusercontent.com/198826/61654289-5777cc80-ac79-11e9-9dde-1c3af53bb512.png" width="320">

- [ ] Update the error message to `"Please enter a complete website address, like example.com."`.
- [ ] Update the title to `"Enter the address of the WordPress site you'd like to connect."`.

**Comment by lorenzolewis** [comment]
I can take this up. I haven't worked with any localization before, do I need to do anything for translations and localizations?

**Comment by jkmassel** [comment]
Thanks for the offer @lorenzolewis! Just ensure the error message is wrapped in `NSLocalizedString()`, and the release tooling will handle the rest! 

If you have any questions, feel free to ask here!
