### ISSUE TITLE
Don't store passwords for WordPress.com

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#1220]
Since we're using OAuth2, we shouldn't be storing the user's password. According to [RFC 6749 #4.3.1](https://tools.ietf.org/html/rfc6749#section-4.3.1):

> The client MUST discard the credentials once an access token has been obtained.

Besides following the standard, this is interfering with #269: if the master password is sent, some parts of the API will fail, even if there's a valid OAuth2 authorization header.

This would probably make obsolete: #488, #422, #965 .

**Comment by koke** [comment]
@jleandroperez thanks for taking good care of this one ;)

![](https://26.media.tumblr.com/tumblr_ll89ciVyjS1qdmeauo1_500.gif)

**Comment by jleandroperez** [comment]
@koke thank you sir! i'm glad you liked the PR! :heart:
