### ISSUE TITLE
“Clear Device Media Cache” doesn't clear everything 

### ISSUE THREAD

**Issue by AtrumGeost** [wordpress-mobile/WordPress-iOS#12218]
Hi folks!

I had a user who's WordPress.com app was using around 21.4 GB. We asked the user to go to **Me > App Settings** and select **Clear Device Media Cache**.

Also, we verified the user didn't have any offline drafts.

### Expected behavior
We expected the app to delete any local content it could be storing.

### Actual behavior
Even though the app was using a lot of space the "Media Cache Size" was "Empty". And selecting **Clear Device Media Cache** didn't help.

### Workaround

Re-installing the WordPress.com deleted the local content and the storage the app was using was reduced to 81.7 MB. 

### Steps to reproduce the behavior
There aren't specific steps for this. This happens over regular use and—I'm guessing—the constant upload of images to the WordPress.com site via the app.

##### Tested on iPhone 7, iOS 12.3.1, WPiOS 12.8.2
(User's devive info)

For internal reference: p1564148616088500-slack-mobile-support

**Comment by frosty** [comment]
Should be fixed by #12241
