### ISSUE TITLE
Repeating notices about failed uploads

### ISSUE THREAD

**Issue by jklausa** [wordpress-mobile/WordPress-iOS#12213]
We've gotten a report from number of users (2204495-zen, https://ios.forums.wordpress.org/topic/strange-behavior-with-uploading-pics#post-15436) about them repeatedly seeing notices in the format of "1 post, 1 file not uploaded", which are probably connected to the recent changes to how we handle file uploads.

**Comment by thehenrybyrd** [comment]
Here's another report in #2212383-zen. URL reachability logs are noted there.
@jklausa Are there any extra details we can be gathering to make your work easier here?

**Comment by jklausa** [comment]
@thehenrybyrd The logs from #2212383-zen seem to point to the same issue as before, so that's good.

If everything will go well, this should get merged into the release that goes out on Monday! I'll try to keep y'all posted on here in Slack.

**Comment by jkmassel** [comment]
I'm moving this issue's milestone forward to `13.1`, which is the next unfrozen release branch. If we need have a fix prepared sooner, please merge it into `release/12.9` or `release/13.0` and DM me and I'll be happy to include it in a beta or hotfix, as required.

**Comment by designsimply** [comment]
Another case:

> I keep getting the error: "1 post, 1 file not uploaded retry?" It happens constantly when updating or uploading media to a draft post. I’ve therefore not published it in case it’s incomplete.

<sup>(internal reference: 2213448-zen) cc @charliescheer p1564506124053600-slack-cellular-happiness</sup>

**Comment by ivan-ottinger** [comment]
Another report: #2247839-zen

→ Asked the user which version of app they are using.

**Comment by sirbrillig** [comment]
FWIW I'm still experiencing this in 12.9.1, except that now the notices also appear as banners and on the lock screen instead of only when opening the app. I haven't used the app to write a post in months (years?) so presumably this is a notification from some ancient post.

**Comment by designsimply** [comment]
Re-opening until the merge for the new PR goes through.

**Comment by jklausa** [comment]
There will be two additional mitigations in 13.0, which should _for realsies_ this time fix this.

**Comment by designsimply** [comment]
I haven't been able to see the repeated failed upload notices "1 post, 1 file not uploaded" in testing. @sirbrillig 13.0 has been released, are you still seeing failed upload notices in banners and on the lock screen?

**Comment by sirbrillig** [comment]
@designsimply I had to re-log in with the update, but it seems to be fixed now! 🎉 Thank you!

**Comment by jklausa** [comment]
I think the mitigation in 13.0 did it. Closing for now, will reopen if there are more issues noticed.
