### ISSUE TITLE
[Post List] Add "+" icon to navigation bar

### ISSUE THREAD

**Issue by SylvesterWilmott** [wordpress-mobile/WordPress-iOS#12219]
The new post list uses a view changer in the upper right-hand corner of the screen which has replaced the "+" button / the action to create a new post.

Let's re-include the "+" button to the top right corner:

<img width="400" alt="Screenshot 2019-07-29 at 11 28 04" src="https://user-images.githubusercontent.com/36532468/62041604-f52c4800-b1f3-11e9-8501-86212961d689.png">

**Comment by frosty** [comment]
Also merged into 12.9: https://github.com/wordpress-mobile/WordPress-iOS/pull/12222
