### ISSUE TITLE
iOS and Android: Consistent messaging in Publicize to Facebook

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12228]
This is a link to the main issue which describes the changes for both iOS and Android: https://github.com/wordpress-mobile/WordPress-Android/issues/10278.

**Comment by cerezo074** [comment]
Hi there, I would like to help you with this issue specially with the ios part first. can I?

**Comment by shiki** [comment]
@cerezo074 Please do! Thank you!
