### ISSUE TITLE
Post Settings: Screen underneath editor is visible when adding a tag in post settings

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#12232]
### Expected behavior

I expect the Post Settings > Tags screen to be full screen.

### Actual behavior

At the top of the Tags screen, you can see the screen underneath the editor (e.g. the My Sites screen) bleeding through above the tags text field:

![2019-07-30 13 08 53](https://user-images.githubusercontent.com/8658164/62131116-6e9a6800-b2d2-11e9-8d14-7dc0da7ac880.png)

The screen you see there is whatever screen you were on before opening the editor.

### Steps to reproduce the behavior

1. Go to the My Sites screen in the app and select a site.
2. Start a new post.
3. Open the Post Settings.
4. Open the Tags section.

Result: The My Sites screen is visible at the top of the Tags screen, above the text field.

**Comment by rachelmcr** [comment]
This was also reported by a TestFlight beta tester (iPad Pro (11-inch), iOS 13.0). I tested in the internal beta 13.1.0.20190814 and confirmed this is still an issue there.

**Comment by designsimply** [comment]
I also ran into this bug while beta testing 13.1—in my case I can see the Post List menu items on the Tags screen and those shouldn't be there.

<img src="https://user-images.githubusercontent.com/1119271/63204083-a551db80-c051-11e9-87f0-037d84cdfc21.PNG" width="270" alt="IMG_2944">
<sup>Tested with WP Internal 13.1.0.20190814 on iPhone 6S iOS 12.4.</sup>

**Comment by rachelmcr** [comment]
Closing as this is no longer happening. I now see this explanatory text at the top of the Tags screen:

> Tags help tell readers what a post is about.
> Separate different tags with commas.
