### ISSUE TITLE
Make WordPress a client for feed:// URLs

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#1225]
When a user taps a link in Safari that is an RSS feed (prefix of feed://) make WordPress be an option for launching it.  We can add it to the user's Reader if they're signed in, otherwise let them view the feed via logged out Reader.

**Comment by astralbodies** [comment]
@aerych - is this something we could still consider doing?

**Comment by aerych** [comment]
Thanks for surfacing this one.  Let's keep the issue open and I'll have a look at it along with #5149

**Comment by aerych** [comment]
Closing this one.  Not on the radar in the foreseeable future.
