### ISSUE TITLE
[Auto-upload Published] Page list does not automatically update

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12280]
Part of #12240. 

Use the `issue/12240-master-branch` master branch commit 9813fd087550e804862d9105ef3c890b902c2849. 

When a page draft is automatically uploaded, it stays in the Drafts list. The Drafts list only gets updated when you navigate away from it. 

Please see [this video (37 sec)](https://drive.google.com/file/d/1p486h7nIV9AqTlPk5bE4mSybJNrG4kRy/view?usp=sharing).

## Steps 

1. Go offline.
2. Navigate to a Site → Pages.
3. Create a page and publish it.  A notice with an error will be shown. 
4. `00:06` The page will be shown in Drafts as expected.
5. `00:10` Go online. The auto-uploader should automatically upload the page in the background. There is currently no UI feedback for this. ⚠️ 
6. `00:19` A notice that says the page was published will be shown. The page is still in the Drafts list. This is **incorrect**. Pulling to refresh does not do anything. ❌ 
7. `00:28` Navigate to the Published list. The page is now there as expected. 
8. `00:33` Navigate back to the Drafts list. The page is no longer there as expected. 

## Notes

🌲The fix should be applied in the master branch, `issue/12240-master-branch`. 

❓I'm not sure how much effort is required to get this fixed. But it seems like a terrible experience.  Should this be out of scope?

**Comment by shiki** [comment]
> Should this be out of scope?

After talking with @malinajirka, we'll defer the decision for getting things working on pages until the full workflow for posts is done.

**Comment by yaelirub** [comment]
@shiki , On Android we cancelled the option to auto-upload pages. Should we do the same for iOS?

**Comment by shiki** [comment]
@yaelirub Yes. This has been decided some time ago. I haven't created an issue for it yet.

**Comment by shiki** [comment]
This is why I marked this task as blocked for now.

**Comment by kean** [comment]
Not applicable starting from 24.9 (pcdRpT-6vS-p2)
