### ISSUE TITLE
[Auto-upload Published] Incorrect Post List tab is shown after exiting the editor

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12284]
Part of #12240.

Based on the design described in #12240, PR #12252 changed the placement of locally published posts so that they will be initially placed in the Drafts list. After uploading, they will be moved to the Published list. 

However, there is a pre-existing feature where when exiting the editor after publishing, online or offline, the Post List automatically **shows the Published list**. 

## Steps

Please take a look at [this video](https://drive.google.com/file/d/1SZhc3DlWZFLOhBo4aNkMQZDGDZWEoGcc/view?usp=sharing). 

1. `0:00` Navigate to _Scheduled_. This is just to illustrate the tab switching.
2. `0:02` Create a post and while online and publish it.
3. `0:17` Notice that the current tab was automatically switched to the Published tab. ❓ 
4. `0:19` Navigate to Drafts list. The post is there. It will be moved to the Published list after uploading is done. 
5. `0:31` Go offline. Navigate to the Scheduled list again. Create a post and publish it. 
6. `0:45` Notice that after exiting the editor, the Published tab is selected again. ❓ 
7. `0:48` Navigate to Drafts list. The post is there as expected. Go online and it will be moved to the Published post once uploading is done. 

This can be reproduced by using the `issue/12240-master-branch` master branch commit 9813fd087550e804862d9105ef3c890b902c2849. 

## Questions 

- [x] @osullivanchris What do you think should be done for this? @malinajirka, did you handle this differently in WPAndroid? 

## Decision 2019-Aug-12

- [ ] As agreed in https://github.com/wordpress-mobile/WordPress-iOS/issues/12284#issuecomment-520402865, we will remove the auto-switching of tabs when exiting the editor. 

## Notes 

🌲Fixes should be targeting the master branch, `issue/12240-master-branch`.

**Comment by malinajirka** [comment]
>@malinajirka, did you handle this differently in WPAndroid?

I didn't need to change the behavior on Android - posts were already being filtered by their remote status not the locally changed status. 

>However, there is a pre-existing feature where when exiting the editor after publishing, online or offline, the Post List automatically shows the Published list.

We show the correct tab in these cases
- draft tab when editing a draft
- published tab when editing a published post
- etc.

**Comment by shiki** [comment]
After testing https://github.com/wordpress-mobile/WordPress-Android/pull/10319, it looks like Android's experience is better. It doesn't automatically change the tab at all. Wherever the editor is started, whether editing an existing post or creating a draft using FAB, the user will stay where they were previously. 

This seems to make more sense to me. And changing this on iOS would probably not require a lot of code.

**Comment by osullivanchris** [comment]
@shiki agree with what you landed on there. The snackbar says 'view' if its a published post too, so if you're not sure where to go that will take you there.

Assuming this one is fine but ping me if you need more input.

**Comment by shiki** [comment]
@osullivanchris Thank you. The decision is then to remove the auto-switching of tabs and keep the user where they are. Updated the description. ☝️

**Comment by shiki** [comment]
Done in #12302
