### ISSUE TITLE
Reader: Bad formatting for bullet lists created with the block editor

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#12288]
### Expected behavior

Unordered lists in block editor Reader posts should be formatted correctly, with consistent bullet point characters, colors, and no extra bullets.

### Actual behavior

Posts with lists created in the block editor contain different sub level bullets, differently coloured bullets (the blue ones in the screenshot are directly followed by a hyperlink in the text), and extra unnecessary bullets:

![File](https://user-images.githubusercontent.com/4780/62768589-106a4380-ba8f-11e9-89a8-9677e5d27c32.jpg)

### Steps to reproduce the behavior

* Using the block editor, create a post with multiple levels of indentation.
* View that post in the Reader in the app

##### Tested on device, iOS 12.4, WPiOS 13.0

**Comment by frosty** [comment]
Related issue for the blue bullets: https://github.com/wordpress-mobile/WordPress-iOS/issues/9525

**Comment by rachelmcr** [comment]
This came up again in an internal report (p4a5px-2vg-p2).

**Comment by designsimply** [comment]
I spotted some extraneous bullets in lists in the WPiOS Reader while testing the Custom HTML block using these steps:

1. Go to https://raw.githubusercontent.com/cbracco/html5-test-page/master/index.html
1. Copy the content inside the `body` tags.
1. Create a new post in the app or on the web.
1. Add a paragraph block.
1. Add a Custom HTML block and paste the content copied in step 2.
1. Add another paragraph block.
1. Publish the post and view it in the Reader.

**Result:** scroll through the post and look at the bulleted list near the top. I added a screenshot from Android below to compare.

WPAndroid 14.7-rc-3 | WPiOS 14.7.0.2 TestFlight beta
---|---
<img src="https://user-images.githubusercontent.com/1119271/80546763-c35b3400-8973-11ea-8b17-56314c6b4b4b.png" width="200" alt="Screenshot_20200428-131250">|<img src="https://user-images.githubusercontent.com/1119271/80546770-c7875180-8973-11ea-9867-12d5f1269525.PNG" width="200" alt="IMG_3940">

<p style="clear:both;"><sup>Tested with WPAndroid 14.7-rc-3 on Pixel 3 Android 10 and WPiOS 14.7.0.2 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

**Comment by elibud** [comment]
@designsimply let's remove this from Groundskeeping as might be solved as part of the Reader Improvements project. cc: @yaelirub

**Comment by yaelirub** [comment]
Thanks for the ping, @elibud !
We’ll remove this and any other ticket for rendering block issues that are going to be fixed as part fo RI. cc: @leandroalonso

**Comment by elibud** [comment]
It's going to be a happy day! Ping me if I can help.

**Comment by leandroalonso** [comment]
This was solved during Reader Improvements. :)
