### ISSUE TITLE
Share / Reblog Text Illegible When Sharing Content Inside the WordPress iOS App

### ISSUE THREAD

**Issue by pmciano** [wordpress-mobile/WordPress-iOS#12299]
### Expected behavior
Legible text for sharing/reblogging content inside of the WordPress app.

### Actual behavior
I see white text on a light grey background. The text is barely legible.

![share_text](https://user-images.githubusercontent.com/6855537/62898952-8975cf00-bd0b-11e9-8485-de9b88cf9f57.PNG)

### Steps to reproduce the behavior

1. Browse content in the WordPress iOS app.
2. Attempt to share a post.
3. Share text options are illegible.

##### Tested on iPhone 6, iOS 12.4 WPiOS 12.9.1

Reported in 2266520-zen

**Comment by rachelmcr** [comment]
Thanks for the report! We're tracking this in a master issue in https://github.com/wordpress-mobile/WordPress-iOS/issues/11683#issuecomment-512543207, related to color palette changes in the app.
