### ISSUE TITLE
Editor: Changing the selected site in the editor sets post status to Published instead of Draft

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#12300]
### Expected behavior

I expect all new posts to be created with a Draft post status (not Published) per https://github.com/wordpress-mobile/WordPress-iOS/pull/8983.

### Actual behavior

If you open the editor and then use the site picker to switch sites, the post status is set to Published instead of Draft.

This is especially a problem if you are using to saving a draft while exiting the editor, as it can cause you to accidentally publish a post when you think you are saving a draft.

### Steps to reproduce the behavior

1. Open the editor in the app.
2. Tap the site name at the top of the editor.
3. In the site picker, select a different site.
4. Open the Post Settings and note that the status is Published (should be Draft).
5. Add a title/content to the post.
6. Tap the X to close the editor.
7. In the action sheet that appears, select "Update post." Note that the post is then published (instead of being saved) without any publish confirmation.

**Comment by designsimply** [comment]
Tested and confirmed that a new post defaults to published instead of a draft when the site switcher is used within the editor ([1m30](https://cloudup.com/c--vMFxKEkO) Aztec, [1m58s](https://cloudup.com/ciCbvV_le1Z) block editor).

**Comment by designsimply** [comment]
Note: sometimes I did see an additional prompt asking me if I wanted to keep editing or publish now but it didn't happen every time:

<img src="https://user-images.githubusercontent.com/1119271/62982489-83562000-bde9-11e9-96c4-297b7b80f11b.PNG" width="270" alt="IMG_2931">
<sup>Tested with WPiOS 12.9.1 (app store version) on iPhone 6S iOS 12.4.</sup>
