### ISSUE TITLE
Add "Share" action to the post "more" menu in the posts list

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#12314]
### Current behavior

Currently, when you go to My Site > Blog Posts > Published each post has an ellipsis "more" menu with these actions:

* View
* Stats
* Move to Draft
* Move to Trash

(With the expanded posts list design, "View" is on the post card instead of in the more menu.)

![Photo 14-08-2019, 15 30 32](https://user-images.githubusercontent.com/8658164/63029554-b01d3c80-bea8-11e9-8545-f5d8dcdd3aaf.png)

### Requested behavior

A TestFlight beta user requested a Share action in that menu.

This was also mentioned in https://github.com/wordpress-mobile/WordPress-iOS/issues/12267#issuecomment-517939383:

> It might be nice to have a Share button there as well. Right now you need to view the post to access the activity view controller to share your posts. If you could share the post from the post list it would be nice

**Comment by ngoctr** [comment]
Hey folks, I will be working on this and will submit a PR soon.
