### ISSUE TITLE
Next button in login is tappable after cancelling Google login

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#12316]
When entering an email to login to WordPress.com, the next button doesn't become enabled until a valid email is entered. However, this validation is skipped when tapping "Log in with Google".

Steps:
1. Enter junk into the email field, such as "notanemail"
2. Tap the "Log in with Google" button
3. Cancel login with Google immediately.
4. Tap Next

The app immediately crashes with an assertion failure on line `344` in `LoginEmailViewController.swift`.

**Comment by ScoutHarris** [comment]
With https://github.com/wordpress-mobile/WordPress-iOS/pull/12305, the login options changed and 'Log in with Google' is no longer displayed. Closing as this is no longer an issue.
