### ISSUE TITLE
[Auto-upload Published] Show notice after canceling

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12325]
📣 Part of #12240. This is a continuation of the #12317 PR and requires that to be merged first. Any fixes should target the `issue/12240-master-branch` branch. 

In #12317, we added a _Cancel_ button on the Post List for locally published posts. To follow the spec described in #12240, pressing the _Cancel_ button should show a notice:

<img width="320" alt="notice" src="https://user-images.githubusercontent.com/198826/63062898-c252a700-beb7-11e9-91f4-0a71d670ef22.png">

Please note that the message has been changed to “Changes will not be published“ instead of the one shown in the image.

**Comment by diegoreymendez** [comment]
Closing this issue as the connected PR seems to have fixed this issue.
