### ISSUE TITLE
[Auto-upload Published] Canceling should hide “Upload failed”

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12328]
📣 Part of #12240. This is a continuation of the #12317 PR and requires that to be merged first. Any fixes should target the `issue/12240-master-branch` branch. 

In #12317, we added a _Cancel_ button on the Post List for locally published posts. In that PR branch, pressing the _Cancel_ button will hide the button but the “Upload failed” message is immediately shown:

<img src="https://user-images.githubusercontent.com/198826/63107938-18b8f780-bf43-11e9-9476-735630330634.png" width="320">

I wanted to include this as part of #12317 but ran into a roadblock.

## Technical Challenge

Hiding this would require us to remove the `AbstractPostRemoteStatusFailed` from `Post.remoteStatus` when canceling in:

https://github.com/wordpress-mobile/WordPress-iOS/blob/504b9153cc2ed2ac29e9468b746d64919bfc74cc/WordPress/Classes/Services/PostCoordinator.swift#L273-L282

`AbstractPost.remoteStatus` is not nullable. I thought of setting the value to `.local` but I ran into this usage of `.local`:

https://github.com/wordpress-mobile/WordPress-iOS/blob/aa14eaa70b24f34dfebe48aee42f6532c3eb7d75/WordPress/Classes/Models/AbstractPost.m#L350-L353

That is used when discarding changes in the editor:

https://github.com/wordpress-mobile/WordPress-iOS/blob/aa14eaa70b24f34dfebe48aee42f6532c3eb7d75/WordPress/Classes/ViewRelated/Post/PostEditor%2BPublish.swift#L239-L246

If we reset the `remoteStatus` to `.local`, and the user edits the post and discards it, the post will get deleted!

### Option A

So it's looking like we will need a new `AbstractPostRemoteStatus` enum value. But that looks really complicated. I could use any advice here. 

### Option B 

Another option would be to just hide the message and keep the `.failed` value. We will replace the message with “Local changes“ instead. WPAndroid shows the same message after canceling. 

@diegoreymendez @jklausa @yaelirub I'd love to hear your suggestions on this.

**Comment by yaelirub** [comment]
A challenge indeed.

At first I was leaning towards option B because that's what Android is doing but mainly because I'm aware of the complexity with adding another status.

The thing is, I'm not sure that's the right thing to do. Thinking about it from a user POV, if I cancel an upload of a post, it means that it was never uploaded so changing its status to local makes total sense but then we have to deal with changes in the discard function which Android doesn't have to deal with. Ugh.

How complex is it to add a status like remoteStatusCanceled or something like that?

**Comment by shiki** [comment]
> How complex is it to add a status like remoteStatusCanceled or something like that?

@yaelirub I haven't gone that far analyzing this yet. I'll try it and see how it goes.

**Comment by diegoreymendez** [comment]
Option B seems "enough" for me to get a good experience.  We can work on standardizing the "Discard Changes" thing as a mini project after that.

I'd really avoid adding another status just for this, as the status is used in many places for different things, which makes it easy for us to break something.

**Comment by yaelirub** [comment]
Ok then, @diegoreymendez , @shiki , let's go with option B

**Comment by shiki** [comment]
Done in #12419.
