### ISSUE TITLE
User reports being unable to approve comments from notifications (Self hosted)

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#1232]
User reports that when they approve a comment from the comments screen there isn't a problem but when they try and approve a comment from the notifications screen nothing happens.

**Comment by hoverduck** [comment]
29Oct15 Bug Scrub

Closing - unable to reproduce

**Comment by koke** [comment]
For reference, I believe this might have been fixed by https://github.com/Automattic/jetpack/issues/2792
