### ISSUE TITLE
Stats: Post Stats: No longer linking directly to posts/pages from stats

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-iOS#12339]
### Expected behavior

In Post Stats, I expect that tapping the post title will take me to the post in question.

### Actual behavior

Tapping the post title does nothing.

### Steps to reproduce the behavior

Go to My Site > Stats > Days (or Weeks/Months/Years) and find a time period with views.
Scroll down to "Posts and Pages", and tap one of the Posts or Pages that has views.
Try tapping the site title under "Showing stats for:"
Note that you are not taken to the Post or Page in question.

![statslink](https://user-images.githubusercontent.com/15107387/63262617-1cc07e80-c28f-11e9-9dff-73f62e3cec92.png)

##### Tested on iPhone SE, iOS 12.3.1, WPiOS 13.0
User report in #2282822-zen
iPhone XS, iOS 12.4, WPiOS 13.0

Initial change to link the post title was merged in https://github.com/wordpress-mobile/WordPress-iOS/pull/11499 
This may have been effected by recent changes in https://github.com/wordpress-mobile/WordPress-iOS/pull/11624
cc: @rachelmcr

**Comment by elibud** [comment]
@danielebogo can you please look into this?

**Comment by danielebogo** [comment]
@elibud @thehenrybyrd PR opened [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/12341)

**Comment by rachelwinspear** [comment]
Another case: #2288555-zen

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/12341.
