### ISSUE TITLE
Author filter issues

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#12330]
### Expected behavior

The author tooltip filter should have a tiny arrow on top, and be responsive.
![IMG_8600](https://user-images.githubusercontent.com/5558824/63113575-3436f900-bf69-11e9-80da-5dff472fde01.PNG)

### Actual behavior

The arrow is not present on iOS 13 and the tooltip is super unresponsive.
![IMG_1776](https://user-images.githubusercontent.com/5558824/63113488-03ef5a80-bf69-11e9-886a-a6d9c73822f0.jpg)

### Steps to reproduce the behavior

On an iOS 13, multi-author blog, tap on the avatar on the top left column. Notice the arrow missing and the unresponsiveness.

**Comment by frosty** [comment]
After testing on the latest iOS 13 I don't see any responsiveness issues or problems with the arrow, but the tableview is inset incorrectly:

<img width="259" alt="image" src="https://user-images.githubusercontent.com/4780/63646518-3557eb00-c70c-11e9-8e17-90bd3f645492.png">

**Comment by frosty** [comment]
@elibud Yes, that’s the plan, we just didn’t quite get to it before the freeze.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/12410.
