### ISSUE TITLE
Track editor source of events from editor_button_tapped events

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-iOS#12333]
- [ ] We should use the`WPAppAnalyticsKeyEditorSource` property on `editor_button_tapped` events. 
- [ ] Add `gutenberg` as a source for this property and make sure `aztec` is correctly set.
- [ ] Check other places where this property could be used (publish, upload events, etc).

**Comment by designsimply** [comment]
Still looks valid. Noting a request from https://github.com/wordpress-mobile/WordPress-Android/issues/10360:

> Can you make sure we use the same name in wpios (`editor_source`) and wpandroid for this specific property?
> <sup>—requested by @maxme at https://github.com/wordpress-mobile/WordPress-Android/issues/10360#issuecomment-521993665.</sup>
