### ISSUE TITLE
Can't delete posts sometimes while online.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#12365]
I'll cut straight to the chase, since this issue is pretty straightforward.

I was able to be in a situation where I'm online but can't delete a post because the App says I'm offline.

The reason this happens is that we're checking if the device is online using Reachability before allowing the user to delete the post.  This is NOT how Reachability should be used.

## Reference

Straight from Apple: https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/WhyNetworkingIsHard/WhyNetworkingIsHard.html

> - Always attempt to make a connection. Do not attempt to guess whether network service is available, and do not cache that determination.
> - If a connection fails, use the SCNetworkReachability API to help diagnose the cause of the failure. Then:
>   - If the connection failed because of a transient error, try making the connection again.
>   - If the connection failed because the host is unreachable, wait for the SCNetworkReachability API to call your registered callback. When the host becomes reachable again, your app should retry the connection attempt automatically without user intervention (unless the user has taken some action to cancel the request, such as closing the browser window or clicking a cancel button).

## Proposed solution

This logic: https://github.com/wordpress-mobile/WordPress-iOS/blob/e888614b0a0f57cfca2872a3a97da34420b0686e/WordPress/Classes/ViewRelated/Post/PostListViewController.swift#L639-L643

should be replaced with new logic to handle the offline error case here:

https://github.com/wordpress-mobile/WordPress-iOS/blob/e888614b0a0f57cfca2872a3a97da34420b0686e/WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift#L980-L1001

**Comment by kean** [comment]
The app no longer checks reachability in this any many other situations – obsolete.
