### ISSUE TITLE
[Offline Posting] Do not automatically retry upload after 3 failures

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12369]
📣 Part of #12240. Please use the `issue/12240-master-branch` as the target branch. 

In Android, https://github.com/wordpress-mobile/WordPress-Android/issues/10059, we ran into an issue where a post can be automatically uploaded indefinitely. There can be many reasons for this but one of the reasons can be that the user doesn't have permission to upload to the site. 

We should also add this for iOS to preemptively avoid this scenario. 

See [UploadActionUseCase](https://github.com/wordpress-mobile/WordPress-Android/blob/ec1fb997c3d3113048c2c83b03863d5f77f20642/WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadActionUseCase.kt#L46-L49) for how it is implemented on Android.

## Known Tasks  

- [x] #12504 [Auto-upload Published] Do not automatically retry media uploads after 3 failures
- [ ] Add maximum retry for posts
- [ ] Add tests

**Comment by shiki** [comment]
@malinajirka Are we still going with a maximum of 10 failures?

**Comment by malinajirka** [comment]
Hmm I know we discussed going with 3 retries and changing the copy based on the retry count, right? I can't find that conversation and I don't remember what we decided 😞.

**Comment by malinajirka** [comment]
Found it :) - we'll soon have only 3 retries on android. More info https://github.com/wordpress-mobile/WordPress-Android/issues/10370

**Comment by shiki** [comment]
@malinajirka Thanks, I tried looking for it yesterday. 😄

**Comment by shiki** [comment]
Messages to be shown in the Post List are described in https://github.com/wordpress-mobile/WordPress-Android/issues/10370#issuecomment-525288850.
