### ISSUE TITLE
[Auto-upload Published] Fix UI Tests

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12368]
📣 Part of #12240. Please use the `issue/12240-master-branch` as the target branch. 

We broke the UI tests at some point in the master branch. ¯\\\_(ツ)\_/¯ They'll have to be fixed before we can merge the branch in `develop`.

**Comment by leandroalonso** [comment]
@yaelirub @shiki by looking here https://github.com/wordpress-mobile/WordPress-iOS/branches you can see that all tests are succeeding in our CI. Does this task still make sense?

**Comment by shiki** [comment]
I guess not. It fixed itself. Thank you for checking! 🎉
