### ISSUE TITLE
Pages using obsolete wp.getPage instead of wp.getPost

### ISSUE THREAD

**Issue by codydh** [wordpress-mobile/WordPress-iOS#1236]
Certain parts of the app, such as ```Classes/Page.m``` line 127, are using Pages methods (e.g. ```wp.getPage```), which is now obsolete according to the Codex (http://codex.wordpress.org/XML-RPC_WordPress_API). 

Instead, ```wp.getPost``` and related methods should be used.

**Comment by rachelmcr** [comment]
#1521 is closed and I wasn't able to find any remaining Pages methods used in the app. Closing this as resolved.
