### ISSUE TITLE
[Auto-upload Published] Do not auto-upload unpublishable posts

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12367]
📣 Part of #12240. Please use the `issue/12240-master-branch` as the target branch. 

In Android, https://github.com/wordpress-mobile/WordPress-Android/issues/9955, we ran into an issue where there were infinite upload attempts for a post. The reason being, the post is not publishable because they have no content and title. 

We should also add this for iOS to preemptively avoid this scenario. 

See [UploadActionUseCase](https://github.com/wordpress-mobile/WordPress-Android/blob/ef4231cd6f8946c73752f03dd888caecb9736882/WordPress/src/main/java/org/wordpress/android/ui/uploads/UploadActionUseCase.kt#L36-L39) for how it is implemented on Android.

## Known Tasks  

- [ ] Possibly add a simple test in `PostAutoUploadInteractorTests` if this is implemented inside `PostAutoUploadInteractor`.

**Comment by yaelirub** [comment]
@leandroalonso , from my testing on issue/12240-master-branch, if I create a post *online* with no title and content, the post remains as draft and has the "Post will be published next time..." status label.

Can you confirm that you're seeing this as well?

**Comment by leandroalonso** [comment]
@yaelirub Using Aztec, I created a post with empty title and content and the status here is "Local" (I had to close the app while the editor was open). No messages about auto-publishing it.

However, apparently Gutenberg allows you to tap "Publish" for a post with empty title/content and then the post is scheduled. I wonder if this is an issue in Gutenberg?

**Comment by leandroalonso** [comment]
@shiki and I discussed about this issue and we decided that once #12369 is done this will not be an issue anymore.
