### ISSUE TITLE
[Offline Posting] Add a feature flag that toggles automatic uploading

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12370]
📣 Part of #12240. Please use the `issue/12240-master-branch` as the target branch. 

As a pre-emptive measure, we can add a feature flag that toggles the automatic uploading. 

We can possibly use the `FeatureFlag` enum.

**Comment by shiki** [comment]
@diegoreymendez tagging you in case you have an objection for this. I believe you mentioned this once.

**Comment by yaelirub** [comment]
@shiki , I started working on implementation for this but I am not sure we should do this. 
My concern is that if we every choose to disable it and than re-enable it, posts that were failed to upload will get auto uploaded or the UI won't make sense. 

Are we doing this on Android?

Why is this feature a good candidate for a feature flag?

**Comment by shiki** [comment]
Thank you for the info, @yaelirub. This was mostly born out of @diegoreymendez's concern of “what if this causes a major bug”. He mentioned once that we should think about how to react quickly if that happens. 

If you think this causes more trouble than it's worth, and it sounds that way, then I'm okay with abandoning it. 

We don't have this on Android.

**Comment by yaelirub** [comment]
Thanks @shiki !
Ok then. I'm going to close this one and if we ever see a reason to pursue it, I'll create a new ticket so we can discuss.
