### ISSUE TITLE
SIWA: Add Continue with Apple to Sign Up

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#12398]
There is no SIWA button on the Sign up for WordPress.com option in log in.

**Comment by designsimply** [comment]
Adding a screenshot for reference: 

<img src="https://user-images.githubusercontent.com/1119271/64051501-89156a80-cb38-11e9-9a3e-b700b62b21ce.PNG" width="270" alt="IMG_3023">
<sup>Tested with WPiOS 13.2-beta1 (TestFlight) on iPhone 6S iOS 13.1 Beta 1.</sup>

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/12447.
