### ISSUE TITLE
[Stats Refresh] Insights: Load overview block independently in details view

### ISSUE THREAD

**Issue by danielebogo** [wordpress-mobile/WordPress-iOS#12424]
On Insights we should load all the details view using the ghost animation

**Comment by designsimply** [comment]
By details view do you mean the view more links? ([8s](https://cloudup.com/cgoYOo_6-lF))

I tested and noticed there was a super quick flash showing the "Loading Stats…" animation and I think this is the thing you're recommending to replace. (I wanted to add a screenshot for reference. 🙂)

<img src="https://user-images.githubusercontent.com/1119271/65200763-67c3e200-da45-11e9-9d21-4671afbef9b6.png" width="270" alt="loading-stats">
<sup>Tested with WPiOS 13.2.1.2 (TestFlight) on iPhone 6S iOS 13.1.</sup>
