### ISSUE TITLE
SIWA: Update all screens per designs provided

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#12433]
@mattmiklic provided several design iterations for Sign in with Apple and there's surrounding changes to screens like in the prologue and epilogue that need to be addressed. For example:

![sign-in-with-apple-i4-1](https://user-images.githubusercontent.com/373903/64035295-04b1f000-cb16-11e9-82c2-c19969e1a716.png)

**Comment by mattmiklic** [comment]
I can work next week on documenting everything in terms of colors and materials used, sizes, etc. The visual design changes will also impact parts of the WordPress.com and self-hosted login flows (outside of SIWA) so it might make sense to tackle them all at once?

**Comment by astralbodies** [comment]
@mattmiklic It probably does make sense to tackle them at once because it would be jarring if login was very different than the rest of the app. In the end the screens right now don't look awful. We should at least do a pass to make sure we're not missing any pieces of data you may have accounted for that aren't on the existing screens we reused from Sign in with Google.

**Comment by mattmiklic** [comment]
Yep, I think the main thing is creating the "WordPress.com Password Confirmation" screen. Should be able to re-use the existing Password screen layout with the "Please enter the password for your WordPress.com account to log in with your Apple ID" message in the screenshots above. For the v1 implementation agree that the existing screen layouts are sufficient.

**Comment by designsimply** [comment]
Adding the `Needs Design` label because design direction for color, type, and spacing are still incoming for this task.

@astralbodies if a developer is queued up to work on this sooner than later, please make a note here and we can raise the priority so that design knows to move it further up on the list.

**Comment by ScoutHarris** [comment]
@designsimply FWIW, (some time soon) I'm going to strip this issue down to just the "Please enter the password for your WordPress.com account to log in with your Apple ID" view @mattmiklic mentioned above.

Updating the designs as a whole isn't strictly SIWA related and, as others mentioned, should be handled separately. I don't want to speak out of turn, but I think @frosty can add this to User Success' project list for proper tracking.

**Comment by ScoutHarris** [comment]
Ah, I totally forgot - the "Please enter the password for your WordPress.com account to log in with your Apple ID" view has already been implemented with https://github.com/wordpress-mobile/WordPress-iOS/pull/12383.

Sadly, it no longer works. 🙁 I've created https://github.com/wordpress-mobile/WordPress-iOS/issues/12556 to look into that.

With that, I'm closing this issue.
