### ISSUE TITLE
SIWA: Fetch display name & e-mail address from sign-in endpoint

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#12434]
When a user logs back into the app with SIWA (in other words, they're already a SIWA account), the data coming from Apple will not have a display name or e-mail address. The epilogue is pretty sparse after because of this missing information.

![IMG_0007](https://user-images.githubusercontent.com/373903/64035569-bc470200-cb16-11e9-8c90-b2e7d7cc992f.PNG)

When the result comes back from the social login endpoint, retrieve the user's display name and e-mail address from the response. Update the epilogue screen with those values.

This will require an endpoint change @Tug to include those two values.

**Comment by Tug** [comment]
@astralbodies I think we should do the same as for google and get this information from the wpcom user object, it should be available there.

**Comment by ScoutHarris** [comment]
> This will require an endpoint change

Hey @Tug - sorry if I missed it, but has this been done yet?

**Comment by Tug** [comment]
Hi @ScoutHarris, no this hasn't been done and probably won't. I don't understand what's blocking here to be honest. This isn't new, the login endpoint has always returned an access token that gives access to the `/me` endpoint to retrieve the user data.

**Comment by ScoutHarris** [comment]
Ah, sorry @Tug I misunderstood your initial response. Thank you!

**Comment by Tug** [comment]
@ScoutHarris I was wrong here and mixed the signup endpoint with the login one. We did have user info already on the signup one as it was designed for mobile exclusively. Now that the server patch is merged as well as #12471, I guess we can close this?

**Comment by ScoutHarris** [comment]
Hey @Tug . Sorry, I forgot to close this yesterday. Closing now.

Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/12471.
