### ISSUE TITLE
Site briefly appears, then disappears from site list when visibility is turned off.

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/WordPress-iOS#12448]
### Expected behavior
Sites in the site list do not show up briefly, then disappear.

### Actual behavior
Sites in the site list briefly show up, then disappear.

### Steps to reproduce the behavior
1. Hide blog from edit sites menu.
2. Find it using search.
3. Open it.

### Potential cause

- By default the site list shows only visible sites, but we also show any recently used sites at the top (maximum 3), even if they’re hidden.
- For some reason, once you tap on any site on the list, we flag it as visible, but only locally.
- Whenever the site list appears, it will sync the list of sites and set `visible=NO` for that site again.

**Comment by kean** [comment]
Obsolete as site visibility featured was removed.
