### ISSUE TITLE
SIWA: Provide a route to login support if SIWA fails

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#12463]
### Expected behavior
Once I start logging in or signing up, I expect a clear route to support in case of any problems.

This is especially helpful if there are still rough edges when SIWA launches — support can help with any user questions or unexpected scenarios, and raise any unforeseen issues.

### Actual behavior
If you choose “Continue with WordPress.com” or “Continue with Google,” you are moved to a screen with a Help button in the top right:

<img src="https://user-images.githubusercontent.com/8658164/64266588-bc873900-cf2c-11e9-8198-31f76bc76682.png" width="50%">

<img src="https://user-images.githubusercontent.com/8658164/64266597-c0b35680-cf2c-11e9-8a17-986de415f011.png" width="50%">

But if you choose “Continue with Apple” if just brings up a modal over the Prologue screen. If there’s a problem, you’re taken back to the Prologue screen with no obvious way to contact support.

**Comment by ScoutHarris** [comment]
Error alerts with support button was added with https://github.com/wordpress-mobile/WordPress-iOS/pull/12468. And other views in the flow already have the nav bar 'Help' buttons. So I'm closing this issue.
