### ISSUE TITLE
Reader single-post bottom toolbar doesn't span full-width on landscape iPhone and iPad

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/WordPress-iOS#12470]
### Expected behavior

When viewing a post on Reader, I expect the bottom toolbar (containing `save`, `like`, `comments`, etc. to span the full width of the viewport.

### Actual behavior

The toolbar only extends to the edges of the readable margins.

#### iPad running iPad OS 13.1 beta 1

![IMG_0569](https://user-images.githubusercontent.com/1200432/64294115-b2b50400-cf33-11e9-8c2c-2c5a442c6a23.jpeg)

#### iPhone XS Max (screen-zoomed to XS) running iOS 12.4

![IMG_5728](https://user-images.githubusercontent.com/1200432/64294285-01fb3480-cf34-11e9-99a3-5e85a88a065e.jpeg)

### Steps to reproduce the behavior

Open a post on Reader using an iPad or iPhone in landscape.

##### Tested on [device], iOS [version], WPiOS [version]

Tested on both iPhone (iOS 12.4) and iPad (iPad OS 13.1 beta 1)

**Comment by elibud** [comment]
@designsimply this one seems good for groundskeeping.

**Comment by iamthomasbishop** [comment]
I found another issue in Reader, where the same thing is happening under the "manage" view (`Reader > Followed Sites > Manage`).

![IMG_0571](https://user-images.githubusercontent.com/1200432/64369598-50ffa300-cfe2-11e9-811e-3700686ba40c.jpeg)

**Comment by rachelmcr** [comment]
I ran into this today while dogfooding on an iPad Mini (using WPiOS 14.2.0.20200220). Added it to the groundskeeping project.
