### ISSUE TITLE
SIWA: Support logging in with SIWA with wpcom two-step enabled accounts

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#12477]
The app allows the user to connect SIWA to a wpcom account with two-step (password is requested and wpcom two step code). Subsequent logins, however, present the user with an error when attempting to sign in. (Before this was a silent fail).

![Simulator Screen Shot - iPhone Xʀ - 2019-09-05 at 08 28 58](https://user-images.githubusercontent.com/373903/64346547-efc2da00-cfb7-11e9-9e08-da7fc561fec7.png)

**Comment by ScoutHarris** [comment]
I'm not able to repro this. But I'm not actually able to login in again due to https://github.com/wordpress-mobile/WordPress-iOS/issues/12556. I'll check this again once that is fixed.

For reference, @astralbodies 's repro steps:
1. Log in using SIWA for the first time to a wpcom account with a matching e-mail address (to the Apple ID) that has two step enabled.
2. Go through the dance of setting up the connection with providing your password and two-step code.
3. Log out of the app.
4. Log back in with SIWA.
5. Receive error about two-step being enabled.

**Comment by ScoutHarris** [comment]
I was able to workaround https://github.com/wordpress-mobile/WordPress-iOS/issues/12556 by saving my password on the device, then selecting it when signing in. This magically populated the email address, allowing me to log in.

![password_prompt](https://user-images.githubusercontent.com/1816888/65919711-64601d00-e39a-11e9-954a-223d46d4073c.jpeg)

![populated_fields](https://user-images.githubusercontent.com/1816888/65919741-7641c000-e39a-11e9-81e8-f5f037e85144.jpeg)

Once I was able to log in, I confirmed that I could successfully re-login with a 2fa account.

![authenticator_prompt](https://user-images.githubusercontent.com/1816888/65919755-7e99fb00-e39a-11e9-846b-8c162667556d.jpeg)

**Comment by sarahfg** [comment]
These are the details from the user report

```
WordPress app: 13.4 
iPhone XR 32GB - iOS 13.1.3
```

**Comment by astralbodies** [comment]
@ScoutHarris Any chance you could take a second look at this to determine if it's an API limitation, or a misinterpretation of an API response on the client side in Authenticator?

**Comment by ScoutHarris** [comment]
I was finally able to repro this by:
- Created WP account with SIWA.
- On the WP account in a browser, enabled Two-Step Authentication.
- Tried to log into the WPiOS app with SIWA.
- Got the error.


I also did the same with a Google account, and got the same error.
- Created WP account with Google.
- On the WP account in a browser, enabled Two-Step Authentication.
- Tried to log into the WPiOS app with Google.
- Got the error.

I am able to log in with both accounts using the WordPress.com path.

Unless Google is broken, I don't think this was ever a supported path. Although it seems it should be. Maybe we can add this to User Success project list to implement for both social account types?

@frosty @astralbodies thoughts?

**Comment by frosty** [comment]
@ScoutHarris Were you able to tell whether this was a client side or server side issue?

**Comment by ScoutHarris** [comment]
Hey @frosty . Sorry about that, I forgot to communicate what I'd found.




Both Google and Apple call the `createSocialWPComAccount` method, which pings the `users/social/new` endpoint. In this particular scenario, that request fails with this error:
```
Optional(Error Domain=WordPressKit.WordPressComRestApiError Code=7 "This account is associated with a WordPress.com account which has Two-Step Authentication enabled." UserInfo={WordPressComRestApiErrorMessageKey=This account is associated with a WordPress.com account which has Two-Step Authentication enabled., NSLocalizedDescription=This account is associated with a WordPress.com account which has Two-Step Authentication enabled., WordPressComRestApiErrorCodeKey=2FA_enabled})
```

We should be able to check for `WordPressComRestApiErrorCodeKey=2FA_enabled` and re-direct the flow accordingly.

**Comment by ScoutHarris** [comment]
Per a Slack convo with @frosty , I'll go ahead and look into this now.

**Comment by ScoutHarris** [comment]
> Unless Google is broken

As it turns out, Google is broken. Resulting from the login flow change we made with SIWA. Woops. I'll fix that too.
