### ISSUE TITLE
[Auto-upload Published] Auto-upload published posts with failed media

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12498]
📣 Part of #12240. Changes should target `issue/12240-master-branch`. 

In #12466, we found that locally published posts are not set to be automatically uploaded. We added auto-uploading in #12252 but we seemed to have missed this case. 

## Steps to reproduce

1. Use `issue/12240-master-branch`
2. Go offline. 
3. Create a post and add an image.
4. Tap on _Publish_ in the top right and publish the post. 

Notice that the Post List says “Upload failed” instead of “Post will be published...”.

## Investigation

Described from the comment https://github.com/wordpress-mobile/WordPress-iOS/pull/12466#discussion_r321806426, the `shouldAttemptAutoUpload` returns `false`. This is why the action is `.autoSave` instead of `.upload`. The `shouldAttemptAutoUpload` is initially set to `true` here: 

https://github.com/wordpress-mobile/WordPress-iOS/blob/2c6380a68b583dafe3eba8bb7cccaa69790bbf5b/WordPress/Classes/ViewRelated/Post/PostEditor%2BPublish.swift#L87

However, something in our code changed the `status` to `.failed` which resulted in the hash changing, and ultimately the `shouldAttemptAutoUpload` return value.

https://github.com/wordpress-mobile/WordPress-iOS/blob/2c6380a68b583dafe3eba8bb7cccaa69790bbf5b/WordPress/Classes/Models/AbstractPost%2BHashHelpers.m#L7-L25

This is a case we probably did not find during #12252. Though it's worth investigating if this worked in #12252 and we somehow changed the location of when we set `shouldAttemptUpload` to true.

**Comment by yaelirub** [comment]
@shiki , after pulling the latest fixes this doesn't seem to be an issue anymore. 
Can you confirm?
![20190915_124827](https://user-images.githubusercontent.com/1335657/64924900-801ecd00-d7b7-11e9-9e09-c52b74ec631a.gif)

**Comment by leandroalonso** [comment]
@yaelirub it's still happening here:

<img width="416" alt="Screen Shot 2019-09-20 at 14 38 10" src="https://user-images.githubusercontent.com/7040243/65346926-4c2b1980-dbb4-11e9-8e95-6373fccb2f21.png">
