### ISSUE TITLE
Notifications: Persistent gap at top of notifications list in iOS 13

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#12495]
The Notifications list regularly has a large gap at the top:

![File](https://user-images.githubusercontent.com/4780/64461014-e048ab80-d0f3-11e9-80b6-205e9f58e8e8.jpg)

**The issue is persistent on iOS 13.0 and WPiOS: 13.2.1**

It seems that this is due to the prompts we display in that area (prime for push, app rating prompt) – I guess it's not getting collapsed when it should be. Also related: https://github.com/wordpress-mobile/WordPress-iOS/issues/11531

**Comment by designsimply** [comment]
Fixed in #12525. Props @yaelirub. 🎉
