### ISSUE TITLE
Title of blog does not reflect changes made via wp-admin

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#1251]
To reproduce, 

- Add a blog to the app. 
- Open the wp-admin in a browser and change the title of the blog. 
- Go back to the app. 

The blog title does not update.  The only way to update it seems to be to sign out and back in.

**Comment by rachelmcr** [comment]
I tested using the steps above. Although the site's title doesn't change immediately, if I open the site's settings the new title appears and is changed everywhere.

I'm closing as works for me, but please reopen if the goal is to have the title update everywhere immediately.
