### ISSUE TITLE
Backgrounding the app on iPad when in dark mode switches the detail view to light mode

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#12528]
### Expected behavior

Running on iPad, on dark mode.
1. Open any tab that contains a list+details UI (i.e Notifications or My Sites)
2. Background the app
3. Bring the app back to the foreground
4. The details UI should remain in dark mode.

### Actual behavior

Running on iPad, on dark mode.
1. Open any tab that contains a list+details UI (i.e Notifications or My Sites)
2. Background the app
3. Bring the app back to the foreground
4. The details UI switches to light mode.

Step 1 (app in the foreground)
<img src="https://user-images.githubusercontent.com/2722505/65395053-44dc5980-ddc8-11e9-90b0-d33013a90cbb.jpg" width="350"/>

Step 4 (after sending the app to the background and bringing it back into the foreground)
<img src="https://user-images.githubusercontent.com/2722505/65395058-56256600-ddc8-11e9-9f39-c90cb9da4d56.jpg" width="350"/>

### Steps to reproduce the behavior
1. Open any tab that contains a list+details UI (i.e Notifications or My Sites)
2. Background the app
3. Bring the app back to the foreground
4. The details UI switches to light mode.

##### Tested on [device], iOS [version], WPiOS [version]
iPad Pro 11", iOS 13.1 beta 4, WPiOS 13.2 (13.2.0.6)

**Comment by danielebogo** [comment]
@ctarda I think this has been fixed here #12521

**Comment by ctarda** [comment]
Oopsies. Sorry! @danielebogo should I close this as duplicated?

**Comment by danielebogo** [comment]
@ctarda I think so yes! Just to be sure, if you try `release/13.2.3` this problem shouldn't happen anymore 😊

**Comment by danielebogo** [comment]
I close this since it has been fixed here https://github.com/wordpress-mobile/WordPress-iOS/pull/12521
