### ISSUE TITLE
Editor: New scheduled post shows "Publish" button and publish confirmation.

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#12544]
### Expected behavior

I expect to see a "Schedule" button and schedule confirmation dialog when I schedule a new post.

### Actual behavior

When I schedule a new post, the primary button continues to say "Publish" and when I tap that button, the confirmation dialog says "Are you sure you want to publish?"

However, if I confirm at that step, the post is correctly scheduled (not published) on the site.

<img src="https://user-images.githubusercontent.com/8658164/65522556-db04a280-dee2-11e9-99f1-572ce41acc13.png" width="50%">

See also https://github.com/wordpress-mobile/WordPress-iOS/issues/9224 for a similar past issue around this behavior. We probably need some tests for post save/update/publish/schedule behavior to avoid further regressions around this.

### Steps to reproduce the behavior

1. Start a new post and add some text.
2. Open post settings and set the publish date to a future date.
3. Go back to the editor and note that it still says "Publish".
4. Tap "Publish" and note that you get a publish confirmation.
5. Tap "Publish" in the confirmation dialog. Note that the post is successfully scheduled (not published).

**Comment by frosty** [comment]
This looks to be resolved with the scheduling enhancements we've made. They're still feature-flagged to development at the moment until we fix #12992, but I'll mark this as closed for now as we hope to get to that soon.

![Simulator Screen Shot - iPhone 11 - 2019-12-09 at 18 56 05](https://user-images.githubusercontent.com/4780/70463916-bec1dc00-1ab5-11ea-9a80-5dc7ca80ccc6.png)
