### ISSUE TITLE
Consider using NSBatchUpdateRequest in refreshPostStatus 

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#12573]
The suggestion was brought up by @koke in this comment:
https://github.com/wordpress-mobile/WordPress-iOS/issues/12420#issuecomment-535341929

[Explanation on NSBatchUpdateRequest](https://www.bignerdranch.com/blog/new-in-core-data-and-ios-8-batch-updating/)

**Comment by majo-bujnak** [comment]
hi, could I take this issue?

**Comment by yaelirub** [comment]
Hey @majo-bujnak , sure :)

**Comment by majo-bujnak** [comment]
hello @yaelirub, sorry this took so long, I was quite busy. I've created a pull request, could I get a review?

**Comment by kean** [comment]
Obsolete. This whole system was removed in 24.9.
