### ISSUE TITLE
[Offline Posting] “Update” button in editor should work while offline

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12589]
📣 Part of #12227. Please target the `issue/12240-master-branch` branch. 

This is from https://github.com/wordpress-mobile/WordPress-iOS/pull/12466#issuecomment-529694557. 

## Steps to reproduce

1. Go offline
1. Edit an existing post
2. Make some changes
3. Press _Update_. The Snackbar should show “Error occurred during saving”.
5. Force close the app while the editor is still open. 
6. Open the app again and navigate to the Post List. Notice that the Post List says that the post will be automatically uploaded. 

~This is against the principles because we did not mention to the user (via Snackbar) that the post will be automatically uploaded.~

## ~Reason for Low Priority (Outdated)~

~I'm initially giving this a low priority because it seems like an edge case. Also, eventually, the user will end up pressing **X** → _Update Post_ and **confirming** the auto-upload.~

## Update (2019-Oct-10)

During the Design Review, we decided that the Update button should behave similarly to the _Update Post_ option that is shown in the dialog when exiting the editor. 

- It should work offline
- The same Snackbar message like “The post will be published...” should be shown
- ~A key difference is the button should not close the editor~
- ~The blocking progress dialog should be removed~

**Comment by leandroalonso** [comment]
I'll leave these two topics to another issue:

* A key difference is the button should not close the editor
* The blocking progress dialog should be removed

Since they're not directly related to Offline Support and this is the current behavior in `develop` we can work on them later.

**Comment by shiki** [comment]
Done in #12690
