### ISSUE TITLE
[Offline Posting] Publish buttons should not automatically publish scheduled posts

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12588]
📣 Part of #12227. Please target the `issue/12240-master-branch` branch. 
⚠️ It's recommended to start this after #12587 is done.

This desired behavior is based on how Offline Posting for Android was implemented. 

## Scenario A

1. Go offline. 
2. Create a post using Gutenberg. 
3. Change the publishing schedule of the post in the Post Settings. 
4. Tap on _Publish_ in the Editor.
5. The Post List should show a message that the post will be scheduled when the device is online.
6. Press _Cancel_. The Post List should show ”Local changes“
7. Tap on the _Publish_ button in the Post List
8. Go online. The post should be scheduled and **not** immediately published. It should be visible in the _Scheduled_ list. 

## Scenario B

1. Go offline. 
2. Create a post using Gutenberg. 
3. Change the publishing schedule of the post in the Post Settings. 
4. Tap on _Publish_ in the Editor.
5. The Post List should show a message that the post will be scheduled when the device is online.
6. Press _Cancel_. The Post List should show ”Local changes“
7. Go online. 
8. Tap on the _Publish_ button in the Post List
9. The post should be scheduled and **not** immediately published. It should be visible in the _Scheduled_ list. 

---

FYI @yaelirub

**Comment by leandroalonso** [comment]
This will be fixed together with #12587. Please, do not work on it.

**Comment by shiki** [comment]
Done in #12613
