### ISSUE TITLE
[Dark Mode] Account epilogue has a different color

### ISSUE THREAD

**Issue by danielebogo** [wordpress-mobile/WordPress-iOS#12593]
New account epilogue has a different color behind 'new account' which shouldn't be there

![IMG_1142](https://user-images.githubusercontent.com/1396552/64465818-9dc7a480-d0dc-11e9-998a-48e42e9530d7.PNG)

**Comment by ScoutHarris** [comment]
With the [Unified Auth](https://wp.me/pbArwn-5X) project, this view will be refactored. So I'm closing this as it will be irrelevant very soon.
