### ISSUE TITLE
[Dark Mode] Post Settings Tags screen white backgrounds

### ISSUE THREAD

**Issue by danielebogo** [wordpress-mobile/WordPress-iOS#12596]
Tags screen has white to the left and right of the tags field

**Comment by thehenrybyrd** [comment]
Had a report of this in 2456704-zen, and I was able to reproduce.

![ABDA64A9-C02E-4C6F-BF61-D8BB0B9D7B90_L0_001](https://user-images.githubusercontent.com/15107387/67841632-3b4dbc00-fb01-11e9-9a84-04092eef05be.png)

It looks like this is planned for 13.5. Thanks!
