### ISSUE TITLE
[Dark Mode] Manage cell highlighted has white background

### ISSUE THREAD

**Issue by danielebogo** [wordpress-mobile/WordPress-iOS#12602]
Reader - Followed Sites: Tapping Manage and then back leaves the "Manage" cell highlighted (white background)

**Comment by designsimply** [comment]
I spotted this today while testing with WPiOS 13.3.0.0 (TestFlight) on iPhone 6S iOS 13.1.2.

<img src="https://user-images.githubusercontent.com/1119271/66170527-d1c1b700-e601-11e9-8732-847cacc8dcd2.PNG" width="270" alt="IMG_3146">
