### ISSUE TITLE
[Offline Posting] Fix PostService.autoSave() or create a new one

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#12630]
⚒**Fix `PostService.autoSave()` or create a new one**

In `PostService.autoSave()`, upload the post as a draft by modifying `RemotePost` so we don't touch the `Post` `NSManagedObject` ever. We should probably make our own `autoSave` method because the existing one in `PostService` does not look useable for our goal. It looks like it's specific for remote previews.

Also, the current `autoSave` doesn't mark a post as failed when the saving fails. Which leads to this bug:

1. While offline, create a post and publish
2. Cancel the auto-upload
3. Restart the app
4. Check that the progress bar is appearing and that the label "Uploading post..." is visible

**Comment by shiki** [comment]
Fixed by #12652
