### ISSUE TITLE
Stats stuck saying "Loading stats…"

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12646]
There have been several reports in the App Store of stats becoming stuck after updating the app. There are at least a couple reports of this from before Stats Refresh v1 shipped with 12.6 on 2019-06-17. It's possible these reports are from Jetpack users who have had their site connection disrupted in some way and that part needs further investigation but we aren't always able to connect a report in an App Store review to an incoming help request with more data (either because the user does not follow up or they may have followed up and been helped and that information wasn't forwarded). In any case, we can see from the reviews that it is affecting people and they are providing at least some feedback about it. We should try to find more detail including: message or error shown on screen (if any), type of site, copy of app logs from _right after_ an attempt to load stats (if possible).

In the mean time, here is a summary of feedback from App Store reviews about stats performance year-to-date to show what people have been reporting and so it is noted as an area we need to review and test further:

From a 3-star app review "Everything is loading (forever)" 
by HamWarCat – May 12, 2019 Version 12.3
> The ‘Stats’ section just loads forever and never shows anything. 

From a 3-star app review "App no longer works" 
by RichardB999 – Jun 10, 2019 Version 12.5.1
> App no longer shows any stats starting from June 6th, literally empty.

From a 3-star app review "New update won’t load stats" 
by Petros9990 – Jun 28, 2019 Version 12.6.1
> I’m having problems after new update being able to switch to different days and see the stats. Won’t load now.

From a 2-star app review "Used to be helpful" 
by Tom_M_WNC – Aug 5, 2019 Version 12.9
> Now it is slow and painful to use! It takes too long to load the stats since the update.

From a 1-star app review "Update: DO NOT UPDATE. It is a Mess on iPad" 
by Review889900 – Aug 21, 2019 Version 13.0.1
> The stats do not show up at all.

From a 3-star app review "Halfway there 3" 
by SciCheerGopher – Aug 24, 2019 Version 13.0.1
> The stats part of the app keeps loading but not displaying data. Anyone else having this problem?

From a 3-star app review "Worse and worse" 
by MouseRoad – Edited Sep 6, 2019 Version 13.1.1
> The app won’t update stats automatically, and if I come back to the stats the next day, it stays stuck on yesterday’s stats and won’t switch to today’s even if I shut down the app entirely.

From a 3-star app review "Stats not showing up" 
by meganfrau – Sep 10, 2019 Version 13.2
> Not sure why the recent update is so buggy but nothing really loads, the app crashes often and my stats never show up. It’s very frustrating.

From a 1-star app review "Messed up stats" 
by V0lvera – Edited Sep 14, 2019 Version 13.2
> Showing stats still take forever after they change the stats feature and add unnecessary world map etc. it was working great before but nooo wordpress had to add a world map.

From a 3-star app review "Would like it more if I could see my stats" 
by Banana Moon Studio – Sep 29, 2019 Version 13.2.3
> I haven’t been able to view my stats in the app for a couple months now. They are endlessly loading. Please fix this!

From a 5-star app review "Love this app, but gets stuck a lot" 
by Macrophyllum – Oct 7, 2019 Version 13.2.3
> I use this app daily, it’s awesome to quickly see stats of my website. However, somewhere between iOS 13.1 and the most recent update, 9/10 times it just says, “Loading stats…” and the graph never appears. Other pages stats below the graph seem to update. I hope there is a fix for this soon! 🤞

It is also worth noting that there are several really good 5-star reviews mentioning how great stats are, so what we need to investigate is why stats performance is working well for some users and not others!

**Comment by ScoutHarris** [comment]
Hey @designsimply .

Thank you for this!

> We should try to find more detail

As we gather more information, it'd also be good to know if it's Insights or Periods that users get stuck on.

Also, @danielebogo did add async loading of [Insights](https://github.com/wordpress-mobile/WordPress-iOS/pull/12405) in the 13.3 release. I see the feedback you posted has been prior to that. 🤞 this change helps.

Asnyc loading for Periods is not complete yet, but it is still on our todo list.

**Comment by designsimply** [comment]
Ace. Noting again what details we're looking for so it's clear:

* Which screen is getting stuck? (Insights, Days, Weeks, Months, Years)
* Message or error shown on screen (if any).
* Type of site. (Self-hosted, Jetpack, WordPress.com) 
* Copy of app logs from right after an attempt to load stats (if possible).

**Comment by ScoutHarris** [comment]
Hey @designsimply .

My apologies! I just realized Insights async loading is feature flagged, meaning it's not enabled outside of development. I'll check into that...

**Comment by ScoutHarris** [comment]
@designsimply fyi - I [enabled](https://github.com/wordpress-mobile/WordPress-iOS/pull/12658) Insights async loading for _internal testing_ in 13.4. If all goes well, I'll enable it publicly in 13.5.

**Comment by ScoutHarris** [comment]
@designsimply 

> I enabled Insights async loading for internal testing in 13.4. If all goes well, I'll enable it publicly in 13.5.

To confirm - Insights async loading was enabled publicly in 13.5.

> Asnyc loading for Periods is not complete yet, but it is still on our todo list.

@danielebogo has finished async loading for Periods, detail views, and Post Stats (https://github.com/wordpress-mobile/WordPress-iOS/issues/12147). It has been enabled for _internal_ testing in 13.6 and should be enabled publicly in 13.7 (barring any issues).

**Comment by ScoutHarris** [comment]
To follow up  - async loading for Periods was enabled publicly in 13.7.

**Comment by ScoutHarris** [comment]
Hey @designsimply . What are your thoughts on closing this? I suspect the async loading has resolved this...

**Comment by designsimply** [comment]
Thanks for asking! 

I believe the major issues causing stuck stats have been resolved, and if any new ones come up then we can open new issues for those cases individually. 👍
