### ISSUE TITLE
SIWA: "A valid email is needed to create a WordPress.com account." Message appears after authenticating with Touch ID

### ISSUE THREAD

**Issue by erricgunawan** [wordpress-mobile/WordPress-iOS#12665]
### Expected behavior

A WordPress.com account should be created after the Touch ID authenticating step.

This is for email which isn't associated with any WordPress.com account.

### Actual behavior

The `A valid email is needed to create a WordPress.com account.` error message appears instead.

There's also no option to authenticate using a password other than the Touch ID.

### Steps to reproduce the behavior

1. Tap/choose `Continue with Apple`

![IMG_4621](https://user-images.githubusercontent.com/1813857/66541445-8192a980-eb59-11e9-87f9-fe6b148e5ef0.jpg)

2. Authenticate with Touch ID when prompted

![image](https://user-images.githubusercontent.com/1813857/66541475-9bcc8780-eb59-11e9-9b58-51cc236e8a48.png)

3. Result: The error message appears

![IMG_4619](https://user-images.githubusercontent.com/1813857/66541363-41cbc200-eb59-11e9-9b80-eae2823b5fe8.jpg)

**Comment by rachelmcr** [comment]
Thanks for the report! I'm going to close this issue and reopen https://github.com/wordpress-mobile/WordPress-iOS/issues/12490 where this was previously reported, so we can keep track of the full history of this issue.
