### ISSUE TITLE
[Offline Posting] Gutenberg: Scheduled posts are shown as "We'll publish your post...”

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12661]
📣 Part of #12227. Please target the `issue/12240-master-branch` branch. 

<img src="https://user-images.githubusercontent.com/198826/66516061-7417e980-ea9d-11e9-9258-7b1b8908a767.png" width="320">

## Expected behavior

The post list should say “We'll schedule your post...”.

## Actual behavior

The post list should say “We'll publish your post...”.

This seems to be a `Post.status` issue. I'm guessing the `status` is set to `.publish` when pressing the button. This behavior (except the post list message) happens on `develop` too. 

### Steps to reproduce the behavior

1. Go offline.
2. Create a post. Use Gutenberg.
3. Navigate to Post Settings and change the publish date to a few days in the future. 
4. Go back to the editor. Note that Gutenberg shows “Publish” on the top right while Aztec shows ”Schedule”. 
5. Press the _Publish_ button. See the message in the Post List. 

Tested on iPhone XS, iOS 12.4.1, WPiOS `issue/12240-master-branch` (d043083bcdd4844c636be2e27e9678a4f8425ace)

---

@iamthomasbishop Just wanted to confirm if the editor's label should be “Schedule” or maybe the ”Publish” is intentional? 

Aztec | Gutenberg
--------|-------
![IMG_0395](https://user-images.githubusercontent.com/198826/66516451-441d1600-ea9e-11e9-830c-309d9aa3cf6e.PNG)        |       ![IMG_0394](https://user-images.githubusercontent.com/198826/66516456-467f7000-ea9e-11e9-9ab4-a26e8d1577f5.PNG)

**Comment by iamthomasbishop** [comment]
I’m not sure why GB would/should differ from Aztec, as I thought we were using the same wiring for GB – it should be the same unless I'm missing something. With that said, `Schedule` on the button certainly makes more sense to me if I've set something to schedule.
