### ISSUE TITLE
Not receiving comment notifications

### ISSUE THREAD

**Issue by melindahelt** [wordpress-mobile/WordPress-iOS#12672]
### Expected behavior
I expected to get notifications when someone commented on my blog

### Actual behavior
No notifications were received. When I opened notifications tab and refreshed, the notification loaded.

### Steps to reproduce the behavior
* confirm notifications turned on at phone level for WP Internal app
1. Create a free site on the iOS app
2. Publish a blog post
3. Visit blog post in browser logged in as a different user
4. Leave a comment
5. Get email that I have a new comment
6. Check phone, no notification
7. Notice no red dot on notifications tab
8. Open Notifications panel and see notification

Created a new premium site with comment moderation required and repeated steps above with the same results. This time waited  5 minutes before checking the app to see if any delay in notifications on iOS and still no notifications. Emails received almost instantly.

##### Tested on [device], iOS [version], WPiOS [version]
iPhone Xr, iOS 13.1.2 and WPiOS 13.4

**Comment by designsimply** [comment]
Thank you for testing @melindahelt!

Tested and confirmed using WPiOS 13.4.0.1 (TestFlight) on iPhone 6S iOS 13.2 that notifications do not seem to be working on a WP.com simple site new signup. [(4m9s)](https://cloudup.com/cK7BEomw3Vc)

<img src="https://user-images.githubusercontent.com/1119271/66951714-417b6d00-f018-11e9-9eb4-3b1bf3362ec2.png" width="200" alt="ios-notification-settings-for-wp-app"> <img src="https://user-images.githubusercontent.com/1119271/66951713-417b6d00-f018-11e9-8a2c-b00639a9aedd.png" width="200" alt="push-notification-settings-in-app"> <img src="https://user-images.githubusercontent.com/1119271/66951712-40e2d680-f018-11e9-98d0-93aee864f6a3.png" width="200" alt="notifications-tab-settings-in-app"> <img src="https://user-images.githubusercontent.com/1119271/66951768-5f48d200-f018-11e9-9b5f-b6a1da45bb48.png" width="200" alt="automatically-approve-all-comments-setting-in-app"> <img src="https://user-images.githubusercontent.com/1119271/66951917-b8186a80-f018-11e9-9f08-496e6dcee842.png" width="200" alt="notification-bell-does-not-indicate-a-new-comment-has-been-received">

**Comment by frosty** [comment]
Looking into this now!

**Comment by frosty** [comment]
Thanks both for the report! Would either of you mind trying the above scenario again, but relaunch the app after you create the site? (but before you trigger the notification)

For me this 'fixes' the issue in that notifications will start working. If it works for you too, it gives me a hint at what to change to get it working without a relaunch. Thanks!

**Comment by designsimply** [comment]
> Would either of you mind trying the above scenario again, but relaunch the app after you create the site? (but before you trigger the notification)

Confirmed that if I close and re-open the app the comment notifications start working.

<sup>Tested with WPiOS 13.4.0.1 beta (TestFlight) on iPhone 6S iOS 13.2.</sup>

**Comment by frosty** [comment]
Thanks @designsimply! The PR above should fix the issue when merged :)

**Comment by frosty** [comment]
Should be closed by #12732.
