### ISSUE TITLE
[Offline Posting] Compact Post List does not show the date

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12675]
Found during Design Review of #12227. 

Android | iOS
--------|-------
![image](https://user-images.githubusercontent.com/198826/66603544-a42cbe80-eb69-11e9-9ba7-b847aa94134b.png)        |       ![image](https://user-images.githubusercontent.com/198826/66603404-5d3ec900-eb69-11e9-83cb-83a6a89ad261.png)

## Expected behavior

Shows the date.

## Actual behavior

Doesn't show the date.

### Steps to reproduce the behavior

1. Create and publish a post while offline. 
2. See it in the Post List.

Tested on iPhone XS, iOS 12.4.1, WPiOS `issue/12240-master-branch`. 

---

Tagging @osullivanchris just in case you have more comments on this.

**Comment by vphong** [comment]
Hey, I'm looking into this. I believe it has to do with this function:
https://github.com/wordpress-mobile/WordPress-iOS/blob/b96410ddc5700b50fcba763ddad6da17bcb78b00/WordPress/Classes/ViewRelated/Post/PostCompactCell.swift#L117-125
which uses
https://github.com/wordpress-mobile/WordPress-iOS/blob/b96410ddc5700b50fcba763ddad6da17bcb78b00/WordPress/Classes/ViewRelated/Post/PostCardStatusViewModel.swift#L75-77

I think there should be a new case for or modification made for "user is offline." This seems like an overall structural/upstream issue so I hesitate to work on this without guidance, though.

**Comment by shiki** [comment]
Hi @vphong! Thank you for helping us with this. 🙏 

It looks like you are on the right track. In Android, the date is always shown regardless if there is an upload failure. 

It looks like we also need to change `PostCardCompactCell.xib` so that the status (e.g. “We'll publish the post...”) is shown at the bottom. 

<img width="355" alt="PostCompactCell xib 2019-11-06 10-49-58" src="https://user-images.githubusercontent.com/198826/68323851-80369d00-0083-11ea-8d96-2fbe7ba954c7.png">

We recently did something similar on Android so it might be worth looking at how we solved this there too: https://github.com/wordpress-mobile/WordPress-Android/pull/10559

Please let me know if you have any questions. 🙂 And feel free to tag me when you send a pull request.
