### ISSUE TITLE
Unable to share from Safari or Photos

### ISSUE THREAD

**Issue by melindahelt** [wordpress-mobile/WordPress-iOS#12674]
### Expected behavior
I expected to be able to use the built in share features from Safari and Photos to save content as a draft

### Actual behavior
Error

![IMG_0102](https://user-images.githubusercontent.com/8306136/66602149-7c445780-eb77-11e9-92cb-2ebfb7450fd0.png)

### Steps to reproduce the behavior
1. Confirm that you are logged into iOS app
2. Go to Safari,  load website
3. Click share button
4. Select "save as draft (wp internal)"
5. See error above
6. Repeat same steps with photo

Confirm that it does in fact work from same device using stable 13.2.3 WPiOS

##### Tested on [device], iOS [version], WPiOS [version]
iPhone Xr, iOS 13.1.2 and WPiOS 13.4

**Comment by designsimply** [comment]
I tested and found that I could only see this bug happen if I logged in to the app and never viewed the profile screen (Me) at any point before trying a share. ([50s](https://cloudup.com/cffDyDu7zfQ))

<sup>Tested with WP Internal 13.4.20191010 (HockeyApp) and WPiOS 13.4.0.1 (TestFlight) on iPhone 6S iOS 13.2 beta.</sup>

Super tricky 🐛!

**Comment by designsimply** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/12697 since that one got more information before I spotted it as a duplicate.
