### ISSUE TITLE
[Offline Posting] Update copy on failure to upload media

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#12677]
From Design Review: The “this” in “We couldn't upload this media” Post List message may not be applicable if the post has more than one media.

1. Be offline
2. Create a post
3. Add more than one media to post
4. See the copy "“We couldn't upload this media..."

**Comment by kean** [comment]
Not applicable starting from 24.9 – these messages were removed (pcdRpT-6vS-p2)
