### ISSUE TITLE
[Offline Posting] Modify display of  “We won't save the latest changes to your draft” notice 

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#12679]
From Design Review: “We won't save the latest changes to your draft” is misleading for existing draft posts.

Pressing Cancel on an offline-edited draft will show this Snackbar message. However, it is misleading because we auto-save the draft anyway. And the auto-save API's behavior will **overwrite** drafts instead of creating revisions. 

- [ ] We can optionally not show it if the `status` transition is `.draft` to `.draft` but show it if it's `.published` to `.draft`. We can probably use the `statusAfterSync` property. 
- [ ] If the above is difficult, we can optionally just remove the “Cancel” button for edited drafts.

**Comment by kean** [comment]
Not applicable starting from 24.9 – **all** of these message were removed (pcdRpT-6vS-p2)
