### ISSUE TITLE
[Offline Posting] Show snackbar with "We'll publish the post" on failure to upload post with media

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#12678]
From Design Review: “We'll publish the post...” Snackbar is not shown when publishing a post with media while offline.

It shows a “1 post, 1 file not uploaded” instead.

This used to work so it seems that some of our latest work caused this regression.

Steps:
1. Be offline 
2. Create a post with media
3. publish the post
4. See the notice "1 post, 1 file not uploaded"

**Comment by shiki** [comment]
Done in #12722 and #12739
