### ISSUE TITLE
[Offline Posting] Modify "Uploading post..." status when post is not actually uploaded

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#12676]
From Design Review: When auto-saving a post, the Post List shows “Uploading post...“

This is misleading since we're just saving a revision and it can seem contradicting when we display a notice telling the user that we won't upload the post like in case where the upload failed and the user chooses to cancel the auto upload using the cancel button in the post list.  

Note that Android shows the same message.

Steps:

1. Be offline
2. upload a draft
3. See "post will be uploaded..." notice
4. go to post list and tap cancel on the post
5. Go online 
6. see the "Uploading post..." with progress bar

**Comment by kean** [comment]
Not applicable staring from 24.9 (pcdRpT-6vS-p2).
