### ISSUE TITLE
[Offline Posting] Mismatch in colors of texts and icons in post list card menu items

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#12681]
From Design Review: The _Cancel_ button's color in the Post List does not match the warning message's color.

- [ ] Verify if this how iOS's design is supposed to be
- [ ] The Retry button icon's color is blue so this may need to be changed as well.

**Comment by kean** [comment]
Not applicable starting from 24.9 – it was removed (pcdRpT-6vS-p2)
