### ISSUE TITLE
Investigate warning: UITableView was told to layout its visible cells and other contents without being in the view hierarchy

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#12689]
Message in debugger:

> Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window

Following the instructions and adding a symbolic breakpoint shows stops in:

https://github.com/wordpress-mobile/WordPress-iOS/blob/1a94347748be56f51c0ecc1055f7a19675c781cf/WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift#L565

And here:

https://github.com/wordpress-mobile/WordPress-iOS/blob/1a94347748be56f51c0ecc1055f7a19675c781cf/WordPress/Classes/ViewRelated/Notifications/Tools/IntrinsicTableView.swift#L20

<img width="1135" alt="Screen Shot 2019-10-12 at 4 14 27 PM" src="https://user-images.githubusercontent.com/1335657/66709001-fd365700-ed0f-11e9-8510-0992e62e4674.png">
<img width="1413" alt="Screen Shot 2019-10-12 at 4 14 45 PM" src="https://user-images.githubusercontent.com/1335657/66709003-fd365700-ed0f-11e9-9e09-344db7a003ad.png">
<img width="1437" alt="Screen Shot 2019-10-12 at 4 15 35 PM" src="https://user-images.githubusercontent.com/1335657/66709004-fd365700-ed0f-11e9-9567-fa58cb9e2107.png">

### Steps to reproduce the behavior
1. Open the app
2. tap into stats, themes or tap on reader/ me / notifications 
3. rotate the device / simulator 
4. Check debugger for the warning message 

I wonder if these could be related to the latest issues we're seeing  with "Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread." e.g: https://github.com/wordpress-mobile/WordPress-iOS/issues/12628

Only relevant mention I found for this in our rep is here: https://github.com/wordpress-mobile/WordPress-iOS/issues/12554

Related discussions on Apple forum: https://forums.developer.apple.com/thread/120790

##### Tested on [device], iOS [version], WPiOS [version]
iOS 13

**Comment by designsimply** [comment]
Moving to the Prioritized iOS list in the Groundskeeping (maintenance) project board because of the `Pri [High]` label attached.

Please note that sluggish Stats performance has come up multiple times recently from Eli and others at our division meetup. If this investigation can lead to improved performance in Stats, then it should definitely be high priority.

**Comment by diegoreymendez** [comment]
I've spent almost the full day today investigating this in more depth, with little success.

I've tried to void calling `layoutIfNeeded` by placing a guard [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/1a94347748be56f51c0ecc1055f7a19675c781cf/WordPress/Classes/ViewRelated/Reader/ReaderStreamViewController.swift#L561):

```swift
        guard view.window != nil else {
            return
        }
```

Which worked to avoid the specific case we were seeing, but I keep getting the same warning due to this line, wich is causing a layout to happen:

https://github.com/wordpress-mobile/WordPress-iOS/blob/68b83d995f6bc31ba3843db69c5c31a180482433/WordPress/Classes/ViewRelated/System/WPSplitViewController.swift#L503

I tried replacing that line with `return false`, which would seem like it fixes both warnings, but I'm not sure this won't have undesirable side effects.  Maybe @frosty can comment on this, since he worked in the original code.

Even with both fixes above, the OS still keeps raising this warning on its own from other paths like the one reported in the following stack trace (in which none of our code is executed):

```
Thread 1 Queue : com.apple.main-thread (serial)
#0	0x00007fff48260c7e in UITableViewAlertForLayoutOutsideViewHierarchy ()
#1	0x00007fff4825f946 in -[UITableView _updateVisibleCellsNow:] ()
#2	0x00007fff4828055f in -[UITableView layoutSubviews] ()
#3	0x00007fff485784bd in -[UIView(CALayerDelegate) layoutSublayersOfLayer:] ()
#4	0x00007fff2b131db1 in -[CALayer layoutSublayers] ()
#5	0x00007fff2b137fa3 in CA::Layer::layout_if_needed(CA::Transaction*) ()
#6	0x00007fff48563635 in -[UIView(Hierarchy) layoutBelowIfNeeded] ()
#7	0x00007fff47978038 in -[UINavigationController _layoutViewController:] ()
#8	0x00007fff479710e9 in -[UINavigationController _layoutTopViewControllerLookForNested:] ()
#9	0x00007fff47966e9a in __105-[UINavigationController _repositionPaletteWithNavigationBarHidden:duration:shouldUpdateNavigationItems:]_block_invoke ()
#10	0x00007fff47966b9c in -[UINavigationController _repositionPaletteWithNavigationBarHidden:duration:shouldUpdateNavigationItems:] ()
#11	0x00007fff47970339 in -[UINavigationController _updateBarsForCurrentInterfaceOrientationAndForceBarLayout:] ()
#12	0x00007fff47a42124 in -[_UIViewControllerTransitionCoordinator _applyBlocks:releaseBlocks:] ()
#13	0x00007fff47a3e446 in -[_UIViewControllerTransitionContext __runAlongsideAnimations] ()
#14	0x00007fff4856bde6 in +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] ()
#15	0x00007fff4856c395 in +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:options:animations:completion:] ()
#16	0x00007fff47a5665a in __58-[_UIWindowRotationAnimationController animateTransition:]_block_invoke_2 ()
#17	0x00007fff4856ff44 in +[UIView(Internal) _performBlockDelayingTriggeringResponderEvents:forScene:] ()
#18	0x00007fff47a563e8 in __58-[_UIWindowRotationAnimationController animateTransition:]_block_invoke ()
#19	0x00007fff4856bde6 in +[UIView(UIViewAnimationWithBlocks) _setupAnimationWithDuration:delay:view:options:factory:animations:start:animationStateGenerator:completion:] ()
#20	0x00007fff4856c395 in +[UIView(UIViewAnimationWithBlocks) animateWithDuration:delay:options:animations:completion:] ()
#21	0x00007fff47a562c0 in -[_UIWindowRotationAnimationController animateTransition:] ()
#22	0x00007fff480d2e9d in -[UIWindow _rotateToBounds:withAnimator:transitionContext:] ()
#23	0x00007fff480d58e0 in -[UIWindow _rotateWindowToOrientation:updateStatusBar:duration:skipCallbacks:] ()
#24	0x00007fff480d5ed3 in -[UIWindow _setRotatableClient:toOrientation:updateStatusBar:duration:force:isRotating:] ()
#25	0x00007fff480d4e27 in -[UIWindow _setRotatableViewOrientation:updateStatusBar:duration:force:] ()
#26	0x00007fff480d3ca4 in __57-[UIWindow _updateToInterfaceOrientation:duration:force:]_block_invoke ()
#27	0x00007fff480d3bcd in -[UIWindow _updateToInterfaceOrientation:duration:force:] ()
#28	0x00007fff23b9b5bc in __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ ()
#29	0x00007fff23b9aa35 in _CFXRegistrationPost1 ()
#30	0x00007fff23b9a7a1 in ___CFXNotificationPost_block_invoke ()
#31	0x00007fff23c988b3 in -[_CFXNotificationRegistrar find:object:observer:enumerator:] ()
#32	0x00007fff23b9a0f6 in _CFXNotificationPost ()
#33	0x00007fff2574bbf7 in -[NSNotificationCenter postNotificationName:object:userInfo:] ()
#34	0x00007fff47cd5955 in -[UIDevice setOrientation:animated:] ()
#35	0x00007fff477c83f1 in __134-[_UIWindowSceneDeviceOrientationSettingsDiffAction _updateDeviceOrientationWithSettingObserverContext:windowScene:transitionContext:]_block_invoke ()
#36	0x00007fff47bd8c83 in +[BSAnimationSettings(UIKit) tryAnimatingWithSettings:actions:completion:] ()
#37	0x00007fff47cd2dff in _UISceneSettingsDiffActionPerformChangesWithTransitionContext ()
#38	0x00007fff477c8336 in -[_UIWindowSceneDeviceOrientationSettingsDiffAction _updateDeviceOrientationWithSettingObserverContext:windowScene:transitionContext:] ()
#39	0x00007fff477c8231 in __163-[_UIWindowSceneDeviceOrientationSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:]_block_invoke ()
#40	0x00007fff47cd2d02 in _UISceneSettingsDiffActionPerformActionsWithDelayForTransitionContext ()
#41	0x00007fff477c80c1 in -[_UIWindowSceneDeviceOrientationSettingsDiffAction _performActionsForUIScene:withUpdatedFBSScene:settingsDiff:fromSettings:transitionContext:lifecycleActionType:] ()
#42	0x00007fff476206e7 in __64-[UIScene scene:didUpdateWithDiff:transitionContext:completion:]_block_invoke ()
#43	0x00007fff4761f26c in -[UIScene _emitSceneSettingsUpdateResponseForCompletion:afterSceneUpdateWork:] ()
#44	0x00007fff47620411 in -[UIScene scene:didUpdateWithDiff:transitionContext:completion:] ()
#45	0x00007fff47bfac66 in -[UIApplicationSceneClientAgent scene:handleEvent:withCompletion:] ()
#46	0x00007fff365d6c07 in -[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:] ()
#47	0x00007fff365fc99f in __88-[FBSWorkspaceScenesClient sceneID:updateWithSettingsDiff:transitionContext:completion:]_block_invoke_2 ()
#48	0x00007fff365e0c45 in -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:] ()
#49	0x00007fff365fc8dc in __88-[FBSWorkspaceScenesClient sceneID:updateWithSettingsDiff:transitionContext:completion:]_block_invoke ()
#50	0x00000001136e3d48 in _dispatch_client_callout ()
#51	0x00000001136e6cb9 in _dispatch_block_invoke_direct ()
#52	0x00007fff3662237e in __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__ ()
#53	0x00007fff3662206c in -[FBSSerialQueue _queue_performNextIfPossible] ()
#54	0x00007fff3662257b in -[FBSSerialQueue _performNextFromRunLoopSource] ()
#55	0x00007fff23bd4471 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ ()
#56	0x00007fff23bd439c in __CFRunLoopDoSource0 ()
#57	0x00007fff23bd3b74 in __CFRunLoopDoSources0 ()
#58	0x00007fff23bce87f in __CFRunLoopRun ()
#59	0x00007fff23bce066 in CFRunLoopRunSpecific ()
#60	0x00007fff384c0bb0 in GSEventRunModal ()
#61	0x00007fff48092d4d in UIApplicationMain ()
#62	0x000000010d30ef31 in main at /Users/diego/Developer/WordPress-iOS/WordPress/Classes/System/main.swift:7
#63	0x00007fff5227ec25 in start ()
#64	0x00007fff5227ec25 in start ()
```

Unfortunately at this point, I'm feeling like I need to wrap my time-box for this task and move on to the next one.

My rationale is:

1. I'm not sure my fixes above won't have side effects.  Maybe @frosty can help me clear those doubts.
2. Even after my fixes above, the warning will still be present due to the OS triggering layouts on tables that are not in the view hierarchy.
3. I'm not sure what this will fix, beyond just the warning.  I'd suggest re-considering the "high priority" label this issue has.

For now I'm simply unassigning myself and moving to the next task.   Please feel free to ping me if there are doubts / questions.

**Comment by guarani** [comment]
Closing this due to over two years of inactivity, it can be re-opened if needed (for more context on why we're closing issues, see pdXTV4-x5-p2).
