### ISSUE TITLE
Dark mode: Text pasted in from non-dark mode sources near-invisible

### ISSUE THREAD

**Issue by KokkieH** [wordpress-mobile/WordPress-iOS#12688]
### Expected behavior
For text pasted into the editor in dark mode to appear in white on the dark background.

### Actual behavior
Text pasted into the editor remains black, making it almost invisible in the editor.

### Steps to reproduce the behavior
1. Copy text from a source that's not in dark mode, where the text displays black on white, e.g. Simplenote web app
2. Paste into the WordPress app editor with dark mode active.

##### Tested on [iPad Mini], iOS [iPadOS 13.1.2], WPiOS [13.4.0.20191010] (@rachelmcr)

Reported by a user via [Twitter](https://twitter.com/iPadProsPodcast/status/1182481738162933760).

Discussion in p1570785995017600-slack-cellular-happiness

**Comment by fresatomica** [comment]
A user reported this happening also when adding the text from the desktop and then opening the post in the mobile app: https://gifyu.com/image/vIvK

https://en.forums.wordpress.com/topic/wordpress-app-dark-theme-not-working-with-black-font/

**Comment by maxme** [comment]
Notes: 
1. This is fixed in Gutenberg.
2. @SergioEstevao is working on a fix for Aztec.

**Comment by SergioEstevao** [comment]
Fixed in Aztec and Gutenberg.
