### ISSUE TITLE
[Offline Posting] Modify “We won't publish these changes” notice copy for newly created post

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#12680]
From Design Review: When canceling a locally published post, the message “We won't publish these changes” is shown.
We felt that the word “changes” is a bit misleading for a **new** post. The message “We won't publish this post” may be better.

**Comment by osullivanchris** [comment]
Should we get a copy review here to be sure?

**Comment by michelleweber** [comment]
Change looks good to me!

**Comment by kean** [comment]
Not applicable starting from 24.9 – **all** of these message were removed (pcdRpT-6vS-p2)
