### ISSUE TITLE
Switching between editors doesn't reflect the post status

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#12696]
### Expected behavior

If I have a scheduled post and switch between editors, I would expect that the button will still have the label "Schedule"

### Actual behavior

When you switch between editors the button will have the label "Publish", doesn't matter which `status` the post has,

### Steps to reproduce the behavior

1. Create a new Schedule or Pending post using Aztec or Gutenberg
2. Switch to the other editor
3. Check that the button label is "Publish"

<img src="https://user-images.githubusercontent.com/9772967/66828275-e763a480-ef50-11e9-8dd9-93507066b357.gif" />

**Comment by kean** [comment]
Obsolete as scheduling options are not present only in the republishing sheet and are in memory so the "Publish" button doesn't change title.
