### ISSUE TITLE
pull to refresh animantion doesn't properly clear if the top of the table is above the animation

### ISSUE THREAD

**Issue by irbrad** [wordpress-mobile/WordPress-iOS#1271]
Video of the issue:

https://cloudup.com/cpCbyPbKe4G

**Comment by rachelmcr** [comment]
@irbrad - The video is no longer available, so I'm not sure if I'm testing the right issue. Can you still reproduce this issue?

**Comment by rachelmcr** [comment]
I'm going to go ahead and close this issue, but if you can still reproduce it (and/or provide more detailed steps to reproduce) please reopen.
