### ISSUE TITLE
Information Architecture: navigation menus are not consistent with Calypso or WP Admin

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12748]
With <a href="https://dotcomdesignp2.wordpress.com/2019/03/27/nav-drawer-master-thread/">Calypso's recent reorganization of the nav drawer</a>  the language used there has shifted and now our app doesn't match. Currently we use  “Site Pages” and “Blog Posts” in the app, but “pages” and “posts” is used in Calpyso and wp-admin. We also still organize items under the categories <code>Publish</code> <code>Look and Feel</code> <code>Configuration</code> while in Calpyso that is now <code>Site</code> <code>Design</code> <code>Tools</code> and <code>Manage</code>.

<img src="https://user-images.githubusercontent.com/1119271/67258252-e64cde80-f44c-11e9-8ac5-93adb4a6a0e3.png" width="270" alt="screenshot_20191017-094950"> <img src="https://user-images.githubusercontent.com/1119271/67258251-e64cde80-f44c-11e9-97fd-81070b8b01bc.png" width="270" alt="Screen Shot on 2019-10-17 at 09-56-57"> 

<sub>/hat tip @sarahfg for the report (internal reference: p4a5px-2s0-p2, 2428254-zen).</sub>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
