### ISSUE TITLE
Layout / Dark Mode: the "Done" button background after publishing a post is black but should be blue

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12747]
Steps to reproduce:

1. Create and publish a new post.
1. Tap "View" on the notice that appears.

**Result:** the "Done" bar background is black but should be blue.

<img src="https://user-images.githubusercontent.com/1119271/67257133-bbac5700-f447-11e9-9ff0-b69e32044fcc.PNG" width="270" alt="IMG_3249"> <img src="https://user-images.githubusercontent.com/1119271/67257132-bbac5700-f447-11e9-9485-6069303f16c4.PNG" width="270" alt="IMG_3248"> 
<sup>Light mode (left) and dark mode (right) tested with WPiOS 13.5.0.0 beta (TestFlight) on iPhone 6S iOS 13.2.</sup>

<sub>/hat tip @bisko for the report (internal reference: p4a5px-2rG-p2)</sub>

**Comment by ScoutHarris** [comment]
Looks like this has been resolved, and the colors updated.

| ![light](https://user-images.githubusercontent.com/1816888/76446070-18bf8f80-638c-11ea-9116-634f1d775eb6.png) | ![dark](https://user-images.githubusercontent.com/1816888/76446090-1fe69d80-638c-11ea-9a6c-f710bcc614bf.png)  |
|--------|-------|
