### ISSUE TITLE
Quick Start: View Site banner doesn't disappear when it should #10654

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12740]
This bug was reported by a user during 13.4 beta testing. Two people tried and couldn't replicate the problem but I still wanted to post it here for visibility. 

### Expected behavior

I expected the banners or notices in the Quick Start flow to disappear when I do the View Site step.

### Actual behavior

Someone reported that the banner doesn't go away for the View Site step in Quick Start.

<img src="https://user-images.githubusercontent.com/1119271/67228524-a78c3980-f3f6-11e9-974d-aeabd6c9420a.jpg" width="270" alt="screenshot_01">

### Steps to reproduce the behavior

1. Go to the login screen.
1. Tap "Sign up for WordPress.com".
1. Tap "Sign up with Email".
1. Follow the prompts until you reach the screen saying "Want a little help getting started?".
1. Tap "Yes, Help Me".
1. Tap "View your site" in the "Customize Your Site" screen or tap "Yes, show me" in the "View your site" popup.
1. Check to see if the "Tap $site to preview" banner disappears as it should.

**Result:** the "Tap $site to preview" in the View Site step in Quick Start doesn't disappear in some cases. 

**Note:** I tested and was not able to reproduce the problem. ([4m27s](https://cloudup.com/cyQx9ZdGesP)) Here are my screenshots:

<img width="200" alt="Screen Shot 2019-10-21 at Oct 21 11 42 59 AM" src="https://user-images.githubusercontent.com/1119271/67229329-52e9be00-f3f8-11e9-85f7-d06afb222a19.png"> <img width="200" alt="Screen Shot 2019-10-21 at Oct 21 11 42 07 AM" src="https://user-images.githubusercontent.com/1119271/67229331-53825480-f3f8-11e9-8ebc-9f06fe4ce37f.png"> <img width="200" alt="Screen Shot 2019-10-21 at Oct 21 11 41 15 AM" src="https://user-images.githubusercontent.com/1119271/67229332-53825480-f3f8-11e9-9802-df2e6bfe6dc8.png">
<sup>Tested with WPiOS 13.4.0.1 beta (TestFlight) on iPhone 6S iOS 13.2 beta.</sup>

<sup>/hat tip @rachelmcr for the original report (internal reference: p5T066-11x-p2#comment-3605).</sup>

**Comment by rachelmcr** [comment]
I noticed looking at the user's screenshot that they are looking at a post/page preview — note the back arrow and "Preview" text at the top of the screen, and the bottom navigation at the bottom of the screen, both of which appear when previewing a post/page but not when viewing a site from "View Site."

I still couldn't reproduce the issue that way (as soon as I switched to Posts the Quick Start tour disappeared as it should per https://github.com/wordpress-mobile/WordPress-iOS/issues/10398) but that might be a clue.

**Comment by rachelmcr** [comment]
Ah, I found steps that can reproduce this:

1. Create a new WordPress.com site in the app.
2. Follow the prompts until you reach the screen saying "Want a little help getting started?".
3. Tap "Yes, Help Me".
4. Go through each of the tour items in order, stopping when you get to the "View your site" prompt with "Now now" and "Yes, show me" options.
5. With that prompt still on the screen, open the Blog Posts section.
6. Tap "View" to preview a post.
7. While previewing the post, tap "Yes, show me" on the "View your site" prompt.

Result: The blog post preview is open with the "Tap View Site to preview" prompt visible and undismissible on the screen. The prompt stays on the screen until you go back to the My Site screen and either tap "View Site" or open a new section, at which point it is dismissed.

**Comment by frosty** [comment]
I think the right fix here might be to pop the My Site screen back to the root when the user taps on "Yes, show me". That way, the prompted control will be visible on screen.
