### ISSUE TITLE
[Gutenberg] Image file can be uploaded multiple times

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12744]
While working on #12678, we found that it's possible to have an image file attached to a post multiple times. The post will only show 1 media, but the image is uploaded and shown in the Media Library more than once. 

## Expected behavior

The image file is only uploaded once.

## Actual behavior

The image file is uploaded multiple times.

### Steps to reproduce the behavior

1. git checkout dae0b10. Run the app.
2. Edit an existing post (Gutenberg).
3. Go offline.
4. Add an image.
5. Tap X -> Update Post
6. Edit the same post again.
7. Tap X -> Update Post
8. Repeat steps 6 to 7 multiple times. You'll notice that the Snackbar will say
   “1 post, n+1 files not uploaded”.
9. Go online.
10. Tap Retry on the post's card.

When the post is uploaded successfully, go to the Media library. Notice that the image
you added has been uploaded multiple times.

## Others 

We thought this was the cause of an infinite upload so we added a workaround 
(7a106d1) in PR https://github.com/wordpress-mobile/WordPress-iOS/pull/12739. However, we found out that it can be solved by a different change. We reverted the workaround in db1070c. 

Tested on iPhone XS, iOS 12.4.1

**Comment by hypest** [comment]
Tried WPiOS v15.2 and cannot reproduce the issue. In particular, the snackbar doesn't mention "n+1 files not uploaded" at all and the file ended up only once in the media library.

> We reverted the workaround in db1070c

Not sure if this has been worked on separately in the end? @shiki , can you confirm whether the issue still occurs in your tests? Thanks!

**Comment by shiki** [comment]
Hi @hypest! Thank you for the ping. I can no longer reproduce this in `develop` (eec6266d17). Looks like this has been fixed! 🎉
