### ISSUE TITLE
Domain Credit: Domain credit check repeatedly fails, possibly due to device locale

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#12774]
### Expected behavior

I expect that when I have a domain credit on my site, I'll see the option to register a domain on the My Sites tab.

### Actual behavior

I consistently didn't see the option to register a domain on any site, even if I confirmed I had a domain credit on the site and even after restarting my device or re-logging in to the app. It didn't occur to me that the domain credit prompt was missing, but I can see even in the oldest log in the app from 18 Oct (on 13.4.0.20191010) that this was happening then.

In the logs, I saw this error (for various sites):

```
2019-10-24 20:53:34:220 Failed checking domain credit for site https://rachelmtestblog.wordpress.com: Error Domain=WordPressKit.PlanServiceRemote.ResponseError Code=2 "(null)"
```

I then happened to switch my device from `en-UK` to `en-US`, and the problem resolved itself — immediately when I returned to the app (making no other changes) the "Register Domain" prompt appeared. Now, even after switching back to `en-UK`, I still see that prompt.

### Steps to reproduce the behavior

I'm not sure yet, as I haven't been able to reproduce the problem since switching locales.

**Comment by Gio2018** [comment]
I believe this was addressed by #16989 .
