### ISSUE TITLE
Author is not displayed for posts created while offline

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#12776]
The author is not displayed for posts created while offline.

### Steps to reproduce the behavior

1. While offline, create a new post and publish it
2. Make sure "Everyone" is selected
3. Check that no author is displayed

<img src="https://user-images.githubusercontent.com/7040243/67575516-1fb67000-f713-11e9-9078-8b86ccefdb18.PNG" width="400px;">

**Comment by kduncanwelke** [comment]
I'm going to try tracking this one down. 👍🏻
