### ISSUE TITLE
Support: cannot get responses to support messages if a message is sent without setting a contact email

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12779]
Steps to reproduce:

1. Do a fresh install of the app.
1. Log in and to to Profile > Help & Support > WordPress Help Center.
1. Search for something like "test" to get the no results view.
1. Tap the "Contact us" link. 
1. Try to send a message.
1. Wait for a reply (if you have access to Zendesk then go there and send a reply).
1. Check to see if the reply ever appears in the app.

**Result:** the support message goes through but replies to it will have nowhere to go because no from email was set and the user won't be able to see it in "My Tickets" in the app because accessing that screen requires that the user sets an email address and once they do that the history of the previous messages is lost. The message sent will appear in the Zendesk queue as being from "Mobile App User" and there is no email address at the top—no replies will get back to the user.

<img src="https://user-images.githubusercontent.com/1119271/67609729-83f52600-f74b-11e9-8b09-e425c1411505.PNG" width="200" alt="IMG_2988 1"> <img src="https://user-images.githubusercontent.com/1119271/67609788-d5051a00-f74b-11e9-8217-bbe5929e05d6.PNG" width="200" alt="IMG_2992 1"> <img src="https://user-images.githubusercontent.com/1119271/67609722-7344b000-f74b-11e9-9b4c-b30fdf9c80a4.PNG" width="200" alt="IMG_2990 1">
<sup>Tested with WPiOS 13.5(dev) branch `update/zendesk-to-3.0.2` on iPhone 6S iOS 13.1.3.</sup>

**Comment by ScoutHarris** [comment]
Actually, the problem is you shouldn't be able to create tickets from the Help Center if an email address is not set. We have ZD set to not show the 'contact' button in the nav bar to prevent this issue (_that_ appears to be working correctly. 

I haven't done these steps in a while, but this link is new(ish).
> Tap the "Contact us" link.

Zendesk might have added a new setting to disable that. Let's hope.
