### ISSUE TITLE
Notifications tab displays `No followers yet` message

### ISSUE THREAD

**Issue by poojashetty18** [wordpress-mobile/WordPress-iOS#12782]
**Expected behavior**
I expected to view my followers on my Notifications->Follows tab

**Actual behavior**
My followers are only visible when I head to `My Sites' -> 'People' under Configure but the Notifications tab also contains a 'Follows' option which does not display my followers as expected.

**Steps to reproduce the behavior**
<img src="https://user-images.githubusercontent.com/44837596/67654509-394ff580-f967-11e9-87af-5dd821ffe017.PNG" width="270" alt="IMG_5821"> <img src="https://user-images.githubusercontent.com/44837596/67654513-3bb24f80-f967-11e9-9fda-54f47942c0dd.PNG" width="270" alt="IMG_5822">

This issue seems to be present even on the Android version.

**Comment by designsimply** [comment]
In your People screenshot, I see that follower `anukoolhedge` is listed there. Do you happen to know that user started following the site (i.e. via the Reader, by using a form on the site's home page, through a checkbox when they replied to a comment, or some other way)? Do you know if `anukoolhedge` is an email-only follower.

Note: I did a few tests and found that new follows to an Atomic site I own showed up both in My Site > People > Followers as well as in Notifications > Follows but email-only followers did not show up in notifications for me even after verifying the subscription by email.

**Comment by aerych** [comment]
Closing.  The Notifications Followers tab is not intended to show a list of followers, rather notifications of when a new person followed a site.  We might look at improving the text on the no results view at some point if it's causing confusion, but unless we receive other reports it doesn't seem like something to prioritize.
