### ISSUE TITLE
When exiting the editor, Notices cover the tab bar

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12799]
## Expected behavior

The Notice is displayed above the tab bar.

## Actual behavior

The Notice is displayed on top of the tab bar, **covering** it. 

<img src="https://user-images.githubusercontent.com/198826/67792456-cc0f9380-fa3e-11e9-919e-f8e8f2c4e1c4.png" width="320">

### Steps to reproduce the behavior

1. While offline, create a post. 
2. Tap X → Save Draft

A Notice saying something like “We'll save your draft...”. should be shown. 

Tested on iPhone XS, iOS 12.4.1, WPiOS `develop` (d2d9ada).

**Comment by kduncanwelke** [comment]
I'm going to try to fix up this one. 👍🏻
