### ISSUE TITLE
Post error message wrapping on collapsed view

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#12816]
Mirroring https://github.com/wordpress-mobile/WordPress-Android/issues/10555

### Expected behavior

Status messages should not truncate on the post list screen. Text should wrap onto the next line when necessary, regardless of the layout (compact or regular).

### Actual behavior

Status messages appear truncated on the post list screen when using the compact layout. 

### Steps to reproduce the behavior

An example is the status message to be implemented in https://github.com/wordpress-mobile/WordPress-iOS/issues/12141, **_"You've made unsaved changes to this post"_**. This text does not fit the available space and is truncated.

<img src="https://user-images.githubusercontent.com/1898325/67915815-ad121e00-fb72-11e9-8fda-4a805f2a17b3.png" width="300">

**Comment by kduncanwelke** [comment]
I tried investigating this and am unable to get an unsaved changes status message to appear (as the app always prompts to either save or delete edits) - a status message about uploading the post once online again displayed entirely and on the next line, however. The issue may be fixed, but it's hard to tell without being able to see the unsaved changes message.

**Comment by guarani** [comment]
@kduncanwelke these are some steps that should allow you to reproduce this issue and determine if it's still present – taken from https://github.com/wordpress-mobile/WordPress-iOS/pull/12781#issue-332934456:

> 1. On WordPress.com, create a new post or open an existing post for editing
> 2. Set the title to “Hello, world!” and the body to “One.”
> 3. Publish the post
> 4. Re-open the post and add a new line, “Two.” – then close the browser tab without saving
> 5. Again, re-open the post and notice the following message -  “The backup of this post in your browser is different from the version below. Restore the backup”  – this signifies that an autosave was made
> 6. On the WordPress for iOS app, under the My Sites tab, navigate to the list of posts containing the newly created post
> 7. Observe that there is now a status label ("You've made unsaved changes to this post") indicating that an autosave version is available

**Comment by kduncanwelke** [comment]
It appears the position of the label has been changed, so the cut off no longer happens:

![Simulator Screen Shot - iPhone 11 - 2020-03-18 at 13 04 18](https://user-images.githubusercontent.com/43656898/76992341-1b386100-6919-11ea-9a5c-db779d978183.png)

It must have been fixed in a previous commit.

**Comment by guarani** [comment]
Thanks @kduncanwelke for confirming that the issue is no longer present.

Looking at https://github.com/wordpress-mobile/WordPress-iOS/pull/12899 and https://github.com/wordpress-mobile/WordPress-iOS/issues/12675, this issue does appear to have been fixed (the status label was moved to below the timestamp, in the compact layout). I was also unable to reproduce it locally.

@leandroalonso, I see you were involved in the above mentioned PR – would you say this issue can be closed?

**Comment by leandroalonso** [comment]
@kduncanwelke @guarani Yep! It was fixed, thank you both for looking into it!
