### ISSUE TITLE
Preview Post List View button does not show the local changes

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12828]
## Expected behavior

The preview should _probably_ show the local changes. 

## Actual behavior

The preview does not show the local changes.

### Steps to reproduce the behavior

1. Go offline. 
2. Edit an existing published post. 
3. Change the title and contents. Add an image. 
4. Tap X → Update Post
5. Tap Cancel
6. Go back online. The post card will show “Local changes”. Wait until the image has finished uploading. 
7. Tap on View. 

Notice that the Preview will show the _previously published_ title and content and not the changes that you made. 

Tested on iPhone Simulator Xs, iOS 12.2, WPiOS `develop` (c01bfee)

## Notes

This was found in p77Llu-cPf-p2#comment-15271. 

My guess here is that the preview is showing the published/uploaded version. I think we should use the same method that's used in the editor's Preview button which performs an autosave before previewing.

**Comment by chipsnyder** [comment]
Closing this out as Local previews have been deprecated https://github.com/wordpress-mobile/WordPress-iOS/issues/9282
