### ISSUE TITLE
Drafts of other users not visible

### ISSUE THREAD

**Issue by nielslange** [wordpress-mobile/WordPress-iOS#12825]
### Expected behavior

Drafts of other users are visible.

### Actual behavior

Drafts of other users are not visible.

### Steps to reproduce the behavior

1. Log in as user A and create a drafted post.
2. Log out as user A.
3. Log in as user B and look up drafted posts.

In my scenario, both user A and B have admin permissions.

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 7 / iOS 13.2 / WPiOS 13.4.1

**Comment by rachelmcr** [comment]
Thanks for the report! There should be an author picker in the top left on the Blog Posts list, next to the post filters, that lets you switch between users on a multi-user site:

<img src="https://user-images.githubusercontent.com/8658164/68031558-d5556600-fcb3-11e9-88bb-617f343e809b.jpeg" width="50%">

Is that missing for you?

We also had a past issue with that picker not showing up right after login, reported in https://github.com/wordpress-mobile/WordPress-iOS/issues/10859. I actually can't reproduce that issue when I test now but I'd be curious if that issue matches what you see (the picker doesn't appear the first time, but it does appear when you reopen the post list later).

**Comment by nielslange** [comment]
Thanks, @rachelmcr! I totally missed that icon and after selecting `Everyone` I'm able to see the drafted post of the other user. I'll close this issue for now and again, thanks for your quick reply! 🙌
