### ISSUE TITLE
[VoiceOver] Reader: News Card concerns

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#12845]
<img width="320" alt="iPhone Xs — 12 2 2019-11-04 13-48-18" src="https://user-images.githubusercontent.com/198826/68156833-c667f100-ff09-11e9-8f88-978c655e1912.png">

## Issue A: The whole card can be combined into a single VoiceOver element

When opening _Followed Sites_, the title of the News Card is dictated first. This can be a bit jarring experience. It the case of “Clearer Stats”, it's not clear why that's being dictated. 

Just like the other Reader cells, the News Card can be combined into a single unit. And the combined unit should have a `.button` trait. This makes it less convoluted. 

## Issue B: Dismiss button is unclear

The Dismiss button is dictated as “Dismiss”. It's not clear what it is _dismissing_.

**Comment by kean** [comment]
Closing as obsolete.
