### ISSUE TITLE
How to Set Category Wise Division Homepage in table Format  

### ISSUE THREAD

**Issue by Payal36** [wordpress-mobile/WordPress-iOS#12859]
i have one [job alert](https://wifijobalert.com) site and i want my home page to show category wise division with just a title of the article on it. can anybody help me out on this ?

**Comment by designsimply** [comment]
Hi @Payal36, you have posted in the WordPress for iOS bug and feature request system specifically for the iOS mobile app and your question appears to be about how to make a custom change to your WordPress home page which would mostly likely be done using custom theme code or with a plugin. 

To ask for help customizing WordPress, please ask at https://wordpress.org/support/forum/wp-advanced/ and mention what theme you are using and whether or not you know how to setup a child theme and how comfortable you are making changes to the theme code.

One potential workaround to showing the title only where posts are listed in most themes already, including archives pages as well as the home page, you can try adding a more tag at the very top of the post. See https://wordpress.org/support/topic/read-more-tag-28/ for some discussion about that.

I did a search on Google and found an article that describes how to limit posts by category in a couple different ways: https://www.wpbeginner.com/wp-tutorials/how-to-display-recent-posts-from-a-specific-category-in-wordpress/ Which option you choose will depend on the theme you're using and whether that theme already has widget areas placed where you want to display the lists of posts by category. 

Please have a look at the resources I've linked above and then please ask for help at https://wordpress.org/support/forum/wp-advanced/ and include details about your theme and what you've tried so far.
