### ISSUE TITLE
Gutenberg progressive rollout strategy

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-iOS#12888]
Implement a progressive rollout strategy to opt more users in the Gutenberg editor.

The current idea is to do this on the client only and take into account the current user preference.

- If the user opt-ed out Gutenberg, we don't want to opt them in.
- Progressive (target 10%, then 20%, then 50%, then 100%) to make sure all use cases are covered and that we have time to manage fixes.
- Target WordPress.com users first.

Android equivalent: https://github.com/wordpress-mobile/WordPress-Android/issues/10747

**Comment by maxme** [comment]
I had a look at the iOS migration and unfortunately we can't distinguish users who didn't change their editor settings or if they actually opt-ed out gutenberg.

Looking at the migration code: 
https://github.com/wordpress-mobile/WordPress-iOS/blob/b53c3c1afb889136e283241c9ce69661b80a5554/WordPress/Classes/Utility/Migrations/87-88/BlogToBlogMigration87to88.swift#L20-L28

During the migration `isGutenbergEnabled` default to `false` in case the setting wasn't defined, and then it will remotely change the mobile editor setting and set it to `aztec`.

I wanted to implement the equivalent of https://github.com/wordpress-mobile/WordPress-Android/issues/10747 but this won't be possible as it.

There might be an alternative solution, but not perfect solution: reuse the `kUserDefaultsGutenbergEditorEnabled` value and if it's not defined, consider the user didn't opt-ed out, whatever the `mobileEditor` value is.

**Comment by hypest** [comment]
Can we close this or is there any rollout step yet to occur?
