### ISSUE TITLE
Add events for actions on new interstitial and validate

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#12880]

**Comment by maxme** [comment]
Make sure to use the same event and property names that we're using on Android: https://github.com/wordpress-mobile/WordPress-Android/pull/11014

**Comment by maxme** [comment]
We used the following event names:
```
welcome_no_sites_interstitial_shown
welcome_no_sites_interstitial_button_tapped
welcome_no_sites_interstitial_dismissed
```

Discussion about the names: https://github.com/wordpress-mobile/WordPress-Android/pull/11014#discussion_r361180655
