### ISSUE TITLE
Menus: Can't view (or delete) invalid menu items

### ISSUE THREAD

**Issue by catkiinson** [wordpress-mobile/WordPress-iOS#12914]
### Expected behavior
Be able to delete invalid menu items. 

### Actual behavior
Invalid menu items not listed. 

### Steps to reproduce the behavior
On desktop browser: 
- Publish a new site page. 
- Add site page to menu. 
- Delete site page. 

On iOS mobile app: 
- Try to delete that menu item 
- Cannot delete it as it isn't listed. It still shows on the live site. 

##### Tested on [device], iOS [version], WPiOS [version]
iPhone XR, iOS 13.1.2, WPiOS 13.4.1

Reported by user in 2482573-zen. Was able to replicate on my own test site.

**Comment by designsimply** [comment]
Thank you for reporting this! I re-tested using the steps provided but when I deleted the page on the web it was removed from the menu on the front-end and I feel that is the appropriate behavior. ([3m24s](https://cloudup.com/cOKuD1KwYLv))

It's possible the reporting user had the front-end view with the deleted menu item cached or it's possible the issue has been fixed between the time you reported it and now. In any case, I think we can close this issue and we can always re-open or report it again as new if it comes up again. Cheers!
