### ISSUE TITLE
Enhanced / Full Screen Commenting

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#12918]
At the moment the comment input field is restricted to 5 lines of text. Editing a comment or composing a longer comment can, therefore, be fiddly and generally a bad experience. We want to improve this experience and remove the frustration from composing a longer comment.

**Goals:**

 - Allow a full-screen view for comments
 - Provide a better commenting experience

![](https://user-images.githubusercontent.com/912252/63276854-23a1be00-c29c-11e9-8b9a-04051956c486.png)

**Colors**

- Background color -> .basicBackground
- Divider -> .divider
- Text (even title) -> .text
- Placeholder text -> .textPlaceholder
- Expand/Collapse icon -> .listIcon
- Send button active -> .primary or .primaryButtonBackground
- Send button inactive -> .listSmallIcon

**Comment by emilylaguna** [comment]
Subtasks:

- [ ] Update the UI for the existing `ReplyTextView`
  - Remove border from text field
  - Update the comment field font
  - Replace the 'Reply' with the new image from the design
    - Get the correct 'reply' icon

- [ ] Animate the reply button
   - When textfield gains focus:
     - Transition the button in from the right
   - When textfield loses focus: 
      - Transition the button out from the left
   - When the button is active:
    - Change tint color to: .primaryButtonBackground
  - When the button is inactive:
    - Change tint color to: .listSmallIcon

- [ ] Add ability to go fullscreen while commenting
  - Add a button to "enter fullscreen" with the gridicon: `chevron-up`
  - Utilize the EditViewController to allow for fullscreen commenting
     - Subclass the EditViewController to change the UI
       - Override the Cancel button to exit fullscreen instead
       - Add a button to "exit fullscreen" with the gridicon: `chevron-down`

- [ ] Implement fullscreen commenting in the following locations:
  - `CommentViewController`
  - `NotificationDetailsViewController`
  - `ReaderCommentsViewController`
