### ISSUE TITLE
Crashing at launch on iPhone 6 for some users

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#12941]
Opening an issue to track.

We have a couple of reports in the iOS forum from iPhone 6 users reporting that a fresh install of the app crashes at launch.  See:
https://ios.forums.wordpress.org/topic/app-crashing-on-iphone-6-ios-1242
https://ios.forums.wordpress.org/topic/wordpress-app-crashing?replies=10#post-15515
One user provided a video demonstrating the issue at https://youtu.be/S4w_hzhAwiA 

This seems unrelated to some other issues where the app is crashing at launch in that its a fresh install--no chance of a Core Data issue or dup account/blog issue, etc. 

My suspicion is the app is being terminated due to low resources, but this is tricky to test and reproduce due to individual device differences.  Our own testing on an iPhone 5s, and iPhone 6, and an iPad mini 2 (all devices with one gig of ram) has shown the app can launch and perform well on older iOS devices.

If we can find a device that reproduces the issue, it would be interesting to inspect its console logs via Xcode > Window > Devices and Simulators > [The connected device] > Open Console and see what is logged when the app is launched.

**Comment by designsimply** [comment]
> I can’t use Wordpress on my iPad. Every time I open the app it shuts down without allowing me to use it. When I click on the WP icon, the app seems to open as I get to a blue screen showing WP but after a few seconds it simply shuts down. I never get to a human image icon screen at all (& can’t see any blogs, etc.).
> I tried a fresh installation already in the past and it didn’t help.
> A soft reset of my iPad doesn’t help either.

* iPad mini 2; software version 12.4.5
* Capacity 12GB; Availability 2.07GB

Note: the same person has a iPhone 6 iOS 12.4.5 device running WPiOS 14.1 which is working normally for them.

<sup>(internal reference: 2730643-zen)</sup>

**Comment by diegoreymendez** [comment]
@designsimply - Have there been new reports of this issue?

The video is no longer accessible and I don't feel we have enough information on this issue to follow up right now.

I suggest closing this issue for now if there haven't been new reports.

**Comment by diegoreymendez** [comment]
Closing for now.  Feel free to reopen.

**Comment by designsimply** [comment]
No new issues that I know of! Thank you for asking. Happy to re-open if we get any new reports (but also happy to track that in a new issue if someone misses this when reporting in the future). Thanks @diegoreymendez! 👍
