### ISSUE TITLE
Refine border color on default site icon

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/WordPress-iOS#12942]
Default site icons have a solid white border, which IMO looks _okay_ in light mode, but it's a bit strong in dark mode.

<img width="382" alt="image" src="https://user-images.githubusercontent.com/1200432/68784379-13328280-0602-11ea-8a5a-aead802c7326.png">

We might want to refine this by either removing the border or dimming/thinning the color relative to the background color, which looks roughly like `SystemGray`. Here are some examples of the current, and a few options:

* No borders (probably the most straight-forward solution)
* Solid systemGray borders
* Semi-transparent borders

<img width="776" alt="image" src="https://user-images.githubusercontent.com/1200432/68785794-4d9d1f00-0604-11ea-9751-b505e52b6834.png">

cc @mattmiklic @SylvesterWilmott – any thoughts or preferences?

**Comment by mattmiklic** [comment]
I'd be in favor of eliminating the border altogether.

**Comment by SylvesterWilmott** [comment]
In the final option are you using an inner border? I think this option is the best especially when site icon colours are similar to the app background which is common on logos (light shade of grey/dark shade of grey)

**Comment by iamthomasbishop** [comment]
> In the final option are you using an inner border?

Yea, it's an inner border. I'm on the fence because I think the semi-transparent border looks sharp but removing the border would simplify things a bit. I'm mainly referring to the default/empty site icon, if we were to do a bordered solution here, we could apply it to all site icons.

Side note: once a decision is made here, we should probably create a ticket on the WP-Android repo as well.

**Comment by mattmiklic** [comment]
With the new My Site header rolling out in 17.0 I wanted to revisit this issue. Here's what the site icon border looks like now in dark mode:

![IMG_F707084D8A3F-1](https://user-images.githubusercontent.com/1396552/113454462-467fd800-93d6-11eb-9a16-4705fff264b1.jpeg)

I think we could use the same color for the site icon border as we're currently using on the quick action buttons. I think we could also reduce the border on both those buttons and the site icon to 0.5pt, which would render at 1px (a hairline, like the border at the bottom of this screenshot).

@osullivanchris what do you think?

**Comment by osullivanchris** [comment]
@mattmiklic agree with all that.

Only other thing I think we could consider is to have the border on top of the image, rather than outside, with transparency e.g. white/black 10%. Then, you only really see the border for a white/black image. And you don't see the border when its not needed.

Specific to the new header, theres a couple of other fixes [I have captured over here](https://github.com/wordpress-mobile/WordPress-iOS/pull/16132#issuecomment-803004209).

Just noting on the original issue it looks like it is showing a site in the list. Currently, on the list in the site switcher, I see no border on the site icons.

**Comment by mattmiklic** [comment]
> the border on top of the image, rather than outside, with transparency e.g. white/black 10%. Then, you only really see the border for a white/black image. And you don't see the border when its not needed.

A visual might be helpful here; I'm having a hard time imagining what exactly that'd look like. In terms of color, I think the system `separatorColor` would make most sense to use for both borders (site icon and quick actions) so they match the border on the background.

**Comment by osullivanchris** [comment]
Sorry it wasn't clear. Here's what I was thinking.

First, with no border. In light mode, an icon with a dark image looks great. But an icon on a white background lacks any boundary.
![1 no border](https://user-images.githubusercontent.com/50576199/113868345-7c8ed480-97a7-11eb-872f-a5ef21ab0d55.png)

Second. If we add a grey border. The icon on the right with the white background is resolved, it now has a border around it. But the dark icon which didn't need a border, now looks fuzzy with the grey line outside its black image.
![2 grey border](https://user-images.githubusercontent.com/50576199/113868426-929c9500-97a7-11eb-9852-6715efd31aa6.png)

My suggestion was to put the border on top of, and inside the image. Here the border is #000000 with 10% opacity. Then, the white background on the right is resolved. On the left, the border is invisible.
![3 transparent border](https://user-images.githubusercontent.com/50576199/113868551-b3fd8100-97a7-11eb-8d17-1e3d78768a81.png)

**Comment by osullivanchris** [comment]
One last attempt at explaining! 
 
![illustratino](https://user-images.githubusercontent.com/50576199/113869271-6c2b2980-97a8-11eb-9b6c-48ca62232595.png)

**Comment by mattmiklic** [comment]
Gotcha, thanks for the visuals -- that definitely makes it clear. I like this idea. It'd be good to try it with the standard separator color (which is semi-translucent) first but a tint of white/black seems like it works pretty well.

**Comment by SylvesterWilmott** [comment]
This is what the App Store does for screenshots and icons for same reason Chris mentioned. From what I can tell by eye, light mode uses a black border with 8% opacity and dark mode uses a white border with 8% opacity.

**Comment by mattmiklic** [comment]
> light mode uses a black border with 8% opacity and dark mode uses a white border with 8% opacity.

I dig it; I think we can roll with this.
