### ISSUE TITLE
[Dark Mode] White footer in Stats opened from Today widget 

### ISSUE THREAD

**Issue by danielebogo** [wordpress-mobile/WordPress-iOS#12950]
### Expected behavior
Opening Stats I shouldn't see a white background in Dark Mode

### Actual behavior
When Stats is presented from the widget there's a white background at the bottom

### Steps to reproduce the behavior
Open Stats clicking on the Today widget

##### Tested on [iPhone 11], iOS [iOS 13], WPiOS [develop - 13.7]
![widget-stats-list](https://user-images.githubusercontent.com/912252/68882553-4579d800-0707-11ea-9075-cdb3abccfbde.jpg)

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/13323.
