### ISSUE TITLE
Stats Today Widget: Visitors number is displaying Views, not Visitors

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#12990]
Steps to reproduce:

1. Log in to the app and go to Stats > Insights.
1. Note the numbers for Views, Visitors, Likes, and Comments in the Today card.
1. Tap Today in the nav bar, then tap "Use this site".
1. Go to the Home Screen and swipe left until you see widgets.
1. Scroll dow, tap Edit, add the WordPress Today widget.
1. Check to see if the numbers in the widget match the numbers from the card in step 2.

**Result:** the Visitors number is displaying Views, not Visitors.

<img src="https://user-images.githubusercontent.com/1119271/69393636-f1d33580-0c96-11ea-9671-ffe0ae8d6067.PNG" width="270" alt="IMG_3137 1"> <img src="https://user-images.githubusercontent.com/1119271/69393637-f26bcc00-0c96-11ea-86ba-18913a98fb8a.PNG" width="270" alt="IMG_3138 1">
<sup>Tested with WPiOS 13.7.0.0 TestFlight beta on iPhone 6S iOS 13.2.3.</sup>

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/12994.
