### ISSUE TITLE
Visual Issues with Menu Editor

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#12996]
The UI for editing menus appears to be consistently broken to varying degrees:

**WPiOS 13.7 on iPhone XS running iOS 12.4**

<img src="https://user-images.githubusercontent.com/1123407/69463812-f43a9b80-0d39-11ea-8f94-ac515f77d79c.jpeg" width="270" alt="IMG_E0FC91EA7E82-1">

**WPiOS 13.7 on iPhone 11 Pro Max running iOS 13.2**

<img src="https://user-images.githubusercontent.com/1123407/69463727-a887f200-0d39-11ea-851c-8b4cccf5f6c6.PNG" width="270" alt="IMG_0774">

 **WPiOS `develop` on Simulated iPhone 11 Pro running iOS 13.2**

<img src="https://user-images.githubusercontent.com/1123407/69463934-3fed4500-0d3a-11ea-8053-4266e381c6ab.png" width="270" alt="Simulator Screen Shot - iPhone 11 Pro - 2019-11-22 at 15 10 04">

**Comment by Shiaulis** [comment]
Working on it
