### ISSUE TITLE
Post Scheduling: post date doesn't match messaging

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#12992]
From release [testing](https://wp.me/p5T066-15Z-p2/#comment-3906):

Posts seem to be  scheduled using the device timezone not the site settings timezone. This is consistent with previous versions (I tested with 13.7 TestFlight beta), however, it doesn't match with the note displayed below the datetime picker.

To test:

<ol>
<li>Go to Settings > Timezone and set it to something a few hours later than the device timezone.</li>
<li>Schedule a new post for a few minutes in the future compared to the device time.</li>
<li>Notice that the Date and Time picker states the post will be published according to the site timezone.</li>
<li>Wait until the scheduled time passes according to the device timezone.</li>
<li>Observe that the post is published according to the device timezone not the site timezone.</li>
</ol>

![postdate](https://user-images.githubusercontent.com/1816888/69450128-af9f0800-0d19-11ea-8934-f5a0181901e3.png)

Ref: https://github.com/wordpress-mobile/WordPress-iOS/pull/12820

**Comment by frosty** [comment]
We might want to also consider https://github.com/wordpress-mobile/WordPress-iOS/issues/13080 as we fix this.
