### ISSUE TITLE
Images uploaded from Other Apps renamed by app.

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-iOS#13018]
### Expected behavior

After editing the names of all the images I wanted to upload and saving them in Files on iCloud, you would expect the files to keep the name when uploaded to the media library from the app. 

### Actual behavior

When you add them to the post the app renames them with numbers.

### Steps to reproduce the behavior

1. Choose an image from your iPhoto library and save to files. Select either iCloud Drive or On My iPad).
2. Rename the image and save.
3. Open the WordPress app and go to Media > + to add a new image.
4. Select 'Other Apps' to open files library (whether you select from On My iPad or iCloud Drive the same behaviour happens)
5. Select the renamed image to add to your site. 
6. After it uploads, click on the image to verify file info, the file was renamed to a series of numbers/letters.

There is no way to edit the file name after it's been uploaded. The problem about renaming them after uploading to WP is that you only change the title, but not the file name, that is what appears in the url, and that’s not good for SEO. 

This doesn't happen if you select the image from 'Choose from My Device', however there is no way in iOS to rename the picture in Photo unless you save to files/iCloud first. 

It also doesn't happen if you upload a picture from Files in Calypso or WP-admin (desktop of mobile device browser too). 

Screenshot of image uploaded from same iCloud location in Calypso:
<img width="1526" alt="Image 2019-11-28 at 1 34 00 pm" src="https://user-images.githubusercontent.com/10325627/69814111-70762880-11eb-11ea-943b-3d205be635a4.png">

Screenshot of image uploaded from same iCloud location in iOS app: 
<img width="1524" alt="Image 2019-11-28 at 1 34 41 pm" src="https://user-images.githubusercontent.com/10325627/69814195-94d20500-11eb-11ea-839b-78d297a6332c.png">

**Comment by designsimply** [comment]
@SergioEstevao is this something we can change or is the file name that comes from iCloud what we're stuck with?

**Comment by SergioEstevao** [comment]
I will give it a look to see if we can get the original filename from iCloud and use it to name the file before upload.
