### ISSUE TITLE
Captions on Video/Images in Block Editor are stuck in left alignment

### ISSUE THREAD

**Issue by cameronvoell** [wordpress-mobile/WordPress-iOS#13022]
Introduced to WPiOS on this change: https://github.com/wordpress-mobile/WordPress-iOS/commit/0b6cba4100f88e1ebfe250092f0768e9865fa1f7
(Observe the issue does not show up after checking out previous commit - 19ed6f96fb9bde1b936dd21d885c44b489d4b8cf)

### Expected behavior
Captions should be centered
### Actual behavior
Captions are left aligned

![image](https://user-images.githubusercontent.com/1103838/69838842-20f32500-120a-11ea-933e-8bb5c7671dec.png)

### Steps to reproduce the behavior
1. Edit an article in the Block Editor
2. Add Image or Video Block and upload media
3. Observe Caption field is left aligned instead of center

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPhone X iOS 12.2 emulator and iPhone XR iOS 13.2.3

**Comment by cameronvoell** [comment]
I have a hunch this change included in the Aztec Update might be related: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1228

Working on testing that now.

**Comment by maxme** [comment]
Here: https://github.com/wordpress-mobile/AztecEditor-iOS/compare/issue/caption-alignemnent-fix?expand=1 - I tried to revert the changes from https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1228 and captions alignment got fixed.

@SergioEstevao can you have a look at this since you reviewed wordpress-mobile/AztecEditor-iOS#1228 ?

**Comment by maxme** [comment]
The bug is happening on new image or empty caption. Seems fine when you open an existing post with an existing caption.

Demo:
https://bia.is/s/M7QK/Screen_Recording_2019-11-29_at_12.08.02.mov

**Comment by maxme** [comment]
Fix in progress: https://github.com/WordPress/gutenberg/pull/18818

**Comment by maxme** [comment]
Fixed by WordPress/gutenberg#18818
