### ISSUE TITLE
Quick Start: Confusing transition from Themes tour to Customize tour

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#13070]
### Expected behavior

I expect to be clearly guided from Quick Start tour to the next, with any required steps to complete the first tour done before the next tour starts.

### Actual behavior

After doing the Themes tour and activating a new theme, the Customize tour begins while the new theme's demo page and confirmation dialog are still on screen. This page and dialog prevent you from continuing the tour until you close them, and the tour doesn't guide you as to how to do that.

There's also simply a lot on screen at once and it's hard to know what should take priority.

### Steps to reproduce the behavior

1. Create a new site in the app.
2. When prompted, accept more help getting started to get the Quick Start tours.
3. Select the "Choose a theme" tour.
4. Open the Themes section.
5. Select and activate a new theme.
6. Notice that immediately after activating a new theme, a "Theme Activated" dialog appears along with the "Customize your site" tour prompt.

<img src="https://user-images.githubusercontent.com/8658164/70559396-76babc00-1b7e-11ea-8a14-e50ca22cea1c.png" width="50%">

**Comment by Gio2018** [comment]
Hey @rachelmcr ! Thanks for finding this out! Should the flow just show the next step once the user has returned to "My Site" (as it happens in the "customize" step)? Or something else? Maybe @osullivanchris can provide some advice here too.
Thanks!

**Comment by osullivanchris** [comment]
> Should the flow just show the next step once the user has returned to "My Site" (as it happens in the "customize" step)?

Yeah @Gio2018 I think so! I'm not sure if there's a general logic we can apply (or that already exists) or if it is particular to this use case. But definitely agree with the original bug and I would expect it to appear once I close the theme preview to go back to My Site.

**Comment by rachelmcr** [comment]
The only caveat I'd mention is that the "Customize" option is also under My Site > Themes. So I think it's meant to appear right away when you get back to the Themes screen (without having to go all the way back to My Site). That said, if the most straightforward fix is to wait until the user has returned to My Site, that seems like a reasonable solution.

**Comment by Gio2018** [comment]
> The only caveat I'd mention is that the "Customize" option is also under My Site > Themes. So I think it's meant to appear right away when you get back to the Themes screen (without having to go all the way back to My Site). That said, if the most straightforward fix is to wait until the user has returned to My Site, that seems like a reasonable solution.

Hey @rachelmcr , thanks for pointing this out!
In the current UI, as soon as users tap on 'Activate', the 'Themes Browser' is dismissed "behind the scenes" (the navigation controllers pops to root before the theme preview is dismissed), so as soon as they close the theme preview, they will see the 'My site' page. For this reason, and since it's an acceptable solution, I am going to show the next step when they go back to 'My Site'.
