### ISSUE TITLE
Save as Draft: button text is barely visible

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#13074]
### Expected behavior
Save as Draft: button text should be visible.

### Actual behavior
Save as Draft: button text is barely visible. It's white on a grey background.

![button_color](https://user-images.githubusercontent.com/1816888/70579048-b1b3f400-1b6c-11ea-9bad-0ec97a6d1b5f.jpeg)

### Steps to reproduce the behavior
- On a post in the Reader, select More > Share.
- Select 'Save as Draft'.
- Notice the 'Cancel' and 'Save' buttons are barely visible at the top.

![button_color](https://user-images.githubusercontent.com/1816888/70579113-e9bb3700-1b6c-11ea-9e76-6c2536fe7e21.jpeg)

**Comment by frosty** [comment]
Thanks for reporting – that extra background behind the extension window looks kind of odd, too.
