### ISSUE TITLE
Add “cancel” button to version conflict dialog

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/WordPress-iOS#13093]
![5733E1EA-2A7D-4DE2-A9B4-83A9048824DB](https://user-images.githubusercontent.com/1200432/70763915-62f88c80-1d1b-11ea-8479-a5706da78a2a.jpeg)

I accidentally tapped on a post with some local changes  in my Posts list. I then saw the version conflict Alert and could not dismiss, only choose a version.

I expected to see a button for “cancel” or “dismiss”.

### Steps to reproduce the behavior

* Find a post that has both a local and remote draft changes saved.
* Tap on the version conflict message on the Post Card.
* See the Alert, without the ability to cancel/dismiss.

**Comment by kean** [comment]
Fixed in 24.9 – there is a new dialog that looks and works like the one in Gutenberg and does have an option to dismiss it.

<img width="340" alt="Screenshot 2024-05-07 at 11 20 59 AM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/e4fb75f3-a8ec-473c-a1df-89409095db8c">
