### ISSUE TITLE
[VoiceOver] Login Epilogue Enhancements

### ISSUE THREAD

**Issue by shiki** [wordpress-mobile/WordPress-iOS#13090]
<img src="https://user-images.githubusercontent.com/198826/70751334-62e19800-1ced-11ea-8856-bd54228e8c15.png" width="320">

This page is shown after logging in and before the user is shown the dashboard (i.e. My Sites). 

- [ ] The image (“Add account image”) is accessible but you can't do anything with it. 
- [ ] The “My Sites“ does not have the heading attribute
- [ ] The site cells' text can be spoken as “Site Title **at** domain.com“

**Comment by giogus** [comment]
Hey @shiki,

Can I work on these enhancements? 👨‍💻

**Comment by shiki** [comment]
Of course. Thanks for contributing!

**Comment by giogus** [comment]
@shiki 

> The image (“Add account image”) is accessible but you can't do anything with it.
Should we make the image not accessible? 

> The “My Sites“ does not have the heading attribute
I will replicate the same accessible behavior from the "Logged in as".

> The site cells' text can be spoken as “Site Title at domain.com“
Great suggestion. 👍

**Comment by shiki** [comment]
@giogus Again, sorry for the late response. 😞 

> Should we make the image not accessible?

Yes. Please keep in mind that that image **is accessible** in some parts of the app. It's just not accessible in this specific scenario. 

> I will replicate the same accessible behavior from the "Logged in as".

Yup. I believe it just needs the [header](https://developer.apple.com/documentation/uikit/uiaccessibility/uiaccessibilitytraits/1620170-header) trait.

**Comment by ScoutHarris** [comment]
This was addressed with the [new](https://github.com/wordpress-mobile/WordPress-iOS/issues/13413) Login Epilogue.
