### ISSUE TITLE
Add Dark Mode settings

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#13122]
Add a Dark Mode setting to App Settings to let users override the systemwide setting.

Options should include:

- Dark Mode
- Light Mode
- System default

**Comment by mattmiklic** [comment]
Design:

![ios-Dark Mode Settings](https://user-images.githubusercontent.com/1396552/71194167-76df4980-2259-11ea-9a00-132dc11edfbb.png)

**Comment by elibud** [comment]
It seems like this one is good to close @frosty?

**Comment by frosty** [comment]
Yep, I'm not sure why Github didn't auto close it.
