### ISSUE TITLE
Post Published date: make consistent with Post Scheduling

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#13132]
With [Post Scheduling Enhancements](https://github.com/wordpress-mobile/WordPress-iOS/pull/12820), the scheduled/published date is now displayed in a new view. However, the `Post Settings` date format does not match that on the `Publish` view. It'd be nice if `Post Settings` adopted the format from `Publish`.

![post_settings](https://user-images.githubusercontent.com/1816888/71030064-ecb6aa00-20cd-11ea-9d9e-5b48eb45f45a.jpeg)

![post_scheduling](https://user-images.githubusercontent.com/1816888/71030067-efb19a80-20cd-11ea-90cf-7f31625c5703.jpeg)

**Comment by bjtitus** [comment]
I think it would be useful for users if some (all?) of the formatters matched the ones set in the blog settings. Not sure if that would fit in many of these spots but it would be consistent with the way the Gutenberg editor displays the date:

One of the default settings:

![Screen Shot 2019-12-17 at 1 11 54 PM](https://user-images.githubusercontent.com/3250/71030590-fd1b5480-20ce-11ea-94f5-83c2097b46a1.png)

With date format set to `d/m/y`:

![Screen Shot 2019-12-17 at 1 13 00 PM](https://user-images.githubusercontent.com/3250/71030601-ff7dae80-20ce-11ea-9baf-88e1c7c2eefa.png)

It should be possible to convert the [PHP date format strings](https://www.php.net/manual/en/function.date.php) to [Unicode date format strings](https://www.unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns) but will lead to more code to maintain.
