### ISSUE TITLE
LaTeX equations in reader posts show incorrectly

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#13135]
The size seems too small, and since they are images, they don't respect dark mode settings

![IMG_ED96DFBA16A5-1](https://user-images.githubusercontent.com/8739/71094719-b7808980-21ab-11ea-989a-dd6e5c71946f.jpeg)

The good news is that it seems like we're rendering those through an API, so we can rewrite the size and color parameters:

`https://s0.wp.com/latex.php?latex=%7Bn%2C+f_0%28n%29%2C+f%5E2_0%28n%29%2C+f%5E3_0%28n%29%2C+%5Cldots%7D&bg=ffffff&fg=000000&s=0`

![](https://s0.wp.com/latex.php?latex=%7Bn%2C+f_0%28n%29%2C+f%5E2_0%28n%29%2C+f%5E3_0%28n%29%2C+%5Cldots%7D&bg=ffffff&fg=000000&s=0)

`https://s0.wp.com/latex.php?latex=%7Bn%2C+f_0%28n%29%2C+f%5E2_0%28n%29%2C+f%5E3_0%28n%29%2C+%5Cldots%7D&fg=ffffff&bg=000000&s=4`

![](https://s0.wp.com/latex.php?latex=%7Bn%2C+f_0%28n%29%2C+f%5E2_0%28n%29%2C+f%5E3_0%28n%29%2C+%5Cldots%7D&fg=ffffff&bg=000000&s=4)

cc @aerych

**Comment by leandroalonso** [comment]
Sizes are now fixed.

While we can change the background to better display it for dark mode it has its own complexities, like handling when the system switches the system theme. Given apparently no users are complaining about it I'm going to close the issue for now. We can reassess it in the future if needed.
