### ISSUE TITLE
Stats screens show stale data (often zero)

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#13138]
**Screenshot of the issue:** 

<img src="https://user-images.githubusercontent.com/1123407/71126865-198ac000-21a7-11ea-9e51-a4f10fa07683.PNG" width="200" />

**Video of the issue**
![RPReplay_Final1576705697 MP4](https://user-images.githubusercontent.com/1123407/71127558-90748880-21a8-11ea-8e11-e7afc8d91b5e.gif)

****Steps to reproduce****
- Delete and reinstall the app (13.8 or above)
- Log into an account with many sites
- Choose "stats", then remain on "insights" until it loads. Then tap through the other tabs. 
- Sometimes, the number won't change between two tabs – so "days" and "weeks" will show the same data. Other times, a tab will just show "0" at the top. 
- It may be necessary to try this on a few sites before it works.
- It _may_ also be related to persistence – I noticed that if the device froze very briefly when switching tabs (due to core data save?) the issue seemed to happen more.

**Workaround**
Pull-to-refresh seems to consistently show the correct values.

**Comment by rezzap** [comment]
Reported by a user in zen-2568707

Full set of error logs are available in the reply. 

> There are 15 websites and they all have problems... When I pull down stats to refresh the number of visitors and visits remains the same on my main website, and when I choose weeks, months or years there is no change, everything remains the same. Other websites don't have statistics at all.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/13140.
