### ISSUE TITLE
Image uploaded by app Wordpress doesn't get automatically "feature image"

### ISSUE THREAD

**Issue by Snoop-T** [wordpress-mobile/WordPress-iOS#13144]
### Expected behavior
I used for years the app Wordpress for iOS in order to post images to my photoblog. Thanks to the plugin "Easy Add Thumbnail", any picture I used to post did automatically get as the "Feature Image". This used to work great.

### Actual behavior
Since few months, it did stop working. However, if I post from desktop browser, it works and pic gets "Feature Image" automatically thanks to the plugin. But from the app, the image doesn't get "feature image". In order for this to work, I need to edit the post (in the app or through the desktop browser), click on properties of the post and add the image to get "feature image" and click on Update.

### Steps to reproduce the behavior
Post a pic from the iOS app...

##### Tested on iPhone 11 Pro, iOS 13.3, WPiOS 13.8

bug 🐛 
🏷

**Comment by Snoop-T** [comment]
That's my first contribution so not sure I did everything right. Couldn't manage to add a "feature label"... sorry.

**Comment by designsimply** [comment]
No problem! The label warnings are for admins. 🙂

I should have time to test this soon, but in the meantime may I ask If you are using the block editor on both the desktop browser and in the app?

**Comment by Snoop-T** [comment]
Thanks!

1. Yes, I use in the app the block editor and I add a picture via the + button in the editor field.

2. Same on the browser, I add image thanks to the button “Add Media” (need to say that I use the Classic Editor plugin)

When using method 2, all is fine but when using method 1, the pic doesn’t get automatically added to “feature image”

Happy Christmas!

**Comment by illusaen** [comment]
Adding a feature image via WPiOS itself works; unfortunately, we are unable to test the 3rd party plugin. Please reach out to the authors if the issue still exists :)

**Comment by illusaen** [comment]
Closing this as non reproducible but, please feel free to reopen if it still occurs, thanks!
