### ISSUE TITLE
The app doesn't handle password changes very well

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-iOS#1315]
- Start the app and go to the Notification screen
- [Web browser]: change your password, and revoke the access to WordPress Internal in "connected apps section"
- Pull to refresh notifications ----> The app takes you to the login screen
- Insert your password and hit done
- The app start loading Notifications, but takes you back to the login screen
- You need to close and restart the app to make it working again.

**Comment by hoverduck** [comment]
29Oct15 Bug Scrub

Still broken, but with a different signature than the original issue.  If I open the app, go to Notifications, and then change my password and revoke access from the web, the Notifications panel still works on the app.  New notifications still pop into the app.

However, if I go try to write a post I get "Error occurred during publishing".

**Comment by kurzee** [comment]
Mostly related to https://github.com/wordpress-mobile/WordPress-iOS/issues/2282, will require a larger refactor to properly handle consistently.
