### ISSUE TITLE
Notifications: Adjust Metrics

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#13151]
### Details:

- [x] Adjust **TableViewCell's** horizontal + vertical spacing
- [x] Adjust **TableViewHeader** Metrics
- [x] **Users** + **Post Titles** + **Comments** should now be bold
- [ ] Review Fonts

---

![Mockup](https://user-images.githubusercontent.com/1195260/71270014-541f6480-232f-11ea-9fd6-726a47f4cece.jpg)

![strings](https://user-images.githubusercontent.com/1195260/71269993-479b0c00-232f-11ea-9817-c35c431e4b23.jpg)

**Comment by loremattei** [comment]
Hey! I moved this to 14.1 because 14.0 has been cut. Please, ping me if you want it to make it to 14.0 😀
