### ISSUE TITLE
Generated excerpts show gallery captions without spacing between the captions making them hard to read

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13154]
Steps to reproduce:

1. Add a new post using the block editor.
1. Add a gallery block as the first content in the post.
1. Add captions for each photo in the gallery.
1. Go to My Sites > Blog Posts and look at the generated excerpt.

**Result:** the generated excerpt for a post with a gallery block as the first content shows all of the captions from the gallery without any spacing between them. I expected that the captions wouldn't be shown at all in a generated excerpt, but if they do show then there should be spaces between each caption so the excerpt is more readable.

<img src="https://user-images.githubusercontent.com/1119271/71372190-ec585c00-2570-11ea-8094-1bfd52845e17.PNG" width="200" alt="IMG_3225"> <img src="https://user-images.githubusercontent.com/1119271/71372192-eebab600-2570-11ea-9738-b977d94a9a1e.PNG" width="200" alt="IMG_3224"> <img src="https://user-images.githubusercontent.com/1119271/71372195-f4b09700-2570-11ea-9f7f-183ead3c90ed.PNG" width="200" alt="IMG_3209">
<sup>Tested with WPiOS 13.9.0.0 TestFlight beta on iPhone 6S iOS 13.2.3 using a self-hosted site `remote-seals.jurassic.ninja` running WordPress 5.3.2 and on a WordPress.com Premium site `made4testing0318.blog`.</sup>

**Note:** In Calypso on WordPress.com and WP Admin in WordPress.org, excerpts aren't shown at all in the Posts List.

<img src="https://user-images.githubusercontent.com/1119271/71372282-24f83580-2571-11ea-97eb-b64d3dbafff3.PNG" width="200" alt="IMG_3229 1"> <img src="https://user-images.githubusercontent.com/1119271/71372285-275a8f80-2571-11ea-9b17-31078e05428f.PNG" width="200" alt="IMG_3227 1">
<sup>Tested with Safari on iPhone 6S iOS 13.2.3.</sup>

**Note:** On the front-end, when in a view that displays excerpts such as the archive view in the Twenty Nineteen theme, generated excerpts do not contain any captions from galleries.

<img src="https://user-images.githubusercontent.com/1119271/71372326-3fcaaa00-2571-11ea-9bfc-a50a4d49ddd5.PNG" width="200" alt="IMG_3226">
<sup>Tested with Safari on iPhone 6S iOS 13.2.3 on a site using the Twenty Nineteen theme and viewing the `/2019` archives list.</sup>

**Comment by yaelirub** [comment]
Hey @designsimply , thanks for flagging this issue. 
The caption content is presented in the `snippetLabel` of the PostCardCell in the post list. So this is something that can be handled in the cell of the post list.

Are you suggesting to hide the captions in the excerpts for galleries only or for single media as well?

**Comment by designsimply** [comment]
If you want to match how generated excerpts are displayed on a blog's front-end, then you could hide the captions. If you want the captions to show, you could add a space between each caption. 

Personally, I think either would be fine (no strong opinion) and I would lean toward matching the front-end behavior: no captions shown for galleries in generated excerpts.

**Comment by diegoreymendez** [comment]
A fix is coming up here: https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/244

There's a GIF animation in the PR showing the new behavior in case you want to validate it @designsimply.

**Comment by designsimply** [comment]
> There's a GIF animation in the PR showing the new behavior in case you want to validate it @designsimply.

GIF LGTM. Thanks @diegoreymendez! ❤️
