### ISSUE TITLE
Add ability to set parent to Page Settings in editor

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/WordPress-iOS#13150]
### Expected behavior

I expect to be able to `Set Parent` for the current page in Settings while I'm editing a page.

### Actual behavior

I cannot 😄 

### Steps to reproduce the behavior

* Open or create a new page
* Tap `•••` menu
* Tap `Post Settings` (side note: this should be labeled **Page** Settings)
* Note the lack of ability to set parent

Note: this applies to both Aztec and Gutenberg editors, because settings are shared across both.

##### Tested on iPad/iPhone, iOS 13.3, WPiOS 13.9b

[Related issue on Android](https://github.com/wordpress-mobile/WordPress-Android/issues/11002)

**Comment by designsimply** [comment]
> side note: this should be labeled Page Settings

Note: tracking this at https://github.com/wordpress-mobile/WordPress-iOS/issues/12374.

**Comment by designsimply** [comment]
I noticed the `Set Parent` action is available in the More menu from the Pages List but not from inside the Page Settings while editing the post. I also saw that analytics were added in https://github.com/wordpress-mobile/WordPress-iOS/pull/10463 (in case they're helpful to reference).

<img src="https://user-images.githubusercontent.com/1119271/71373191-946f2480-2573-11ea-949c-fa4f7b1302eb.PNG" width="270" alt="IMG_3230 1"> <img src="https://user-images.githubusercontent.com/1119271/71373193-9933d880-2573-11ea-8e71-cd6e61f6ecb9.PNG" width="270" alt="IMG_3231 1">
<sup>Tested with WPiOS 13.9.0.0 TestFlight beta on iPhone 6S iOS 13.2.3.</sup>

@frosty do you know if there was a deliberate decision to only include the `Set Parent` action in the Pages List and not when editing a page directly?

**Comment by frosty** [comment]
No, I'm not sure if any reason why this is the case – I guess just an oversight.
