### ISSUE TITLE
Migrate PostPreviewViewController to WKWebView

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#13180]
Tasks:

- [ ] Replace UIWebView and any related code with WKWebView.
- [ ] Replace UIWebViewDelegate implementation.

**Comment by diegoreymendez** [comment]
@bjtitus - Was this closed on purpose?

**Comment by bjtitus** [comment]
@diegoreymendez No, I think Github auto-closed with the issue.

Sorry about that!

**Comment by diegoreymendez** [comment]
I'm marking this as out of scope after this discussion: https://github.com/wordpress-mobile/WordPress-iOS/pull/13357#issuecomment-582011691
