### ISSUE TITLE
Improve "Nothing to show" message in Media Library

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/WordPress-iOS#13217]
### Expected behavior

- [ ] Media Library should show a better indication of loading. We can use a spinner/loader instead. 
- [ ] If we'll continue to have a text it should at least be positioned better and rephrased to indicate loading

### Actual behavior

Media Library shows "Nothing to show" message during loading.

### Steps to reproduce the behavior

Be sure to reset Media Library cache by either fresh installing the app or switching to a new site that you'll edit the first time.
Slow down your connection via Settings -> Developer -> Network Link Conditioner -> %100 loss

- Add a new post via block editor
- Add Gallery block
- Tap on placeholder
- Choose "WordPress media library"

Result: 

1. It says "Nothing to show" as if the media library is empty.
2. The position of the message is odd.

<img src="https://user-images.githubusercontent.com/5032900/72172352-fe961f00-33e5-11ea-85f6-1dd52c9280ea.jpg" width="270" alt="File">

**Comment by ScoutHarris** [comment]
This has been resolved. A loading indicator and a No Results View is now displayed.

![File](https://user-images.githubusercontent.com/1816888/98416274-00e3fc80-203c-11eb-8291-46e74e1948dc.jpg)
