### ISSUE TITLE
Scrolling to see new text entry in editor breaks with external keyboard

### ISSUE THREAD

**Issue by sarahfg** [wordpress-mobile/WordPress-iOS#13224]
### Expected behavior
As text is inputed into the app the text should scroll upwards automatically as I get to the bottom of the screen, so text is never hidden below where I can see it

### Actual behavior
If an external keyboard is attached to the iOS device and used to enter text then it will be hidden as you get to the end of the viewable area. The text stays hidden for 1-3 lines, then auto scrolls upward

### Steps to reproduce the behavior
1. Add an external keyboard to your iOS device. I used Apple's Magic Keyboard
2. Open a new post or page using the block editor
3. Write until the page is full of text 

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPad, iOS 13.3, WPiOS 13.8.1 with Magic Keyboard
User reported on iPad Pro 9,  iOS 13.3, WPiOS13.81 with a Logitech keyboard #2625427-zen

**Comment by designsimply** [comment]
Tested and confirmed using WPiOS 14.0.0.0 TestFlight beta on iPhone 6S iOS 13.3. ([33s](https://cloudup.com/cYZyUdhxNAk))

**Note:** also tested with WPAndroid 13.9  on Pixel 3 Android 10 and did not see the same problem happen there. ([24s](https://cloudup.com/cdjSLfQP1kz))
