### ISSUE TITLE
[Offline Pages] Track when the app initiates auto-uploads for pages

### ISSUE THREAD

**Issue by malinajirka** [wordpress-mobile/WordPress-iOS#13285]
We currently track when the app initiates auto-upload for posts (auto_upload_post_invoked).

Goal of this task is to create a similar tracking event for pages.

New track event: `auto_upload_page_invoked`
Attributes: The same we use for "auto_upload_post_invoked"

**Comment by kean** [comment]
Not applicable starting from 24.9 (pcdRpT-6vS-p2)
