### ISSUE TITLE
Comment Editing: Tapping to select a word can sometimes result in the line above being selected

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#13295]
### Expected behavior
When tapping a word for selection it becomes selected

### Actual behavior
When tapping a word for selection is can sometimes select the line above it

### Steps to reproduce the behavior
1. Open WordPress for iOS
2. Locate a long comment to edit
3. Edit it
4. Find a word in the middle of the text to select
5. Double tap to select it

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 13.3 
WPiOS 13.9

### Demo
<img src="https://user-images.githubusercontent.com/793774/73305630-58149100-41cf-11ea-9b54-2b7396566f63.gif" width="50%" />

**Comment by designsimply** [comment]
This is so great! 🎉

Tested with WPiOS 14.2.0.2 TestFlight beta on iPhone 6S iOS 13.3.1 and it works like a charm.
