### ISSUE TITLE
Share Sheet navigation bars use white instead of system default colors

### ISSUE THREAD

**Issue by bjtitus** [wordpress-mobile/WordPress-iOS#13302]
### Expected behavior

The Share Sheet (aka `UIActivityViewController`) should use the default (system) button colors and styles. This would be consistent with other apps on the system.

### Actual behavior

Buttons in parts of the `UIActivityViewController` and other presented controllers are changed to white.

### Steps to reproduce the behavior

* Share any content (blog post, web page from the page preview browser).
* Attempt to Edit Actions
* Notice bar button color

<img src="https://user-images.githubusercontent.com/3250/73320338-2d8cfd00-41fc-11ea-8d30-5d17cfde000f.png" width="250px">&nbsp;&nbsp;<img src="https://user-images.githubusercontent.com/3250/73320321-21a13b00-41fc-11ea-9eb8-d1638d1c3111.jpeg" width="250px">

##### Tested on iPhone X, iOS 13.0, WPiOS 14.0

**Comment by Gio2018** [comment]
Buttons seem to appear fine in modals and share sheet, so I'm closing this one.
