### ISSUE TITLE
[GlobalStep] Spacer and Shortcode blocks are missing in small devices

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13304]
### Description
When creating a post, pressing the button to add a new block brings up the available options. On small devices the buttons to add a “Spacer” and a “Shortcode” are missing. The panel that presents the available block options fills the entire screen with the first two buttons being pinned to the top of the screen and it's not possible to scroll for the missing buttons to be visible.

### Reproduction Rate
4/4 100%

### Expected behavior
All types of blocks should be presented to the user.

### Actual behavior
The “Spacer” and “Shortcode” options aren’t displayed.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Press the “Add new” button.
4. Press the “Plus” button (+).

##### Tested on the following
iPhone SE (13.1.3)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/73353533-717b1300-428b-11ea-8291-683ca4d3a752.jpg" />

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Fixed in https://github.com/wordpress-mobile/gutenberg-mobile/pull/1837. Props @lukewalczak. 🎉
