### ISSUE TITLE
Information Architecture: ‘Me’ menu move

### ISSUE THREAD

**Issue by bjtitus** [wordpress-mobile/WordPress-iOS#13319]
Design: https://wp.me/pauD4L-nx-p2

![ios-my-site-blueprint](https://user-images.githubusercontent.com/3250/73475610-f0388480-434d-11ea-9aac-10d449268f78.png)

Moves the ‘Me’ menu to the ‘My Site‘ screen.

- [x] Add feature flag.
- [x] Add the ‘Me‘ icon/gravatar to ‘My Site‘ nav bar
- [x] Add action to modally present (as `pageSheet`) the ‘Me‘ page
  - [x] This action needs to be called from the ‘Me‘ icon, as well as from any other part of the app that requires the ‘Me‘ page
    - [x] `WpTabBarController.showMeTab` callers: 
      - [x] Update `MeNavigationAction` for universal links (`Routes+Me.swift`)
      - [x] Update `openAppSettingsScreen()`, `openMeTab() `and `openSupportScreen()` in `SearchManager.swift`
      - [x] Update `handleSupportNotification` in `PushNotificationManager.swift`
- [x] Add the `Me` button to the `No Sites` screen
- [x] Remove the ‘Me‘ menu from the tab bar (`WpTabBarController.setViewControllers`)
  - [x] Ensure that re-arranging tabs does not require changing indexes in the app (and change them if it does)
- [x] Ensure views are correct for Dark Mode.
- [x] Add Accessibility support.
- [x] Add Tracks.
- [x] Add unit tests.
- [x] Enable feature flag for internal.
- [ ] Enable feature flag for all.
- [ ] Remove feature flag.

**Comment by ScoutHarris** [comment]
@Gio2018 @bjtitus - I don't see it explicitly addressed here, so I just wanted to bring up the scenario where an account has no sites to be sure it's addressed. Since there is no site details, that Me button can't be displayed. On Android, the Me button in this scenario is displayed in the nav bar.

![android_no_sites](https://user-images.githubusercontent.com/1816888/74680529-23687980-517e-11ea-8faf-36443e1bbc05.png)

**Comment by Gio2018** [comment]
> @Gio2018 @bjtitus - I don't see it explicitly listed here, so I just wanted to bring up the scenario where an account has no sites to be sure it's addressed. Since there is no site details, that Me button can't be displayed. On Android, the Me button in this scenario is displayed in the nav bar.
> 
> ![android_no_sites](https://user-images.githubusercontent.com/1816888/74680529-23687980-517e-11ea-8faf-36443e1bbc05.png)

Very good point! Since we do that on Android, we should do the same on iOS. I'll add that in the task list.
