### ISSUE TITLE
[GlobalStep] Allow notifications banner causes the Welcome to Wordpress notification to clip through the filter headings. 

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13311]
### Description 
When a user first launches the app and navigates to notifications a banner is present at the top of the screen prompting the user to allow notifications. When going to this page the filter headings will be lower than usual to account for the banner, however the first notification “Welcome to Wordpress” will be positioned behind it. This will then move to the correct position as the banner appears.

### Reproduction Rate
4/4 100%

### Expected behavior
Notifications should load in the correct position below the filter header to avoid any clipping issues 
 
### Actual behavior
The notifications will be originally positioned clipping through the filter headers, before adjusting itself to the correct position to account for the allow notifications banner. 
 
### Steps to reproduce the behavior
1. Install and Launch ~Wordpress wpandroid-14.1-rc-1-universal.apk~ WordPress 14.1.0.0  (via TestFlight)
2. Create a new account. 
3. Tap Notifications. 

##### Issue was found to occur on the following: 
 iPhone XS (12.3.1)

Please see attached video 
[NotificationsClipping.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4128065/NotificationsClipping.zip)

### Submitted By: 
Alex Wood

**Comment by designsimply** [comment]
Nice find! I'm dropping in a quick screenshot from the video you included:

<img width="270" alt="Screen Shot 2020-01-29 at Jan 29 8 31 53 AM" src="https://user-images.githubusercontent.com/1119271/73370692-daee2800-4271-11ea-9b40-f344f42a8fa9.png">

**Comment by frosty** [comment]
@jleandroperez Did you latest changes to Notifications fix this one?

**Comment by jleandroperez** [comment]
@frosty I wasn't really aware of this bug, but **I think** it's fixed already. This is what I'm getting after a fresh signup, latest TF build:

![IMG_4317](https://user-images.githubusercontent.com/1195260/73545889-0102fc00-441b-11ea-9318-6eb7d45ee1d2.png)

**Comment by jleandroperez** [comment]
Closing as cannot repro (WPiOS Mark 14.1)! Thanks everyone!
