### ISSUE TITLE
[GlobalStep] The Widget “WordPress This Week” footer is displayed with graphical issues after regaining internet connection

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13312]
### Description
While on iOS Today view without an internet connection, the WordPress This Week is displayed with a message announcing the lack of a network connection. After the user reconnects to the internet while still on this screen, the widget will then be displayed with graphical errors on the footer.
On the iPhone SE (13.1.3) the footer was displayed with an extra empty line below the site’s domain and on the iPhone XS (12.3.1) the footer was only partially displayed and the site’s domain was not visible.

### Reproduction Rate
4/4 100%

### Expected behavior
The Widget should be displayed without any graphical issues when regaining an internet connection.

### Actual behavior
The Widget’s footer isn’t displayed as intended when regaining an internet connection.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Navigate to iOS Today view.
4. Scroll to the bottom of Today’s screen.
5. Press Edit.
6. Add the “WordPress This Week” widget.
7. Press Done.
8. Disable the device’s internet connection.
9. Open WordPress 14.1
10. Navigate to the “My Sites” tab.
11. Press Stats.
12. Press Widgets.
13. Press “Use this site”.
14. Navigate to iOS Today view.
15. Enable the device’s internet connection without leaving the Today screen.

##### Tested on the following
iPhone SE (13.1.3)
iPhone XS (12.3.1)

#### Please see the attached video and screenshot for more information
https://user-images.githubusercontent.com/60415523/73363451-aba2df80-42a0-11ea-8210-473e820b20a2.jpg
[iPhoneSEWidget.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4128425/iPhoneSEWidget.zip)

### Submitted by:
Luis Pimenta

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/13321.
