### ISSUE TITLE
[GlobalStep] Unfollowing a site through the post button doesn’t update the Header

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13315]
### Description
When viewing a site the Follow / Unfollow button is displayed on both the header and on every single post.
While pressing the Follow / Unfollow button on the header updates the posts’ buttons aswell, pressing the button on one of the posts updates the following status on those buttons on the posts’ buttons but not the header one. Furthermore after this desynchronization, if the user attempts to Follow the site when it’s already being followed or vice versa, an error saying there was a problem Following / Unfollowing the site is displayed.
This issue was also seen to occur on Sites like ‘discover.wordpress.com’ where the posts belong to different users.

### Reproduction Rate
4/4 100%

### Expected behavior
The Posts’ Follow / Unfollow button should also update the Header’s button accordingly.

### Actual behavior
The Posts’ Follow / Unfollow button causes the following status between the header and the posts buttons to be desynchronized.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Navigate to the “Reader” tab.
4. Tap “Followed Sites”.
5. Tap “Manage”.
6. Tap one of the Sites.
7. Follow / Unfollow the Site through the header and one of the posts repeatedly.

##### Tested on the following
iPhone SE (13.1.3)

#### Please see the attached video for more information
[iOSFollowingDesync.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4129054/iOSFollowingDesync.zip)

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Adding a screenshot from the attachment inline for reference:

<img width="611" alt="Screen Shot 2020-08-12 at Aug 12 1 23 02 AM" src="https://user-images.githubusercontent.com/1119271/89986902-6f324200-dc3a-11ea-84cb-d2d4fb788505.png">

**Comment by designsimply** [comment]
This bug feels a lot more prominent to me after the Following button becomes bigger and more visible in the Reader site header in WPiOS 15.5. ([50s](https://cloudup.com/cwR7CXjOurr))

<img src="https://user-images.githubusercontent.com/1119271/89987293-0ac3b280-dc3b-11ea-8b1c-50b30481f011.png" width="270" alt="image">
<p style="clear:both;"><sup>Tested with WPiOS 15.5.0.0 TestFlight beta on iPhone 11 iOS 13.6.</sup></p>

**Comment by yaelirub** [comment]
Hey @designsimply , thanks for flagging. I pushed a fix but for develop so will be available for 15.6
