### ISSUE TITLE
[GlobalStep] Tapping any plan will open up the WordPress.com Free plan. 

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13325]
### Description
Within “My Sites” the user can tap on Plans where they can see the 5 different types of plan and tap each one to bring up an information page for the plan. However, regardless of which plan is tapped, whilst the header will display the correct plan, all the following text will be for the Free plan. If the user swipes left and right they are able to swipe to the actual plan pages. 

### Reproduction Rate
4/4 100%

### Expected behavior
Tapping on a plan should open the corresponding plan. 

### Actual behavior
Tapping any plan will open up the Free plan page 

### Steps to reproduce the behavior
1. Launch WordPress _14.1 beta_ ~wpandroid-14.1-rc-1-universal.apk~
2. Log into an account
3. Tap My Sites > Plans.
4. Tap any of the plans other than Free.
5. Observe that the text will be referring to the free plan.

##### Tested on 
iPhone 8 Plus (13.1.2)

[OpeningPlans.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4133518/OpeningPlans.zip)

<img width="270" src="https://user-images.githubusercontent.com/60415523/73441816-83bc8600-434b-11ea-8d78-c739ca133110.jpg" />

### Submitted By:
Alex Wood

**Comment by designsimply** [comment]
Odd! I couldn't replicate this one! ([37s](https://cloudup.com/cRcOjLUla9X))

🤔 we'll want to circle back to this one to check from some different accounts to see if we can figure out if it's happening to some accounts and not others, though I'm not sure why that would happen!

**Comment by gibtang** [comment]
Just log out and login again. Then select Free to see free plan, select Personal and free plan appear. Same free plan appears if you select premium

**Comment by designsimply** [comment]
This issue is no longer relevant as of https://github.com/wordpress-mobile/WordPress-iOS/pull/14520. 👍
