### ISSUE TITLE
[GlobalStep] Flickr videos are displayed as a blank space

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13335]
### Description
Utilizing shortcodes to add a Flickr video to a post causes it to be displayed as a blank space due to lack of Adobe Flash support.

### Reproduction Rate
4/4 100%

### Expected behavior
An error message should be displayed.

### Actual behavior
A blank space is displayed.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Press the “Add new” button.
4. Select the blog post option.
5. Type a title.
6. In the post contents add a Flickr video, the following example can be used:
```
[flickr video=2402990826] 
```
##### Tested on the following
iPhone 7+ (11.4.1)

#### Post’s content
<img width="270" src="https://user-images.githubusercontent.com/60415523/73531660-d745d700-4412-11ea-9b0e-e9e185cd0e34.png" />

#### Post’s View
<img width="270" src="https://user-images.githubusercontent.com/60415523/73531687-e2006c00-4412-11ea-86c6-b3a7cd48210b.jpg" />

### Submitted by:
Luis Pimenta

**Comment by wptester9845** [comment]
This issue was seen to still occur on WordPress 4.2

Luis Pimenta

**Comment by chipsnyder** [comment]
Testing this out I wasn't able to find a video on Flickr to test with but using the sample in the ticket I am seeing the previews work with the video placeholder

Editor | Preview
--- | ---
<kbd><a href="https://user-images.githubusercontent.com/3384451/112883991-f1be2380-909c-11eb-8461-bba4c1f78c22.PNG"><img width="300" src="https://user-images.githubusercontent.com/3384451/112883991-f1be2380-909c-11eb-8461-bba4c1f78c22.PNG"/></a></kbd> | <kbd><a href="https://user-images.githubusercontent.com/3384451/112884209-377aec00-909d-11eb-8537-d14108562c73.PNG"><img width="300" src="https://user-images.githubusercontent.com/3384451/112884209-377aec00-909d-11eb-8537-d14108562c73.PNG"/></a></kbd>
