### ISSUE TITLE
[GlobalStep] VideoPress error is seen partially off screen

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13337]
### Description
VideoPress error saying “This video doesn’t exist” when an invalid video is used, clips past the page’s borders and extends off screen.

### Reproduction Rate
4/4 100%

### Expected behavior
The VideoPress error message should be displayed without graphical issues.

### Actual behavior
The VideoPress error message  is displayed partially off screen.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Press the “Add new” button.
4. Select the blog post option.
5. Type a title.
6. In the post contents add the shortcode for a VideoPress with an invalid video link, the following example can be used:
```
[wpvideo 0cobLTqC] 
```
##### Tested on the following
iPhone 7+ (11.4.1)

#### Please see the attached screenshots for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/73535754-407e1800-441c-11ea-94ed-da84e2c9d72d.jpg" />

### Submitted by:
Luis Pimenta

**Comment by wptester9845** [comment]
This issue was seen to still occur on WordPress 4.2

Luis Pimenta

**Comment by chipsnyder** [comment]
I was able to reproduce this issue and confirmed that this happens on desktop browsers as well. The [recommended](https://github.com/Automattic/jetpack/issues/11836) source for videos is to use a video block instead I'm going to close this issue. If it is a higher priority we might want to recreate the issue in https://github.com/Automattic/jetpack to get the proper eyes on it.
