### ISSUE TITLE
[GlobalStep] Terms of Service Header Menu is not pinned to the top of the window

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13330]
### Description
The Terms of Service Header Menu does not pin to the top of the window when opened within the application which causes text to be seen above it after pagination.

### Reproduction Rate
4/4 100%

### Expected behavior
The header’s menu should be pinned to the top of the window.

### Actual behavior
The header’s menu is slightly below the top of the window causing text to be seen above it.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Navigate to the “Me” tab.
4. Press “App Settings”.
5. Press “About WordPress for iOS”.
6. Press “Terms of Service”.
##### Tested on the following
iPad Pro 12.9” (13.1.2)
iPhone 8+ (13.1.2)

#### Please see the attached video for more information
[iOSTermsOfService.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4135162/iOSTermsOfService.zip)

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Thanks for the report! I tested and found this happens in a browser and not just the app, so I've moved this report to our wpcom.trac system at WordPress.com to be fixed there. 

<sup>(internal reference: 8194-wpcom)</sup>
