### ISSUE TITLE
[GlobalStep] Pressing “Play on SoundCloud” on a block with an invalid SoundCloud URL displays a blank page

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13339]
### Description
Pressing “Play on SoundCloud” on a block with an invalid SoundCloud URL displays a blank page without any error message.

### Reproduction Rate
4/4 100%

### Expected behavior
There should be an error message stating the SoundCloud URL is invalid.

### Actual behavior
Pressing the “Play on SoundCloud” button causes a blank page to appear.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Press the “Add new” button.
4. Select the blog post option.
5. Type a title.
6. In the post contents add the shortcode for a SoundCloud with an invalid SoundCloud link, the following example can be used:
```
[soundcloud url=”https://soundcloud.com/claude-de-lune”] 
```
##### Tested on the following
iPhone 7+ (11.4.1)

#### Please see the attached video for more information
[iOSInvalidSoundCloud.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4139286/iOSInvalidSoundCloud.zip)

### Submitted by:
Luis Pimenta

**Comment by wptester9845** [comment]
This issue was seen to still occur on WordPress 4.2
While a Blank Page no longer opens, the button "Play on SoundCloud" does not function.
The message stating the provided URL is invalid can partially be seen underneath this button.

Please see the attached screenshots for more information.
#### Invalid SoundCloud block seen on the iPhone
<img width="270" src="https://user-images.githubusercontent.com/60415523/74425796-2f85cb80-4e4c-11ea-824f-cc1d2d2a235c.jpg" />

#### Invalid SoundCloud block seen on a Web Browser
<img width="270" src="https://user-images.githubusercontent.com/60415523/74425801-301e6200-4e4c-11ea-8eba-894732e47672.JPG" />

Luis Pimenta

**Comment by designsimply** [comment]
This is a front-end display issue with a shortcode and so we'll want to track it for WordPress.com outside of the context of the mobile apps.

Moved to 8221-wpcom (internal reference).

**Comment by designsimply** [comment]
Moved to https://github.com/Automattic/wp-calypso/issues/44722.
