### ISSUE TITLE
[GlobalStep] The button to lock rotation of a 360 photo causes it to be open in Fullscreen

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13344]
### Description
Pressing the button to lock rotation of a 360 photo does so as intended but it also causes the photo to unexpectedly be open in Fullscreen.

### Reproduction Rate
4/4 100%

### Expected behavior
The rotation should be locked without any further behavior.

### Actual behavior
Besides the lock of rotation, the photo is also displayed in Fullscreen.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Press the “Add new” button.
4. Select the blog post option.
5. Type a title.
6. In the post contents add the shortcode for a 360 photo, the following example can be used:
```
[vr url=https://en-support.files.wordpress.com/2016/12/vr-shortcode-360.jpg view=360]
```
7. Publish the post.
8. View the post.
9. Press the compass button.
##### Tested on the following
iPhone 7+ (11.4.1)

#### Please see the attached video for more information
[iOS360Fullscreen.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4140150/iOS360Fullscreen.zip)

### Submitted by:
Luis Pimenta

**Comment by wptester9845** [comment]
This issue was seen to still occur on WordPress 4.2

Luis Pimenta

**Comment by designsimply** [comment]
Because this is an issue with the shortcode display and shortcodes are not managed in the app, I have moved this issue to 8218-wpcom (internal reference). 

<sup>(also see p58i-9dx-p2#comment-47227)</sup>

**Comment by designsimply** [comment]
Moved to https://github.com/Automattic/wp-calypso/issues/44719.
