### ISSUE TITLE
[GlobalStep] The content of a Presentation is not displayed

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13343]
### Description
The content of a Presentation is not displayed.

### Reproduction Rate
4/4 100%

### Expected behavior
The content of a Presentation should be displayed.

### Actual behavior
The content of a Presentation is not displayed.

### Steps to reproduce the behavior
1. Install WordPress 14.1
2. Log in to an account.
3. Press the “Add new” button.
4. Select the blog post option.
5. Type a title.
6. In the post contents add the shortcode for a Presentation, the following example can be used:
```
[presentation]
[slide] ooone [/slide]
[slide] twotwotwotw [/slide]
[slide] thererereeeeeee [/slide]
[slide] foufourfour [/slide]
[/presentation]
```
##### Tested on the following
iPhone 7+ (11.4.1)

#### Please see the attached screenshots for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/73549696-fb1d1300-443a-11ea-8a6e-c4df57717901.jpg" />

### Submitted by:
Luis Pimenta

**Comment by wptester9845** [comment]
This issue was seen to still occur on WordPress 4.2

Luis Pimenta

**Comment by designsimply** [comment]
This is a front-end mobile web display issue for a shortcode and so we want to file it as a WordPress.com display bug and not as a bug in the app. 👍

Moved to 8220-wpcom (internal reference).

**Comment by designsimply** [comment]
Duplicate https://github.com/Automattic/wp-calypso/issues/43725.
