### ISSUE TITLE
Can't connect to Facebook (Publicize)

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#13356]
As shown in this video: https://cloudup.com/chsb5K66tvP

I am unable to:

1. Interact with the publicize web views by tapping on them.
2. Connect to Facebook through publicize.

### Steps to reproduce the behavior

Follow the steps from [the video](https://cloudup.com/chsb5K66tvP).

Please note that during the video recording I was tapping on buttons and links in the web view and was not able to interact with any of them.

**Comment by leandroalonso** [comment]
@diegoreymendez You need to have a Page in order to connect with Facebook.

WordPress publishes in Pages — not in your profile.

I was able to connect with a page testing in `develop`.

**Comment by diegoreymendez** [comment]
@leandroalonso - I have pages in the video shown above.  Am I missing something?

**Comment by diegoreymendez** [comment]
I'll close this issue for now - the buttons don't work fine for me, but it seems publicize works fine if you have a (Facebook) page (which I don't).

**Comment by diegoreymendez** [comment]
@loremattei - Fyi, this was added to 14.1.
