### ISSUE TITLE
Stats: File Downloads section shows for Jetpack sites (and doesn't work)

### ISSUE THREAD

**Issue by msilbers** [wordpress-mobile/WordPress-iOS#13370]
### Expected behavior
per Jetpack stats support documentation:
> Note: WordPress.com stats on Jetpack sites does not track or show you Totals, Followers, and Shares on your stats page. It also does not track file downloads for any files hosted on your server, such as PDF links.

File downloads should show for WordPress.com sites and not Jetpack sites in the app.

### Actual behavior
The section shows and indicates "An error occurred" 

### Steps to reproduce the behavior
This happens with any Jetpack plan (including free).
1. Create a site, or log into an existing site on the iOS app
2. Go to Stats
3. Scroll down past Videos and confirm that you can see File Downloads

##### Tested on iPhone 6S+, iOS 13.3, WPiOS 13.9

<img src="https://user-images.githubusercontent.com/31680407/73776570-fa93bd80-4755-11ea-8e9e-338fa2755827.png" width="50%">
<img src="https://user-images.githubusercontent.com/31680407/73776673-3169d380-4756-11ea-9497-ea8f345e63dc.PNG" width="50%">

**Comment by msilbers** [comment]
reported in #2802033-zen
WordPress iOS 14.3

**Comment by syhussaini** [comment]
I got the exact same issue on ticket #5445436-zen

_See the image below for reference_
![image](https://d.pr/i/8S1DVM+)
_Please [click here](https://d.pr/i/8S1DVM) if you are unable to see the image above_

**Comment by kerrynicl** [comment]
> I got the exact same issue on ticket #5445436-zen
> 
> _See the image below for reference_ ![image](https://camo.githubusercontent.com/7ad007898e9461ff4dbfec32b5c228274705d6a49ebdc218b3d63560f4d5e317/68747470733a2f2f642e70722f692f38533144564d2b) _Please [click here](https://d.pr/i/8S1DVM) if you are unable to see the image above_

Adding details of Users device:
mobile make is Apple iPhone 12 Pro Max
app version is 20.3 (20.3.0.2)
