### ISSUE TITLE
Prevent pages from being trashed or permanently deleted while offline.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#13383]
Prevent pages from being trashed or permanently deleted while offline.

Posts List | Pages List
--- | ---
<img src="https://user-images.githubusercontent.com/1836005/73875175-9515fe80-4833-11ea-8eef-8a4251339c25.jpg" width="300"> | <img src="https://user-images.githubusercontent.com/1836005/73875178-96472b80-4833-11ea-8fcb-51c32d3b67e2.jpg" width="300">

- [ ] Make sure users can't trash posts while offline.
- [ ] Make sure users can't permanently delete posts while offline.

**Comment by kean** [comment]
Not applicable starting from 24.9 (pcdRpT-6vS-p2)
