### ISSUE TITLE
Change message shown for pages queued for publishing.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#13380]
Show an appropriate inline note in pages that were published while offline.

Posts List | Pages List
--- | ---
<img src="https://user-images.githubusercontent.com/1836005/73869702-917d7a00-4829-11ea-97eb-404ca70d988d.jpg" width="300"> | <img src="https://user-images.githubusercontent.com/1836005/73869707-93dfd400-4829-11ea-9e8a-ec51724b79f0.jpg" width="300">

- [ ] Change the message to read "We'll publish the page when the device is back online."
- [ ] Change the coloring to match the posts list.

**Comment by kean** [comment]
Not applicable starting from 24.9 (pcdRpT-6vS-p2)
