### ISSUE TITLE
Change message shown for page drafts queued for saving.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#13381]
Show an appropriate inline note in page drafts that were saved while offline.

Posts List | Pages List
--- | ---
<img src="https://user-images.githubusercontent.com/1836005/73874081-9c3c0d00-4831-11ea-91f5-8b8d723fe8b9.jpg" width="300"> | <img src="https://user-images.githubusercontent.com/1836005/73874089-9e9e6700-4831-11ea-8581-c5895af1903f.jpg" width="300">

- [ ] Change the message to read "We'll save your draft when the device is back online."
- [ ] Change the coloring to match the posts list.

**Comment by kean** [comment]
Not applicable starting from 24.9 (pcdRpT-6vS-p2)
