### ISSUE TITLE
Let users cancel offline publishing.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#13382]
Let users cancel posts that were queued for offline publishing / draft-saving.

Posts List | Pages List
--- | ---
<img src="https://user-images.githubusercontent.com/1836005/73874322-12407400-4832-11ea-8c62-d2fccc64629e.jpg" width="300"> | <img src="https://user-images.githubusercontent.com/1836005/73874347-1f5d6300-4832-11ea-9e55-41d617b863e1.jpg" width="300">

- [ ] Remove the option to retry publishing / saving in the pages list.
- [ ] Add an option to cancel publishing / saving in the pages list.

**Comment by kean** [comment]
Not applicable starting from 24.9 (pcdRpT-6vS-p2)
