### ISSUE TITLE
Reader: action buttons only appear in detail view for some posts

### ISSUE THREAD

**Issue by Gio2018** [wordpress-mobile/WordPress-iOS#13393]
### Expected behavior
In the reader, for a given post, the action buttons in the toolbar should be the same both in the post list and in the post detail view.

### Actual behavior

For some posts, action buttons are not visible in the post list, and are visible in the post detail (see video below). This behavior seems to be pretty common in the `Discover` feed.

![ActionButtons](https://user-images.githubusercontent.com/34376330/73986714-ebeb0900-4903-11ea-9c0c-5eaa0425b110.gif)

### Steps to reproduce the behavior

1. Tap `Reader` in the tab bar
2. Select `Discover` from the streams
3. Scroll down until a post with no action buttons shows up
4. Tap the post to enter the detail view, and verify that the action buttons show up in that view

##### Tested on: iPhone Simulator (11 Pro Max), iOS 13.3, WPiOS 14.2 Dev (video is from this one)

**Comment by designsimply** [comment]
Discover might be a special case. See https://github.com/wordpress-mobile/WordPress-iOS/pull/9422

@frosty are all of the action buttons always expected to show for posts in the Discover Reader stream? Does it depend on the type of post it is (such as a reblog)? Which action buttons are expected to show for which types of posts?

**Comment by frosty** [comment]
Thanks @designsimply – we're discussing this in pbArwn-58-p2

**Comment by designsimply** [comment]
Looping back to sync up with an update from the internal discussion at pbArwn-58-p2.

The reason some posts on the Discover stream have action buttons and some do not is that some posts are actual blog posts on Discover whereas others are promoting posts or sites elsewhere.

The Editorial team mentioned that their main concern is that user content is properly attributed. For Discover posts which are referencing posts elsewhere, readers can tap the visit and share buttons to interact with the content owner directly.

For reference, here are some screenshots showing the current state of the quick action buttons for both types of posts:

Post written on Discover:

Card in Stream | Individual Post View
--- | ---
<img src="https://user-images.githubusercontent.com/1119271/79369339-08ac4a00-7f0e-11ea-8f06-efc317212930.PNG" width="200" alt="IMG_3836"> | <img src="https://user-images.githubusercontent.com/1119271/79369348-0ba73a80-7f0e-11ea-8418-18d835fb71f6.PNG" width="200" alt="IMG_3837">

Post promoted by Discover:

Card in Stream | Individual Post View
--- | ---
<img src="https://user-images.githubusercontent.com/1119271/79369351-0cd86780-7f0e-11ea-9ede-a9aef8a5ba0e.PNG" width="200" alt="IMG_3838"> | <img src="https://user-images.githubusercontent.com/1119271/79369356-0d70fe00-7f0e-11ea-90c4-78f158fda971.PNG" width="200" alt="IMG_3839">

<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.1 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

Notice how not every site that is promoted has an option for comments. For example, https://wideopenschool.org/ doesn't but other promoted content does.

@frosty @Gio2018 I think the explanation above is satisfactory to close this issue. If you agree, can you please go ahead and close it?

**Comment by Gio2018** [comment]
Hi @designsimply !! Thanks a lot for the update! We both think that the explanation is satisfactory, I'm closing the issue.
