### ISSUE TITLE
Change message shown for pages scheduled for publishing.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#13403]
Show an appropriate inline note in pages that were scheduled while offline.

Posts List | Pages List
--- | ---
<img src="https://user-images.githubusercontent.com/1836005/74053705-219ef900-49bb-11ea-85fb-47e466aecc85.PNG" width="300"> | <img src="https://user-images.githubusercontent.com/1836005/74053693-1c41ae80-49bb-11ea-8d87-98778a9cd788.PNG" width="300">

- [ ] Change the message to read "We'll schedule the page when the device is back online."
- [ ] Change the coloring to match the posts list.

**Comment by kean** [comment]
Not applicable starting from 24.9 (pcdRpT-6vS-p2)
