### ISSUE TITLE
Reader: Post reblogging should not be available for posts on private sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#13418]
### Expected behavior

I expect reblogging to be unavailable for posts published on private sites. That's consistent with web Reader behavior and my expectation that private site content shouldn't be sharable.

### Actual behavior

I see the reblog button in the Reader on posts published on privates sites. I can tap the reblog button and the editor is opened, populated with content from that post.

### Steps to reproduce the behavior

1. Open the Reader and find a post published on a private site.
2. Tap the reblog button on the post.
3. If needed, select a site to publish to and confirm the editor opens with content from that post.

##### Tested on [iPhone XS], iOS [13.3], WPiOS [14.2.0.20200210]

cc @Gio2018

**Comment by frosty** [comment]
Thanks for catching this @rachelmcr!

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/13421.
