### ISSUE TITLE
Log in: site address text color could have more contrast in Dark mode

### ISSUE THREAD

**Issue by jaclync** [wordpress-mobile/WordPress-iOS#13417]
From https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/173#pullrequestreview-337758076

### Expected behavior

In Dark mode and during login, the site address could have more contrast from the background after entering the site address.

### Actual behavior

<img src="https://user-images.githubusercontent.com/1945542/74203683-6ec8e680-4cab-11ea-88c9-856350b6cf76.png" width="320"/>

### Steps to reproduce the behavior

- Log out from the app
- Tap "Log in"
- Tap "entering your site address" at the bottom
- Enter site address --> note the site address text color on the next screen

##### Tested on [device], iOS [version], WPiOS [version]

any simulator or device, iOS 13 for Dark mode, WPiOS 13.9

**Comment by ScoutHarris** [comment]
This was addressed in the Unified Auth project.
