### ISSUE TITLE
Preview: Tapping preview twice in a row causes errors

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#13437]
### Expected behavior

I expect that if I'm able to tap on elements on the screen, even while waiting for another action to complete, I won't cause problems.

### Actual behavior

If I select "Preview" twice in a row, it causes two problems:

* A "Preview Unavailable" screen appears.
* The editor no longer works as expected.

### Steps to reproduce the behavior

1. Create a new post and add some content.
2. Select "Preview" from the ellipsis menu.
3. Immediately (while the status bar still shows "Generating preview") select "Preview" from the ellipsis menu again.
4. After the preview window appears, close it and notice that a screen is visible that says "Preview Unavailable."
5. Go back and notice that the editor no longer works as expected (post settings don't work and can cause a crash, new content can be lost, etc - some similar results as reported in https://github.com/wordpress-mobile/WordPress-iOS/issues/13436)

**Comment by elibud** [comment]
@bjtitus has this one been addressed?
