### ISSUE TITLE
Pages: Improve UX when user tries to edit content on blog posts page

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#13439]
If you have a static front page and a separate blog posts page, it can be confusing if you change the content on the posts page. That content will never appear on the site, since the posts page content is replaced by the blog posts.

Currently, the app doesn't distinguish between a regular page and a page set as the posts page. We should clarify this in the app, either preventing the user from editing that page or clarifying what that page is for on their site. In Calypso, they block users from editing it unless it's switched back to a regular page. Screenshots of the Calypso Pages List for the page set as the posts page on a site:

![Screenshot 2020-02-12 16 16 28](https://user-images.githubusercontent.com/8658164/74354700-a6bb5100-4db3-11ea-9bc5-6b9554483be9.png)
![Screenshot 2020-02-12 16 16 43](https://user-images.githubusercontent.com/8658164/74354703-a8851480-4db3-11ea-9452-a8e1fb2e84e6.png)
![Screenshot 2020-02-12 16 16 53](https://user-images.githubusercontent.com/8658164/74354706-a9b64180-4db3-11ea-9bfd-2d43c162c574.png)

See related internal report: p4a5px-2v4-p2#comment-10537

**Comment by erricgunawan** [comment]
Another confused user from 5223031-zen:

> I don’t understand this new editor format. It’s not user friendly. Why is it such a headache trying to simply figure out how to go to a page and delete the default “Tiffany” text from the new template?

> Why is my Blog Posts Page saying I can’t edit it because my posts are “auto generated“? How is it MY blog can’t be edited by ME?! And who’s generating my posts? I was actually getting ready to upgrade, but this is a MAJOR red flag: I cannot for the life of me do something as simple as remove a HI, I’M TIFFANY default intro from my blog page template. This is super crazy & frustrating.

<details>
  <summary>Screenshots:</summary>
  <br>
  
![0796AC95-1454-49CE-BC9E-C359BA0E81C3_L0_001](https://user-images.githubusercontent.com/1813857/169205863-68d92018-5497-419c-ba0e-ab57b15e71c2.png)

![4330E4AC-4160-450B-9348-98F05BFDD676_L0_001](https://user-images.githubusercontent.com/1813857/169205883-d547e775-5757-4c73-b168-720c01c1e611.png)
  
</details>
