### ISSUE TITLE
Preview: Publishing from preview creates errors/problems in the editor

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#13436]
### Expected behavior

I expect the Publish action in the post preview to work just like the Publish action in the top nav.

### Actual behavior

After I publish from a preview, I run into various problems:

* The editor stays open, with no indication that anything is happening behind the scenes. (I have to wait to see the Post published notice.)
* If I make any changes to the post while the post is being published (between the preview being closed and the publish notice appearing), those changes aren't published. I can then close the editor and am not prompted to save or discard my changes — the editor just closes and my changes are lost.
* The editor still shows a "Publish" action (instead of "Update"). If I tap Publish, the editor closes and any changes I made after the post was published are discarded.
* If I try to preview the post, I get a "Preview Unavailable" error.
* If I select "Switch to classic editor" it switches to the classic editor but the editor is empty (no site title in the nav bar, no title or content in the editor).
* Post Settings don't work: Various fields that should have content are blank (e.g. categories, status) and tapping on a field (e.g. category) makes the app crash.

In addition, there's no confirmation step on the Publish action in the post preview, so it's very easy (or at least I fear that it's easy, creating anxiety) to accidentally tap and publish the post.

cc @bjtitus

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/13442.
