### ISSUE TITLE
[GlobalStep] Gallery’s Preview is inconsistent with its final appearance

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13434]
### Description
When adding a Gallery to a post with many pictures and then turning the number of columns up will have no affect on how the Gallery is displayed in the preview of the post. It was observed that while in portrait mode a maximum of two columns were displayed and in landscape mode a maximum of four columns were displayed.
After the post is published it will still be displayed according to the selected settings.

### Reproduction Rate
4/4 100%

### Expected behavior
The Preview should accurately reflect the final appearance of the post.

### Actual behavior
The Preview does not reflect how the post will look after being published.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Open the Post Editor.
4. Add a Gallery block.
5. Press “Add Media”.
6. Press “WordPress Media Library”.
7. Add more than 8 pictures.
##### Tested on the following
iPhone XR (12.0.1)

#### Screenshot of the Post Editor
<img width="270" src="https://user-images.githubusercontent.com/60415523/74342641-b7fb6200-4da1-11ea-9954-c362d3c570e0.jpg" />

#### Screenshot of the Post viewed in the Reader
<img width="270" src="https://user-images.githubusercontent.com/60415523/74342639-b6ca3500-4da1-11ea-9666-df8809d8515d.jpg" />

### Submitted by:
Luis Pimenta

**Comment by rachelmcr** [comment]
Thanks for the report! The behavior/preview of the gallery block in the editor depends on the block editor, so I'm going to close and combine this report with https://github.com/wordpress-mobile/gutenberg-mobile/issues/1899 (moved from WordPress-Android).
