### ISSUE TITLE
Editor: Improve UX for saving/discarding newly created drafts

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#13432]
We occasionally get reports of posts getting lost in the app that seem to fit this sequence of events:

1. A user creates a new post in the app.
2. The user assumes the post is saved (either because they thought they manually saved it, or they assumed the app would autosave it as they worked on the post) but it isn't.
3. The user closes the editor and discards the changes, which discards the entire draft.

Since the user assumed the draft was saved, they are surprised when it doesn't appear anywhere in the app, and we have no way to recover it for them since it wasn't saved remotely.

We should explore how to improve this experience so that users never lose drafts like this. The solution could be technical (e.g. autosave newly created posts at some point, even if the editor/app isn't closed) or it could be more design oriented (e.g. showing whether/when a post was last saved, or communicating more clearly what will be discarded when the editor is closed). On Android, for example, if you create a new draft in the app and then exit the editor, the post is always autosaved (there is no discard option) which would prevent new posts from being accidentally discarded.

Related internal report: p4a5px-2v4-p2

**Comment by rachelmcr** [comment]
After taking a look at the original internal report, @diegoreymendez also mentioned Android's behavior in this scenario.

Could a designer review this UI/UX, especially to see if we want to match the Android behavior here?

**Comment by yaelirub** [comment]
Related:https://github.com/wordpress-mobile/WordPress-Android/issues/9810

**Comment by kean** [comment]
Closing as obsolete. Starting with 24.9, drafts are saved automatically like in Android and Web.
