### ISSUE TITLE
[GlobalStep] On some tablet devices the lower right preview option lists default and mobile which appear the same.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13440]
### Description
When the user loads the app on a larger tablet device, while previewing a post the lower right icon to switch between desktop and mobile views lists ‘Default’ and ‘Mobile’ , when selected there is no visual appearance in the app, it could be that the mobile view on these tablets is also the default but due to the larger native screen it is being treated as desktop by the app.

### Reproduction Rate
4/4 100%

### Expected behavior
Selecting ‘desktop’, ‘mobile’ or ‘default’ switched the appearance of the preview.

### Actual behavior
Selecting any of the available options causes no change the appearance of the app.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Select ‘My sites’.
4. Select ‘View’ on any post.
5. In the lower right select the change view style button.
6. Select ‘Mobile’ then back to ‘Default’.

##### Tested on the following
iPad 6th Gen (11.3.1)
iPad Air 3 (13.2.3)

#### Please see the attached video for more information.
[Tablet_Change_View.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4193480/Tablet_Change_View.zip)

### Submitted by:
Oliver Howe

**Comment by rachelmcr** [comment]
cc @bjtitus
