### ISSUE TITLE
[GlobalStep] After creating a presentation and viewing the post in portrait, the right arrow does not appear or function.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13447]
### Description
When the user creates a presentation post, tapping inside of the presentation box will reveal left and right arrows in landscape, however while holding the device in portrait the right arrow is missing, and tapping where it ought to be does not function to slide through the presentation to the right.

### Reproduction Rate
4/4 100%

### Expected behaviour
Left and right arrows appear in both orientations.

### Actual behaviour
The right side arrow is missing in portrait.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Select the “Add new post” button.
4. Create a presentation post.
5. Publish and view or preview the post.
6. Tap inside the presentation box while holding the device portrait.

##### Tested on the following
Samsung Galaxy S7 (7.0)
iPhone X (12.3.1)

#### Please see the attached video for more information
[arrow_presentation_portrait.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4197950/arrow_presentation_portrait.zip)

### Submitted by:
Oliver Howe

**Comment by rachelmcr** [comment]
I confirmed that this is not specific to the app previews — the right arrow does not appear in Safari web either. Additionally, there are known iOS issues are being tracked internally (5853-wpcom) so I'll go ahead and close this issue in favor of that internal ticket.
