### ISSUE TITLE
[GlobalStep] No X or button indicator shown on sharing social media site window on tablet devices.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13448]
### Description
On just iOS tablet devices it can be observed that when selecting any of the social media site links within the sharing tab, the user must tap in the upper left of the pop up window to close it and return to the app, however no X or any symbol is displayed in the button area.

### Reproduction Rate
4/4 100%

### Expected behaviour
A symbol indicates where to press to close to the window

### Actual behaviour
No symbol or indicator is given to show where to press to close the window.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Select ‘My Sites’.
4. Select ‘Sharing’.
5. Select any of the social media sites; Facebook, Linkedin, Tumblr or Twitter.
6. Attempt to close the window by tapping out of it or in the upper right.
7. Tap in the top left corner of the window.

##### Tested on the following
iPad Pro 11 (12.3)
iPad Air 3 (13.2.3)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/74431129-3c0f2180-4e56-11ea-8807-3fa7216e22e8.jpg" />

### Submitted by:
Oliver Howe

**Comment by kean** [comment]
Fixed in 25.3 thanks to the removal of the global navigation bar style overrides.
