### ISSUE TITLE
[GlobalStep] iOS 13 - Capture button is not displayed when an empty album is selected while changing the profile’s photo

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13454]
### Description
When attempting to change the profile’s photo a capture button is shown at the top of the window. However, on iOS 13 and when browsing an empty album this button is not shown.

### Reproduction Rate
4/4 100%

### Expected behavior
The capture button should be displayed regardless of the selected album containing no photos.

### Actual behavior
The capture button disappears when the selected album contains no photos.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Select the “Me” tab.
4. Press the profile’s photo.
5. Select an empty album.
##### Tested on the following
iPhone 8 (13.2.3)
iPhone 7+ (13.3)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/74450469-037f4000-4e76-11ea-8709-10b34002f61a.jpg" />

### Submitted by:
Luis Pimenta

**Comment by kean** [comment]
Fixed in the scope of https://github.com/wordpress-mobile/WordPress-iOS/issues/21190
