### ISSUE TITLE
[GlobalStep] Empty bar displayed in the Post Editor’s Site Switcher

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13457]
### Description
When creating a post, pressing the Site switcher at the top of the screen causes the list of the user’s Sites to be displayed along a Search bar. If the user paginates an empty space can be seen above that Search Bar.

### Reproduction Rate
4/4 100%

### Expected behavior
There should be no empty space above the Search bar.

### Actual behavior
There is an empty space above the Search Bar.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Open the Post Editor.
4. Access the Site Selection screen by pressing the Site’s Name at the top of the screen.
5. Swipe down.
##### Tested on the following
iPhone 8 (13.2.3)
iPhone 7+ (13.3)

#### Please see the attached video for more information
[iOSEmptySpaceSiteSwitcher.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4199944/iOSEmptySpaceSiteSwitcher.zip)

### Submitted by:
Luis Pimenta

**Comment by rachelmcr** [comment]
Good catch! This is a layout issue related to the search bar that we're tracking in https://github.com/wordpress-mobile/WordPress-iOS/issues/7819.
