### ISSUE TITLE
[GlobalStep] App crashes on login and logout on the iPhone X 12.3.1

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13451]
### Description
It is being observed on just one device (iPhone X 12.3.1) the app will crash to the home screen every time the user logs in and logs out, immediately after entering password and selecting next on login and immediately after tapping the logout button. The app remembers the login status, so on next launch will be logged in or out depending on the previous action. The issue was attempted to be reproduced on a iPhone XS 12.3.1, exact same firmware but no crash occurred.

### Reproduction Rate
4/4 100%

### Expected behaviour
No crash occurs any time.

### Actual behaviour
App crashes on every login and logout.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Login.
3. Relaunch WordPress 14.2
4. Select the ‘Me’ tab.
5. Logout.
##### Tested on the following
iPhone X (12.3.1)

#### Please see the attached video and logs for more information
[login_crash_iphonex.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4198826/login_crash_iphonex.zip)
[WordPress-2020-02-13-124615.ips.beta.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4198827/WordPress-2020-02-13-124615.ips.beta.zip)

### Submitted by:
Oliver Howe

**Comment by rachelmcr** [comment]
It looks like this is the related Sentry issue for the login crash: [WORDPRESS-IOS-2T1G](https://sentry.io/organizations/a8c/issues/1512391386/?referrer=github_integration)

And this for the logout crash (which I've also experienced): Sentry Issue: [WORDPRESS-IOS-2T0M](https://sentry.io/organizations/a8c/issues/1507594440/?referrer=github_integration)
