### ISSUE TITLE
[GlobalStep] HTML Character codes in a site’s title are displayed in search results

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13456]
### Description
Using HTML Character codes in a site’s title causes the code to be shown instead of the respective characters when displayed in the search results or on the site’s title and header after the user accesses the site through those results.

### Reproduction Rate
4/4 100%

### Expected behavior
The characters corresponding to the HTML Character codes should be displayed.

### Actual behavior
The HTML Character codes are displayed.

### Steps to reproduce the behavior
1. In a Web Browser access a WordPress account and set a Site’s title to ````&#039;test````
2. Install WordPress 14.2
3. Log in to the same account used on Step #1.
4. Navigate to the “Reader” tab.
5. Press Search.
6. Search the address of the site used in Step #1.
7. Access the Site through the search results.
##### Tested on the following
iPhone 8 (13.2.3)

#### Title seen in the Site View and how it should be displayed
<img width="270" src="https://user-images.githubusercontent.com/60415523/74458603-ddf83380-4e81-11ea-9ef1-ce877faeb934.jpg" />

#### Title seen in the Search Results
<img width="270" src="https://user-images.githubusercontent.com/60415523/74458607-df296080-4e81-11ea-8e3b-0b4f4155e44b.jpg" />

#### Title seen when the site’s contents is accessed from the corresponding Search Results
<img width="270" src="https://user-images.githubusercontent.com/60415523/74458606-de90ca00-4e81-11ea-94da-a15a408be10a.jpg" />

### Submitted by:
Luis Pimenta

**Comment by daniloercoli** [comment]
Checked on Jetpack 24.2, and I can still reproduce the issue.

**Comment by kean** [comment]
Closing in the scope of https://github.com/wordpress-mobile/WordPress-iOS/issues/23720
