### ISSUE TITLE
[GlobalStep] Attempting to change a profile’s photo opens a default album named “Selfies”

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13455]
### Description
Pressing the profile’s photo to change it opens up a default album named “Selfies”.
This album is different from a user created album also named “Selfies” and displays separate content.
Note that the first time the user accesses this function after installing the application, the “Recents” album is opened. Every following attempt causes the album “Selfies” to be opened, even after closing and reopening the application as reported in the issue #13453.
Furthermore, because on iOS 13 an empty album does not display the capture button as reported in the issue #13454 this album always remains empty.

### Reproduction Rate
4/4 100%

### Expected behavior
The “Recents” album should open by default as that’s always present on the device.

### Actual behavior
An empty album named “Selfies” which is separate from the user created album also named “Selfies” is opened.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Select the “Me” tab.
4. Press the profile’s photo.
5. If this is a fresh install, close the current window and repeat the previous step.
##### Tested on the following
iPhone 8 (13.2.3)
iPhone 7+ (13.3)

#### Please see the attached video for more information
[iOSProfileSelfies.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4199204/iOSProfileSelfies.zip)

### Submitted by:
Luis Pimenta

**Comment by rachelmcr** [comment]
Defaulting to the Selfies album is the intended behavior per https://github.com/wordpress-mobile/WordPress-iOS/pull/6153.
