### ISSUE TITLE
[GlobalStep] Attempting to change a profile’s photo opens the “Recents” album on the first time only

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13453]
### Description
The first time after installing the application the user presses profile’s photo to change it, the “Recents” album is opened but afterwards, the album named “Selfies” is always opened, even following the closing and reopening of the application.

### Reproduction Rate
4/4 100%

### Expected behavior
The default album for when the user is changing the profile photo should be consistent and always the same.

### Actual behavior
The first time the user attempts to change the profile photo the “Recents” album opens, and after that the “Selfies” album will always open.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Log in to an account.
3. Select the “Me” tab.
4. Press the profile’s photo.
5. Close the photo browser and repeat the previous step to note a different album is opened.
##### Tested on the following
iPhone 8 (13.2.3)
iPhone 7+ (13.3)

#### Please see the attached video for more information
[iOSProfileFirstTime.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4199167/iOSProfileFirstTime.zip)

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Tested and confirmed using WPiOS 14.2.0.2 TestFlight beta on iPhone 6S iOS 13.3.1. ([10s](https://cloudup.com/cSIPc7tgyuk))

**Comment by guarani** [comment]
This has now been fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/18132. The app will now show the same album, "Recents", whenever the profile image picker is opened. Previously the app was attempting to open the "Selfies" album and ran into a separate issue. That likely caused the next attempt to default to the "Recents" album.
