### ISSUE TITLE
[GlobalStep] “Lost your password?” text clips with incorrect password error message

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13465]
### Description
When logging in to a WordPress account using a password, if the user types in a wrong password the message “It seems like you’ve entered an incorrect password. Want to give it another try?” is displayed. When the user then selects the password text box so the keyboard is displayed, the “Lost your password?” button can be seen to clip with the error message.

### Reproduction Rate
4/4 100%

### Expected behavior
There should be no text clipping and all the visible text should be readable.

### Actual behavior
The text from the button clips with the error message making both hard to read.

### Steps to reproduce the behavior
1. Install WordPress 14.2
2. Press the Log In button.
3. Select the “Continue with WordPress.com option”
4. Type in a valid username.
5. Select the “Enter your password instead” option.
6. Type in an invalid password.
7. Press the Password textbox.
##### Tested on the following
iPhone SE (12.0.1)
iPhone 5S (11.4)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/74523783-ae930680-4f15-11ea-8431-cbfd2a64a195.jpg" />

### Submitted by:
Luis Pimenta

**Comment by rachelmcr** [comment]
@mattmiklic I know you're working on new login designs, so this is a bit of an FYI for you to think about re: small screens and error states.

**Comment by mattmiklic** [comment]
Thanks for the ping @rachelmcr! This is a good reminder to think about the SE-class devices. We're rearranging the layout a bit so I think we can fix this when implementing the new login design.

**Comment by mindgraffiti** [comment]
The fix is pending and will be released in WPiOS 15.7

**Comment by mindgraffiti** [comment]
Confirmed fixed in build 15.7

**iPhone SE, iOS 13+**
<img src="https://user-images.githubusercontent.com/1062444/92519993-86843100-f1e0-11ea-849b-d9105d81eab4.png" width="350" />

https://github.com/wordpress-mobile/WordPress-iOS/pull/14764
