### ISSUE TITLE
Post Scheduling: Day of Week labels incorrectly positioned when week starts on Monday

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-iOS#13491]
### Expected behavior

If the week starts on Monday in my region, the calendar in the app should reflect that. The dates on the calendar should line up appropriately with the days of the week labels at the top of the calendar.

### Actual behavior

If the week starts on Monday, the dates on the calendar are in the correct positions, however the days of the week labels are incorrect, with "S" coming first.

### Steps to reproduce the behavior
Steps to reproduce:

1. In iOS Settings > General > Language and Region, set a Region where the week begins on Monday. I chose Lithuania.
2. In WPiOS, create a new post and go to post settings to schedule the post.
3. Check what day it is, and what day of the week it is.

With my region set to Lithuania, the days of the week are incorrect, starting on Sunday when they should start on Monday. Additionally, the dates are in the correct positions, so the dates and the day labels don’t line up, making February 17th a Sunday - which is not true.
￼
![IMG_0561](https://user-images.githubusercontent.com/15107387/74754755-c69eb900-527a-11ea-82d7-211c6d45e744.PNG)

With my region set to US, the days of the week are correct, starting on Sunday and lining up properly with the dates. February 17th is a Monday, as it should be.
￼
![IMG_0560](https://user-images.githubusercontent.com/15107387/74754747-c2729b80-527a-11ea-9ac7-ee0d7bacc666.PNG)

I also checked Calypso, and everything seems fine there.

In Calypso, Language set to English calendar is displayed with Monday as the first day of the week. Dates line up accordingly, with Feb 17th being Monday.
￼
<img width="271" alt="February 2020" src="https://user-images.githubusercontent.com/15107387/74754674-a53dcd00-527a-11ea-84ca-5815a8f359bf.png">

In Calypso, Language set to English (UK), calendar is displayed with Sunday as the first day of the week. Dates line up accordingly, with Feb 17th being Monday.
￼

<img width="270" alt="February 2020" src="https://user-images.githubusercontent.com/15107387/74754634-95be8400-527a-11ea-9be5-caa72523764b.png">

**Comment by ScoutHarris** [comment]
cc @bjtitus .
