### ISSUE TITLE
Comment renders with block delimiters shown

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-iOS#13513]
### Expected behavior
Comment should render without Gutenberg block delimiters on the individual comment screen.

### Actual behavior
Comment shows Gutenberg block delimiters on the individual comment screen. See screenshot:

<img src="https://user-images.githubusercontent.com/1032913/74914350-f3fa7c80-53ca-11ea-822d-5a7079520934.png" width="300">

### Steps to reproduce the behavior
1. In a browser (desktop or mobile web), hop on a site with Gutenberg enabled for post comments, add a two-paragraph comment in a post
2. Publish the comment
3. Open the WP mobile app, go to My Site -> Comments and pull to refresh to get the new comment
4. Tap on the comment to view it in the individual comment screen
5. Notice how the block delimiters are shown 💥

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 6s, iOS v13.3.1, WPiOS v14.1

**Comment by hypest** [comment]
Tested the internal 14.2 beta is the issue is not there. @emilylaguna has pointed me to https://github.com/wordpress-mobile/WordPress-iOS/pull/13351 which should alleviate the issue.

That said, it seems that in my testing, the block delimiters are not there, but at the same time the blockquote is not rendered at all:

<img src="https://user-images.githubusercontent.com/1032913/74944144-3a1d0380-53fe-11ea-85c6-660628f80009.png" width="300">

**Comment by ScoutHarris** [comment]
This seems resolved. The block quote now appears. Tested in 17.0.

![IMG_34F45564D491-1](https://user-images.githubusercontent.com/1816888/113067625-eab91300-9179-11eb-8b17-19ec519ae18c.jpeg)
