### ISSUE TITLE
Missing `post_type` property on some `wpios_editor_` events

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-iOS#13527]
We're not tracking the `post_type` property on the following events:

- editor_post_published
- editor_post_updated
- editor_post_scheduled
- editor_draft_saved
- editor_post_created

This property is useful to differentiate post and page publishing. 

Note: it's correctly set [in wpandroid](https://github.com/wordpress-mobile/WordPress-Android/blob/c701c44dd58a2b49ae3d72320a15e04c7b338a6c/WordPress/src/main/java/org/wordpress/android/ui/posts/PostUtils.java#L67) for these events.

**Comment by pinarol** [comment]
Thank you @maxme for the ticket. @chipsnyder let's add that prop using some guidance from @koke if necessary.

**Comment by chipsnyder** [comment]
@maxme Just want to confirm a flow for a particular event:

1) Create a new Page or Post
2) Make a few edits Set title and content
3) Select "X" in the top left-hand corner 
*Expect:* To see a dialog with "You have unsaved changes." and "Save Draft"
4) Select Save

Question: Which analytics event should I be expecting?
- `editor_draft_saved`
- `editor_quick_draft_saved` 
- `editor_post_published` (This is what that flow currently logs)



**FYI** `editor_quick_draft_saved`  is logged by selecting `...` in the top right-hand corner then "Save as Draft"

**Comment by maxme** [comment]
@chipsnyder - I don't know why we want to differentiate the 2 saves action (`editor_quick_draft_saved` and `editor_draft_saved`), that seems like the same action to me (tapping X and save a draft, or tapping "save"). There is no prompt on Android, so that's probably why there is not difference. I'll have a look at the history to see if I'm missing some context.

In that case, `editor_post_published` is wrong, the current description of that event is "The user published a post." and this is not the case when the user saved a draft.

**Comment by chipsnyder** [comment]
>In that case, `editor_post_published` is wrong,

Thanks @maxme, that's what I had assumed. I'll open another issue for that and include it in my PR.

**Comment by maxme** [comment]
`editor_quick_draft_saved` was introduced [here](https://github.com/wordpress-mobile/WordPress-iOS/commit/151a84688be28b67d5e484372ef5071bfaf23d57). @frosty what's your opinion about merging `editor_quick_draft_saved` and `editor_draft_saved` events? Maybe we can merge them and track the difference in a property?

**Comment by frosty** [comment]
So we use the quick draft and quick published events to track whether the user uses those quick actions available in the `...` menu. It would probably be nice to have some way to differentiate those events whenever we look at updating the publishing flow – I guess we could track it as a property to simplify the number of events we have 👍

**Comment by chipsnyder** [comment]
> Thanks @maxme, that's what I had assumed. I'll open another issue for that and include it in my PR.

Based on the other bits of conversation it sounds like we should open a separate issue to track these changes then for their ideal state.

**Comment by chipsnyder** [comment]
@frosty @maxme I created an issue to track `editor_draft_saved` not firing. Happy to update it with the info from @frosty's comment if that's the way we want to go.
