### ISSUE TITLE
Support for Uploading Multiple Images from a Device to Gallery Block

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#13537]
### Expected behavior

In Aztec, it's possible for users to upload multiple images from their device to the app by navigating to the post editor, tapping the + icon, then tapping all the images from their device that they'd like to upload.

As a lot of users are used to this workflow, I'd expect it to be possible for them to easily upload multiple photos from their device with Gutenberg, also. In particular, I'd expect it to be possible to select multiple images from your device using the Gallery block.

### Actual behavior

If Gutenberg's enabled, you're only able to upload one image from your device at a time. 

The Gallery block only allows you to choose images from your site's media library. It doesn't allow you to select images from your device.

To upload multiple images from your device, you'd need to follow these steps:

1. Tap the + icon in the post editor.
1. Choose the Image block to add that block to your post.
1. Tap the Image block then select the "choose from device" option.
1. Select the image you want to use from your device.
1. Repeat the above steps for every image you'd like to upload to the post.

This adds a lot of time and steps to a process that is relatively simple with the Aztec editor.  

This was reported in 2736092-zen, by a user who regularly uploads multiple images from their device at a time and who found that the switch to the block editor disrupted their workflow.

##### Tested on iPad Mini, iOS 12.4.5, WPiOS 14.1

**Comment by GeoJunkie** [comment]
Reported in 2754693-zen

**Comment by KokkieH** [comment]
Another report in https://wordpress.com/forums/topic/select-files-button-not-working-for-multiple-photo-upload-on-iphone/

**Comment by pinarol** [comment]
This can be tracked with the gutenberg-mobile ticket: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2255

**Comment by hypest** [comment]
> This can be tracked with the gutenberg-mobile ticket: wordpress-mobile/gutenberg-mobile#2255

👋 @pinarol , can we close this in favor of the gb-mobile ticket or do the ticket scopes don't match?

**Comment by pinarol** [comment]
Scopes match but I wasn't sure if @SiobhyB wanted to keep this open. I'll close now but let me know if you prefer to keep this one open as well @SiobhyB .
