### ISSUE TITLE
Cannot select a mentioned user when composing the first comment

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13577]
Steps to reproduce:

1. Log in as the user to be mentioned.
1. Go to Notifications > Settings (gear icon) > Your Sites > Notifications Tab.
1. Verify "User mentions" are enabled.
1. Log in as anyone other than the mentioned user on a site where you are both users.
1. Go to My Site > Posts > + to start a new post.
1. Add a title.
1. Add some content and mention @username for the mentioned user.
1. Publish the post.
1. Log in as the mentioned user.
1. Tap on the mention in the Notifications section.
1. Tap the comment icon near bottom right.
1. You should see a message saying "Be the first to leave a comment."
1. Type "@" into the comment area and try to select any option in the mentioned user selector.

**Result:** the text "Be the first to leave a comment" is visible over the top of the mentioned user selector and the selections are not tappable.

<img src="https://user-images.githubusercontent.com/1119271/75598366-581ae180-5a58-11ea-84e4-0efa72a7ddbf.PNG" width="270" alt="IMG_3504">
<sup>Tested with WPiOS 14.3.0.1 TestFlight beta on iPhone 6S iOS 13.3.1.</sup>

**Comment by elibud** [comment]
Can we add this to groundskeeping please and tackle asap please?
cc: @amamujee who reported.
