### ISSUE TITLE
Bold and italicized text doesn't appear bold in Reader or Notifications

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13609]
Steps to reproduce:

1. Create a new post on the web.
1. Add a title and some content.
1. Make one of the paragraphs bold **_and_** italics.
1. Publish the post.
1. View the post in the iOS app via Notifications, Reader, and Webviews and check to see whether the bold and italic text looks correct or not.

**Result:** text in a paragraph that is both bold and italicized doesn't look bold in Reader or Notifications but does look bold in Webviews and in a browser such as Safari.

<img src="https://user-images.githubusercontent.com/1119271/76248062-3367fc00-6206-11ea-9a44-e997d8d49429.PNG" width="270" alt="IMG_3516"> <img src="https://user-images.githubusercontent.com/1119271/76248039-2a772a80-6206-11ea-980f-1c6f3bfc80af.PNG" width="270" alt="IMG_3519">
<sup>Tested with WPiOS 14.3 on iPhone 6S iOS 13.3.1.</sup>

The second paragraph looks correctly bold **_and_** italics in Safari, the block editor and in Webviews such as by accessing Editor > {post} > Preview or My Site > View Site.

| Safari | Block Editor | Preview via Editor | View Site |
|---|---|---|---|
| <img src="https://user-images.githubusercontent.com/1119271/76248108-4da1da00-6206-11ea-9436-05bf18fc160e.PNG" width="150" alt="IMG_3520"> | <img src="https://user-images.githubusercontent.com/1119271/76248102-4b3f8000-6206-11ea-81a3-e5c2c495768c.PNG" width="150" alt="IMG_3521"> | <img src="https://user-images.githubusercontent.com/1119271/76248106-4bd81680-6206-11ea-9c32-29d05f22ed32.PNG" width="150" alt="IMG_3522"> | <img src="https://user-images.githubusercontent.com/1119271/76248107-4d094380-6206-11ea-87e4-c9e00a6d027b.PNG" width="150" alt="IMG_3523"> |

<sup>Tested with Safari and WPiOS 14.3 on iPhone 6S iOS 13.3.1.</sup>

<sub>h/t @beaulebens for the original report, internal reference: p4a5px-2vp-p2.</sub>

**Comment by elibud** [comment]
Removing from groundskeeping as it will probably be tackled on the reader improvements being worked on right now by @leandroalonso.

**Comment by leandroalonso** [comment]
Fixed during the Reader Improvements project.
