### ISSUE TITLE
Editing: Editor notices persist for too long (can't be dismissed)

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#13632]
I get frustrated with our editor notices (e.g. "Post draft uploaded" after saving a draft) because they can't be dismissed and they often persist for longer than I want/need.

They end up interfering with my desired actions, such as opening post settings in the editor or viewing my site in the My site tab. I especially tend to notice this when I am editing post settings, because I save often while working on a post and usually save right before opening the settings to add things like tags and categories.

### Steps to reproduce the behavior

1. Create a new post and add a title/content.
2. Open the ellipsis menu and select "Save as draft."
3. Open the ellipsis menu and try to select "Post Settings." Observe that the notice overlaps the action sheet so you can't select it until the notice disappears.
4. Make some changes to the post and tap "Update." Observe that the notice appears again.
5. Publish the post (e.g. with the "Publish now" action in the ellipsis menu). Observe that the editor closes and the notice appears again.
6. Scroll down to the "View Site" option in the My Sites tab and observe that the notice overlaps it so you can't select it until the notice disappears.

<img src="https://user-images.githubusercontent.com/8658164/76444434-e0d04080-63bb-11ea-83c7-3ac0d859b874.png" width="50%">
<img src="https://user-images.githubusercontent.com/8658164/76444456-e6c62180-63bb-11ea-9c42-07127d87914c.png" width="50%">

**Comment by gibtang** [comment]
Will shortening the time that the notice appears fix the issue?

**Comment by rachelmcr** [comment]
I'm not sure — I'd like a design perspective on this before making any change to the current behavior. Just shortening the time could make it harder for someone to take the action on the notice (in this case, the Publish action) if that's their intent, and so far I haven't heard anyone else complain about the current behavior so it might be just me. :)

**Comment by ScoutHarris** [comment]
> so far I haven't heard anyone else complain about the current behavior so it might be just me. :)

FWIW, I find it annoying and blocking as well. 

Shortening the time would probably help, but maybe @osullivanchris has some thoughts?

**Comment by bjtitus** [comment]
I'd like to see a dismissible version of this:

The [PanModal](https://github.com/slackhq/PanModal) project has something like this in their demo project:

<a href="https://user-images.githubusercontent.com/3250/78279789-4acc9900-74d5-11ea-8dbc-27ed9e4c599d.gif"><img src="https://user-images.githubusercontent.com/3250/78279789-4acc9900-74d5-11ea-8dbc-27ed9e4c599d.gif" width="300"></a>

Or inside:

<a href="https://user-images.githubusercontent.com/3250/78279813-55872e00-74d5-11ea-9826-9b24c188344c.gif"><img src="https://user-images.githubusercontent.com/3250/78279813-55872e00-74d5-11ea-9826-9b24c188344c.gif" width="300"></a>

**Comment by gibtang** [comment]
Dismissible sounds good. How about a tap anywhere outside the notice to dismiss it instead of swipe down to dismiss?

**Comment by bjtitus** [comment]
> How about a tap anywhere outside the notice to dismiss it instead of swipe down to dismiss?

Yeah, that functionality would be included. You can see the tap in the first recording I posted.

**Comment by osullivanchris** [comment]
Thanks for the example @bjtitus . That was my idea too, swipe to dismiss. 

We have to balance the different possible intentions of the user here. If the user **does** want to read the notice,
- reducing the time it is displayed would be negative
- I guess tap anywhere to dismiss might be ok, but the user could be multi tasking and tapping while reading

Therefore I think 'swipe to dismiss' is the best option as the user is giving us a clear signal what they want (rather than us inferring it).

The demo looks cool. The only thing is the drag handle on the top means (or at least implies) you can only drag down. I feel like I should be able to just swipe it away in any direction, that would make it feel super light. I'd still be ok with this otherwise though

**Comment by kean** [comment]
These snackbars for drafts were removed in 24.9, along with a couple of other less useful ones.
The app now show snackbars only for important updates.
