### ISSUE TITLE
Reader: Icons on some posts in Reader list have low contrast

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#13630]
Sometimes when I view my Followed Sites list in the Reader, the icons on the bottom of the post card have low contrast. This is also reported in https://github.com/wordpress-mobile/WordPress-iOS/issues/12441#issuecomment-544723368 but I wanted to raise it separately because:

1. I don't recall switching between dark and light mode recently.
2. It only affects some posts, not all.

<img src="https://user-images.githubusercontent.com/8658164/76440540-e6c32300-63b5-11ea-8f85-3fd75a112b88.png" width="50%">

**Comment by designsimply** [comment]
I re-tested this using WPiOS 14.6 beta iPhone 11 and found that I can see the problem only if I have switched between light and dark modes at some point _after_ the app has been opened.

Steps to reproduce:

1. Close the app completely.
1. Switch to Dark Mode.
1. Open Reader and check to see if the icons at the bottom of cards are too low-contrast.
1. Switch to Light Mode.
1. Open Reader again and check to see if the icons at the bottom of cards are too low-contrast.
1. Close the app completely.
1. Repeat the steps except reverse the steps for light and dark mode.

**Result:** the icons at the bottom of post cards become light gray on white and are low-contrast and hard to see. ([1m26s](https://cloudup.com/c3VWWIGo6NC))

<img width="200" alt="Screen Shot 2020-04-15 at Apr 15 2 24 21 PM" src="https://user-images.githubusercontent.com/1119271/79384829-d22df980-7f24-11ea-8e16-c3bb89b505cc.png">
<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.1 TestFlight beta on iPhone 6S iOS 13.3.1.</sup></p>

Note: I also tried testing to see if I could find any super low-contrast icons if I opened the app in either light or dark mode and _did not_ switch between them at any time while the app was open. I couldn't find any grayed out Reader quick action buttons on cards in that case. I scrolled through quite a few! 🙂I checked from a couple different accounts for good measure. I also checked the Search stream and the Site stream for the site showing in the screenshot included earlier, and I didn't spot any troubles with the contrast of the icons at the bottoms of the cards.

<img src="https://user-images.githubusercontent.com/1119271/79381482-4b2a5280-7f1f-11ea-8e90-78c3756df116.PNG" width="200" alt="IMG_3842"> <img src="https://user-images.githubusercontent.com/1119271/79381473-46fe3500-7f1f-11ea-8557-e24bef4c4b4a.PNG" width="200" alt="IMG_3840"> <img src="https://user-images.githubusercontent.com/1119271/79381479-49f92580-7f1f-11ea-8b58-b974c0c0558e.PNG" width="200" alt="IMG_3841"> 
<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.1 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

I can definitely see the problem if I switch back and forth between dark and light mode _while_ the app is open or _after_ the app has been opened but is in the background.

**Comment by leandroalonso** [comment]
Fixed during the redesign of the post cards.
