### ISSUE TITLE
Cannot change a draft to a use a date in the past without publishing it

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13654]
Steps to reproduce:

1. Go to My Site > Blog Posts > + to start a new draft.
1. Add a title and content.
1. Go to More > Post Settings > Publish. 
1. Change to a date in the past.
1. Go back to the edit view.
1. Tap the X button at top left.
1. Tap "Update Post".

**Result:** the post is published when I thought a draft would be saved. ([2m21s](https://cloudup.com/cbvtcS95kbq))

<img width="270" alt="Screen Shot 2020-03-13 at Mar 13 4 35 55 PM" src="https://user-images.githubusercontent.com/1119271/76664272-62090e00-6549-11ea-9657-a0187d347836.png"> <img width="270" alt="Screen Shot 2020-03-13 at Mar 13 4 36 07 PM" src="https://user-images.githubusercontent.com/1119271/76664276-646b6800-6549-11ea-8549-b513b33b7807.png">
<sup>Tested with WPiOS 14.4.0.0 TestFlight beta on iPhone 11 iOS 13.3.1.</sup>

**Comment by elibud** [comment]
@bjtitus is this good to close?

**Comment by bjtitus** [comment]
I tested this and it seems to still be happening. I'll unassigned myself for now and see if I can come back around to it a little later.

**Comment by kean** [comment]
The "Publish Date" fields was removed from drafts in 24.9.
