### ISSUE TITLE
Conflict Resolution Dialog

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#13683]
We've been receiving a lot of complaints of users confused about posts not being updated and displaying the "Local Changes" label (ref #9449).

To reproduce this issue:

1. Create a post using the app and save as a draft
2. Open the post, type some content and then close the app (without exiting the editor)
3. Go to the web, change the post content and publish it
4. Go back to the app, the post will have a "Local changes" label and will never update unless the user discards the changes

Our goal is to match the implemented behavior in Android, which displays a clear message to the user and prompts for an action:

| Post list        | Prompt           |
| ------------- |:-------------:|
| <img src="https://user-images.githubusercontent.com/7040243/76760446-711bd600-676c-11ea-8ea3-34e50ec721c4.png" width="300px" /> | <img src="https://user-images.githubusercontent.com/7040243/76760543-99a3d000-676c-11ea-804d-d514f9a8c7d4.png" width="300px" /> |

#### Showing label

* When the user has a post with local changes
* That has been published with another device (ie.: web)
* The app shows "Version conflict" label

#### Showing prompt to the user

* When the user has a post with local changes
* That has been published with another device (ie.: web)
* And the user tap to edit the post
* We prompt the user to choose between the local version or the remote version

#### Choosing "Discard web"

* We update the post using the local post

#### Choosing "Discard local"

* We discard the local post

## References

* Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/8989
* Revision Dialog on iOS (which is quite similar, but not the same thing): https://github.com/wordpress-mobile/WordPress-iOS/issues/12141

**Comment by embryoconcepts** [comment]
Subtasks (will add PR links when available):

- UI 
	- Add label for `Version Conflict` on `PostCardCell`
	- Add an alert to `Resolve sync conflict` on `PostListViewController`
	- Add toast to `Undo` conflict resolution on `PostListViewController `
- Logic
	- Create a flag for a post having a conflict, based on last modified date
	- Show label when a post has a version conflict in `PostCardCell`
	- Show alert when tapping on a post with a version conflict
	- Present Undo toast, handle behavior for discarding local or web update

**Comment by diegoreymendez** [comment]
I've chatted with @leandroalonso about closing this.  Please DM Leandro or myself if you have questions.
