### ISSUE TITLE
Login: Continue with Apple button no longer has a dark background

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13713]
Steps to reproduce:

1. Log out.
1. Go to the login screen.
1. Verify the colors of the buttons and background color of the bottom sheet are the expected colors. Check from light mode and dark mode.

**Result:** the Continue with Apple button no longer has a dark background like it did in previous releases ([screenshot](https://user-images.githubusercontent.com/1119271/77395609-9198f100-6d67-11ea-9459-7076db9acbaf.PNG) from 14.3 for comparison).

<img src="https://user-images.githubusercontent.com/1119271/77395521-631b1600-6d67-11ea-8221-36b45e20f54d.PNG" width="270" alt="IMG_3582">
<sup>Tested with WPiOS 14.5.0.0 TestFlight beta on iPhone 11 iOS 13.3.1.</sup>

**Comment by ScoutHarris** [comment]
Hey @designsimply . This is by design, ref https://github.com/wordpress-mobile/WordPress-iOS/pull/13686.

**Comment by designsimply** [comment]
Aha, apologies for not catching that. Thank you for the update and clarification!
