### ISSUE TITLE
Login: left and right margins are missing for the button on the two-factor auth screen and elsewhere

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13714]
Steps to reproduce:

1. Use an account that has two-factor authentication setup.
1. Go to Log in > Continue with Apple.
1. Check the "Next" button appearance on the screen where you are prompted to enter the verification code from your authenticator app.

**Result:** left and right margins are missing for the "Next" button.

<img src="https://user-images.githubusercontent.com/1119271/77395881-27348080-6d68-11ea-9313-036e29228eb5.PNG" width="200" alt="IMG_3586"> <img src="https://user-images.githubusercontent.com/1119271/77395876-256abd00-6d68-11ea-9829-b1f67202537a.PNG" width="200" alt="IMG_3587">
<sup>Tested with WPiOS 14.5.0.0 TestFlight beta on iPhone 11 iOS 13.3.1.</sup>

**Comment by loremattei** [comment]
This should already be fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/13703.

**Comment by designsimply** [comment]
Closing as fixed by #13703. Props @mindgraffiti. 🎉
