### ISSUE TITLE
Reader: Password-protected posts appear to site members in site feed but can't be viewed

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#13719]
### Expected behavior

I expect password-protected posts to always be excluded from the Reader, since they can't be viewed there.

### Actual behavior

As the owner of a site, when I view my site's feed in the Reader I can see password-protected posts in the feed:

Site Feed|Post Detail
-|-
<img src="https://user-images.githubusercontent.com/8658164/77439424-ef1c5480-6dde-11ea-9dc7-e1f7ce7a75ce.PNG"> | <img src="https://user-images.githubusercontent.com/8658164/77439440-f2afdb80-6dde-11ea-8739-8ccc990047e0.PNG">

Other scenarios that work as expected:

* If I view the site feed (logged in as the same user) on the web, the password-protected post doesn't appear.
* If I am logged in as a user who isn't a member of the site and I view the site feed, the password-protected post doesn't appear.

### Steps to reproduce the behavior

1. Follow a site you own.
2. Publish a password-protected post on that site.
3. Confirm you don't see that post in your followed sites feed under Reader > Followed Sites.
4. View the site's Reader feed, e.g. by going to Reader > Followed Sites > Manage > Select the site.
5. Notice that the post appears in the list of posts in the site feed. Select the post to open the post detail.

##### Tested on [iPhone XS], iOS [13.3.1], WPiOS [14.4]

Related Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/11519

**Comment by leandroalonso** [comment]
This still happens.

However, given the lack of activity here and the fact that is not affecting users I'll go ahead and close the issue. We can reassess that decision anytime, of course.
