### ISSUE TITLE
What exactly should be shown when a post has a date but is still a draft?

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13724]
<sup>h/t @bjtitus for the original report (internal reference: p5T066-1dA-p2#comment-4522).</sup>

It seems confusing to indicate that the post is published/scheduled when the status is different.

* Published: “Published on”
* Scheduled: “Scheduled for”
* Draft: “Scheduled for” / “Published on” depending on whether the date is in the future.

<img src="https://user-images.githubusercontent.com/1119271/77481031-702c1980-6de8-11ea-9c1b-e1383c0bae5f.PNG" width="270" alt="IMG_3574"> <img src="https://user-images.githubusercontent.com/1119271/77481035-70c4b000-6de8-11ea-9d69-170b5a13f9be.PNG" width="270" alt="IMG_3575">
<sup>Tested with WPiOS build 14.5 (25496) MS App Center on iPhone 11 iOS 13.3.1.</sup>

This might be one of those cases where having both the date labeling and the post status is confusing.

**Comment by kean** [comment]
This fields was removed for draft in 24.9.
