### ISSUE TITLE
[GlobalStep] The image displayed in the Magic Link confirmation screen is not properly scaled on the iPhone 5S.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13755]
### Description
An image is displayed after the user presses the “Send Link” button during the Log In flow after the user inputs the Email Address. This image is not properly scaled on iPhone 5S devices and is partially cropped.
It was observed that the cropped portion of the image is slightly bigger on iOS 11.4 than on iOS 12.0.

### Reproduction Rate
4/4 100%

### Expected behaviour
The page should be fully visible.

### Actual behavior
The Image is only partially displayed as it does not fit the screen.

### Steps to reproduce the behavior
1. Install WordPress 14.5
2. Tap “Log In” button.
3. Select the “Continue with WordPress.com” option.
4. Input a valid Email Address.
5. Press the “Next” button.
6. Press the “Send Link” button.
##### Tested on the following
iPhone 5S (11.4)
iPhone 5S (12.0)

#### iPhone 5S (11.4)
<img width="270" src="https://user-images.githubusercontent.com/60415523/77743553-2aea3080-7010-11ea-998e-be9db61c7b3f.jpg" />

#### iPhone 5S (12.0)
<img width="270" src="https://user-images.githubusercontent.com/60415523/77743575-34739880-7010-11ea-82e5-4ebd242ac854.jpg" />
### Submitted by:
Luis Pimenta

**Comment by ScoutHarris** [comment]
Hey @designsimply . Do you have any opposition to closing this? It will probably be a couple months, but this view will be entirely different with the Unified Auth project, and won't have the image at all.

<img width="326" alt="Screen Shot 2020-03-27 at 3 28 25 PM" src="https://user-images.githubusercontent.com/1816888/77802021-a44d4780-703f-11ea-8518-7893827d902f.png">

**Comment by designsimply** [comment]
No objection! Closing with a note that progress on the Unified Login & Signup is being tracked at https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/182. 👍
