### ISSUE TITLE
[GlobalStep] Changing the device’s orientation while in “Media” causes spacing issues.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13765]
### Description
Rotating the device while in “Media” causes additional spacing between the thumbnails to be visible.

### Reproduction Rate
4/4 100%

### Expected behaviour
Changing the device’s orientation should happen without issues.

### Actual behavior
Changing the device’s orientation causes graphical issues.

### Steps to reproduce the behavior
1. Install WordPress 14.5
2. Login to a valid account
3. Tap the “Media” button.
4. Rotate the device.
##### Tested on the following
iPhone SE (13.1.3)
iPad Air 3 (13.2.3)

#### Please see the attached video for more information
[MediaOrientation.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4394902/MediaOrientation.zip)

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Screenshots from the video for reference:

<img width="200" alt="Screen Shot 2020-03-30 at Mar 30 10 34 13 PM" src="https://user-images.githubusercontent.com/1119271/77987259-9a914180-72d6-11ea-96bf-69881e376ab9.png">   <img width="200" alt="Screen Shot 2020-03-30 at Mar 30 10 34 03 PM" src="https://user-images.githubusercontent.com/1119271/77987267-9ebd5f00-72d6-11ea-991b-377f79b4f355.png">

**Comment by designsimply** [comment]
I tested with my iPhone 6S and I can see a similar gap between columns of images after rotating the device, but it's not as pronounced on my device—probably because the screen size is slightly larger in comparison. ([15s](https://cloudup.com/c_SbhPOU8hF))

Moving this issue to Groundskeeping because I don't think it's urgent to fix for the current release.

**Comment by kean** [comment]
In was fixed in one the previous versions.
