### ISSUE TITLE
[GlobalStep] Dark Mode - Graphical issue present when viewing a Followed Site’s Blog Post in the Reader.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13763]
### Description
When viewing a Followed Site’s Blog Post in the Reader while using Dark Mode, an unexpected Grey area is displayed surrounding the top right corner of the post.

### Reproduction Rate
4/4 100%

### Expected behaviour
There should be no graphical issues.

### Actual behaviour
A Grey border is displayed.

### Steps to reproduce the behaviour
1. Install WordPress 14.5
2. Login to a valid account.
3. Navigate to the “Reader”.
4. Access “Followed Sites”.
5. Tap one of the posts.
##### Tested on the following
iPhone SE (13.1.3)

### Portrait
<img width="270" src="https://user-images.githubusercontent.com/60415523/77773967-3f472100-7042-11ea-99b5-fb16d791f020.jpg" />

### Landscape
<img width="270" src="https://user-images.githubusercontent.com/60415523/77774037-57b73b80-7042-11ea-9047-40f18975d291.jpg" />

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
I tested and found that if I viewed an individual post in the Reader after opening the app and before switching between light and dark mode after that point then I couldn't see the problem mentioned:

<img src="https://user-images.githubusercontent.com/1119271/77986390-2a81bc00-72d4-11ea-9e82-04c5fa19e9ad.PNG" width="200" alt="IMG_3585"> <img src="https://user-images.githubusercontent.com/1119271/77986382-2786cb80-72d4-11ea-8b1e-da4a6a07ad3c.PNG" width="200" alt="IMG_3582"> 
<p style="clear:both;"><sup>Tested with WPiOS 14.5.0.1 TestFlight beta on iPhone 6S iOS 13.3.1.</sup></p>

However, if I switch between light or dark mode _while the app is open_, then I can see the problem very clearly—the area to the right of the title isn't doesn't look right:

<img src="https://user-images.githubusercontent.com/1119271/77986890-7aad4e00-72d5-11ea-832f-61ddc17c0df0.PNG" width="200" alt="IMG_3581"> <img src="https://user-images.githubusercontent.com/1119271/77986894-7da83e80-72d5-11ea-805e-cb81949d5850.PNG" width="200" alt="IMG_3584">
<p style="clear:both;"><sup>Tested with WPiOS 14.5.0.1 TestFlight beta on iPhone 6S iOS 13.3.1.</sup></p>

<sup>(internal reference: p4a5px-2wF-p2#comment-10730 which notes we should prioritize visual problems with rendered posts more aggressively right now)</sup>

**Comment by ScoutHarris** [comment]
> However, if I switch between light or dark mode while the app is open, then I can see the problem very clearly—the area to the right of the title isn't doesn't look right:

Thanks for your notes @designsimply . That helped me reproduce the issue.
