### ISSUE TITLE
[Enhancement] When deleting activity logs, user should be presented with a popup seeking confirmation

### ISSUE THREAD

**Issue by gibtang** [wordpress-mobile/WordPress-iOS#13774]
[Type] Enhancement

### Expected behavior
User should be presented with a popup asking user to confirm deleting of activity logs

### Actual behavior
No modal popup presented

### Steps to reproduce the behavior
Go to “Help & Support“, “Activity Logs” and tap on “Clear old activity logs” 

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPhone XR iOS version 13.3.1

**Comment by designsimply** [comment]
Thank you for the suggestion! 

I tested and verified that Account (Me) > Help & Support > Activity Logs > Clear old activity logs doesn't prompt for a confirmation before deleting the old app logs. ([27s](https://cloudup.com/cPFG2MOZsbN)) I think it's a good suggestion and will add it to our backlog to see if someone can pick it up in a future maintenance rotation or hack week.

<img src="https://user-images.githubusercontent.com/1119271/78170202-d4b22e80-740f-11ea-8407-6e7ec6f5ac23.PNG" width="200" alt="IMG_3689">
<sup>Tested with WPiOS 14.5.0.1 TestFlight beta on iPhone 11 iOS 13.4.</sup>

**Comment by gibtang** [comment]
I can do a fix for that if you wish. I think this can be tagged as a good first issue

**Comment by designsimply** [comment]
That sounds great! Let me see if I can get you some guidance on design and pre-existing code patterns for a prompt like this one if that's needed. Or are you feeling comfortable enough with the codebase to take it on already?

**Comment by gibtang** [comment]
Thanks, I have done it and here is the PR https://github.com/wordpress-mobile/WordPress-iOS/pull/13799

Let me know if the design or code syntax needs to be changed to fit certain guidelines

**Comment by designsimply** [comment]
Apologies for the delay. I see you're getting the code and design feedback in the PR so you're all set and we should be able to close this issue out soon. 🎉

Thanks for contributing!
