### ISSUE TITLE
iA Navigation: Startup Modal with link to Announcement Blog Post

### ISSUE THREAD

**Issue by bjtitus** [wordpress-mobile/WordPress-iOS#13788]
Add a modal introducing the Create FAB, Me, and Reader navigation changes on startup.

https://ministryofmagicp2.wordpress.com/2020/01/28/ia-project-my-site-ios/#comment-571

**Comment by designsimply** [comment]
I removed the milestone from this issue since 14.6 has already shipped and I think tracking this issue in the Information Architecture Refresh project board makes the milestone on the issue unnecessary—the PR is the place to add a milestone, once a PR is avail. 👍
