### ISSUE TITLE
iA Tooltip for FAB

### ISSUE THREAD

**Issue by bjtitus** [wordpress-mobile/WordPress-iOS#13787]
Add a tooltip for the Create FAB so new users are introduced to the navigation change.

https://ministryofmagicp2.wordpress.com/2020/01/28/ia-project-my-site-ios/#comment-571

**Comment by designsimply** [comment]
Note: I removed the 14.6 milestone from this issue because I noticed the associated PR now shows the milestone as 14.8 and I think that PRs are traditionally the best place to track the milestone in most cases. 👍
