### ISSUE TITLE
iA Reader Navigation: Intro card for Reader navigation changes

### ISSUE THREAD

**Issue by bjtitus** [wordpress-mobile/WordPress-iOS#13789]
Add a card to describe the changes to Reader Navigation

https://ministryofmagicp2.wordpress.com/2020/01/28/ia-project-my-site-ios/#comment-571

See `ReaderNewsCard` for implementation of the current Offline new card.

**Comment by designsimply** [comment]
I removed the 14.6 milestone from this issue in favor of tracking it in the Information Architecture Refresh project board.
