### ISSUE TITLE
Layout: do an audit of the app to make sure we are consistent with the support of safe area insets

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13792]
While beta testing version 14.5 of the app, I noticed quite a few places where various parts of the layout don't extend all the way to the right of the screen when in landscape mode. Here is an example from the Themes screen:

<img src="https://user-images.githubusercontent.com/1119271/78185571-89584a00-7428-11ea-9af8-74f25a2f13fe.PNG" width="540" alt="IMG_3672 copy">
<p style="clear:both;"><sup>Tested with WPiOS 14.5.0.1 TestFlight beta on iPhone 11 iOS 13.4.</sup></p>

In comparison, it looks much nicer on a smaller device such as an iPhone 6S probably because it doesn't trigger a splitscreen view at that size:

<img src="https://user-images.githubusercontent.com/1119271/78185768-d50af380-7428-11ea-819e-63ab83d25ef5.PNG" width="540" alt="IMG_3595">
<p style="clear:both;"><sup>Tested with WPiOS 14.5.0.1 TestFlight beta on iPhone 6S iOS 13.3.1.</sup></p>

I took several more screenshots for reference:

<img src="https://user-images.githubusercontent.com/1119271/78185997-37fc8a80-7429-11ea-85ac-28de81435631.PNG" width="200" alt="IMG_3660"> <img src="https://user-images.githubusercontent.com/1119271/78186002-3af77b00-7429-11ea-8310-d7f59a174319.PNG" width="200" alt="IMG_3661"> <img src="https://user-images.githubusercontent.com/1119271/78186004-3b901180-7429-11ea-9afe-3fbbb34a4398.PNG" width="200" alt="IMG_3662"> <img src="https://user-images.githubusercontent.com/1119271/78186006-3b901180-7429-11ea-90e7-ecf70d1d1c5f.PNG" width="200" alt="IMG_3663"> <img src="https://user-images.githubusercontent.com/1119271/78186007-3c28a800-7429-11ea-877c-2a030540092c.PNG" width="200" alt="IMG_3664"> <img src="https://user-images.githubusercontent.com/1119271/78186008-3cc13e80-7429-11ea-8db2-962ffca10cb0.PNG" width="200" alt="IMG_3665"> <img src="https://user-images.githubusercontent.com/1119271/78186011-3d59d500-7429-11ea-91a8-6a359a6d71ed.PNG" width="200" alt="IMG_3666">  <img src="https://user-images.githubusercontent.com/1119271/78186013-3d59d500-7429-11ea-9fee-41a58528455f.PNG" width="200" alt="IMG_3667"> <img src="https://user-images.githubusercontent.com/1119271/78186014-3df26b80-7429-11ea-9f4f-376971a0ca07.PNG" width="200" alt="IMG_3668"> <img src="https://user-images.githubusercontent.com/1119271/78186016-3df26b80-7429-11ea-875a-4f7f2c1cfe59.PNG" width="200" alt="IMG_3669"> <img src="https://user-images.githubusercontent.com/1119271/78186018-3df26b80-7429-11ea-9073-ebf7a0b327f3.PNG" width="200" alt="IMG_3670"> <img src="https://user-images.githubusercontent.com/1119271/78186019-3df26b80-7429-11ea-845d-9ca766d67ad8.PNG" width="200" alt="IMG_3671"> <img src="https://user-images.githubusercontent.com/1119271/78186020-3e8b0200-7429-11ea-8007-9b9dbdd6b789.PNG" width="200" alt="IMG_3672"> <img src="https://user-images.githubusercontent.com/1119271/78186022-3e8b0200-7429-11ea-88c2-fa1877666b3b.PNG" width="200" alt="IMG_3674"> <img src="https://user-images.githubusercontent.com/1119271/78186026-3f239880-7429-11ea-9ca1-767a60d42893.PNG" width="200" alt="IMG_3675"> <img src="https://user-images.githubusercontent.com/1119271/78186027-3f239880-7429-11ea-802f-0db14e8de83e.PNG" width="200" alt="IMG_3676"> <img src="https://user-images.githubusercontent.com/1119271/78186028-3fbc2f00-7429-11ea-9afb-2f42d9e6a76c.PNG" width="200" alt="IMG_3677"> <img src="https://user-images.githubusercontent.com/1119271/78186029-3fbc2f00-7429-11ea-80cc-0afca23adf32.PNG" width="200" alt="IMG_3678"> <img src="https://user-images.githubusercontent.com/1119271/78186030-3fbc2f00-7429-11ea-9163-8868b6d4f398.PNG" width="200" alt="IMG_3679"> <img src="https://user-images.githubusercontent.com/1119271/78186031-4054c580-7429-11ea-8f79-e17b3df7545d.PNG" width="200" alt="IMG_3685"> <img src="https://user-images.githubusercontent.com/1119271/78186033-4054c580-7429-11ea-9380-7ddd823a3b14.PNG" width="200" alt="IMG_3686"> <img src="https://user-images.githubusercontent.com/1119271/78186036-40ed5c00-7429-11ea-9eb9-4e51a34e5a11.PNG" width="200" alt="IMG_3687"> <img src="https://user-images.githubusercontent.com/1119271/78186037-4185f280-7429-11ea-8f96-d0fb0fa09752.PNG" width="200" alt="IMG_3688">
<p style="clear:both;"><sup>Tested with WPiOS 14.5.0.1 TestFlight beta on iPhone 11 iOS 13.4.</sup></p>

<sup>(internal reference: p4a5px-2wF-p2#comment-10730, where we specifically discussed display problems in the Reader but also decided to prioritize making sure user-created content is properly displayed in the apps)</sup>

**Comment by bjtitus** [comment]
> it looks much nicer on a smaller device such as an iPhone 6S probably because it doesn't trigger a splitscreen view at that size

Just wanted to point out that this is an issue with the notch on these devices.

Many of these should be cleaned up, but we should expect to have a bit of a gap in many cases where controls would be obscured. As an example, this screenshot of Settings matches pretty closely with what the native Notes applications does with cells.

![](https://user-images.githubusercontent.com/1119271/78186018-3df26b80-7429-11ea-9073-ebf7a0b327f3.PNG)
![IMG_1311](https://user-images.githubusercontent.com/3250/78188363-52d0fe00-742d-11ea-871a-65924c438b60.png)

**Comment by frosty** [comment]
Thanks for the report, @designsimply! We should do an audit of the app to double check we're being consistent with the support of safe area insets. For now, I'm going to adjust this issue to low priority, due to low severity (visual issue) x medium impact (only notched devices affected).

**Comment by mindgraffiti** [comment]
I'm currently researching this issue. The landscape layouts aren't consistent between similar viewports. For example, the iPhone 11 (iOS 13.4) displays a splitscreen view, but the iPhone 11 Pro (iOS 13.4) shares the same viewport size and does not display splitscreen. Please note that I say **viewport** and not **screen size**, because the iPhone 11 Pro has a higher pixel density but the same physical size as an iPhone 11.

**iPhone 11, iOS 13.4.1**
<img src="https://user-images.githubusercontent.com/1062444/79774175-10963080-82f8-11ea-8b79-6494dbd2550e.png" />

**iPhone 11 Pro, iOS 13.4.1**
<img src="https://user-images.githubusercontent.com/1062444/79774227-24419700-82f8-11ea-9fd1-ea3c241d1208.png" />

**Comment by mindgraffiti** [comment]
For reference, check out the Human Interface Guidelines > Visual Design > [Adaptivity and Layout page](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/adaptivity-and-layout/), Device Size Classes heading. 

In looking at the `Landscape Orientation` column of the HIG page, any device that is listed as `Regular width` should display the two-column layout. Any device that is listed as `Compact width` should display the single-column layout. 

It appears that any device with a physical size of 6 inches (152.4 mm) or greater gets the two-column layout in Landscape orientation. 

They include:
- all iPads
- any iPhone "Plus" models
- any iPhone "Max" models
- the iPhone XR

All other devices are expected to keep compact mode (single-column layouts):
- iPhone SE
- iPhone 6, 7, 8, X, Xs, 11 Pro

**Comment by frosty** [comment]
Just an addition to your device lists above, the XR _and 11_ have a regular width by default.

**Comment by mindgraffiti** [comment]
Thanks @frosty! Edited ✔️

**Comment by designsimply** [comment]
Moved this out of the Prioritized iOS list due to low priority and I updated the title to reflect the comment saying we should "do an audit of the app to double check we're being consistent with the support of safe area insets." 👍

**Comment by designsimply** [comment]
I'd like to suggest we cover this case as part of the audit proposed in this issue:

- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/13846

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jkmassel** [comment]
This was done a long time ago
