### ISSUE TITLE
Clean up our image-downloading code.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#13848]
There are many different classes *kinda* doing the same thing, and sometimes re-implementing the same logic for image downloads.

We should review if there's any way in which we can simplify this to make our code easier to maintain.

- https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Utility/Media/ImageLoader.swift
-  https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Gutenberg/GutenbergImageLoader.swift
- https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Utility/Media/ImageDownloader.swift
- https://github.com/wordpress-mobile/WordPressUI-iOS/blob/develop/WordPressUI/Extensions/UIImageView+Networking.swift
- https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Services/MediaThumbnailService.swift

**Comment by kean** [comment]
Image loading was largely consolidated in 23.* – closing as obsolete.
