### ISSUE TITLE
[GlobalStep] Sharing Media from the device’s Photos application does not function.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13845]
### Description
Attempting to share Media from the device’s Photos application causes a tapping animation to be played on the WordPress icon but nothing else occurs.

### Reproduction Rate
4/4 100%

### Expected behaviour
The selected Media should be successfully shared to WordPress.

### Actual behaviour
Nothing occurs.

### Steps to reproduce the behaviour
1. Install WordPress 14.6
2. Login to a valid account.
3. Open the device’s “Photos” application.
4. Attempt to share Media to the WordPress application.
##### Tested on the following
iPhone 7+ (12.0.1)

#### Please see the attached video for more information
[iOSPhotosShare.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4449717/iOSPhotosShare.zip)

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
I tested with 14.6.0.0 TestFlight beta on iPhone 11 iOS 13.4 and sharing from Apple's Photos app to the WPiOS app worked normally for me.

Noting that we should do further testing on our end with iOS 12.x for this case.
