### ISSUE TITLE
[GlobalStep] Changing the device’s orientation to Landscape mode while in the “My Sites” screen when all Sites are hidden causes the image to disappear.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13859]
### Description
When all Sites are hidden in the “My Sites” screen, an image is displayed along a message stating how many Sites are hidden and prompting the user to change their visibility. Rotating the device to Landscape mode while in this screen causes the image to disappear.
The image is properly displayed when the user accesses this screen while already in Landscape mode.

### Reproduction Rate
4/4 100%

### Expected behaviour
The screen’s layout should be maintained during orientation changing.

### Actual behaviour
The Image presented in this screen disappears.

### Steps to reproduce the behaviour
1. Install WordPress 14.6
2. Login to a valid account.
3. Navigate to “My Sites”.
4. Click “Edit”.
5. Toggle all Sites to “Hidden”.
6. Click “Done”.
7. Rotate the device to Landscape mode.
##### Tested on the following
iPhone 7+ (12.0.1)

### Image in Landscape mode
<img width="270" src="https://user-images.githubusercontent.com/60415523/78915034-3bc08a80-7a83-11ea-9ae0-73d6a39eab31.jpg" />

### Video of the same screen without the Image being displayed
[iOSMySitesOrientationImage.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4457276/iOSMySitesOrientationImage.zip)

### Submitted by:
Luis Pimenta

**Comment by ScoutHarris** [comment]
This is by design. Because there is less vertical space, the image is purposefully hidden on iPhone + landscape.
