### ISSUE TITLE
[GlobalStep] While in Landscape mode in the “My Sites” screen, the “Change Visibility” button is slightly behind the footer’s menu and its text is unnecessarily truncated.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13857]
### Description
When all sites are hidden, in the “My Sites” screen, a “Change Visibility” button is shown. While in Landscape Mode, this button is only partially visible as the bottom part of it goes behind the footer’s menu even when the user attempts to scroll down. Furthermore the text of this button is unnecessarily truncated, similar to issue https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/issues/155 

### Reproduction Rate
4/4 100%

### Expected behaviour
The button and its text should be fully displayed without graphical issues.

### Actual behaviour
Part of the button is hidden behind the footer’s menu and the button’s text is unnecessarily truncated.

### Steps to reproduce the behaviour
1. Install WordPress 14.6
2. Login to a valid account.
3. Navigate to “My Sites”.
4. Change the device’s orientation to Landscape Mode.
5. Press “Edit”.
6. Toggle all Sites to “Hidden”.
7. Press “Done”.
##### Tested on the following
iPhone 7+ (12.0.1)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/78914825-e6847900-7a82-11ea-8451-5d23b1a40d99.jpg" />

### Submitted by:
Luis Pimenta

**Comment by kean** [comment]
This feature was removed.
