### ISSUE TITLE
Update XML-RPC to not call the deprecated metaWeblog methods

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#1385]
The metaWeblog methods are deprecated. Let's not use them anymore.

**Comment by aerych** [comment]
Working on the switch from metaWeblog.getRecentPosts to wp.getPosts

**Comment by aerych** [comment]
Switched from `metaWeblog.getRecentPosts` to `wp.getPosts` in https://github.com/wordpress-mobile/WordPress-iOS/commit/09558cc9a2938aa2b0c869ae930f567204cab76c

**Comment by kurzee** [comment]
Surprisingly, we're still using both `metaWeblog.newPost` and `metaWeblog.editPost`.

**Comment by aerych** [comment]
Crazy right?

**Comment by kean** [comment]
umm, so yeah
done in pcdRpT-6vS-p2
oof
