### ISSUE TITLE
[GlobalStep] Changing device’s orientation to Portrait mode when in Blog Posts’ condensed view causes a Grey square overlay over the Meatball menu button.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13854]
### Description
When viewing the list of Blog Posts in its condensed view that hides the spacing between posts and moves the “View” and “Edit” buttons to the Meatball menu, changing the device’s orientation from Landscape to Portrait mode causes a Grey square overlay to be displayed over the Meatball menu button.

### Reproduction Rate
4/4 100%

### Expected behaviour
The orientation change should not cause any graphical issues.

### Actual behaviour
A Grey square overlay is displayed over the Meatball menu button.

### Steps to reproduce the behaviour
1. Install WordPress 14.6
2. Login to a valid account.
3. Navigate to Blog Posts.
4. Choose the condensed View.
5. Change the device’s orientation to Landscape mode.
6. Change the device’s orientation to Portrait mode.
##### Tested on the following
iPhone 7+ (12.0.1)

#### Please see the attached video for more information
[iOSOrientationGrey.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4455386/iOSOrientationGrey.zip)

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Nice catch! Adding a screenshot from the video for reference:

<img width="200" alt="Screen Shot 2020-04-09 at Apr 9 5 19 23 PM" src="https://user-images.githubusercontent.com/1119271/78948650-4c263480-7a86-11ea-85ce-dc014cf6888f.png">

**Comment by kean** [comment]
Closing as obsolete (thanks to the redesign https://github.com/wordpress-mobile/WordPress-iOS/pull/21744).
