### ISSUE TITLE
[GlobalStep] While in Landscape in the “My Sites” screen, dismissing the “Edit” screen causes the Site list to clip under the header.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13858]
### Description
When viewing the “My Sites” screen in Landscape mode, entering “Edit” mode and pressing “Done” causes the Site list to be slightly shifted and consequently clip under the header.

### Reproduction Rate
4/4 100%

### Expected behaviour
There should be no graphical issues.

### Actual behaviour
The Site list is shifted out of view.

### Steps to reproduce the behaviour
1. Install WordPress 14.6
2. Login to a valid account.
3. Navigate to “My Sites”.
4. Change the device’s orientation to Landscape Mode.
5. Press “Edit”.
6. Press “Done”.
##### Tested on the following
iPhone 7+ (12.0.1)

#### Please see the attached video for more information
[iOSMySitesEditLandscape.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4457264/iOSMySitesEditLandscape.zip)

### Submitted by:
Luis Pimenta

**Comment by kean** [comment]
There is no edit mode in this screen anymore.
