### ISSUE TITLE
Reader: problematic unordered markup is showing for galleries when Link to > Media File is used

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13863]
Steps to reproduce:

1. Create a new post.
1. Add a gallery block and add several images.
1. In the block settings, set "Link to" > "Media File".
1. Publish the post.
1. View the post in the Reader or Notifications.

**Result:** there are bullet points on the gallery that shouldn't be there—unordered list markup shouldn't be showing for galleries like that!

Block Editor | Reader
--- | --- 
<img src="https://user-images.githubusercontent.com/1119271/78955436-813d8180-7a9c-11ea-9b4a-6b80ccfec2da.PNG" width="200" alt="IMG_3822"> | <img src="https://user-images.githubusercontent.com/1119271/78955431-7d116400-7a9c-11ea-81a9-4bc82e2d83e1.PNG" width="200" alt="IMG_3821">

<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.0 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

<sub>(internal reference: p4a5px-2wF-p2 h/t @elibud)</sub>

**Comment by designsimply** [comment]
cc @aerych because https://github.com/wordpress-mobile/WordPress-iOS-Shared/pull/165 (just in case it's an easy fix)

**Comment by aerych** [comment]
@designsimply Sorry, I haven't had a chance to look into this yet. If I were to guess I'd say probably not a terribly difficult fix, just a matter of determining what it is in the markup that the parser needs to account for.
