### ISSUE TITLE
Reader: too much space between sections

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13864]
There are a few areas in the Reader where we can check on block cadence and make it flow a lot more nicely. 

Steps to reproduce:

1. Create a new post.
1. Add several different types of blocks with paragraphs in between.
1. Publish the post.
1. View the post in the Reader or Notifications.

**Result:** too much space between sections and some blocks simply aren't displaying correctly, here are some examples we could look into:

- [ ] Too much space after lists.
- [ ] Too much space between headings and paragraphs.
- [ ] Button doesn't display correctly.
- [ ] Cover block with linear gradient doesn't display correctly.
- [ ] Too much space between video and video caption.
- [ ] Not enough space between caption and the following content, such as a paragraph block.
- [ ] Not enough space between caption and separator.
- [ ] Too much space between separator and the next content, such as an image block.

<img src="https://user-images.githubusercontent.com/1119271/78957404-7980db80-7aa2-11ea-892b-0a601d4b6ec4.PNG" width="150" alt="IMG_3823"> <img src="https://user-images.githubusercontent.com/1119271/78957409-7dacf900-7aa2-11ea-8ede-ca9d7a4a1d69.PNG" width="150" alt="IMG_3824"> <img src="https://user-images.githubusercontent.com/1119271/78957410-7e458f80-7aa2-11ea-9892-2cd8f7790e91.PNG" width="150" alt="IMG_3825"> <img src="https://user-images.githubusercontent.com/1119271/78957412-7ede2600-7aa2-11ea-828d-094ae7fe7ceb.PNG" width="150" alt="IMG_3826">

<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.0 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

<sub>(internal reference: p4a5px-2wF-p2 h/t @elibud)</sub>

**Comment by elibud** [comment]
cc: @yaelirub @bummytime as we'll want to tackle these fixes as part of the Reader improvements project. Thanks @designsimply .

**Comment by designsimply** [comment]
While testing the Custom HTML block today, I found that the following HTML is nice to use for testing spacing issues: https://raw.githubusercontent.com/cbracco/html5-test-page/master/index.html

More testing steps:

1. Go to https://raw.githubusercontent.com/cbracco/html5-test-page/master/index.html
1. Copy the content inside the `body` tags.
1. Create a new post in the app or on the web.
1. Add a paragraph block.
1. Add a Custom HTML block and paste the content copied in step 2.
1. Add another paragraph block.
1. Publish the post and view it in the Reader.

**Result:** scroll through the post and look for areas where the spacing looks off.

Here is one set of screenshots just showing some of the differences in the content displayed in Android Reader compared to iOS Reader:

WPAndroid 14.7-rc-3 | WPiOS 14.7.0.2 TestFlight beta
---|---
<img src="https://user-images.githubusercontent.com/1119271/80546361-a70ac780-8972-11ea-8201-937615e25ba9.png" width="200" alt="Screenshot_20200428-124655">|<img src="https://user-images.githubusercontent.com/1119271/80546406-c6a1f000-8972-11ea-9206-ed2c2bef626c.PNG" width="200" alt="IMG_3937">

<p style="clear:both;"><sup>Tested with WPAndroid 14.7-rc-3 on Pixel 3 Android 10 and WPiOS 14.7.0.2 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>
