### ISSUE TITLE
Reader: individual post fullscreen view switches to splitscreen view in landscape mode after rotating back and forth

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13872]
Steps to reproduce:

1. Start in landscape mode.
1. Go to Reader.
1. Open an individual post.
1. Observe that the post is fullscreen.
1. Rotate the device to portrait.
1. Rotate the device back to landscape.

**Result:** individual post fullscreen view switches to splitscreen view in landscape mode after rotating back and forth. ([29s](https://cloudup.com/cUZA3prTKXu))

Before rotating | After rotating
--- | ---
<img width="270" alt="Screen Shot 2020-04-10 at Apr 10 6 15 42 PM" src="https://user-images.githubusercontent.com/1119271/79030671-62e88c00-7b57-11ea-95db-2f2369ae6f3d.png"> | <img width="270" alt="Screen Shot 2020-04-10 at Apr 10 6 15 47 PM" src="https://user-images.githubusercontent.com/1119271/79030670-624ff580-7b57-11ea-86ba-0e590202ff88.png">
<p style="clear:both;"><sup>Tested with WPiOS 14.5 App Store version on iPhone 11 iOS 13.4.1.</sup></p>

**Note:** it happens on my iPhone 11 (13.4.1) doesn't happen on my iPad Mini (13.3.1).

**Comment by designsimply** [comment]
Possibly related: #13794.

**Comment by leandroalonso** [comment]
This doesn't happen anymore.
