### ISSUE TITLE
Allow adding new lines (<br>) without a keyboard in Gutenberg

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-iOS#13875]
### Expected behavior
I expected to be able to add a new line within a paragraph block. 
On a laptop or with an external keyboard, this is done by pressing "shift" and "return" together.

### Actual behavior
Instead, there is no way to add a new line, other than entering "HTML Mode" and using a `<br>`.

##### Tested on iPhone SE, iOS 13.1.2, WPiOS 14.3

Requested in #2859616-zen

**Comment by thehenrybyrd** [comment]
Related: https://github.com/wordpress-mobile/WordPress-iOS/issues/9111

**Comment by hypest** [comment]
Closing in favor of https://github.com/wordpress-mobile/gutenberg-mobile/issues/559 since that's older and with more discussion. Let me know if this needs to stay open too, thanks!
