### ISSUE TITLE
Reader: space around images doesn't update when switching between light and dark mode while viewing images on an individual post

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13873]
Steps to reproduce:

1. Go to Reader and open an individual post that contains images.
1. Switch from light to dark mode, or vice versa.
1. Check the area around images and you'll see the edges don't get switched.

**Result:** space around images doesn't update when switching between light and dark mode while viewing an individual post. ([2m28s](https://cloudup.com/cdHb4a5dfbk))

<img width="200" alt="Screen Shot 2020-04-10 at Apr 10 6 51 44 PM" src="https://user-images.githubusercontent.com/1119271/79031518-6af6fa80-7b5c-11ea-9cc8-17dd4bb61dfb.png">
<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.1 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

**Comment by leandroalonso** [comment]
After the Reader Detail refactor this issue doesn't happen anymore.
