### ISSUE TITLE
Self-hosted XML-RPC URL is not sanitized properly

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#1388]
When adding a self-hosted site I used "astralbodies.net/" as the URL - XML-RPC URL after creating is set to "http://astralbodies.net//xmlrpc.php".  Not a huge deal but may indicate other URL sanitization issues.

**Comment by hoverduck** [comment]
29Oct15 Bug Scrub

Verified this is still an issue.  Adding a host with and without the trailing slash (or https://) results in the site being listed multiple times.

But since this hasn't been touched in a year, should we close as wontfix?

**Comment by rachelmcr** [comment]
Given the comments above, I'm closing this as wontfix. If we receive significant user reports indicating that this is an issue, we can reopen.
