### ISSUE TITLE
Login: update error message for WordPress.com Business users who try to log in using the 

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13898]
Currently, it's not possible to sign in to the app using the site address sign-in flow with a WordPress.com Business site ([13870](https://github.com/wordpress-mobile/WordPress-iOS/issues/13870)). Would it be possible to either update the error message for this specific case or redirect to the email sign in flow instead?

Steps to reproduce:

1. Create a WordPress.com Business site and install at least one plugin.
1. Go to "Log" In and select the option to enter your site address.
1. Enter the site address and tap "Next".
1. Copy and paste the username and password in and tap "Next".

**Result:** the following error appears regardless of whether or not you enter the correct username and password.

> It looks like this username/password isn't associated with this site.

<img width="200" alt="Screen Shot 2020-04-10 at Apr 10 4 06 25 PM" src="https://user-images.githubusercontent.com/1119271/79026199-45aac200-7b45-11ea-9884-96f0629586ae.png">
<p style="clear:both;"><sup>Tested with WP Internal 14.6.0.20200410 MS App Center alpha on iPhone 6S iOS 13.3.1.</sup></p>

**Comment by designsimply** [comment]
Adding a quick note to say I tested with the custom domain `madefortesting347.blog` and username `user157`.

**Comment by mindgraffiti** [comment]
Ref. PbArwn-1s-p2

This issue is a good candidate for the upcoming XML-RPC error handling improvement project. `Investigate XMLRPC error assistance` in roadmap.

**Comment by ScoutHarris** [comment]
https://github.com/wordpress-mobile/WordPress-iOS/issues/13870 has been resolved, so this should no longer be an issue.
