### ISSUE TITLE
Reader detail full screen mode

### ISSUE THREAD

**Issue by isaackeyet** [wordpress-mobile/WordPress-iOS#139]
When you read a longer Reader post, the navbar doesn't hide like it used to. In fact, it's pretty broken.

1. You can kick in scroll-hide by tapping Comment or Reblog.
2. Once "activated" you can scroll fast or tap to make the navbar and toolbar hide, but only a few times. Then it starts hiding and then showing immediately after.
3. When activated, the statusbar is not really visible (we should probably do what safari and other apps do instead and simply just compress the statusbar+navbar and only hide the toolbar completely).
4. When activated, scrolling fast only works if you're at the very top and not in the middle of the content.

**Comment by aerych** [comment]
Closed in #4033
