### ISSUE TITLE
Reader: buttons block background is missing

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13921]
Steps to reproduce:

1. Create a new post.
1. Add a paragraph.
1. Add a button block.
1. Open the block settings.
1. Change the border radius.
1. Add a URL.
1. Toggle "Open in new tab" on.
1. Publish the post.
1. View the post in the Reader.

**Result:** the button background color doesn't display in the Reader at all.

Reader in app | Safari on iOS
--- | --- 
<img src="https://user-images.githubusercontent.com/1119271/79520381-e866b300-8013-11ea-8f72-f6c1b02c021c.PNG" width="200" alt="IMG_3843"> | <img src="https://user-images.githubusercontent.com/1119271/79520379-e56bc280-8013-11ea-895b-0a72a799b920.PNG" width="200" alt="IMG_3844">

<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.1 TestFlight beta on iPhone 11 iOS 13.4.1 Dark Mode.</sup></p>

**Note:** the Button Block was shipped in https://github.com/wordpress-mobile/gutenberg-mobile/pull/1866 and it will become a component of the newer Buttons Block which is being worked on in https://github.com/wordpress-mobile/gutenberg-mobile/pull/1866 — noting it because the html is subject to change and we'll also want to re-test once the Buttons Block ships.

Also reported for Android: https://github.com/wordpress-mobile/WordPress-Android/issues/11679.

**Comment by designsimply** [comment]
The buttons block was re-tested in 14.8 beta testing and it was found that buttons still aren't displayed correctly in the Reader.

**Comment by leandroalonso** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/43779
