### ISSUE TITLE
Reader: cover block backgrounds are missing and text is not formatted properly

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13920]
Steps to reproduce:

1. On the web, create a new post.
1. Add a cover block with an image background.
1. Add a cover block with a solid color background.
1. Add a cover block with a linear gradient background.
1. Add a cover block with a radial gradient background.
1. Set the height for each block to 100.
1. View the post in the Reader.
1. Compare how the post looks in the editor, preview, mobile web, and Reader.

**Result:** 

- [ ] Image background isn't displayed.
- [ ] Color backgrounds aren't displayed.
- [ ] Text size is incorrect.
- [ ] Text is not centered horizontally or vertically.
- [ ] Spacing between cover blocks should be checked after the backgrounds become visible.

Reader in app | Safari on iOS
--- | --- 
<img src="https://user-images.githubusercontent.com/1119271/79519843-45616980-8012-11ea-9fc1-8a2adbe5a15e.PNG" width="200" alt="IMG_3845"> | <img src="https://user-images.githubusercontent.com/1119271/79519836-41354c00-8012-11ea-8f9a-eb35866965f3.PNG" width="200" alt="IMG_3846">

<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.1 TestFlight beta on iPhone 11 iOS 13.4.1 Dark Mode.</sup></p>

**Comment by designsimply** [comment]
Also reported for Android: https://github.com/wordpress-mobile/WordPress-Android/issues/11674.

**Comment by designsimply** [comment]
I noticed that gradients are now showing up for button blocks in the Reader but the spacing and font color for them shows up incorrectly and background images do show up now but neither the background image nor the position of the text are correct. Note: this is after switching to Webviews in the Reader in 15.2.

Editor | Reader Webview
--- | --- 
<img src="https://user-images.githubusercontent.com/1119271/86185126-d795eb80-baf2-11ea-80c9-dbed405f2fab.png" width="200" alt="C3AC6EF5-2709-4E4D-998B-4450966869EC">|<img src="https://user-images.githubusercontent.com/1119271/86185118-d369ce00-baf2-11ea-8221-c26b701b074a.png" width="200" alt="88B9275A-0838-470F-8EC9-B1A60EB36491">

<p style="clear:both;"><sup>WPiOS 15.2.0.0 TestFlight beta on iPhone 11 iOS 13.5.1.</sup></p>

**Comment by designsimply** [comment]
I tested color-only backgrounds today as a part of 15.4 beta testing and found that gradient colors are still not displayed in the Reader and verified horizontal and vertical text alignment are still not working.

Editor|Preview|Reader
---|---|---
![IMG_4413](https://user-images.githubusercontent.com/1119271/88848939-5fc8e880-d1a6-11ea-86f3-9e8c4746db65.PNG)|![IMG_4416](https://user-images.githubusercontent.com/1119271/88848950-62c3d900-d1a6-11ea-941e-572dbcd4ae36.PNG)|![IMG_4418](https://user-images.githubusercontent.com/1119271/88848952-648d9c80-d1a6-11ea-945f-0a776e60b634.PNG)

<p style="clear:both;"><sup>Tested with WPiOS 15.4.0.0 TestFlight beta on iPhone 11 iOS 13.6.</sup></p>

**Comment by leandroalonso** [comment]
A lot of blockers were fixed as part of a task force to fix blocks.

If any block doesn't appear correctly, it probably doesn't render correctly on the web too. All the fixes done for Reader web now apply to iOS Reader, so if there's any block issue we should open an issue in https://github.com/Automattic/wp-calypso
