### ISSUE TITLE
Add tappable sites to Login epilogue

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#13933]
Ref. pauD4L-Bb-p2#comment-624

First check that it's possible to add the ability to select a site row in the My Sites table. (When the user reaches the login epilogue screen or the signup epilogue screen.) Then make the changes.

Tapping a row should dismiss the view and navigate the user to the selected site.

<img width="227" alt="Screen Shot 2020-02-24 at 4 05 47 PM" src="https://user-images.githubusercontent.com/1062444/75195580-ce010f00-571f-11ea-9568-d5afce90d500.png">

**Comment by sohan-shingade** [comment]
Is it okay if I try fixing this?

**Comment by mindgraffiti** [comment]
Hi @sohan-shingade  👋.  Of course! Contributors are always welcome. :)  We have some [helpful guidelines here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/CONTRIBUTING.md), and some notes on our [code style here](https://github.com/wordpress-mobile/WordPress-iOS/wiki/Coding-Style-Guide).
Let us know if you have any questions we can help answer!

**Comment by sohan-shingade** [comment]
Thank you so much! I am kind of confused, do the websites have their own section in the table view or are they part of the userInfoSection in the LoginEpilogueViewController?

**Comment by ScoutHarris** [comment]
Hey @sohan-shingade .

`LoginEpilogueViewController` displays `LoginEpilogueTableViewController` via a segue (you can see the structure in `LoginEpilogue.storyboard`). In `cellForRowAt`, you'll see custom rows added to the table, including User Info and sites. Hope that helps!

**Comment by sohan-shingade** [comment]
<img width="962" alt="Screen Shot 2020-06-08 at 4 28 28 PM" src="https://user-images.githubusercontent.com/55606409/84089935-34dfc680-a9a5-11ea-89cc-e3370626e0a4.png">

I am trying to replace the "section for user sites" with the section that is for the user's sites, but I can't seem to find a section that has the users sites.

**Comment by ScoutHarris** [comment]
I think I see. You might want to look at `BlogListDataSource`. `LoginEpilogueTableViewController` uses `blogDataSource.tableView`.

**Comment by sohan-shingade** [comment]
I found a solution and added the feature. However, I don't really know how to run UI and unit tests. Once I figure it out, I will send a PR.

**Comment by kean** [comment]
The login epilogue screen was removed, closing.
