### ISSUE TITLE
Reader: group block alignment and color are not displayed and to much spacing between group and nested group blocks

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13931]
Steps to reproduce:

1. Create a new post on the web.
1. Add a group block.
1. Add a heading block and center it.
1. Add a paragraph below the heading.
1. Add a group block.
1. Add a paragraph inside the nested group block.
1. Leave the nested group block (you're still in the main group block) and add a paragraph with center alignment.
1. Add another paragraph in the same group as the centered paragraph.
1. Modify the colors in the block settings.
1. Publish the post.
1. View the post in the Reader.

**Result:** alignment and color block settings aren't displayed for blocks inside the group block. The spacing should also probably be tightened up between nested group blocks. cc @mbshakti (for input, because nested group blocks may be a tricky case)

Editor | Reader in app | Mobile Web
--- | --- | ---
<img src="https://user-images.githubusercontent.com/1119271/79599454-bb151600-80a2-11ea-9f3a-9edaac89b69b.PNG" width="200" alt="IMG_3869">|<img src="https://user-images.githubusercontent.com/1119271/79599465-c0726080-80a2-11ea-82ce-92277e2225cf.PNG" width="200" alt="IMG_3867">|<img src="https://user-images.githubusercontent.com/1119271/79599485-cbc58c00-80a2-11ea-9f71-78e294f7ea00.PNG" width="200" alt="IMG_3866">
<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.1 TestFlight beta on iPhone 11 iOS 13.4.1 Dark Mode.</sup></p>

**Note:** this problem also happens with the MediaText block, which is a group block. I also noticed the stacking is reversed in the Reader vs the web, in the Reader the text is stacked below the image while on the web the text is stacked above the image—this is with the "Show media on right" option selected in the editor ([screenshot](https://user-images.githubusercontent.com/1119271/79597097-ee55a600-809e-11ea-831d-f977ac667583.PNG)), it looks like that option is not being respected in the Reader.

Reader in app | Reader in app (landscape) | Mobile Web
--- | --- | ---
<img src="https://user-images.githubusercontent.com/1119271/79596764-6079bb00-809e-11ea-9021-c2c691539dc5.PNG" width="200" alt="IMG_3853"> | <img src="https://user-images.githubusercontent.com/1119271/79596816-78e9d580-809e-11ea-93ba-833883e06347.PNG" width="200" alt="IMG_3852">|<img src="https://user-images.githubusercontent.com/1119271/79596767-61125180-809e-11ea-80da-ef58967beb6c.PNG" width="200" alt="IMG_3854">
<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.1 TestFlight beta on iPhone 11 iOS 13.4.1 Dark Mode.</sup></p>

**Aside:** content inside nested group blocks is not shown in Reader cards. I think this is okay, however, please let me know if you'd like a separate issue filed for this! cc @mbshakti 

| Reader in app | 
| --- | 
| <img src="https://user-images.githubusercontent.com/1119271/79597370-67ed9400-809f-11ea-8f7f-49396a6f0e76.PNG" width="200" alt="IMG_3849"> |

**Comment by designsimply** [comment]
Corresponding Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/11681.

**Comment by leandroalonso** [comment]
The spacing is now correct, however, we do not render all the applied colors given we want to keep Reader with a generic visual.

Plus, all the block fixes should now be added in https://github.com/Automattic/wp-calypso (which is where the CSS resides)
