### ISSUE TITLE
Reader: too much space below latest posts block and the content inside the block doesn't have proper line breaks

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13932]
Steps to reproduce:

1. Create a new post on the web.
1. Add a Latest Posts block.
1. Adjust the block settings to show 10-word excerpts.
1. Adjust the block settings to display the post date
1. Publish the post.
1. View the post in the Reader.

**Result:** dates and excerpts in the latest post block appear next to the title without any spacing between them instead of showing on the next line like they do on the web—too much space below latest posts block and the next paragraph.

Reader in app | Mobile Web
--- | ---
<img src="https://user-images.githubusercontent.com/1119271/79600126-e4827180-80a3-11ea-85ac-30a996b29785.PNG" width="200" alt="IMG_3870"> | <img src="https://user-images.githubusercontent.com/1119271/79600135-e6e4cb80-80a3-11ea-89e4-56a63cb76999.PNG" width="200" alt="IMG_3871">

<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.1 TestFlight beta on iPhone 11 iOS 13.4.1 Dark Mode.</sup></p>

**Comment by designsimply** [comment]
Corresponding Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/11682.

**Comment by leandroalonso** [comment]
Should be addressed in https://github.com/Automattic/wp-calypso/issues/43595
