### ISSUE TITLE
Reader: captioned images with alignment set show up centered in a full-width container

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13937]
Steps to reproduce:

1. Create a new post.
1. Add an image block.
1. Set the image size to thumbnail.
1. Right align the image.
1. Add a caption that is several words long.
1. Publish the post.
1. View the post in the Reader.

**Result:** image container seems to be full-width even though the thumbnail image is right-aligned.

**Note:** there's a separate issue for caption styling at https://github.com/wordpress-mobile/WordPress-iOS/issues/2310.

Reader in app | Reader in app | Chrome Android 10 | Chrome Android 10
--- | --- |--- | --- 
<img src="https://user-images.githubusercontent.com/1119271/79612610-3df59b00-80ba-11ea-9e44-227746feccce.PNG" width="200" alt="IMG_3860">|<img src="https://user-images.githubusercontent.com/1119271/79612593-3a621400-80ba-11ea-80e0-4baa0d9be38b.PNG" width="200" alt="IMG_3879">|<img src="https://user-images.githubusercontent.com/1119271/79612607-3d5d0480-80ba-11ea-87a9-8fedd7bc82ae.PNG" width="200" alt="IMG_3861">|<img src="https://user-images.githubusercontent.com/1119271/79612601-3cc46e00-80ba-11ea-95fe-40e52a7d31c3.PNG" width="200" alt="IMG_3880">

<p style="clear:both;"><sup>Tested with WPAndroid 14.6-rc-2 on Pixel 3 Android 10 Dark Theme.</sup></p>

**Comment by yaelirub** [comment]
@leandroalonso , should this be moved to Reader Post Rendering instead?

**Comment by leandroalonso** [comment]
@designsimply I've discussed this issue with @malinajirka and we reached to the conclusion that this is the intended behavior.

In smaller devices, the image now appears centered (with the caption centered too), but if you're reading on an iPad then the correct alignment will be applied (given we have a lot more space).
