### ISSUE TITLE
Reader: spacer blocks in the Reader all show the same amount of space regardless of their height setting

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13935]
Steps to reproduce:

1. Create a new post.
1. Add a paragraph block.
1. Add a 20-pixel spacer block.
1. Add another paragraph block.
1. Add a 50-pixel spacer block.
1. Add another paragraph block.
1. Add a 100-pixel spacer block.
1. Publish the post.
1. View the post in the Reader.

**Result:** spacer blocks in the Reader all show the same amount of space regardless of their height setting, it's more space than I would have expected while also ignoring the height setting.

How much space should be showing between spacer blocks—should the height setting be respected or ignored? Also see the related Android screenshots in https://github.com/wordpress-mobile/WordPress-Android/issues/11684 where the spacing is uniform and it looks like the spacers are ignored completely. cc @mbshakti 

Reader in app | Mobile Web
--- | ---
<img src="https://user-images.githubusercontent.com/1119271/79604529-8063ab80-80ab-11ea-93b9-aeaee8e22419.PNG" width="200" alt="IMG_3872">|<img src="https://user-images.githubusercontent.com/1119271/79604533-80fc4200-80ab-11ea-8bb8-efe0be0ac391.PNG" width="200" alt="IMG_3874">
<p style="clear:both;"><sup>Tested with WPiOS 14.6.0.1 TestFlight beta on iPhone 11 iOS 13.4.1 Dark Mode.</sup></p>

**Comment by leandroalonso** [comment]
We want to keep a consistency and generic experience in the Reader. For now, we won't be supporting custom spacing: https://github.com/Automattic/wp-calypso/issues/43595#issuecomment-675969533
