### ISSUE TITLE
Crash when rendering comments

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#13950]
When navigating to the list of comments for an internal p2 post, the app will crash if there are comments.

### Expected behavior
It should be possible to navigate to the list of comments for a given post

### Actual behaviour
The app crashes when rendering the list of comments.

### Steps to reproduce the behavior
1. Navigate to the Notifications tab
2. Tap a notification (for example, a notification about a new post)
3. Tap the "comments" icon at the bottom right
4. The app navigates to the list of comments, and will crash, apparently, when it is about to render the list of comments

The crash can be reproduced when initiating the navigation from the Reader.

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPhone 11 Pro Max, iOS 13.4.1, WPiOS 14.7.0.0

**Comment by frosty** [comment]
Looks like the crash is occurring in `ReaderCommentCell` `configureText()`, line 209:

```
textView.mediaHost = MediaHost(with: comment.blog, failure: { error in
```

When I recreate it here, `comment.blog` is `nil`.
