### ISSUE TITLE
Reader: there's no path to log in to leave a comment on a post if you are viewing the Reader anonymously

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13963]
### Expected behavior

I expect that tapping on a comment icon in the Reader would give me an option to leave a comment or prompt me to log in if logging in is required before I can leave a comment.

### Actual behavior

If you view the Reader after adding a self-hosted site (without logging in to WordPress.com), posts with comments enabled show a comment icon but if you tap the icon there's no way to leave a comment.

### Steps to reproduce the behavior

1. Log out.
1. Tap "Log in" and add a self-hosted site by entering a site address.
1. Go to Reader > Search and find a post that has comments enabled but no comments yet.
1. Tap the comment icon below the post.
1. Try to find a way to leave a comment.

<img src="https://user-images.githubusercontent.com/1119271/79927360-bb901280-83fc-11ea-87b8-6ae8914b5342.PNG" width="200" alt="IMG_3900"> <img src="https://user-images.githubusercontent.com/1119271/79927366-c21e8a00-83fc-11ea-80d7-e299db24e74c.PNG" width="200" alt="IMG_3899"> <img src="https://user-images.githubusercontent.com/1119271/79927369-c480e400-83fc-11ea-8300-7bbb7313e33f.PNG" width="200" alt="IMG_3901">
<p style="clear:both;"><sup>Tested with WPiOS 14.7.0.1 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

##### Tested on iPhone 11, iOS 13.4.1, WPiOS 14.7.0.1 TestFlight beta

**Comment by leandroalonso** [comment]
Given the cost of the change versus the impact, I'll close this issue for now. We can reassess it in future Reader projects.
