### ISSUE TITLE
[GlobalStep] iOS – The Publishing Options do not properly fit its panel.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13978]
### Description
When creating a Post, the Publishing options are displayed when the user clicks the “Publish” Button, the content of this menu does not accurately fit its panel causing the Publish button to appear pinned down to the bottom of the screen without any margin. There is a superfluous amount of available pagination that represents the intended margin below this button.

### Reproduction Rate
4/4 100%

### Expected behavior
The Publishing Options Panel should be slightly bigger.

### Actual behavior
The Publish button is pinned down to the bottom of the screen despite the small amount of available pagination that reveals no new content except for a thin amount of blank space below that button.

### Steps to reproduce the behavior
1. Install and launch WordPress 14.7
2. Login to a valid account.
3. Create a new Post.
4. Tap the Publish button.
5. Scroll the Publish Options Panel.
##### Tested on the following
iPhone 7+ (12.0.1)

#### Please see the attached video for more information
[iOSPublishWindow.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4521738/iOSPublishWindow.zip)

### Submitted by:
Luis Pimenta

**Comment by leandroalonso** [comment]
I wasn't able to reproduce this issue. That's how it looks on a iPhone 7 Plus:

<img src="https://user-images.githubusercontent.com/7040243/80393967-96315780-8887-11ea-9622-4b2d7937623d.png" width="300px">
