### ISSUE TITLE
Add page option goes missing after rotating while editing

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13972]
Steps to reproduce:

1. Go to My Site > Pages.
1. Add a title and some content.
1. Rotate to landscape.
1. Rotate back to portrait.
1. Tap the X at top left.
1. Save or discard the page.
1. Try to add another page immediately.

**Result:** the + to add a new page at top right goes missing if you rotate to landscape and back while editing and then use the X to leave the page. ([22s](https://cloudup.com/ctbyxCKzxoT))

<img src="https://user-images.githubusercontent.com/1119271/80048306-0c6f3c00-84cd-11ea-91d1-5c8a64b5afc8.PNG" width="200" alt="IMG_3920">
<p style="clear:both;"><sup>Tested with WPiOS 14.7.0.1 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

**Comment by ScoutHarris** [comment]
The nav bar "+" has been replaced with the FAB.
