### ISSUE TITLE
[GlobalStep] iOS – The currently selected Site can be hidden from the Sites list.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13979]
### Description
The currently selected Site can be hidden from the Sites list which is inconsistent with the behaviour the Web and  Android applications.

### Reproduction Rate
4/4 100%

### Expected behaviour
The user should not be able to hide the currently selected Site.

### Actual behaviour
All Sites can be hidden.

### Steps to reproduce the behaviour
1. Install and launch WordPress 14.7
2. Select the “Log In” option.
3. Navigate to the “My Site” tab.
4. Press the back button to navigate to “Switch Site”.
5. Press the “Edit” button.
6. Disable all toggles.
7. Press the “Done” button.
##### Tested on the following
iPhone 7+ (12.0.1)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/80088036-e04ace00-8553-11ea-88d4-fb36769ef733.jpg" />

### Submitted by:
Luis Pimenta

**Comment by kean** [comment]
This feature was removed.
