### ISSUE TITLE
Prepublishing Nudges: Stuck in publish loop after changing publish date to immediately

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#13985]
### Expected behavior

I expect that if I decide not to publish a draft post, I will be able to save my changes and exit the editor.

### Actual behavior

If I start to publish a post, change the publish date to Immediately, and then close the bottom sheet (i.e. decide not to publish now), I get stuck in a publish loop.

When I try to exit the editor, I have the options to update the post or discard my changes. If I've made changes to the draft that I want to save, I choose update — but that reopens the pre-publish nudge rather than saving the draft.

The only way to save my draft without publishing is to go to the ellipsis menu and select Save as Draft, but that's not obvious.

### Steps to reproduce the behavior

1. Go to the My site tab > Blog posts > Drafts.
2. Select a draft to open it in the editor.
3. Optional: make some changes to the post content.
4. Open the ellipsis menu and tap "Publish now."
5. Notice that the publish date is set to when I last saved the draft. Tap Publish > select Publish immediately.
6. Dismiss the bottom sheet.
7. Tap "X" to close the editor.
8. Notice the "You have unsaved changes" prompt appears. Select "Update Post" to save the changes to the draft.

Result: The pre-publishing nudge appears again.

Screencast: https://cloudup.com/cM5yyYyggH5

**Comment by rachelmcr** [comment]
The same kind of loop can occur if you change the post visibility to Private in the pre-publish nudge, since a private post has to be published (you can't save a draft with visibility set to private).

**Comment by leandroalonso** [comment]
@rachelmcr I submitted a PR to fix the schedule issue (both in the Nudges view and Post Settings). 🎉

However, changing the visibility issue is a little more tricky I guess. In the previous version, the same change (but under Post Settings) produces similar results, but instead of displaying the Prepublishing Nudges an action sheet was shown:

<img src="https://user-images.githubusercontent.com/7040243/80228768-d7c2c800-8625-11ea-9864-b1f4b0161d47.PNG" width="300px" />

Do you think we can create another issue and prioritize it for Groundskeeping?

**Comment by rachelmcr** [comment]
Thanks for the quick fix @leandroalonso!

> Do you think we can create another issue and prioritize it for Groundskeeping?

Yes, I think in this case that makes sense because it may take some additional thought around how to improve the UX for private posts. I opened https://github.com/wordpress-mobile/WordPress-iOS/issues/13995 to track that.

In the process, though, I thought of another case involving scheduled + private posts that result in unexpected published posts. I don't _think_ the fixes you did cover this case, but please feel free to close the issue if it's already fixed. Here's the issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/13996
