### ISSUE TITLE
[GlobalStep] iOS – The layout of the Tags’ Panel in the Publishing Options hides a lot of its content while in Landscape Mode.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13980]
### Description
When using Landscape Mode, creating a new Post and pressing the Publish button so the Publish Options are displayed before accessing the Tags Section causes the Tags Panel to be displayed only partially as the recommended Tags are hidden behind the Device’s Keyboard at this point. Furthermore, typing enough Tags so that the text box expands behind the Keyboard causes them to not be visible as the user cannot paginate that text box but only the Recommended Tags list.

### Reproduction Rate
4/4 100%

### Expected behaviour
It should be possible to Paginate the Tags Panel and the Tags text box so that all content can be visible in Landscape Mode.

### Actual behaviour
A Long Tag list is only partially visible and the Recommended Tags list is not visible at all when using Landscape Mode.

### Steps to reproduce the behaviour
1. Install and launch WordPress 14.7
2. Select the “Log In” option.
3. Create a new Post.
4. Click the “Publish” button.
5. Select the “Tags” option.
6. Change the Device’s Orientation to Landscape Mode.
##### Tested on the following
iPhone 7+ (12.0.1)

#### Please see the attached video for more information
[iOSPublishTagsLandscape.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4522097/iOSPublishTagsLandscape.zip)

### Submitted by:
Luis Pimenta

**Comment by leandroalonso** [comment]
We've spotted that one. However, we haven't fixed because that would require custom code for portrait or breaking the standard we defined for Bottom Sheets.

Even in Post Settings we have almost no space to show tags: 

<img src="https://user-images.githubusercontent.com/7040243/80387925-9e859480-887f-11ea-8799-cb017fc6a79d.PNG" width="600px">

We can add a code that will lock this screen in Portrait but I'm not sure if it's a good solution.

@emilylaguna @mbshakti thoughts?

**Comment by mbshakti** [comment]
I think more than a pre-publishing nudges problem, this is a problem with bottom sheets. We are really pushing the limits of bottom sheets with this project, as we previously acknowledged :) But that said, I could see this exact problem arising with a different flow which uses the bottom sheets + auto-shows the keyboard. 

One quick solution I could see for this specific case (only on landscape mode, not portrait), we: (1) don't auto-show the keyboard layout, (2) hide the "tags help readers..." copy that sites above the input box. 

That would atleast allow the user to see the tag suggestions if there are any. But I'm definitely open to other suggestions as well....

Again, we may encounter a similar problem in the future if we are using bottom sheets + auto-showing keyboard on landscape mode. 

H/u to @osullivanchris just for awareness

**Comment by leandroalonso** [comment]
Closing it for now.

If we receive users complaints about it we can come up with a solution on the Bottom Sheet level.
