### ISSUE TITLE
[GlobalStep] The Primary Site can be hidden.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13987]
### Description
The Selected Primary Site can be hidden and remains selected as Primary Site and a hidden Site can be selected as Primary Site and remains hidden.
Note that hidden sites are initially hidden when the user navigates to the Primary Site screen, but selecting the Search bar causes every Site to be revealed.

### Reproduction Rate
4/4 100%

### Expected behaviour
The Primary Site must be visible.

### Actual behaviour
The Primary Site can be hidden.

### Steps to reproduce the behaviour
1. Install and launch WordPress 14.7
2. Login to a valid account.
3. Navigate to the “My Site” tab.
4. Navigate to “Switch Site”.
5. Press “Edit”.
6. Hide a Site that is not the selected one.
7. Navigate to the “Me” tab.
8. Access “Account Settings”.
9. Select the “Primary Site” option.
10. Click the Search bar.
11. Select the hidden Site.
##### Tested on the following
iPhone 7+ (12.0.1)

#### Please see the attached video for more information
[iOSHidingPrimarySite.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4528580/iOSHidingPrimarySite.zip)

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
> Note that hidden sites are initially hidden when the user navigates to the Primary Site screen, but selecting the Search bar causes every Site to be revealed.

On this point, this looks like it's by design. I saw a note about it in https://github.com/wordpress-mobile/WordPress-iOS/pull/3879.

> Search bar should appear along w/ the list view refreshing to show all sites (hidden/unhidden)

**Comment by kean** [comment]
This feature was removed.
