### ISSUE TITLE
[GlobalStep] iOS – The “Back” and “Done” buttons of the Tags’ Panel in the Publishing Options do exactly the same.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13981]
### Description
Creating a Post and clicking the Publish button for the Publish Options to be displayed and then accessing the Tags Panel displays a “Back” button and a “Done” button. These two buttons display the same behaviour and confirm the Tag changes which is redundant. It’s expected that the “Back” button would cancel the changes made while the “Done” button would confirm them.

### Reproduction Rate
4/4 100%

### Expected behaviour
The “Back” button should cancel any made changes.

### Actual behaviour
Both the “Back” and “Done” button confirm the made changes.

### Steps to reproduce the behaviour
1. Install and launch WordPress 14.7
2. Select the “Log In” option.
3. Create a new Post.
4. Click the “Publish” button.
5. Select the “Tags” option.
6. Type anything and press the “Back” button.
##### Tested on the following
iPhone 7+ (12.0.1)

#### Please see the attached video for more information
[iOSPublishingTagsBackDone.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4522185/iOSPublishingTagsBackDone.zip)

### Submitted by:
Luis Pimenta

**Comment by leandroalonso** [comment]
Thanks for submitting this issue, Luis.

However, this behavior is intentional. I'm not sure if this can be confusing to the user, so I leave that to @mbshakti. 

Personally, I would wait before changing it — since this will affect the flow under Post Settings and I guess we never had issues there.

**Comment by mbshakti** [comment]
We added the "done" button because during the design review, one of the pieces of feedback was that folks weren't sure that tapping the "back" button meant that the tags they are inputting are going to be saved. 

So to +1 @leandroalonso, this was intentional. Let's await the future feedback here and revisit this issue later.
