### ISSUE TITLE
[GlobalStep] Blank space between Header’s menu and Notifications List when first accessing the “Notifications” tab after the Application was launched.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13988]
### Description
The first time the “Notifications” Tab is accessed after the Application is launched, a Blank space can be seen between the Tab’s Header’s menu and the Notifications List.

### Reproduction Rate
4/4 100%

### Expected behaviour
There should be no graphical issues.

### Actual behaviour
There is an erroneous blank space between the Menu at the top and the Notifications List.

### Steps to reproduce the behaviour
1. Install and launch WordPress 14.7
2. Login to a valid account.
3. Navigate to the “Notifications” tab.
##### Tested on the following
iPhone 7+ (12.0.1)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/80210045-f7a8ba80-862a-11ea-9e40-f0e23a6824ba.jpg" />

### Submitted by:
Luis Pimenta

**Comment by aerych** [comment]
I've encountered this (or something similar) recently after the rollout of the new headers.  Steps to reproduce:
- Go through the sign up flow 
- After signed up, visit the Notifications tab. 
- Note that the no results view is pushed farther down the screen than we'd expect.

**Comment by aerych** [comment]
Refs https://github.com/wordpress-mobile/WordPress-iOS/issues/14898

**Comment by salimbraksa** [comment]
Closing this issue as it is no longer reproducible.

![CleanShot 2024-03-07 at 00 30 45](https://github.com/wordpress-mobile/WordPress-iOS/assets/9609223/ed37c32a-0485-414c-a113-cc4158d56b39)
