### ISSUE TITLE
Prepublishing Nudges: customized date is ignored for previously saved drafts

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#13983]
Steps to reproduce:

1. Go to My Site > Blog Posts > +.
1. Add a title and some content.
1. Tap More > Save as Draft. 
1. Tap More > Publish Now. 
1. Change the date to something in the future.
1. Tap the "Schedule Now" button.
1. Notice the post is unexpectedly published with the current date and time. 

**Result:** customized date is ignored for previously saved drafts. ([1m15s](https://cloudup.com/cBnL0zq6OLZ))

Scheduled for May 9 on Apr 23 | Post was published immediately
--- | ---
<img src="https://user-images.githubusercontent.com/1119271/80159517-6da81580-8588-11ea-8d58-8b0fd41514c4.png" width="200" alt="scheduled-for-may-9">|<img src="https://user-images.githubusercontent.com/1119271/80159516-6d0f7f00-8588-11ea-926e-5d414ec12d47.png" width="200" alt="published-immediately">
<p style="clear:both;"><sup>Tested with WPiOS 14.7.0.1 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

**Note:** this happens when scheduling posts for the future or backdating posts to the past. It happens if you close and re-open a draft and then try to schedule it or if you use "Save as Draft" and then publish in the same session.

<p style="clear:both;"><sup>h/t @rachelmcr for reporting this in Slack. Thank you!</sup></p>

**Comment by rachelmcr** [comment]
I labelled this one critical priority because it involves unexpected publishing. I'd say this is a blocker for release.
