### ISSUE TITLE
Crash when clearing chosen tag in self hosted reader

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#13997]
### Expected behavior
I expect the Reader to have content or show empty view and to be able to filter the content by choosing a tag. I expect the app not to crash when I clear the tag

### Actual behavior
The Reader is empty, only filters are showing. Tapping filters shows an empty site list, tapping tags and choosing a tag does nothing and when clearing the tag the app crashes 

### Steps to reproduce the behavior
1. Log in to self hosted site 
2. Tap Reader
3. tap filters 
4. tap Tags
5. choose a tag
6. In the search bar, tap x to clear the tag
7. See the crash

The app crashes in line: https://github.com/wordpress-mobile/WordPress-iOS/blob/9fb2e8169a5a13c63206efc8ece44e0eb1379473/WordPress/Classes/ViewRelated/Reader/Tab%20Navigation/ReaderTabView.swift#L227

with:
```Fatal error: Index out of range:```

![20200424_112432](https://user-images.githubusercontent.com/1335657/80244689-3ab06100-861e-11ea-823e-60f23aab237e.GIF)

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 11 pro + Simulator, iOS 13.4, WPiOS Develop

**Comment by Gio2018** [comment]
Thanks for finding this @yaelirub !!

**Comment by Gio2018** [comment]
Issue addressed In PR  #13984
