### ISSUE TITLE
[GlobalStep] The option to Disconnect a Self-Hosted Jetpack Site is not present.

### ISSUE THREAD

**Issue by wptester9845** [wordpress-mobile/WordPress-iOS#13994]
### Description
After adding a Self-Hosted Jetpack Site the option to disconnect it from the current WordPress account is not present in the respective Site’s settings.

### Reproduction Rate
4/4 100%

### Expected behaviour
There should be an option to disconnect the Site from the account.

### Actual behaviour
The button to disconnect the Site from the account is not present.

### Steps to reproduce the behaviour
1. Install and launch WordPress 14.7
2. Login to a valid account.
3. Switch to a Self-Hosted Jetpack Site.
4. Navigate to the Settings.
##### Tested on the following
iPhone 7+ (12.0.1)

#### Please see the attached screenshot for more information
<img width="270" src="https://user-images.githubusercontent.com/60415523/80230346-ba9ff080-8649-11ea-96e6-a96614b0b6a6.jpg" />

### Submitted by:
Luis Pimenta

**Comment by designsimply** [comment]
Related: https://github.com/wordpress-mobile/WordPress-iOS/issues/7473.

**Comment by koke** [comment]
Related: #8641

**Comment by designsimply** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/8641.
