### ISSUE TITLE
Editor: Setting post to private makes it stuck in a publish loop

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#13995]
Posts set with private visibility are tricky because private posts can't be saved as a draft or scheduled; they have to be published immediately.

### Expected behavior

I expect clear messaging around why a private post must be published immediately, with help to change the post's visibility if I want to save/schedule it instead of publishing it now.

On the web, this is handled by immediately publishing the post when private post visibility is selected. A dialog appears to confirm the publish action:

![Screenshot 2020-04-24 17 38 39](https://user-images.githubusercontent.com/8658164/80236109-94328300-8652-11ea-851b-1644e94bdbfa.png)

If I choose "Cancel" in that dialog, the post visibility is not changed to private.

### Actual behavior

In the app, once I change the post visibility to private (in the post settings or in the pre-publish nudge introduced in 14.7), I get "stuck" in a publish loop. It isn't obvious how to save the post as a draft or why I'm being forced to publish:

When I try to exit the editor, I have the options to update the post or discard my changes. If I've made changes to the draft that I want to save, for example, I'll choose update — but that reopens the pre-publish nudge rather than saving the draft.

I have to manually change the post visibility in post settings or select "Save as Draft" in the ellipsis menu to resolve it so I can save it as a draft (which automatically reverts the post visibility change). This isn't obvious if you don't understand the restrictions on private posts.

### Steps to reproduce the behavior

These steps are to reproduce the issue in v14.7+ (with the pre-publishing nudge) although the issue also exists in previous versions:

1. Go to the My site tab > Blog posts > + to start a new post.
2. Add a title and/or post content.
3. Open the ellipsis menu and tap "Publish now."
4. Tap on "Visibility."
5. Select "Private."
6. Dismiss the bottom sheet.
7. Tap "X" to close the editor.
8. Notice the "You have unsaved changes" prompt appears. Select "Update Post" to save the changes to the draft.

Result: The pre-publishing nudge appears again.

< v14.7 (publish confirmation) | 14.7+ (pre-publish nudge)
-|-
![IMG_2384](https://user-images.githubusercontent.com/8658164/80237051-fa6bd580-8653-11ea-8f06-5acf78ecee6f.PNG)|![IMG_2385](https://user-images.githubusercontent.com/8658164/80237017-e4f6ab80-8653-11ea-8909-a7844806bb70.PNG)

##### Tested on [iPhone XS], iOS [13.4.1], WPiOS [14.5 & 14.7.0.20200421]

Originally raised in https://github.com/wordpress-mobile/WordPress-iOS/issues/13985#issuecomment-618891951.

**Comment by elibud** [comment]
@yaelirub can you/someone from your team work on this one please?

**Comment by elibud** [comment]
@yaelirub and @leandroalonso took care of fixing this one.
