### ISSUE TITLE
Improve UI of post card in the Reader

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#14005]
Update the UI of the post card in the Reader. 

Note: 
- The following design might be out-of-date. Check out `figma` to see the most current design.

<img src="https://user-images.githubusercontent.com/7040243/80415573-1caa6100-88a9-11ea-8997-7c6a332a87b5.png">

**Comment by yaelirub** [comment]
@emilylaguna , @leandroalonso can this issue be closed ?
