### ISSUE TITLE
Update UI of the empty view on the following tab

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#14006]
Update the UI of the empty view on the following tab.

Consider if we need to make any changes to the design when
- the user is logged in with a self hosted site
- the user is logged in with .com account
- the user is logged in with both self-hosted site and .com account

Note:
- The following design might be out of date. Check out figma to see the most current design.
<img width="306" alt="Screenshot 2020-04-27 at 12 12 33" src="https://user-images.githubusercontent.com/2261188/80361069-97ab5180-8880-11ea-886a-fd506baf82d5.png">

**Comment by mbshakti** [comment]
Figma link here https://www.figma.com/file/fRlSXNHB5ZFHLmXWNkMphY/2-%E2%80%94-Following-Feed-Empty-State?node-id=12%3A0
