### ISSUE TITLE
Reader: tiled galleries are not formatted as galleries and have too much spacing between things

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#14025]
Steps to reproduce:

1. On the web for a WP.com or Jetpack site, create a new post.
1. Add a paragraph.
1. Add a tiled gallery block with several images.
1. Add a few more tiled gallery blocks with various settings.
1. Add another paragraph.
1. Publish the post.
1. View the post in the Reader.

**Result:** 

- [ ] No gallery formatting, images are just stacked and full-width.
- [ ] Too much spacing between some images and between paragraphs and galleries

WPiOS Reader | iOS Safari
---|---
<img src="https://user-images.githubusercontent.com/1119271/80654943-b7867500-8a3a-11ea-8ffe-23d0218b9b57.PNG" width="200" alt="IMG_3968">|<img src="https://user-images.githubusercontent.com/1119271/80654948-bbb29280-8a3a-11ea-9c54-315ade59431d.PNG" width="200" alt="IMG_3969">

<p style="clear:both;"><sup>Tested with WPiOS 14.7.0.2 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

**Note:** it's possible this is intentional, if so please close this issue with an explanation. Thank you!

**Comment by designsimply** [comment]
Also filed for Android at https://github.com/wordpress-mobile/WordPress-Android/issues/11779.

**Comment by simison** [comment]
For most layouts, tiled gallery will need JS to calculate the layout, so it's gonna be pretty hard to get it work on mobile.

That said, little fall-back CSS will already do miracles! There are pretty canonical row/column/image semantics going on in the gallery.

**Comment by daniloercoli** [comment]
Tiled galleries are rendered stacked on my mobile devices, but aside from this aspect they work fine on my blogs. Pictures are all available, and arranging them stacked is probably better than trying to render a tiled gallery on a small screen. I'm closing this issue for now since it's quite old, but we can reopen it later if we decide the layout of the tiled gallery needs improvement.
