### ISSUE TITLE
Self hosted user reports images not getting attached to the post.

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#1402]
Here's the list of plugins:
>Akismet by Automattic
BruteProtect by Parka, LLC
Functionality Plugin for Ellie Clements by Dave Clements
Google Authenticator by Henrik Schack
Gravity Forms by rocketgenius
Gravity Forms MailChimp Add-On by rocketgenius
InfiniteWP – Client by Revmakx
Jetpack by WordPress.com by Automattic (will also delete its data)
Options Framework by Devin Price (will also delete its data)
Redirection by John Godley
Soliloquy by Thomas Griffin
Symple Shortcodes by AJ Clarke
WordPress Importer by wordpressdotorg
WordPress SEO by Joost de Valk (will also delete its data)
WP Migrate DB Pro by Delicious Brains

**Comment by hoverduck** [comment]
29Oct15 Bug Scrub -

I haven't tested with all of the plugins listed in the original issue, but in general I was able to successfully upload media.  I'm betting this is fixed, but will leave it open until the next scrub.  Maybe in the meantime somebody will have time to really try to reproduce it.

**Comment by rachelmcr** [comment]
I tested on a WordPress.com site and confirmed that the images I uploaded in a post (in the body of the post and as a featured image) were not attached to the post. Those images are listed as unattached in the media library. For WordPress.com, at least, this is still an issue.

I also tested on a self-hosted install with no plugins, running WordPress 4.4.1. Images I uploaded in the body of the post were attached as expected, but the featured image was not attached. I also enabled Akismet and Jetpack (tested with it disconnected and connected) and the images were still attached as expected.

Tested on iPhone 6, iOS 9.2, app beta v. 5.0.20161113.

**Comment by rachelmcr** [comment]
Another report from #4855:

>After the last iOS app update, it looks like photos uploaded with posts created in the iOS app do not get attached as media to the published post. They do get added to the media library, and the image is published as expected, but the media item is not connected to the post as seen in the Media item's "Uploaded to:" field (it's blank for media items uploaded from the app on my phone, but if I add it through the web interface, it's properly associated with a blog post)

**Comment by dlnorman** [comment]
I'm seeing it on self-hosted WordPress (4.4.2), with the iOS WordPress app (5.9.1). I'm running a few plugins, [documented on my site's colophon](https://darcynorman.net/about/colophon/). I believe it was working normally with iOS-posted-images added as media to blog posts, until the last iOS WordPress app update.

**Comment by rachelmcr** [comment]
Thanks! When you create those posts, do you save them as drafts first or do you publish them right away?

A couple testing notes:
- I tested with a self-hosted site (WordPress 4.4.2) with Jetpack activated. When I created a new post, added an image, and published the post immediately, the image was attached as expected. But when I created a new post, added an image, _saved the post as a draft_, and then published later, the image wasn't attached.
- I also tested with a self-hosted site (WordPress 4.4.2) without Jetpack, and in both of the above scenarios the image was attached to the post as expected.

**Comment by dlnorman** [comment]
I'm not saving as drafts (intentionally, at least - could it be auto saving as draft?). This is a quick photo blogging workflow, trying to post photos quickly. Take photo with Camera app, launch WordPress app, click "+" new post, enter title, tap in content box, tap photo icon, select photo, publish. (That's a lot of taps for a quick photoblogging workflow ;-) ) Then, photos get pushed to twitter/Facebook/Flickr automatically.

**Comment by kurzee** [comment]
Tested this one, looks this is resolved. We've have quite a bit of work on media the last couple months so likely resolved as a part of those changes.
