### ISSUE TITLE
Reader: file block is missing spacing and the download button isn't styled

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#14024]
Steps to reproduce:

1. On the web, create a new post.
1. Add a paragraph.
1. Add a file block.
1. Add another paragraph.
1. Publish the post.
1. View the post in the Reader.

**Result:** 

- [ ] No space between the filename and the download button.
- [ ] Download button is missing styling.

WPiOS Reader | WPiOS Reader | iOS Safari
---|---|---
<img src="https://user-images.githubusercontent.com/1119271/80653300-1e099400-8a37-11ea-8321-164c583c6743.PNG" width="200" alt="IMG_3965">|<img src="https://user-images.githubusercontent.com/1119271/80652720-cae31180-8a35-11ea-80fe-10d673de189f.PNG" width="200" alt="IMG_3964">|<img src="https://user-images.githubusercontent.com/1119271/80652725-cc143e80-8a35-11ea-964a-4547b2e20301.PNG" width="200" alt="IMG_3963">

<p style="clear:both;"><sup>Tested with WPiOS 14.7.0.2 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

**Comment by designsimply** [comment]
Related button block issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/13921.

**Comment by designsimply** [comment]
Also filed for Android: https://github.com/wordpress-mobile/WordPress-Android/issues/11778.

**Comment by leandroalonso** [comment]
Should be addressed in https://github.com/Automattic/wp-calypso/issues/43595
