### ISSUE TITLE
Search post pages

### ISSUE THREAD

**Issue by megimix** [wordpress-mobile/WordPress-iOS#1403]
I'm working on my proposal for GSoC 2014, I decided to take the search posts and pages idea for the iOS app.

I'm trying to investigate the API request and response for receiving the search result of posts and pages.

For now I figure that the iOS app use XML-RPC protocol to communicate with wordpress server.

From the Blog object in the iOS app it uses the API call to get the post list is "wp.getPostFormats". In the documentation I didn't find how to filter the result by search string.

I read somewhere that WP XML-RPC have can run WP_Query but i didn't understand how.

Could you refer me to information for how should I implement get posts list filtered by search string?

**Comment by sendhil** [comment]
Closing this as this is now in the app.
