### ISSUE TITLE
Changes made on the web are not being reflected in real time on the mobile app

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#14056]
From a 1-star app review by raesrod – May 1, 2020:

> I’m always trying to update and edit on the go, but for some reason, any changes I’ve made on my desktop do NOT update in real time on the mobile app. I have uninstalled, and reinstalled.

<sup>Version 14.6</sup>

**Comment by jkmassel** [comment]
This isn't something we'll be able to tackle in the foreseeable future – .org sites don't have web sockets, and we don't want to be constantly polling and potentially slow down their site.
