### ISSUE TITLE
The request was explicitly cancelled.

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#14051]
**Sentry Url**: https://sentry.io/share/issue/c9b19e7196d34a9eb75f60b70b625ac3/
**User Count**: 3667
**Count**: 10500
**First Release**: 27585
**First Seen**: 2020-04-23T11:57:22Z
**Last Seen**: 2020-05-05T09:32:38Z
**24 Hours**: 8473
**30 Days**: 10313

```
The request was explicitly cancelled.

```

**Comment by loremattei** [comment]
This is not a crash, it's an error, but it has an impressive amount of occurrences, so it's probably worth investigation.

**Comment by bummytime** [comment]
Context from @oguzkocer in Slack:

> In order to fix (remove) the request cancelled logs, we need to filter them out in 'UIImageView+SiteIcon.swift'.

Specifically, [this call](https://github.com/wordpress-mobile/WordPress-iOS/pull/13770/commits/8cb6a0cdefe14a32dc485b08d43cf6317a50f468#diff-948fdb5e390f12d935326fc45662f2e2R74).

> There are a couple different places where we report the errors, so that probably needs to be done in all of them.

Looking through the events, I'm seeing a lot of `downloadSiteIcon()` calls originating from the My Site tab. 

> Just to re-iterate from an earlier point, it's a common practice to cancel an ongoing request if a new one is created. And even though these are reported in an error callback, I don't think they should be treated as errors.

I agree with his assessment. This one line of code has been flooding Sentry with events and we should be more judicious about only sending Sentry things that are **truly** errors.
