### ISSUE TITLE
Latest Post Summary showing incorrect elapsed time since post publish

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#14072]
### Expected behavior

I expect to see on the Latest Post Summary section of site Stats the elapsed time since my latest post was published.

### Actual behavior

I see an incorrect elapsed time on the Latest Post Summary section.

### Steps to reproduce the behavior

1. Create and publish a post
2. Go to the My Site tab | $site | Stats
3. In the Latest Post Summary section, the "It's been $value hours since $post was published..." text has an incorrect $value.

I made a post on a new site and viewed site stats about 15 minutes later, there the time since post was published was shown as already _four hours ago_. Since my local timezone is UTC/GMT-04:00, it looks like the timestamp from the server is being interpreted as local time instead of UTC when calculating elapsed time, which would account for the 4 hour difference. My site is in _UTC_ (My Site tab | $site | Settings | Timezone).

The Android app is showing the correct elapsed time, and the blog list screen is also showing a correct elapsed time.

| Stats (iOS) | Blog List | Stats (Android) |
| -- | -- | -- |
| ⚠️ | ✅ | ✅ |
| <kbd><img src="https://user-images.githubusercontent.com/1898325/81220091-c0cd8f80-8fae-11ea-9844-f9351f1758ba.jpg"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/1898325/81220094-c1662600-8fae-11ea-968f-8217b9377c6c.PNG"></kbd> | <kbd><img src="https://user-images.githubusercontent.com/1898325/81220083-bdd29f00-8fae-11ea-8146-b77ba9788c7a.jpg"></kbd> |

**Comment by elibud** [comment]
@ScoutHarris do you have plans to work on this one next week or can I take it?

**Comment by ScoutHarris** [comment]
Hey @elibud . Go for it!
