### ISSUE TITLE
[GlobalStep] [iOS] After creating a post from Blog Posts, white spaces get trim to 1 from paragraph when viewed on webpage.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-iOS#14076]
**Environment:**
 iOS: iPad Air 2 v13.3.1
 
 **Steps To Reproduce:**
  1. Install and open the application.
 2. log in with valid credentials.
 3. Tap on "My site"
 4. Tap on "+" symbol to add new blog post.
 5. Tap on "Blog Post".
 6. From footer tap on "+" symbol to add paragraph.
 7. Notice a paragraph is added on the blog.
 8. Type text with multiple whitespaces inbetween the words.
 9. From the header, tap on three dots symbol->Select Preview
 10. Observe that white spaces trim to a single white space from paragraph when previewed on webpage

 **Actual Result:**
At create Blog, white spaces get trim to 1 from paragraph when viewed on webpage.
 
**Expected Result:**
At create Blog, White spaces should not be removed from paragraph when previewed on webpage

[#14076.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4594639/14076.zip)

**Comment by designsimply** [comment]
Thank you for reporting this! Whitespace is automatically collapsed in web browsers unless you use preformatted text when creating your post. In the WordPress editor, you can preserve whitespace by using the preformatted or verse blocks.
