### ISSUE TITLE
[GlobalStep] [iPad] Incorrect button format is displayed on readers tab when viewed on devices.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-iOS#14082]
Environment:
iOS:  iPad (6th Gen)-v12.4, iPad Air 2(v13.3.1)

Steps To Reproduce:
 
 1. Install and launch the application.
 2. Tap on "Log In".
 3. Log in to the app using valid credentials.
 4. Go to My site and go to Blog Posts section
 5. Go to Published tab and open a post with coloured buttons format.
 6. Note that in View it displays the formatted coloured buttons.
 7. Now go to Reader tab, (Assuming your site is in "followed sites" or else Followed Sites> Manage> Enter URL)
 8. Observe that it fails to display the post with proper coloured buttons format.

Note: Colour options present on dekstop website,hence created a post from their and viewed on app.
 
 Actual Result:
Incorrect button format is displayed on readers tab when viewed on devices.

 Expected Result:
On readers tab, button format should be displayed properly on readers tab when viewed on devices.

[#14082.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4594837/14082.zip)

**Comment by designsimply** [comment]
Screenshot from the attached video for reference:

Editor|Reader
---|---
<img width="300" alt="Screen Shot 2020-05-12 at May 12 11 36 24 PM" src="https://user-images.githubusercontent.com/1119271/81775160-7a45cc80-94a9-11ea-9162-c0cc770e6010.png">|<img width="300" alt="Screen Shot 2020-05-12 at May 12 11 36 39 PM" src="https://user-images.githubusercontent.com/1119271/81775157-77e37280-94a9-11ea-9e94-c53a0901e092.png">

**Comment by designsimply** [comment]
Thank you for the report! It is good to confirm this is still a problem for the buttons block in 14.8 beta and let's continue tracking this issue at https://github.com/wordpress-mobile/WordPress-iOS/issues/13921. 👍

**Comment by gglobalstep** [comment]
This issue is observed to be "Open" for following Environment:
Android: Samsung Galaxy S7 (v8), Samsung Galaxy Tab A (v9).
Build WPAndroid [version]: v14.9

Attachment:
[#14082.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4658236/14082.zip)
