### ISSUE TITLE
[GlobalStep] [iOS] Under "Menus" black empty box flashes for few seconds before "Nothing Found" message is prompted while adding new item.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-iOS#14080]
Environment:
iOS: iPad Air 2(v13.3.1), iPhone 11 Pro (v13.3.1)

Steps To Reproduce:
 
 1. Install and launch the application.
 2. Tap on "Log In".
 3. Log in to the app using valid credentials.
 4. Open "My site" tab.
 5. Tap on "Menus".
 6. Select or add new menu.
 7. Tap on New item and list will open.
 8. Tap on any option from the list (eg. Page,Link, Tag, Post,Product)
 9. Observe that   black empty text box is displayed for few second and then "Nothing found" message is displayed.
  
 Actual Result:
Under "Menus" black empty box flashes for few seconds before "Nothing Found" message is prompted while adding new item

 Expected Result:
Upon adding new item in Menu from "Menus" blank empty box should not display.

[#14080.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/4594795/14080.zip)

**Comment by designsimply** [comment]
Tested and confirmed that the color of the placeholder that flashes prior to showing the "Nothing found" notice for empty result sets when adding a menu item doesn't match the background and looks like a mistake. You can see it in light or dark mode, although it's a bit more prominent in dark mode.

Light Mode | Dark Mode
---|---
<img width="200" alt="Screen Shot 2020-05-12 at May 12 11 13 12 PM" src="https://user-images.githubusercontent.com/1119271/81773810-6a78b900-94a6-11ea-9d5a-4a2ae7e2c839.png">|<img width="200" alt="Screen Shot 2020-05-12 at May 12 11 11 50 PM" src="https://user-images.githubusercontent.com/1119271/81773813-6cdb1300-94a6-11ea-8541-bbe669638d82.png">

<p style="clear:both;"><sup>Tested with WPiOS 14.8.0.1 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

**Comment by designsimply** [comment]
Labeling low priority because it's a small visual glitch and not blocking menu item searches or saves.

**Comment by negna1** [comment]
As i see this issue is still active and I want to take it.

**Comment by frosty** [comment]
Looking at the code, it's intentional that this area pulses as a loading indicator. I wonder if we should replace it with a standard UIActivityIndicatorView spinner, though.

**Comment by etoledom** [comment]
I have [reviewed the PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/14312#pullrequestreview-491302873) that fixes this ticket. Let's hope @negna1 is available to check out the feedback :)

**Comment by chipsnyder** [comment]
I pinged the author of the [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/14312#pullrequestreview-491302873) to see if they'll have a chance to look at it. If not I can work on taking it over.
