### ISSUE TITLE
Unable to upload a Featured Image

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#14098]
#### Uploading

1. Tap Post Settings
2. Tap "Set Featured Image"
3. Select an image from your device
4. The image appears

#### Removing

1. Tap Post Settings
2. Tap your featured image
3. Tap "Remove"
4. The image should be removed and the option to "Set Featured Image" should appear

#### Uploading

1. Tap Post Settings
2. Tap "Set Featured Image"
3. Select an image from your device
4. An error saying "Featured Image did not load" appears

#### Removing

1. Tap Post Settings
2. Tap your featured image
3. Tap "Remove"
4. The image still there

### Steps to reproduce the behavior

See above.

**Comment by designsimply** [comment]
Tested and confirmed with 14.8-rc-2 on iPhone 11 iOS 13.4.1 except the "Featured Image did not load" error was persistent for me so I didn't ever see the option to "Remove". Despite the error, I could see the featured image appear in the Blog Posts list and in the published post on the web. ([2m6s](https://cloudup.com/cyseU3VIl53))

<img src="https://user-images.githubusercontent.com/1119271/81611921-2d72d080-9399-11ea-8f6a-7b493cb81167.PNG" width="200" alt="IMG_4019"> <img src="https://user-images.githubusercontent.com/1119271/81611700-bd644a80-9398-11ea-998b-07090d906415.PNG" width="200" alt="IMG_4018"> <img src="https://user-images.githubusercontent.com/1119271/81611704-c1906800-9398-11ea-8773-3589ee6e39b4.PNG" width="200" alt="IMG_4020">

<p style="clear:both;"><sup>Tested with WPiOS 14.8.0.1 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>
