### ISSUE TITLE
[GlobalStep] [iOS] "Greyed Out Password field " and Magic link tool tip is not displayed under account details upon completing Sign Up

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-iOS#14120]
Environment:
iPad Air 2(v13.3.1), iPad(6th Gen)-v12.4
 
Steps To Reproduce:
 1. Install and launch the application.
 2. Tap on "Sign Up for WordPress.com".
 3. Continue with the any option(Email/Google/Apple).
 4. Add your account and complete the sign up.
 5. Observe that on the Sign up page only Name and Username is displayed and Password field is missing. 
   
 Actual Result:
"Greyed Out Password field " and Magic link tool tip is not displayed under account details upon completing Sign Up
 
 Expected Result:
"Greyed Out Password field " and Magic link tool tip shouold display under account details upon completing Sign Up

![#2237](https://user-images.githubusercontent.com/41110392/81325091-81d63180-90b5-11ea-9ed9-fd3eafb8b23c.png)

**Comment by designsimply** [comment]
Tested with WPiOS 14.8.0.2 (TestFlight beta) and verified that the WordPress the "Sign up with Email" flow results in the optional password field and the magic link tip both showing up as expected.

<img src="https://user-images.githubusercontent.com/1119271/81883383-4ffc1980-9552-11ea-8f3e-8aa4db173e60.PNG" width="300" alt="IMG_0365"> <img src="https://user-images.githubusercontent.com/1119271/81883381-4ecaec80-9552-11ea-9f0a-9558141c1a64.PNG" width="300" alt="IMG_0364">

<sup>Tested with WPiOS 14.8.0.2 TestFlight beta on iPad Mini 4 (WiFi) (iPad5,1) iPadOS 13.4.1.</sup>

Good catch though! It wasn't clear in the test instruction that only the email signup flow would have that part of the design included. 👍
