### ISSUE TITLE
Proposal: Use system-defined grays for Tooltip and Snackbar components'

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/WordPress-iOS#14136]
Over on the Mobile Gutenberg project, we've been working on a [RN-based tooltip](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2216) and I noticed that the new native Tooltip components for WPiOS (and WPAndroid) use [Color Studio](https://color-studio.blog) grays, which conflicts a bit with our preference of using system-defined grays. 

Considering both WPiOS and WPAndroid are both using system-defined grays, I think we might as well change the background-color on both the Tooltip and Snackbar components to use the following colors on iOS (from the [HIG](https://developer.apple.com/design/human-interface-guidelines/ios/visual-design/color/)), inverted for each mode (light mode using a dark mode gray and vice versa):

* Light mode: Use _dark-mode values_ of `systemGray5` or `systemGray6`
* Dark mode: Use _light-mode values_ of `systemGray5` or `systemGray6`

Note: we can't exactly use _dynamic_ system colors on RN, but we can target the default system grays separately with static hex or RGB values for each platform. So if this proposal is accepted, I'll likely propose doing so on RN. // cc @geriux 

CC'ing @mattmiklic @osullivanchris @bjtitus for feedback and discussion. 😄

**Comment by bjtitus** [comment]
> conflicts a bit with our preference of using system-defined grays

I'm all for sticking to the system-defined colors where possible 👍 

Not sure if the new React Native `PlatformColor` API solves the dynamic system color problem: https://reactnative.dev/docs/next/platformcolor

**Comment by iamthomasbishop** [comment]
> Not sure if the new React Native PlatformColor API solves the dynamic system color problem

Holy moly, I did not know this existed — _mind blown_ 🥰  @geriux can we use this API? If so, we might as well just start using the same system values right away (and over the long-term, I can start using this API/model for just about _all colors_).

**Comment by geriux** [comment]
> > Not sure if the new React Native PlatformColor API solves the dynamic system color problem
> 
> Holy moly, I did not know this existed — _mind blown_ 🥰 @geriux can we use this API? If so, we might as well just start using the same system values right away (and over the long-term, I can start using this API/model for just about _all colors_).

It is a cool feature that they just added 😍 but... it'll be available in React Native version 0.63 which is still a [release candidate](https://github.com/facebook/react-native/releases/tag/v0.63.0-rc.1). We are currently updating to 0.62. So it'll take a bit until we can use that API :(

**Comment by osullivanchris** [comment]
I had no vision or preference for the color we used in the tooltip. I just wanted to re-use something that already existed. So we piggybacked on the Snackbars, taking colors etc from there.

So there was no rational for using a non-system color and I'm 100% supportive of changing to the system greys if we're doing across both components.

**Comment by iamthomasbishop** [comment]
> but... it'll be available in React Native version 0.63 which is still a release candidate.

@geriux Aw, shucks! That’s good to know then. I’ll start thinking about how we can properly shift over to using more platform colors.

> So there was no rational for using a non-system color and I'm 100% supportive of changing to the system greys if we're doing across both components.

@osullivanchris Good to know! Perhaps we can find someone else to wrangle these changes 😄. @frosty or @yaelirub do you know if anyone would be available on your teams to tackle this quick change of background-color on snackbars and tooltips (and the same change on Android)?

(@geriux for now let’s keep our colors on the RN side until we have this one lined up)

**Comment by frosty** [comment]
We can take care of this one!
