### ISSUE TITLE
ReaderPostCardCell UI Issues

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#14147]
### Expected behavior
The reader post card layout looks correct when switching between tabs

### Actual behavior
The reader post card layout breaks after switching between tabs:
- The action buttons are all overlapping each other
- If a post does not have an image, the space for the image is displayed
- The action buttons sometimes are spread out unequally or are missing items
- The space for the blog image is displayed if the blog does not have an image

#### Examples
<img width="117" alt="Screen Shot 2020-05-19 at 10 11 19 AM" src="https://user-images.githubusercontent.com/793774/82361351-983a9200-99bf-11ea-892f-9f22142e5e45.png">

<img width="404" alt="Screen Shot 2020-05-19 at 10 37 31 AM" src="https://user-images.githubusercontent.com/793774/82361349-9670ce80-99bf-11ea-94ed-ee532d8b42c3.png">
<img width="386" alt="Screen Shot 2020-05-19 at 10 58 37 AM" src="https://user-images.githubusercontent.com/793774/82361453-b4d6ca00-99bf-11ea-9261-a71f2a7b6523.png">

<img width="390" alt="Screen Shot 2020-05-19 at 10 58 59 AM" src="https://user-images.githubusercontent.com/793774/82361509-c7e99a00-99bf-11ea-9585-666bbeb8fd6b.png">

### Steps to reproduce the behavior
1. Open the Reader Tab
2. Dismiss the new reader nav message if visible
3. Tap on the Discover tab
4. Wait for the posts to load
5. Switch back to the Following tab
6. It may take a couple times of switching between tabs to reproduce the issue

<img width="30%" src="https://user-images.githubusercontent.com/793774/82361969-77bf0780-99c0-11ea-87de-f4f908e50d5c.gif">

##### Tested on [device], iOS [version], WPiOS [version]
- iPhone 11 Pro, 13.4 Simulator, 14.9
- iPhone 11 Pro, 13.4.1, 14.9

**Comment by emilylaguna** [comment]
👋@Gio2018! I noticed this issue on the 14.9 release. Could you please take a look into this?

**Comment by Gio2018** [comment]
> 👋@Gio2018! I noticed this issue on the 14.9 release. Could you please take a look into this?

Thanks for finding this @emilylaguna ! Will look into it!
