### ISSUE TITLE
Share to Simplenote: unable to complete sharing

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#14157]
### Expected behavior
When sharing to Simplenote, I should be able to actually complete the process.

### Actual behavior
When the Share view is displayed, there are no controls to actually finish sharing. In addition, there is no way to dismiss the share view, so the user is stuck.

### Steps to reproduce the behavior
- Initiate share to Simplenote. Example: on a post, tap the Share nav bar button and select Simplenote.
- When the share view appears, notice there is no way to complete the share or dismiss the view.

| ![IMG_DF4B93D0140F-1](https://user-images.githubusercontent.com/1816888/82489726-5b45cc80-9a9f-11ea-911f-3489c4d99ae3.jpeg) | ![IMG_659545F0E58C-1](https://user-images.githubusercontent.com/1816888/82489750-64369e00-9a9f-11ea-9ab7-24fa0353bdd1.jpeg) |
|--------|-------|

**Comment by rachelmcr** [comment]
I confirmed that when sharing to Simplenote from another app, the controls (Cancel/Save) appear in the top left and top right:

<img src="https://user-images.githubusercontent.com/8658164/82550641-c30b1e80-9b56-11ea-9802-96dbfbba8b08.PNG" width="300px">

When I tap in those locations while sharing from WordPress, the controls work — they just aren't visible. It sounds like this is the issue described in https://github.com/wordpress-mobile/WordPress-iOS/issues/13302?

**Comment by bummytime** [comment]
@ScoutHarris @rachelmcr Thanks for submitting this issue! The Simplenote share extension's UI is part of the Simplenote iOS project actually. So, I [filed an issue there](https://github.com/Automattic/simplenote-ios/issues/773) and will close this one.

**Comment by bummytime** [comment]
@ScoutHarris @rachelmcr FYI, this was fixed in https://github.com/Automattic/simplenote-ios/pull/774

**Comment by ScoutHarris** [comment]
Thanks @bummytime !
