### ISSUE TITLE
Plans: feature lists in the app do not match the web

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#14161]
Steps to reproduce:

1. On the web, go to https://wordpress.com/plans and view the Premium feature list.
1. In the app, go to My Site > Plans and view the Premium and Business feature lists.
1. Compare the lists to see if they are the same on the web and in the app.

**Result:** the plan feature lists in the app do not match the web. Specifically, Google Analytics is included in the Premium plan on the web but is not included in the Premium plan on the app.

Web Premium|WPiOS Premium|WPiOS Business
---|---|---
<img width="200" alt="Screen Shot 2020-05-21 at May 21 7 18 00 AM" src="https://user-images.githubusercontent.com/1119271/82563978-3a2fbb00-9b35-11ea-8678-aa846e46c0ee.png">|<img src="https://user-images.githubusercontent.com/1119271/82565108-18cfce80-9b37-11ea-8c89-fe1574537d42.PNG" width="200" alt="IMG_3647">|<img src="https://user-images.githubusercontent.com/1119271/82565112-1a00fb80-9b37-11ea-8e2c-02e8e0410aad.PNG" width="200" alt="IMG_3648">

<p style="clear:both;"><sup>Tested with WPiOS 14.9.0.1 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

Support request:

> Confused cause the Google Analytics feature was included in the Business but not in the Premium Plan.

<sup>(internal reference: p4a5px-2z5-p2 h/t @mlaetitia)</sup>

**Comment by aerych** [comment]
Closed via r208293-wpcom
