### ISSUE TITLE
[GlobalStep] [iOS] Application fails to display JetPack option on MySite "+"  menu option.

### ISSUE THREAD

**Issue by gglobalstep** [wordpress-mobile/WordPress-iOS#14173]
**Environment:**
iOS: iPhone 8 (v13.4.1), iPhone 11 Pro (v13.2.2), iPhone XS (v13.2.2).
Build [version]: v14.9

**Steps To Reproduce:**
 1. Install and launch the application.
 2. Tap on "Log In".
 3. Log in to the app using valid credentials.
 4. Go to My Site and tap on + icon beside My Site header.
 5. Observe only two options: WordPress.com and Self-hosted is visible.

**Actual Result:**
Application fails to display JetPack option on MySite "+"  menu option.

**Expected Result:**
Application should display all the three types: WordPress.com, JetPack and Self-hosted upon tapping MySite "+"  menu option.

**Attachment:**
<img src="https://user-images.githubusercontent.com/41110392/82593461-2d0bde00-9bc0-11ea-806a-1088ead0bb75.PNG" width="200" alt="#2300">

**Comment by designsimply** [comment]
Closing as invalid. Jetpack sites will appear automatically in the WordPress mobile apps when the site has the Jetpack plugin installed, active, and connected—there is no need to add a Jetpack from the My Sites screen. This is an interesting misunderstanding though! I will discuss the case with our designers.

Related help page: https://jetpack.com/support/getting-started-with-jetpack/#install-jetpack
