### ISSUE TITLE
Notifications: comment threads appear entirely italicized in like notifications if it a comment like notification is the first type of comment tapped while it is in the first position in the notifications stream after re-launching the app

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#14205]
To prepare:

1. Have an account where you have received at least one comment like notification and at least one other type of notification.
1. The first notification in the notifications stream must be a comment like notification.

To test:

1. Completely close and re-launch the app.
1. Go to Notifications.
1. Tap on a comment you made that received a comment like notification.
1. Verify the first notification at the top of the main notification stream is a comment like notification.
1. Tap on the comment snippet to view the comment thread.
1. Observe that the comment thread is entirely italicized.
1. Completely close and re-launch the app.
1. Go to Notifications.
1. Tap on any other type of notification other than a like notification.
1. Tap on a comment you made that received a comment like notification.
1. Tap on the comment snippet to view the comment thread.
1. Observe that the comment thread is not italicized.

**Result:** if a like notification is tapped first after re-launching the app, the comment thread appears in all italics. ([2m34s](https://cloudup.com/cfKwk10jjMi), [54s](https://cloudup.com/cBkinRkNUUb))

<p style="clear:both;"><sup>Tested with WP Internal 14.9.0.20200527 541ff14 MS App Center alpha on iPhone 11 iOS 13.4.1.</sup></p>

<p style="clear:both;"><sup>(internal reference: p4a5px-2zz-p2 cc @codebykat)</sup></p>

**Comment by bummytime** [comment]
While I was not able to repro this, my hunch is that [something in `WPRichContentView.formattedAttributedString()`](https://github.com/wordpress-mobile/WordPress-iOS/blob/a5339a72c8da01e2e40015eef3769c746cdf708f/WordPress/Classes/ViewRelated/Views/WPRichText/WPRichContentView.swift#L174-L197) is failing.

Ref: #6564
