### ISSUE TITLE
[iPad] Reader post links are unresponsive despite tapping many times

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#14217]
### Expected behavior
When I navigate into a post in Reader, I expect the linked content to appear in a modal view upon tapping it. 

### Actual behavior
The link will sometimes change to bold text or have a subtle color change onPress. It will not open the referenced content in a modal view. 

### Steps to reproduce the behavior
Ref. p57gV0-Pw-p2

Visit the referenced link as it contains a variety of link types. If you are lucky, the link will respond after multiple attempts (3+) to tap it.

##### Tested on iPad Pro 10.5", iOS 13.4.1, WPiOS 14.9
Also tested on iPad Pro 12.9" (4th generation), iOS 13.4.1, WPiOS 14.8

**Comment by yaelirub** [comment]
Fixed as part of Reader post rendering project. Will close when 15.2 is released
