### ISSUE TITLE
Add Zendesk plan field

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#14224]
Copying this 👇 from [the Android issue](https://github.com/wordpress-mobile/WordPress-Android/issues/12064).

---

We are currently sending the site plans as tags and these are converted to a single Plan field on the Zendesk side. When the user has more than one site, each one with different plans, the last unique plan will be selected. This is not the behavior we want. Instead, we want the Plan field to show the "highest" plan the user has. Here are the changes we need to make to accomplish that:

1. [x] Remove the plan tags [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/support/ZendeskHelper.kt#L433-L435). This is so that when we send the plan field Zendesk doesn't try to override it. Even if that wasn't an issue, when multiple plan tags are sent, there are some cases where some plans are removed, so it's just simpler to not send them.
2. [x] Add a new ticket field id [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/support/ZendeskHelper.kt#L491) which I believe is `25175963`. Please verify this value with HEs if the plan you're sending is not showing up.
3. [x] Add the "highest" plan as a custom field with the id from Step 2 [here](https://github.com/wordpress-mobile/WordPress-Android/blob/develop/WordPress/src/main/java/org/wordpress/android/support/ZendeskHelper.kt#L369-L378). You can use the `allSites` parameter in the function to figure that out. The [`shortPlanName`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/model/SiteModel.java#L92) property is localized, so it's probably best to not rely on that. Instead, we can hopefully use the [`planId`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/model/SiteModel.java#L91) property to add a hard-coded matching. If that doesn't work, we have [`FETCH_PLANS`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/action/SiteAction.java#L81) action to fetch the plan details for a site, but I suggest avoiding that because Zendesk config build is probably not a great time to do multiple fetch requests. (due to multiple sites) Instead, we might want to add a new property to `SiteModel` and set it [here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/develop/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteRestClient.java#L1024-L1035). (This is only if we can't use the `planId` property)

Note that there is a little bit of research involved in this issue. Specifically, we'll need to figure out what the "highest" plan is and that'll depend on which property we can utilize. 
- [x] Regardless, my suggestion is to first get the connection between app and Zendesk working and verify that you are able to set the plan to whatever you want through a hardcoded value. Once that's working, all we'll need to do is to find the highest plan which we can probably extract somewhere and unit test for future-proofing and possible maintenance. (in case we need to modify it)

Here are the Plan field values I can see in Zendesk:
```
Free, Blogger, Personal, Premium, Business/Professional, eCommerce, Tier 1, Tier 2, Tier 3, Tier 4, Other, Add-On
```
I think some of these will not be applicable to us, so I wouldn't worry about using all of them. I also don't know for sure if these are the values we need to send.

---

Hope these details will be useful to whoever is working on this. Please don't hesitate to ping me if you have any questions. Also please consider testing the integration very early to verify that you're setup correctly just so you don't waste time thinking something doesn't work when in fact the issue might be elsewhere. (speaking from experience :) ) Finally, please remember to use an email that is not your Zendesk agent email for your Zendesk identity. (which will be set the first time you visit Help through a dialog) If you use your Zendesk agent email, the integration will not work.

---
- [x] there seems to be an issue with the Business/Professional plan: Zendesk wants the value `business_professional`, while we are sending `Business`. To be investigated
  - there is a WP.com Automation that will assign the Business/Professional plan if there is a `Business` tag. to be determined what to do with the custom field.

**Comment by Gio2018** [comment]
Fixed in #14298
