### ISSUE TITLE
History: verse and preformatted blocks are unreadable in revision visual previews

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#14241]
Steps to reproduce:

1. Go to device Settings > Display & Brightness > Appearance > Dark.
1. Create a new post or page.
1. Add a preformatted block with some content.
1. Save changes.
1. Add a paragraph block with some content.
1. Save changes, close the post, and re-open it.
1. Add a verse block with some content.
1. Go to ellipsis menu > History and open the latest revision.
1. Go to ellipsis menu > Switch to Visual Preview.

**Result:** content using `<pre>` is not readable History visual previews in Dark Mode.

<img src="https://user-images.githubusercontent.com/1119271/83667534-cb6a4d00-a58b-11ea-9362-2bdb74306d63.PNG" width="200" alt="IMG_4204"> <img src="https://user-images.githubusercontent.com/1119271/83667691-053b5380-a58c-11ea-9fd4-e2234cb80695.PNG" width="200" alt="IMG_4252">

<p style="clear:both;"><sup>Tested with WPiOS 15.0.0.0 TestFlight beta on iPhone 11 iOS 13.4.1.</sup></p>

**Comment by elibud** [comment]
@guarani can you please look into this one?

**Comment by guarani** [comment]
> @guarani can you please look into this one?

Yes, thanks for letting me know about this issue.

**Comment by guarani** [comment]
@iamthomasbishop—on the post history Visual Preview screen, pre-based blocks such as Verse and Preformatted have a background color of rgb(243, 246, 248) in both light and dark mode.
This is the default Aztec background color for these types of blocks and this color doesn't match any of the app's Murial colors.
Can you please help me identify which color should be used for both light and dark mode?

**Comment by iamthomasbishop** [comment]
@guarani  is this rendered entirely using Aztec? If so, we can probably use system colors. Either way, let me know and I’ll be happy to provide my suggestions.

**Comment by guarani** [comment]
> @guarani is this rendered entirely using Aztec? If so, we can probably use system colors.

Yes, it's an instance of Aztec. The current color would be fine left as-is except that it doesn't have a dark mode color (leading to the bug reported in this issue). 
Is there a Muriel color that would work here, or which system color could work? Ideally something like `.neutral(.shade5)` would work, but I'm seeing that its light mode color is a it off here.

(`.neutral(.shade5)` is `muriel color gray shade5` in light mode, and `muriel color gray shade90` in dark mode.)

Using this color, the bug with dark mode is fixed, but as you can see in the screenshots below, light mode is also a bit darker in color, which looks wrong. I'm wondering if you have a suggestion about which color to use to fix this.

| | Before | After |
| -- | -- | -- |
| Light Mode | <img src="https://user-images.githubusercontent.com/1898325/84851792-38b8bc00-b029-11ea-87a6-6eca00cc7e40.png"> | <img src="https://user-images.githubusercontent.com/1898325/84851799-39e9e900-b029-11ea-8cba-0934842f1a18.png">
| Dark Mode | <img src="https://user-images.githubusercontent.com/1898325/84851796-39e9e900-b029-11ea-847f-840774b103ea.png"> | <img src="https://user-images.githubusercontent.com/1898325/84851800-3b1b1600-b029-11ea-99e9-a6657804c422.png"> |

**Comment by iamthomasbishop** [comment]
@guarani ok thanks for the clarification! Because this is fully native and Aztec (which uses mostly system colors, afaik) my vote would be to use a system gray instead of one from Color Studio (f.k.a. Muriel). Perhaps we can use `systemGray6` (which should in theory dynamically account for the system appearance setting) or a fill color such as `quaternarySystemFill` or `tertiarySystemFill`.

If that doesn't work, another alternative would be to use a semi-transparent black in light mode and semi-transparent white in dark mode, but I think the system colors should be more aligned with Aztec if that's indeed what we're using.
