### ISSUE TITLE
Editor: Can't save a draft with a past or future publish date

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#14251]
### Expected behavior

I should be able to set a post's publish date to the future or past and save it as a draft.

### Actual behavior

When I set a post's publish date to the future or past, I can't save it as a draft:

* For a new post, the "Save as Draft" option in the ellipsis menu is gone.
* If I try to exit the editor, I get the prompt "Update Post" which either **publishes the post** (if the post is backdated) or schedules it (if the post is future dated).

### Steps to reproduce the behavior

1. Create a new post.
2. Add a title and/or content.
3. Open the Post Settings.
4. Select "Publish Date" and change it to a different date.
5. Go back to the editor.
6. Tap the ellipsis menu and notice there is no option to save the post as a draft.
7. Notice the call to action is "Schedule."
8. Tap the "X" to exit the editor.
9. Tap "Update Post" to save your draft.

Result: The post is published (if you chose a publish date in the past) or scheduled (if you chose a publish date in the future), instead of saved as a draft.

##### Tested on [iPhone XS], iOS [13.4.1], WPiOS [15.0.0.20200603]

Found while testing the changes in #14249 but it exists in the current beta release, too.

**Comment by yaelirub** [comment]
This issue has been around for a while (you can find the same behavior in 14.2) 
Tackling post status issues is on our road map. I will label this and other tickets regarding post status issues as part of that future project

**Comment by negna1** [comment]
I can add "save as draft" button  , when publish date will be past or future. And also change text "Update Post" to "publishes the post"

**Comment by dcalhoun** [comment]
Posting to confirm this issue is still valid and happens for me on iPhone SE, iOS 14.4.2, WPiOS 16.9 (16.9.0.13).

**Comment by kean** [comment]
The "Publish Date" field for drafts was removed in 24.9.
