### ISSUE TITLE
Quick Start v2: "Publish a post" misplaced indicator

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#14267]
### Expected behavior
The "Publish a post" task should show an indicator on the Floating Action Button. 

### Actual behavior
It is indicating on the Reader tab due to navigation changes.

### Steps to reproduce the behavior
1. My Sites > + button > Create WordPress.com site
2. Name your site > Create > Done
3. When the fancy alert appears, choose Yes, Help Me.
4. Close the "Customize Your Site" tour guide.
5. Choose "Grow Your Audience" tour guide.
6. Choose "Publish a post" from the list.

### Screenshots
<a href="https://user-images.githubusercontent.com/1062444/84069216-d3f9c380-a98f-11ea-9a39-ff72afcbb44b.PNG"><img src="https://user-images.githubusercontent.com/1062444/84069216-d3f9c380-a98f-11ea-9a39-ff72afcbb44b.PNG" width="350" /></a>

**Comment by mindgraffiti** [comment]
I don't have enough context into this to propose new changes. I don't know what the old flow looked like, so I don't know what steps were assisting the user with this task. The closest I could find is Ref. p9xubY-mI-p2

**Comment by frosty** [comment]
It looks as though this tour will now need to highlight the create FAB, as the tab bar create button that it used to reference no longer exists. However, the tour notice is overlapping the FAB... @bjtitus do you know if there's any easy way we'd be able to make the FAB avoid notices?

**Comment by bjtitus** [comment]
> do you know if there's any easy way we'd be able to make the FAB avoid notices?

This is going to be tricky since I ended up adding the FAB and all of its constraints to the Blog Details view. Theoretically, it could be moved manually depending on the presented notice position (which is in another window) but that doesn't seem like a great solution.

I think it would be much easier to present the new tooltip by listening to the `QuickStartTourElementChangedNotification` and then calling `tourGuide.visited(.newpost)`.

Something like:

```swift
func listenForQuickStart() {
    quickStartObserver = NotificationCenter.default.addObserver(forName: .QuickStartTourElementChangedNotification, object: nil, queue: nil) { [weak self] (notification) in
        self?.didDismissTooltip = false
        self?.showCreateButton()
    }
}

private func hideNotice() {
    if let container = noticeContainerView {
        QuickStartTourGuide.find()?.visited(.newpost)
        NoticePresenter.dismiss(container: container)
    }
}
```

**Comment by frosty** [comment]
I just came here to ask if we could use the tooltip, and you beat me to it! Thanks for the advice!

**Comment by osullivanchris** [comment]
We also purposefully designed the Tooltip to match our SnackBars, so it shouldn't look out of place in this instance.
