### ISSUE TITLE
Change server address and credential if I am using wordpress Siri shortcut

### ISSUE THREAD

**Issue by thorque** [wordpress-mobile/WordPress-iOS#14308]
Hello,

I am using the Siri shortcut to post media direct to my self-hosted wordpress instance. During the initial configuration of the whole shortcut I was asked for server address, username and password. Now I need to change all the things: server address, username, password. Where can I do this? Or where can I reset the current credentials? Removing the instance out of the wordpress app itself has no effect. Re-installation has no effect, too.

Any hints?
Thorsten

**Comment by jkmassel** [comment]
Hi @thorque – when you say "removing the instance", does that refer to deleting the site out of the app entirely? Out of curiosity, can you fix this by deleting and re-creating the shortcut?

**Comment by thorque** [comment]
Hi @jkmassel,

Yes, that's what I mean with removing instance.
Fun fact: if I remove the entire app from my device there is still the wordpress shortcut. How can this be, it seems not to do with an installed app?

**Comment by jkmassel** [comment]
That has to do with the way shortcuts works - it has its own storage for parameters and such - I suspect that if you were to try to run it, it may prompt you to install the all before continuing. 

As far as I know, we aren’t able to dynamically provide shortcuts with a list of your sites at this time, which would allow for a single shared login. 

But this is something we can definitely look into further!

For an immediate solution, I’d suggest deleting and recreating the shortcut as stores your account details inside of its configuration.

**Comment by thorque** [comment]
I've already deleted all shortcuts with Wordpress inside but nothing changed. Do you know yow to remove the wordpress action itself out of the list of apps and actions?

**Comment by thorque** [comment]
Oh god...I am such a dummy. There is a small icon in the top right corner auf the shortcut action where I can setup my credentials. I am sure I touched yesterday on it, but perhaps a millimeter besides. So this problem is solved.

But another interesting thing: Should the shortcut action not be removed if I remove the Wordpress app?

**Comment by jkmassel** [comment]
>Oh god...I am such a dummy. There is a small icon in the top right corner auf the shortcut action where I can setup my credentials. I am sure I touched yesterday on it, but perhaps a millimeter besides. So this problem is solved.

I'm glad to hear it!!

>Should the shortcut action not be removed if I remove the Wordpress app?

I don't believe so, but this is a shortcuts-specific thing. Shortcuts can be saved, exported, and sent to other people, so based on this, I think you can keep shortcuts around for apps you don't have installed? If you run it, I suspect the OS will prompt you to install before continuing though.

**Comment by designsimply** [comment]
I see that you already found the answer, and I'd like to add some related links and close the issue. If either of you would like to add a separate feature request for adding Shortcut suggestions or user-configurable Shortcuts, please do so in a separate issue. Thanks!

See [Edit or customize a shortcut](https://support.apple.com/en-us/HT208309) at Apple.

Also see [Shortcuts User Guide](https://support.apple.com/guide/shortcuts/shortcuts-at-a-glance-apdf22b0444c/ios) from Apple.
