### ISSUE TITLE
Update Lottie

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#14325]
The Lottie Pod is out of date, and just updating it seems to prevent the animations from running. 

Out of curiosity, I wonder how important this is to fix, or if we should just use static images (or pre-rendered image/video?) 

Some of the animations (particularly the Jetpack spinner image) run very oddly in the production version of the app.

**Comment by crazytonyli** [comment]
Updated to the latest version in https://github.com/wordpress-mobile/WordPress-iOS/pull/22605.
