### ISSUE TITLE
Tables should stay in position after content changes

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#1433]
It happens in many places but the most common is the reader. Typical case:

- Launch the app
- Reader shows with content from yesterday
- This article looks interesting maybe I'll ta...
- Content refreshes, you're looking at a totally different post
- Scroll around to see what you were looking at

Unless a table is at the top, every cell added removed should recalculate the scroll offset so the content displayed stays where it is

**Comment by jleandroperez** [comment]
Update on this one: @aerych already took care of this glitch on the Reader, with his awesome *WPTableViewHandler* helper.

Let's flip the [same flag that does this magic](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Reader/WPTableViewHandler.h#L50) for Notifications!.
