### ISSUE TITLE
Reader iPad Card UI: Abnormal spacing between metadata and post thumbnail

### ISSUE THREAD

**Issue by mbshakti** [wordpress-mobile/WordPress-iOS#14348]
### Expected behavior
Normal spacing between metadata and post thumbnail

### Actual behavior
Large spacing between metadata and post thumbnail

### Steps to reproduce the behavior
Open app -> Go to reader
Here's where it gets tricky. I don't always see this? It seems up sometimes, and sometimes seems to be normal.

### Tested on [device], iOS [version], WPiOS [version]
iPad 11, iOS version 13.4.1, WP version 15.0

### Screenshot
Take a look at the second story here (gilly macmillan)
![IMG_0035](https://user-images.githubusercontent.com/6350997/85029873-c5a76680-b14a-11ea-8dfc-bf5291fe13b9.PNG)

Both the first and second story here seem to have this issue
![IMG_0036 2](https://user-images.githubusercontent.com/6350997/85030073-03a48a80-b14b-11ea-8c58-dba17dc351d6.PNG)

**Comment by kean** [comment]
The design has changes multiple over the previous iterations. It no longer reproduces.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
