### ISSUE TITLE
Prompt users to log in/sign up if they try to follow a blog without an account

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#1435]
Restore the follow button when logged out, and when users try to follow/like/comment content, prompt them to log in or create an account

**Comment by rachelmcr** [comment]
I checked the additional broken things:

>- Reader comment is available but doesn't work
>- Reader topics shows friend finder

In my testing (beta v. 5.8.0.20151124), these were no longer issues. However, the original enhancement idea remains to be done.
