### ISSUE TITLE
[Quick Start] Add initial "Set a site title" step

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#14362]
Since we removed choosing a site title from the site creation flow, we'd like to move it to be the first step in the Quick Start process.

**Gridicon:** `pencil`
**Title:** "Set a site title"
**Description:**  "Choose a site title that best reflects your site’s personality and topic, so your visitors know what it's all about."

**Steps**

1. "Tap **Site Title** to set a new title" (replace Site Title with the current site name, and show a spotlight on it in the site header)
2. The usual action sheet will be displayed, and a spotlight will be shown on the site title row in Site Settings, as per https://github.com/wordpress-mobile/WordPress-iOS/issues/14361. Visiting the Site title screen will check off this tour.

Editorial team, this will be shown as part of the Quick Start tour feature of the mobile apps. Each tour has a summary row like this:

<img width="417" alt="Screenshot 2020-06-22 at 14 41 33" src="https://user-images.githubusercontent.com/4780/85294491-9cfad600-b496-11ea-8a8e-5a64472ac25d.png">

And one or more steps as the user completes the tour, like this:

<img width="415" alt="Screenshot 2020-06-22 at 14 41 43" src="https://user-images.githubusercontent.com/4780/85294486-99ffe580-b496-11ea-9489-ccc74cecd8a5.png">

If you could help us with the best wording of the above title, description, and step 1 text above, that would be fab – thank you!

**Comment by michelleweber** [comment]
Ideas:

Set your site title
Give your site a name that reflects its personality and topic. First impressions count!

Set your site title
Give your site a name that reflects your brand or topic, and get new readers excited to click.

Set your site title
Choose a site title that reflects your site’s personality and topic.

(They're in my order of preference, but I think they all work!)

----------

Unrelated: could we tweak the theme step just a little bit? Seeing these all together in the screen shot, I would love to get rid of perfect/perfectly being used in back-to-back items. "Browse all our themes, and find the one that's just right for you."
