### ISSUE TITLE
New Reader: Unfollowed sites are not removed. 

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-iOS#14387]
### Expected behavior

I would expect that a site unfollowed from the browser would be removed from the app followed site list. 

### Actual behavior

The site remains in the list and when I try to unfollow it I get an error message "Could not unfollow site. You are not subscribed to the URL" and the site remains on the list. 

### Steps to reproduce the behavior

1. Log into WordPress.com in a browser and go to your reader followed site list. 
2. Select a site to unfollow. 
3. Go to the reader in the app and click the gear icon to switch to "Followed Sites". 
4. Pull down to refresh the list, the site will still display. 
5. Click on the icon to unfollow the site. 
6. For a second the site is removed, then the error message pops-up and the site returns to the list. 

Logging out of WordPress.com and back in through the app cleared the site from the list. 

##### Tested on iPhone X, iOS 13.5.1, WPiOS 15.0.1.

Reported by a user in 3074502-zen
Youtube video showing the issue listed in the ticket.

**Comment by leandroalonso** [comment]
Hi @rezzap! 

Thank you for reporting that. I was able to reproduce the issue.

While the site doesn't go away in the listing under "Followed Sites", the content doesn't appear anymore.
