### ISSUE TITLE
Media: can we show the disk quota information and max file upload size sooner when uploading media items over storage limit?

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#14397]
Steps to reproduce:

1. For a WordPress.com Simple site, go to My Site > Media.
1. Add items until you run out of space.
1. Upload a new item that exceeds the site storage limit.
1. Observe the error message that appears.
1. Tap the image.
1. Observe the error message that appears.

**Result:** I expected to see a warning about going over storage capacity sooner, but the warning that includes quota and space usage only appears after I attempt a media item upload that exceeds the site storage limit and _then_ I tap on the image. ([5m17s](https://cloudup.com/cLM8EW58yjk))

A generic error is shown after uploading an image past storage capacity (left) and a better error is shown after tapping on the failed image upload (right).

> 1 post, 1 file not uploaded

> Not enough space to upload
> 100% of 3 GB used on your site

<img src="https://user-images.githubusercontent.com/1119271/86067433-19129200-ba32-11ea-8a2d-47dc59cf2b5d.png" width="33%" alt="1-post-1-file-not-uploaded-media-library-wpios-15 1 0 3"> <img src="https://user-images.githubusercontent.com/1119271/86067477-321b4300-ba32-11ea-8b80-7c9ba7e8df96.png" width="33%" alt="1-post-1-file-not-uploaded-media-library-after-tapping-retry-wpios-15 1 0 3 png">
<p style="clear:both;"><sup>Tested with WPiOS 15.1.0.3 TestFlight beta on iPhone 11 iOS 13.5.1 on WordPress.com Free site gotravelrewards.blog logged in as testuser0313.</sup></p>

**Comment by designsimply** [comment]
I also noticed that WPAndroid shows a persistent message at the bottom of the screen when the storage limit has been reached. Can we do the same for WPiOS?

WPAndroid|WPiOS
---|---
<img src="https://user-images.githubusercontent.com/1119271/86263483-88959800-bb7e-11ea-8a04-f2bada0a4028.png" width="270" alt="100-percent-of-3-gb-used-wpandroid-15 1-rc-2">|<img src="https://user-images.githubusercontent.com/1119271/86263726-d6120500-bb7e-11ea-876a-6b47d22a9bf4.PNG" width="270" alt="IMG_4324">

<p style="clear:both;"><sup>Tested with WPiOS 15.1.0.3 TestFlight beta on iPhone 11 iOS 13.5.1 and with WPAndroid 15.1-rc-2 on Pixel 3 Android 10 on WordPress.com Free site gotravelrewards.blog logged in as testuser0313.</sup></p>

**Comment by kean** [comment]
The app now proactively displays the limit:

<img width="320" alt="Screenshot 2023-11-09 at 8 27 26 AM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/55b7a296-23b6-44ec-841f-7eb0310b479a">

Implemented in https://github.com/wordpress-mobile/WordPress-iOS/pull/22013; snipping in 23.7.
