### ISSUE TITLE
Navigation bar title color broken in v15.2 beta

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#14404]
### Description
I noticed today that the app's nav bar title text is showing up black instead of its previous white. I don't think this was an intentional change

### To Reproduce
1. Log into the WordPress for iOS app version v15.2 beta
2. Observe the nav bar title color is black instead of the expected light color

### Expected behavior
The nav bar title used to have a light (white) text color.

### Screenshots
<img width="250" src="https://user-images.githubusercontent.com/1898325/86196128-8e5c9080-bb20-11ea-88b8-5648e9c0e48f.png">

### Smartphone
 - Device: iPhone 7
 - OS: iOS 13.5.1
 - Version WPiOS 15.2

### Additional context
I'm only seeing this on iOS 13.5.1. On iOS simulators with iOS 13.5 I don't see the issue.

**Comment by yaelirub** [comment]
Thanks so much for reporting, @Guarani !

**Comment by yaelirub** [comment]
Hey @ScoutHarris , can you please take a look at this? I think this might be due to the recent changes for unified login. The title appears black after login, when relaunching the app, the title is in the right color

**Comment by designsimply** [comment]
This happened to me after testing a new signup in 15.2.0.0 TestFlight beta. The header titles got stuck in dark colors when I switched from dark mode to light mode on the device on a new account where I had never changed the in-app appearance setting on the Account > App Settings screen, so this may also have something to do with the new in-app appearance setting shipped in 15.1 (see https://github.com/wordpress-mobile/WordPress-iOS/pull/14260).

<img src="https://user-images.githubusercontent.com/1119271/86419490-8ae81700-bc90-11ea-867f-48114f0ebc54.PNG" width="33%" alt="IMG_4376">
<p style="clear:both;"><sup>Tested with WPiOS 15.2.0.0 TestFlight beta on iPhone 11 iOS 13.5.1.</sup></p>

**Comment by ScoutHarris** [comment]
Fixed with #14418 .
