### ISSUE TITLE
Editor: Media uploads fail silently when site storage is full

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#14400]
### Expected behavior

When I try to upload media to a post, but my site storage is full, I expect to see a clear error message.

### Actual behavior

When I try to upload media to a post, but my site storage is full, a progress indicator remains indefinitely on screen. I only see an error if I tap on the image/video (in which case an error appears in the Retry action sheet) or if I save the post as a draft.

Note: This only happens in Gutenberg; in the classic editor, the failed upload error appears immediately.

Failed image upload in new post|After saving post as draft
-|-
![IMG_3591](https://user-images.githubusercontent.com/8658164/86142716-669f0580-baeb-11ea-8bd9-dbe64a083d4b.PNG)|![IMG_3592](https://user-images.githubusercontent.com/8658164/86143711-ae725c80-baec-11ea-80ea-a2e70fa43d47.PNG)

### Steps to reproduce the behavior

0. On a WordPress.com Simple site, fill the media library up to the site's storage limit.
1. Start a new post.
2. Add an image block.
3. Select an image to upload.
4. Result: The image placeholder appears with a progress indicator that never changes.
5. Tap on the image block and notice an action sheet appears with details about the failed upload.
6. Save the post as a draft and notice the image placeholder/progress indicator is replaced with an error message.

**Comment by designsimply** [comment]
Also see https://github.com/wordpress-mobile/gutenberg-mobile/issues/2448 which requests that a specific error message about storage upload limits is added to media blocks. We'll keep this issue open as well since this issue relates to uploads silently failing when uploading to the block editor in the iOS app which should not happen regardless of the storage limit.

**Comment by dcalhoun** [comment]
Posting to confirm this issue is still valid and happens for me on iPhone SE, iOS 14.4.2, WPiOS 16.9 (16.9.0.13).

**Comment by eduardozulian** [comment]
Also reported on 3972642-zen but the error message was `Upload failed`. It took us some back and forth to determine that the issue was indeed the user's storage.
