### ISSUE TITLE
Feature Request: Manage media folders on the Wordpress app

### ISSUE THREAD

**Issue by peaz** [wordpress-mobile/WordPress-iOS#14415]
### Expected behaviour 
When editing the media’s details, there could be a section where I can select where to move the media form the default root folder to a sub-folder. 

This is to easily add new images to a gallery that is displaying photos from a specific folder.

### Actual behavior
Currently the only way to move media to different folders is on the web admin page.

**Comment by rachelmcr** [comment]
Do you use a plugin to organize your media into folders? This isn't a core feature of WordPress, and the app is unlikely to support it until it is built into WordPress. (There's an open WordPress ticket suggesting that feature here: https://core.trac.wordpress.org/ticket/39644)

I'll close this issue, but we can reopen it if we decide to revisit this feature for the app.
