### ISSUE TITLE
Reader: main stream placeholder and content load too slowly

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#14412]
Steps to reproduce:

1. Do a fresh install of the app or log out and back in to a different account.
1. Go to Reader.
1. Observe how long it takes for any placeholder or content to appear.

**Result:** it takes a long time for any content or placeholder to load and feels like something is broken. ([1m57s](https://cloudup.com/c8RexPkRuAS))

<img width="33%" alt="screen-shot-2020-07-02-at-jul-2-8 26 05-am" src="https://user-images.githubusercontent.com/1119271/86420294-4e69ea80-bc93-11ea-90ce-0f416a44b469.png"> <img src="https://user-images.githubusercontent.com/1119271/86420319-68a3c880-bc93-11ea-8807-83d2265e8e78.PNG" width="33%" alt="IMG_4334">
<p style="clear:both;"><sup>Tested with WPiOS 15.2.0.0 TestFlight beta on iPhone 11 iOS 13.5.1.</sup></p>

**Comment by emilylaguna** [comment]
Hey @designsimply. https://github.com/wordpress-mobile/WordPress-iOS/pull/14454 was merged to reduce the blank screen time in 15.2, but we're keeping this issue open so we can make sure it's looked at again in the future.
