### ISSUE TITLE
Bug: An unordered list is not converted correctly when switching to blocks editor

### ISSUE THREAD

**Issue by ahmet-izgi** [wordpress-mobile/WordPress-iOS#14424]
### Expected behavior
When changing the editor the list should be converted as entered.

### Actual behavior
The list has empty values between entered values

### Steps to reproduce the behavior

1. Create a new post
2. Switch to classic editor
3. Add unordered list
4. Enter a few values (3+)
5. Switch to blocks editor

##### Tested on [device], iOS [version], WPiOS [version]
iOS: iPhone 6, 12.4.7, WordPress 15.0.1

Expected | Actual
--- | ---
<img src="https://user-images.githubusercontent.com/13905159/86818541-2dd4d280-c08f-11ea-9fc7-a573283fe2ba.png" width="200"> | <img src="https://user-images.githubusercontent.com/13905159/86818553-3200f000-c08f-11ea-9185-2d3ea633daa5.png" width="200">

**Comment by rachelmcr** [comment]
Similar to https://github.com/wordpress-mobile/WordPress-iOS/issues/14426, we don't expect seamless editing when switching from classic to block editor, so I'm going to close this issue as a wontfix.
