### ISSUE TITLE
Feature Request: Search posts with categories

### ISSUE THREAD

**Issue by ahmet-izgi** [wordpress-mobile/WordPress-iOS#14430]
### Expected behavior
I expect to see categories on the post list and able to search for posts with categories.

### Actual behavior
Categories are not visible to the user on search or lists.

Same as wordpress-mobile/WordPress-Android#12364

**Comment by rachelmcr** [comment]
Similar to https://github.com/wordpress-mobile/WordPress-iOS/issues/14429, searching by category isn't currently supported but we could consider something similar to the wp-admin web experience where you can select/filter by category. If we work on this, it would also be a good time to implement broader category management as outlined in https://github.com/wordpress-mobile/WordPress-iOS/issues/11115.

**Comment by kean** [comment]
Implemented in 23.7.
