### ISSUE TITLE
Can't add title and editor looks blank in RTL

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#14477]
### Expected behavior
I expect to see place holders for "Add title" and "start writing".
I expect to be able to add a title 

### Actual behavior
I can't adda title and there are no place holders for the title and content so it's hard to know where to tap to start writing.

### Steps to reproduce the behavior
1. Have your device on RTL language 
2. Create a new post
3. See no placeholders and not being able to add title 

![20200715_115954](https://user-images.githubusercontent.com/1335657/87586706-cbcf2b00-c695-11ea-95a2-9a2249dd1886.GIF)

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 11 pro, iOS 13.5.1. WPiOS 15.3

**Comment by yaelirub** [comment]
I wonder if this is only an issue in Hebrew or generally in RTL languages cc: @rachelmcr

**Comment by rachelmcr** [comment]
Ah, good catch! I see the same when I set the app to Arabic. I also noticed that I don't see a cursor on screen even when the paragraph block has focus. If I type, it enters the text there, and if I delete all the text I see the placeholder flash on screen for a split second, but that's it.

**Comment by elibud** [comment]
@hypest can we please make sure this is taken care of ASAP? Thanks

**Comment by etoledom** [comment]
At some point this was working properly. I think we are not testing RTL enough after important UI changes.

**Comment by hypest** [comment]
Thanks for self-assigning @etoledom !
