### ISSUE TITLE
Media Asset requests should be cancelled when unneeded

### ISSUE THREAD

**Issue by bjtitus** [wordpress-mobile/WordPress-iOS#14528]
### Expected behavior

Media asset requests should be cancelled when they are no longer needed and restarted when the content is about to become visible on screen.

### Actual behavior

Image requests in the Media Picker pile up and cause extremely long load times when scrolling to the bottom of a list.

### Steps to reproduce the behavior

1. Open a site with a lot of media
2. Go to the Media section in Blog Details
3. Scroll quickly down the list
4. Requests will pile up (if you're tracking with a proxy, you should see a LARGE number of requests in flight)

### Description

The `Media` type has a `cancelImageRequest` method which is currently unimplemented by some of of the types that adopt it.

Most importantly, `WPMediaAsset` does not implement this method, causing requests to pile up when scrolling far down the Media Library collection view.

https://github.com/wordpress-mobile/WordPress-iOS/blob/c0ba5e5a4cf0d532a5b11a0f0ae87d37eb434f76/WordPress/Classes/Categories/Media%2BWPMediaAsset.m#L99-L102

This is probably part of #14495 but not the entire issue so I thought it made sense to create this separate one.

**Comment by kean** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/21470; targeting 23.7.
