### ISSUE TITLE
Reader: Media & Text block settings for "Crop image to fill entire column" and "Show image on right" are not working

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#14540]
Steps to reproduce:

1. Create a new post.
1. Add a Media & Text block.
1. Tap "Add image or video".
1. Tap "Choose from Free Photo Library".
1. Search for, select, and insert an image.
1. Tapp "Show image on right" button.
1. Tap the cog icon to open block settings.
1. Turn on the "Crop image to fill entire column" option. 
1. Publish the post.
1. View the post in the Reader.

**Result:** Reader doesn't show the correct order of media and text when the "Show image on right" setting is selected (the text should be stacked above the image on small screens in that case) and a portrait oriented image is not cropped as it should be when the the "Crop image to fill entire column" setting is selected.

"Show image on right" setting|"Crop image to fill entire column" setting|Preview|Reader
---|---|---|---
![IMG_4421](https://user-images.githubusercontent.com/1119271/88847757-ba614500-d1a4-11ea-81ec-af334de39265.PNG)|![IMG_4420](https://user-images.githubusercontent.com/1119271/88847762-bf25f900-d1a4-11ea-8d54-e0b25ef53e55.PNG)|![IMG_4399](https://user-images.githubusercontent.com/1119271/88847876-eb417a00-d1a4-11ea-90d7-6b2e95ed8db7.PNG)|![IMG_4404](https://user-images.githubusercontent.com/1119271/88847903-f1cff180-d1a4-11ea-8eb3-2f4dd58227e3.PNG)

<p style="clear:both;"><sup>Tested with WPiOS 15.4.0.0 TestFlight beta on iPhone 11 iOS 13.6.</sup></p>

**Comment by leandroalonso** [comment]
@designsimply I tried fixing these styles in the Reader web but it's not that simple: just like the iOS app the Reader Web also strips the `style` HTML tags, which prevents this block from appearing correctly in some occasions.

We need a fix in Calypso side and only then we can work on fixing it in iOS, more context here: https://github.com/Automattic/wp-calypso/issues/45524

Specifically about that:

> Reader doesn't show the correct order of media and text when the "Show image on right"

In the original post (https://made4testing0318.blog/2020/07/29/media-text-block/) I'm seeing the text after the image, so I'm not sure this is something that needs to be fixed?

<img src="https://user-images.githubusercontent.com/7040243/92637764-b1898600-f2af-11ea-9c57-715aba238be5.jpeg" width="300">

**Comment by leandroalonso** [comment]
I'm going ahead and closing this issue given that fixing it opens a rabbit hole.
