### ISSUE TITLE
Adding to the Reader P2 Follow/Unfollow comments capability

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-iOS#14574]
### Background

We already massively use P2 blogs internally in a8c to enforce teams project collaboration and we are going to launch the P2 Product [p7DVsv-8N3-p2] pretty soon. 

In a P2 web page we allow a user to Follow/Unfollow a stream of comments to a post by the `Follow` button available at the bottom of a post itself.

<p align="center">
  <img width="300" src=https://user-images.githubusercontent.com/47797566/89401055-05370b80-d715-11ea-8bcf-5bf2b49d831a.png>
</p>

The effect of Following a post comments stream is that the user gets notified by emails of new comments to that post.

### Task

With the above in mind we would like to add the capability in the app to Follow/Unfollow a P2 post comments stream from the Reader (will add some mocks related to this soon)

### Relevant endpoints

- [Subscribe to a post comments stream](https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/posts/%24post/subscribers/new/)  
- [Unsubscribe from a post comments stream](https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/posts/%24post/subscribers/mine/delete/)
- [Get subscription state](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/posts/%24post/subscribers/mine/)

NOTE: the new P2 Product blogs are marked as `"is_wpforteams_site": true,` in the site options response

<p align="center">
  <img width="300" src=https://user-images.githubusercontent.com/47797566/89405144-606bfc80-d71b-11ea-804d-d6b915d7100b.png>
</p>

as of current understanding this does not apply to older a8c internal P2s. In case we cannot find a flag that marks an old P2 site as being a P2 we could eventually evaluate to assume that the blogs that are in the reader Automattic Tab are P2s (note those P2s are only available to Automatticians).

<p align="center">
  <img width="300" src=https://user-images.githubusercontent.com/47797566/89405504-f7d14f80-d71b-11ea-8acc-41e8390b6a10.png>
</p>

cc @leandroalonso

**Comment by designsimply** [comment]
Want.

**Comment by momo-ozawa** [comment]
@designsimply Thanks for adding labels to the subtasks! 😄
