### ISSUE TITLE
Posts appear duplicated on post list screen

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#14572]
### Expected behavior

After publishing a post and navigating to the post list screen (under published tab), there should be only **one** instance of the recently published post there in the list.

### Screen recording

<kbd><img width="250" src="https://user-images.githubusercontent.com/1898325/89352462-2bf83200-d682-11ea-9a0d-d7c786868d2d.gif"></kbd>

### Actual behavior

After publishing a post and navigating to the post list screen (under published tab), there are duplicate posts, i.e. **two** instances of the recently published post there in the list. If the user pulls-to-refresh the post list, the duplicate post disappears and the screen contains the expected list of posts.
This bug does not occur if the user waits for the post to be published remotely before navigating to the post list screen. The easiest way to reproduce this bug is to start on the site screen and tap the floating action button (FAB) to create a new post. 
There is no evidence that posts are duplicated remotely.

### Steps to reproduce the behavior
1. Navigate to the site screen
2. Tap the create button (the floating action button) and select blog post
4. Add any content and tap Publish followed by Publish Now
5. Immediately tap the Posts button to show the post list screen
6. Notice that the newly added post appears twice in the post list

** The issue appears as early as WPiOS 14.7 (possibly earlier)

**Comment by designsimply** [comment]
@guarani https://github.com/wordpress-mobile/WordPress-iOS/issues/12800 is very similar except mentions offline editing, do you think the issues are the same?

**Comment by guarani** [comment]
I think you're right @designsimply, I'd overlooked that issue due to the emphasis on offline posting.

I'm going to go ahead and close this, but leave a comment on the other issue to clarify that it also happens when the device is offline.

Closing as duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/12800.

**Comment by guarani** [comment]
I'm reopening as suggested here: https://github.com/wordpress-mobile/WordPress-iOS/issues/12800#issuecomment-671333615

**Comment by reginabally** [comment]
Another report in 3829199-zd-woothemes with screenshots attached in the ticket. According to one of the screenshots, the duplicate posts have the "Upload failed" status.

Device: iPhone 7 (iPhone9,3)
iOS: 14.4
App version: 16.7.1

**Comment by dcalhoun** [comment]
Recreated this issue when publishing a Story post.

* **Device:** iPhone SE
* **OS:** iOS 15.0
* **App version:** 18.4

<details><summary>Screen recording</summary>

https://user-images.githubusercontent.com/438664/136050385-57745751-67ac-48b1-af48-b6abd79b9a64.MP4

</details>

**Comment by mkevins** [comment]
I can also confirm that I observed this after publishing a story post:

* Device: iPhone 11
* OS: iOS 14.8.1
* App version: 19.3

**Comment by kean** [comment]
Is going to be addressed by https://github.com/wordpress-mobile/WordPress-iOS/pull/23152
