### ISSUE TITLE
Update Reader Card to display an expandable list of tags for the posts on the Discover feed

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#14570]
Parent Issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/14395

<img width="436" alt="Screen Shot 2020-08-04 at 10 33 14 AM" src="https://user-images.githubusercontent.com/793774/89306484-cd509b00-d624-11ea-91e3-84ea88cd3ee8.png">

### Goal
- Display a single row of chips for the tags for the post
- If the number of tags will overflow out of the cell then display an overflow chip `X+`
- When tapped the chips will expand to multiple rows to display the remaining tags
- Track `reader_chips_more_toggled when the user taps the more/hide button
### Designs
- [Figma](https://www.figma.com/file/BL53gDs6URD0yRUmGRCbhr/%F0%9F%93%90-Discover-Postcard-UI-(Specs)?node-id=492%3A805)

**Comment by leandroalonso** [comment]
@emilylaguna Could you please track `reader_chips_more_tapped` when the user taps "X+" to expand the topics list?

**Comment by emilylaguna** [comment]
Is there an event to track if the user collapses?

**Comment by leandroalonso** [comment]
Perhaps we can rename the event to `reader_chips_more_toggled` and add a property `action: expand|collapse`? cc @yaelirub @mbshakti

**Comment by yaelirub** [comment]
I think that we can do with just `reader_chips_more_toggled` (no need for expand, collapse) . That's at least what I'd be interested in looking at.

**Comment by mbshakti** [comment]
+1 to @yaelirub's comment.

Would we also be able to look at if the user tapped on any of these topics (to go to the topic page) or are we already tracking that?
