### ISSUE TITLE
Follow Button UI Design Feedback 

### ISSUE THREAD

**Issue by mbshakti** [wordpress-mobile/WordPress-iOS#14612]
**Feedback on font style for follow/following button:**

I have been playing around with the blog headers and noticed that the text hierarchy seems a bit off, I think it's because the follow button feels too big. Because of this, I'd like to suggest that we revisit the font-style, and reduce the prominence by using the "callout" text style instead of "headline". 

![light mode](https://user-images.githubusercontent.com/6350997/89818150-4ebd9700-db17-11ea-83d7-ad586d1dbf60.png)

**Feedback on the "following" button in dark mode:**

- For the button border, can we use separator opaque?
- Can remove the bolding of font? (only when "following" instead of "follow")
- Can we make the background of the button transparent instead of black? 
- Can we use the "Grey 2 light" fill color for the icon?

![dark mode](https://user-images.githubusercontent.com/6350997/89818163-52511e00-db17-11ea-9f41-177e8097fbc1.png)

Thank you!

**Comment by yaelirub** [comment]
Hey @mbshakti ,
We can make all the changes

>Can we use the "Grey 2 light" fill color for the icon?

Do you want the  color of the icon to remain the same as the text and also, what is gray 2 light?

**Comment by mbshakti** [comment]
We just discussed on slack -- but by gray 2 I meant systemGray2. Sorry for confusion. 

Also, on a different note: in the issue description, I said to use `separator opaque` for the _following_ button in darkmode. Just a clarification that, we'd use `separator opaque` for the button border on light mode as well.
