### ISSUE TITLE
Site header has too much spacing inside

### ISSUE THREAD

**Issue by mbshakti** [wordpress-mobile/WordPress-iOS#14617]
### Expected behavior
I'm not sure if this assumption is correct but if the site bio doesn't exist, the site header has too much additional spacing inside. Haven't been able to reproduce this visual bug when there's a site bio. Description of actual/expected behavior:

<img width="1087" alt="Screen Shot 2020-08-11 at 2 49 40 PM" src="https://user-images.githubusercontent.com/6350997/89936775-2189eb00-dbe2-11ea-9978-b420750dd5bc.png">

##### Tested on [device], iOS [version], WPiOS [version]
iPhone Xs, iOS 13.6

**Comment by yaelirub** [comment]
Hey @mbshakti,
In the example you shared, the site description is actually not empty, its a space " " (probably overlook by the site owner) 
If you look at a site that really doesn't have a description, like Eric's site, it looks like the expected:
I did adjust the spacing from 20 to 16 in case of an empty description though here : https://github.com/wordpress-mobile/WordPress-iOS/pull/14622

**Comment by yaelirub** [comment]
Closing this issue as other issues are handled in #14622
