### ISSUE TITLE
My Site: editing a long Site Title is difficult with the small amount of space given in the editing field

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#14628]
Steps to reproduce:

1. Go to My Site.
1. Tap on the site title in the header to edit it.
1. Add a very long site title.
1. Try to scroll back to the words in the beginning of the title and edit them.

**Result:** it's very difficult to scroll back to the beginning of the site title while editing it. The cursor jumps to the end and the title is often saved unexpected in the middle of editing before the Save button is tapped. ([1m43](https://cloudup.com/cgc7ZLQbnXy))

<img src="https://user-images.githubusercontent.com/1119271/89983685-3cd21600-dc35-11ea-82ab-89837f137ef3.PNG" width="270" alt="IMG_4485">

<p style="clear:both;"><sup>Tested with WPiOS 15.5.0.0 TestFlight beta on iPhone 11 iOS 13.6.</sup></p>

**Comment by designsimply** [comment]
Note: I also tested the Tagline field in My Site > Settings and didn't have the same difficulty with the cursor jumping to the to end or the unexpected saves if I tapped outside the edit field on the screen. Still, it would be nice to have more space to edit that field in the app (unless it's discouraged to put a long tagline in which case it's less important).

**Comment by jkmassel** [comment]
This is working as intended – the title just shouldn't be that long.
