### ISSUE TITLE
Single site install & auto-push oddities

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#1463]
If there is only a single site on the device, we currently push the site when tapping on Me.  This lets a user manage the posts/pages/etc with one less tap.  The side-effect of this, however, is that Settings & Add a Site is now hidden.  If a user taps "< Me" to go back to the top, it pushes back to the Site.

Maybe figure out a way to merge the main screen inside of the blog screen when a single site exists.  This is up for debate, of course.

**Comment by rachelmcr** [comment]
It looks like this is no longer an issue. I added a single site to the app, and the Me tab is accessible and usable. The My Sites tab defaults to opening the single site, but I can tap on Back to get the site list and add a site.

Closing as works for me.
