### ISSUE TITLE
UI Feedback on Site Header

### ISSUE THREAD

**Issue by mbshakti** [wordpress-mobile/WordPress-iOS#14634]
Two requests/UI feedback:
<img width="962" alt="Screen Shot 2020-08-12 at 3 22 42 PM" src="https://user-images.githubusercontent.com/6350997/90058398-b1e23180-dcaf-11ea-8bbf-078d678683d7.png">

- Instead of having the site name on the app tab bar, can we just say "site" instead? We are doing the same thing on Android, so that we are not repeating the site name twice, in a single view. 

- Can we ensure that the spacing between the site name & site URL is the same as the spacing between the follow button and follow count? In the specs, I had 4dp for both. The spacing between site name & site URL seems apt. The spacing b/w the follow button and follow count seems a bit tight.

**Comment by yaelirub** [comment]
>Instead of having the site name on the app tab bar, can we just say "site" instead? We are doing the same thing on Android, so that we are not repeating the site name twice, in a single view.

Sure. Can do in the next release. 

>Can we ensure that the spacing between the site name & site URL is the same as the spacing between the follow button and follow count? In the specs, I had 4dp for both. The spacing between site name & site URL seems apt. The spacing b/w the follow button and follow count seems a bit tight.

So in code and  in the debugger they are actually both 4px:
<img width="530" alt="Screen Shot 2020-08-12 at 1 46 55 PM" src="https://user-images.githubusercontent.com/1335657/90066643-ddaaea80-dca2-11ea-848c-2157e2dd1ad7.png">

I updated the spacing to 8px between to count and the button 

<img width="439" alt="Screen Shot 2020-08-12 at 2 02 06 PM" src="https://user-images.githubusercontent.com/1335657/90067748-69714680-dca4-11ea-99eb-92a2f255c5d8.png">

**Comment by mbshakti** [comment]
8 looks good, thanks!
