### ISSUE TITLE
Reader: Sites filter shows unending loading animation if logged in to self-hosted site only

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#14643]
### Expected behavior

When I'm only logged in to a self-hosted site (not logged in to WordPress.com), I expect the Reader Sites filter (Reader > Following tab > Filter > Sites) to be hidden or show a prompt to log in to a WordPress.com account.

### Actual behavior

The Sites filter shows a loading animation forever:

<img src="https://user-images.githubusercontent.com/8658164/90161132-9bf56f00-dd8a-11ea-8cad-7d6c3ae75b1d.PNG" width="300px">

### Steps to reproduce the behavior

1. Log out of WordPress.com if you are already logged in.
2. Log in to a self-hosted site.
3. Go to the Reader tab.
4. In the "Following" Reader section, select "Filter" to open the filter bottom sheet.
5. Notice the Sites list shows a loading animation that never ends.

##### Tested on [iPhone XS], iOS [13.6], WPiOS [15.5.0.0 TestFlight beta]

cc @yaelirub

**Comment by rachelmcr** [comment]
It looks like this was also mentioned in https://github.com/wordpress-mobile/WordPress-iOS/pull/14037 with a planned design:

> Note: the The empty sites screen in the 'Filter Sheet' for self hosted login is not there yet, you would see an indefinite ghost for now. Here is the final design for it

<img src="https://user-images.githubusercontent.com/34376330/80762778-d18b8a80-8b02-11ea-8383-d7ca83d2a35c.png" width="300px">

**Comment by daniloercoli** [comment]
We can close this issue since we have empty states that redirect you to log in to WordPress.com.
