### ISSUE TITLE
Unable to deselect images uploaded using the free photo library 

### ISSUE THREAD

**Issue by megsfulton** [wordpress-mobile/WordPress-iOS#14646]
### Expected behavior
Each new instance of the free photo library picker should be reset with no images selected. 

### Actual behavior
After uploading a set of images using the free photo library, the free photo library picker keeps the images from the previous set selected with no way to deselect them. 

### Steps to reproduce the behavior
1) Open media library, tap + to add media
2) Select "Free Photo Library"
3) Search and select media to upload, upload media
4) After media is uploaded, select + to add more media
5) Select "Free Photo Library" 
6) The previously uploaded images are shown in the preview option and the other action is to add the previously uploaded media with no way to deselect or reset it 

Here's a video of the behavior: https://photos.app.goo.gl/rChC2gpz6QCVB8vVA

**Comment by kduncanwelke** [comment]
I'm going to look into this one. 👍🏻
