### ISSUE TITLE
Me: Adding a new site should scroll to it after adding

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#1466]
When adding a new site to the device, the table view should scroll to that row (ensuring it's visible at least) and possibly even pulse the row.  This only really helps in cases where the device has at least a near screen full of sites already.

**Comment by kurzee** [comment]
@frosty perhaps you might take a peak at this one? This old request might go along nicely with the My Sites split-view hitting `6.7`.
