### ISSUE TITLE
Editor: Leaving editor open in background for a long time turns it into an invisible overlay

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#14674]
### Expected behavior

I should be able to leave the editor open while the app is backgrounded, and when I open the app I can use the editor as usual.

### Actual behavior

When you leave the editor open with the app in the background for a long time, the editor becomes an invisible overlay over the rest of the app. (Originally reported by @megsfulton; see the original report at p4a5px-2C1-p2 for a video showing the behavior.)

### Steps to reproduce the behavior

1. Have a post / page open in the editor with unpublished changes
2. Background the WP app for a period of time, do other things / put the device to sleep
3. Open the app back up and there’s a stack of screens with only app bar of the top screen visible.

##### Reproduced on iPhone XS, iOS 13.6, WPiOS 15.5 TestFlight beta

cc @yaelirub

**Comment by ceyhun** [comment]
I was able to reproduce on iPhone 6s simulator, iOS 13.6, release/15.5 branch

### Steps to reproduce:

1. Start the app from Xcode
1. Go to My Site -> **Pages**
1. Press + to create new
1. Background app using the Home button
1. Stop the debugger in Xcode
1. Launch the app again using Xcode
1. State restoration process is initiated and the invisible editor is shown

<img width="300" src="https://user-images.githubusercontent.com/1845482/90818950-93bfa580-e32f-11ea-9b51-9ebab83b07f1.png">



### Notes

- The app works fine when you do the same but for **Posts**.
- You can reproduce the same issue with **Pages** when the editor is open from Floating Action Button 
 to create a `Site Page` as well.

Seems to me that the state restoration for an editor that is editing a **Page** is not implemented.

When they are launched initially, the modals' presentation styles and the navigation controllers used to present them seem to also be different between **Post** and **Page** editors.

Post List | Page List
-- | -- 
<img width="400" alt="post-list" src="https://user-images.githubusercontent.com/1845482/90819651-87881800-e330-11ea-8a18-056929c3fb41.png"> | <img width="400" alt="page-list" src="https://user-images.githubusercontent.com/1845482/90819637-835bfa80-e330-11ea-9603-ee4997a6dd86.png">

Post Editor | Page Editor
-- | -- 
<img width="400" alt="post-editor" src="https://user-images.githubusercontent.com/1845482/90819827-c28a4b80-e330-11ea-89b7-0719cd5b1f88.png"> | <img width="400" alt="page-editor" src="https://user-images.githubusercontent.com/1845482/90819846-c6b66900-e330-11ea-8489-110daa24343c.png">
