### ISSUE TITLE
Bug: Warning about a tableView performing cell layout before its added to the view hierarchy.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#14689]
When restoring state to the post list screen the following warning is logged to the console: 

> 2020-08-19 21:27:25.307107-0500 WordPress[75669:1495127] [TableView] Warning once only: UITableView was told to layout its visible cells and other contents without being in the view hierarchy (the table view or one of its superviews has not been added to a window). This may cause bugs by forcing views inside the table view to load and perform layout without accurate information (e.g. table view bounds, trait collection, layout margins, safe area insets, etc), and will also cause unnecessary performance overhead due to extra layout passes. Make a symbolic breakpoint at UITableViewAlertForLayoutOutsideViewHierarchy to catch this in the debugger and see what caused this to occur, so you can avoid this action altogether if possible, or defer it until the table view has been added to a window. Table view: <UITableView: 0x7fa72f01d200; frame = (0 0; 375 557); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x7fa72e63e7a0>; layer = <CALayer: 0x7fa72e63a320>; contentOffset: {0, 0}; contentSize: {375, 106}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <UITableViewController: 0x7fa6ee45e570>>

It seems likely that during state restoration, somewhere tableView.reloadData is being called before a tableView is added to the view hierarchy.  It's not immediately clear if this is the post list's tableView or something else.  The error does not appear when restoring state to the site details screen, or the list of sites.  Nothing seems obviously broken but it's something we should probably address.

### Steps to reproduce the behavior
- Browse to a site's post list. 
- Background the app. 
- If you're in the simulator cancel the debugger at this point. If you're on a device you'll need to wait for the OS to terminate the app (do not force close). You can also restart your device.
- Launch the app again and look closely at what is logged to the console to find the warning.

**Comment by bjtitus** [comment]
Not sure if it’s exactly the same, but I was able to reproduce the first one just by going into the blog posts list. It seems to be happening in `PostListViewController` in the `showCompactOrDefault` method call in `isCompact’s` `didSet`. I think before reloading data or sections in the table views in `PostListViewController` we should check that they have been added to the window. They aren’t added to the view hierarchy until after `viewDidLoad`.
