### ISSUE TITLE
Connecting an existing site to Jetpack is buggy

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#1468]
When a pre-existing site on the device gets the Jetpack plugin installed and activated, the app doesn't perform as expected.  

1. Add a self-hosted site that does not have the Jetpack plugin installed.  This may have to be a fresh site because I believe blog options is not necessarily rewritten when the Jetpack plugin is removed.
2. Visit Stats on the site and notice the recommendation to install the Jetpack plugin.
3. Go through the process of installing the plugin and then activate it.
4. Tap Back to go back to stats - expectation is stats should be viewable.  Result is actually being asked for the username & password of Jetpack credentials.
5. Tap back to go back to the site and then tap Stats again.  Now the credentials are filled in and user can tap save.

Not sure how to solve this but it's very jarring for the user.

**Comment by koke** [comment]
I tried this on `develop`, and on step 4, when you go back to the Jetpack screen it refreshes on appear, so after a second or so it turned into this

![ios simulator screen shot 01 jun 2015 12 10 31](https://cloud.githubusercontent.com/assets/8739/7910713/5d70843a-0857-11e5-94c3-7b881ade95fd.png)

Which isn't perfect, but much better than the original flow.

I'm tempted to `wontfix` this. We could capture traffic from the web view to detect when the user logs in to wp.com and grab the username/password, but that sounds like a lot of work and a complex feature for something that's (probably) rarely used.

I'd rather wait until we have a way (WP-API?) to natively install and connect Jetpack.

**Comment by rachelmcr** [comment]
I agree with `wontfix`ing this issue, given that the app now detects the username and the user only has to fill in the password. It isn't ideal, but the ideal really seems like it would be to natively install and connect Jetpack rather than spend a lot of time/effort to improve the flow as it is now.

Closing as `wontfix`.
