### ISSUE TITLE
Unknown File Type Error for HEIC images on WordPress.com Business plan sites

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-iOS#14680]
### Expected behavior
I would expect that I could upload images (live or still) from my iPhone to my media library without needing to convert them. 

### Actual behavior
On a Business plan sites on WordPress.com (atomic), live photos from the iPhone media library get an error 'unknown file type' and cannot be uploaded or the posts published. 

### Steps to reproduce the behavior
1. Go to My Sites and select a WordPress.com business plan site with plugins installed to edit in the app.
2. Go to Blog Posts to create a new post or edit an existing one and use the image block or gallery block.
3. Select Choose from my device. 
4. Choose a 'live photo' (HEIC) from your albums and click 'Add New'.
5. The image will try to upload until you get an error 'failed to insert media. Please tap for options.
6. Options come up with Media Options, File type uknown' and retry or dismiss. 

The post can't be published 
![24fa887f-4286-434c-bbb0-283653806734](https://user-images.githubusercontent.com/10325627/90623239-20724280-e20e-11ea-982a-88ccf4b18042.jpg)

I tried using Safari browser on the same device, same site and using the same image and was able to do so from the browser. 

##### Tested on iPhone X, iOS 13.6, WPiOS 15.3

Internal link: p1HpG7-9XE-p2

**Comment by rezzap** [comment]
Reported in 3238635-zen with logs.

**Comment by bummytime** [comment]
Closing. Fixed in #14686 and #14691.
