### ISSUE TITLE
Reader: Paragraph alignment is off

### ISSUE THREAD

**Issue by davemart-in** [wordpress-mobile/WordPress-iOS#14707]
### Expected behavior
Center and right aligned content to show up in the iOS reader.

### Actual behavior
All text was left aligned.

### Steps to reproduce the behavior
Here's what I posted:

<img width="803" alt="Image 2020-08-21 at 11 27 01 AM" src="https://user-images.githubusercontent.com/5634774/90908094-e8036d80-e3a1-11ea-8764-f0439d6fe137.png">

Here's what I saw in the iOS reader:

![IMG_1514](https://user-images.githubusercontent.com/5634774/90908171-06696900-e3a2-11ea-9032-62b435b68536.PNG)

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 7+ - 13.5.1 - 15.3

**Comment by leandroalonso** [comment]
The reader doesn't apply all the styles that a user defines. We did that in order to keep the consumable in Reader a little bit more generic.

Plus, this needs to be addressed in Calypso styles, not in the mobile code.

I'm closing the issue, we can always reassess if needed.
