### ISSUE TITLE
Reader: WordPress embed blocks appear cropped

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#14708]
Refs: https://github.com/Automattic/wp-calypso/issues/45105

When viewing a post that contains Gutenberg WordPress embed blocks in the iOS reader, the content can be cropped.

#### Steps to reproduce
1. Create a post on a test site and add some Gutenberg WordPress embed blocks. Link the blocks to WordPress posts that will generate preview cards.
2. View the post in the WPiOS reader.
3. Compare the post in the reader vs the post on the site. Notice that the bottom of the card is cropped.

Depending on the card, this might look okay, or it might end up cropping the site logo beneath the card image. In any event the border around the card is cropped.

My expectation is the full card would be shown.

![IMG_1736](https://user-images.githubusercontent.com/1435271/90908591-30b72880-e39a-11ea-9d84-9b0b66d77832.PNG)

**Comment by leandroalonso** [comment]
Needs to be fixed in https://github.com/Automattic/wp-calypso/issues/45105
