### ISSUE TITLE
Reader: Jetpack slideshow block displays as bulleted image list

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-iOS#14701]
Slideshow blocks are being displayed as a list of images with bullet points in the reader. This likely requires a similar fix to https://github.com/wordpress-mobile/WordPress-iOS/issues/10206, at least to remove the bullets.

![wpios-reader-slideshow-bullet-list](https://user-images.githubusercontent.com/9613966/90840853-1a0ed280-e396-11ea-8fed-b778102aa2d1.png)

(For screenshots with a bit more context see the Calypso and Android issues below.)

This is happening in the Calypso reader, Android, and e-mail notifications as well.

Calypso issue: https://github.com/Automattic/wp-calypso/issues/45085
Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/12738

### Expected behavior

Possibly the slideshow in gallery format, or at least no bullets.

### Steps to reproduce the behavior

1. Create a new post with a Slideshow block
2. View that post in the reader
3. Observe that the images show up as a bulleted list

**Comment by leandroalonso** [comment]
Needs to be fixed in Calypso.
