### ISSUE TITLE
Reader: Lastest Posts block doesn't appear when inserted in a comment

### ISSUE THREAD

**Issue by cpapazoglou** [wordpress-mobile/WordPress-iOS#14706]
### Expected behavior
Expected to at least see the latest posts block .

### Actual behavior
Latest posts block is not visible at all.

### Steps to reproduce the behavior
1. Boot a site which has Gutenberg enabled for comments (eg a P2)
2. Add a comment containing `latest-posts` block
3. View the comment in the Reader of your iOS device

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPhone XR, 13.6.1

**Comment by leandroalonso** [comment]
Given that comments use the `WPRichContentView` we won't be tackling these right now and we'll keep a centralized issue for comments issues: https://github.com/wordpress-mobile/WordPress-iOS/issues/14870
