### ISSUE TITLE
Reader: Pay with PayPal Block, PayPal button does not render

### ISSUE THREAD

**Issue by belcherj** [wordpress-mobile/WordPress-iOS#14705]
### Expected behavior

When using the Pay with PayPal block I should see the PayPal button in the reader

### Actual behavior

I do not see the PayPal button

### Steps to reproduce the behavior

1. Starting at URL: https://wordpress.com/read/feeds/77116051/posts/2871659129
2. Observe that PayPal button does not appear

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 7, 13.6, 15.3

**Comment by leandroalonso** [comment]
Needs to be fixed in Calypso/backend.

Given this is not part of the scope of the Reader mobile I'm closing this issue.
