### ISSUE TITLE
Facebook Embed block in comments does not appear

### ISSUE THREAD

**Issue by belcherj** [wordpress-mobile/WordPress-iOS#14710]
### Expected behavior

Facebook Embed block in comments should appear

### Actual behavior

Facebook Embed block does not appear

### Steps to reproduce the behavior

1. Use Facebook embed block in a comment
2. View comment in app
3. Observe it does not appear

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 7, 13.6, 15.3

**Comment by leandroalonso** [comment]
Given that comments use the `WPRichContentView` we won't be tackling these right now and we'll keep a centralized issue for comments issues: https://github.com/wordpress-mobile/WordPress-iOS/issues/14870
