### ISSUE TITLE
Notifications: Youtube Blocks in Comments aren't processed

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#14716]
### Expected behavior
Comment Notifications containing Youtube Blocks should display a video player.

### Actual behavior
Raw text is displayed!

**NOTE:**
Mentions in post **do work**. This issue is for **comment Notifications!**

### Steps to reproduce the behavior
1. Add a new comment
2. Mention **User B**
3. Insert a Youtube Block

As a result, whenever **User B** receives the notification, there won't be a Youtube player.

**Comment by ScoutHarris** [comment]
Linking to https://github.com/wordpress-mobile/WordPress-iOS/issues/14870, the master issue for Comment block issues.
