### ISSUE TITLE
Notifications : Button block is not rendering correctly in comments.

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-iOS#14717]
### Expected behavior
The button block will be rendered with the respective border or background based on the behavior that's added during it's creation. 

### Actual behavior
Only the text and link (if configured) are shown. The button's style is not rendered.
<kbd><img src="https://user-images.githubusercontent.com/1509205/90922868-4df7f100-e3b2-11ea-8875-391b260a2a00.PNG" width="320"></kbd>

### Steps to reproduce the behavior
1. Utilize the bock editor to create a button block as a response to a comment or post.
2. See the behavior.

**Comment by ScoutHarris** [comment]
Confirmed still an issue in 17.0.

**Comment by ScoutHarris** [comment]
Linking to https://github.com/wordpress-mobile/WordPress-iOS/issues/14870, the master issue for Comment block issues.
