### ISSUE TITLE
Instagram embed not rendering correctly in Reader comment

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#14719]
### Expected behavior

An Instagram embed in a post **comment** should be rendered correctly (i.e. the Instagram post should be visible in the comment).

### Actual behavior

The Instagram embed shows the text "View this post on Instagram" in the center of the screen with significant white space all around.

This works correctly when viewing an Instagram embed in a _post_ in Reader, it's broken when the embed is in a _comment_ in Reader.

| Reader Post ✅ | Reader Comment ❌ |
| -- | -- |
| <img alt="Screenshot showing Instagram embed working correctly in Reader post" src="https://user-images.githubusercontent.com/1898325/90925984-2e67c500-e3c0-11ea-9581-46173e7219e4.PNG" width="300" /> | <img alt="Screenshot showing Instagram embed not rendering in Reader comments" src="https://user-images.githubusercontent.com/1898325/90924800-1bec8c00-e3be-11ea-8195-a072b764274b.PNG" width="300" /> |

### Steps to reproduce the behavior

1. On the web, log into a WordPress site that has Gutenberg enabled in comments (e.g. create a site on http://wp.com/p2)
2. Reply to any post or comment, and add the Instagram block (embed any Instagram post)
3. Click Reply to send the comment
4. Log into the WPiOS app using the same account
5. Go to Reader, and find the comment (you can filter by the site in question)
6. Notice:
  a. the comment renders as mostly whitespace, with a "View this post on Instagram" instead of the post's photo
  b. there is a dashed border along the left edge of the screen where the post is 
  c. the Instagram post's text has lost most of its formatting (new lines, blank lines, etc)

**Comment by leandroalonso** [comment]
Given that comments use the `WPRichContentView` we won't be tackling these right now and we'll keep a centralized issue for comments issues: https://github.com/wordpress-mobile/WordPress-iOS/issues/14870
