### ISSUE TITLE
Comments: Gallery block not rendering correctly

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#14724]
### Expected behavior

The Gallery block on comments should render correctly.

### Actual behavior

On Site->Comments it doesn't render at all/there's no indication there's a gallery.

![IMG_5C822360BB9F-1](https://user-images.githubusercontent.com/5558824/90928818-f8314200-e3cd-11ea-9fb5-419b879eab3b.jpeg)

When navigating to all comments it renders as a list of images.
![IMG_736EBF2A00FF-1](https://user-images.githubusercontent.com/5558824/90928387-282c1580-e3cd-11ea-972d-b17f9c1ef15b.jpeg)

**Comment by ScoutHarris** [comment]
Linking to https://github.com/wordpress-mobile/WordPress-iOS/issues/14870, the master issue for Comment block issues.
