### ISSUE TITLE
Instagram embed not rendering correctly in notification mention

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#14722]
### Expected behavior

When viewed via the Notifications tab in WPiOS, a comment containing an Instagram embed should be rendered correctly (i.e. the Instagram post should be visible in the comment). Note: it should be possible to see the post's photo, since it renders fine in Reader posts, see https://github.com/wordpress-mobile/WordPress-iOS/issues/14719#issue-683765173.

### Actual behavior

The Instagram embed shows the text "View this post on Instagram" in the center of the screen with significant white space all around (similar to to https://github.com/wordpress-mobile/WordPress-iOS/issues/14719, but without the dashed left border).

| <img alt="Screenshot showing Instagram embed rendering incorrectly in a WPiOS Notification comment" src="https://user-images.githubusercontent.com/1898325/90927017-3c1e4a00-e3c2-11ea-8069-198a9ff7e66e.PNG" width="300" /> |
| -- |

### Steps to reproduce the behavior

1. On the web, log into a WordPress site that has Gutenberg enabled in comments (e.g. create a site on http://wp.com/p2)
2. Add another WordPress user, granting the Administrator role (other roles may work)
3. Still on the same site, create a reply (comment) to a post, @-mentioning the newly added user
4. Add an Instagram embed to that same reply
5. Send the reply
6. From the WPiOS app, log in as the newly added Administrator
7. In the Notifications tab, locate the notification for the reply that @-mentioned the user
8. Open the comment, and notice:
  a. the comment renders as mostly whitespace, with a "View this post on Instagram" instead of the post's photo
  b. the post's text has lost most of its formatting (new lines, blank lines, etc)

**Comment by ScoutHarris** [comment]
Linking to https://github.com/wordpress-mobile/WordPress-iOS/issues/14870, the master issue for Comment block issues.
