### ISSUE TITLE
Comments : Media & Text - text alignment does not work.

### ISSUE THREAD

**Issue by jd-alexander** [wordpress-mobile/WordPress-iOS#14729]
### Expected behavior
That the text will be right-aligned if configured as such.

### Actual behavior
The text is not right-aligned.

<kbd><img src="https://user-images.githubusercontent.com/1509205/90940383-29147580-e3d4-11ea-8f25-7dc4462e9155.PNG" width="320"></kbd>

### Steps to reproduce the behavior
1. Make a Media & Text block within a comment and right-align the text. 
2. Notice that the right align does not take effect.

**Comment by leandroalonso** [comment]
Given that comments use the `WPRichContentView` we won't be tackling these right now and we'll keep a centralized issue for comments issues: https://github.com/wordpress-mobile/WordPress-iOS/issues/14870
