### ISSUE TITLE
Classic Block in comments not rendered properly

### ISSUE THREAD

**Issue by AmandaRiu** [wordpress-mobile/WordPress-iOS#14733]
### Expected behavior
Classic block would render bullet and numbered lists properly, text would align as specified, text color formatting would be applied.

### Actual behavior
The bulleted and numbered lists both have extra lines added to the list after nested items, text color formatting is ignored and text indent/justification is ignored. 

### Steps to reproduce the behavior
1. Add a comment using the classic block using the source code below)
2. Open comment from notification
3. Notice rendering issues.

### Source used in Comment

```
<p>This is a classic block snippet. <strong>This sentence in bold. <em>This sentence in </em></strong><em>italics. </em></p>
<ul>
<li>This is bullet 1</li>
<li>bullet 2
<ul>
<li>nested bullet</li>
</ul>
</li>
<li>bullet 3</li>
</ul>
<ol>
<li>one</li>
<li>two</li>
<li>three
<ol>
<li>nested one</li>
<li>nested two</li>
</ol>
</li>
<li>four</li>
</ol>
<blockquote>
<p>A beautiful quote format</p>
</blockquote>
<p>Regular indent</p>
<p style="padding-left: 40px;">Indented further</p>
<p style="text-align: center;">centered sentence</p>
<p style="text-align: right;">Right justified</p>
<p><del>Strikethrough text</del></p>
<hr />
<p><span style="color: #0000ff;">Using a different color (blue)</span></p>
<p><a href="http://www.google.com">hyperlink</a></p>
```

### Screenshots

This is what the comment looks like on the web:

![Screen Shot 2020-08-22 at 5 31 25 PM](https://user-images.githubusercontent.com/5810477/90966179-609b2480-e49d-11ea-9a45-d56a82b79638.png)

Here's how it's rendered in iOS (scrolled across two screenshots)

1 | 2
-- | --
![IMG_5D58A45D13EB-1](https://user-images.githubusercontent.com/5810477/90966166-38abc100-e49d-11ea-97d0-3af34e1303b8.jpeg)|![IMG_A8AE150979B7-1](https://user-images.githubusercontent.com/5810477/90966164-36e1fd80-e49d-11ea-81db-e0c47bea9ad2.jpeg)

##### Tested on [device], iOS [version], WPiOS [version]
- iPad Pro (12.9-inch) (3rd generation) [13.6]

**Comment by leandroalonso** [comment]
Given that comments use the `WPRichContentView` we won't be tackling these right now and we'll keep a centralized issue for comments issues: https://github.com/wordpress-mobile/WordPress-iOS/issues/14870
