### ISSUE TITLE
Comments: Twitter embeds don't show tweet content

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-iOS#14730]
When opening a comment containing a twitter embed, the embed is just shown as a link:

![wpios-comment-twitter-embed](https://user-images.githubusercontent.com/9613966/90942470-e80e7680-e450-11ea-85b8-45d6a040b3f9.jpg)

### Expected behavior

Would have expected a render of the embed content as a quote, for example here's the same comment on WPAndroid:

![wpandroid-comment-twitter-embed](https://user-images.githubusercontent.com/9613966/90942471-e9d83a00-e450-11ea-86de-0f5c68a67ded.png)

### Steps to reproduce the behavior

1. Create a comment containing a twitter embed
2. View that content in the app (for example, by switching to that site and opening the Comments screen)

**Comment by ScoutHarris** [comment]
Linking to https://github.com/wordpress-mobile/WordPress-iOS/issues/14870, the master issue for Comment block issues.
