### ISSUE TITLE
UL&S: Bug in password challenge screen

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#14747]
I'm seeing the email, and sometimes the gravatar image going away when entering an incorrect password in the password challenge screen.  I've also managed to get the App to crash once while doing this.

### Preconditions:

- Make sure your Google account is disconnected from your WP.com account.
- Make sure your WP.com account has a password set.

### Steps:

1. Start the app, and make sure you're logged out
2. Log in with Google
3. Make it to the password challenge screen
4. Enter any wrong password
5. See the email, and sometimes the gravatar go away

### Extra notes:

When I crashed the app I combined the above, with sending the App to background and back to foreground.  I entered an incorrect password a few times in the process.

## Video:

This video shows the issue, although for some reason the recording isn't showing when I input the wrong password.  The issue can still be seen.

https://cloudup.com/cBcUrE2QMk5

**Comment by mindgraffiti** [comment]
Closed via #14752
