### ISSUE TITLE
Reader Improvements Phase 2 Design Feedback

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#14745]
An issue to track the items for design feedback for Reader Improvements Phase 2

**Comment by mbshakti** [comment]
Hide button on postcard topic chips: Can we remove the fill color for the hide button? The reason being that right now the hide button seems like a topic called "hide". To make it visually distinct from the rest, let's remove the fill so it's just text. 

<img width="448" alt="Screen Shot 2020-08-25 at 9 51 34 AM" src="https://user-images.githubusercontent.com/6350997/91182758-9405cb00-e6b8-11ea-8ce2-2145f9b8558a.png">

A bug I encountered:
- For some reason I'm not able to `like` posts straight from the discover feed. I need to go tap into the post to like it. I'm using an iPhone Xs 13.6. Maybe just an issue with the build?

**Comment by mbshakti** [comment]
Another thing I observed was that sometimes site pages or topic pages take a long time to load. Is that expected? Gif below:


![Kapture 2020-08-25 at 10 17 53](https://user-images.githubusercontent.com/6350997/91186225-c87b8600-e6bc-11ea-9426-c21bae203555.gif)

**Comment by mbshakti** [comment]
This seems like an API problem, but seeing a lot of non-English content in some English topics. I think the topic I followed was "politics". Anyway, I'm not sure if expected behavior or no, but just surfacing for visibility! 

<img width="1008" alt="Screen Shot 2020-08-25 at 10 27 34 AM" src="https://user-images.githubusercontent.com/6350997/91186960-a0405700-e6bd-11ea-982b-b2ec318676b8.png">

**Comment by mbshakti** [comment]
If I only follow 1 or 2 topics (not more), I see the "topics you might like card" twice right after each other. 

<img width="977" alt="Screen Shot 2020-08-25 at 10 30 20 AM" src="https://user-images.githubusercontent.com/6350997/91187277-0036fd80-e6be-11ea-8405-c320ae37ca5d.png">

**Comment by emilylaguna** [comment]
> Another thing I observed was that sometimes site pages or topic pages take a long time to load. Is that expected? Gif below:

This looks like an API issue.

**Comment by emilylaguna** [comment]
> This seems like an API problem, but seeing a lot of non-English content in some English topics. I think the topic I followed was "politics". Anyway, I'm not sure if expected behavior or no, but just surfacing for visibility!

This is an API thing as well.

**Comment by emilylaguna** [comment]
> If I only follow 1 or 2 topics (not more), I see the "topics you might like card" twice right after each other.
> 
Do you know which topics you followed?

**Comment by mbshakti** [comment]
Hmm can't recall, but something random like "disney" and maybe something adjacent to that. Sorry :/ I'll document that next time.
