### ISSUE TITLE
Plans page is accessible from WordPress Help Center

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#14751]
### Expected behavior
The app shouldn't have any ability to view a list of plans, or link to a page that does.

### Actual behavior
It currently does

### Steps to reproduce the behavior
Go Me > Help & Support > WordPress Help Center > Search for "Plan" > Choose the Top Entry > Tag "Purchase Page".

##### Tested on iPhone 11 Pro Max, iOS 13.6, WPiOS 15.5

<table>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/1123407/91212758-e43b5800-e6cd-11ea-9c6e-0c8126da2820.PNG" />
</td>
<td>
<img src="https://user-images.githubusercontent.com/1123407/91212793-f0271a00-e6cd-11ea-8a77-730bc00b0498.PNG" />
</td>
</tr>
</table>

**Comment by jkmassel** [comment]
This is a tricky one – I don't think we can fix it in-app, we'd probably need to change it somewhere in ZenDesk, but I don't know if we can exclude it from showing up in the app from there?

**Comment by ScoutHarris** [comment]
This properties of the article can be changed to no longer show in the mobile app. Ref https://wp.me/pbArwn-12K/#comment-1521.

**Comment by rezzap** [comment]
I have unpublished the Zendesk page and double-checked the app that the page can't be searched. This should be resolved now.

**Comment by jkmassel** [comment]
I can confirm this is resolved – closing.

Thanks @rezzap and @ScoutHarris!!
