### ISSUE TITLE
YouTube shortcode not rendering correctly in notification mention

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#14758]
### Expected behavior

When viewed via the Notifications tab in WPiOS, a comment that includes a Shortcode block which in-turn contains the YouTube shortcode (e.g. `[youtube https://www.youtube.com/watch?v=fX8YLri4wxU]`) should be rendered correctly (i.e. the YouTube video should be visible in the comment). Note: this works fine for posts that contain this same content.

### Actual behavior

The raw shortcode itself is visible instead of the referenced YouTube video.

| Post notification — works here ✅ | Comment notification — doesn't work here ❌ |
| -- | -- |
| <img alt="Screenshot showing YouTube shortcode rendering correctly in post notification in WPiOS" src="https://user-images.githubusercontent.com/1898325/91240075-fb4e6a00-e70e-11ea-959c-239629db31dd.png" width="300" /> | <img alt="Screenshot showing YouTube shortcode rendering incorrectly in comment notification in WPiOS" src="https://user-images.githubusercontent.com/1898325/91240082-ff7a8780-e70e-11ea-9969-ebc19dc1e6f8.PNG" width="300" /> |

### Steps to reproduce the behavior

1. On the web, log into a WordPress site that has Gutenberg enabled in comments (e.g. create a site on http://wp.com/p2)
2. Add another WordPress user, granting the Administrator role (other roles may work)
3. Still on the same site, create a reply (comment) to a post, @-mentioning the newly added user
4. Add an Shortcode block to that same reply (sample content `[youtube https://www.youtube.com/watch?v=fX8YLri4wxU]`)
5. Send the reply
6. From the WPiOS app, log in as the newly added Administrator
7. In the Notifications tab, locate the notification for the reply that @-mentioned the user
8. Open the comment, and notice the video is not visible — only the raw shortcode is visible

**Comment by ScoutHarris** [comment]
Linking to https://github.com/wordpress-mobile/WordPress-iOS/issues/14870, the master issue for Comment block issues.
