### ISSUE TITLE
Stats not changing when you switch from one site to the other

### ISSUE THREAD

**Issue by rossanafmenezes** [wordpress-mobile/WordPress-iOS#14759]
We have had 3 reports lately regarding an issue with the iOS WP app. However, each of them happened in a different "scenario". This user 3252442-zen has simple WP.com site, this one 3254212-zen has multiple self-hosted JP sites, and this one 3238193-zen is a beta tester.

So, users open the app and it shows the stats for site # 1. All good there. They then switch to another site, let's call site # 2 and open the stats screen. 

### Expected behavior

We would expect the stats screen to show the stats pertaining to site # 2 once you switch. 

### Actual behavior

The stats keep showing the information from site # 1 

### Steps to reproduce the behavior

I was not able to reproduce here, so it's not 100% consistent, but @rezzap was able to reproduce on the beta version. 

- Open the app 
- Go to the stats page
- Click on Switch site and pick a different site 
- see the stats showing for the last site and not te current one. 

##### Tested on:

Tested by @rezzap on 15.5 iPhone X, 2 WordPress.com sites (one atomic, one Premium) iOS 13.6.1

User on 3238193-zen tested on  iPhone X iOS, 14.0 WordPress for iOS 15.5 (they also provided a screencast of the issue on the ticket).

The other 2 users I don't have the information on their devices or iOS version but both are on WordPress for iOS 15.4

**Comment by designsimply** [comment]
I noticed period stats were not updating after switching sites last night while beta testing 15.6.0.0 and was able to capture a video showing the problem. In my case, Stats Insights updated but the Days/Weeks/Months/Years screens did not update even after pull-to-refresh. I also observed that it first happened for a site from a prior login. 😱

Video: [4m35s](https://cloudup.com/cx2MhUraJbG)
<p style="clear:both;"><sup>Tested with WPAndroid 15.6-rc-1 on Pixel 3 Android 10.</sup></p>

**Comment by designsimply** [comment]
> I can't pinpoint when this started, but it the last 1-2 weeks over several betas, the Stats section has 'cached' data even when you look at a different site. Very confusing to see the first few times! Refreshing doesn't help.
> 
> <sup>Beta tester feedback Aug 12, 2020 at 4:52 PM WPiOS 15.5.0.0 iPhone X iOS 14.0</sup>

<p style="clear:both;"><sup>appstoreconnect-testflight/screenshots/ACVhi5nDtN8ON-H8iT4UqQ8</sup></p>

<p style="clear:both;"><sup>Note: I followed up with them in 3238193 and it's one of the tickets referenced in the original issue. 👍</sup></p>

**Comment by erricgunawan** [comment]
From app review:

> I manage multiple sites on wordpress.com. When switching between sites in the app, statistics are not updated. Instead, it shows statistics from the previous site.

Reported on Aug 26, 2020 | WPiOS 15.4

**Comment by designsimply** [comment]
> I manage multiple sites on wordpress.com. When switching between sites in the app, statistics are not updated. Instead, it shows statistics from the previous site.
> 
> <sup>2-star app review by by eirikjeistad – Aug 25, 2020 WPiOS 15.4</sup>

<sup>(internal reference: appstoreconnect-reviewId=6360003807)</sup>

**Comment by msilbers** [comment]
> The other 2 users I don't have the information on their devices or iOS version but both are on WordPress for iOS 15.4

3252442 reply: iOS 13.6.1 on all devices
3254212 reply: Apple iPhone 8+ with "latest" iOS version

**Comment by msilbers** [comment]
reported in 3255246-zen

WPiOS 15.4
iOS 13.6.1
iPhone 10,5

> The data of three websites are muddled up... Data in browser is correct though.

**Comment by rezzap** [comment]
Another report in 3263957-zen

WPiOS 15.5
iOS, 12.4.8
iPhone6

Will let them know this should be fixed in 15.7

**Comment by rossanafmenezes** [comment]
Another report here 3266255-zen

WP version 15.4
Asked for details about the iOS and device.

**Comment by designsimply** [comment]
@rossanafmenezes no need to ask for more details from people reporting the stats issue at this point—please let them know the issue will be fixed in the 15.7 release at the latest. 🙂 

@yaelirub I've just answered three new 1-star app reviews to let them know a fix is on the way—because of these reviews and the interest from users, would you like to move this up to target the 15.6 release which is currently in code freeze until Sep 4?

1-star review "All sites showing same stats"
> I don’t know what’s going on with recent updates but all my sites are showing the stats and data of one single site. The app is basically useless now.
> 
> <sup>by agirlandhermac - Aug 29, 2020 - WPiOS 15.5 - appstoreconnect-reviewId=6375803926</sup>

1-star review "Multi-domain statistics" - translated from Japanese with Google Translate
> After updating, I can no longer see statistics for each site. Even if you switch sites, the statistics will be for different domains.
> 
> <sup>by Yama------ - Aug 30, 2020 - WPiOS 15.5 - appstoreconnect-reviewId=6378958569</sup>

1-star review "Statistics" - translated from Japanese with Google Translate
> I have registered multiple blogs, but all have the same statistics. This is my first time. Thank you for your patience.
> 
> <sup>by @danad - Aug 31, 2020 - WPiOS 15.5 - appstoreconnect-reviewId=6380253571</sup>

**Comment by yaelirub** [comment]
> would you like to move this up to target the 15.6 release which is currently in code freeze until Sep 4?

Yes! @Gio2018 , i see you already merged this to 15.7, can you please cherry pick the fix to 15.6

**Comment by designsimply** [comment]
Looping back to note I tested this n 15.6 (App Store version) and 15.7.0.1 (TestFlight beta) from a few different accounts and I was able to switch sites and see the Stats update to the correct site. 👍
