### ISSUE TITLE
Reader Improvements: Discover: Sorting Posts

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#14765]
Project Issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/14768

### Goal
When the user is on the new Discover screen they are given the option to sort the posts by popularity or most recent.

### Screenshots

<img width="983" alt="Screen Shot 2020-08-26 at 3 07 03 PM" src="https://user-images.githubusercontent.com/793774/91345740-b0773580-e794-11ea-98d1-8a328e12d92d.png">

### Designs
- [Explorations](https://www.figma.com/file/gVXXG9V6AiMkXbBvvy6Ggw/Sorting-Posts?node-id=2%3A387)
- [Specs](https://www.figma.com/file/1I8UKvncCSTRjUtJuLp2xd/Sorting-UX?node-id=1%3A172)

High level asks:

- [ ] Add feature flag
- [ ] Ensure views are correct for both dark and light appearance.
- [ ] Add Accessibility support.
- [ ] Add Tracks.
- [ ] Enable feature flag for internal.
- [ ] Enable feature flag for all.
- [ ] Remove feature flag.

**Comment by kean** [comment]
You can now do that with "topics":

<img width="320" alt="Screenshot 2024-11-15 at 9 55 02 AM" src="https://github.com/user-attachments/assets/fc3ad202-8dd7-404c-846c-dac0deeccc0b">
