### ISSUE TITLE
Quick Start: pulsing dot appears on My Site instead of Reader for the "Select Reader to continue" step

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#14780]
Steps to reproduce:

1. Log out and sign up as a new user and create a new site.
1. Select "Yes, Help Me" when prompted for help getting started.
1. Complete each quick start tour step and confirm that the pulsing dot shows up correctly for each step.

**Result:** the pulsing dot is a little too hidden behind the FAB (floating action button) on the My Site screen in the "Select View Site to preview" step and the pulsing dot is on the wrong icon in the "Select Reader to continue" step.

"Select View Site to preview"|"Select Reader to continue"
---|---
![IMG_4564](https://user-images.githubusercontent.com/1119271/91505201-404bdb00-e88c-11ea-9171-a92de7d6db34.png)|![IMG_4565](https://user-images.githubusercontent.com/1119271/91505203-42159e80-e88c-11ea-9221-de404d4afe05.png)

Note: happy to file a separate issue for the partially hidden dot on the View Site step or to drop it if you think it's not worth fixing. Please let me know either way!

**Comment by leandroalonso** [comment]
@designsimply which tour produces this issue? Do you remember?

**Comment by designsimply** [comment]
View Site is in the Next Steps > Customize Your Site tour and the Reader step is in the Follow other sites step in the Grow Your Audience Tour. (I think that's what you mean.)

Full signup test for reference: [15m31s](https://cloudup.com/cgWm8m_q2bc)
<p style="clear:both;"><sup>Scroll to 3:05 for Quick Start prompt, 7:57 for View Site, 13:00 for Reader.</br>Tested with WPiOS 15.6.0.1 TestFlight beta on iPhone 11 iOS 13.6.1.</sup></p>
