### ISSUE TITLE
SIGABRT: Cannot form weak reference to instance (0x281511310) of class WordPressKit.WordPressOrgXMLRPCApi....

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#14787]
**Sentry Url**: https://sentry.io/share/issue/8b016bafccf045cebde095bc0ce0525d/
**User Count**: 14
**Count**: 121
**First Release**: 15.4.0.0
**First Seen**: 2020-07-28T08:36:13Z
**Last Seen**: 2020-08-28T15:57:19Z
**24 Hours**: 29
**30 Days**: 118
**LogID:** 2D143B8C-8563-445B-A9A2-69AB925E6F86

```
SIGABRT: Cannot form weak reference to instance (0x281511310) of class WordPressKit.WordPressOrgXMLRPCApi....
  File "WordPressOrgXMLRPCApi.swift", line 53, in WordPressOrgXMLRPCApi.makeSessionManager
  File "WordPressOrgXMLRPCApi.swift", line 31, in WordPressOrgXMLRPCApi.sessionManager.getter
  File "WordPressOrgXMLRPCApi.swift", line 29, in WordPressOrgXMLRPCApi.sessionManager.getter
  File "WordPressOrgXMLRPCApi.swift", line 90, in WordPressOrgXMLRPCApi.__deallocating_deinit
  File "<compiler-generated>", line null, in WordPressOrgXMLRPCApi.__deallocating_deinit
  File "Classes/Models/Blog.m", line 109, in -[Blog didTurnIntoFault]
...
(17 additional frame(s) were not displayed)
```

**Comment by designsimply** [comment]
Noticed there's a similar-sounding error for Gutenberg Mobile at https://github.com/wordpress-mobile/WordPress-iOS/issues/13758.

**Comment by bummytime** [comment]
@bjtitus I see [you updated some refs](https://github.com/wordpress-mobile/WordPressKit-iOS/commit/b84d27ac10b0690493edd9dd9a96d4ebab4fab12) in `WordPressKit/WordPressOrgXMLRPCApi.swift` on July 20th. Any chance this is related? 😄

**Comment by bjtitus** [comment]
I think this is absolutely related to that change which went into 15.4. #13427 no longer exists in [15.4](https://sentry.io/organizations/a8c/discover/results/?display=top5&field=title&field=user&field=project&name=Errors+by+Title&query=event.type%3Aerror+title%3A%22EXC_BAD_ACCESS%3A+.cxx_destruct+%2A%22+project%3Awordpress-ios+release%3A15.4%2A&sort=-title&statsPeriod=24h&widths=-1&widths=-1&widths=-1) or [15.5](https://sentry.io/organizations/a8c/discover/results/?display=top5&field=title&field=user&field=project&name=Errors+by+Title&query=event.type%3Aerror+title%3A%22EXC_BAD_ACCESS%3A+.cxx_destruct+%2A%22+project%3Awordpress-ios+release%3A15.5%2A&sort=-title&statsPeriod=24h&widths=-1&widths=-1&widths=-1), though this could have just replaced it.

One thing jumped out at me looking at this. The crash log states: "It is possible that this object was over-released, or **is in the process of deallocation**." The stack trace seems to indicate just that given that we pass through `WordPressOrgXMLRPCApi.deinit`. The `sessionManager` properties are both lazy and, thus, created on demand. The calls to these properties in `deinit` then trigger the lazy block to run (this is why we see `makeSessionManager` called from within `deinit`):

```swift
deinit {
    sessionManager.session.finishTasksAndInvalidate()
    uploadSessionManager.session.finishTasksAndInvalidate()
}
```
##### From [WordPressOrgXMLRPCAPI:89-92](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/3d06ae4cdaf4c602a0d62458a01cfe0d1f0d801c/WordPressKit/WordPressOrgXMLRPCApi.swift#L89-L92)

I think it _may_ be a bad idea to use those properties in `deinit`. When they aren't initialized, we don't care about running `finishTasksAndInvalidate`. I haven't had a chance to test any of this, but using optional properties from `deinit` could be a solution:

```swift
private var _sessionManager: Alamofire.SessionManager?
private var _uploadSessionManager: Alamofire.SessionManager?

private var sessionManager: Alamofire.SessionManager {
    guard let sessionManager = _sessionManager else {
        let sessionConfiguration = URLSessionConfiguration.default
        let sessionManager = self.makeSessionManager(configuration: sessionConfiguration)
        _sessionManager = sessionManager
        return sessionManager
    }
    return sessionManager
}

private var uploadSessionManager: Alamofire.SessionManager {
    if self.backgroundUploads {
        guard let uploadSessionManager = _uploadSessionManager else {
            let sessionConfiguration = URLSessionConfiguration.background(withIdentifier: self.backgroundSessionIdentifier)
            let sessionManager = self.makeSessionManager(configuration: sessionConfiguration)
            _uploadSessionManager = sessionManager
            return sessionManager
        }
        return uploadSessionManager
    }
    return sessionManager
}
```

```swift
deinit {
    _sessionManager?.session.finishTasksAndInvalidate()
    _uploadSessionManager?.session.finishTasksAndInvalidate()
}
```

**Comment by bummytime** [comment]
Thanks @bjtitus! @leandroalonso do you have any thoughts on this ☝️ ?

**Comment by bjtitus** [comment]
@bummytime @leandroalonso I was unable to reproduce this exact same issue but did reproduce effectively the same stack trace by creating a new `SessionManager` property which is never initialized before `deinit` is called – it crashed with the same error. Based on that little test, I believe the theory I mentioned above is correct.

I've submitted a PR here: https://github.com/wordpress-mobile/WordPressKit-iOS/pull/283
