### ISSUE TITLE
EXC_BAD_ACCESS: managedObjectContext >

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#14791]
**Sentry Url**: https://sentry.io/share/issue/5e9e3d76a8c44a88bbbeb53c32c29674/
**User Count**: 18
**Count**: 141
**First Release**: 14.9.0.4
**First Seen**: 2020-06-07T03:10:48Z
**Last Seen**: 2020-08-28T09:14:15Z
**24 Hours**: 13
**30 Days**: 125
**LogID:** 16ED1558-0C2B-48D6-9657-65CC2F1D90EF

```
EXC_BAD_ACCESS: managedObjectContext >
  File "Classes/Services/ReaderTopicService.m", line 248, in __50-[ReaderTopicService preserveSavedPostsFromTopic:]_block_invoke
  File "Classes/Services/ReaderTopicService.m", line 248, in -[ReaderTopicService preserveSavedPostsFromTopic:]
  File "Classes/Services/ReaderTopicService.m", line 194, in -[ReaderTopicService deleteNonMenuTopics]
  File "ReaderTabViewModel.swift", line 231, in ReaderTabViewModel.clearTopics
  File "ReaderTabViewModel.swift", line 203, in ReaderTabViewModel.addNotificationsObservers
  File "<compiler-generated>", line null, in @callee_guaranteed
  File "main.swift", line 7, in main
...
(34 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
Not many users or events...adding to Groundskeeping.

**Comment by designsimply** [comment]
**Events in the last 90d:** 144
**Users affected in the last 90d:** 19
<sub>https://sentry.io/share/issue/5e9e3d76a8c44a88bbbeb53c32c29674/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1713620038&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/92031845-1841f900-ed1e-11ea-911a-7901f5fc3711.png)</a>

Noticed an uptick for this one in the last 2 weeks, not sure if it'll stick though.

**Comment by designsimply** [comment]
**Events in the last 90d:** 135
**Users affected in the last 90d:** 16
<sub>https://sentry.io/share/issue/5e9e3d76a8c44a88bbbeb53c32c29674/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1713620038&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/94750692-e08d9780-0343-11eb-88dc-c38867a28bf8.png)</a>

Looks like the one had a spike that dropped to almost nothing. @bummytime ok to close?

**Comment by bummytime** [comment]
@designsimply 👍 from me. Thank you!
