### ISSUE TITLE
@-mentions not working on Atomic sites

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#14844]
### Expected behavior

@-mentions (or suggestions) should work for all types of WordPress.com sites, including those with plugins installed (Atomic). 

Note: This does work on WordPress for Android.

| Android ✅ | iOS ❌ |
| - | - |
| <img alt="Screenshot showing @-mentions working on Atomic sites on WordPress for Android" width="300" src="https://user-images.githubusercontent.com/1898325/92261184-063f9200-eea7-11ea-90ad-f2f9a1320e6f.jpg" /> | <img alt="Screenshot showing @-mentions working on Atomic sites on WordPress for Android" width="300" src="https://user-images.githubusercontent.com/1898325/92261241-1bb4bc00-eea7-11ea-9556-5e0b2b9d4a56.PNG" /> |

### Actual behavior

In Reader, the @ character does not trigger a list of users to be shown when the site in question is Atomic, but it does work if the site is a regular WordPress.com site. 
It doesn't work in Notifications or Gutenberg, either.

### Steps to reproduce the behavior

1. On the WordPress for iOS app, go to the Reader and locate a post from an Atomic site. If none available, create one like so:
  a. Find or create a WordPress.com site with a Business plan, install any plugin
  b. Publish a post from that site
  c. Add another user to the site
  d. Log in to the WordPress for iOS app using that recently added user
2. Create a comment on that post, type the @ character and notice that no UI is shown for adding mentions

**Comment by guarani** [comment]
This is due to this code:
https://github.com/wordpress-mobile/WordPress-iOS/blob/ed9df296c60e0875e4121e3e8595aa9787638578/WordPress/Classes/Services/SuggestionService.m#L114-L118

The check `[blog supports:BlogFeatureMentions]` incorrectly interprets Atomic sites as not being hosted on WordPress.com:

https://github.com/wordpress-mobile/WordPress-iOS/blob/8bfca4663f4beeab131ec1d67e2d4cf6f946f5a0/WordPress/Classes/Models/Blog.m#L478-L479

Note: The `isHostedAtWPcom` property is false for Atomic sites in my tests. (It should really be named `isWPComSimpleSite` or similar.)

**Comment by hypest** [comment]
Fixed by #15317
