### ISSUE TITLE
Update header for P2 postcards to show author 

### ISSUE THREAD

**Issue by mbshakti** [wordpress-mobile/WordPress-iOS#14875]
After receiving some feedback internally that it's much more efficient to have the author name included in the postcard UI for P2 posts specifically, I've updated the design for P2 postcards as per below.

Changes to header include:

- Show author name next to site name
- Show author icon next to site icon
- Show timestamp below

<img width="846" alt="Screen Shot 2020-09-10 at 2 56 16 PM" src="https://user-images.githubusercontent.com/6350997/92785916-cf212300-f375-11ea-8b32-bd958adcdda6.png">

<img width="857" alt="Screen Shot 2020-09-10 at 2 56 19 PM" src="https://user-images.githubusercontent.com/6350997/92785922-d0525000-f375-11ea-853f-c8c6e23ff690.png">

Specs coming tomorrow (Sep 11)

**Comment by mindgraffiti** [comment]
Android equivalent: https://github.com/wordpress-mobile/WordPress-Android/issues/12934

**Comment by ScoutHarris** [comment]
Hey @mbshakti .

A couple of questions please.

1. To be clear, do you want to show the author any time a P2 card is displayed in any Reader feed (`Following`, `Likes`, etc.)? Or just when `Automattic` is selected?

2. On cross-post cards, the author avatar is on top of the site icon. Can we make the P2 card the same for consistency?

<img width="404" alt="Screen Shot 2020-11-11 at 5 26 14 PM" src="https://user-images.githubusercontent.com/1816888/98880073-214cf600-2444-11eb-9bc6-d6677724113b.png">

**Comment by mindgraffiti** [comment]
@mbshakti if there is a Figma link, would you DM that to us as well?

**Comment by mbshakti** [comment]
Hey @ScoutHarris 

> do you want to show the author any time a P2 card is displayed in any Reader feed (Following, Likes, etc.)? Or just when Automattic is selected?

Yes, anywhere the card is displayed (likes/saved). AFAIK, we don't show P2 content on "following", right? Isn't "following" only reserved for non-P2 sites?

> On cross-post cards, the author avatar is on top of the site icon. Can we make the P2 card the same for consistency?

Good catch! yes, let's do that.

**Comment by mbshakti** [comment]
@mindgraffiti I will put this together on Figma and share it by EOD today or tomorrow. Does that work?

**Comment by ScoutHarris** [comment]
Thanks @mbshakti !

> AFAIK, we don't show P2 content on "following", right?

I see now. I believe you are correct - the _new_ P2s do not appear in Following.

**Comment by mindgraffiti** [comment]
> share it by EOD today or tomorrow

@mbshakti sounds good. Thank you!

**Comment by ScoutHarris** [comment]
Hey @mbshakti . I'm wondering why we're removing the URL. It seems like a handy piece of information to see, just like any other site card. I don't suppose we could leave it? FWIW, the "time ago" is already being displayed, and there is enough room for both. 

<img width="433" alt="Screen Shot 2020-11-12 at 1 48 12 PM" src="https://user-images.githubusercontent.com/1816888/98994968-e6070180-24ed-11eb-9cf7-d6800e8bbf41.png">

**Comment by ScoutHarris** [comment]
Hey @mbshakti .

Another thing to note. All the Reader avatars have borders on them. I assume this is so avatars that are not perfectly round and color-filled look better. Like Simplenote and Puffin:

<img width="63" alt="simplenote" src="https://user-images.githubusercontent.com/1816888/99011794-1e1c3d80-250a-11eb-8eb8-e7c33162a70d.png">
<img width="85" alt="puffin" src="https://user-images.githubusercontent.com/1816888/99011802-21172e00-250a-11eb-8387-c3f75aff157b.png">

I'm going to leave it this way because without the borders some icons just look...weird. If you prefer another method, that can be addressed separately to cover all Reader icons in all cards.

**Comment by mbshakti** [comment]
> I'm wondering why we're removing the URL.

One of things we found in research was that new users didn't know where content on the reader was coming from. We included the URL in the postcards to help new users build a mental model that these are posts from websites (hence the URL). With P2, I didn't see it as that important since users of P2 already know what it else etc. And the P2 name on top helps close the gap on knowing which p2 the content is from. Does that make sense? I still open to including the URL if you think it's helpful to the reader!

> I'm going to leave it this way because without the borders some icons just look...weird. If you prefer another method, that can be addressed separately to cover all Reader icons in all cards.

We kept borders for exactly that reason, and yes we can maintain that here 👍🏾

**Comment by ScoutHarris** [comment]
@mbshakti and I had a Slack conversation about hiding the URL. To summarize the conclusion: "if we have the space, readers might benefit from the URL. I think we shouldn’t unnecessarily make the postcards inconsistent if they don’t need to be."

So I'll leave the URL. If need be it can be removed later.

**Comment by mbshakti** [comment]
@mindgraffiti the figma for this is here https://www.figma.com/file/MhMFkAdCxg7zOMga3ypKGo/P2-Postcards?node-id=0%3A1 - in case I'm using any text styles or colors in the Figma that are different from what's the production, let's lean on what's in production since we want to maintain consistency with the current postcard design :) Feel free to ping me any questions!
