### ISSUE TITLE
Reader: Tag suggestions cut off at bottom of list 

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#14885]
### Expected behavior
Show the user a list of tags they might like. 

### Actual behavior
list is cut off on both iPhone and iPad.

<img width="237" alt="image-5" src="https://user-images.githubusercontent.com/66104034/92970541-1376f680-f43c-11ea-9300-2e73d8973a67.png">
<img width="743" alt="screenshot-2020-09-11-at-10 33 41" src="https://user-images.githubusercontent.com/66104034/92970547-14a82380-f43c-11ea-9de0-2b02a13fa1fa.png">

### Steps to reproduce the behavior
1. Move the app to background while on Discover tab
2. Launch the app again - You wil be on discover tab
3. Go to another tab (Likes , Following)
4. Come back to Discover and see the last suggested interest is cut in the "You Might Like" list

##### Tested on [device], iOS [version], WPiOS [version]
iPad (2019), iOS 13.7, WPiOS 15.7.0.1

**Comment by startuptester** [comment]
On reviewing the steps, I noticed I sometimes have to go to My Site and back to Reader at the end of the steps in order to see the bug

**Comment by yaelirub** [comment]
I am unable to reproduce this. Are you able to reproduce this consistently, @startuptester ?

**Comment by startuptester** [comment]
Updated the steps. 

I can reproduce this every time on both iPad and iPhone following the steps. Added more clarity.

**Comment by leandroalonso** [comment]
The design of this section was changed, thus the issue doesn't happen anymore.
