### ISSUE TITLE
Interest picker screen: change size of done button on iPad

### ISSUE THREAD

**Issue by mbshakti** [wordpress-mobile/WordPress-iOS#14893]
The done button spans the entire screen width and looks unpolished. Can we please reduce the width of the button per the specs on Figma? https://www.figma.com/file/NuCzgHcTmaW0YkGpX3YKD0/%F0%9F%93%90-Interests-Picker-Screen-(Specs)?node-id=194%3A1177

Screenshot from build
![img_0014-1](https://user-images.githubusercontent.com/6350997/93096952-fc6e1980-f672-11ea-8069-5cc58f86878f.png)

Figma
<img width="727" alt="Screen Shot 2020-09-14 at 10 14 52 AM" src="https://user-images.githubusercontent.com/6350997/93097126-2aebf480-f673-11ea-95e1-b2560d0f00eb.png">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/23784
