### ISSUE TITLE
UL&S: epilogue screen is showing multiple times

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#14897]
### Expected behavior
After successfully logging in to a DotCom account and adding a self-hosted site, the login epilogue should not appear. 

### Actual behavior
The login epilogue is showing for a second time.

### Steps to reproduce the behavior
1. Log in with any WordPress.com account.
2. Go to the My Site tab and tap Switch Site.
3. On the My Site screen, tap the + button on the toolbar.
4. On the dialog, tap Add self-hosted site.
5. Notice the Site Address screen.
6. Verify that the Prologue screen is not shown.
7. Verify that iCloud Keychain is not shown.
8. Complete the login flow with any self-hosted site.
9. Verify that the Epilogue screen is not shown at the end of the flow.

**Comment by ScoutHarris** [comment]
This isn't a bug. The epilogue has always shown in this path. If we don't want it to, that can be a future enhancement.

**Comment by mindgraffiti** [comment]
Reopening as an enhancement, because Android follows this behavior and iOS should be consistent with that.

**Comment by mindgraffiti** [comment]
Ignore me. This is not a bug or an enhancement, it's expected behavior.
