### ISSUE TITLE
Notifications: Notifications screen has incorrect layout immediately after sign in.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#14898]
Immediately after signing in, or logging in to an account with no notifications, the no results screen is incorrectly positioned. 
Example:
![IMG_1820](https://user-images.githubusercontent.com/1435271/93135622-3e618480-f6a0-11ea-8343-6c964210e592.PNG)

### Steps to reproduce the behavior
Sign up to wpcom with a brand new account via the app, or log in with an account that has no notifications.
Once signed in switch to the notifications tab.
Observe the incorrect layout. 
Switch to a different tab and back again.
Notice the layout updates but there is still a bar across the top giving the tab a different feeling from the other tabs.

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 11 pro, iOS 13.6.1, WPiOS 15.7

**Comment by aerych** [comment]
Refs #14547

**Comment by salimbraksa** [comment]
Closing this issue as I couldn’t reproduce the bug and the empty view looks good on my side. Also, when navigating away from the notifications screen and then returning, the empty view remained in the same position.

cc @aerych 

![image](https://github.com/wordpress-mobile/WordPress-iOS/assets/9609223/1c9717fa-1559-4b63-a22d-035db6261ec6)
