### ISSUE TITLE
Reader: unfollowing list of tags doesn't actually unfollow all the tags 

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#14900]
### Expected behavior
When a user unfollows a tag, I expect that to be propagated to all their views of Reader. (iOS, Android, web) 

### Actual behavior
While they appear to not be following any tags on iOS, 3 of the deleted ones are still being followed. 

### Steps to reproduce the behavior
1. In the Discover tab, follow all the tags that start with 'A'
![IMG_8FFC9F4225A1-1](https://user-images.githubusercontent.com/66104034/93165372-180c0b00-f6d9-11ea-8847-00bb6ffe63ec.jpeg)

2. Go to Followed Tags and delete all the tags in the list 
![IMG_6E3E99ADBEAE-1](https://user-images.githubusercontent.com/66104034/93165389-265a2700-f6d9-11ea-9697-7b7c34d01435.jpeg)
![IMG_B84B4CF84621-1](https://user-images.githubusercontent.com/66104034/93165392-29551780-f6d9-11ea-9c19-7e47af84ee15.jpeg)

3. go to wordpress.com/read and view what is listed under tags 
<img width="509" alt="Screen Shot 2020-09-14 at 10 20 32 PM" src="https://user-images.githubusercontent.com/66104034/93165409-396cf700-f6d9-11ea-81c8-112a0342b718.png">

##### Tested on [device], iOS [version], WPiOS [version]
iPad (2019), iOS 13.7, WPiOS 15.7 beta

**Comment by leandroalonso** [comment]
@frosty @bjtitus I wonder if one of you has seen this issue before?

My suspicion here is that removing a lot of tags at the same time is causing `429` errors.

**Comment by yaelirub** [comment]
This seems to be a problem only when removing tags fast. Otherwise it works as expected. 
@startuptester , did you test removing lots of tags, fast, in older versions too? 
@emilylaguna , I vaguely remember we said something about issues when deleting tags fast.

**Comment by startuptester** [comment]
@yaelirub 
1. Yes it only happens when you delete quickly, but re-adding the deleted tag does not need to be done fast after the delete. For example, I deleted that tags quickly (but really that is no faster than I would do it normally if I were clearing the list) and 
 I waited 5 minutes before re-adding on I deleted and I still got the error. 

2. I was not able to reproduce this in 15.5

**Comment by leandroalonso** [comment]
@startuptester given this is an issue that occurs with very specific conditions (such as removing tags really fast) I don't think it's affecting our users.

I'll close the issue but feel free to reopen it anytime.
