### ISSUE TITLE
Install Jetpack prompt remains on the Stats screen after installing Jetpack via Notifications until you browse away then back again

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#14915]
### Expected behavior

After I go to Notifications and tap "Install Jetpack", I expect the Stats screen will no longer show the "Install Jetpack" prompt.

### Actual behavior

After I go to Notifications and tap "Install Jetpack", the Stats screen still shows the "Install Jetpack" prompt until I browse away and back again.

### Steps to reproduce the behavior

1. Add a self-hosted site that does not have Jetpack installed.
1. Go to My Site > Stats and observe the "Install Jetpack" prompt but do not tap it.
1. Go to Notifications, tap "Install Jetpack", and complete the install and connection steps.
1. Go back to My Site > Stats and observe the "Install Jetpack" prompt is showing even though Jetpack was just installed.
1. Browse to a different screen and back to Stats and observe the "Install Jetpack" prompt is now gone.

Video: [3m41s](https://cloudup.com/c4toJ6lzAvN)

<img width="400" alt="Screen Shot 2020-09-15 at Sep 15 8 23 31 PM" src="https://user-images.githubusercontent.com/1119271/93285608-8234b680-f792-11ea-975c-8006c427e146.png">

##### Tested on iPad Mini 4 (WiFi) (iPad5,1), iOS 13.6.1, WPiOS 15.7.0.1 TestFlight beta

<sup>(internal reference: pbMoDN-15R-p2#comment-2389)</sup>

**Comment by staskus** [comment]
Closing as a duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/19260
