### ISSUE TITLE
HTML entity in tag name on tag listing 

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#14913]
### Expected behavior
no html entity displayed 

### Actual behavior
![image](https://user-images.githubusercontent.com/66104034/93275132-4f31f900-f779-11ea-8c7e-66f45711500c.png)

**reported by Chris Rosser**
_"i think it’d mean patching an old endpoint (v1.2 /read/tags/:tag/posts) but it must have been like that for a while"_
https://appstoreconnect.apple.com/apps/335703880/testflight/screenshots/AIEOLOme87GSC-3ZDF6lTgA?0=%3F&1=p&10=e&11=V&12=e&13=r&14=s&15=i&16=o&17=n&18=I&19=d&2=r&20=%3D&21=0&22=d&23=5&24=9&25=a&26=7&27=2&28=8&29=-&3=e&30=7&31=3&32=0&33=d&34=-&35=4&36=f&37=5&38=d&39=-&4=R&40=a&41=7&42=3&43=c&44=-&45=c&46=c&47=9&48=7&49=8&5=e&50=3&51=f&52=7&53=b&54=6&55=5&56=f&57=%26&58=s&59=o&6=l&60=r&61=t&62=%3D&63=-&64=t&65=i&66=m&67=e&68=s&69=t&7=e&70=a&71=m&72=p&8=a&9=s&preReleaseVersionId=0d59a728-730d-4f5d-a73c-cc9783f7b65f

##### Tested on [device], iOS [version], WPiOS [version]
iPhone X, 13.6.1, WPiOS 15.7.0.1 beta

**Comment by daniloercoli** [comment]
Closing this issue since I cannot replicate it on the latest Jetpack version.
![Screenshot 2024-02-26 at 11 45 38](https://github.com/wordpress-mobile/WordPress-iOS/assets/518232/aa1b5a39-d504-40f9-afe7-322ae6d59a41)
