### ISSUE TITLE
NSInvalidUnarchiveOperationException: *** -[NSKeyedUnarchiver decodeInt64ForKey:]: value for key (start) is not an integer number

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#14956]
**Sentry Url**: https://sentry.io/share/issue/3e1a21f3b2814fac9765682ae76ebbc4/
**User Count**: 78
**Count**: 254
**First Release**: 14.8.2.0
**First Seen**: 2020-06-24T12:39:00Z
**Last Seen**: 2020-09-22T04:17:47Z
**24 Hours**: 1
**30 Days**: 83
**LogID:** 515732CF-E863-4C27-8520-8145870C6BCD

```
NSInvalidUnarchiveOperationException: *** -[NSKeyedUnarchiver decodeInt64ForKey:]: value for key (start) is not an integer number
  File "TextList.swift", line 64, in TextList.init
  File "<compiler-generated>", line null, in TextList.init
  File "<compiler-generated>", line 56, in TextList.init
  File "ParagraphStyle.swift", line 92, in ParagraphStyle.init
  File "<compiler-generated>", line null, in ParagraphStyle.init
  File "<compiler-generated>", line 90, in ParagraphStyle.init
  File "UIPasteboard+Helpers.swift", line 54, in UIPasteboard.aztecAttributedString
  File "UIPasteboard+Helpers.swift", line 13, in UIPasteboard.attributedString
  File "TextViewPasteboardDelegate.swift", line 115, in AztecTextViewPasteboardDelegate.tryPastingString
  File "TextView.swift", line 516, in TextView.pasteWithoutFormatting
  File "null", line null, in TextView.cut
  File "main.swift", line 7, in main
...
(37 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
Added to groundskeeping

**Comment by designsimply** [comment]
**Events in the last 90d:** 347
**Users affected in the last 90d:** 80
<sub>WORDPRESS-IOS-37XQ: https://sentry.io/share/issue/3e1a21f3b2814fac9765682ae76ebbc4/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1695057810&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/94946113-e5b02b00-0498-11eb-9ecf-f170550f23c7.png)</a>

**Comment by designsimply** [comment]
**Events in the last 90d:** 450
**Users affected in the last 90d:** 56
<sub>WORDPRESS-IOS-37XQ: https://sentry.io/share/issue/3e1a21f3b2814fac9765682ae76ebbc4/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1695057810&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101844881-a80bf600-3b0a-11eb-9f48-1eef3045042b.png)</a>

It _looks_ stopped, but I am feeling suspicious of Sentry issues that stopped getting entries at the end of November. 🤨 I checked and a search for `NSInvalidUnarchiveOperationException` still shows crashes for that phrase and they are still happening in the latest release but only with one or a few instances per day in 16.2.

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=NSInvalidUnarchiveOperationException&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101845172-3a13fe80-3b0b-11eb-81c9-ac601d8909a1.png)</a>

**Comment by maximare** [comment]
We are having the same issue, and it's happening a lot. Could you increase the priority of the issue?

**Comment by designsimply** [comment]
@maximare it looks like we aren't seeing very many (6 total) of the original error "NSInvalidUnarchiveOperationException: *** -[NSKeyedUnarchiver decodeInt64ForKey:]: value for key (start) is not an integer number" in our app and that it has not happened in any of our latest versions, so I don't think the priority should be raised in our case. Unfortunately, I am not sure what caused the error to stop happening! But I can see that it has not happened in the WP app in any version above 15.9.02 and our latest stable is 16.7.

I am not sure what might be happening in your app (I am assuming you're referring to building a different app), and if you are building a separate app I would encourage you to keep searching for debugging info in more general Android or similar development forums because this case was specific to the WordPress app and since no one logged an update I don't have any more specific info to help you. I am sorry about that!

**Comment by zhandosbolatbekov** [comment]
We are having the same issue and a full scenario that 100% reproduces it. Could we try to solve this issue?
