### ISSUE TITLE
NSInvalidArgumentException: no object at index 0 in section at index 0

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#14964]
**Sentry Url**: https://sentry.io/share/issue/a153ddbcdb5b4b6190fc964d85bc0a21/
**User Count**: 84
**Count**: 117
**First Release**: 15.5.0.3
**First Seen**: 2020-08-26T00:27:14Z
**Last Seen**: 2020-09-21T20:17:52Z
**24 Hours**: 6
**30 Days**: 117
**LogID:** 75F66FC0-47BC-434B-AA6E-E02E5CE8B62A

```
NSInvalidArgumentException: no object at index 0 in section at index 0
  File "PostListViewController.swift", line 442, in PostListViewController.tableView
  File "null", line null, in PostListViewController.tableView
  File "Classes/Utility/WPTableViewHandler.m", line 296, in -[WPTableViewHandler tableView:didSelectRowAtIndexPath:]
  File "main.swift", line 7, in main
...
(18 additional frame(s) were not displayed)
```

**Comment by bummytime** [comment]
Adding to groundskeeping.

**Comment by designsimply** [comment]
**Events in the last 90d:** 171
**Users affected in the last 90d:** 121
<sub>WORDPRESS-IOS-38VM: https://sentry.io/share/issue/a153ddbcdb5b4b6190fc964d85bc0a21/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=device&field=os&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1871043755&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/94751902-f9e41300-0346-11eb-8e63-1016e85ed76e.png)</a>

**Comment by designsimply** [comment]
**Events in the last 90d:** 1,400
**Users affected in the last 90d:** 994
<sub>WORDPRESS-IOS-38VM: https://sentry.io/share/issue/a153ddbcdb5b4b6190fc964d85bc0a21/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=device&field=os&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1871043755&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101847902-8104f280-3b11-11eb-8b2e-addf3cc9b441.png)</a>

**Comment by Gio2018** [comment]
@designsimply @startuptester , looked into this issue and the Sentry link points to a group of `NSInternalInconsistencyException` (thanks @jkmassel for help me understanding how the grouping works).
So I did an explicit search of the error message in Sentry, and found 87 events in the last 90 days, with the latest occurring on Dec 1, so I'm holding off on this one and move to another one.
