### ISSUE TITLE
Comments: add a visual editor for comments

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#14973]
We received the following feedback internally.

> I went to write a reply from the app and I was surprised I couldn’t include a link in there. I had to write the HTML manually. Also, when I did that, the keyboard added smart quotes for the href which I had to replace manually.

Adding a new comment (full-screen)|To edit on an existing comment|Editing an existing comment
---|---|---
<img src="https://user-images.githubusercontent.com/1119271/93949231-97af6080-fcfd-11ea-9a40-c48880b45fc7.png" width="270" alt="IMG_4604">|<img src="https://user-images.githubusercontent.com/1119271/93949112-59b23c80-fcfd-11ea-97ec-75975f815a36.png" width="270" alt="IMG_4602">|<img src="https://user-images.githubusercontent.com/1119271/93948996-10fa8380-fcfd-11ea-8f7a-4f3a308f53e5.png" width="270" alt="IMG_4603">

<sup>Tested with WPiOS 15.8.0.0 TestFlight beta on iPhone 11 iOS 14.0.</sup>

Note: in the Android app, the screens where you add or edit a comment look slightly different (mainly the font is different and one says "Edit" in the heading while the other doesn't) but in iOS they look the same except for the heading at the top. I am not sure if the underlying code is different for each or if they are powered by essentially the same stuff. 

#### Extra Notes

The subset of HTML tags which are allowed in comments are stored in the `$allowedtags` global variable. See https://core.trac.wordpress.org/browser/tags/5.5.1/src/wp-includes/kses.php#L414

We don't have a visual editor for comments on the web yet, but there is a tag inserter in the WP Admin > Comments section.

<img width="640" alt="Screen Shot 2020-09-22 at Sep 22 5 42 40 PM" src="https://user-images.githubusercontent.com/1119271/93948254-31c1d980-fcfb-11ea-831d-7ac644781b1e.png">

You can interact with comments in a few different locations: on rendered blog posts in a browser, Reader, Notifications, and in My Site > Comments or WP Admin > Comments. At the time of this writing, the only place I could find a tag inserter for comments in a default setup was on a WordPress.org install in WP Admin > Comments. 

Automattic P2s have been using a modified plugin to use the Gutenberg block editor comments on a subset of P2s.
<sup>(internal reference: pb6Nl-do2-p2)</sup>

ht @koke p4a5px-2CS-p2 https://github.com/wordpress-mobile/WordPress-Android/issues/13005

**Comment by ScoutHarris** [comment]
This should be resolved when the '[Gutenberg Comment Editor](https://hummingbirdp2.wordpress.com/2021/01/12/project-thread-gutenberg-comment-editor/)' feature is implemented.
