### ISSUE TITLE
Floating nav bar exists after re-opening from the background

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#14977]
### Expected behavior
In 15.7, if I open the editor for an existing page and close the app (swipe up to force close) and then open the app fresh, it opens to the My Site screen. 
In 15.8, following the same steps, it tried to open it to where I left off, at that open editor. 

### Actual behavior
Hanging nav bar on re-launch. 

### Steps to reproduce the behavior
1. Open WPiOS
2. My Site > Pages > Open a page 
3. Swipe up and force close the app
4. relaunch the app and see floating nav bar. 
I get clusters where I can repro this every time but occasionally it won't. If that happens, do it a few more times and it will. 

https://cloudup.com/ccriRwqzU-z

**Comment by designsimply** [comment]
Odd bug! I tried testing with my iPhone 11 iOS 14 device and couldn't replicate. I'll help keep an eye out for other reports of it. 

Note for later: if we can confirm it as happening in iOS14-only, do add the `iOS 14` label.

**Comment by etoledom** [comment]
Thanks @startuptester for opening the ticket!

This same issue is also described here: https://github.com/wordpress-mobile/WordPress-iOS/issues/14674

**Comment by ceyhun** [comment]
@startuptester just created a PR fixing https://github.com/wordpress-mobile/WordPress-iOS/issues/14674. Can you please check with the installable build here: https://github.com/wordpress-mobile/WordPress-iOS/pull/15012 to see if you can still reproduce it.
