### ISSUE TITLE
Update WPAvatarSource to be more Swift-friendly

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#14996]
### Description

Refactor `WPAvatarSource.parseURL(forAvatarHash:)` so that it doesn't require an inout parameter.

After Suggestions was ported from Obj-C to Swift, the `inout` keyword was used to interface with Obj-C code that uses double pointers (`**`). We should refactor this code to eliminate the need to use `inout`, because there is likely better ways of handling this.

**Comment by kean** [comment]
THe `WPAvatarSource` component was removed in one of recent versions.
