### ISSUE TITLE
Crash: using Free GIF library 

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#14991]
### Expected behavior
A user should be able to search for and choose an image from the GIF free library

### Actual behavior
Crash 

### Steps to reproduce the behavior
1. Insert Image block 
2. Choose Free GIF library 
3. Start typing in search

[crashlog.txt](https://github.com/wordpress-mobile/WordPress-iOS/files/5279935/crashlog.txt)

**Comment by hypest** [comment]
> Tested on iPad 2019, iOS 14, WPiOS 15.8

👋 @startuptester , looking at the crashlog.txt, I notice it mentions `OS Version: iPhone OS 13.7 (17H35)`. Does that mean that the issue happens both on iOS v13.7 and v14?

**Comment by hypest** [comment]
I'm seeing the app crash on the Media library too after typing "cat" in the search and hitting the "done" button or wait a bit for the search to commence automatically.

device: iPhone 6s
iOS: v13.5.1
WPiOS: v15.8

**Comment by startuptester** [comment]
Thanks, @hypest. It was reproducible in both when I logged this but I am now only able to repro it in iOS 13 like you say. I have updated the description. Thanks for your help!

**Comment by hypest** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/15007
