### ISSUE TITLE
Reader: Image links are ignored

### ISSUE THREAD

**Issue by aforcier** [wordpress-mobile/WordPress-iOS#15009]
### Expected behavior

If an image in a post has a link attached, I expect tapping that image in the Reader detail view to open the link.

### Actual behavior

To make all images clickable, [this code](https://github.com/wordpress-mobile/WordPress-iOS/blob/3a26653502ce63186b0a9539a5f852ac52d0edf6/WordPress/Classes/ViewRelated/Reader/Detail/WebView/ReaderWebView.swift#L73) wraps them in a hyperlink. When an image already has a link, this ends up going in between the image tag and its original hyperlink tag, and disabling the original link.

```html
<body class="reader-full-post reader-full-post__story-content">
  <figure class="wp-block-image size-large">
    <a href="https://en.wikipedia.org/wiki/Tree"> // Original link from post
      <a href="https://image.jpg"> // Inserted by ReaderWebView
        <img src="https://image.jpg">
      </a>
    </a>
  </figure>
</body>
```

### Steps to reproduce the behavior

1. On a site you're following in the reader, create a new post
2. Add an image to the post, and set the link property of that image to a custom URL
3. Open that post in the iOS Reader
4. Notice that tapping the image opens the full-size image viewer, instead of opening the link

**Comment by designsimply** [comment]
Tested and confirmed using WPiOS 15.8.0.0 TestFlight beta on iPad Mini 4 (WiFi) (iPad5,1) iPadOS 13.7. Thanks for the report! 

<img src="https://user-images.githubusercontent.com/1119271/94607113-b9a66700-0258-11eb-9e06-6f0b0f7da17e.gif" width="480" alt="15009">
