### ISSUE TITLE
Media details: Share button does not provide a description to VoiceOver in Spanish

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#15003]
The Share Button in Media Details does not seem to be exposed to VoiceOver properly localised.

In English, the Button is read as "button - share" while in Spanish (es_ES) it's read only as "botón" (button)

<Img src="https://user-images.githubusercontent.com/2722505/94392445-dc6a4a00-018a-11eb-898d-9cda3bcd2b99.PNG" width="350" alt="Screenshot of the Media Details screen with the Share button highlighted"/>

### Expected behavior

The Share button in the media details view should provide a description to VoiceOver , so VoiceOver could read it as "button - share", when the system is in Spanish

### Actual behavior
The Share button reads, correctly, as "button - Share" in English, however it read only as "button" (botón) in Spanish

### Steps to reproduce the behavior
* Test on a system localised in Spanish (es_ES)
* Activate VoiceOver
* Navigate to My Site > Pick a site > Media > Select one image > Swipe left once (to reach the Share icon in the navigation bar)
* Notice how the Share icon is read only as "Button" in Spanish. 

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPhone 6s+, iOS 13.7, WPiOS 15.7, es_ES
Tested on iPhone 11 Pro Max, iOS 14.0.1, WPiOS 15.7, en_CA

**Comment by rohanrk** [comment]
Hi there! Could I take a stab at this issue?

**Comment by rohanrk** [comment]
Tried testing this out on my iPad. Looks like neither bar buttons have an accessibility label and both read button in my English voiceover. Accessibility inspector confirms this. I would guess we'd have to create a preferred label for it and add it to Localizable strings for translations

**Comment by shiki** [comment]
Hi @rohanrk! Thanks for contributing. Go for it! I assigned you to the issue. 🙂
