### ISSUE TITLE
Reader doesn't open anchor links correctly, or doesn't scroll to anchor

### ISSUE THREAD

**Issue by hypest** [wordpress-mobile/WordPress-iOS#15017]
### Expected behavior
Tapping on a link that points to an anchor in a different webpage should open that link and scroll to the anchor position.

### Actual behavior
Couple of different behaviors observed:
a. Post is opened but content doesn't scroll to the anchor. That's what folks encounter in this ZD ticket: 3345628
b. Post is not opened. That's what I observed on my iPhone 6s, iOS v13.5.1, WPiOS 15.8 (and 15.6 Internal)

### Steps to reproduce the behavior
1. In the Reader, use the search box and put the URL of a post you know it includes an anchor link
2. Open the post
3. Tap on the anchor link
4. Either nothing happens, or the post is opened but content not scrolled to the anchor position

Example:
[Click here](https://makyo0117.wordpress.com/2019/11/18/shbdt-chuong-1/) and scroll to the bottom of the article.
Click Mục lục  to be taken to an anchor link and a list of chapter/article numbers

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 6s, iOS v13.5.1, WPiOS v15.8 (link not opening case)
iPad Air (3rd gen), iOS 13.6.1 (17G80) (scroll not happening case)

**Comment by designsimply** [comment]
Thanks for the report @hypest! This was fixed recently in the Android app, see https://github.com/wordpress-mobile/WordPress-Android/issues/7654.
