### ISSUE TITLE
Prologue Carousel: extend background behind button view

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#15073]
Project Issue: #15056

The current prologue, `LoginPrologueViewController`, uses two containers to manage the page carousel and the button view. The bottom container holds the button view. The top container holds the carousel.

- [x] extend the container behind the button view

<img width="315" alt="Screen Shot 2020-10-07 at 9 44 36 AM" src="https://user-images.githubusercontent.com/1062444/95346876-e6becf00-0881-11eb-9d66-997bfe40d878.png">

**Comment by designsimply** [comment]
Thank you for including screenshots in your GitHub issues! It makes them easier to follow and I appreciate that. ❤️
