### ISSUE TITLE
UI changes for Interest Picker Screen (in Discover tab)

### ISSUE THREAD

**Issue by mbshakti** [wordpress-mobile/WordPress-iOS#15088]
<img width="317" alt="Screen Shot 2020-10-13 at 12 33 56 PM" src="https://user-images.githubusercontent.com/6350997/95889588-913a6480-0d50-11eb-87d8-3c2c2d55e739.png">

Request 1: Center align screen contents for interest picker within Discover tab

<img width="557" alt="Screen Shot 2020-10-13 at 10 40 19 AM" src="https://user-images.githubusercontent.com/6350997/95889453-69e39780-0d50-11eb-8288-1ba6504c3c07.png">
Request 2: If current spacing is 24px, can we bump it to 32px?

Thank you!

**Comment by mbshakti** [comment]
Thanks for implementing this change as quickly, looking good, @emilylaguna. I noticed two things, both would be "nice to" fix:

1. Can we unsticky the H1 & H2 ("discover and follow blogs you love" & "choose your interests") so that way the user can see more topics as they scroll? Right now, the H1 & H2 take up too much page. When it was full screen, it didn't matter much, but I feel like the space is too small here. 

2. What's the spacing on top of the H1 "Discover and follow blogs.."? It feels a bit tight. Is It 24px right now? If so, can we hike it to 32px (to match the padding bottom)? 

That is all. Part from these 2 things, looks good to me, and we can ship it.

**Comment by emilylaguna** [comment]
> Can we unsticky the H1 & H2 ("discover and follow blogs you love" & "choose your interests") so that way the user can see more topics as they scroll? Right now, the H1 & H2 take up too much page. When it was full screen, it didn't matter much, but I feel like the space is too small here.

Unfortunately that is a pretty big change since I'll need to change how the entire view is structured and works. If this is something we really want to do it'll be in another task. 

> What's the spacing on top of the H1 "Discover and follow blogs.."? It feels a bit tight. Is It 24px right now? If so, can we hike it to 32px (to match the padding bottom)?

The spacing right now is 16px, but I'm worried about increasing the size of it since we'll start running into more vertical space issues like you mentioned above. Thoughts?

**Comment by mbshakti** [comment]
I see. In that case, I'll take a note of this for myself and we can revisit this at some point!

**Comment by mbshakti** [comment]
For the top spacing, can we just bump it to 20px? That should be much, and it will feel slightly less tight.
