### ISSUE TITLE
My Sites > Unable to select the first site in the list (iOS 16.0)

### ISSUE THREAD

**Issue by kyleaparker** [wordpress-mobile/WordPress-iOS#15140]
### Expected behavior

When I navigate to the "My Sites" screen for a moment there is a loading icon towards the top of the page that prevents me from clicking on the first site in the list, I am able to click on any other site though. I wouldn't expect the loading icon to be visible at all at this point, as it appears the sites list has loaded. 

### Actual behavior
Every time I navigate to "My Sites" there is a brief loading animation. Clicking inside the "Search" input also triggers the loading behaviour. 

### Steps to reproduce the behavior
1. In the app click on the My Site icon
2. Notice the loading icon towards the top, while this is spinning try to click on the first site in the list

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 11 Pro 
iOS 14.1
WPiOS 16.0

**Comment by elibud** [comment]
@diegoreymendez @ScoutHarris can you check if this one is fixed as part of the work you are currently doing?

**Comment by ScoutHarris** [comment]
Thanks @elibud . Yes, this is exactly what we're fixing. I'll close this when all the PRs are merged.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/15320 and https://github.com/wordpress-mobile/WordPress-iOS/pull/15325.
