### ISSUE TITLE
Improving Error Messaging for non-English characters in Site Creation Flow

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-iOS#15155]
### Expected behavior

I would expect to be told non-English characters are not supported if I'm using unsupported characters in trying to create a site. 

### Actual behavior

When trying to create a site using a language like Arabic or Chinese, we see the error `No available addresses matching your search` instead. It would be helpful if we could show a message that non-English characters are not supported in site addresses on WordPress.com. 

### Steps to reproduce the behavior

1. Navigate to the site creation flow and add a new WordPress.com site.
2. Use Chinese, Arabic, Hebrew, etc. characters to create a new site address.
3. See the error. 

<img src="https://user-images.githubusercontent.com/10325627/96991464-60141e00-1520-11eb-89ad-cf611271ea0b.jpeg" width="270" alt="IMG_10EA29E2AF13-1">

##### Tested on iPhone X, iOS 13.7, WPiOS 15.9

Internal report: p4a5px-2Ez-p2#comment-11419

**Comment by bummytime** [comment]
On WP.com, this is the error displayed when the `اختبارات` is used as a site name:

<img width="953" alt="Screen Shot 2020-10-23 at 11 18 46 AM" src="https://user-images.githubusercontent.com/154014/97028525-e1b87b80-1521-11eb-8514-0250e36f9d52.png">
