### ISSUE TITLE
Today Widget - Localization and internationalization

### ISSUE THREAD

**Issue by Gio2018** [wordpress-mobile/WordPress-iOS#15157]
Make sure that the localization and translations work properly on the widget.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/15186

**Comment by ScoutHarris** [comment]
For localizations, I had first [shared](https://github.com/wordpress-mobile/WordPress-iOS/pull/15186) WP's `Localizable.strings` with the widget. It worked, except it increases the bundle size too much. So I [reverted](https://github.com/wordpress-mobile/WordPress-iOS/pull/15260) it. Unless/until @wordpress-mobile/platform-9 comes up with a better solution, the translations from the existing [Today widget](https://github.com/wordpress-mobile/WordPress-iOS/tree/develop/WordPress/WordPressTodayWidget) will need to be manually copied to this widget.
