### ISSUE TITLE
Today Widget - Tracks

### ISSUE THREAD

**Issue by Gio2018** [wordpress-mobile/WordPress-iOS#15158]
Add tracks to the Today Widget

**Comment by ScoutHarris** [comment]
Hey @Gio2018 .

One thing I remembered while working on https://github.com/wordpress-mobile/WordPress-iOS/pull/15198. 

The widget tracks don't appear in the Xcode console. However, they do appear in the Tracks Live View. For example, if you search for an existing widget's Event Name, you'll see the results. You can verify the new widget's tracking the same way.
