### ISSUE TITLE
 Unable to search for site content to link to, must paste in URL manually

### ISSUE THREAD

**Issue by ericamQA** [wordpress-mobile/WordPress-iOS#15161]
### Expected behavior

When creating a link, you should be able to search for existing content to link to rather than pasting in the title. 

### Actual behavior

Site Content is not suggested and a URL must be pasted in

### Steps to reproduce the behavior

1. Edit a page or post
2. Select text and tap chain link icon to turn it into a link
3. Start to type the name of another post on the site
4. Site Content is not suggested 

![iOS-15-8-internal-links](https://user-images.githubusercontent.com/44411833/97094553-a1d9bd00-1623-11eb-8279-ed43fc5b2f7b.png)

##### Tested on iPhone 11, iOS 14.0.1, WPiOS 15.8

**Comment by designsimply** [comment]
Thanks for the report @wpericam! The ability to search for existing content was not added until version 1.38 of Gutenberg Mobile (see sidebar [here](https://github.com/wordpress-mobile/gutenberg-mobile/pull/2484)) and that version was shipped with 15.9 of the WPiOS app (you can see which Gutenberg Mobile went out with each release by checking out the [milestone](https://github.com/wordpress-mobile/WordPress-iOS/milestone/172?closed=1) in GitHub—the Gutenberg Mobile release number is usually near the top).

There's no need for you to know this by default though and I was just adding it as a point of interest in case you did want to know how to look it up in the future! You can also always ask in our Slack channels. 😁

I doubled checked the feature using my iPhone 11 iOS 14.0 WPiOS 15.9 (App Store version) and found that it's working as expected. ([2m6s](https://cloudup.com/c6UsBjRcaD6))

If you find any problems with this feature in v15.9 or later, please let me know!
