### ISSUE TITLE
Crash on iPad when sharing a post from the Notifications Tab

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#15169]
The application crashes when sharing a post by clicking the Share button in the navigation bar (top right corner), only on iPad, and only when the Notifications tab is active.

Step 1: Select a Notification
<Img src="https://user-images.githubusercontent.com/2722505/97248027-d32cd580-183b-11eb-959e-584f75517ea1.png" width="350"/>

Step 2: Navigate down until reaching the content of the post
<img src="https://user-images.githubusercontent.com/2722505/97248191-2ef75e80-183c-11eb-9bb6-6357d958d256.png" width="350"/>

Step 3: Tap share
<Img src="https://user-images.githubusercontent.com/2722505/97248260-55b59500-183c-11eb-87bd-ca1cc2fa98c4.png" width="350"/>

### Expected behavior
It should be possible to share a post on iPad when navigating to said post from a Notification

### Actual behavior
The application crashes, on iPad, when trying to do so.

### Steps to reproduce the behavior
0.- On iPad.
1.- Navigate to the Notifications tab (this is important, as this seems to be the only place where the crash happens)
2.- Select one notification that might end up linking to a post (for example, a comment)
3.- Navigate until reaching the actual content of the post
4.- Tap the Share button
5.- The app crashes

The app will not crash when sharing a post if the user reaches the post navigating from Reader.

##### Tested on [device], iOS [version], WPiOS [version]
iPad Pro 11, iOS 14.1, WPiOS 16.0.0.3

**Comment by startuptester** [comment]
I am unable to repro this following the steps in the description on iPad (2019), iOS 14.2, WPiOS 16.3.0.5. 
Also checked in 15.9.

**Comment by designsimply** [comment]
Ditto @startuptester. I could replicate the bug using 16.0.0.3 ([45s](https://cloudup.com/c9dqQBJCRJW)) but not with 16.2.0.5 ([37s](https://cloudup.com/ctlPo1oWLRh)).

Thanks for the report @ctarda! I'll close it since we've tested and couldn't replicate the crash in the latest release.

**Comment by jtpesek** [comment]
****

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
