### ISSUE TITLE
[Xcode 12] Fix miscellaneous build warnings

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#15165]
There are a few random Xcode 12 / iOS 14 build warnings that we should address:

- [x] System Blur Style before iOS 13.0
- [x] Non-Default Vibrancy Style before iOS 13.0
- [x] Plain Style unsupported in a Navigation Item
- [x] MinimumOsVersion of '4.0' is less than the value of IPHONEOS_DEPLOYMENT_TARGET '11.0'
- [x] Backward matching of the unlabeled trailing closure is deprecated; label the argument with 'failure' to suppress this warning
- [x] Implicit conversion from enumeration type 'enum UITableViewStyle' to different enumeration type 'UISplitViewControllerStyle' (aka 'enum UISplitViewControllerStyle')
- [x] The image set name "democover01" (and "democover02") is used by multiple image sets.

The first two appear to be present in `CollapsableHeaderViewController.xib`
The third is in `LayoutPickerStoryboard.storyboard`

**Comment by hypest** [comment]
👋 @guarani , can you have a look here regarding the Gutenberg Integration side of things and share a quick assessment of how many warnings are related to Gutenberg and what do you think the effort/difficulty will be to address them? Asking so we can plan to address them. Thanks!

**Comment by guarani** [comment]
We have lots of Pods that need their deployment target updated, e.g.:
```
The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99.
```
some are forks, some are Gutenberg RN pods, others are regular pods. While we could [fix this in the `Podfile`](https://stackoverflow.com/a/58367269/1305067), the best solution might be to look for new versions of affected Pods (and update our forks).

**Comment by guarani** [comment]
Another warning we've been seeing a lot lately (not directly related to Gutenberg) relates to Core Data:
```
AbstractPost.revisions is using a nil or insecure value transformer. Please switch to NSSecureUnarchiveFromDataTransformerName or a custom NSValueTransformer subclass of NSSecureUnarchiveFromDataTransformer 
```
the fix involves updating the `.xcdatamodel` to use `NSSecureUnarchiveFromDataTransformer`:
```
-        <attribute name="options" optional="YES" attributeType="Transformable"/>
+        <attribute name="options" optional="YES" attributeType="Transformable" valueTransformerName="NSSecureUnarchiveFromDataTransformer"/>
```

Also, as @danielebogo pointed out offline, custom types have to have a custom ValueTransformer (and all your entities must conform to `NSSecureCoding`). 
And as @leandroalonso said offline, we might have to add this change to older data model versions to avoid warnings when running (migration) tests.

**Comment by frosty** [comment]
FYI we have separate issues for both of these items:

- [CocoaPods deployment targets](https://github.com/wordpress-mobile/WordPress-iOS/issues/15164)
- [Core Data transformers](https://github.com/wordpress-mobile/WordPress-iOS/issues/15167)

**Comment by frosty** [comment]
> And as @leandroalonso said offline, we might have to add this change to older data model versions to avoid warnings when running (migration) tests.

I don't think changing older models is a good idea... once they're released, they should generally be left alone. I don't think potentially having some warnings during tests is an issue.

**Comment by guarani** [comment]
> FYI we have separate issues for both of these items:

Good to know! Hadn't looked for an issue.
