### ISSUE TITLE
Today Widget - unconfigured view

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#15178]
On the current Today widget, we have an "unconfigured" view that is displayed when the widget is added but a site to use for widgets has not been selected within the app. Example:

![no_site](https://user-images.githubusercontent.com/1816888/97353742-08e0b700-185a-11eb-8ed9-8f970b9ddc43.jpg)

We need the same sort of view for the Home Today widget.

**Comment by ScoutHarris** [comment]
@mattmiklic - do you have any thoughts on what this would look like for the new Today widget?

**Comment by mattmiklic** [comment]
@ScoutHarris here's the design we should use if the user is logged out of WordPress (pbArwn-116-p2):

![Unconfigured Widget](https://user-images.githubusercontent.com/1396552/97383277-9eecff80-18a3-11eb-8ac3-1c9d160ea4be.png)

Here are the specs for the font color and size:

<img width="921" alt="Screen Shot 2020-10-27 at 10 25 25 PM" src="https://user-images.githubusercontent.com/1396552/97383293-a57b7700-18a3-11eb-81eb-a678fc511114.png">

Regarding having an "unconfigured" state if the user is logged in -- we should avoid this by defaulting to the user's primary site when they add a widget. They can change it to a different site through the system-level widget settings menu:

<img width="970" alt="Screen Shot 2020-10-27 at 10 30 05 PM" src="https://user-images.githubusercontent.com/1396552/97383438-fe4b0f80-18a3-11eb-8c6a-b0b5b1d2fb22.png">

Thus, there shouldn't be any widget configuration inside the app, or the chance for a logged-in user to have a widget that's not set up (more detail here: pbArwn-T7-p2/#comment-1390)

**Comment by ScoutHarris** [comment]
Ah, ok, thanks @mattmiklic !
