### ISSUE TITLE
Today Widget - Show release type in widget name 

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#15177]
On the current Today widget, we display the release type name on the widget to differentiate the widgets between release, alpha, and internal. Example:

![today_internal](https://user-images.githubusercontent.com/1816888/97352357-50664380-1858-11eb-9013-1919f4dd364a.jpg)

We should do the same for the Home Today widget. I propose following the same method, and add alpha and internal to the "Today" label. 

**Alpha:**
<img width="366" alt="alpha" src="https://user-images.githubusercontent.com/1816888/97351661-ae465b80-1857-11eb-9b44-7f823e47e981.png">

**Internal:**
<img width="364" alt="internal" src="https://user-images.githubusercontent.com/1816888/97351689-b8685a00-1857-11eb-8f3e-cc3e22bb807c.png">

**Release:**
<img width="368" alt="release" src="https://user-images.githubusercontent.com/1816888/97351717-bf8f6800-1857-11eb-9bd3-3b3fe22170c1.png">

**Comment by ScoutHarris** [comment]
@mattmiklic - does this work for you?

**Comment by mattmiklic** [comment]
@ScoutHarris I think this sounds fine.

**Comment by Gio2018** [comment]
Closing this one as the release type is included in the app name itself for the widget
