### ISSUE TITLE
Crash in iOS 14 when using Bulgarian or Icelandic keyboards.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#15187]
# Description

The App is crashing when focusing a text field using the Bulgarian or Icelandic keyboards.

Reference: p4a5px-2F1-p2

# Crash reproduction

## Prerequisites

- Make sure your device is running iOS 14.
- Make sure you're logged out before running this test.  It's not specific to the login flow but the steps below use the login flow.

## Steps

1. Add the Bulgarian or Icelandic language as the preferred one in your device.  Make sure the corresponding keyboard is also added.
2. Launch WPiOS
3. Tap "Continue with WordPress.com"
4. Tap on the email field to start writing.  If the Bulgarian / Icelandic keyboard is the selected one the App should crash right away.
5. If the selected keyboard is not Bulgarian / Icelandic, tap on the globe icon in your keyboard until you switch to it.

The app will crash.

**Comment by bjtitus** [comment]
Hey @diegoreymendez, I've been following along with this from Slack since it sounded so crazy! 

I think you also need to set one of these languages as the top preferred language also. If English is the preferred language it was not crashing for me.

<img width="374" alt="Screen Shot 2020-10-29 at 9 39 26 AM" src="https://user-images.githubusercontent.com/3250/97596770-b07cf700-19ca-11eb-9f78-786f1a05a98e.png">

**Comment by diegoreymendez** [comment]
Thanks @bjtitus - I wrongly tried to simplify the testing steps without properly testing them, my bad.  I actually tested this issue by adding the language as you rightly mentioned.

I'm updating the description.

**Comment by diegoreymendez** [comment]
@frosty, @ScoutHarris - I added a very small project showcasing this issue, with validations steps, and a testable workaround.  It's not necessary to check it out but it can give some interesting context around this issue.

It's available here:

https://github.com/diegoreymendez/BulgarianKeyboardCrash

The repo's readme file contains all necessary instructions.
