### ISSUE TITLE
Menus: detail view is cut off on iPhone split view

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#15216]
### Expected behavior
The view should be sized properly in split view.

### Actual behavior
The left side of the view is cut off in split view.

### Steps to reproduce the behavior
On an iPhone with split view (ex: iPhone 11 Pro Max) go to Site > Menu. Rotate the device. Notice the detail view is cut off.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-11-04 at 11 09 11](https://user-images.githubusercontent.com/1816888/98152938-b02fa080-1e8f-11eb-9014-9dceef40c049.png)

On a single view iPhone and on iPad it does display correctly.

**Comment by kean** [comment]
iOS no longer supports split views.
