### ISSUE TITLE
My site: Unable to select first blog in list of My Sites

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#15256]
The first (top) site in the list of sites in the My Sites tab does not react to taps.

<Img src="https://user-images.githubusercontent.com/2722505/98504250-7eed1100-2291-11eb-8142-7bd42490df39.gif" width="350"/>

### Expected behavior
I should be able to select the first (top) site in the list of sites.

### Actual behavior
I can not select the first site in the list of sites. Other sites can be selected.

### Steps to reproduce the behaviour
1. Navigate to My Sites
2. Tap the first site on the list. Nothing happens
3. Tap a different site. The app navigates to the "site details" view (the one that provides access to stats, pages, posts, media...)

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPhone 12 Pro, iOS 14.1, WPiOS 16.1.0.3
Tested on iPhone 12 Pro simulator, iOS 14.1, `develop`

**Comment by guarani** [comment]
I've experienced this too. This is especially annoying when searching for a site and you want to pick the first search result.
A "workaround" is to pull to refresh, and while refresh takes place, tap the first cell 😅.

**Comment by guarani** [comment]
FWIW, there was recent work on the site list refresher here: https://github.com/wordpress-mobile/WordPress-iOS/pull/15136

**Comment by diegoreymendez** [comment]
If you wait long enough, does the cell become tappable again?

That's what I'm seeing here.

**Comment by guarani** [comment]
> If you wait long enough, does the cell become tappable again?
> 
> That's what I'm seeing here.

It depends, if I'm searching for a site and there is one search result, this first cell never becomes tappable (I waited ~20 seconds). If I cancel the search, the first cell is still not tappable, and if I then pull to refresh, the first cell becomes tappable again.

**Comment by startuptester** [comment]
Checked on my iPhone 12 Pro in 16.0, 16.1 and 16.2 (beta)
iOS 14.2 

I am able to reproduce this, but I had to open site details for a different site first, then tap "Switch To" and come back to the list in order to trigger the bug. Repeating those steps, it happens 1/10 times and the cell does not become tappable after at least 1 minute.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/15320 and https://github.com/wordpress-mobile/WordPress-iOS/pull/15325.
