### ISSUE TITLE
View link: sharing a link to the post displays a preview URL instead of the public one

### ISSUE THREAD

**Issue by eduardozulian** [wordpress-mobile/WordPress-iOS#15266]
When you click on the `View` button on published posts is bringing the preview link (ending with ?preview=true) instead of the correct link to the blog post.

### Expected behavior

The actual link to the published post. In my case, `https://eduardoistesting.blog/2020/10/18/testing-the-form-block/`

### Actual behavior

I got a Preview link to `https://eduardoistesting.wordpress.com/2020/10/18/testing-the-form-block/?preview=true`

### Steps to reproduce the behavior

1. Open the app
2. Select a WordPress.com site with a custom domain set to primary
3. Go to your list of posts
4. Click on the View button here: https://d.pr/i/HRMgM6/H5UHEugvhQ
5. Click on the Share link icon on the bottom left
6. Copy the URL or try to share the post on a service (Telegram, WhatsApp, whatever)

**Comment by eduardozulian** [comment]
Now I’m wondering if this is not the expected behavior on newer versions of the app. In this case, if the user really wants to share their public link, they should go to More > Share instead.

**Comment by msilbers** [comment]
> I got a Preview link to https://eduardoistesting.wordpress.com/2020/10/18/testing-the-form-block/?preview=true

I just wanted to note that this is a bigger issue than just the preview parameter being added, as it also doesn't use the site's custom domain that way. Preview links use the underlying subdomain/site address

**Comment by edequalsawesome** [comment]
Also seeing the same behavior in WPiOS 16.1 beta on my iOS 14.2 device -- if there's any other information I can provide, let me know!

**Comment by happychait** [comment]
A customer report in 12134877-hc

**Comment by rezzap** [comment]
There was another use report in 25609324-hc and I was able to replicate the issue myself on iOS 16.0.

**Comment by guarani** [comment]
I also reproduced this on WPiOS 16.0. 

> I just wanted to note that this is a bigger issue than just the preview parameter being added, as it also doesn't use the site's custom domain that way. Preview links use the underlying subdomain/site address

Good point! Apart from the lack of custom domain and presence of `preview=true` at the end of the URL in 16.0, it's also missing:
- Twitter, Facebook and WordPress Like buttons
- related posts

| 15.9 | 16.0 |
| - | - |
| <img src="https://user-images.githubusercontent.com/1898325/99074651-edceb080-2596-11eb-9e41-b961f7d9d16d.jpg" alt="screenshot of 15.9 showing correct preview screen" width="350">  | <img src="https://user-images.githubusercontent.com/1898325/99074127-f4105d00-2595-11eb-858b-901c94438795.jpg" alt="screenshot of 16.0 showing incorrect preview screen" width="350"> |

**Comment by designsimply** [comment]
>  it also doesn't use the site's custom domain that way. Preview links use the underlying subdomain/site address

For reference, a related update was in https://github.com/wordpress-mobile/WordPress-iOS/pull/15061.

> it's also missing:
> Twitter, Facebook and WordPress Like buttons
> related posts

I believe it's expected that "Share this" and "Like" options should not show in a Preview (i.e. viewing a change to a post or page from the editor or viewing a draft) but you would expect those options to show in a View such as when tapping View Site and browsing to an individual post or when tapping View on a published post in the Posts List. In other words, a different view may be expected depending on context (i.e. previewing changes via the Editor vs viewing a published post from View Site or the Posts/Pages list).

The related posts or “More on this topic..” section was recently removed from Reader Detail views (individual posts viewed in the Reader) but that wouldn't affect Previews/Views in other areas of the app would it?

**Comment by guarani** [comment]
> I believe it's expected that "Share this" and "Like" options should not show in a Preview (i.e. viewing a change to a post or page from the editor or viewing a draft) but you would expect those options to show in a View such as when tapping View Site and browsing to an individual post or when tapping View on a published post in the Posts List.

That makes sense, @designsimply — I agree that sharing or liking a preview of a post should not be possible.

> The related posts or “More on this topic..” section was recently removed from Reader Detail views (individual posts viewed in the Reader) but that wouldn't affect Previews/Views in other areas of the app would it?

I'm not sure it would, although I'm not familiar with that change.
