### ISSUE TITLE
UI Tests: Status bar override cuts off first character of date and time

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#15265]
As noted in https://github.com/wordpress-mobile/WordPress-iOS/pull/15108#pullrequestreview-510827441 there's a problem with the status bar override we do in the UI tests (for screenshots).

The `override_status_bar` setting used when generating screenshots should set the simulator date/time to `9:41 AM Tue Jan 9` but it shows `:41 AM ue Jan 9` instead:

<img width="1366" alt="iPad Pro (12 9-inch) (2nd generation)-1-dark-Editor" src="https://user-images.githubusercontent.com/8658164/98711837-6c500600-237d-11eb-9e45-1053ec7ec880.png">

**Comment by jkmassel** [comment]
This _may_ be fixed in Xcode 12.2 – the release version should drop within a couple of days, so we can check then 🙂

**Comment by rachelmcr** [comment]
It turns out the issue here isn't Xcode; it's that we're also using `SimulatorStatusMagic`. Removing that resolves the issue with the status bar. I'll have a PR up for that soon!
