### ISSUE TITLE
Stories: remove "New" badge after the user has seen it X number of times

### ISSUE THREAD

**Issue by megsfulton** [wordpress-mobile/WordPress-iOS#15279]
In the create sheet, we should create a condition so the new badge is only shown a certain number of times. I'm not sure what the limit for that should be. 

Maybe 3 times? Open to suggestions / other thoughts.

**Comment by bjtitus** [comment]
The "New" badge was removed from the stories option in release 17.4 (https://github.com/wordpress-mobile/WordPress-iOS/pull/16421)
