### ISSUE TITLE
Stories: slides exported out of order 

### ISSUE THREAD

**Issue by megsfulton** [wordpress-mobile/WordPress-iOS#15280]
In this story: https://wpstoriesdemo.mystagingwebsite.com/2020/11/11/random-extra-long-story-title-so-very-long-long-long-long-long/

The order in the editor was: 
1 - dog photo (captured with camera in app)
2 - bird video (photo library)
3 - bird photo (photo library)
4 - cat photo (photo library)

The export order ended up being:
1 - cat photo
2 - dog photo
3 - bird video
4 - bird photo

**Comment by bjtitus** [comment]
This should be fixed in build 37660.
