### ISSUE TITLE
Reader Comments: Comment cell can sometimes show an mismatched avatar

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#15285]
We've received a report and an example of a reader comment cell showing a mismatched avatar.  See p1605192953097200-slack-wpmobile.  Per the report it was not able to be reproduced. 

One theory is this is an edge case where a cell is being reused while there is an inflight image download that, when complete, replaces a correct image that had been previously retrieved from the image cache. 

### Steps to reproduce the behavior
Unknown, but likely requires scrolling the comment list with a particular sequence of cells, having those cells be reused in a certain order, with corresponding images cached and not cached. 

We might try canceling any inflight downloads when a cell is reused as a fix and use this issue to track future occurrances.

**Comment by leandroalonso** [comment]
@aerych this was fixed?

Given it's quite an edge case and we haven't been hearing complaints about it I think we might want to close this issue.
