### ISSUE TITLE
Commenting inside the View Site screen requires re-authentication for mapped domains

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#15296]
### Expected behavior

When I visit a site within the app (_Site Screen_ → View Site), I expect to be able to comment on posts/pages. However, if the site has a mapped domain (a.k.a. custom domain), this does not seem possible (or it requires re-authentication).

### Actual behavior

| Un-mapped domain ✅ | Mapped domain ❌ |
| - | - |
| <img src="https://user-images.githubusercontent.com/1898325/99113831-a6fcad00-25ce-11eb-98d6-c7976d53d563.gif" alt="" width="350">  | <img src="https://user-images.githubusercontent.com/1898325/99113521-2ccc2880-25ce-11eb-85c1-95cc99b82ff3.gif" alt="" width="350"> |

### Steps to reproduce the behavior

1. Log into the WPiOS app
2. Choose a site that has a mapped domain (e.g. yoursite.com, not yoursite.wordpress.com)
3. Scroll down the site screen and tap on View Site
4. Try to comment on a post and notice that you'll be asked to log in

### Additional information

Differs from https://github.com/wordpress-mobile/WordPress-iOS/issues/11414 in that this issue relates to the user being unable to comment within the View Site screen for sites on mapped domains. https://github.com/wordpress-mobile/WordPress-iOS/issues/11414 relates to viewing posts on the post list and Reader screens.

**Comment by designsimply** [comment]
/hat tip @inaikem for passing along the report from internal reference 18747941-hc/3483014-zen. 👍

> When I select "Visit Site", it stops recognizing me (likes don't show up and my name/email don't show up on the comments section.

**Comment by rezzap** [comment]
There is another report of this in 3462155-zen 

> There are two scenarios that are problematic since Version 16.0 of the WordPress iOS app was installed on my iPhone. One has to do with when I see a post in my reader on my iPhone and click on "Visit" to go to the actual post. The other is in my Notifications, when, for example, another blogger has created a pingback (linked) to one of my posts and I click on "Read the source post." The issues I'm about to describe don't happen for all posts in my reader or when I read the source post for a pingback, but it does on many, if not most posts.

Issue #1: I can't "like" the posts. When I click "like," on the post, the screen flashes for an instant and then returns to the post I'm trying to "like," but no "like" shows up.

Issue #2: For those same posts, if I try to comment, it doesn't seem to recognize that I'm already logged on to WordPress and asks me to enter my name, email, and website. In some cases, it tells me that must be logged in to post a comment, and when I click on "logged in," it takes me to a page that says "Log in to your account," and shows my avatar and name. When I hit "Continue," it takes me back to the post that I'm trying to make a comment on, but still says that I must be logged in to post a comment.

User has provided some screenshots and recording in the ticket.

**Comment by rezzap** [comment]
I believe there is another report of this here: 3486967-zen

> Regularly it crashes, either that I can no longer put likes, or that I do not know who gave me a like, or that I have to rewrite my coordinates for each comment I send, several on the blog we are going we have his problems we want him to leave WordPress

Translation from French.

**Comment by rezzap** [comment]
Another issue that is linked here, since a viewer is not authenticated in the web view when they click 'visit site' the stats count them as a view. I've replicated this on a Premium plan WordPress.com Public site with a custom domain. 

Reported by a few users in 3491046-zen 
WordPress.com Personal plan, custom domain. 
Public Site

And again in 3490091-zen
WordPress.com Personal plan, custom domain. 
Public Site

**Comment by mdrockwell** [comment]
I believe there is another report of this here: 3492126-zd-woothemes

> Upon 1st opening the app
> -Go to My site
> -View site
> -Read current blog
> -Tap comment
> -Receive “You must login to comment”
> -Log in & receive same “You must be logged in” msg.
> Site does allow us to comment & like if we use the “Reader” view

**Comment by designsimply** [comment]
I moved this to high priority because we have received several user reports about it.

**Comment by guarani** [comment]
Although https://github.com/wordpress-mobile/WordPress-iOS/pull/15309 will potentially address this issue, there are some user reports I'm not sure we've explicitly addressed.

### Can't like or comment source posts from pingbacks

In https://github.com/wordpress-mobile/WordPress-iOS/issues/15296#issuecomment-727184900, the user mentions:

> Also, from my notifications, when other bloggers link back to a prompt post of mine via a pingback and I click on “Read the source post,” it also, for most (but not all) posts it takes me to, but I can’t like or comment on them.

### Stats counting user's own views

In https://github.com/wordpress-mobile/WordPress-iOS/issues/15296#issuecomment-727842323 the user mentions how "View Site" incorrectly counts as a view in Stats. I think https://github.com/wordpress-mobile/WordPress-iOS/pull/15309 will fix this but it we should test it before merging.

I'll loop back here once https://github.com/wordpress-mobile/WordPress-iOS/pull/15309 is ready for review again to check if this issue can be closed once it's merged (cc @aerych).

**Comment by guarani** [comment]
After reviewing #15309, I think it fixes this issue but does not address the two secondary problems I mentioned in the above comment https://github.com/wordpress-mobile/WordPress-iOS/issues/15296#issuecomment-733040126.

@aerych, do you think we should close this issue when #15309 is merged and open separate issues for the pingbacks and stats issues mentioned here or leave this open?

**Comment by aerych** [comment]
> close this issue when #15309 is merged and open separate issues for the pingbacks and stats issues mentioned here or leave this open

I'm a fan of closing and opening specific issues for ping backs and stats.

**Comment by guarani** [comment]
I opened the above two issues for pingbacks and stats.

**Comment by guarani** [comment]
> I'm a fan of closing and opening specific issues for ping backs and stats.

https://github.com/wordpress-mobile/WordPress-iOS/pull/15309 (scheduled to land in WPiOS 16.3) has fixed this specific issue (commenting inside the View Site web view) and we have new issues for other scenarios:
- Not able to like or comment source posts via pingback notification: https://github.com/wordpress-mobile/WordPress-iOS/issues/15386
- Stats getting counted incorrectly due to logged out web views (Jetpack): https://github.com/wordpress-mobile/WordPress-iOS/issues/15388
- Reader "Visit" functionality broken for private sites with mapped domains: https://github.com/wordpress-mobile/WordPress-iOS/issues/15389
- Problems with likes in web views: https://github.com/wordpress-mobile/WordPress-iOS/issues/15390

I'm closing this issue and ideally we can match any user reported issues to one of the above (or create a new issue if there is no match), but feel free to reopen this if you think otherwise.

**Comment by reginabally** [comment]
Another report in 3683399-zen. The screenshot mentioned in the comment below can be found in the ticket.

> When I click on the post link it will bring me to the website i scroll down to like and then it will load wordpress for a very quick sec and nothing happens. You can see at the bottom of the screenshot the wordpress screen that is cut off. Its hard to screen shot the picture because its a matter of a second.

**Comment by guarani** [comment]
> Another report in 3683399-zen. The screenshot mentioned in the comment below can be found in the ticket.

Thanks for the report @reginabally! I took a look at the screenshot and I think this report matches https://github.com/wordpress-mobile/WordPress-iOS/issues/15390, which tracks Likes not working in "View Site" and "View Post" screens. If you agree, would you be able to add your above comment to that issue as well please? 

As for a resolution for this user, we faced a similar situation recently and @aerych's reply to a user's blog post [here](https://href.li/?https://fivedotoh.com/2020/11/03/another-wordpress-bug/#comment-119869) provides a great summary of where things stand with regard to Like functionality in these web view screens on WordPress for iOS (see last three paragraphs of his comment).

**Comment by reginabally** [comment]
Thanks for pointing that out, @guarani! I'll move this report over to  [#15390](https://github.com/wordpress-mobile/WordPress-iOS/issues/15390).
