### ISSUE TITLE
Quick Start: Sharing step is unachievable for Jetpack sites that do not have the Publicize plugin enabled

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#15294]
<img width="375" alt="Screen Shot 2020-11-13 at 1 45 55 PM" src="https://user-images.githubusercontent.com/793774/99109283-6c2e5100-259d-11eb-8c18-c2c561328c89.png">

### Expected behavior
The Quick Start list should only show steps that can be completed for the current site. 

### Actual behavior
For Jetpack sites without the Publicize plugin the Sharing option is not present which means when they are prompted to 'Enable Post Sharing' they are stuck on a step that can not be completed

### Steps to reproduce the behavior
1. Link a Jetpack site that does not have the `Jetpack: Publicize` plugin activated
2. Enable Quick Start for the site, you can do this by doing to `Me > App Settings > Debug > Tools > Enable Quick Start for Site` then selecting the site to test
3. Tap on the 'Grow your Site' item
4. Tap on 'Enable post sharing'
5. You will be prompted to share but no option is available

**Comment by SiobhyB** [comment]
Noting that the sharing step is also shown to users who are logged into a self-hosted site without Jetpack connected.

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
