### ISSUE TITLE
Crash when publishing a post 

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15297]
### Expected behavior
Post publishes without crash

### Actual behavior
Beta users are experiencing a crash 

### Steps to reproduce the behavior
I am not able to reproduce this yet, but this is the crash: 
0  WordPress                     	0x0000000104882420 Swift runtime failure: Unexpectedly found nil while implicitly unwrapping an Optional value + 0
1  WordPress                     	0x0000000104882420 NotificationDetailsViewController.attachSuggestionsViewIfNeeded() + 884
2  WordPress                     	0x00000001048820cc NotificationDetailsViewController.attachSuggestionsViewIfNeeded() + 32
3  WordPress                     	0x0000000104882080 NotificationDetailsViewController.refreshInterface() + 196
4  WordPress                     	0x0000000104881878 NotificationDetailsViewController.viewWillAppear(_:) + 136

##### Tested on iPad (6th generation), iOS 14.1, WPiOS 16.1 (16.1.0.3)

**Comment by mindgraffiti** [comment]
The crash log comes from this issue: https://sentry.io/share/issue/02558ce4c4ee42f6bd3d3936da263663/

And was fixed in this PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/15300
