### ISSUE TITLE
Prepublishing Nudges Categories: Height of bottom sheet doesn't reset when going back from categories view

### ISSUE THREAD

**Issue by emilylaguna** [wordpress-mobile/WordPress-iOS#15305]
### Expected behavior
The PPN view will always be the correct height

### Actual behavior
The PPN view can become clipped or appear too large

#### On a site with 1 or 2 categories:
1. Create a new post
2. Tap the Publish button
3. Tap on the Categories item
4. Swipe down to shrink the bottom sheet
5. Tap back

The bottom sheet will stay "minimized" clipping the PPN content

<img width="30%" alt="Screen Shot 2020-11-16 at 2 59 16 PM" src="https://user-images.githubusercontent.com/793774/99301674-2a9edf80-2803-11eb-94c2-e3a979dc4e00.png">

#### On a site with 10+ categories:
1. Create a new post
2. Tap the Publish button
3. Tap on the Categories item
4. Swipe up to see all the categories
5. Tap back

The bottom sheet will stay maximized

<img width="30%" alt="Screen Shot 2020-11-16 at 3 00 44 PM" src="https://user-images.githubusercontent.com/793774/99301839-65a11300-2803-11eb-8d25-2cbe04facf57.png">

Here's a demo video of these issues: https://cloudup.com/c4sn-A9n4zC

**Comment by bjtitus** [comment]
I tested this on simulator and device and was unable to reproduce the issues shown in the recording following either set of steps. Didn't see a specific commit that might have fixed it but I'm curious is anyone else can reproduce.

**Comment by emilylaguna** [comment]
I did some work on this view end of last year, this may have been fixed by: https://github.com/wordpress-mobile/WordPress-iOS/pull/15551/files

**Comment by kean** [comment]
It was replaced with a native sheet in one of the previous release, and it's no longer an issue.
