### ISSUE TITLE
"View Site" is not working for private sites with a custom domain or free .blog subdomains

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#15306]
Steps to reproduce:

1. Set up a site with a domain that does not end in .wordpress.com.
1. Go to My Site > Settings > Privacy and select "Private".
1. Go to My Site > View Site.
1. If you are prompted to log in, try logging in to view the site.

**Result:** private sites with any domain other than *.wordpress.com prompt you to log in but the login loops back and shows the Protected Blog page with the login prompt again. ([2m7s](https://cloudup.com/c1p95NZlOnb))

<img src="https://user-images.githubusercontent.com/1119271/99301679-2d013980-2803-11eb-86ed-f786235d6668.gif" width="270" alt="private-site-with-custom-domain-cannot-view-site-9s">

Private|Protected Blog|Continue|Protected Blog again
---|---|---|---
![IMG_4683](https://user-images.githubusercontent.com/1119271/99301849-689c0380-2803-11eb-8524-1e2e8efb1994.PNG)|![IMG_4684](https://user-images.githubusercontent.com/1119271/99301847-68036d00-2803-11eb-9514-71f6a736e601.PNG)|![IMG_4685](https://user-images.githubusercontent.com/1119271/99301842-66d24000-2803-11eb-84d4-3f46bb80a923.PNG)|![IMG_4686](https://user-images.githubusercontent.com/1119271/99301830-6174f580-2803-11eb-872b-bd448a9bf6fb.PNG)

<sup>Tested with WPiOS 16.1.0.2 TestFlight beta on iPhone 11 iOS 14.1.</sup>

**Note:** the resolution for this might be the same as for https://github.com/wordpress-mobile/WordPress-iOS/issues/15296 but I've filed a separate issue just in case. cc @guarani @aerych 

This was reported in the following help request: 

> I'm not able to us the 'View Site' feature. As my blog is private, tapping on 'View Site' takes me to the 'Protected Blog' page where I tap 'Log in here'. Then I'm taken to the 'Log into your account' page, which correctly shows my name and profile picture, but when I press 'Continue' I'm taken back to the 'Protected Blog' page. I've cleared my cookies and cache on the iPhone with no success. My blog is working perfectly on the web.

* WordPress.com Personal
* Device model: iPhone SE 2020 (not to be confused with the original iPhone SE discontinued in 2018)
* iOS version: 14.2
* WordPress app version: 16.0

/hat tip @rezzap for reporting the issue in Slack. (internal reference: 3484471-zen)

**Comment by designsimply** [comment]
I think https://github.com/wordpress-mobile/WordPress-iOS/issues/15306 might fix this problem. 🤞

**Comment by guarani** [comment]
> I think #15306 might fix this problem. 🤞

👋 That link should be https://github.com/wordpress-mobile/WordPress-iOS/pull/15309, right? I agree that #15309 should fix this, will check!

**Comment by designsimply** [comment]
Yes, #15309 🤦‍♀️ thank you!

**Comment by yaelirub** [comment]
Hello 👋  @guarani , can we close this issue?

**Comment by guarani** [comment]
Yes @yaelirub! Thanks for catching this. I double checked by testing 16.3 beta (16.3.0.2) and I could Visit Site on private sites with mapped domains 😄.
So I'll close this now since https://github.com/wordpress-mobile/WordPress-iOS/pull/15309 fixed it 🎉
