### ISSUE TITLE
Site creation preview shows cut-off site header

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#15313]
### Expected behavior

The preview of a newly created site shouldn't have cut-off sections.

### Actual behavior

After creating a site in the app, the site preview is shown but the top of the site is cut-off.

| <img src="https://user-images.githubusercontent.com/1898325/99396448-84b1aa80-28c0-11eb-81c0-e47838f27cc2.jpg" alt="Screenshot showing cut-off site preview" width="350"> |
| - |

### Steps to reproduce the behavior

1. Start the "Create WordPress.com site" wizard (either after the creation of a new WP.com account or from the site list when logged in)
2. Create a Blank Site (although this issue might be present for other types of sites)
3. On the "Your site has been created!" screen, notice that the top of the preview is cut-off

### Additional info

This issue is also present on WPAndroid https://github.com/wordpress-mobile/WordPress-Android/issues/13410

**Comment by designsimply** [comment]
Noting this should be fixed with a combination of https://github.com/wordpress-mobile/WordPress-iOS/pull/15303 and internal reference D53196-code (background: pbMoDN-1A9-p2#comment-3222). Props @chipsnyder @enejb. 🎉

**Comment by chipsnyder** [comment]
There is some code clean up that might be able to happen thanks to these changes. Spun up a new issue to track the investigation I would like todo in order to remove those items: 

https://github.com/wordpress-mobile/WordPress-iOS/issues/15411
