### ISSUE TITLE
Activating a theme does not close the preview or disable the "Activate" button

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15329]
### Expected behavior
I expect activation to look like something is installing and then the preview to close.

### Actual behavior
1. During activation, there is no user feedback, so I do not actually know anything is happening and I am likely to keep tapping the Activate button. (The video is a bit faster, actual time of seemingly no action is about 7 seconds). 
2. It stays open and the Activate button is still enabled, so even though I got the message thanking me for choosing the theme, I still feel like it didn't work and I need to tap the button again. 

### Steps to reproduce the behavior
https://cloudup.com/cPSa1glnLMw

**Comment by designsimply** [comment]
Tested and confirmed using WPiOS 16.2.0.0 TestFlight beta on iPhone 11 iOS 14.1. 

I noticed the theme _is_ activated but the modal window is not dismissed afterward (the "Activate" link in the overflow menu that triggers a bottomsheet selector works normally though).

**Comment by yaelirub** [comment]
I looked into this issue and tried to come up with a simple design solution on the client side. Displaying a loader in the activate button while loading looked ok but didn't work well with long theme titles.

Another solution that came to mind is displaying a top banner like the one we show in the editor when performing an action on a block ("block copied") with "Activating theme..."

I think we need a design solution here.
cc: @iamthomasbishop , @kyleaparker , @chipsnyder

**Comment by iamthomasbishop** [comment]
> Displaying a loader in the activate button while loading looked ok but didn't work well with long theme titles.

My suggestion would also be a loader (the standard iOS-style spinner/loader) shown while waiting. What type of loader did you try @yaelirub? Maybe I'm missing something, but I would think a spinner would work well because it is probably narrower than the text label. 🤔

**Comment by yaelirub** [comment]
Hey @iamthomasbishop , thanks for the input. That's what I did  but it didn't look great. I'll work on improving that
