### ISSUE TITLE
EXC_BREAKPOINT: bvx2

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15333]
**Sentry Url**: https://sentry.io/share/issue/611bd7342e4e4a8882f57ea636958805/
**User Count**: 835
**Count**: 1769
**First Release**: 16.0.0.0
**First Seen**: 2020-10-21T00:25:04Z
**Last Seen**: 2020-11-19T05:31:45Z
**24 Hours**: 172
**30 Days**: 1761
**LogID:** 5E783C30-D0D6-4CD6-848D-3B0272B51D85

```
EXC_BREAKPOINT: bvx2
  File "GutenbergViewController.swift", line null, in value
  File "GutenbergViewController.swift", line 346, in GutenbergViewController.viewDidLoad
  File "GutenbergViewController.swift", line 346, in GutenbergViewController.viewDidLoad
  File "BlogJetpackSettingsService.swift", line 67, in BlogJetpackSettingsService.syncJetpackSettingsForBlog
  File "<compiler-generated>", line null, in BlogJetpackSettingsService.syncJetpackSettingsForBlog
  File "<compiler-generated>", line null, in @callee_guaranteed
  File "main.swift", line 7, in main
...
(10 additional frame(s) were not displayed)
```

**Comment by renanferrari** [comment]
I'm not totally sure about this one, but going by the Sentry logs this seems to be an issue around a call to `BlogJetpackSettingsService::syncJetpackSettingsForBlog` inside the `GutenbergViewController` class. 

@yaelirub Would you mind taking a look at this? It seems like you have worked around this area of the codebase recently, so you probably have the necessary context to evaluate this better than me.

I'm labeling this issue as medium priority ([high severity, low impact](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/docs/issue-triage.md#prioritization)) but feel free to change it as you see fit.

**Comment by yaelirub** [comment]
Did I just completely drop the ball on this one?? 😨 
I don't believe this is related to the Jetpack section. The change in GutenbergViewController was for a reference to a renamed class.
@etoledom , could this be related in anyway to https://github.com/wordpress-mobile/WordPress-iOS/pull/15380 ?

**Comment by designsimply** [comment]
I checked this issue in Sentry and found that 98.27% of cases recorded in the last 90 days were in 16.0.0.6 and 16.1.1.0 and there were only 2 total cases recorded in 16.2 which was released 11 days ago on 2020-11-30.

I am inclined to close this issue with an ask to re-open if the crash numbers increase again or if it shows up in another Sentry issue for some reason.

<sub>WORDPRESS-IOS-396D: https://sentry.io/share/issue/611bd7342e4e4a8882f57ea636958805/</sub>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1969669577&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101952985-c8918a00-3bb6-11eb-8ae3-308c2cda4dd2.png)</a>

<a href="https://sentry.io/organizations/a8c/discover/results/?display=daily&field=timestamp&field=release&field=os&field=device&field=culprit&name=All+Events&project=1438083&query=issue.id%3A1969669577+release%3A16.2%2A&sort=-timestamp&statsPeriod=90d&widths=-1&widths=-1&widths=-1&widths=-1&widths=-1">![image](https://user-images.githubusercontent.com/1119271/101952931-b283c980-3bb6-11eb-976d-7f0c01a68486.png)</a>
