### ISSUE TITLE
Reader Comments: missing and outsized emoji

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#15341]
### Expected behavior
All emoji load, instead of a gray box appearing, and when it loads, it shows up as the correct size.

### Actual behavior
Some emoji show up as a large gray box. Some emoji load but as large blurry photos.

### Steps to reproduce the behavior
1. Navigate to Notifications > "liked your comment" > Comment. The `twemoji` images are too big.
2. Navigate to Reader > Following > choose a post with comments > view comments. The `twemoji` explode.

### Screenshots
| First example | Second |
| --- | --- |
| ![IMG_5265](https://user-images.githubusercontent.com/1062444/99719435-e5ccb000-2a71-11eb-8772-0c0ebbcce024.PNG) | ![IMG_5266](https://user-images.githubusercontent.com/1062444/99719431-e49b8300-2a71-11eb-9766-5c2ba5bd13d3.PNG) |

**Comment by startuptester** [comment]
Sent to groundskeeping

**Comment by mindgraffiti** [comment]
Tentatively adding as part of the P2 Improvements project as an optional bug to tackle.

**Comment by mindgraffiti** [comment]
Possibly related issue https://github.com/Automattic/wp-calypso/issues/47807
