### ISSUE TITLE
Quick Start guidance in the Reader

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15351]
### Expected behavior
The Quick Start guidance really doesn't show a user what to do in the Reader or show off the many new improvements. 

### Actual behavior
It tells me to follow a site, but doesn't show me how to do that and even after I navigate it myself, the Grow Your Audience > Follow Other Sites steps isn't completed. 

https://cloudup.com/cZhOp8vJ-dl

### Steps to reproduce the behavior
1. Login with a new email address and accept Quick Start guidance to set up a new site 
2. On the My Site screen, choose Grow Your Audience and then Follow Other Sites
3. See where the guidance takes you, it leaves you at the opened Reader

**Comment by yaelirub** [comment]
@bjtitus , can you please take a look at this? For a quick fix I recommend we either show the notice higher than the FAB, or reduce the height and font of the notice.

I think I've seen this issue of the notice covering the FAB in other places too so maybe we should think of a different way or style for presenting the instructions

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
