### ISSUE TITLE
Reader: Followed Sites: Mark all as seen

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#15357]
- [ ] Design TBD.
- [ ] Get clarity on the design
- [x] Discover: what does it mean to "Mark all as seen"? Does that only mark **posts** as seen? Comments? Mentions? - The "Mark as seen" button affects only **post counts.** It does not affect comment counts, nor does it affect mentions.
- [ ] Discover: are we scoping this to "Mark all as seen" for all sites and for a single site?
- [ ] Calypso alignment: Do not release until 16.4 or later.

As a P2 user, I expect parity between the web and mobile for key features. 

On the web I can go to Reader > Followed Sites (All) and Mark all as seen:
<img width="1144" alt="Screen Shot 2020-11-20 at 8 56 33 AM" src="https://user-images.githubusercontent.com/1062444/99822233-942b3080-2b18-11eb-93e7-dca6fc09f9ce.png">

On the web I can go to Reader > (Single followed site) and "Mark all as seen". This marks all of the **posts** as seen.
<img width="304" alt="Screen Shot 2020-11-20 at 10 15 48 AM" src="https://user-images.githubusercontent.com/1062444/99823020-7d390e00-2b19-11eb-8e11-c62f917d4a0c.png">

**Comment by ScoutHarris** [comment]
Closing this for now since we're not ready to do it yet. Will recreate issue when we get there.
