### ISSUE TITLE
Reader: Add unread counts

### ISSUE THREAD

**Issue by mindgraffiti** [wordpress-mobile/WordPress-iOS#15354]
### Project Issue

Ref. pbArwn-1p9-p2#comment-2018 

As a user, I want to see the unread counts for posts, comments, and mentions of my username in the Reader section of the app.

- [ ] unread count for posts - https://github.com/wordpress-mobile/WordPress-iOS/issues/15483
- [ ] unread count for comments
- [ ] unread count for mentions

### Context on the web

In the new P2 design, there are unread counts for posts, comments, and mentions. Here is what is looks like on the web:

<img width="419" alt="Screen Shot 2020-11-20 at 8 58 55 AM" src="https://user-images.githubusercontent.com/1062444/99814586-c9328580-2b0e-11eb-81c8-488e052bc4f0.png">

### Designs for mobile:

![unread-counts-1](https://user-images.githubusercontent.com/1062444/100663430-df64f080-331b-11eb-9893-bd650dca8ea9.png)
![unread-counts-specs](https://user-images.githubusercontent.com/1062444/100663439-e2f87780-331b-11eb-87f0-161e85b66b43.png)

**Comment by ScoutHarris** [comment]
From Slack convo: Unread count -> currently returned for followed sites under `/read/following/mine` as `unseen_count`.

**Comment by mindgraffiti** [comment]
Closing this one to keep the noise down. We don't have details on unread comments or unread mentions at this time. We'll open new tickets for those if/when there is more info.
