### ISSUE TITLE
Reader: cannot unsave post from Saved filter

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#15381]
### Expected behavior
If a post is unsaved from the Saved filter, it should remain unsaved.

### Actual behavior
If a post is unsaved from the Saved filter, it remains saved. If it is unsaved from another filter, it is then unsaved.

### Steps to reproduce the behavior
- Save a post from a feed, say Following.
- Go to Saved. Unsave the post.
- Go back to Following. Note the post is marked as saved.
- Go back to Saved. The post reappears there.
- Go back to Following. Unsave the post.
- Go back to Saved. The post no longer appears.

![post_saving](https://user-images.githubusercontent.com/1816888/100135170-7e827780-2e46-11eb-8c37-782016cefdbe.gif)

**Comment by rezzap** [comment]
There was another report of this in 3571129-zen

I'll let the user know we're working on a fix.
