### ISSUE TITLE
Latest Post Summary "An Error Occurred" if there are no posts

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15401]
### Expected behavior
If the site has no previous posts, I would expect it to say “You haven’t published any posts yet.” or something like that

### Actual behavior

It says "an error occurred" 

![image](https://user-images.githubusercontent.com/66104034/100393739-f2b04d00-2ff7-11eb-8287-0c6588d76ca3.png)

Also the widgets in iOS say "Unable to Load" and there is no ability to refresh the widget

![image](https://user-images.githubusercontent.com/66104034/100394036-ef699100-2ff8-11eb-900f-396015bcad97.png)

### Steps to reproduce the behavior
1. Login with site that does not have any published posts
2. Open Stats
3. Notice the error under Latest Post Summary

**Comment by ScoutHarris** [comment]
@startuptester I've fixed the Latest Post Summary on #16074 . The widget problem was discussed in Slack (after this issue was created) and was determined to be an iOS bug, so I'm ignoring that part.
