### ISSUE TITLE
Like and Save not working in Reader Discover

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#15417]
### Expected behavior

When I Like or Save (bookmark) a post within the Reader post screen (Reader → Discover tab → tap on a post → land on full-screen post screen), the Like or Save button should stay blue (i.e. persist) when I navigate to the previous screen or other parts of the app.

### Actual behavior

When I Like or Save (bookmark) a post within the Reader post screen (Reader → Discover tab → tap on a post → land on full-screen post screen), tap the Like or Save button and navigate back to the previous screen or other parts of the app, the post is no longer Liked or Saved.

| <img src="https://user-images.githubusercontent.com/1898325/100746800-f4935b00-33bf-11eb-9d30-455b970332e9.gif" alt="Screen recording showing Like and Save button actions not persisting when navigating to other parts of the app." width="350"> |
| - |

### Steps to reproduce the behavior

1. Open the Reader
2. Open the Discover tab (the bug isn't present in the Following tab)
3. Tap any post and expect the post is displayed in a new screen
4. Tap the Like or Save buttons at the bottom of the screen
5. Navigate back to the previous screen, locate the liked or saved post, observe that the relevant button is un-selected (it should be blue indicating the previous Like or Save action)

**Comment by leandroalonso** [comment]
The issue doesn't happen anymore.
