### ISSUE TITLE
Status bar icons invisible in Reader

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#15458]
### Expected behavior

The status bar icons should always be visible.

### Actual behavior

The status bar icons are invisible in the Reader when viewing content.

### Steps to reproduce the behavior

1. Go to the Reader tab
2. Tap on a Post or Page to view it full-screen
3. Notice the lack of status bar icons

| <img src="https://user-images.githubusercontent.com/1898325/101658926-45d8c580-3a24-11eb-98f6-c412a0fdd564.gif" alt="Screen recording showing lack of status bar on Reader screens when viewing posts or pages" width="350">  |
| - |

**Comment by startuptester** [comment]
Closing because it was fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/15459
