### ISSUE TITLE
Improve behavior of pull to refresh in Media Library

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15469]
### Current behavior

The pull-to-refresh control in the media library disappears instantly if local Media items are available. This is due to the call to `success` in `loadDataWithOptions:success:failure:` in `MediaLibraryPickerDataSource`. We then continue to perform a network request in the background.

### Ideal behavior

It would be better for user experience if the control stayed visible while the network requests complete. This would make it easier to understand what's happening in the process of refreshing the media library.

### Steps to reproduce the behavior

1. Navigate to media library and swipe down to refresh the images

**Comment by kean** [comment]
Fixed in the scope of https://github.com/wordpress-mobile/WordPress-iOS/issues/21457; shipping in 23.7.
