### ISSUE TITLE
Mention screen not displaying likes on comments

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#15488]
### Expected behavior

When I'm mentioned in a comment and I tap the notification in the app, I get shown a Mentions screen with a Like button. If I've already liked the comment (e.g. via the web), the Like button should be rendered already-set (filled blue icon).

### Actual behavior

The Like button behaves as if I have not liked the comment (it's rendered in its off state (gray outline icon).

### Steps to reproduce the behavior

1. In the Notifications tab locate a comment where someone has @-mentioned you and you have already liked their comment
2. Tap that comment and the app shows the "Mention" screen
3. Notice that the Like button does not reflect the fact that you've already liked the comment

**Comment by aerych** [comment]
I'm seeing this same behavior on the web.  A number of comments I've liked are not showing as liked in the notification screen.  This is potentially related to some recent updates to p2 likes. It could also be an issue with how the notifications endpoint caches data. More investigation is needed. 
Asking in p1618430158119600-slack-automattic

**Comment by alpavanoglu** [comment]
The issue wasn't platform specific and seem to be fixed. I tested this case on `trunk` and the like count was already 1 when I viewed the details screen.
