### ISSUE TITLE
Navigating to comment replies not working in Notifications

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#15487]
### Expected behavior

When viewing someone's reply to a comment of mine, tapping the "You replied to this comment." button (if present) should take me to my reply to their comment. It could also highlight my reply, just as it does on WPAndroid.

### Actual behavior

When viewing someone's reply to a comment of mine, tapping the "You replied to this comment." button takes me to the first comment on the post, and I have to manually scroll down to locate my reply.

### Steps to reproduce the behavior

1. In the Notifications tab
2. Locate a reply to a comment of yours to which you have already replied 
3. Tap the Notification and the reply from someone else will be shown on a separate screen
4. Tap the "You replied to this comment." button and notice that you are not scrolled to your reply, instead you're navigated to the post's comments without being auto-scrolled to the particular reply in question

### Additional information

On the Reply screen, the link to the original reply doesn't work either (this deserves its own issue).

**Comment by aerych** [comment]
Dup of https://github.com/wordpress-mobile/WordPress-iOS/issues/5540

**Comment by guarani** [comment]
Thanks for spotting @aerych! I'm closing this now.
