### ISSUE TITLE
Reader site filters: remove filter tab bar for P2s and A8C

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#15496]
With https://github.com/wordpress-mobile/WordPress-iOS/pull/15484, the `Filter` option was added to P2 and A8C streams to filter by site. 

Previously, the Filter was only used for Following, which allows filtering by Site and Topic. P2 and A8C only allow Site filtering. Making the filter tab bar in that view unnecessary.

| Following | P2s |
|--------|-------|
| <img width="438" alt="Screen Shot 2020-12-14 at 5 29 19 PM" src="https://user-images.githubusercontent.com/1816888/102152307-f8989180-3e31-11eb-852c-a697e5b60ad5.png"> | <img width="439" alt="Screen Shot 2020-12-14 at 5 29 32 PM" src="https://user-images.githubusercontent.com/1816888/102152327-00583600-3e32-11eb-817c-a1f29d3365e9.png"> |

We should remove the filter tab bar for P2 and A8C (as [requested](https://github.com/wordpress-mobile/WordPress-iOS/pull/15484#issuecomment-744859379) by @mattmiklic).

**Comment by ScoutHarris** [comment]
Hey @mattmiklic .

Question please. With the filter tab bar removed, we no longer have a count. 

| <img width="337" alt="Screen Shot 2021-03-08 at 5 39 24 PM" src="https://user-images.githubusercontent.com/1816888/110401131-40e0dd80-8036-11eb-9428-a21a777fd387.png"> | <img width="339" alt="Screen Shot 2021-03-08 at 5 38 27 PM" src="https://user-images.githubusercontent.com/1816888/110401143-46d6be80-8036-11eb-9905-bccdda5d6f98.png"> |
|--------|-------|

Is that acceptable, or would we want to put the count with the stream title (ex: `Automattic (33)`)?

**Comment by mattmiklic** [comment]
> Is that acceptable

@ScoutHarris Yeah, I think this makes sense.

**Comment by ScoutHarris** [comment]
@khaykov @develric I noticed Android has this same issue. Just bringing it to your attention that we've removed it from iOS.

**Comment by develric** [comment]
Thanks for the ping @ScoutHarris 🙇  ! [Issue created](https://github.com/wordpress-mobile/WordPress-Android/issues/14246) and added to the Android P2 project 👍   (cc @khaykov )
