### ISSUE TITLE
Status bar icons invisible on some screens

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#15506]
### Expected behavior

The status bar icons should always be visible.

### Actual behavior

The status bar icons are invisible in some parts of the app (e.g. when tapping on a notification for a post that I'm subscribed to).

### Steps to reproduce the behavior

1. Go to the Notifications tab
2. Tap on a Notification for a post on a site you're subscribed to
3. Notice the lack of status bar icons

### Additional information

This is similar to https://github.com/wordpress-mobile/WordPress-iOS/issues/15458 but covers any part of the app including Notifications screens, whereas that issue was solely focused on Reader screens.

**Comment by startuptester** [comment]
@emilylaguna  didn't you work on this recently?

**Comment by emilylaguna** [comment]
👋 @startuptester I did, but it was a slightly different issue. I have this on my list of things to look into today and will hopefully have a quick PR for it.

**Comment by emilylaguna** [comment]
Reopening because I reverted the change: https://github.com/wordpress-mobile/WordPress-iOS/pull/15607
