### ISSUE TITLE
image in WPRichContentView show gray shadow at Xcode12

### ISSUE THREAD

**Issue by chengjingfeng** [wordpress-mobile/WordPress-iOS#15501]
### Expected behavior
image should not show shadow 

### Actual behavior
image show shadow 

### Steps to reproduce the behavior
use WPRichContentView to display html content.  when it build and run by xcode12, the images in WPRichContentView show gray shadow.

the same code build and run by Xcode10, it did not show gray shadow.

![IMG_2997](https://user-images.githubusercontent.com/8434766/102179042-71a2f200-3ee1-11eb-88cc-c09ca176ccbc.PNG)

**Comment by chengjingfeng** [comment]
Is it a bug of Xocde12? or should I update the code for Xcode12？

**Comment by chengjingfeng** [comment]
hope someone can help me

**Comment by designsimply** [comment]
This is possibly a silly question, but can you tell me steps for how to use WPRichContentView to display html content? I'm not quite sure how to do that. I help out with testing on the iOS app from time to time, and I wasn't sure how to do the steps you provided in your post.
