### ISSUE TITLE
Publish Button is cut off / goes off the bottom edge of the screen

### ISSUE THREAD

**Issue by supernovia** [wordpress-mobile/WordPress-iOS#15511]
### Expected behavior
To be able to see the full publish button, or scroll to it

### Actual behavior
The publish button goes off the bottom of the screen and can't be accessed easily

![ios publish screen](https://user-images.githubusercontent.com/3476361/102287347-7a9ebe00-3ef7-11eb-8fa2-d1de6e2e5d88.png)

### Steps to reproduce the behavior
- Create a new post
- Click Publish
- Note a post settings screen comes up with "Publish New" at the bottom, but it's cut off. I was not able to scroll down.

##### Tested on [device], iOS [version], WPiOS [version]
iPhone SE, 14.2, 16.2

Mentioned in a tweet here:
https://twitter.com/ljpuk/status/1338925898926534660

(they are using iOS 14.3)

**Comment by reginabally** [comment]
I've tested this with an iPhone SE (MX9R2MY/A), iOS 14.2, and WPiOS 16.2. I'm able to see the text but the bottom of the bottom looks cut off too.

![IMG_A1672B6EC55E-1](https://user-images.githubusercontent.com/40906847/102317853-47216980-3fb3-11eb-8483-d2f895262815.jpeg)
