### ISSUE TITLE
Following button on Reader screen jumps into place as screen loads

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#15510]
### Expected behavior

Navigating to the Reader screen should show the Following button in its correct position (on screen).

### Actual behavior

Sometimes, the Following button starts slightly off-screen and jumps into place as the screen loads. I reproduced this on an account where I follow a lot of sites, and couldn't reproduce on a site where I only follow one or two sites.

### Steps to reproduce the behavior

1. Log into the app using an account that follows many sites (e.g. a dozen or more)
2. Tap the Reader tab bar button
3. Notice the Following button starts off-screen and jumps into place as the screen loads

<img src="https://user-images.githubusercontent.com/1898325/102280452-f0ad2000-3f0b-11eb-8f84-02a3e9bf9cb3.gif" alt="Reader follow button jumping into place" width="350">

**Comment by fluiddot** [comment]
I managed to reproduce this issue in current production version `16.3` too, but it only happens the first time I navigate to the Reader tab upon opening the app.

**Tested on iPhone 8, iOS 14.0, WPiOS 16.3**

<img width=300 src=https://user-images.githubusercontent.com/14905380/102327844-98673400-3f86-11eb-81b0-fd62bf71f255.gif>

**Comment by startuptester** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/15513
