### ISSUE TITLE
Publish Now/Schedule Now button is cut off on iPad

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15529]
### Expected behavior
full button displayed, no scroll

### Actual behavior
the button is cut off and the window is scrollable since adding Categories to this window

![IMG_47AC64851346-1](https://user-images.githubusercontent.com/66104034/102412026-27d50d00-3fb0-11eb-90f7-841143590de5.jpeg)
![IMG_0032](https://user-images.githubusercontent.com/66104034/102412030-299ed080-3fb0-11eb-89cf-67664a66818f.PNG)

### Steps to reproduce the behavior
1. Edit a draft or create a new post 
2. Click on the "..."
3. Select Publish and view the button

**Comment by startuptester** [comment]
oops, closing as duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/15511

**Comment by designsimply** [comment]
I can see the scrollbar on the right when prepublishing nudges first opens, then it fades out. I don't see the publish/schedule button being cut off.

<img src="https://user-images.githubusercontent.com/1119271/102414956-97e59200-3fb4-11eb-958a-235f5879a15d.PNG" width="330" alt="IMG_0575"> <img src="https://user-images.githubusercontent.com/1119271/102414950-96b46500-3fb4-11eb-99ca-ee5b43a41980.PNG" width="330" alt="IMG_0576">

<sup>Tested with WPiOS 16.4.0.0 TestFlight beta on iPad mini 4 iOS 14.2.</sup>
