### ISSUE TITLE
Site Creation: site name selection disappears if selected before list is done loading

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15541]
### Expected behavior
Selection made while loading site name options should remain after the loading is done

### Actual behavior
The selection and its option, also the confirmation button are gone

### Steps to reproduce the behavior

1. I choose a design
2. it says ‘Choose a domain’
3. in the field, I typed some letters
4. A spinner is shown in place of the search icon while it is finding domains
5. I selected a domain before it finished spinning
6. Initially, I could see my domain, with a selected blue checkmark, and a button to claim it
7. However, when the loading completed, I could no longer see that domain and the button disappeared

Screenshot 1: typed dhhdhe and selected a domain
![image](https://user-images.githubusercontent.com/66104034/102645244-676e3700-411f-11eb-8a7c-f4303ce0fa12.png)

Screenshot 2: I have not taken any further action, the loading just completed, but the d106.home.blog selection that I made has disappeared along with the confirmation button.
![image](https://user-images.githubusercontent.com/66104034/102645277-7359f900-411f-11eb-9129-89085d204b45.png)

**Comment by chipsnyder** [comment]
Thanks for bringing this up @startuptester! This should be solved as part of https://github.com/wordpress-mobile/WordPress-iOS/pull/15482
