### ISSUE TITLE
Reader Enhancement: Automatically pull tags for featured content based on recently published posts.

### ISSUE THREAD

**Issue by rezzap** [wordpress-mobile/WordPress-iOS#15556]
> In “Reader > Discovery” tab there is “followed topics” section. User can add some tags for automatic blogs and posts suggestions.
> 
> It would be nice if “followed topics” could be populated automatically. For example by tags from “my site’s” posts published in last 4 weeks.
> 
> Authors who published posts about some topic could easily find other blogs which publishing the same topics. 

From a forum post: https://ios.forums.wordpress.org/topic/discovery-tab-in-reader-include-tags-from-my-site%e2%80%99s-tags?replies=1#post-15774

**Comment by designsimply** [comment]
<sup>(internal reference: p9xfpQ-1cO-p2#comment-2884)</sup>

**Comment by leandroalonso** [comment]
Hi @rezzap! Thanks for sharing the user's feedback here.

As for now, we don't have plans to include this feature in the Reader in the near future. Please let us know if more users request that feature, we can always reassess it.
