### ISSUE TITLE
Unable to select a .blog subdomain

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-iOS#15553]
### Expected behavior

I would expect to be able to select a .blog subdomain regardless of whether I'm choosing a homepage design when creating a new site.

### Actual behavior

If I skip the homepage design picker or select a certain homepage design (the first or the second in the list), I can only select a WordPress.com subdomain. I can select a .blog subdomain when I choose the third or the fourth homepage design.

### Steps to reproduce the behavior

1. Go to My Site > Switch Site > "+" > Create WordPress.com site
2. Tap "SKIP" to skip choosing a homepage design
3. Type a keyword to search for a site address, e.g. testsite20201222
4. See that the available options are WordPress.com subdomains
5. Go back to the homepage design selection screen, select the first or second design in the list
6. See that the available options are WordPress.com subdomains
7. Go back to the homepage design selection screen again, select the third or the fourth design in the list
8. See that the available options are .blog subdomains.

Screen recording: https://d.pr/v/Ki2Zyy/quPQnNKLmm

**Comment by chipsnyder** [comment]
Added this to the Gutenpages project we'll look at getting this addressed with the other Site creation enhancements 

https://github.com/wordpress-mobile/WordPress-Android/issues/13653#issuecomment-755417943

**Comment by ericamQA** [comment]
Another request in 3687540-zen

**Comment by chipsnyder** [comment]
This is taken care of in https://github.com/wordpress-mobile/WordPress-iOS/pull/15736
