### ISSUE TITLE
Reader filters cause Discover tab to take over Following tab

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15649]
### Expected behavior
Reader filters should persist while in the app

### Actual behavior
If you filter on the Following tab, then change to the Discover tab, the Discover tab persists on the Following tab. 

https://cloudup.com/c4UJjpDpdSu

### Steps to reproduce the behavior
1. In Reader, filter for a certain site
2. Note that the filter works correctly
3. Switch to the Discover tab and then back to the Following tab
4. Notice that the Following tab has the filter you applied, plus the Discover tab content

##### Tested on iPhone 12 Pro, iOS 14.3, WPiOS 16.5.0.0

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/15668.
