### ISSUE TITLE
Public/private/blocksearchengines codes defined in WordPressComApi.h != REST api

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-iOS#1566]
See https://github.com/wordpress-mobile/WordPress-iOS/blob/e9addc294aa47d268643ffdc7e48d0081082c7c7/WordPress/WordPressApi/WordPressComApi.h#L16-L18

**Comment by rachelmcr** [comment]
I checked and there's no longer any blog visibility defined in `WordPressComApi.h` or `WordPressComApi.m`. It looks like the only public/private/hidden codes are defined here now: https://github.com/wordpress-mobile/WordPress-iOS/blob/de005ebe1a07c7aaeea119c357e69afeaf92f66a/WordPress/Classes/Models/Blog.h#L36

Closing as resolved.
