### ISSUE TITLE
Quick Start: Skipped Step Still Shows as Incomplete

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15713]
### Expected behavior
If I choose "Not Now", it should no longer be in the list of steps to Customize my site

### Actual behavior
It remains in the list

### Steps to reproduce the behavior
1. While completing Quick Start, follow the guide dots to change your site title
2. Once you complete that, a prompt will appear suggesting you upload a new site icon
3. Choose "Not Now"
4. View the Customize your Site list and see that uploading a new site icon is still there

**Comment by startuptester** [comment]
@mattmiklic this was in your session notes, but I wanted to ask what you would expect here. I agree that they shouldn't be prompted to do something they skipped, but they might still need the guidance later, so should it be completely removed from the steps? 
@osullivanchris, you reported something similar before so maybe you have some ideas?

**Comment by osullivanchris** [comment]
@startuptester  hey, if referring to https://github.com/wordpress-mobile/WordPress-Android/issues/12278, there I was talking about the prompts that appear in tooltips at the bottom. They automatically bring you to the next step. If I have ignored a step, I think I should no longer be prompted to do it, as part of the flow.

However I agree with you, that I think it should still be in the list if I want to find it myself and do it later.

**Comment by mattmiklic** [comment]
Hey @startuptester -- I think you're right that they should remain in the list. I had this observation while watching Aaron walk through the steps, but we do want people to be able to find it again if they skip it the first time around. It's probably ok to ignore this one, but I agree with Chris that we probably shouldn't proactively prompt someone to do a task they've chosen to skip.

**Comment by startuptester** [comment]
Thanks for explaining that! I will update the details in this ticket to capture what Chris mentioned.

**Comment by startuptester** [comment]
Closing (read notes above)
