### ISSUE TITLE
Add bundle identifier property to "app_open" event  

### ISSUE THREAD

**Issue by yaelirub** [wordpress-mobile/WordPress-iOS#15719]
We'd like to be able to quantify internal builds  
So something like app_build_type [production, internal] should work

**Comment by aerych** [comment]
I think we can go a step farther and add a global property so any event can be quantified, not just app open.   

We could use the same constant used by magic links to identify different build types: 
wpdebug = development
wpinternal = internal beta
wpalpha = alpha
wordpress = production

With this approach, if we ever add a new build target we won't need to remember to update the tracks code as well.

**Comment by yaelirub** [comment]
Excellent idea!
