### ISSUE TITLE
Quick Start: Completing a step on your own does not automatically remove it from the list

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15712]
### Expected behavior
If I change the site title or complete any other step in Quick Start, the step should no longer be on the list. 

### Actual behavior
The step remains in the list of things to do

### Steps to reproduce the behavior
1. Create a new WP.com site in the app
2. Accept help when prompted to start Quick Start
3. Change the site title or upload an icon on your own and see that those items are still in the Customize list

https://cloudup.com/cwDobmUpO01

**Comment by yaelirub** [comment]
Hey @frosty , can you please work on this fix for 16.8?

**Comment by frosty** [comment]
Sure! 👍
