### ISSUE TITLE
User can delete Homepage and break their site

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/WordPress-iOS#15729]
### Description
It is possible to delete your Homepage while it's set as your static Homepage. This is a feature that is disabled on dotCom. If a user does delete their Homepage then their site will render with an error when you navigate there. 

### Steps to reproduce the behavior
**_Setup:_** Set your site's Homepage settings to use a Static Homepage

1. Navigate to pages
2. Tap the `...` 
3. Tap `Move to Trash`

##### Tested on iPhone 11, iOS 13.5, WPiOS 16.6

Android ticket: https://github.com/wordpress-mobile/WordPress-Android/issues/13908

**Comment by startuptester** [comment]
Pri High because of state the user is left in. @yaelirub, @frosty can someone be assigned to this?

**Comment by yaelirub** [comment]
Thanks for the ping, @startuptester ! 
@chipsnyder , let's figure out how we want to handle this 🙏

**Comment by chipsnyder** [comment]
I also just discovered that I can move my homepage to a draft which also breaks the site. So we should prevent that too even though the web allows it. 

I think this should be a straightforward fix and it looks like it has been around for a while. I'll add it to Gutenpages and work on taking care of it in 16.7
