### ISSUE TITLE
Reader: unable to unfollow external sites from post card and post details

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#15738]
### Expected behavior
When an external site is unfollowed from either a reader post card or post details, it is actually unfollowed.

### Actual behavior
When an external site is unfollowed from either a reader post card or post details, the menu option changes to `Follow Site`, but on refresh it reverts back to `Unfollow Site`, the posts are still in the stream, and the site still shows in the Manage > Followed Sites list.

External sites can successfully be unfollowed from Manage > Followed Sites.

### Steps to reproduce the behavior
- Go to Reader > Manage and follow an external site (ex: cnn.com).
- In the Following stream, find a site's post.
- Either:
  - In the card's options menu, select `Unfollow Site`.
  - Tap the card. In the post details options menu, select `Unfollow Site`.
- Pull to refresh the stream.
- Notice the site remains.

**Comment by designsimply** [comment]
Is it possible the siteURL and feedURL don't match as mentioned in https://github.com/wordpress-mobile/WordPress-iOS/issues/5633 or do you think this is for sure a separate issue?

**Comment by ScoutHarris** [comment]
Thanks for pointing that out @designsimply . I tested #5633 and I couldn't repro it. That appears to be resolved. I'll close it. But, to answer your question, I haven't looked into this issue yet so I'm not sure what the problem is/may be. But I'm going with it's different than #5633. 😄
