### ISSUE TITLE
Domain Registration: No Option to Continue from Contact Info Step

### ISSUE THREAD

**Issue by mdrockwell** [wordpress-mobile/WordPress-iOS#15744]
### Expected behavior
Should be able to continue the domain registration flow after selecting privacy protection options and entering contact information.

### Actual behavior
There is no option to proceed with the registration.

### Steps to reproduce the behavior
From within the app, switch to a site with domain credits available:

1. Tap on the "Register Domain" option
2. Select a domain
3. The "Register Domain" button is not there.

##### Tested on iPhone 11 Pro, iOS 14.3, WPiOS 16.6 and also tested in 16.5.

![PNG image-2F1745CF44C3-1](https://user-images.githubusercontent.com/42454301/106317295-1bdd9b80-623c-11eb-84d2-687887fbbf57.png)

User reported here: 3694790-zd-woothemes

**Comment by elibud** [comment]
I believe @frosty has already fixed this one.

**Comment by frosty** [comment]
Yes, this should be resolved by #15748 – which should be in the next test build of 16.6. 🙂

**Comment by frosty** [comment]
#15748 has now been merged, so marking this as closed.
