### ISSUE TITLE
Bug: The "Comments" screen is not refreshed on state restoration

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-iOS#15743]
### Expected behavior

When opening back the app after a while when it was on the Comments screen, I expect the UI to be consistent and showing the actual comments

### Actual behavior

When opening the WordPress app after a while, while the last time I closed it it was on the Comments screen of a particular post, this happens:

<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/216089/106295057-420d3680-6250-11eb-852e-ecd050a8c1f4.PNG" /></td>
<td><img src="https://user-images.githubusercontent.com/216089/106295423-b47e1680-6250-11eb-8983-3c6cd5af1703.PNG" /></td>
<td><img src="https://user-images.githubusercontent.com/216089/106295443-bcd65180-6250-11eb-8d2c-45d431816427.PNG" /></td>
</tr>
<tr>
<td>Immediately after opening the app</td>
<td>After scrolling a bit down and back up to "recycle" the top cell</td>
<td>After scrolling up and back down to "recycle" the bottom cell
</td>
</table>

Scrolling all the way to for recycling all the cells, or going back one screen and tapping to get back on the screen again refreshes everything and thus solves the display issue.

### Steps to reproduce the behavior

- Open the WordPress app
- Go to the Notifications Screen
- Tap on a notification about a comment (mine was "UserX liked your comment on PostY")
- Then tap on the first cell showing the first line of your comment, to get to the full "Comments" screen and see the thread of all comments
   - _I think any alternate way to go to that screen (like open a post in the iOS app, scroll to bottom, tap "Comments>" link at bottom) would work too, but the above steps are how I ended up on that screen yesterday iirc before seeing that bug today._
- Send the app to the background
- Somehow trigger a memory warning to make iOS run out of memory and deallocate the cells from the app's RAM (like launching many other memory-greedy apps)? At least that's my guess of what happened between when I opened the screen yesterday and when I reopened the app today that would explain such a state?
- Reopen the WordPress app. You end up on the Comments screen again where you left the app at, except that each cell showing a comment is now showing "Author" "Date" and no comment body, instead of the expected content for each cell (see screenshots above)

##### Tested on [device], iOS [version], WPiOS [version]

* iPhone 11 Pro
* iOS 14.4
* WordPress Internal 16.6.0.20210125 @ 33d17a2 (latest beta)

**Comment by kean** [comment]
Native state restoration was removed from the app, so it no longer an issue. I'm sure there were a bunch more unknown issues related to it.
