### ISSUE TITLE
Post Publishing: Date Picker resets to initial selection after changing screen orientation

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15767]
### Expected behavior
Screen orientation shouldn't change current selections

### Actual behavior
https://cloudup.com/c4OJyR7qXXh

### Steps to reproduce the behavior
1. Open post/page settings, and navigate to “Published on” setting.
2. Tap on the Date and Time option to show date picker.
3. Scroll date picker to the left or right. Optionally pick a date.
4. Change device orientation and confirm that date picker scrolled back to the month you opened it with.

**Comment by fluiddot** [comment]
**This issue still happens**, I managed to reproduce on iPhone 11, iOS 14.2, WPiOS 17.0 (17.0.0.6).

**Comment by kean** [comment]
Reimplemented in 24.9 using SwiftUI. I tested it and it no longer reproduces.
