### ISSUE TITLE
Reader: Following site from post card does not produce the “Turn on notifications” toast

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15763]
### Expected behavior
When I follow a site, I expect to be prompted to enable notifications

### Actual behavior
It does not appear on the post card screen

### Steps to reproduce the behavior
1. Open a Site title from the Discover screen
2. Tap on Follow and notice the toast
3. ![IMG_45DE45541715-1](https://user-images.githubusercontent.com/66104034/106662296-71c58280-655f-11eb-98ac-f978fb5a1edf.jpeg)
4. Go back to the post card view and do the same on a different site from the postcard
5. Notice there is no toast

**Comment by ScoutHarris** [comment]
As I stated on the testing post, I will include this in my project to align the post card and post details options menus. https://github.com/wordpress-mobile/WordPress-iOS/issues/15761.

**Comment by startuptester** [comment]
Thanks @ScoutHarris! I was so in the zone and just kept logging, but this works for keeping track of it anyway. Thank you!!
