### ISSUE TITLE
Posts/Pages Lists: Search Bar is glitchy after screen rotation

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15764]
### Expected behavior
Same in portrait and landscape

### Actual behavior
Search Bar is glitchy after screen rotation

### Steps to reproduce the behavior
1. When search filter is focused change device orientation to landscape – notice the the filter is cut at the top.
![image](https://user-images.githubusercontent.com/66104034/106662952-498a5380-6560-11eb-8cbd-13d12efbd324.png)

2. Tapping on search filter in landscape mode results in this:
![image](https://user-images.githubusercontent.com/66104034/106663293-c1f11480-6560-11eb-8600-c2e15df8590d.png)

**Comment by kean** [comment]
Fixed in the upcoming Modernization project https://github.com/wordpress-mobile/WordPress-iOS/pull/21744

<img width="894" alt="Screenshot 2023-10-20 at 1 42 16 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/157d46a1-e1dd-44d2-a109-255dfcc4e51c">
