### ISSUE TITLE
Reader/ Discover: Site Header "Follow" doesn't change after Following a new site from the postcard menu

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15762]
Reported by @khaykov 

### Expected behavior
Both locations should have the same Following/Follow state

### Actual behavior
the Site Header have a “Follow” button, while menu in the postcards says “Unfollow”

### Steps to reproduce the behavior
1. In Discover tab, find a post from the site you are not following. 
2. From postcard menu, tap Follow site.
3. Immediately navigate to the Blog Preview of this site.
4. Notice that the Site Header have a “Follow” button, while menu in the postcards says “Unfollow”

This state did reset after I restarted the app (navigating back to reader and back to blog preview did not fix this).

**Comment by ScoutHarris** [comment]
I'm unable to reproduce this. I tried with 16.8 and 16.9.

It's possible I accidentally fixed it when I addressed some post card / post details state issues on https://github.com/wordpress-mobile/WordPress-iOS/issues/15761, which was complete in 16.8.
