### ISSUE TITLE
Post Publishing Target site selector filter input field and filtered list content are not preserved on configuration change

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15765]
### Expected behavior
Selector and search returns should remain despite orientation change

### Actual behavior
Selector is cleared

### Steps to reproduce the behavior
https://cloudup.com/c3NXerG0lEE

**Comment by fluiddot** [comment]
**This issue still happens**, I managed to reproduce on iPhone 11, iOS 14.2, WPiOS 17.0 (17.0.0.6).

The steps to reproduce it are:
1. Go to a site
2. Create a new blog post
3. Tap on the site selector located at the top
4. Input some text in the search field
5. Rotate the device
6. Observe that the search is reset

**Comment by kean** [comment]
Target site is no longer a thing, closing.
