### ISSUE TITLE
Stats - Mismatch in Today values between Insights and Days

### ISSUE THREAD

**Issue by Gio2018** [wordpress-mobile/WordPress-iOS#15826]
### Expected behavior: 

In the stats, the Today card in "Insights" and the current day in "Days" should display the same values

### Actual behavior: 

Insights and Days differ for the number of Visitors. this also affects Today Widget (see screenshots below)

Insights | Days | Widget
-- | -- | --
<img width="250" src="https://user-images.githubusercontent.com/34376330/107312272-9afd7b80-6a55-11eb-852c-e56aa70f9fd7.png"> |  <img width="250" height=200 src="https://user-images.githubusercontent.com/34376330/107312306-ae104b80-6a55-11eb-98aa-b1adf5058e8c.png"> |  <img width="250" src="https://user-images.githubusercontent.com/34376330/107312322-be282b00-6a55-11eb-9ce6-5379514423d1.png">

### Steps to reproduce the behavior:

- Update stats on your site
- Note the difference between Insights and Days
- Install today widget and observe the same difference

**Comment by Gio2018** [comment]
cc @startuptester

**Comment by startuptester** [comment]
@Gio2018 and @frosty, is there an update on this one? It's targeting the frozen branch which should ship tomorrow

**Comment by Gio2018** [comment]
> @Gio2018 and @frosty, is there an update on this one? It's targeting the frozen branch which should ship tomorrow

Hey @startuptester , not sure why it did not close automatically, but this issue was addressed in [this](https://github.com/wordpress-mobile/WordPress-iOS/pull/15856) PR, which got merged onto [this other one](https://github.com/wordpress-mobile/WordPress-iOS/pull/15838) which was merged and should be part of the latest beta
