### ISSUE TITLE
Stats widgets not updating after signing up for new account

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#15833]
### Expected behavior

The new Stats widgets should detect when you change accounts and update themselves accordingly (or at least allow you to update them without having to re-add them)

### Actual behavior

When switching sites in the app, I had to re-add the Stats widgets to get them to work.

### Steps to reproduce the behavior

1. I was using the app and had added some Stats widgets and everything was working fine
2. I signed out and created a new WordPress.com account in the app (and a brand-new site)
3. I used the app for a little while (testing some new features e.g. updates to Quick Start)
4. I back-grounded the app and noticed the widgets were asking me to sign in (this was unexpected)
5. I tried to edit the widgets and update their site but it showed an empty list of sites
6. I ultimately had to re-add the widgets to get them to work

**Comment by staskus** [comment]
Judging by the code, the conversation and my testing this issue should be already fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/15838 @guarani

**Comment by guarani** [comment]
Thanks for noticing this issue was already fixed @staskus, I forgot about I was involved in testing the fix 😅. It looks like the PR used the "Fixes #issue_link" keyword, but the issue was not closed automatically by GitHub when the PR was merged 🤔. I've seen this happen a couple of times lately and I'm not sure of the cause. 

Either way, I've closed the issue now.
