### ISSUE TITLE
Facebook Publicize Connect not working

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15847]
### Expected behavior
I'd expect to be able to connect to my Facebook page

### Actual behavior
![IMG_514D6D5AB5FE-1](https://user-images.githubusercontent.com/1123407/107443919-e5830480-6af6-11eb-9b44-89399d316ba3.jpeg)

### Steps to reproduce the behavior
- Go to My Site > Sharing > Facebook.
- OAuth into an account with an associated page, choose the page, then hit done
- See this error

**Comment by jkmassel** [comment]
Verified by @startuptester

**Comment by startuptester** [comment]
@yaelirub  is anyone available for this one?

**Comment by yaelirub** [comment]
@jkmassel , I see you put 16.8. Is this not  happening in beta?

**Comment by startuptester** [comment]
It is happening in the 16.7 beta

**Comment by yaelirub** [comment]
@aerych, can you please take a look?

**Comment by aerych** [comment]
Tested with the current beta and with develop and everything seems to work fine for me. 
@jkmassel can you confirm you have created at least one page to connect to?  Pages are different from Profiles and the error suggests there might not be one. 
<img width="366" alt="Screen Shot 2021-02-10 at 12 32 16 PM" src="https://user-images.githubusercontent.com/1435271/107554813-0fdacd80-6b9c-11eb-98d6-a7c51a49d61b.png">

**Comment by startuptester** [comment]
@aerych, @jkmassel did have a page and then asked me to run it and it also did not work for me. This might have changed a bit and the issue might be Facebook, not us? Not sure about that.
When I go through this now in the 16.8 beta: 
1. the spacing in the border is weird
2. It seems to think I have no pages but I have 5 published. (I am also admin)
3. I cannot interact with the "Create a Page" button or the permissions toggles 

https://user-images.githubusercontent.com/66104034/109866834-05ec3d80-7c23-11eb-83b4-70cf32c8bb5d.mov

**Comment by aerych** [comment]
Was the movie from the test account that had pages?  Facebook says there are no pages and shows a prompt to create one at the 5 second mark.

<img width="272" alt="Screen Shot 2021-03-03 at 4 19 15 PM" src="https://user-images.githubusercontent.com/1435271/109880165-342a4700-7c3c-11eb-80e6-7b4f2f858e42.png">

**Comment by aerych** [comment]
@startuptester what do you see when you try from Calypso?

**Comment by aerych** [comment]
What do you see at https://www.facebook.com/settings?tab=business_tools&ref=settings 
Is your connection configured to share pages or to block access? 
Mine looks like: 
<img width="517" alt="Screen Shot 2021-03-03 at 5 19 16 PM" src="https://user-images.githubusercontent.com/1435271/109885785-be76a900-7c44-11eb-8fad-9316176f8c21.png">

**Comment by startuptester** [comment]
This is working now in 16.8. 

h/t @aerych for the walkthrough
