### ISSUE TITLE
Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureRea...

### ISSUE THREAD

**Issue by jkmassel** [wordpress-mobile/WordPress-iOS#15870]
**Sentry Url**: https://sentry.io/share/issue/eb331d147e8749af9d475641b46704bf/
**User Count**: 6
**Count**: 39
**First Release**: 16.7.0.20210208
**First Seen**: 2021-02-09T07:51:43.339000Z
**Last Seen**: 2021-02-11T20:19:55Z
**24 Hours**: 8
**30 Days**: 40

```
Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureRea...

```

**Comment by startuptester** [comment]
@guarani as the CTOW, can you please take a look?

**Comment by ceyhun** [comment]
Assigning low priority as currently it affects ~500 users and since it doesn't seem to be a crash but a logged error.

**Comment by bjtitus** [comment]
I made a change (https://github.com/wordpress-mobile/WordPress-iOS/pull/16314) to stop logging 404 errors as they would be expected when no site icon exists. This should reduce the volume of these errors by roughly half. Next steps should be to investigate the 400s (the next largest error group). I have a theory that they may be caused when Photon requests are made with bad parameters or when the URL passed to Photon has some kind of error.

**Comment by jkmassel** [comment]
This issue is no longer being reported by Sentry
