### ISSUE TITLE
Crash on Jetpack Scan history

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#15908]
### Expected behavior
When History is tapped, the history is displayed

### Actual behavior
Crash

### Steps to reproduce the behavior
1. Go to scan
2. tap 'scan now'
3. when it says 'preparing to scan' tap 'History'
4. first time I do it, scan seems to crash and I go back to My Site
5. second time I do it, the whole app crashes

Reported by: @osullivanchris

**Comment by leandroalonso** [comment]
@startuptester this is originally an Android issue and it has been fixed there. :)
