### ISSUE TITLE
Milestone Notifications: Truncated Text for Most Likes In One Day Notification

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#15900]
<img src="https://user-images.githubusercontent.com/6711616/108152537-93f10000-711c-11eb-8f34-8372d7dd1b18.png" width=30%>

### Expected behavior
Text should not be truncated

### Actual behavior
Text is truncated
"That's pretty awesome, well"

### Steps to reproduce the behavior
1. Go to the Notifications tab
2. Find a "Your best day for likes on X" notification
3. 👀 Notice that the last sentence is cut off (i.e. "That's pretty awesome, well")

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 11 Pro, iOS 15.4
WPiOS App Store Version 16.6.1
WPInternal Version 16.7.0

**Comment by AliSoftware** [comment]
Also I noticed that if I use the arrows on the upper-right corner to go to the next notification, then back to this screen, the text is not truncated anymore.

https://user-images.githubusercontent.com/216089/108249383-4cd33100-7155-11eb-85be-63505265295f.mov

_My wild guess and 2 cents is that maybe the first time the ViewController is loaded and the first AutoLayout pass is run, UIKit doesn't take into account the final size of the image (that we animate with a growing effect) properly, but once the screen is instantiated if we go away and back and the ViewController is still in memory, autolayout is re-triggered on `viewDidAppear` or something and computes the sizes properly on that second pass…? This is pure speculation on my part though, just a thought / investigation idea._

**Comment by frosty** [comment]
It looks like this is resolved by our work for Milestone Notifications – you can see on the screenshots in https://github.com/wordpress-mobile/WordPress-iOS/pull/15968 that all of the text of this particular notification is visible as of our latest changes.
