### ISSUE TITLE
Stories post type non-functional for .org sites

### ISSUE THREAD

**Issue by trevormeier** [wordpress-mobile/WordPress-iOS#15965]
### Expected behavior

1. Go to Posts Page
2. Press FAB button
3. Menu option to create blog post or story

### Actual behavior

1. Go to Posts Page
2. Press FAB button
3. New blog post opens in block editor

### Steps to reproduce the behavior

Press FAB button in post list on existing wordpress.org site in WPiOS

##### Tested on [device], iOS [version], WPiOS [version]

iPhone X
iOS 14.4
WPiOS 16.8.0.0

**Comment by startuptester** [comment]
This is expected behaviour due to it being a jetpack block.
