### ISSUE TITLE
Notifications: detail view is showing incorrect nav bar in internal & release versions

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#15987]
### Expected behavior
In internal and release app versions, the nav bar should be the old blue one.

### Actual behavior
- The nav bar is the white one.
- On iPhone with split view, the Notifications nav bar turns grey when rotating into landscape (i.e split view).
- On iPhone, the top of the details view is under the nav bar.
- On iPad, the nav bar has a back button that doesn't do anything.

### Steps to reproduce the behavior
Go to Notifications.
Note the nav bar style.
Tap a notification. 
Note the nav bar difference. It is particularly obvious in split view.

| iPhone portrait | iPhone landscape | iPad |
|--------|-------|-------|
| ![iphone_portrait](https://user-images.githubusercontent.com/1816888/109343541-c68cae00-782a-11eb-81f7-979c50929c68.jpeg) | ![iphone_landscape_split](https://user-images.githubusercontent.com/1816888/109343564-cbe9f880-782a-11eb-8534-d4630d5644e9.jpeg) | ![ipad](https://user-images.githubusercontent.com/1816888/109343581-d0aeac80-782a-11eb-81a0-d6329c0ec691.jpeg) |

**Comment by aerych** [comment]
Closing now that the new navigation bars are in use app wide.
