### ISSUE TITLE
Stories: Investigate Media Upload failures

### ISSUE THREAD

**Issue by bjtitus** [wordpress-mobile/WordPress-iOS#16023]
### Expected behavior

* Media upload should occur after publish/save while the post is uploaded
* Any errors should be silently reported as failed uploads can be retried from the post cell

### Actual behavior

* Media upload may occur before post publishing
* Media upload failures will show an alert with too much information:
<a href="https://user-images.githubusercontent.com/3250/110151198-6bfcd000-7d9d-11eb-80cb-5e6ac143f4df.png"><img src="https://user-images.githubusercontent.com/3250/110151198-6bfcd000-7d9d-11eb-80cb-5e6ac143f4df.png" width="300"></a>

### Steps to reproduce the behavior
* Create a new story
* Add several media items
* Hit the Publish Button
* Instead of seeing the Prepublishing Sheet, the editor dismisses and an error shows

**Comment by eduardozulian** [comment]
Reported in 3817908-zen

**Comment by eduardozulian** [comment]
@bjtitus is there anything specific we could ask users for in terms of troubleshooting? I was not able to reproduce this with a WordPress.com site.

**Comment by bjtitus** [comment]
@eduardozulian Thanks for reporting this! There are two major things we can try:

1. Find out if they are in a bad network environment. Also, find out if the post is able to be published following dismissal of this message. It should be stored as a Draft with a "Failed" state

2. Ask them to update to version 16.8.1 and see if they experience any issues publishing. That version removes this alert and instead logs the error since this was catching many network errors and other events which can be retried later from the Post List screen.

**Comment by iamgabrielma** [comment]
3817908-zen replied with more details: 

> The device I am using is:
> 
> - iPhone 12mini
> - iOS 14.4
> - WordPress app version 16.8 - and then 16.8.1 (I have tried it in both)
> 
> The sites I was trying to post a story to were all on a WordPress Multisite server running:
> 
> - WordPress 5.6.2
> - JetPack 9.5

I'll ask them to check for drafts in failed state, as they're already using 16.8.1 and the problem persists. Some other information they've added:

> the only other thing I can think about is that I set up basic HTTP authentication in my .htaccess file so that I have to enter a username and password via HTTP auth before I get to the /wp-login page. When I first set up the site in the WordPress iOS app, I seem to remember entering the HTTP auth user/password, so the app should have it. 

AFAIk this goes through the WP-API and whatever they've added to the `/wp-login` shouldn't affect the media upload, is that right?

**Comment by bjtitus** [comment]
> this goes through the WP-API and whatever they've added to the /wp-login shouldn't affect the media upload

Yes, that's correct. If they are able to upload Media normally through the app, uploading stories should work as well. The same APIs are used. That might be one other thing to confirm, whether they are able to upload other Media outside of Stories.

**Comment by mdrockwell** [comment]
3817908-zen replied with more info:

- Says they have a good internet connection, doesn't believe that is an issue at all.
- Not able to publish with a "retry", still gets an error.

**Comment by bjtitus** [comment]
We made a change to better handle media uploads happening after posts are published.
https://github.com/wordpress-mobile/WordPress-iOS/pull/16445

I will close this issue but please comment with any future details if these problems appear to continue.
