### ISSUE TITLE
Improve layout and cell reuse in native stats views

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#1605]
There are a number of UIKit violations in the native stats views such as alerting view hierarchy in layoutSubviews and in prepareForReuse.  There was also at least one case of code called layoutSubviews directly rather than telling the view setNeedsLayout.
1. Ensure layoutSubviews does not modify the view hierarchy.  If the view's underlying values it represents changes, then do the alterations elsewhere.
2. Do not call layoutSubviews anywhere.
3. When prepareForReuse is called, reset internal data, do NOT modify the view hierarchy.

This should improve drawing performance tremendously.  A refactor may be required since some of the code is tightly coupled.

**Comment by saraseif** [comment]
Hi! Can I ask where your new repo is?

**Comment by elibud** [comment]
Here it is: https://github.com/wordpress-mobile/WordPress-iOS
