### ISSUE TITLE
Stories: Editor can be rotated to landscape when editing from Gutenberg

### ISSUE THREAD

**Issue by bjtitus** [wordpress-mobile/WordPress-iOS#16062]
### Expected behavior

* The Story editor should be portrait only

### Actual behavior

* The editor can be rotated to landscape when opened from the Gutenberg editor

### Steps to reproduce the behavior

* Open an existing Story post
* Edit a story block
* Rotate the device to landscape 

![IMG_4478](https://user-images.githubusercontent.com/3250/110720366-a87c6180-81cb-11eb-98e2-4ba1c1a77437.PNG)

**Comment by guarani** [comment]
I ran into an issue which is probably the same as this but want to confirm:
1. Open a new blog post
2. Add a Story block
3. Add Media (camera view opens)
4. I rotate device to landscape-left
5. Image is stretched

If Stories isn't supposed to support landscape, I'd say this issue will go away when that change is made.


https://user-images.githubusercontent.com/1898325/113882647-7a1e8180-978b-11eb-8c12-0768b4355450.mov

**Comment by bjtitus** [comment]
Yep! The issue you pointed out should be fixed by removing rotation while in the Story editor but we will likely need to fix it for iPad support. I've got a change coming up for 17.2 to fix the rotation issue.

**Comment by erricgunawan** [comment]
When I tested and tried to reproduce #17606 I didn't have this rotating issue.

Just wondering if this can be closed 🤔

**Comment by guarani** [comment]
I can't seem to locate a PR that removed landscape orientation support.
👋 @bjtitus, could you please help me recall if this issue was fixed? Not sure if landscape orientation support was removed or not.
