### ISSUE TITLE
Allow stories to be captured without microphone access

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#16065]
### Expected behavior

When creating a Story, the user should be able to capture media with the camera without granting microphone permission (i.e. without tapping the "Allow access to microphone" button).

### Actual behavior

Until the user grants the app microphone permission, they can't capture media. 

### Steps to reproduce the behavior

1. Tap the Floating Action Button on the My Sites screen
2. Choose "Story post"
3. Continue past the welcome screen if needed
4. Grant camera permission but not microphone permission
5. Notice that the background remains black and the only options for adding media are the media libraries

### Additional info

I haven't tested this scenario on WPAndroid so the same may apply there. Looking at other apps, Instagram also requires microphone permission to take photos, but there is no technical limitation forcing them to do this (that I'm aware of). The overlay Instagram uses to request microphone access is translucent and underneath the camera live viewport is clearly visible.

**Comment by bjtitus** [comment]
The corresponding Kanvas issue: https://github.com/tumblr/kanvas-ios/issues/41

**Comment by rachelmcr** [comment]
I'd definitely love to see this! I pretty much never share video on my blog, only photos, and it's off-putting to have to give microphone access when I'll never use it. I almost didn't notice that I could at least access my device media library, so for a moment I was ready to give up on using the feature entirely.

Here's how it looks as-is (on iPhone 12 Mini, iOS 14.4.2, WPiOS 17.3):

<img src="https://user-images.githubusercontent.com/8658164/118628214-53109200-b7c4-11eb-986a-66516caf104e.PNG" width="300px">

**Comment by twstokes** [comment]
This UI seems to have changed and will increase user confusion. The microphone was disabled for the app and access to All Photos was granted.

iPhone 12, iOS 15.7, WPiOS 21.0

<img src="https://user-images.githubusercontent.com/2092798/196595465-d19c3d16-8af7-4160-b190-f6b5f58d5d2e.jpeg" width="350px" />

**Comment by guarani** [comment]
> This UI seems to have changed and will increase user confusion. 

👋 Hey @twstokes, it looks like the UI has changed, but also the button text now showing a placeholder. Are you referring to both these changes or just the former? 

It looks like the former could be a deliberate UI change, but it could be a worse UI. The latter seems like a bug.

**Comment by twstokes** [comment]
> Are you referring to both these changes or just the former?

👋 Hey @guarani - I was referring to both, but I've added https://github.com/wordpress-mobile/WordPress-iOS/issues/19508 since this should be treated as a separate issue. 👍
