### ISSUE TITLE
Login: Sign in request doesn't appear when app is open.

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#16075]
When trying to approve a WordPress.com sign in request in the apps, I did not receive the sign in request when the app was open. 

The sign in request worked fine both when the app was in the background and when the device was locked.

This was tested in versions 16.8 and 16.9 beta.

I was trying to log in to calypso on the web using the mobile app to verify the login. 
It worked fine when the app wasn’t active; I got a push notification and that dialog opened in the app.
![image](https://user-images.githubusercontent.com/66104034/111244095-deed1e80-85c7-11eb-9fd6-4a75d82c35e1.png)
But when I already had the app in the foreground, no notification came in.

**Comment by jd-alexander** [comment]
I also observed this very behavior during testing. I did not receive the sign-in request while the app was open.
