### ISSUE TITLE
Plugins: horizontal scrolling doesn't work and nothing from the Featured section can be selected

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#16087]
### Expected behavior
I expect to be able to scroll horizontally through the rows and be able to select a plugin from the row of Featured ones

### Actual behavior
**1. Scrolling: I cannot scroll horizontally in any row
2. Featured row: they all seem to be disabled
3. Popular row: It opens a list view when I select one, I don't think that is right**

![IMG_9FF046E363EF-1](https://user-images.githubusercontent.com/66104034/110991929-79cccb00-8332-11eb-9bb7-380dc4ad2d13.jpeg)

### Steps to reproduce the behavior
With a jp connected site, open plugins from My Site
Tap a plugin from the Installed row and note that it opens the Manage screen
Tap a plugin from the Popular row and note that it opens a list view - I expect to see a detail view of that plugin though?
Tap a plugin from the Featured row: nothing happens
Notice that none of the rows scroll horizontally

iPhone 12 Pro, iOS 14.4, WPiOS 16.6-16.9 (I don't think it's version specific)

**Comment by yaelirub** [comment]
@Gio2018 , @frosty this has been broken for a while and I think we should give it a priority. Last relevant changes I see are here : https://github.com/wordpress-mobile/WordPress-iOS/pull/15588

**Comment by Gio2018** [comment]
> @Gio2018 , @frosty this has been broken for a while and I think we should give it a priority. Last relevant changes I see are here : #15588

Thanks for the heads-up @yaelirub , we'll give priority to this issue.

**Comment by frosty** [comment]
FYI I have a fix up for this now: https://github.com/wordpress-mobile/WordPress-iOS/pull/16538
