### ISSUE TITLE
Reader: In-app browser preview hides/cuts important elements

### ISSUE THREAD

**Issue by eduardozulian** [wordpress-mobile/WordPress-iOS#16106]
When you preview a post from the Reader using the 🌏 icon, you get a preview of the site itself. However, some elements (especially fixed ones like cookie-related banners) are hidden behind the bottom bar and cannot be used.

### Expected behavior
To be able to access all the elements from the in-app preview.

### Actual behavior

The bottom overlay bar gets on top of important elements like the button to accept/deny cookies:

https://zerowastechef.com/ | https://rafaelfunchal.com.br/ | https://toddhensonphotography.com/
------------ | ------------- | -------------
<img src="https://user-images.githubusercontent.com/1136160/111379368-d0633d80-8681-11eb-9963-996c04058633.png"/> | <img src="https://user-images.githubusercontent.com/1136160/111379384-d48f5b00-8681-11eb-9f47-83141636b596.png"/> | <img src="https://user-images.githubusercontent.com/1136160/111379389-d5c08800-8681-11eb-91b8-9d6c6d5fa41b.png"/>

### Steps to reproduce the behavior

1. Open the Reader
2. Open a post from a site with one of these bottom banners. Examples: https://toddhensonphotography.com/blog, https://zerowastechef.com/, or https://rafaelfunchal.com.br/
3. Tap the globe icon to preview the site
4. Check the bottom

##### Tested on iPhone 7, iOS 14.4, WPiOS 16.8.0.4

Reported also in 3826878-zen

**Comment by kduncanwelke** [comment]
I'd like to try taking on fixing this one 👏🏻
