### ISSUE TITLE
Label incorrect on widgets

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#16123]
### Expected behavior
The blue labels should say "Views" in the small widgets. 

### Actual behavior
Instead they duplicate the Today/All Time labels.

![image](https://user-images.githubusercontent.com/66104034/111561484-24415580-875a-11eb-8e02-b1c6bc173baf.png)

### Steps to reproduce the behavior
Install the smaller versions of the All Time and Today widgets

iOS 14

**Comment by Gio2018** [comment]
This should be fixed by #16125
