### ISSUE TITLE
[Push Notifs] "Like" Notifications are always one step behind

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-iOS#16128]
_(Not entirely sure that this is an iOS-side issue vs server side, but posting here since I experience this only in WPiOS, and wonder if that might not be due to something in our NotificationsExtensions rather than server-side)_

### Expected behavior

- After I created a post P and person A liked it
- If later person B likes the same post, I want to receive a notification saying "B liked your post P" or "B and A liked your post P".
- Then when I open the app and its notification's screen, I want to see "A and B liked your post P" too

### Actual behavior

- Instead, I receive a notification "A liked your post P" (where A is the name of the previous person who liked said post)
- But when I open the app on the Notifications Screen, I can properly see that the notification cell tells me "B and A liked your post P" not just A.

### Steps to reproduce the behavior

- Create a new post
- Have one person A like it
- Then have another person B like it.
- Observe that the notification you then receive will tell you that A liked it, without mentioning the new like from B
- Tap the notification to open the app on the Notifications Screen. Observe that the notification list properly mentions "A and B liked your post"
- Have another person C like your post
- Observe that the notification you then receive tells you "A and B liked your post", without mentioning the new like from C. In other words, the notification text is the one you were supposed to have received from the _previous_ like.
- Tap the notification to open the app. On the Notifications Screen, the notifications list properly mentions "A, B and C liked your post"
- Go to the web (wordpress.com) and open the notification pane. See that the notification list on the web also properly mentions "A, B and C liked your post". So only the notification popup/payload received by the iOS app is one step behind, while the notifications list both on the web and in the iOS app are correct.

##### Tested on iPhone 11 Pro, iOS 14.4.1, WPiOS Internal 16.9.0.20210317 (but it has been happening for a couple of days already)

<details><summary>Logs extract</summary>

This is the payload I see in the app logs when receiving the notification after Stefanos have liked my post. As you can see, the notification payload says Joel and Jira liked my post, while in practice when the notification got emitted it was after Stefanos' like so it should say "Stefanos, Joel and Jira" instead

```
application(_:didReceiveRemoteNotification:fetchCompletionHandler:)
2021-03-18 18:23:55:634 Received push notification:
Payload: {
    aps =     {
        alert = "mrjoeldean and Jiri Malina liked your post Versioning of FluxC & our internal Android\U00a0libs";
        badge = 1;
        category = like;
        "content-available" = 1;
        "mutable-content" = 1;
        sound = "n.caf";
    };
    blog = 150314751;
    "blog_id" = 150314751;
    "note_id" = 5291443886;
    type = like;
}
```
</details>

### Potentially related issues?

 - https://github.com/wordpress-mobile/WordPress-iOS/issues/11847 – Similar general description but different outcome described

**Comment by alpavanoglu** [comment]
Tested it and it works as expected on the live version (24.3)
