### ISSUE TITLE
Quick Start > Dark mode: completed header has white edges

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#16164]
### Expected behavior
The `Complete (x)` header is fully dark grey.

### Actual behavior
The `Complete (x)` header has white edges.

### Steps to reproduce the behavior
On a iPad in dark mode:
- Create a new site.
- Accept quick start.
- When the steps are displayed, notice the `Complete` color.

![quick_start_dark](https://user-images.githubusercontent.com/1816888/112549304-35eeb280-8d83-11eb-8eef-014269fa6688.jpeg)

**Comment by pachlava** [comment]
The same can be seen on iPhone in landscape mode:

![IMG_4410](https://user-images.githubusercontent.com/73365754/142603513-ddeafbd7-5443-4318-9361-c01bbc4740d0.PNG)

iPhone XR, iOS 14.8, [WPiOS One-Off Build](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-iOS/25697/workflows/53e04980-1108-44e6-b094-fb5ab99ec258/jobs/60643/steps).

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
