### ISSUE TITLE
Feature Request: Add "Pending Review" filter for blog posts

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-iOS#16174]
Currently, to view the posts that are having the "Pending Review" status, users will have to look for its label on the Drafts tab. It was mentioned in 3860874-zd-woothemes:

> The inability to easily see the post you've submitted for review can be frustrating.

I understand even on Calypso, this isn't available but on WP Admin, there is such a filter on the Posts page.

**Comment by kean** [comment]
Closing as duplicated https://github.com/wordpress-mobile/WordPress-iOS/issues/4563
