### ISSUE TITLE
Account Settings: Primary Site row stays selected

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#16242]
### Expected behavior
Row selection cleared if `Select Site` view is cancelled or dismissed.

### Actual behavior
If `Select Site` is cancelled or dismissed (via swipe down) the `Primary Site` row is still selected.

### Steps to reproduce the behavior
- Go to Me > Account Settings.
- Select `Primary Site`.
- Cancel or dismiss `Select Site`.
- Notice `Primary Site` is still selected.

If a site is selected, the `Primary Site` row selection is cleared as expected.

![account_settings](https://user-images.githubusercontent.com/1816888/113783688-5a3a7f80-96f1-11eb-93ab-c70367fc587c.jpeg)

**Comment by kean** [comment]
No longer reproduces.
