### ISSUE TITLE
Schedule Now button is hidden from the screen when scheduling a story

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#16248]
### Expected behavior
The schedule Now but is visible on the screen when scheduling a story without scrolling

### Actual behavior
Schedule Now but is hidden from the screen when scheduling a story

### Steps to reproduce the behavior
1. Create a new Story
2. Press the arrow on the top-right of the screen
3. Tap on the "Publish Date" and schedule in the future
4. Press Done
5. Notice that the **"Schedule Now" button is hidden** with no visible indication of the scrolling behaviour of the bottom sheet
6. Scroll down to see the button

<image src="https://user-images.githubusercontent.com/304044/113885904-e66ba600-97c8-11eb-911f-9b862ec7d633.PNG" width="360"/>

<details>
 <summary>Note: Similar behaviour is experienced in other post types but does not affect the usability since the button is partially visible</summary>

<image src="https://user-images.githubusercontent.com/304044/113887672-5dee0500-97ca-11eb-86db-ca8441c9b1e9.PNG" width="360"/>

</details>

**Comment by bjtitus** [comment]
Just a note on temporary workarounds that the prepublishing sheet should be swipeable in this state so the button is reachable upon swiping up. Also, taller devices (primarily those without a home button) will show the top part of the button as shown in the Note section. I'm investigating at a few possible fixes for this.
