### ISSUE TITLE
Webviews: white text on white headers (invisible text and icons)

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#16247]
There are quite a few webviews where I'm seeing white text and icons on a white background in the toolbar, meaning the page title and any icons are invisible. This only applies to light mode; in dark mode they are visible (but the web address subtitle is dark and hard to read).

- Me > App Settings > Privacy Settings > Learn More (under "Share information with our analytics tool...")
- Me > App Settings > Privacy Settings > Read privacy policy
- Me > App Settings > Privacy Settings > Privacy notice for California users
- Me > App Settings > Privacy Settings > Learn more (under "We use other tracking tools...")
- Me > App Settings > About > Terms of Service
- Me > App Settings > About > Privacy Policy
- Me > App Settings > About > Blog
- Me > App Settings > About > Source Code
- Me > App Settings > About > Acknowledgements (the title is visible here, but icons aren't)
- My Site > Stats > Days (or weeks, months, or years) > Posts and Pages > Post title > Post title
- My Site > Stats > Days (or weeks, months, or years) > Referrers > Referer name
- My Site > Comments > Tap any comment > Tap the URL if there is one, under the commenter's name
- My Site > Themes > Customize (under Current Theme) (title is visible, icons aren't)
- My Site > Themes > Details (under Current Theme) (title is visible, icons aren't)
- My Site > Themes > Support (under Current Theme) (title is visible, icons aren't)
- My Site > Themes > Tap any theme screenshot (title is visible, icons aren't)
- My Site > Themes > `•••` icon > Try & Customize (title is visible, icons aren't)
- My Site > Themes > `•••` icon > View (title is visible, icons aren't) 
- My Site > Themes > `•••` icon > Details (title is visible, icons aren't) 
- My Site > Themes > `•••` icon > Support (title is visible, icons aren't) 
- My Site > People > `+` icon > "Learn more about roles" link
- My Site > Plugins > Plugin detail page > tap link on plugin developer name
- My Site > Settings > Date and Time Format > "Learn more about date and time formatting" link
- My Site > Settings > Security (under Jetpack) > "Learn more…" link

They look like this (except for those where I noted that the title is visible).

![IMG_4724](https://user-images.githubusercontent.com/1396552/113795012-e06abc00-9719-11eb-85c2-c0c518e609da.PNG)

**Comment by yaelirub** [comment]
@frosty , @Gio2018 can one of you please take a look at this? If we can fix it for the next beta that would be great

**Comment by frosty** [comment]
Thanks for reporting, I'll take a look! This should've been fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/16116, so I'll see what's going on here.

**Comment by startuptester** [comment]
@frosty should this one have closed automatically?

**Comment by frosty** [comment]
I think so!
