### ISSUE TITLE
Unsupported redirect error when creating logo

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-iOS#16256]
When I was testing the "Create logo" feature on WPiOS 17.0.0.6, I see an "Unsupported redirect" error.

### Expected behavior

No error appears on the screen before I was redirected to the BuildMyLogo page.

### Actual behavior

I'm seeing an "Unsupported redirect" error.

### Steps to reproduce the behavior

1. On the app, switch to a WordPress.com Simple site
2. Go to My Site > Themes > Customize > Site Identity
3. Tap on the "Create logo" button
4. See the "Unsupported redirect" error
5. Tap the "Back" link
6. The BuildMyLogo page loads

Screen recording: https://d.pr/v/MNFOx0/83fDefXYRJ

Note: Repeat the same steps on a WordPress.com Atomic site, on Step 4, instead of seeing an error, I was redirected to WP Admin.

**Comment by startuptester** [comment]
Thanks @reginabally! I'm unable to repro this on a Simple site using the 17.2 beta from TestFlight. Can you please confirm? If so, we can call this fixed.

**Comment by reginabally** [comment]
Thanks for the update @startuptester! I'm unable to reproduce this on 17.2 beta too so we're good to close this issue. 🎉
