### ISSUE TITLE
After latest update Hebrew version of the site is truncated 

### ISSUE THREAD

**Issue by rossanafmenezes** [wordpress-mobile/WordPress-iOS#16267]
### Expected behavior

Since Hebrew is part of the Mag16 languages, I would expect the app to look normal if you have your phone set to Hebrew. 

### Actual behavior

The user reported they are not able to switch sites because the switch site option is not showing:

![Annotation on 2021-04-09 at 09-19-51](https://user-images.githubusercontent.com/30724184/114186953-6f8ff380-9915-11eb-9893-b1e4f3bee9dc.png)

While I was not able to reproduce this on my iPAD since the screen is way bigger I was able to reproduce not the same issue but a very similar one on my Android Phone:

![photo_2021-04-09 09 25 53](https://user-images.githubusercontent.com/30724184/114187587-2a1ff600-9916-11eb-84ca-4782b86e4a02.jpeg)

I'm adding it to the Android Repo as well. 

### Steps to reproduce the behavior

on an iPhone, set the phone language to Hebrew
Open the WordPress app

##### Tested on [device], iOS [version], WPiOS [version]

Waiting for the user to confirm which device model and OS version they have. 
WP version: 17.0
3886795-zen

**Comment by iamgabrielma** [comment]
They confirmed the version is  Version 17.0 (17.0.0.6)

**Comment by sdooh393** [comment]
Sz
