### ISSUE TITLE
Bug: Author names don't appear in Blog Posts list

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#16297]
This bug only applies to self-hosted WordPress sites.

<img src="https://user-images.githubusercontent.com/2092798/114650216-d9aaee80-9caf-11eb-8c62-35efafa7e8ba.png" width=500 />

### Expected behavior

In the Blog Posts view either:

1. An author name should be shown following the dot separator after the published date.
2. The dot separator should not be shown after the date if an author name isn't available or if an author shouldn't be shown.

(please see the attached screenshot)

### Actual behavior
In some cases no name is shown and the dot separator is still present.

### Steps to reproduce the behavior

1. Publish a sample blog post to a self-hosted WordPress site.
2. From the My Site view, tap "Blog Posts".
3. Observe a dot separator with no author name following. **Note:** For Administrator roles, view posts for "Everyone".

**Comment by guarani** [comment]
Thanks a lot for catching this issue, @twstokes! 🙇
