### ISSUE TITLE
Cannot compose offline with images

### ISSUE THREAD

**Issue by blobaugh** [wordpress-mobile/WordPress-iOS#1630]
When creating a new post with images the app must have a connection to the internet as the images are uploaded immediately. This is pretty inconvenient as I am often composing posts in an offline situation. Writing a text post does not need a connection and will happily sit in the app until you return with a connection and tell it go. This leads to a juggling act where I write a post and input my own text placeholders for the images, save it as a draft so it does not publish by accident, then later I come along and upload the images then move the html snippet into the placeholder. Images should be able to live in the app as drafts until the post is pushed to the server also.

**Comment by dvor** [comment]
Not sure why this was closed, but it would be nice to have feature. Any plans adding support for offline images one day?
