### ISSUE TITLE
Page List doesn't reflect a newly added page until the list is refreshed.

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/WordPress-iOS#16370]
### Expected behavior
When adding a new page it should appear on that appropriate filter after the editor is closed.

### Actual behavior
The page doesn't appear on the filter until the list is refreshed.

### Steps to reproduce the behavior

1. Navigate to the page list
2. Take note of the filter you're on (ie Published, Drafts, or Scheduled)
3. Create a new page
4. Save the page so that it will appear under the filter you have selected

**Comment by antonis** [comment]
The following two Page List refresh issues are related and may be solved along this issue:
* https://github.com/wordpress-mobile/WordPress-iOS/issues/15535
* https://github.com/wordpress-mobile/WordPress-iOS/issues/14079

**Comment by dvdchr** [comment]
As per https://github.com/wordpress-mobile/WordPress-iOS/issues/20647#issuecomment-1603357554, I've created #21377 to address this issue.

**Comment by kean** [comment]
No longer reproduces. Tested in `trun` (future 24.9). I believe it was fixed in 23.7.
