### ISSUE TITLE
Landing Screen buttons with Larger Text need work

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#16377]
![img_2095-1](https://user-images.githubusercontent.com/66104034/116142035-a8122a00-a696-11eb-8a39-16db42ceddfd.png)
![img_2094-1](https://user-images.githubusercontent.com/66104034/116142043-ab0d1a80-a696-11eb-8c1c-07ad29fc415f.png)

### Steps to reproduce the behavior

Increase system font size and download the app

**Comment by kean** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/16444
