### ISSUE TITLE
Help Page is not localized

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#16386]
### Expected behavior
Help content should be localized and very accessible

### Actual behavior
![img_2105-1](https://user-images.githubusercontent.com/66104034/116154865-7bfea500-a6a6-11eb-842c-43c51587e986.png)

### Steps to reproduce the behavior
View help in non-English language

**Comment by frosty** [comment]
I'm not sure there's much we can do here directly. Some support pages do have translations, and if there are any available they'll be listed at the top of the page:

<img width="717" alt="Screenshot 2021-04-28 at 11 48 44" src="https://user-images.githubusercontent.com/4780/116391937-b471c080-a817-11eb-939c-6e71a9e4e0c0.png">

I don't think we can really attempt to load a different language page automatically, as there's no guarantee it'll be available in the required language.

**Comment by startuptester** [comment]
That's a good point, @frosty. WDYT, @Gio2018?

**Comment by Gio2018** [comment]
> That's a good point, @frosty. WDYT, @Gio2018?

I agree, doesn't look we can do much here.
