### ISSUE TITLE
Missing "Choose" translation on Site Creation preview

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#16381]
![img_2098-1](https://user-images.githubusercontent.com/66104034/116150483-a9e0eb00-a6a0-11eb-9727-4112d712dea5.png)

### Steps to reproduce the behavior
Create a new site and preview the templates

**Comment by frosty** [comment]
@startuptester Please could you confirm that this is still happening to you? I see the translation in the Spanish translation files in the app, and when testing in Spanish I see the button translated:

<img src="https://user-images.githubusercontent.com/4780/117482977-0ecbf900-af5d-11eb-8f89-eca0fee27b9b.png" width=250>

**Comment by startuptester** [comment]
Can confirm. I checked French and Hebrew and both "Choose" button locations were translated. 

Thanks, @frosty!
