### ISSUE TITLE
Larger Text: Posts and Pages screen don't look great 

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#16385]
There's overlap between UI elements and it's crowded

![img_2099-1](https://user-images.githubusercontent.com/66104034/116154352-cc293780-a6a5-11eb-8643-adf8a5f039b5.png)
![img_2109-1](https://user-images.githubusercontent.com/66104034/116154358-cdf2fb00-a6a5-11eb-9193-09e84f574464.png)

### Steps to reproduce the behavior
In settings, enable Larger Text and choose a large setting
View Posts and Pages

**Comment by startuptester** [comment]
Adding @osullivanchris' sketch: 

![image](https://user-images.githubusercontent.com/66104034/116157240-de0cd980-a6a9-11eb-9a85-9a76b12ac42d.png)

**Comment by momo-ozawa** [comment]
Closed via #16437
