### ISSUE TITLE
Reader: align following a site with adding a topic

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-iOS#16397]
In WordPress iOS, to add a topic, there is an action at the top of the list.

This brings you to a separate view where you enter the topic, and add it.

<img width="1222" alt="Screenshot 2021-04-28 at 10 44 32" src="https://user-images.githubusercontent.com/50576199/116383431-bbe09c00-a80e-11eb-828e-fa8f50b6bce8.png">

If you want to follow a site, the UI is completely different. I find the field confusing. It looks like you are going to search the list below it.

<img width="613" alt="Screenshot 2021-04-28 at 11 00 21" src="https://user-images.githubusercontent.com/50576199/116385700-f64b3880-a810-11eb-8855-df71643fea65.png">

Here's what it would look like if we aligned the Follow Site behaviour to be more like adding a topic
![follow site](https://user-images.githubusercontent.com/50576199/116385754-06fbae80-a811-11eb-9406-0631c3f12c17.png)

**Comment by mohit92** [comment]
I am interested in picking this up. I will start working on it as nobody else seems to be working on it right now.

**Comment by osullivanchris** [comment]
@mohit92 sure thing. Let me know if I can provide more details. The idea was to re-use as much of the same code as possible for both sections. Right now they function totally differently.

**Comment by kean** [comment]
This screen is going to be removed, closing.
