### ISSUE TITLE
Quick Start 'View site' task doesn't scroll to right position on iPad and iPhone

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-iOS#16402]
### Expected behavior
The page should scroll to the bottom and I should be able to see the preview menu item

### Actual behavior
It doesn't auto scroll to the bottom, and the snackbar might hide the menu item even if it does

### Steps to reproduce the behavior
- make a new site
- accept quick start tour
- proceed to 'View your site' task
- notice that it doesn't scroll to the correct position
- hard to access the touch target with the Snackbar
![img_0057](https://user-images.githubusercontent.com/50576199/116527653-d714df80-a8d2-11eb-90dd-3ca586e6ff74.png)

**Comment by dcalhoun** [comment]
I reproduced this same issue on an iPhone Pro 11, iOS 14.6, WPiOS 17.6.0.3. Prior to this point, each previous Quick Start step successfully scrolled and highlighted the relevant UI element. 

<details><summary>Screenshot</summary>

![wpios-next-steps-no-scroll](https://user-images.githubusercontent.com/438664/123326771-3e2fc880-d4ff-11eb-8586-e68f8092872e.jpeg)

</details>

**Comment by Gio2018** [comment]
Hey @osullivanchris , given the recent changes to My Site, do you think we should still keep this issue open?

**Comment by osullivanchris** [comment]
@Gio2018 this could be closed now. We're pointing to the URL at the top instead, so this no longer applies!

**Comment by Gio2018** [comment]
Thanks for confirming @osullivanchris !
