### ISSUE TITLE
Quick Start tour dot displays wrong for homepage task on iPad

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-iOS#16401]
### Expected behavior
Quick start tour indicator points to the Homepage row in Site Pages

### Actual behavior
It points to the row, but it appears as if I have swiped from the right

### Steps to reproduce the behavior
- Make new site on iPad
- Accept Quick Start tour
- Proceed to 'edit your homepage' task
- When you arrive in 'Site pages', the dot indicator displays a bit weird as described
![img_0055](https://user-images.githubusercontent.com/50576199/116527293-6f5e9480-a8d2-11eb-83bb-c7aabce0e257.png)

##### Tested on iPad Pro 11 inch, iOS 14.3, WPiOS v17.2.0.1

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
