### ISSUE TITLE
Quick Start iPad doesn't recognise tap on selected menu item

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-iOS#16400]
### Expected behavior
- When Quick Start tells me to tap on 'Site Pages', I should be able to tap on 'Site Pages' to proceed in the Quick Start tour

### Actual behavior
- As I am already within 'Site Pages', Quick Start doesn't recognise my tap

### Steps to reproduce the behavior
- Create a new site on iPad
- Accept Quick Start Tour
- Leave Tour
- Tap on 'Site Pages' (you are now 'in' the Site Pages section on the right hand of the split view)
- Tap on 'Customise your site' quick start steps
- Select 'Review Site pages'
- Because you are already inside 'Site Pages', it doesn't realise you are tapping there, and you can't proceed in the tour. 
- Only way to free it up is to leave Site Pages, move to another section, and enter the task again.
Quite an edge case in fairness!

##### Tested on iPad Pro 11 inch, iOS 14.3, WPiOS v17.2.0.1
![img_0054](https://user-images.githubusercontent.com/50576199/116526776-e0ea1300-a8d1-11eb-8a10-793a6ab8965e.png)

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
