### ISSUE TITLE
Enhancement: change "Blog Posts" menu label to simply "Posts"

### ISSUE THREAD

**Issue by eduardozulian** [wordpress-mobile/WordPress-iOS#16418]
Now with the Nav Unification in WordPress.com, the dashboard is closely aligned to self-hosted sites. On both dashboards, we have **Posts** as the menu item.

On the mobile devices, however, we still show them as **Blog Posts**. The suggestion is to change it **Posts** so they all match.

### Steps to reproduce the behavior

1. Open the app
2. Tap on My Site
3. Find **Blog Posts**

Context: 3949093-zen

**Comment by eduardozulian** [comment]
Another request in 4130272-zen

**Comment by AliSoftware** [comment]
@eduardozulian I'm working on #17156 to address this and was wondering if we should also change “Site Pages” to just “Pages” in that same screen (even if that one is not mentioned in the original ZenDesk tickets, but just for consistency).

I ended up changing that wording too when working on #17156 but I would love to have your input/confirmation if that's ok to do so.

**Comment by eduardozulian** [comment]
As we chatted in p7cLQ7-1H5-p2#comment-3250, it does make sense to change them to Pages as well.

Thank you again, @AliSoftware!
