### ISSUE TITLE
Remove the Menus configuration from Site Details Screen

### ISSUE THREAD

**Issue by chipsnyder** [wordpress-mobile/WordPress-iOS#16413]
### Desscription
iOS has support to configure Menus via a native interface that has come up as a point of confusion in recent User studies. We'd like to remove this menu (to match Android) and then re-introduce it in a more holistic way during FSE. 

<img width="300" src="https://user-images.githubusercontent.com/3384451/116697806-a182fb80-a991-11eb-932c-7dea188ba059.png">

**Comment by antonis** [comment]
This change request is dropped as discussed in `pbArwn-2c8-p2#comment-3138`
