### ISSUE TITLE
Crash when marking a comment as spam, then approving or unapproving it

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#16431]
### Expected behavior
No crash, marking a comment as spam moves it to the Spam tab immediately

### Actual behavior

https://user-images.githubusercontent.com/66104034/116929050-17e65e80-ac1b-11eb-814c-2697a77dddff.MP4

### Steps to reproduce the behavior
1. Go to Comments and open the detail view of a comment
2. Mark as Spam
3. Notice it does not move to the Spam tab
4. Tap on Approve/Unapprove 
5. Crash

**Comment by ScoutHarris** [comment]
Hey @startuptester .

I'll take a look at the crashing. Automatically moving Comments to other tabs is part of the upcoming Comment Unification project (pbArwn-2ej#comment-3225), so I'll probably leave that for now. But I'll report back once I've looked at it.

**Comment by ScoutHarris** [comment]
Hey @startuptester .

1) The crash is fixed. 
2) As noted in the [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/16645), multiple moderation actions on a Comment resulted in some weird states. So now the Comment details view is dismissed after any Comment moderation action (approve, unapprove, trash, spam). 
3) Just wanted to point out something that may not be obvious if you're not aware of it. If you Trash a Spam comment, the comment is _permanently_ deleted, i.e. it doesn't appear in the Trash filter and simply disappears. This isn't new behavior, and matches the web. But it's more obvious now with the filters. Our messaging isn't clear about what happens (which I'll be fixing), so it can be confusing.
