### ISSUE TITLE
Accessibility: VoiceOver + large text makes scroll impossible in the publishing sheet

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#16460]
### Expected behavior

1. When using large titles and voice over
2. The user is able to use the 3-swipe gesture to scroll the prepublishing sheet

### Actual behavior

1. The scroll doesn't happen

### Steps to reproduce the behavior

1. Go to iOS settings: Accessibility > Display & Text Size  > Larger text
2. Enable "Larger Accessibility Sizes"
3. Put the text at the biggest possible size
4. Enable VoiceOver
5. Go to WordPress and into the flow of publishing a post (Blog Posts -> New -> enter title -> tap Publish)
6. Using 3 fingers gestures, try to scroll in the republishing sheet
7. Nothing happens

**Comment by ScoutHarris** [comment]
Looks similar/related to https://github.com/wordpress-mobile/WordPress-iOS/issues/16384.

**Comment by leandroalonso** [comment]
@ScoutHarris they're a little bit different: #16384 is about a cue that it can be scrollable. In this case, it's not possible to scroll at all.

But they're def related!

**Comment by momo-ozawa** [comment]
Closed via #16501
