### ISSUE TITLE
Reader: duplicated posts under lists

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#16466]
Few users reported duplicated posts under lists. This normally is fixed after a pull to refresh:

<img src="https://user-images.githubusercontent.com/7040243/117727050-e4c54180-b1bd-11eb-9870-0a203ef2c62e.png" width="300">

### Steps to reproduce the issue

1. Follow any list
2. The first time the issue will probably not happening
3. Leave the app in the background for a few hours
4. When you get back posts will be duplicated

**Comment by dougaitken** [comment]
I've replicated this on the initial list that was reported, the "a12s" list but I also have it on a list I created about 4 years ago and another that I followed but didn't create about 2/3 years ago. I can link to lists if needed.

I can replicate on 
iOS 14.5.1 (18E212)
iPhone XS
WordPress internal beta Version 17.3 (17.3.0.20210507)

Happy to offer debug files but unsure if that's helpful if others can reproduce
