### ISSUE TITLE
Issue with page-type label in the pages list.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#16473]
As reported here: https://github.com/wordpress-mobile/WordPress-iOS/pull/16437#pullrequestreview-653263355

In the pages list, there's a label to describe the type of page.  When enabling large text in a small screen the label becomes cut.

<img src="https://user-images.githubusercontent.com/4780/117285911-74868b00-ae60-11eb-904a-a8cfed2296eb.png" width=250>

@frosty suggested to either use a horizontal stack view, and make it vertical on smaller screens, or to hide the label using something like this:

```swift
    [[NSNotificationCenter defaultCenter]
      addObserver:self
         selector:@selector(contentSizeCategoryDidChange)
             name:UIContentSizeCategoryDidChangeNotification
           object:nil];
}

- (void)contentSizeCategoryDidChange
{
    NSArray *accessibilitySizes = @[
                              UIContentSizeCategoryAccessibilityMedium,
                              UIContentSizeCategoryAccessibilityLarge,
                              UIContentSizeCategoryAccessibilityExtraLarge,
                              UIContentSizeCategoryAccessibilityExtraExtraLarge,
                              UIContentSizeCategoryAccessibilityExtraExtraExtraLarge
    ];

    BOOL shouldHide = [accessibilitySizes containsObject:self.traitCollection.preferredContentSizeCategory];
    [self.typeLabel setHidden:shouldHide];
}
```

### Steps to reproduce the behavior

Go to iOS Settings > Accessibility > Large Text and enable a really large font size.
Go back to WPiOS and look at the list of pages for a site that has a "Homepage".

**Comment by jkmassel** [comment]
We're cutting `17.5` today, so this PR is being bumped to `17.6`

**Comment by kean** [comment]
This screen was redesign in 23.7 – closing as obsolete.
