### ISSUE TITLE
Bottom sheets are incorrectly sized on iPad split screen.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#16492]
[Reported](https://github.com/wordpress-mobile/WordPressUI-iOS/pull/89#pullrequestreview-657798706) by Frosty:

> On iPad in splitscreen (so the app is half or 1/4 of the screen), the bottom sheet appears to take up the entire height of the display. This only seems to happen on iPad, not on iPhone. I confirmed that this also happens on `develop`.

![Simulator Screen Shot - iPad Pro (11-inch) (2nd generation) - 2021-05-12 at 12 31 26](https://user-images.githubusercontent.com/4780/117971964-72ba3d00-b322-11eb-9dbb-e8026dd8af76.png)

Bottom sheets should correctly sized when the app is in split screen node on the iPad.

**Comment by kean** [comment]
The presentation appears to be correct considering it's a `.compact` horizontal size class.
