### ISSUE TITLE
Consistently show popovers on iPad

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#16491]
[Reported](https://github.com/wordpress-mobile/WordPressUI-iOS/pull/89#pullrequestreview-657798706) by Frosty: 
> On iPad, I noticed that some popovers appear below the tapped row, and some on the left. It might be good to change the permittedArrowDirections property to ensure this is consistent (I think perhaps always pointing to the left might be the best).

It would be good to audit everywhere we are presenting popovers and ensure they are presented consistently in the space available.

**Comment by kean** [comment]
In 25.4, popovers were adopted throughout the app on iPad – closing.
