### ISSUE TITLE
Lost access to WP app

### ISSUE THREAD

**Issue by cavrich** [wordpress-mobile/WordPress-iOS#16516]
I use the Wordpress on my iphone to view all my WP blog stats (from jetpack I think). I;ve been using the app for years.

About a week ago, the screen went blank. It's now a blue screen with the WP logo and that's it. There are no links, buttons, nothing - completely blank. 

I checked my Jetpack plugin but can't see anything to do there. The stats are showing on my desktop. I did change my theme last week (to Kadence) so I don't know if that has anything to do with it. I checked the app in my iphone settings, but there is nothing I see to do anything. I can't even delete the app. 

How can I get my app working again to view my stats? Thanks very much for your help.

**Comment by cavrich** [comment]
Where do I find those? I don’t see where to add type label and feature label. Is it within the body of the message?  Thanks, Cheryl (sorry, first timer)

**Comment by startuptester** [comment]
This issue was resolved via support channels.
