### ISSUE TITLE
Posts: The time a scheduled post will publish can be confusing

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#16514]
When scheduling a post it's not always clear if the scheduled date/time refers to the user's local timezone or the blog's time zone as set in `wp-admin > Settings > General`.

The app appears to consistently show the date in the blog's timezone.  However, out of the five following examples the only place the time zone is specified is in the section footer of the Post Settings Publish Date Screen.

## Date Picker Control:
![IMG_2418](https://user-images.githubusercontent.com/1435271/118535992-c8228f80-b710-11eb-8a38-f99de609cbf0.PNG)

## Post Settings Publish Date Screen
![IMG_2419](https://user-images.githubusercontent.com/1435271/118535998-ca84e980-b710-11eb-9ad2-41379ce5fe65.PNG)

## Post Settings Published On Row
![IMG_2420](https://user-images.githubusercontent.com/1435271/118536065-dffa1380-b710-11eb-832b-cee3b9960ae9.PNG)

## Pre-Publish Bottom Sheet
![IMG_2421](https://user-images.githubusercontent.com/1435271/118536094-e9837b80-b710-11eb-98b9-5894092471fa.PNG)

## Post List Post Card
![IMG_2422](https://user-images.githubusercontent.com/1435271/118536123-f30ce380-b710-11eb-880a-06483bb5196e.PNG)

Meanwhile, on the web the scheduled date can be shown in the blog's timezone or the user's local time depending on the view. The only place the timezone is shown is the Editor's date picker:

### Calpyso's post list (local time)
<img width="513" alt="Screen Shot 2021-05-17 at 1 20 40 PM" src="https://user-images.githubusercontent.com/1435271/118537539-af1ade00-b712-11eb-9907-7312631ba474.png">

### Editor's Date Picker
<img width="289" alt="Screen Shot 2021-05-17 at 1 21 29 PM" src="https://user-images.githubusercontent.com/1435271/118537624-cce84300-b712-11eb-97a1-26743f7aa5d4.png">

### Editor's pre-publish summary
<img width="284" alt="Screen Shot 2021-05-17 at 1 21 06 PM" src="https://user-images.githubusercontent.com/1435271/118537584-be019080-b712-11eb-9870-0929f683337b.png">

### wp-admin's Post List
<img width="202" alt="Screen Shot 2021-05-17 at 1 22 27 PM" src="https://user-images.githubusercontent.com/1435271/118537723-ef7a5c00-b712-11eb-9800-63d2c82f7b39.png">

# Clarifying the date
Perhaps we can help clarify things by always showing the timezone with the schedule/publish date wherever it appears.

**Comment by kean** [comment]
If the site is in a different timezone, the picker nows shows the time offset, the blog timezone, and a warning shown your local time (pcdRpT-6vS-p2)
