### ISSUE TITLE
Jetpack/Stats: Tapping "more information" shows the FAQ but not anything specific to Jetpack

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#1652]
Title has it. 

![jetpack_stats](https://cloud.githubusercontent.com/assets/1435271/2831187/6a24b582-cfb6-11e3-919b-06102ca33d31.jpg)

**Comment by aerych** [comment]
Status on this one?

**Comment by koke** [comment]
Will be fixed in #3652

**Comment by koke** [comment]
Hmm, not really. #3652 fixes the link, but it seems to render scroll to the wrong place in the FAQ

https://cloudup.com/cygJDIw1__S

**Comment by aerych** [comment]
Interesting. When I tried in the 8.2 simulator it jumped to the correct location, but on the 8.3 simulator I reproduced the loading glitch.

**Comment by koke** [comment]
This seems to work fine on the latest beta
