### ISSUE TITLE
Refresh spinner freeze when switching tabs

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#1653]
A slow connection / iPhone 4 makes this more apparent. 
To reproduce:
Open your post list, and pull to refresh. (Can also use the Reader)
Quickly tap to another tab.
Quickly tab back. 
The pull to refresh spinner is still visible but frozen. 

Might just be an issue on slower hardware.

**Comment by rachelmcr** [comment]
I tested this on a slow connection (Edge network) and reproduced the issue. However, a moment after I saw the frozen refresh spinner, the post list finished refreshing and the frozen spinner disappeared.

This seems like a relatively minor/rare issue; I propose wontfixing it.

**Comment by aerych** [comment]
Thanks for testing @rachelmcr!  This one slipped through the cracks, and we have a new post and page list since this issue was opened. Interesting to learn its still an issue. 

Without testing, I think the fix might be as simple as making a call to `UIActivityIndicatorView startAnimating` in `viewWillAppear:` if the activity view is visible.

**Comment by aerych** [comment]
I'm going to close this as wont fix. When returning to the controller while the sync is still in process, `UIRefreshControl.refreshing` is `true`, and calling `begingRefreshing` causes no change in the spinner behavior.  I did a bit more digging and this behavior can be reproduced even in the simplest test project. I'm inclined to consider this a framework bug.

**Comment by rachelmcr** [comment]
:+1:
