### ISSUE TITLE
Author filter should default to Everyone instead of Me

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#16593]
### Expected behavior

On a multi-author site, the Post List and Page List screens should show the default active author filter as "Everyone".

As @enejb mentioned offline, [now that users can change author of posts and pages](https://github.com/wordpress-mobile/WordPress-iOS/pull/16281), having "Everyone" be the default active filter, instead of "Me", makes more sense. This is because user's posts "disappear" from the Post List when their author is changed to someone else and the "Me" filter is active, which can lead to user confusion. By changing to a default of "Everyone", we can largely avoid this user confusion.

### Actual behavior

The default active filter is "Me" (when it should be "Everyone"), as noted above.

### Steps to reproduce the behavior

1. Log in to a WP.com account that has access to a multi-author site (logging into a multi-author self-hosted site could work as well)
2. Open the Post List (if you don't see the filter, see https://github.com/wordpress-mobile/WordPress-iOS/issues/16592)
3. Notice the active filter is "Me" when it should be "Everyone"

**Comment by kean** [comment]
[@osullivanchris](https://github.com/osullivanchris), thoughts on this? I was also confused when I invited my other account to a site and saw no posts when I logged it. I think showing "Everyone" makes more sense regardless of the "change author" feature. The web defaults to "Everyone". Do you know the reason for selecting "Me" on mobile?

**Comment by osullivanchris** [comment]
@kean not sure why it wouldn't default to 'everyone'. Definitely agree to change/fix it

**Comment by kean** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/21766
