### ISSUE TITLE
Discover: when restoring posts disappear

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#16663]
### Expected behavior

When the app is restored in Reader/Discover, posts are updated.

### Actual behavior

When the app is restored in Reader/Discover, the no results VC is shown.

<img src="https://user-images.githubusercontent.com/7040243/121536394-64bb1300-c9d9-11eb-9c09-933f87389615.gif" width="300">

### Steps to reproduce the behavior

1. Open the app and go to Reader > Discover
2. Put the app into the background
3. Kill the app
4. Re-run the app

### Additional info

The posts shown in Discover are cleared when the app starts. This is probably causing this issue when Discover is shown right away.

##### Tested on iPhone 11 (13.7) simulator

**Comment by startuptester** [comment]
@leandroalonso, I'm no longer able to repro this in the 18.1 beta. Does it still occur for you?

**Comment by kean** [comment]
State restoration is removed. It was causing multiple issues across the app, including this one. The app now uses an ad-hoc mechanism that restores your previous selection the way it's typically done in modern apps and SwiftUI.
