### ISSUE TITLE
Comment/Notification lists: update to use the same UI

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#16738]
Update Comments and Notifications lists to use the same UI.

- [x] Add feature flag.
- [x] #16740 
- [x] #16741
- [x] Accessibility.
- [x] Tracks.
- [ ] Enable feature flag and add release note.

Designs from Zeplin:

| ![Comment List iOS](https://user-images.githubusercontent.com/1816888/123323891-631e3e80-d4f3-11eb-8ab9-25b815b450fc.png) | ![Nofications iOS](https://user-images.githubusercontent.com/1816888/123323903-674a5c00-d4f3-11eb-868d-36d094a005e3.png) |
|--------|-------|

**Comment by dvdchr** [comment]
### Accessibility Review
- Tested that the new components works correctly with VoiceOver.
- Improved undo overlay layout for large text sizes.

### Tracks Review
- The use of unified list leaves `NoteTableViewCell`, `NoteTableHeaderView`, and `CommentsTableViewCell` unused. I've verified that there are no tracking requests made from the three components above.
- No new tracking events needed for the new list components.

### Next Steps

Once #16962 is merged, I'll open a PR that enables the feature flag by default, and add an entry to release notes.
