### ISSUE TITLE
Stories text overflows the height of the colored background

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/WordPress-iOS#16742]
### Expected behavior
The text is contained within the color background element.

### Actual behavior
The text overflows the color background element, causing potential legibility issues.

### Steps to reproduce the behavior
1. Log into a WPCom account in the WPiOS app. 
2. Tap the FAB.
3. Tap Story post. 
4. Add an image to the post. 
5. Add text to the image. 
6. Toggle the background color. 

##### Tested on iPhone 11 Pro, iOS 14.6, WPiOS 17.6.0.3

<details><summary>Screenshot</summary>

![wpios-stories-text](https://user-images.githubusercontent.com/438664/123326494-ed1fd480-d4fe-11eb-9ad2-8c6cb9a3796b.jpeg)

</details>

**Comment by erricgunawan** [comment]
> I noticed when customising the text the background colour doesn’t cover the whole height of the text. It’s the same with each font.

<details>
  <summary>Screenshot:</summary>
  <br>
  
![Attachment1CAFC522-A73F-48AF-A514-4CDA704812D5](https://user-images.githubusercontent.com/1813857/183561257-fabbbf49-4e51-4682-ab30-e0de517638f6.jpeg)

  
</details>

5455064-zen
