### ISSUE TITLE
Jetpack: Display Error Screen for Disabled Stats Module

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-iOS#16753]
Android Issue: [WordPress-Android#14942](https://github.com/wordpress-mobile/WordPress-Android/issues/14942)

Currently, we don’t indicate to the user that the `Stats` module is disabled. Instead, we display a generic loading error, see below:

<img src="https://user-images.githubusercontent.com/9729923/123419165-8fed5700-d5c2-11eb-8a66-e68b8beabaab.png" width="250" height="500">

We should consider displaying the same error screen we show in `Calypso`, see below:

![Jetpack App - Show Error Screen for Disabled Stats Module (Calypso)](https://user-images.githubusercontent.com/9729923/123419363-d0e56b80-d5c2-11eb-89b2-015ef440e28f.png)

**Comment by osullivanchris** [comment]
Thought we could just use web content with our existing empty state style. 

Image optional. Button only if action is possible, obviously! 

<img width="574" alt="Screenshot 2021-07-02 at 00 41 56" src="https://user-images.githubusercontent.com/50576199/124200867-4e7f0f00-dace-11eb-934c-aaa2059b0370.png">
