### ISSUE TITLE
Jetpack: Display Scan Not Available Screen for Unavailable Scan State

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-iOS#16755]
Android Issue: [WordPress-Android#14946](https://github.com/wordpress-mobile/WordPress-Android/issues/14946)

If a site is a multisite, the scan endpoint returns `unavailable` for the scan state.

GET: `https://public-api.wordpress.com/wpcom/v2/sites/SITE_ID/scan`
RESPONSE:
```
{
    "state": "unavailable",
    "threats": null,
    "has_cloud": false,
    "reason": "multisite_not_supported"
}
```

Currently we are not doing any anything for this `unavailable` the state, we display the `Don’t worry about a thing` green state, which is actually a bug, see below:

NOTE: Note that on iOS there’s a method to check [if scan is available](https://href.li/?https://github.com/wordpress-mobile/WordPress-iOS/blob/a3eae1d75066b28c215180cafd12e4947c74e556/WordPress/Classes/Services/JetpackScanService.swift#L11-L18), but we’re not calling the method.

<img src="https://user-images.githubusercontent.com/9729923/123429805-0e9cc100-d5d0-11eb-9470-ce7e857438e5.png" width="250" height="500">

We should consider displaying the same view we show in `Calypso`, see below:

![Jetpack - Display Scan Not Available Screen for Unavailable Scan State (Calypso)](https://user-images.githubusercontent.com/9729923/123429812-12c8de80-d5d0-11eb-8752-047fdd82195e.png)

**Comment by osullivanchris** [comment]
As with the stats error, I thought we could just use the web content with our standard empty state style.

<img width="454" alt="Screenshot 2021-07-02 at 00 46 12" src="https://user-images.githubusercontent.com/50576199/124201062-e846bc00-dace-11eb-9713-45d12ef86690.png">
