### ISSUE TITLE
Jetpack: Hide Restore Option for Unavailable Rewind State

### ISSUE THREAD

**Issue by ParaskP7** [wordpress-mobile/WordPress-iOS#16754]
Android Issue: [WordPress-Android#14945](https://github.com/wordpress-mobile/WordPress-Android/issues/14945)

If a site is a multisite, the rewind endpoint returns `unavailable` for the rewind state, see:

GET: `https://public-api.wordpress.com/wpcom/v2/sites/SITE_ID/rewind`
RESPONSE:
```
{
    "state": "unavailable",
    "threats": null,
    "has_cloud": false,
    "reason": "multisite_not_supported"
}
```

Currently, we are not doing anything for this `unavailable` state, we continue displaying the restore option, see below:

<img src="https://user-images.githubusercontent.com/9729923/123427071-d47df000-d5cc-11eb-9e74-2fed33131b05.png" width="250" height="500">

We should consider displaying the same view we show in `Calypso` and hide, or at least disable, the restore option, see below:

![Jetpack App - Display Restore Not Available for Unavailable Rewind State (Calypso)](https://user-images.githubusercontent.com/9729923/123427269-160e9b00-d5cd-11eb-831b-5c44c073d1b4.png)

**Comment by leandroalonso** [comment]
@osullivanchris what do you think about this solution on iOS?

<img width="391" alt="Screen Shot 2021-06-28 at 17 12 08" src="https://user-images.githubusercontent.com/7040243/123698160-312f1400-d834-11eb-93dc-425e9477ec75.png">

The only downside is that we don't have the documentation link, but give this is a system component we have a low cost for a big benefit (with accessibility and everything else).

**Comment by osullivanchris** [comment]
👋  @leandroalonso  hey it looks pretty good. I wonder if the user is expecting to find restore there or not. Maybe they already know. Its an improvement anyway so lets do it to start! 

Do we have the same problem on the event detail view or are we hiding the button? There, we have more space to explain, so could be more similar to Calypso with an explanation in the page. Also similar to Server Credentials errors.

**Comment by leandroalonso** [comment]
> Do we have the same problem on the event detail view or are we hiding the button? There, we have more space to explain, so could be more similar to Calypso with an explanation in the page. Also similar to Server Credentials errors.

This is a very good point. I knew I was forgetting something, will work there and get back to you.

**Comment by leandroalonso** [comment]
@osullivanchris this is how the detail looks like for a multisite:

<img src="https://user-images.githubusercontent.com/7040243/124171719-4cda2a80-da7f-11eb-8c83-a213f40d511a.png" width="300">

**Comment by osullivanchris** [comment]
Nice! I mocked it up today. But landed on more or less the same thing. I had the button disabled, so you know the feature exists. But its probably not worth changing, what you have is good.

<img width="985" alt="Screenshot 2021-07-02 at 00 42 55" src="https://user-images.githubusercontent.com/50576199/124200916-72425500-dace-11eb-838d-1a10f0ec95bf.png">
