### ISSUE TITLE
No option to download media from the site's Media Library into the device

### ISSUE THREAD

**Issue by iamgabrielma** [wordpress-mobile/WordPress-iOS#16762]
User on 4093679-zen reported that they're unable to save their Media into their device in iOS, however this is a possibility with Android:

> Is there a way to download images from the Wordpress site content library back onto the iPhone (maybe to camera roll)? This is possible on the android app but I don’t see how to do it in iOS.

I was able to reproduce this with 17.2 and 17.5, there's no option to save to the device.

### Expected behavior
I expected that "Save to Folder" (or similar) would be one of the available options when we open a Media item from the site Media Library. 

### Actual behavior
We can only see options to share to other services, depending on what's installed in each device.

### Steps to reproduce the behavior
- Go to Media Library
- Open a Media element
- Click on "^" to see the image options
- See how there's no "Save" option

**Comment by kean** [comment]
It was added one of the 23.x releases.
