### ISSUE TITLE
Update UI editor tests to handle blogging reminders

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#16797]
Since the introduction of the new blogging reminders feature, our UI tests started failing (e.g. [this](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-iOS/22603/workflows/712983ac-3548-4e69-b4cb-785175261983/jobs/52000?invite=true#step-106-479) and [this](https://app.circleci.com/pipelines/github/wordpress-mobile/WordPress-iOS/22603/workflows/712983ac-3548-4e69-b4cb-785175261983/jobs/52000?invite=true#step-106-479)) because there is no backed-in way to dismiss the blogging reminder notice after publishing a post.

<img width="300" alt="Screen Shot 2021-07-02 at 5 33 50 pm" src="https://user-images.githubusercontent.com/1218433/124238667-35bd3a80-db5c-11eb-928b-b0ba70270615.png">

**Comment by mokagio** [comment]
I think the work to fix this will be a good occasion to adopt [ScreenObject](https://github.com/Automattic/ScreenObject/) and [XCUITestHelpers](https://github.com/Automattic/XCUITestHelpers/), starting with finishing #16648.

**Comment by tiagomar** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/17455
