### ISSUE TITLE
Option to Save Post as Draft from Share Sheet

### ISSUE THREAD

**Issue by mdrockwell** [wordpress-mobile/WordPress-iOS#16813]
### Expected behavior
When using the WordPress app share sheet extension, there should be an option to save the post as a draft.

### Actual behavior
When using the WordPress app share sheet extension, there is only the option to publish.

### Steps to reproduce the behavior
- Initiate the WordPress app's share sheet extension from anywhere it's available (from a photo, a web page, with selected text, etc.)
- Compose a post.
- Tap "Next"

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPhone 11 Pro, iOS 14.6, WPiOS 17.7

4109866-zd-woothemes

**Comment by rogermedia** [comment]
Yes please to this option. I personally use the share sheet option mostly to save things for later use. In the case of a blog post I want to create a draft of a website I am reading in Safari. Being able to save to a draft directly into my self hosted WP site would be wonderful. I created a post with screenshots to show a final page mockup with a Draft option next to the Publish button: https://rogerbikes.com/2022/02/17/wordpress-for-iphone-forums-requests-and-feedback/

iPhone XR, iOS 15.3.1, WPiOS 19.1.1.0

**Comment by reginabally** [comment]
We have a user who lost the content they added via the Share extension because they didn't publish the post. They thought the app would save the content as a draft when they closed the screen.

> I always see that it saves automatically until I publish. I didn’t publish it. I went back to finish and it was just gone.

iPhone 12, iOS 15.4.1, WPiOS 19.8.1

5257289-zd-woothemes

**Comment by twstokes** [comment]
👋 Hello all, there should be a "Save as Draft" action in the Share Sheet. You may have to tap "Edit Actions" to enable and promote it to the top.

<img src="https://user-images.githubusercontent.com/2092798/231909562-206cb098-bd56-4857-9ae6-6b3302474dfd.png" width="300" />

**Comment by twstokes** [comment]
Related: https://github.com/wordpress-mobile/WordPress-iOS/issues/20541

**Comment by tiagomar** [comment]
Closing this ticket since the [option is actually available](https://github.com/wordpress-mobile/WordPress-iOS/issues/16813#issuecomment-1507757181) and  there's an [enhancement ticket to improve the experience](https://github.com/wordpress-mobile/WordPress-iOS/issues/20541).
