### ISSUE TITLE
Signup is stuck on epilogue when there is an existing self-hosted site

### ISSUE THREAD

**Issue by Gio2018** [wordpress-mobile/WordPress-iOS#16824]
### Expected behavior
Signing up with a new account after adding a self-hosted site should dismiss the signup epilogue and the app should be usable

### Actual behavior
the signup epilogue does not dismiss and I can't use the app

### Steps to reproduce the behavior
- Install the app from scratch or logout
- Add at least a self hosted site if necessary 
- Signup with a new account
- Tap "Done" on the signup epilogue and verify that it does not dismiss

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 11 Pro MAx iOS 14.6, WPiOS version: 17.7 and `develop`

cc @startuptester

**Comment by diegoreymendez** [comment]
Resolved in 17.7.
