### ISSUE TITLE
Blogging reminders buttons not responding

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#16820]
### Expected behavior

The buttons to "Set reminders" or close the blogging reminders button sheet should work.

### Actual behavior

On my device, the "Set reminders" and close buttons on the blogging reminders button sheet don't work.

### Steps to reproduce the behavior

1. Locate a site that uses a blogging template (i.e. at site creation, a template under the Blog category was chosen)
2. Create and publish a new post
3. Observe the Blogging Reminders bottom sheet is shown
4. Notice that neither the "Set reminders" button nor the close button (X icon) work

A few things to note:
- While this bug is 100% reproducible on my physical iPhone 11 running iOS 14.5, it seems like this bug is not reproducible for others
  - I tried to reproduce on a physical iPad and also an iPhone simulator but it appears that blogging reminders is disabled in both these environments (just a guess, because the bottom sheet isn't shown at all when I publish a post)
- The `wpios_blogging_reminders_button_pressed` Tracks event isn't called when I tap the button
- The button dims/highlights when I press it, so it is receiving the touch event
- I checked the code and the "Set reminders" button is hooked up to the [`getStartedTapped`](https://github.com/wordpress-mobile/WordPress-iOS/blob/f43a27ee0ecc452816f91dd896cdda542dfd8c36/WordPress/Classes/ViewRelated/Blog/Blogging%20Reminders/BloggingRemindersFlowIntroViewController.swift#L167) function. I put a breakpoint there and it was not called, which is very unusual since [this function is the button's action](https://github.com/wordpress-mobile/WordPress-iOS/blob/f43a27ee0ecc452816f91dd896cdda542dfd8c36/WordPress/Classes/ViewRelated/Blog/Blogging%20Reminders/BloggingRemindersFlowIntroViewController.swift#L50).

https://user-images.githubusercontent.com/1898325/124764297-cc924a00-df02-11eb-9f0b-de8401f52cfb.MP4

**Comment by startuptester** [comment]
Keeping an eye on this since no other beta testers were able to repro it

**Comment by eduardozulian** [comment]
I tested this and couldn't reproduce it with an iPhone 7, iOS 14.6, WPiOS 17.9.0.4

**Comment by guarani** [comment]
I think this issue was resolved and had a similar root cause to https://github.com/wordpress-mobile/WordPress-iOS/pull/17976. I can't reproduce this anymore so I'm closing.
