### ISSUE TITLE
Error Replying to Comments as Author on an Atomic Site

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#16859]
### Expected behavior

As of https://github.com/wordpress-mobile/WordPress-iOS/pull/16783, it should be possible for authors to like and reply to approved comments. I confirmed that this works as expected while logged into a simple WordPress.com site as an author and it'd be my expectation for this to be true while logged in as an author on an Atomic site.

### Actual behavior

While logged in as an author on an Atomic site, I see an "unexpected error" at the bottom of the screen when attempting to reply to an approved comment. You'll see this in the following "before" screenshot, with the "after" screenshot showing that my comments were published but seem as though they're from an "anonymous" source:

| Before  | After |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/2998162/125513174-6ae09df2-0fc1-4d7e-8570-4b1e01c066da.PNG" width="100%"> | <img src="https://user-images.githubusercontent.com/2998162/125513137-6b2cc6de-b17e-4e3c-9765-0b0b276fc52c.PNG" width="100%">

Possibly related to https://github.com/wordpress-mobile/WordPress-iOS/issues/16858, which outlines the fact that authors on Atomic sites aren't currently able to publish or edit their own posts from the app.

### Steps to reproduce the behavior

_**Prequisite: To test, you'll need to be assigned as an author on an Atomic site. The Atomic site should also have some existing, approved comments.**_

* Log into an Atomic site that you're an author on.
* Navigate to _My Site_ → _Comments_.
* Reply to any of the approved comments.

##### Tested on iPhone XR, iOS 14.6, WPiOS 17.8

**Comment by ScoutHarris** [comment]
Fixed with #16869 .
