### ISSUE TITLE
Can't enter Jetpack Install / Connect flow from Stats

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-iOS#16867]
### Expected behavior
After adding a self-hosted site to the app, I expect to go to My Site > Stats and either Install or Connect Jetpack.

### Actual behavior
In 17.8.0.1, I am presented with a notice "Enable Site Stats" instead of the "Install" or "Connect" button.
Tapping the "Enable Site Stats" button results in a reload animation, and the "Enable Site Stats" button remains.

<img src="https://user-images.githubusercontent.com/15107387/125652540-acb9098b-028f-4085-a67f-2fd96a7e4c26.PNG" width="50%">

This is not the case in 17.7, where I see "Install Jetpack" as expected.

### Steps to reproduce the behavior
1. Add a self-hosted site which is not connected via Jetpack 
2. Go to My Site > Stats

**Comment by mokagio** [comment]
A fix for this has been bundled as part of [17.8 beta 2 (17.8.0.2)](https://github.com/wordpress-mobile/WordPress-iOS/pull/16878).
