### ISSUE TITLE
Mobile IAP Package: Project Issue

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#16861]
## Description
This is the parent project issue for Mobile IAP. We'll be using this issue to keep track of the Mobile IAP project's progress.

## Notes
- We'll be using the [original StoreKit API](https://developer.apple.com/documentation/storekit/original_api_for_in-app_purchase). This is because [StoreKit2 is iOS 15+](https://developer.apple.com/documentation/storekit/choosing_a_storekit_api_for_in-app_purchase), and we probably won't be able to drop iOS 14 support until late 2022 / early 2023.
- [MobilePayKit](https://github.com/Automattic/MobilePay-Apple) will be built as a multiplatform (iOS/macOS) **Swift Package**.
- We’ll define the API calls inside the Mobile IAP package instead of WPKit to avoid library interdependence. To authenticate, **we'll pass a bearer token** from the app.
- The following tasks were created with **Consumables** in mind. However, we should be able to extend the Mobile IAP package to support [Subscriptions](https://developer.apple.com/documentation/storekit/original_api_for_in-app_purchase/subscriptions_and_offers) in the future.
- Restoring purchases will not be a part of the MVP, as [Consumables aren't restorable](https://developer.apple.com/documentation/storekit/skpaymentqueue/1506123-restorecompletedtransactions).

## Tasks

- [x] #16862
- [x] #16864
- [x] #16863
- [x] #16930
- [x] #16865
- [x] #17018
- [x] #16894
- [x] Review project structure
- [x] Add UI for macOS demo app
- [x] Write documentation

**Comment by leandroalonso** [comment]
@momo-ozawa I added a new task to review the project structure. https://github.com/Alamofire/Alamofire is a great example of a library that supports SPM and Cocoapods and I think we can borrow a lot of ideas from them (it was one of the sources I used when working on https://github.com/wordpress-mobile/MediaEditor-iOS). :)

**Comment by leandroalonso** [comment]
Added a new task: write documentation
