### ISSUE TITLE
Mobile IAP Package: Publish MobilePayKit

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#16894]
Project Issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/16861

## Description

- Add CI for Cocoapods (part of Platform 9's BuildKite migration tasks)
- Find out how to handle publishing Swift Package

**Comment by momo-ozawa** [comment]
Hey @mokagio 👋 (cc: @jkmassel @leandroalonso)

I'm closing [the project issue for MobilePayKit](https://github.com/wordpress-mobile/WordPress-iOS/issues/16861), and wanted to check in on the status of the Buildkite migration project. Has CI for cocoapods been added for the MobilePaykit project?

**Comment by mokagio** [comment]
Hey @momo-ozawa, thank you for the ping 😄 

> Has CI for cocoapods been added for the MobilePaykit project?

I'm not up to speed on this project, sorry, but, from what I can see on [the current `develop` of what I think is the library's repo](https://github.com/Automattic/MobilePay-Apple/tree/75abcb7c38e6ef7fca3cf6a8907afe410a2239c3) the answer is no. 

Could you please post a request in our internal Apps Platform Requests P2, so we can prioritize and assign it?

_Apologies in advance if this had been discussed elsewhere already and I missed it._

Thanks 🙇

**Comment by momo-ozawa** [comment]
Request submitted here: paaHJt-2Gr-p2
