### ISSUE TITLE
Update to GoogleSignIn version 6.x

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#16924]
On 2021/7/13 Google published a new major version of its GoogleSignIn library, version 6.0.0.

From the [release notes](https://developers.google.com/identity/sign-in/ios/release).

- Google Sign-In for iOS is now [open source](https://github.com/google/GoogleSignIn-iOS/).
- Swift Package Manager support.
- Support for Simulator on M1 Macs.

The aim of this issue is to start the discussion around how to upgrade.

**Comment by dvdchr** [comment]
Thanks for filing this issue, @mokagio! This should be addressed in #16974. 🙂

**Comment by mokagio** [comment]
Well done @dvdchr! Thanks 🙌
