### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#16941]
A new [change in App Store Review Guideline](https://developer.apple.com/news/?id=dovxb62h) adds this update:

> 5.1.1(v): Apps supporting account creation must also offer account deletion.

In order to conform to this, we need to implement account deletion on our app.

In Calypso we have the following rule to allow account deletion: https://github.com/Automattic/wp-calypso/blob/b550e845f46f9c93641f54193d73626cb5b669e9/client/me/account-close/main.jsx#L90

The endpoint for account deletion is `v1.1/me/account/close`

**Comment by mokagio** [comment]
See also related PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/17075 and https://github.com/wordpress-mobile/WordPress-iOS/pull/17076.
