### ISSUE TITLE
Login Epilogue: Site with long title is not truncating

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-iOS#17010]
When viewing the Login Epilogue, sites with long titles are not truncating (showing ellipse)

### Expected behavior
Site with long titles to truncate and show an ellipse

### Actual behavior
Sites with long titles are shown in full taking up a good portion of the view.

### Steps to reproduce the behavior
- Create a site with a very, very, very, long title
- Logout of the app
- Log back into the app
- Notice the site with the long title is not truncated

<kbd><img src="https://user-images.githubusercontent.com/506707/129097764-93102fef-3d85-4d0f-bf43-736c224b150e.jpg" width="350" /></kbd>

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPhone, iOS 14.6, WPiOS 18.0

**Comment by s0sharma** [comment]
Hi, I would like to work on this, can you suggest me ways to get started?

**Comment by ScoutHarris** [comment]
Hey @zwarm . This view is displayed by the `LoginEpilogueTableViewController`. For the site rows, it uses `LoginEpilogueBlogCell`.

**Comment by zwarm** [comment]
@s0sharma Thanks for jumping in, we're happy to have you contribute.

@ScoutHarris has provided some detail on what classes this logic resides in. And a very gracious thanks to them, as my primary focus is Android so I'm a bit rusty when it comes to the iOS code base. This should be a great starting point.

Once you have a working solution, I suggest you head over to our [Contribution Guide](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/CONTRIBUTING.md) for details on how to contribute the fix, make pull requests and other important details. 

Thanks again!

**Comment by giovannapezzini** [comment]
Hi @zwarm, it's been a month since the last reply so I took the liberty to create a PR fixing the issue. 🙂
