### ISSUE TITLE
Unactionable notifications for likes on P2s

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#17038]
This issue is from a Mobile Request

> Recently I started noticing that there are a few notifications that I can’t “tap” from the WordPress app.
> From what I can see they are usually Like notification for P2 comments/posts

### Actual behavior
If I tap it – nothing happens. I can use the other default iOS controls for the notification, but only that.

To see it I need to open the WP app and mark it as seen there as it doesn’t disappear if I just open the app. The notification still shows until I mark it as seen in the notifications tab. Which is a bit annoying as I receive a few a day and I have to manually clear them out or they would stay there forever.
Tapping on the home screen does absolutely nothing and at some point even the display times out and turns off.
Nothing is added to the log entries when I try to tap the notification.

The weird thing is that I was able to tap it once and it opened the notification on the comments context for the post in question.
Now the App is stuck on this post and the Notifications tab. I can’t “close” the notification and see other notifications.
Even going out of the notification tab and going back to it, still shows this context.

### Artifacts (2 logs, 1 video)
[Archive.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/6995892/Archive.zip)

**Comment by justtwago** [comment]
Closing the issue. It's irrelevant since the notifications have been migrated to the Jetpack app.
