### ISSUE TITLE
Themes > Try and Customize screen always says "Active" when it should say "Activate" 

### ISSUE THREAD

**Issue by startuptester** [wordpress-mobile/WordPress-iOS#17060]
### Expected behavior
When navigating themes, only the active theme should ever display Active in the top corner. The rest should say Activate.  

### Actual behavior
In the Try & Customize screen, all themes say Active. 

### Steps to reproduce the behavior
https://user-images.githubusercontent.com/66104034/130161236-846ba8ac-2ae4-458d-a9af-9295e66b8f46.MP4

**Comment by guarani** [comment]
👋 Hey @illusaen, I came across this issue while groundskeeping and wonder if it can be closed. It looks like your PR, https://github.com/wordpress-mobile/WordPress-iOS/pull/17107, fixed this but I want to double-check with you. 
If there's any follow-up tasks to this issue, e.g. https://github.com/wordpress-mobile/WordPress-iOS/pull/17107#issuecomment-914564215, maybe they'd be best suited to a separate issue.

**Comment by ScoutHarris** [comment]
Hey @illusaen . Just a re-ping to see if this can be closed or what else needs to be done here.

**Comment by illusaen** [comment]
Ahh yeah it should be fixed now and can be closed!
