### ISSUE TITLE
Login: improve wording for the error "The operation couldn't be completed"

### ISSUE THREAD

**Issue by iamgabrielma** [wordpress-mobile/WordPress-iOS#17119]
Similar to https://github.com/wordpress-mobile/WordPress-iOS/issues/12746

Then there's an XML-RPC connection error, the message is not user-friendly:

<img width="200" alt="Screenshot 2021-09-06 at 12 08 23" src="https://user-images.githubusercontent.com/3812076/132200915-8da7da41-0c6c-49fd-9126-85753d01b3f7.png">

Is there any specific project/label I can add this to? @mindgraffiti

**Comment by mindgraffiti** [comment]
@iamgabrielma added the `Login` label. As far as I know, there are no active projects to further improve Login.
