### ISSUE TITLE
Some X-Posts fail to load the content when opened from Notifications tab

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-iOS#17127]
### Expected behavior

When I see a notification about an X-post in the Notifications tab, and click on it, it lands me on the raw `"X-Post from +site: <title>"` post. If I then click on the `<title>` link on that post, I'm expected to see the actual post content this links to. This works on some posts, but fails on others.

### Actual behavior

For some posts, tapping on the `<title>` link in the raw X-Post post lands to the "Error Loading Post – Open in Browser" page.

At first glance it seems that this only happens with posts having Unicode characters in their title, though @guarani have found some posts without Unicode chars that seem to have the same issue too.

🎬  A video demonstrating the issue is available in p1630920299046800/1630920273.046700-slack-C011BKNU1V5

### Steps to reproduce the behavior

 - Go on the Notifications tab
 - Tap on one notification about an X-Post
 - On the raw X-Post post, tap on the link to the actual post that was cross-linked to the site
 - Check if we can access the linked post's content or if we have an error.
 - Retry with multiple X-Post notifications–especially ones with Unicode or non-standard characters?

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 11 Pro, iOS 14.7.1, WPiOS 18.1.0.3

**Comment by Gio2018** [comment]
@AliSoftware I removed the `requires triage` tag as we only use it for crashes

**Comment by justtwago** [comment]
Hey @AliSoftware! I'm investigating it and wanted to double-check if you still encounter the issue since it's been 2.5 years since the bug was reported.

**Comment by AliSoftware** [comment]
@justtwago In retrospect I think the core of the issue was not really X-Posts per se, but accessing a post in the mobile app from a blog which I do not belong.

In those cases, on the web I can click the yellow banner to add myself to the p2, and once I do I can then open the post in the mobile app too.

And the reason I ended up relating this to X-Posts back when I wrote this issue originally is probably because that's the most common case that led me to try opening a post from a blog I wasn't a member—opening a notification from blog `A` that I belong to but that was just an X-Post to blog `B` that I didn't belong to.

**Comment by justtwago** [comment]
Totally makes sense! Thanks for the clarification, Olivier!

**Comment by AliSoftware** [comment]
Btw, if that's indeed the core of the issue, personal opinion that I think just updating the generic error message screen from "Error Loading Post" to a slightly more describing error for that particular case would be enough imho (e.g. "Cannot show this post because you don't have access to this blog" or something like that?) 🙂 .
Except of course if there's an underlying reason not to reveal this (e.g. we don't want to reveal that a private blog exists at this URL for some security reasons I'm not aware of or something?)

**Comment by justtwago** [comment]
Really great idea! 💯
I'll figure out if there is a specific error code for this case so we can display this kind of error message.

**Comment by justtwago** [comment]
I managed to reproduce the bug without touching the x-posts. It's enough to leave a P2 I already have some notifications from. Fun fact that this bug behaves differently for each type of notification (haven't tested "Follows" yet):
Likes - displays "Error loading likes. User cannot access this private blog" (which is the correct behavior).
Mentions - it's either "Oops. There was an error loading the comment" or "Error Loading Post" messages. The first error is a mention in a comment, and the second is a mention in a P2 post.
Comments - Endless loading of comments.

I'm going to unify all the errors to match them to the "Likes" approach.

**Comment by justtwago** [comment]
I closed the ticket since we are now displaying specific error messages for this kind of error.
