### ISSUE TITLE
Feature Request: Mark all notifications as read

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-iOS#17135]
Requested in 4280910-zd-woothemes from a Jetpack iOS app user:

> It would be nice to mark all notifications as read

I agree that it would be nice to have an option to mark all notifications as read, especially when we have old and outdated notifications.

**Comment by snehash90** [comment]
Could you please tell me how I can add Label and featured Label into my issue?

**Comment by ScoutHarris** [comment]
Hey @mattmiklic .

I was thinking about how we might do this, and I was looking at Woo to see how they do this for Reviews (what they call notifications). There are a couple of UI differences where I was hoping you could provide some guidance.

- Woo has a checkmark button that automatically marks all notifications as read. However, WP has a settings button in that nav bar location.
  - Where do you think we could display a `mark all as read` button?
  - What button icon do you think is appropriate here?

- Woo has a flat list, so the button does in fact mark _all_ notifications as read. However, WP has Notification filters. I would expect `mark all as read` to apply to the selected filter (where `All` would actually be _all_). What do you think?

Thank you!

| Woo | WP |
|--------|-------|
| <img width="472" alt="woo" src="https://user-images.githubusercontent.com/1816888/144517288-7ecb429a-4776-4b18-9ba2-f88c9f86be4e.png"> | <img width="469" alt="wp" src="https://user-images.githubusercontent.com/1816888/144517286-d40f065a-ea5b-451d-8872-babfba85d247.png"> |

**Comment by mattmiklic** [comment]
I like the idea of re-using the solution from Woo; it's simple and the consistency between the two apps is helpful in some ways. I'd use the same checkmark (I assume it's from Gridicons). It could go to the left of the settings icon.

I agree about the behavior applying to the filter you've currently got selected, including All meaning _all_.

**Comment by ScoutHarris** [comment]
Thanks @mattmiklic . Did you have any thoughts on `Where do you think we could display a mark all as read button?`? With the settings button already there, I'm not sure where we'd put it. 🤔

**Comment by ScoutHarris** [comment]
For reference - 

This is where/how Woo updates multiple Notifications at once: https://github.com/woocommerce/woocommerce-ios/blob/4fe952211777fad134084cbc19d4db229a37c8c9/Networking/Networking/Remote/NotificationsRemote.swift#L52

This is where WP does it: https://github.com/wordpress-mobile/WordPressKit-iOS/blob/70a644bc038205e8860081f0e2c84ba2a4ef3f6c/WordPressKit/NotificationSyncServiceRemote.swift#L56

**Comment by ScoutHarris** [comment]
High level tasks:

- [x] Add feature flag.
- [x] Add button to nav bar.
- [x] Mark notifications read for the selected filter.
- [x] Add tracks for feature usage. (`notifications_mark_all_read_tapped`)
- [x] Accessibility support.
- [x] Enable feature flag and add release note (after branch is merged to `trunk`).

Feature branches: 
WPiOS - `feature/17135-notifications_mark_all_read`
WPKit - `feature/17135-notifications_mark_all_read_support`

**Comment by alpavanoglu** [comment]
Hi @mattmiklic 
I was assigned this task for my trial, and while looking into it I came up with a question:

I noticed that in the READER tab, there are 2 buttons in the navigation bar. But the right item (SEARCH) does not follow the Apple's Design Guidelines in its size (44x44 min).
If I follow the guidelines in this new feature, it will result in inconsistency between two tabs meaning when we switching between the two tabs (READER & NOTIFICATIONS) the position of those icons will not comprehend each other.

To resolve this, I think we can pick one of the three solutions:
1. Make READER tab follow the guideline too by letting both buttons have 44x44 size.
2. In the notifications tab follow the guideline but remove the spacing between two items so they are consistent between 2 tabs.
3. Do the same as READER screen and make the second button smaller (24 in width).

What do you think about these options? Your input would be greatly appreciated.

**Comment by mattmiklic** [comment]
Hi @alpavanoglu! It sounds like option 1, making both buttons 44x44, is the right solution. Could I see a screenshot of what this would look like, to ensure there's no visual regression by making this change?

**Comment by alpavanoglu** [comment]
@mattmiklic 

Here are the screenshots from the updated version for both screens:
| Reader-After | Notifications |
| ------------- | ------------- |
| <img width="450" alt="Screenshot 2022-01-06 at 00 48 25" src="https://user-images.githubusercontent.com/15968946/148305877-d212a1e7-8300-4ff1-9a50-36be4d802da1.png">  | <img width="451" alt="Screenshot 2022-01-06 at 00 48 39" src="https://user-images.githubusercontent.com/15968946/148305886-b62d0de5-2420-48f6-9726-cdd99b8022ce.png">  |

And the existing version with some help to visualize how the search button was cut:
| Reader-Before | Before-View-Hierarchy |
| ------------- | ------------- |
| <img width="449" alt="Screenshot 2022-01-06 at 00 40 06" src="https://user-images.githubusercontent.com/15968946/148305350-43b4b5b1-bb4b-473d-9b40-fc700321781c.png">  | <img width="457" alt="Screenshot 2022-01-06 at 00 15 01" src="https://user-images.githubusercontent.com/15968946/148305800-0328426c-58ad-49db-819b-43d0fc6ade6f.png">  |

One thing to note settings icon changes position.

I hope this helps.

**Comment by mattmiklic** [comment]
Thanks @alpavanoglu -- that looks just fine to me! 👍

**Comment by alpavanoglu** [comment]
Hi there, I have two follow up questions here:

1. Would it make sense to disable the Checkmark button and change its tint color to a disabled color like gray when there are no unread notifications under a certain filter?

Hiding it wouldn't look great I think as it will pop in and out. Or the practice would be to leave it as is?

2. The MySite tab also has the same issue. I looked in to Apple's iOS Apps and it seems to me that the usual pattern is to not trailing-align the battery icon and the navigation buttons in that way. So the MySite icon is closer to trailing than other tabs' icons. I just wanted to highlight it in case it is a problem. If not nothing needs to be done. If so, I can also align it with the other tabs.

| Updated Reader  | Apple Messages |
| ------------- | ------------- |
| <img width="355" alt="Screenshot 2022-01-12 at 15 52 45" src="https://user-images.githubusercontent.com/15968946/149164158-5c6ee5d1-ccdb-452e-ba0f-7f1d095055ac.png">  | ![IMG_0FA3BBB0AD12-1](https://user-images.githubusercontent.com/15968946/149164683-5e7e30ce-d183-4951-8be3-c41880b23713.jpeg)  |

| View Hierachy  | My Site |
| ------------- | ------------- |
| <img width="397" alt="Screenshot 2022-01-12 at 15 50 18" src="https://user-images.githubusercontent.com/15968946/149165302-f7dfdebf-3e12-45ae-a29e-fa99d604a465.png">  | <img width="356" alt="Screenshot 2022-01-12 at 15 59 01" src="https://user-images.githubusercontent.com/15968946/149164882-069e2f95-9055-45e7-8f88-d19c2c7a4ddb.png"> |

Any input is very much appreciated here. Thanks in advance.

**Comment by ScoutHarris** [comment]
Hi, @alpavanoglu .

1. Yes, I think we can disable and grey it. We could probably use the same color as other nav bar buttons. This one for example:

![File](https://user-images.githubusercontent.com/1816888/149211244-beaff46f-0308-44c2-a193-40c7ab95caf1.jpg)



2. Sure, you can align it with the other buttons if you like, if it's a minor fix that won't detour you too much.

**Comment by mattmiklic** [comment]
Agreed on both counts; thanks @ScoutHarris!

**Comment by ScoutHarris** [comment]
Just to note here, @alpavanoglu will not address the nav bar spacing/sizing issues with this feature. A separate GH issue will be created so it can be addressed later.
