### ISSUE TITLE
Jetpack Scan displays "Something went wrong" when VaultPress is being used

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-iOS#17146]
A similar report on Android here: https://github.com/wordpress-mobile/WordPress-Android/issues/14168

It was reported in 4293286-zd-woothemes that the user wasn't able to access the Scan feature in the Jetpack iOS app. The app displays a "Something went wrong" error when the site has VaultPress enabled which isn't helpful.

### Expected behavior

I would expect the app would point me to the VaultPress dashboard (https://dashboard.vaultpress.com/), similar to the notice on Calypso:

![Screenshot](https://user-images.githubusercontent.com/1136160/109562340-01a61000-7abd-11eb-9517-a9b88b2de453.png)

### Actual behavior

The app displays a "Something went wrong" error:

![IMG_DFC111ACAD24-1](https://user-images.githubusercontent.com/40906847/133025233-2a557d15-3a45-4765-bf0b-361acd279e5a.jpeg)

The following log entries were not helpful as well:

```
2021-09-12 22:52:54:607 🔵 Tracked: jetpack_scan_accessed <>
2021-09-12 22:53:00:982 🔵 Tracked: jetpack_scan_run_tapped <>
2021-09-12 22:53:01:222 Error starting scan: Scan response returned false
2021-09-12 22:53:01:224 🔵 Tracked: jetpack_scan_error <action: scan, cause: scan response returned false>
```

##### Tested on iPhone SE, iOS 14.7.1, JPiOS 18.2.0.1

**Comment by reginabally** [comment]
Another case in 4377899-zd-woothemes (WPiOS 18.3).

**Comment by leandroalonso** [comment]
I did an investigation on that and the fix should be quite straightforward. The response for a VP-powered site is like this:

```json
{
    "state": "unavailable",
    "threats": null,
    "has_cloud": true,
    "reason": "vp_active_on_site"
}
```

We can just rely on `reason` and show the message shared on the print above with a button that links to `https://dashboard.vaultpress.com/`
