### ISSUE TITLE
Bug: Feature image should auto generate from post's images.

### ISSUE THREAD

**Issue by snehash90** [wordpress-mobile/WordPress-iOS#17165]
### Stats: App not allowing to generate featured image automatically from Posts while publishing it.

I would like to manage my wordpress org website through WORDPRESS app.I have created my blog site with using auto feature image generator plugin.. which will allow post to generate featured image automatically from Posts while publishing it.

Also, I am using a plugin called “FS Poster” to auto post into my social media platform Fb etc.

Everything is working well when I publish posts from web browser but when I am trying to do the same thing from WordPress App.. it’s not working at all.

Please suggest anyone how I can operate my website from WordPress App. Because, I don’t have my desktop always and I really want to manage my Blog site through App

This topic was modified 5 days, 22 hours ago by Jan Dembowski. Reason: Moved to Fixing WordPress, this is not an Everything else WordPress topic
The page I need help with: [http://tenaybenes.com/]

##### Bug

**Comment by snehash90** [comment]
# [Bug]

**Comment by startuptester** [comment]
Thanks for reaching out! You are using third-party plugins the app does not support. The apps will only set the featured image of a post based on the post settings. What you can do is:
Edit the post content using the app
When you're ready to post, go to My Site > WP Admin in the app, look for the post, configure the appropriate settings related to the plugins they're using and publish from there.

For any future assistance, please contact us from the app's Help & Support section so we can help you out from there. Thank you!
