### ISSUE TITLE
auto feature image generator plugin not working

### ISSUE THREAD

**Issue by snehash90** [wordpress-mobile/WordPress-iOS#17162]
### Stats: App not allowing to generate featured image automatically from Posts while publishing it.

I would like to manage my wordpress org website through WORDPRESS app.I have created my blog site with using auto feature image generator plugin.. which will allow post to generate feature image automatically from Posts while publishing it.

Also, I am using a plugin called “FS Poster” to auto post into my social media platform Fb etc.

Everything is working well when I publish posts from web browser but when I am trying to do the same thing from WordPress App.. it’s not working at all.

Please suggest anyone how I can operate my website from WordPress App. Because, I don’t have my desktop always and I really want to manage my Blog site through App

This topic was modified 5 days, 22 hours ago by Jan Dembowski. Reason: Moved to Fixing WordPress, this is not an Everything else WordPress topic
The page I need help with: http://tenaybenes.com/

##### Tested on 8+ iPhone iOS 14.7.1

[Type] Improvements

**Comment by snehash90** [comment]
> Fails
> 🚫	
> Please add a type label to this issue. e.g. '[Type] Enhancement'
> 
> 🚫	Please add a feature label to this issue. e.g. 'Stats'
> Generated by 🚫 [dangerJS](https://danger.systems/js)

where I can do this??

**Comment by snehash90** [comment]
#17163

**Comment by startuptester** [comment]
This bug was reported several times by the same user. Closing all the duplicates.
