### ISSUE TITLE
iOS 15: Login Prologue via iCloud Keychain + 2FA disabled doesn't work

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17171]
https://user-images.githubusercontent.com/6711616/133634449-f2e6b56f-659a-47ce-a67c-8b01c72f2edc.mov

### Expected behavior
Selecting an iCloud Keychain credential with 2FA disabled on the Login Prologue screen should successfully log the user into the app

### Actual behavior
Selecting an iCloud Keychain credential with 2FA disabled on the Login Prologue screen takes the user to Get Started screen and a `Please enter a password.` error message is displayed

### Steps to reproduce the behavior

1. Build and run WPiOS on Xcode 13 / iOS 15 on a real device, not a simulator (At the time of writing the `Continue with Passcode` button is unresponsive on the simulator)
2. On the Login Prologue screen, select an iCloud Keychain credentials with 2FA disabled
3. 👀 Notice that there's a `Please enter a password.` error message displayed on the Get Started screen

### Investigation Notes

Please note that this issue doesn't seem to happen with 100% reproducibility. I was able to reliably reproduce this issue for about 2 days, then suddenly it stopped happening. 🙃 

This issue happens when running iOS 15 RC via Xcode 13 RC, as well as on the WPiOS 18.2 Testflight build on iOS 15 RC.

The root cause of this issue seems to be that the `ASAuthorizationCredential` we fetch from iCloud Keychain has a blank password. I suspect that this is an iOS 15 bug. I haven't found any radar submissions for this yet.

<details>
  <summary>Click to expand</summary>
  
#### Debug output
  
Breakpoint on ~`authorizationController(controller:didCompleteWithError:)`~ `authorizationController(controller:didCompleteWithAuthorization)` method.

#### Xcode 12 / iOS 14.5

```
(lldb) p authorization
(ASAuthorization) $R0 = 0x00000001124064e0 {
  ...
  _credential = some {
    some = 0x0000000112417980 {
      baseNSObject@0 = {
        isa = ASPasswordCredential
      }
      _user = 0x0000000112531380 "<user>@automattic.com"
      _password = 0x00000001dce7a628 "<password>"
    }
  }
}
```

#### Xcode 13 RC / iOS 15 RC

```
(lldb) p authorization
(ASAuthorization) $R0 = 0x00000001124064e0 {
  ...
  _credential = some {
    some = 0x0000000112417980 {
      baseNSObject@0 = {
        isa = ASPasswordCredential
      }
      _user = 0x0000000112531380 "<user>@automattic.com"
      _password = 0x00000001dce7a628 ""  // Notice that password is an empty string!!!
    }
  }
}
```

</details>

**Comment by twstokes** [comment]
I've tried but failed to reproduce this on iOS 15.1 / WPiOS 18.6.0.0. I was able to successfully log in with every attempt.

I did want to confirm this bit @momo-ozawa:
>Breakpoint on `authorizationController(controller:didCompleteWithError:)` method.

I wonder if this was supposed to say `authorizationController(controller:didCompleteWithAuthorization)`? Otherwise, can I ask how you inspected the `authorization` object?

Thanks!

**Comment by momo-ozawa** [comment]
Hi @twstokes!

I think that it may be safe to close this issue. @dvdchr looked into this a couple weeks ago and wasn't able to reproduce it. This bug may have been caused by some server-side issues in iCloud that have since been resolved

More details here: pbArwn-2T0-p2#comment-4134

(Also, I think you're right about `authorizationController(controller:didCompleteWithAuthorization)` 🙈 )

**Comment by twstokes** [comment]
Thank you @momo-ozawa for the info! Between the three of us testing it and not seeing any recent related issues in Zendesk, I also think we may be safe to close. I'll close it now. 🙇
