### ISSUE TITLE
Comments: Loading image is not shown correctly in iPad layout

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#17201]
### Expected behavior
The loading image / view is shown correctly, centered in the detail view controller.

### Actual behavior
The loading image is displayed incorrectly. Looks like a bug on the view's constraints causing the loading view to ignore the sidebar.

![ipad_comments_loading-state](https://user-images.githubusercontent.com/1299411/134126873-418e524f-9dfb-4c34-a02b-1ea019b70c0f.png)

### Steps to reproduce the behavior

- Run the app on an iPad simulator.
- Log in and select any site.
- Tap My Site > Comments.
- The loading image should be shown as described above.

**Comment by ScoutHarris** [comment]
> Tap My Site > Comments.
> The loading image should be shown as described above.

To clarify this, the view is only shown if there are no Comments cached for the site. (i.e. you won't see it every time).

And just to note, it also happens on iPhone:

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-09-21 at 11 26 22](https://user-images.githubusercontent.com/1816888/134218767-92dc34bc-4cde-4b2e-affe-4d4b8799b9b7.png)
