### ISSUE TITLE
Replace `otherElements.firstMatch` matchers with screen-specific ones

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#17231]
Screen objects such as `ActivityLogScreen`, use a query to identify whether they are loaded that is too loose.

https://github.com/wordpress-mobile/WordPress-iOS/blob/3fc8ad56626cdbed9c702e3aee7eb6730661541b/WordPress/UITestsFoundation/Screens/ActivityLogScreen.swift#L6

`otherElements.firstMatch` will find _something_ most, if not all of the times.

Even though the screens that do this are leaf screens in the navigation hierarchy and the tests don't interact with them, we should still use appropriate queries. Doing so would at least help us notice if a navigation that the tests expect to result in that screen ends up somewhere else.

---

If you are reading this and what to have a crack at it, ping me for a review 😄

**Comment by kean** [comment]
I've updated these nearly everywhere, so I think it's safe to say it can be closed.
