### ISSUE TITLE
Empty Stats: Investigate publicize with Jetpack sites

### ISSUE THREAD

**Issue by nikola-milicevic** [wordpress-mobile/WordPress-iOS#17309]
When tapping "Sharing" (both from the Empty Stats nudge and My Site) the Publicize screen is shown for .com sites and for Jetpack sites the "Manage sharing buttons" are displayed.

**Comment by leandroalonso** [comment]
Based on my initial analysis it seems that we check for `blog.supportsPublicize()`. If `true` we show the Publicize, if not the manage buttons sharing screen.

I tested the same flow on the web and when the Publicize module is not enabled this message is shown:

<img width="400" alt="Screen Shot 2021-10-13 at 12 21 57" src="https://user-images.githubusercontent.com/7040243/137163789-3af4082a-db40-4ffb-ba1a-23c244049bed.png">

We can fix it in a similar way to what we did for when the Stats module is not enabled (#16822):

* Always show the `SharingViewController`
* Check for `blog.supportsPublicize()` inside this VC
* If `true`, show the screen as it is
* If `false`, show a message with the option to enable the module

`SharingViewController` is quite old so it might be a good opportunity to convert it into Swift but that will depend on the complexity, so I'll keep this issue updated.
