### ISSUE TITLE
Login: tapping done on the Login Epilogue screen doesn't deallocate previously presented view controllers

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17430]
### Expected behavior

After tapping done on the Login Epilogue screen, the following view controllers aren't deallocated:
- `WordPressAuthenticator.LoginNavigationController`
- `WordPressAuthenticator.LoginPrologueViewController`
- `WordPress.LoginEpilogueViewController`

### Actual behavior

After tapping done on the Login Epilogue screen, previously presented view controllers should be deallocated.

### Notes 
It seems like switching the root vc isn't deallocating previously presented vcs

https://github.com/wordpress-mobile/WordPress-iOS/blob/0af6d6ae5b503d83521ab10547d6b6d05eb5c42f/WordPress/Classes/System/WindowManager.swift#L80-L88

### Steps to reproduce the behavior

1. Add `deinit` and add a breakpoint to the following VCs
  - `WordPressAuthenticator.LoginNavigationController`
  - `WordPressAuthenticator.LoginPrologueViewController`
  - `WordPress.LoginEpilogueViewController`
2. Log out then log in
3. Press Done on the Login Epilogue
4. 👀 Notice the VCs mentioned in step 1 aren't deallocated (doesn't trigger breakpoint)

Or follow steps 2, 3, then check the Debug Memory Graph -- the presented VCs in step 1 will still be there

**Comment by kean** [comment]
The login epilogue screen was removed, closing.
