### ISSUE TITLE
Editor media uploads: Photo not added when "Add Photos Only" access is enabled and camera is used

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#17467]
### Expected behavior
Photo from camera is inserted into the post.

### Actual behavior
Photo from camera is not inserted into the post.

### Steps to reproduce the behavior
1. Clean install WordPress (delete first, then install)
2. Confirm that Settings -> WordPress -> "Allow WordPress to Access" -> Doesn't contain anything about photos
3. In a new Post, tap the + and choose the Image block
4. Select "Take a Photo"
5. When prompted with "'WordPress' Would Like to Access Your Photos", tap "Don't Allow"
6. When prompted with "'WordPress' Would Like to Access the Camera", tap "OK"
7. Take a picture and choose "Use Photo"
8. Tap "OK" on the "'WordPress' Would Like to Add to your Photos" prompt
9. Observe no image is added to the post
10. Confirm that Settings -> WordPress -> "Allow WordPress to Access" -> Photos -> "Add Photos Only"
11. Confirm that the photo taken exists in the Photos app

**Comment by twstokes** [comment]
Related: #17468

**Comment by sla8c** [comment]
Update / note:  I looked at this during hack week last week and have a PR coming sometime this week thx

**Comment by twstokes** [comment]
It looks like this is resolved with #18139. I'm going to close this out. Thanks @sla8c!
