### ISSUE TITLE
Editor media uploads: Provide feedback when photo access is disabled and camera is used

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#17468]
### Expected behavior
A message is shown to the user that access to photos is disabled.

### Actual behavior
No message or feedback is shown to remind the user that access to photos is disabled.

### Steps to reproduce the behavior
1. Clean install WordPress (delete first, then install)
2. Confirm that Settings -> WordPress -> "Allow WordPress to Access" -> Doesn't contain anything about photos
3. In a new Post, tap the + and choose the Image block
4. Select "Take a Photo"
5. When prompted with "'WordPress' Would Like to Access Your Photos", tap "Don't Allow"
6. When prompted with "'WordPress' Would Like to Access the Camera", tap "OK"
7. Take a picture and choose "Use Photo"
8. Tap "Don't Allow" on the "'WordPress' Would Like to Add to your Photos" prompt
9. Observe that no message or feedback is shown to the user that the app doesn't have access to photos
10. Confirm that Settings -> WordPress -> "Allow WordPress to Access" -> Photos -> "None"
11. In the same Post, tap the + and choose the Image block
12. Select "Take a Photo" (no access prompts should appear)
13. Take a picture and choose "Use Photo" (no access prompts should appear)
14. Observe that no message or feedback is shown to the user that the app doesn't have access to photos

**Comment by twstokes** [comment]
When "Allow WordPress to Access" -> Photos is set to "None" and I try to "Choose from Device", I see the following:
<img src="https://user-images.githubusercontent.com/2092798/141519685-f5915718-60bf-4db7-b9c4-a4c4ae51e236.png" width="250px" alt="Screenshot of message informing the user that the app can't access the Media Library" />
.

**Comment by bluefuton** [comment]
I ran into this one last night and it was pretty puzzling to figure out. The photos pane just pops up completely empty with no feedback about why that might be.

This is how Facebook Messenger handles the same situation, which would be a good pattern to follow:

<img width="847" alt="Screen Shot 2022-05-18 at 11 39 18" src="https://user-images.githubusercontent.com/17325/168929352-830923d7-629c-499f-985a-7629b66810be.png">

**Comment by kean** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/21398. The access is not longer needed.
