### ISSUE TITLE
Media: Error shown when adding media with limited access to photos

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#17470]
### Expected behavior
A useful message is shown to the user that access to photos are limited or disabled.

### Actual behavior
A message at the bottom shows:

<img src="https://user-images.githubusercontent.com/2092798/141522511-55a5c945-3ea6-4c1a-b911-682bdf8d9054.PNG" width="300px" alt="Screenshot of error" />

**Unable to Sync**
The operation couldn't be completed. (WPMediaPickerErrorDomain error 0.)

### Steps to reproduce the behavior
1. In iOS Settings -> WordPress -> "Allow WordPress to Access" -> Photos -> Select "None" or "Add Photos Only" (**see note below**)
2. My Site -> Media
3. Tap the + at the top right
4. Select "Choose from My Device"
5. Observe error (see screenshot)

#### Note: Photo access levels
Photo access levels in Settings -> WordPress -> "Allow WordPress to Access" -> Photos don't appear until the app interacts with photos in some way. Even then, not all levels may appear. 

**To populate the main options (None, All Photos, Selected Photos):**
- Add a photo from your device to the media library and follow the prompts to allow, limit, or deny access.

**To populate the "Add Photos Only" option:**
- First set the "Allow WordPress to Access" setting to "None", then add a photo from the camera. You should be prompted with "'WordPress' Would Like to Add to your Photos". Tapping OK will add it.

**Comment by twstokes** [comment]
Possibly the pattern used when adding media in the editor could be reused here:

<img src="https://user-images.githubusercontent.com/2092798/141523881-3a6551b0-7c06-4eff-9d8d-84a5210eeef4.png" width="300px" alt="Message showing that the app needs permission" />

**Comment by sla8c** [comment]
Fixed by #17734
