### ISSUE TITLE
Quick Start Steps > Rotating the iPhone makes pulsating blue dots inaccessible.

### ISSUE THREAD

**Issue by pachlava** [wordpress-mobile/WordPress-iOS#17509]
### Expected behavior
If we aim for showing the hints to the user (by the means of blue pulsating dots, in this case), we should be sure they can be seen in all cases.

### Actual behavior
If the `Customize your site` or `Grow your audience` is open on iPhone, rotating the device to landscape and back will cause `Stats` screen to be shown in the background (because it’s the first screen in the list). The issues start once the user taps any of the Quick Start steps : they will not see anything helpful, because Stats are open:

https://user-images.githubusercontent.com/73365754/142637361-dbfba81b-77e4-4adc-8628-30c112e6436b.MP4

### Steps to reproduce the behavior
1. Use iPhone in portrait orientation
2. Make sure you have `Customize your site` or `Grow your audience` opened
3. Set the device to landscape mode and then back to portrait
4. Tap any of the items from the list ~> the hint will not be shown, because `Stats` page is open.

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
