### ISSUE TITLE
Quick Start Steps > Extra space between a cell and a `Skip` button.

### ISSUE THREAD

**Issue by pachlava** [wordpress-mobile/WordPress-iOS#17507]
### Expected behavior
The `Skip` button should be placed right next to the action cell.

### Actual behavior
There's a gap between the `Skip` button and a cell in Landscape mode for iPhone:

![IMG_4411](https://user-images.githubusercontent.com/73365754/142634764-39d3422d-d89d-4d83-84af-c31ed25f7b48.PNG)

Note: the issue for while edges around completed cells is tracked separately in #16164

### Steps to reproduce the behaviour
1. Use iPhone
2. Make sure you have uncompleted steps in `Customize your site` or `Grow your audience`
3. Set the device to landscape mode
4. Swipe on any of not yet done cells ~> there's a gap between a cell and the `Skip` button.

It's not so evident in Light mode, but it's reproducible too.

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
