### ISSUE TITLE
Quick Start Steps > Not yet completed items get crossed under certain conditions.

### ISSUE THREAD

**Issue by pachlava** [wordpress-mobile/WordPress-iOS#17508]
### Expected behavior
No completed items never get crossed out.

### Actual behavior
The item(s) remaining in 'not done' category get crossed out if another item was skipped, and the complete items are expanded:

https://user-images.githubusercontent.com/73365754/142636278-0a8dc934-6dab-4c3f-9d00-e853abb2e836.MOV

### Steps to reproduce the behavior
1. Make sure you have at least two uncompleted steps in `Customize your site` or `Grow your audience`, and have some completed, too.
2. Expand the completed list
3. `Skip` one of the uncompleted ~> the remaining items might get crossed out

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
