### ISSUE TITLE
add missing strings to german localization and fix misleading ones

### ISSUE THREAD

**Issue by barooney** [wordpress-mobile/WordPress-iOS#1751]
I found some strings in the app, which were misleading or just not translated to german.

**Comment by rachelmcr** [comment]
@barooney — Are there still strings in the app that are incorrect or not translated? If you let us know which strings those are, we can take a look.

**Comment by barooney** [comment]
I'll check that! I made a pull request almost a year ago, but obviously it's gone...

Just let me have a closer look!

**Comment by rachelmcr** [comment]
You can find all of the German translations (and untranslated strings) in the GlotPress project here:

https://translate.wordpress.org/projects/apps/ios/dev/de/default

If you find the misleading or untranslated strings there, please submit the correct translation.

I'm going to go ahead and close this issue, as most translation issues can be resolved by submitting the correct translation in GlotPress. If you find any untranslated strings that are missing from the GlotPress project, please open a new issue about those strings. Thanks!
