### ISSUE TITLE
Posts List: Add Copy link functionality for posts

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#17528]
### Description
The user should be able to easily copy a post link as it happens on the web.
The functionality was introduced [on Android with this PR](https://github.com/wordpress-mobile/WordPress-Android/pull/15570):

1. In post cards mode press the More button / In post list mode press the dots at the right of the post
2. A **Copy link button should be added above the Trash button**
3. When the user presses the *Copy link button* a **snackbar message appears saying "Link copied to clipboard"**
4. The link is available in the clipboard for pasting

**Comment by mertGokduman** [comment]
Hi @antonis , can you assign this issue to me? :)

**Comment by antonis** [comment]
Done! Thank you for volunteering to help on this @mertGokduman 🙇

**Comment by mertGokduman** [comment]
Thank you :)
