### ISSUE TITLE
Crash when taping on a like notification in Notifications tab

### ISSUE THREAD

**Issue by AliSoftware** [wordpress-mobile/WordPress-iOS#17529]
### Expected behavior

 - When tapping on a like notification in the Notifications tab, I expect to see the list of people who liked my post

### Actual behavior

 - After briefly showing the previous list of likers that the app had in cache, the app crashes without showing the updated list containing the latest likers

### Steps to reproduce the behavior

 - Go on the Notifications Tab
 - Tap on a "like" notifications that you already opened previously (†)
 - See the next screen, with the list of likers from the last time you opened that like notification, show up briefly, without the latest likers yet
 - After about 1 second on that screen (while it's apparently trying to update that list of latest likers), the app crashes

(†) This will only crash on specific "like" notifications. Given the log below, it likely only happens if a user who has their preferred blog having `user: nil` field (for some reason) is part of the list of likers.

### Logs

I found this in the logs which is **very likely** to be the culprit of the crash:

```
2021-11-23 10:54:01:834 🔵 Tracked: notifications_notification_details_opened <notification_type: like>
2021-11-23 10:54:03:933 Unresolved Core Data save error: Error Domain=NSCocoaErrorDomain Code=1570 "user est une valeur obligatoire." UserInfo={NSValidationErrorObject=<LikeUserPreferredBlog: 0x283a094a0> (entity: LikeUserPreferredBlog; id: 0xa74f17ddc8ce9958 <x-coredata://B2589825-657F-4C25-A3B2-DB4E71C15E45/LikeUserPreferredBlog/p2155>; data: {
    blogID = **redacted**;
    blogName = "**redacted**";
    blogUrl = "**redacted**";
    iconUrl = "";
    user = nil;
}), NSLocalizedDescription=user est une valeur obligatoire., NSValidationErrorKey=user, NSValidationErrorValue=null}
2021-11-23 10:54:03:933 Generating exception with reason:
Non-optional property with a nil value on LikeUserPreferredBlog.user
```

_Note: I've redacted the user info manually; for un-redacted data and video, see p1637670932064900-slack-C012H19SZQ8. Also note that the error's LocalizedDescription is in French simply because my phone is in French._

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 11 Pro, iOS 15.1, WPiOS 18.7.0.0

**Comment by diegoreymendez** [comment]
@startuptester - I'm tackling this as part of Groundskeeping since I triaged this issue as high priority.
