### ISSUE TITLE
Pages List: Add Copy link functionality for pages

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#17534]
### Description
The user should be able to easily copy a page link (for posts the functionality is covered in https://github.com/wordpress-mobile/WordPress-iOS/issues/17528):

1. Press the dots at the right of a page in the list
2. A **Copy link button should be added above the Trash button**
3. When the user presses the *Copy link button* a **snackbar message appears saying "Link copied to clipboard"**
4. The link is available in the clipboard for pasting

**Comment by mertGokduman** [comment]
Hi @antonis, can i work on this issues and issue #17528 ?

**Comment by antonis** [comment]
Hey @mertGokduman 👋 
Thank you for volunteering to work on this 🙇 

> can i work on this issues and issue #17528 ?

Yes, of course! Please ping me if you need any help.

**Comment by InnovaMert** [comment]
Hİ @antonis 
Thank you for answering. Also, can you assign issue #17528 to me?

**Comment by antonis** [comment]
> Hİ @antonis Thank you for answering. Also, can you assign issue #17528 to me?

@mertGokduman Please ping me on issue #17528 to be able to make the assignment 🙇

**Comment by mertGokduman** [comment]
Hi @antonis . Is there any toast message function in project? I couldnt see. If there is not, I will add an extension for toast message to UIViewController.

**Comment by antonis** [comment]
Hey @mertGokduman 👋 
I'm not sure if you already answered the question. For presenting a toast you can use `NoticeAction` ([example](https://github.com/wordpress-mobile/WordPress-iOS/blob/a08cc72e4bfb15d4fa88c06c549c16941fb2a64a/WordPress/Classes/ViewRelated/Pages/PageListViewController.swift#L930)).

**Comment by mertGokduman** [comment]
Hi @antonis 
I added extension for toast message to UIViewController :)

**Comment by mertGokduman** [comment]
Hi @antonis 
İn PageListViewController, how can i get pageUrl?

**Comment by antonis** [comment]
Hello @mertGokduman 👋 

> İn PageListViewController, how can i get pageUrl?

You should be able to use the [`permaLink` of the BasePost model](https://github.com/wordpress-mobile/WordPress-iOS/blob/06de9c0b5118e66fe26ed52176f5dc323c363778/WordPress/Classes/Models/BasePost.h#L19) that the [Page model](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/Classes/Models/Page.swift) inherits from. You can also check the [`View` action that is currently available and also uses the page url](https://github.com/wordpress-mobile/WordPress-iOS/blob/a08cc72e4bfb15d4fa88c06c549c16941fb2a64a/WordPress/Classes/ViewRelated/Pages/PageListViewController.swift#L663).
Thank you for taking the time to work on this issue 🙏 
Don't hesitate to ping us if we can help further.

**Comment by mertGokduman** [comment]
Hey @antonis, I used to permaLink for url, my mistake :) . I also have a question. Will copy link function available for trashed posts and pages? or it will be availabe for published, draft and scheduled ones? And I used Wordpress medium blue for toast message background color. Is it okey or do you want any specific color for its background?

**Comment by antonis** [comment]
> Will copy link function available for trashed posts and pages? or it will be availabe for published, draft and scheduled ones?

Let's keep it to published, draft and scheduled posts pages 👍 

> And I used Wordpress medium blue for toast message background color. Is it okey or do you want any specific color for its background?

I can request some feedback from a designer during the PR review on this. Another approach would be to [use the existing notice utility like it is used in other actions](https://github.com/wordpress-mobile/WordPress-iOS/blob/06de9c0b5118e66fe26ed52176f5dc323c363778/WordPress/Classes/ViewRelated/Pages/PageListViewController.swift#L829) for consistency.

<details>
<summary>Notice UI</summary>

![IMG_85A6B17AAC40-1](https://user-images.githubusercontent.com/304044/153012107-5473441f-518c-4605-9df4-d6edac81920c.jpeg)
</details>

**Comment by mertGokduman** [comment]
Ok, I will use this notice utility, and Copy Link function will be available for published, draft and scheduled posts and pages.

**Comment by mertGokduman** [comment]
Hi @antonis,
I created PR for #17528 and this issue. Can you review?

**Comment by antonis** [comment]
> Hi @antonis, I created PR for #17528 and this issue. Can you review?

Thank you for your work on this @mertGokduman 🙇 
We'll get to this ASAP in the next few days 🙏

**Comment by mertGokduman** [comment]
I also thank you for your help and comments 🙏

**Comment by twstokes** [comment]
Closed by https://github.com/wordpress-mobile/WordPress-iOS/pull/17911. 🎉
