### ISSUE TITLE
Stats widget not working until user visits Stats screen in app

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#17567]
### Expected behavior

If a user adds a WordPress widget to their device's home screen, the widget should work out of the box or display an actionable message to help the user get it functioning.

### Actual behavior

After adding the widget, it shows "Unable to load site stats". This happens only if the user hasn't visited the app's Stats screen after logging in.

### Steps to reproduce the behavior

1. Perform a fresh install of WPiOS
2. Log in to the app
3. Background the app and add the Today widget
4. Notice the "Unable to load site stats" message appears, with no instruction on how to remedy this
5. Notice that tapping on the widget opens the app, but does not deep link to the Stats screen (see https://github.com/wordpress-mobile/WordPress-iOS/issues/18452)

### Possible solution

My understanding is that there is an implicit requirement that the user visits the Stats page in the app for widgets to work. If widgets must depend on that user action taking place first, the widget could show the actionable message instead of "Unable to load site stats". For example, we could use "Visit the app's Stats page to enable the widget".

##### Tested on iPhone 11, iOS 15.0.2, WPiOS 18.6.1

First reported by @AliSoftware

**Comment by AliSoftware** [comment]
> For example, we could use "Visit the app's Stats page to enable the widget".

Bonus point if we could make this message tappable and deep-link to said Stats page 🙂

**Comment by twstokes** [comment]
> > For example, we could use "Visit the app's Stats page to enable the widget".
> 
> Bonus point if we could make this message tappable and deep-link to said Stats page 🙂

👋 This came up today so I added https://github.com/wordpress-mobile/WordPress-iOS/issues/18452.
