### ISSUE TITLE
WebView: Likes not registered

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-iOS#17571]
Similar to [this report](https://github.com/wordpress-mobile/WordPress-iOS/issues/16542), the user reported another issue in 4543689-zd-woothemes when pressing the Like buttons with WebView within the app. The action doesn't get registered even after the app tries to sign us in.

### Expected behavior

The user expects that their actions to Like a post are saved.

### Actual behavior

The "likes" weren't saved after refreshing the post on Webview.

### Steps to reproduce the behavior

1. Go to the apps' Reader
2. Open up a post on a site that has a mapped domain
3. Tap the web icon to launch the in-app browser
4. Tap the "Like" button on the post, notice that the "Like" button changed to blue color but your gravatar doesn't show up beside the button
5. Tap the refresh button on the in-app browser, notice the "Like" button changed back to the default color
6. Check the post on a web browser, the "Like" action isn't saved

### Screen recordings

**Tested with a post on WordPress.com News**
(e.g. https://wordpress.com/blog/2021/11/23/shining-a-spotlight-on-podcasts/)

https://user-images.githubusercontent.com/40906847/143513331-b36d7f98-82bf-40aa-bbe3-a3fabaeac7a2.MP4

**Tested with a post with a mapped domain**

https://user-images.githubusercontent.com/40906847/143513392-dbb99847-a94b-42e9-bf1a-cea63272280e.MP4

##### Tested on iPhone 11, iOS 15.1, WPiOS 18.6.1

**Comment by guarani** [comment]
Likes not working in the app's web views (on sites with mapped domains) has come up in https://github.com/wordpress-mobile/WordPress-iOS/issues/15390. 

The only difference I see between this issue and that existing issue, is that this issue mentions the web views in Reader. I think we could update https://github.com/wordpress-mobile/WordPress-iOS/issues/15390 to mention Reader and close this issue, wdyt @reginabally?

**Comment by reginabally** [comment]
@guarani Thanks for taking a look! Yes, it sounds good to update the existing bug report and close this one. I recall that I saw that report some time ago but failed to find it yesterday. 😅

**Comment by guarani** [comment]
> Yes, it sounds good to update the existing bug report and close this one.

I've added a note to https://github.com/wordpress-mobile/WordPress-iOS/issues/15390 to include the Reader and will close this now, thanks for the report!
