### ISSUE TITLE
Reader Comments: Loading view is misplaced in iPad, iOS 15.

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#17665]
### Expected behavior
The loading view is centered correctly.

### Actual behavior
The loading view is misaligned.

### Steps to reproduce the behavior

- Open the app using an iPad.
- Go to Notifications > select any comment notification.
- Tap on the notification header row to go to the comment threads.
- Observe that the NoResultsView is misplaced in both portrait and landscape orientation.

Portrait | Landscape
--|--
![17645_ipad_portrait_before](https://user-images.githubusercontent.com/1299411/145613446-6cd0fe37-f197-4a89-89b0-0f73c416f5ce.png) | ![17645_ipad_landscape_before](https://user-images.githubusercontent.com/1299411/145613437-45d9963e-3f26-4d11-b55d-8c448834510a.png)

### Findings

Somehow the `traitCollectionDidChange:` gets called every time a view controller is pushed – and turns out this only happens when we override the Appearance setting (My Site > Me > App Settings > Appearance) AND the overridden value is different with the system scheme. Since the `ReaderCommentsViewController` refreshes the NRV in `traitCollectionDidChange:`, this caused the view to be misplaced.

See also: https://github.com/wordpress-mobile/WordPress-iOS/pull/17656#issuecomment-991135489

**Comment by kean** [comment]
It was fixed in one of the previous versions.
