### ISSUE TITLE
Add post fab dissapearing on split screen on iPad

### ISSUE THREAD

**Issue by kyleaparker** [wordpress-mobile/WordPress-iOS#17661]
### Expected behavior
Fab to add new posts should always be visible on the Posts screen, it's the only way to add a new post. 

### Actual behavior
When pulling the WP app into a split screen view on iPad, the fab doesn't initially appear on the posts screen. Tapping back to My Site and then back to Posts brings it back. 

Video of the issue: 

https://user-images.githubusercontent.com/712873/145466159-dce65a34-9e7e-4d16-b1b7-560b020b3223.MP4

### Steps to reproduce the behavior
- Open the WP app on iPad
- Open another app
- Drag the WP app into view as a split-screen and resize the WP app to the smallest size.
- Sometimes the add post fab shows up, sometimes it doesn't

##### Tested on [device], iOS [version], WPiOS [version]

This issue was reported by a user and I was able to reproduce it. 

Test on iPad, iOS 15.1, WPiOS 18.8

**Comment by kean** [comment]
Fixed in 25.4.
