### ISSUE TITLE
Story post option missing from the floating button

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-iOS#17680]
Originally reported in 4541370-zd-woothemes.

### Expected behavior

I expect to be able to create a new story post from the floating button on the My Site screen.

### Actual behavior

The Story post option is missing from the floating button. I can see the same option on WPAndroid 18.8.

### Steps to reproduce the behavior

1. On My Site, switch to a WPCOM or Jetpack site.
2. Tap the floating + button.
3. Notice the add new Story post option is missing.

##### Tested on iPhone 11, iOS 15.1 WPiOS 18.8.0.5

**Comment by tiagomar** [comment]
👋  Hi, @reginabally! 
Do you mind confirming if this is still happening? 
I couldn’t reproduce it in the last 5 releases. Am I missing something?

**Comment by reginabally** [comment]
@tiagomar Thanks for following up! I can see the "Story post" option on both WPCOM and Jetpack sites in the app now. 🎉
