### ISSUE TITLE
Feature Request: Add spinning icon when post and page list is first displayed

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-iOS#17694]
Internal discussion: p4a5px-2Kk-p2#comment-12600

Please add a spinner or some other form of loading indicator when the post list is first displayed. This could inform users on a slower internet connection that an action is happening and wait until it completes before editing their posts.

We have an open case in the p2 linked above that the user might open the post in the app for editing without waiting for it to download the latest version they made on the web. This confused the user that there's a sync issue in the app.

**Comment by kean** [comment]
There is a loading indicator in the latest versions of the app (added in the scope of the Posts & Pages modernization). Closing.
