### ISSUE TITLE
Crash on comment sync

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#1771]
![screen shot 2014-05-27 at 17 01 38](https://cloud.githubusercontent.com/assets/8739/3093184/e8f0efd4-e5af-11e3-9c23-af81b3e6a467.png)

> CoreData could not fulfill a fault for '0xd0000000018c000a <x-coredata://B30049C2-9285-40EB-8882-074EF79F97B8/Post/p99>'

It looks like using `filteredSetUsingPredicate:` with faults will crash. 

I wasn't even doing anything related to comments, must have been a background sync.

**Comment by sendhil** [comment]
@koke it's back ;) except it's here now:
https://github.com/wordpress-mobile/WordPress-iOS/blob/86141dde01c6c0ee1429e0dce4b76270a7a8d55b/WordPress/Classes/Services/CommentService.m#L566-566

**Comment by sendhil** [comment]
re-opening

**Comment by koke** [comment]
I don't see any crashes for 4.9, but that doesn't necessarily mean it's fixed.

I'm not sure how to reproduce the scenario, but perhaps there's a safer way to find comments by ID
