### ISSUE TITLE
WPiOS crashed when clicking on the People tab

### ISSUE THREAD

**Issue by thabotswana** [wordpress-mobile/WordPress-iOS#17719]
A user reported that when they click on the People link under **CONFIGURE**, their app shuts down immediately. They reinstalled the app but that didn't help.

I found the [Sentry reports](https://sentry.io/organizations/a8c/discover/results/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=1438083&query=user.email%3Agregcrandall%40mac.com&sort=-timestamp&statsPeriod=7d&yAxis=count%28%29) with the following error:

```
NSInvalidArgumentException: no object at index 1 in section at index 0
```

##### User/device details
Ticket link: 4663505-zen
App version: 18.8.0.5
Device model: iPad Pro 12.9-inch 4th-gen (WiFi) (iPad8,11)
OS version: iOS 15.2
Type of site (Simple, Atomic, Jetpack, or self-hosted): Simple

**Comment by igotdes** [comment]
Also reported in #5280743-zen:

- App version: 19.9.1.0
- OS version: iOS 15.5
- Device: iPad13,8
- Type of site: Atomic

**Comment by twstokes** [comment]
👋 Just wanted to note that I can reproduce this issue on a physical iPad Pro and am working on a fix.

**Comment by mokagio** [comment]
#18907, which will ship as part of 20.1 in about a week, should close this.
