### ISSUE TITLE
Comment Threads: Add undo functionality for moderation actions

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#17752]
Refs `pbArwn-2ks-p2#comment-4465`

Comment thread moderation functionality is currently hidden behind the feature flag `commentThreadModerationMenu` since 18.9. When opening Reader comments using an account that has moderation capabilities, the Share button turns into an ellipsis icon that shows an overlay context menu when tapped:

<img width="408" alt="Screen Shot 2022-01-13 at 15 41 56" src="https://user-images.githubusercontent.com/1299411/149295754-40584cda-a826-40cc-970f-f819360e7672.png">

`pbArwn-2ks-p2#comment-4465` suggested that an undo functionality is added to allow the user to revert their action in case of misclicks. I'm thinking that the implementation should be similar to Follow Conversation where an actionable "Undo" button is shown after enabling push notifications.

**Comment by ScoutHarris** [comment]
Reopening due to issues with restoring comments #17834.
