### ISSUE TITLE
Follow Topics screen has unused space at the bottom

### ISSUE THREAD

**Issue by joshheald** [wordpress-mobile/WordPress-iOS#17774]
### Expected behavior
The tags should show in as much of the screen as possible, only having a scrollbar if there is not enough space to show them all.

### Actual behavior
There is a bar of unused space at the bottom of the screen (in dark mode this can be seen in a different grey) which is not used for tags.
On some devices, there are a few tags hidden behind this space, which you need to scroll to see

### Steps to reproduce the behavior
On a site with no followed topics,
1. Go to the Reader tab
2. Tap `⚙️`
3. Tap `Discover more topics`
4. Observe that there is empty space at the bottom of the screen, and the topics can be slightly scrolled.

##### Tested on iPhone 7 Plus, iPhone 13 Pro.
Unsure whether it will reproduce on a Pro Max size device.

https://user-images.githubusercontent.com/2472348/149753591-099c67bc-1eac-4232-b146-16eb7555f003.mp4

**Comment by Apollo2203** [comment]
> Unsure whether it will reproduce on a Pro Max size device.

https://user-images.githubusercontent.com/25265111/149965624-aeb6b545-d089-4f36-b3dd-f67e354b7611.MP4

I can confirm that the issue persists on Pro Max-sized devices. Linked is a screen recording from an iPhone 12 Pro Max running iOS 15.0.1 and Wordpress version 18.9. The gray bar is large and visible in dark mode, but where my experience differs is that I don't have enough topic options to allow vertical scrolling. In light mode there doesn't seem to be anything noticeable.
