### ISSUE TITLE
Posts list inconsistency on Android and iOS

### ISSUE THREAD

**Issue by jostnes** [wordpress-mobile/WordPress-iOS#17809]
### Expected behavior
There is an inconsistency between how Android and iOS apps show posts on Posts list screen. Issue discussed here: p5T066-2Vl-p2#comment-11031

### Actual behavior
On Android, all users' posts are displayed by default. On iOS, only posts by the logged-in user are displayed by default. There is an option to change this for everyone. On Post Cards, it will show by default everyone. 

### Steps to reproduce the behavior
On Android:
![android-list](https://user-images.githubusercontent.com/17252150/150913609-3b3d394b-b533-4030-9a11-cd33e58c07cb.jpg)

On iOS:
![ios-list](https://user-images.githubusercontent.com/17252150/150913644-099aeb0a-472f-4792-8d58-8d02241c5bda.PNG)

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 13 mini, iOS 15.0, v18.9

**Comment by kean** [comment]
Thanks for the report!

Duplicate:https://github.com/wordpress-mobile/WordPress-iOS/issues/16593
Fixed in the following PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/21766
