### ISSUE TITLE
Unable to connect to Facebook

### ISSUE THREAD

**Issue by reginabally** [wordpress-mobile/WordPress-iOS#17835]
### Expected behavior

I would expect to be able to connect my Facebook page to the WordPress.com site within the app.

### Actual behavior

Originally reported in 4717482-zd-woothemes, I was able to reproduce the issue of viewing a blank screen on the webview after I logged in to Facebook.

### Steps to reproduce the behavior

1. Go to My Site > Sharing > Facebook and tap the "Connect" button
2. Log in to Facebook on the webview
3. Select the Facebook page you want to connect to the site
4. Tap the "OK" button when you see the "You've now linked WordPress to Facebook"
5. When webview was redirected back to https://public-api.wordpress.com, it shows a blank screen
6. Tap the "X" button on the webview to return to the Sharing screen and see a pop-up with the notice "Connection canceled".

Screen recording of my testing steps can be found in the ticket.

##### Tested on iPhone 11, iOS 15.2.1, WPiOS 19.0.0.4

**Comment by ScoutHarris** [comment]
I think @frosty has fixed this with https://github.com/wordpress-mobile/WordPress-iOS/pull/17803.

**Comment by frosty** [comment]
I'm going to close this for now as it should be fixed by the above referenced PR. Thank you for the report!
