### ISSUE TITLE
Stats: Move Add New Insights Card to navigation bar

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#17845]
To make managing the Insights view in Stats more prominent, we should remove the "+ Add stats card" row from the bottom of the Insights screen and instead add a settings icon (cog) to the trailing end of the navigation bar.

**Comment by renanferrari** [comment]
@frosty @sla8c I noticed that #17867 didn't use the "Fixes" keyword in the description, so this issue wasn't automatically linked to it. I guess it can be closed now, though?

**Comment by sla8c** [comment]
@renanferrari sorry I didn't know `Fixes` was a keyword.  Thanks + noted!

@frosty will update my other PR with `Fixes`
