### ISSUE TITLE
Quickstart: View your site does not scroll the my site list to the View Site menu button.

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-iOS#17853]
### Expected behavior
During quickstart, when covering the View your site step, the my site list should scroll to the View Site menu button.

### Actual behavior
During quickstart, when covering the View your site step, the my site list should does not scroll to the View Site menu button.

### Steps to reproduce the behavior
Note: I tested this with an iPad that has a split view. Not sure if the issue is only relevant to iPad or can occur in iPhones as well.

- Opt into the QuickStart steps
- Complete the steps for "Customise Yout Site"
- When coming to the 6th step ("View your Site") notice the my site list is not scrolled to the View Site menu button

![image](https://user-images.githubusercontent.com/47797566/151951470-7d89445e-49e8-4361-be15-c77c2d6519de.png)

**Comment by tiagomar** [comment]
It is also reproducible on iPhone 13, iOS 15.0.2, WPiOS 19.1.0.2.
