### ISSUE TITLE
Quickstart - Grow your audience steps crossed out even if steps are not completed.

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-iOS#17852]
### Expected behavior
The Quickstart steps belongs to 2 categories:
1. Customise Yout Site
2. Grow Your Audience

When the steps belonging to the first category is completed only the first category should be crossed out to mark it as all completed.

### Actual behavior
When the steps belonging to the first category is completed I sometimes got both the first and second category crossed out to mark them as all completed, even though the second category step was not covered yet at all.

### Steps to reproduce the behavior
I was not able to consistently reproduce the issue; I was just creating a new .com site and completing the steps 1 by 1. I sometimes got to this condition below (sorry for not being able to provide detailed steps to reproduce)

![image](https://user-images.githubusercontent.com/47797566/151950563-122dfd41-4584-4dc8-bc03-092bb0d68784.png)

Note that I was getting the issue both using English and Italian (this last being the language reported in the screenshot)

Reference: p5T066-2Wh#comment-11099-p2

**Comment by tiagomar** [comment]
For me, `Grow Your Audience` got crossed out after completing `Customize Your Site` and starting `Grow Your Audience` only by clicking its first step `Social sharing` without even completing it.

#### iPhone 13, iOS 15.0.2, WPiOS 19.1.0.2
