### ISSUE TITLE
My Site Dashboard (Phase 2)

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#17879]
## Description

:star: **Goal**: Release the dashboard. Move the dashboard into the detail view controller for iPad.

Parent issue for phase 2 of the My Site Dashboard project.

Ref: pbArwn-3mP-p2

## Issues
- #17873
- #17874 
- #17875 
- #17876 
- #17877 
- #17878

**Comment by leandroalonso** [comment]
## Nice to have

### Posts card

- [x] Constraints warnings ([see description here](https://github.com/wordpress-mobile/WordPress-iOS/issues/17875))

**Comment by leandroalonso** [comment]
Given all the subtasks have been completed I'll close this Project Issue.

All the remaining tasks can be tracked using the [My Site Dashboard label](https://github.com/wordpress-mobile/WordPress-iOS/labels/My%20Site%20Dashboard).
