### ISSUE TITLE
[iOS] Stats: Improve table reloading

### ISSUE THREAD

**Issue by sla8c** [wordpress-mobile/WordPress-iOS#17929]
In the various Stats subscreens, it appears that any time the Store changes we reload the entire tableview through the store change observer callback.

As a result, sometimes the loading experience doesn't look very smooth: the various ghost views can restart their animations resulting in flickering, and it's more obvious that the screen is still loading as items refresh. I think if we could only reload the rows for specific items of data, we may be able to have a more seamless loading experience.

**Comment by sla8c** [comment]
Just an FYI + adding detail to this ticket.  Currently when selecting a Period tab, tableViewModel() is called / recreated 35 times

![image](https://user-images.githubusercontent.com/88816724/153353311-93b7b570-481b-4642-b958-23666ca28770.png)

**Comment by staskus** [comment]
@sla8c is it still a relevant task?

**Comment by sla8c** [comment]
@staskus I think we can close this for now + am doing
