### ISSUE TITLE
Refactor blog options

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#1793]
Currently we're storing blog options as a dictionary with anything that comes through `wp.getOptions`.

On #1788, we're turning the REST response into something that looks like that XML-RPC dictionary.

Since we can have multiple backends, and are only interested in a few options, let's store them as attributes of `Blog` and drop `options`

**Comment by kurzee** [comment]
This is still needed, believe it or not. Closing for now, but I'm sure we'll hit a brick wall with this at some point.
