### ISSUE TITLE
Reader Comments: Wrong avatar image assignment

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#17972]
Reported in `p1645046712677069-slack-C011BKNU1V5` and `p1645039635217679-slack-C0HTU7HV3`.
Refs #14926.

### Expected behavior
Comments should be displayed with the correct avatar image.

### Actual behavior
When opening Reader Comments from Notifications, sometimes the comment would show the wrong avatar image.

![duplicated_avatars](https://user-images.githubusercontent.com/1299411/154391201-bae0d92b-eff5-4864-9c0e-8942854acbb1.jpeg)

The image and username are censored out, but I tried to illustrate that the comment author (colored blue) has the avatar image of someone else (colored red).

### Steps to reproduce the behavior

- Go to Notifications.
- Tap a mention notification.
- Tap on the header to go to the comment threads.
- Observe that the avatar image is mismatched.

**Comment by yaelirub** [comment]
received another report with this issue in 19.3 p1649591059252629-slack-C3EA6SMFH

**Comment by dvdchr** [comment]
Thank you @yaelirub ! The fix in #17974 was more of a preventative measure since I was not able to reproduce the issue. I'll reopen this issue again.

**Comment by daniloercoli** [comment]
Hey @dvdchr, can we close this issue? It's about 2 years old now, and i don't think we've received feedback from users about it.

**Comment by dvdchr** [comment]
@daniloercoli, the solution proposed in https://github.com/wordpress-mobile/WordPressUI-iOS/pull/131 is not merged, so I think the incorrect image problem may still be happening. Let's keep it open for a little bit longer?

**Comment by guarani** [comment]
FYI I just ran into this on 24.4 beta:

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1898325/e93d86f5-d89b-4124-8f42-05b7c37976a5" width="400" />

**Comment by kean** [comment]
Fixed here https://github.com/wordpress-mobile/WordPress-iOS/issues/23548
