### ISSUE TITLE
Title and URL remain after deleting WP.com site

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#17982]
This was tested with a WP.com account that had access to multiple sites.

### Expected behavior
After site deletion, the app switches to an exiting site and updates the title and URL to the site it switched to.

### Actual behavior
After site deletion, the app switches to an exiting site but doesn't update the title and URL to the site it switched to.

### Steps to reproduce the behavior
1. On a WP.com site that's OK to delete, go to Site Settings from the My Site view
2. Delete Site
3. Observe that the title and URL of the deleted site remain in the My Site view

https://user-images.githubusercontent.com/2092798/154616284-94c8c71f-b6cf-4456-ae6b-de6fb47b7467.mp4

**Comment by twstokes** [comment]
I believe this is related to #17928.

**Comment by twstokes** [comment]
This is related to https://github.com/wordpress-mobile/WordPress-iOS/issues/17993

**Comment by momo-ozawa** [comment]
Closed via #17995
