### ISSUE TITLE
Title and URL aren't updated after creating WP.com site

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#17993]
### Expected behavior
After creating a new WP.com site, the site title and URL are updated on the My Site view.

### Actual behavior
After creating a new WP.com site, the site title and URL aren't updated on the My Site view.

### Steps to reproduce the behavior
1. Have an existing site loaded in the My Site view
2. Create a new WP.com site
3. Observe that the title and URL of the previous site remain in the My Site view

https://user-images.githubusercontent.com/2092798/154783951-5be03345-41df-40d5-a738-8b2f7b446977.mp4

**Comment by twstokes** [comment]
Hi @momo-ozawa and @leandroalonso 👋! While troubleshooting this error (as well as https://github.com/wordpress-mobile/WordPress-iOS/issues/17982), I spotted that in #17814 we're no longer adding a SitePickerViewController [if one already exists](https://github.com/wordpress-mobile/WordPress-iOS/pull/17814/files#diff-4e5c233c5685b8886da6dcf2950bfe0acf3745816942b57f42e07036fea02114R541) in the MySiteViewController. [`addSitePickerIfNeeded(for blog: Blog)` is called in the `blog` setter](https://github.com/wordpress-mobile/WordPress-iOS/blob/129df7013c2b877a00103897a84ef5a04ea0b325/WordPress/Classes/ViewRelated/Blog/My%20Site/MySiteViewController.swift#L94).

I wonder if perhaps this change is blocking updates when the title and URL need to be updated? Thanks for any insight!

**Comment by momo-ozawa** [comment]
Hi @twstokes -- the title and url weren't being updated because we weren't updating the blog for SitePickerViewController if SitePickerViewController already exists. Thanks for alerting us about this issue!
