### ISSUE TITLE
Push notifications should wait to register until signed into WP.com

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#1802]
The app should not be registering for push notifications until the app is signed into WordPress.com.  The context surrounding why push is needed is lost - and I think the registration call ultimately fails on the server side anyway (or is never made).

![img_0002](https://cloud.githubusercontent.com/assets/373903/3162020/6f00d270-eb31-11e3-9153-a3357e379beb.PNG)

**Comment by rachelmcr** [comment]
I confirmed that the app still registers for push notifications immediately after install in the latest stable release (5.7). I could see either waiting until the user contacts support or logs in (better), or first showing a prompt that explains what the app uses push notifications for to give a little context (better than nothing).
