### ISSUE TITLE
[Site Intent Question] Display default verticals

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#18035]
### Description

A new screen has been added to the site creation flow. It will display ~20 default verticals that will either:
- be bundled with the app
- ~~or, be fetched from the verticals WP.com API: [`wpcom/v2/verticals`](https://public-api.wordpress.com/wpcom
/v2/verticals) (TO-DO: link to separate issue)~~

Other considerations:
- Each vertical, when tapped, should send the vertical's ID to Tracks and navigate the user next screen (the "Choose a design" screen).
- ~~The verticals are English-only~~ The verticals will be localized
- Each vertical will have an associated emoji
- The screen will have a search input ~~but its functionality will be done in a separate issue (TO-DO: link to separate issue)~~
- The screen will have a "Skip" button that will also send a Tracks event
- This screen should only appear on dev-builds (until the feature is released)

This issue is UI-only and can be considered Done when the screen looks and behaves like the design below. ~~Dummy data can be used since API integration is a separate issue. The search input should be visible but not functional.~~

_Note: All development should be behind [the feature flag `SITE_INTENT_QUESTION`](https://github.com/wordpress-mobile/WordPress-iOS/issues/18043)_

### Latest design

The latest design found below covers the updated site creation flow.

<img src="https://user-images.githubusercontent.com/1898325/155761319-a642b5fe-2c07-439f-8354-85ad3288a9c0.png" alt=""> 

The scope of this issue is the "Choose a site topic" screen:

<img width="250" alt="Screen Shot 2022-02-25 at 14 39 34" src="https://user-images.githubusercontent.com/1898325/155761694-932e813c-7798-4bf6-84d5-0f834a0c6731.png">

### Issue breakdown
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/18106
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/18107
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/18108
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/18205

**Comment by guarani** [comment]
I've updated the issue description due to a recent decision to not use the verticals API but instead use bundled and localized verticals. Please edit it and leave a comment if it doesn't sound right.

**Comment by ovitrif** [comment]
I added #18205 to the issue breakdown sections

**Comment by antonis** [comment]
Closing this as all subtasks have completed 🎉
