### ISSUE TITLE
[iOS] Stats: Insight Defaults View - changes for meaningful cards

### ISSUE THREAD

**Issue by sla8c** [wordpress-mobile/WordPress-iOS#18042]
As part of Stats revamp:

 * Change the default view in "Insights", which includes:
   * Move "meaningful" cards to the top, so that they are immediately visible to users (TBD exactly which cards, but we seem to have an agreement that views, visitors, likes, comments have priority)

**Comment by staskus** [comment]
@sla8c Does this issue still has a purpose or meaning or could we close it? Thanks!

**Comment by sla8c** [comment]
@staskus we can close this + I’m closing thanks for flagging
