### ISSUE TITLE
[Site Intent Question] Analytics tracking

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#18086]
### Description
The following events should be tracked for the [Site Intent Question screen](https://github.com/wordpress-mobile/WordPress-iOS/issues/18035):
1. **Cancel/Back** pressed (`enhanced_site_creation_intent_question_canceled`): No properties
2. **Skip** pressed (`enhanced_site_creation_intent_question_skipped`): No properties
3. Vertical **selected** (`enhanced_site_creation_intent_question_vertical_selected`): ~~2 properties `vertical_id`, `vertical_slug`~~ 1 property `vertical_slug`
4. **Continue** Pressed (`enhanced_site_creation_intent_question_continue_pressed`):  1 property `search_term`
5. **Search** focused (`enhanced_site_creation_intent_question_search_focused`): No properties
6. Screen **viewed** (`enhanced_site_creation_intent_question_viewed`): No properties

![Screenshot 2022-03-03 at 5 51 16 PM](https://user-images.githubusercontent.com/304044/156600728-4bc66e87-3eb6-49b1-b5c5-40d1925e0cdc.png)

**Comment by antonis** [comment]
Adding one more [tracking event for the selected variation](https://github.com/wordpress-mobile/WordPress-iOS/issues/17988) to match the [Android implementation](https://github.com/wordpress-mobile/WordPress-Android/pull/16128/commits/efa17407ebb5a5a390ba8ff34998700479397659) and make the analysis easier:
7. event `enhanced_site_creation_intent_question_experiment`, property `variation`, values: `control`, `treatment`

**Comment by twstokes** [comment]
👋 [Stubs for all events](https://github.com/wordpress-mobile/WordPress-iOS/blob/d63ac5a048e6ee973d01265d31f67d8059297261/WordPress/Classes/ViewRelated/Site%20Creation/Shared/SiteCreationAnalyticsHelper.swift#L10-L33) but `enhanced_site_creation_intent_question_experiment` were added to #18166.

**Comment by guarani** [comment]
> 👋 [Stubs for all events](https://github.com/wordpress-mobile/WordPress-iOS/blob/d63ac5a048e6ee973d01265d31f67d8059297261/WordPress/Classes/ViewRelated/Site%20Creation/Shared/SiteCreationAnalyticsHelper.swift#L10-L33) but `enhanced_site_creation_intent_question_experiment` were added to #18166.

Thanks for adding those! https://github.com/wordpress-mobile/WordPress-iOS/issues/18086 will track the adding of the actual events, right?

**Comment by twstokes** [comment]
> Thanks for adding those! #18086 will track the adding of the actual events, right?

That's my understanding @guarani, which is this issue.

**Comment by guarani** [comment]
I updated the issue description to remove `vertical_id` from `enhanced_site_creation_intent_question_vertical_selected`, since the slug will be enough to identify the vertical.
