### ISSUE TITLE
[Site Intent Question] Enable searching through default verticals on the Site Intent Question screen

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#18108]
### Description

Subpart of:
- https://github.com/wordpress-mobile/WordPress-iOS/issues/18035

Search input & functionality exists in the [Site Intent Question screen](https://github.com/wordpress-mobile/WordPress-iOS/issues/18106).

### Acceptance Criteria

- [x] Search input is displayed above the verticals list
  - [x] Placeholder with examples is displayed inside search input
- [x] Search input tap (focus)
  - [x] hides Title & Subtitle in Header (with parallax slide down transition)
- [x] Search input empty:
  - [x] Placeholder with examples is displayed inside search input
  - [x] The full list of searchable verticals is presented, ref: pbArwn-447-p2#default-verticals
  - [x] Continue button is hidden
- [x] Search input typing:
  - [x] filters the verticals presented below it to match the search term
  - [x] When no results match the search term:
    - [x] Blank white surface is displayed for search results
    - [x] Continue button shows above keyboard
      - [x] Continue button tap → Navigates to "Choose a Design" screen
- [x] Search result list item tap → Navigates to "Choose a Design" screen

#### Other Considerations:

- [ ] Unit Tests are added where applicable
- [ ] List of search results is scrollable
- [ ] Events are tracked (Vertical selected, Search focused, Continue Pressed, )

### Expected Design & Flow

![iosFlow3](https://user-images.githubusercontent.com/4588074/160114585-64874684-404d-4d80-89a4-feb967ad4af7.png)

**Comment by ovitrif** [comment]
I updated the Acceptance Criteria & the image with the latest specs from i2 design - pbArwn-447-p2
