### ISSUE TITLE
Quick Start: "View your site" blue dot is hidden behind FAB button

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#18154]
### Expected behavior
While taking the `View your site` tour, the pulsating blue dot should be visible on `View Site` menu button

### Actual behavior
`View Site` menu button's blue dot is hidden behind FAB button.

| Simple site ❌  | Atomic site ✅ |
| - | - |
| <img width="300" alt="image" src="https://user-images.githubusercontent.com/42008628/158674384-04cf670c-f532-4b8e-b5ef-917f5acf03b0.png"> | <img width="300" alt="image" src="https://user-images.githubusercontent.com/42008628/158677571-b58e15dd-6457-4059-a99b-3037c05524c8.png"> |
| <video width="300" src="https://user-images.githubusercontent.com/42008628/158674188-fcedd854-3c64-4fa8-b85c-d96e9e761a8b.mov"> | <video width="300" src="https://user-images.githubusercontent.com/42008628/158675289-928d4264-6bb3-459a-ac6f-0760595df865.mov"> |

### Steps to reproduce the behavior
1. Log in or create a new site
2. Tap `Show me around`
3. Tap `Customize Your Site`
4. Tap `View your site`

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
