### ISSUE TITLE
My Site Dashboard: make sure deeplinking to My Site works

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#18174]
Make sure deeplinking actions to My Site work as expect.

**Comment by hassaanelgarem** [comment]
@leandroalonso @momo-ozawa 
I've tested all the relevant deep links mentioned [here](https://wpmobilep2.wordpress.com/2021/03/15/overview-of-the-deeplinks-in-the-wordpress-app/) (My site and stats links), and all works as expected.

When MSD is enabled and the dashboard is the selected tab, we first navigate to the site menu tab then carry on normally.

One thing to note, is that we sometimes take unecessary actions. For example we can get to stats from the dashboard (quick actions), however, in that case we first navigate to the site menu then to stats page. Changing that however won't be so simple I guess. Is this something we want to do now?

**Comment by momo-ozawa** [comment]
@hassaanelgarem Thank you for testing deep linking!

> I've tested all the relevant deep links mentioned [here](pbArwn-1S1-p2) (My site and stats links), and all works as expected.

😄 

> One thing to note, is that we sometimes take unecessary actions. For example we can get to stats from the dashboard (quick actions), however, in that case we first navigate to the site menu then to stats page. Changing that however won't be so simple I guess. Is this something we want to do now?

I think improving deep linking is out of scope for MSD. Also, given that the dashboard is an experiment, I don't think we need to enhance deep linking for the dashboard at this point in time.

**Comment by hassaanelgarem** [comment]
Makes sense 👌 
I will close this task then 👍
