### ISSUE TITLE
Stats: Referrers Card Doesn't Show the Expandable Data/Row

### ISSUE THREAD

**Issue by erricgunawan** [wordpress-mobile/WordPress-iOS#18172]
### Expected behavior

Referrers card should show all data like in the desktop version, be it a single row/data or an expandable one.

This mostly can be observed on the `Search Engines` row which usually includes multiple expansible rows. 

### Actual behavior

It now only shows data on a single row. The expansible ones are missing in the app. 

I'm taking my guess, but it might be affected by this redesign work: https://github.com/wordpress-mobile/WordPress-iOS/issues/16710

Reported on 4867132-zen but I can reproduce on my own site. 

### Steps to reproduce the behavior

1. Take a pick on the Stats on the desktop. 
2. Make sure it's on "Traffic", then pick between Days, Weeks, Months, Years, it doesn't matter.
3. But especially look for the one that has many Views/data on the Referrers section.
4. Open the same Stats on the app and observe it didn't display the expansible rows. 

<details>
  <summary>Screenshot on Desktop:</summary>
  <br>
  
<img width="473" alt="2022-03-21 Stats Referrer 2" src="https://user-images.githubusercontent.com/1813857/159396867-5e214bc6-e55f-4b44-9340-f747b020fa18.png">

</details>

<details>
  <summary>Screenshot on App:</summary>
  <br>
    
![IMG_3219](https://user-images.githubusercontent.com/1813857/159221990-247e13ca-b530-43d0-b977-f56fef924306.PNG)

![IMG_3220](https://user-images.githubusercontent.com/1813857/159222013-00b85110-fd46-40b0-a2a5-88fbd5aca679.PNG)

</details>

**Comment by mdrockwell** [comment]
I'm not sure I understand what is different. Aren't you able to see the same information on desktop and mobile, but instead of expandable sections, you can tap on them to see the list in another view? duckduckgo.com, Baidu, and Yandex are all visible on both with the same stats on each. Is there something that I'm misunderstanding? Is the user just looking to have these expandable instead of taking them to another view with the list?

**Comment by erricgunawan** [comment]
I'm replacing the original screenshot for the Desktop one to hopefully make it a bit more clear.

On the app version, we're missing the ones in the green box.

For the example above, in Desktop, if we expand `Search Engines`, we'll see 6 items in total:

- 3 in the green box (Google Search, Bing, Yahoo Search) which can be expanded (to a 2nd level)
- 3 in the red box (duckduckgo.com, Baidu, and Yandex), not expandable

In the app, we only see the ones in the red box. We're missing the ones in the green box (Google Search, Bing, Yahoo Search).

**Comment by mdrockwell** [comment]
@erricgunawan Thanks for the clarification, I missed that when I was looking at it previously. :)

**Comment by ChrissiePollock** [comment]
Any updates on this? The customer is back enquiring.... @mdrockwell Are you working on this?

**Comment by fluiddot** [comment]
> For the example above, in Desktop, if we expand `Search Engines`, we'll see 6 items in total:
> 
> * 3 in the green box (Google Search, Bing, Yahoo Search) which can be expanded (to a 2nd level)
> * 3 in the red box (duckduckgo.com, Baidu, and Yandex), not expandable
> 
> In the app, we only see the ones in the red box. We're missing the ones in the green box (Google Search, Bing, Yahoo Search).

I'm wondering if the fact that the items `Google Search`, `Bing`, `Yahoo Search` can also be expanded is related to the cause of the issue 🤔.

**Comment by frosty** [comment]
We're making a few tweaks to the Referrers card soon as part of the Stats Revamp project on iOS. We can check into why these additional search engines aren't showing up in the list, but we have no plans to add any extra 'dropdown' or expand / collapse functionality – currently you can navigate into the list of search engines by tapping on the Search Engines title.

**Comment by frosty** [comment]
Apologies, misclicked the comment button!

**Comment by fluiddot** [comment]
Regarding the priority of this issue, I understand that missing stats information is a bit critical, moreover, if the referrers are search engines which most likely are the top ones, so I'll mark this as a high priority.
