### ISSUE TITLE
Edit Post: Confusing user experience when editing the same post multiple times

### ISSUE THREAD

**Issue by brcavallaro** [wordpress-mobile/WordPress-iOS#18180]
### Expected behavior
Stale data (previous post versions) should be discarded after publishing a new post version.

### Actual behavior
When editing and publishing the same post several times, it seems the previous edition screens are kept in the background, causing a _weird_ behavior. Check the recording and steps below.

<div align="center">

https://user-images.githubusercontent.com/2813972/159394529-4abd9be5-aa22-4c82-a623-635b1b06483a.mov

</div>

### Steps to reproduce the behavior

1. Edit an existing post, creating a new block.
2. Publish the editions.
3. In the summary view, click on `Edit Post` again.
4. Repeat the steps above multiple times.
5. After publishing the last edition, tab the `OK` button in the summary view.

**Comment by twstokes** [comment]
👋 Hi @brcavallaro - this is hopefully resolved now. Thanks for bringing it to our attention!
