### ISSUE TITLE
Remove emojis from design screen when we show the intent question

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#18205]
Since emojis are used on the Site Intent screen, it was decided to remove emojis from the existing design screen:

| Before | After |
| - | - |
| <img src="https://user-images.githubusercontent.com/1898325/159940846-3f90a173-fec2-43d0-98d3-630210d27ea1.jpeg" alt="" width="350"> | <img width="350" alt="Screen Shot 2022-03-24 at 11 38 06" src="https://user-images.githubusercontent.com/1898325/159940870-839865be-f54a-4a12-b671-fa3cf47d1ea0.png"> |

This issue mirrors https://github.com/wordpress-mobile/WordPress-Android/issues/16165.

**Comment by antonis** [comment]
Dropping this as discussed internally (ref `pbArwn-447-p2#comment-5290`)
