### ISSUE TITLE
Notifications Details: App crashed a few times when navigating through the details of my notifications

### ISSUE THREAD

**Issue by brcavallaro** [wordpress-mobile/WordPress-iOS#18218]
### Expected behavior
The app should allow the user to navigate through all the existing notifications and see their details, without crashing.

### Actual behavior
The app is crashing sometimes when navigating through the notifications' details.

> I tried to reproduce this a few times to get some screen recordings but I couldn't. [Check here the activity logs](https://github.com/wordpress-mobile/WordPress-iOS/files/8358816/2022-03-27_activitylog.txt).

### Steps to reproduce the behavior
1. Go to the **Notifications** list view
2. Open the details of one of the notifications
3. Navigate quickly over the other notifications you have by tapping the arrows `↑ ↓` in the top menu

**Comment by ScoutHarris** [comment]
I’m unable to reproduce this. I tried:

- different devices
- different iOS versions
- slow network
- fresh install
- rapidly tapping on the arrows

I can’t get it to crash. I see you noted in the description you weren’t able to repro it, but if you do and can provide more information I’ll gladly look into it again.
