### ISSUE TITLE
Call to notifications/seen shouldn't be done when phone is locked

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#1822]
If you leave your device locked but on the notifications tab, the call to notifications/seen is being done.  This is effectively causing push notifications to be dismissed on all devices.  The app should be aware if the screen is locked (and if the user is on the root controller or inside of a notification) and only make the call to seen when appropriate.  

I believe this is how it used to work but may have been changed with the recent refactoring.

**Comment by jleandroperez** [comment]
I'm closing this one since it's no longer relevant. "Last Seen" is now being handled via Simperium, and the field is effectively updated when:

- The app becomes active, and NotificationsViewController was visible.
- The user taps over the Notifications icon.

Thanks everyone!
