### ISSUE TITLE
Sharing: Share Sheet does not consistently display WordPress app when sharing images

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-iOS#18232]
### Expected behavior
When I tap on "share" an image or a video, I expect to see the WordPress app as an option to select.

### Actual behavior
The WordPress app no longer seems to be listed among the "Share via" app list, as of the current beta (19.5).

### Steps to reproduce the behavior
1. Update WordPress or Jetpack to 19.5-rc-1 or rc-2 (current)
2. Open an image or video and tap the share icon
3. Look for the WordPress icon.

In my testing, the WordPress icon didn't appear after updating. 
Some time later, it did appear again (perhaps after restarting the photos app).

**Comment by thehenrybyrd** [comment]
@ashiagr I see you fixed this in Android with https://github.com/wordpress-mobile/WordPress-Android/pull/16195, however I am still running into this with videos in iOS 19.6.
Do you have any ideas about this?

**Comment by ashiagr** [comment]
👋 @momo-ozawa, @hassaanelgarem 
Can you help us with this?

**Comment by momo-ozawa** [comment]
Sure, will take a look!

**Comment by momo-ozawa** [comment]
Actually, @frosty @sla8c I see that you've worked on the share sheet somewhat recently (https://github.com/wordpress-mobile/WordPress-iOS/pull/17785)   -- would you mind taking a look at this issue? Thank you!

**Comment by frosty** [comment]
Hey @momo-ozawa and @thehenrybyrd, I've done some testing here and I'm unable to reproduce the issue with photos myself – the app icon is always there for me. I also think our recent changes are unrelated, as they only affect code that is run after the Share Extension is activated.

Regarding the icon not showing for video, this is expected. The share extension currently only supports photos, text, and URLs.

**Comment by thehenrybyrd** [comment]
@frosty thanks for testing! I was also unable to repro for images.

> Regarding the icon not showing for video, this is expected. The share extension currently only supports photos, text, and URLs.

Oh, good to know! I wouldn't have expected that, and I do see WP Android's share sheet supports video.
This seems like it would make a good enhancement request. Do you know of any limitations that would make this unachievable?
Otherwise, I'll close this issue and create an enhancement request to support videos in share sheet.

**Comment by frosty** [comment]
From my understanding, it is more problematic on iOS due to the restrictions on applications running in the background. With videos being larger than photos and taking longer to upload, I think the issue is ensuring the app or share extension stay awake in the background long enough to upload. It'd require further investigation for sure.

I think an enhancement request is the way to go! Thank you :)

**Comment by thehenrybyrd** [comment]
Thanks! Enhancement request is here: https://github.com/wordpress-mobile/WordPress-iOS/issues/18327
I'll close this issue now.
