### ISSUE TITLE
My Site Dashboard freezes on fresh install, iOS 15.4

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#18256]
Refs `p1648811499644559-slack-C011BKNU1V5`, https://github.com/wordpress-mobile/WordPress-iOS/pull/18251#issuecomment-1084907112

### Expected behavior
The dashboard does not freeze.

### Actual behavior
When switching from Site Menu to the Home dashboard, the app freezes.

### Steps to reproduce the behavior
- Modify the code so that the feature flag for My Sites Dashboard is turned on.
- Uninstall the WordPress app from the simulator.  ⚠️ NOTE: **This issue only happens on a fresh install**. ⚠️ 
- Build the app using Xcode 13.3, targeting iOS 15.4.
- After logging in and selecting a site, you should see the Site Menu dashboard being active/selected.
- Tap on the Home section.
- Observe that the app freezes.

The dashboard works just fine on subsequent runs (after the app is killed and started again). Here are some screenshots:

On fresh install, app freezing | After reruns, working just fine
-|-
![freezing](https://user-images.githubusercontent.com/1299411/161261368-84752a98-0e8c-4903-a572-eb11f99735c7.png) | ![reruns](https://user-images.githubusercontent.com/1299411/161261396-43aceafb-b5be-4db6-ad0b-495a1244ba65.png)

### Tested on

- iOS 15.4 Simulator:
  - iPhone 8
  - iPhone 11 Pro Max
  - iPhone 12
  - iPhone 12 Pro Max
- Device:
  - iPhone 11 Pro Max (iOS 15.4)

Note that this problem is not reproducible on iPads.

**Comment by leandroalonso** [comment]
Side note: we should probably also address the issue of the "Write your next post" label being cut.

**Comment by leandroalonso** [comment]
Another test that might be interesting to do: once `19.6` is on TestFlight, try the same steps on a device with iOS `15.4.1`. I tested this [build here](https://github.com/wordpress-mobile/WordPress-iOS/pull/18215#issuecomment-1079092265) and didn't have any issues.

We still need to address this though, but then it means it will not affect users.

**Comment by hassaanelgarem** [comment]
@leandroalonso 

> Side note: we should probably also address the issue of the "Write your next post" label being cut.

I created a separate issue (#18266) to track this 👍
