### ISSUE TITLE
Enforce or show warning when local Ruby version doesn't match .ruby-version

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#18261]
### Expected behavior
Helpful messaging to the developer when their local version of Ruby doesn't match what's in [`.ruby-version`](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/.ruby-version) ([like we do with Xcode](https://github.com/wordpress-mobile/WordPress-iOS/blob/8f6cc9d9cb54cf75106c63a6adaf3215e0a2f70a/Rakefile#L314)). We could also add to the error or docs that [rbenv](https://github.com/rbenv/rbenv) can be used to manage versions.

### Actual behavior
On Apple Silicon Macs `rake dependencies` fails to finish successfully without a clear reason why.

### Steps to reproduce the behavior
**Precondition**: Apple Silicon Mac running the default Ruby version included with macOS Monterey (I had `ruby 2.6.8p205`)
1. Clone the repo
2. Run `rake init:oss` or `rake dependencies`
3. Observe error in the "Extra context" section below

After installing the Ruby version that matched `.ruby-version`, `rake dependencies` finished successfully. I did receive a warning that Bundler didn't match the lockfile version, which was fixed with the suggested command.

### Extra context

<details>
<summary>Error output</summary>

```
  763 /Users/tanner/dev/WordPress-iOS/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/struct_layout_builder.rb
  764 /Users/tanner/dev/WordPress-iOS/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/struct_by_reference.rb
  765 /Users/tanner/dev/WordPress-iOS/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/struct.rb
  766 /Users/tanner/dev/WordPress-iOS/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/union.rb
  767 /Users/tanner/dev/WordPress-iOS/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/managedstruct.rb
  768 /Users/tanner/dev/WordPress-iOS/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/callback.rb
  769 /Users/tanner/dev/WordPress-iOS/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/io.rb
  770 /Users/tanner/dev/WordPress-iOS/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/autopointer.rb
  771 /Users/tanner/dev/WordPress-iOS/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/variadic.rb
  772 /Users/tanner/dev/WordPress-iOS/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/enum.rb
  773 /Users/tanner/dev/WordPress-iOS/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/version.rb
  774 /Users/tanner/dev/WordPress-iOS/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi/ffi.rb
  775 /Users/tanner/dev/WordPress-iOS/vendor/bundle/ruby/2.6.0/gems/ffi-1.15.4/lib/ffi.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: https://www.ruby-lang.org/bugreport.html

[IMPORTANT]
Don't forget to include the Crash Report log file under
DiagnosticReports directory in bug reports.

rake aborted!
Command failed with status (): [bundle exec pod install...]
/Users/tanner/dev/WordPress-iOS/Rakefile:653:in `pod'
/Users/tanner/dev/WordPress-iOS/Rakefile:75:in `block (4 levels) in <top (required)>'
/Users/tanner/dev/WordPress-iOS/Rakefile:643:in `fold'
/Users/tanner/dev/WordPress-iOS/Rakefile:74:in `block (3 levels) in <top (required)>'
/Users/tanner/dev/WordPress-iOS/Rakefile:69:in `block (3 levels) in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
Tasks: TOP => dependencies:pod:install
(See full trace by running task with --trace)
```

</details>

**Comment by twstokes** [comment]
cc @wordpress-mobile/owl-team for their thoughts

**Comment by mokagio** [comment]
Great idea @twstokes! Thank you for bringing this up 🙇‍♂️ 

I have other things on my plate right now, but here's a suggestion if you or someone else has time to play with this. 

- We can get the runtime Ruby version with `RUBY_VERSION`
- We can get the expect Ruby version by reading it from the version file, `File.read('./.ruby-version')`

So, we could do something like 

```ruby
if File.read('./.ruby-version) != RUBY_VERSION
  # Print error and rbenv instructions, then fail the Rake task
end
```
