### ISSUE TITLE
[Site name] Submit the Site name value

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#18275]
## Description
The site name value entered by the user should be submitted to the API. For this a new parameter `blog_title` will be added in the existing API call `sites/new/` that is performed at the end of the flow.

**Comment by antonis** [comment]
Check https://github.com/wordpress-mobile/WordPress-iOS/issues/18324 for the full details of the API call modification

**Comment by twstokes** [comment]
This was resolved with [this change](https://github.com/wordpress-mobile/WordPress-iOS/blob/faa4739a282127c469c2cf06d737fa3761c74e20/WordPress/Classes/ViewRelated/Site%20Creation/Site%20Name/SiteNameStep.swift#L22) from #18335.

I've confirmed that the [`SiteCreationRequest` assembled here](https://github.com/wordpress-mobile/WordPress-iOS/blob/faa4739a282127c469c2cf06d737fa3761c74e20/WordPress/Classes/ViewRelated/Site%20Creation/Wizard/SiteCreator.swift#L50) will use this value and send it to the API on site creation.
