### ISSUE TITLE
[Site Name] A/B Test the site name screen

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#18272]
### Description
The site name screen should be shown conditionally to A/B test the implementation.
We will use the ExPlat platform to run this experiment

_Note: All development should be behind [the feature flag `SITE_NAME `](https://github.com/wordpress-mobile/WordPress-iOS/issues/18271)_

**Comment by antonis** [comment]
Hey @twstokes 👋 
I've created an experiment we can use for testing `wpios_site_name_v1`. This [older ExPlat integration](https://github.com/wordpress-mobile/WordPress-iOS/pull/17429) might also be helpful

**Comment by twstokes** [comment]
> Hey @twstokes 👋 I've created an experiment we can use for testing `wpios_site_name_v1`. This [older ExPlat integration](https://github.com/wordpress-mobile/WordPress-iOS/pull/17429) might also be helpful

Thank you @antonis!
