### ISSUE TITLE
Video length restrictions should only apply to free .com sites

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#18277]
## Description
Video length restrictions should only apply to free .com sites. [Implementation PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/17689).

<sub>Internal ref: p1649093929647349-slack-C011BKNU1V5</sub>

### Expected behavior
No restrictions to video length on a self-hosted site.

**Note:** Server limitations will still apply, such as max upload size.

### Actual behavior
"Selection not allowed" error is shown.

<img src="https://user-images.githubusercontent.com/2092798/161607435-1b5351ae-d437-405a-bea4-61b24134bd54.png" width="350px" alt="Selection not allowed error" />

### Steps to reproduce the behavior
**Precondition:** A video that is within the server upload limit and longer than five minutes. See instructions below on how to find the max upload size.

1. Connect WPiOS to a self-hosted site
2. Tap "Media"
3. Tap "Upload Media"
4. Tap "Choose from My Device"
5. Select a video longer than five minutes

#### Finding max upload size

1. Log in to the self-hosted site's dashboard
2. Select "Media"
6. Select "Add new"
7. Look at the value under the "Select Files" button

<img src="https://user-images.githubusercontent.com/2092798/161608311-dfd59949-cd4b-4acd-9414-4240f0218005.png" width="400px" alt="Max upload size image" />

##### Tested on iPhone 12 Pro, iOS 15.4.1, WPiOS 19.6

**Comment by guarani** [comment]
Thanks so much for spotting this, @twstokes! ❤️ 

The severity of this is high in my opinion (uploading videos is part of editing which is a high priority area). Impact seems low because we've only had one user report (@twstokes). This gives me an overall Medium priority ([internal ref](pbArwn-1gZ-p2)), so I'll update the priority here.

**Comment by guarani** [comment]
👋 @sla8c, could you please look into this?

**Comment by sla8c** [comment]
@twstokes @Guarani I have a PR for this issue here: https://github.com/wordpress-mobile/WordPress-iOS/pull/18414

Thanks @frosty for pointing me in the right direction!
