### ISSUE TITLE
My Site Dashboard: Error when navigating to dashboard as a contributor or author

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#18287]
### Expected behavior

It should be possible to navigate to the main My Site dashboard as a contributor or author without seeing any error.

In addition, if the app is unable to retrieve posts for any reason, the "unable to load posts" error shouldn't obfuscate any text and should be styled in a consistent manner. 

### Actual behavior

The "post" cards in the new My Site dashboard display an error when navigating as a contributor or an author.

There's also a large gap between the error's sentences and it overlays other text. In my testing, I found that a random image from one of my sites would also sometimes appear alongside the error.

| Overlapping text  | Random image |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/2998162/161782248-b709828f-6490-4cdc-8df9-be4673cd635b.PNG" width="100%"> | <img src="https://user-images.githubusercontent.com/2998162/161782542-c03ffcb0-63ee-4b9f-8c12-6569bb3db3ec.PNG" width="100%"> |

### Steps to reproduce the behavior

1. Log into a WordPress.com site on which you are an author or a contributor. The site should also have some existing posts and drafts. 
2. Navigate to the new My Site Dashboard within the app and observe that all appears as expected.
4. Tap on a post to get to the posts list and navigate back to the new dashboard again.
5. Keep navigating to different areas of the app before navigating back to the new dashboard and eventually seeing the "unable to load posts" error.
6. Observe that the error overlaying the dashboard's posts sections isn't styled as expected. 

##### Tested on iPhone XR, iOS 15.3, WPiOS 19.6 beta

**Comment by leandroalonso** [comment]
cc @momo-ozawa (I think it's the same issue @osullivanchris shared)

**Comment by leandroalonso** [comment]
@SiobhyB I wasn't able to reproduce that. 🤔

Here's what I did:

1. Open the app on a real device
2. Dashboard loaded with a few posts
3. I turned on the airplane mode
4. Went to Stats and then back to the Dashboard
5. No overlayed message was shown

Could you please provide the exact steps of where you navigated? Are you an admin or contributor in that site?

**Comment by SiobhyB** [comment]
@leandroalonso, huh, interesting! I'd assumed this happened as a result of me toggling aeroplane mode on/off but, in further testing, I think it may be the result of me being a contributor on the site I'm testing. I can replicate by following these steps on the site where I'm a contributor:

* Navigate to the new dashboard.
* Tap on a post to get to the posts list and navigate back to the new dashboard again.
* Keep navigating to different areas of the app before navigating back to the new dashboard and eventually seeing the error.

I'm not certain whether the user role is the cause of this or not, so would be interested to hear whether you're able to reproduce while logged in as a contributor on a WordPress.com site. If not, I'd be happy to invite you as a contributor to the site where I'm able to reproduce this error, to see if you can spot anything else that may be causing it.

**Comment by osullivanchris** [comment]
@SiobhyB @leandroalonso I had the same bug down to being a contributor as well! Here are the steps I mentioned (you can find on the project slack channel)

- went to a site that I own, cards appear as normal
- switched to automattic.design where I think I am an author but not an admin
- initially nothing appeared in the draft posts card
- refreshed and it said the 'unable to load posts' message
- refreshed again and got the 'create next post' on top of that
- For the record I do have 1 draft on that site. But I dont have access to anybody elses drafts

**Comment by SiobhyB** [comment]
@osullivanchris, thank you for confirming that! I've gone ahead to update the issue's description to more accurately reflect the issue here 🙌

**Comment by osullivanchris** [comment]
@SiobhyB nice one, thanks for driving it! 🙏

**Comment by momo-ozawa** [comment]
I was also able to replicate this after being invited to Siobhan's test site as a contributor
<img src="https://user-images.githubusercontent.com/6711616/161993039-b60bfaf3-55c5-4ac2-bc5e-63aea1628684.PNG" width=200>
