### ISSUE TITLE
My Site Dashboard: Show site name in nav title when nav bar is collapsed

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#18289]
## Description

Currently the nav title remains "My Site" when the nav bar is collapsed. Android displays the site name instead -- it would be nice to have this behavior on iOS as well.

<img width="1046" alt="Screen Shot 2022-04-05 at 17 46 06" src="https://user-images.githubusercontent.com/6711616/161805679-ac29d01b-f7ab-4193-aaaf-b978dba1ef08.png">

**Comment by amustafa15** [comment]
not sure how to self-assign but I can take a look at this

**Comment by momo-ozawa** [comment]
Hi @amustafa15 👋 
Thanks for taking a look! 

Just a heads up -- we're hoping to include a fix for this issue in an upcoming release. So depending on how far you are with a solution, we may end up tackling this issue ourselves. If you can have a PR ready by the end of this week, we'd be more than happy to review.

Otherwise, we have other good first issues [here](https://github.com/wordpress-mobile/WordPress-iOS/issues?q=is%3Aopen+is%3Aissue+label%3A%22Good+First+Issue%22). Thanks again, and let us know what you think!
