### ISSUE TITLE
My Site Dashboard: "If you want to try get more views..." prompt overflows container in landscape mode

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#18286]
### Expected behavior

A new "if you want to try get more views..." prompt displays within the new My Site dashboard on sites with no recent views or visitors. It's expected that the prompt's text should stay within its white container, which it does within portrait mode.

### Actual behavior

The text overflows its container in landscape mode:

![IMG_AED77EA28F09-1](https://user-images.githubusercontent.com/2998162/161775535-1dfc12f0-22b9-4b39-89ef-bd8a2de8637e.jpeg)

### Steps to reproduce the behavior

1. Navigate to a WordPress.com site with no recent views or visitors.
2. Notice the new "if you want to try get more views..." prompt.
3. Switch the device to landscape mode and observe how the prompt overflows its container.

##### Tested on iPhone XR, iOS 15.3, WPiOS 19.6 beta

**Comment by leandroalonso** [comment]
Edit: I was able to reproduce that just by going to landscape and then back to portrait.

@SiobhyB I also noticed in another screenshot you shared that this content is wrong even while on portrait:

<img src="https://user-images.githubusercontent.com/7040243/161819155-fe039101-bfe9-44be-81b6-328aad4766d8.png" width="300">

Is this also on iPhone XR? Do you see that often?

**Comment by SiobhyB** [comment]
@leandroalonso, it looks like you discovered this already, but to confirm: that portrait issue happens when returning to portrait mode from landscape. That's the only time I'm able to see the issue while in portrait mode.

**Comment by leandroalonso** [comment]
Additional info from https://github.com/wordpress-mobile/WordPress-iOS/issues/18291:

The "top tips" is not tappable in landscape or rotated portrait (when it's not inside the card). (thanks @ScoutHarris)
