### ISSUE TITLE
My Site Dashboard: The dashboard is inaccesible when the window is compact.

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#18288]
### Expected behavior

The dashboard should always be available on iPads even when the app window is compact

### Actual behavior
When switching from a regular to a compact window by adding another window of a different app, the Home cell in the My Site menu disappears and the segmented control is not displayed as well. So there is no way to reach the dashboard in this case. 

https://user-images.githubusercontent.com/25306722/161796026-4075c46f-690f-4b4e-9a4b-40b31b1101ac.mov

### Steps to reproduce the behavior
1. Run the app on an iPad
2. Add another window of any other app. You should have WordPress and another app running side by side.
3. Observe that the Home cell disappears, and the segmented control is also not there.

**Comment by dvdchr** [comment]
👋 ! Seeing that this is labeled `iPad`, I wanted to add that this could also be reproduced in large iPhone models. More context: `p1649184912416589-slack-C011BKNU1V5`. 🙂

**Comment by momo-ozawa** [comment]
@dvdchr 👋 
Thanks for raising this! I created a fix for this: #18315
