### ISSUE TITLE
My Site Dashboard > Today's Stats: card is not resized correctly on rotation

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#18291]
### Expected behavior
The card should be resized so the text is rendered correctly.

### Actual behavior
On rotation, the card is not resized correctly. Also, the `top tips` link is not tappable in landscape or rotated portrait (when it's not inside the card).

### Steps to reproduce the behavior
- On an iPhone plus, start in portrait mode. The card renders fine.
- Rotate to landscape. Note the bottom text overflows outside the card.
- Rotate back to portrait. The card isn't quite tall enough - the bottom text is right at the card bottom.

| Original Portrait | Landscape | Rotated Portrait |
|--------|-------|-------|
| <img width="404" alt="original_port" src="https://user-images.githubusercontent.com/1816888/161836230-89d5746e-35dc-4bb1-ba42-e70a9673e8d7.png"> | <img width="304" alt="landscape" src="https://user-images.githubusercontent.com/1816888/161836243-9e800228-d614-4391-9603-3e3fa6840f8a.png"> | <img width="408" alt="post_port" src="https://user-images.githubusercontent.com/1816888/161836239-e13a9ab4-015e-4b26-a35c-64727f2876e4.png"> |

**Comment by ScoutHarris** [comment]
cc @leandroalonso

**Comment by leandroalonso** [comment]
Thanks for reporting that, @ScoutHarris! This is being tracked on #18286 but we weren't aware of it not being tappable, I'll add that info there!

**Comment by ScoutHarris** [comment]
Bah I looked but I missed that open one. Sorry!
