### ISSUE TITLE
Quick Start: Some steps are unachievable for certain user roles

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#18292]
### Expected behavior

When going through the Quick Start list, I'd expect to only see prompts that I'm able to complete.

### Actual behavior

The same prompts are displayed regardless of the capabilities associated with your user role e.g. a contributor sees the prompts to upload a site icon and edit the site title, even though they're not able to complete those steps.

Related discussion: p5T066-37N-p2#comment-11859 

### Steps to reproduce the behavior

* _Pre-requisite: A contributor account on a self-hosted site (not connected via Jetpack)._
* Navigate to _My Site_ within the app and tap the _+_ icon from the dropdown menu to add a new site.
* Follow the prompts to add a self-hosted site and log into your contributor account.
* While logged into the contributor account, observe the Quick Start checklist in the _My Site_ area. Attempt to complete some of the steps that are not achievable for the contributor role, such as uploading a site icon.

This is similar to these issues, in which certain site or user capabilities aren't taken into account as part of the Quick Start flow:

* https://github.com/wordpress-mobile/WordPress-iOS/issues/18066
* https://github.com/wordpress-mobile/WordPress-iOS/issues/15294

##### Tested on iPhone XR, iOS 15.3, WPiOS 19.6 beta

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
