### ISSUE TITLE
[Site name] Remove the domain screen from the flow

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#18324]
## Description
When the [Site Name screen is shown](https://github.com/wordpress-mobile/WordPress-iOS/issues/18273) for the [experiment treatment variation](https://github.com/wordpress-mobile/WordPress-iOS/issues/18272) the **site domain screen should be removed** from the site creation flow.

![site-name-short](https://user-images.githubusercontent.com/304044/162406062-dead38bf-d2c0-4b97-a335-90fada5d2150.png)

This modification adds two new use cases in the `sites/new` API call.
The domain of the site is generated with the following logic:
1. If the [siteName] is provided it is used as a domain (current behavior)
2. If the [siteName] is not provided the [siteTitle] is passed and the API generates the domain from it
3. If neither the [siteName] or the [siteTitle] is passed the [username] is used by the API to generate a domain

Note: The [siteTitle] can be used only if it contains latin alphanumeric characters (regex: `"[^a-zA-Z0-9]"`)

In the cases 2 and 3 two extra parameters are passed:
- `site_creation_flow` with value `with-design-picker`
- `find_available_url` with value `1`

Internal ref `pbArwn-49A-p2#comment-5390`

_Note: All development should be behind the [feature flag `SITE_NAME `](https://github.com/wordpress-mobile/WordPress-iOS/issues/18271)

**Comment by Gio2018** [comment]
### Note ###
The domain screen has already been removed in this [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/18298). The rest of the work will be to make the flow work without the domain suggestion

**Comment by antonis** [comment]
@Gio2018 I've added a note above on when we can use the site title
`Note: The [siteTitle] can be used only if it contains latin alphanumeric characters (regex: "[^a-zA-Z0-9]")`
If this is not the case we should fallback to the username since the site title will result in an error
