### ISSUE TITLE
[Site name] Add tracks events

### ISSUE THREAD

**Issue by mkevins** [wordpress-mobile/WordPress-iOS#18337]
We should emit the following tracks events:

* `enhanced_site_creation_site_name_viewed`: when the Site Name screen is shown
* `enhanced_site_creation_site_name_canceled`: when the Back button is pressed
* `enhanced_site_creation_site_name_skipped`: when the Skip button is pressed
* `enhanced_site_creation_site_name_entered`: when the Continue button is pressed (or enter button pressed) with a site name entered

We should also include:
* `enhanced_site_creation_site_name_experiment`: at the start of the site creation flow, passing the variation as a parameter.

**Comment by twstokes** [comment]
Should we also include `enhanced_site_creation_site_name_experiment`?

**Comment by mkevins** [comment]
Good idea, I've updated the description :+1:
