### ISSUE TITLE
My Site Dashboard: delay before opening the editor when tapping the next post prompt

### ISSUE THREAD

**Issue by leandroalonso** [wordpress-mobile/WordPress-iOS#18331]
### Expected behavior

The editor should open right away.

### Actual behavior

It takes about a second for the editor to open. Compared to the FAB, it seems slower.

### Steps to reproduce the behavior

1. Open the app
1. Open a site with no drafts and scheduled
1. Tap the card
1. Notice how there's a delay before the editor opens
1. Subsequent taps open right away

Tested on simulator and iPhone 13 Pro.

**Comment by momo-ozawa** [comment]
Closed via #18332
