### ISSUE TITLE
[Site Name] Use the site vertical from the intent screen in the header

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#18361]
## Description
The selected site intent/vertical should be used in the header of the site name screen

### Expected Design
![ios](https://user-images.githubusercontent.com/304044/161550962-583f9050-56c5-44a5-a22d-f130c71ada13.png)

_Note: All development should be behind [the feature flag `SITE_NAME `](https://github.com/wordpress-mobile/WordPress-iOS/issues/18271)_

**Comment by twstokes** [comment]
This was resolved in #18335. 👍
