### ISSUE TITLE
Jetpack for iOS: Backup and Scan Messaging for VaultPress Users

### ISSUE THREAD

**Issue by JenSwish** [wordpress-mobile/WordPress-iOS#18364]
### Expected behavior

Messaging about backup and security scans for users with VaultPress backups and scans should indicate one of the following: 

- Their backups and/or scans are not performed by Jetpack, and they should visit VaultPress.com instead
- The actual status of their backups and/or scans

### Actual behavior

User received messaging in app that their scan failed to run.

### Steps to reproduce the behavior

Reported in #4941446-zen. Have responded to user asking for screenshots if possible.

**Comment by purplepioneer** [comment]
The customer has sent us two screenshots of the error messages they received. They're from Jetpack scan.

I've attached them to this message
![Screenshot 2022-04-13 at 22 41 10](https://user-images.githubusercontent.com/82608846/163278376-be8c6dbf-042a-4223-8c71-9d1eb4b9b303.png)
<img width="414" alt="PNG image 2" src="https://user-images.githubusercontent.com/82608846/163278423-5d71b937-37b8-45b7-a6fe-0c9e3a72a2dd.png">

**Comment by foleynotrose** [comment]
Similar issue reported here: https://github.com/wordpress-mobile/WordPress-iOS/issues/17146

**Comment by leandroalonso** [comment]
@foleynotrose I'll close this issue to keep everything on #17146!
