### ISSUE TITLE
[Quick Start] Notification should dismiss when presenting Site Picker

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#18404]
### Expected behavior
Notification is dismissed when the Site Picker is presented.

### Actual behavior
Notification persists.

### Steps to reproduce the behavior
1. Create a new site and select "Show me around" upon creation to enable Quick Start
2. Tap "Customize Your Site" under "Next Steps" and select a Quick Start item (e.g. Check your site title)
3. Observe the notification "Select [current title] to set a new title."
4. Open the Site Picker by pressing the chevron at the top right
5. Observe that the notification isn't dismissed

https://user-images.githubusercontent.com/2092798/164117641-bb127660-d5ab-4225-954b-b6b54b005bcb.mov

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
