### ISSUE TITLE
Quick Start: Menu rows are resized when navigating back to Menu tab during Quick Start tasks.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#18420]
### Expected behavior
Menu rows should not be resized while navigating back to the Menu tab during QS tasks.

### Actual behavior
While following QS tasks the Menu rows seem to be resized when coming back to Menu tab. The issue is more evident for bigger font sizes.

### Steps to reproduce the behavior
1. Run `Customize Your Site` > `Edit your homepage` task.
2. Follow the focus point and navigate to `Pages`.
3. Go back to `My Site`.
4. Notice that the Menu rows are resized.

https://user-images.githubusercontent.com/42008628/164558936-5862c393-b7f9-4133-bd92-fafdf85d9dee.mov

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
