### ISSUE TITLE
Bug: Screen title does not change size with iPhone settings

### ISSUE THREAD

**Issue by lmischner** [wordpress-mobile/WordPress-iOS#18442]
When I change the default text size of a device, I expect the screen titles across the WordPress app to adjust size. (This occurs in other apps.)

The size of the screen title does not change with the phone settings. 

Steps to reproduce:
1. Open WordPress app without adjusting accessibility settings. 
2. On My Site screen (or your favorite one), scroll so you see the screen title.
3. In Settings > Accessibility > Display & Text size > Larger Text, adjust the text size to be large enough that the screen title of the settings page changes.
4. Return to the WordPress app.
5. Note that the screen title is the same size as in step 2.

Tested on iPhone XS, iOS 15.4.1, WPiOS 19.7.01

**Comment by christianbilodeau** [comment]
Created a PR for this issue [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/23640)
