### ISSUE TITLE
Login: "not a WordPress site" error sometimes displays incorrectly

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#18497]
### Expected behavior

If I enter the URL for a WordPress site that blocks the app's requests for any reason, I expect to receive a helpful error message that informs me why I'm not able to log into that site via the app.

### Actual behavior

Recent app reviews at pbArwn-4xZ-p2 clued us into the fact that there are some scenarios in which the following error displays when users attempt to log into self-hosted WordPress sites: 

"Couldn't connect to the WordPress site. There is no valid WordPress site at this address. Check the site address (URL) you entered."

For example, the user in 5170539-zd-woothemes was seeing the above error even though there site is using WordPress, but was blocked due to an inability to connect via cURL.

Screenshot:

<img src="https://user-images.githubusercontent.com/2998162/166473723-1e76884d-97bf-48f0-a052-4aba95344185.jpeg" width="50%" />

Previous related issues: 

* https://github.com/wordpress-mobile/WordPress-iOS/issues/10293
* https://github.com/wordpress-mobile/WordPress-Android/issues/12401
* Android version: https://github.com/wordpress-mobile/WordPress-Android/issues/16467

### Steps to reproduce the behavior

A URL for testing can be found at pbArwn-4xZ-p2#comment-5712 and/or 5170539-zd-woothemes (not included in this ticket to protect user privacy):

1. Navigate to the app's login screen and select the "Log in by entering site address" option.
2. Submit the test URL.

Note, more work needs to be done to identify the exact issues a site must have to reproduce this error, as disabling XML-RPC isn't enough to reproduce.

**Comment by staskus** [comment]
### Issue

The self-hosted login flow in `SiteAddressViewController` goes through these steps:

1. `checkSiteExistence`
2. `guessXMLRPCURL`
3. `fetchSiteInfo` (`connect/site-info`)
4.  .. present username password form

Connecting with the given site fails at `guessXMLRPCURL` step, failing multiple checks within `WordPressOrgXMLRPCValidator`. 

```swift
23:31:16:255 The operation couldn’t be completed. (WordPressKit.WordPressOrgXMLRPCValidatorError error 406.)
23:31:16:255 Assume the given url is the home page and XML-RPC sits at /xmlrpc.php
23:31:16:392 The operation couldn’t be completed. (WordPressKit.WordPressOrgXMLRPCValidatorError error 403.)
23:31:16:392 Try the original given url as an XML-RPC endpoint: http://*.com
23:31:16:997 There was a problem communicating with the site. The serialisation of the response failed.
23:31:16:998 Fetch the original url and look for the RSD link by using RegExp
23:31:17:605 The operation couldn’t be completed. (WordPressKit.WordPressOrgXMLRPCValidatorError error 406.)
23:31:17:609 Error on trying to guess XMLRPC site: WordPressKit.WordPressOrgXMLRPCValidatorError(rawValue: 406)
23:31:17:610 Error attempting to connect to site address: https://*.com
```

The concrete error is failing to extract [RSD URL](https://en.wikipedia.org/wiki/Really_Simple_Discovery#:~:text=Really%20Simple%20Discovery%20(RSD)%20is,%2C%20password%2C%20and%20homepage%20URL.) from HTML. 

```swift
guard let data = data,
      let responseString = String(data: data, encoding: String.Encoding.utf8),
      let rsdURL = self.extractRSDURLFromHTML(responseString)
else {
        failure(WordPressOrgXMLRPCValidatorError.invalid as NSError)
    return
}
```

### Our options

- As mentioned in the description, one of the options is to look for more indications that would allow us to identify concrete XML-RPC issues with the site, making further additions to `WordPressOrgXMLRPCValidator`. Similar to what was done most recently in https://github.com/wordpress-mobile/WordPress-iOS/pull/17724.

- A second option is to tackle the problem of us displaying a misleading  “There’s no valid WordPress site at this address” error for a site that is actually a valid WordPress site. If we call `fetchSiteInfo` (`connect/site-info`) on this particular site, we do get a response from a backend that this is indeed a WordPress site. With this option, we could at least indicate to users that this may be an XML-RPC issue and they should contact their host. Such an option was also suggested previously as a possible failback https://github.com/wordpress-mobile/WordPress-iOS/issues/10293#issuecomment-431916333 

Ideally, I think it's worth trying to implement both options. The first one to cover the concrete case this user is experiencing. But especially the second one to avoid misleading users with "not a WordPress site" messaging if any other unexpected connection issues happen.
