### ISSUE TITLE
My Site Dashboard: Views dismissed when entering landscape

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#18540]
Ref: p5T066-3cf-p2#comment-12283

### Expected behavior

When viewing a screen from the my site home dashboard and then switching to landscape, it should maintain the current view in a split screen.

### Actual behavior

The screen gets dismissed and the home dashboard is shown.

### Steps to reproduce the behavior

- Keep phone in portrait
- Log in
- Open a site
- Navigate to the 'My Site' tab home area
- Tap on either Pages, Posts, Media, or Stats
- Rotate phone to landscape

### Current behavior

https://user-images.githubusercontent.com/2454408/167446040-9aca0926-7ed4-4927-b229-ad3b8e9ef898.mp4

### Previous behavior

https://user-images.githubusercontent.com/2454408/167445970-3bb23403-e562-48da-acd8-705afb904bbc.mp4

**Comment by kean** [comment]
This menu was removed in one of the 23.x release and the issue is now obsolete.
