### ISSUE TITLE
Quick Start: Site list is displayed and the selection ignored after adding a self-hosted site.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#18546]
### Expected behavior
I would expect to land on MySite after logging into a self-hosted site and dismissing Quick Start prompt.

### Actual behavior
After logging into a self-hosted site and dismissing Quick Start prompt the user sees the site list and regardless of what site they choose the recently added self-hosted site will be displayed in MySite.

https://user-images.githubusercontent.com/42008628/167513752-6ad6f3bb-86dd-44f9-9aab-d475359980c7.MP4

### Steps to reproduce the behavior
1. Tap on site picker.
2. Add a self-hosted site.
3. Tap `No thanks` in Quick Start prompt.
4. ❌ Notice the site list is displayed and whatever site you choose will be ignored.

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
