### ISSUE TITLE
Quick Start: Quick Start is broken for self-hosted sites

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#18547]
### Expected behavior
~Quick Start should be functional and users should be able to complete the tours for self-hosted sites.~

Quick Start (and the prompt) shouldn't be displayed for self-hosted sites.

### Actual behavior
Quick Start is broken for self-hosted sites. Only the first tour is fully functional. 

https://user-images.githubusercontent.com/42008628/167513100-39c4def6-54a1-41b9-b86e-54afcb450c88.mov

### Steps to reproduce the behavior
1. Add a self-hosted site.
2. Tap `Show me around` on Quick Start prompt.
3. Try to complete the tours.
4. ✅ Notice that the first tour works as expected.
5. ❌ Notice that the second tour is completed even though it's not possible to change the site's icon.
6. ❌ Notice that some of the next blue dots are not displayed.
7. ❌ Notice that tours like `Social sharing` are impossible to complete.

**Comment by leandroalonso** [comment]
I compared that to Android and the behavior there is to not show Quick Start for self-hosted sites. The same should apply to WPiOS.

I updated the expected behavior to reflect that.

**Comment by hassaanelgarem** [comment]
@momo-ozawa After fixing this we can close #18458 as well 👍
