### ISSUE TITLE
Self-hosted site login username field should not have a visibility toggle

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#18573]
### Expected behavior

When logging in to a self-hosted site, the app should give the user the option to "show" the password as its being typed in. What's typed into the username field should always be visible.

### Actual behavior

When logging in to a self-hosted site, if I toggle the visibility of the password field, the username field can also become hidden (and erroneously shows an "eye" button to toggle the visibility of the field).

### Steps to reproduce the behavior

1. Type in a self-hosted site address
2. On the screen that asks for a username and password, type in incorrect values
3. Tap Continue
4. Notice that the username field now shows a visibility toggle ("eye" icon)

|  |
| - |
| <img src="https://user-images.githubusercontent.com/1898325/167944093-d019cf65-94eb-43be-a1c0-3faf69661f5d.jpeg" alt="" width="350">  |

**Comment by twstokes** [comment]
Related: https://github.com/wordpress-mobile/WordPress-iOS/issues/19031

**Comment by guarani** [comment]
👋 @twstokes, I don't see any differences between these two issues. Would you agree?

**Comment by twstokes** [comment]
> 👋 @twstokes, I don't see any differences between these two issues. Would you agree?

👋 @guarani - yep, upon closer reading I agree that my newer issue can be closed. Thanks!

**Comment by twstokes** [comment]
👋 @guarani - can you reproduce this anymore? If not, this may be resolved.

Below are comparisons of `20.3` and `trunk`:

| 20.3 | Trunk |
| - | - |
| <video src="https://user-images.githubusercontent.com/2092798/188669800-1383735a-bbdf-4cc1-9c63-80f4ca8bc4c3.mp4" /> | <video src="https://user-images.githubusercontent.com/2092798/188669843-617f526b-768e-4bd9-88e5-d48431dd9d42.mp4" /> |

**Comment by guarani** [comment]
Thanks for checking, I agree it's no longer reproducible. I couldn't reproduce on 20.6 by following the above steps to reproduce.

I'm closing this now but please re-open it if you disagree.
