### ISSUE TITLE
Web Stats fails to authenticate after sign out

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#1857]
Looking at the `authStats` method:

```obj-c
    // Skip the auth call to reduce loadtime if its the same username as before.
    NSString *lastAuthedUsername = [[self class] lastAuthedName];
    if ([username isEqualToString:lastAuthedUsername]) {
        authed = YES;
        [self loadStats];
        return;
    }
```

Checking for auth makes sense so we don't login on every request, but the current check doesn't actually check for a valid cookie. How to break it:

- Sign in with a WordPress.com account
- View stats (this sets `_lastAuthedName`)
- Sign out
- Sign in with the same username

`authStats` will see `_lastAuthedName` matches the current username and won't bother authenticating, even though the auth cookies have been deleted

**Comment by astralbodies** [comment]
I don't think this is an issue any more, can you verify @koke?
