### ISSUE TITLE
Quick Start: Site url waypoint cut off on iPads 

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#18585]
### Expected behavior
Waypoint to not be cut off. It should be displayed the same way it's displayed on iPhones.

<img src="https://user-images.githubusercontent.com/25306722/168087823-eaf665bd-55be-45ec-b378-4a7793f2a000.png" width=50%>

### Actual behavior
Waypoint is cut off.

<img src="https://user-images.githubusercontent.com/25306722/168088165-cfe0acaa-2a3f-4691-a019-7a8d927ad24a.png" width=50%>

### Steps to reproduce the behavior

1. Install the app on an iPad
2. Enable quick start
3. Start the Preview Your Site tour
4. Notice that the waypoint is not correctly displayed.

**Comment by momo-ozawa** [comment]
Closed via #18619
