### ISSUE TITLE
[iOS] Stats:  Top Followers Card

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#18602]
The top followers card requires some tweaks for the revamp:

* Different tab style at the top
* Remove Follower count
* Remove Follower and Since headings
* Add 'follow' button to right hand side. Follow user when tapped.

| Before | After |
|---|---|
| ![IMG_CB70AEBE8555-1](https://user-images.githubusercontent.com/4780/168259228-633615e7-9799-4043-97ff-83f0dd7d68f0.png) | <img alt="Screenshot 2022-05-13 at 10 46 40" src="https://user-images.githubusercontent.com/4780/168258284-dd5fcb69-e04b-463f-8286-fa6ccffe69b8.png"> |

**Comment by staskus** [comment]
Not relevant anymore. Updates to Followers (Subscribers) will be addressed in a separate dedicated project.
