### ISSUE TITLE
My Site Dashboard: Hide Quick Actions on primary vc if dashboard is enabled

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#18618]
## Description

![IMG_6D7B2DD59D44-1](https://user-images.githubusercontent.com/6711616/168560283-3ba29cd0-65c4-4558-97ff-e0f3da9ee637.jpeg)

On iPad, hide the Quick Actions in the left panel of the split vc if the dashboard is enabled -- having Quick Actions on both the site menu and the Dashboard detail vc is redundant.

Ref: p1652351612610399-slack-C0290FLA0RM

**Comment by kean** [comment]
Closing as it is no longer relevant as this navigation was entirely replaced.
