### ISSUE TITLE
[iOS] Stats: Feature Announcement

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#18624]
We need to announce the new stats revamp changes when they're complete. We should use the new Feature Announcement functionality to do so: https://github.com/wordpress-mobile/WordPress-iOS/issues/18176

<img width="455" alt="Screenshot 2022-05-16 at 17 09 27" src="https://user-images.githubusercontent.com/4780/168636742-556c73f9-ca26-4c5b-a3e7-d8d9ce8aad23.png">

This should be displayed on app launch the first time the user runs the app after updating to a version that contains the new Insights features.

**Comment by guarani** [comment]
I've implemented the UI and it's looking close to what's shown in the above design.

#### Open questions
1. The "Try it now" and "Remind me" buttons are used on Blogging Prompts, but they don't seem applicable here. Would a single button that can take users to the Stats screen work instead? The user can always dismiss the screen by swiping down or tapping the close "x" button.
2. I'm not sure I understand the "You can find out how you are doing with guidance on the next steps." message. Is it referring to guides and action cards?
3. The preview graphic shown in the design above doesn't match the one I found on the Figma page "⭐️Ready - v2 scope - iOS & Android", so I'm using the one currently shown in Figma which I think is newer.
4. Is the feature announcement screen suitable for this project given that Stats is an existing feature (first raised by @ravishanker last week)?

#### Next steps for me on the implementation
- [ ] Make the background color of the preview graphic match the design (it uses a light blue)
- [ ] Make the action button take the user to the Stats Insights screen
- [ ] Get guidance from the team who implemented the feature introduction screen for Blogging Prompts it should be shown (e.g. once per device per feature): [asked on Slack](p1653513035610779-slack-C0339PBMQ92)

**Comment by frosty** [comment]
The "Try it now" and "Remind me" buttons are used on Blogging Prompts, but they don't seem applicable here. Would a single button that can take users to the Stats screen work instead? The user can always dismiss the screen by swiping down or tapping the close "x" button.
I'm not sure I understand the "You can find out how you are doing with guidance on the next steps." message. Is it referring to guides and action cards?
The preview graphic shown in the design above doesn't match the one I found on the Figma page "⭐️Ready - v2 scope - iOS & Android", so I'm using the one currently shown in Figma which I think is newer.
Is the feature announcement screen suitable for this project given that Stats is an existing feature (first raised by @ravishanker last week)?

**Comment by frosty** [comment]
Thanks! Here's my attempt at answering some of those questions:

> The "Try it now" and "Remind me" buttons are used on Blogging Prompts, but they don't seem applicable here. Would a single button that can take users to the Stats screen work instead? The user can always dismiss the screen by swiping down or tapping the close "x" button.

I think "Try it now" could still work in this regard as it could take you to the Insights area to check out the new features. I agree, perhaps just a single button is needed here.

> I'm not sure I understand the "You can find out how you are doing with guidance on the next steps." message. Is it referring to guides and action cards?

I think it might be, but to be honest I think we need some editorial work on all the text on this screen (title and both paragraphs) as it's not super clear.

> The preview graphic shown in the design above doesn't match the one I found on the Figma page "⭐️Ready - v2 scope - iOS & Android", so I'm using the one currently shown in Figma which I think is newer.

Makes sense, let's use whatever's newest.

> Is the feature announcement screen suitable for this project given that Stats is an existing feature (first raised by @ravishanker last week)?

I think so, because it's a new take on the existing feature. It looks quite different to the old version. And this one screen doesn't feel too disruptive to me.

**Comment by guarani** [comment]
Thanks @frosty!

I've submitted a PR for the UI, not the functionality. The next steps would be handled in a separate PR and will include:
- [x] Making the action button take the user to the Stats Insights screen
- [x] Figuring out when to show this announcement and how to ensure it doesn't conflict with other feature announcements the app may show in the same release
- [x] Implement the logic to show the announcement
- [x] Copy review of the text shown on the screen

**Comment by frosty** [comment]
Implemented by #18943.
