### ISSUE TITLE
Posts List: Users can access deleted posts right after deleting them

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#18637]
### Expected behavior
Deleted posts to not be accessible for editing once deleted.

### Actual behavior
During a brief window, deleted posts can be accessed and edited.

#### Dashboard

1. Make sure to test with a slow connection
2. Open a site with draft posts
3. Open the posts list view
4. Trash a draft post
5. Go back to the dashboard
6. Tap on the just deleted post
7. Notice that you can edit this post

#### Posts List View

1. Make sure to test with a slow connection
2. Open a site with draft posts
3. Open the posts list view
4. Trash a draft post
5. Dismiss the posts list
6. Open the posts list again (drafts)
7. Tap on the just deleted post
8. Notice that you can edit this post

**Comment by hassaanelgarem** [comment]
Related PR: #18390

**Comment by kean** [comment]
Fixed in 23.9.
