### ISSUE TITLE
Quick Start: Notifications focus point is misplaced for RTL languages

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#18641]
### Expected behavior
All Quick Start focus point should be perfectly placed for RTL languages.

### Actual behavior
Notifications focus point appears over My Site icon for RTL languages.

<img width="300" src="https://user-images.githubusercontent.com/42008628/168902943-71609398-c953-4b70-9c0b-a1c2f60e89e9.png">

### Steps to reproduce the behavior
1. Device with RTL language.
2. Login with an account with an existing site.
3. 'Show me around'.
4. Select the Notifications flow.
5. ❌ Note that the focus point is over `My Site` instead of `Notifications` icon

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
