### ISSUE TITLE
Quick Start: Stats focus point gets hidden after rotating the device from Landscape to Portrait

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#18644]
### Expected behavior
Focus point should always be visible after rotating the phone. I would expect the Stats element to be brought into view after rotating the phone.

### Actual behavior
Stats focus point gets hidden after rotating the device from Landscape to Portrait.

https://user-images.githubusercontent.com/42008628/168914110-30d6d264-6d2b-4178-b45a-c6bef403f243.mov

### Steps to reproduce the behavior

1. Me > App Settings > Initial Screen -> `Home`
2. Device in Landscape
3. Start the `Check your site stats` flow
4. ✅ Stats focus point is displayed properly
5. Rotate the device to Portrait
6. ❌ Stats focus point is hidden
7. Start the `Check your site stats` flow
8. ✅ Stats focus point is displayed properly

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
