### ISSUE TITLE
[Site Design Revamp] Main view UI tweaks

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#18677]
### Tweak 1
Tighten up the space above and below the view's title to better match the designs.

| Designs | Current |
| - | - |
| <img src="https://user-images.githubusercontent.com/2092798/169435921-485071c5-87b4-4372-b1f3-8ea696926036.png" width="350px" /> | <img src="https://user-images.githubusercontent.com/2092798/169435982-ecb2dbc1-6a22-4160-9097-b15be6f89c72.png" width="350px" /> |

### Tweak 2
[Per this comment](https://github.com/wordpress-mobile/WordPress-iOS/pull/18710#issuecomment-1136602070), consider adding some margin beneath the recommended section caption.

<img src="https://user-images.githubusercontent.com/2092798/170161107-e7688208-bacd-4ad6-a357-1a0934cb189f.png" width="350px" />

### Tweak 3

Remove the thumbnail selection border when a preview is being dismissed.

### Tweak 4

Match the top bar and background colors.

PRs should target the `feature/site-design-revamp` feature branch.

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/18754, https://github.com/wordpress-mobile/WordPress-iOS/pull/18787 and https://github.com/wordpress-mobile/WordPress-iOS/pull/18789 🎉
