### ISSUE TITLE
[Site Design Revamp] Large gap at end of table and header is stuck in collapsed state

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#18678]
## Description

Sometimes a large gap appears at the bottom of the site designs view and the header gets stuck in a "collapsed" state. This can possibly be reproduced by navigating back and forth from the Site Intent view, or switching screen orientations.

The fix will most likely involve overriding the [`estimatedContentSize`](https://github.com/wordpress-mobile/WordPress-iOS/blob/28f368208d9fc8afd201de86da12a730b056c2f4/WordPress/Classes/ViewRelated/Gutenberg/Collapsable%20Header/CollapsableHeaderViewController.swift#L248) method of its superclass.

PRs should target the `feature/site-design-revamp` feature branch.

**Comment by Gio2018** [comment]
This was fixed in #18656
