### ISSUE TITLE
[Site Design Revamp] Add caption above recommended section label

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#18674]
## Description

Add the caption "PICKED FOR YOU" above the recommended section label.

**Attributes:**
- 13pt
- All caps
- Light gray

<img src="https://user-images.githubusercontent.com/2092798/169432275-cbabe360-532d-4047-afc8-ea80889c5674.png" width="350px" />

PRs should target the `feature/site-design-revamp` feature branch.

**Comment by twstokes** [comment]
Per @kyleaparker, this should match the typography used on the My Site view:

<img src="https://user-images.githubusercontent.com/2092798/171249485-0079dbab-b74a-449f-bf89-6e9778c69b5f.png" width="350px" />

Inspecting `BlogDetailsSectionHeaderView` shows that this is the "Footnote" size:

<img width="864" alt="image" src="https://user-images.githubusercontent.com/2092798/171252059-3899d1bc-ee19-4780-8a5c-674bbbc1e2aa.png">

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/18786
