### ISSUE TITLE
Jetpack , probleme

### ISSUE THREAD

**Issue by Aucoeurdelaruche** [wordpress-mobile/WordPress-iOS#18718]
WordPress.com no longer recognizes my Jetpack site either nothing works I can't connect to the mobile woocommerce application I tried everything but nothing works how to do it please

##### Tested on [mobile ans destock , iOS [15.4.1],

**Comment by Aucoeurdelaruche** [comment]
I dont understand

**Comment by twstokes** [comment]
👋 Hi @Aucoeurdelaruche - sorry to hear you're having trouble with your site. Please reach out to support [from within the app](https://apps.wordpress.com/support/mobile/my-account/where-should-i-go-for-support/) or by emailing mobile-support@automattic.com to get assistance. There are also resources on the [WordPress.com Mobile App Support](https://apps.wordpress.com/support/mobile/) page in case that's helpful.

Thank you!
