### ISSUE TITLE
[Site Design Revamp] Recommended designs testing

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#18736]
_This issue is only for tracking tests and can be closed once they are completed._

Now that the [ability to fetch beta designs](https://github.com/wordpress-mobile/WordPress-iOS/pull/18683) from the API endpoint has been integrated, we can test recommend designs on the Site Design picker.

**Prerequisites:**
- Run these test from `feature/site-design-revamp`
- Enable beta designs by toggling on the "Fetch Beta Site Designs" feature flag

### Selecting a vertical with recommended designs

1. Start the Site Creation flow
2. Tap the first default vertical (e.g. Food)
3. Expect that that "Best for Food" is shown as the recommended category with enlarged designs
4. Expect the recommend designs to change depending on the vertical chosen
5. Repeat steps 1-3 for each of the six default verticals with step three showing "Best for [vertical name]"

### Fallback category is used when a vertical doesn't match

1. Start the Site Creation flow
2. Tap "Skip" or select a vertical that is **not** one of the initially shown six defaults (such as Automotive)
3. Expect that "Best for Blogging" is shown as the recommended category with enlarged designs
4. Expect that no "Blog" category is shown in the list of categories

_Note:_ The UI has been updated since these screenshots but the functionality should be the same.
| No matching vertical chosen | Food vertical chosen |
| - | - |
| <img src="https://user-images.githubusercontent.com/2092798/169392798-f8a04bc0-190c-4629-9582-e8db6e8881a4.PNG" width="300px" /> | <img src="https://user-images.githubusercontent.com/2092798/169393036-1ebdb83f-a58d-4ad3-a6b0-ad0519aa0c54.PNG" width="300px" /> |

**Comment by Gio2018** [comment]
Tested and everything worked!
