### ISSUE TITLE
Quick Start: Notices sometimes have full width on large devices

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#18757]
### Expected behavior
Notices to always have 50% width on large devices.

### Actual behavior
Notices only have 50% width when the device gets rotated.

<img src="https://user-images.githubusercontent.com/25306722/170611823-2115c5b8-a4fb-41a2-bb09-2ca33986a30f.png" width=50%>

### Steps to reproduce the behavior

1. Test on a large device (13 Pro Max)
2. Enable quick start for existing sites
3. Put the device in landscape mode
4. Start notifications task
5. Notice that the notice fills the width of the whole screen
6. Rotate the device to portrait then back to landscape
7. Notice that the notice now correctly fills 50% of the screen

**Comment by momo-ozawa** [comment]
Closed via https://github.com/wordpress-mobile/WordPress-iOS/pull/18758
