### ISSUE TITLE
Block Editor: Editor becomes out of control and crashes after double tapping the space between the last block and editor toolbar

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#18783]
### Expected behavior
No crashes are seen.

### Actual behavior
Editor becomes out of control and crashes after double tapping the space between the last block and editor toolbar.

### Steps to reproduce the behavior
I've been able to consistently reproduce it by editing a published post, but I'm not sure it's the only way.
1. Edit a published post with several blocks
2. Scroll to the last block
3. Double tap the space between the last block and the editor toolbar
4. ❌  Notice that the page will scroll up and down and the keyboard will be expanded and dismissed in loop
5. ❌  The only way to stop the issue is to leave the post by closing the editor and discarding the changes but it won't be easy to hit the Discard button.

https://user-images.githubusercontent.com/42008628/171218070-e7281053-c653-429b-b87b-a6a06f19e77c.mov

**Comment by geriux** [comment]
Just did a quick check to see if it's a new regression from the Drag & drop blocks feature but this is present in older versions, I tried WordPress `19.3` and I can reproduce this bug. So we need to keep investigating to see why this is happening. Thanks for catching this bug!

**Comment by dcalhoun** [comment]
For context, this may relate to/duplicate the following issues: 

* https://github.com/wordpress-mobile/gutenberg-mobile/issues/953
* https://github.com/wordpress-mobile/gutenberg-mobile/issues/1696
* https://github.com/WordPress/gutenberg/issues/30562
