### ISSUE TITLE
[Site Design Revamp] Reset the scroll position of the designs when loading the Site Design picker

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#18794]
## Description

When a user navigates to the Site Design picker screen (whether forwards or backwards in navigation), we should reset the scroll position to the top.

### Current behavior:

<video src="https://user-images.githubusercontent.com/2092798/171281124-4a8786c9-5c3e-4498-b6ed-2d744c13c330.mp4" />

**Comment by antonis** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/18795
