### ISSUE TITLE
Quick Start: Stats button and focus point are scrolled out of screen for RTL languages

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#18798]
### Expected behavior
Stats button and focus point should be displayed in `Check your site stats` tour.

### Actual behavior
Stats button and focus point are scrolled out of screen for RTL languages.

### Steps to reproduce the behavior
1. Set the language to a RTL language (eg. Arabic)
2. Login and select an existing site.
3. Start `Get to know your app` > `Check your site stats` tour
4. ❌ Notice that Stats button and focus point are scrolled out of the screen.

https://user-images.githubusercontent.com/42008628/171302535-67fadca9-f003-42f9-8ca4-b086e17567dc.mov

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
