### ISSUE TITLE
Mention UI should make parent comment's author prominent in list of suggestions

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#18818]
### Expected behavior

When inserting an @-mention into a reply, the app brings up a list of suggestions. It would be nice if the username of the parent comment or post was at the top of the list, for convenience.

### Actual behavior

You have to manually search for the username of the parent post or comment when inserting an @-mention.

### Steps to reproduce the behavior

1. Locate a post or comment
2. Start a reply
3. Type `@` to insert an @-mention
4. Notice that the author of the parent comment isn't shown at the top of the list

**Comment by salimbraksa** [comment]
Hey, @twstokes @guarani I have a question about this task:

Let's say a user is replying to a comment, should we display both the post and comment authors at the top of the suggestions list or only the comment's author?

**Comment by twstokes** [comment]
> Hey, @twstokes @guarani I have a question about this task:
> 
> Let's say a user is replying to a comment, should we display both the post and comment authors at the top of the suggestions list or only the comment's author?

Good question @salimbraksa! I'd like to run this by the designers to get their thoughts. 🙇
