### ISSUE TITLE
WPiOS crashed when editing or creating posts

### ISSUE THREAD

**Issue by thabotswana** [wordpress-mobile/WordPress-iOS#18836]
It was reported in 5274346-zen, that the user has not been able to edit or write new posts since the app crashes frequently.

I found the [Sentry reports](https://sentry.io/organizations/a8c/discover/wordpress-ios:58e5844f216b42d1832dc24275067fe8/?field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=1438083&query=user.email%3Adedeg73%40gmail.com&sort=-timestamp&statsPeriod=7d&yAxis=count%28%29) with the following error:

```
EXC_BREAKPOINT: leViewController > release > RNSVGDefsManager
```

**Smartphone:**
 - Device: iPhone 13 Pro
 - OS: iOS 15.5
 - Version 19.9.1

**Comment by ChrissiePollock** [comment]
The customer gave permission to access their site in the app as long as nothing is changed or lost. #5274346-zen

**Comment by thabotswana** [comment]
This was a false alarm. Found out that user has no sites added to the app 😊
