### ISSUE TITLE
Media library: 'No media matching your search' message is no visible

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#18840]
### Expected behavior
While searching for media in Media Library, `No media matching your search` message is displayed when no results are found.
Also, if the search is cancelled and the user tries to add a media file again, they will see all available media in the search screen.

### Actual behavior
When searching Media Library without results, `No media matching your search` message is not visible, but underneath the header.
Also, when the search is canceled by tapping the `Cancel` header button the `No media matching your search` message will be displayed if the user tries to add Media Library items again for any media block.

### Steps to reproduce the behavior
1. Create a new blog post
2. Add a Image block
3. Click `ADD IMAGE`
4. Click `WordPress Media Library`
5. Search for some string that will not return any results
6. ❌ `No media matching your search` message is not visible. _Expected: The message IS visible._
7. Click `Cancel` button in Navigation bar
8. Click `ADD IMAGE`
9. Click `WordPress Media Library`
10. ❌ `No media matching your search` message is visible. _Expected: Available images are displayed_

https://user-images.githubusercontent.com/42008628/172656786-618ba8ee-b2da-4bd2-bc8c-d6cc3c686f0d.MP4

**Comment by diogo-lins** [comment]
Hello everyone 👋🏾, after research and a walkthrough in the code I saw the root cause is: 
**The keyboard when it appears pushes the "MediaLibraryView" up.** 

So I'll do some code changes on a future PR to resolve this!
