### ISSUE TITLE
Users should be able to search through their blog list

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#1885]
Matt pointed out to us that for users with a lot of sites on their mobile app it was very difficult to find a particular blog as you had to scroll a lot. Let's add in the ability to search through the blog list to be able to more quickly find a particular site.

**Comment by sendhil** [comment]
Lets try to get this into the next release.

**Comment by SergioEstevao** [comment]
We should coordinate this with the calypsofication of the interface. The search interface UI could be copied from the blog post and pages interfaces. We could also look at the mobile web interface.
