### ISSUE TITLE
Feature Request: Video Block - add video from URL

### ISSUE THREAD

**Issue by Mito173** [wordpress-mobile/WordPress-iOS#18931]
### Expected behavior
When creating a blogpost over the IOS WordPress app, I would like to add a video block and add the video **as URL** (in my case from our NexctCloud site) like it is possible when editing a blogpost in a browser window, e.g. in Firefox.

### Actual behavior
When creating a video block in a blogpost in the WordPress IOS app, you can choose the video from the following sources only:
- Choose from device
- Take a Video
- WordPress Media Library
- Other Apps

##### Tested on [device], iOS [version], WPiOS [version]
Apple iPhone 7 Plus, iOS 15.4.1, WPiOS 19.9.1

**Comment by Mito173** [comment]
Just installed the new WordPress IOS app update to version 20.0.1. Now it is possible to add images sung 'Insert from URL' - this is already a nice feature but it would be more important for videos as they can be way over 100MB. Keeping them on two locations /WordPress library and e.g. a cloud) does waste expensive storage space and data transfer usually takes much time.

So, maybe the same part of code of the image block can be reused in the video block?

Would be great :-)
Thanks!

**Comment by tiagomar** [comment]
👋  Hey, @Mito173!

You might want to check the release notes for 20.3. =)

https://github.com/wordpress-mobile/WordPress-iOS/blob/555553ec17bf6a5e5cf8ffe7b33cf36a61b2fd55/RELEASE-NOTES.txt#L11

**Comment by fluiddot** [comment]
Hey @Mito173 👋 !

As @tiagomar mentioned in [this comment](https://github.com/wordpress-mobile/WordPress-iOS/issues/18931#issuecomment-1187579597), we already added this feature in version 20.3 via [this PR](https://github.com/WordPress/gutenberg/pull/41493). Hence, I'm going to close the issue but please feel free to reopen it if there's anything related to this feature that we're missing, thanks!

**Comment by Mito173** [comment]
Hey @tiagomar , @fluiddot , thanks a lot for this fast implementation - great job!
