### ISSUE TITLE
Bring WordPressMocks into WordPress-iOS, then deprecate the repository

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#18956]
We no longer benefit from having a dedicated, shared repository for the WordPress API mocks used by the UI tests. After a brief discussion with @ParaskP7 from the Android Platform side and the iOS devs internally we agreed to move all the iOS-related logic into this repo, then proceed to deprecate https://github.com/wordpress-mobile/WordPressMocks.

- [x] Move all the relevant WordPressMocks code into here. _Maybe as a package like Flux?_
- [x] Once the PR lands into `trunk`, double-check with @ParaskP7 that we're good to archive the [mocks repo](https://github.com/wordpress-mobile/WordPressMocks).

**Comment by ParaskP7** [comment]
👋 @mokagio !

> ...double-check with @ParaskP7 that we're good to archive the [mocks repo](https://github.com/wordpress-mobile/WordPressMocks).

From the Android side, we're good to archive the [mocks repo](https://github.com/wordpress-mobile/WordPressMocks), so feel free to do so as soon as you're ready on the iOS side as well.
