### ISSUE TITLE
[iOS] Stats screen shown incorrectly on iPad

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#18985]
### Expected behavior

The Stats screen should always be shown on the right side of the iPad (secondary pane).

### Actual behavior

The Stats screen is shown on the left side of the iPad (primary pane), replacing the My Site Home/Menu. This happens when users log in and choose the "focus" called checking stats.

### Steps to reproduce the behavior

1. Ensure you are logged out of the app
2. Log into the app
3. After choosing a site, the app will ask you what focus you would like to pick
4. Choose "checking stats" (or a similarly named item)
5. Optionally enable notifications
6. Notice that the Stats screen is shown on the left and right sides of the screen

### Screenshot

<img width="1248" alt="Screen Shot 2022-07-04 at 15 16 26" src="https://user-images.githubusercontent.com/1898325/177213334-5a79de0a-f581-4808-8e12-bbfa839e7443.png">

### Additional information

I’m not 100% sure this bug is related to the recent Stats Revamp project. @frosty found that it was reproducible even when the Stats Revamp feature flag was off.

**Comment by guarani** [comment]
If it's determined that this bug is not related to the recent Stats Revamp, I would re-consider whether it's worthy of a betafix.

**Comment by sla8c** [comment]
@guarani @frosty this issue occurs for me on production AppStore build with old stats cards (ie FeatureFlag off)

**Comment by sla8c** [comment]
@Guarani this issue is also still unresolved on latest TestFlight build (20.3)
