### ISSUE TITLE
[iOS] Stats Revamp cards not responding to changes between Dark and Light mode

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#19015]
### Expected behavior

The Stats' Insights screen should adapt instantly to changes in the device's Dark/Light mode settings.

### Actual behavior

The Stats' Insights screen doesn't immediately reflect changes.

### Steps to reproduce the behavior

1. Open the Stats screen
2. Ensure you're on the Insights screen
3. Change the device appearance mode between Light and Dark
4. Notice that the text color does not adapt correctly
5. Refresh the screen, to the previous screen, and return to the Stats' Insight screen
6. Notice that the text colors have now adapted

### Screenshots

| <img src="https://user-images.githubusercontent.com/1898325/178021132-eb678555-084b-4fb4-a86e-d0624d0df9d9.png" alt="" width="350">  |
| - |

**Comment by griffinreding** [comment]
Creating a branch for this issue with the intent to resolve.
