### ISSUE TITLE
Disambiguate "Dismiss" localizations

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#19028]
# Problem 

While smoke testing version 20.2, sharp eyed @tiagomar noticed an issue. In the QR code login screen, the [English copy](https://github.com/wordpress-mobile/WordPress-iOS/blob/b9e75959281516bc22631f3b4aded972e17289f8/WordPress/Classes/ViewRelated/QR%20Login/View%20Controllers/QRLoginVerifyAuthorizationViewController.swift#L187-L188) for the message and button are "Tap dismiss and..." and "Dismiss" respectively, but the Italian translation was inconsistent:

![image](https://user-images.githubusercontent.com/1218433/178412857-65dab4d7-9a10-4aaf-9018-0441e328a06b.png)

This happened because there is no clear relationship between the "Dismiss" used in the message and the one used in the button, so it's up to the translator or translators that happened to pick up the string to use the translation they think makes more sense given the limited context provided by the developer comment.

To make matter worse, we have 20 usages of the "Dismiss" across the app: 

https://github.com/wordpress-mobile/WordPress-iOS/blob/b9e75959281516bc22631f3b4aded972e17289f8/WordPress/Resources/en.lproj/Localizable.strings#L2508-L2528

While "Dismiss" might work in English in all those instances, we cannot assume whichever translation "Dismiss" happens to have in one locale is appropriate in all the instances for that locale as well. As a matter of fact, that is exactly the case for the Italian locale, where "Dismiss" got translated to "Respinto" ("Reject"), but then translated to "Ignora" ("Ignore") in the context of the "Tap dismiss and..." copy for the QR code screen.

# Proposed Solution

We need to disambiguate between the various context in which "Dismiss" is used.

One option would be to use replace each `NSLocalizedString("Dismiss", "...")` definition with ones using [reverse DNS notation](https://en.wikipedia.org/wiki/Reverse_domain_name_notation)  for the key, e.g. `NSLocalizedString("qr_code_login.verify_authorization.dismiss_button", "...")`. This approach would result in dedicated entries for each "Dismiss" usage and should give translators more flexibility.

This approach (kudos @AliSoftware for making it happen) is already in use, for example in `StatSection.swift`: https://github.com/wordpress-mobile/WordPress-iOS/blob/ac84f8a21ca717f0f43bd93ea880d957fd1740d4/WordPress/Classes/ViewRelated/Stats/Helpers/StatSection.swift#L408

If we had this setup in place at the time of the issue described above, we could have fixed the translation for the button and message in the QR code screen to be in line and consistent, that is with a better Italian translation that actually signifies dismiss, like "Dismetti". Instead, we had to edit the message translation to use "Respinto" because we couldn't risk changing the button translation as it was used in 19 other screens.

And alternative to ensure consistency, albeit without extra flexibility, would be to use string interpolation:

```swift
static let subtitle = NSLocalizedString(
  "Tap %@ and head back to your web browser to continue.", 
  comment: "Subtitle instructing the user to tap the dismiss button to leave the log in flow. %@ is a placeholder for the dismiss button name"
)
 
static let confirmButton = NSLocalizedString(
  "Dismiss",
  comment: "Button label that dismisses the qr log in flow and returns the user back to the previous screen"
)
```

**Comment by mokagio** [comment]
I have a demo for the reverse-DNS approach: https://github.com/wordpress-mobile/WordPress-iOS/pull/19029

**Comment by AliSoftware** [comment]
I think we should actually adopt a mix of **both** your suggestions, so that we have both the ability to provide a different translation of "Dismiss" for each of the 20 places based on context… _and_ ensure consistency (between subtitle and button title on that screen) via code, instead on assuming the translator(s) will know the relation between those two strings.

```swift
static let subtitle = NSLocalizedString(
  "qr_code_login.verify_authorization.subtitle",
  value: "Tap %@ and head back to your web browser to continue.", 
  comment: "Subtitle instructing the user to tap the dismiss button to leave the log in flow. %@ is a placeholder for the dismiss button name"
)
 
static let confirmButton = NSLocalizedString(
  "qr_code_login.verify_authorization.dismiss_button",
  value: "Dismiss",
  comment: "Button label that dismisses the qr log in flow and returns the user back to the previous screen"
)
```

**Comment by mokagio** [comment]
> I think we should actually adopt a mix of both your suggestions...

@AliSoftware I've been thinking about this and I agree with you. Even though interpolation feels a bit clunky, the translators are familiar with it already and it's the most secure way to ensure consistency.

**Comment by mokagio** [comment]
https://github.com/wordpress-mobile/WordPress-iOS/pull/19635 closed this issue, but I forgot to followup or to use one of GitHub's option to close this as it got merged.
