### ISSUE TITLE
Stats Revamp Feature announcement displays then auto dismisses without user input

### ISSUE THREAD

**Issue by sla8c** [wordpress-mobile/WordPress-iOS#19035]
### Expected behavior
The Stats Revamp Feature announcement should display and then be dismissed by one of the user input options

### Actual behavior
The Stats Revamp Feature announcement displays briefly and then automatically dismisses

### Steps to reproduce the behavior
1. Enable feature flag `statsNewInsights`
2. Log out of app or install from scratch2. 
3. Login to the app3. 
4. Choose a site and when asked what focus you would like to pick choose Stats
5. Optionally enable notifications 
6. The Stats Revamp Feature announcement briefly appears before being dismissed

##### Tested on [device], iOS [version], WPiOS [version]
iPad Air 5th Gen Simulator, WPiOS 15.5, branch [fix/18985-insights-navigation-ipad](https://github.com/wordpress-mobile/WordPress-iOS/tree/fix/18985-insights-navigation-ipad)

Discovered while testing this PR
https://github.com/wordpress-mobile/WordPress-iOS/pull/18987#pullrequestreview-1029150254

**Comment by staskus** [comment]
Closing the issue since the feature announcement is removed
