### ISSUE TITLE
Upgrade App Center to the latest version + Consider using SPM

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#19042]
The App Center pod is currently at version 4.4.1. The latest version at this time is [4.4.2](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.4.2).

From the [changelog](https://github.com/microsoft/appcenter-sdk-apple/releases/tag/4.4.2), I don't see anything useful to grant an upgrade. However, I'd love for us to get better at keeping our dependencies up to date, under the assumptions that:

- On average, the most up to date a library is the less issue it has
- Upgrading frequently should result in smoother upgrades. There is an overhead in upgrading frequently vs when we need to because of a bug or feature, but that overhead cancels out when we account for the complexity of a many versions upgrade. I consider it a risk mitigation strategy.

---

Related: the library supports installation via Swift Package Manager. When we pick up this task, we should consider also moving to SPM.

**Comment by jkmassel** [comment]
Given the fact that we're dropping App Center, I'm comfortable closing this.
