### ISSUE TITLE
Suggestions list (using @-mention) disappear after expanding/collapsing the reply input

### ISSUE THREAD

**Issue by RenanLukas** [wordpress-mobile/WordPress-iOS#19051]
### Expected behavior
Suggestions list continue to be shown after expanding/collapsing the reply input.

### Actual behavior
Suggestions list disappear after expanding/collapsing the reply input.

### Steps to reproduce the behavior
The issue is also reproducible in the other scenarios mentioned in [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/18979).

1 - Tap the "My Site" tab.
2 - Tap on "Menu"
3 - Tap on "Comments" row.
4 - Tap any comment.
5 - Tap "Reply" button.
6 - Type `"@"`. You should see the suggestions list. Tap on the chevron up button: the reply input is expanded and the suggestions list is gone.
7 - Delete the `"@"` and type it again. You should see the suggestions list. Tap on the chevron down button: the reply input is collapsed and the suggestions list is gone.

**Comment by twstokes** [comment]
Related:
- https://github.com/wordpress-mobile/WordPress-iOS/issues/18988
