### ISSUE TITLE
Reader > Search: Jetpack banner is visible and animated in 'No posts found' screen.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#19097]
Jetpack banner is responding to scroll up/down gestures in `Reader` > `Search` > `'No posts found' screen`. 
The same thing happens for the `Unable to load this content right now` screen.

|  |  |
| :-: | :-: |
| <video width="300" src="https://user-images.githubusercontent.com/42008628/180320519-782eb7dd-d00e-4ca9-9b0f-1348e2e14fee.mov"> | <video width="300" src="https://user-images.githubusercontent.com/42008628/180321015-c7c1b92d-5479-4ffd-96ed-a614e6e74730.mov"> |

### Steps to reproduce the behavior
1. Open the app.
2. Go to `Reader`.
3. Tap `Search` button.
4. Type several letters in the search field to the result is the `No posts found` screen.
5. Swipe the screen up and down.
6. ❌ Notice the Jetpack banner is responding to scrolling up/down gestures.
7. Turn the Airplane mode ON.
8. Search for something.
9. Notice the `Unable to load this content right now` screen is displayed.
10. Swipe the screen up and down.
11. ❌  Notice the Jetpack banner is responding to scrolling up/down gestures.

**Comment by Gio2018** [comment]
@tiagomar @twstokes , just a thought here: is the issue that the banner responds to the scroll events, or that the no result views are still bouncing? I'm fine with both approaches (and I agree that this is a low priority issue), just wanted to share this thought.

**Comment by tiagomar** [comment]
Good question @Gio2018! The requirements actually changed a bit since I filed this ticket (I'll update the description), now we do expect the banner to be displayed in Reader Search results, so the weirdness would be the banner hiding and reappearing when the screen is not actually scrolled.

Removing the bouncing sounds like simplest fix to the rookie in me. =P 

It's good to notice that the Banner in Reader Search results is still not present in Android as of 20.4.

**Comment by Gio2018** [comment]
> Removing the bouncing sounds like simplest fix to the rookie in me. =P

it would be, but my observation was incorrect. In fact, the bouncing is there because it could trigger a refresh of the table that could then produce valid posts. So, never mind, discard my observation and sorry for the inconvenience.
