### ISSUE TITLE
Remove force try and force unwrap from `DeleteSiteViewController.swift`

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#19132]
See https://github.com/wordpress-mobile/WordPress-iOS/pull/16168/files#diff-1deb973c422464bf87dafac9a46ce22477d88c63df976c221cf09a5ffb785d5fR234-R236

**Comment by entunidotdeb** [comment]
Hi, can i take this up with optional try (try?) and if let ?

**Comment by mokagio** [comment]
@entunidotdeb that would be great, thanks!

**Comment by entunidotdeb** [comment]
> @entunidotdeb that would be great, thanks!

[PR 19146](https://github.com/wordpress-mobile/WordPress-iOS/pull/19146) 

@mokagio that is raised against move/wpaccount-lookup-out-of-account-service

**Comment by momo-ozawa** [comment]
Closed via https://github.com/wordpress-mobile/WordPress-iOS/pull/19167
