### ISSUE TITLE
Install Jetpack screen crops icon, doesn't scroll. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#1914]
On an iPhone in landscape orientation, the Install Jetpack screen crops the Jetpack logo. This would be fine if the view could scroll.

![ios simulator screen shot jul 8 2014 2 00 30 pm](https://cloud.githubusercontent.com/assets/1435271/3515128/8d569e6e-06d2-11e4-9faa-a27c78e7f09a.png)

**Comment by rachelmcr** [comment]
Tested and confirmed that the logo is still cropped/doesn't scroll on iPhone 6s, iOS 9.1, app beta 5.8.0.20151124 in landscape orientation.

**Comment by astralbodies** [comment]
Taking this on now.

**Comment by aerych** [comment]
Possibly related: https://github.com/wordpress-mobile/WordPress-iOS/issues/4665
