### ISSUE TITLE
[Revamp Landing Screen] WPiOS - Remove carousel & redesign landing screen

### ISSUE THREAD

**Issue by ovitrif** [wordpress-mobile/WordPress-iOS#19226]
Redesign the landing screen of the WordPress app, by replacing the carousel with a static wp-admin themed splash screen:

![WPSplash](https://user-images.githubusercontent.com/4588074/187252054-da3d1656-2499-484c-8c3e-7ec304e8c4c7.png)

---
- Development should be behind [the recently introduced feature flag](https://github.com/wordpress-mobile/WordPress-iOS/issues/19227).

**Comment by mokagio** [comment]
Bumping to the next release, from 20.7 to 20.8, because it hasn't been reviewed yet and I'm about to start the 20.7 code freeze.
