### ISSUE TITLE
Unable to abort WP.com login flow while managing a self-hosted site

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#19245]
### Expected behavior

I should be able to go back if I decide to abandon the WP.com login flow while logged in to a self-hosted site

### Actual behavior

I can't abandon the WP.com login flow while logged in to a self-hosted site. The app doesn't let me go back.

### Screen recording

https://user-images.githubusercontent.com/1898325/186749512-4a91d564-2f87-4d5a-8bc5-d4048d1907e6.MP4

### Steps to reproduce the behavior

1. Log into a self-hosted site using its site credentials
2. Tap the account avatar to reach "Me" screen
3. Tap Log In under the "WordPress.com Account" section
4. You're taken to the WP.com log in screen 
5. Notice that you can't go back to the "Me" screen

**Comment by guarani** [comment]
Added priority medium because this affects both apps and the only workaround I know is to re-install the app (update: [a better workaround is to force quit the app](https://github.com/wordpress-mobile/WordPress-iOS/issues/19245#issuecomment-1228595543)).

**Comment by momo-ozawa** [comment]
@guarani You can force quite the app to escape the log in screen. (Still not great, but not as terrible as having to reinstall the app)

<details>
<summary>Expand for video</summary>

https://user-images.githubusercontent.com/6711616/186933231-5eb81604-3e1b-427e-96ea-93c88b5bc66b.mp4

</details>

**Comment by guarani** [comment]
True, that's definitely a better workaround. I updated my previous comment to reflect this.
