### ISSUE TITLE
Jetpack plugin installation and completion flow improvement thread

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#19261]
A list of improvements to Jetpack plugin installation. Moved from https://github.com/wordpress-mobile/WordPress-iOS/issues/17721

### Login & Connection

- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/19271
- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/16489 pe5sF9-B9-p2
- [x] #20259
- [x] #20260
- [ ] Sometimes, a PHP error occurs during setup after a fresh install
- [ ] When logging into WP.com account that is not associated with site's Jetpack connection we show generic error. We should either allow to add additional user to Jetpack connection or at least show a clear error

### UX

- [x] https://github.com/wordpress-mobile/WordPress-iOS/issues/19272
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/19301
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/issues/19260
- [ ] After installing Jetpack and logging into WPcom display a message informing the user we're enabling the features. This prevents the blog details from being silently updated and confusing for the user, especially on slower connections
- [x] Sometimes there can be a blank screen displayed after displaying the connect webview: https://github.com/wordpress-mobile/WordPress-iOS/pull/17722#pullrequestreview-846499849
- [ ] If a user logs into the blog using a site address that Jetpack installed and connected, we should inform them they have Jetpack installed and ask them if they want to sign in with their WP.com account
- [ ] If you tap on Install Jetpack from the stats view and go through the install and connection process you are then brought to a screen requiring you to log into your WP.com for a second time.
- [ ] Notifications view does not reload when the Jetpack plugin installation state changes (NotificationsViewController has no JetpackLoginViewController completion block)
- [ ] When the error happens during Jetpack installation, suggest to user that the plugin can be installed through the browser

**Comment by guarani** [comment]
There was a bug a couple of months ago which broke the Jetpack plugin installation flow in the apps and required a hotfix: https://github.com/wordpress-mobile/WordPress-iOS/pull/19056
I'm only sharing here as an example of a recent bugfix in the installation flow.
