### ISSUE TITLE
Jetpack Install subview does not fully fit inside Notifications view

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#19272]
Jetpack Install subview does not fully fit inside Notifications view

- Install Jetpack subview does not fully fit, Jetpack FAQ view is not visible
- "Older than a week" section is shown

### Steps to reproduce the behavior

1. Log in to the self-hosted site which doesn't have Jetpack installed with iPhone 13
2. Select "Notifications"
3. Observe "Install Jetpack" subview

##### Tested on iPhone 13, iOS 15.5, WPiOS 20.6

https://user-images.githubusercontent.com/4062343/187922658-ec5d137e-9322-4244-b54e-b613fba945ef.mp4

**Comment by momo-ozawa** [comment]
Looks like this issue was addressed by [d28c64a](https://github.com/wordpress-mobile/WordPress-iOS/pull/19360/commits/d28c64aadaefa0e3eea3e8cfeed79754790a603c) in https://github.com/wordpress-mobile/WordPress-iOS/pull/19360.

**Comment by staskus** [comment]
@momo-ozawa, thank you for notifying me!

I tested and can confirm that the issue is no longer reproducible.
