### ISSUE TITLE
Add TTL logic to remote feature flags

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#19279]
### Description
The app already supports remote feature flags (#14799). We want to tweak the current implementation to refresh the feature flags on every app resume, ~but only if the TTL (24 hours) has passed~.

**Comment by enejb** [comment]
Just posting an note here as to what we chatted about in the call today. 

We should also make sure that we request the endpoint if we are logged in. (Re-fetch the endpoint after logging in and logging out. )

**Comment by AjeshRPai** [comment]
@enejb I am going ahead and implementing the same in Android as well.

**Comment by hassaanelgarem** [comment]
> We should also make sure that we request the endpoint if we are logged in. (Re-fetch the endpoint after logging in and logging out. )

@enejb I created #19291 to track this 👍

**Comment by hassaanelgarem** [comment]
After some discussion [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/19293#discussion_r969029287) and on slack: p1664828821652799-slack-C03T04HETR8, we decided to refresh the feature flags on every launch and relaunch but without any TTL logic.
