### ISSUE TITLE
New color palette — carets

### ISSUE THREAD

**Issue by drw158** [wordpress-mobile/WordPress-iOS#1927]
Every caret should be changed to #B1C6D4 [rgb(177, 198, 212)] to adhere to the new WordPress.com color palette.

![](https://i.cloudup.com/mSeo4PoLJJ.png)

**Comment by kurzee** [comment]
Looks like we still can't change the color of these, even with `tintColor`, probably also shouldn't use custom images in every cell within the app. Closing, can reopen if needed later.
