### ISSUE TITLE
New color palette — tab bar icons

### ISSUE THREAD

**Issue by drw158** [wordpress-mobile/WordPress-iOS#1929]
The inactive tab bar icons + text (currently gray) should be changed to #90aec2 [rgb(144, 174, 194)] to adhere to the new WordPress.com color palette.

![](https://i.cloudup.com/utV3iyJ8Sw.png)

**Comment by rachelmcr** [comment]
Checked the inactive tab bar buttons and they currently use `allTAllShadeGrey`. Closing this issue as resolved.
