### ISSUE TITLE
Endless loop when accessing QR login from mobile device

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#19298]
### Expected behavior

When trying to log into WP.com using "QR login", the link to the app should only open the Jetpack app.

### Actual behavior

The app starts an endless loop when I try to log into WP.com using "QR login" and have both the WP and JP apps installed.

### Screen recording

https://user-images.githubusercontent.com/1898325/189195812-d7041757-c5a3-4555-ad49-1f1199a554c4.mov

### Steps to reproduce the behavior

1. Fresh install the JP and WP apps from the App Store
2. Sign out of WordPress.com on your mobile browser
3. On your mobile browser, go to WordPress.com
4. Open the Hamburger menu, tap "Log in"
5. Tap "Log in via the mobile app" 
6. ⚠️ Looks like QR code login wasn't meant to be used from mobile devices, just desktops
7. I tap "Open the Jetpack App..." link anyway
8. App cycles between the WP and JP apps indefinitely :infinite:

**Comment by guarani** [comment]
Assigning priority low because QR login wasn't designed for use on mobile browsers, to my knowledge. The workaround is to use a different login option.

**Comment by twstokes** [comment]
👋 Hey @guarani - I wasn't able to reproduce this issue and it may be due to @zwarm's [changes to the Jetpack App URL](https://github.com/Automattic/wp-calypso/pull/69138) on the QR login that sends iOS / iPadOS clients directly to the [Jetpack App Store page](https://apps.apple.com/us/app/jetpack-website-builder/id1565481562).

More context: D87113-code | p1665499305548209-slack-C9EJ7KSGH

**Comment by zwarm** [comment]
👋  I wasn't able to reproduce this either. The previous link also sent the user to the play store too.

**Comment by guarani** [comment]
Thanks for checking this issue and finding it's no longer reproducible. 

I tested it again and can't reproduce it either 👍 

I found it a bit odd that the "Open the Jetpack App" link opens the app's store page even if the app is installed. It would be better UX for it to open the installed Jetpack app directly. Would this be unrelated to the changes you were involved in, @zwarm?

**Comment by twstokes** [comment]
>It would be better UX for it to open the installed Jetpack app directly.

Step 5 would also be a bit weird if doing this all from mobile:

>Point your phone to this screen to scan the code.

**Comment by zwarm** [comment]
@guarani 

> I found it a bit odd that the "Open the Jetpack App" link opens the app's store page even if the app is installed. It would be better UX for it to open the installed Jetpack app directly. 

The intention or assumption was that the link would only be used on a non-mobile device. The experience is not to log into the native app, but to use the logged in session of the native app to seamlessly log into a session on a non-mobile device. There is definitely room for improvement.

Would this be unrelated to the changes you were involved in, @zwarm?
Correct, not at all related - the same behavior existed prior.

**Comment by guarani** [comment]
Gotcha, thanks for explaining, @zwarm! I'm closing this as no longer reproducible. Thanks folks!
