### ISSUE TITLE
In-app ratings for the Jetpack app are submitted instead to the WordPress app

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#19300]
### Expected behavior

When I tap Rate Us to rate the Jetpack app, it should allow me to rate the Jetpack app.

### Actual behavior

When I tap Rate Us to rate the Jetpack app, the rating I enter is submitted for the WordPress app instead.

### Screen recording

https://user-images.githubusercontent.com/1898325/189222169-e6091423-4a76-4e09-9657-226a3ee73dec.mov

### Steps to reproduce the behavior

1. Go to the "My Site" tab
2. Tap profile pic
3. Tap "About Jetpack for iOS"
4. Tap "Rate Us"
5. ⚠️ Notice that as the modal screen is presented to rate the app, the WordPress app listing is shown behind the modal
6. Submit a review
7. Notice the app was submitted for the WordPress app instead of the Jetpack app. To verify:
  a. Open the App Store app
  b. Tap your profile picture
  c. Tap your name 
  d. Tap "Ratings and Reviews"
  e. ⚠️ Notice that the rating was submitted for the WordPress app

**Comment by dvdchr** [comment]
Closing as this should've been resolved via #19299, which is deployed in 20.7. Also double-checked that the Rate Us button in the latest version points to the correct app.

**Comment by guarani** [comment]
Thanks, @dvdchr! I must've forgotten to close this.
