### ISSUE TITLE
[iOS] Stats: Inconsistent rounding of numbers in the cards of Insights tab

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#19346]
The rounding of numbers differ between iOS and Android/Web. Make it consistent with Android.

![image](https://user-images.githubusercontent.com/4062343/192260961-c30bd816-a990-4bbe-9dbe-6bb5a29185fe.png)
![image](https://user-images.githubusercontent.com/4062343/192260977-d883812a-7677-43e5-8967-34b3e7444098.png)

### Expected behavior

1. Most Popular Time percentages match Android and Web
2. If the previous period was empty, don't show zero increase in the brackets: Show `+6` instead of `+6 (0%)`
3. This Year's statistics rounding matches Android

### Steps to reproduce the behavior

1. Enable statsRevamp feature flag
2. Open Stats
3. Open Insights Tab
4. Compare "Most popular time" and "This Year" information with Android and Web

**Comment by mokagio** [comment]
@staskus  I'm going to bump this to the next release because we'll be code freezing 20.9 today and this is still open and with  no linked PR working on it.
