### ISSUE TITLE
[iOS] Stats: Views & Visitors card shows information for the last 7 days instead of this week

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#19345]
Views & Visitors card and details view shows information for the last 7 days

![image](https://user-images.githubusercontent.com/4062343/192260003-2e586cd7-6e3a-415e-a5cb-26682bef6c2c.png)

More context in the investigation here: https://github.com/wordpress-mobile/WordPress-iOS/issues/19337

### Expected behavior

Show view and visitor stats for this week, starting from the beginning of the week.

On the Web and Android it works as expected

### Steps to reproduce the behavior

1. Enable statsRevamp feature flag
2. Open Stats
3. Open Insights Tab
4. Add Views & Visitors card
5. Notice that the diagram and numbers show the information for the last 7 days, although the label indicates "This week"
6. Click "Week" button on top right of the card
7. Notice that the diagram still shows the information for the last 7 days, although on the top we see time range selected for this week starting on Monday.

**Comment by mokagio** [comment]
@staskus  I'm going to bump this to the next release because we'll be code freezing 20.9 today and this is still open and with  no linked PR working on it.
