### ISSUE TITLE
[iOS] Stats: This week's visitor numbers don't match Web and counts non-unique visitors without providing a clear context

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#19355]
This week's visitor numbers don't match Web. Web reports much lower numbers than mobile applications.

[See the investigation for more context.](https://github.com/wordpress-mobile/WordPress-iOS/issues/19337)

It most probably happens because on the Web only unique visitors are counted:
```
The unique weekly visitors can sometimes be less than the sum of daily visitors for the same week. The same goes for unique weekly visitors being less than your total monthly visitors. This occurs when the same visitor appears multiple times during the week or month.
```

See [WordPress support stats](https://wordpress.com/support/stats/)

![image](https://user-images.githubusercontent.com/4062343/192465084-0c4938a6-7ffc-4202-b88c-a9fe69c9417a.png)

### Expected behavior

This week's visitor numbers should match Web numbers.

### Steps to reproduce the behavior

1. Open Jetpack app with `statsRevamp` feature flag enabled
2. Open Stats view
3. Make sure "Views and Visitors" card is added
4. Compare visitor numbers with the Web
5. Click "Week"
6. Compare visitor numbers with the Web

**Comment by sla8c** [comment]
@staskus thanks for creating the issue!  I've taken a look and indeed it is the unique visitor count being shown on web vs on iOS

I was looking to see what Android / @irfano did so we can be consistent and I see that they closed their issue https://github.com/wordpress-mobile/WordPress-Android/issues/17212

I think on iOS we should follow the same design decisions that result from https://github.com/wordpress-mobile/WordPress-Android/issues/17450?

Thanks!

**Comment by staskus** [comment]
> @staskus thanks for creating the issue!  I've taken a look and indeed it is the unique visitor count being shown on web vs on iOS
> 
> I was looking to see what Android / @irfano did so we can be consistent and I see that they closed their issue https://github.com/wordpress-mobile/WordPress-Android/issues/17212
> 


@sla8c thanks for taking a look. We defintely should not be making a decision in isolation. Data appearing consistent across platforms is vital for Stats.

> I think on iOS we should follow the same design decisions that result from https://github.com/wordpress-mobile/WordPress-Android/issues/17450?

As I understand, there's no decision made for now on Android side, or am I mistaken? Thanks!

**Comment by staskus** [comment]
This issue does not have a clear resolution, since this is a different element than on the Web and we show a daily visitor count in the chart. As mentioned [on the Android issue](https://github.com/wordpress-mobile/WordPress-Android/issues/17450), we might need to consider providing context and adding explanations.

**Comment by guarani** [comment]
Closing in favor of https://github.com/wordpress-mobile/jetpack-issue-repo/issues/21 because we'll be removing the Views & Visitors card.
