### ISSUE TITLE
[iOS] Stats: This year's stats are not consistent between mobile and web as different API endpoints return different yearly data

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#19356]
Yearly statistics of views, visitors, likes, and comments match Adnroid but don't match the Web.

![image](https://user-images.githubusercontent.com/4062343/192469248-1365f3fd-ce07-4df8-b99b-fba976819cb1.png)

### Expected behavior

All the platforms have the same numbers.

### Steps to reproduce the behavior

1. Open Jetpack app with `statsRevamp` feature flag enabled
2. Open Stats tab
3. Make sure "This year" card is added
4. Compare year statistic with the Web

**Comment by sla8c** [comment]
@staskus I found the issue for this - web is inconsistent with itself when reporting Years numbers.

On the web clicking the tab `Traffic` is the equivalent of our StatsPeriodStore api calls and uses endpoint `/stats/visits/`

And it matches the app currently for PeriodStats Years tab
![image](https://user-images.githubusercontent.com/88816724/206257978-32702aa2-2f52-4928-875e-cf7db0bf399c.png)

However on the web clicking tab `Insights` makes a call to the `/stats/insights/` endpoint which is also what we do in app and it matches

![image](https://user-images.githubusercontent.com/88816724/206260018-f12ace97-9f86-468b-a199-ed5be12e462f.png)

I would summarise as follows:
 * iOS is consistent with Web
 * however both web and iOS inconsistently display yearly information for the user as the yearly information is from 2 different api calls which return different values for the same fields

Possible solutions are:
 * we are in sync with web so we should prob see with them on what should be the intended behaviour and action that
 * if the web team can't action / doesn't have a strong opinion then I think we should the "View more" button at the bottom of the This Year card so the user can't navigate there and it would reduce confusion.  However this should probably go through design review?

![image](https://user-images.githubusercontent.com/88816724/206261076-141ad781-f76a-4f95-a891-afb1a72b9d25.png)


cc @irfano @ravishanker for heads up re: Android

**Comment by staskus** [comment]
@sla8c, thanks for the research. It gives much more insight! 👍

> we are in sync with web so we should prob see with them on what should be the intended behaviour and action that
> if the web team can't action / doesn't have a strong opinion then I think we should the "View more" button at the bottom of the This Year card so the user can't navigate there and it would reduce confusion. However this should probably go through design review?

I agree. I'll try to get in touch with web folks about these questions.

**Comment by staskus** [comment]
I am changing the priority due to the discovery that our numbers do match the Web but only the parts that are using the same API endpoint.

No clear resolution plan for now.

**Comment by staskus** [comment]
This is not a client-side issue https://github.com/wordpress-mobile/WordPress-Android/issues/17213#issuecomment-2024936531
