### ISSUE TITLE
Establish a unique pattern for testing `UIViewController` presentation

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#19373]
See discussion [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/19366#discussion_r982225336).

One options suggested is to use a mock:

```swift
let presenterMock = PresenterMockViewController()
...
presenter.presentReblog(blogService: blogService!, readerPost: readerPost!, origin: presenterMock)
...
presenterMock.expectPresentationToOccurr()

// In PresenterMockViewController
func expectPresentationToOccurr(file: ... = #file, line: ... = #line) {
  guard let presentExpectation = self.presentExpectation else { /* fail */ }

  waitForExpectations([presentExpectation], timeout: ...) { error in
    guard let error = error else { return }
    XCTFail("present was not called", file: file, line: line)
  }
}
```

Another option I used with good results in the past is the classic `protocol`-based test double. Something like:

```swift
protocol ViewControllerPresenting {

  // 1-1 copy of the UIViewController signature
  func present(_ viewControllerToPresent: UIViewController, animated flag: Bool, completion: (() -> Void)? = nil)
}

extension UIViewController: ViewControllerPresenting {}

class ViewControllerPresentingSpy {

  private(set) var presentedViewController: UIViewController?

  func present(_ viewControllerToPresent: UIViewController, animated flag: Bool, completion: (() -> Void)? = nil) {
    presentedViewController = viewControllerToPresent
    // doesn't actually present so we don't waste time nor need to worry about async
  }
}

// In tests
expect(presenterSpy.presentedViewController).toNot(beNil())
```

☝️ All those are _just ideas_ to throw in the mix. We ought to have a look at what the existing tests do and what production code needs, and then choose an option that works best.

---

## Tests to update

_Anyone with contributor access can update this list by updating the PR description. Seems easier than adding comments to scroll through._

- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/19366#discussion_r982225336
- [ ] https://github.com/wordpress-mobile/WordPress-iOS/pull/19374#discussion_r985392325

**Comment by mokagio** [comment]
@kean @dcalhoun @jkmassel @crazytonyli What do you think of this issue?

Is it worth keeping? If so, I'll shadow it in our Apple Core board in the Automattic org.

Or, given that the UIKit footprint should be shrinking with more and more SwiftUI usage, shall we consider this a tech debt that we'll pay off by eventually converting flows to SwiftUI and removing the inconsistent tests?

<details>
    <summary>My opinion. Hidden to avoid biasing.</summary>

I say let's close this and consider it tech debt. Of all the things we need to bo, investing on the old tech that is UIKit seems like very, very low in the priority ladder.
</details>

**Comment by kean** [comment]
I say let's close this and consider it tech debt 😉

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
