### ISSUE TITLE
Stats: Scrolling jumps and stutters while data is loading

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#19405]
Scrolling jumps and stutters while data is loading. 

### Expected behavior

When data loads the scrolling indicator stays at the same position and scrolling doesn't stop

### Technical notes

There may be multiple issues causing this behavior:
1. A lot of `emitChange` and `tableView.reloadData` calls until all the data loads (maybe diffing or throttling could be an option?)
2. Unclear row and estimated row sizes that causes table view drastically change its content size

### Steps to reproduce the behavior

1. Open Stats
3. Select "Days/Weeks/Months/Years"
4. Scroll down while the data is loading
5. Notice that the scrolling stutters/stops/jumps until the data is fully loaded

**Comment by guarani** [comment]
Closing because this issue is about the Days/Weeks/Months/Years tabs, which will be removed, and in my testing, https://github.com/wordpress-mobile/WordPress-iOS/pull/22542 solves this same issue on the Traffic tab. 

@staskus, please re-open this if it is still an issue 🙇

**Comment by staskus** [comment]
> https://github.com/wordpress-mobile/WordPress-iOS/pull/22542 solves this same issue on the Traffic tab

@guarani thanks! Yes, a more efficient reloading strategy should mostly solve this issue. Theoretically, there's still a chance of jumping due to some inefficient constraint loading and sizing of cells but we can open another issue if we observe behavior such as this.

**Comment by staskus** [comment]
@guarani I'm doing testing of the Traffic tab (https://github.com/wordpress-mobile/jetpack-issue-repo/issues/12) and my assessment is that scrolling could still be smoother. Since table view cells are no longer refreshed when data is not changed then the second reason could be related to inefficient UI layout code.

My suggestion would be to:
1. Timebox an improvement task (e.g. 1 day)
2. Use [Animation Hitches](https://developer.apple.com/videos/play/tech-talks/10855/) and/or TimeProfiler to identify the most inefficient reloads
3. Try to make improvements to the most inefficient reloads

**Comment by guarani** [comment]
I think that makes sense. Could you add an issue for it to the GitHub board please?

**Comment by staskus** [comment]
@guarani sure, done!

- https://github.com/wordpress-mobile/WordPress-iOS/issues/22721
