### ISSUE TITLE
[Revamp Landing Screen] JPiOS - UI glitches when changing between light and dark mode

### ISSUE THREAD

**Issue by Gio2018** [wordpress-mobile/WordPress-iOS#19402]
### Expected behavior
In the new Jetpack prologue screen, the UI and the animation are consistent between light and dark mode

### Actual behavior
When changing between light and dark mode, the prompts get slightly resized and re-arranged, plus the animation glitches at some point. The first is more visible when changing mode on the simulator via keyboard shortcuts, but will probably be less noticeable on a device

size change/rearrange | glitch
-- | --
<img width=300 src=https://user-images.githubusercontent.com/34376330/194110754-fb563ecb-92ed-4193-937c-8f205babeb2e.gif> | <img width=300 src=https://user-images.githubusercontent.com/34376330/194110784-f37a2593-1dcd-423d-be4f-01e63b9d990d.gif>

**Comment by twstokes** [comment]
May be fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/19410.

https://user-images.githubusercontent.com/2092798/194415572-852dfc55-4356-45b5-a422-da74069f80ab.mp4
