### ISSUE TITLE
[Wordpress/Jetpack] Crash on tapping Account Settings menu for accounts with no sites

### ISSUE THREAD

**Issue by vanessamaartinstt** [wordpress-mobile/WordPress-iOS#19413]
### Expected behavior
User should be able to access account settings for accounts with no sites created or added yet.

### Actual behavior
When trying to access account settings the app crashes.

### Steps to reproduce the behavior

1. Fresh install the app
2. Create a new account or login with an account with no sites created or added
3. Go to My Site
4. Click on Me (Avatar on the right top corner of the screen)
5. Click on Account Settings

### Notes
Only on Jetpack: after crashing and restarting the app the login needs to be performed again.

##### Tested on [device], iOS [version], WPiOS [version]
Device: Iphone 12 Pro Max
iOS Version: 16.0.2
Jetpack and Wordpress app version: 20.9 (20.9.0.0)
[WP Crash 10_06.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/9729158/WP.Crash.10_06.pdf)
[JP Crash 10_06.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/9729159/JP.Crash.10_06.pdf)

https://user-images.githubusercontent.com/107848100/194436063-6728e621-1736-40f6-9ee8-31e1aa8aaa42.MP4
https://user-images.githubusercontent.com/107848100/194436116-097d9888-9ed6-4a39-a796-f4dcac5d71df.MP4

**Comment by guarani** [comment]
Thanks for catching this and reporting, @vanessamaartinstt! I can reproduce it and I see this has now been fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/19418 (thanks @staskus and @crazytonyli).

> Only on Jetpack: after crashing and restarting the app the login needs to be performed again.

I saw this as well but I'm not sure why this is the case. @crazytonyli, do you happen to know why the JP app is logged out after the crash, but the WP app isn't?

**Comment by crazytonyli** [comment]
I don't think this log out issue is related to the crash. I can reproduce it using in development code and the Jetpack app in App Store. So, I don't think it's related to the crash. I've created #19426 to track this issue.

**Comment by guarani** [comment]
Thank you @crazytonyli! 🙇

**Comment by kean** [comment]
I believe this is fixed as there is a dedicated "No Sites" state that also allows you to view your account.
