### ISSUE TITLE
Add lock screen widgets to the app

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#19411]
### Expected behavior

Some users expect the app to have lock screen widgets (new in iOS 16).

### Actual behavior

The app only has home screen widgets.

### Steps to reproduce the behavior

1. On your device lock screen, long tap and tap Customize
2. Tap the widget area
3. Notice no Jetpack or WordPress widgets are available

Stats lock screen widgets might be an option, but there could be better uses for lock screen widgets.

**Comment by guarani** [comment]
Here are some ideas for where to take this:
- A circle-shaped widget showing:
  - site view stats
  - site visitor stats
- A rectangle-shaped widget showing:
  - site view & visitor stats
- An inline text widget showing:
  - site view & visitor stats 

Here's a rough look at what the circle and inline widgets could look like:

| <img src="https://user-images.githubusercontent.com/1898325/219974494-35ab8063-c214-452b-888f-ace47d90382a.png" alt="" width="350"> |
| - |

Given the current home screen widgets, we have the data available to build these. Just like the home screen widgets, each lock screen widget can be configurable to show stats for any of the users sites (if they have multiple sites).

**Comment by staskus** [comment]
Completed in https://github.com/wordpress-mobile/WordPress-iOS/pull/21535
