### ISSUE TITLE
User with no blogs can't stay signed in on Jetpack app

### ISSUE THREAD

**Issue by crazytonyli** [wordpress-mobile/WordPress-iOS#19426]
### Expected behavior
Signed in user stays signed in after relaunch the app.

### Actual behavior
Jetpack app prompts the user to log in upon relaunch.

### Steps to reproduce the behavior
1. Get a WP.com account *with no blogs*.
2. Sign in to the Jetpack app using the account.
3. Kill the app after signed in.
4. Launch the app again.
5. The app shows sign in page.

##### Tested on [device], iOS [version], WPiOS [version]
iPad, Jetpack 20.8 on App Store.

**Comment by crazytonyli** [comment]
It's probably caused by https://github.com/wordpress-mobile/WordPress-iOS/blob/e3c3e41637a5319dd2577a3bba9be88a1ed6349a/WordPress/Jetpack/Classes/System/JetpackWindowManager.swift#L6-L9

**Comment by guarani** [comment]
Thanks a lot for creating the issue. I gave it a medium priority because it could be frustrating to new users who skip site creation and happen to close the app.

**Comment by alpavanoglu** [comment]
Yeah that bit has caused us to raise an eyebrow as well. I am not entirely sure why it was there in the first place. Removing it should fix it. I'll open a PR in a few.

**Comment by dvdchr** [comment]
For context, I believe the check was introduced in https://github.com/wordpress-mobile/WordPress-iOS/pull/16462 due to this issue:

> During testing of magic links I found a bug where if the user logs in with no Jetpack sites and displays the no sites message, tapping the 'Try with another account' button didn't work correctly anymore.

Even though the PR has been more than a year old, If we want to remove the `hasBlogs` check, we'll need to also ensure that the magic links login flow works.

**Comment by alpavanoglu** [comment]
I'll try to make sure, both scenarios work after my PR 😬
Thanks @dvdchr !

**Comment by alpavanoglu** [comment]
PR created here: https://github.com/wordpress-mobile/WordPress-iOS/pull/19749
The aforementioned possible side affect is no longer valid due to that message/button no longer shown in the app.
