### ISSUE TITLE
[Revamp Landing Screen]  Jetpack App - Improve text color of the scrolling prompts

### ISSUE THREAD

**Issue by ovitrif** [wordpress-mobile/WordPress-iOS#19489]
### Expected behavior
The colors of the scrolling prompts are adjusted as per the [updated design specs](https://github.com/wordpress-mobile/WordPress-Android/pull/17231#issuecomment-1263930870).

> the current dark theme implementation (JP Green 50, JP Green 20) is probably okay as-is, but something was off with the light theme. For that, we could try JP Green 50 for both labels, and apply ~50% opacity to the secondary label.

Android previews for reference:
| Light | Dark |
| - | - |
| `JP Green 50 @ 50% alpha`, `JP Green 50` | `JP Green 50`, `JP Green 20` |
| <img width="314" src="https://user-images.githubusercontent.com/4588074/193870305-19fd60a0-7b2f-4d44-a5c8-fd571c1b0d76.png"> | <img width="314" src="https://user-images.githubusercontent.com/4588074/193870326-c6d78fc8-c177-4f86-b3f2-948f584d571a.png"> |

### Actual behavior
Latest guidelines for the colors are not applied.

### Steps to reproduce the behavior

1. Open the Jetpack app 
2. **Verify** The text color of the scrolling (light & dark mode) don't match the latest guidelines (see Android screenshots above).

**Comment by mokagio** [comment]
Closing this issue because #19497 addressed it. The PR description mentions it in a "Fixes" sentence, but I guess GitHub didn't pick it up as a linked issue.
