### ISSUE TITLE
NSInternalInconsistencyException: attempt to perform an insert and a move to the same index path (<NSIndexPath: 0xbf2ac48e899c9003>...

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#19507]
**Sentry Url**: https://sentry.io/share/issue/31b7abaf4db94466863036a0cdffcbd8/
**User Count**: 1296
**Count**: 4751
**First Release**: 15.5.0.3
**First Seen**: 2020-09-06T07:30:54Z
**Last Seen**: 2022-10-25T00:58:12Z
**24 Hours**: 220
**30 Days**: 4066
**LogID:** E9DDDA7D-F7DB-4351-B91E-BD5C056C2C6B

```
NSInternalInconsistencyException: attempt to perform an insert and a move to the same index path (<NSIndexPath: 0xa9f518baca9e2eaa>...
  File "WPMediaPickerViewController.m", line 684, in -[WPMediaPickerViewController updateDataWithRemoved:inserted:changed:moved:]
  File "WPMediaPickerViewController.m", line 131, in __58-[WPMediaPickerViewController registerDataSourceObservers]_block_invoke
  File "MediaLibraryPickerDataSource.m", line 189, in -[MediaLibraryPickerDataSource notifyObserversWithIncrementalChanges:removed:inserted:changed:moved:]
  File "MediaLibraryPickerDataSource.m", line 519, in -[MediaLibraryPickerDataSource controllerDidChangeContent:]
  File "main.swift", line 7, in main
...
(32 additional frame(s) were not displayed)
```

---

See also discussion in https://github.com/wordpress-mobile/WordPress-iOS/issues/19505 which, according to how Sentry groups issues, is an instance of this one.

**Comment by mokagio** [comment]
Possibly related with:

- https://github.com/wordpress-mobile/WordPress-iOS/issues/10073

Not to be confused with:

- https://github.com/wordpress-mobile/WordPress-iOS/issues/15370
- https://github.com/wordpress-mobile/WordPress-iOS/issues/15368

**Comment by twstokes** [comment]
- This is currently affecting a low number of users on `20.8` in the App Store.
- I can only reproduce in `trunk` (as pointed out in [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/19505)) after commit https://github.com/wordpress-mobile/WordPress-iOS/commit/fcbb9e025a28d5aafecddcf5b128a6dbb4d591ed from https://github.com/wordpress-mobile/WordPress-iOS/pull/19433.

cc @crazytonyli for any insight

**Comment by crazytonyli** [comment]
@twstokes Thanks for providing these very helpful details, much appreciated! I'll have a look at this issue today.

Using `NSPersistentContainer`'s context objects (which is what the "new CoreData context strucuture" feature flag does) has exposed a few implementation issues in features that use `NSFetchedResultController`, so I won't be surprised this issue falls into the same category given the stacktrace shared [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/19505#issuecomment-1289917145).

**Comment by jkmassel** [comment]
This only happens in very old versions of the app, so it can be closed.
