### ISSUE TITLE
Disconnect from WordPress.com doesn't work properly

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#19501]
### Expected behavior
When My Site → Jetpack Settings → Manage Connection → "Disconnect from WordPress.com button" is tapped, the site should be closed, and the site picker screen should display. 

### Actual behavior
- When My Site → Jetpack Settings → "Disconnect from WordPress.com button" is tapped, it returns "Jetpack Settings" screen. The "Disconnect from WordPress.com" button is still enabled, and it doesn't work when tapped.
- It displays an error message when tapped again after the first tap.
- Stats screen shows error messages. It's reported in https://github.com/wordpress-mobile/WordPress-iOS/issues/7183
- When the site list is refreshed, the disconnected site is closed automatically.

https://user-images.githubusercontent.com/2471769/197395214-86a20f6e-4b09-4bfd-b419-4ede55dbda00.mp4

### Steps to reproduce the behavior
1. Launch the WP app.
2. Select a site with Jetpack plugin installed.
3. Tap My Site → Jetpack Settings → Manage Connection → "Disconnect from WordPress.com button". After a while, it will return to the "Jetpack Settings" screen.
4. Tap Manage Connection again. Notice the "Disconnect from WordPress.com button" is still enabled.
5. Tap "Disconnect from WordPress.com button". Notice the error message.
6. If you use a phone navigate back to My Site and open the Stats screen. If you use an iPad, tap the Stats screen from the left menu.
7. Notice error messages.
8. Open the site chooser screen.
9. Refresh the site list by pulling it down.
10. Notice your disconnected site is lost from the list and closed.

**Comment by staskus** [comment]
I changed the priority from `[Pri] High` to `[Pri] Medium` since the issue happens in rare cases and has a workaround (once the site list is refreshed).
