### ISSUE TITLE
Stats are 0 when minimizing and re-opening the app

### ISSUE THREAD

**Issue by joashrajin** [wordpress-mobile/WordPress-iOS#19528]
### Expected behaviour

The stats should show the correct information, even when multitasking and switching between apps

### Actual behaviour

The views stat reverts to 0 in some cases

### Steps to reproduce the behaviour

- Go to Stats > Days, then switch between a couple of days
- Minimize the app (go back to the app launcher), then go back to the WordPress app
- It may take a few attempts, but switching between the dates will show you 0 views

https://user-images.githubusercontent.com/16253818/198267409-48b5488c-8ede-4bcd-b731-4156e279a3af.mov

**Comment by tiagomar** [comment]
I couldn't reproduce this issue but I noticed that the Date moves from `24 Oct 2022` to `25 Oct 2022`. It's not possible to determine what the stats were for `25 Oct 2022` at the time the video was taken, but the highlighted stack didn't move and clearly indicates more than `0`.

<img width="907" alt="image" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/42008628/27bdfd45-5139-43f8-b88c-f85314e0275e">

**Comment by staskus** [comment]
I couldn't reproduce issues anymore. There were many internal issues in Stats throughout the last period. These issues are likely resolved.
