### ISSUE TITLE
Stats widgets added multiple times are tracked only once

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#19534]
### Expected behavior

Tracks should detect each time a Stats widget is added to the device home screen.

### Actual behavior

Tracks only detects the first time a Stats widget is added to the device home screen. Subsequent additions of the same widget are not tracked 

### Steps to reproduce the behavior
1. Add a Stats widget to the home screen
2. Add another Stats widget of the same type 
3. Check tracks and you'll see only one `wpios_today_home_extension_widget_updated` event fired (the prefix will be `jpios` if testing from the Jetpack for iOS app)

### Additional info

First reported in https://github.com/wordpress-mobile/WordPress-iOS/pull/19526#pullrequestreview-1160477021

**Comment by staskus** [comment]
@guarani, thanks for creating an issue!

This might be intentional since the widget types are saved to `UserDefaults` in `Tracks+StatsWidgets` to avoid tracking the same Widget twice.

**Comment by guarani** [comment]
Thanks for sharing that thought. It might be so. I'd assumed the event would track each new addition of a widget to allow us to know how often users might add multiple This Week stats widgets (each monitoring a different site's stats).

I'm not sure what the correct behavior is, so I've lowered the priority here for now.

**Comment by guarani** [comment]
I'm going to close this since it seems acceptable to only track each widget type once as they're added. If we have a need to track it differently we can always revisit.
