### ISSUE TITLE
Replace `if let strongSelf = self` and `if let self = self` checks in closures with modern `if let self`

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#19549]
There's nothing _wrong_ with using `if let strongSelf = self` or `guard let strongSelf = self`. However, `strongSelf` makes the code a bit more cumbersome to read. 

`strongSelf` or any other name different from `self` used to be required when we couldn't use that keyword in an assignment within a closure, but we now can and do so in various places, e.g.

https://github.com/wordpress-mobile/WordPress-iOS/blob/939521f2af12485d1ba2932bccf473b59311fcd1/WordPress/Classes/ViewRelated/Stats/Insights/SiteStatsInsightsTableViewController.swift#L512-L514

We should remove the leftover instances of this old pattern and keep the codebase homogeneous.

**Update**, we can actually use [an even better syntax](https://github.com/wordpress-mobile/WordPress-iOS/issues/19549#issuecomment-1302690610):

```swift
if let self {
  ...
}
```

I renamed the issue accordingly to include acting on both `strongSelf = self` and `self = self`.

**Comment by twstokes** [comment]
👋 @mokagio - how do we feel about [SE-0345](https://github.com/apple/swift-evolution/blob/main/proposals/0345-if-let-shorthand.md) shorthand in these cases? We may need to address it in the [style guide](https://github.com/wordpress-mobile/swift-style-guide) either way.

**Comment by mokagio** [comment]
I didn't know about [SE-0345](https://github.com/apple/swift-evolution/blob/main/proposals/0345-if-let-shorthand.md) or about the [style guide](https://github.com/wordpress-mobile/swift-style-guide).

Love them both. Thanks!

Yes. We should definitely adopt the new syntax because it's more compact and clear, as well as updating the style guide to mention it.

**Comment by mokagio** [comment]
I just noticed that a recent SwiftLint version add a rule for this: https://github.com/realm/SwiftLint/issues/4202 🦾
