### ISSUE TITLE
Jetpack Focus: Disable Local Notifications

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#19560]
Part of https://github.com/wordpress-mobile/WordPress-iOS/pull/19531

This task can be branched from and merged into https://github.com/wordpress-mobile/WordPress-iOS/pull/19531 to support disabling both local and remote notifications.

### Task

Disable local notifications on the WordPress app when Jetpack is installed and has notifications enabled.

https://github.com/wordpress-mobile/WordPress-iOS/pull/19531 implements disabling of push notifications using `NotificationServiceExtension`. However, this extension is only triggered by remote notifications and cannot be used to filter local notifications.

#### Potential solution

Use `wordPressNotificationsEnabled` flag created in https://github.com/wordpress-mobile/WordPress-iOS/pull/19531 and avoid scheduling **new** `WordPress` local notifications based on this flag. 

This is only a potential solution, any solution that allows to disable local `WordPress` notifications from `Jetpack` app and avoid showing already scheduled local notifications is welcome.

**Comment by mokagio** [comment]
Pushing to 21.3. See also [this comment on the PR linked in the description](https://github.com/wordpress-mobile/WordPress-iOS/pull/19531#issuecomment-1311717844)
