### ISSUE TITLE
Hide Scan Login Code when logged into an account with 2FA

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-iOS#19567]
### Expected behavior
Expected not to see this option when logged into an account with 2FA, since Scan Login Code is not available for 2FA-enabled accounts.

### Actual behavior
Scan Login Code appears, leading me to believe I can use it. Then, when I try to use it to login to a WordPress.com site, I get a "Could not validate the log in code" message. This message encourages me to try scanning again.

### Steps to reproduce the behavior
1. Login to the Jetpack app with a WordPress.com account that has 2FA enabled.
2. In a web browser, open a browser or incognito tab where you're not logged into WordPress.com.
3. Head to WordPress.com > Login > Login via the Mobile App. Note the QR code is shown.
4. In the app, head to Me > Scan Login Code, and scan that QR code.
5. Note that validation fails

Suggestion: Remove "Scan Login Code" from Me section when logged into an account with 2FA enabled.
Alternative: Adjust the "Could not validate" message to state that you cannot use QR code login for an account with 2FA enabled.

**Comment by thehenrybyrd** [comment]
User report in 5719223-zd-woothemes (Android), the user was unable to login via QR code, but doesn't know why.

**Comment by vanessamaartinstt** [comment]
Also reproducible on JP iOS app version 21.3.0.0
Iphone 14 Pro Max
iOS version 16.1.1
