### ISSUE TITLE
Blank screen when selecting media when photo permission is missing

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#19576]
### Expected behavior

When adding a photo from the device, the app should show an appropriate message if photo permission is lacking. 

### Actual behavior

A message is shown when adding images via Media (My Site tab → Menu → Media), but **not** when adding media via the block editor.

### Steps to reproduce the behavior

1. Ensure the app does not have access to photos:
  a. Go My Site tab → Menu → Media
  b. Go to add media, but deny the app permission
2. Now open a new post
3. Add the image block 
4. Tap "Choose from device"
5. Notice the blank screen
6. Optionally, notice that an appropriate message is shown on the media screen
  a. Open My Site tab → Menu → Media
  b. Add media
  c. Notice the app prompts you to enable photo permission in settings

**Comment by guarani** [comment]
First reported by @sourourn.

**Comment by kean** [comment]
Fixed in the scope of https://github.com/wordpress-mobile/WordPress-iOS/issues/21190
