### ISSUE TITLE
Publish content not possible anymore on self-hosted site

### ISSUE THREAD

**Issue by smezger** [wordpress-mobile/WordPress-iOS#19589]
### Expected behavior
* Create e.g. an article (with or without) media in the app and publish it. 
* Result it works

### Actual behavior
* Create e.g. an article (with or without) media in the app and publish it. 
* Result it does not work and simply states upload failed

### Steps to reproduce the behavior
* see above

### Additional information
* worked before 
* tested it with two different self-hosted instances on different servers/hosters. Same result for both sites
* Same workflow on an Android device with Wordpress Android is working

##### Tested on [device], iOS [version], WPiOS [version]
iPohne 11 Pro, iOS 16.1.1, Wordpress 21.0

**Comment by phubbard** [comment]
This is also blocking me. Self-hosted site, certbot SSL, iPad 16.1.1, latest app version as of today. Just says 'Upload failed' but if I post via the browser it works every time.

**Comment by twstokes** [comment]
I can confirm this as well running a clean install from tag `21.1` (and I suspect `trunk` as well).

**Environment:**
- Self-hosted site, no Jetpack connection
- One author

The debug output shows an invalid author ID:

```
<methodResponse>
  <fault>
    <value>
      <struct>
        <member>
          <name>faultCode</name>
          <value><int>404</int></value>
        </member>
        <member>
          <name>faultString</name>
          <value><string>Invalid author ID.</string></value>
        </member>
      </struct>
    </value>
  </fault>
</methodResponse>
```

**Comment by twstokes** [comment]
👋 @smezger and @phubbard - until we can get this sorted on the self-hosted side, [connecting the site to Jetpack](https://jetpack.com/) should unblock you since it uses a different API.

**Comment by smezger** [comment]
@twstokes  Thanks for looking at it and the workaround you have provided! 👍🏻

**Comment by twstokes** [comment]
**Another possible workaround until we get this resolved, which doesn't involve Jetpack:**

If this is a single-user site, add another user to it so that the author picker appears in the Post settings. Explicitly choosing the author fixes it for me. The app may need to be restarted to populate the author list, and your user may need to be admin-level.

<img src="https://user-images.githubusercontent.com/2092798/204027400-12b38653-a0e0-414c-b51a-088a32c21183.png" width="350px" />

**Comment by phubbard** [comment]
@twstokes thanks, that works. The Jetpack is unavailable as I'm on Debian and they're still on the 5.7.8 release. This gives me a workaround for now, thank you very much.
