### ISSUE TITLE
Prompt the user to confirm publishing a post without a title

### ISSUE THREAD

**Issue by fluiddot** [wordpress-mobile/WordPress-iOS#19596]
Posts can be published without a title, however, in most cases, this might be performed by the user by mistake. Not having a title has downsides, especially related to SEO, as the title is used in several parts of the post like to form the Permalink and social meta tags.

An enhancement to incorporate in the publishing flow is to display a confirmation dialog when the user tries to publish a post without a title. The description of the dialog will inform the user about the benefits of setting a title, and will display two options:
- **Set title:** This option will stop the publishing flow and will focus on the title's text input.
- **Skip:** This option will continue with the publishing flow.

**Comment by mitaligondaliya** [comment]
@fluiddot Can I go ahead and start working on this issue?

**Comment by fluiddot** [comment]
Hey @mitaligondaliya 👋 , thanks for reaching out and offering your help to address the issue. We re-evaluated the issue and considered dropping the enhancement in favor of keeping the publishing flow simple. Hence, I'm closing the GitHub issue.

Feel free to check other [Good First Issues](https://github.com/wordpress-mobile/WordPress-iOS/labels/Good%20First%20Issue) we have in the repository, if you'd like to contribute to the project. Thanks 🙇 !
