### ISSUE TITLE
The "In reply to your comment" text should link to the comment in question

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#1960]
When you receive a notification for a reply to a comment you've made, the top of the screen has a blurb that says "In reply to your comment" and the "your comment" portion is clickable. This takes the user to the post in question, not the comment the user originally made. We should adjust this so as to point back to the comment the user made.

**Comment by jleandroperez** [comment]
Closing this issue in favor of #2549
