### ISSUE TITLE
Value for key `WPSplitViewPreferredDisplayModeRestorationKey` is not an object

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#19637]
While working on #19636, I notice the following TSAN warning:

> *** `-[UIStateRestorationKeyedUnarchiver decodeObjectForKey:]`: value for key (`WPSplitViewPreferredDisplayModeRestorationKey`) is not an object. This will become an error in the future.

![image](https://user-images.githubusercontent.com/1218433/203375454-7cf5a36b-7e74-4153-b613-8d90e63504d1.png)

Logging it here as I don't have time to investigate right now. cc @crazytonyli

**Comment by mokagio** [comment]
I'm going to close this under the assumption that the issue has either been addressed as the result of some other work, or that it will resurface again in the future.

Also, I searched for `WPSplitViewPreferredDisplayModeRestorationKey` in this and other repos and did not get any match.

**Comment by kean** [comment]
`WPSplitViewController` and all of the related code is gone.
