### ISSUE TITLE
[Jetpack Migration Flow] Create prompt to update WordPress App

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#19641]
## Description

Subtask of https://github.com/wordpress-mobile/WordPress-iOS/issues/19640

Create a view that will be shown to the user when we determine that the WordPress App should be updated before a migration can take place.

<img src="https://user-images.githubusercontent.com/2092798/203454366-2c64e022-618d-411a-b7bd-f8411a71187f.png" width="350px" />

**Comment by antonis** [comment]
As discussed this issue is dropped for now (ref: `p1669743219444469-slack-C046L7LPV0F`)
