### ISSUE TITLE
[Jetpack Migration Flow] Handle flow when WordPress is compatible but hasn't been loaded yet

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#19640]
## Description

**For users who:**
- Have the WordPress app installed that is capable of migrating to Jetpack
- Have not loaded the WordPress app yet (to run the pre-flight)
- Have not authenticated the Jetpack app

We should handle the flow by sending the user to the WordPress app and back to the Jetpack app.

**Caveat:** We currently cannot detect if the user hasn't authenticated the WordPress app, meaning some users will be sent to the app, but there's nothing to do.

## Tasks

- [x] #19641
- [x] #19642
- [x] #19656
- [x] #19710 - Send user to the WordPress app to run the migration pre-flight 
- [x] #19710 - Send analytics event to log whether the WordPress app was migratable or not (related: https://github.com/wordpress-mobile/WordPress-iOS/pull/19692)

## Logic

![Jetpack WordPress compatibility 4](https://user-images.githubusercontent.com/2092798/204646287-a971bbd2-9abf-4ea2-86c1-633479615b35.png)

**Comment by antonis** [comment]
As discussed we won't prompt the user to update for now (ref: `p1669743219444469-slack-C046L7LPV0F`). 
@twstokes My understanding from the new flow diagram is the the issue is repurposed. Please update the title/description if that is the case or close.
