### ISSUE TITLE
[iOS] Stats: Days tab doesn't display today's data after backgrounding the app and returning the next day

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#19688]
### Expected behavior

Stats days view should reload after coming back to the app the next day and correctly display today's data in labels and graph.

Related issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/18260

### Actual behavior

Stats days view shows 0s and an outdated graph after coming back to the app the next day. Pull to refresh doesn't help.

**Workaround:** Switch between "Weeks and Days" tab

### Steps to reproduce the behavior

1. Set iPhone clock to yesterday
2. Fresh install WordPress and login to account that has stats
3. Open Stats
4. Open Days tab
5. Background the app
6. Set iPhone clock back to today
7. Come back to Stats
8. Notice that yesterday's date is selected
9. Select today by clicking ">" icon
10. Notice 0s are shown and the graph still displays yesterday's data
11. Try pull to refresh
12. Notice that the view still didn't refresh
13. Switch between the "Weeks" and "Days" tab
14. Notice that now the "Days" tab displays today's data correctly

https://user-images.githubusercontent.com/4062343/204784611-223ecfdd-346b-4192-9306-6f6e05f53aae.mov

**Comment by sla8c** [comment]
@staskus This is definitely stats related but it's not a part of stats revamp I think? Maybe it should not be a part of the stats revamp github project and is just a stats bug in isolation?

**Comment by staskus** [comment]
> @staskus This is definitely stats related but it's not a part of the stats revamp I think? Maybe it should not be a part of the stats revamp github project and is just a stats bug in isolation?

@sla8c you are right that this is not directly part of the project. I wanted to include it as a part of the Stats fixing effort but yes, technically it's a Stats bug in isolation.
