### ISSUE TITLE
Stats widgets not auto-updating to fetch the latest site stats 

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#19685]
### Expected behavior

Stats widgets should periodically refresh to show current data.

### Actual behavior

Stats widgets don't seem to ever update after they've been added.

### Steps to reproduce the behavior
1. Add a widget to display today's views & visitors (any widget should suffice)
2. Configure it to display for a particular site
3. Make note of the view & visitors count displayed on the widget
4. Generate some page views for that site (e.g. load the page in another browser)
5. Return to the widget after waiting a considerable time (e.g. one hour) 
6. Notice that the widget's views & visitor values are unchanged

### Additional info

First reported in pbArwn-5Da-p2#comment-7034 after an app review reported the issue:

> No real issues except the new widgets are terrible on iPhone. They do not update/refresh with current traffic data like the old ones do and imo look worse.

##### Tested on iPhone 11, iOS 16, WPiOS 21.1

**Comment by staskus** [comment]
Test note:

https://user-images.githubusercontent.com/4062343/204799704-fd65d814-d583-49e4-9950-6aaef40228e9.mo

I connected the debugger and after some time `getTimeline` method was triggered, `service.fetchStats(...)` was called, and the widget refreshed with the newest data.

Investigating further.

**Comment by staskus** [comment]
### Why the issue may not be reproducible with debugger

From https://developer.apple.com/documentation/widgetkit/timelineprovider:
> WidgetKit does not impose this limit when debugging your widget in Xcode. To verify that your widget behaves correctly, test your app and widget’s behavior outside of Xcode’s debugger.

Worth investigating if it's a budget problem:

> A widget’s budget applies to a 24-hour period. WidgetKit tunes the 24-hour window to the user’s daily usage pattern, which means the daily budget doesn’t necessarily reset at exactly midnight. For a widget the user frequently views, a daily budget typically includes from 40 to 70 refreshes. This rate roughly translates to widget reloads every 15 to 60 minutes, but it’s common for these intervals to vary due to the many factors involved.

**Comment by guarani** [comment]
Thanks for investigating this, @staskus! 
I've set up another test:
- Installed the "This week" Stats widget
- Noted 171 views today (Nov 30) for a particular site
- Will check tomorrow if it has been updated
- I'll use the app a little today and this should encourage Apple to give it more "budget"

**Comment by staskus** [comment]
> Thanks for investigating this, @staskus! I've set up another test:
> 
> * Installed the "This week" Stats widget
> * Noted 171 views today (Nov 30) for a particular site
> * Will check tomorrow if it has been updated
> * I'll use the app a little today and this should encourage Apple to give it more "budget"

Thanks, @guarani. Let me know the results.

I personally got the updates coming on the device without the debugger, albeit not as quickly as with the debugger connected. Maybe it's a coincidence. I think we could increase the refresh interval from 60 minutes to at least 30 minutes. It'll go in the range of allowed refreshes 40-70 for frequent users. 

This would be a change:

https://github.com/wordpress-mobile/WordPress-iOS/pull/19694

**Comment by guarani** [comment]
> Thanks, @guarani. Let me know the results.

I checked back today and the widget did update from 171 to 187 views for Nov 30, so it seems to be working there. 

 I think we could increase the refresh interval from 60 minutes to at least 30 minutes. It'll go in the range of allowed refreshes 40-70 for frequent users.

Thanks! This seems like a good idea.
