### ISSUE TITLE
[iOS] Stats: This week's views numbers don't match the web and Android

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#19731]
This week's views (last 7 day) numbers don't match the web and Android.

![Image](https://user-images.githubusercontent.com/4062343/205659379-38a50ce8-4438-43c3-8fc1-fc389e4982eb.png)

**Comment by sla8c** [comment]
@staskus I took a look at this issue as well + compared all the platforms and how the aggregate the last 7 day numbers.  I've compiled all the information in this google sheet [here](https://docs.google.com/spreadsheets/d/1Olc1Fo8WOOTtUYdLOwXU6qcbt5SvN1f0AoyRJ16IxOc/edit?usp=sharing) cc @irfano @ravishanker for web, iOS and Android.

In summary it looks like:

- web uses the last 8 days ago through yesterday for its last 7 day calculation
- Android is aggregating all 8 days (note I used Android JetPack production so perhaps this has changed on trunk?)
- iOS is currently using 7 days ago through today

I will make the change to make iOS consistent with the web but just wanted to double check that's the count approach we want to take for consistency?

**Comment by staskus** [comment]
Thank you @sla8c, great findings! 

It would be beneficial to understand the reasoning behind the Web as well since it doesn't show the data of the current date. 

Android is the only one that looks incorrect and I would consider as a bug.

I could find arguments for both iOS and Web.

**Comment by staskus** [comment]
@sla8c, I did similar [calculations for Total Likes](https://docs.google.com/spreadsheets/d/17ZGNQPt0xNCoOTgaEHaki0vDnNvcvEPYMDYA6Qy1CZY/edit#gid=0), and I see that both iOS and Android use 7-day calculation (including today). The web continues to calculate using 7-day calculation (excluding today). 

I think the iOS way is more consistent than Android. iOS uses the same calculation logic for different elements in insights. I don't see a clear change that would make sense to make on iOS.

I'm moving this issue away from the project iteration as it requires more discussions.

p1672416589393599-slack-C02UJ9192TC

**Comment by staskus** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/19882
