### ISSUE TITLE
Media Library: Items jump around on refresh

### ISSUE THREAD

**Issue by joashrajin** [wordpress-mobile/WordPress-iOS#19737]
### Expected behaviour

The items (videos and images) should not move around on refresh and should stay in their position. 

### Actual behaviour

The videos move around each time you refresh. Images also jump around on scroll, but it isn't behaving the same as videos and isn't as bad.  

### Steps to reproduce the behaviour

- Ensure you have videos and images in your media library
- Go to My Site > Media, then Pull Down to Refresh
- Notice the issue

https://user-images.githubusercontent.com/16253818/205853344-bbdf1521-0d3c-4026-9883-9c31eda267c6.mp4

##### Tested on [iPhone 14 Pro Max], iOS [16.1.2], WPiOS [21.2.0.4]

5758350-zd-woothemes

**Comment by erricgunawan** [comment]
Another case from 6249955-zen (translated):

> 1. I emptied the cashe memory.
> 2. I logged out and logged in again
> 3. I uploaded a new image in Media
> 4. The first images are in order in both Media and WordpressMedia. 👍🏻
> 5. I check that all other images are in Media as it looks like the app moves images from time to time. They change places in their locations.
> 6. Discover that some pictures are missing (see attached picture). It's just a black box where they should be.
> 7. Going to the "animals" page in JETPACK, the pictures of the cats are not there either. ( see attached picture)
> 8. I go into Android and look in Media, there are the pictures! ( see attached picture)
> 9. I go to WordPress on Chrome and the pictures are there too! ( see attached picture)

Note: pictures are not included here since it may contain personal info

> Jetpack for iOS 22.1 (22.1.0.3)...
Device model: iPad Pro 11-inch 2nd-gen (WiFi) (iPad8,9)
OS:        iPadOS, 16.4.1
Language:  sv-SE

**Comment by kean** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/21210
