### ISSUE TITLE
iOS - Update compatible version checks

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#19743]
## Description
Since we won't ship the feature in `21.3` we should make sure that the compatibility checks (introduced with https://github.com/wordpress-mobile/WordPress-iOS/pull/19680) are still relevant in the next version. If not we should update them accordingly.

**Comment by dvdchr** [comment]
After checking, we won't need to adjust the compatibility check logic for 21.4 since we are checking against supported URL schemes instead of the app version.

I'm closing this issue for now, but feel free to reopen if I missed anything! 🙂

**Comment by twstokes** [comment]
> make sure that the compatibility checks

Good call. It's why I went with a `wordpressmigration+v1` namespace approach instead of pinning it to an app version. 😅
