### ISSUE TITLE
`'init(documentTypes:in:)'` was deprecated in iOS 14.0

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#19745]
Bumping the deployment target to iOS 14.0, 9f588258b4, resulted in a bunch of warnings:

> `'init(documentTypes:in:)'` was deprecated in iOS 14.0

Example call sites are https://github.com/wordpress-mobile/WordPress-iOS/blob/eb7da677caf8256a881e8037034900b7eb8117dc/WordPress/Classes/ViewRelated/Media/StockPhotos/AztecMediaPickingCoordinator.swift#L75 and https://github.com/wordpress-mobile/WordPress-iOS/blob/eb7da677caf8256a881e8037034900b7eb8117dc/WordPress/Classes/ViewRelated/Gutenberg/Utils/GutenbergFilesAppMediaSource.swift#L17

The new [`UIDocumentPickerViewController`](https://developer.apple.com/documentation/uikit/uidocumentpickerviewcontroller) APIs don't have a mode parameter, but that shouldn't be a problem for us, since:

- As far as I can see, all our usages are `.import` (opening)
- There are now dedicated inits for opening vs exporting documents:

<img width="874" alt="image" src="https://user-images.githubusercontent.com/1218433/205958239-c592534c-e0d3-4485-b62f-9e2897a472d6.png">

I haven't looked into updating the inits because I don't have context around what we want to do with that code.

**Comment by kean** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/22286 in the scope of https://github.com/wordpress-mobile/WordPress-iOS/issues/20860.
