### ISSUE TITLE
Editor: Adding content via microphone

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/WordPress-iOS#19858]
### Expected behavior
That instead of typing that I would be able to post via the microphone

### Actual behavior
The content gets added as expected but the moment. I do anything else it disapears. 

### Steps to reproduce the behavior
Go to the editor. 
Use the microphone button to add text. Press space. Notice that the content is gone. 

##### Tested on iPhone 11 Pro, WPiOS 21.2

**Comment by tiagomar** [comment]
It's now fixed.

<details><summary>Video</summary>
<video width="300" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/42008628/35ebd77c-70dc-4d83-b375-0706fca03938">
</details> 

_Tested on iPhone 13, iOS 16.5, Jetpack iOS 22.7_
