### ISSUE TITLE
Jetpack Migration Flow: Finish button hides delete prompt with zoomed display or large dynamic type

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-iOS#19859]
### Expected behavior
Expected the "delete the WordPress app" prompt to appear clearly, or space between the "we've transferred..." text and the WordPress app icon to be reduced.

### Actual behavior
When using Dynamic Type at larger sizes, or when using the iOS's "zoomed" display setting, the WordPress app icon and deletion prompt are hidden by the "finish" button.

### Steps to reproduce the behavior
1. In the Settings App > Display & Brightness, set Text Size to a large Dynamic Type setting. Or, set Display Zoom to "Zoomed".
2. Complete the content migration flow and stop on the last screen.
3. Note the "Finish" button partly or completely covers the WordPress app icon and deletion prompt.

<img src="https://user-images.githubusercontent.com/15107387/211003222-4139906a-9cd0-4546-bdfd-4f6276120368.PNG" width="50%">

**Comment by tiagomar** [comment]
It's fixed now.

<img width="348" alt="image" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/42008628/7f614a6c-f84d-4708-be7b-4cba56b8e338">
