### ISSUE TITLE
Jetpack Migration Flow: Transfer App Icon Settings

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-iOS#19861]
### Expected behavior
After completing the Jetpack Content Migration flow, I expected my Jetpack app icon to be the same color as I'd selected in the WordPress app.

### Actual behavior
App icon setting is not transferred.

### Steps to reproduce the behavior
1. Delete and reinstall the Jetpack app
2. Set a fun app icon in the WordPress app
3. From the WordPress app, initiate and complete the Jetpack Content Migration Flow
4. Note that the Jetpack app does not get your fun app icon color, though the options are available in Me > App Settings

![IMG_4311](https://user-images.githubusercontent.com/15107387/211005193-b2cc8d20-69f1-4f5c-98a8-7c6473ecf5ba.PNG)

**Comment by jkmassel** [comment]
The icon can only be changed by the user, this can't be done programmatically. Closing.
