### ISSUE TITLE
[Jetpack Content Migration Flow] Gravatar not shown after migration flow if started from self-hosted 

### ISSUE THREAD

**Issue by thehenrybyrd** [wordpress-mobile/WordPress-iOS#19867]
### Expected behavior
I expected my Gravatar to show in the "Me" icon spot in the Jetpack app after completing the content migration flow.

### Actual behavior

After starting the flow with a pure self-hosted (no Jetpack) site selected, the “Me” icon (Gravatar) isn’t displaying (at the top of home/menu) after the flow. After a restart, the “Me” icon displays, but not without a flash of default icon. 
With further testing, I found that restarting while a self-hosted site was selected resulted in default icon, while restarting with a WordPress.com site selected resulted in Gravatar (with a quick flash of default). Restarting again with a self-hosted site selected brought back the default icon.
This occurred while logged into a WordPress.com account, with some pure self-hosted sites logged in as well.

### Steps to reproduce the behavior
1. Login to the WordPress app with a WordPress.com account
2. Now, tap "Add Site" and connect a self-hosted site that doesn't have the Jetpack plugin connected
3. Make sure that self-hosted site is selected
4. Initiate the Content Migration flow from within the WordPress app
5. Note that after the flow, you see the default "Me" icon instead of your Gravatar

https://user-images.githubusercontent.com/15107387/211015964-73d89a96-d05b-4134-98f1-5d1018c4f2a6.mov

**Comment by tiagomar** [comment]
This issue is possibly not caused by the migration as it can be reproduced straight into Jetpack. 
More details here: p5T066-3Ue-p2#comment-14541.
