### ISSUE TITLE
Author selection for Pages should not include users with roles lower than Editor

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#19886]
### Expected behavior
List doesn't contain users who have a role lower than Editor.

### Actual behavior
List contains users who have a role lower than Editor, although they cannot technically publish Pages.

When tapping **Publish**:

- **Self-hosted sites** without a WordPress.com connection do not throw an error.
- **WordPress.com sites** throw an error from the backend that is presented by the user interface.

```
Error Domain=WordPressKit.WordPressComRestApiError Code=2 "Assigned author cannot publish post." UserInfo={NSLocalizedDescription=Assigned author cannot publish post., WordPressComRestApiErrorCodeKey=unauthorized, WordPressComRestApiErrorMessageKey=Assigned author cannot publish post.}
```

<img src="https://user-images.githubusercontent.com/2092798/211725080-19face15-4045-49f4-8341-1ba4550d5aba.png" width="300" />

### Steps to reproduce the behavior

**Prerequisites:** Two users exist on a blog - one Administrator role, and one lower than Editor (e.g. Author or Contributor).

- [WordPress.com roles](https://wordpress.com/support/user-roles/)
- [WordPress.org roles](https://wordpress.org/support/article/roles-and-capabilities/)

1. Log into the app as the Administrator user
2. Tap the FAB and select Site page to create a page
3. Choose any layout
    - ℹ️ If the Blank Page layout was chosen, populate a title
4. In the Page settings tap Author
5. **Observe:** The list of users

### Notes

WordPress.com's web interface (Calypso) allows one of these users to be set and for the Page to be published without error.

**Comment by twstokes** [comment]
WPAndroid issue: https://github.com/wordpress-mobile/WordPress-Android/issues/17739

**Comment by kean** [comment]
This now works better as the error message contains the reason why it fails, which I think is an acceptable solution:

– less logic to be hardcoded in the app
– no guessing why a user is missing from the list

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/ac420c1c-51f6-4ad2-a1ab-9d278340db21" width="340px">
