### ISSUE TITLE
Stats Revamp: Use Jetpack green color for charts

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#19883]
On JPiOS, the Views & Vistors graph on the Stats Insights tab uses WordPress blue as the accent color. 

It would look nicer if we used the Jetpack green color - especially since the other Stats tabs use Jetpack green for the graphs.

<img src="https://user-images.githubusercontent.com/6711616/211573269-ca742852-207d-46d1-93f1-33654800e76f.png" width=200> | <img src="https://user-images.githubusercontent.com/6711616/211574896-e009f424-6d40-40cd-9b1a-d35ef0db93e2.png" width=200>
-- | --

**Comment by momo-ozawa** [comment]
@staskus @guarani 👋 

I created the [same issue for Android](https://github.com/wordpress-mobile/WordPress-Android/issues/17418) a while back, and noticed I hadn't done the same for iOS.

**Comment by staskus** [comment]
Closing since it was an intentional decision to keep the graph blue for Jetpack.

p1673863317990199/1673461455.583419-slack-C042DG1CHJN
