### ISSUE TITLE
Activity logs should be cleared

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#19913]
### Expected behavior
Activity Logs should be removed after logging out.

### Actual behavior
After logging out, activity logs aren't being removed. Internal discussion: p1673653812673169-slack-C011BKNU1V5

### Steps to reproduce the behavior
1. Launch the app and log in.
2. Use the app for a while.
3. Log out and log in with a different account.
4. Open Me screen by tapping your profile icon on the top of the screen.
5. Tap "Help & Support"
6. Tap "Activity Logs".
7. Look inside your saved logs and notice your logs from your logged out account is visible.

##### Tested on iPhone 14 Pro Simulator, iOS 16.2, WPiOS 21.5

**Comment by guarani** [comment]
I gave this a high priority and removed the Activity Log label because it seems to refer to Jetpack Activity Log (not the app's own activity log).
