### ISSUE TITLE
Create a Forum Support card on Help Screen

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#19978]
Parent: https://github.com/wordpress-mobile/WordPress-iOS/issues/19968

1. Create a Forum Support card on Help Screen
2. Replace a current support card
3. Open new mobile forums when tapping on the CTA

![Image](https://user-images.githubusercontent.com/4062343/214255330-88ea0446-d04e-45ea-bda7-1dde1915e682.png)

**Comment by guarani** [comment]
I think this is done now that https://github.com/wordpress-mobile/WordPress-iOS/pull/19993 is merged.
