### ISSUE TITLE
Total cards show "higher" word instead of "lower"

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#19995]
### Expected behavior
When the change is negative, total cards should say `-1 (-100%) lower than the previous 7-days`.

### Actual behavior
When the change is negative, total cards should say `-1 (-100%) higher than the previous 7-days`.
<img  src="https://user-images.githubusercontent.com/2471769/214700948-22fb50d8-06cf-4864-af41-9724812e5833.PNG" height=600>

### Steps to reproduce the behavior
1. Launch the JP and login.
2. Navigate to "My Site → Stats".
3. Ensure the Total cards are on your screen. If not, add them via the ⚙️ button at the top of the screen.
4. Verify that positive changes should say `... higher than`, negative changes should say `... lower than`.

**Comment by staskus** [comment]
@irfano 

Thanks! I'd like to get the fix into 21.6, if possible.

Also, the light font here is incorrect, it should be dark. Does it always appear to you like this?
<img width="202" alt="image" src="https://user-images.githubusercontent.com/4062343/214781196-0936e242-c20f-4a18-bcb3-5b9a5bee6b20.png">

**Comment by irfano** [comment]
> @irfano
> 
> Thanks! I'd like to get the fix into 21.6, if possible.
> 
> Also, the light font here is incorrect, it should be dark. Does it always appear to you like this? <img alt="image" width="202" src="https://user-images.githubusercontent.com/4062343/214781196-0936e242-c20f-4a18-bcb3-5b9a5bee6b20.png">

Yes, I opened the issue https://github.com/wordpress-mobile/WordPress-iOS/issues/20001.
