### ISSUE TITLE
Crash after backgrounding app from Stats screen

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#20006]
### Expected behavior

App shouldn't crash when using Stats.

### Actual behavior

I downloaded the app and opened Stats, then I went off to do other things (after backgrounding the app, I think). Then after some minutes, I can back to my phone which was on the Home Screen and I got the alert that the app had crashed.

<details>
  <summary>Here’s the relevant portion of the crash log</summary>
  <pre>
Last Exception Backtrace:
0   CoreFoundation                	0x1d3a91e38 __exceptionPreprocess + 164 (NSException.m:202)
1   libobjc.A.dylib               	0x1ccc2f8d8 objc_exception_throw + 60 (objc-exception.mm:356)
2   Foundation                    	0x1ce347a28 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 172 (NSException.m:251)
3   UIKitCore                     	0x1d60ab5a0 _UIApplicationDrainManagedAutoreleasePool + 264 (UIApplication+AutoreleasePool.m:171)
4   CoreFoundation                	0x1d3b19d30 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36 (CFRunLoop.c:1789)
5   CoreFoundation                	0x1d3aa2280 __CFRunLoopDoObservers + 532 (CFRunLoop.c:1902)
6   CoreFoundation                	0x1d3b03c50 __CFRunLoopRun + 1048 (CFRunLoop.c:2981)
7   CoreFoundation                	0x1d3b08eb0 CFRunLoopRunSpecific + 612 (CFRunLoop.c:3418)
8   UIFoundation                  	0x1ddfbab54 -[NSHTMLReader _loadUsingWebKit] + 1436 (NSHTMLReader.m:2633)
9   UIFoundation                  	0x1ddfbb708 -[NSHTMLReader attributedString] + 24 (NSHTMLReader.m:3222)
10  UIFoundation                  	0x1ddf787c4 _NSReadAttributedStringFromURLOrData + 6556 (NSAttributedStringAdditions.m:2741)
11  UIFoundation                  	0x1ddf76db0 -[NSAttributedString(NSAttributedStringUIFoundationAdditions) initWithData:options:documentAttributes:error:] + 148 (NSAttributedStringAdditions.m:1442)
12  Jetpack                       	0x100521d90 @nonobjc NSMutableAttributedString.init(data:options:documentAttributes:) + 144 (<compiler-generated>:0)
13  Jetpack                       	0x100521680 0x100228000 + 3118720 (NSAttributedString+StyledHTML.swift:23)
14  Jetpack                       	0x100545a44 specialized static StatsTotalInsightsData.makeTotalInsightsGuideText(lastPostInsight:statsSummaryType:) + 700 (StatsTotalInsightsCell.swift:81)
15  Jetpack                       	0x100543368 static StatsTotalInsightsData.makeTotalInsightsGuideText(lastPostInsight:statsSummaryType:) + 12 (<compiler-generated>:0)
16  Jetpack                       	0x100543368 StatsTotalInsightsCell.rebuildGuideViewIfNeeded() + 104 (StatsTotalInsightsCell.swift:274)
17  Jetpack                       	0x100543368 StatsTotalInsightsCell.traitCollectionDidChange(_:) + 220 (StatsTotalInsightsCell.swift:154)
18  Jetpack                       	0x100543408 @objc StatsTotalInsightsCell.traitCollectionDidChange(_:) + 52 (<compiler-generated>:0)
  </pre>
</details>

### Steps to reproduce the behavior

1. Install app version 21.6 or above (e.g. from `trunk` or TestFlight)
2. Log in an open Stats
3. Background the app
4. Notice the app crashes (100% reproducibility)

**Comment by staskus** [comment]
<img width="931" alt="image" src="https://user-images.githubusercontent.com/4062343/214889633-da169cb1-1fa8-4457-8510-a66ed2e0258f.png">

**Comment by staskus** [comment]
We call this method when the app is in the background, [which causes the crash](https://stackoverflow.com/questions/46881393/ios-crash-report-unexpected-start-state-exception)
