### ISSUE TITLE
start implementing UI testing

### ISSUE THREAD

**Issue by irbrad** [wordpress-mobile/WordPress-iOS#2000]
- [x] investigate options for libraries
- [x] add to project
- [x] write tests for sign in/out

**Comment by irbrad** [comment]
![nooooooo_luke_skywalker](https://cloud.githubusercontent.com/assets/1220715/8150116/9d5febf0-12aa-11e5-9fe0-060155b6ac52.gif)

**Comment by bummytime** [comment]
Hah!
