### ISSUE TITLE
Stats: Date selector buttons for stats can't be seen

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#20004]
### Expected behavior
The date selector buttons should be visible.

### Actual behavior
The date selector buttons can't be seen. 
> **Note**
> System theme is dark, app theme is light.

![IMG_0106](https://user-images.githubusercontent.com/2471769/214830278-d0223bff-7d3b-47b0-9d08-3f4e59752a13.PNG)

### Steps to reproduce the behavior
1. Launch the JP app on your iPad and log in.
2. Open "My Site → Stats".
3. Ensure the "Views & Visitors" or "Total Likes" cards are on your screen. If not, add them via the ⚙️ button at the top of the screen.
4. Open the detail screen of "Views & Visitors" or "Total Likes" cards by tapping the button at the top right of the cards.
5. Notice the date selector button

**Comment by staskus** [comment]
> System theme is dark, app theme is light.

Good observation, that's where issues like these come in. Need to take the "overriding" of system defaults into account.

**Comment by kean** [comment]
It was evidently fixed in one the previous releases, like 25.3.

<img width="1316" alt="Screenshot 2024-09-12 at 2 22 52 PM" src="https://github.com/user-attachments/assets/9ae69cbd-a910-4eae-9608-26a8b3e79e94">
