### ISSUE TITLE
 Homepage templates are not editable in the Mobile apps 

### ISSUE THREAD

**Issue by azollafox** [wordpress-mobile/WordPress-iOS#20032]
### Expected behavior
I would expect to be able to edit all content on my site in the app, including that which is my Homepage Template. I would expect to access this the same way I do on a browser, by clicking the site editor, or the link to the site editor from my Pages

### Actual behavior
This content can't be accessed in the app. Because templates can't be edited I can't edit my homepage in the app

![WordPress com Editor](https://user-images.githubusercontent.com/7907292/215529158-598d836d-14ff-47b9-a52a-86fb90502857.png)

<img width="375" alt="Screenshot 2023-01-30 at 11 03 52 AM png" src="https://user-images.githubusercontent.com/7907292/215529184-443f65c5-7fec-4c0a-8db4-85b63c11d28c.png">

Reported : pNEWy-fW1-P2 and 5900990-zen

**Comment by fluiddot** [comment]
cc @geriux as this is related to the Site editor (p9ugOq-3mf-p2).

**Comment by twstokes** [comment]
The [Site Editor MVP](https://github.com/wordpress-mobile/WordPress-iOS/pull/20713) was rolled out in `22.5` and should resolve this issue. 🚀
