### ISSUE TITLE
Reader search result incorrectly shows "No posts found"

### ISSUE THREAD

**Issue by crazytonyli** [wordpress-mobile/WordPress-iOS#20138]
### Expected behavior
The search result is displayed.

### Actual behavior
The page says "No posts found"

### Steps to reproduce the behavior
1. Go to Reader tab
2. Tap the search button on the top right corner
3. Type "Food" (any other keyword should do) and search. Some posts should be displayed on screen.
4. Tap the search bar and tap the same keyword ("Food") in the drop down list

##### Tested on [device], iOS [version], WPiOS [version]
The production app on the App Store.

**Comment by twstokes** [comment]
👋 Hey @crazytonyli - these look similar: https://github.com/wordpress-mobile/WordPress-iOS/issues/19190

**Comment by crazytonyli** [comment]
@twstokes Yes indeed. I'll close this one. Thanks!
