### ISSUE TITLE
Reader: the Following tab shows the empty view of the Likes tab

### ISSUE THREAD

**Issue by crazytonyli** [wordpress-mobile/WordPress-iOS#20149]
### Expected behavior
"Following" tab shows posts of following sites.

### Actual behavior
"Following" tab shows "Nothing liked yet"

<img src="https://user-images.githubusercontent.com/1101828/219298155-5d530fa4-8195-4ac0-8e83-5c71bd854717.png" width="300">

### Steps to reproduce the behavior
1. Log in using an account which doesn't have any liked posts.
2. Go to the "Reader" tab.
3. Tap the "Likes" tab. An empty view (with a title "Nothing liked yet") should be displayed on screen.
4. Tap the "Go to Following" button on the empty view.

##### Tested on [device], iOS [version], WPiOS [version]
commit 143e835c3effe8a6bb88b43d28041022659d0986

**Comment by tiagomar** [comment]
Previously loaded posts on Following tab are not visible. Pull to refresh doesn't work.

**Comment by kean** [comment]
The solution should be to remove the "Go to Subscriptions" button – makes zero sense to show it there.
