### ISSUE TITLE
Test forum support changes

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#20181]
This issue serves as a place to track testing of the new forum for users of the .org forum. Please note the scope of this change only includes the WordPress app. There should be no meaningful changes to the Jetpack app except for minor changes like an updated copy, which isn't covered here.

~~⚠️ Please note that until the remote feature flag is switched on, the above changes won't be present. See https://github.com/wordpress-mobile/WordPress-iOS/pull/20109 for details.~~

**Comment by guarani** [comment]
Testing on `trunk` (d8bd9e008dfc6cc70dcfc96b8e42522a9aa04e47) on an iPhone 11 with iOS 16.3. 

## Self-hosted users on the WordPress app
- [ ] Self-hosted users who request help locating their site address are given forum support
- [ ] Self-hosted users who are logged in to their site using their site credentials and request help are given forum support
- [ ] Self-hosted users who are logged in to their site using WP.com credentials (via the Jetpack plugin) and request help are given forum support 

## WP.com users on the WordPress app

- [ ] WP.com users who are logged out and request help logging in are given forum support (no matter what plan they might have)
- [ ] WP.com users logged in to a WP.com site with a free plan who request help are given forum support
- [ ] WP.com users logged in to a WP.com site with a paid plan who request help are given chat-like support

## Users on the Jetpack app

- [ ] All users on the Jetpack app are given chat-like support

**Comment by staskus** [comment]
## Self-hosted users on the WordPress app
- [x] Self-hosted users who request help locating their site address are given forum support
- [x] Self-hosted users who are logged in to their site using their site credentials and request help are given forum support
- [x] Self-hosted users who are logged in to their site using WP.com credentials (via the Jetpack plugin) and request help are given forum support
⚠️ _It depends on what kind of WP.com site is connected to. If it contains paid plans, the chat-like support is still shown._ 

## WP.com users on the WordPress app

- [x] WP.com users who are logged out and request help logging in are given forum support (no matter what plan they might have)
- [x] WP.com users logged in to a WP.com site with a free plan who request help are given forum support
- [x] WP.com users logged in to a WP.com site with a paid plan who request help are given chat-like support

## Users on the Jetpack app

- [x] All users on the Jetpack app are given chat-like support

**Comment by guarani** [comment]
Thanks for diving in and testing here, @staskus!

> * ⚠️ _It depends on what kind of WP.com site is connected to. If it contains paid plans, the chat-like support is still shown._

This makes sense to me and matches what I saw on Android 👍

**Comment by guarani** [comment]
Marked this done since all the testing scenarios have been executed.
