### ISSUE TITLE
Consider centralizing the logic to create a `WordPressComRestApi` instance

### ISSUE THREAD

**Issue by mokagio** [wordpress-mobile/WordPress-iOS#20208]
See discussion at https://github.com/wordpress-mobile/WordPress-iOS/pull/20197#discussion_r1115196527.

I used "consider" in the title because it's not clear to me whether it DRYing the code would be beneficial given, as @crazytonyli points out, the different implementation vary in subtle ways.

If we can adopt a standard approach, then it would be beneficial, otherwise... well I'd say I'd like to understand _why_ we can't standardize, first.

**Comment by mokagio** [comment]
See also the code at https://github.com/wordpress-mobile/WordPress-iOS/blob/0fe3962338f8ff3f4f892f03e26844525a992dc9/WordPress/Classes/Services/JetpackRestoreService.swift#L5-L19

As well as other files touched in https://github.com/wordpress-mobile/WordPress-iOS/pull/20198/files

**Comment by jkmassel** [comment]
We plan to drop `WordPressComRestApi` eventually, so this will happen organically.

**Comment by mokagio** [comment]
🎉
