### ISSUE TITLE
[Blaze] UI issue on Blaze card menu

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#20218]
There's something slightly off on iPhone, more visible on `Light` mode. It looks perfect on iPad.

_*Tested on real devices._

| **iPhone 13 - iOS 16.1.1** | **iPad - iPadOS 15.4.1** | 
| - | - |
| <img width="600" alt="image" src="https://user-images.githubusercontent.com/42008628/221298960-2514a71c-5b9f-4bb6-8e2a-2665d81151a0.png"> | <img width="600" alt="image" src="https://user-images.githubusercontent.com/42008628/221299118-d8ec6e04-d7e6-4c52-9866-63c07780fe2a.png"> |
| <img width="600" alt="image" src="https://user-images.githubusercontent.com/42008628/221299021-7ef006fa-c9b3-4304-83f9-d4247150b642.png"> | <img width="600" alt="image" src="https://user-images.githubusercontent.com/42008628/221299157-54f443f6-0493-4112-8361-8db4e39257fd.png"> |

### Steps to reproduce the behavior
0. Make sure that Blaze is enabled via the debug menu
1. Switch to a site that has Blaze enabled
2. Switch to the dashboard
3. A Blaze dashboard card is displayed
4. Tap on the ellipsis button

**Comment by kean** [comment]
It's a standard menu appearance, so there is nothing we can do. It's just some background appearing behind.
