### ISSUE TITLE
Render posts in the Posts list as a ReaderPostContentView

### ISSUE THREAD

**Issue by mikejohnstn** [wordpress-mobile/WordPress-iOS#2022]
On the Me tab, when you browse to a site and view your posts, it's currently a pretty boring list of titles. Let's try rendering each post like you see in the Reader tab instead.

The class for that view is `ReaderPostContentView` and it has a `shouldShowActions` attribute that will let us disable the action buttons (which probably shouldn't be visible in the context of your post list).

**Comment by oguzkocer** [comment]
Per @aerych's awesome work in #3609, closing this!
