### ISSUE TITLE
Can't connect to Social Network

### ISSUE THREAD

**Issue by crazytonyli** [wordpress-mobile/WordPress-iOS#20264]
### Expected behavior
The app can connect to SNS

### Actual behavior
The SNS authorization web view says "Invalid/missing request nonce."

### Steps to reproduce the behavior
1. Uninstall the app. This step is important since this issue seems to relate to the cookie storage on the device.
2. Log in, "My Site" tab -> "Menu" segment -> "Sharing"
3. On the "Sharing" screen, select an unconnected social connection.
4. Tap "Connect" button.
5. Check out the content of the web view.

To workaround this issue, go to the root of "My Site" tab and open the site URL on top of the screen, then connecting to a social network will work. So, this issue looks like it's related to missing cookies in the web view cookies storage.

##### Tested on [device], iOS [version], WPiOS [version]
ea6b32e245bd1d1492603773944f042b9eb3fe80

**Comment by tiagomar** [comment]
Social connection is working fine. Closing this ticket for now.
