### ISSUE TITLE
Add ability to toggle the visibility of all dashboard cards

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#20296]
### Expected behavior

I expect to be able to hide any of the dashboard cards.

### Actual behavior

I can only hide some (e.g. the Prompts card) but not others (e.g. the "Today's Stats" card). Also, if I choose to show a card again, there's no option to do so.

### Steps to reproduce the behavior

1. Log in to the Jetpack app
2. On the first tab, "My SIte", switch to the "Home" tab
3. Notice that the "Today's Stats", "Work on a draft post" and possibly some other cards have no option to hide
4. Notice that some other cards have the option to hide e.g. the Prompts card, the Blaze card (not visible on App Store builds), the "Next Steps" card (only visible for newly created sites), etc
5. Notice that once a card is hidden, there is no option to show it again (we're missing a dashboard card management screen)

### Additional info

Adding the option to hide dashboard cards (as well as show them again via a "dashboard management" screen) is discussed in this internal ref pcdRpT-1MX-p2).

**Comment by kean** [comment]
It shipped in 22.6.
