### ISSUE TITLE
Overlay not presenting on site switch

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#20319]
Ref: pctCYC-Gx-p2#comment-743

### Expected behavior

The overlay should appear when a user switches to a site that is eligible for the full plugin and hasn't seen the overlay yet.

### Actual behavior

Overlay does not appear if starting on a separate site and then switching to the site that needs the full Jetpack plugin.

### Steps to reproduce the behavior

- Setup a self-hosted site with just a single Jetpack plugin installed and connected to your WordPress account
- Launch the app, login, and select a site that is not the self-hosted site
- Open the site picker
- Select the self-hosted site you created
- Overlay does not appear

**Comment by dvdchr** [comment]
Closed via #20320
