### ISSUE TITLE
iOS - Tweak the messaging for other JP features

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#20328]
## Description
We should change the messaging for the other Jetpack features (Activity Log, Jetpack Social, Backup, Scan, Menus, People, Themes) to:
`Moving to the Jetpack app in a few days.`

Please check pcdRpT-21n-p2 any updates in the copy above.

**Comment by hassaanelgarem** [comment]
@dvdchr  In #20331, I added a new case `staticScreens` under `JetpackFeaturesRemovalCoordinator.GeneralPhase`

We should update `JetpackBrandingTextProvider` to return the new copy if the current phase is `staticScreens`

**Comment by dvdchr** [comment]
Closed via #20332
