### ISSUE TITLE
iOS - Create reusable static screen for Stats, Reader, and Notifications

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#20330]
## Description

Create a reusable view controller to be shown in the Stats, Reader, and Notifications screen

![jpstaticprompt](https://user-images.githubusercontent.com/304044/225290656-92fba3c3-9e91-465b-bc52-1a86ba4e5a46.png)

Please check pcdRpT-21n-p2#comment-3549 for any design updates.

**Comment by dvdchr** [comment]
Closing as this should be resolved via #20334. Feel free to reopen if there are still some follow-ups!
