### ISSUE TITLE
Add Interactive Comment Notifications for iOS 8

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-iOS#2036]
For comment notifications, we should add:
- Like button if the user can like the comment. This will run in the background and not load a UI.
- Reply button if the user can reply. This will load the comment detail view when tapped?
- Moderation buttons based on the current comment status. We may be limited to the amount of buttons we can add so maybe one button for Approve/Unapprove. Don't show this button if the user can't moderate. This will also be a background action.

**Comment by jleandroperez** [comment]
Problem with this issue is that Interactive Notifications don't require any kind of authentication.

We've been discussing this in the WordPress slack, and @astralbodies pointed out it'd be a good idea to also provide an opt-out setting.

That way, you could prevent anyone that picked up your phone from replying, without unlocking the phone first.

**Comment by koke** [comment]
> Problem with this issue is that Interactive Notifications don't require any kind of authentication

Replying to a message doesn't require authentication but archiving an email asks for TouchID/passcode

![rich-notification-auth](https://cloud.githubusercontent.com/assets/8739/8249412/ea23d57e-1669-11e5-8838-ba82384e026c.png)

**Comment by jleandroperez** [comment]
@koke try the same with SMS's. You'll get the Reply button, even when logged out.

**Comment by koke** [comment]
> If you set the action’s authenticationRequired property to YES and the device is locked when the user responds to the notification, the user must enter a passcode when choosing the action. However, this does not unlock the device, so if your app needs to access files, make sure the files are in the right data protection class. When the value of the activationMode property is UIUserNotificationActivationModeForeground, the value of the authenticationRequired property is assumed to be YES regardless of its actual value.

https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/IPhoneOSClientImp.html#//apple_ref/doc/uid/TP40008194-CH103-SW26

**Comment by jleandroperez** [comment]
@koke awesome! all concerns cleared then, this issue has a green light.

Thank you!

**Comment by jleandroperez** [comment]
#### Update:
iOS 9 adds support for Text Input UIUserNotificatioNActions. Let's implement this as soon as we switch to Xcode 7 GM!

**Comment by koke** [comment]
Is there something else to do here? It looks like this is implemented, although we could add a few more actions (e.g. spam/trash for comments)

**Comment by jleandroperez** [comment]
@koke actually... we do support Replying to comments, but that action ends up opening the app. 

This issue was intended to add actual "Inline Reply" support (pretty much like iMsg / Whatsapp, when you force press an incoming message, within the lock screen).

**Comment by koke** [comment]
Gotcha, I think I'll create a separate issue to make that clearer :)

**Comment by jleandroperez** [comment]
Awesome, thank you sir!
