### ISSUE TITLE
Incorrect Navigation Bar Appearance in Reader Detail screen

### ISSUE THREAD

**Issue by salimbraksa** [wordpress-mobile/WordPress-iOS#20362]
### Description

This is a regression bug caused by a PR targeting the upcoming v22.0:
-  https://github.com/wordpress-mobile/WordPress-iOS/pull/20278

### Expected behavior

The navigation bar appearance in the Reader Detail screen should be transparent if the post has a featured image.

### Actual behavior

The navigation bar appears white.

<img src="https://user-images.githubusercontent.com/9609223/226131530-19496f54-fec1-475a-b981-a5da475d35cc.png" width=400 />

### Steps to reproduce the behavior
1. Enable Light Mode.
2. Navigate to any post with a featured image.
    - For example: https://lostinamberland.wordpress.com/2023/03/18/way-too-far/
3. Notice how the navigation bar appears white. It should be transparent so that the featured image is visible.  

##### Tested on iPhone 14 Pro Max, iOS 16, WPiOS 22.0

**Comment by mokagio** [comment]
I'm about to start the 22.0 code freeze. This issue is not ready to land into trunk, but it seems worth leaving under the 22.0 milestone and update to point to release/22.0 once the branch is ready given it's a UI fix.

**Comment by mokagio** [comment]
Closed via #20363
