### ISSUE TITLE
Activity Log and Plugins not functional on Jetpack

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#20471]
### Expected behavior
Activity log and Plugin to load normally

### Actual behavior
Activity Log never loads, and Plugins shows "Error loading plugins" message.

### Steps to reproduce the behavior

1. Run the WordPress app
2. Log in to an account that has a connected self-hosted site
3. Logout
4. Run the Jetpack app
5. Log in to the same account from step 2
6. Navigate to the Menu
7. Navigate to Activity Log
8. Notice that the screen never finishes loading
9. Go back
10. Navigate to Plugins
11. Notice that the installed plugins never load and shows an error message.

**Comment by tiagomar** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/issues/20472
