### ISSUE TITLE
Reader: Subscribing to a site can cause Jetpack app crash

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#20492]
### Expected behavior
App to not crash.

### Actual behavior
App sometimes crashes.

### Steps to reproduce the behavior
1. Load a *.wordpress.com site in mobile Safari
2. Open the site in Jetpack in Reader
3. Tap the button to subscribe

### Notes

The exception thrown is `*** -[__NSCFString rangeOfString:options:range:locale:]: nil argument` [here in WordPressKit](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/1e563201e30eddb26d1605513b741ae9402a6b40/WordPressKit/ReaderSiteServiceRemote.m#L249). I would assume `siteURL` is `nil` when we weren't expecting it to be.

**Comment by guarani** [comment]
I couldn't reproduce this. I went through the same testing steps (reproducing here in case you can spot a difference):
1. Opened a site in mobile Safari e.g. https://renardsworld.wordpress.com/2023/03/25/are-you-still-using-the-wordpress-mobile-app/) 
2. Tapped the Open button on the top bar 
3. Jetpack (which is already logged in) opens to show the post
4. I tap the Follow button and the site is followed

https://user-images.githubusercontent.com/1898325/230969053-b15314ad-b6a6-44f6-a791-9234b79e12e5.MP4

**Comment by twstokes** [comment]
👋 Thanks for testing this @guarani (as well as @staskus), those steps look correct and I haven't been able to reproduce it either since initially reporting it.

I didn't spend much timing digging in, but my conclusions are:
- This crash doesn't happen often
- It's due to an assumption we're making that [`siteURL absoluteString`](https://github.com/wordpress-mobile/WordPressKit-iOS/blob/1e563201e30eddb26d1605513b741ae9402a6b40/WordPressKit/ReaderSiteServiceRemote.m#L249) won't return `nil`
- According to Sentry it may be increasing in frequency

**Comment by guarani** [comment]
I ran into this today and have consistent steps to reproduce:
1. In a different app, tap on a link such as p7H4VZ-4tN-p2 
2. When the app opens, tap the follow button next to the post's title
3. Notice the app crashes

**Comment by twstokes** [comment]
Nice catch @guarani! I clean installed from `trunk` @ daac1a0e27a12ad1e3ae41e9e8a1acec065f8880 and was able to reproduce the crash in debug mode [using your steps](https://github.com/wordpress-mobile/WordPress-iOS/issues/20492#issuecomment-1640961522).

Stack trace:

```
Thread#0	0x000000019dd60cb4 in __exceptionPreprocess ()
#1	0x0000000196e003d0 in objc_exception_throw ()
#2	0x0000000198018450 in -[NSString rangeOfString:options:range:locale:] ()
#3	0x00000001033c9a50 in __70-[ReaderSiteServiceRemote checkSubscribedToFeedByURL:success:failure:]_block_invoke at /Users/tanner/dev/WordPress-iOS/Pods/WordPressKit/WordPressKit/ReaderSiteServiceRemote.m:249
#4	0x0000000103600c30 in thunk for @escaping @callee_unowned @convention(block) (@unowned Swift.AnyObject, @unowned NSHTTPURLResponse?) -> () ()
#5	0x00000001035feae0 in closure #2 in WordPressComRestApi.request(method:urlString:parameters:encoding:success:failure:) at /Users/tanner/dev/WordPress-iOS/Pods/WordPressKit/WordPressKit/WordPressComRestApi.swift:206
#6	0x000000010278f77c in closure #1 in closure #1 in DataRequest.response<τ_0_0>(queue:responseSerializer:completionHandler:) at /Users/tanner/dev/WordPress-iOS/Pods/Alamofire/Source/ResponseSerialization.swift:167
#7	0x0000000100dae748 in thunk for @escaping @callee_guaranteed () -> () ()
#8	0x000000010a89c520 in _dispatch_call_block_and_release ()
#9	0x000000010a89e038 in _dispatch_client_callout ()
#10	0x000000010a8ae798 in _dispatch_main_queue_drain ()
#11	0x000000010a8ae2dc in _dispatch_main_queue_callback_4CF ()
#12	0x000000019ddefc28 in __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ ()
#13	0x000000019ddd1560 in __CFRunLoopRun ()
#14	0x000000019ddd63ec in CFRunLoopRunSpecific ()
#15	0x00000001d927335c in GSEventRunModal ()
#16	0x00000001a01636e8 in -[UIApplication _run] ()
#17	0x00000001a016334c in UIApplicationMain ()
#18	0x0000000101e2c61c in main at /Users/tanner/dev/WordPress-iOS/WordPress/Classes/System/main.swift:7
#19	0x00000001bd2aedec in start ()
```

**Comment by twstokes** [comment]
Just making a note of what I've found so far, but [this ReaderSiteTopic](https://github.com/wordpress-mobile/WordPress-iOS/blob/daac1a0e27a12ad1e3ae41e9e8a1acec065f8880/WordPress/Classes/Services/ReaderTopicService.m#L450) has no [feedURL](https://github.com/wordpress-mobile/WordPress-iOS/blob/daac1a0e27a12ad1e3ae41e9e8a1acec065f8880/WordPress/Classes/Services/ReaderTopicService.m#L517) so this is why the crash occurs when following.

I also want to note that the crash seems different for following versus unfollowing. Perhaps the app is left in a weird state after crashing due to following, so it may be best to figure out the following crash first.

Higher up the chain, [this `readerPost`](https://github.com/wordpress-mobile/WordPress-iOS/blob/daac1a0e27a12ad1e3ae41e9e8a1acec065f8880/WordPress/Classes/Services/Reader%20Post/ReaderPostService.m#L293) has a `nil` topic.

**Update:**

I've traced this back to [this call where `lookupWithFeedID` is passed `nil`](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/Classes/Services/Reader%20Post/ReaderPostService.m#L313) (because `readerPost.feedID` is nil) yet it returns a value.

I wonder if [this method](https://github.com/wordpress-mobile/WordPress-iOS/blob/81807b9a08a20081bdd0331a89d541cf20561fec/WordPress/Classes/Models/ReaderSiteTopic%2BLookup.swift#L37) is converting that `nil` `NSNumber` to a zero, and causing a successful lookup, when [previously](https://github.com/wordpress-mobile/WordPress-iOS/commit/74f094fc80c80d2073f0ee18768f190585fbebe8?diff=split#diff-6f18194bd77632a248210426d1358cec7298affec8c1c9d38e46f137957faaafL991) a `nil` would be returned.

**Comment by twstokes** [comment]
I've assigned myself to this, PR incoming.

**Comment by twstokes** [comment]
Sentry has a [duplicate issue for this](https://a8c.sentry.io/issues/4263600395/?project=5716771&project=1438083&query=ReaderSiteServiceRemote&referrer=issue-stream&statsPeriod=14d&stream_index=0) that I've attempted to merge.

I've marked both as being resolved in 22.9 due to no occurrences, although it currently only has a 25% adoption rate so we can revert if needed:
- https://a8c.sentry.io/share/issue/bc31ecdcd6b24daa999abe0d6cdbc85b/
- https://a8c.sentry.io/share/issue/1feb4a1175a94572898b7105bf7f983a/

**Comment by staskus** [comment]
@twstokes thanks!

One question, does it Sentry crash looks familiar from the first look https://a8c.sentry.io/issues/4340368025/?project=5716771&referrer=github_integration or is it a different issue?

**Comment by twstokes** [comment]
> One question, does it Sentry crash looks familiar from the first look https://a8c.sentry.io/issues/4340368025/?project=5716771&referrer=github_integration or is it a different issue?

Really good question @staskus - I'll investigate this some and report back.

**Comment by twstokes** [comment]
@staskus I'm not totally confident due to the lack of info from Sentry, but it seems to me like [what you've linked to](https://a8c.sentry.io/share/issue/76275c1e84aa4610827f92a390e8cd2e/) is a different issue than this one. I see that @salimbraksa created https://github.com/wordpress-mobile/WordPress-iOS/issues/21307 for it so I'll leave a note there with thoughts. Thanks!

**Comment by staskus** [comment]
> @staskus I'm not totally confident due to the lack of info from Sentry, but it seems to me like [what you've linked to](https://a8c.sentry.io/share/issue/76275c1e84aa4610827f92a390e8cd2e/) is a different issue than this one. I see that @salimbraksa created #21307 for it so I'll leave a note there with thoughts. Thanks!

Thanks, @twstokes for taking your time to investigate!
