### ISSUE TITLE
Crash in Blaze service

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#20507]
**Sentry Url**: https://sentry.io/share/issue/9fa741cab7204d82aa32d9d219847971/
**User Count**: 2745
**Count**: 3807
**First Release**: 21.9.0.2
**First Seen**: 2023-03-15T17:45:42Z
**Last Seen**: 2023-04-11T22:25:42Z
**24 Hours**: 118
**30 Days**: 3806
**LogID:** B4A29557-4C97-4B93-B7CC-326B6C8BB66D

```
EXC_BAD_ACCESS: Exception 1, Code 1338969264, Subcode 8 >
  File "BlazeService.swift", line 59, in BlazeService.updateBlog
  File "<compiler-generated>", line null, in thunk for closure
  File "ContextManager.swift", line 91, in ContextManager.performAndSave
  File "<compiler-generated>", line null, in ContextManager.performAndSave
  File "<compiler-generated>", line null, in thunk for closure
...
(13 additional frame(s) were not displayed)
```

**Comment by guarani** [comment]
@wordpress-mobile/kahu, I found this crash on Sentry. It's one month old and has 3.8K events. I looked at a sample of the events and they all mentioned Blaze in the stack trace. Does this need further investigation?

**Comment by momo-ozawa** [comment]
Hey @guarani 👋 

Thanks for the ping! It looks to be the same as [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/20397), which was resolved by [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/20413) targeting 22.0.

**Comment by guarani** [comment]
Thanks! I missed that issue when I did a quick search here before creating this one. I'm closing this issue as a duplicate.
