### ISSUE TITLE
On iPads, UI doesn't fit after logging in from stats screen

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#20535]
### Expected behavior
On an iPad, after logging in from the Stats screen, the UI should appear correctly.

### Actual behavior
On an iPad, after logging in from the Stats screen, the UI doesn't fit the screen. This issue is resolved after changing the screen and reopening the Stats screen

<img width="720" alt="logging-in-from-stats-screen" src="https://user-images.githubusercontent.com/2471769/231817317-aee84a19-f6c4-4f4c-bb52-4207aa898718.png">

### Steps to reproduce the behavior
1. Launch the JP app on iPad and connect a self-hosted website with Jetpack.
2. Navigate to Stats.
3. Tap the Login button and log in with an account that you can use Jetpack features with.
4. Notice that card views don't fit the screen.

**Comment by kean** [comment]
Fixed in the scope of the Sidebar redesign.
