### ISSUE TITLE
Reader renders P2 Task block labels in German

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#20616]
### Expected behavior

When a post is shown in the Reader, all labels should be shown in the correct language.

### Actual behavior

With the device language set to English, the Reader renders some parts of the UI in German.
Specifically, [P2 Task blocks](https://p2help.wordpress.com/using-p2/the-editor/blocks/tasks-project-status/) in the post content use German.

### Steps to reproduce the behavior

1. Ensure the device language is English
2. Open a post in Reader that contains a Task block (these blocks can only be added on a [P2 site](https://p2help.wordpress.com/what-is-p2/) on the web, they can't be added on the Jetpack app)
3. Notice that the P2 labels are in German (e.g. `Bearbeitung von Mai 31`)

##### Tested on iPhone 11, iOS 16.3, Jetpack iOS 22.1, reported in p1682607079281709-slack-C0HTU7HV3

**Comment by guarani** [comment]
Giving this a low priority due to low severity (it's a visual issue with a P2 block) and low impact (one user report).

**Comment by akirk** [comment]
This likely happened because I created/edited the post with my UI language set to German. Looks like these labels are stored verbatim in the post_content and don't get rendered in the viewer's user language. Thus I think it can be closed since it's not iOS specific but rather a P2 bug.

**Comment by guarani** [comment]
Good catch! I'm closing this and will report this separately for P2.
