### ISSUE TITLE
Reader: Tapping the Menu Bar Doesn't Scroll to Top

### ISSUE THREAD

**Issue by mdrockwell** [wordpress-mobile/WordPress-iOS#20625]
### Expected behavior
When tapping the top toolbar/menu/status bar on iOS, it is expected that the app will scroll to the top of the current list.

### Actual behavior
When tapping on the top toolbar, nothing happens.

### Steps to reproduce the behavior
1. Open the Reader tab in the Jetpack app
2. Scroll down the list.
3. Tap the status bar.

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
iPhone 13 Pro, iOS 16.4.1, Jetpack iOS 22.2

**Comment by jsnajdr** [comment]
I can confirm this bug is really there. On other views, like My Site or Notifications, the scroll to top feature works, but not in Reader. It's like if the relevant view didn't have [`scrollsToTop`](https://developer.apple.com/documentation/uikit/uiscrollview/1619421-scrollstotop) enabled.

**Comment by twstokes** [comment]
At first glance the fix may be that we need to set the `FilterTabBar` [to not scroll to top here](https://github.com/wordpress-mobile/WordPress-iOS/blob/8f53ee75ce87eebe7620400f7ab88d75947d1d02/WordPress/Classes/ViewRelated/System/FilterTabBar.swift#L36).

See `UIScrollView` [special considerations](https://developer.apple.com/documentation/uikit/uiscrollview/1619421-scrollstotop#1681700) - two scroll views (which Reader has - the filter and the posts) will default to `true`, which disables the feature.

I'll see if I can make this tweak. 👍

**Comment by jsnajdr** [comment]
Today my Jetpack app was (finally) updated to 23.7.1 and I can confirm this is fixed :tada: Thanks!

**Comment by twstokes** [comment]
> Today my Jetpack app was (finally) updated to 23.7.1 and I can confirm this is fixed 🎉 Thanks!

Great to hear @jsnajdr! Thanks for using the app.
