### ISSUE TITLE
[Site Editor] Implement feature flag

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#20642]
## Tasks

- [x] Add "Site Editor" feature flag. https://github.com/wordpress-mobile/WordPress-iOS/pull/20640

**Comment by dvdchr** [comment]
#20640 is merged to trunk, but the PR is somehow closed. 🤔 probably related to [this incident](https://www.githubstatus.com/incidents/f0mhbz9xn497) as discussed in p1683642069637929-slack-C02KLTL3MKM.
