### ISSUE TITLE
Plans on JP: Create Plans selection and integrate in the flow

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#20688]
See pc8eDl-Vv-p2

- [x] Basic integration of the web view: https://github.com/wordpress-mobile/WordPress-iOS/pull/20716
- [x] Test once https://github.com/Automattic/wp-calypso/pull/77029 is merged to ensure just the Personal & Premium plans show and the webpage back button is hidden.

**Comment by guarani** [comment]
> [ ] [Add UI tests](https://github.com/wordpress-mobile/WordPress-iOS/pull/20716#issuecomment-1557523397)

Removed this now that we have a separate issue for it: https://github.com/wordpress-mobile/WordPress-iOS/issues/20720

**Comment by mokagio** [comment]
I'll be starting the 22.5 code freeze shortly and this PR hasn't been approved yet.

I'm going to push it to the 22.6 milestone to err on the side of caution. I understand domains is a feature we want to iterate and experiment on quickly, so feel free to revert and target `release/22.5` if appropriate. However, considering most of the tasks in the description are currently unchecked, I don't think that will be the case?

**Comment by staskus** [comment]
@guarani, both depend on the inner implementation of Calypso.

-  Accessibility for dynamic type, high contrast, and right-to-left languages
-  Make the web view adapt to the device language

There were and there are projects addressing accessibility improvements on the web and there isn't a way to pass a flag to localize a page.

I'd say we should remove these tasks from the scope of this phase of the project, and if we want to make these changes, we should first clearly define what kind of changes we want to be done on the web view side of things (e.g pe7hp4-aM-p2) and then see what's the way to address them. Educating in web development & wp-calypso or having a calypso team implement it for us. WDYT?

**Comment by guarani** [comment]
Good idea! I've moved those items from here to https://github.com/orgs/wordpress-mobile/projects/154?pane=issue&itemId=28650005.

**Comment by guarani** [comment]
Marking this resolved now that https://github.com/Automattic/wp-calypso/pull/77029 is merged and I've been able to confirm that the app's now just showing the Personal & Premium plans 👍
