### ISSUE TITLE
Blaze Card UI exceeds view margins on the dashboard

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-iOS#20687]
The Blaze card exceeds the left-side view margins. See image.

<img width="250" height="500" alt="Alt desc" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/506707/271635cf-301e-4805-8db1-d8f300e6d7ad">

**Comment by antonianuzzolo** [comment]
Yo! I'm working on this.
