### ISSUE TITLE
Plans on JP: Analytics

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#20692]
See pc8eDl-Vv-p2

**Comment by guarani** [comment]
Re-opening to add a small change: add a `source` property to the [existing domains_dashboard_select_domain_tapped event](https://github.com/wordpress-mobile/WordPress-iOS/blob/416615c3313de86891b0e74b8fb2f97947d59707/WordPress/Classes/ViewRelated/Domains/Domain%20registration/RegisterDomainSuggestions/RegisterDomainSuggestionsViewController.swift#L221) (see https://github.com/wordpress-mobile/WordPress-iOS/pull/20710#pullrequestreview-1437478612 for context).

**Comment by guarani** [comment]
Closing this because https://github.com/wordpress-mobile/WordPress-iOS/pull/20810 finished off the analytics work. Please feel free to re-open if I missed something @staskus 🙇
