### ISSUE TITLE
Plans on JP: Success view

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#20690]
See pc8eDl-Vv-p2

Figma: gYd0CqIGZQfok23OBljWnX-fi-2098%3A18001

- [x] Create a success view UI
- [x] Integrate in the flow after a successful checkout https://github.com/wordpress-mobile/WordPress-iOS/issues/20727
- [x] Test the whole flow from the start to the end

**Comment by guarani** [comment]
Updated link to point to screen's design.
