### ISSUE TITLE
Mastodon Social Connection shows no instances

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#20703]
### Expected behavior
The ability to connect to a Mastodon instance.

### Actual behavior
There are no Mastodon instances to connect to.

https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/8d07ea59-048d-41b0-82a4-94efa4300672

### Steps to reproduce the behavior
1. Go to My Site -> Sharing (WPiOS) or My Site -> Social (JPiOS)
2. Select Mastodon
3. Tap Connect

**Comment by twstokes** [comment]
**Note:** The Mastodon option disappeared later the same day. Social Connections are controlled by the backend so it may have been a temporary server-side issue.

**Comment by tiagomar** [comment]
Mastodon option is still not available. I'll close this ticket and we can reopen if needed.
