### ISSUE TITLE
Editor: Can't insert image from camera without "All Photos" permission

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#20715]
### Expected behavior
To be able to insert an image from the camera with "Selected Photos" permission, maybe less.

### Actual behavior
A message is shown that the app needs permission to access media library photos, requiring the "All Photos" setting.

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/702e97f2-e187-48a0-bebc-19d4dbfc4f15" width="300" />

### Steps to reproduce the behavior

Prerequisites:
- Photos permission set to "Selected Photos"

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/87a4c0a9-bfbb-4cce-8c7b-6c566bb3e947" width="300" />

1. Start a new post and add an image block
2. Tap "Take a Photo"
3. Take a picture and tap "Use Photo"

### Notes

This restriction doesn't exist when adding photos from the camera in the My Site -> Media view.

**Comment by kean** [comment]
> This restriction doesn't exist when adding photos from the camera in the My Site -> Media view.

I've been testing the media view with the same setup: "selected photos" + camera access. I was not able to add photos to Media and it fails silently.

`CameraCaptureCoordinator` has a return on line 26 that ignores all errors.

**Comment by kean** [comment]
I raised this issue in the following channel p1692736622147249-slack-C04SFL0RP51. It's now more important than ever to solve it because, with https://github.com/wordpress-mobile/WordPress-iOS/issues/21190 in place, the app no longer needs or asks for access to the Photos library.
