### ISSUE TITLE
Memory leak in domain flow

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#20747]
### Expected behavior

Closing the domain flow should release all view controllers from memory.

### Actual behavior

Closing the domain flow leaves some view controllers in memory. I noticed this because when I had Safari open to inspect some of the flow's web views, the inspector didn't close automatically when I closed the flow. Xcode memory inspector also shows an increase in memory each time the flow is opened and Xcode's Debug Memory Graph shows the cause might a retain cycle.

- `RegisterDomainSuggestionsViewController` has a strong reference to `DomainSuggestionsTableViewController` via its `domainsTableViewController` property.
- `DomainSuggestionsTableViewController` has a strong reference back to `RegisterDomainSuggestionsViewController` via its `delegate` property.

### Steps to reproduce the behavior

1. Open the domain flow (e.g. via one of the domain dashboard cards or the My Site > Menu > Domains option
2. Tap into the domain search screen and then close the flow 
3. Notice that memory increases
4. Repeat Step 1 and 2 and notice that memory usage keeps increasing

**Comment by staskus** [comment]
@guarani nice catch!

**Comment by guarani** [comment]
Moving this to to-do but leaving it outside of any project since it doesn't look to be breaking anything or affecting metrics ([even if it's causing the duplicate tracks events](p1685597429987419/1685572533.214929-slack-C04UMS1RD89)).
