### ISSUE TITLE
App hanging for at least 2000 ms

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#20771]
**Sentry Url**: https://sentry.io/share/issue/fcf140e7663d45e8bfac0ec3f5e19be3/
**User Count**: 2522
**Count**: 4983
**First Release**: 22.3.0.2
**First Seen**: 2023-05-15T04:58:44.524090Z
**Last Seen**: 2023-05-30T21:20:32Z
**24 Hours**: 568
**30 Days**: 4976

```
App Hanging: App hanging for at least 2000 ms.
  File "main.swift", line 7, in main
...
(15 additional frame(s) were not displayed)
```

Sentry [detects app hangs](https://docs.sentry.io/platforms/apple/configuration/app-hangs/). Looking at a couple of events for this Sentry issue, I couldn't see a pattern in the Breadcrumbs view nor enough information in the Breadcrumbs to know what the user was doing when the app hang. I also tapped around the app with the hope of reproducing this issue but the app didn't hang.

**Comment by yukiyamazaki** [comment]
me too.

**Comment by senenpalanca97** [comment]
Happened here too!

**Comment by twstokes** [comment]
`22.9` adoption is still ramping up, but I wanted to surface https://github.com/wordpress-mobile/WordPress-iOS/pull/21065 which may have a high impact on reducing hangs.
