### ISSUE TITLE
Hiding dashboard cards: Update release notes

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#20775]
## Description
Add release notes for the Personalize Home Tab feature

**Comment by kean** [comment]
Hey, @momo-ozawa. Should I also enable the feature flag? AFAIK, It should be enabled for Jetpack only.

**Comment by momo-ozawa** [comment]
@kean 👋 

> Should I also enable the feature flag?

Yes please

> AFAIK, It should be enabled for Jetpack only.

Correct! cc: @guarani @staskus
