### ISSUE TITLE
iOS - Track user actions

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#20798]
Implement the following new analytic events.

Event | Trigger
---- | ----
`privacy_choices_banner_presented` | When the banner is presented
`privacy_choices_banner_settings_button_tapped` | When the settings button is tapped
`privacy_choices_banner_save_button_tapped` | When the save button is tapped

**Comment by hassaanelgarem** [comment]
I reopened this task as it's still pending on #21017
