### ISSUE TITLE
Translation issue for "Sharing" in Turkish

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#20816]
### Expected behavior
"Sharing" should be the same on the menu and quick start message in Turkish.

### Actual behavior
"Sharing" is different on the menu and quick start message in Turkish.

### Steps to reproduce the behavior
1. Launch the JP app on a device with the Turkish language.
2. Log in.
3. Create a new site and choose to be guided by Quick Start.
4. On Sharing item of quick start steps, you'll notice the wording in the message is different from the menu item.

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2471769/43021e07-e1cf-48ee-9ecd-9990b5b097a0" width=300>

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
