### ISSUE TITLE
Crash logging error or message: EXC_BAD_ACCESS: copyWithZone: > initWithBytes:length: >

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#20858]
**Sentry Url**: https://sentry.io/share/issue/cfdd1d5028ff4c41b28f71730e940b9e/
**User Count**: 59
**Count**: 77
**First Release**: 21.5.1.0
**First Seen**: 2023-01-25T05:14:02Z
**Last Seen**: 2023-06-12T12:58:46Z
**24 Hours**: 0
**30 Days**: 42
**LogID:** EFC939BD-81FF-403D-83EF-F944C22AD3F3

```
EXC_BAD_ACCESS: copyWithZone: > initWithBytes:length: >
  File "WPAccount+Lookup.swift", line 58, in WPAccount.lookup
  File "WPAccount+Lookup.swift", line 38, in WPAccount.lookupDefaultWordPressComAccount
  File "WPCrashLoggingProvider.swift", line 53, in WPCrashLoggingDataProvider.currentUser.getter
  File "<compiler-generated>", line null, in WPCrashLoggingDataProvider.currentUser.getter
  File "<compiler-generated>", line 50, in WPCrashLoggingDataProvider
  File "CrashLogging.swift", line 119, in CrashLogging.beforeSend
  File "<compiler-generated>", line null, in thunk for closure
...
(16 additional frame(s) were not displayed)
```

**Comment by guarani** [comment]
Added priority `Urgent` on GitHub board since [this Sentry event](https://a8c.sentry.io/issues/3895699109/events/135619113d4e4059b4022739e15462af/?project=5716771) and [this Sentry event](https://a8c.sentry.io/issues/3895699109/events/65e783b9fceb401baaeffc10acc5495e/?project=5716771) – both part of the same Sentry issue [JETPACK-IOS-FH](https://a8c.sentry.io/issues/3895699109) – match the crash report being discussed in https://a8c.slack.com/archives/C05CANZ2B6F.

**Comment by staskus** [comment]
By looking at the stack trace, it seems related to the https://github.com/wordpress-mobile/WordPress-iOS/issues/20836, since the crash happens through `WPCrashLoggingDataProvider.currentUser.getter`

I'll check logs to see what could be the entry point of this crash.

**Comment by staskus** [comment]
After the investigation and discussion closing this is a duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/20836

There're paths in the code where `logMessage` and `logError` could be called from the background thread which can cause crashes such as this. https://github.com/wordpress-mobile/WordPress-iOS/issues/20836 is an issue only tracked on Sentry since 22.3. We concluded that it happened due to the updates made in the version of Automattic Tracks which happened in 22.3 Otherwise, these issues are identical.

**Comment by guarani** [comment]
Sounds good, thanks for closing @staskus. I've also removed the `Urgent` priority from this so it can be added to https://github.com/wordpress-mobile/WordPress-iOS/issues/20836 if it could be the culprit of the crashes reported in https://a8c.slack.com/archives/C05CANZ2B6F.

**Comment by guarani** [comment]
I re-opened and closed again as "Close as not planned" since this is a dupe. This should help filter this out of GitHub boards with the `-reason:"not planned" filter.
<img width="614" alt="Screenshot 2023-06-14 at 17 04 27" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1898325/a22c8bd5-5b0f-4518-bef3-6ac9d8646a3a">
