### ISSUE TITLE
Reader search duplicates screen

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#20877]
### Expected behavior

In Reader, tapping the search button should navigate to the search screen.

### Actual behavior

Instead, it opens the search screen twice, resulting in the app visibly transitioning to the search screen twice.

### Steps to reproduce the behavior

1. Log in to a WP.com account in the JP app
2. Switch to the Reader tab
3. Tap the search icon (magnifying glass icon in upper-right corner) 
4. Notice two screens are pushed on to the navigation stack

https://github.com/wordpress-mobile/WordPress-iOS/assets/1898325/2cca6274-b1dc-400b-b9d0-853e48ee8b50

**Comment by daniloercoli** [comment]
I tested with the latest version and cannot replicate the issue. Closing it for now.
