### ISSUE TITLE
NSInvalidArgumentException: <UINavigationController: 0x1370f9400> is pushing the same view controller instance

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#20890]
This corresponds to one of the distinct crashes found in [JETPACK-IOS-31](https://a8c.sentry.io/issues/3140539221/?referrer=github_integration):

```
NSInvalidArgumentException
<UINavigationController: 0x1370f9400> is pushing the same view controller instance (<WPMediaPickerViewController: 0x138021a00>) more than once which is not supported and is most likely an error in the application : com.automattic.jetpack
```

**Comment by guarani** [comment]
I reproduced this crash using these steps:
1. To to My Site > Media
2. Tap "plus button" and "Choose from my device"
3. On the Albums screen, I have three rows: "Recent", "Recently Added", and "Videos"
4. Tapping quickly on different rows with both hands, I reproduced the crash 

Sentry created a new issue for this, [JETPACK-IOS-RXC](https://a8c.sentry.io/share/issue/b36a5befb4144728b8be438609d6707c/), although it could be merged with the others shown [here](https://a8c.sentry.io/issues/?query=is%3Aunresolved+%22WPMediaPickerViewController%22+%22more+than+once+which+is+not+supported%22&referrer=issue-list&statsPeriod=14d).

Here's the screen recording of the crash:

https://github.com/wordpress-mobile/MediaPicker-iOS/assets/1898325/51afd485-9fbe-4a82-a297-2cdabca43232

**Comment by kean** [comment]
@Guarani, please, test if you can reproduce it in this branch https://github.com/wordpress-mobile/WordPress-iOS/pull/21105

**Comment by guarani** [comment]
Tested but still getting the crash: https://github.com/wordpress-mobile/WordPress-iOS/pull/21105#issuecomment-1636621068

**Comment by kean** [comment]
This will be fixed in the scope of https://github.com/wordpress-mobile/WordPress-iOS/issues/21190

**Comment by staskus** [comment]
Closing the issue, it's fixed.
