### ISSUE TITLE
Reader crash when following site

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#20922]
### Expected behavior

Following a site in the Reader shouldn't crash the app.

### Actual behavior

Following a site in the Reader crashed the app in one instance, although I couldn't reproduce on subsequent tries.

### Steps to reproduce the behavior

These were the steps I took, but they're not reliable steps to reproduce:
1. Open Reader
2. Open Discover tab
3. Follow Movies
4. Tap a site that showed up under Movies
5. Try to follow the site by tapping the follow icon
6. App crashes

**Comment by twstokes** [comment]
Possibly related: https://github.com/wordpress-mobile/WordPress-iOS/issues/20492

**Comment by guarani** [comment]
Thanks for linking these two @twstokes! 
They look related, but I'm not sure they're duplicates yet because neither has reliable steps to reproduce.

**Comment by twstokes** [comment]
Two related PRs:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21140
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21341
