### ISSUE TITLE
Weekly Roundup background task causes Core Data multithreading violation

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#20957]
### Expected behavior
No multithreading violation to occur.

### Actual behavior
Running the Weekly Roundup background task can cause the app to halt on a Core Data multithreading violation (`_PFAssertSafeMultiThreadedAccess_impl ()`) when ran in debug mode.

### Steps to reproduce the behavior

Running a local build attached to Xcode's debugger:

1. On My Site tap the avatar at the top right
2. App Settings
3. Debug
4. Weekly Roundup
5. Tap Schedule immediately
6. Observe Xcode

### Notes:
- In production this may cause `-[__NSCFSet addObject:]: attempt to insert nil` to be thrown
- It may be a variation of https://github.com/wordpress-mobile/WordPress-iOS/issues/20843

**Comment by twstokes** [comment]
Ref: p1687798521543829/1686964519.271019-slack-C05CANZ2B6F

**Comment by twstokes** [comment]
@crazytonyli do you have any ideas about this one? Thanks!

**Comment by salimbraksa** [comment]
Just want to add that the app crashes at this [line](https://github.com/wordpress-mobile/WordPress-iOS/blob/21b25f2db5ac88c2826a9ca904e704eac561949e/WordPress/Classes/Utility/BackgroundTasks/WeeklyRoundupBackgroundTask.swift#L196) in `WeeklyRoundupBackgroundTask.swift`:
```swift
let result = try coreDataStack.mainContext.fetch(request)
```
Looks like the `mainContext.fetch` is called from a background thread, which is a clear concurrency violation.

I'll assign myself to this issue if that's okey with everyone. 🙏
