### ISSUE TITLE
Circular reference between ReaderTopicCollectionViewCoordinator and TopicsCollectionView

### ISSUE THREAD

**Issue by crazytonyli** [wordpress-mobile/WordPress-iOS#20972]
The strong references between them may lead to memory leak.

https://github.com/wordpress-mobile/WordPress-iOS/blob/32972a8dfadd96a10c1c423dbd1d3360228337e0/WordPress/Classes/ViewRelated/Reader/Tags%20View/TopicsCollectionView.swift#L33

https://github.com/wordpress-mobile/WordPress-iOS/blob/32972a8dfadd96a10c1c423dbd1d3360228337e0/WordPress/Classes/ViewRelated/Reader/Tags%20View/ReaderTopicCollectionViewCoordinator.swift#L43

**Comment by mokagio** [comment]
To make matters worse, the coordinator (strongly retained by the collection view) sets itself as the delegate and data source, roles that the UIKit designers clearly marked as a [having to be `weak`](https://developer.apple.com/documentation/uikit/uicollectionview/1618091-datasource).

https://github.com/wordpress-mobile/WordPress-iOS/blob/32972a8dfadd96a10c1c423dbd1d3360228337e0/WordPress/Classes/ViewRelated/Reader/Tags%20View/ReaderTopicCollectionViewCoordinator.swift#L83-L84

On top of that, the collection view becomes the delegate of the coordinator:

https://github.com/wordpress-mobile/WordPress-iOS/blob/32972a8dfadd96a10c1c423dbd1d3360228337e0/WordPress/Classes/ViewRelated/Reader/Tags%20View/TopicsCollectionView.swift#L33-L34

**Comment by mokagio** [comment]
@crazytonyli you've done an excellent work in #20978 but I wonder whether we should leave this issue open even after the PR lands. 🎖️ 

Your work addresses the memory leak, but that's only an effect of the circular reference design we have in place here. 

I feel it would be best to address the design limitation in the first place. Unfortunately, that's no small feat. If we were to go down that path, we might as well rewrite the whole thing in SwiftUI, which opens a hole new rabbit hole.

That's all to say, we might benefit from this issue remaining open as a reminder that the reader needs additional work.

**Comment by crazytonyli** [comment]
I'm not sure how feasible it is to refactor the "topic collection view" in SwiftUI, given it's a view inside a collection view cell. Also for this small part of the Reader, I'm not aware of any issues (other than this memory leak) that warrants a refactor.

It's probably difficult (most times unnecessary) to make collection view and its layout to not reference each other. Because in most cases, when we create a custom collection view layout, it's not to be used in a generic way. They usually have specific features that are tied to how its user the collection view is used.

If we'd want to explore ways to improve the code health, one small step might be to replace the generic `delegate` and `collectionView` references with concrete types to make it explicit that the coordinator, the layout, and the collection view they tightly coupled.
