### ISSUE TITLE
Login with site address is blocked after failing the first attempt.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#20985]
### Expected behavior
Login with correct site address should always work.

### Actual behavior
Login with site address is blocked after failing the first attempt. 

The user will only be able to proceed with login if they cancel and start over, or if the correct site address includes `http://` or `https://`.

| First try - Wrong site address | Following tries - No `https://` | Success after adding `https://` |
| - | - | - |
| <img width="600" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/42008628/29101abb-cd13-4695-9494-2d4a26721150"> | <img width="600" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/42008628/4baf51b5-bfd0-4352-a15f-3310428ff3fb"> | <video width="300" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/42008628/d75988a8-8e5f-434b-a1b6-9dd3323e45d4"> |

### Steps to reproduce the behavior
1. On Login screen, tap `Enter your existing site address` (Alternatively, try to add a self-hosted site from the Site Picker)
2. Inform a non-existing WordPress site address like `zzzz.zzz.zz`
3. Tap `Continue` and notice the error message
4. Type the existing site address
5. ❌ `There is no valid WordPress site at this address.` error is displayed.

Tested on iPhone 13, iOS 16.5, Jetpack iOS / WordPress iOS 22.7

**Comment by tiagomar** [comment]
The error message is the same as in #18497, but in that case a specific site is mentioned and a first failed attempt is apparently not required.

**Comment by dcalhoun** [comment]
I encountered this recently while testing. 

I have seen negative store reviews more than once where users state the app claims their valid site address is invalid. Those reviews seem related to this easily reproducible issue. Typing on mobile devices is difficult and error prone. It is likely quite easy to mistype an address and subsequently have the app claim it is invalid after fixing a typo.
