### ISSUE TITLE
You cannot post comments only if you insert your credentials when you use the option "View Site"

### ISSUE THREAD

**Issue by dolorespente** [wordpress-mobile/WordPress-iOS#2098]
Steps to reproduce
1. Log in as the Steps to reproduce
2. Go to your blog
3. Use the option "View Site"
4. Go to a post
5. Try to leave a comment
 
Expected results:
We expect to post the comment as the owner of the blog without loging in again or giving any credentials.

Actual result:
You are required to insert your name and e-mail, and if the e-mail is used for WP account you have to also give your password.

Mention: tested on IOS iPad 7.1.2, iPhone 7.1.1    WP 4.1.3;  Oracle: desktop version of WP: after you log in when you open the app, you don't have to log in again when you want to leave a comment

**Comment by rachelmcr** [comment]
Thanks for the detailed report. This happens because when you use "View Site" you don't always get a logged-in view of the site. That issue is currently being tracked and discussed in #4381, so I'm closing this issue.
