### ISSUE TITLE
Stats: Sites for clicked URLs do not open

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#21121]
### Expected behavior
Tapped link to open in a web view.

### Actual behavior
- Only links on the Stats view seem to open
- Links on the "View more" view do not open properly - they may show a Gravatar icon

https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/e42e0ce6-ea13-4517-985a-35b0cb144f62

### Steps to reproduce the behavior
1. Add multiple links to a site's post (seven worked in my case)
2. In an incognito session, click the links in a web browser so they are registered in Jetpack Stats
3. Open the site in the Jetpack app -> Stats -> Days tab, scroll to the Clicks section
4. Tap a link
5. **Observe** that a web view is loaded for the link
6. Close the web view
7. Tap "View more"
8. Tap the same link

**Comment by twstokes** [comment]
Set to medium priority due to:
- Low Severity
- High number of users affected

**Comment by masterspin** [comment]
Hi @twstokes , I would like to take a look into adding this feature. Could you assign this task to me? Thanks

**Comment by masterspin** [comment]
I have made a pull request here: https://github.com/wordpress-mobile/WordPress-iOS/pull/22061
