### ISSUE TITLE
Reader: pressing bookmark icon triggers like button animation

### ISSUE THREAD

**Issue by bluefuton** [wordpress-mobile/WordPress-iOS#21141]
### Expected behavior

When I press the bookmark icon, there are no side effects on the like button.

### Actual behavior

When I press the bookmark icon, the like button animation is unexpectedly shown.

https://github.com/wordpress-mobile/WordPress-iOS/assets/17325/47bad899-91a1-466a-bf39-323712656230

### Steps to reproduce the behavior

To to the Reader tab and find a post that you haven't bookmarked yet in Following.

Press the bookmark icon and keep an eye on the like button on the right hand side.

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

iPhone 13 mini, iOS 16.5.1 (c), Jetpack iOS v22.7

**Comment by tiagomar** [comment]
No longer reproducible with the Reader modernization released with 23.5.
