### ISSUE TITLE
My Site: Site title loading indicator is slightly off

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#21176]
### Expected behavior

The loading indicator should be placed properly, with equal leading constraints to the site's URL link.

### Actual behavior

![site-title-loader](https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/124777b9-810d-4a08-ada3-22b3460d3f88)

### Steps to reproduce the behavior

1. Launch the Jetpack app.
2. Tap on the site title to edit the site title.
3. Make some small changes, and tap 'Done'.
4. Observe that the loading indicator is slightly misplaced.

**Comment by kean** [comment]
Fixed in the scope of https://github.com/wordpress-mobile/WordPress-iOS/pull/21502
