### ISSUE TITLE
Quick Start guide notices are easily overridden by regular notices

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#21177]
### Expected behavior

I'm not sure if this is expected behavior, but perhaps the less-important notices should not dismiss the Quick Start guide? Perhaps the notices can be "stacked", and be automatically dismissed according to their configuration without overwriting Quick Start's persistent notices.

### Actual behavior

After doing the task recommended by Quick Start, a success notice dismisses the Quick Start's notice.

### Steps to reproduce the behavior

1. Begin Quick Start by either creating a new site or restarting the steps from the debug menu.
2. Follow the steps until the one where you need to update the Site Title.
3. Update the site title.
4. 🔎 After updating, observe that the next Quick Start step is shown, but shortly dismissed by a success notice for the site title update action.

If this is expected behavior, feel free to close this issue!

**Comment by tiagomar** [comment]
No longer reproducible.
