### ISSUE TITLE
You cannot reblog a post again if you delete it after it was previously rebloged

### ISSUE THREAD

**Issue by dolorespente** [wordpress-mobile/WordPress-iOS#2118]
Steps to reproduce:
1. Reblog a post
2. Delete the post from your site
3. Go back to reader
4. Try to reblog the same post again

Expected result:
To be able reblog it again from the same place.

Actual result:
The reblog button remains activated (like it was pressed before) and you can not press it again.

**Comment by blowery** [comment]
@aerych what api changes?

**Comment by aerych** [comment]
@blowery Past me forgot to relay that info to present me. :-/

**Comment by aerych** [comment]
Superseded by #3852
