### ISSUE TITLE
Integrate PHPickerViewController

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#21190]
Integrate [`PHPickerViewController`](https://developer.apple.com/documentation/photokit/phpickerviewcontroller).

<img width="1350" alt="Screenshot 2023-08-09 at 5 55 35 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/0472ce9d-7209-4182-b49a-ccceeb4882a2">

### Changes

- https://github.com/wordpress-mobile/WordPress-iOS/pull/21343
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21360
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21370
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21369
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21388
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21389
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21391

**Out of the Scope**: 
- Aztec (deprecated, won't risk introducing regressions)
- Stories (low usage, integration is more complicated than on other screens meaning high risk of regressions)

### Fixes

These fixes were made in the scope of the task:

- https://github.com/wordpress-mobile/WordPress-iOS/pull/21352
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21398
- https://github.com/wordpress-mobile/WordPress-iOS/pull/21411

### Advantages

- No need to request access to the photo library
- Allows you to see your albums and favorites
- Zoom
- Search (if you have enough photos)
- Consistent UI with the Photos app
- Apple maintains and improves it every year
- Allows excluding location metadata from the assets (iOS 17)
- Runs out of process
- Should be much better at supporting massive photo libraries
- Modernize the codebase by removing the legacy [Objective-C code](https://github.com/wordpress-mobile/MediaPicker-iOS)
- The new system for adding assets to the post eliminates memory spikes (more in https://github.com/wordpress-mobile/WordPress-iOS/pull/21360)

### Limitations

- There is no way to add custom UI to `PHPickerViewController`, so it won't be possible to add "Edit" feature to the picker. Fortunately, the app already allows the users to edit the photos after selection, and based on Tracks, the number of users who take advantage of editing is low (<2% of total uploads).
- I'm yet to find a way to export full-size RAW images. NSFileProvider servers a downscaled version. More info [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/21343#issuecomment-1684292986).
- We can no longer show the video duration upload limit for free plan directly in the picker. More info [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/21411).

### Closed Defects

Replacing the custom picker with a native allowed us to close the following issues:

- https://github.com/wordpress-mobile/WordPress-iOS/issues/21085
- https://github.com/wordpress-mobile/WordPress-iOS/issues/21189
- https://github.com/wordpress-mobile/WordPress-iOS/issues/19576
- https://github.com/wordpress-mobile/WordPress-iOS/issues/21081
- https://github.com/wordpress-mobile/WordPress-iOS/issues/13454
- https://github.com/wordpress-mobile/WordPress-iOS/issues/11738
- https://github.com/wordpress-mobile/WordPress-iOS/issues/17468

### More Info

- [NSItemProvider in depth](https://www.humancode.us/2023/07/08/all-about-nsitemprovider.html)
- [WWDC20: Meet the new Photos picker](https://developer.apple.com/videos/play/wwdc2020/10652/)
- [WWDC22: What's new in the Photos picker](https://developer.apple.com/videos/play/wwdc2022/10023)
- [WWDC23: Embed the Photos Picker in your app](https://developer.apple.com/videos/play/wwdc2023/10107)

**Comment by kean** [comment]
@staskus , @Guarani, thoughts on this one?

It fixes a number of issues, not to mention the massive UX improvements.

- https://github.com/wordpress-mobile/WordPress-iOS/issues/21102
- https://github.com/wordpress-mobile/WordPress-iOS/issues/20890
- https://github.com/wordpress-mobile/WordPress-iOS/issues/21189
- https://github.com/wordpress-mobile/WordPress-iOS/issues/21085

**Comment by kean** [comment]
One of the other benefits of using the native picker is that it runs out of process, so it doesn't contribute to the app's memory usage. It can be hugely beneficial, for example, if you are editing a post that already requires a lot of memory. It will also never bring the app down if it crashes.

Uploading media from the device must be one of the major reasons users will want the app on their phones. It has to work flawlessly.

**Comment by staskus** [comment]
@kean, thanks for the proposal!

I agree with your reasoning, especially given the benefits of memory management. Plus, since it's native it will require less maintenance compared to maintaining our own library [MediaPicker-iOS](https://github.com/wordpress-mobile/MediaPicker-iOS).

[PHPickerViewController](https://developer.apple.com/documentation/photokit/phpickerviewcontroller) is fairly new, when starting fresh I doubt we would choose to create our own [MediaPicker-iOS](https://github.com/wordpress-mobile/MediaPicker-iOS).

To make a transparent transition, I think it would be good to map the features that we use of [MediaPicker-iOS](https://github.com/wordpress-mobile/MediaPicker-iOS) and [PHPickerViewController](https://developer.apple.com/documentation/photokit/phpickerviewcontroller) to be transparent about what can be supported out of the box and what we would lose out (if anything) if we make the transition. A quick search shows that the picker is used not only for picking the photo from the device but also for `WordPress Media Library`, `Free Photo Library`, and `Free GIF Library`, at least from the editor (`TenorPicker`, `StockPhotosPicker`, `MediaLibraryPicker`).

**Comment by osullivanchris** [comment]
Came across this PR from your comment re; KPIs. Please push to make this happen and advocate for same on Android. Sounds great.

**Comment by osullivanchris** [comment]
This approach 100% makes sense when the user wants to access all their device images. I just wanted to check something. We have some explorations where we're showing media in line. 

- In the first example, the user has added an image block. Before opening the full library of photos on the device, Paul tried showing some recent images within the sheet
- In the second example, I was playing around with showing images in the editor empty state. So a user could add an image in one tap, before even choosing an image block. 


![in-line media examples](https://github.com/wordpress-mobile/WordPress-iOS/assets/50576199/c365b2b8-553f-4bc5-a14c-a4ec6cb14329)


Of course in both cases we'd need an entry point to the full 'phone library' of images. But I'm just wondering does what we're doing in these cases play well with what you're proposing here, or does it contradict what you're suggesting?

**Comment by kean** [comment]
@osullivanchris, the iOS has the APIs to do both:
- When you enter the fullscreen experience, we can show the native picker
- There is also a way to display the recent local assets in any way you want in the app

**Comment by kean** [comment]
> I agree with your reasoning, especially given the benefits of memory management. Plus, since it's native it will require less maintenance compared to maintaining our own library [MediaPicker-iOS](https://github.com/wordpress-mobile/MediaPicker-iOS).

@staskus we are on track to completely eliminate the need for the MediaPicker repo: the Photos picker is already in the works, and the Media screen will be re-written to Swift in phase 2. It will be a huge win to help modernize the codebase. The only missing part is the "Free" libraries that, based on Tracks, virtually nobody use.

**Comment by staskus** [comment]
Thanks for sharing @kean, that's great news! 👍

**Comment by mokagio** [comment]
I bumped some of the PRs in this issue from [23.1](https://github.com/wordpress-mobile/WordPress-iOS/milestone/255) to 23.2 because they were not ready to merge and the 23.1 code freeze will start shortly. I'll do the same with this issue, for consistency.

If this cannot wait two weeks and it's important that it makes it into this release, let me know and we'll organize a new beta once ready.

**Comment by kean** [comment]
It's done.
