### ISSUE TITLE
Contact Us: Unable to enter a message

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-iOS#21196]
### Expected behavior
Expect to be able to type a message in the Contact Us view

<img width="200" height="400" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/506707/99ea10e1-c1a6-4b0f-8961-ae3e404dd7a1">

### Actual behavior
There is no ability to type a message. The keyboard is not shown when tapping in the input area and a "Scan Text" message is shown.

### Steps to reproduce the behavior
- Install 22.9.0.0
- Tap Continue with WordPress.com button
- Tap help
- Tap contact support
- Tap in the "Write a message" text input area
- Note that the keyboard doesn't open and a "Scan Text" message is shown

**Note: This happened to me three times, but it is not consistently repeatable. Sometimes if I enter the email address first and then tap Help, then the keyboard will show in the Contact Support form. It goes the other way as well, if I am in the contact form and am unable to get the keyboard to open, then navigating back to the enter email screen, then the keyboard doesn't show for the email address field. Perhaps it's an iOS thing and not an app thing?

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
iPhone, iOS 16.3.1, Jetpack iOS v22.9.0.0

**Comment by kean** [comment]
I tried five time – clean build each time – and was not able to reproduce it.
This screen is provided by Zendesk (SupportSDK.RequestContainerController, closed-source).

**Comment by zwarm** [comment]
Thanks @kean . Since this is owned by Zendesk and it can't be reproduced, I'm going to close the ticket.
