### ISSUE TITLE
Jetpack App Crash When Trying to Publish

### ISSUE THREAD

**Issue by thabotswana** [wordpress-mobile/WordPress-iOS#21218]
A user reported that when they tap "Publish" in the app, it crashes.

I found a [Sentry report](https://a8c.sentry.io/discover/jetpack-ios:52f0d98258354132bbc5a87c05305169/?field=title&field=event.type&field=project&field=user.display&field=timestamp&field=replayId&homepage=true&name=All+Events&project=5716771&query=user.email%3Apublisher%40thecapitalsportsreport.com&sort=-timestamp&statsPeriod=14d&yAxis=count%28%29) with the following error:

`NSInternalInconsistencyException: Invalid update: invalid number of items in section 0. The number of items contained in an existing section after the update (6101) must be equal to the number of items contained in that section before the update (9), plus or minus the number of items inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out). Collection view: <UICollectionView: 0x1058aa200; frame = (0 0; 430 807); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x283e1afa0>; backgroundColor = <UIDynamicProviderColor: 0x283130ac0; provider = <__NSMallocBlock__: 0x283f366d0>>; layer = <CALayer: 0x2837f8f20>; contentOffset: {0, -56}; contentSize: {430, 428}; adjustedContentInset: {56, 0, 34, 0}; layout: <UICollectionViewFlowLayout: 0x104421420>; dataSource: <WPMediaPickerViewController: 0x10588da00>>`

##### User/device details
Ticket link: 6595660-zen
App version: 22.8.0.3
Device model: iPhone15,3
OS version: iOS 16.6
Type of site: Jetpack

**Comment by kean** [comment]
Thanks for the report, @thabotswana. The team is currently investigating this crash, which is being tracked in the following issue https://github.com/wordpress-mobile/WordPress-iOS/issues/21102. I'm going to close this one as a duplicate. Thanks for the additional context.
