### ISSUE TITLE
Update FABs color

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#21284]
Should match Android (black instead of current green).

**Comment by momo-ozawa** [comment]
Hey @osullivanchris 👋 

Looked through some old threads (ref: p1686633672245249/1686513683.293089-slack-C04SFL0RP51)  - are we using gray90 for light mode and gray80 for dark mode?

**Comment by osullivanchris** [comment]
Do we think its better to use iOS System colors or [Automattic's color studio](https://color-studio.blog/)? 

For iOS system colours I think on light mode we'd either need to use label colour, or a system colour from dark mode. All the light mode greys provided are very light.

For dark mode if we want to use iOS system colors, system grey 2 has the desired appearance.

Let's also change the icon to the simpler plus icon.

<img width="1975" alt="Screenshot 2023-08-11 at 12 59 37" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/50576199/bb173291-c7df-4bd8-866a-64e5b3a1cbbc">
