### ISSUE TITLE
Allow sharing multiple photos to the app

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#21334]
### Expected behavior

I should be able to select multiple photos in the Photos app and share them to the Jetpack app.

### Actual behavior

After selecting multiple photos and tapping the JP app in the share sheet, nothing happens (it does a slight animation as if to open the JP app and then stops). Only if I choose a single photo to share does it work.

### Steps to reproduce the behavior
1. Open the Photos app
2. Select multiple photos 
3. Tap the share button
4. Tap the Jetpack icon in the share sheet
5. Notice that nothing happens

**Comment by kean** [comment]
I can't reproduce it; tried up to 7 photos.

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/233e1e92-90ad-4428-ac0d-8c7ee6ff4f36

**Comment by guarani** [comment]
It's working now for me, too! I'm closing this.
