### ISSUE TITLE
Contact Support: Open from different parts of the app

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#21347]
1. New bot interface is opened from all the places where support can be reached:
- Gutenberg Editor
- Account Settings
- Notifications view
- Help & Support view
2. The ticket creation flow works fro all the entry points

**Comment by ravishanker** [comment]
- Gutenberg Editor - ( FAB -> Create Post -> : menu on top right hand corner next to Publish -> Help & Support)

  - **Contact Support**) is going to Zendesk.

  - More support options goes to Help screen so it is covered.

- **Log in** 
  - **Contact Support** (Help (?) at the top right corner -> Help) -> is going to Zendesk
  - **Need more help?** ("Enter your existing site address" -> "Find your site address" -> "Need more help?") -> is going to Zendesk


- Account Settings (Me -> Account Settings -> Close Account -> Contact Support -> Help -> Contact Support) is covered, nothing to do

- Notifications view - is there Help/Contact Support?

- Help & Support view - is covered
