### ISSUE TITLE
[Reader] - Saving a post from discover tab shows the discover tab on saved tab

### ISSUE THREAD

**Issue by jostnes** [wordpress-mobile/WordPress-iOS#21415]
### Expected behavior
When saving a post from Discover tab, only the saved post should appear on Saved tab

### Actual behavior
Found during review of https://github.com/wordpress-mobile/WordPress-iOS/pull/21412. When saving a post from Discover tab, the Saved tab shows everything that was on Discover tab

### Steps to reproduce the behavior
1. Go to Reader
2. Tap on Discover tab
3. Save any of the posts displayed
4. Tap `View` on the `Post Saved` notice when it appears
5. See that user is redirected to `Saved` tab but the content of the page is exactly the same as what was on `Discover` (to get the correct content to show, tap to go to another tab before returning to `Saved` again)

See:
https://github.com/wordpress-mobile/WordPress-iOS/assets/17252150/b05f1252-44bb-4b97-b86b-125aba663a10

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
Test on Simulator iPad Air, iOS 16.4. Also reproducible on iPhone 13 Pro, iOS 16.4, v23.1

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Should be fixed in the re-implemented version.
