### ISSUE TITLE
🍎 Add Domains Button to the Me Screen

### ISSUE THREAD

**Issue by alpavanoglu** [wordpress-mobile/WordPress-iOS#21424]
Add `Domains` button to the "Me" Screen. Until the new improvements are made for the "Me" screen, we can simply add the button as a new row to the list.

## Acceptance Criteria
- A new row titled "Domains" should be visible on the Me Screen.
- Tapping on it should open the Domains List Screen.

**Comment by hassaanelgarem** [comment]
@alpavanoglu As mentioned in #21701, there's an upcoming PR to polish UI changes. Should this issue be moved to "In Development" then?
Ref: https://github.com/wordpress-mobile/WordPress-iOS/pull/21701#pullrequestreview-1695974734

**Comment by hassaanelgarem** [comment]
@alpavanoglu While testing the linked PR I noticed that the Domains button is visible for logged-out users with just self-hosted sites. I believe it should be hidden in this case.

cc @mkevins In case this case is not handled on Android

**Comment by mkevins** [comment]
> cc @mkevins In case this case is not handled on Android

Indeed, the same issue exists on Android. Good catch!

**Comment by hassaanelgarem** [comment]
Moved this back from Done, and linked it to #21935
cc @alpavanoglu

**Comment by mkevins** [comment]
Following up: this same issue on Android has been resolved with https://github.com/wordpress-mobile/WordPress-Android/pull/19539.
