### ISSUE TITLE
🍎 Add Domain Menu UI

### ISSUE THREAD

**Issue by alpavanoglu** [wordpress-mobile/WordPress-iOS#21425]
Adds the menu accessed from the FAB button.

## Acceptance Criteria
- The menu should contain the 3 options: "Add domain to site" | "Purchase domain only" | "Transfer domain(s)"
- UI should match the designs.

## Screenshot for Reference

![Image](https://user-images.githubusercontent.com/15968946/263297568-6ca240f9-e887-4cdc-ba93-ebb8923b8294.png)

**Comment by hassaanelgarem** [comment]
@alpavanoglu @salimbraksa We no longer need a context menu in the domains list screen. I haven't tested the changes in the linked PRs, and I can't see screenshots, but it's possible we'll need to revert some changes from the linked PRs. Can you please check? 🙏 
Project Spec Ref: pc8HXX-1gR-p2#domains-list
Slack Ref: p1694094368274089-slack-C05NS0YV7HS

**Comment by alpavanoglu** [comment]
We can close down this issue as it has become obsolete with the update.
