### ISSUE TITLE
When you bookmark a post, like button animates

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#21436]
Recording:

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/0a9ed2a2-c2ca-4261-bd3d-393e7c4007dd

**Comment by twstokes** [comment]
Good catch @kean - looks like we also have https://github.com/wordpress-mobile/WordPress-iOS/issues/21141, so we can consolidate.
