### ISSUE TITLE
Posting from unverified WP.com account results in broken flow

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#21472]
### Expected behavior

When I try to post from the Jetpack app with a WP.com account that hasn't been verified yet (I haven't clicked the verify email), the editor should seamlessly allow me to verify the email before publishing.

### Actual behavior

Instead, there are some issues:
- The email sent when I click Resend doesn't open the Jetpack app but instead the web browser
- If I return to the app, it shows a blank bottom sheet (I'm not sure what it's supposed to show)

### Steps to reproduce the behavior

The steps I recall are these (I'm not confident I recall all steps correctly):
1. On WP.com, create an account but don't verify it yet
2. Log in on the app using the account's username and password
3. Create a post and try to publish it
4. When the app informs you that the account is unverified, tap Resend
5. Open the email in the device's email client and tap the link to verify
6. Notice that the link doesn't open the installed Jetpack app but instead opens in the browser ⚠️ 
7. Follow the steps in the browser to verify the email anyway
8. Return to the app and notice the blank bottom sheet ⚠️ 

### Additional information

See p1693352915619269/1693352778.413019-slack-C6UJ0KRKQ

##### Tested on iPhone 11, iOS 17 beta, Jetpack iOS 23.1 beta

**Comment by SiobhyB** [comment]
We receive a one star app review on the Google Play store due to this broken flow:

> Multiple error messages that I need to verify my email address and not able to publish drafts so they are only saved locally on my device

**Comment by kean** [comment]
This step was removed in the scope of the "Offline Mode" project. WP.com doesn't perform verification for this step. If it needs to be added in the future, it will need to be re-implenented and should be based on API error codes and not hardcoded in the app.
