### ISSUE TITLE
Quick Start automatic scroll obscures Pages menu item

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/WordPress-iOS#21506]
### Expected behavior
When completing the "Review site pages" Quick Start item, the view is scrolled to the point where the Pages menu item is easily seen. 

### Actual behavior
When completing the "Review site pages" Quick Start item, the view is scrolled to the point where the Pages menu item is partially obscured. 

<details><summary>Screenshot</summary>

![quick-start-review-pages](https://github.com/wordpress-mobile/WordPress-iOS/assets/438664/e79cce85-d2be-4b94-be46-fdf781b2c132)

</details>

### Steps to reproduce the behavior
1. Create or log into a WordPress.com account. 
2. Create a new site. 
3. Begin the Quick Start tour. 
4. Select the "Review site pages" task. 
5. Tap the "Menu" tab.

**Comment by dcalhoun** [comment]
👋🏻 @momo-ozawa I wondered if this relates to https://github.com/wordpress-mobile/WordPress-iOS/pull/21348. Are you able to reproduce this issue?

**Comment by tiagomar** [comment]
I confirmed that I can reproduce in `23.2` and it works fine on `23.1`.

**Comment by momo-ozawa** [comment]
Hey @dcalhoun, @tiagomar - thanks for raising this!

https://github.com/wordpress-mobile/WordPress-iOS/pull/21502 will change the layout for the dashboard, and this will no longer be an issue.

I'll look into if there's a quick fix for this issue for 23.2, but just wanted to point out the changes to the dashboard targeting 23.3 🙇‍♀️

**Comment by kean** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/21502
