### ISSUE TITLE
Cannot change site icon during Quick Start flow

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/WordPress-iOS#21507]
### Expected behavior
After selecting the "Choose a unique site icon" task of the Quick Start flow, tapping the site icon opens a menu to change the icon image and thus completing the task. 

### Actual behavior
After selecting the "Choose a unique site icon" task of the Quick Start flow, tapping the site icon does nothing. 

<details><summary>Screen recording</summary>

https://github.com/wordpress-mobile/WordPress-iOS/assets/438664/aebbadb4-7d61-4535-99e2-820f64e38538

</details>

<details><summary>Screenshot</summary>

![quick-start-site-icon](https://github.com/wordpress-mobile/WordPress-iOS/assets/438664/66ac4619-55f0-4b05-8fb6-54ebd49ed473)

</details>

### Steps to reproduce the behavior
1. Create a WordPress.com account. 
2. Create a new site. 
3. Begin the Quick Tour flow. 
4. Select the "Check your site title" task. 
5. Modify the site title. 
6. Begin the "Choose a unique site icon" task. 
7. Tap the site icon to the left to the site name and address.

**Comment by dcalhoun** [comment]
👋🏻 @kean I wondered if this relates to https://github.com/wordpress-mobile/WordPress-iOS/pull/21370. Is that feature enabled in 23.2? Are you able to reproduce this issue?

**Comment by kean** [comment]
It's likely related.

> Is that feature enabled in 23.2?

Yes, and this flow has been tested. I've also been testing it extensively today in the scope of https://github.com/wordpress-mobile/WordPress-iOS/issues/21492

> Are you able to reproduce this issue?

No, can you think of any prerequisites?

**Comment by dcalhoun** [comment]
@kean I am unable to reproduce now. I'll continue exploring and follow with more information or close the issue. Thanks!

**Comment by tiagomar** [comment]
I couldn't reproduce it either on iPhone or iPad.

**Comment by kean** [comment]
You have to be an admin and have `upload_files` capability to change the icon. The tour seems to be shown regardless of whether you are eligible or not. This may be the reason why it didn't work.

**Comment by dcalhoun** [comment]
@kean I reproduced the issue again. I updated the reproduction steps and added a screen recording. 

I believe the nuanced step may be one of two: 

1. Changing the site title via the Quick Guide's "Check your site title" task _before_ attempting to complete the "Choose a unique site icon" task. 
2. Using a brand new account. 

My guess is the first. Let me know if you can reproduce with the updated steps. Thanks! 🙇🏻

**Comment by kean** [comment]
**RCA**

When you create an account and open the site for the first time, the local blog in the database briefly has no admin access:

```swift
(lldb) po blog.isAdmin
false
(lldb) po blog.isUploadingFilesAllowed()
false
```

But the menu is created once and doesn't change if the blog status changes:

```swift
    func makeSiteIconMenu() -> UIMenu? {
        guard siteIconShouldAllowDroppedImages() else {
            return nil
        }
        return UIMenu(children: [
            UIDeferredMenuElement.uncached { [weak self] in
                $0(self?.makeUpdateSiteIconActions() ?? [])
            }
        ])
    }
```

**Workaround:** if you close the app and reopen it, the menu starts working. 

Steps I used:

- Create a new account
- Create a new site
- Tap the site icon (quick tour is not a required step)

In order to fix it, I'll move the eligibility check inside `UIDeferredMenuElement.uncached` so that it's performed every time you invoke the menu.
