### ISSUE TITLE
Blogging Reminders prompt not displayed after publishing first blog post

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/WordPress-iOS#21505]
### Expected behavior
The Blogging Reminders bottom sheet is displayed after I publish my first blog post. 

### Actual behavior
The Blogging Reminders bottom sheet is _not_ displayed after I publish my first blog post. 

<details><summary>Screen recording</summary>

https://github.com/wordpress-mobile/WordPress-iOS/assets/438664/44218834-8cd4-4ab0-9e9d-00cd91b1dd01

</details>

### Steps to reproduce the behavior
1. Create or log into a WordPress.com account. 
2. Create a new site. 
3. Publish a post.

**Comment by dcalhoun** [comment]
I added a screen recording to the description. Also, I am able to reproduce this while reproducing https://github.com/wordpress-mobile/WordPress-iOS/issues/21507, so it may relate to the Quick Guide. I wonder if reproducing the absent Blogging Reminders requires following the steps in https://github.com/wordpress-mobile/WordPress-iOS/issues/21507 first before publishing the first post.

**Comment by twstokes** [comment]
👋 Hey @dcalhoun, is this issue the same as https://github.com/wordpress-mobile/WordPress-iOS/issues/18696?

**Comment by dcalhoun** [comment]
@twstokes I believe it is highly likely this issue is duplicative of https://github.com/wordpress-mobile/WordPress-iOS/issues/18696. Thank you for connecting them.
