### ISSUE TITLE
Post publish screen lacks bottom padding on devices with a home button

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/WordPress-iOS#21509]
### Expected behavior
The post-publish screen displays bottom padding between the content and the display edge. 

### Actual behavior
The post-publish screen content is flush with the bottom of the display. 

<details><summary>Screenshot</summary>

![post-publish](https://github.com/wordpress-mobile/WordPress-iOS/assets/438664/a6e40b38-85db-4492-9b75-c30218786e67)

</details>

### Steps to reproduce the behavior
1. Publish a post on an iPhone SE. 
2. Tap View in the post published in-app notification.

**Comment by tiagomar** [comment]
It also happens on iPad (portrait and landscape).

**Comment by kean** [comment]
The design has been updated in the scope of https://github.com/wordpress-mobile/WordPress-iOS/pull/23128. This issue no longer applies.

<img width="360" alt="Screenshot 2024-05-01 at 12 33 17 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/adb0fb51-b370-4113-9a9d-c437bb59a2b3">
