### ISSUE TITLE
Stats option not shown for self-hosted site

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#21516]
### Description

Self-hosted sites with or without WP.com account do not show the Stats option in the menu. They are still shown on Android.

![Simulator Screenshot - iPhone 14 - 2023-09-07 at 14 45 12](https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/92555ec1-2165-4fcf-88b3-9137705669e2)

**Comment by twstokes** [comment]
@staskus does this articulate the issue accurately?

Stats visibility in iOS:

| Site type | Should show stats | Actually shows stats | Status |
| - | - | - | - |
| Self-hosted, no Jetpack | No | No | ✅ |
| Self-hosted, Jetpack site-connection only | Yes | No | ❌ |
| Self-hosted, Jetpack with user connection | Yes | Yes | ✅ |

**Comment by staskus** [comment]
@twstokes not entirely. I think we should always show the Stats option since we allow to install Jetpack plugin and establish user connection. You can check Case 4 (and video "Full installation flow (Case 4)") of the testing plan of this PR (https://github.com/wordpress-mobile/WordPress-iOS/pull/20307), as long as I worked on the app it was possible to access Stats menu option and install Jetpack. 

The only case we shouldn't show Stats would be if there's a configuration that prevents us from installing the Jetpack plugin.

**Comment by twstokes** [comment]
> I think we should always show the Stats option since we allow to install Jetpack plugin and establish user connection

True! I agree. We can look at "Notifications" as a similar model.

So this becomes:

| Site type | Should show stats | Actually shows stats | Status |
| - | - | - | - |
| Self-hosted, no Jetpack | Yes | No | ❌  |
| Self-hosted, Jetpack site-connection only | Yes | No | ❌ |
| Self-hosted, Jetpack with user connection | Yes | Yes | ✅ |

**Comment by staskus** [comment]
We hidden Stats here https://github.com/wordpress-mobile/WordPress-iOS/pull/20623 and we did that for more cases than we wanted:

> Contributors do not have the permissions to view stats, yet we show the stats button in the My Site Menu. This PR removes the stats button when unsupported.

There are user reviews as well as support tickets related to this 6737974-zd-a8c.

**Comment by kean** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/21548
