### ISSUE TITLE
Posts list flashes after quit searching

### ISSUE THREAD

**Issue by crazytonyli** [wordpress-mobile/WordPress-iOS#21546]
### Expected behavior
The posts list does not flash when switching tabs

### Actual behavior
The posts list flashes when switching tabs

### Steps to reproduce the behavior
1. Go to Posts List.
2. Tap the search bar and then the Cancel button to quit searching
3. Switch among the Published, Draft, Scheduled, and Trashed tabs

https://github.com/wordpress-mobile/WordPress-iOS/assets/1101828/26dbd7f7-2976-4cc7-b58c-bf7a827f9b7f

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
trunk (https://github.com/wordpress-mobile/WordPress-iOS/commit/74c91bb1a90966d764ba1df7a0a040fd5bfa6095)

**Comment by kean** [comment]
There are still ways to go, but we largely fixed both the loading animations (by removing ugly skeleton cells) and replacing the search with `UISearchController`.

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/e9d2f406-eeb4-442d-b6e0-fa9b501b3d13

(disregard the misaligned state views).

I think it should also show the full-screen loading view only the first time you open the tab.
