### ISSUE TITLE
Contact Support: Investigate scrolling issues

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#21549]
## After a long answer, the web view prevents from scrolling up and seeing the whole message

https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/db833d63-ee43-46ff-9288-8ca8f41748fd

It happens due to 2 scroll views existing:
- One for scrolling chat message content
- One for scrolling the whole view when the keyboard appears

- Keyboard lifts the content too much making the short message not visible without scrolling

More information: p5T066-44s-p2#comment-14854

**Comment by ravishanker** [comment]
Just wondering, dismissing if keyboard offers better experience than scrolling up.  They have to scroll back down for long answers as it cuts-off top when scrolled-up.

**Comment by staskus** [comment]
> Just wondering, dismissing if keyboard offers better experience than scrolling up. They have to scroll back down for long answers as it cuts-off top when scrolled-up.

@ravishanker  Since I couldn't yet find a working solution to fix scrolling issues, automatically dismissing a keyboard after submitting a question could help "hide" both issues: 1) first message not visible 2) double scroll bar. I'll try to see what would be the experience.

**Comment by staskus** [comment]
The behavior that causes these problems turns out to be a long-running "feature" on mobile Safari https://bugs.webkit.org/show_bug.cgi?id=141832

The viewport size does not change; instead, the whole view goes up when the keyboard appears, causing unwanted behavior for the messaging interface. This is intentional from the mobile Safari side since this solution performs better than resizing and keeps 60fps.

[There're workarounds](https://blog.opendigerati.com/the-eccentric-ways-of-ios-safari-with-the-keyboard-b5aa3f34228d), none of which sound robust:
- Trick Safari by momentarily placing the input field high enough on the page, and then returning to the place when the keyboard appears
- Trick Safari by focusing on a dummy input field which is high on the page when user taps on a real input field
- Calculate window heights when the keyboard appears and add additional padding

Even found [a matrix client adding various workarounds for this issue](https://github.com/vector-im/hydrogen-web/pull/279) which is used by [Automattic's chatrix](https://github.com/Automattic/chatrix).
