### ISSUE TITLE
🍎 Domains List Search Bar UI

### ISSUE THREAD

**Issue by alpavanoglu** [wordpress-mobile/WordPress-iOS#21561]
## Screenshot Reference

![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/15968946/53b579a4-bdd4-45dd-853b-9a11a5e1dd91)

**Comment by hassaanelgarem** [comment]
@alpavanoglu Since we've decided to use a native search bar, do we still need this issue?

**Comment by alpavanoglu** [comment]
We'll reuse the existing Search Domain screen so we can close this issue.
