### ISSUE TITLE
Split View broken on Plus/Max iPhones

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#21579]
The issue appeared after the recent dashboard changes introduced in https://github.com/wordpress-mobile/WordPress-iOS/issues/21492. These changes have not shipped yet.

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/9e51e313-4451-4da2-ae8a-7190157f0eb2

Before the changes the behavior was the following:

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/edb0cea6-b9da-4c08-b906-cfab643a5a04

**Comment by kean** [comment]
Hey, @osullivanchris, I think I'll need your input on this one because I need to figure out what's the best way to proceed.

The current behavior in production is the following:

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/d5016abb-2c59-401f-b313-a4b3a66fadfc

I spot at least 8 visual defects in this video alone.

I would argue that the Split View is not designed to be used in this scenario. Apple never does, and we should also stop using it on iPhone on the My Site page and align it with Android, which also doesn't.

The Split View on larger iPhone is designed mainly for homogeneous lists of content where switching between rows and viewing details is quicker with a Split View. Think, Mail app. It also works best if the details screen uses the same design that it well-optimized for a compact width and can't take advantage of the larger width.

In the case of the Home page, there is no need to jump between items quickly. But the Split View does make the experience worse on the details page by limiting their content area. For example, the Media screen could take advantage of the larger screen. And the Split View actually prevents me from hiding the bottom tab bar when showing Media, as I also mentioned in https://github.com/wordpress-mobile/WordPress-iOS/pull/21580.

Another problem with the Split View is that it uses an iPad-style navigation and menus. It clashes with the new menu we introducing in 23.3.

The My Site page without a Split View will look something like this (disregard a few bugs – these will be fixed):

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/73333479-0679-4174-aa25-07ba90ee0584

The Notifications screen will continue working as is. It uses a Split View and takes full advantage of it. This is a textbook scenario.

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/764ac1f2-af20-4c2c-8fc0-17694fe3e099

**Comment by kean** [comment]
The best example is probably the Media screen, so just to compare here is the production version:

<img width="729" alt="Screenshot 2023-09-15 at 9 26 16 AM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/3280c721-7941-41ce-b762-657a05f3c603">

<br/>
<br/>

And here is a potential new version:

<img width="729" alt="Screenshot 2023-09-15 at 9 22 15 AM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/14674d75-73f1-4664-86bb-3c832c27de8b">

<br/>

<img width="729" alt="Screenshot 2023-09-15 at 9 22 19 AM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/0c6b04ae-0c27-4ff6-b55d-393b5787d6d3">

**Comment by kean** [comment]
I'd argue most of the details pages for blog should open with no tab bar to allow for more vertical space.

**Comment by osullivanchris** [comment]
> I'd argue most of the details pages for blog should open with no tab bar to allow for more vertical space.

just on landscape?

**Comment by kean** [comment]
It only works in both or none.

**Comment by kean** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/21588
