### ISSUE TITLE
Allow deep links to be read on the web instead of the app

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#21608]
### Expected behavior

Add the ability to choose whether links such as https://xyz.wordpress.com/2023/09/19/abc are opened by the Jetpack app or the system browser.

### Actual behavior

The Jetpack app handles opening links to blog posts and provides no way to handle these in the system browser.

### Steps to reproduce the behavior
1. On a device with the Jetpack for iOS app installed, open a 3rd party app like notes and paste this link: https://edoodless.wordpress.com/2023/09/14/what-is-your-least-favorite-word/
2. Tap the above link
3. Notice it opens the Jetpack app
4. Notice there's no way to have it open Safari instead

### Additional info
Some apps like Reddit and GitHub mobile app have a setting to control if the app opens external links (although in my testing they didn't work), we could use something similar here.

**Comment by guarani** [comment]
> Opens links from iMessage in the app instead of browser  ·  I'm not sure what happened, but the latest update broke the ability for me to clink on a link I've sent to someone in iMessage to open in a browser window. It now opens the JetPack app and I can't disable this. I'm not pleased with this, it's inconvenient because I'm trying to double check a link  I've sent someone.
> How do I get this behavior to stop? I want all my links in iMesssge to open with a browser instead of the app.
– [App user](https://appfigures.com/reviews/334311506925LuOoNxvin6rkKeZNIWjca5Q?lang=en)

**Comment by guarani** [comment]
👋 @dvdchr, do you happen to know if disabling deep links from opening in the app was ever possible? Asking around because I recall some discussions about deep links earlier this year but a quick search didn't turn it up.

**Comment by twstokes** [comment]
👋 @guarani - is this relevant to the issue you're describing? ref: pbArwn-55r-p2#comment-6328

If so, from my experience it's possible, but it has to be done with these steps:

1. Open a link in Safari (type the URL directly)
2. Long press on a link in Safari – for example, the title of a post.
3. Choose “Open” (top item in the menu)
4. From now on, links should always open in Safari

I haven't investigated if iOS 17 does anything different.

**Comment by guarani** [comment]
Thanks a lot, @twstokes, that does indeed work 👍 
After reading your message, I came across a support article for this: P7jrAc-23h-p2

**Comment by guarani** [comment]
Closing this since there is a way to stop the Jetpack app from opening links.

**Comment by dvdchr** [comment]
Hey @guarani, apologies for missing your ping! I was stuck in the visa application office then and forgot to save this for later 😅. And thanks @twstokes for jumping in 🙇🏼!

Yes, AFAIK, the user pretty much needs to do it manually (as y'all have shared) if they want to override `*.wordpress.com` deeplink patterns only for specific subdomains. However, cases such as #19870 _can_ be addressed by making changes to the site association file (see: D119413-code) since it applies to all users and all subdomains.

**Comment by twstokes** [comment]
Public support link for this issue: https://apps.wordpress.com/support/mobile/posts-and-pages/ios-can-i-prevent-links-to-wordpress-posts-pages-from-automatically-opening-in-the-app/

**Comment by guarani** [comment]
No worries @dvdchr! ❤️ 

Thanks @twstokes for finding the correct link 🙇
