### ISSUE TITLE
Dashboard: Quick Start on "hide this" dismiss next steps and target touch points

### ISSUE THREAD

**Issue by zwarm** [wordpress-mobile/WordPress-iOS#21603]
### Expected behavior
When you tap on the "Hide This" option within the Quick Start Card, the associated snack bars displaying quick start next steps and touch target points are still visible on screen.

### Actual behavior
When you tap on the "Hide This" option within the Quick Start Card, it will dismiss any associated snack bars displaying quick start next steps and hide the touch target points.

### Steps to reproduce the behavior
- Login to the app
- Select "Not sure, show me around" option
- Select the check your site stats option
- Tap the Get to know the app "hide this" more menu option
- Note the associated snack bars displaying quick start next steps and touch target points are still visible on screen.

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
Android 12, iOS 16.6, JP 23.3.0.0

**Comment by kean** [comment]
@osullivanchris, let's remove "Quick Start" from the "Personalization" screen and revert to the previous behavior: when you press "Hide this", it terminates the tours and you never see them again. It'll fix the bug and It'll bring it in line with other one-shot cards, such as "Share", "Free Domain". The rest of the cards on the Personalization screen are "persistent".

**Comment by osullivanchris** [comment]
@kean sounds good for me. There wasn't a very strong case for allowing the user to turn it back on. If it is causing bugs it is not worthwhile. And like you said there is some other precedent now.

**Comment by zwarm** [comment]
@osullivanchris - After I entered this issue, I doubled checked on Android and it seems we are seeing some quirky behavior with this logic as well. I'm going to second opinion the removal of the "Next Steps" and "Getting to know you" cards from the personalize view. Give me a thumbs here @kean that you will be removing both cards. Thanks

**Comment by kean** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/21610
