### ISSUE TITLE
Unsupported block fails to open for editing

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#21620]
An exception on step 5 of TC001 in [unsupported-block-editing---test-cases](https://github.com/wordpress-mobile/test-cases/blob/trunk/test-cases/gutenberg/unsupported-block-editing.md#unsupported-block-editing---test-cases).

<img width="1103" alt="Screenshot 2023-09-21 at 5 06 53 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/492ebeb3-5de0-40dd-b745-6409b639f675">

```
WordPress/GutenbergWebViewController.swift:104: Fatal error: Failed to load `extra-localstorage-entries` JS script for Unsupported Block Editor: sourceFileNotFound("extra-localstorage-entries.js")
```

When I comment out the assertions, it doesn't crash, but the page doesn't load and there is the following message in the consul:

```
Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=54, WKJavaScriptExceptionMessage=TypeError: undefined is not an object (evaluating 'window.wp.data'), WKJavaScriptExceptionColumnNumber=16, WKJavaScriptExceptionSourceURL=user-script:2, NSLocalizedDescription=A JavaScript exception occurred}
```

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/f5d7a603-cf42-4882-b8f4-b6031b7afd23

### Steps to reproduce the behavior
 
Follow the linked TC.

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

iPhone Simulator, iOS 17
23.3 RC (compiled from 9bfba439f1e91f68867af7e1a6f41a3b317f73bf)

**Comment by twstokes** [comment]
Thanks @kean for surfacing this!

**Comment by SiobhyB** [comment]
@kean, thank you for the report! I'm curious whether you've been able to reproduce on an actual device, or only the simulator? I've attempted to reproduce locally and with the latest changes from `trunk`, but haven't been able to.

A previous report of this error was the result of some local settings, which might be something to explore. We're discussing this further here: p1695331938440969-slack-C6UJ0KRKQ

**Comment by geriux** [comment]
Hey there 👋 I've just tested the TC001 test case on a real device and it is working for me I was able to edit an Unsupported block and make changes using the Unsupported block editor, I used an iPhone 14 Pro running iOS 17 on a simple site.

**Comment by kean** [comment]
I could not reproduce the issue on a physical device with 23.3.0.1 installed. I'll prioritizing testing on the device moving forward.

**Comment by tiagomar** [comment]
Assigning `Medium` priority for now but it'll be probably `Low` if we confirm it's a local Simulator issue.

**Comment by SiobhyB** [comment]
@tiagomar, I've gone ahead to change the status to `Low` as we've been able to confirm this is limited to the simulator. As this is also an inconsistent issue that was previously resolved via changes to local settings (ref: p1639698165171500-slack-C6UJ0KRKQ) it also seems unlikely we'll prioritise this anytime soon.

**Comment by kean** [comment]
I opened a PR to add it to the list of known issues https://github.com/wordpress-mobile/test-cases/pull/157 in case someone encounters it again.

**Comment by twstokes** [comment]
Thank you all! I'll remove my assignment and review the PR in https://github.com/wordpress-mobile/WordPress-iOS/issues/21620#issuecomment-1735577157. 🙇
