### ISSUE TITLE
Account and settings: Options not accessible when no sites exist

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#21690]
### Expected behavior
The ability to view the options under the "Account and settings" view.

### Actual behavior
Most options under the "Account and settings" view do nothing.

| WordPress 23.2 | WordPress 23.3 |
| - | - |
| <video src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/36fe7bd8-d363-41ca-b9b6-fd2486e47658" /> | <video src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/5165182e-7c14-43a8-b8d2-b133848d276f" /> |

### Steps to reproduce the behavior
1. Install WordPress version 23.3
2. Create a new account (which will have no sites by default)
3. In the main view, tap "Account and settings"
4. Attempt to tap an option

### Notes
- This does not happen in the Jetpack app
- This does not happen once a site is added in the WordPress app
- This seems to be a regression going from WordPress 23.2 to 23.3

**Comment by twstokes** [comment]
👋 Hey @momo-ozawa would you mind taking a look at this and seeing if there's any relation to the recent work in https://github.com/wordpress-mobile/WordPress-iOS/pull/21348? There may be no connection, but I thought I'd start with you first. Thank you!

**Comment by momo-ozawa** [comment]
@twstokes Will do!
