### ISSUE TITLE
Integrate 1Password into App

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#2170]
https://github.com/AgileBits/onepassword-app-extension

**Comment by jleandroperez** [comment]
Few UX notes from Dave Whitley:
- Show the 1Password action button in the spot in which the 'show password' button currently is (if the extension is available).
- If the user begins typing on any of the textFields, let's fall back to the 'Show Password' button.

**Comment by sendhil** [comment]
@jleandroperez are you going to add it to the app?

**Comment by jleandroperez** [comment]
@sendhil Yes sir! on the way!
