### ISSUE TITLE
Two Step Authentication Warning Isn't Translated

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#2172]
![image](https://cloud.githubusercontent.com/assets/437043/3775724/5c63334c-1949-11e4-8926-c81958260e69.png)

**Comment by rachelmcr** [comment]
I tried testing this and can no longer get this error message to come up. When I tried logging in to a WordPress.com account with 2FA enabled, I get this error instead:

>Invalid username or password

I brought this up in #4521 and am closing this issue for now.

I also checked GlotPress and see that the string in the screenshot above is translated into Japanese ([see translated string](https://translate.wordpress.com/projects/wpcom/ja/default?filters[status]=either&filters[original_id]=54147&filters[translation_id]=4251252)) so if we bring back this error message and this issue persists, we can reopen the issue at that point.
