### ISSUE TITLE
Recommended tags followed from the search bar should show up in Followed tags

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2174]
A user can type in the search bar the title of a Recommended tag to follow it. When this happens, the tag should appear in the followed tags list and disappear from the recommended tags list.

**Comment by rachelmcr** [comment]
I tested this with the following steps in beta v. 5.8.0.20151124:
1. Open the Reader and tap on Menu
2. Swipe over to Popular Tags
3. In the search bar, type in one of the tags listed below it (e.g. "Books")
4. Tap Done
Result: The tag disappeared from the popular tags list and appeared in the followed topics list.

I repeated these steps while on the Followed Topics screens with the same result. Closing this issue as resolved.
