### ISSUE TITLE
WordPress: Buttons in the Me screen are not working

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#21750]
### Expected behavior
Buttons in the Me screen should always be interactable.

### Actual behavior
Most buttons in the "Me" screen don't react to taps, after signing up on the WordPress app

### Steps to reproduce the behavior

1. Run the WordPress app
2. Create a new account
3. After landing on the simplified UI tap on the "Account & Settings" button
4. The Me screen should be displayed modally
5. Tap on "My Profile"
6. Notice that nothing happens
7. Notice that the same applies to the rest of the buttons

**Comment by twstokes** [comment]
👋 Hey @hassaanelgarem - is this the same as https://github.com/wordpress-mobile/WordPress-iOS/issues/21690? A fix was merged into `23.4` but it looks like it hasn't been reintegrated back into `trunk` from what I can tell.

**Comment by hassaanelgarem** [comment]
@twstokes Oh, it is the same yes. Thanks for pointing that out!
