### ISSUE TITLE
Compliance Popover breaks presentation of views after onboarding 

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#21758]
Compliance Popover breaks the presentation of views after onboarding. 

After tapping "Checking Stats" in onboard questions, the compliance popover either blocks the presentation of Stats or appears in a blank state.

### Expected behavior

Compliance Popover presentation should not block views appearing after onboarding and when the popover appears it shouldn't be in a blank state.

#### Atempt 1: Compliance Popover disappears after briefly showing
https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/c0a11338-f403-4330-9af6-34235aac5ac2

#### Atempt 2: Blank Compliance Popover opens up after opening Stats
https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/8abdede3-e34d-4e6e-ad47-b5201bec257d

### Steps to reproduce the behavior

1. Make sure you're in compliant country or  `shouldShowPrivacyBanner` returns `true`
2. Fresh install WordPress/Jetpack app
3. Log in
4. Click "Checking Stats" on onboarding questions
5. Notice that either Stats doesn't open up or if it opens, compliance popover appears blank

**Comment by salimbraksa** [comment]
Hey @staskus, I couldn't reproduce the bug using the latest `trunk` commit 05a954e50ad82c1e651ce0e972bcb8dadc5c7be6. Maybe the issue is fixed since the last time you reported this issue. Can you double check? 🙏
