### ISSUE TITLE
Bug: Reader detail header overlaps with the content sometimes

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#21797]
### Expected behavior
The Reader detail header section shouldn't overlap with the content.

### Actual behavior
The header section overlaps with the content. See pcdRpT-45K-p2#comment-6761.

### Steps to reproduce the behavior

- Navigate to the Notifications tab.
- Select any post-type notifications.
- Observe that the header overlaps into the content area about 10-25% of the time.

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm using `[Pri] Medium` since the issue is a visual imperfection that occurs in 10-25% of times and is not a blocker. Correct me if I'm wrong.

**Comment by dvdchr** [comment]
Reopening this issue as we are still getting reports of this occurring on `release/23.6`. See: p1699469705425659-slack-C05N140C8H5

**Comment by dvdchr** [comment]
Adding another record of occurrences, courtesy of @salimbraksa (internal ref: p1710899579663249-slack-C01CW1VMLAF):

> I’ve encountered this problem multiple times, but I can’t figure out how to consistently reproduce it. The issue occurs when I navigate to `ReaderDetailViewController` from the Notifications screen, and sometimes I see a glitch in the `ReaderDetailNewHeaderView` layout.

**Comment by dvdchr** [comment]
This issue should be fixed by #22939 (particularly https://github.com/wordpress-mobile/WordPress-iOS/pull/22939/commits/8a0c72d64eff1fad513adbf4f5f66b63c04a356a), which will be released in version 24.6. I'll close the issue now, but feel free to reopen if you still see this after 24.6! 🙂
