### ISSUE TITLE
Remove conditional logic in Stats Revamp code

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#21792]
### Expected behavior

The `statsRevampV2Enabled` app configuration should be removed since it's no longer needed. Stats was removed from the WordPress app and is only available on the Jetpack app. When Stats was available on both apps, `statsRevampV2Enabled` was used to enable it on the Jetpack app and disable it on the WordPress app.

**Comment by staskus** [comment]
Done in https://github.com/wordpress-mobile/WordPress-iOS/pull/22444
