### ISSUE TITLE
Bug: Tapping the Reader tab doesn't scroll all the way to the top sometimes

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#21800]
### Expected behavior

The Reader stream should be properly scrolled to the top after tapping the Discover tab.

### Actual behavior

The Discover tab sometimes doesn't fully scroll to the top.

![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/2e2a3a4f-bef7-4bef-bf1f-885f30cd2072)

### Steps to reproduce the behavior

- Navigate to the Reader > Discover.
- Scroll down.
- Navigate away to other tabs (Notifications or Me).
- Tap the Reader tab.
- Tap the Reader tab again to make it scroll to the top.
- Observe that it doesn't fully scroll to the top sometimes.

**Comment by twstokes** [comment]
👋 @dvdchr it seems this is more likely to happen when more posts have been appended and we're scrolled further down. At the beginning of the video I'm near a top post can't reproduce the issue.

https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/2e8d8aa7-0023-4dc9-a2da-4d63bfaea71e

**Comment by dvdchr** [comment]
Thank you for the additional info, @twstokes ! I'll do a bit more digging into this. 🙂

**Comment by dvdchr** [comment]
Closed via #21821

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm using `[Pri] Low` judging from the issue description. Correct me if I'm wrong.
