### ISSUE TITLE
Reader: Hide comments/likes if they're at zero

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#21807]
Ref: p1697461135179259-slack-C05N140C8H5

When there are either zero comments or likes, hide the label, respectively.

**Comment by dvdchr** [comment]
Closed via #21808

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm using `[Pri] Low` judging from the issue description (I would even categorize it as an Enhancement). Correct me if I'm wrong.
