### ISSUE TITLE
Reader: Update follow button label to correct size

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#21809]
Ref: p1697541472738849-slack-C05N140C8H5

- The Follow button text should use the Subheading / 15pt text style.
- The button's leading & trailing margin should be 24pt on Tag/Site header, and 16pt on spaces where it is tighter.

**Comment by dvdchr** [comment]
Closed via #21810

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm using `[Pri] Low` judging from the issue description. Correct me if I'm wrong.
