### ISSUE TITLE
Site Domains: Domains suggestion table always shows the dotcom domain as the primary domain

### ISSUE THREAD

**Issue by hassaanelgarem** [wordpress-mobile/WordPress-iOS#21826]
### Expected behavior
The message shared while adding a domain should be accurate. It should always state that new domains will redirect to the primary domain.

### Actual behavior
The message shared while adding a domain is inaccurate. It always states that new domains will redirect to the dotcom domain.

### Steps to reproduce the behavior
* Setup a site with a paid plan and a custom domain set as the primary domain
* Navigate to My Site -> More -> Domains
* Notice that the custom domain is marked correctly as the primary domain
* Tap "Add a domain"
* Notice that the header displayed reads "Domains purchased on this site redirects to {Your Dotcom Domain instead of the custom domain}"

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm using `[Pri] Medium` judging from the issue description. Please correct me if I'm wrong.
