### ISSUE TITLE
Bug: Recommended tags in Discover is listed in the wrong direction in RTL

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#21830]
### Expected behavior
When using an RTL language, the recommended tags should also be displayed from right to left. Based on the image below, the correct layout should be:

```
┌───────────────────────────────────┐
│                    You might like │
│                                   │  
│  [Travel] [Photography] [Culture] │
│                           [Music] │
└───────────────────────────────────┘
```

### Actual behavior
The recommended tags list is displayed from left-to-right when using an RTL language. See screenshot:

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/806dd89a-f9d8-40f8-9bd4-0bb1ec7a7c2e" width=375>

Note that I was using a Right-to-Left Pseudolanguage to simulate an RTL layout.

### Steps to reproduce the behavior

- Use an RTL language or a pseudolanguage to trigger an RTL layout.
- Launch the Jetpack app.
- Go to Reader > Discover tab.
- Observe that the recommended tags are laid out in the wrong direction.

**Comment by wargcm** [comment]
Closing with https://github.com/wordpress-mobile/WordPress-iOS/pull/21831.

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm using `[Pri] Medium` judging from the issue description. Please correct me if I'm wrong.
