### ISSUE TITLE
Site to follow: The site address is partly hidden with large text/display configuration

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#21836]
### Expected behavior
With large text/display configuration the site address is visible in the sites to follow card

### Actual behavior
With large text/display configuration the site address is partly hidden in the sites to follow card

### Steps to reproduce the behavior
1. Set a large font size or the large text display zoom
2. Browse to the discover tab
3. Scroll to the sites to follow card
4. Notice that the address is cut and not fully visible

![IMG_0215](https://github.com/wordpress-mobile/WordPress-iOS/assets/304044/66eb7e28-1389-44b7-8282-62e75e0c3049)

**Comment by wargcm** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/21885.
