### ISSUE TITLE
Reader: Avatar spacing with title when there's only an author

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#21857]
Ref p5T066-47C-p2#comment-14971

### Expected behavior

When there is only an author avatar: there should be spacing between the avatar image and the title

### Actual behavior

The elements have no spacing between each other.

### Steps to reproduce the behavior

1. Follow a P2 which has the site image disabled
2. Navigate to the Automattic filter in the Reader
3. Filter for that specific P2
4. Observe the avatar image and title spacing

**Comment by wargcm** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/21858.

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm using `[Pri] Low` judging from the issue description. Please correct me if I'm wrong.
