### ISSUE TITLE
Bug: Reader site stream header misaligned on iPad

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#21851]
Refs p5T066-47C-p2#comment-14972

### Expected behavior
The Site stream header should follow the readable content guide to align with the rest of the content.

### Actual behavior
The Site stream header aligns itself to the edges of the screen. 

### Steps to reproduce the behavior

- Launch Jetpack on iPad.
- Navigate to Reader > Discover.
- Tap the site to go to the site's stream.
- Observe that the Site stream header is misaligned.

##### Tested on iPad, any supported iOS version, Jetpack iOS 23.5.0.2

**Comment by wargcm** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/21882.

**Comment by pachlava** [comment]
Adding a priority label to better align with the rules for MTTR metric.
See pdcxQM-2Su-p2

I'm using `[Pri] Medium` judging from the issue description. Please correct me if I'm wrong.
