### ISSUE TITLE
Stats: Year/Month/Week Stats are empty after navigating

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#21862]
### Steps to reproduce the behavior

1. Go to stats -> years
2. Tap the < icon to go back a year
3. Tap the Years “header”
4. Tap > to go forward a year

Now the current year shows all 0s.

More context: p58i-fHk-p2#comment-59841

##### Tested on iPhone 14 pro, iOS [version], Jetpack iOS / WordPress iOS 23.5

**Comment by rohitsar123** [comment]
Hi @staskus I would like to take a look at this issue. Can you assign this to me? Thanks

**Comment by ghost** [comment]
Hi @staskus, I would like to take a look into this bug. Can I be assigned to this bug? Thanks

**Comment by staskus** [comment]
@rohitsar123, we appreciate you contributing to the project! I was away for a bit so I couldn't get back to you. I see that you also made a pull request addressing the issue (https://github.com/wordpress-mobile/WordPress-iOS/pull/21970). We will review the solution.
