### ISSUE TITLE
Bug: Reader recommended tags' bottom border is clipped

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#21867]
### Expected behavior

The recommended tags list should be displayed correctly.

### Actual behavior

The tags' bottom border is clipped. See screenshot below:

![img_0116](https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/faa3f319-e350-4cfc-88a5-93484910321c)

### Steps to reproduce the behavior

- Launch the Jetpack app.
- Navigate to Reader > Discover tab.
- Observe that the recommended tags' bottom border is clipped.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Adding "High" priority because it's directly in the feed that everyone sees.
