### ISSUE TITLE
Login: Two 2FA controllers are opened when logging in

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#21864]
### Expected behavior

One 2FA controller should be opened

### Steps to reproduce the behavior

1. Login with a WP.com account that has 2FA enabled
2. Observe 2FA controllers being opened one after another

https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/382bf061-6424-4262-82a5-a21d77c79fad

It does not prevent successful login

### Technical details:

I inspected the code and both `needsMultifactorCode` methods get triggered one after another, in line 107 and line 111. They were introduced in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/788

We need to understand the reasoning between 2 of them existing. Maybe it's enough to add `nonceInfo != nil` for the second `if` to prevent both of them being called.

<img width="918" alt="both get triggered" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/c1a57f86-d889-4f73-8334-96df7d72be43">

**Comment by staskus** [comment]
@tiagomar noticed this issue when fixing other login issues. Tagging in case you would want to group them together. Do you think we should try to get this fixed together with other grouped Login issues now? Thanks!

**Comment by staskus** [comment]
Same issue with WooCommerce-iOS 15.9. I'll provide a fix.

**Comment by guarani** [comment]
👋 I noticed this can only be reproduced with WP.com accounts that do not have passkey enabled.

**Comment by staskus** [comment]
> 👋 I noticed this can only be reproduced with WP.com accounts that do not have passkey enabled.

@guarani you're correct, good observation!

**Comment by tiagomar** [comment]
Hey @staskus!

> @tiagomar noticed this issue when fixing other login issues. Tagging in case you would want to group them together. Do you think we should try to get this fixed together with other grouped Login issues now? Thanks!

Yeah, it makes sense to group them together. While apparently not blocking, this is one of those issues that contributes to the 'buggy app' feeling, so it's good to know that you're working on a fix. 🙇
