### ISSUE TITLE
Stats: Related cards show mismatching numbers

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#21876]
Two numbers for the same stat, on the same or similar screens sometimes don’t match.

### Total Comments page

The numbers of Total Comments, Top Commenters, and Comments on Posts can be all different.

### Insights

Total Likes card number and the description can show mismatching numbers

### Total Followers numbers

Followers on the diagram and followers on the table can be shown different numbers. Also the insights are only for WordPress.com subscribers and not total subscribers which should be clarified.

There's likely to be more places such as this, it's important to understand the root cause. 

![Image](https://user-images.githubusercontent.com/4062343/277854020-2d233c00-6c28-4add-b4df-03ecd04a23ef.png)

**Comment by staskus** [comment]
I investigated all the issues described here. Some are already fixed, some are UX issues, and some are API issues:

### Total Comments displays a different number

<img width="253" alt="image" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/caa582d5-3053-48f9-847f-4bc1c9c3cd1f">

✅  This issue was recently fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/22914 and now all the comment numbers should match.

### Total Likes card number and the description can show mismatching numbers

<img width="244" alt="image" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/89ecbc17-da3e-41dd-93c3-914838f5377d">

This is easily reproducible and happens because "Total Likes" card doesn't display a number of total likes, and only displays the number of total likes within the last 7 days. However, the description at the bottom of "Your latest post has received 2 likes" shows the total number of likes. The same issue applies to "Total Comments" card.

❔  Therefore, it's not a bug but rather an ambiguous user experience that we need to clarify. We could rename "Total Likes" card and indicate that the totals are only for the last 7 days or indeed show an all-time number of likes. I will register it as a task. 

### Total Followers show more followers in the table than the total count

<img width="238" alt="image" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/9a240603-0749-4c3c-a821-a3c78c6b6b4c">

I inspected the app's code and concluded that this is not a bug on the app since we display the numbers from `/followers` endpoint without making any manipulations.

However, I can confirm that `/followers`endpoint on a given blog returns less `total_wpcom` and `total` counts than `subscribers` in the list. I reported the bug on the Jetpack side:

- https://github.com/Automattic/jetpack/issues/36696

**Comment by guarani** [comment]
> Therefore, it's not a bug but rather an ambiguous user experience that we need to clarify. We could rename "Total Likes" card and indicate that the totals are only for the last 7 days or indeed show an all-time number of likes. I will register it as a task.

I just saw your comment here after creating https://github.com/wordpress-mobile/WordPress-iOS/issues/23015, which I think should address the issue in the way you describe.
