### ISSUE TITLE
Stats: Data is shown for the Month before the site was created

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#21877]
Context: p58i-fHk-p2

For the site created in October, there're stats shown from July. 

![Image](https://user-images.githubusercontent.com/4062343/277855038-5538631e-b683-482c-b446-987fbc0084fc.png)

**Comment by masterspin** [comment]
Hi @staskus , is there any information on how to recreate this bug? Thanks!

**Comment by guarani** [comment]
There's a way to limit to the site creation date, see: https://github.com/wordpress-mobile/WordPress-Android/issues/20396#issuecomment-1983594164

**Comment by staskus** [comment]
> For the site created in October, there're stats shown from July

The original issue was reported in p58i-fHk-p2 and the concern was that Stats showed data from before the site existed, However, I checked the site and in fact, it was created in July. Therefore, this particular bug report is invalid. I'm closing this issue.

> There's a way to limit the site creation date, see: https://github.com/wordpress-mobile/WordPress-Android/issues/20396#issuecomment-1983594164

This is unrelated to this bug report. We could limit scrolling and navigating in Stats based on `Site Creation` but I would argue this is not a critical task. If we find it necessary, we could incorporate it as a requirement for any Date Picker improvements we do, and not allow to select a date beyond a site creation. I think it's unwise making these changes in the scope of current Days/Weeks/Months/Years tabs or in a new Traffic tab. @guarani

**Comment by guarani** [comment]
> This is unrelated to this bug report.

It makes sense; I misunderstood the issue as "the date picker lets you navigate to (empty) months before the site was created," but now I see it was about views and visitors being shown in months before site creation. I'm glad to see that it was not a bug after all and the views and visitors were valid 👍
