### ISSUE TITLE
Stats: Subscriber growth graph

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#21880]
Context: pcdRpT-4iq-p2

Growth graph would be pretty great to have in mobile apps, as stats are something folks actively follow and subscriber stats are some of the most important stats for bloggers. Apps show only the static number.

![Image](https://user-images.githubusercontent.com/4062343/277856145-d3a4f4bb-db51-480a-ae8b-ca089270de31.png)

**Comment by masterspin** [comment]
@staskus I would like to look into adding this feature. Can you assign this task to me? Thanks

**Comment by masterspin** [comment]
Hi, @staskus. I would like to take a look into adding this feature. Could you assign this task to me? Thanks

**Comment by staskus** [comment]
Hi, @masterspin, we appreciate your intention to contribute to the project! 🙇 I was away for a while so I couldn't get back to you.

This task is not yet ready for development and requires some more alignment from our side. It wasn't labeled properly. Until then, it could be more convenient [to contribute to other Stats issues labeled as bugs](https://github.com/wordpress-mobile/WordPress-iOS/labels/Stats).

Some examples of issues that could be picked up more easily to get familiar with Stats:
- https://github.com/wordpress-mobile/WordPress-iOS/issues/20001
- https://github.com/wordpress-mobile/WordPress-iOS/issues/20004
- https://github.com/wordpress-mobile/WordPress-iOS/issues/21245
- https://github.com/wordpress-mobile/WordPress-iOS/issues/21877
- https://github.com/wordpress-mobile/WordPress-iOS/issues/21121
- https://github.com/wordpress-mobile/WordPress-iOS/issues/21992

Thanks again! Let me know if you have any questions!
