### ISSUE TITLE
Posts do not appear in the correct status tab when they have local changes

### ISSUE THREAD

**Issue by crazytonyli** [wordpress-mobile/WordPress-iOS#21895]
### Steps to reproduce the behavior
1. Go to Posts List -> Published, open a published post in post editor.
2. In the post editor, make a change without tapping the "Update" button.
3. Send the app to the background.
4. On your computer's browser, go to WP.com and move the same published post to trash.
5. Go back to the app -> Posts List, check out which status tab the edited post is in.

### Expected behavior
The post is in the Trashed tab.

### Actual behavior
The post is in the Published tab.

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
v23.4

**Comment by crazytonyli** [comment]
Potentially relate to https://github.com/wordpress-mobile/WordPress-iOS/issues/8111. Because this issue here might make it seem like the post isn't synced—it's still in its old status.

**Comment by kean** [comment]
This has been fixed in the scope of the "Offline Mode (Sync Issues)" project (pilot in 24.8; release in 24.9).
