### ISSUE TITLE
NSInternalInconsistencyException: Invalid update: invalid number of rows in section

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#21920]
**Sentry Url**: https://sentry.io/share/issue/e4e1efc57cd649f7962919f5ca66e2fe/
**User Count**: 761
**Count**: 14669
**First Release**: org.wordpress-12.4.1
**First Seen**: 2020-09-02T03:16:25.756595Z
**Last Seen**: 2023-10-30T23:05:02Z
**24 Hours**: 8
**30 Days**: 213
**LogID:** B45094BF-5A53-484C-9A68-AABD53FBC0AB

```
NSInternalInconsistencyException: Invalid update: invalid number of rows in section 0. The number of rows contained in an existing ...
  File "AbstractPostListViewController.swift", line 963, in AbstractPostListViewController.deletePost
  File "PostListViewController.swift", line 711, in PostListViewController.trash
  File "<compiler-generated>", line null, in thunk for closure
  File "<compiler-generated>", line null, in thunk for closure
  File "<compiler-generated>", line null, in thunk for closure
  File "main.swift", line 7, in main
...
(28 additional frame(s) were not displayed)
```

**Comment by guarani** [comment]
This issue had 56 events in 23.4 and has one event so far in the 23.5 beta. 

Based on the stack trace which mentions deleting a post and going through the confirmation dialog/alert, I tried to reproduce by deleting a bunch of posts (published & drafts) but didn't run into this crash.

**Comment by guarani** [comment]
👋 @kean, with your recent work on Posts search and [this thread about post deletion UI](p1698359488119619-slack-C04SFL0RP51), do you have any insight into this issue?

I'm curious if any new work will render this bug obsolete (e.g. if old code post deletion code is being removed and replaced with something new) or if this issue still stands and should be looked into independently of the recent Posts screen changes.

**Comment by kean** [comment]
It will be fixed in the scope of https://github.com/wordpress-mobile/WordPress-iOS/issues/21819.

**Comment by guarani** [comment]
Thanks! I missed the other issue. Closing
