### ISSUE TITLE
Partner themes should not be listed on mobile

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#21932]
### Expected behavior
Partners themes should not be listed on mobile because they need to be subscribed to before activating them, and we currently do not support subscribing to them. 
The same issue was addressed on Android by using `theme_type` field from the themes endpoint response: https://github.com/wordpress-mobile/WordPress-Android/pull/19497

### Actual behavior
Partner themes are displayed on the themes screen, and attempting to activate them results in an error message.

https://github.com/wordpress-mobile/WordPress-iOS/assets/2471769/0922e687-1b4d-466d-ba33-97edf54bd50c

### Steps to reproduce the behavior
1. Launch the JP app.
2. Login with a site that you own and have a business plan.
3. From the My Site tab, tap the "More" button on the shortcut list.
4. Tap Themes.
5. Search for partner themes, such as "Scentina" or "Kereta".
6. Observe that the partner theme is included in the list.

##### Tested on iPhone 15 Pro Simulator, iOS 17.0, Jetpack iOS 23.6

**Comment by irfano** [comment]
@tiagomar, this is the same bug as https://github.com/wordpress-mobile/WordPress-Android/issues/18308 on iOS, which is on the Maintenance Week Android board. Can we move this issue to the Maintenance Week iOS board?

**Comment by tiagomar** [comment]
Thanks for the ping, @irfano! Just added to the board. 🙇
