### ISSUE TITLE
Posts & Pages: Incorrect search bar placement on iPad

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#21936]
<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/8ee5a737-0e7c-433f-b750-ab661eb440a3" width=400>

### Expected behavior
Search bar should be below the nav title

### Actual behavior
Search bar is next to nav title

### Steps to reproduce the behavior
On iPad, go to the posts list screen

**Comment by kean** [comment]
It was a super small change. I fixed directly in the branch https://github.com/wordpress-mobile/WordPress-iOS/pull/21744/commits/e4aac98666b57db7703e88dce9e7c073ad0b46be.
