### ISSUE TITLE
Local post changes are saved automatically

### ISSUE THREAD

**Issue by crazytonyli** [wordpress-mobile/WordPress-iOS#21941]
### Expected behavior

The changes should only be saved when tapping the "Published" button.

This expected behaviour is my interpretation of the app's offline editing support. The editor should behave like a text editor: it writes to the opened file only when user taps "Save" button.

### Actual behavior

Changes are saved automatically after sending the app to background.

### Steps to reproduce the behavior

1. Go to Posts list -> Draft.
2. Create a post and tap the "Publish" button.
3. Go back to the Posts list. You should see a draft post here.
4. Tap the draft post and make some changes to it.
5. Go to the device's home screen, wait for a couple of seconds, and kill the app.
6. Re-open the app and go to Posts list -> Draft.
7. Checkout the post content.

Here is a video recording:

https://github.com/wordpress-mobile/WordPress-iOS/assets/1101828/5cba3f2d-ee34-4871-9515-7d164285a14d

**Comment by crazytonyli** [comment]
I did a little big digging and found a same issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/10248. I guess the issue was fixed at one point (5 years ago).

**Comment by kean** [comment]
Btw, if you remove "and make some changes to it" from step 4, it will still save the revision and display "local change" (incorrectly).

> The editor should behave like a text editor: 

That's an interesting thought. If you also compare it to Notes, the Notes app syncs files seamlessly/automatically and merges changes in the case of a conflict automatically. 

But Notes are private. I think there can be more potential negative implications of unintentionally posting content to a user's public website. I'd rather be on the side of caution and only upload when the user publishes/saved explicitly, as you suggested. It should never auto-retry, especially not after closing the app.

**Comment by kean** [comment]
Btw, the label "local changes" also seems too technically. Maybe we could say "Unpublished changes" or something like that? I'm sure there is a better way to communicate this.

**Comment by kean** [comment]
This has been fixed in the scope of the "Offline Mode (Sync Issues)" project (pilot in 24.8; release in 24.9).
