### ISSUE TITLE
Error Domain=PostEditor.OverwritePost Code=1 "(null)"

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#21945]
**Sentry Url**: https://sentry.io/share/issue/ed32ec984bf54403ac67be4cf5141249/
**User Count**: 1
**Count**: 1
**First Release**: 23.6.0.0
**First Seen**: 2023-11-01T02:38:59.976577Z
**Last Seen**: 2023-11-01T02:38:59Z
**24 Hours**: 1
**30 Days**: 1

```
Error Domain=PostEditor.OverwritePost Code=1 "(null)"

```

**Comment by guarani** [comment]
This is a new error in the 23.6 beta, so I've added the `[Pri] Blocking` label as per instructions for new crashes in beta (internal ref PCYsg-TWi-p2).

**Comment by guarani** [comment]
Changed to Priority Low after @crazytonyli pointed out it's not a crash (it's non-fatal) in p1698887237808899/1698886720.242009-slack-C012H19SZQ8.

**Comment by kean** [comment]
The severity is high. This error tracks the scenario where the app overwrites the changes made outside of the app without asking the user.

**Comment by guarani** [comment]
> The severity is high. This error tracks the scenario where the app overwrites the changes made outside of the app without asking the user.

I agree the severity of what's happening is high. I interpret this log as saying that in the 23.6 beta, one user had their post overwritten (e.g. the app is about to overwrite a post revision created on another device), which is bad. Using the priority matrix, pbArwn-1gZ-p2, it's Severity Critical (due to data loss) + Impact Low (due to one report in the beta) = High Priority. 

I put a high priority on https://github.com/wordpress-mobile/WordPress-iOS/issues/8111 (the original issue), closed this issue since it's not a separate issue, and linked the above Sentry issue to the original GitHub issue. 

Thanks for flagging the priority concern, @kean and let me know if you have any questions 👍

**Comment by kean** [comment]
Step to repro (and there are other ways to):

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/cbd92130-7506-4f8e-91ef-e0ce2d1d99f1
