### ISSUE TITLE
Crashes in various view controllers: NSInternalInconsistencyException and others

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#21943]
Sentry groups a number of distinct crashes in [WORDPRESS-IOS-38W2](https://a8c.sentry.io/issues/1871799689/):

| Error Log                                                                                               | Sentry Event Link                                     | GitHub Issue |
|---------------------------------------------------------------------------------------------------------|------------------------------------------------------|--------------|
| `AbstractPostListViewController.deletePost (AbstractPostListViewController.swift:963)`                   | [View Event](https://a8c.sentry.io/issues/1871799689/events/a928adb34f6d4df7b5c7f3b7778726f5/?project=1438083) | https://github.com/wordpress-mobile/WordPress-iOS/issues/21920 |
| `PrivacySettingsViewController.init (PrivacySettingsViewController.swift:21)`                            | [View Event](https://a8c.sentry.io/issues/1871799689/events/6588f06dba4b441f8a8231fff1439f9d/?project=1438083) | https://github.com/wordpress-mobile/WordPress-iOS/issues/21944 |
| `NSInternalInconsistencyException: Requested the number of rows for section (0) which is out of bounds.` | [View Event](https://a8c.sentry.io/issues/1871799689/events/e9985e76dd914c2ebd77e410cbd2a0d2/?project=1438083) |              |
| `NSInternalInconsistencyException: Invalid parameter not satisfying: pos`                                | [View Event](https://a8c.sentry.io/issues/1871799689/events/c62b2eb752214c7db66bc0d5424cd3c1/?project=1438083) | https://github.com/wordpress-mobile/WordPress-iOS/issues/21086 |
| `SignupUsernameTableViewController.reloadSections (SignupUsernameTableViewController.swift:65)`          | [View Event](https://a8c.sentry.io/issues/1871799689/events/fcb18599f72f423b829d91c053765efd/?project=1438083) |              |
| `NSInternalInconsistencyException: attempt to delete section 0, but there are only 0 sections before the update` | [View Event](https://a8c.sentry.io/issues/1871799689/events/b78f5ad9f3e6412087bd9b0f3fb0f265/?project=1438083) |              |
| `PageListTableViewHandler.refreshTableView (PageListTableViewHandler.swift:78)`                          | [View Event](https://a8c.sentry.io/issues/1871799689/events/d06105c7feee486d932449b4e46af50e/?project=1438083) |              |
| `SupportTableViewController.init (SupportTableViewController.swift:46)`                                  | [View Event](https://a8c.sentry.io/issues/1871799689/events/f87325080ac942b0b8f54b2ff6e80385/?project=1438083) | seems similar to https://github.com/wordpress-mobile/WordPress-iOS/issues/21944 |

This is a parent GitHub issue to reference on the Sentry issue since Sentry doesn't support unmerging these events nor linking to multiple GitHub issues.

**Comment by kean** [comment]
I've checked all of the listed crashes and the all – unless I missed something – have been fixed. The last time they were seen were in 16 in release [22.8.0.3](https://a8c.sentry.io/releases/22.8.0.3/?project=1438083).

**Comment by staskus** [comment]
Note: This Sentry report started trending again for 24.4 with a new issue (https://github.com/wordpress-mobile/WordPress-iOS/issues/22936). However, it looks like a new Aztec update for 24.6 should resolve these crashes.

**Comment by staskus** [comment]
A new issue started trending grouped with this report https://github.com/wordpress-mobile/WordPress-iOS/issues/23271

Update: fixed for 25.0
