### ISSUE TITLE
Discarding changes to a local post deletes the post

### ISSUE THREAD

**Issue by crazytonyli** [wordpress-mobile/WordPress-iOS#21940]
### Expected behavior

Discarding new changes to a local post should only discard the new changes, not the whole post.

### Actual behavior

In Gutenberg editor, when discard new changes to a local post, the local post is deleted.

### Steps to reproduce the behavior

1. Go to Posts list -> Draft.
2. Turn off the iOS device's WiFi.
3. Create a new post and tap Publish.
4. Go back to the draft post list. You'll see a draft post that has not been uploaded to the site yet.
5. Tap the draft post and make some changes.
6. Tap the back button in the post editor and tap discard.
7. Go back to the draft post list. The draft post is gone.

Here is a video recording:

https://github.com/wordpress-mobile/WordPress-iOS/assets/1101828/13dc6d78-544b-48c5-ac00-0c0e6937f06c

**Comment by kean** [comment]
There were two fixes to this issue made in the scope o the "Offline Mode (Sync Issues)" project (pilot in 24.8; release in 24.9):

- The app now stores intermediate local revisions, so "Discard" only deletes the latest changes
- The app no longer has the "Discard Changes" dialog for draft and pending posts (this change came later)
