### ISSUE TITLE
Bug: Not logged in after downloading the Jetpack App via the WP app. 

### ISSUE THREAD

**Issue by enejb** [wordpress-mobile/WordPress-iOS#21959]
### Expected behavior
When I don't have the Jetpack app installed and am asked by the WordPress app to create a new site in the Jetpack app. 
After I install the app I would expect us to be logged in to the Jetpack App. 

### Actual behavior
When I don't have the Jetpack app installed and am asked by the WordPress app to create a new site in the Jetpack app. 
After I install the app I need to go though the login process in to the Jetpack App. To complete the site creation process. 

### Steps to reproduce the behavior
Download the WP App. 
Create a new user account. 
Try to Create a new Site. 
Download the Jetpack app. 
Launch the Jetpack App. 
Notice that you are not logged in. 

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
Latest.

**Comment by twstokes** [comment]
Good thought @enejb!

[Here's where we're determining the user's migration eligibility](https://github.com/wordpress-mobile/WordPress-iOS/blob/dd774d2549b388d4a55303fa70c93db9ab1ff733/WordPress/Classes/Utility/Migration/ContentMigrationCoordinator.swift#L190) based on the number of blogs they have (which would be zero in this case, making them ineligible).

**Comment by enejb** [comment]
I don't think we would have to "migrate them" if the don't have any blogs/sites since the email might be a bit confusing. 
but just having them logged in would be 🥳

**Comment by twstokes** [comment]
I've created a draft PR to demonstrate the quickest fix and its potential drawbacks: https://github.com/wordpress-mobile/WordPress-iOS/pull/21968
