### ISSUE TITLE
Pages screen isn't updated after publishing a new page

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#21993]
### Expected behavior
The page screen is updated after publishing a new page

### Actual behavior
Pages screen is updated after publishing a new page. It is also not updated after removing a page.

https://github.com/wordpress-mobile/WordPress-iOS/assets/2471769/42dc8b73-0ac0-443b-a220-93a04eb94291

**Comment by kean** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/21946; will ship in 23.7.
