### ISSUE TITLE
Change reblogged posts to match how they are displayed on the desktop reader

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2199]
title has it.

**Comment by kurzee** [comment]
Probably a good one for detail view refresh.

**Comment by yaelirub** [comment]
Seems like this has been handled already as reblogging from the app and web have similar layouts:

Web|App
-|-
![Screen Shot 2020-06-09 at 2 56 56 PM](https://user-images.githubusercontent.com/1335657/84205357-cb71bd80-aa61-11ea-8f44-93c6b83bfd90.png)|![IMG_E651744171C7-1](https://user-images.githubusercontent.com/1335657/84205370-d3316200-aa61-11ea-8e16-b49947fa28d4.jpeg)

**Comment by yaelirub** [comment]
I believe this can be solved as part of Reader post rendering project.
@leandroalonso , lets make sure that reblogged posts look good with the transition to webviews.
