### ISSUE TITLE
Opening the Stats screen from the Quick Start menu issue on iPads

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#21992]
### Expected behavior
After opening the stats screen from the quick starts menu, the "Stats" should be selected in the left menu.

### Actual behavior
After opening the stats screen from the quick starts menu, the Home page remains selected in the left menu, and tapping on the Homepage does not have any effect.

https://github.com/wordpress-mobile/WordPress-iOS/assets/2471769/e8ff8cb7-fd08-4976-a709-204a3d9c4d2b

### Steps to reproduce the behavior
1. Launch the JP app on an iPad.
2. Log in and create a new site.
3. Choose to be guided by Quick Start and go through each step
4. After tapping the Stats item in the quick start steps, notice that Stats is still selected in the left menu, as shown in the video.

**Comment by tiagomar** [comment]
It also happens for other Quick Start items, like `Review site pages`. Also, the blue, pulsating dots are missing for these tasks.

**Comment by kean** [comment]
Quick Start is removed in 25.3 – closing.
