### ISSUE TITLE
Uploaded video doesn't play for private sites

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#22003]
### Expected behavior
When a video is uploaded to a post in the editor for private sites, it should be playable.

### Actual behavior
When a video is uploaded to a post in the editor for private sites, it doesn't play.

https://github.com/wordpress-mobile/WordPress-iOS/assets/2471769/ccdf83af-51b5-44f8-8393-940d40fe7f05

### Steps to reproduce the behavior
1. Launch the JP app.
2. Log in and select a private site.
3. Tap "+" button on the My Site tab.
4. Select Blog post.
5. Add a video block to the post and record a video.
6. Wait for the upload to be completed.
7. Tap the uploaded video.
8. Notice that it's not playing.

**Comment by twstokes** [comment]
👋 Hey @fluiddot, do you happen to have any added context from our VideoPress work? Thanks!

**Comment by fluiddot** [comment]
> 👋 Hey @fluiddot, do you happen to have any added context from our VideoPress work? Thanks!

Yep, I shared some info internally (pcdRpT-4n3-p2#comment-7243). Regarding the VideoPress work, private videos work as expected in the VideoPress block but the core Video block (the one referenced in this issue) wasn't updated as part of that project. Updating the core block and converting it to a VideoPress block was part of phase 2. In fact, this was one of the proposed improvements after finishing the MVP version of the block:

> **Proposed Improvements:**
> **Resolving private video playback issues:** Integrating the VideoPress web player’s capabilities can ensure that users have a seamless experience regardless of their video’s privacy settings.
(p9ugOq-3SJ-p2)

**Comment by irfano** [comment]
Duplicate of https://github.com/wordpress-mobile/gutenberg-mobile/issues/5497
