### ISSUE TITLE
If a post was deleted on a remote and modified locally, it can't be deleted

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#22037]
### Expected behavior

The app notifies you that the post was deleted and suggest saving the changes as a new draft

### Actual behavior

- There is no way to save the post
- There is no way to delete the post
- Every time you open the app, it shows an "upload failed" popup

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/34d565cc-7a8d-4a8a-b247-5e18cfbe3f70

### Steps to reproduce the behavior

- Create a post in the app
- Close the Posts page
- Open wp.com and permanently delete the created post 
- Return the to the app
- Open the Posts page and quickly open the deleted post before the refresh finishes
- Modify and save the post
- Try to delete the post

**Comment by crazytonyli** [comment]
The trash post HTTP API probably returns an error that indicates the post has been deleted. The app should handle the error better, and potentially show another alert with options like "Save as draft", "Discard the post".

**Comment by kean** [comment]
This has been fixed in the scope of the "Offline Mode (Sync Issues)" project (pilot in 24.8; release in 24.9).
