### ISSUE TITLE
Icons on Posts/Pages menu items are suppressed for larger fonts

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#22093]
### Expected behavior
Icons are always displayed for any font sizes.

### Actual behavior
Icons on Posts/Pages menu items are suppressed for larger fonts

<img width="273" alt="image" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/42008628/59968a9d-2182-4036-8776-c845068faf9f">

### Steps to reproduce the behavior
1. Settings > Display & Brightness > Text Size
2. Select larger font sizes
3. Open the app
4. Navigate to Posts/Pages
5. On the Posts/Pages list, tap the menu for one of the entries
6. Notice that the icons are not displayed

**Comment by kean** [comment]
This menu is managed entirely by the system, so we have no control over it. The native apps exhibit the same behavior. I'm going to close the issue unless you think differently.

<img width="453" alt="Screenshot 2023-12-22 at 5 37 28 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/1ab16f7c-99c9-46d8-9b41-4806e2091ff6">
