### ISSUE TITLE
The Site More menu becomes unresponsive

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#22102]
### Actual behavior

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/e03495e1-6334-4825-a742-ce76d7c62474

### Steps to reproduce the behavior

- Unknown

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

Unknown

**Comment by tiagomar** [comment]
Setting priority to Medium for now as we learn about the reproducibility.

> I managed to get into this state a couple times where the deeper menu page links don’t bring me anywhere. I was customizing themes and previewing my site so it may be related to opening web views and then coming back to the app.

I haven't been able to reproduce it based on this comment so far.

**Comment by kean** [comment]
I was never able to reproduce it in any of the recent releases, so I'm going to close it.
