### ISSUE TITLE
Publishing from toaster notification doesn't remove post from Drafts

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#22107]
### Expected behavior
Post to appear in the list of published posts.

### Actual behavior
Post continues to appear in the list of draft posts.

https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/90248cff-e720-4d2a-a39c-6db34e5da1d5

### Steps to reproduce the behavior
_Used a Jetpack-connected self-hosted site._

1. Start a new post and save as a draft. Exit the editor.
2. Open the post under "Drafts" and add content to it. Save it.
3. Expect a toaster notification to appear at the bottom: "Post draft uploaded" with a button to "Publish"
4. Tap "Publish"
5. Observe that the post is published on the website

**Comment by kean** [comment]
This is no longer applicable. Starting with 24.8/24.9 this snackbar has no "Publish" button.
