### ISSUE TITLE
Reblogging a post with a gallery causes undesired post 

### ISSUE THREAD

**Issue by irbrad** [wordpress-mobile/WordPress-iOS#2215]
The gallery shortcode shows in the reader on mobile upon a reblog from mobile.  The desktop reader does not do this. 

Tapping through to the post causes the re-blogger's Gravatar image to be extremely large and pixellated above the gallery.

![2014-08-06-08-26-45](https://cloud.githubusercontent.com/assets/1220715/3860827/28158bfa-1f28-11e4-8c10-5dfa659da76b.png)
![2014-08-06-08-45-21](https://cloud.githubusercontent.com/assets/1220715/3860830/2ab1db66-1f28-11e4-87fe-5585148e4e25.png)

**Comment by rachelmcr** [comment]
I tested in beta v. 5.8.0.20151124, and reblogged galleries don't show the gallery shortcode or a scaled up Grav anymore. They aren't exactly beautiful, but I'll close this in favor of putting more attention on higher priority issues (e.g. galleries in the Reader in general).
