### ISSUE TITLE
Helpshift: isWPCom incorrectly being set to true for self-hosted user

### ISSUE THREAD

**Issue by irbrad** [wordpress-mobile/WordPress-iOS#2218]
![helpshift custom data tweak mobile requests](https://cloud.githubusercontent.com/assets/1220715/3861178/f78e9b3a-1f2b-11e4-8b6b-5a7bc6d3d19b.jpg)

**Comment by SergioEstevao** [comment]
@sendhil do you know if this is solved?

**Comment by kurzee** [comment]
This looks to be resolved.
