### ISSUE TITLE
[iOS] Display a card on Site domain

### ISSUE THREAD

**Issue by ravishanker** [wordpress-mobile/WordPress-iOS#22243]
Apply same conditions for displaying plans card on My site dashboard

![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/990349/b9a96c4f-6c02-4fc1-b388-3999db347ade)

**Comment by staskus** [comment]
Updated UI:

<img width="832" alt="image" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/870071db-4be6-47c9-80d1-cb53201fa60d">

**Comment by staskus** [comment]
Updated UI:

![image](https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/618fdfc8-2e0f-46be-a336-17fa21b837a3)

**Comment by staskus** [comment]
Updated UI:

![image](https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/618fdfc8-2e0f-46be-a336-17fa21b837a3)
