### ISSUE TITLE
Update apple-app-site-association to support Universal Link for /domains/manage path

### ISSUE THREAD

**Issue by salimbraksa** [wordpress-mobile/WordPress-iOS#22256]
Users should be redirected to the Jetpack app when they visit "https://wordpress.com/domains/manage" link. To support that, we should add the path "/domains/manage" in [apple-app-site-association](https://wordpress.com/.well-known/apple-app-site-association)

**Comment by hassaanelgarem** [comment]
With D132479-code deployed, this is now done.
cc @alpavanoglu
