### ISSUE TITLE
Site Domains: Modernize UI

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#22262]
Modernize Site Domains UI to use the same guidelines and elements as All Domains

Context: p1702983267774689-slack-C06AMD6LSPN

![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/fb3afd89-99fe-4e51-8329-752ea9062f70)

**Comment by irfano** [comment]
We also updated the color of "Add a domain" button to black on https://github.com/wordpress-mobile/WordPress-Android/pull/19831.

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2471769/60c2002d-a138-4de9-ab78-84e6bba7e27c" width=300>
