### ISSUE TITLE
Pages are not displayed in a hierarchy

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#22283]
Reported by user [here](https://a8c.slack.com/archives/C04HB8JU78A/p1703315190170519), and I confirmed it on my site that I used for testing pages hierarchy.

<img width="320" alt="Screenshot 2023-12-23 at 9 35 14 AM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/9283591d-e074-4ff1-9f34-a050e30f81f7"> 

<img width="800" alt="Screenshot 2023-12-23 at 9 35 27 AM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/470edb68-8c9c-4ea7-bb0a-62a4e625dbf4">

**Comment by kean** [comment]
It appears to be a regression introduced in 23.8.1.

**Comment by crazytonyli** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/22345, which will be shipped in 24.0.
