### ISSUE TITLE
Change nav bar / tab bar appearance 

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#22334]
## Background
Currently the nav bars and tab bars have an opaque background. Updating the appearance to transparent/translucent breaks native screens

**Comment by kean** [comment]
Related defect https://github.com/wordpress-mobile/WordPress-iOS/issues/22333

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/23443
