### ISSUE TITLE
Reader: Extra vertical spacing above some post titles

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#22350]
### Expected behavior
No extra vertical spacing.

### Actual behavior
Extra vertical spacing shows above some titles.

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/ef881e24-e05d-4f6d-99bf-2d4431c695df" width="300" />

### Steps to reproduce the behavior
This may occur with post titles that wrap. See red line in screenshot.

**Comment by twstokes** [comment]
This first appeared in 23.5.

**Comment by dvdchr** [comment]
Should be fixed via #22517. Feel free to reopen if this still occurs!
