### ISSUE TITLE
Initiating split view when in post/page editor leads to crash

### ISSUE THREAD

**Issue by lmischner** [wordpress-mobile/WordPress-iOS#22373]
### Expected behavior
User should be able to use split view / slide over with the editor open in Jetpack.

### Actual behavior
When the editor is open, the Jetpack app crashes.

### Steps to reproduce the behavior
1. On an iPad, open draft post or page
2. Use 3 dot menu at top of screen to open Full Screen / Split View / Slide Over options
3. Choose Split View or Slide Over
4. Note crash

##### Tested on iPad Air, iPadOS 17.1, Jetpack iOS 24.0.0.0
I could neither reproduce this on Jetpack 23.9.0.4 nor on WordPress 24.0

**Comment by geriux** [comment]
Hey there @lmischner 👋 I'm trying to reproduce it but I'm not getting the app to crash, I'm following these steps using an iPad 10th gen with iOS 17.1.1. I wonder if I'm not following the steps correctly 🤔 

https://github.com/wordpress-mobile/WordPress-iOS/assets/4885740/f290bfc1-6e86-44ab-91a5-623fff5182ec

**Comment by lmischner** [comment]
Thanks for taking a look, @geriux ! Interesting that you didn't run into it -- I see it every time. 🤔 

https://github.com/wordpress-mobile/WordPress-iOS/assets/103850310/62fc8428-dc85-4495-8eb1-e138be8fba7f

**Comment by geriux** [comment]
Can you please try to open the editor from the "Home" section? I think there's an issue with the Post list view table. Just to double check it is that. Let us know, thank you!

**Comment by geriux** [comment]
I can see the crash without opening the editor in the Post List section 😅 

- Go to the Post list
- Set the Split view mode
- The app crashes

**Comment by lmischner** [comment]
Aha! Good sleuthing. When I launched the editor from the Home view (tapping on the Bloganuary prompt), I did not see the crash.

**Comment by geriux** [comment]
Thanks for checking! We will look into it 👍

**Comment by fluiddot** [comment]
As shared internally in pcdRpT-5gd-p2#comment-8473.

When using the simulator and building the app locally, I can reproduce it in versions 24.0, 23.9, and 23.7, but not 23.6. This makes me wonder if it's related to the Post/Page list screen redesign introduced in version 23.7 ([reference](https://github.com/wordpress-mobile/WordPress-iOS/blob/3e18c1f6cce85c08215f80dc28d94abd6cbf9ad2/RELEASE-NOTES.txt#L74)).

cc @momo-ozawa

**Comment by momo-ozawa** [comment]
Hey @fluiddot! I took a look into this crash and I don't think it's related to post/page list screen changes, but rather a Xcode 15 / iOS 17 issue.

https://stackoverflow.com/questions/77228311/nsinternalinconsistencyexception-reason-layout-requested-for-visible-naviga

When I switch to trunk, I can repro the crash on an iPad running iOS 17 but not iOS 16.4.

I'm not sure if this is the best solution, but adding the following on L515 of `WPSplitViewController.swift` prevents the crash.

```
secondaryViewController.viewControllers = []
```

**Comment by fluiddot** [comment]
> Hey @fluiddot! I took a look into this crash and I don't think it's related to post/page list screen changes, but rather a Xcode 15 / iOS 17 issue.

Ah, good catch, thanks for investigating it @momo-ozawa. Sorry to have misinterpreted the debug session results 🙇 .

> https://stackoverflow.com/questions/77228311/nsinternalinconsistencyexception-reason-layout-requested-for-visible-naviga
> 
> When I switch to trunk, I can repro the crash on an iPad running iOS 17 but not iOS 16.4.

That's interesting. So we can confirm that it's an issue related to the combination of iOS and Xcode version.

**Comment by momo-ozawa** [comment]
An update confirming that this is an iPad split view issue that manifests on Xcode 15/iOS 17.

I can repro the crash on the following screens
- posts list
- pages list
- notifications tab > notifications detail
- me tab > app settings
- ... and other screens that have detail views

I've opened a [PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/22386) that uses my proposed solution above 😄

**Comment by kean** [comment]
The linked PR (https://github.com/wordpress-mobile/WordPress-iOS/pull/22386) was merged, closing.
**Note**: In 25.4, the split view behavior is reimplemented using new triple-column navigation.
