### ISSUE TITLE
Stats Traffic: Analyze High Level Stats architecture

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#22383]
Parent issue: https://github.com/orgs/wordpress-mobile/projects/222/views/8

Analyze current high-level Stats architecture to determine the most optimal approach to develop Stats Traffic while simultaneously improving the quality along the way.

## Task

Detail:
- Stats View Controllers and their functionality
- Data sources
- View update mechanisms
- Date and Period update mechanisms

Suggest:
- Possible approaches for developing Stats Traffic tab 

#### StatsViewController

* Presents
    * **SiteStatsDashboardViewController**
    * NoResultsViewController
    * Jetpack Installation Prompt
    * Activity Indicator
* Initializes Stats Widgets
* Refreshes blog details if needed
* Starts Jetpack plugin installation flow

#### SiteStatsDashboardViewController

* Presents
    * UIPageViewController
        * **SiteStatsPeriodTableVIewController**
        * **SiteStatsInsightsTableViewController**
    * FilterTabBar
    * Manage Insights Button
* Saves and restores previously selected tab and date period
* Manages switching between tabs
* Tracks Stats presentation events

#### SiteStatsPeriodTableViewController

The same view controller is used for `Days/Weeks/Months/Years`. The state of this ViewController can be changed by changing `selectedPeriod: StatsPeriodUnit` variable. `SiteStatsDashboardViewController` changes it when switching between tabs.

* Presents
    * DatePicker (SiteStatsTableHeaderView)
    * UITableView 
    * Ghost Cell Loading
* Is UITableViewController
    * Uses [ImmuTable](https://github.com/wordpress-mobile/WordPress-iOS/blob/a9a56ef2ea989d02d5972181deb1a349287f4926/WordPress/Classes/Utility/ImmuTable.swift#L34) for managing UITableViewController
* Uses `SiteStatsPeriodViewModel` and table view section and row model that it builds.
    * [Sets new tableViewModel on ImmuTableHandler when data changes which fully refreshes table view](https://github.com/wordpress-mobile/WordPress-iOS/blob/a9a56ef2ea989d02d5972181deb1a349287f4926/WordPress/Classes/ViewRelated/Stats/Period%20Stats/SiteStatsPeriodTableViewController.swift#L164)
    * Uses [WordPressFlux](https://github.com/wordpress-mobile/WordPressFlux-iOS). ViewController holds `changeReceipt: Receipt` to observe and keep the reference to viewModel changes. Similar to what’s done in Combine with AnyCancellable.
* Routes to details
* Pull to Refresh
* Supports table view expansion and shrinking (expandedRowUpdated) 

#### SiteStatsPeriodViewModel

ViewModel's main responsibility is to build a data representation of the whole table view. Also, it holds the state of the selected date, period, and latest data.

* Is `WordPressFlux` [Observable](https://github.com/wordpress-mobile/WordPressFlux-iOS/blob/c0a9fe6a20a40b7addaa87093a3d52339485c8ef/WordPressFlux/Sources/Observable.swift#L15)
* Observes `StatsPeriodStore` for changes and notifies its observers
* Requests `StatsPeriodStore` updates with the selected date and selected period
* Builds [tableViewModel ImmuTable](https://github.com/wordpress-mobile/WordPress-iOS/blob/a9a56ef2ea989d02d5972181deb1a349287f4926/WordPress/Classes/ViewRelated/Stats/Period%20Stats/SiteStatsPeriodViewModel.swift#L85) with [rows [ImmuTableRow]](https://github.com/wordpress-mobile/WordPress-iOS/blob/a9a56ef2ea989d02d5972181deb1a349287f4926/WordPress/Classes/ViewRelated/Stats/Period%20Stats/SiteStatsPeriodViewModel.swift#L264), taking information from `StatsPeriodStore`
* Updates date [updateDate(forward: Bool) -> Date?](https://github.com/wordpress-mobile/WordPress-iOS/blob/a9a56ef2ea989d02d5972181deb1a349287f4926/WordPress/Classes/ViewRelated/Stats/Period%20Stats/SiteStatsPeriodViewModel.swift#L238)
* Updates chart bar selection [chartDate(for entryIndex: Int) -> Date?](https://github.com/wordpress-mobile/WordPress-iOS/blob/a9a56ef2ea989d02d5972181deb1a349287f4926/WordPress/Classes/ViewRelated/Stats/Period%20Stats/SiteStatsPeriodViewModel.swift#L229C11-L229C49)

#### StatsPeriodStore

* Is `WordPressFlux` [QueryStore](https://github.com/wordpress-mobile/WordPressFlux-iOS/blob/c0a9fe6a20a40b7addaa87093a3d52339485c8ef/WordPressFlux/Sources/QueryStore.swift#L20)
* Accesses API to fetch the data [via StatsServiceRemoteV2](https://github.com/wordpress-mobile/WordPress-iOS/blob/a9a56ef2ea989d02d5972181deb1a349287f4926/WordPress/Classes/Stores/StatsPeriodStore.swift#L182)
* Uses debouncing, and checks loading state to avoid unnecessary data requests
* Fetches all the necessary information for `SiteStatsViewModel`, and requests data based on `StatsPeriodUnit`(day, week, month, year)
* Caches fetched data in memory using `StatsPediodCache`

#### Flow Chart

```mermaid
flowchart TD
    A[StatsViewController] -->|load| B[SiteStatsDashboardController]
    B -->|load| C[SiteStatsPeriodTableViewController]
    C -->|startFetchingOverview, refreshPeriodOverviewData| D[SiteStatsPeriodViewModel]
    D -->|dipatchAction - startFetchingOverview, refreshPeriodOverviewData| E[StatsPeriodStore]
    E -->|onChange| D[SiteStatsPeriodViewModel]
    D -->|onChange| C[SiteStatsPeriodTableViewController]
    C -->|refreshTableView| H[ImmuTable]
    C -->|get tableViewModel| D
    H -->|refreshData| I[UITableView]
 ```

#### Example data loading sequence

`StatsPeriodStore` dispatches many loading actions for each of the data types, and the mechanism refreshes the whole table view every time we receive new data:

<details>
  <summary>Expand</summary>

  **Refresh table view**
Finished setting data to Period store from disk cache.
**Refresh table view**
Cancel all operations
Finished fetching summary.
**Refresh table view**
Enter group fetching posts.
Enter group fetching referrers.
Enter group fetching published.
Enter group fetching clicks.
Enter group fetching authors.
Enter group fetching search terms.
Enter group fetching countries.
Enter group fetching videos.
Enter group fetching file downloads.
Finished fetching countries.
**Refresh table view**
Finished file downloads.
**Refresh table view**
Finished fetching videos.
Finished fetching search terms.
Finished fetching posts.
Finished fetching published.
Finished fetching clicks.
**Refresh table view**
**Refresh table view**
**Refresh table view**
**Refresh table view**
**Refresh table view**
Finished fetching authors.
**Refresh table view**
Finished fetching referrers.
**Refresh table view**
Finished fetchAsyncData.

</details>

### Date and Period update mechanisms

`SiteStatsTableHeaderView` notifies about changed data through a delegate, and `SiteStatsPeriodTableViewController` triggers `SiteStatsPeriodViewModel` with a changed date to `refreshPeriodOverviewData`. Then the same flow repeats.

```mermaid
flowchart TD
    User -->|Tap back arrow| A[SiteStatsTableHeaderView] -->|dateChangedTo| B[SiteStatsPeriodTableViewController]
    B -->|refreshPeriodOverviewData| C[SiteStatsPeriodViewModel]
```

### Direction

In a nutshell, the new Stats Traffic tab is an evolution of the existing `SiteStatsPeriodTableViewController` that incorporates a date picker within a view, shows a new bar chart, and has a modernized table view style. We're going to use the same data sources and rely on the same behavior of all the other rows within this view. Given that, I don't think there's enough of an argument to justify a complete rewrite of `SiteStatsPeriodTableViewController`. I suggest using existing VCs and VMs as a starting point, replacing what’s working poorly, removing what’s not necessary, and adding new things that we need. 

### Scope

I suggest keeping `StatsViewController`, and `SiteStatsDashboardViewController` out of scope since they are containers that hold Period and Insights view controllers but don't hold the majority of business and UI logic. Also, `SiteStatsInsightsTableViewController` should be unaffected by any changes we're making, unless it requires adapting to any code changes made between shared code.

### Feature Flag

To support the feature flag but also not slow down the development, one option would be creating duplicates of the view controller and view model. For example, `SiteStatsPeriodTableViewControllerDeprecated` and `SiteStatsPeriodTableViewModelDeprecated`. They would be used when feature flags are disabled and removed together with the removal of feature flags. Then we could continue the work on `SiteStatsPeriodTableViewController` and `SiteStatsPeriodTableViewModel` with the advantage of preserved git history. 

This suggestion is optional but would allow us to make changes more freely, build on existing solutions, and at the same time not be concerned about breaking existing functionality.

`SiteStatsPeriodTableViewController` has already a separation of concerns and most of the business logic is held within `SiteStatsPeriodTableViewModel`. 

#### Immutable

`SiteStatsPeriodTableViewController` is based on `ImmuTable` which is also used in a couple of other places outside Stats. `ImmuTable` centralizes table view configuration and provides more structural ways to provide information to the View Controller.

There's one huge drawback of refreshing the whole table view every time data changes which can contribute to stutters or blinks within the view.  I think we should try addressing these issues within the scope of the project.

Therefore the decision to stop using `ImmuTable` can be based on the complications introducing a more efficient table view reloading techniques ([UITableViewDiffableDataSource](https://developer.apple.com/documentation/uikit/uitableviewdiffabledatasource)) or issues with modernizing UI. Otherwise, I'm leaning on keeping it as it is. 

#### WordPressFlux

`SiteStatsPeriodViewModel` is `WordPressFlux.Observable` object. [WordPressFlux](https://github.com/wordpress-mobile/WordPressFlux-iOS) was last updated 5 years ago before `SwiftUI` was introduced.  I think we should be comfortable replacing `WordPressFlux` with `Combine` or any other native techniques during development.

#### Immutable

Same as with ViewController, unless we encounter blockers, I don't see any issues continue building `ImmuTableRow` types within `SiteStatsPeriodViewModel`

#### Testing

`SiteStatsPeriodViewModel` is untested at the moment. We should add tests for the functionality we add or change, refactoring it along the way. Lets also remove any other functionality that will no longer be needed in Stats Traffic tab. View Model contains lots of little pieces of business logic. By adding tests to the functionality we'll be reusing and changing, we'll ensure we understand it.

### Stats Period Store

This store also is built on top of `WordPressFlux`. In my understanding, we need exactly the same data for Stats Traffic as we have for existing Days/Weeks/Moths/Years tab. I think changes to this Store should be outside the scope unless we find it requiring many additions or edits.

**Comment by staskus** [comment]
## StatsPeriodStore

> In my understanding, we need exactly the same data for Stats Traffic as we have for existing Days/Weeks/Moths/Years tab

Since we want to show a Week total but display bars for Day (same for Months, and Years) we may need to fetch a little bit of different data for `Stats Traffic` tab (see `func fetchChartData(date: Date, period: StatsPeriodUnit`).

**Comment by staskus** [comment]
## API

Shared endpoint performance analysis in this task:
- https://github.com/wordpress-mobile/WordPress-iOS/issues/22459

**Comment by guarani** [comment]
I'm closing this issue since it's marked Done and I don't think there's anything to add.
