### ISSUE TITLE
Reader: Followed Sites redundant UI

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#22388]
### Description
It's redundant that we have the "Following" badge for sites in the "Followed Sites" tab.

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/3b6dee54-ec90-48db-9491-8af5fadbf225" width="300" />

### Steps to reproduce the behavior
1. Reader
2. Manage
3. Followed Sites tab

**Comment by kean** [comment]
Fixed.

<img width="320" alt="Screenshot 2024-11-13 at 5 11 43 PM" src="https://github.com/user-attachments/assets/6e038dfd-b337-4a2b-b7aa-cc61358223fe">
