### ISSUE TITLE
Stats Traffic: Create Today card

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#22393]
Parent: https://github.com/wordpress-mobile/jetpack-issue-repo/issues/1
![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/a00e6335-235a-4067-9bed-af657c1c9b83)

**Comment by ravishanker** [comment]
Are we going to replace Today's Stats on dashboard with this new one?

**Comment by staskus** [comment]
> Are we going to replace Today's Stats on dashboard with this new one?

I haven't thought about it before but I think it would make sense to have the same card for both.
