### ISSUE TITLE
Tab Bar: Button animations out of sync with selected item

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#22428]
### Expected behavior
The button icon always animates with the selected item.

### Actual behavior
Sometimes the "Me" icon animates when "Notifications" is selected.

https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/dc7011d6-bd8a-47a0-a9b2-8de6ed0ab5c4

### Steps to reproduce the behavior
I'm not sure how it got into this state. It corrected itself after going to the "Me" tab.

**Comment by twstokes** [comment]
cc @momo-ozawa and @kean as you've worked on these enhancements recently. Thanks!

**Comment by momo-ozawa** [comment]
@twstokes Thanks for the ping! Here's the PR - https://github.com/wordpress-mobile/WordPress-iOS/pull/22430
