### ISSUE TITLE
Stats: Monthly and yearly stats for sites high traffic load super slow or fail

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#22442]
Stats: Monthly and yearly stats for sites with high traffic load super slow or fail

### Steps to reproduce the behavior

1. Pick a site with high traffic and long history
2. Open the Jetpack app
3. Stats
4. Month
5. Notice Stats either successfully load after 1-2 mins or fail to load at all

Example: p1706001126202199-slack-C06BR07TJHK

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

**Comment by irfano** [comment]
The issue also occurs on Android. It is likely related to the usage of endpoints.
