### ISSUE TITLE
Update UI tests for Traffic tab

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#22447]
We have some minimal tests in `StatsTests` that need to be updated [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/UITests/Tests/StatsTests.swift) when the Traffic tab is enabled.

**Comment by staskus** [comment]
Implemented tests (https://github.com/wordpress-mobile/WordPress-iOS/pull/22703) were date-dependant (https://github.com/wordpress-mobile/WordPress-iOS/pull/22734/commits/1c83a974119c179b0d325e4463fb520e249809b7). The date that was associated with February, are now associated with March (see `./API-Mocks/WordPressMocks/src/main/assets/mocks/mappings/wpcom/stats/stats_visits-month.json`). Tests require improvement.

**Comment by guarani** [comment]
I moved this issue off the Traffic project because the UI Tests for Traffic that remain verify that the Traffic screen is there:

https://github.com/wordpress-mobile/WordPress-iOS/blob/f7a950d324a650aeb9de21a2c6c0b54598b6d79d/WordPress/UITests/Tests/StatsTests.swift#L40

I think that's sufficient for this project. I've put this on the "Address remaining bugs" project to follow up on later.

**Comment by staskus** [comment]
No longer relevant for now.
