### ISSUE TITLE
Not correct Gravatar displayed in comments

### ISSUE THREAD

**Issue by develric** [wordpress-mobile/WordPress-iOS#22456]
I was not able to reproduce it, but creating this issue for tracking purposes, so that it does not get lost (and thanks @enejb for spotting it and reporting p1705766488507539-slack-C05N140C8H5 🙇 . Feel free to add to the below in case any further detail is missing 👍 )

In the image below it seems like the Gravatar from two different users is duplicated in comments.

<p>
<image src="https://github.com/wordpress-mobile/WordPress-iOS/assets/47797566/a7531b41-4b4f-4077-9b51-60a6a93e101b" width=300>
</p>

Here is how it (correctly) appears on the web

![image](https://github.com/wordpress-mobile/WordPress-iOS/assets/47797566/b54acd87-365c-431b-ace5-80b115a7d2e9)

But also in my iPad it seems correct, so might be some race or caching issue at play 🤔 

![Screenshot 2024-01-24 at 12 29 37](https://github.com/wordpress-mobile/WordPress-iOS/assets/47797566/2e80de10-0d01-4710-a2a7-9ce4e59fdd07)

**Comment by kean** [comment]
Duplicate: https://github.com/wordpress-mobile/WordPress-iOS/issues/23548.
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/23597.
