### ISSUE TITLE
[Gravatar] Gravatar SDK integration umbrella task

### ISSUE THREAD

**Issue by pinarol** [wordpress-mobile/WordPress-iOS#22543]
Let's list and track work items related with Gravatar integration here.

Replace avatar fetching calls with SDK calls in following places, make sure each flow is tested:

- [x] CommentContentTableViewCell
- [x] MyProfileHeaderView
- [x] NoteBlockCommentTableViewCell
- [x] EpilogueUserInfoCell
- [x] AuthorFilterButton
- [x] AuthorFilterViewController
- [x] ListTableViewCell
- [x] GravatarEmailTableViewCell
- [x] LoginLinkRequestViewController
- [x] UIBarButtonItem+MeBarButton

---

Investigate following methods in the existing UIImageView+Gravatar extension, make sure we don't break the functionality for them after integrating the SDK

- [x] overrideGravatarImageCache
- [x] listenForGravatarChanges

---

- [x] Profile fetching: We won't replace this, the code is unreachable.

Task list for profile uploading:

- [x] Avatar uploading

---

Task list for rename types in Gravatar SDK when `Gravatar` is used unnecessarily:
- [ ] `ImageCache` and `ImageCaching`

**Comment by pinarol** [comment]
## List of places that download avatar via "URL"

This list is intended to be used for regression testing.

### CommentContentTableViewCell

- Go to notifications 
- Tap on a notification of type “comment” ([Person] commented on [your post])

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/201811ff-98f1-4d9c-a0a7-a9437a3b94f5" width=250/>


### NoteBlockHeaderTableViewCell

- Go to notifications 
- Tap on a notification "XXX liked your comment"

- Check the image at the header:

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/f0f1eb84-450d-4f58-bb42-26cb60dee9ad" width=250/>


### LoginNavigationController

As the name describes, this VC is shown when logging in:

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/f88a311c-101c-4749-a55e-5f936d8ca610" width=250/>

### PeopleCell

My Site > People 

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/96ac56f3-95b3-41f8-81b1-0d1f8814ad6f" width=250/>

### PersonViewController

Tap on one of the people on the previous step:

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/ab40a2cc-b69e-4e69-87c0-0d236de46da7" width=250/>

### RevisionsTableViewCell

My Site > Posts > Select a post > … button on the navigation bar > History

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/d67d4733-30c2-4fd4-b60a-b34eaeb7337a" width=250/>

### ~~ListTableViewCell~~

ListTableViewCell is not used for notifications after the PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/22593 

So this test case is cancelled.

~~Notifications tab, each cell is a ListTableViewCell:~~

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/5a31e5ad-fd79-4006-a2b6-3134a39ce0b2" width=250/>



### NotificationContentView

Note: This target is not used and there's a task to remove it: https://github.com/wordpress-mobile/WordPress-iOS/issues/19535 The code is basically unreachable. 

So we don't need to test it. 
~~This one requires for us to generate a push notification~~

<img src="https://user-images.githubusercontent.com/912252/65517294-60d02000-deda-11e9-833a-c98632b6ab42.jpg" width=250/>

~~Alternatively we should be able to drag and drop an .apns file to the simulator and simulate the push notification. I tried this method but couldn't get the result I wanted. I tried running the project with the targets of our notification service extensions. I am able to generate the notification but I couldn't get the `didReceive()` to be called (which is in `extension NotificationViewController: UNNotificationContentExtension`).~~

For WP:

```
{
    "Simulator Target Bundle": "org.wordpress",
    "aps": {
        "alert": {
            "body": "Holy Moly, a notification!",
            "title": "WordPress"
        },
        "category": "like"
    },
    "richNotificationViewModel": { }
}
```

For JP:

```
{
    "Simulator Target Bundle": "com.automattic.jetpack",
    "aps": {
        "alert": {
            "body": "Holy Moly, a notification!",
            "title": "Jetpack"
        },
        "category": "like"
    },
    "richNotificationViewModel": { }
}

```

Related PRs
https://github.com/wordpress-mobile/WordPress-iOS/pull/12542
https://github.com/wordpress-mobile/WordPress-iOS/pull/15253

### NoSitesView

This one normally shows when there's no sites in your account and the `appUIType == .simplified`.


<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/dd7066dd-aed1-48a9-8d29-a98ad387b5ee" width=250/>

Since it is difficult to reproduce those conditions, I manipulated the code this way to be able to see that screen:

<img width="400" alt="Screenshot 2024-02-16 at 12 55 23" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/b4a368e8-7acc-44bd-8193-fbe33fb5d2d8">

<img width="400" alt="Screenshot 2024-02-16 at 12 55 17" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/a5109c04-d42e-4e45-a90c-da311699e859">


----
## Unreachable code

### NoteBlockCommentTableViewCell

Unreachable.

https://github.com/wordpress-mobile/WordPress-iOS/blob/4f2cdc31372ccf8a748357333acb09cc8464e7f6/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationsViewController/NotificationsViewController.swift#L839

That cell is only used by `NotificationDetailsViewController` if the note type is `.comment` but we don’t open `NotificationDetailsViewController` when tapped on a `.comment`, we instead open `NotificationCommentDetailViewController`.


### NoteBlockUserTableViewCell - XXXX and 2 others liked your post YYYYY

Unreachable. Notifications of type "like" are displayed in `LikesListController` anymore so this one become unreachable as far as I understand. https://github.com/wordpress-mobile/WordPress-iOS/blob/4f2cdc31372ccf8a748357333acb09cc8464e7f6/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationDetailsViewController.swift#L430

**Comment by pinarol** [comment]
## List of places that download avatar via "email"

This list is intended to be used for regression testing.

### MeHeaderView

- Go to "Me" 
- The avatar at the top:

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/4fb65606-64cd-46ef-98a8-d569e2a5adc8" width=250/>

### MyProfileHeaderView

- Go to "Me" > My Profile 
- The avatar at the top:

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/8f3d9ab3-c71c-4440-893e-938dba7e58bb" width=250/>

### UIBarButtonItem+MeBarButton

- My Site > (The down arrow at the top right of the page, right near your site title/url) 
- Check the avatar in the navigation bar

The avatar here will be visible only if there are no sites, so I manipulated the code this way to see it:

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/d6e5684d-a0cd-491e-8148-0fe8e94e9b76" width=400/>

<br> 

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/7ae6a6f3-68c7-4361-bf97-418f01fb56ae" width=250/>


### AuthorFilterViewController

- Go to Posts
- Tap on the navigation bar right button
- The filtering sheet opens. Content of that sheet is "AuthorFilterViewController".
- Check the avatar:

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/0ac2a20b-83a2-4a4f-b94c-0a0f44f93dcd" width=250/>

### AuthorFilterButton

- Tap on the "Posts by me" option shown in the previous step
- Check the avatar on the navigation bar

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/ce7a1de9-1449-49af-82b3-d57cf01ac1a4" width=250/>

### EpilogueUserInfoCell

- Login to the app
- After the login this page will appear
- Check the avatar:

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/5032900/352f6f47-367f-4793-aab9-14344a85c8c9" width=250/>

----------

Refer to https://github.com/wordpress-mobile/WordPress-iOS/issues/22543#issuecomment-1948014118 for the below cases:

- ListTableViewCell
- NoteBlockCommentTableViewCell
- CommentContentTableViewCell

**Comment by etoledom** [comment]
## List of places where Profile Fetch is used:

Gravatar profile fetch is used here:

https://github.com/wordpress-mobile/WordPress-iOS/blob/109e40dc342302207835f1f87e1f76b60ffa8dab/WordPress/Classes/ViewRelated/NUX/LoginEpilogueTableViewController.swift#L285

Though it seems to be currently unreachable since https://github.com/wordpress-mobile/WordPress-iOS/pull/18608

To test this code path, is needed to first comment out:

https://github.com/wordpress-mobile/WordPress-iOS/blob/d6978e2f309d65d05559eb6646c63f6c8a2e3b89/WordPress/Classes/ViewRelated/NUX/WordPressAuthenticationManager.swift#L314-L325

Other pre- requisites: 
- Have a self-hosted site with Jetpack.
- If you don't have any, you can create one fast using https://jurassic.ninja/ (the default will install Jetpack connected to your logged-in WPCom account).

After commenting out the mentioned lines and building the app again:
- Log out of any WPCom account.
- Log in using the self hosted site.
  - Check that you see your information from Gravatar in the epilogue screen.

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/9772967/c44da733-5500-4101-a16f-f0827f3dc24a" width="40%">

**Comment by etoledom** [comment]
## List of places where Image Upload is used:

### MyProfileController

- Go to `Me` tab bar option 
- My profile
  - Tapping on `Update Profile Photo` will trigger the image picking and upload process

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/9772967/d8a1078a-a65a-4640-8d04-9dd1a47988b1" width="40%">

### EpilogueUserInfoCell

- Create a new account using WPCom signup process.
- When the account is created, the epilogue user info will prompt to update a user image (+ button at the avatar's top right corner)
  - Tapping on the avatar image, will trigger the image picking and upload process. 

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/9772967/466543ae-f4e2-4802-b85b-c32943af2a22" width="40%">

## Test the results

- Go to https://gravatar.com/site/check/
- Search for the email of the account.
- Check that it shows the avatar selected in the app.
