### ISSUE TITLE
Fix crash in comments introduced via a merge

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2254]
A crash was introduced in the Comments feature via 2cd1694fc58850335b63ab4a6f34e3ee78fb1dac. 

[This line](https://github.com/wordpress-mobile/WordPress-iOS/blob/2cd1694fc58850335b63ab4a6f34e3ee78fb1dac/WordPress/Classes/ViewRelated/Comments/CommentViewController.m#L102) was included after the merge, resulting in the `replyButton` being reassigned. The crash occurs when action button constraints are assigned because the newly created button does not exist in the view hierarchy.

**Comment by rachelmcr** [comment]
This should have been fixed by #2263; please reopen if the issue persists.
