### ISSUE TITLE
Update the ghost loading layout for Reader

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#22568]
Internal ref: p1704102409662609-slack-C05N140C8H5

Update the ghost loading layout so that it matches the latest design:

![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/56059b89-2ac2-424a-bd2e-7a2b024caab3)

**Comment by dvdchr** [comment]
Moving this to the follow-up bug fixing project.

**Comment by kean** [comment]
Done in the scope of a separate project and in a slightly different way. Old Reader code was removed.
