### ISSUE TITLE
Add or update analytics

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#22594]
The current events will be updated based on the discussion at https://github.com/wordpress-mobile/jetpack-issue-repo/issues/4.

Android corresponding PR: https://github.com/wordpress-mobile/WordPress-Android/pull/20194

|`tap_source` property that has been added to `stats_accesed` event|Description|
|-|-|
|`quick_actions`|opening stats from My Site|
|`row`|opening stats from My Site → More|
|`posts`|opening stats from My Site → Posts|
|`today_stats_card`|opening stats from "Today's Stats" card on "My Site"|
|`notification`|opening stats from a notification|
|`link`|opening stats from a deeplink|
|~~`activity_log`~~|~~opening stats from Activity Log screen~~|
|~~`jetpack_connection`~~|~~opening stats after connecting Jetpack~~|
|`widget`|opening stats from widgets|
|`onboarding`|opening stats from onboarding prompt|
|`shortcut`|opening stats from app icon shortcut|

**Comment by staskus** [comment]
@irfano, I added `onboarding` case since Stats can also be opened from the onboarding prompt after login.

**Comment by staskus** [comment]
@irfano, on iOS I'm not going to add `jetpack_connection` tracking since we open the Stats view which has a Jetpack plugin uninstalled state. Therefore `stats_accessed` gets called with any other `tap_source` from which it gets accessed and users either see Stats or an option to install Jetpack plugin / login.

Also, I couldn't find `activity_log` https://github.com/wordpress-mobile/WordPress-Android/pull/20194/files#r1498101816 one as well.

**Comment by irfano** [comment]
> Therefore stats_accessed gets called with any other tap_source from which it gets accessed and users either see Stats or an option to install Jetpack plugin / login.

This approach is preferable. The architecture was different on Android, and implementing it in the current way on iOS would require more effort. I may change it in the future.

> Also, I couldn't find activity_log https://github.com/wordpress-mobile/WordPress-Android/pull/20194/files#r1498101816 one as well.

I searched through the history regarding launching stats from formattable content in the activity log but couldn't find them. So, I don't know how to test opening Stats from Activity Log. Still, I added that event into Android code since opening stats was available in the code. I can delve deeper into this later, but I believe it's not worth prioritizing at the moment.

**Comment by staskus** [comment]
@irfano, thanks for explainin!

> I can delve deeper into this later, but I believe it's not worth prioritizing at the moment.

Yes, I think so too. On iOS, [we don't explicitly route to any Stats-specific views from Activity Log](https://github.com/wordpress-mobile/WordPress-iOS/blob/trunk/WordPress/Classes/ViewRelated/Activity/FormattableContent/ActivityContentRouter.swift). Adding analytics event would also mean implementing explicit handling which I agree is very low priority and not in scope.
