### ISSUE TITLE
iOS 8 punch list

### ISSUE THREAD

**Issue by mikejohnstn** [wordpress-mobile/WordPress-iOS#2262]
Let's be proactive instead of reactive. Test all areas for iOS 8 problems:
- [x] Editor @bummytime @diegoreymendez 
- [x] Notifications @jleandroperez 
- [x] Reader @aerych 
- [x] Site Stats @astralbodies 
- [x] Sign up @sendhil @irbrad @koke 
- [x] Sign in @sendhil @irbrad @koke 
- [x] Jetpack @koke 
- [x] Settings @sendhil @irbrad 
- [x] Me @sendhil @irbrad 
- [x] Overall navigation (e.g. tabs) @sendhil @irbrad 

Added names of people who are working in each area (with Sendhil and Brad filling in gaps). Check it off if you've already done an iOS 8 pass.

**Comment by bummytime** [comment]
I think we are ready for iOS 8. Closing.
