### ISSUE TITLE
🍎 Misplaced avatars (likely due to cell reuse)

### ISSUE THREAD

**Issue by alpavanoglu** [wordpress-mobile/WordPress-iOS#22645]
Wrong avatar is shown. i.e. instead of Person A's avatar, Person B's avatar is shown. This occurs after scrolling back and forth.

Reported here: pdcxQM-39Z-p2#comment-2649 first issue

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by hassaanelgarem** [comment]
@alpavanoglu Is this fixed by #22630?

**Comment by alpavanoglu** [comment]
@hassaanelgarem I suspect it had something to do with caching rather than that issue. I can't reproduce it anymore but I am not 100% sure it is resolved.

**Comment by alpavanoglu** [comment]
It seems this was resolved here: pdcxQM-39Z-p2#comment-2665
