### ISSUE TITLE
🍎 Early truncation & 6 dots (Cannot Reproduce)

### ISSUE THREAD

**Issue by alpavanoglu** [wordpress-mobile/WordPress-iOS#22673]
Reported here: pdcxQM-39Z-p2#comment-2649
Mentioned again here: pdcxQM-39Z-p2#comment-2654

Text truncates earlier than expected and appears to have double "...".

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by alpavanoglu** [comment]
I cannot reproduce this issue both on iPad and on iPhone. I am moving it back for now. If it doesn't surface after RC, we can close the issue.

**Comment by antonis** [comment]
Closing as non-reproducible.
