### ISSUE TITLE
Center Inline Actions vertically with the User Avatar

### ISSUE THREAD

**Issue by salimbraksa** [wordpress-mobile/WordPress-iOS#22693]
Ref https://github.com/wordpress-mobile/WordPress-iOS/pull/22652#pullrequestreview-1896256471

**Actual**
Currently, the notification row subviews are all top aligned when the text height is larger than the avatar's height. 

**Expected**
The Inline Action should always be vertically centered with the user avatar

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by hassaanelgarem** [comment]
Fixed by #22696
