### ISSUE TITLE
[Reader] Change "N Bloggers Like This" to "N Likes" to match web

### ISSUE THREAD

**Issue by osullivanchris** [wordpress-mobile/WordPress-iOS#22710]
<img width="596" alt="Screenshot 2024-02-27 at 14 23 31" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/50576199/4f14f625-4dd6-4c80-aefb-1ba620f3ca8b">

pcdRpT-5X8-p2#comment-9234

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
