### ISSUE TITLE
Deep link to Stats day not working

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#22714]
### Expected behavior

When I visit https://wordpress.com/stats/day in my phone's browser, tapping on the button to open the Jetpack app should take me to the "Day" tab (or "By day" Traffic tab).

### Actual behavior

It opens whatever previously opened Stats tab was saved in memory.

### Steps to reproduce the behavior
1. In the Jetpack app, open Stats and go to a tab e.g. the Weeks tab (or "By week" Traffic tab)
2. Go to https://wordpress.com/stats/day on the phone's web browser
3. Tap "Open" to open the app 
4. Notice that the day tab isn't opened and instead the week tab is still shown

### Additional context 
See https://github.com/wordpress-mobile/WordPress-iOS/pull/22695#issuecomment-1968426825

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by guarani** [comment]
I couldn't reproduce this on 24.4.0.3 (using the Traffic tab). @staskus, do you know if this was fixed? 

Since I'm unable to reproduce, I'll close this. We can re-open if needed. Here's a video showing the deep link to "By day" working for me:

https://github.com/wordpress-mobile/WordPress-iOS/assets/1898325/16fd5cb9-a945-4701-9a80-47d2922d7e93

**Comment by staskus** [comment]
@guarani thanks, I'll try to reproduce as well.

**Comment by staskus** [comment]
@guarani, yes, it works fine for me as well. Maybe WP.com URLs changed or other improvements to the solution made this work.

**Comment by guarani** [comment]
Closing this as not planned instead of completed since we couldn't reproduce. I think that better captures the result here, especially in the context of the "Stats Bug Hunt" project.
