### ISSUE TITLE
Stats Traffic: stats_period_accessed event called when opening Insights tab

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#22717]
### Steps

1. Enable Stats Traffic feature flag
2. Open Stats
3. Select Insights tab
4. Leave Stats
5. Return to Stats
6. Confirm Insights tab is opened
7. Notice both `stats_period_accessed` and `stats_insights_accessed` are tracked

It happens because `SiteStatsDashboardViewController` initializes `trafficTableViewController` which initializes `StatsTrafficDatePickerViewModel` which calls ` period.track()` within the initializer.

⚠️  It even happens with Stats Traffic feature flag disabled. `trafficTableViewController` is incorrectly initialized even when feature flag is disabled.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
