### ISSUE TITLE
Previously selected period not shown when navigating to the Traffic tab

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#22727]
On the Stats Traffic tab, if I select a period such as "By weeks", then go back to the My Site dashboard, and return to Stats, I should still see the "By week" period selected.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by guarani** [comment]
Closing as this is fixed. I'd forgotten that this was fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/22695. I tested and confirmed it's working on the latest `trunk`.
