### ISSUE TITLE
Stats Details: Optimize table view updates by integrating diffable data source

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#22720]
Optimize table view updates by integrating a diffable data source into Stats Details views:
- Insights -> Details
- Traffic -> Details

Use the example and mechanisms of past implementations:
- https://github.com/wordpress-mobile/WordPress-iOS/pull/22542
- https://github.com/wordpress-mobile/WordPress-iOS/pull/22592

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by guarani** [comment]
Just letting you know I'm moving the "Performance improvements" to a separate GitHub project board, will clarify over Slack.
