### ISSUE TITLE
Increase the touch area of Traffic date picker buttons

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#22728]
On the Stats Traffic tab, the arrow buttons and even the "By day" dropdown may be too small to easily tap (mentioned in https://github.com/wordpress-mobile/WordPress-iOS/pull/22400#discussion_r1504278343). Let's check if these need to be made larger.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
