### ISSUE TITLE
Stats Traffic: Show tooltip when tapping on bars

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#22731]
Show tooltip when tapping on bars the same way it's done for Views & Visitors card

![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/d5b628ed-e3ea-4dda-9f7d-55bf518750f3)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
No longer relevant.
