### ISSUE TITLE
Dashboard not accessible in Split View or Slide Over modes on iPad

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#22739]
### Expected behavior

The Home row should always be visible in the side menu on iPad.

### Actual behavior

The Home row disappears from the side menu on iPad when in Split View or Slide Over modes. This prevents access to the dashboard.

### Screenshots

| Split View | Slide Over |
| - | - |
| <img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1898325/a21ac8ad-eb95-418e-9a35-27713de1b976" /> | <img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1898325/326512bf-5dc7-479e-8a02-2c114dfd361e" /> |

#### Split View mode
1. Log in to the Jetpack app on iPad
2. Use Split View mode to put the Jetpack app to one side of the screen (make it narrow)
3. Notice the Home row disappears from the app's side menu

#### Slide Over mode
1. Log in to the Jetpack app on iPad
2. Use Slide Over mode to put the Jetpack app on top of another app
3. Notice the Home row disappears from the app's side menu

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Fixed in 25.4.

<img width="1316" alt="quick-actions" src="https://github.com/user-attachments/assets/384f7ed4-76f9-48ca-bacb-21d1e569bc39">

The app should never check `isPad` when determining which layout to show. It should be done based on a size class.
