### ISSUE TITLE
Stats Traffic: Total Month data is not shown in some cases

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#22749]
![Image](https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/05092575-192d-4044-b906-8f22a91cb0b4)

stats/visits endpoint returns 0 views and visitors if the (future) last day of the month is passed as a parameter:

0 views and visitors this Month (March): `v1.1/sites/180619633/stats/visits?unit=month&quantity=1&date=2024-03-31`
correct number of views and visitors this Month (March) : `v1.1/sites/180619633/stats/visits?unit=month&quantity=1&date=2024-03-30`

Reported here:

https://github.com/Automattic/jetpack/issues/36117

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
