### ISSUE TITLE
Stats Traffic: Prefetching and caching improvements

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#22743]
Possible improvements:

- [ ] Skip refreshing data if cached data exists for the past period
- [ ] Consider prefetching the previous period once the current period loads
- [ ] Consider prefetching different data range once the current data range and period loads

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
No longer relevant. We'll likely make changes to date-picking in general which would require completely different caching strategies.
