### ISSUE TITLE
Stats Traffic chart of current month should not include traffic from previous month

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#22751]
### Expected behavior

When I view traffic for March, I should not see traffic from February.

### Actual behavior

The chart's first bar often includes days from the previous month. This makes it unintuitive for users who expect the chart only to show traffic from March when viewing March.

### Steps to reproduce the behavior
1. Open the Traffic tab in Stats 
2. Switch to By month
3. Notice the first bar in the chart has a date range that includes days from the previous month (assuming the month didn't start on the first day of the week)
4. Notice the bar's height, which is the Views count, includes all the days in that range, which include days from the previous month

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1898325/def2b77e-94a4-46b6-bd36-3d30df153980" width="400" />

The same thing can happen at the end of the month. It's just a coincidence that in the above example, the last week of March will end on the last day of the month.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by guarani** [comment]
I can see arguments for and against leaving this as-is:

Arguments for:
- If users analyze weekly patterns, leaving this as-is is helpful as each bar can be compared to the next.

Arguments against:
- If users are interested only in trends during the current month, then clipping the start and end weeks to remain in the current month would "fix" this issue. Otherwise, users can switch to **By year** to see trends over multiple months.
- Showing a bar with 129 views in March while showing 19 views below makes this screen less glanceable and intuitive. It takes a little mental effort to see the date range and realize what's happened.

**Comment by irfano** [comment]
Good points, @guarani! 🤔  
Clipping weeks is indeed a good solution to fix the disadvantages of the current implementation. However, it would make comparing bars pointless. From the user's perspective, it would be hard to notice that the first week has 6 days instead of 7.

> Showing a bar with 129 views in March while showing 19 views below makes this screen less glanceable and intuitive. It takes a little mental effort to see the date range and realize what's happened.

I agree. But I remain hesitant about "clipping weeks" as it introduces additional issues. I believe this card can be redesigned in another project.

**Comment by guarani** [comment]
Related discussion thread: p1709576037356079-slack-C06BR07TJHK

**Comment by staskus** [comment]
No longer relevant.
