### ISSUE TITLE
Notifications View Controller Memory Leak

### ISSUE THREAD

**Issue by salimbraksa** [wordpress-mobile/WordPress-iOS#22764]
### Expected behavior
The `NotificationsViewController` object shouldn't leak when the user signs out.

### Actual behavior
The `NotificationsViewController` object is retained even after the user signs out.

### Steps to reproduce the behavior
1. Build and run the app in Xcode
2. Navigate to Notifications screen
3. Find a notification with the "Star" Inline Action
4. Tap the Inline Action
5. Sign out
6. Activate the Memory Graph debugger
7. Search for `NotificationsViewController`. The expected behavior is that it shouldn't be found.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
