### ISSUE TITLE
Stats Traffic tab dates should include year 

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#22767]
### Expected behavior

The date shown on the Stats Traffic tab should include the year to avoid confusion about which year is being displayed.

Discussed in:
- p1709586750284709/1709585366.152709-slack-C06BR07TJHK
- p1709042259067229/1709042158.468369-slack-C06BR07TJHK

### Actual behavior

The dates are shown without a year (e.g. "May", "May 1", "Feb 19 - Feb 25")

### Steps to reproduce the behavior
1. Open Stats
2. Go to the Traffic tab
3. Switch "By day" to different periods and notice the dates are displayed without a year.

##### Tested on iPad, iOS 17, Jetpack iOS 24.4 beta

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
