### ISSUE TITLE
Media: Free photo library doesn't open on self-hosted sites that don't have a Jetpack connection

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#22761]
Ref: p1709559396191479-slack-C06AJCED8EN

### Expected behavior
Don't show "Free photo library" option if it's not available - account must be connected

https://github.com/wordpress-mobile/WordPress-iOS/blob/e29a8edf6f2cdef7915e7cb5b924c8251763799d/WordPress/Classes/Models/Blog.m#L547-L548

### Actual behavior
Tapping on "Free photo library" option doesn't do anything

### Steps to reproduce the behavior
- Create a new site via Jurassic Ninja
- Don't connect your WP.com account
- Go to Media > + > Free photo library
- Notice: Nothing happens

##### Tested on JPiOS 24.4

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by momo-ozawa** [comment]
This issue is mentioned in this app review: p1709559396191479-slack-C06AJCED8EN
