### ISSUE TITLE
Comment likes count becomes inaccurate when the notification like action is tapped in quick succession

### ISSUE THREAD

**Issue by salimbraksa** [wordpress-mobile/WordPress-iOS#22779]
### Expected behavior

Tapping the like inline action in quick succession or not should not result in inaccurate likes count.

### Actual behavior

See this message p1709661314601119/1709655110.809149-slack-C06BWNSR02K

### Steps to reproduce the behavior

1. Navigate to Notifications screen
2. Switch to "Comments" tab
3. Navigate to the Comment Details screen by tapping the row. Note down the initial likes count.
4. Go back to Notifications screen
5. Tap the like action twice in quick succession
6. Tap the notification row again
7. Verify if the likes count is accurate or not

##### Tested on iPhone 14 Pro Max, iOS 17 Jetpack iOS / WordPress iOS dd01aca6e0b7729bb792e557fdfa817ef20b7e5f

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
