### ISSUE TITLE
When the device is rotated to landscape, the app automatically navigates from the Notifications screen to Notification Details

### ISSUE THREAD

**Issue by salimbraksa** [wordpress-mobile/WordPress-iOS#22777]
### Expected behavior

The app shouldn't navigate to Notification Details screen when device is rotated to landscape.

### Actual behavior

<video src="https://github.com/wordpress-mobile/WordPress-iOS/assets/9609223/fa423268-66b7-45f0-90f8-3778616da63b" ></video>

### Steps to reproduce the behavior

Using an iPhone device:

1. Navigate to Notifications screen
2. Rotate the device to landscape
3. App automatically navigates to Navigation Details screen

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
