### ISSUE TITLE
Selected notification row displays incorrect background color when device is in landscape orientation

### ISSUE THREAD

**Issue by salimbraksa** [wordpress-mobile/WordPress-iOS#22778]
### Expected behavior

The background color of selected rows should match that of the other rows.

### Actual behavior

![](https://github.com/wordpress-mobile/WordPress-iOS/assets/9609223/bb5a901c-001f-4617-bd77-dc1fe81c9853)

### Steps to reproduce the behavior

Using an iPhone device:

1. Navigate to Notifications screen
2. Rotate the device to landscape
3. The background color of selected rows differs from that of other rows.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
