### ISSUE TITLE
[iPad] Back Button Incorrectly Visible on Reader Details Screen When Accessed from Notifications

### ISSUE THREAD

**Issue by salimbraksa** [wordpress-mobile/WordPress-iOS#22780]
### Expected behavior

The back button shouldn't be visible for root view controllers in the navigation stack.

### Actual behavior

![CleanShot 2024-03-06 at 16 36 31](https://github.com/wordpress-mobile/WordPress-iOS/assets/9609223/dd3d3522-42e1-4b21-95cc-a1522a72af83)

### Steps to reproduce the behavior

Using an iPad device:

1. Navigate to Notifications screen
2. Locate a new post notification
3. Select the notification row
4. Expect the Reader Details screen to appear
5. Verify the Back Button is visible
6. Tapping the Back Button doesn't nothing

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
