### ISSUE TITLE
Reader: Expand the filter bottom sheet's height as the user scrolls the list

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#22815]
Ref: p1708516692210319-slack-C05N140C8H5

The filter bottom sheet starts at half-screen height. Currently, to expand its height, the user needs to manually drag the sheet handle. To improve this, when the user scrolls the filter list, the sheet should expand to fullscreen—ideally matching the velocity as the user scrolls.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Obsolete.
