### ISSUE TITLE
Improve navigation bar hide animation

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#22816]
Refs p1708516551917529-slack-C05N140C8H5, https://github.com/wordpress-mobile/WordPress-iOS/pull/22353#pullrequestreview-1821532770

Currently, the navigation bar lives in a `UIStack`beside the content view. When the navigation bar is hidden, this causes a height change on the content view, which causes the list to slightly jitter due to the size change. The transition also makes it feel like the navigation bar is placed under the content view: 

https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/452b05dc-7569-4189-ad85-21d9df07819a

Possible solution is to hierarchically place the view on top of the content view, and pad the top of the content view so that the contents aren't covered by the navigation bar.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
This whole are is getting replaced, so I'm going to close it.
