### ISSUE TITLE
Deauthorizing app causes auth loops

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#2282]
If you deauthorize the app on WordPress.com, relaunch the app and try to do things there is inconsistent behavior across the app.  Stats, for example, does not show any indication of authentication failure because of its component nature.  This may be addressed with some sort of delegate pattern that can bubble up to StatsViewController.

Ultimately there is an issue with the existing "log back in" view controller that pops up.  Entering in your current WP.com password lets the screen dismiss, but then another comes up right away.  It feels like the new oauth2 token isn't being used/stored and then the next request fails.  I was on the Reader tab when this happened.

**Comment by rachelmcr** [comment]
What's the status on the WPcom/org API client?

I tested deauthorizing the app on WordPress.com and relaunching the app. Nothing came up to prompt me to re-authenticate, show any errors, or stop me from using the app. I was able to continue navigating through the app, but in a more broken state (some sections of the app lacked content, didn't respond when I tapped on them, or crashed when I tried to interact with them). In some cases it was very similar to using the app while offline.

Here are some screenshots that show how the app worked for me after deauthorizing that account: https://cloudup.com/cpH_w4jprvl

**Comment by rachelmcr** [comment]
@sendhil Is there a plan to look into this issue, or can we add a priority/milestone to the issue here?

It seems like a low-frequency issue, but when it comes up it's a high-stakes issue — when users deauthorize the app it shouldn't allow them to continue accessing anything in a logged-in state.

**Comment by kurzee** [comment]
I'm closing this and labelling as Graveyard. While it is a big issue, as mentioned above, there's a larger solution here requiring a big rework of our auth/request code that will have to see the light another day.
