### ISSUE TITLE
Stats Insights: Total Comments details shows a different value

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#22824]
1. Select a higher-traffic site
2. Open Stats
3. Insights
4. Locate Total Comments card and remember the comment number
5. Tap View More
6. Notice Total Comments details card now shows a different number

The details view is also missing Date Picker which is visible in Total Likes. It could be a solution to solve the issue and the confusion.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
Beyond the bug, there's an inconsistency in numbers and/or naming for Total Comments, and Total Likes cards. None of these cards show a "total" number, only a number for a 7-day or a week:

Stats Insights:

|      | iOS | Android     |
| :---        |    :----:   |          ---: |
| **Total Likes** | Shows Likes from **the last 7 days** |  Shows Likes from **the last 7 days** |
| **Total Comments** | Shows Comments from **the last 7 days** | Shows Comments from **the last 7 days** |
| **Total Followers** | Shows **Total** Followers Count | Shows **Total** Followers Count |

Stats Insights Details:

|      | iOS | Android     |
| :---        |    :----:   |          ---: |
| **Total Likes** | Shows Likes from **the current week**, allows to switch weeks, shows Posts and Pages likes for **the current week** |  Shows Likes from **the current week**, allows to switch weeks, shows Posts and Pages likes for **the current week** |
| **Total Comments** | **Shows 0 Comments (this bug)**, shows Top Commenters and Posts cards with **an all-time total comment** stats | Shows Comments from **the last 7 days**, shows Top Commenters and Posts cards with **an all-time total comment** stats |
| **Total Followers** | Shows **Total** Followers Count | Shows **Total** Followers Count |

**Comment by guarani** [comment]
> Beyond the bug, there's an inconsistency in numbers and/or naming for Total Comments, and Total Likes cards. None of these cards show a "total" number, only a number for a 7-day or a week:

Good point. A simple fix could be to remove the "Total " prefix, but these cards aren't part of WP.com's Stats Insights, so removing thes might be an option. WP.com has 7-day highlights on the Traffic tab, which mobile doesn't have, so it feels like we need to take a step back and look at what to add and remove.

**Comment by guarani** [comment]
To address the inconsistency in naming of the Total Likes and Total Comments cards, I added these issues to the Stats Bug Hunt board:
- https://github.com/wordpress-mobile/WordPress-Android/issues/20639
- https://github.com/wordpress-mobile/WordPress-iOS/issues/23015
