### ISSUE TITLE
Post settings: Date title should always be labeled as "Publish"

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#22855]
## Proposal
In the production app, the app shows different titles for the date row depending on the post status. This introduces complexity, and the "Published on" title for contributor roles is misleading since the post hasn't been published yet - just submitted for review.

I'd like to propose matching the web and simply showing "Publish" as the title for the publish date. 

Published | Draft | Draft (contributor) | Scheduled
-- | -- | -- | --
![Simulator Screenshot - iPhone 15 Pro - 2024-03-19 at 16 54 32](https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/0d6bc3d9-e242-4bce-98ff-686828e614f3) | ![Simulator Screenshot - iPhone 15 Pro - 2024-03-19 at 16 54 20](https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/493ed4c5-6238-4809-874d-e39f54b92845) | ![Simulator Screenshot - iPhone 15 Pro - 2024-03-19 at 16 54 07](https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/19025a41-9ce9-42f0-ba7e-226108a34448) | ![Simulator Screenshot - iPhone 15 Pro - 2024-03-19 at 16 53 59](https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/20f10ca8-c161-4833-98cc-746ed4d58a5e)
<img width="1624" alt="Screenshot 2024-03-19 at 17 04 19" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/8e2f07bc-38c0-49d0-9cc0-ce198ce6dc0f"> | <img width="1624" alt="Screenshot 2024-03-19 at 17 04 44" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/07249c5d-0c87-449f-8879-615e227a0aa4"> | <img width="1624" alt="Screenshot 2024-03-19 at 17 04 55" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/f082c68e-0898-4c5e-bd33-2ad82e10b6f0"> | <img width="1624" alt="Screenshot 2024-03-19 at 17 05 07" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/7bb8d3a3-f3d5-486e-a8a5-f1b90c0d9905">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Fixed in 24.9. It now simply says "Publish Date" and uses a shorter format to make sure the data always fits.

<img width="320" alt="Screenshot 2024-05-02 at 6 45 17 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/d5214417-fc55-48f8-91f2-f8832b6701ff">
