### ISSUE TITLE
Posts list: contributor drafts missing context menu actions

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#22854]
### Expected behavior
Contributor drafts should have the "Duplicate" and "Publish" actions available in the context menu to match the web

<img width="1238" alt="Screenshot 2024-03-19 at 16 32 23" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/16515279-a11d-4830-972a-4a45b701e9e3">

### Actual behavior
"Duplicate" and "Publish" are missing.

It's particularly inconvenient that "Publish" is missing; the only way to publish is to go in to post settings and change the status to "Published". There is no option in the editor overflow menu to publish either. I'm not sure if this is intentional, but I think the editor should also have a "Publish" option. 

### Steps to reproduce the behavior
- Create a contributor post for a site and submit for review (on the web or app, whichever is easier)
- On the app, log in via an account that has admin access and locate the above post
- Tap on the context menu for the post

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
