### ISSUE TITLE
Stats Traffic: Card information fails to load when date cannot be parsed when returned from API

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#22859]
self.periodDataQueryDateFormatter.date(from: "2023-10-01") returns nil  resulting in "An error occurred" messages shown on Stats Traffic cards

From https://github.com/wordpress-mobile/WordPress-iOS/pull/22826#pullrequestreview-1944807282

> An error occurred when viewing certain weeks

I thought it might be related to Oct having six calendar weeks, but it looks to be related to DST kicking in in my timezone on Oct 1st.

> On the team P2 with the week of "Sep 25 - Oct 1, 2023" selected, the screen doesn't load and `An error occurred" is shown:

> self.periodDataQueryDateFormatter.date(from: "2023-10-01") returns nil for me, which ends up being due to clocking moving forward one hour at that time. Adding df.timeZone = TimeZone(secondsFromGMT: 0) seems to fix the issue.
> This is unrelated to this PR, so not a blocker.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
The bug is reproducible and looks to be tightly related to TimeZones and DTS. The one used in Paraguay has a DTS change at midnight 10-01 which is ambiguous to `DateFormatter` and `nil` is returned. Even [similar examples from StackOverflow](https://stackoverflow.com/questions/72406774/dateformatter-returns-nil-with-specific-combination-of-timezone-and-locale) reference Paraguay timezone with this particular bug.

DateFormatter:

```
private var periodDataQueryDateFormatter: DateFormatter {
    let df = DateFormatter()
    df.locale = Locale(identifier: "en_US_POSIX")
    df.dateFormat = "yyyy-MM-dd"
    return df
}
```

```
po df.timeZone = TimeZone(identifier: "America/Asuncion")
po df.date(from: "2023-10-01")

nil
```

```
po df.timeZone = TimeZone(identifier: "Europe/Vilnius")
po df.date(from: "2023-10-01")

▿ Optional<Date>
  ▿ some : 2023-09-30 21:00:00 +0000
    - timeIntervalSinceReferenceDate : 717800400.
 ```

### Solution

[In documentation](https://developer.apple.com/documentation/foundation/dateformatter) Apple suggests to set the timezone to UTC:

> When working with fixed format dates, such as RFC 3339, you set the [dateFormat](https://developer.apple.com/documentation/foundation/dateformatter/1413514-dateformat) property to specify a format string. For most fixed formats, you should also set the [locale](https://developer.apple.com/documentation/foundation/dateformatter/1411973-locale) property to a POSIX locale ("en_US_POSIX"), and set the [timeZone](https://developer.apple.com/documentation/foundation/dateformatter/1411406-timezone) property to UTC.

> RFC3339DateFormatter.timeZone = TimeZone(secondsFromGMT: 0)

However, this is not a straightforward solution, since in Stats we're working with the dates that are in site's timezone.

**Comment by staskus** [comment]
Closing as won't fix. See https://github.com/wordpress-mobile/WordPress-iOS/pull/22910#issuecomment-2188056662
