### ISSUE TITLE
[Reader] Unable to subscribe to website

### ISSUE THREAD

**Issue by alpavanoglu** [wordpress-mobile/WordPress-iOS#22865]
Reported by a user on AppStore: p1710914818818319-slack-C06AJCED8EN

## Description
The user is unable to subscribe to a website on Reader. They see either on of these error messages:
- Couldn't subscribe to a website at the specified address
- Network connection was lost.

## Steps to reproduce the behavior
I don't have the steps since it was reported by a user. If there's a match for the errors above, that could help surfacing the exact issue.

iOS Version: 24.4
Jetpack App

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
