### ISSUE TITLE
Use new feature announcement UI

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#22868]
The new feature announcement screen isn't enabled by default. Now that we're targeting 24.5 for release on iOS, enable it.

The old UI (left) vs. the new UI (right):

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1898325/b54a2af3-03f6-45bf-a84c-d30367b49d9c" width="500" />

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by guarani** [comment]
Closed by https://github.com/wordpress-mobile/WordPress-iOS/pull/22869.
