### ISSUE TITLE
Posts & Pages: Context menu shows "Submit for review" instead of "Publish" for JP disconnected self-hosted sites

### ISSUE THREAD

**Issue by momo-ozawa** [wordpress-mobile/WordPress-iOS#22864]
### Expected behavior
"Publish" in the context menu

### Actual behavior
"Submit for review" in the context menu, but the action actually publishes the post/page

### Steps to reproduce the behavior
- Add a JP disconnected self-hosted site
- Create a draft
- In the drafts tab, locate the draft and tap the context menu
- Notice: a "Submit for review" action is displayed
- Tap the "Submit for review" action
- Notice: the post is actually published

https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/0c7aadfb-91e9-4cb7-b24e-1c2f01b9782d

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by momo-ozawa** [comment]
Closing since this is no longer an issue

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/6711616/6f0be883-3344-4067-8409-7a61ecfefb2a" width=200>
