### ISSUE TITLE
Reader: Viewing site details doesn't show correct values

### ISSUE THREAD

**Issue by wargcm** [wordpress-mobile/WordPress-iOS#22883]
Ref: p4a5px-2UT-p2

### Expected behavior

When a user views a site by tapping on it, it should show the correct information for the site.

### Actual behavior

If an earlier, cached version of the site exists locally, that is returned instead of fetching the latest data.

### Steps to reproduce the behavior

1. Using a site you can post on, subscribe to it
2. View the blog details in the Reader
3. Add posts to the blog
4. View the blog details again after the posts

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
