### ISSUE TITLE
The labels on the traffic chart are not fitting on the card

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#22893]
### Expected behavior
The labels on the traffic chart do not fit properly on the card when using long words in languages other than English, such as Turkish.

### Actual behavior
When the device language is set to Turkish, the labels on the traffic chart do not fit on the card.

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2471769/3f41fea1-2879-4865-8c73-d95b78c4456a" width=320>

### Steps to reproduce the behavior
1. Set the device language to Turkish.
2. Log in.
3. Open the Traffic ("Trafik") tab from "My Site → Stats"

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
