### ISSUE TITLE
Cleanup: Remove unused editor code

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#22906]
Research and confirm if we can remove the following from the project:
- ✅ `EditPageViewController(homepage:)`
- ✅ `PostEditorAction.continueFromHomepageEditing`
- ⚠️ `AztecVerificationPromptHelper`

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Please, don't remove these just yet. I'll do it on Monday as long with some other unused code.

**Comment by twstokes** [comment]
No problem @kean - my plan is just to help research and confirm.

**Comment by twstokes** [comment]
`EditPageViewController(homepage:)` can go since it has no more callers.

**Comment by kean** [comment]
Nice!

**Comment by twstokes** [comment]
`PostEditorAction.continueFromHomepageEditing` can go because (from what I can tell) it depends on `isHomePageEditor` being `true`, and that's only set via `EditPageViewController(homepage:)`. That then cascades to undoing [this project](https://github.com/wordpress-mobile/WordPress-iOS/pull/17429/files) which lands the user in the editor after creating a new site.

Personally I'm not sure _why_ we chose to stop supporting this functionality as it appears quite a bit of effort went into it. Perhaps it was the shift to the Site Editor and the fact that more themes are depending on it. (e.g. there's no "home page" to land in for those themes)

**Comment by twstokes** [comment]
`AztecVerificationPromptHelper` is an interesting one... what I did to test:

1. Create a new account on WordPress.com web by entering my email address
2. Do **not** verify the email address (Dotcom web will show a banner that the email address has not yet been verified)
3. Set a password for the account
4. Start a new draft on web using the "Classic" editor (so the app will use Aztec)
5. Authenticate into the app with the account email and password from step 3
6. Open the draft (which loaded Aztec), make edits, and tap "Publish"
7. I expected the confirmation prompt, but it published successfully

I think this is due to the post being created on the web, so from the app the [`action` is an `update`](https://github.com/wordpress-mobile/WordPress-iOS/blob/f6f88908b3b378bed35feb1c57bb74c583417867/WordPress/Classes/ViewRelated/Aztec/Helpers/AztecVerificationPromptHelper.swift#L50). I've also confirmed that if I **duplicate** the post that was created on the web inside the app, the verification prompt helper will show.

So it looks like we technically still have a need for it, albeit via an extreme edge case. Thoughts @kean? IMO if web lets users publish posts without confirming their email (which it does), maybe we should lift this from the app?

**Comment by kean** [comment]
> IMO if web lets users publish posts without confirming their email (which it does), maybe we should lift this from the app?

I agree. The risk is low – you'll presumably get an API error if there is a business rule that prevents that action.
The implementation has to go too. If it becomes a requirement, It should be based on the API response and not hardcoded in the app.

```swift
guard action == .publish 
```

It's not checking `schedule` 👀

**Comment by SiobhyB** [comment]
If we agree that email verification shouldn't be necessary for publishing a post, then we could also fix https://github.com/wordpress-mobile/WordPress-iOS/issues/21472. :D I personally agree with matching the web, too.

**Comment by dcalhoun** [comment]
I agree that removing email verification to mirror the web experience makes sense. The earliest references I could find for adding this mechanism are in https://github.com/wordpress-mobile/WordPress-iOS/commit/965a456c455b0a38f86c04244ed21ee0a4c59ed6 and https://github.com/wordpress-mobile/WordPress-iOS/commit/5367658efcdc65167ea42b669e5a14555be8b5cb, but it offers no explanation for why. 

I noticed the logic appears to be referenced in the GutenbergViewController. Is there a scenario where the verification is applied there as well? 

https://github.com/wordpress-mobile/WordPress-iOS/blob/a80e96ea95f3df5f3569cfabee8a54f50caa246c/WordPress/Classes/ViewRelated/Gutenberg/GutenbergViewController.swift#L311

**Comment by twstokes** [comment]
> Is there a scenario where the verification is applied there as well?

That's correct @dcalhoun - we show it in the block editor.

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2092798/d23fa4d4-54f3-4b4a-8ba6-ee639fd926f3" width="300" />

**Comment by dcalhoun** [comment]
My thought is that the email verification might've been a spam site deterrent, a tool to increase marketing contacts, a mechanism to help prevent account lockout, or all of those. 

I still think it is odd for the web and mobile app experiences to diverge, but is it worth first asking if the current web experience is a bug?

**Comment by twstokes** [comment]
That's a good thought @dcalhoun. After seeing the context below (see ref) it seems intentional, but it would be good to double-check the latest as it's got some age to it. I also confirmed that a site can be launched without confirming the address.

ref: p58i-bwV-p2

**Comment by twstokes** [comment]
@kean I'm going to unassign myself from this issue, but please let me know if there's anything else to address. To summarize, it looks like:

**Can be removed:**
- ✅ EditPageViewController(homepage:)
- ✅ PostEditorAction.continueFromHomepageEditing

**Can be removed if it's confirmed that the [web's behavior is not a bug](https://github.com/wordpress-mobile/WordPress-iOS/issues/22906#issuecomment-2034600285):**
- ⚠️ AztecVerificationPromptHelper

We could also proceed with the same treatment for Mobile Gutenberg and [resolve this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/21472) as pointed out by @SiobhyB.
