### ISSUE TITLE
Reader Customization

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#22925]
![customisation mocks](https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/8431ab91-7283-4a21-b8c5-e26576b273d3)

Continuing from #22851, this task tracks the remaining issues with Reader customization that should be resolved before enabling the feature flag.

- [x] Properly apply display settings on:
  - [x] #22929
  - [x] #22938
- [x] #22939 
- [x] #22948 
- [x] #22967
- [x] #22985 
- [x] #22995 
- [x] #23001
- [x] #22999
- [ ] Create a custom slider component to match the design (maybe...)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by dvdchr** [comment]
This has been shipped for 24.7, publicly available on Apr. 29, 2024.
