### ISSUE TITLE
Uploading media and posts sporadically fails, reporting the lack of an internet connection

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/WordPress-iOS#22922]
### Expected behavior
Uploading media in the editor should consistently succeed when an active internet connection is available — wi-fi or cellular. 

### Actual behavior
Uploading media or updating posts sporadically fail, reporting there is no internet connection. This was experienced on a cellular connection, but it could possibly also occur on an unstable wi-fi connection as well. 

<details><summary>Screenshots</summary>

| Screenshots | Screenshots |
| - | - |
| ![IMG_8277](https://github.com/wordpress-mobile/WordPress-iOS/assets/438664/f1ea322b-d0b8-4d2c-b6a1-1725cf8e00ca) | ![IMG_8278](https://github.com/wordpress-mobile/WordPress-iOS/assets/438664/81af399c-442a-433a-a682-72772ee1adf6) |
| ![IMG_8279](https://github.com/wordpress-mobile/WordPress-iOS/assets/438664/1b12abc0-69cc-46c1-822c-a10649571797) | ![IMG_8280](https://github.com/wordpress-mobile/WordPress-iOS/assets/438664/1183c704-495d-4495-a441-70d6557135f9) |
| ![IMG_8281](https://github.com/wordpress-mobile/WordPress-iOS/assets/438664/a5102ef1-1294-4054-bfa5-b6d95f30bb1c)| |

</details>

### Steps to reproduce the behavior
1. Disable wi-fi and use a (possibly unstable) cellular connection. 
2. Create a new post. 
3. Attempt to upload images for the post content. 
4. At times, the uploads may fail and report there is no internet connection.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by wargcm** [comment]
This issue is mentioned in this app review: p1714365370940719-slack-C06AJCED8EN

**Comment by kean** [comment]
I think it's safe to say that it can be closed now as it was an HTTP3-related issue. What's the latest on it is another story.
