### ISSUE TITLE
NSInternalInconsistencyException: UIGraphicsBeginImageContext() failed to allocate CGBitampContext: size={-1, -1}, scale=2.000000, bitmapInfo=0x2002. Use UIGraphicsImageRenderer to avoid this assert.

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#22936]
Parent ticket: https://github.com/wordpress-mobile/WordPress-iOS/issues/21943
Sentry Issue: https://a8c.sentry.io/issues/1871799689/events/a241b6f32c044ccfb692a24b21ce9a86/?project=1438083

> NSInternalInconsistencyException: UIGraphicsBeginImageContext() failed to allocate CGBitampContext: size={-1, -1}, scale=2.000000, bitmapInfo=0x2002. Use UIGraphicsImageRenderer to avoid this assert.

Sentry issue contains many unrelated issues. This one spiked on 24.4.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
This crash should be fixed for 24.6. https://github.com/wordpress-mobile/WordPress-iOS/pull/22425 updated Aztec version which made a fix in the latest version https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1383
