### ISSUE TITLE
EXC_BAD_ACCESS: Exception 1, Code 1, Subcode 16 >

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#22942]
**Sentry Url**: https://sentry.io/share/issue/5cdf180e209e4c9f9a1da7ddc8581ff1/
**User Count**: 1
**Count**: 5
**First Release**: com.automattic.jetpack@24.5+24.5.0.2
**First Seen**: 2024-04-02T22:15:37Z
**Last Seen**: 2024-04-02T22:15:45Z
**24 Hours**: 5
**30 Days**: 5
**LogID:** 4ED7AC58-4BE6-46DA-9BD8-0B36C7C190E6

```
EXC_BAD_ACCESS: Exception 1, Code 1, Subcode 16 >
  File "null", line null, in swift::AsyncTask::waitFuture
  File "null", line null, in swift::swift56override_swift_task_future_wait_throwing
...
(3 additional frame(s) were not displayed)
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by guarani** [comment]
I'm not assigning a priority yet. This has one affected user (low impact), but unknown severity since I don't know what happens when this crash occurs. The stack trace doesn't reveal any app code.

**Comment by guarani** [comment]
Asked about this in p1712114130843549-slack-C012H19SZQ8

**Comment by guarani** [comment]
I gave this Medium priority due to high severity (logs show app crashing on startup) and low impact (only one user affected).
