### ISSUE TITLE
 The content of the Posts tab is not being updated due to an unknown reason

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#22969]
### Expected behavior
When switching the tab of Posts, the content should be updated accordingly.

### Actual behavior
The user switches tabs of “Posts” page, and after a few switches, the tab no longer updates the content; it remains stuck on “Published” content. 

### Steps to reproduce the behavior
The issue was reported by a user, but we don't know how to reproduce it. It may be related to the number of posts on the site, as the user has 1239 draft posts and 2642 published posts. The user was using voice control.
Internal ref: p1712310923635989-slack-C0180B5PRJ4

##### Tested on iPad mini 6th gen, iOS 17.4, Jetpack iOS 24.3

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by alinclamba** [comment]
User replied sharing a few more details and screenshots, it might help to let you know. Please review their reply from Sat, 6th April - 7859553-zd-a8c

**Comment by kean** [comment]
It's likely fixed by #22966. 
Since there are no steps to repro, I would just leave this bug open and close it if there are no more similar reports in the future.

**Comment by irfano** [comment]
> User replied sharing a few more details and screenshots, it might help to let you know. Please review their reply from Sat, 6th April - 7859553-zd-a8c

This appears to be a separate issue. I have opened a new [issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/22972) for it.

**Comment by kean** [comment]
Fixed in 24.9.

**RCA**
- `controllerDidChangeContent` produces an incorrect set of updates
- the app catches an ObjC exception and try to call `reloadData` and it hoses the updates
