### ISSUE TITLE
Connection issues on 24.6

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#22970]
Updating from 24.5 to 24.6 beta for some users results in connection or no network issues, in some rare instances leading to a crash.

Discussion: p1712262895900119-slack-C012H19SZQ8 and pcdRpT-6gD-p2#comment-9689
Testflight crash link: https://appstoreconnect.apple.com/apps/1565481562/testflight/crashes/AM0gClJHOzNzhF43Uk-LBmQ?appPlatform=IOS&sort=-timestamp
Similar Woo issue: p1711543418425459-slack-CGPNUU63E p1709828841472819-slack-CGPNUU63E

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
@crazytonyli, it would be great if you shared your expertise on Monday if you have an idea of potential causes.

**Comment by crazytonyli** [comment]
We have identified the issue might relate to HTTP3. HTTP3 support has been disabled for iOS apps. We'll see how it goes from here.

**Comment by crazytonyli** [comment]
No connection issues reported so far since HTTP3 is disabled. I'll close this issue for now.
