### ISSUE TITLE
When you share a post and tap "Copy", it copies title instead of a URL

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#22988]
### Expected behavior

- It copies a URL (previous behavior)

### Actual behavior

- It copes a title + newline + URL

### Steps to reproduce the behavior

- Open Post List 
- Open the context menu for a post
- Tap "Share"
- Tap "Copy"

**_Update_**: the same issue applies to other parts of the app.

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

24.6

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by hassaanelgarem** [comment]
@kean Thanks for reporting this. Are you suggesting that this is the expected behavior for all share actions or just the "Copy" action?

**Comment by kean** [comment]
It's an expected behavior for the "Copy" action in the "Post List" for posts. It replaced the old "Copy Link" context menu action.

Ideally, there should be an action in the sheet named "Copy URL" to avoid any ambiguity, but that would be an enhancement request and not a defect.

**Comment by hassaanelgarem** [comment]
> Ideally, there should be an action named "Copy URL"

I agree. That's why I don't see this as a "Bug". But I see how this can break a user's workflow. We can try to keep this behavior for other actions like sharing to apps and revert to the old behavior for the copy action only.

**Comment by kean** [comment]
Hey, @hassaanelgarem, would your team able to prioritize this issue for 24.7? "Share" is the most common action on posts, so it's a major issue for the Post List. I think it also broke the flow in other parts of the app.

**Comment by hassaanelgarem** [comment]
@kean I am AFK at the moment.
@alpavanoglu Can you work on a fix for this?

**Comment by oskosk** [comment]
From my personal experience, I haven't encountered the issue as described here: `It copies a title + newline + URL`. 

However I witnessed this problem when accessing a post from the notifications list, then clicking the share button, and then copying. I only get the title. 

Most apps show "Copy Link" as the action in such context. 

It started with Jetpack 24.4.0.0

**Comment by alpavanoglu** [comment]
To confirm, are we going to add the "Copy Link" action in addition to existing "Copy"?  I think the regular share actions can contain the title but we don't need both "Copy" and "Copy Link". So I'll just revert the "Copy Link" title and functionality then unless you all had something else in mind. Lmk.

**Comment by kean** [comment]
There was a regression in how the existing "Copy" button works. The expected behavior is for it to copy only the URL. I would prioritize fixing this issue.

I also floated an idea of adding a "Copy Link" action to the share sheets. I think it should be doable using a `UIActivity` sublclass. This would be ideal.

**Comment by momo-ozawa** [comment]
👋 Hey @kean, I'm bumping this PR to 24.8 since it's code freeze day. If this PR needs to target 24.7, please target the release branch once it's been cut. Thanks!

**Comment by dvdchr** [comment]
Looks like this issue has been resolved through #23007, which was merged into 24.7. I'll remove the milestone assignment from this issue and mark this as completed. Feel free to reopen this issue if you still see this occurring on 24.7 or higher.

**Comment by oskosk** [comment]
Hi folks. This issue seems to be back. Testing 24.9.05 @dvdchr should we reopen?

**Comment by dvdchr** [comment]
Thank you for the report @oskosk! Will reopen the issue.

**Comment by kean** [comment]
Starting with https://github.com/wordpress-mobile/WordPress-iOS/pull/23692, the app no longer includes "title" and "summary" in the share sheets, so it will always share and/or copy only the URL in Reader, Post List, and any other parts of the app.
