### ISSUE TITLE
Crash when opening post stats

### ISSUE THREAD

**Issue by guarani** [wordpress-mobile/WordPress-iOS#23036]
### Expected behavior

Viewing a posts stats should work.

### Actual behavior

The app crashes when viewing a post's stats.

### Steps to reproduce the behavior
1. Log into the Jetpack app
2. Go to Posts
3. Open the `...` menu
4. Tap Stats
5. Notice the app crashes

Logs show:
```
Thread 1: "Fatal: supplied item identifiers are not unique. Duplicate identifiers: {(\n    WordPress.AnyHashableImmuTableRow(immuTableRow: WordPress.TopTotalsPostStatsRow(itemSubtitle: \"Period\", dataSubtitle: \"Views\", dataRows: [], limitRowsDisplayed: true, postStatsDelegate: Optional(<WordPress.PostStatsTableViewController: 0x13ee5de00>), action: nil))\n)}"
```

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by guarani** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/23038 (I think GitHub doesn't auto-resolve issues when the linked PR doesn't target the main branch `trunk`)
