### ISSUE TITLE
Subscribers Email Opens and Clicks Card & Details

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#23045]
Full Scope: https://github.com/Automattic/wordpress-mobile/issues/47
Design: [IqhXWz3Iir7RMb5XH5gGfZ-fi-883%3A4006](https://href.li/?https://www.figma.com/file/IqhXWz3Iir7RMb5XH5gGfZ/?node-id=883%3A4006)

Create Emails Opens and Clicks card.

#### More Details

This task will likely require the implementation of new endpoints that are used on the web.

(`/rest/v1.1/sites/{site_id}/stats/emails/summary?quantity=30&sort_field=opens&sort_order=desc`) fbhepr%2Skers%2Sjcpbz%2Sjc%2Qpbagrag%2Syvo%2Srznvy%2Qfgngf%2Srznvy%2Qfhzznel.cuc%3Se%3Q53087o60%26sv%3Qtrg_rznvy_fhzznel%2335-og

### Scope 

- Emails Opens and Clicks Card that displays 6 item list
- Emails Opens and Clicks Details that display a longer list as on WP.com

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
