### ISSUE TITLE
Total Subscribers Card

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#23048]
Full Scope: https://github.com/Automattic/wordpress-mobile/issues/47
Design: [IqhXWz3Iir7RMb5XH5gGfZ-fi-883%3A4006](https://href.li/?https://www.figma.com/file/IqhXWz3Iir7RMb5XH5gGfZ/?node-id=883%3A4006)

Create Total Subscribers Card

### Scope 

- Total Subscribers Card without navigation

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
