### ISSUE TITLE
Stats: Create missing ghost (loading) views

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#23059]
Full Scope: https://github.com/Automattic/wordpress-mobile/issues/47
Design: [IqhXWz3Iir7RMb5XH5gGfZ-fi-883%3A4006](https://href.li/?https://www.figma.com/file/IqhXWz3Iir7RMb5XH5gGfZ/?node-id=883%3A4006)

- Create a three-column ghost cell to be used when loading the Emails Opens and Clicks card, which was implemented in https://github.com/wordpress-mobile/WordPress-iOS/pull/23056
- Create a line chart ghost cell to be used when loading Subscribers Chart

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
