### ISSUE TITLE
Stats Subscribers: Dynamic type support improvements

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#23060]
Full Scope: https://github.com/Automattic/wordpress-mobile/issues/47
Design: [IqhXWz3Iir7RMb5XH5gGfZ-fi-883%3A4006](https://href.li/?https://www.figma.com/file/IqhXWz3Iir7RMb5XH5gGfZ/?node-id=883%3A4006) 

Improve dynamic type support for cards used in the Subscribers tab. Comes from https://github.com/wordpress-mobile/WordPress-iOS/pull/23056#pullrequestreview-2015662409

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
