### ISSUE TITLE
Stats Widget: Widgets do not update automatically

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#23087]
Stats Widgets don't update automatically on their own anymore.

Context: p1714038584459619-slack-C0180B5PRJ4

### Steps to reproduce

1. Install Jetpack app
2. Login
3. Go to the home screen
4. Any widget
5. Notice that it shows zero values when it's loaded

Expected: Widget should load values itself

### Investigation

Widget calls `StatsServiceRemoteV2.getData` by itself to fetch stats info. However, the `guard let` code fails.

<img width="814" alt="image" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/4062343/a7ccc60e-1627-4484-8ea2-36acb2b01402">

It happens because `self` is `nil` since `StatsServiceRemoteV2` is not retained in `StatsWidgetService`. There may have been some internal fixes within `StatsServiceRemoteV2` which removed some retain cycles which made the widget code work in the first place.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
