### ISSUE TITLE
Image captions in the reader should be styled. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2310]
Title has it. Currently they are unstyled.

**Comment by kurzee** [comment]
Maybe one of the design refreshes coming up.

**Comment by aerych** [comment]
Possibly.  Our use of DTCoreText for rendering has made this a bit tricky but (hopefully) soon it will no longer be a factor.

**Comment by rachelmcr** [comment]
Reopening this as it was recently reported by a user (internal ref: p4a5px-2kH-p2) who expected image captions to at least be centered when the image and caption are centered in their post.

**Comment by designsimply** [comment]
Tested and confirmed using the following steps:

1. Go to My Site > Blog Posts > +.
1. Add a title, content, and an image with a caption.
1. Publish the post.
1. Find the post in the Reader and open to the individual post view.
1. Check to see if the caption looks stylized or differentiated from other paragraph text at all.

**Result:** captions for images seen in individual posts inside the Reader are indistinguishable from other paragraph text.

| Editor | Reader | Safari |
| --- | --- | --- |
|  <img src="https://user-images.githubusercontent.com/1119271/76908746-128b5080-686f-11ea-9767-238143b9878b.PNG" width="180" alt="IMG_3565"> | <img src="https://user-images.githubusercontent.com/1119271/76908743-115a2380-686f-11ea-80d3-951b04eaab35.PNG" width="180" alt="IMG_3567"> | <img src="https://user-images.githubusercontent.com/1119271/76908737-0ef7c980-686f-11ea-8529-e4141a698e51.PNG" width="180" alt="IMG_3568"> |

<sup>Tested with WPiOS 14.4.0.0 TestFlight beta on iPhone 6S iOS 13.3.1.</sup>

<sup>h/t @elibud and monicavohara for the report.</sup>

**Comment by yaelirub** [comment]
Confirmed that this is fixed with the work done in Reader Post Rendering project.
