### ISSUE TITLE
Editor: image uploads are not removed when the block is deleted

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23124]
### Steps to reproduce the behavior

- Open an editor
- Add an image block with a failing uploads (e.g. the size is too large)
- Remove the block (do NOT cancel the upload)

### Expected behavior

The associated upload is removed. You can publish a post or save it as a draft.

### Actual behavior

The upload is not cancelled and prevents the app from publishing the post or saving it as a draft. There are no workarounds.

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/47ca6cc2-70fe-4351-a009-74c890649e34

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

24.5, 24.7

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Changing the priority to "High" because severity is high, but I don't believe it's a common scenario.
