### ISSUE TITLE
Post Jetpack login causes funky stats view

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#2315]
After being prompted to enable/sign into Jetpack for stats to work, a user reported seeing the following:
![photo1](https://cloud.githubusercontent.com/assets/373903/4134842/5935a1e6-3370-11e4-9a29-cefdd81ea9c2.png)

I suspect there is some sort of missing refresh for the table data after logging into Jetpack.  There could also be a problem with how stats is signing into Jetpack.

**Comment by hoverduck** [comment]
29Oct15 Bug Scrub

Unable to reproduce, recommend closing.  The page design looks completely different now, with Insights and everything, so I assume that this is OBE.

**Comment by astralbodies** [comment]
THanks @hoverduck - closing for now
