### ISSUE TITLE
Wrong background color on the pie chart of Subscribers stats card

### ISSUE THREAD

**Issue by irfano** [wordpress-mobile/WordPress-iOS#23162]
### Expected behavior
The background color of the pie chart should be the same as the card's background.

### Actual behavior
The pie chart's background color is different.

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/2471769/0cd1d55d-007a-45e5-a80e-e9fd734bd14a" width=320>

### Steps to reproduce the behavior
1. Log in.
2. Change the app's theme to dark from "Me → App Settings → Appearance". 
4. Open the Insights tab from "My Site → Stats".
5. Tap the "View more" button on the "Total Subscribers" card.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/23443
