### ISSUE TITLE
The site search functionality does not work in the site picker

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#23209]
### Expected behavior
The user is able to search sites in the site picker

### Actual behavior
The site search functionality does not work

https://github.com/wordpress-mobile/WordPress-iOS/assets/304044/e40f65c1-2284-42d8-81e0-ad7434ca1091

### Steps to reproduce the behavior
1. Open the site picker
2. Type on the search field
3. Press search
4. Notice that nothing happens

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
