### ISSUE TITLE
[WordPress] Cannot update Post body (only header changes publish)

### ISSUE THREAD

**Issue by alpavanoglu** [wordpress-mobile/WordPress-iOS#23206]
### Description
This issue is reported by a user on AppStore. I could not reproduce the issue. I'm creating this as a placeholder in case more such reports appear.

I think we can delete this issue if no other such reports occur by **July 15th 2024**.

### Expected behavior
- Post body to change after modifying the body and tapping "Update"

### Actual behavior
- Only header changes pass through. Body updates fail.

### Steps to reproduce the behavior
- I was not able to reproduce.

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
WordPress iOS v24.8

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
It was re-engineered in 23.9, so should no longer be the case.
