### ISSUE TITLE
The "Post Published!" pop-up overlaps the done button with the other options

### ISSUE THREAD

**Issue by antonis** [wordpress-mobile/WordPress-iOS#23208]
### Expected behavior
The "Post Published" pop-up sheet does not have overlapping action buttons on small screen devices

### Actual behavior
The "Post Published" pop-up overlaps the done button with the other options

![IMG_0224](https://github.com/wordpress-mobile/WordPress-iOS/assets/304044/88e0673b-aef4-42f4-89b4-e327e6152ba7)

### Steps to reproduce the behavior
1. Publish a post
2. Select "View" in the snack bar
3. Notice the overlap in the done button

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
