### ISSUE TITLE
PostSearchViewModel: Fatal: supplied item identifiers are not unique. Duplicate identifier

### ISSUE THREAD

**Issue by staskus** [wordpress-mobile/WordPress-iOS#23271]
Parent GitHub issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/21943
Sentry report: https://a8c.sentry.io/issues/1871799689/events/3dc5e9e3a40c4cc1a5e8047c67e5f905/?project=1438083
Last seen: 24.8

> Fatal: supplied item identifiers are not unique. Duplicate identifiers: {(
    WordPress.PostSearchViewModel.ItemID.post(0x8a43f53697eaf478 <x-coredata://5C3E8B10-BFB8-4E92-8057-BB5538A47B77/Post/p345>)
)}

There's also this issue [grouped together on Sentry](https://a8c.sentry.io/issues/1871799689/events/863d1fa3ec22454ea3670bdcde1e8ea6/?project=1438083):

> NSInternalInconsistencyException
Invalid update: invalid number of rows in section 0. The number of rows contained in an existing section after the update (11) must be equal to the number of rows contained in that section before the update (0), plus or minus the number of rows inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out). Table view: <UITableView: 0x1050f1800; frame = (0 0; 0 0); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x28130a160>; backgroundColor = <UIDynamicSystemColor: 0x28143f7c0; name = systemBackgroundColor>; layer = <CALayer: 0x280025260>; contentOffset: {0, 0}; contentSize: {0, 40}; adjustedContentInset: {0, 0, 0, 0}; dataSource: <WordPress.PostListViewController: 0x1051a1800>>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by staskus** [comment]
Closing as duplicate of https://github.com/wordpress-mobile/WordPress-iOS/issues/23263
