### ISSUE TITLE
Reader bug: Navigating back to a post detail in modal context removes the dismiss icon

### ISSUE THREAD

**Issue by dvdchr** [wordpress-mobile/WordPress-iOS#23309]
### Expected behavior
The `v` icon on the navigation bar (to dismiss the modal) should remain visible after navigating back from another post.

### Actual behavior

In the post detail, tapping any posts from the 'More from {blog}' presents that post in a modal context. Tapping another post from the 'More from {blog}' section pushes a view onto the navigation stack. When navigating back, this removes the `v` icon on the left side of the navigation bar, which dismisses the modal.

<img width="394" alt="Screenshot 2024-06-05 at 15 46 51" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/8c29b31a-cb85-442c-a76a-fa6505ea7b79">

### Steps to reproduce the behavior

1. Navigate to Reader and open any post.
2. Scroll down to the 'More from {this blog}' or 'More on WordPress.com' section.
3. Tap on any post. The should show that post in a modal context. 
4. Scroll down to the 'More' section again, and tap any post.
5. Tap back.
6. 🔎 Observe that the dismiss icon (`v`) is missing.

Here is a video:

https://github.com/wordpress-mobile/WordPress-iOS/assets/1299411/7964deec-5263-4afc-96fd-4aa9fc835107

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
The posts are no longer displayed in modals, and this issue no longer appears. Closing.
