### ISSUE TITLE
Jetpack App - Blog Post Word Count

### ISSUE THREAD

**Issue by jromales** [wordpress-mobile/WordPress-iOS#23341]
### Expected behavior

The user reported that they used to see the word count feature immediately when clicking on three dots in a post editor. 

![Screenshot 2024-06-11 at 4 34 36 PM](https://github.com/wordpress-mobile/WordPress-iOS/assets/89536719/6860be2f-21ed-4af9-9fb2-baec7dccba20)

### 
Actual behavior

Clicking three dots does not immediately show the feature from the drop-down: 

![Screenshot 2024-06-11 at 4 35 54 PM](https://github.com/wordpress-mobile/WordPress-iOS/assets/89536719/84fb57f8-4201-4483-8ae2-8a8d4e19960e)

When I tested this, the feature only showed up after I tried to add new blocks in the editor. 

### Steps to reproduce the behavior

1. Go to Jetpack app using iPhone with latest iOS version.
2. Select a site.
3. Go to Posts and select a post to edit.
4. Click the three dots at the top right of the editor. The feature will not appear.
5. Add new blocks in the editor.
6. Click the three dots again at the top right and the feature will appear. 

##### Tested on iPhone 14 Pro Max, iOS 17.5.1, Jetpack iOS 25.0

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Thanks for reporting it, @jromales. The issue is [fixed](https://github.com/wordpress-mobile/WordPress-iOS/pull/23347) with a target release date 25.1.
