### ISSUE TITLE
Site picker not syncing

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23346]
### Steps to reproduce the behavior

- Get your account added to a new site (I added myself as an Editor)
- Open the app with a cached site list
- Open new Site Switched

### Expected behavior

- The new site shows up when I open the site picker
- If the site doesn't show up immediately, you can use pull-to-refresh to update it

### Actual behavior

- The new site is never showing up
- No PTR

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

`trunk`

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Fixed in the redesigned version of the picker.
