### ISSUE TITLE
Show disclaimers about unsupported features on a private site

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23373]
The media screen should have the following disclaimer:

<img width="1266" alt="Screenshot 2024-06-18 at 3 41 34 PM" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/9f0832ee-f8ad-46bb-ba03-cafe285f46e2">

When you switch to a "private" mode in Site Settings, it should also inform the user about the limitations of this mode.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Update: this has been largely fixed, and this recommendation no longer applies – closing.
