### ISSUE TITLE
Editing Interface Appears Blank on iPad OS 17.5.1 in Jetpack App and Browser

### ISSUE THREAD

**Issue by bizanimesh** [wordpress-mobile/WordPress-iOS#23413]
### Expected behavior

When accessing the website [https://elnavegante.eu](https://www.elnavegante.eu) on an iPad Pro using the Jetpack App or a web browser, the content should display correctly and be fully editable in the editing interface.

### Actual behavior

The website displays correctly when viewed normally. However, when accessed for editing through the Jetpack app or browser-based editor in iPadOS, the content appears almost blank, making it impossible to manage the site effectively.

### Key Details:

- **Device:** iPad Pro (iPad OS 17.5.1)
- **Browsers Tested:** Safari, Firefox, Firefox Focus
- **Other Devices Affected:** Issue occurs on iPads and iPhones as well.
- **Connections Tested:** Both Wi-Fi and cellular connections

### Troubleshooting Steps Taken:

- Cleared browser and DNS cache.
- Restarted devices.
- Used both Wi-Fi and cellular connections.

Related Ticket: 8445774-zd-a8c

If further information is required, please let us know.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by bizanimesh** [comment]
I investigated the issue again and found that it was not an actual issue. Some sections of the homepage are being controlled by the "Customizer" option, which means those will not appear in the page editor in the browser or the app.
