### ISSUE TITLE
Compliance popover fails to save settings and dismiss

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23416]
### Expected behavior

- The popover is dismissed

### Actual behavior

- The popover is not dismissed

**Workaround**: Tap "Go to Settings"

### Steps to reproduce the behavior

- Install the app for the first time
- Login with a country with GDPR 
- Add a self-hosted site
- Verify that a compliance popover is shown
- Tap "Save Settings"

https://github.com/wordpress-mobile/WordPress-iOS/assets/1567433/6ca65dd6-d239-418a-bbed-db03ee13cfce

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

trunk

Affects self-hosted sites in countries with GDPR.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
**RCA**

`CompliancePopoverViewModel` returns without doing anything if the wp.com accountId is not present: 
https://github.com/wordpress-mobile/WordPress-iOS/blob/2a20648fe23bdc50c279c793a166b2b883597a8f/WordPress/Classes/ViewRelated/EEUUSCompliance/CompliancePopoverViewModel.swift#L49

**Comment by geriux** [comment]
I've just encountered this, I'm not sure if it's related but once I managed to close this modal, the suggestion to "Save your login credentials" system modal was behind it.
