### ISSUE TITLE
Reply button is not visible when replying to a post from the Posts list.

### ISSUE THREAD

**Issue by tiagomar** [wordpress-mobile/WordPress-iOS#23410]
### Expected behavior
Reply to a post from Posts list should be possible.

### Actual behavior
After typing a message, the `Reply` button is not visible.

### Steps to reproduce the behavior
1. Posts list
2. Tap `...` menu on one of the posts
3. Tap `Comments`
4. Tap 'Reply to post' text field
5. Type a message
6. ❌ Reply button is not visible

<details><summary>In landscape mode, it's possible to see and tap part of the `Reply` button.</summary>
<img width="1200" alt="image" src="https://github.com/wordpress-mobile/WordPress-iOS/assets/42008628/60c367ad-bee3-4ffb-9b69-959e903be377">
</details>

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by bormansix** [comment]
Additional issues can be seen for landscape orientation on the iPhone.  The input field size is not recalculated after rotating the device to landscape.  On an iPhone 15, the dynamic island bumps against the input field:

<img src="https://github.com/wordpress-mobile/WordPress-iOS/assets/138129417/63f36aa2-051b-4651-b8e1-a094812df128" height=50% width=50%>

**Comment by kean** [comment]
Fixed in 25.5 https://github.com/wordpress-mobile/WordPress-iOS/pull/23710
