### ISSUE TITLE
[iPad] Add site action sheet is in the wrong place

### ISSUE THREAD

**Issue by crazytonyli** [wordpress-mobile/WordPress-iOS#23451]
This issue only appears on iPad.

![IMG_5584](https://github.com/user-attachments/assets/0ae7c041-2442-4c18-a338-06a2edc66ca4)

### Steps to reproduce the behavior

Tap the + button in the site switcher.

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

With the "site switcher redesign" feature flag on.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
