### ISSUE TITLE
The WordPress App is crashing on my iPad Pro when trying to open the sites tab in the sidebar.

### ISSUE THREAD

**Issue by Atten007** [wordpress-mobile/WordPress-iOS#23460]
### Expected behavior
I can open the sites tab in the sidebar from a WordPress website in the WordPress App on my iPad.

### Actual behavior
The App crashed and I couldn‘t open the sites tab.

### Steps to reproduce the behavior
1. Open the WordPress App.
2. Tap on the „Sites“ tab.
3. The app will crash.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
The main navigation was re-implemented on sidebar in 25.4 – closing.
