### ISSUE TITLE
Domains - TabBar has a transparent background in the detail screen when using Dark Mode

### ISSUE THREAD

**Issue by geriux** [wordpress-mobile/WordPress-iOS#23493]
In `trunk` the TabBar does not have a background when using the app in Dark Mode and accessing the Domain's detail screen.

### Expected behavior
The TabBar should have a background in Dark mode

https://github.com/user-attachments/assets/37ee1cef-1fb7-4d33-b769-1bd30da153ec

### Actual behavior
The TabBar has a transparent background

https://github.com/user-attachments/assets/89a3192e-2551-450e-81e0-0810dce29287

### Steps to reproduce the behavior
- Open the app
- Go to "Me" in the TabBar
- All Domains
- Open a Domain

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by geriux** [comment]
Hey @kean 👋  I know you've worked recently on some changes related to the navigation. Could this be related?

**Comment by kean** [comment]
Nice catch. Thanks for reporting it. I'll address it shortly.

**Comment by kean** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/23495.

Btw, I'm not sure how you got it to work because this page always redirects me to the standalone Safari because of this code:

```swift
            if !self.shouldAllowNavigation(for: url) {
                // Open URL in device browser then go back to Domain Management page.
                self.open(url)
                self.goBack()
            }
```

It was broken for me since the introduction, so its an existing bug.

**Comment by geriux** [comment]
> Btw, I'm not sure how you got it to work because this page always redirects me to the standalone Safari because of this code:

Interesting, I was able to access all of my domains 😅
