### ISSUE TITLE
Blaze icon not displayed

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23494]
<img width="320" alt="Screenshot 2024-08-13 at 11 59 44 AM" src="https://github.com/user-attachments/assets/99cf39f0-3cdc-4b3b-8335-8b21a8cfb881">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
It might be related to https://github.com/wordpress-mobile/WordPress-iOS/pull/23471.
