### ISSUE TITLE
Automattic About not showing icons

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23502]
Since the library was updated from version 1.1.2 to 1.1.4, it is no longer showing the app icons:

<img width="320" alt="Screenshot 2024-08-16 at 9 00 40 AM" src="https://github.com/user-attachments/assets/cebb6d75-ea91-4369-bb0d-d8ee1627a32a">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by crazytonyli** [comment]
Strange. I used the latest trunk branch and can see them in simulators.

<img width="936" alt="Screenshot 2024-08-19 at 9 27 26 AM" src="https://github.com/user-attachments/assets/179205f1-80a1-4183-97c6-bf27a05f88dd">

**Comment by jkmassel** [comment]
@kean are you still seeing this?

**Comment by kean** [comment]
No, I think it can be closed.
