### ISSUE TITLE
User Feedback: Support for Footnotes Block in Mobile App

### ISSUE THREAD

**Issue by alinclamba** [wordpress-mobile/WordPress-iOS#23524]
The [Footnotes block](https://wordpress.org/documentation/article/footnotes-block/) is currently not supported in the Jetpack mobile app for iOS. [Here's the list](https://apps.wordpress.com/support/mobile/posts-and-pages/supported-blocks-in-jetpack-and-wordpress-mobile-apps/) of currently supported blocks. 

A user has requested the ability to add and edit footnotes directly from the mobile app, similar to how they can on the web version.

Requested here: 8659443-zd-a8c

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
I'd appreciate if "add block" reports could be consolidated in a single issue. Blocks are no longer going to be added one-by-one.

**Comment by jkmassel** [comment]
This should be addressed by the new experimental editor – it'll support all core blocks

**Comment by alinclamba** [comment]
Givne that this will be addressed by the new editor, I think this issue can be closed.
