### ISSUE TITLE
When posting a comment, my avatar sometimes turn to other things

### ISSUE THREAD

**Issue by dzver** [wordpress-mobile/WordPress-iOS#23548]
### Expected behavior
I should always see my own avatar

### Actual behavior
I sometimes see the default gravatar or the avatar of the previous person who posted a comment

### Steps to reproduce the behavior
Post comments until you see it. It doesn't happen very often so the issue might not be the easiest to reproduce.

Both Veselins are me with another avatar
![IMG_9036](https://github.com/user-attachments/assets/1693617d-a0af-4d70-a80f-878f91dffdf5)
![IMG_9035](https://github.com/user-attachments/assets/51fd0f59-bf38-4310-846c-df3685348167)

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
Jetpack iOS, iPhone 15 Pro

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Fixed in the upcoming 25.4.
