### ISSUE TITLE
The avatar blinks when liking a post in the Reader

### ISSUE THREAD

**Issue by dzver** [wordpress-mobile/WordPress-iOS#23546]
### Expected behavior
Avatars should not blink

### Actual behavior
Avatars sometimes blink

There's something wrong with avatars, it's not only that they blink but they're also sometimes missing or incorrect. I've seen all kinds of faces instead of mine. However, this a report for the blinking behavior.

### Steps to reproduce the behavior
1. Use Dark Moder
2. Follow 20-30 sites and start liking their posts
3. You'll notice that most of the times avatars blink when you like but not always

https://martechp2.wordpress.com/wp-content/uploads/2024/09/rpreplay_final1725389293.mp4

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

Jetpack iOS, iPhone 15 Pro

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Fixed in the upcoming 25.4.
