### ISSUE TITLE
Notifications, VoiceOver: screen reader detects useless images

### ISSUE THREAD

**Issue by elettrona** [wordpress-mobile/WordPress-iOS#23553]
What happens: when focusing the "notifications" tab in JetPack or WordPress mobile app, it no longer shows notifications one after another. But before and after every notification there are at least 2 or 3 unlabelled images.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jkmassel** [comment]
Thanks for letting us know @talksina!

We've resolved this, and the fix will be part of the next release (should come out early October).

Please let us know about any other issues you come across – we'd be happy to resolve them!
