### ISSUE TITLE
Unable to set Publish Date in IOS App (see also #23369)

### ISSUE THREAD

**Issue by 4milesmax** [wordpress-mobile/WordPress-iOS#23562]
### Expected behavior

Set future publish time & date via the IOS App

### Actual behavior

It is possible to set the date and time however there appears no way to save the date & time

### Steps to reproduce the behavior

<img width="572" alt="image" src="https://github.com/user-attachments/assets/be665406-737c-4446-bcff-95154fce7fea">

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

ipad Pro running IpadOS 17.6.1 Jetpack for Wordpress 25.3

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
> It is possible to set the date and time however there appears no way to save the date & time

Hey 👋 
You should be able to save by tapping "Back", which is consistent with the rest of the forms in the app. If this doesn't work, please, describe the steps to reproduce an issue. Thank you 🙇

**Comment by 4milesmax** [comment]
I tried exactly this process several times without success however I left the scheduler screen open with the desired date and time set and hit ‘Back’ when you responded and it worked. 

By all means close this ticket, if I have the problem again I will re-test and share my results via a new ticket.  

Thanks for the quick response.
