### ISSUE TITLE
Stats pages are not updated when returning to the app

### ISSUE THREAD

**Issue by crazytonyli** [wordpress-mobile/WordPress-iOS#23604]
### Expected behavior
Comments and other content on the Stat page is refreshed when the app is brought back to foreground.

### Actual behavior
It is not refreshed.

### Steps to reproduce the behavior

1. Launch the app and go to a site's Stats page.
2. Stay on the "Traffic" tab.
3. Go to device's home screen.
4. Go to a web browser and add a comment to a post in the test site.
5. Open the app without interacting with the app.
6. Observe the comment count displayed on the "Traffic" tab.

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

**Please ensure the issue is fixed on both iPhone and iPad.**

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
