### ISSUE TITLE
Push notifications are not working for new orders

### ISSUE THREAD

**Issue by alinclamba** [wordpress-mobile/WordPress-iOS#23610]
### Expected behavior

I have a WooCommerce shop on my Jetpack-connected site. I enabled notifications for orders on my phone at https://wordpress.com/me/notifications:

![Uui4Fp.png](https://github.com/user-attachments/assets/f12a24ff-a1b3-43ba-b8f2-7f4a2e87b522)

When I place a new order, I don't get push notifications on my iPhone even if I can see the notification:

![yQ8fPr.png](https://github.com/user-attachments/assets/4a0aeffa-3788-4c9e-92c8-20e91a85eabd)

Initially reported here: 8725931-zd-a8c

##### Tested on iOS 17.7 with Jetpack iOS 25.3 and on Android 12 with Jetpack 25.2.1 (1444)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jkmassel** [comment]
This is actually deliberate – if they want push notifications for orders, they should probably use the WooCommerce app.
