### ISSUE TITLE
Notifications: issue with a clear navigation bar on scroll

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23622]
The navigation bar should not be transparent as you scroll.

![4CD2DEA9-2933-4D39-BE1E-800170520EA5_4_5005_c](https://github.com/user-attachments/assets/3d70e0e0-5014-42fe-aeab-b5f3c3e686e9)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/23593
