### ISSUE TITLE
Unable to reply and comment

### ISSUE THREAD

**Issue by LesleyScoble** [wordpress-mobile/WordPress-iOS#23620]
Unable to reply and comment on my Jetpack app. Please advise and assist.
Many thanks,
Lesley Scoble

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by LesleyScoble** [comment]
Thank you. The problem has gone on for a while. I’ve troubleshooted by uninstalling the app and reinstalling, but the fault still persists.

**Comment by kean** [comment]
Hey Lesley, thanks for reporting the issue!

> Unable to reply and comment on my Jetpack app.

I just wanted to clarify if there is no "reply" button, or are you seeing an error message after sending a reply?

There is a potentially related UX issue https://github.com/wordpress-mobile/WordPress-iOS/issues/22839 where for posts with closed comments, you can't see the "Reply" button, but there is no message in the app about the comments being closed.

**Comment by kean** [comment]
There is no reply in Notifications on iPad:

<img width="1316" alt="Screenshot 2024-10-28 at 11 31 39 AM" src="https://github.com/user-attachments/assets/a0983b52-1af9-442f-9b5e-1bccd428d0ca">
