### ISSUE TITLE
Post details inconsistently displayed with [...]

### ISSUE THREAD

**Issue by dzver** [wordpress-mobile/WordPress-iOS#23638]
### Expected behavior
When clicking the post details, I should see either the post or the cropped version consistently. If cropped version appears, there should be a link to the full version.

### Actual behavior
I sometimes see a cropped post ending with [...], and sometimes see the real one. The cropped one has no link to the full one.

### Steps to reproduce the behavior
1. Subscribe to the site https://mydelarosa.com/
2. In the reader, click a post - cropped version appears. 
3. Cropped version has no link to the full version
4. Then click the site, and click the post again - full version appears

https://github.com/user-attachments/assets/35185809-854b-4be7-8ffe-7e87942a0389

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by tiagomar** [comment]
I spent some time trying to understand this issue and here are my findings:

* When [...] happens, we don't display the "Visit Inspirations with De La Rosa for more/the full post." on iOS as we do for Android and Web.

| iOS | Android | Web |
| - | - | - |
| <img width="150" src="https://github.com/user-attachments/assets/fd53e25f-714e-45c5-9270-38cc8ae938f3"> | <img width="150" src="https://github.com/user-attachments/assets/3c170fb8-7f6f-4194-93ba-0d2f34ec9bb8"> | <img width="400" src="https://github.com/user-attachments/assets/bc369e70-f861-42a0-aa28-c865a23e9547"> |

* Only on iOS, after subscribing to the blog I ended up with two items in `Filter by blog` list, one of which has a trailing `/`. Filtering by one or the other determines whether the full post or the cropped version is displayed.

| `Filter by blog` list | Filtering by `https://mydelarosa.com/` | Filtering by `https://mydelarosa.com` |
|--------|--------|--------|
| <img width="220" src="https://github.com/user-attachments/assets/07ed2671-df43-40e1-84c8-d0d43d169866"> | <img width="220" src="https://github.com/user-attachments/assets/d72e52dd-3118-48f8-ba83-07b9ed07e400"> | <img width="220" src="https://github.com/user-attachments/assets/5bd537b3-0cd5-4e9c-adeb-d42eff0826eb"> |

**Comment by dzver** [comment]
These findings are even more unexpected than the original report.

**Comment by kean** [comment]
> Only on iOS, after subscribing to the blog I ended up with two items in Filter by blog list, one of which has a trailing /

😆 

Thanks for the investigation, Tiago. I'm working on this area right now, and I added this defect to my list.

**Comment by kean** [comment]
> Only on iOS, after subscribing to the blog I ended up with two items in Filter by blog list, one of which has a trailing /

This is fixed in the upcoming release (25.5)

**Comment by kean** [comment]
Going back to the original issue, this is how these posts are rendered on wp.com:

<img width="600" alt="Screenshot 2024-11-20 at 4 10 13 PM" src="https://github.com/user-attachments/assets/885bbc6f-a2c6-40f8-9eb1-fbf5d21dc795">

**Comment by kean** [comment]
I've added an implementation similar to the web, so both issues will now be fixed.

<img width="320" alt="Screenshot 2024-11-21 at 4 03 40 PM" src="https://github.com/user-attachments/assets/7d4def1e-e61d-4966-a76c-5ae39df917f0">
<img width="320" alt="Screenshot 2024-11-21 at 4 03 43 PM" src="https://github.com/user-attachments/assets/2737f648-4496-497d-baf0-0e40fb441487">
