### ISSUE TITLE
iPad: "New in Reader" is showing old data and is not updated for iPad changes

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23650]
This needs to be gone. We also don't need this dedicated view for announcements anymore. We'll either user a global announcement or TipKit if someting important comes up.

![IMG_0110](https://github.com/user-attachments/assets/525828fc-0948-43ec-821a-6004c7925d1c)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
