### ISSUE TITLE
Add support for opening detail for individual posts in Stats / Authors 

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23684]
### Steps to reproduce the behavior

- Open Stats / Traffic
- Scroll to Authors
- Expand one of the sections (authors)
- Tap on one of the posts

8910334

### Expected behavior

You can see the post details

### Actual behavior

Nothing happens

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
