### ISSUE TITLE
Editor closes after moving the app to the background

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23686]
### Steps to reproduce the behavior

- In wpios, go to Posts and open a post for editing
- Switch to another app
- Return the to the wpios app

### Expected behavior

- The editor is still on the screen

### Actual behavior

- The app is back to the home page

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]

25.4

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
**RCA**: [workaround](https://github.com/wordpress-mobile/WordPress-iOS/pull/23608) added for partial split-view support (was added too late in the game). It's probably best to remove it entirely until we have a sound architecture that can support it.

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
