### ISSUE TITLE
Update the share sheet to copy only the URLs

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23685]
### Steps to reproduce the behavior

- Open post details in the Reader
- Tap "Share" 
- Share in Messages

### Expected behavior

- The new message contains a preview of the post automatically generated by the system. The preview has a title and shows part of an excerpt.

### Actual behavior

- The new message contains a preview, but it also shows a title and a cut-off part of the excerpt (you see the title and the excerpt twice)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Review other share sheets in the app.

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
