### ISSUE TITLE
Layout issue with a No Sites empty state view

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23691]
Layout issue with the empty state view (should be wider, buttons should be one liners)

![authenticated_image](https://github.com/user-attachments/assets/19bf0ff4-35b8-4163-a5a5-e8438761a942)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by kean** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/23755
