### ISSUE TITLE
Animation glitch when tapping Share in Reader

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23694]
- Open the post details
- Tap "Share" in the navigation bar

Observers result: navigation bar buttons jump.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
