### ISSUE TITLE
dotCom sites are not appearing in the Share Sheet

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23707]
### Expected behavior

The site lists shows all your sites

### Actual behavior

The site lists shows only self-hosted sites connected to Jetpack

### Steps to reproduce the behavior

- Open Posts
- Tap "Share" on one of the posts and select the "Jetpack" app

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by dcalhoun** [comment]
A few users have reported this issue: 

* 8931559-zd-a8c
* 8931850-zd-a8c

**Comment by dcalhoun** [comment]
This appears to have been implemented intentionally: 

* https://github.com/wordpress-mobile/WordPress-iOS/pull/16140
* https://github.com/wordpress-mobile/WordPressKit-iOS/pull/375

My best guess is that, given the 2021 date that is in close proximity to the original Jetpack app launch, the intention was to filter the Jetpack app's sites to Jetpack sites only as a distinguishing attribute from the WordPress mobile app. That timeframe predates any efforts to position the Jetpack app as an app suited for _all_ WordPress sites—WordPress.com or self-hosted. 

I intend to research this further and open a PR addressing this unexpected behavior for the present.
