### ISSUE TITLE
Stats: Bar graph colors mismatched across light and dark modes

### ISSUE THREAD

**Issue by twstokes** [wordpress-mobile/WordPress-iOS#23709]
### Expected behavior
- Shades of green (not blue) when in Jetpack
- Not to mix blue and green

### Actual behavior
| Light | Dark
| - | - |
| ![iOS-Light](https://github.com/user-attachments/assets/0c6831e4-8d71-4a13-9438-aceece337b48) | ![iOS-Dark](https://github.com/user-attachments/assets/39e2b706-6b3b-415e-8cc6-afb479f12fb8) |

### Steps to reproduce the behavior
In the Jetpack app go to Stats and toggle light / dark modes.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
