### ISSUE TITLE
Opening the reader tab  "freezes" the app on iPad, Jetpack app

### ISSUE THREAD

**Issue by chatoxz-wp** [wordpress-mobile/WordPress-iOS#23728]
### Expected behavior
Open the "read" tab and the "recent" without freezing the app.

### Actual behavior
The application stops working and does not respond

### Steps to reproduce the behavior
On an iPad, access the Jetpack app and select "reader." 
They also mentioned the "recent" tab freezing the app. I will confirm the exact steps to reproduce with the user.

They are using an iPad Air 3rd generation
iOS version 18.0.1  
Jetpack version 25.4.1 

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
I could not reproduce this on Android 14, Device Moto G5-2024, and Jetpack 25.4

Ticket 8944609-zd-a8c

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Hey, thanks for the report. This issue is tracked in https://github.com/wordpress-mobile/WordPress-iOS/issues/23652, so I'm going to close this one as a duplicate.

**Workaround**: disable "Reduce Motion" in "Accessibility" / "Motion" in the Apple Settings app.
