### ISSUE TITLE
Missing background in the notification permissions prompt

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23772]
<img width="456" alt="Screenshot 2024-11-05 at 3 56 44 PM" src="https://github.com/user-attachments/assets/b394fe86-a910-4692-9c24-f775f8e12606">

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Not sure how I was able to reproduce it. It looks OK now in `trunk`.

<img width="320" alt="Screenshot 2024-11-06 at 2 14 20 PM" src="https://github.com/user-attachments/assets/ca8ab437-92f5-444e-a4e9-0df0513c7c10">
