### ISSUE TITLE
Changing site settings creates an infinite request loop

### ISSUE THREAD

**Issue by dcalhoun** [wordpress-mobile/WordPress-iOS#23787]
### Expected behavior
Updating a single setting should result in a single `POST` request. 

### Actual behavior
Updating a single setting results in a never-ending stream of `POST` requests. 

### Steps to reproduce the behavior
1. Set up your device so that you can monitor network traffic—e.g., send device requests through Charles Proxy. 
1. Navigate to _My Site_. 
2. Tap _More_. 
3. Scroll down and tap _Site Settings_. 
4. Scroll down to and tap _Discussion_. 
5. Toggle _Allow Comments_.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by dcalhoun** [comment]
From debugging this, it appears the persist settings [guard clause](https://github.com/wordpress-mobile/WordPress-iOS/blob/9f88062477f39d98f79c61fd285b8275636a404c/WordPress/Classes/ViewRelated/Blog/Site%20Settings/DiscussionSettingsViewController.swift#L72-L74) is insufficient. Settings are persisted anytime the [context changes](https://github.com/wordpress-mobile/WordPress-iOS/blob/9f88062477f39d98f79c61fd285b8275636a404c/WordPress/Classes/ViewRelated/Blog/Site%20Settings/DiscussionSettingsViewController.swift#L93), which then results in the context changing again. The guard clause needs to be more robust to ensure an infinite loop is not created when the settings object is changed.
