### ISSUE TITLE
Append "+testing" to feedback form email for Automatticians

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-iOS#23794]
From Zendesk:

> Attempts to submit requests with a staff member role (admin, agent, etc.) identity will fail by design. Apologies for any confusion around this behavior.

The end result is that HEs are unable to test the feedback form. According to Zendesk, a potential workaround for this is to programmatically append "+testing" when the feedback form is submitted from an @automattic.com or @a8c.com email address.

**Update:** This change should be made for all Zendesk ticket creation, not just the support form.

[Related Android issue](https://github.com/wordpress-mobile/WordPress-Android/issues/21449)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
