### ISSUE TITLE
iPad: Open posts in main navigation area when accessing them from the Notifications popover

### ISSUE THREAD

**Issue by kean** [wordpress-mobile/WordPress-iOS#23883]
### Expected behavior

- Opens in the main navigation area (tech note: user Reader navigation paths)

### Actual behavior

- Opens in the popover itself (not useful)

### Steps to reproduce the behavior

https://github.com/user-attachments/assets/d7481abc-75be-4991-afbf-a3e8b8efe66e

**Comment by dangermattic** [comment]
Thanks for reporting! 👍
