### ISSUE TITLE
Email stats not ordered by latest

### ISSUE THREAD

**Issue by dzver** [wordpress-mobile/WordPress-iOS#23910]
### Expected behavior
Going to Stats -> Emails -> View More produces a list of most opened emails

### Actual behavior
It should give a longer list of latest email

### Steps to reproduce the behavior
1. Go to Stats -> Emails -> View More 
2. This is what I see and it's not very useful

!<img src="https://github.com/user-attachments/assets/219ebab5-1c86-43f8-9ddf-6cb5f3aa80c9" width="50%"/>

##### Tested on [device], iOS [version], Jetpack iOS / WordPress iOS [version]
iOS, iPhone 15

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
It seems pretty straightforward. The app and the web says "latest emails". The web sorts by `post_date` but the app does by `opens`. I [added](https://github.com/wordpress-mobile/WordPressKit-iOS/pull/824) `post_date` sorting option and fixes this issue in https://github.com/wordpress-mobile/WordPress-iOS/pull/23913.
