### ISSUE TITLE
Off by one in likes

### ISSUE THREAD

**Issue by dzver** [wordpress-mobile/WordPress-iOS#23911]
### Expected behavior
When liking a post and it has 5 likes, I should see 5 likes and 5 avatars.

### Actual behavior
I sometimes see 6 avatars and 5 likes, and sometimes see -1 likes.
<img src="https://github.com/user-attachments/assets/5766b5c5-21f3-4b9b-a650-6603fb039852" width="50%" />
<img src="https://github.com/user-attachments/assets/8abfeff6-08b3-40d0-84a1-6476aaf8e40c" width="50%" />

### Steps to reproduce the behavior
When browsing p2s, just like - it doesn't always happen but it happens. Choose posts with 1-5 likes.

The -1 like has a consistent path to reproduce:
- Like a post with 0 likes from the list of posts
- Click the individual post to read it, you'll see no likes present
- Unlike and like
- -1 appears

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
Hey, thanks for reporting it. I fixed it in https://github.com/wordpress-mobile/WordPress-iOS/pull/23912 and we'll ship in 25.6 (early Jan).
