### ISSUE TITLE
Support custom post statuses

### ISSUE THREAD

**Issue by MatthewEppelsheimer** [wordpress-mobile/WordPress-iOS#2420]
This is a feature request for self-hosted blogs. Plugins like EditFlow extend editorial workflow for posts and pages with custom statuses, beyond the standard "draft", "scheduled", "published", etc. 
### Current Behavior

The app is currently limited to only displaying pages and posts that have standard post statuses, and only allowing the user to set standard post statuses in post options. 

Illustrating with logged-in views from galacticpanda.com, here is the app's view of post list: 

![image](https://cloud.githubusercontent.com/assets/1035068/4290156/5620e30a-3db9-11e4-9ad1-804e987162c8.jpg)

… compared with the same site's post list viewed from wp-admin: 

![image](https://cloud.githubusercontent.com/assets/1035068/4290174/7e58a5ba-3db9-11e4-847e-749df9f51e32.jpg)

Note the "Status" column's values include "prompt" and "outline", which are custom statuses set for this site. 

Here's a wp-admin view of the post status selector: 

![image](https://cloud.githubusercontent.com/assets/1035068/4290293/65eeab86-3dba-11e4-839c-e574f7781e7b.jpg)

Again, this is due to EditFlow settings, but other plugins and/or theme customizations can accomplish the same thing.

… compared with the same site's post edit > options > status control view:

![image](https://cloud.githubusercontent.com/assets/1035068/4290306/81c5b016-3dba-11e4-88b1-1538bbc2fa90.jpg)
### Requested Behavior

The app's post list shows all posts regardless of (custom) status), and displays the status for each post. The app's post edit > options > status view includes all custom statuses, and the app keeps the list of custom statuses synchronized with the site. 
### Notes
- I hope this is helpful. This is my first time posting a feature request to this repo. If I'm missing some protocols for feature requests, many apologies, and thanks in advance for pointing me in a better direction. 
- I'd gladly roll up my sleeves and submit a PR, but my Cocoa skills are about four years rusty. :smile:

**Comment by kurzee** [comment]
Graveyarding this one until we can properly support this via WP APIs.
