### ISSUE TITLE
iPhone 6 (not Plus), Swiftkey, Landscape, Wrong Keyboard Position

### ISSUE THREAD

**Issue by allendav** [wordpress-mobile/WordPress-iOS#2465]
With WP for iOS 4.3, iPhone 6 (not Plus), Swiftkey 3rd party keyboard, Landscape, the keyboard sits in the middle of the screen

![img_0008](https://cloud.githubusercontent.com/assets/1595739/4397454/3360b0e4-4443-11e4-8292-c7cf10a647c1.png)

With the built-in (iOS) keyobard, the keyboard sits at the bottom like it should.

![img_0009](https://cloud.githubusercontent.com/assets/1595739/4397460/45680332-4443-11e4-9251-be475a360488.png)

Note that the SwiftKey keyboard works fine in iOS Notes in landscape:

![img_0011](https://cloud.githubusercontent.com/assets/1595739/4397469/721d385c-4443-11e4-8e4a-c3badf1cfd11.png)

**Comment by rachelmcr** [comment]
I tested this again on an iPhone 6, iOS 9.1, app beta v. 5.8.0.20151204. In both portrait and landscape, the Swiftkey keyboard sits at the bottom of the screen as expected.

Screenshot in landscape:

![2015-12-15 15 09 47](https://cloud.githubusercontent.com/assets/8658164/11824253/337e0da0-a33e-11e5-9730-2c5a84a9e079.png)

I also tested with the visual editor disabled, and it works as expected there as well:

![2015-12-15 15 11 18](https://cloud.githubusercontent.com/assets/8658164/11824278/5588997e-a33e-11e5-9ffa-8a9e6b024918.png)

Closing as resolved.
