### ISSUE TITLE
Two Step Help Should Not Include Login Link

### ISSUE THREAD

**Issue by allendav** [wordpress-mobile/WordPress-iOS#2468]
If you attempt to log in to WordPress.com with an account for which 2 step is active, you will (correctly) receive the following warning:

![img_2685](https://cloud.githubusercontent.com/assets/1595739/4397576/278482bc-4445-11e4-81d8-199ee7a8b258.png)

If you tap on the Need Help? link, you'll see this support page:

![img_2686](https://cloud.githubusercontent.com/assets/1595739/4397579/33e4b360-4445-11e4-873a-cf309cdb1a91.png)

If you read what it says, and scroll down, you'll see a link to "Security tab"

![img_2687](https://cloud.githubusercontent.com/assets/1595739/4397583/46c0369e-4445-11e4-902b-6a3d62bf5cde.png)

If you click on that link, you're prompted to login:

![img_2688](https://cloud.githubusercontent.com/assets/1595739/4397584/51224e4c-4445-11e4-904f-53ef13584814.png)

At this point, if you give up trying to do it on your phone, and use your laptop to generate the one-time-password, and then type it into that login prompt, you'll successfully login with mobile Safari within the app, but you're not actually logged into the app.

You might even close the dialog on your laptop with the password.

You'll then eventually realize you're not actually logged into the app, and you'll have to generate another one time password.

Maybe that link should be suppressed in the in-app browser view, or a different page served without that link.

**Comment by rachelmcr** [comment]
I'm going to close this as worksforme, now that the app supports logging in with a 2FA code instead of requiring an app-specific password.
