### ISSUE TITLE
Notifications: Weird alpha when performing a PTR

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-iOS#2470]
It looks a little weird when you see the PTR spinner underneath the 'Today' header in Notifications:
![img_0038](https://cloud.githubusercontent.com/assets/789137/4407112/c9c61360-44c7-11e4-905b-8e3ad3cdeae7.PNG)

**Comment by jleandroperez** [comment]
This is no longer an issue in iOS 8, since there is a nice interactive animation that gradually shows the spinner.

@roundhill thanks for verifying this one!


![ptr](https://cloud.githubusercontent.com/assets/1195260/5599370/e17cfdb4-92a3-11e4-9bf2-708916d640fa.jpg)
