### ISSUE TITLE
Notifications: 'Manage' button shift

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-iOS#2476]
The 'Manage' button shifts slightly when returning to the notifications list:

https://cloudup.com/czuUa0W2pMW

**Comment by jleandroperez** [comment]
I'm reopening this issue because i'm not happy with the fix. Let's do some cleanup and:

- [ ] Initialize the Manage button in viewDidLoad
- [ ] Update NotificationsManager to a note gets posted when the Push Notifications settings change

Thanks!
