### ISSUE TITLE
App crashes when marking spam

### ISSUE THREAD

**Issue by kwight** [wordpress-mobile/WordPress-iOS#2478]
App consistently crashes on an iPad Air, iOS8, newest version, when marking a comment as spam. The crash happens as soon as you click on the first "Mark as spam" dialog from the More menu item.

May be iOS8 related, as it doesn't happen on an iPhone 4S still on iOS7.

**Comment by rachelmcr** [comment]
I'm closing this issue since the fix was merged quite a while ago; please reopen if the issue persists.
