### ISSUE TITLE
Resize Table Views for iOS 8

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2491]
Refactor any controllers with UITableViews so the tableviews are naturally the correct width on the iPad vs using the frame setting trick in WPTableViewCell. 

This is most important for table views with editable cells. 
- [x] Blog Settings
- [x] Comments list
- [ ] Notifications
- [x] Posts/Pages list
- [ ] Reader
- [x] Settings
- [x] Stats

**Comment by astralbodies** [comment]
@aerych Is this something you want to accomplish? Not sure if its made its way into other issues.

**Comment by aerych** [comment]
The post and pages lists will be take care of with #3506 and I'll take care of the reader when we refresh its UI. Everything else is up for grabs :)

**Comment by astralbodies** [comment]
What is your approach? No longer inherit WPTableViewCell?

**Comment by aerych** [comment]
> No longer inherit WPTableViewCell?

Yep.  I think we should consider `WPTableViewCell` deprecated. The technique it uses to achieve margins is unsafe and creates complications for things like swipe-to-delete.

> What is your approach?

I add an inner content view that is centered with a max width of 600 on the iPad. All the other subviews of a cell live inside it. Then I use a `hitTest` to [catch and ignore taps in the margins](https://github.com/wordpress-mobile/WordPress-iOS/blob/issues/3506-refresh-post-page-list-ui/WordPress/Classes/ViewRelated/Post/RestorePostTableViewCell.m#L28).  This lets us have a centered layout and keep the scroll bar flush right to the screen.  A con is you have to have a fully customized cell and can't use the default views.

**Comment by kurzee** [comment]
This is mostly done with the readability work, well covered in other issues/projects.
