### ISSUE TITLE
Add some hints as to what a more complex password is

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#2497]
If a user doesn't select a complicated enough password when creating an account they get the error message "Please try a more complex password". We should give them an example of what a more complex password is so they don't get stuck on this screen.

**Comment by koke** [comment]
Is #2632 enough to close this?
Also, dupe of #1831

**Comment by allendav** [comment]
Moving this to @astralbodies for reassignment

**Comment by astralbodies** [comment]
Closing this as it's duplicated and this is the younger issue.
