### ISSUE TITLE
Implement Dynamic Type

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-iOS#2506]
We should add support for Dynamic Type in the app. It would help with accessibility and the font readability on different screen sizes.

**Comment by diegoreymendez** [comment]
@astralbodies - This task feels like something we should split up in smaller tasks before tackling, since this will potentially affect all of our view controllers.

It also goes beyond the scope of what we can achieve in a single groundskeeping rotation, unless of course it's broken down a bit.

**Comment by astralbodies** [comment]
We could transform this into a GitHub Project because of its size :)

**Comment by elibud** [comment]
We are tracking this one here: https://github.com/wordpress-mobile/WordPress-iOS/issues/7068
