### ISSUE TITLE
Remove duplication when it comes to retrieving a WPAccount

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#2518]
Throughout the code we see this:

```
            AccountService *accountService = [[AccountService alloc] initWithManagedObjectContext:context];
            WPAccount *account = [accountService defaultWordPressComAccount];
```

Lets cut back on the duplication and make it simpler to get a WPAccount.

h/t @diegoreymendez

**Comment by kurzee** [comment]
This is a good one to also add a cacheing layer for not running a fetch request every time `defaultWordPressComAccount` is called.
