### ISSUE TITLE
Improve post purging on sync

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#2527]
Right now, two things happen:

- When posts sync, everything that's not in the server response gets purged (this usually means only the latest 40 posts stay)
- When the posts list appears, a sync is triggered

This leads to annoying side effects when managing older posts:

![posts-purge](https://cloud.githubusercontent.com/assets/8739/4540851/55f51226-4e0c-11e4-9f90-fc9635d45100.gif)

I think the original idea behind purging old posts was:

- Not storing every single post on the device wasting space
- If a post is not in a sync response, is it just old, or it's deleted?

Let's find a better way

**Comment by rachelmcr** [comment]
I tested this in the latest 5.8 beta and when I exit the editor (with or without saving changes), the posts list doesn't refresh. I remain at the same point in the list, at the old post I was editing.

I'm closing this issue as it looks like the annoyance is resolved. Please reopen if you see remaining issues that aren't resolved yet.
