### ISSUE TITLE
Adding app to Today before choosing a blog to source it requires reboot

### ISSUE THREAD

**Issue by allendav** [wordpress-mobile/WordPress-iOS#2543]
If when setting up Today for the first time, you, swipe down on the iOS home screen, go to Today, edit, add WP and THEN go to the WP app, Me, choose a blog with non trival stats, Stats, Today, then the WP "widget" will not appear in iOS Today.

Removing the WP app from iOS Today and re-adding it also does not help at this point.

Rebooting the iOS device is needed to get iOS Today to start display WP stats for the selected blog.

**Comment by tommi** [comment]
@allendav I'm unable to reproduce this with iOS 8.3, for me, the WP was in today. Can you retest with the latest iOS version?

**Comment by astralbodies** [comment]
I have a feeling that this is only happening with our private enterprise-signed binary and not the App Store build. Thanks for testing this @tommi. @allendav if you see it again let me know.
