### ISSUE TITLE
Row height during push controller animation shrinks

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#2558]
When selecting rows that push view controllers in Settings, the row heights shrink during the animation.  When popping back to the VC, it's back to normal.  I did a little bit of digging but can't find anything obvious.  All of the cells and UITableViewController are "out of the box" objects and aren't highly customized.  I don't see this happening elsewhere.  Possibly a side-effect of how we're modally presenting it?

![rowheight](https://cloud.githubusercontent.com/assets/373903/4575925/b37251dc-4fad-11e4-8cda-cedb67837f75.gif)

**Comment by allendav** [comment]
Moving this to @astralbodies for reassignment

**Comment by astralbodies** [comment]
I'm closing this since we dropped < iOS 9 and I can't reproduce any longer.
