### ISSUE TITLE
Reader: Action buttons present on posts from feeds/self-hosted sites

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2594]
The action buttons should be hidden for unsupported sites but are sometimes appearing.  They seem to be correctly hidden when viewed on the blogs I follow feed, but present when viewed via a tag or a list feed. 

Theory: potentially due to differences in site_ID between what was followed and what was consumed by the feed aggregator

**Comment by designsimply** [comment]
Continued at https://wpcom.trac.automattic.com/ticket/7240
