### ISSUE TITLE
Make default/primary site first in site selector & site lists

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#2599]
Since #2546 the concept of a default blog/site for an account exists.  Adjust the sort order of site lists so that the default site is at the top of the site selector and site listing under Me.  It might be good to put it in a separate section with a small gap under it to differentiate it from the rest subtly.

**Comment by koke** [comment]
Reopening this as primary blog still isn't first on site lists

**Comment by astralbodies** [comment]
I was about to check for this the other day and forgot. Thanks for reopening - it's probably one of the stabbiest things still in the app. :smile:

**Comment by astralbodies** [comment]
Reopening as this was reverted.
