### ISSUE TITLE
Update Login Prompt to use NUX

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#2625]
Title has it.

**Comment by rachelmcr** [comment]
The screen `WPcomLoginViewController` was nuked in https://github.com/wordpress-mobile/WordPress-iOS/commit/8b98f2ef89b2941d0630f1cbdc3cf0463320eb6a. I'm not sure what login screen is being used in this case now; is this still an issue?

**Comment by aerych** [comment]
Closing as its no longer an issue as pointed out by @rachelmcr
