### ISSUE TITLE
Heavyweight Migrations swizzle NSManagedObject's objectID

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#2637]
#### Scenario:
1. Fresh Install `tags/4.3` on a device.
2. Log into your wpcom account.
3. Connect a Jetpack site.
4. Print out the WPAccount entities, with their objectID's
5. Install `tags/4.4` on top of 4.3

#### Result:
WPAccount's objectID property will get swizzled. And thus, the defaultWordPressAccount will map a non wpcom account.

This will cause both the Reader and Notifications not to work, since they'll be grabbing a non wpcom token.

#### Fixes:
- [ ] Implement a one shot routine that will review the *Account* entities, and fix their mapping in the AccountService class.
- [ ] Review + fix the usage of `objectID`, so this never happens again.

/cc @sendhil + @koke + @astralbodies

**Comment by astralbodies** [comment]
This got fixed, right @jleandroperez?

**Comment by jleandroperez** [comment]
@astralbodies yes sir, closing this one, since it was effectively fixed in #2638.
