### ISSUE TITLE
Log on MixPanel Logout events

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#2646]
Log explicit logout events done by the user and also events that happen because we detected incorrect states on the API calls ( wrong or expired tokens).

This may help to find issues where users can't login or get logged out in the app.

**Comment by jstart** [comment]
@sendhil @SergioEstevao Would this be mixpanel logging or simperium, etc.?  Are there specific keys that are used between iOS and Android for these kind of logout events?

**Comment by jstart** [comment]
Or, on second thought, was this already done in 4.6 and just never got closed?

**Comment by sendhil** [comment]
@jstart this isn't in the app yet.
