### ISSUE TITLE
Jetpack connected site is prompted for credentials (again)

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2669]
To reproduce:

Sign in to the app with a wpcom account. 
Add a self-hosted site that is connected to Jetpack with a different wpcom account.
Go to Me > Self-hosted Site > Site Settings > Configure 
You'll be prompted to connect to Jetpack, even tho its already connected.  The form will be pre-filled with the wrong screen name. 

![ios simulator screen shot oct 28 2014 1 31 54 pm](https://cloud.githubusercontent.com/assets/1435271/4815274/6cc77546-5ed5-11e4-9313-6a305a35634b.png)

**Comment by koke** [comment]
If Jetpack uses REST (#3627), this doesn't happen, #3141 happens instead.
Anyway, that screen will be gone in #3628
