### ISSUE TITLE
Notifications & reader should continue to function after signing out of wpcom when a self-hosted+Jetpack site exists

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2670]
Not sure if this is more of an auth issue than a Jetpack issue.  To reproduce: 

Sign into the app with wpcom account.
Add a self-hosted site connected to Jetpack with a different wpcom account. 
Sign out of the first wpcom acct so you just have the self-hosted site. 
Notice that:
- the reader is logged out
- notifications shows a prompt to connect to Jetpack
- stats are still displayed correctly. 

So the app is in this weird state now.  I would expect that the reader and notifications would just use the wpcom acct connected to Jetpack and intelligently communicate this to the user.

**Comment by koke** [comment]
I think #3628 will take care of this
