### ISSUE TITLE
Show posts you've authored as contributor in post list

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS#2680]
It appears that if marked as "contributor" on a post, we're not displaying any posts in the post list. We should be displaying posts (only that) user has authored.

In wp-admin, when you're a contributor, posts you've authored appear in post list:
![](https://cloudup.com/infnW5CZEbW+)

View on mobile app for the same blog - no posts appear:
![](https://cloudup.com/iiOLWFZZ7eS+)

**Comment by rachelmcr** [comment]
I tested in 5.7 (stable release) and as a contributor on a site I can see my draft and pending posts but not my published posts. When a post is approved and published by a site admin, it disappears from my Draft list but never appears on my Published list. I confirmed that those posts are returned by the REST API for the contributor user.

**Comment by aerych** [comment]
@rachelmcr for due dilligence, it was missing from both the "Everyone" and "Only Me" post list filters?

**Comment by rachelmcr** [comment]
I don't see post list filters at all on that site where I'm a contributor. Here's a screenshot:

![2015-11-30 18 36 28](https://cloud.githubusercontent.com/assets/8658164/11480835/a416f260-9791-11e5-8aa8-2373a336bf86.png)

**Comment by rachelmcr** [comment]
Adding these notes from #3915 so we don't lose track:

> A user with a contributor role can not edit posts, not even the ones they author. Since posts are requested from the wpcom REST API with an edit context, the list for a contributor is always empty.

> We should support displaying a contributor's posts with just "view" and "stats" options.
