### ISSUE TITLE
Support 2 step authentication

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#269]
We support 2 step authentication via app specific passwords, but unless the user knows that, the process is very confusing.

Login to WordPress.com using regular password:
![ios simulator screen shot oct 17 2013 12 28 13 pm](https://f.cloud.github.com/assets/8739/1350993/f9c8a510-3716-11e3-8bd6-eb365c51cac4.png)

If you login to a self-hosted, the Jetpack screen accepts the master password initially, but then stats don't work and further Jetpack screens won't accept the password:
![ios simulator screen shot oct 17 2013 12 28 50 pm](https://f.cloud.github.com/assets/8739/1350992/f9c42328-3716-11e3-8a07-a51c9b528fe9.png)

**Comment by jleandroperez** [comment]
We're gonna be implementing MFA support, both on Android and iOS.

I wasn't aware of this old ticket (sorry). Closing this one in favor of #3223 (which contains the updated UI designed by Dave).

Issue #1220 is still a blocker, we're also tackling that one.

Thanks gentleman!

**Comment by sendhil** [comment]
:dancers:
