### ISSUE TITLE
Support Publicize on posting

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#2698]
We should really be supporting WordPress.com's Publicize feature on new posts.  Not necessarily so much to add connections but to at least edit the slug and make users aware that we're hitting all the Publicize endpoints by default.

**Comment by jeremeylduvall** [comment]
Another user was looking for the ability to customize the messaging/publicize targets here:

https://twitter.com/jmcdonall/status/582625453900353536

Just logging so we can follow-up later!

**Comment by rachelmcr** [comment]
Another request for the option to add a custom message for the Publicize feature:

https://twitter.com/tvserieshub/status/628599755879395328

**Comment by dcoleonline** [comment]
> I think it could be good to also allow the user to enable/disable certain publicize targets. I know for myself I usually save a draft on mobile and publish from the web as I don't want all of my posts to hit all of my publicize connections.

A second request from 2731741-t

**Comment by astralbodies** [comment]
Oh yes, still one of my biggest wants.
