### ISSUE TITLE
Reconfigure Today Widget when current site is deleted from app

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#2746]
If a site is removed from the device (deleted from API side maybe?) the Today Widget remains in a configured state.  Reconfigure it so the new primary .com is chosen in its place.  Maybe do a sanity check upon launch for this as well.

**Comment by jstart** [comment]
Where do you think is the best place to notify the TodayExtensionService that a site has been removed?  What kind of sanity check would we need to do?  Can we check some sort of store or API to see if the site in group NSUserDefaults still exists?

**Comment by astralbodies** [comment]
@jstart Definitely we should remove the configured site for Today when a logout is performed on the main WordPress.com WPAccount. It's been a while since I've looked around the code (things have changed so quickly lately) but see if you can find where logging out is performed. Effectively if the user logs out it will (or should) revoke their OAuth2 token which will cause a 500 or 403 error in the widget and it might make itself disappear.

**Comment by hoverduck** [comment]
29Oct15 Bug Scrub

Verified this is still an issue.  I set the Today widget to display a site where I was only a user, not the owner, and then I removed my access.  The Today widget remained in place with the most recent data it has, but the site name disappeared after a while.

**Comment by rachelmcr** [comment]
I tested this issue again with the same steps as above. Immediately after removing the user's access to the site, the Today widget remained in place with the most recent data and the site appeared in the list of available sites in the app. However, after closing and reopening the app, the Today widget removed the information about the site, displaying the message "Please remove the widget and re-add it again."

Do we expect the widget (and app) to respond immediately to the user's access being removed, or is this behavior acceptable?

**Comment by rachelmcr** [comment]
I just retested this issue with the same steps as above (removing the user's access to the selected site) and verified that it is still an issue.

I also tested it by deleting the site used in the Today widget, and Today widget remained in place with the site's details even though the site immediately disappeared from the site list in the app.

Tested on iPhone 6, iOS 9.2, app v. 5.8.

**Comment by kwonye** [comment]
Also, changing the primary site doesn't change the site shown on the widget.
