### ISSUE TITLE
Add support for animated gifs. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2752]
Look into using a library like gifu to handle animated gifs without bumping into memory issues.  

See #2105 for some background.

**Comment by rachelsquirrel** [comment]
Another request for this from a user in HS:
https://automattic.helpshift.com/admin/issue/58090/

**Comment by theck13** [comment]
Another report from @m.

### Steps
1. Used Motion Stills to make a GIF.
2. Saved it to camera roll.
3. Added it via add image to a draft on wordpress.com.
4. A static, non-animated image (shown below) was embedded.

![img_0788](https://cloud.githubusercontent.com/assets/3827611/17869445/8151a9ea-6870-11e6-9553-5292f325839d.gif)

**Comment by kurzee** [comment]
To note, for supporting posting/uploading an actual .gif as  media, we would need an edge case handler for detecting that an image asset is indeed a .GIF data format and then maintaining that data.

In the past, one way to pull this off on iOS was reading the first three bytes of the raw image data from a picker image asset, checking for the beginning "GIF":

```
if (bytes[0] == 'G' && bytes[1] == 'I' && bytes[2] == 'F')
```

After detecting a GIF, we would then avoid rewriting or resizing that image data and just upload as is... maybe I'll just add this fix in myself 😄

**Comment by SergioEstevao** [comment]
@kurzee I had a look on this you don't need to look at that raw data you can simple check the UTI of the resource/file and compare it to "com.compuserve.gif". I have the code ready for this to go.

@aerych for you scenario inside the Reader did you have a look to this library: https://github.com/Flipboard/FLAnimatedImage it looks it could be easily be pluged in the reader for scenarios where a gif is detected and then we replace the uiimage for this flview.

**Comment by aerych** [comment]
Nice find!

**Comment by kurzee** [comment]
>simple check the UTI of the resource/file and compare it to "com.compuserve.gif"

That was particularly broken in iOS7, IIRC, but after testing your PR it looks iOS9 handles the detection perfectly. 👍

**Comment by rachelmcr** [comment]
I saved a GIF to my device and was able to upload and add it to a post, and it worked as expected. Very cool. :) However, it would be great if we could also support adding GIFs with these approaches:

- Sharing a GIF directly to the WordPress app (through the share extension). Right now, GIFs shared to the app (e.g. from the Giphy app) are added as a still image.
- Pasting a GIF directly into the app's editor. Right now, copying a GIF (e.g. from the Giphy app) and pasting it into the editor results in a still image.
- Adding GIFs from third-party keyboards such as Giphy Keys and Reboard.

More discussion about this here: https://make.wordpress.org/mobile/2016/10/12/call-for-testing-wordpress-for-ios-6-6/#comment-19220

**Comment by rachelmcr** [comment]
A recent app store review (4 stars) requested GIF support.

**Comment by kurzee** [comment]
>Pasting a GIF directly into the app's editor. Right now, copying a GIF (e.g. from the Giphy app) and pasting it into the editor results in a still image.

I've kept this one in mind with all of the recent work, I _think_ we'll be able to have this supported soon.

**Comment by apeatling** [comment]
Am I correct in stating that GIF insertion into Aztec has caused a regression here? When I insert a GIF into the editor, I do not see any animation.

**Comment by SergioEstevao** [comment]
Yes you are correct. Animated gif support is still not available in Aztec.

Enviado do meu iPhone

No dia 22 de out de 2017, às 04:37, Andy Peatling <notifications@github.com> escreveu:

**Comment by ScoutHarris** [comment]
@etoledom - did your animated gif work cover this issue?

**Comment by etoledom** [comment]
We added gif playback support to some key areas of the app:
- Post list.
- Post settings (featured image).
- Media Picker.
- Reader feed.
- Reader detail.
- Comments.

There is still some work to be done on importing gifs, we decided to work on it in an upcoming project.
So, mostly yes :)

**Comment by SergioEstevao** [comment]
We still don't support the display of animated GIF in the Aztec editor you can insert and upload them and the end result on the web will be animated, it's just that we don't show the animation in Aztec.

**Comment by bummytime** [comment]
@SergioEstevao @etoledom I see the Aztec repo has this issue: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/757

Could we either close this issue in favor of that one _or_ make a new, specific issue for animated gif display in Aztec here?

**Comment by SergioEstevao** [comment]
We can close this and keep the Aztec one.

**Comment by bummytime** [comment]
Thanks @SergioEstevao ! Closing this in favor of https://github.com/wordpress-mobile/AztecEditor-iOS/issues/757

🎉 🎈
