### ISSUE TITLE
App lets users add a site twice

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#2782]
If you add a site that's already set up in the app, the app would go through with the login/jetpack setup. It won't show it duplicated, but it should prevent the login.

When adding a site that has no Jetpack, this is OK as it will just return to the list and the blog will be there. It performs unnecessary authentication, but is not confusing to the user

When adding a Jetpack site, it will ask for the wp.com credentials (even if it's already added and set up correctly).

Ideally we'd skip the authentication and send the user to the blogs list, maybe point out where the blog is (#1466)

**Comment by rachelmcr** [comment]
I tested this with a Jetpack site, and it behaved the same as a non-Jetpack site — after I entered the self-hosted credentials, it returned to the blog list (not asking for wp.com credentials). However, I agree that it should prevent the login and ideally point out where the blog is in the blog list.
