### ISSUE TITLE
Sometimes new posts are duplicated in app

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#2804]
When you create a new post, it might appear on the posts list twice temporarily. What happens:

- New posts don't have an ID until the upload request finishes
- When you save a new post, the editor will dismiss and go back to the posts list
- When the posts list appear, it will sync posts. The result might include the new post if the request finishes before the upload request does

**Comment by meremagee** [comment]
Any takers on this one?

It's particularly evident for new users: https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/407

**Comment by sendhil** [comment]
Hmmm, @koke is out on Paternity leave right now but we'll try to get to the bottom of this. @meremagee  do you have consistent reproducible steps?

**Comment by aerych** [comment]
@bummytime and I have been chatting about an issue where edits to an existing post are lost, that we feel is a different symptom of this bug.  
What happens:
* edit an existing post and save.
* the save request is triggered meanwhile the user returns to the post list.
* the post list will attempt to sync in the background

The post list can finish its sync before the save request is complete and if the timing was right, the old version of the post will be resynced, losing the most recent edits until the user refreshes again.

**Comment by aerych** [comment]
Closed in #3432
