### ISSUE TITLE
Stats: "Top Posts and Pages" "Yesterday" shows Post Written Today

### ISSUE THREAD

**Issue by allendav** [wordpress-mobile/WordPress-iOS#2824]
There is something wrong with the Top Posts and Pages part of Stats (Me > {blog} > Stats.  I wrote a post today ("Seamless Donations For WordPress 3.3.0 - Important Update; Nov 19) and yet it appears under Top Posts and Pages when the section toggle filter is set to Yesterday (Nov 18, impossible):

![img_0531](https://cloud.githubusercontent.com/assets/1595739/5117374/5a907f32-7008-11e4-966d-16d6448e3c80.PNG)

When set to "Today", it says "No top posts or pages..."

I double checked and the WPCOM blog in question (allendav.com) timezone is set to Los Angeles, as is the iPad (Cupertino).  I also checked and the WPCOM REST API is returning the correct data for Nov 19 ( GET /sites/allendav.com/stats/top-posts?date=2014-11-19 )

**Comment by astralbodies** [comment]
@allendav Can you confirm if this is an issue with the redone stats?

**Comment by astralbodies** [comment]
Closing
