### ISSUE TITLE
Adding a Jetpackked site requires wpcom two step users to generate another app password

### ISSUE THREAD

**Issue by allendav** [wordpress-mobile/WordPress-iOS#2825]
If you use two step authentication on your wpcom account, which requires you to generate an app password itself, and then you later attempt to add a jetpackked self-hosted blog to the iOS app, you're required to generate yet another application specific password to enable Stats and Notifications:

![img_2922](https://cloud.githubusercontent.com/assets/1595739/5131281/27e5206c-70a6-11e4-8f5f-c09e8a492b39.PNG)

![img_2921](https://cloud.githubusercontent.com/assets/1595739/5131284/2b32730a-70a6-11e4-9c89-43a1bed8b24a.PNG)

**Comment by jleandroperez** [comment]
Closing this issue since it's no longer relevant (the app got 2FactorAuth support!).

Thank you both!
