### ISSUE TITLE
Tapping on a site under Me unexpectedly changes its blavatar size

### ISSUE THREAD

**Issue by allendav** [wordpress-mobile/WordPress-iOS#2832]
Before tapping on Allen Snook (little panda):

![before](https://cloud.githubusercontent.com/assets/1595739/5147867/3eef16be-716e-11e4-8aea-29b54155068f.png)

After tapping on Allen Snook (bigger panda!):

![after](https://cloud.githubusercontent.com/assets/1595739/5147869/43d88976-716e-11e4-9a3c-fcaf4aff6208.png)

Possibly similar fix is needed as was done for https://github.com/wordpress-mobile/WordPress-iOS/issues/2558 (not sure)

**Comment by rachelmcr** [comment]
I checked the blavatars before and after tapping on sites on the current My Sites tab, and they didn't change size. Closing this as works for me now.
