### ISSUE TITLE
Login button might be enabled even with an empty password

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#2844]
Minor issue, but there's a glitch in the way `WPWalkthroughTextField` works.

- Open the login form
- Fill out username
- Type a few characters in the password field
- Toggle the password visibility on and off
- Press backspace
- Password field is cleared, but sign in button is enabled

Another variant:

- Open the login form
- Fill out username
- Fill out password
- Tap on username field
- Tap on password field
- Press backspace
- Password field is cleared, but sign in button is enabled

I've checked and the delegate's `textField:shouldChangeCharactersInRange:replacementString:` is called with parameters as if only one character was being deleted, and `textFieldShouldClear:` isn't being called in this case.

I've seen some suggestions in [this SO thread](https://stackoverflow.com/questions/18604488/is-an-event-triggered-when-a-uitextfield-with-securetextentry-yes-is-cleared) to just use the delegate methods to trigger an async UI update, but I'm not sure what's the best option

**Comment by jstart** [comment]
@koke Toggling the password visibility calls setSecureTextEntry and setNeedsDisplay.  This briefly makes the password field resign responder.  So the next edit is affected by the default secure text entry behavior.  Doesn't seem like there is a way other than KVO to get notified about this secure entry deletion.

What we can do, is check the .isSecureEntry property on the text field and keep track of the toggledVisibility state. 
If secureEntry is true
and we toggledVisibility 
and the the immediate next replace delegate call is an empty string (or backspace event)
then disable the Sign In button by setting isPasswordFilled to NO.

Working on a proposed fix.  Does this sound reasonable?

**Comment by koke** [comment]
I can't reproduce this anymore, so closing it for now
