### ISSUE TITLE
New Jetpack login screen

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#2847]
We're adding WordPress.com user data to `wp.getOptions` in https://github.com/Automattic/jetpack/pull/1329. When that's available, show the username, email, and gravatar, and only ask users for their password.

![jp-manage-login](https://cloud.githubusercontent.com/assets/8739/5200673/78260a48-7568-11e4-84d9-f171f17769c3.png)

Even when user data isn't available, this new screen will correct a bunch of other issues, like adding a "forgot password" link, or in-app help

**Comment by kjellr** [comment]
I think the copy here could be a little softer- anything that "needs" my password sounds a little scary. How about something like:

> Login to WordPress.com to unleash the power of Jetpack Manage

Another minor note- I'd suggest making the avatar round to align with other avatars in the app + on WP.com.

**Comment by koke** [comment]
Closing this in favor of #3628. Might revisit this after that's done
