### ISSUE TITLE
Error replying to comment on self-hosted + Jetpack site

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#2894]
When I'm signed into my wpcom test site I'm seeing self-hosted sites connected to jetpack in my wpcom site list.  I can also add that self-hosted site via the add sites, and still connect it to Jetpack.  The result is I have an entry for the site under wpcom and self-hosted sections. 

If I choose the self-hosted entry, and try replying to a comment via the Notifications or Me tab, I see the following error. The cause seems to be that the self-hosted version is making the call to the REST API passing a blog ID of 0.

![ios simulator screen shot dec 8 2014 11 19 56 am](https://cloud.githubusercontent.com/assets/1435271/5345648/04f2d80a-7edf-11e4-95ba-a13da0d7ac79.png)

**Comment by aerych** [comment]
@koke @jleandroperez I think this issue can't happen anymore after some of our recent changes, yes?

**Comment by jleandroperez** [comment]
@aerych i've refactored that viewController (recently), but i haven't touched any of the service layer calls. However, i think @koke did upgrade the Jetpack API to REST.

Not sure, though, if that's enabled for everyone!

**Comment by koke** [comment]
I can't reproduce the error, but the site can still be added twice: #2782

**Comment by aerych** [comment]
Closing this one as fixed, since we can't repo and the double site situation is handled in a different issue.
