### ISSUE TITLE
Editing pages you can not add images

### ISSUE THREAD

**Issue by sandymcfadden** [wordpress-mobile/WordPress-iOS#2971]
When trying to edit a page with version 4.6.0.2 you do not get the option to add images.
Creating new pages seems to work no problem

![photo 2014-12-23 8 00 26 pm](https://cloud.githubusercontent.com/assets/1326294/5544491/86eabbb0-8ade-11e4-81b4-a88a92b48215.png)

**Comment by meremagee** [comment]
looks good now

**Comment by bummytime** [comment]
*now == release 4.7
