### ISSUE TITLE
Refactor WPAnalyticsTrackerMixpanel for updating email

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-iOS#2984]
Since we are [starting to store](https://github.com/wordpress-mobile/WordPress-iOS/pull/2977) `email` for default WordPress.com accounts, we probably don't need to do any checks for the existence of email in `WPAnalyticsTrackerMixpanel`. I wasn't absolutely sure about removing the whole logic for getting the user email so I haven't removed it in [that PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/2977). This might affect existing users somehow even though their accounts should have been setup by now. In any case I wanted to separate it just to make sure it's done properly.

@sendhil Could you take a look at this? You can let me know about the changes and I can handle it as well, if you prefer. Thanks!

**Comment by sendhil** [comment]
@oguzkocer  - I'll take a look. Thanks for the heads up.
