### ISSUE TITLE
Reset Notification Badges on Logout

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#2986]
#### Steps:
1. Log into WPiOS
2. Send the app to BG. Make sure that the Notifications tab is not selected.
3. Trigger an action that will send a push notification (ie. like one of your own posts).
4. When the push is received, go to Me > Settings > Logout.
5. Log into a secondary account.

#### Results:
The app will still show the badge it was showing up in step (4), no matter if the new account has or has not unread notifications.

#### Expected:
As soon as you logout the badges should be reset.

Props to @aerych for finding + reporting this one. (Thank you Eric!).

**Comment by astralbodies** [comment]
I want to say the mechanism for this used to work at one point.

**Comment by jleandroperez** [comment]
I probably broke it at some point, during the Notifications Refactor!
