### ISSUE TITLE
Reader: Post shows comment count, but comments missing for site with Jetpack configuration issues.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3002]
Like a post. In testing I used a post on a wpcom site with a mapped domain. 
Find the post in the Posts I Like list. 
Tap on the comments icon to view the comments. 
The comment vc displays but comments are never loaded.

**Comment by aerych** [comment]
The operation responseString is: `{"error":"unknown_token","message":"Unknown Token"}`

**Comment by aerych** [comment]
It looks like in this particular case, the site is a self-hosted site with Jetpack installed.  The error seems to be related to either an old version of Jetpack or some other connection issue.

**Comment by rachelmcr** [comment]
I reproduced this issue on the same self-hosted Jetpack site, and confirmed that it isn't possible to post new comments.

If the user tries to comment, they receive the error "There has been an unexpected error while sending your reply" with the following message in the logs: `Error sending reply: Error Domain=com.wordpress.api Code=0 "The Jetpack site is inaccessible or returned an error: transport error - HTTP status code was not 200 (403) [-32300] [jetpack_error]" UserInfo={WordPressComApiErrorCodeKey=jetpack_error, NSLocalizedDescription=The Jetpack site is inaccessible or returned an error: transport error - HTTP status code was not 200 (403) [-32300] [jetpack_error]}`

**Comment by alisterscott** [comment]
I noticed with this Jetpack site (https://wordpress.com/read/feeds/45695948 https://cupofjo.com/) that in Calypso comments are not shown at all, but in the iOS apps I can see the number of comments and then an empty comments list. Should comments be showing for this at all in WPiOS?

![cupofjo - 1](https://user-images.githubusercontent.com/128826/28054055-c703d58c-6656-11e7-8e04-5b6dfc95c717.jpg)
![cupofjo - 2](https://user-images.githubusercontent.com/128826/28054056-c706c710-6656-11e7-9ed8-02b419f36781.jpg)

Is this the same issue as specified in this issue or should I raise this separately?
