### ISSUE TITLE
Multiple prompts to enter Basic HTTP Auth credentials

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3016]
To reproduce:
Add a site that is secured with Basic HTTP Auth.  You will be prompted to enter credentials when you add the site to the app. 
Once added, tap to view the site's details screen (the list of posts, pages, comments, etc.) 
You will encounter multiple prompts to enter credentials, one for each request being made.  
View the post list and pull to refresh.  You are again prompted to enter credentials. 

It seems like every unique URL request eventually triggers the check `WPHTTPRequestOperation connection:willSendRequestForAuthenticationChallenge:` but subsequent requests of a previously requested URL do not.  I haven't gotten to the root of why subsequent requests do not show the prompt (maybe caching related?). 

Also, as far as I can tell we're not adding an authorization header to any request on the secured site and I'm not sure why we wouldn't be doing that. 

I used our site on bh.wpmt.co when testing.

**Comment by sendhil** [comment]
Yikes.

**Comment by aerych** [comment]
Been digging into this one.  It looks like at least some of the prompts are related to a check of `NSURLAuthenticationChallenge previousFailureCount` but I'm not sure that's the only issue. 

I also noticed a keychain error when removing the site. This is potentially due to the DEBUG flag being set and the keychain being emptied `WordPressAppDelegate removeCredentialsForDebug`.  
> 2015-01-08 16:20:49:138 WordPress[4894:607] <Blog:bh.wpmt.co> remove
2015-01-08 16:20:49:204 WordPress[4894:607] Error while deleting WordPressComOAuthKeychainServiceName token: Error Domain=SFHFKeychainUtilsErrorDomain Code=-25300 "The operation couldn’t be completed. (SFHFKeychainUtilsErrorDomain error -25300.)"

**Comment by aerych** [comment]
New clues:
When navigating to the Site Detail screen (posts, pages, etc.) `BlogService syncBlog:success:failure:` is called. If you drop an NSLog into `WPHTTPRequestOperation` and examine the challenge, you'll see that six (for this blog) HTTP Request are made, and all six will show a `challenge previousFailureCount` of zero.  However, one or more of these requests fail (wha?) in a way that increments the `challenge previousFailureCount` and now the user is prompted with one or more credentials dialogs.  I can mitigate the issue by altering `syncBlog` to only make four requests. Five or more and I can trigger the error 10/10 in the simulator.

**Comment by aerych** [comment]
In `WPXMLRPCClient`, its `NSOperationQueue` is configured with a max of four concurrent operations, as defined by `WPXMLRPCClientDefaultMaxConcurrentOperationCount`. This, plus the combination of more than four calls made in `BlogService syncBlog:success:failure:` can explain the behavior we're seeing. 

When `syncBlogs` is called, six requests are enqueued. Once the fifth request is made, the max number of concurrent requests is exceeded. At this point it appears that one of the preceding requests is canceled in favor of the most recent request, incrementing the value of `previousFailureCount`.  The result is that all requests (including the canceled one when it is retried) are prompted for new credentials. 

Options for a fix: 
- raise the max number of concurrent connections
- batch the requests so there is never more than 4 at a time. 

Thoughts? 
cc @sendhil @astralbodies @jleandroperez

**Comment by sendhil** [comment]
Raising the max number of concurrent connections seems like a less risky fix for now.

**Comment by jleandroperez** [comment]
+1, increasing from 4 to 6? 8? maximum concurrent connections "doesn't sounds"  like a big deal.

(Famous last words, i know!)

**Comment by astralbodies** [comment]
There used to be and still may be an artificially imposed limit on NSURLConnection for five connections to a single server address at a time. I wrote an enterprise iPad app for Generac and discovered that queued connections would time out before they even hit the wire. The timer on each of the queue operations would start prematurely because there was a limiter at a lower level (two queues with a bottleneck between). Just be aware of this when you're testing as it might cause you to place sharp objects into your eyes.

**Comment by aerych** [comment]
@astralbodies @sendhil @jleandroperez Thanks guys.

After a lot more testing, it seems that raising the max current connections doesn't seem to make a difference. Even setting as high as 20 I still can reproduce the issue. 

Additionally I think I've misunderstood part of what is happening. Previously I said

>  it appears that one of the preceding requests is canceled in favor of the most recent request

but I'm not sure this was correct. 

The basic flow for each request is: 
1 The request is executed sans authentication headers.
2 An authentication challenge is received
3 The app responds to the challenge, retrieving stored credentials, and handing these off to the relevant `NSURLAuthenticationChallengeSender` delegate method.
4 The challenge response is sent. 
5 Either success or failure. 

When making four requests or less, this flow executes perfectly.  But starting with the fifth request (concurrent or not) something weird starts happening in steps 3 and 4. 

At step four, if you examine request headers via Charles Proxy you'll see there is no authentication header included with the request. One *is* included at this step with four or fewer requests

With no auth header passed the request fails, and the api attempts a retry (go to step 2). When performing the retry, the credentials obtained at step 3 has `nil` for a password. (Theory: nil is returned either due to keychain locking, or because it was previously returned for the current protection space for this connection.)  

If step four fails, then there doesn't seem away past the issue until either retyping the credentials, or limiting the number of requests. 

I'm debating whether this is something busted in the framework and worthy of a radar (or if I'm just missing something).  As it is, the only viable patches I can suggest for this issues is to either 
1) batch the requests be performed (not ideal)
2) manually add the Authentication header to the requests (tested and is viable). 

I'm not a fan of either tbh.  Option 1 doesn't address the underlying cause and option 2, while potentially cleaner, avoids Apples intended mechanism for handling authentication challenges.  Its an approach that is permitted but not encouraged for security concerns. 

Thoughts on all of this?  I've sailed into strange waters and would welcome a more experienced guide.

**Comment by jleandroperez** [comment]
@aerych (Please, snap me if this is not accurate).

- In order to trigger this, you need to: add a self hosted WordPress site that has a *.htaccess* in its `wp-admin` folder.
- A series of requests are queued as soon as you launch the app (of course!) =)
- The app requests username / password for your site. If you enter it, it'll work only for 4 requests. Request number five will fail, no matter if it was dispatched once the other four finished, or concurrently.

Is that's accurate (4 requests work, 5 don't), i would suspect of *NSURLCredentialStorage*. We could build a sample app to replicate (just) this behavior, perhaps with NSURLSession, to keep the amount of code to the minimum.

(If it's indeed NSURLCredentialStorage, maybe we should switch to our old friend, the Keychain?)

Thanks!

**Comment by jleandroperez** [comment]
+ Just for the sake of testing, maybe we could replace NSURLCredentialStorage with NSUserDefaults?

(Used in WPHTTPAuthenticationAlertView and WPHTTPRequestOperation)

(No, i'm not saying we should commit that code, but it's a quick change to prove (or) discard that class as the source of the glitch).

**Comment by aerych** [comment]
> In order to trigger this, you need to: add a self hosted WordPress site that has a .htaccess in its wp-admin folder.

I'm not sure the location matters. It could be in the site root as well. 

> If you enter it, it'll work only for 4 requests. 

For four simultaneous requests, yes. Sequential requests have no trouble as far as I can tell.

**Comment by aerych** [comment]
Yesterday I built a [super simple tester](https://github.com/aerych/BasicAuthTest) to see if the problem was somewhere hiding in the app code or elsewhere.  For [the test](https://github.com/aerych/BasicAuthTest/blob/master/BasicAuthTest/ViewController.m), I'm not bothering with operation queues, and just making multiple requests via NSURLConnections.  I can reproduce the same behavior.  Four or fewer requests succeed, but more begin to fail. 

With this, I'm pretty sure the app code is fine and the problem is in the SDK... or there is something really weird going on with BlueHost.

**Comment by aerych** [comment]
Tested (via the test app) on two other non-bluehost sites courtesy of @maxme and @jleandroperez. I was able to reproduce the issue with @maxme's site but not @jleandroperez, which suggests the meat of the matter has something to do with server config and not an SDK bug.

**Comment by aerych** [comment]
Props @jleandroperez.  After comparing notes we discovered the key difference between Jorge's and Maxime's test sites was that Jorge's site did not have `keepalive` enabled. Once he enabled keepalive for connections, the issue could be reproduced on his site.

**Comment by astralbodies** [comment]
Did this get resolved then @aerych? Just catching up on my backlog and I realized I didn't follow through.

**Comment by aerych** [comment]
@astralbodies Yah, tho I don't think we'd all like to see a better patch.  #3057 staggers a block of requests to avoid triggering the issue, and while it works (for now) its not great.  The X factor seems to be whether the host has connections set to keep-alive or not.  I think if we could force the client connections to set keep-alive to false we'd have a cleaner way to avoid the issue, assuming there aren't any drawbacks to that approach. I haven't found a reliable way to do this so, for now, its a moot point. 

Closing.
