### ISSUE TITLE
Date on a draft post doesn't change to current time when draft is published

### ISSUE THREAD

**Issue by rachelsquirrel** [wordpress-mobile/WordPress-iOS#3032]
When drafts are published with the app, the date sticks to the date the draft was originally created rather than the date it was published.

Steps to reproduce:

1. Create a draft post with the app and save it.
2. Wait a bit (or find an existing draft that's old).
3. Edit the draft and publish it. The date doesn't change to the current time.

**Comment by AramZS** [comment]
I can confirm this, in fact it seems to blank the post date field.

**Comment by jstart** [comment]
PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/3290

Let me know if this is a sufficient fix.  Just checking if the status is changing from draft to publish, and if so, setting the publish date to now.

**Comment by jstart** [comment]
@astralbodies  any code review changes needed?
