### ISSUE TITLE
iOS Location Services not saving permission for WordPress

### ISSUE THREAD

**Issue by sandymcfadden** [wordpress-mobile/WordPress-iOS#3042]
Using an iPhone 6 with 8.1.2 and iPad 2 with 8.1.1 Location Services does not seem to be saving when you set WordPress to always allow location access.

Once you enable access you are able to make a post and it will find the geo location, but then if you close the app and open it again you will not be able to use location services. You then must go back in and set the app to always allow again.

**Comment by sendhil** [comment]
cc @bummytime

**Comment by jstart** [comment]
Looks like this issue should be closed thanks to the WhenInUseUsageDescription fix from @SergioEstevao
