### ISSUE TITLE
Login with a user without edit post permission, makes app crash

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#3043]
When trying to read the options array from the REST response on this method

`- (NSDictionary *)mapOptionsFromResponse:(NSDictionary *)response` on `BlogServiceRemoteRest`, the options array is not there so the app crashes when trying insert nil on the responses.

**Comment by tommi** [comment]
Tested this to be okay.

**Comment by sendhil** [comment]
Closing as this was fixed in #3043.
