### ISSUE TITLE
Text is selectable on the new beautiful UIAlertView

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3094]
Looks like the UITextView being used allows text selection.

![img_4545](https://cloud.githubusercontent.com/assets/373903/5941159/97aca2d0-a6d4-11e4-99b4-4b7f32ab4d85.PNG)

BTW great job on this interface - it's awesome.

**Comment by sendhil** [comment]
cc @diegoreymendez

**Comment by diegoreymendez** [comment]
Fixed.

**Comment by diegoreymendez** [comment]
@meremagee - Pinging you since there's no `resolved > test` tag in this repo.
