### ISSUE TITLE
Crash on start - 4.8

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS#3095]
1. crash upon update > open

- log: https://cloudup.com/c4Fo1mjXqDe
- description:
 - open app
 - saw notif that new version was ready for install
 - install from hockeyapp
 - open app
 - crash
 - open app
 - crash
 - open app
 - alert to send crash report
 - [onboarding modal](https://cloudup.com/iNbxggOQCSp) pop up over alert
 - dismiss onboarding
 - send report

cc @diegoreymendez (in case it has to do with onboarding)

**Comment by bummytime** [comment]
@diegoreymendez @sendhil this may actually have something to do with app rating. See:

https://rink.hockeyapp.net/manage/apps/34115/app_versions/147/crashes/2625327658

**Comment by bummytime** [comment]
Whoops...looks like https://github.com/wordpress-mobile/WordPress-iOS/pull/3144 may fix things.

**Comment by diegoreymendez** [comment]
@bummytime - Do you happen to know if we can close this issue?

**Comment by bummytime** [comment]
@diegoreymendez Yeps. Closing this now.
