### ISSUE TITLE
Crashes - Editor

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS#3096]
Repro is 100% consistent w/ visual editor enabled

- logs: https://cloudup.com/ckseYbvnOAF
- description:
 - create new post
 - Hit new post button
 - x to cancel
 - discard post
 - Hit my sites
 - switch site
 - while on site page hit new post
 - crash

cc @bummytime

**Comment by bummytime** [comment]
@meremagee I would humbly ask that you test this again when the new version of 4.8 internal is released. I tested this with my https://github.com/wordpress-mobile/WordPress-iOS/pull/3107 fix in place and could not crash it.

**Comment by meremagee** [comment]
resolved
