### ISSUE TITLE
Visual Editor Missing

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3097]
Upgrade path. The visual editor was not available or enabled in the previous version. After upgrading the legacy editor is the default and there is no setting to enable the visual editor.

**Comment by bummytime** [comment]
Thanks @aerych!

> The visual editor was not available or enabled in the previous version.

Check.

> After upgrading the legacy editor is the default and there is no setting to enable the visual editor.

Were you expecting the new editor to be turned on even tho it wasn't in the previous version?  (If so, keep in mind this: https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/497 was not implemented yet)

**Comment by aerych** [comment]
> Were you expecting the new editor to be turned on even tho it wasn't in the previous version

I was! I missed that it had not yet been enabled. (Darn tickets in multiple places.)  Let's close this one as invalid.
