### ISSUE TITLE
Sign up: Support screen is wrong size. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3098]
To reproduce on the iPad:
Go to the sign in screen. 
Log in with incorrect credentials to see the error prompt. 
Tap the "Need Help?" button. 
Support opens in the full width of the screen. 

We should either display this screen as a form modal or update the views to have the correct styling. 

![img_0036](https://cloud.githubusercontent.com/assets/1435271/5945838/f7cc747a-a6f6-11e4-84be-17eae5d86106.PNG)

**Comment by sendhil** [comment]
Closed in #3197
