### ISSUE TITLE
Web stats shows wpcom bar after refresh

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3099]
To reproduce on iPhone or iPad
Go to Me > [Site] > Stats.  
Scroll down and tap to view web stats. 
Pull to refresh. 

![img_3260](https://cloud.githubusercontent.com/assets/1435271/5945891/62c2f952-a6f7-11e4-8c7b-19b6f1ab8be0.PNG)

**Comment by sendhil** [comment]
cc @astralbodies

**Comment by astralbodies** [comment]
Similar to #3100 I'm closing this issue for now since we're replacing stats in 3.9. The new web stats doesn't have a "chromeless" view yet so this is close to what you'll see. :stabby:
