### ISSUE TITLE
Return to stats link is cropped.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3100]
To reproduce on the iPhone:
Go to Me > [site] > Stats
Scroll down and tap to view web stats. 
Tap a link like Summaries. 
Notice that the link to return to the main stats page is truncated. 

![img_3259](https://cloud.githubusercontent.com/assets/1435271/5945916/9a145572-a6f7-11e4-83e8-e84fbf193bb6.PNG)

**Comment by sendhil** [comment]
cc @astralbodies

**Comment by astralbodies** [comment]
I'm closing this issue for now since we're replacing stats in 3.9 and the web stats link is updated to point at the new web version. If we went up letting people point back at old stats, I'll make sure this gets fixed on the web.
