### ISSUE TITLE
Expanded chart details collapse when refreshing.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3101]
Minor, and maybe not a bug per se, but it doesn't seem like an ideal experience. 
To reproduce, 
Go to the stats screen for a site. 
Tap on a column in the chart to view details about that column.
With the details expanded, pull to refresh. 
When the refresh is complete the details are collapsed

**Comment by astralbodies** [comment]
Closing as the UI was replaced with stats 0.2.0
