### ISSUE TITLE
Comments: Reply form is titled "Edit Reply"

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3102]
Go to Me > [site] > Comments 
Select a comment. 
On the comment detail tap Reply. 
The reply form is titled "Edit Reply". Should probably just be "Reply"

![img_0061](https://cloud.githubusercontent.com/assets/1435271/5946068/9916bf9c-a6f8-11e4-85b9-771a3cbcb916.PNG)

**Comment by sendhil** [comment]
cc @jleandroperez

**Comment by jleandroperez** [comment]
Thanks for filing this one @aerych + (@sendhil for the ping!).

Will get this one for 4.9!
