### ISSUE TITLE
Comments: Unable to dismiss reply modal. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3103]
To reproduce:
Go to Me > [site] > Comments
Pull to refresh. 
While the list is refreshing, tap on a comment to view its detail, then tap to reply to that comment. 

When the refresh completes you're taken back to the comment list (why?) but the Reply modal does not dismiss. 
Tapping the Cancel button has no effect.

**Comment by SergioEstevao** [comment]
@aerych I couldn't reproduce this, do you know if it was fixed by someone? If yes do you know the version?

**Comment by aerych** [comment]
Unable to reproduce as well. This was happening back when sites were under the Me tab vs their own tab. Something may have changed in the shuffle to fix the issue but I can't say what it might have been.  Let's close and we can reopen if necessary.
