### ISSUE TITLE
Editor Options: Featured image upload cell is cramped.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3104]
The cell used to show the featured image upload progress is very cramped. 
We should probably adjust its height for some nice vertical spacing. 

![img_0037](https://cloud.githubusercontent.com/assets/1435271/5946148/2d8ec23c-a6f9-11e4-8e47-9139174fc64d.PNG)

**Comment by sendhil** [comment]
@SergioEstevao :point_up:

**Comment by aerych** [comment]
Closed in #3259
