### ISSUE TITLE
Editor Options: Improve featured image upload progress presentation

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3105]
The upload cell shows progress in bytes.  A more user friendly approach would be kilobytes (and specify the unit of measure), or perhaps just a 0 to 100% scale. 

![img_0037](https://cloud.githubusercontent.com/assets/1435271/5946181/72bfdcc4-a6f9-11e4-96f0-0e2bd43533c3.PNG)

**Comment by sendhil** [comment]
@SergioEstevao :point_up:
