### ISSUE TITLE
Screens under the new Me tab are not properly styled. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3106]
To reproduce, on the iPad go to Me > Account Settings or Me > Support.
These screens were designed to be presented in form modals on the iPad and do not have the correct stylings to be displayed full screen.  We should either present these as modal screens, or updating the styling to be consistent with the rest of the app.  Related #3098

![img_0039](https://cloud.githubusercontent.com/assets/1435271/5946253/eb0d2a10-a6f9-11e4-93fe-afb666413478.PNG)

![img_0036](https://cloud.githubusercontent.com/assets/1435271/5946257/f1086bc8-a6f9-11e4-8f43-11ab6fef85fc.PNG)

**Comment by sendhil** [comment]
Closed in #3197
