### ISSUE TITLE
Me tab's avatar never loads.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3109]
The Me tab shows a mystery-man for an avatar placeholder, but never shows the user's real avatar.  This feels broken since through out the rest of the app the user's avatar is displayed (comments, notifications, etc.) 

If we're unable to display the real avatar it might be best to just hide it until we have that capability.

**Comment by beaulebens** [comment]
FWIW, I was going to report this as well, but mine did in fact load eventually. It just seemed to take a very long time, and there was no indication that anything was going on, so I assumed it was broken as well.

**Comment by aerych** [comment]
Looks like the culprit is a non "G" content rating on the gravatar.
