### ISSUE TITLE
Notifications: Reply notification shows unrendered HTML 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3110]
The cell for a reply notification can show HTML in its contents. Maybe we can strip this out? Happens both in the list and in the detail. 

![img_0041](https://cloud.githubusercontent.com/assets/1435271/5946483/a7ee23ea-a6fb-11e4-96cd-4552d5215694.PNG)

![img_0040](https://cloud.githubusercontent.com/assets/1435271/5946486/ad1413fc-a6fb-11e4-8171-6b3db0a893f9.PNG)

**Comment by dmsnell** [comment]
See https://github.com/Automattic/notifications-client/issues/369

Should be fixed in [r112064](https://wpcom.trac.automattic.com/changeset/112064)

@aerych do you still have the notification to confirm that this is fixed?

**Comment by aerych** [comment]
@dmsnell I'm still seeing the html. I tried signing out and then back in thinking that should clear anything that was cached and let fresh content sync.

**Comment by dmsnell** [comment]
@aerych what user are you using for those notes?

**Comment by aerych** [comment]
Signed in as "aerychtest"

**Comment by aerych** [comment]
Just checked again and its fixed. Thanks @dmsnell!
