### ISSUE TITLE
Editor: Prompted for unsaved changes when no changes are made.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3111]
Happens with the legacy editor and the visual editor.  
To reproduce 
- Create a new post, then tap to dismiss it. 
OR
- Tap to edit an existing post but make no changes. Tap to dismiss.  

Note that the prompt says you have unsaved changes. 

![img_0043](https://cloud.githubusercontent.com/assets/1435271/5946678/497b4b56-a6fd-11e4-8b91-9691ddd8fe53.PNG)

**Comment by meremagee** [comment]
logged in editor repo https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/531
