### ISSUE TITLE
Editor: Crash saving draft. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3112]
To reproduce:
Tap the new post button to create a new post. 
Make no changes. 
Tap to close the post. 
When prompted, choose the option to save a draft. 
Crash. 
Likely related to #3111

**Comment by bummytime** [comment]
The crash is in the legacy editor only based on my quick tests. However, the new editor will close the empty post then save the blank post. Not sure if this is acceptable behavior either. 

/cc @meremagee

**Comment by aerych** [comment]
> The crash is in the legacy editor only

This was my experience also. My bad for not including that detail in the description.

**Comment by meremagee** [comment]
> However, the new editor will close the empty post then save the blank post. Not sure if this is acceptable behavior either.

We handled this in the ui with https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/441 but didn't account for the action sheet "save." Can we remove the "save draft" option if at least 1 character hasn't been added to title OR body, which would be the same behavior that we execute currently on an _existing post_ that you edit then cancel before making any changes:

action sheet when editing existing post > make no changes > hit cancel
![](https://cloudup.com/iYBm1O0Uv_W+)
