### ISSUE TITLE
Posts / Pages: Duplicate entries (on the device) when publishing new posts/pages. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3113]
Go to the post or page feature. 
Create a new post / page and publish. 
On the list, note that there is two entries for the newly created post/page.  
Pull to refresh clears the extra. 

![img_0044](https://cloud.githubusercontent.com/assets/1435271/5946690/61764634-a6fd-11e4-81cb-7618a93351a6.PNG)

**Comment by bummytime** [comment]
Thanks @aerych. We have this logged here: https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/407 so I am going to close this one.

**Comment by aerych** [comment]
:+1: Sorry for the dup!
