### ISSUE TITLE
Me: Signout does not take you to the sign in screen. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3114]
This seems to be specific to the iPad. 

On the iPad version of the app, be logged in with a wpcom account and have no self-hosted sites in the app. 
Go to the Me tab and click sign out. 
You are left on a logged out version of the app with no sites. 
You're able to tap between the tabs until you tap the new post button. At this point the you are finally taken to the sign in screen. 

![img_0045](https://cloud.githubusercontent.com/assets/1435271/5946697/6b42f996-a6fd-11e4-81f2-ec56396caedc.PNG)

![img_0046](https://cloud.githubusercontent.com/assets/1435271/5946707/794d82fe-a6fd-11e4-8ed7-3ce7db453a0f.PNG)

**Comment by oguzkocer** [comment]
Fixed in #3201.
