### ISSUE TITLE
Visual Editor Enabled prompt does not match orientation. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3115]
Maybe not an issue if the visual editor will be enabled by default but documenting in case.  Seems like this was an issue from before? 

![img_0048](https://cloud.githubusercontent.com/assets/1435271/5946732/b08e2192-a6fd-11e4-9a06-46df806fe61c.PNG)

**Comment by meremagee** [comment]
won't hit production
