### ISSUE TITLE
Unhelpful error screen when creating a new account.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3117]
When walking though the new acct NUX I encountered an error. The error screen tells me nothing about what kind of error it was.
 
![img_0051](https://cloud.githubusercontent.com/assets/1435271/5946812/2e9f4598-a6fe-11e4-9af3-cf29925be6f3.PNG)

Yep.

**Comment by sendhil** [comment]
@aerych - do you remember how you reproduced it?

**Comment by aerych** [comment]
I think I was entering some bad values in the form. I didn't recall at the time exactly what they were :(  I can try to reproduce

**Comment by sendhil** [comment]
@aerych :+1:

**Comment by SergioEstevao** [comment]
Unable to reproduce so I'm going to close this down.
