### ISSUE TITLE
Stats: Probably should not show "Today" button if not connected to Jetpack

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3118]
Title has it. 

![img_0053](https://cloud.githubusercontent.com/assets/1435271/5946853/6822dbd6-a6fe-11e4-96eb-ec3fe0804d68.PNG)

**Comment by astralbodies** [comment]
Thanks @aerych! I believe I've fixed this in the develop branch for 3.9 for merging in stats 0.2.0. I'll leave this open until that gets merged in.

**Comment by koke** [comment]
This seems fixed in develop
