### ISSUE TITLE
Fix flash that occurs for new users opening the app

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#3120]
If you open the app up on a fresh install you get a brief flash of a blank me screen before the login screen appears.

**Comment by aerych** [comment]
@sendhil Can you still reproduce this?  I'm unable to as of 5.7. Closable?

**Comment by nheagy** [comment]
This appears to still be happening, might only be on fresh installs.

**Comment by koke** [comment]
If I sign out, force quit, and launch the app I can still see it
