### ISSUE TITLE
Editor: Visual editor title field honors carriage returns

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3122]
We probably want to trap the return key and not make that change. 

![img_0057](https://cloud.githubusercontent.com/assets/1435271/5947144/a4b952ee-a700-11e4-83ba-c51039f775b7.PNG)

**Comment by meremagee** [comment]
fixed: https://github.com/wordpress-mobile/WordPress-iOS-Editor/pull/532
