### ISSUE TITLE
Editor: Image progress tag visible in post preview

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3123]
Progress bar shows up on post preview after image has uploaded. 
![img_0058](https://cloud.githubusercontent.com/assets/1435271/5947174/c9d1d7ae-a700-11e4-8422-cb5f10766380.PNG)

**Comment by bummytime** [comment]
@aerych I am having a difficult time trying to repro this. Any tips?

**Comment by aerych** [comment]
Seems timing related. I can reproduce it almost consistently with these steps. 
Open a new post. 
Add a title. 
Tap into the body content field and tap to add a photo. 
When the photo has uploaded (the uploading status goes away) I casually tap on the preview button.
The progress bar is displayed on the preview. 
Tap back then tap preview again, the progress bar is no longer visible. 

Timing issue maybe?

**Comment by bummytime** [comment]
Ok...I got it to happen :-) Thanks. 

/cc @SergioEstevao

**Comment by SergioEstevao** [comment]
Just found that we have the same issue when a upload fails and we go for preview mode.
Should I just remove all failed items when we go to preview? Like we do for saving and going to HTML mode. Showing an alert in the way?

**Comment by bummytime** [comment]
@SergioEstevao 

> Should I just remove all failed items when we go to preview? Like we do for saving and going to HTML mode.

I would vote for yes. Do you want to add this to your PR?

**Comment by SergioEstevao** [comment]
Fix by this: https://github.com/wordpress-mobile/WordPress-iOS/pull/3155
