### ISSUE TITLE
Editor: Error cancelling an uploading featured image.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3124]
Cancel uploading featured image shows an NSURLErrorDomain -999 error.   
Try to upload again causes a crash (sometimes you need to try a couple of times to trigger). 

![img_0060](https://cloud.githubusercontent.com/assets/1435271/5947241/2336fbbc-a701-11e4-8a93-e8c1dc1defa2.PNG)

**Comment by sendhil** [comment]
Fixed in #3193
