### ISSUE TITLE
Site Settings / Edit Site: Cells change position and size when transitioning to new screen

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3128]
View the Site Settings / Edit Site screen for a self-hosted site. 
- Note the size and position of the cells.  
- Tap Configure.  
Notice that the cells change size and position as the new screen appears.  
Tap the back button and observe the same effect.

**Comment by garza** [comment]
sorry, first PR was from a not up-to-date develop branch, latest PR should be clean
