### ISSUE TITLE
Tabs should reset their nav hierarchy when accounts change. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3130]
To reproduce on the iPhone: 
- I signed out of my wpcom account.  This returned me to the sign in screen. 
- Created a new site via NUX. 
- When I was finished I was placed on Me tab. 
- I tapped on the My Sites tab and was taken to the comments screen. 

This was probably the last screen open on this tab before I signed out.  Tapping back showed a site belonging to the acct I signed out from. Tapping back again showed the list with just the newly created site.

I repeated the steps above, but this time I left the My Site tab on the post list. When I tapped to the My Sites tab after going through the NUX process the app crashed.

**Comment by oguzkocer** [comment]
There is also another way to re-produce a similar issue:

* Login with your WordPress.com account
* Add your self-hosted site
* Go into one of your WordPress.com account blogs in the "My Sites" tab
* Go into "Me" tab and logout from WordPress.com
* Go back to "My Sites" tab and you'll still be in the WordPress.com blog's detail page

**Comment by oguzkocer** [comment]
Fixed in #3203.
