### ISSUE TITLE
My Sites can show invalid site information after connecting to Jetpack

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3132]
Different issue but probably related to #3130. 

Sign into a self hosted site and skip the Jetpack step. 
Go to My Sites > [newly added site] > Settings 
Now configure Jetpack.

This is going to replace the self-hosted record of the site with the wpcom/Jetpack record of the site. 
The issue is you are still drilled down into a blog record that no longer exists and you can still see that information in the detail screen as you navigate backward.

**Comment by koke** [comment]
I just followed the steps, and after configuring Jetpack it sent me back to the sites list. Can you still reproduce?

**Comment by koke** [comment]
I think #3203 fixed this.
Also see #3596
