### ISSUE TITLE
Comments: Details uses both a square and a circlular icon. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3133]
A comment detail shows a square avatar in the header but a circular icon in the detail.  We're using circular icons through out the apps which makes this a little confusing. 

I think we were trying to use a square icon to designate a site and a circular icon to designate a person, but it looks like this isn't clear when default icons are used. 

![img_3269](https://cloud.githubusercontent.com/assets/1435271/5947729/15cbda5c-a705-11e4-97c2-f4e0f7c46858.PNG)

**Comment by itsaboutcode** [comment]
I believe this issue is already fixed.
<img width="487" alt="screen shot 2015-08-05 at 11 22 37 am" src="https://cloud.githubusercontent.com/assets/204423/9079512/5b25e54a-3b64-11e5-8ed2-417d7782c711.png">

**Comment by rachelmcr** [comment]
>I believe this issue is already fixed.

Yep! I checked again and only see circular avatars in notifications, as in the screenshot above. Closing this as resolved.
