### ISSUE TITLE
Editor: The preview does not wrap an unbroken line of text

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3136]
Editor preview does not wrap an unbroken line of text.  The active editor does. 

### Preview:
![img_3273](https://cloud.githubusercontent.com/assets/1435271/5947818/b7be6d3e-a705-11e4-8609-79e55964db6d.PNG)

### Active:
![img_3274](https://cloud.githubusercontent.com/assets/1435271/5947848/e81025b8-a705-11e4-8400-8c81e3422657.PNG)

**Comment by meremagee** [comment]
moving to editor repo > 4.9
