### ISSUE TITLE
Editor: Device image path sometimes not replaced.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3137]
Seems like there is an edge case where visual editor does not successfully replace a local URL path with a remote URL path for an image. Seems a bit hit or miss. I could reproduce it semi-reliably by uploading just an image to a post, make no other changes, and publish as soon as the uploader was complete. Timing issue maybe? 

@bummytime perhaps this could be related to the disappearing private image issue? 

Example is from an earlier test where I edited an existing post
![img_3276](https://cloud.githubusercontent.com/assets/1435271/5947873/219625ee-a706-11e4-837d-68f4f1b613f8.PNG)

**Comment by bummytime** [comment]
> perhaps this could be related to the disappearing private image issue?

Definitely possible. @SergioEstevao any thoughts on this one?

**Comment by meremagee** [comment]
resolved

**Comment by sendhil** [comment]
@SergioEstevao :point_up:

**Comment by sendhil** [comment]
Woops - ignore that last ping @SergioEstevao, didn't see @meremagee's comment
