### ISSUE TITLE
Jetpack site can appear in both self-hosted and wpcom site lists. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3138]
To reproduce: 

Sign in to self-hosted account connected to Jetpack and connect to Jetpack. 
Note that the site shows up in the wpcom list. 
Tap to add a self-hosted site and add the self hosted site again, but skip the step to connect to jetpack. 
You now have a wpcom/Jetpack record of the site, and a self-hosted record.

**Comment by koke** [comment]
I think this is covered by #2782
