### ISSUE TITLE
My Sites pushes me to the first item in the list when there are multiple blogs

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3139]
From the sign in screen, sign in to a wpcom account with multiple sites. 
Tap the My Sites button. 
You will briefly see the list of sites but you are immediately pushed into the first item in the list. 

This maybe makes sense if there is just one site in the list but when there is more than one its not so great.

**Comment by aerych** [comment]
It might be that I tapped the My Sites tab twice unknowingly which seems to have the same effect.

**Comment by oguzkocer** [comment]
After the masterbar changes "My Sites" should be opening up with the last used blog, instead of the all sites list. The push navigation shouldn't be shown though, I am not sure what happened there.

https://github.com/wordpress-mobile/WordPress-iOS/blob/release/4.8/WordPress/Classes/ViewRelated/System/WPTabBarController.m#L110

**Comment by aerych** [comment]
I was really trying to put the app into weird states to break things.  I might have hit a tricky edge case.

**Comment by oguzkocer** [comment]
Hmm... maybe we can keep an eye on this one and if we can reproduce until submission, we'll fix it. Does that work?

**Comment by aerych** [comment]
Yep.  We can track here.  If we can't duplicate we can eventually close it.

**Comment by oguzkocer** [comment]
It's possible that an update on an existing app could be causing the app to forget the last used blog which will lead the app to select the first blog instead.

**Comment by oguzkocer** [comment]
@aerych I have looked into this issue again. I can't seem to be able to reproduce it and as far as I can tell, the way we're handling it is probably the best we can do. I wasn't able to come up with an edge case that'd break the following code:

```
self.blogListViewController = [[BlogListViewController alloc] init];
_blogListNavigationController = [[UINavigationController alloc] initWithRootViewController:self.blogListViewController];

Blog *blogToOpen = [blogService lastUsedOrFirstBlog];
if (blogToOpen) {
    BlogDetailsViewController *blogDetailsViewController = [[BlogDetailsViewController alloc] init];
    blogDetailsViewController.blog = blogToOpen;
    [_blogListNavigationController pushViewController:blogDetailsViewController animated:NO];
}
```

What do you think?

**Comment by aerych** [comment]
I can't reproduce it either.  Let's call it a ghost in the machine and revisit if it returns in a way we can reproduce.

**Comment by aerych** [comment]
Thanks for checking back on this @oguzkocer!

**Comment by oguzkocer** [comment]
Thanks @aerych!
