### ISSUE TITLE
Sites from two different wpcom accounts can appear in the site list. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3141]
To reproduce:
- Sign in to a self-hosted site that has Jetpack but skip the Jetpack step.  
- Sign in to wpcom account that is not connected to the self-hosted acct's Jetpack.  
- Now go to the self-hosted site's settings and configure its Jetpack.  
- Notice that the site list now shows a mix of the sites belonging to both wpcom accounts. 

![img_3281](https://cloud.githubusercontent.com/assets/1435271/5948122/0d9bfe2c-a708-11e4-9ae6-ad8416cd35f4.PNG)

**Comment by SergioEstevao** [comment]
@aerych @koke is this still happening? If no please close and assign the milestone where it was sorted.

**Comment by koke** [comment]
Yep, still happening.

**Comment by koke** [comment]
To fix this, I think we shouldn't call syncBlogs unless the newly created account is the default account
https://github.com/wordpress-mobile/WordPress-iOS/blob/0253488f27a18a12b5e68098143abd3fe2bcf14b/WordPress/Classes/Models/Blog%2BJetpack.m#L173
