### ISSUE TITLE
Status bar missing after uploading to 4.8.0.20150128

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3147]
Steps taken:
I opened the app. 
Accepted the prompt to upgrade.
When the update was complete I launched the new version.
Upon launch, the stats bar transitioned away. 

Fluke maybe?   

![img_3282](https://cloud.githubusercontent.com/assets/1435271/5961100/c8cadb18-a79f-11e4-83c5-2911d9a8336f.PNG)

**Comment by aerych** [comment]
Possibly related to something weird with state restoration? I remember seeing the editor in the background when prompted to update, and it does not display the status bar.

**Comment by rachelmcr** [comment]
I tested this while updating to 5.7 (stable release), and I think you're right about state restoration. I opened the editor before updating, installed the update to 5.7, reopened the app, and it opened to the reader without the status bar.

**Comment by kurzee** [comment]
Probably not a problem, since we don't hide the status bar anymore.
