### ISSUE TITLE
Add WPAnalyticsStatEditorDisabledNewVersion analytics enum.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#3165]
WPiOS is currently expecting `WPAnalyticsStatEditorDisabledNewVersion` to be declared in our analytics pod.

I'll manually comment the lines that expect this enum to be declared in WPiOS until the enum is available again.

/cc @bummytime, @sendhil

**Comment by bummytime** [comment]
@sendhil could you publish the `0.0.20` version of the analytics pod so @diegoreymendez can do his magic here?

**Comment by bummytime** [comment]
@diegoreymendez ok, the ```0.0.20``` analytics pod is published.

**Comment by bummytime** [comment]
Actually @diegoreymendez, I am going to close this issue in favor of this PR:

https://github.com/wordpress-mobile/WordPress-iOS/issues/3160

@sendhil and I chatted and he will make sure all of the required analytics are being tracked.

**Comment by diegoreymendez** [comment]
@bummytime, @sendhil - Thank you guys!
