### ISSUE TITLE
Me: Username label can show email address preceeded by an @

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3169]
To reproduce, sign out of the app
Sign back into the app but use your email address in lieu of your username. 
Go to the Me tab.  You'll see your email address instead of your username below the avatar, and it is prefixed with an @. 
`@your@emailaddresss.com`

**Comment by oguzkocer** [comment]
Fixed in #3217.

**Comment by jleandroperez** [comment]
Reopening this issue since the fix is causing a crash in iOS 7.
