### ISSUE TITLE
CRASH: logout > log in > my sites

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS#3180]
100% repro on iphone 5s, ios7

log: https://cloudup.com/iqjEDl5Y5Eq

Repro
- logout of app in "Me"
- login - to same or different account
- upon login, land on "Me"
- tap "My Sites"

**Comment by jleandroperez** [comment]
It's highly likely this crash got fixed in #3203 already.

Cannot repro using the latest code in **release/4.8** branch. Let's keep it open until we can validate, with a new Internal Beta.

Thanks!

**Comment by meremagee** [comment]
looks good!

**Comment by jleandroperez** [comment]
@meremagee you're the best!! thank you!
