### ISSUE TITLE
Unsetting feat img on Pages - UI

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS#3181]
UI is off after removing a featured img on pages (works as expected on posts)

Repro
- go to page
- add featured img
- remove/delete featured img
- featured img placeholder remains size of the img

![](https://cloudup.com/icYVK0AhHiw+)

lower priority since functionality is still solid

**Comment by sendhil** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/3194
