### ISSUE TITLE
View Admin not in in-app webview

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS#3196]
In site detail, View Admin should open in in-app web view like View Site does, as opposed to launching a new safari tab

**Comment by jstart** [comment]
https://github.com/wordpress-mobile/WordPress-iOS/pull/3289
Let me know if this is a sufficient fix.  I copied from AboutViewController.m where you show links like automattic.com/privacy where you check for reachability, then push the WPWebViewController
