### ISSUE TITLE
Can't Add Site

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#3199]
Originally reported by: @debex 
Moved from: https://github.com/wordpress-mobile/WordPress-iOS-Editor/issues/539

---

I was not able to add a new site through the mobile app. I tested with several types of users:

* a brand new user (created through browser) with no existing site
* a new user created through mobile app with one existing site
* an existing user with multiple sites 

1. Sign into mobile app 
2. Tap **My Sites** icon
3. Tap **Add Site** link
4. Enter username, password, and (desired, available) site address into the Add Site form
![add-site-form](https://cloud.githubusercontent.com/assets/8136035/6066853/3d9320f6-ad3e-11e4-9745-a378801eab0c.png)
 * A possible point of confusion in the form shown above is whether you need to enter the desired address as only the *sitename*, or as *sitename.wordpress.com*. The image below shows a similar screen that we present when someone is creating a new account in the mobile app -- note how we fill in the *.wordpress.com* to indicate they don't need to type it out.
![create-account-form](https://cloud.githubusercontent.com/assets/8136035/6066989/38e259c2-ad3f-11e4-9197-ea1e499b4d8a.png) 
 * When adding a new site **not** as part of new user signup, a user is likely to enter only the sitename. If so, an error screen is displayed with the message: "Sorry, we can't log you in. Unable to find a WordPress site at that URL..."

![sorry](https://cloud.githubusercontent.com/assets/8136035/6066860/4c75757e-ad3e-11e4-9a15-27aab110ec36.png)

 * If instead you enter a complete address, like *sitename.wordpress.com* and tap **Add Site**, you are returned to the My Sites screen but no new site has been added:

![my-sites](https://cloud.githubusercontent.com/assets/8136035/6066963/00d01812-ad3f-11e4-9d75-78244b27ee4f.png)

So either way it doesn't work to add a new site. Regarding the address field in the Add Site form, my feeling is that we should use the form that fills in the *.wordpress.com* part for them. I also wanted to ask if it's necessary to prompt them for their username/password for this step. It seems like a bit of hassle.

**Comment by rachelmcr** [comment]
Adding a site in the iOS app currently only allows you to add an existing (self-hosted) site. New WordPress.com sites can't be created there.

We should add the ability to create new WordPress.com sites under the same account the user is logged in with; that enhancement idea is being tracked at #3941. I'm closing this issue in favor of that one.
