### ISSUE TITLE
Adding "Set Feature" image, results in a Failed Upload message

### ISSUE THREAD

**Issue by susered** [wordpress-mobile/WordPress-iOS#3210]
The latest released WordPress app for iOS, 4701, is erroneously reporting that a "Failed" upload/update occurred. This seemingly only happens when a "Set Feature" image is set - I used this feature though from my computer though not the WordPress app. When I remove the "Set Feature" image, the upload/update is a success in the WordPress app.

Performing any of these actions through a browser is successful. So, it is seemingly an app problem.

**Comment by aerych** [comment]
Dup of https://github.com/wordpress-mobile/WordPress-iOS/issues/3045
