### ISSUE TITLE
Notifications List: Trim Snippet

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#3224]
We've got reports of Notification Snippets rendering newlines at the beginning (or at the end) of the text being displayed (in the Notifications List).

Let's update the helpers that format the snippet, so that the resulting string doesn't contain newline characters at the beginning / end.

**Comment by SergioEstevao** [comment]
@jleandroperez is this sorted out?

**Comment by jleandroperez** [comment]
@SergioEstevao closing this one, since i couldn't reproduce any glitch. The only way in which newlines would be rendered, is when the comment actually has a new line.

(And it actually makes sense to actually render that!).

Thanks for checking!
