### ISSUE TITLE
Onboarding: multiple new editor dialogs

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#3232]
This may not be that serious. After you first see the new editor dialog, close and reopen the app...another dialog is then placed on top of the existing dialog. This forces the user to tap the dialog's dismiss button multiple times to remove all the alerts. 

Note this was a fresh install, not an upgrade. Demo of bug on an iPhone 5s running iOS 8.1.2:

https://cloudup.com/caXpcjBa0NF

/cc @diegoreymendez @meremagee

**Comment by meremagee** [comment]
> Note this was a fresh install, not an upgrade.

new users should not see onboarding so this seems more odd than usual

**Comment by meremagee** [comment]
reproed, ios7/iphone5s

**Comment by diegoreymendez** [comment]
I'm onto this.

**Comment by diegoreymendez** [comment]
Fixed.

**Comment by diegoreymendez** [comment]
@meremagee - `resolved > test`
