### ISSUE TITLE
Post Formats

### ISSUE THREAD

**Issue by lewiguez** [wordpress-mobile/WordPress-iOS#3236]
I'm not sure if this would be an issue with the iOS app or if this would be an issue within WordPress itself. Inside of `BlogServiceRemoteXMLRPC`, the method `operationForPostFormatsWithBlog:success:failure:` adds the blog's post formats to the `Blog` object. These formats are used in the editor for a post and only display the supported formats. The supported formats come across in the dictionary response as an NSArray. This method parses the response and checks to see if it contains the `supported` key and if the value for that key is an NSArray. (Line 71 in current develop branch)

Normally, this works fine.

However, in a specific circumstance, the response that comes back is different than expected. If a particular theme has set `add_theme_support` for `post-formats` and included an invalid post format (e.g. misspelled "aside" as "asside") the response returned from the service is an NSDictionary instead of an NSArray.

If this happens, the "Post Format" box on the post settings section contains the `postFormat` instead of the `postFormatText`. Then, when you go to select a new post format, the list appears with "Standard" and blank table view cells. Tapping on a cell causes the application to **crash** currently (the end result is because it's trying to set an NSDictionary that has somehow made it this far as the new `postFormatText` in the `onItemSelected` block for the post format).

As stated, I'm not sure if this is a problem with the app or the service. I'm not even sure if it should be something that's coded around since really the theme is at fault for providing an invalid post format. However, this doesn't affect the WordPress post editor and it's something that has made it into production builds for WordPress, so it feels like it should be at least coded around in the application because it's a hard crash and you can't change post formats through the application otherwise. 

If you feel the same way, I've got a patch and would love to participate in the process. If this is something I should log elsewhere, please let me know. Thanks!

P.S. Pulled down develop and love the new editor!

**Comment by aerych** [comment]
![wow-bravo](https://cloud.githubusercontent.com/assets/1435271/6137901/686999c4-b142-11e4-8b59-e6e22a894e8a.gif)
@lewiguez Awesome find and report.  Our mantra tends to be "trust our API"s, and this sounds like a bit of an edge case. However, we want to avoid crashes, and patches are *always* welcome. :)  We'd love to take a look.  The easiest way is to just submit a pull request. 
cc @bummytime

**Comment by bummytime** [comment]
@lewiguez Thanks for the *detailed* report! I second what @aerych said in that pull requests are indeed welcome. 

> P.S. Pulled down develop and love the new editor!

Excellent! Glad you liked it. It will be going live for all users VERY soon.

**Comment by lewiguez** [comment]
OK. Sounds good. I created a pull request.
