### ISSUE TITLE
Posts and pages don't indicate visibility in list view

### ISSUE THREAD

**Issue by debex** [wordpress-mobile/WordPress-iOS#3244]
When viewing the list of posts or pages, you can see an indication of status for any posts that are not published: either *Pending* or *Draft* appears above the post/page title, as shown in the 3rd and 4th post titles in the image below:

![posts-list-mobile](https://cloud.githubusercontent.com/assets/8136035/6149043/e4db0b82-b1d3-11e4-9d5d-73801646b553.png)

It would be helpful if visibility (either password or private) also was indicated within the list view; otherwise there's no indication, either in the list or when viewing/editing the post within the app, that the post does not have public visibility. You can only see that by going into the post settings. 

My concern here is that users may set a post/page to private, forget (or not realize) that they did so, and then end up confused when they can see the post in their app but no one else can see it online.

Here's how the list looks in wp-admin, in comparison:

![posts-list](https://cloud.githubusercontent.com/assets/8136035/6148914/f8c79210-b1d2-11e4-8acd-070501553655.jpg)

I checked with Pages and found the same thing (I indicated published/pending/draft and visible/password/private in the title, to keep them straight):

![pages-list-mobile](https://cloud.githubusercontent.com/assets/8136035/6149121/83ff0074-b1d4-11e4-97d7-9facc33f8005.png)

**Comment by SergioEstevao** [comment]
@aerych do you mind to have a look on this while you do your Calypso redesign?

**Comment by aerych** [comment]
The posts/pages UI refresh will address this. Leaving it open for now.

**Comment by aerych** [comment]
This is mostly implemented with the new list card style. We need ways to indicate posts that are private, or password protected but we'll do that in separate PRs.  
Closing this one.
