### ISSUE TITLE
Reader: Add tracking metrics to the site preview. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3250]
Let's if its accessed, and if its accessed from a list or from a detail. Let's also see how often the site's viewed via the in app browser. 
cc @sendhil

**Comment by aerych** [comment]
Maybe also how many details are viewed from the preview list.  An easy way to check is to look at the ReaderPostStyle property

**Comment by maxme** [comment]
Note: events have been created in wpandroid: https://github.com/wordpress-mobile/WordPress-Android/pull/2329/ ("Reader - Blog Preview")

**Comment by aerych** [comment]
Closed in #3250
