### ISSUE TITLE
CRASH: img meta data

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS#3251]
logs: https://cloudup.com/cow8OzWUog8

repro inconsistent: got it multiple times on ios7, iphone5s; couldn't repro on ios8, ipadmini

- create new post
- add an image
- tap image to initiate "edit"
- tap image again to view img settings
- close
- tap img to initiate "edit"
- tap image again to view img settings
- close
- tap img to initiate "edit"
- tap off img to cancel edit
- tap img to initiate "edit"
- crash

cc @aerych

**Comment by bummytime** [comment]
Closing. I think this should be fixed here: #3327
