### ISSUE TITLE
Switching Blogs when writing a Post is not moving or removing the  images

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#3253]
How to replicate
- start a new post
- write some text
- add some images 
- switch site/blog using the drop down menu.

Expected result:
- The post should be assigned to the new blog and all the content should be switched to new site or at least all the text and the images  removed.

What happens:
- The post is copied to the other blog all text content is copied,  media links are kept but point to the previous blog.

**Comment by SergioEstevao** [comment]
@bummytime , @meremagee , @diegoreymendez what do you think about this?

**Comment by diegoreymendez** [comment]
Well, for starters I'm not a big fan of the blog picker being inside the editor for two reasons:

1. A transfer operation while you're editing a post can bring up several different exceptional cases to break things.
2. The blog picker takes up space in the editor in a not-very-standard way, while picking a blog is something you could do before entering the editor.  Transferring a post could also be done outside of the editor with a progress bar in case the content includes images or video.

That said, the transfer operation should make sure all contents are moved from blog A to blog B - which includes the images.  We just need to make sure we write the code to do this.

**Comment by diegoreymendez** [comment]
As to how to proceed we'll need to:

- Also migrate the media, when changing blogs.
- Add some sort of progress bar for the user to see.

**Comment by SergioEstevao** [comment]
As first fix I think we can do the same as before, just remove the media. Second phase we can think in a way to move all the media.

**Comment by meremagee** [comment]
Please see https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/243 for alert copy

**Comment by bummytime** [comment]
@SergioEstevao @diegoreymendez why don't we use this issue: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/243 for the UX refactoring of the blog picker (or let @thianhlu create a new issue as a spec). I agree that we should prolly remove the ability to switch blogs from the editor itself.

> As first fix I think we can do the same as before, just remove the media.

Seems like a good plan for 4.9

> Second phase we can think in a way to move all the media.

Maybe a feature for  5.0 or beyond?

**Comment by meremagee** [comment]
> we should prolly remove the ability to switch blogs from the editor itself.

things to consider: 
- there is a blog picker on editor in [web](https://cloudup.com/cwmCeN8aQbu)
- we're still defaulting to the top blog in the alphabetical list, not default blog - this make starting a draft on the wrong post very easy
- single site users (majority) would never run into an issue here
- there has been a blog picker in the ios app for a long time, but it's been inconsistent, only appearing if you hit "new post" from reader/my sites. It disappears and leaves you context-less if you hit "new post" from blog detail. 

I'd like to remove my bias as a heavy multi-site user by at least doing some user testing/usage analysis here before we change the newly implemented behavior.

![](https://cloudup.com/cwmCeN8aQbu+)

**Comment by diegoreymendez** [comment]
> I'd like to remove my bias as a heavy multi-site user by at least doing some user testing/usage analysis here before we change the newly implemented behavior.

Just as a note - we'll not make any changes if they're not approved by T or by you.  No worries about that @meremagee! :+1: 

I think your points are very good.  It'd be nice to revisit this discussion after we can address the points in your list that can be improved (like defaulting to the default blog).  I also like the idea of looking at the numbers to get an idea.

I still don't like it being inside the editor though (for the reasons of my first reply), but I guess we can discuss it moving forward - no rush.

**Comment by thianhlu** [comment]
Great points by @meremagee on the multi-site bias. The perfect solution is @SergioEstevao mentioned, is seamless and all content gets moved over (text, images, etc) in one swoop. Let's keep track of this request as well and tackle it when appropriate. Most likely past 5.0

**Comment by kurzee** [comment]
This issue still replicates, although with a warning:

![simulator screen shot oct 27 2016 5 23 00 pm](https://cloud.githubusercontent.com/assets/1873422/19787776/271b108c-9c6a-11e6-9246-57cb728dd43c.png)

However the media still points to the originally uploaded site.

**Comment by rachelmcr** [comment]
I tested this issue again, and now the "Change Site" message that pops up is accurate. You can switch sites, but uploaded media is removed from the post.

I'm closing this issue as it seems to be working as expected, and further discussion about the site switching flow can be discussed in https://github.com/wordpress-mobile/WordPress-iOS/issues/6218.
