### ISSUE TITLE
Switching Blogs when writing a Post is not deleting the post from the previous blog

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#3255]
How to replicate
 * start a new post
 * add some content
 * close post and save draft
 * open a post again
 * switch site/blog using the drop down menu.

What happens:
 * The post is copied to the other blog but a copy is kept on the previous blog

What should happen:
* The post should be assigned to the new blog and the previous post should be remove from the old site

**Comment by kurzee** [comment]
This appears resolved since a user can't change site's on a saved draft/post.
