### ISSUE TITLE
Implement 1Password Support

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#3261]
If the 1 Password extension is available (iOS 8) let's:

- Show the 1Password action button in the spot in which the 'show password' button currently is.
- If the user begins typing on any of the textFields, let's fall back to the 'Show Password' button.

**Comment by astralbodies** [comment]
Duplicate of #2170?

**Comment by jleandroperez** [comment]
@astralbodies huh duplicate indeed!.

Closing in favor of #2170 !
