### ISSUE TITLE
Reader: Freeze due to WebCore deadlock when viewing some posts.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3283]
We've found a case where a [post in Freshly Pressed](https://inpoortasteblog.wordpress.com/2014/11/11/fully-developed-nation-deeply-regrets-brief-affair-with-fred-durst/) was causing the app to freeze.  Some debugging showed that the post was loading a Getty image via an iFrame, which the app tries to accommodate via a UIWebView. A deadlock was occuring when setting the page's viewport settings. 

Props @jleandroperez who first noticed the freeze.

**Comment by aerych** [comment]
Thread:
![screen shot 2015-02-17 at 11 19 01 am](https://cloud.githubusercontent.com/assets/1435271/6233193/e142657a-b696-11e4-9fc3-5fa38847e379.png)

**Comment by jleandroperez** [comment]
@aerych nice catch!
