### ISSUE TITLE
Track Today Extension usage in analytics

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3306]
Sounds easier than it is since we don't include the analytics pod and it sort of is a separate app.

**Comment by SergioEstevao** [comment]
@astralbodies  any new thoughts on this?

**Comment by astralbodies** [comment]
@SergioEstevao I'll assign this to 5.2 since it's a minimal amount of work

**Comment by astralbodies** [comment]
Scratch that, I remember now why I haven't done it yet. I'm waiting for modules because otherwise I need to bring another pod or three into the project.

**Comment by astralbodies** [comment]
Yeah I'm just putting this back into Someday ... needs architectural changes and I don't have the cycles to work on it this release.
