### ISSUE TITLE
Integrate 1Password into JetpackSettingsViewController

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#3310]
#### Steps:
1. Perform a fresh WPiOS install.
2. Sign into a self hosted website.
3. The *JetpackSettingsViewController* screen will be displayed.

**Expected**:
The username field has the 1Password-Lookup button.

**Comment by SergioEstevao** [comment]
@jleandroperez any progress on this?

**Comment by jleandroperez** [comment]
@SergioEstevao no progress on this one (yet). I'm delaying this one, since it may become obsolete after #3367.

**Comment by jleandroperez** [comment]
Closing this one in favor of #3367, since both, JetpackSettingsViewController and LoginViewController share almost everything (except, of course, for the service layer calls).
