### ISSUE TITLE
Logging in self-hosted causing two Blog instances in the db/screens

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3316]
1. Start the NUX.
2. Log in with your self-hosted Jetpack-enabled site using the local admin/password/url combo.
3. When prompted for WordPress.com credentials, enter them.
4. After success, look at the sites in My Sites. Notice the self-hosted site under "Self-hosted" and also the site is listed under "Username's Sites". One comes from WordPress.com autoconfig, the other the self-hosted credentials.

cc: @sendhil

**Comment by koke** [comment]
This should have taken care of the dupe self hosted: https://github.com/wordpress-mobile/WordPress-iOS/blob/4a1b8412d392bf39b9f9e30cfde10a412dfb3de9/WordPress/Classes/Services/BlogService.m#L521

I can't reproduce this in a test blog, can you consistently reproduce or debug that method?

**Comment by astralbodies** [comment]
Yup I can consistently reproduce the behavior.

**Comment by astralbodies** [comment]
Sites that came through with WordPress.com connection:
![img_5030](https://cloud.githubusercontent.com/assets/373903/7145139/a7081f4a-e2af-11e4-811f-0fac91e7e94c.PNG)

Self-hosted Site:
![img_5031](https://cloud.githubusercontent.com/assets/373903/7145143/a8d868e8-e2af-11e4-9145-5ea9e605da65.PNG)

**Comment by koke** [comment]
Could you set a breakpoint at https://github.com/wordpress-mobile/WordPress-iOS/blob/4a1b8412d392bf39b9f9e30cfde10a412dfb3de9/WordPress/Classes/Services/BlogService.m#L540 and see if there's a mismatch in xmlrpc/ID?

**Comment by astralbodies** [comment]
I'm going to get back to this today .. sorry :worried:

**Comment by astralbodies** [comment]
It looks like this is resolved in develop. Sorry for leaving you hanging for so long @koke!
