### ISSUE TITLE
Img meta data - size doesn't work

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS#3322]
image `Size` in "edit" modal does not set correct h/w in post. It appears to be overridden by the default/original upload size setting or by h/w=0.

- example where it gets overridden by default upload size (meta settings add "class="size-large" though meta says "large - 640 x 480"): https://cloudup.com/iekOCcC5HBd
- example where it is set to "small" in img settings > makes height & width = 0 in html until published > publish and it's overridden by default upload size: https://cloudup.com/clOwgPg9TKt

note: if themes set image size based on class (size-small, size-medium, and size-large), then let's remove dimensions or make them dynamic.

cc @aerych

**Comment by aerych** [comment]
I don't understand this one.

**Comment by bummytime** [comment]
@aerych I took a quick peek at this. I think the problem is that we are adding ```height``` and ```width``` attributes of zero when you change the image size.  For example:

```html
<img width="0" height="0" alt="" src="https://bummypublic.files.wordpress.com/2015/02/img_06981.jpg" title="" class="size-medium">
```

**Comment by bummytime** [comment]
Potentially related: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/266
