### ISSUE TITLE
CRASH: img meta data

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS#3327]
log: https://cloudup.com/cm04GUS1CV0

reproed on ios7/iphone5s:
- open existing post with an img
- tap edit to make post contents editable
- tap img to bring up 'edit' overlay
- tap img again to open img details dialogue
- close img details
- crash

cc @aerych

**Comment by aerych** [comment]
Dug into this a bit.  It looks like we're getting a crash in WebCore when transitioning from the image detail modal, back to the editor. Only on iOS7, and it doesn't happen 100% of the time.  It looks like there might be a race condition between changes to the DOM and the view controller's transition animation.  The trigger seems to be when the DOM is updated during the transition in such a way that it results in invalid geometry in the UIWebViews graphics context.  
Yay iOS7 UIWebView. :P

**Comment by aerych** [comment]
Closed in #3329
