### ISSUE TITLE
Nuke duplicate UIWebView wrappers

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#3331]
We've got several class'es that wrap up UIWebView:

- [x] WPWebAppViewController
- [x] WPWebBridge
- [x] WPChromelessWebViewController

Let's analyze if it's possible to have a single tool to do the job. And if possible, proceed to cleanup the duplicated code.

/cc @aerych =D

**Comment by aerych** [comment]
WPWebBridge and WPWebAppViewController can just go away as soon as we replace Friend Finder with a native option. :)

WPChromelssWebViewController can go away as soon as @astralbodies is ready to drop webstats from the app :)

WPWebViewController,.... that guy just needs some love.

**Comment by aerych** [comment]
Following up, we removed `WPWebBridge` and `WPWebAppViewController`in #3600.

**Comment by jleandroperez** [comment]
@aerych **wow**, thanks for the awesome update!. Your coffee is way stronger than mine Eric!

**Comment by jleandroperez** [comment]
Closing this in favor of #4561, where @astralbodies nuked ChromelessVC. (YAY!)
