### ISSUE TITLE
Img meta data - make dimensions proportionate

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS#3332]
dimensions for image size in img details modal should be proportionate to original img as they are in wp-admin image editor: https://cloudup.com/cCMWGSDpacd

for example, this is a square image but the size appears to be hardcoded as rectangular:
![](https://cloudup.com/iekOCcC5HBd+)

related https://github.com/wordpress-mobile/WordPress-iOS/issues/3322

cc @aerych

**Comment by hoverduck** [comment]
29Oct15 Bug Scrub

Closing - appears to be fixed.  I uploaded square and slightly-off-square images and the size selections appear to scale appropriately.  Using the internal beta 5.7.0.20151026.
