### ISSUE TITLE
Infinite scroll through posts skips dates on second refresh

### ISSUE THREAD

**Issue by JasonSnow-Mad** [wordpress-mobile/WordPress-iOS#3334]
Reported in helpshift chat #14510 

Issue is on iOS with App version 4.8

Tested and issue is not present on App version 4.7.1

Steps to recreate:
1) In a WordPress.com hosted site, go to Blog Posts with lots of posts over a wide date range
2) Scroll for the refresh of the Posts List.
3) See date jump.

This does not appear to be affecting WordPress.org sites.

**Comment by aerych** [comment]
I tweaked the description to remove a couple of links.

**Comment by SergioEstevao** [comment]
@aerych does your Post refresh branch addresses this issue?

**Comment by aerych** [comment]
> does your Post refresh branch addresses this issue?

I haven't been able to reproduce so I can say for sure if it does. In theory it wouldn't as the syncing logic has not changed.

**Comment by SergioEstevao** [comment]
Ok I was able to reproduce and I think I know what is the problem, I will  sort this out.
