### ISSUE TITLE
One cannot make use of one's own media library

### ISSUE THREAD

**Issue by southp** [wordpress-mobile/WordPress-iOS#3344]
There is no way users can make use of media library of their wordpress blog when edit a post.

Two specific cases I encountered:

1. I can't reuse the same photo I uploaded even if it's there.
1. When I create a post with a feature image which is also inlined somewhere in the post, I can't use the same uploaded one, because "insert an image" and "set a feature image" both upload the picture as different copies.

As the blog space is limited, I think it's very important to enable users to reuse materials in the app easily.

**Comment by sendhil** [comment]
@southp thanks for the report. Just to let you know getting a media library up and running is definitely on our radar for the year.

**Comment by southp** [comment]
@sendhil Good to know! Looking forward :)

**Comment by beaucollins** [comment]
See #3456

**Comment by SergioEstevao** [comment]
Media from the WordPress media library is now available to pick on the media picker since version 5.3
