### ISSUE TITLE
Post formats - default to setting in wp-admin

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS#3351]
Site owners can change the default post format for their blog/site in general > writing. The mobile app should reflect this by setting the post format to the default type for each blog upon post creation. 

https://cloudup.com/cIb86ufhApQ

**Comment by rachelmcr** [comment]
I tested this in both a WordPress.com and self-hosted site in the latest 5.8 beta. I confirmed that the default post format I had selected for those sites appeared under Settings in the app, and as the default in the post editor. Closing this issue as resolved.
