### ISSUE TITLE
Merge LoginViewController and JetpackSettingsViewController

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#3367]
Both ViewControllers share several key features:

- One Password Integration
- Keyboard Handling
- Username / Password / Multifactor Code

Let's proceed as follows:
- [ ] Move LoginViewController's UI code over to a Interface Builder file
- [ ] Move JetpackSettingsViewController specific code over to LoginViewController
- [ ] If needed, add a NIB specifically to handle JetpackSettingsViewController interface

**Comment by koke** [comment]
There's a bunch of code that might be useful for this in https://github.com/wordpress-mobile/WordPress-iOS/compare/feature/2847-new-jetpack-login-screen

Also see #2847. The new Jetpack screen supports setting the username (plus email/gravatar), which could be useful for the regular re-auth flow

**Comment by jleandroperez** [comment]
(Just in case): this issue is on hold until #3512 is merged.

Thanks for the tips @koke!!

**Comment by jleandroperez** [comment]
Closing this one since `LoginViewController` has been actually refactored into multiple pieces.
