### ISSUE TITLE
build error: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by inix** [wordpress-mobile/WordPress-iOS#3395]
I download codes and pod install,open workspace,try to run on simulator and got following errors:

<pre>
~/WordPress-iOS/Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:117:21: 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.
</pre>

Anyone can help?
Thanks

**Comment by sendhil** [comment]
@inix - are you using Cocoapods 0.36? If so can you try 0.35?

**Comment by inix** [comment]
hi,yes,after using vesion 0.35,build process is OK now.

**Comment by inix** [comment]
Is it acctually an issue?

**Comment by sendhil** [comment]
The problem is that version of AFNetworking doesn't work with CocoaPods 0.36. When they issue an update it should work just fine.

**Comment by inix** [comment]
OK.I will close this issue.Thanks
