### ISSUE TITLE
Friend Finder: Problems connecting to Twitter and Facebook

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3408]
Reported: 

Trying to connect to Facebook and Twitter to look for friends’ blogs. Navigated to the Friend Finder tab, selected Facebook and “OK” on the access prompt but it failed.

There seems to be no other way to add WordPress to the allowed apps in the Facebook settings. Replication steps below.

Note: tested this on version 4.8.

Replication Steps:

Facebook

    Open the WordPress or WP Internal app.
    Go to the Reader tab
    Tap on the Tag icon in the top-right corner
    Tap on the Friends bar at the bottom
    Tap on “Facebook” then “OK” on the access prompt to get the failure notification.

Twitter

    Navigate to the Friend Finder by following the steps above.
    Tap on Twitter, allow access and it connects properly (shows up under Twitter settings). However, it gets stuck on “Searching 0 friends”:

**Comment by kwonye** [comment]
In `[WPFriendFinderViewController findFacebookFriends]` it's getting an `ACErrorPermissionDenied` with description: `The Facebook server could not fulfill this access request: no stored remote_app_id for app (404)`

Looks like the issue is that the iOS access is not open in the WordPress app on facebook. I can't look there but whoever can should verify the app is not is sandbox mode.

**Comment by codebykat** [comment]
It is *not* in sandbox mode. Can someone clarify more specifically what we need to change?

The only thing I found that might be relevant is that there's an "Add Platform" section that looks like this:

![screen shot 2015-03-26 at 11 40 02 pm](https://cloud.githubusercontent.com/assets/52152/6863552/7f976f08-d411-11e4-9105-e1b589a4576d.png)

**Comment by codebykat** [comment]
Indeed, <a href="http://stackoverflow.com/questions/12555799/mac-os-x-facebook-login-failed-no-stored-remote-app-id-for-app">StackOverflow</a> seems to think we need to add the "bundle ID".

**Comment by codebykat** [comment]
For future reference.

![screen shot 2015-03-27 at 8 23 57 am](https://cloud.githubusercontent.com/assets/52152/6870744/47c05e7e-d45b-11e4-88af-ec666c8143f7.png)

**Comment by jkudish** [comment]
FYI: I’ve had to disable this temporarily until the app is re-reviewed to comply with v2.3 of their API.

**Comment by jkudish** [comment]
Setting restored now

**Comment by aerych** [comment]
Closing as we've removed the hybrid friend finder.
