### ISSUE TITLE
Create a Helper for checking logged in status

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3409]
We have several places in the app where we need to check a user's logged in status.  A lot of code is duplicated for these checks.  It would be nice to have a helper (maybe on WPAccount) for a one line check and replace all the duplicated code.

**Comment by aerych** [comment]
h/t @jleandroperez

**Comment by jleandroperez** [comment]
Thanks for adding this one Eric!. @astralbodies probably won't like it, but.. maybe a static getter in `AccountService` would be the right spot!.

**Comment by astralbodies** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by aerych** [comment]
> NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

Ha ha! 

Well, service classes should be stateless as possible which is why I was thinking WPAccount.  However, since `WordPressAppDelegate` is already listening for `WPAccountDefaultWordPressComAccountChangedNotification` maybe it makes sense to have a helper method there?

**Comment by sendhil** [comment]
Macro anyone ;)?
