### ISSUE TITLE
Reader: Adjustable font size on post detail

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3413]
Provide a way for user's to adjust the font size of the reader detail

**Comment by kurzee** [comment]
Maybe for the detail refresh, likely following iOS system font sizing and accessibility.

**Comment by elibud** [comment]
Yes we will use iOS dynamic type for this.
Lets keep only this issue https://github.com/wordpress-mobile/WordPress-iOS/issues/7068
