### ISSUE TITLE
Redacted

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3415]
When using the reader, sometimes you see a story that is interesting, but you don’t have time to read. It would be nice to have a way to flag a story as “read it later”, and a way to view a list of stories flagged this way. 

This feature should:
* be implemented only in the client since there is no REST API support
* be available in the signed out reader. 
* display an icon or button in the post cells to save a post for later reading. 
* provide a way to access a list of posts saved for later.
* remove a saved post from the saved list once its been read, including if it was not read from the saved list. 

Bonus:
* display an notification that there are unread saved stories after a day or two.

**Comment by supernovia** [comment]
Leaving a note so can follow up with this person if we ever implement this:
https://twitter.com/PrincessicaOB/status/646190504674131968

**Comment by rachelmcr** [comment]
Another user requested a Read It Later feature like this in the Reader, to avoid having to use a separate, third-party app to save posts and read them later.
