### ISSUE TITLE
Add support for Clang Format in the project

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#3423]
Support [Clang Format](http://clang.llvm.org/docs/ClangFormat.html) to do automatic code format following [Automatic code guidelines](https://github.com/wordpress-mobile/WordPress-iOS/wiki/WordPress-for-iOS-Objective-C-Style-Guide).

**Comment by koke** [comment]
Also interesting: https://github.com/realm/SwiftLint

**Comment by diegoreymendez** [comment]
I'm closing this ticket for the time being, as Clang Format offers no support for Swift, and there seems to be no plan to support it for the time being.
