### ISSUE TITLE
Post/Page revisions appear for wpcom blogs

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3428]
A change in the v1.1 REST API returns any white listed post type, including revisions.  

In the app when a blogs content is synced from the blog details screen it queries for new posts and specifies a type of "any".  The idea was to fetch posts and pages in one pass, however we don't want the revisions.

**Comment by bummytime** [comment]
Fixed here: https://github.com/wordpress-mobile/WordPress-iOS/pull/3429
