### ISSUE TITLE
Reader: adding img of post above each post

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS#3437]
Each entry for Freshly Pressed in reader contains a screenshot of the themed/published post above the content - within reader list as well as post view, even if post has a featured image

![](https://cloudup.com/cOhzm1Fvmxh+)

https://lookback.io/watch/3z3rHcfcXMfmNbhwX

cc @aerych

**Comment by aerych** [comment]
@SergioEstevao Please don't make assignments like this. If its not something that i have on my roadmap its probably going to get ignored. :)

**Comment by aerych** [comment]
Closing.  The issue was tied to a web tool error that has since been resolved.
