### ISSUE TITLE
Allow multiple sites in Today Widget

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3445]
Related: http://wptavern.com/how-to-add-a-wordpress-sites-pageview-and-visitor-count-to-the-ios-notification-center

Allow for multiple sites to be configured in the today widget. Suggestion is to swipe like in a page controller. Will probably need to rethink UX for configuring sites on the app side.

**Comment by rachelmcr** [comment]
Here's how the Today Widget currently looks (support for a single site) in the iOS 10 Notification Center:

![2016-10-18 14 34 44](https://cloud.githubusercontent.com/assets/8658164/19481238/2dc2956c-9545-11e6-816e-46999e51c39f.png)

Tested on iPhone 6, iOS 10.0.1, WPiOS 6.6.0.20161012

**Comment by ScoutHarris** [comment]
Pinging @SylvesterWilmott as we'll soon be updating the Stats widgets. If this is included, it'll get done as part of that project.
