### ISSUE TITLE
Edit Site View Controller - const cleanup

### ISSUE THREAD

**Issue by garza** [wordpress-mobile/WordPress-iOS#3450]
Meant to submit this a while ago, after fixing #3128 , wanted to do some further cleanup on EditSiteViewController, mostly to pull out any numbers that could be better identified with constants

Used BlogDetailsViewController as a reference as it looked a bit cleaner.  Please review, wouldn't mind improving this a bit more.

**Comment by sendhil** [comment]
Closing because of #3451
