### ISSUE TITLE
Japanese Kanji conversion does not work on HTML mode

### ISSUE THREAD

**Issue by naokomc** [wordpress-mobile/WordPress-iOS#3452]
Tested on v4.9 (iPhone 5s with iOS 8.2).

Steps to reproduce:
1. Switch to Japanese input method, using the Settings app.
2. Make sure the Visual Editor is turned on under Me > Settings on the WP app.
3. Open a new post editor screen and tap the HTML button in the Editor toolbar.
4. With Japanese mode, type "TESTO" into the post title field.

It should look like this (this is a screenshot taken without tapping the HTML button). Note the color of the text and optional selections above the keyboard.

![Visual mode](https://cloud.githubusercontent.com/assets/34067/6780142/e2c39d2c-d1a5-11e4-8f92-4385d575ad4d.png)

Here's the current screenshot. No options to select, and the title is in black (Hiragana is automatically selected).

![HTML mode](https://cloud.githubusercontent.com/assets/34067/6780143/e2c608a0-d1a5-11e4-9207-a9cd4e12d52c.png)

**Comment by sendhil** [comment]
cc @bummytime

**Comment by bummytime** [comment]
Thanks for reporting this @naokomc! I am moving this issue over to the editor repo:

https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/604
