### ISSUE TITLE
LoginViewController is presented to a logged in user, being inside app without possibility to cancel

### ISSUE THREAD

**Issue by knutigro** [wordpress-mobile/WordPress-iOS#3453]
To reproduce:

1. Log into app using wordpress.com account, without adding wordpress site
2. When inside the app, click on Addpost (in the WPTabBarController)
3. Now user is taken to LoginViewController but cancelbutton is not visible.
4. User is now stuck in this mode and will have to log in again.

**Comment by jleandroperez** [comment]
Closed via #3454. Thank you @knutigro!
