### ISSUE TITLE
Allow user to browse and use blog's media library

### ISSUE THREAD

**Issue by beaucollins** [wordpress-mobile/WordPress-iOS#3456]
Currently the post and page composer is only able to use images and media from the phone's local media library. The user should also be able to browse the images hosted on their blog's media library.

Feature should include the ability to:

- [ ] Browse media from blog's online library
- [ ] Insert media into a page or post using the composer
- [ ] Make media available for composing while network is not available
- [ ] Use XMLRPC API

**Comment by sendhil** [comment]
fyi @bummytime @SergioEstevao

**Comment by SergioEstevao** [comment]
@beaucollins why use XMLRPC API? It should use REST and XMLRPC API.

**Comment by sendhil** [comment]
@SergioEstevao XMLRPC API will hit the largest chunk of users.

**Comment by bummytime** [comment]
From another user:

> An iOS user says that he relies heavily on pictures taken on his phone when he blogs. He doesn’t blog with our app per se, but would like a fast way to upload his images to his media library using it, similar to the Android app. The way he does it right now is he creates a new blog post in the app and upload his images from there, then deletes the post. It’s a workaround at best. :) It would indeed be nice to have a smarter way of doing it.
>
> That said, the ability to insert images into a post or page from the media library would be cool to have too.

**Comment by SergioEstevao** [comment]
Media from the WordPress media library is now available to pick on the media picker since version 5.3
