### ISSUE TITLE
Tweak design on Jetpack connection screen

### ISSUE THREAD

**Issue by melchoyce** [wordpress-mobile/WordPress-iOS#3460]
The current Jetpack connection screen looks a bit uneven: 

![img_2193](https://cloud.githubusercontent.com/assets/2846578/6807229/9769d368-d223-11e4-96f2-d7d1c437a5d0.png)

Ex: No margin between paragraphs, centered text is a little wonky, "skip" link at the bottom isn't aligned to the grid. I've made some small adjustments:

![ios-jetpack](https://cloud.githubusercontent.com/assets/2846578/6807262/d7e9b02a-d223-11e4-9264-92bc596234c5.jpeg)

I've left-aligned, widened, and aligned the intro text to the grid, and added space between the the sentences. I've also made the "sign in" button full-width, and aligned the "skip" link to the grid. I also moved the hide/reveal icon over a smidge to be the same distance from the edge as the other icons in the field.

**Comment by sendhil** [comment]
cc @koke when you get back.

**Comment by koke** [comment]
@jleandroperez are you working on this or do you want me to take over?

**Comment by koke** [comment]
Actually, this screen is being replaced by #2847

**Comment by jleandroperez** [comment]
@koke not working on this one (yet). Should we close this one in favor of #2847?

**Comment by koke** [comment]
:+1:
