### ISSUE TITLE
Reader: Move follow toggle to stop inadvertent unfollowing

### ISSUE THREAD

**Issue by shaunandrews** [wordpress-mobile/WordPress-iOS#3462]
In your Blogs I Follow stream its way too easy to accidentally unfollow a site. Unfollowing isn't a common enough action to deserve such a high profile placement in the layout. My suggestion is to move the toggle to the "..." detail sheet. Not only would this help accidental unfollows, but it makes for a more concise header on the card. Here's a few quick mockups:

![smaller header](https://cloud.githubusercontent.com/assets/191598/6826698/b2a8a08a-d2d9-11e4-8d24-8403305b856e.png)

![new follow toggle](https://cloud.githubusercontent.com/assets/191598/6826701/b4e0f122-d2d9-11e4-963d-7050a73bc937.png)

I think this makes a lot of sense in the context of "Blogs I Follow" and other lists. But, for Freshly Pressed (and other places where you're viewing sites that you don't actually follow) maybe the Follow button deserves to stay in its current place.

**Comment by aerych** [comment]
Closed by #4032 and #4280
