### ISSUE TITLE
Visual editor is randomly broken with VoiceOver

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3468]
Original report: https://twitter.com/TheBlurredNerd/status/581207539741753344

> edit/new post text fields are erratic, can't always access them.

cc: @bummytime - if you want me to move this to https://github.com/wordpress-mobile/WordPress-Editor-iOS let me know

**Comment by bummytime** [comment]
@astralbodies would you mind moving this there? I will look at it right away.

**Comment by astralbodies** [comment]
Moved over to https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/608

**Comment by bummytime** [comment]
Thanks @astralbodies !
