### ISSUE TITLE
GPLv2 License

### ISSUE THREAD

**Issue by therealslimjamie** [wordpress-mobile/WordPress-iOS#3483]
Hi,

As you know, the iOS app source code is licensed under the GPLv2, and any contributions are also licensed under this. However, there are a lot of incompatibilities between the GPL and the App Store terms of service (relating to DRM and the redistribution of signed/encrypted binaries, GPL § 6)

This means Apple could remove the app from the App Store at any point, and any contributors would have a legal ground to have the app pulled if they so decided. 

I would urgently suggest changing the license to something less restrictive like the LGPL.

**Comment by sendhil** [comment]
>I would urgently suggest changing the license to something less restrictive like the LGPL.

Actually, it’s Apple’s license that is the restrictive one, not the GPL.

Thanks for the feedback. WordPress is and always has been GPL licensed.
