### ISSUE TITLE
Upgrade to HelpShift 4.10.2

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3484]
We're currently using HelpShift v 4.8.0 in our Podfile.  This version of HelpShift has a bug where sharing a URL without specifying the scheme (http:// or https://) will still create a hyperlink, but if a user clicks on that link the app will crash. 

This behavior appears to be patched in version 4.10.2.

**Comment by sendhil** [comment]
As this is currently in `release/5.0` - it'll come into `develop` when we merge it back shortly.
