### ISSUE TITLE
Create New Account - no VoiceOver status given to indicating spinner spinning

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3491]
When a user using VoiceOver creates a new account, there is no audible indicator that a remote process is waiting for the next screen to appear or that the account was created successfully.

In general our dismissal of the NUX when a user creates a new account is somewhat anticlimactic even for visual users.

**Comment by bummytime** [comment]
Just verified this issue on the latest internal. The transition from NUX to site menu is indeed very anticlimactic as demonstrated in this video:

https://cloudup.com/cQ2UeWT8nca

We should probably:

1) [Make the activity indicator accessible](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/UIKitUICatalog/UIActivityIndicatorView.html#//apple_ref/doc/uid/TP40012857-UIActivityIndicatorView-SW8)
2) Create some kind of "tada!" message in voiceover after the NUX flow is completed successfully.

**Comment by ctarda** [comment]
@etoledom Apparently this screen is being sunset. I will leave the ticket as in progress for now.

**Comment by etoledom** [comment]
This screen was replaced with the new sign up flow, so we can safely close this issue.
