### ISSUE TITLE
Updated store artwork for next release

### ISSUE THREAD

**Issue by beaucollins** [wordpress-mobile/WordPress-iOS#3494]
New logo artwork for iTunes store. Goodbye to the gradient.

Thanks @thianhlu 

https://cloudup.com/csNNZNWkRFN

[512px Version](https://cldup.com/ftUKuD0ZQq.png)
[1024px Version](https://cldup.com/VkgTA7CGcd.png)

![](https://cldup.com/VkgTA7CGcd.png)

**Comment by beaucollins** [comment]
I'm now hearing that the app store is just displaying outdated graphics.

**Comment by sendhil** [comment]
Those links are inverted ;)

**Comment by sendhil** [comment]
Updated.

![screen shot 2015-04-09 at 6 51 56 pm](https://cloud.githubusercontent.com/assets/437043/7080586/89c9689a-dee9-11e4-84df-2a5705cee8da.png)
