### ISSUE TITLE
Translation doesn't fit in screen on iPhone

### ISSUE THREAD

**Issue by chantalcoolsma** [wordpress-mobile/WordPress-iOS#3501]
When you go to Statistics, two buttons doesn't fit on the screen with Dutch.

![slack_for_ios_upload](https://cloud.githubusercontent.com/assets/867632/6991933/aea2cd32-dab1-11e4-9f85-f8433a399b30.png)

Don't know if the same happens for other languages. Maybe other polyglots could check that.

**Comment by sendhil** [comment]
cc @astralbodies

**Comment by astralbodies** [comment]
Whoops I obviously didn't set the constraints properly on the control. I'll also look at what the strings are for WordPress.com to compare. 

Some day we'll share strings between the codebases :smile:

**Comment by astralbodies** [comment]
@chantalcoolsma this is German, right? Can you let me know if its still broken?

**Comment by chantalcoolsma** [comment]
@astralbodies no it is Dutch. Still happens in the latest version

![image](https://cloud.githubusercontent.com/assets/867632/9348492/fb3d829e-4637-11e5-8874-02936ab8f73d.jpeg)

**Comment by astralbodies** [comment]
Thanks again for the report, @chantalcoolsma! I got the problem fixed but it probably won't make it into WPiOS until v5.6 in a month or so.

**Comment by astralbodies** [comment]
@chantalcoolsma This should hopefully be resolved now in the current App Store version. Can you verify for me? Thanks :)

**Comment by chantalcoolsma** [comment]
Shows okay in version 5.6. However another problem is introduced in the Insights tab:

![img_0107](https://cloud.githubusercontent.com/assets/867632/10135250/86a45172-65ec-11e5-932b-5a64aee34cd4.jpg)

**Comment by astralbodies** [comment]
Closing this - will be resolved in WPiOS 6.0

https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/373
