### ISSUE TITLE
Add general option to resize images before upload

### ISSUE THREAD

**Issue by antwortzeit** [wordpress-mobile/WordPress-iOS#3502]
After heavily using the app during the last week we found ourselves often in trouble with uploading images from both iPhone 6 and 6 plus. Resizing the images before adding them in Wordpress did the trick. So It would be pretty could if the Wordpress app did it itself. Maybe we could provide standardized formats or even allow setting a large side in pixels.

**Comment by bummytime** [comment]
@antwortzeit Did you try using the max image size slider in settings?

![scaled screen_shot_2015-04-06_at_10_13_01_am](https://cloud.githubusercontent.com/assets/154014/7006324/cb67985e-dc45-11e4-9ab3-90b0dd89db7e.png)

**Comment by antwortzeit** [comment]
Damn it, sorry, we missed that. Just looked for the settings per account. This solves the ticket then :-) Thanks!

**Comment by bummytime** [comment]
No worries @antwortzeit  :grinning:
