### ISSUE TITLE
Refresh Post and Page list UI

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3506]
### Post List
- Cells should have a card layout for more context about the post and new options for interacting with the post.
- List should be searchable
- List should have filters for post status.

### Page List
- Cells should have option for modifying status.
- List should have filters for post status.

**Comment by aerych** [comment]
Remaining post list TODOs

### Syncing
- [ ] Adjust syncing and loading more to ignore filters, but always get the next “full page” of posts.

### Author Filters
- [ ] Update Blog model to have author ID field, and isMultiAuthor  bool.
- [ ] XML-RPC: Call wp.getUsers specifying “who” as “authors” to get a count of authors
- [ ] REST:  Call /sites/$site/users to get a count of authors
- [ ] need data model changes to track author ID and whether the blog is multi author (multiple users)
- [ ] Show author filters only if multi author.
- [ ] Add filter logic for multi author blogs
- [ ] Background for bar behind author filter.
- [ ] Navbar color for iPad filter popover

### Search (local)
- [ ] Update predicate based on search string & clear search predicate when search string changes.
- [ ] Can we adjust the iPhone search bar animation at all? (Adam B.)

### Post Cards:
- [ ] “Undo” view for recently trashed posts.  Can use same mechanic as Reader?.
- [ ] Wire up thumbnail & featured images.  Requires data model change to store featured image URL that does not compete with existing featured image logic. Requires logic to pick a good image to display if the user did not set a featured image.
- [ ] Adapt header view depending whether the blog is multi or single author. 
- [ ] Fix initial layout wonkiness. Label is wrongly positioned
- [ ] Create and wire up thumbnail post card.

**Comment by a4jp-com** [comment]
FIltering for the pages & posts would be great.

**Comment by aerych** [comment]
### Fixes and Polish

- [ ] Negative date for scheduled posts
- [ ] Missing no results view when navigating to empty list
- [ ] Missing draft status label
- [ ] Confirm restored posts move to correct list.
- [ ] Glitchy animation when first loading the list. 
- [ ] 1px separator above action buttons
- [ ] Missing table footer spinner when loading more. 
- [ ] Display the table footer for when there are no more posts to show

### Maybe

- [ ] Hide author filter bar when scrolling down, reappear when scrolling up? 
- [ ] Custom viewcontroller transition to display filters

**Comment by aerych** [comment]
We'll handle the following items in individual pull requests:

-  Hide author filter bar when scrolling down, reappear when scrolling up? 
-  Custom viewcontroller transition to display filters
-  Maybe custom background and divider images for author filter UISegementControl. 
-  Can we adjust the iPhone search bar animation at all? (Adam B.)
-  Navbar color for iPad filter popover
-  Glitchy animation when first loading the list.
