### ISSUE TITLE
Fix the project for Xcode 6.3/Swift 1.2

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3514]
Lets fix all the broken things for Xcode 6.3 so we can upgrade and keep moving forward. :smile:

**Comment by nheagy** [comment]
One problem will be that [Travis-CI won't be able to support Xcode 6.3](https://github.com/travis-ci/travis-ci/issues/3216) right away because they don't have any machines running 10.10.3.

**Comment by bummytime** [comment]
:+1:

**Comment by aerych** [comment]
@astralbodies Is this one taken care of?

**Comment by astralbodies** [comment]
Yup done!
