### ISSUE TITLE
Mixpanel Tracker causes fire of event for all trackers

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3515]
In `WPAnalyticsTrackerMixpanel.m` we are tracking when the app is installed and then firing an event to the base analytics object which is causing every tracker to get the event. While I think its important we track fresh installs I think this method is flawed. We really should have no dependencies on lifecycle with a specific tracker and if we do, then the event shouldn't be fired for the entire set of trackers, only the current tracker.

``` objc
- (void)incrementSessionCount
{
    NSInteger sessionCount = [self sessionCount];
    sessionCount++;

    if (sessionCount == 1) {
        [WPAnalytics track:WPAnalyticsStatAppInstalled];
    }
```

Two possible solutions:
1. Do `[self track:WPAnalyticsStatsAppInstalled];` instead which only will record the event with Mixpanel.
2. Abstract out this app lifecycle analysis to somewhere else in the app and track the event there, removing the requirement to use Mixpanel's session count.

cc: @sendhil

**Comment by sendhil** [comment]
Nice catch @astralbodies - this was an accident and tbh i meant for only Mixpanel to catch it and not everyone else. I thin option 1 sounds good to me.

**Comment by rachelmcr** [comment]
I'm not too familiar with how this tracking works — @sendhil did your commit https://github.com/wordpress-mobile/WordPress-iOS/commit/2ec011ddb6d4779828ba5323e3d7a50c7304f58b resolve this issue, or is it still an open issue?

**Comment by sendhil** [comment]
@rachelmcr  - No this is still an issue
