### ISSUE TITLE
Improve post create date handling. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3516]
In #3032, we dealt with an issue where publishing a draft did not update the publish date of a post and in #3290 we always set a draft post's publish date to the current date/time when publishing. 

This patch creates a problem for posts with a draft status, but a correct publish date that is earlier than the current date. An example scenario is when an author gives a published post a draft status while making edits, then changes the status back to publish.  There are probably other scenarios and we've had at least one user comment that the behavior is frustrating. https://ios.forums.wordpress.org/topic/issues-with-49-update

Try this: in wp-admin, create a new post, notice the default publish date is "publish immedately".  Change the date to an earlier date and save a draft.  Notice that the date you set is preserved.  Now publish the draft. The published post also preserves the earlier date.  Ideally we should match this behavior in the app.

I think the proper course is to set a posts create date to the current timestamp _only_ when a new post object is created and make no other changes to the date other than changes initiated by the user. Previously we were preforming checks at publish time to try and determine what the correct create date should be which is tricky and frustrating when the check does not do what it should. 

Thoughts?
cc @bummytime

**Comment by a4jp-com** [comment]
I don't think the publishing date should change from the date when the file is actually published unless that is needed. 

Posts should be sorted in 3 ways as far as I can see:

1. Alphabetically
2. By Date Modified
3. Date Published

Keeping the current sort order would be useful for some people depending on the type of work but adding the 2 other sort orders would make this app a lot better.

This is an example of getting the date modified from WordPress. Sorry it isn't Xcode.

[code]<?php if( get_the_modified_date() != get_the_date() ) echo the_modified_date();?>[/code]

**Comment by bummytime** [comment]
@aerych

> I think the proper course is to set a posts create date to the current timestamp only when a new post object is created and make no other changes to the date other than changes initiated by the user. 

Does this account for the notion of the "publish immediately" setting in wp-admin? Testing it out, it seems to update the publish date to the current time by default...ignoring the actual time a draft was created. Would your suggestion still do this? (Forgive me if I am misunderstanding you.)

**Comment by aerych** [comment]
@bummytime I was just digging into this.  Maybe this is the actual heart of the matter, we have a concept of publish immediately, and we have a user selected date, but we've been trying to satisfy both cases with just the create date field.  I'm thinking it might make sense to have a flag for "publish immedately" for newly created drafts which, if set, would always set the post to the current date when publishing, else the post would use the user selected date. 

Something else that would be good is to add some tests for all the different scenarios.  

I set the 5.1 milestone but it might be better for 5.2 since the scope might be a bit larger than just reverting a previous commit and adding a couple of tweaks.

**Comment by aerych** [comment]
Hmm.... maybe I'm over thinking this.  I think previously we were interpreting a nil value for date_created to mean "publish immedately".

**Comment by aerych** [comment]
Tricky. A draft set to publish immediately in wp-admin has nothing to flag it as such in its XML-RPC result, and returns its create date as its publish date. Hence the original issue I suppose.

**Comment by bummytime** [comment]
@aerych cool. Totes agree that this needs to be re-examined. I think the "publish immediately" (aka "user messed with the date") flag is a good idea, as long as we can figure out how represent this server-side (hence your last 2 comments :grinning: )

> I set the 5.1 milestone but it might be better for 5.2 since the scope might be a bit larger than just reverting a previous commit and adding a couple of tweaks.

5.2 would be my vote

**Comment by aerych** [comment]
Bumped the milestone

**Comment by rachelmcr** [comment]
I tested in beta v. 5.8.0.20151204 and confirmed that this is still problematic there. (For example, a backdated draft is published with the current date/time instead of the date/time that was set on the post.)

>I'm thinking it might make sense to have a flag for "publish immedately" for newly created drafts which, if set, would always set the post to the current date when publishing, else the post would use the user selected date.

I'll add my support for this approach, as well. If there's a way we can flag posts where the user hasn't manually changed the date or previously published the post, and set those posts to publish immediately (current date/time), that seems like the safest way to handle this.

**Comment by diegoreymendez** [comment]
Removing myself from this issue for the time being since I have too many assigned issues.

**Comment by aerych** [comment]
A related user report (h/t Chrissy P)
> User travels and writes offline. When updating drafts, the date defaults to the current date. The user wants to keep the initial date. Right now, they have to go back and change the date after publication. It would be nice to have the option to save the date of the initial draft as the publication date.

**Comment by gracie** [comment]
Related issue in #334381-hc where a user began a post this morning on mobile. They published it this afternoon, and it published with this morning's timestamp.

They expected the post to have a timestamp from when they pressed "publish". The incorrect timestamp (reflecting when they began the draft), buries the post in the Reader.

**Comment by rachelmcr** [comment]
We received another reported of a draft being published with the original creation date instead of the current date. As mentioned above, this also means the post doesn't appear at the top of the Reader so followers don't see it.

Internal ref: AppbotX 28125

**Comment by elibud** [comment]
We need to address two different things for this issue:

1. Publish behavior should be consistent across: Aztec, the current/old editor and the quick Publish action (now it isn't)
2. Whenever Publish is hit for a post that had not been published before, the published date has to be timestamp for when they pressed Publish.

**Comment by rachelmcr** [comment]
> Whenever Publish is hit for a post that had not been published before, the published date has to be timestamp for when they pressed Publish.

There are exceptions to this — if a user intentionally changes the date on the post (e.g. to backdate a post) we should respect that and not set the published date to the timestamp when they press publish.

**Comment by elibud** [comment]
yes @rachelmcr thanks for reminding me of that, I had it in mind but I should've put it there, I will edit that comment.

**Comment by elibud** [comment]
I simply can not find a way, with our current code base + API, to distinguish between a post that has already been published and reverted to a draft from a draft that was never published. I need this to know if I should update the field `dateCreated` on post publishing.
@koke do you have one of your brilliant ideas for this one?

**Comment by koke** [comment]
Sorry, I don't think there are any differences we can rely on :(
But maybe if you roll back a published post into a draft, it's ok to clear the date? I recall seeing some mockups of a two-step publish process that makes date selection more clear, so that could help.

**Comment by elibud** [comment]
@koke yeah I saw that one too, it will help in the long run but I don't think it is something we have scheduled to do any time soon.
As part of: https://github.com/wordpress-mobile/WordPress-iOS/pull/7129 I did some clean up regarding when the "Publish"/"Publish Now" option appears, so now we have a cleaner UI for posting. 
Maybe as part of testing 7.7 @rachelmcr can double check if whenever the "Publish"/"Publish Now" button it display it is OK for us to clear the date to now, and if that is the case we can do those changes.

**Comment by rachelmcr** [comment]
>Maybe as part of testing 7.7 @rachelmcr can double check if whenever the "Publish"/"Publish Now" button it display it is OK for us to clear the date to now, and if that is the case we can do those changes.

I will be AFK for the 7.7 beta/release, so I'd recommend adding this to the call for testing so other beta testers can take a look at it specifically.
