### ISSUE TITLE
Posts with custom statuses not shown for self-hosted sites

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#3520]
As seen in feature request #2420, posts using a custom status are not pulled when connected to a self-hosted site. This can be resolved using the XML-RPC `wp.getPosts` method with the `post_status` parameter set to `any`.

**Comment by sendhil** [comment]
Going to close this as per https://github.com/wordpress-mobile/WordPress-iOS/pull/3521#issuecomment-103972726
