### ISSUE TITLE
Comment: Edit Comment from Notifications and Reader

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3530]
A feature request, it would be nice to be able to edit a comment just made from Notifications (and by extension the Reader).

ht jackiejade

**Comment by ScoutHarris** [comment]
One can now edit a comment from the notification.
- Go to Notifications > Comments.
- Tap one.
- Note the Edit button.

However, one cannot edit a comment from the Reader.
- Filtered Following for a site I'm an admin on.
- Tap the comment button on a post card.
- The only options are Reply and Like. 

@aerych I'm assuming this will be resolved with the Unified Comments project, so I'm closing. Feel free to reopen if you think differently.
