### ISSUE TITLE
Standardise the text and format on all offline alert messages 

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#3546]
Make the alert for offline message the same on the following scenarios:
- Pull to refresh on site posts, pages, notifications, reader, etc..
- When answering to actions from user: reblog, reply, favourite, etc..

**Comment by bummytime** [comment]
Just an update. Still looks to be an issue, but perhaps improved a bit (testing the latest on  `develop`). Refreshing posts and pages yields: 

![2016-12-14 09 31 03](https://cloud.githubusercontent.com/assets/154014/21189000/cbaa629a-c1e2-11e6-8fe6-72df0a1ec4d5.png)

and refreshing notifications, reader, etc will display no errors...silent fail. In addition, the NUX efforts offer the following error when the internet is down:

![2016-12-14 09 42 27](https://cloud.githubusercontent.com/assets/154014/21188875/653fddf0-c1e2-11e6-9972-27907d05b4af.png)

...which seems appropriate in that context.
