### ISSUE TITLE
Reduce unnecessary network calls, and batch requests were it makes sense. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3549]
We have some cases in the app where we make unnecessary network calls. One example is when we synch a blog when navigating to the blog details page. A user with multiple blogs can switch between them quickly resyncing wastefully.

We also have cases where we make multiple API calls for related information (e.g. posts, post formats, categories) which we could be batching. 

Let's review the calls made, limit repetition unless its user initiated and batch what we can batch.

**Comment by sendhil** [comment]
Yes please
