### ISSUE TITLE
Can't install pods in 5.1 branch

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#3555]
After investigating the `pod install` issue in #3553 I've discovered that the Podfile and/or Podfile.lock are in some way preventing pods from being installed fresh.

## To recreate:

`rm -rf Pods`
`pod install`

Cocoapods then quits with an error.

**Comment by sendhil** [comment]
@nheagy is this still an issue for you?

**Comment by nheagy** [comment]
Nope. Between the updated cocoapods support and Xcode this started to work.
