### ISSUE TITLE
Notifications: Badge may not get reset

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#3559]
#### Steps:
1. Launch WPiOS and open the Notifications tab
2. Hit the home button
3. Receive a push notification
4. Tap over the notification

#### Results:
The Badge, which is expected to get cleared out, appears to remain untouched -under unknown circumstances-.

Let's investigate + fix any potential race conditions that might be affecting this flow.

**Comment by c3zh** [comment]
Helpshift issue: https://automattic.helpshift.com/admin/issue/25044/
Speedtest: https://cloudup.com/cdxujk74Ztd
