### ISSUE TITLE
Remove Hybrid Friend Finder

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3572]
Title has it. The hybrid feature is really too broken to justify keeping.  We'll reintroduce it in #1200.
Refs: #3408, #1335, #3331, and #540.

**Comment by SergioEstevao** [comment]
@aerych are you still doing this for 5.1 milestone or can I put in Pending Milestone?

**Comment by aerych** [comment]
Thanks for the nudge @SergioEstevao. PR is up. Switching this to the 5.2 milestone.
