### ISSUE TITLE
Error Message When Accessing Web

### ISSUE THREAD

**Issue by ChrissiePollock** [wordpress-mobile/WordPress-iOS#3579]
WordPress - 5.0
iPad 3
iOS - 8.3
English

User says: It has begun to require authentication details but a) it didn't use to b) there is nowhere to enter them. I have deleted and reinstalled the app but the problem remains.

My app - ![img_0030](https://cloud.githubusercontent.com/assets/2545184/7339152/2673fa02-ec32-11e4-8ba3-a502ea810f30.PNG)

User's App - ![screen shot 2015-04-26 at 4 35 02 pm](https://cloud.githubusercontent.com/assets/2545184/7339154/3e75b32a-ec32-11e4-842e-212133bf9e90.png)

**Comment by Toof** [comment]
This error appears to be the same one effecting customers who are unable to access their Post Previews using the app.

**Comment by Toof** [comment]
In at least some cases, this is resolved by logging out, then logging back in using their WPCOM username rather than their email address.

**Comment by aerych** [comment]
Closing this one as we've iterated on our authentication logic a few times since it was opened and we haven't had any recent reports of this happening. Assuming fixed until it pops up again.
