### ISSUE TITLE
Give stats UIWebView more controls

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3602]
References: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/240

> Can we have these options in the in-app browser – back/forward arrows, page title (with URL at the bottom), refresh and dismiss (x)? Currently, they can only go back, but there’s no way to move forward.

**Comment by SergioEstevao** [comment]
Can I close this @astralbodies?
