### ISSUE TITLE
Make sure when doing multiple sync calls all callbacks are invoked with the correct state.

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#3625]
Details provided by @koke:

> Since the sync/loadMore methods return without calling either succes or callback, the comment loading might get stuck
> 
> https://cloudup.com/c5DxIp-cU1A
> 
> I think the cause is that the blog details view triggers a syncBlog, so if you quickly open comments and pull to refresh, isSyncing is YES so it bails, but it WPTableViewController never learns when the syncing finished, so it never stops "loading"

**Comment by bummytime** [comment]
@SergioEstevao I just tested this issue and it appears to be fixed in the latest develop branch. Should we close this?

**Comment by SergioEstevao** [comment]
Go ahead @bummytime

**Comment by bummytime** [comment]
Thanks @SergioEstevao!
