### ISSUE TITLE
SupportViewController no longer shows log files

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3629]
When `WPLogger` was implemented the CocoaLumberjack file logger was removed from the app delegate and placed under the covers of it. The property on the app delegate was never removed so places that directly accessed the logger, like the support view controller, didn't break the build. None of the log files created by the app are visible when someone selects "Activity Logs" under Me/Help.

@sendhil I think this should get fixed before 5.1 is pushed out to Apple.

cc: @diegoreymendez

**Comment by diegoreymendez** [comment]
Fixed.
