### ISSUE TITLE
Categories: Unable to create a category and set it's Parent

### ISSUE THREAD

**Issue by sandymcfadden** [wordpress-mobile/WordPress-iOS#3634]
When trying to create a new category if you try to select a parent category it doesn't change.
When you save the new category it is a top level and not assigned to the parent category you choose.

**Comment by sendhil** [comment]
cc @bummytime

**Comment by rachelsquirrel** [comment]
Another report on Twitter:
https://twitter.com/tvserieshub/status/632949515046252544

**Comment by SergioEstevao** [comment]
Fixed on version 5.6, @rachelsquirrel @sandymcfadden do you mind to test it on the latest internal version of 5.6.

**Comment by sandymcfadden** [comment]
I just tested and it looks good to me @SergioEstevao. Thanks!
