### ISSUE TITLE
One list to rule them all

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3635]
Let's have just one list of sites for the 'My sites' tab.

Previously, I had discarded the idea because wp.com blogs can be hidden and self hosted can be deleted, so the editing UI look weird.

Here's another idea:

![screen shot 2015-05-08 at 11 06 55](https://cloud.githubusercontent.com/assets/8739/7533556/c3d5b472-f572-11e4-944c-a49d62c5e379.png)

When editing, the self hosted sites and the add site row disapear

![screen shot 2015-05-08 at 11 07 00](https://cloud.githubusercontent.com/assets/8739/7533570/d5ea8a8e-f572-11e4-8725-a9cad2f25586.png)

Then, when you navigate to a self hosted site, there's a new "Remove site" button at the end

![screen shot 2015-05-08 at 11 07 07](https://cloud.githubusercontent.com/assets/8739/7533573/e620b590-f572-11e4-80df-32e84668ff91.png)
![screen shot 2015-05-08 at 11 07 10](https://cloud.githubusercontent.com/assets/8739/7533576/e8b9bf72-f572-11e4-93eb-67c00e9d3e2d.png)

**Comment by koke** [comment]
@jessefriedman ^ since you were advocating for this in the past, does this look good?

Patch: https://gist.github.com/f319f67e67b1ae134c50

**Comment by oguzkocer** [comment]
This looks like a good idea to me. I'd like to cc @mnt since he has worked with me on My Site changes and he might want to chime in :)

**Comment by aerych** [comment]
Having a remove site button in the site details screen feels strange to me.  You are out of the context of where you are removing the blog from. Are you removing it from the app are you removing it from the server?  Will you be able to get it back? 

Is there a way to improve the UI and still manage visibility / removal from the same list?

**Comment by mnt** [comment]
I think the convention of removing a site from the screen after a list is alright, since it matches the convention established in apps like Mail:

![email-account](https://cloud.githubusercontent.com/assets/1396552/7576692/b11264cc-f80e-11e4-91d0-6215ac530a09.png)

That said I would change the "Remove site" text to red; specifically #d94f4f; our shade of alert red from the design handbook.

**Comment by mnt** [comment]
Note the change from a modal to an action sheet for the confirmation dialog. In the text we could reinforce the action, like: 'Are you sure you want to continue? All site data will be removed from your iPhone." The ideal message here helps clarify that the user is deleting a site from the app, not deleting their site from the universe. Someone from Editorial might be able to help improve the copywriting here.

**Comment by aerych** [comment]
Doing this would ease my worries :) :+1:
