### ISSUE TITLE
Connect to WordPress.com cropped on iPhone 5

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3636]
![screen shot 2015-05-08 at 15 09 55](https://cloud.githubusercontent.com/assets/8739/7536899/4e170700-f594-11e4-85fe-2c48ae491636.png)

I guess we all have big iPhones these days?

**Comment by oguzkocer** [comment]
This was my fault, thanks for bringing it up @koke! I'll take care of it.

**Comment by oguzkocer** [comment]
Closed in #3656.
