### ISSUE TITLE
A scheduled post should respect the phone's time zone when displaying the schedule time

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#3642]
If a user schedules a post in one time zone, shifts time zones and then looks at when the post was scheduled the time will still be in the blog's original time zone. We should rather display the time in the phone's time zone so as to not confuse the user.

**Comment by rachelmcr** [comment]
I checked this in the latest 5.8 beta and it looks like we're doing this now. I have a blog set to a timezone that is 6 hours off of my own timezone. I scheduled a post on that blog. On the Blog Posts screen I see a relative time ("in 2h") and in the post settings in the editor under "Scheduled for" I see the scheduled time according to my/my phone's timezone (not the blog's timezone).

Closing as resolved.
