### ISSUE TITLE
NUX: Broken login screen layout

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3649]
Related to #1643
To reproduce:
- On an iPhone, go to the Me tab and disconnect from wpcom. 
- Tap to connect to wpcom
- On the sign in screen, tap the help icon to view the support screen. 
- Rotate the phone to landscape orientation. 
- Tap the cancel button to return to the sign-in screen. 

The result is the sign in screen's content is now squashed to the top of the screen. 
You can also reproduce this by starting in landscape orientation.

![ios simulator screen shot may 12 2015 4 25 54 pm](https://cloud.githubusercontent.com/assets/1435271/7599016/5bbf39a8-f8c4-11e4-84c9-e7c460b80286.png)

**Comment by rachelmcr** [comment]
I tested this in the latest stable release (5.6.1) using the steps above, and couldn't reproduce. @aerych is this still an issue you can reproduce?

**Comment by aerych** [comment]
Yep yep.  Took it for a spin a couple of days ago when I was triaging some old issues.  I'll double check the steps, they might need updating.

**Comment by aerych** [comment]
I can currently reproduce with the following steps in the iOS Simulator
1. While signed out of the app and viewing the sign-in screen, rotate to landscape orientation.  The Sign-in screen requires portrait orientation and does not rotate. This is expected. 
2. Tap the info (?) icon to view the support screen.
3. Rotate to Portrait orientation.
4. Dismiss the support screen.

**Comment by rachelmcr** [comment]
Thanks for the updated steps! I can also reproduce with those steps on my iPhone 6.
