### ISSUE TITLE
Send SMS text is cut off in Spanish

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3664]
![screen shot 2015-05-14 at 13 30 09](https://cloud.githubusercontent.com/assets/8739/7631070/8f55a28c-fa3d-11e4-977d-ddda8e9c690c.png)

**Comment by sendhil** [comment]
@jleandroperez  :-p

**Comment by jleandroperez** [comment]
(None of my devices is in spanish, i swear!). Issue claimed!.

Thanks @koke!
