### ISSUE TITLE
"Be the first to leave a comment", but I can't

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3672]
When there's not a wp.com account and you visit the comments on a post with no comments, it looks like this

![ios simulator screen shot 15 may 2015 10 56 53](https://cloud.githubusercontent.com/assets/8739/7649858/3955954a-faf1-11e4-81ad-0663f46af9dd.png)

I'm prompted to leave a comment, but there's no comment form

**Comment by rachelmcr** [comment]
I reproduced this in 5.7 (stable release). In the main Reader view, posts without comments don't show the comment icon. However, when you tap through to the full post view, you see the comment icon at the bottom of the post and can get to this screen.

It seems like a straightforward fix would be to remove the comment icon, although we could also show a login screen there to encourage users to log in to a wp.com account to leave a comment.

**Comment by koke** [comment]
I can't reproduce this anymore in 6.3
