### ISSUE TITLE
Some UI glitches on the new posts list

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3673]
First, the search bar feels weird on single author blogs, all small and centered

![screen shot 2015-05-15 at 11 14 01](https://cloud.githubusercontent.com/assets/8739/7650123/9dc4807a-faf3-11e4-9cf9-532adab19b56.png)

Posts with featured images do weird things:

https://cloudup.com/czZjGLG2ira

- When trashed, the "undo cell" stays large for a few seconds then collapses into its intended size
- When you tap undo, the post is restored (notice the different stretching of the image), but after a few seconds the featured image is gone

**Comment by aerych** [comment]
> First, the search bar feels weird on single author blogs, all small and centered

@mnt, @adambbecker Thoughts? The current layout should be consistent with the blueprints but I agree with @koke and happy to make a change.

**Comment by adambbecker** [comment]
@aerych: I apologize in advance if this is a super annoying proposal (dev wise), but what if we explored the option of staying consistent with phone header:

![ios_simulator_screen_shot_may_26__2015__4 06 46_pm](https://cloud.githubusercontent.com/assets/1427136/7823532/1903f87c-03ca-11e5-8210-249ce53d2559.png)

Specifically keeping the search icon next to the `+` in the blue header and only using the "author" bar for site's that it's context makes sense. The other thing that might be a nice touch is that on tablets, potentially have the search bar (again still next to `+`) expanded slightly with the placeholder text "Search Published...".

**Comment by aerych** [comment]
> I apologize in advance if this is a super annoying proposal

Not at all!   

Let's give it a try.  I'll wire it up and we'll see how it looks.

**Comment by mnt** [comment]
> Specifically keeping the search icon next to the + in the blue header and only using the "author" bar for site's that it's context makes sense.

I think Adam is right on here. Looking at the first screenshot, the extra bar just seems like a lot of wasted horizontal space that we could free up with this positioning.

**Comment by aerych** [comment]
Here's a quick and dirty version. I'm assuming we'd match the behavior of the iPhone and reveal the search bar when the search icon was tapped.  
![ios simulator screen shot may 26 2015 6 29 12 pm](https://cloud.githubusercontent.com/assets/1435271/7825667/525ee504-03d5-11e5-811e-6ceef6fb56f9.png)

**Comment by mnt** [comment]
:+1:

**Comment by aerych** [comment]
Adding a couple more that @koke reported in #3737 


In the post list, the bottom banner animates but new cells don't

![postlist](https://cloud.githubusercontent.com/assets/8739/7858250/1355f98e-0537-11e5-8e25-eb6abc72d9d2.gif)

When you create a post, the empty post is briefly visible on the list, and it's after the oldest one

![editoropens](https://cloud.githubusercontent.com/assets/8739/7858268/30dcbb3c-0537-11e5-830d-a766caf122f4.gif)

**Comment by aerych** [comment]
Going to close this one as everything has been addressed except the weird footer animation. I'll open a new issue just for that.
