### ISSUE TITLE
Fix NSInvalidArgumentException in - [WPPostViewController addMediaAssets:], line 1786

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3676]
### Stacktrace ###

<pre>WPPostViewController;addMediaAssets:;WPPostViewController.m;1786
MediaService;createMediaWithAsset:forPostObjectID:completion:;MediaService.m;97
WPAssetExporter;exportPhotoAsset:toFile:resizing:stripGeoLocation:completionHandler:;WPAssetExporter.m;101</pre>

### Reason ###

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'

### Link to HockeyApp ###

* [https://rink.hockeyapp.net/manage/apps/34115/app_versions/179/crash_reasons/34826227](https://rink.hockeyapp.net/manage/apps/34115/app_versions/179/crash_reasons/34826227)

**Comment by sendhil** [comment]
Closing as per https://github.com/wordpress-mobile/WordPress-iOS/pull/3677
