### ISSUE TITLE
Video upload works on blog that doesn't support it

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#3683]
You can upload a video to a blog that does not allow videos on it. It looks like we need some kind of check to make sure the WordPress.com blog you’re uploading to allows video uploads.

version: 5.2.0.20150518

**Comment by SergioEstevao** [comment]
This is a feature not a bug. We decided to allows all users of the mobile app to be able to upload videos independently of having installed VideoPress or not.
