### ISSUE TITLE
CommentsViewController: Implement Moderation

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#3685]
Let's implement support for comment moderation -to be displayed when applicable- right in the Comment(s) cell.

@drw158 do you think a text label would do the trick? (It would work pretty much the same way as Like / Unlike)

**Comment by drw158** [comment]
It seems like it would get pretty cramped for all of the actions that we would need (approve, spam, trash)

**Comment by drw158** [comment]
2 ideas:

- Separate the pending comments from the approved comments with a segmented control.
- Swipe to reveal actions like Mail app.

**Comment by jleandroperez** [comment]
@drw158 i kinda like the 'Swipe to Reveal', since that's what Mail.app already does. Will get to it as soon as we ship NCC.

Thanks Dave!

**Comment by jleandroperez** [comment]
**Update:**

Since we're dropping iOS 7 support, we can just use `UITableViewRowAction`. Props to @frosty for the tip (Thanks James!).
