### ISSUE TITLE
Non-ascii character tags cannot be followed in the Reader

### ISSUE THREAD

**Issue by naokomc** [wordpress-mobile/WordPress-iOS#3709]
With the iOS app, you can't follow tags such as "日本" and "América".

Steps to reproduce:

1. Navigate to the "followed tag" page where you can add tags.
2. In the text field, enter "América".
3. You get "Amrica" tag (missing "é").
4. Then, enter "日本".
5. You get an error saying you couldn't follow the topic & "Request failed: not found (404)" This error message should be translatable too.
6. You also get a tag ":(" instead of the intended phrase. You are unable to unfollow this tag. If you try to remove this tag, you get the same 404 error message.

**Comment by sendhil** [comment]
cc @aerych for when you get back.

**Comment by aerych** [comment]
Just about have this sorted.

![ios simulator screen shot may 28 2015 4 40 55 pm](https://cloud.githubusercontent.com/assets/1435271/7871966/8aad6108-0559-11e5-8790-3b8f5636e095.png)
