### ISSUE TITLE
Reblog shows non-wp.com blogs in the selector

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3724]
When reblogging a post, the selector should only show wp.com blogs. Right now it allows reblogging to a Jetpack site. It apparently succeeds, although the reblog isn't posted anywhere

![ios simulator screen shot 27 may 2015 10 43 02](https://cloud.githubusercontent.com/assets/8739/7832183/56dc6f6a-045d-11e5-846e-d3301d33c494.png)
![ios simulator screen shot 27 may 2015 10 43 04](https://cloud.githubusercontent.com/assets/8739/7832182/56db576a-045d-11e5-9cd6-f2da81940fc3.png)
![ios simulator screen shot 27 may 2015 10 43 09](https://cloud.githubusercontent.com/assets/8739/7832185/56e90fb8-045d-11e5-930f-7701e93ea365.png)

**Comment by aerych** [comment]
I'm thinking after #3725 is merged we can edit `WPComBlogSelectorViewController` to only show visible blogs hosted at wpcom, and use it instead of `BlogSelectorViewController`

**Comment by aerych** [comment]
Fixed in #3782
