### ISSUE TITLE
Transparent blavatars look weird

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3738]
IMO, the white border looks odd with transparent blavatars

![screen shot 2015-05-28 at 13 01 11](https://cloud.githubusercontent.com/assets/8739/7858597/bd8cad06-0539-11e5-8f14-11f0ae4c6776.png)

A white background would probably look best, I think that's what calypso does

**Comment by aerych** [comment]
I'm late to the party, but what about removing the border and still having no background?

**Comment by oguzkocer** [comment]
@aerych: When I was working on this in Android, I asked a similar question to @mnt and he wanted white background. The design is a little bit different though, so he might want something different for iOS. But in any case, I think he would be the best person to make the final decision on that :)

**Comment by mnt** [comment]
Yep, a white background will solve it. :y:
