### ISSUE TITLE
Post/Pages: Replace restoration alert with a better prompt view.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3750]
Let's match the style used on the web:
![example-prompt](https://cloud.githubusercontent.com/assets/1435271/7887500/26f0607c-05f7-11e5-805a-754ff316bcfd.png)

**Comment by diegoreymendez** [comment]
@aerych - I'm reviewing old tickets as part of our Groundskeeping.

I was unable to understand what restoration alert this issue is referring to.  Could you clarify it?

**Comment by diegoreymendez** [comment]
I chatted with Eric and we agreed that we could close this for now.
