### ISSUE TITLE
Twitter deep linking doesn't work

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-iOS#3754]
Tapping "Open in WordPress App" in a tweet which contains a wp.com link correctly launches the app, but instead of seeing the post you see "Error loading post."

[Demo video](https://cloudup.com/clXrGvbAB4P)

**Comment by aerych** [comment]
Closing as @nbradbury has determined the [issue lies elsewhere](https://github.com/wordpress-mobile/WordPress-Android/issues/2779#issuecomment-106940880)

```False alarm, the deep linking actually works but is hampered by a limitation in the REST API with custom post types (basically, our API doesn't fully support custom posts).```
