### ISSUE TITLE
NotificationDetails: Initialize WebViewController with DotCom credentials

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#3755]
We got a report indicating that, sometimes, WebViews might be open from within notifications, and the user might get the WordPress.com auth screen.

Let's review + patch accordingly.

**Comment by bummytime** [comment]
@jleandroperez I have actually seen similar behavior recently when previewing posts. Not able to repro consistently though...seems very random almost.

**Comment by jleandroperez** [comment]
@bummytime thanks for the feedback Matt!. In Notifications, this is caused by the lack of creds while initializing the WebView.

I'll take a look at the Post Preview snippet, maybe we've got a similar issue.
