### ISSUE TITLE
iCloud Photo causes photos to disappear from picker after editing

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3759]
WordPress.org Slack Chat: https://wordpress.slack.com/archives/mobile/p1433080270000042
Reference: https://make.wordpress.org/flow/2015/05/31/add-self-hosted-site-to-ios-app-iphone-6/

User report:
> Once I rotate an image via the camera roll, that image disappears from the media picker in the iOS beta. iPhone 6+

cc: @SergioEstevao

**Comment by astralbodies** [comment]
Dug a little deeper and we found the cause of the issue. It appears that editing photos when iCloud Photo is turned on causes some issues with the images disappearing from the picker. Example:

With iCloud Photo turned on, view the picker. The image with the green square of sticky notes is the one I will edit:
![img_0008](https://cloud.githubusercontent.com/assets/373903/8107059/2bc8b26a-100c-11e5-84ac-66c140954405.PNG)

Go in and edit the photo - in this case I rotated it 90º. You can see its still listed in the Photos app. Photo sync completed with iCloud Photo.
![img_0010](https://cloud.githubusercontent.com/assets/373903/8107080/3e609d98-100c-11e5-87f9-ceeb3f45b07e.PNG)

Go back into WPiOS and try to insert an image. The edited image is missing. Sometimes if I close the picker and come back in, the image comes back. More often it does NOT.
![img_0011](https://cloud.githubusercontent.com/assets/373903/8107099/5222f722-100c-11e5-985a-717aa4bc5b75.PNG)

cc: @ryanboren

**Comment by SergioEstevao** [comment]
Fixed on 5.8
