### ISSUE TITLE
WPWebViewController: Revamp Mark II

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#3763]
After some testing, we've realized that it's not a good idea to always fall back to *Safari*, whenever the user taps over an external link (Reference: #3752).

Let's review every single flow in which WebViewController is displayed, and:

- [x] Convert the transition to Modal, when applicable.
- [x] Update the NavigationBar Style, when displayed modally.
- [x] Nuke the Pull to Refresh control.
- [x] Remove the 'Open in Safari' AlertView.
- [x] Bring back the bottom toolbar (as per @drw158's awesome design).
- [x] Bottom Toolbar should be hidden, whenever both Back + Forward are disabled.

--

#### Mockup:

![iphone_6](https://cloud.githubusercontent.com/assets/1195260/7946494/4eda1764-094d-11e5-9a47-f6d6e358afd2.png)

**Comment by folletto** [comment]
Sorry, I just noticed you checked already out the bottom bar. I wouldn't do that. We need to optimize readability, not navigation. That's what our app is for. :)

So my advice there would be to do as Facebook does, with the back/forward at the top (and left aligned on iPad, which Twitter does too by the way, once the screen is big enough). ;)

**Comment by drw158** [comment]
@folletto @jleandroperez I don't feel super strongly about the bottom bar, but it does provide some more room for the site title and url, so that it doesn't become too cramped, especially on 5/5s/5c. Also, like Twitter, the bottom bar is only shown if they tap on a link in the web view, and it hides when the user scrolls down like in Safari.

I can do a mockup of a FB style web view this morning to get a feel for it.

**Comment by jleandroperez** [comment]
@drw158 + @folletto: Thanks for the feedback gentleman!.

Since 5.3 got into Code Freeze yesterday, i'll try to squeeze in the current changes, and enhance the Toolbar / Navbar (if needed) in a secondary issue.

Thanks!!

**Comment by jleandroperez** [comment]
@drw158 + @folletto: Dave's latest mockup is already implemented in 5.3.

I'd be happy to implement any follow up to the design into 5.4!

**Comment by folletto** [comment]
Cool then. Mine was just a sling preference, if it's already coded let's keep this in and let's re-assess later. :)

Does the above include the iPad specific views? Or that has been delayed too?

**Comment by jleandroperez** [comment]
@folletto iPad's UI is the same (for 5.3), but we can definitely do anything else for 5.4!

**Comment by folletto** [comment]
Ok cool! Yes I'd make for sure the changes on iPad for 5.4 because it optimizes the space available — if you have time. 

On the bar at the bottom on iPhone I'm ok in keeping it for now and review later. :)

**Comment by jleandroperez** [comment]
@folletto just in case (to make sure we're on the same page). iPad Specific UI would be:

- Left / Right arrows in the title bar
- No bottom toolbar

Would that be correct?

**Comment by folletto** [comment]
Yep! :)

**Comment by jleandroperez** [comment]
@folletto awesome!. Closing this issue in favor of #3814

I'll try to reuse the exact same assets we already have for the `Back` / `Forward` (not sure if we'll need something custom there, or nope)

**Comment by jleandroperez** [comment]
(By the way, *many* thanks for the feedback and help @drw158 + @folletto)!!
