### ISSUE TITLE
Published notice doesn't include the site name where content was published

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#3769]
To help prevent anxiety about whether or not a post was published to the correct blog, can the "Published!" notice be updated to include the name of the site where the content was published?

<img alt="img_1949" src="https://cloud.githubusercontent.com/assets/1119271/7925972/8061c2b4-0899-11e5-9bde-181e7526b620.png" width="400" />

<sup>Tested using an iPhone 6+. (k3540)</sup>

**Comment by diegoreymendez** [comment]
@designsimply - Can you provide more details about what you'd like to see in the message? (blog name, vs URL, etc...)

Also, have you run this change request through a UX/UI designer?    Just want to make sure there's a green light on this before moving ahead. (/cc @mattmiklic in case you want to step in)

**Comment by mattmiklic** [comment]
I could see a couple of possible solutions.

A pretty quick improvement would be to keep the existing design, and just change the text to read "Post published on [site name]" -- this matches the language used in Calypso.

A bigger iteration could be replacing that alert with a notice that stays on-screen, like the one used in the Me section when a pending change has been made to the user's email address. This could include a link to the post within the app, so the user can easily choose to open it in the browser or edit it.

**Comment by rachelmcr** [comment]
This issue is resolved with https://github.com/wordpress-mobile/WordPress-iOS/pull/6232 (adding a post-post screen that includes the site name).
