### ISSUE TITLE
Infinite scroll loads a few extra posts after it thinks there aren't more

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3812]
A bit hard to explain so I made a video:

https://cloudup.com/c44WLlCpdR1

I scrolled to the bottom of the list and saw the banner indicating there are no more posts. I also saw the loading indicator briefly before that, which makes me think the app actually checked to see that there weren't any new posts.

Then if I scroll back up a bit and then down, a couple more posts load. Then it happens again and shows what I believe it's the actual last post.

/cc @aerych

**Comment by aerych** [comment]
Hmm... does this still happen on the branch in #3801? 
That was showing as a multi author blog, and I'm wondering if it was because the old filter was confusing whether there were actually no more posts.

**Comment by koke** [comment]
Looks fine in #3801 \o/
