### ISSUE TITLE
Getting this error when tried installing dependencies for the project via pod install 

### ISSUE THREAD

**Issue by sagarmane19** [wordpress-mobile/WordPress-iOS#3820]
Hello,

getting following error "[!] Unable to find a specification for `Reachability (= 3.1.1)`" when tried installing dependencies for the project via pod install.

This is log 

Analyzing dependencies
Pre-downloading: `Automattic-Tracks-iOS` from `https://github.com/Automattic/Automattic-Tracks-iOS.git`, tag `0.0.4`
Fetching podspec for `EmailChecker` from `https://raw.github.com/wordpress-mobile/EmailChecker/develop/ios/EmailChecker.podspec`
Pre-downloading: `MGImageUtilities` from `git://github.com/wordpress-mobile/MGImageUtilities.git`, commit `e946cf3d97eb95372f4fc4478bf2e0099e73f4b0`
Pre-downloading: `NSLogger-CocoaLumberjack-connector` from `https://github.com/steipete/NSLogger-CocoaLumberjack-connector.git`, tag `1.5`
Pre-downloading: `SocketRocket` from `https://github.com/jleandroperez/SocketRocket.git`, commit `3ff6038ad95fb94fd9bd4021f5ecf07fc53a6927`
Pre-downloading: `WordPress-AppbotX` from `https://github.com/wordpress-mobile/appbotx.git`, commit `303b8068530389ea87afde38b77466d685fe3210`
Pre-downloading: `WordPress-iOS-Editor` from `https://github.com/wordpress-mobile/WordPress-Editor-iOS.git`, commit `9812b6c9a699cd654ef5c0cffe9bed9f91c06782`
[!] Unable to find a specification for `Reachability (= 3.1.1)`

**Comment by sagarmane19** [comment]
This has solved the issue 

pod repo remove master
pod setup

**Comment by sendhil** [comment]
Thanks for reporting the issue @sagarmane19. Going to close this based on your latest comments...
