### ISSUE TITLE
Blog switcher might overlap with preview button

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3827]
If the current blog title is long enough, it overlaps with the preview button

![screen shot 2015-06-10 at 11 21 43](https://cloud.githubusercontent.com/assets/8739/8079141/f7c416e8-0f62-11e5-9084-d06c418bfb7b.png)

**Comment by bummytime** [comment]
@koke This will be fixed in this PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/3882

**Comment by rachelmcr** [comment]
I can no longer trigger this overlap, so it looks like the PR above resolved the issue. Please reopen if you still notice this issue on certain devices.
