### ISSUE TITLE
iOS Auto Correct doesn't work with Bluetooth Keyboard

### ISSUE THREAD

**Issue by sandymcfadden** [wordpress-mobile/WordPress-iOS#3828]
When a bluetooth keyboard is connected and being used the auto correct built into iOS doesn't work when in the post editor.

If you start typing on the built in keyboard the auto correct will work. This seems to be different than other apps on iOS.

**Comment by rachelmcr** [comment]
I confirmed that when using a bluetooth keyboard, the auto correct in the editor doesn't work the same way as it does with the on-screen keyboard.

Using the on-screen keyboard, I get a pop-up auto-correct suggestion under the word:

<img src="https://cloud.githubusercontent.com/assets/8658164/11502047/6ac4ada0-9830-11e5-87ff-fdb0ca3d2fda.png" width="50%">

Using a bluetooth keyboard, I don't get any pop-up under the word:

<img src="https://cloud.githubusercontent.com/assets/8658164/11502058/7e4c164c-9830-11e5-9c5e-ec9258bc7e69.png" width="50%">

However, if I backspace to the misspelled word I do get a suggested correct spelling:

<img src="https://cloud.githubusercontent.com/assets/8658164/11502083/a14d94a4-9830-11e5-8327-424e220e4384.png" width="50%">

I checked quite a few other apps (such as Mail and Notes) and wasn't able to trigger any better auto-correct behavior than this with a bluetooth keyboard. That said, it would be great if we could trigger that auto-correct pop-up even with an external keyboard.

Tested on iPhone 6, iOS 9.1, app beta 5.8.0.20151124.

**Comment by nheagy** [comment]
Just tested this on my iPhone 6S Plus running 9.3, and app 6.0 from the App Store, as well as my iPad Pro running the same. Autocorrect appears to be showing up with external keyboards on both. Perhaps this was fixed/changed in 9.2 or 9.3?

![img_2602](https://cloud.githubusercontent.com/assets/517257/14154710/3d5bd362-f67b-11e5-9ac0-f3317d1148a4.jpg)

**Comment by rachelmcr** [comment]
Thanks @nheagy! I tested again on my iPhone 6, iOS 9.3.1, running the latest beta version (6.2.0.20160419) and autocorrect is working with my external keyboard now, too. Closing this as resolved.
