### ISSUE TITLE
Sites: Users: Add Invites

### ISSUE THREAD

**Issue by allendav** [wordpress-mobile/WordPress-iOS#3841]
Under My Sites > {Site}, add a new item "Invites" under Admin.  Tapping that item should present view(s) that allow the user to
- invite one or more usernames or email addresses to join the blog with a specific role (including follower for public blogs or viewer for private blogs) with an optional message
- see a list of pending and accepted invitations
- delete an invitation
- resend an unaccepted invitation

This should support WordPress.com, Jetpack and self-hosted sites.

cc @oguzkocer 

Related: https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/follows/
https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/users/

**Comment by rachelmcr** [comment]
> invite one or more usernames or email addresses to join the blog with a specific role (including follower for public blogs or viewer for private blogs) with an optional message

Invites were implemented for WordPress.com and Jetpack users in https://github.com/wordpress-mobile/WordPress-iOS/issues/5381.

The remaining items are still pending as of beta version 6.6.0.20161012.

**Comment by jleandroperez** [comment]
Addressed last year via #5030.

Available via My Sites > {Site} > People.

Thanks everyone!
