### ISSUE TITLE
Sites: Users: Add User Management

### ISSUE THREAD

**Issue by allendav** [wordpress-mobile/WordPress-iOS#3842]
Under My Sites > {Site}, add a new item "Users" under Admin. Tapping that item should present view(s) that allow the user to

 * view a list of current users, grouped by role, including user's gravatar
 * change a user's role
 * remove a user (other than themselves)

This should support WordPress.com, Jetpack and self-hosted sites.

cc @oguzkocer 

Related: https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/users/
https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/follows/

**Comment by koke** [comment]
Tracking progress in #4309
