### ISSUE TITLE
Sometimes footer view animates over non animated cells.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3844]
Refs #3673, props Koke.

In the post list, the bottom banner animates but new cells don't

![postlist](https://cloud.githubusercontent.com/assets/8739/7858250/1355f98e-0537-11e5-8e25-eb6abc72d9d2.gif)

**Comment by parkej60** [comment]
I'm unable to replicate this issue on the iPad Air 8.3 simulator. I also no longer see the 'Fetching posts...' message. Has this been resolved?

**Comment by aerych** [comment]
I don't think we've resolved it. Koke slowed down the animation to make it stand out.  I think its only happening the first time the list is synced.  It might be this was only an issue on iOS 7.1

**Comment by parkej60** [comment]
Ok, I'll keep trying to replicate. Thanks. 

Jameson W Parker

**Comment by rachelmcr** [comment]
I tested and reproduced this issue in beta v. 5.8.0.20151204, iOS 9.1 on iPhone 6, with the following steps:
1. Select a blog and empty the trash
2. Open Blog Posts > Trashed in the app and confirm no posts appear there
3. Trash a post
4. Pull down to refresh the Trashed posts list. Result: After the "Fetching posts..." message appears, you see the animation as shown above.
(I found that looking at the trashed posts list is a reliable way to reproduce this repeatedly for the same blog.)

**Comment by hoverduck** [comment]
Closing, I'm unable to reproduce using @rachelmcr's steps above.  Posts and footer appear to render at once.

**Comment by hoverduck** [comment]
Re-opening...I randomly was able to reproduce it by trashing and then restoring a post:

![ios-floating-footer](https://cloud.githubusercontent.com/assets/7233112/22299521/62937de2-e2f2-11e6-805d-b9318be36c25.gif)

**Comment by rachelmcr** [comment]
Closing as we no longer have that bottom W banner.
