### ISSUE TITLE
Post List: tapping "Edit" on a post opens it in view mode.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#3864]
Steps:
1. Launch the app
2. Go to "My sites"
3. Tap on a blog
4. Tap on "Blog posts"
5. Tap "Edit" on a post.

Current behavior: the post will open in view-mode / read-mode.
Expected behavior: the post should open in edit-mode.

**Comment by aerych** [comment]
Thanks for the report!
