### ISSUE TITLE
Invalid event names for nil events

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3875]
I saw a bunch of errors like this:

> 2015-06-16 13:05:22:331 WordPress[8098:807] Error when validating TracksEvent: Error Domain=TracksErrorDomain Code=3 "An event name contain alpha characters and underscores only." UserInfo=0x17447d000 {NSLocalizedDescription=An event name contain alpha characters and underscores only.}

While some of them were related to https://github.com/Automattic/Automattic-Tracks-iOS/issues/19, I also saw it trying to track `wpios_(null)`. 

The source of the problem is the code in `WPAnalyticsTrackerAutomatticTracks.m`

![screen shot 2015-06-16 at 13 12 05](https://cloud.githubusercontent.com/assets/8739/8181795/5fa33d14-1429-11e5-93b2-20d66f97c539.png)

**Comment by jleandroperez** [comment]
@koke is this one still valid?. Haven't seen this log in the console (at least not lately!).

Thanks!

**Comment by koke** [comment]
I haven't seen this one recently either

**Comment by jleandroperez** [comment]
Thank youo!
