### ISSUE TITLE
Post/Pages: "Search" button should be renamed to "Done" or similar.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#3893]
When searching for posts or pages, the search is triggered by the user typing on the search field, and the virtual keyboard's "Search" button actually acts more like a dismiss button.

To make the button consistent with the action it performs it should be renamed to "Done" or "Dismiss".

/cc @aerych - This is very minor and can be even closed if we still prefer to keep the "Search" button as it is.

**Comment by aerych** [comment]
@diegoreymendez Hmm... yah the name is a little odd, but I think Done or Dismiss would suggest that you were finished with the search all together when really all we're doing is dismissing the keyboard. Let's run it by our trusty designers and get their input. I'm all for improving changing it if one of the other naming options works better.

**Comment by aerych** [comment]
After chatting with @mnt and @drw158 we'll go with "Done"

![ios simulator screen shot jun 23 2015 5 20 07 pm](https://cloud.githubusercontent.com/assets/1435271/8318806/cb0d3768-19cd-11e5-9189-4f6f48ed0771.png)
