### ISSUE TITLE
Blogs list: add pull to refresh

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#3898]
Add pull to refresh to the list of blogs, so that the user can update it manually.

I've tried changing my blog's name through a web browser and the change was only applied to the iOS app after reopening it.  This improvement would slightly mitigate that.

**Comment by koke** [comment]
I had my doubts about this at first, but it's something that could be useful for some, and it's invisible if you don't need it, so :+1: 

BTW, since #3874 it should refresh on appear and not app launch

**Comment by diegoreymendez** [comment]
I was testing it today and I could not get the site's title to update in any way... so I'll make sure to check your PR to see why this was the case - just to know if it was me doing something wrong or if the title isn't changing due to a bug.

Thanks for the heads up.

Also, I agree we should add it since there are no big downsides in adding this, plus it would make the app a bit more consistent.

**Comment by diegoreymendez** [comment]
Removing myself from this issue since this is not a priority at this time.

**Comment by hoverduck** [comment]
I tested today by updating my site's title via the web and then opening the Blogs List to see if it updated.  It didn't update on my first attempt (still loading cached data), but a few seconds later I tried again and it was there.

@diegoreymendez - Do you want to keep this issue open (low priority) to add the pull to refresh capability for consistency, or just go ahead and close it as unnecessary?

**Comment by diegoreymendez** [comment]
To be honest I'd consider leaving this open, as this issue would be an awesome candidate to fix on our groundskeeping rotation.  It's indeed low priority but also quite an easy fix.

I'd certainly be willing to tackle this on my next groundskeeping week.

That said, I'd leave the final decision to you @hoverduck, as you have a much wider point of view on the state of all of our tickets.

**Comment by hoverduck** [comment]
Happy to leave it open if it's going to get attention.  It's tagged Pri Low so it shouldn't cause anyone any heartache
