### ISSUE TITLE
Post/Pages: tapping on a post should open the post in view-mode.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#3899]
Right now the app considers a tap in the post's body as an edit request.  Tapping on a post in the posts list should open the post in view-mode (read-only mode) instead.

**Comment by koke** [comment]
That makes sense, except maybe for drafts?

**Comment by diegoreymendez** [comment]
Well... for drafts I'm not sure.  You have a valid point there, so I'll make that exception.

**Comment by aerych** [comment]
I think the tap behavior should stay consistent. Since there is an edit button on the card, just open everything in read only when tapping the cell itself.

**Comment by diegoreymendez** [comment]
I'm clearing myself from this ticket for the time being, since I'm going to be prioritizing themes in the short term.

**Comment by aerych** [comment]
@diegoreymendez no worries.  I'll pick this one up.  Thanks for reporting it Diego!
