### ISSUE TITLE
Add details web view.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#3908]
Double check this to see how Android does it.  But @folletto mentioned we should use a web view for the theme details.

**Comment by folletto** [comment]
You should have a standard way to load web views in the app, like the one used for the Reader, no? :)

**Comment by diegoreymendez** [comment]
There is.  Why are you asking?

**Comment by diegoreymendez** [comment]
PS: if you're asking because of my mention of double checking how Android does it, it's referring to the fact that during my testing it didn't feel like a web view.

**Comment by folletto** [comment]
So yes, sorry... I wasn't clear. ^^'

I mean that the experience should be aligned. Currently Android uses what seems a view with a custom design. I'd just remove that, and go to the web page as iOS would do too. :)

And in that case — which I was asking in a too cryptic way — we should use the web view modal that already exist in both apps. :)

**Comment by diegoreymendez** [comment]
Awesome, thanks for the clarification @folletto!
