### ISSUE TITLE
Issues with transition from the new post list to editor

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#3910]
Now that we removed the "preview first, then edit" workflow *after* selecting an existing post to edit, there are a few issues that need to be resolved. 

~~1. The user taps once on a post to bring up the editor, however when they want to return to the post list screen they need to tap twice. (once to exit edit mode and once to return to the post list screen from preview mode).~~
2. Because the editor is defaulting to preview mode and then we switch it to edit mode immediately, the animation is a little choppy. Perhaps we can remove the preview mode from the editor altogether?
~~3. Even though we are editing an existing post, the navbar command in the upper right corner starts as "Post" and then changes to "Update" after the screen transitions (admittedly, this could be a separate issue in github).~~

Here is a video: https://cloudup.com/c0t2AM4d0Qp

/cc @aerych @thianhlu @sendhil

**Comment by bummytime** [comment]
Admittedly for point 2 above, I have a hunch the preview mode is mucking things up...it could always be something else :-)

**Comment by bummytime** [comment]
Ref: #3899

**Comment by parkej60** [comment]
Not saying this is the solution, but if I put a delay around the startEditing call it solves the issues with the choppy animation.

```
- (void)editorViewDidFinishLoadingDOM:(WPEditorView*)editorView
{
	// DRM: the reason why we're doing is when the DOM finishes loading, instead of when the full
	// content finishe loading, is that the content may not finish loading at all when the device is
	// offline and the content has remote subcontent (such as pictures).
	//
    self.didFinishLoadingEditor = YES;
    
	if (self.editing) {
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 0.5 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
            [self startEditing];
        });
		
	} else {
		[self.editorView disableEditing];
	}
    
    [self tellOurDelegateEditorDidFinishLoadingDOM];
}
```

**Comment by bummytime** [comment]
Thanks @parkej60!  

I am always leery about injecting delays to fix timing issues. It may fix the issue now but can introduce other issues down the line because we altered the order in which our code runs.  I appreciate the idea though!!

**Comment by parkej60** [comment]
Totally agree. Just used it as a tool to identify the possible culprit while walking through it this morning.

**Comment by bummytime** [comment]
@roop's PR (#3992) fixed [points 1 and 3](https://github.com/wordpress-mobile/WordPress-iOS/issues/3910#issue-89823963) above.

**Comment by SergioEstevao** [comment]
Closing this issue and leave the remaining problem here: https://github.com/wordpress-mobile/WordPress-iOS/issues/4210
