### ISSUE TITLE
Users with a contributor role do not see their posts in the post list

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3915]
A user with a contributor role can not edit posts, not even the ones they author.  Since posts are requested from the wpcom REST API with an edit context, the list for a contributor is always empty. 

We should support displaying a contributor's posts with just "view" and "stats" options.

**Comment by rachelmcr** [comment]
This looks like the same issue as #2680. I'm going to close this duplicate issue in favor of that one.
