### ISSUE TITLE
Request element count before assets in media picker

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS#3924]
thumb next to media library is empty & item count is artificially low/wrong, presumably bc we're waiting for the request response for the assets. let's request # elements before requesting the media assets to display proper count while images load. It would also be great to get a placeholder thumbnail in there (WP logo) before we get the response.

repro
- hit photo icon to add image in blog
- hit media picker to open albums options
- note "media library" is at top with a count
- count is off by a lot & there's no thumbnail next while it awaits the image response

**Comment by parkej60** [comment]
Not positive but it seems like the callback never triggers the group table to reload. It gets the count but since the table never gets reloaded it doesn't update the label. 
https://github.com/wordpress-mobile/MediaPicker-iOS/blob/develop/Pod/Classes/WPMediaGroupPickerViewController.m#L46

**Comment by SergioEstevao** [comment]
This was sorted out on the 5.8 version of the app.
