### ISSUE TITLE
Trigger immediate visual response upon library switch

### ISSUE THREAD

**Issue by meremagee** [wordpress-mobile/WordPress-iOS#3926]
https://lookback.io/watch/Wd9utKxnByJnHLyrp

When you switch from camera roll to wp media library in media picker, there should be an immediate visual response. Right now, the view persists on the camera roll as the app waits for the media library response.

**Comment by SergioEstevao** [comment]
@meremagee I've been working on this and I have two options:

* Switch immediately to the current version of media available on the device ( this could be empty if it's the first time), and **allow you to immediately select assets** and meanwhile there is a background sync, when that finish you see a flash on the screen and updated media that come from the server will show up.

* Switch immediately to the current version of media available on the device **but don't allow** you to immediately select assets and while there is a background sync you see a spinner, when that finish you see a flash on the screen and updated media that come from the server will show up.

**Comment by meremagee** [comment]
Why the flash in both cases?

**Comment by SergioEstevao** [comment]
I changed the way the activity indicator is show to improve the visibility of it.
I also reduced the amount of flashing when updating the assets.
In a future version I will do a improvement to avoid the flash altogether and instead only update the cells that where deleted or inserted from the result of the sync.
