### ISSUE TITLE
Editor: allow linking to existing content from the site

### ISSUE THREAD

**Issue by lancewillett** [wordpress-mobile/WordPress-iOS#3930]
As core WordPress editor allows (as well as the WordPress.com editor), it'd be a nice feature to be able to link to existing posts or pages from your WordPress site from within the editor.

From https://en.support.wordpress.com/links/:

> Or, if you want to link to one of your existing posts or pages, use the search box to quickly find what you’re looking for. Simply enter a keyword or two that appears somewhere on the post or page you want to link to.

Example from desktop, WordPress.com:

![existing_content1](https://cloud.githubusercontent.com/assets/66797/8366341/169f8be6-1b49-11e5-86e9-3b892384808e.png)

Example from mobile web, WordPress.com.
<img src="https://cloud.githubusercontent.com/assets/66797/8366534/8d18ccbe-1b4a-11e5-8678-efc7a87e033f.png" width="480" />

(Suggest internally at Automattic by Ryan Boren.)

**Comment by rachelmcr** [comment]
This came up recently in app feedback:

> Estaría genial que en el editor, a la hora de añadir enlaces en el texto, hubiese una opción para buscar posts anteriores a los que enlazar, tal y como en la versión web. ¡Gracias!

Translation:

> It would be great if in the editor, when adding links in the text, there would be an option to search for previous posts to which to link, as in the web version. Thank you!

Internal ref: AppbotX 28562

**Comment by mattmiklic** [comment]
Another request for this in a recent customer story. ref: p77Llu-a6F-p2

**Comment by mattmiklic** [comment]
Another request from a customer story. ref: p77Llu-a7X-p2

**Comment by dougaitken** [comment]
Adding a request from myself.

**Comment by rachelmcr** [comment]
This feature was added in https://github.com/wordpress-mobile/WordPress-iOS/pull/10074 and will be released in version 10.9 (currently in beta).
