### ISSUE TITLE
Disable edit button on sites list if not connected to WordPress.com

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3932]
Tapping edit puts the table in an odd state -

![img_0001](https://cloud.githubusercontent.com/assets/373903/8378739/11ec4a88-1be1-11e5-978d-e5014151daf2.PNG)

**Comment by aerych** [comment]
The option to remove a self hosted site is now found at the bottom of the site details screen.  Probably we shouldn't be showing the edit button on the blog list unless the user is logged into wpcom.

**Comment by koke** [comment]
So, we only enable the button if there are "hideable" blogs, which we calculate with this predicate

```
[NSPredicate predicateWithFormat:@"account = %@", defaultAccount]
```

What could go wrong?

```(lldb) po predicate
account == nil```
