### ISSUE TITLE
Reader: in single post view, allow clicking anywhere in the header to see blog detail view to avoid unfollowing a blog

### ISSUE THREAD

**Issue by lancewillett** [wordpress-mobile/WordPress-iOS#3935]
(Originally reported internally at Automattic by Ryan Boren.)

Improve the tap target to go to the blog detail stream — right now you have to tap a very small area.

Drilling down to site detail from a single post screen requires tapping a small avatar. The avatar is right next to the follow/unfollow target. I accidentally tap this all the time.

![reader-2](https://cloud.githubusercontent.com/assets/66797/8384290/eef7d68c-1bf4-11e5-9f7f-6374f379863c.png)

Contrast this with the top level Reader stream. In the following shot, I can tap almost anywhere in the header to drill down. I don't have to tap the avatar.

![reader-1](https://cloud.githubusercontent.com/assets/66797/8384274/d229bdc2-1bf4-11e5-9fb7-74ace5b50d48.png)

This inconsistency in drill down targets seems to cause quite a bit of cognitive friction for me. I can't make a habit of tapping the right side of the header and don't want to make a habit of tapping near unfollow when I don't have to.

**Comment by aerych** [comment]
Closed by #4032 and #4280
