### ISSUE TITLE
Add a Site under My Sites doesn't let you create a new WordPress.com site

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#3941]
When tapping "Add a Site" in My Sites you're presented with the self-hosted site NUX. You cannot create a new WordPress.com site/blog within the app.

![img_0012](https://cloud.githubusercontent.com/assets/373903/8415188/9c6fff28-1e62-11e5-89ed-a0f4972a84c1.PNG)

![img_0014](https://cloud.githubusercontent.com/assets/373903/8415187/9c63df86-1e62-11e5-8333-76456d5514d7.PNG)

**Comment by rachelmcr** [comment]
As of version 5.9 it's now possible to create a WordPress.com site in the app. Closing as resolved.
