### ISSUE TITLE
Implement blog settings on the app

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#3970]
Allow the ability to edit the following blog settings on the app:

 - [x] General
   - [x] Site Tile
   - [x] Site Tagline
   - [x] Site Privacy
   - [ ] Language
 - [x] Writing
   - [x] Default Category
   - [x] Default Post Format
   - [x] Post Formats
 - [x] Discussion

The endpoint for settings is this one: https://wpcom.trac.automattic.com/browser/trunk/public.api/rest/json-endpoints.php?rev=119896#L1877

Here is a list of parameters for the POST  endpoint

'blogname'                     => '(string) Blog name', -> General Site Title
'blogdescription'              => '(string) Blog description', -> General Site Tagline
'default_pingback_flag'        => '(bool) Notify blogs linked from article?', -> Discussion Default Article Settings
'default_ping_status'          => '(bool) Allow link notifications from other blogs?', -> Discussion Default Article Settings
'default_comment_status'       => '(bool) Allow comments on new articles?', -> Discussion Default Article Settings
'blog_public'                  => '(string) Site visibility; -1: private, 0: discourage search engines, 1: allow search engines', -> General Visibility
'jetpack_relatedposts_enabled' => '(bool) Enable related posts?', -> General Related Post
'jetpack_relatedposts_show_headline' => '(bool) Show headline in related posts?',  -> General Related Post
'jetpack_relatedposts_show_thumbnails' => '(bool) Show thumbnails in related posts?',  -> General Related Post
'infinite_scroll'              => '(bool) Support infinite scroll of posts?',
'default_category'             => '(int) Default post category', -> Writing Default Post category
'default_post_format'          => '(string) Default post format', -> Writting Default Post Format
'require_name_email'           => '(bool) Require comment authors to fill out name and email?',  -> Discussion Other Comment Settings
'comment_registration'         => '(bool) Require users to be registered and logged in to comment?', -> Discussion Other Comment Settings
'close_comments_for_old_posts' => '(bool) Automatically close comments on old posts?',  -> Discussion Other Comment Settings
'close_comments_days_old'      => '(int) Age at which to close comments',  -> Discussion Other Comment Settings
'thread_comments'              => '(bool) Enable threaded comments?',  -> Discussion Other Comment Settings
'thread_comments_depth'        => '(int) Depth to thread comments',  -> Discussion Other Comment Settings
'page_comments'                => '(bool) Break comments into pages?',  -> Discussion Other Comment Settings
'comments_per_page'            => '(int) Number of comments to display per page',  -> Discussion Other Comment Settings
'default_comments_page'        => '(string) newest|oldest Which page of comments to display first',  -> Discussion Other Comment Settings
'comment_order'                => '(string) asc|desc Order to display comments within page',  -> Discussion Other Comment Settings
'comments_notify'              => '(bool) Email me when someone comments?',  -> Discussion Email me whanever
'moderation_notify'            => '(bool) Email me when a comment is helf for moderation?', -> Discussion Email me whanever
'social_notifications_like'    => '(bool) Email me when someone likes my post?', -> Discussion Email me whanever
'social_notifications_reblog'  => '(bool) Email me when someone reblogs my post?', -> Discussion Email me whanever
'social_notifications_subscribe' => '(bool) Email me when someone follows my blog?', -> Discussion Email me whanever
'comment_moderation'           => '(bool) Moderate comments for manual approval?', -> Discussion Comment Moderation
'comment_whitelist'            => '(bool) Moderate comments unless author has a previously-approved comment?',  -> Discussion Comment Moderation
'comment_max_links'            => '(int) Moderate comments that contain X or more links',  -> Discussion Comment Moderation
'moderation_keys'              => '(string) Words or phrases that trigger comment moderation, one per line',  -> Discussion Comment Moderation
'blacklist_keys'               => '(string) Words or phrases that mark comment spam, one per line',  -> Discussion Comment Blacklist
'lang_id'                      => '(int) ID for language blog is written in', -> General Language
'wga'                          => '(array) Google Analytics Settings',  -> Analytics, only available on business
'disabled_likes'               => '(bool) Are likes globally disabled (they can still be turned on per post)?',
'disabled_reblogs'             => '(bool) Are reblogs disabled on posts?',
'jetpack_comment_likes_enabled' => '(bool) Are comment likes enabled for all comments?',
'sharing_button_style'         => '(string) Style to use for sharing buttons (icon-text, icon, text, or official)',
'sharing_label'                => '(string) Label to use for sharing buttons, e.g. "Share this:"',
'sharing_show'                 => '(string|array:string) Post type or array of types where sharing buttons are to be displayed',
'sharing_open_links'           => '(string) Link target for sharing buttons (same or new)',
'twitter_via'                  => '(string) Twitter username to include in tweets when people share using the Twitter button',
'jetpack-twitter-cards-site-tag' => '(string) The Twitter username of the owner of the site\'s domain.',
'eventbrite_api_token'         => '(int) The Keyring token ID for an Eventbrite token to associate with the site',

And here is a  sample JSON from the setting endpoint GET 
```
{
    ID = 76024335;
    URL = "https://iosonestep.wordpress.com";
    description = "A test site for the ios with 2FA disabled.";
    lang = en;
    name = "iOS One Step";
    settings =     {
        "admin_url" = "https://iosonestep.wordpress.com/wp-admin/";
        "blacklist_keys" = "";
        "blog_public" = 1;
        "close_comments_days_old" = 14;
        "close_comments_for_old_posts" = 0;
        "comment_max_links" = 2;
        "comment_moderation" = 0;
        "comment_order" = asc;
        "comment_registration" = 0;
        "comment_whitelist" = 1;
        "comments_notify" = 1;
        "comments_per_page" = 50;
        "default_category" = 1;
        "default_comment_status" = 1;
        "default_comments_page" = newest;
        "default_ping_status" = 1;
        "default_pingback_flag" = 1;
        "default_post_format" = 0;
        "disabled_likes" = 0;
        "disabled_reblogs" = 0;
        "eventbrite_api_token" = "<null>";
        "jetpack-twitter-cards-site-tag" = "";
        "jetpack_comment_likes_enabled" = 1;
        "jetpack_relatedposts_allowed" = 1;
        "jetpack_relatedposts_enabled" = 0;
        "jetpack_relatedposts_show_headline" = 0;
        "jetpack_relatedposts_show_thumbnails" = 0;
        "jetpack_sync_non_public_post_stati" = 0;
        "lang_id" = 1;
        "moderation_keys" = "";
        "moderation_notify" = 1;
        "page_comments" = 1;
        "post_categories" =         (
                        {
                name = travel;
                value = 200;
            },
                        {
                name = Uncategorized;
                value = 1;
            },
                        {
                name = zebras;
                value = 576440;
            }
        );
        "require_name_email" = 1;
        "sharing_button_style" = "icon-text";
        "sharing_label" = "Share this:";
        "sharing_open_links" = same;
        "sharing_show" =         (
            post,
            page
        );
        "social_notifications_like" = 0;
        "social_notifications_reblog" = 0;
        "social_notifications_subscribe" = 0;
        "thread_comments" = 1;
        "thread_comments_depth" = 3;
        "twitter_via" = "";
        wga = 0;
    };
}
```

For self-hosted you need to use the wp.options endpoint

**Comment by jleandroperez** [comment]
@SergioEstevao heads up! (just in case, so that we don't overlap). I'll be helping with the **Discussion** settings (#4382).

:smile:

**Comment by SergioEstevao** [comment]
@jleandroperez just added the settings endpoint information to the issue description.

**Comment by jleandroperez** [comment]
Thank you @SergioEstevao, much appreciated sir!

**Comment by SergioEstevao** [comment]
Closing this issue now that all the features are implemented except language that needs some REST API work to avoid hard coding languages ids.
