### ISSUE TITLE
Add display name to Me tab

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#3971]
Both WordPress.com and Android show the display name below the avatar. Let's do it on iOS as well

![screen shot 2015-07-03 at 12 56 40](https://cloud.githubusercontent.com/assets/8739/8498101/4a2c74b6-2183-11e5-9f87-e80d6a20e141.png)
![screenshot_2015-07-03-12-56-56](https://cloud.githubusercontent.com/assets/8739/8498103/4c52529c-2183-11e5-808a-c7f5346a2ec6.png)

**Comment by parkej60** [comment]
https://github.com/wordpress-mobile/WordPress-iOS/pull/4002
