### ISSUE TITLE
Code Review: Review editor and publishing logic realted to local-only posts.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#3978]
All local-only posts have a `postID` of `-1`.  This is potentially a problem anywhere reference a post by postID since for local-only post it is not unique.  

Theory: Some of the bug reports regarding missing or vanishing drafts are related to non-unique -1 postID. 

Scrub the publish logic for problems and investigate other options for local-only postIDs. 

cc @bummytime

**Comment by diegoreymendez** [comment]
@aerych - Do you happen to have any of those reports handy?  Or a link?

**Comment by aerych** [comment]
@diegoreymendez I was probably referring to the occasional reports in the [iOS forums](https://ios.forums.wordpress.org/forum/how-to-and-troubleshooting/page/6) about lost drafts/edits. I don't recall a specific thread tho.

**Comment by diegoreymendez** [comment]
No worries just wondering.  I'll investigate this after we merge https://github.com/wordpress-mobile/WordPress-iOS/pull/4952.

**Comment by mchowning** [comment]
Seems this is likely still an issue we should keep open since we still have [a default postId of -1](https://github.com/wordpress-mobile/WordPress-iOS/blob/50e1647c52304eef6b84fd330729d03be9796040/WordPress/Classes/Models/BasePost.swift#L5).

**Comment by kean** [comment]
The default value being `-1` is not problem in itself.

The entire flow has been re-design in the scope of  pcdRpT-6vS-p2. For example, these problematic queries are gone:

```
let query =
            // Existing draft/pending posts
            "(statusAfterSync = status AND status IN (%@))"
            // Existing draft/pending posts transitioned to another status but not uploaded yet
            + " OR (statusAfterSync != status AND statusAfterSync IN (%@))"
            // Posts existing only on the device with statuses defined in `statusesForLocalDrafts`.
            + " OR (postID = %i AND status IN (%@))"
            // Include other existing draft/pending posts with `nil` `statusAfterSync`. This is
            // unlikely but this ensures that those posts will show up somewhere.
            + " OR (postID > %i AND statusAfterSync = nil AND status IN (%@))"
``

It's now just: 

```
"status == draft"
```

Other areas have also been updated and are fully covered by integration tests. I think it's fair to close it.
