### ISSUE TITLE
AboutViewController Interface Revamp

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#3998]
We've decided it's time to spend some minutes revamping the About view!.

Props to @drw158 for the new design. Thanks Dave!

![iphone_6](https://cloud.githubusercontent.com/assets/1195260/8602037/637b89b2-2646-11e5-9940-7f139497ee05.png)

**Comment by drw158** [comment]
Addition: might be nice to include the blog url:

![screen shot 2015-07-09 at 3 41 04 pm](https://cloud.githubusercontent.com/assets/618551/8606397/f267f782-2650-11e5-914f-2fbec4aa28a3.png)
