### ISSUE TITLE
Login + SignIn: Update Top Buttons Alignment

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#4013]
1. Test on an iPhone with at least one blog in the list.
2. In My Sites, tap to Add a Site
3. Notice the position of the cancel button in the sign in modal.
4. Tap the (?) button in the top right to open the support screen.

Notice the position of the Close button. There is a subtle position shift between the two screens, and the font on the login screen seems one size too small maybe?

Props to @aerych for spotting this (and actually writing the whole ticket, i'm just copy'ing and pasting his feedback on #4009).

**Comment by jleandroperez** [comment]
@aerych i'm having second thoughts on this one. Although it looks indeed inconsistent, when compared to a regular UIViewController's NavBar, for some reason, "the correct offsets" feel odd.

@drw158 we could seriously use your opinion!

[NEW Screenshot](https://cloudup.com/cq2eSWyZtpy)
[OLD Screenshot](https://cloudup.com/cwRP7ihWT4R)

Thanks!

**Comment by aerych** [comment]
>  "the correct offsets" feel odd.

Is it because its a different font size from what we normally use for the back buttons?  There was about a 2pt delta iirc.

**Comment by jleandroperez** [comment]
Font aside, i think what feels wrong (to me) is the fact that the Login doesn't really have a NavBar visible, and its bounds aren't really defined.

And thus, compressing the top buttons so much, so that we match the metrics of those views that do have a navBar... well, that's what feels odd to me.

(Just an opinion there!)
