### ISSUE TITLE
Reader: Rapidly unfollow multiple blogs glitches the UI.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4019]
In the Topics > Followed Sites list, if you edit and start unfollowing blogs quickly you can see a previously unfollowed site reappear momentarily then disappear.  
Props @designsimply

**Comment by rachelmcr** [comment]
I also encountered this issue last week while unfollowing blogs in the latest 5.8 beta.

**Comment by hoverduck** [comment]
Unable to reproduce with the current UI.  Closing.
