### ISSUE TITLE
Notifications: Links not visible in unmoderated comments

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#4037]
#### Steps:
1. Receive a Comment Notification with a link
2. Disapprove the comment

Notice that the link is not visible. Let's update the style for unapproved links, so that they're always visible.

**Comment by drw158** [comment]
How the web handles it:

![screen shot 2015-07-20 at 2 01 41 pm](https://cloud.githubusercontent.com/assets/618551/8784487/f8dd2b9c-2ee7-11e5-9705-c6c783f4bbef.png)

Not too bad.

**Comment by jleandroperez** [comment]
Ahhhh the web, always one step ahead!. Let's get iOS up to date, thank you @drw158 !!

**Comment by drw158** [comment]
The blue used is Medium Blue.
