### ISSUE TITLE
Conflict detection and resolution

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#404]
When a post/page has been updated both in the server and the app, we don't do any conflict resolution and the changes in the app can get overwritten by the revision on the server
We should (easiest first):
Always give priority to the version in the app (changes overwritten in the server can be restored through revisions)
Alert the user of the conflict and offer a choice
Ideally allow the user to review the changes, but that seems like a complex UI for mobile

**Comment by aerych** [comment]
Reopening

**Comment by aerych** [comment]
See https://github.com/wordpress-mobile/WordPress-iOS/issues/4870 for two scenarios where this is demonstrated.

**Comment by ned21** [comment]
See also #4904. The is easy to reproduce by toggling airplane mode and makes offline editing  completely unusable in 5.9.1 as local changes are always overwritten when reconnecting.

**Comment by nheagy** [comment]
#4904 was fixed, and one of the two scenarios in #4870 have been fixed as well. That leaves the latter as a more specific description of the remaining case where draft syncing can clobber more recent changes, so I'm closing this one in favor of #4870.
