### ISSUE TITLE
WP.com native stats don't work on IOS 6 IPhone 4

### ISSUE THREAD

**Issue by thegdshop** [wordpress-mobile/WordPress-iOS#4050]
WP.com native stats don't work on IOS 6 IPhone 4

Steps to reproduce: View stats page in IOS 6
Screenshot or video: http://cld.wthms.co/1awDE/3bpvQspZ
Ticket number(s): 2269870
Blog URL(s) & username(s): https://jeffblazar.wordpress.com/
Browser info: Safari IOS6 IPhone 4
Estimated # of users impacted: any using IOS6 IPhone 4
Searched and didn't find anything specific to "Stats IOS6".

**Comment by sendhil** [comment]
Hey @thegdshop - thanks for reporting this and sorry on responding slowly. This isn't WordPress-iOS related code but it's a known bug for WordPress.com and it's being looked into.

**Comment by rachelmcr** [comment]
Since this is a known bug for WordPress.com, and not related to WordPress-iOS, I'm closing this issue. Thanks for the report!
