### ISSUE TITLE
Our web view controller stutters loading some pages

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4079]
Video: 
https://cloudup.com/iJe5X-vkdXB

**Comment by rachelmcr** [comment]
I remember seeing this stuttering in the past, but I can't reproduce it right now. Have changes to the web view controller resolved this issue? I'm not sure if there's still a particular case that will reproduce this.

Tested on iPhone 6, iOS 9.1, app beta v. 5.9.0.20151216.

**Comment by aerych** [comment]
FWIW, I'm still seeing it when previewing posts on my test blog.

**Comment by rachelmcr** [comment]
Interesting, thanks for the update. I'll keep an eye out to try to catch it in action, and see if I can narrow down when it happens.

**Comment by hoverduck** [comment]
@aerych - I can't reproduce this on my sites...can you give it another shot?

**Comment by aerych** [comment]
That is some very old UI right there. :)  
This exact issue is no longer valid since we removed the pull-to-refresh control from the preview screen.  However, there is a somewhat related issue where the loading spinner will rapidly disappear and reappear as various bits of content are being loaded. 
It vexes me and I've had it on my personal list of todos to either remove the spinner outright, or to silence it after the main page loads.  Let's leave it open and I'll whip up a patch for it directly.
