### ISSUE TITLE
App is stripping EXIF data from posts

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#408]
Photos taken with the camera app and added through the app have the GPS set correctly (which is what I was testing), but if the photo is taken with WP, saved to camera roll, then imported it loses it.

**Comment by rachelmcr** [comment]
I tested in beta v. 5.8.0.20151124 with these results:

1. I turned off geotagging on my site, uploaded an unedited image, and the image included EXIF data but not location.
2. I turned on geotagging on the same site, uploaded an unedited image, and the image included EXIF data (including location).
3. I left geotagging on, uploaded an edited image, and the image included EXIF data (including location). (I tested with editing the photo in the Photos app, and another third-party app, with the same results.)

I'm closing this issue as it seems we are currently only stripping location data, and that location data is stripped when geotagging is disabled. If this is still an issue under certain conditions, please reopen.

**Comment by kitchen** [comment]
blast from the past!

question: you said "turn off geotagging on my site", where is this? I'm running into this issue currently, but where I can't get geo exif data on *any* pictures, whether imported from camera roll or taken directly from the app. I've tried various combinations of making sure the post I'm adding has a location set (which does get preserved into the `PREFIX_postmeta` table on my site), taking picture from the app, loading it from camera roll, etc, and none of the geo exif data is being preserved at all.

If I upload the photo using the web interface, then the exif data is preserved.

FWIW I'm using latest version of wordpress and am self-hosting. I have jetpack's image acceleration disabled on my dev site for testing purposes (just to make sure jetpack's CDNing isn't causing any problems)

Thanks!

**Comment by kitchen** [comment]
I should clarify: uploading the photo using the web interface from my laptop. I'm well aware that safari on ios strips geolocation exif data from photos before uploading (or at least, has in the past, when I've tried to do these sorts of things).

**Comment by astralbodies** [comment]
@kitchen The geotagging option is per-post now and not a site-wide option. To turn on/off stripping of location data from images go to the Me tab, App Settings, and flip "Remove Location From Media" off.

**Comment by kitchen** [comment]
aha! that did it. Thanks!
