### ISSUE TITLE
Reader: Menu refresh

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4094]
A refresh of the Reader's menu.  
We'll match the menu used on the web.  The menu will become the root / starting view of the reader. 
Relevant designs: 
https://cloudup.com/iUs35k4xJxi
https://marvelapp.com/66gi8f#7304266

![k-dbb_q87z-3000x3000](https://cloud.githubusercontent.com/assets/1435271/16235065/17aa6660-3799-11e6-9b1d-02ed5d18793d.png)

### Edit: 
We'll stage the roll out of the new menu in a series of feature flagged PRs:
- [x] Introduce the basic menu
- [x] Add tag management
- [x] Add site management
- [x] Enable syncing and state restoration
- [x] Final design review
- [x] Add analytics and remove feature flag.
- [x] Remove the old menu code and ReaderSite entity.

**Comment by SergioEstevao** [comment]
@aerych Is this still open? If yes do you mind updating the Milestone?

**Comment by aerych** [comment]
Current progress for reference:
![simulator screen shot jun 21 2016 10 04 33 am](https://cloud.githubusercontent.com/assets/1435271/16235121/52ef32f0-3799-11e6-9b22-1ba69d7562ff.png)

**Comment by aerych** [comment]
Pinging @mattmiklic and @jancavan for some design feedback.  I'd like your opinions on the best way to tackle in iOS the "manage" buttons that we show beside certain options in the web reader. 

For reference: 
<img width="274" alt="screen shot 2016-06-21 at 10 06 25 am" src="https://cloud.githubusercontent.com/assets/1435271/16234994/d692a80e-3798-11e6-9b1e-4928412b7e59.png">

I want to match the web as closely as possible, but I'm not 100% sure about introducing a "Manage" button inside one of the cells (Following and eventually lists), mostly because of horizontal space considerations and localizations.  Would a gear icon, make more senss, or perhaps an ellipsis as used in the Music app? 

Thoughts?

**Comment by jancavan** [comment]
@aerych I think the word "Manage" is better, but I agree that we may run into i18n issues. I tried just using the cog icon, but it feels like there's quite a few icons in one line already. I also don't think this option needs to be permanently on there since they don't have to access this all the time:

![cog](https://cloud.githubusercontent.com/assets/4924246/17031313/43107384-4f28-11e6-90c5-f1c2a32cba02.jpg)

What about adding an "Edit" link and tapping on that brings up the cog icon?

![edit](https://cloud.githubusercontent.com/assets/4924246/17031329/6164fe90-4f28-11e6-8f60-6f68521b9f79.jpg)

![done](https://cloud.githubusercontent.com/assets/4924246/17031336/68c06d1e-4f28-11e6-8cdf-bd94c8739f1f.jpg)

Although I think this might affect how we handle tags/lists since those you're able to delete through swiping.

**Comment by jancavan** [comment]
Another idea would be to just add it to the Following screen. It's not an exact match to Calypso, but I think is an efficient solution:

![screenshot-2016-07-21-10 16 54](https://cloud.githubusercontent.com/assets/4924246/17032132/9c559128-4f2c-11e6-852c-2ddcb1f0ad7a.jpg)

The Search icon there is also confusing. I thought it was only to search my followed sites when it's actually the same Search on the main menu.

**Comment by mattmiklic** [comment]
> Another idea would be to just add it to the Following screen. It's not an exact match to Calypso, but I think is an efficient solution:

This seems like the best idea to me -- it's the easiest-to-find option when you're already looking at the Reader, which seems like the time when the user's most likely to need the button. 

It would be OK to put an icon in the list -- but if we did, I think it would have to be a standard detail disclosure button (the circled "i" icon), otherwise I'm not sure it would be clear that both the row and the icon are both tappable, and that they do separate things.

So, I think the toolbar placement is the way to go. 👍

**Comment by jancavan** [comment]
Thanks @mattmiklic.

> otherwise I'm not sure it would be clear that both the row and the icon are both tappable, and that they do separate things.

Agreed.

@aerych Just to reiterate, this is what we currently have. I'm not sure why Search is on there, I thought I was searching just my followed list, but it's really all of wpcom. Let's just replace this with Settings.

![screenshot 2016-07-21 10 44 50](https://cloud.githubusercontent.com/assets/4924246/17032913/71431434-4f30-11e6-9627-dff28ad7339f.png)

The other Search we have on the main menu is sufficient and matches with Calypso:

![screenshot 2016-07-21 10 50 07](https://cloud.githubusercontent.com/assets/4924246/17033023/ef61ae66-4f30-11e6-9401-1551c2a03df5.png)

**Comment by aerych** [comment]
> I also don't think this option needs to be permanently on there since they don't have to access this all the time:

Oh? When would Manage Sites not be available to a signed in user? 

> @jancavan : Another idea would be to just add it to the Following screen
@mattmiklic [...] it's the easiest-to-find option when you're already looking at the Reader, which seems like the time when the user's most likely to need the button

I think I disagree.  Putting this under the Following feels like its buried to me.  I think its more useful when its available from the menu, particularly since we can now browse/preview all the posts on a site.  Moving the Manage feature to the top of the following feed would add an additional step. 

FWIW, I've mostly gotten over any concerns I had initially. If you run the develop branch you can see the Manage button in the simulator?  https://cloudup.com/cm2rluEszbf   It works pretty well that way.  If you feel strongly about moving it to the top of the following list then I'll make the change but maybe its okay as is? 


> The Search icon there is also confusing

We did this for the first pass of Search before we had the menu as the first screen of the reader.  When the feature lands these icons will go away and Search will only be accessed from the Menu.

**Comment by mattmiklic** [comment]
> I think I disagree. Putting this under the Following feels like its buried to me. I think its more useful when its available from the menu, particularly since we can now browse/preview all the posts on a site. Moving the Manage feature to the top of the following feed would add an additional step.

Wouldn't it be more buried in the menu? If I'm looking at the Reader, a gear icon in the toolbar is one tap away. Putting it inside the menu means that it would be hidden, so you'd have to know to tap Menu first, then you'd have to tap a small icon inside the row for Followed Sites.

**Comment by aerych** [comment]
> Wouldn't it be more buried in the menu? If I'm looking at the Reader, a gear icon in the toolbar is one tap away. Putting it inside the menu means that it would be hidden, so you'd have to know to tap Menu first, then you'd have to tap a small icon inside the row for Followed Sites.

The new menu is the first screen of the Reader. :D  It is the font from which all content flows. You won't see it in the beta as its feature flagged, but if you give the develop branch a run you can try it and see what you think.

**Comment by jancavan** [comment]
> Oh? When would Manage Sites not be available to a signed in user?

I just mean that they only have to access this screen occasionally. They don't have to manage their followed list all the time.

> We did this for the first pass of Search before we had the menu as the first screen of the reader. When the feature lands these icons will go away and Search will only be accessed from the Menu.

👍 

> but if you give the develop branch a run you can try it and see what you think.

Yeah, I checked this out. It works, but I thought the other issue we were tying to solve was also i18n?

**Comment by aerych** [comment]
> I just mean that they only have to access this screen occasionally. They don't have to manage their followed list all the time.

Ah, gotcha! 

> but I thought the other issue we were tying to solve was also i18n

True. But after taking a closer look, maybe its not so bad.  German has seemed to me to be a good benchmark when testing i18n concerns and horizontal width.  "Followed Sites" is "Gefolgt Seiten" (I think) and "Manage" is "Verwalten" which still leaves us with good separation between the row title and the button.   Unless we're seeing the labels truncated to an ellipsis maybe we're okay.

**Comment by mattmiklic** [comment]
> The new menu is the first screen of the Reader. :D It is the font from which all content flows. You won't see it in the beta as its feature flagged, but if you give the develop branch a run you can try it and see what you think.

Oh, whoa. Have we talked about the potential implications of this change? I'm concerned that presenting the user with a menu when they tap "Reader" could potentially have some negative side effects. On Calypso (mobile web) we don't follow this pattern, so I'm just curious as to whether this has been thought completely through.

**Comment by aerych** [comment]
> Oh, whoa. Have we talked about the potential implications of this change?

I believe so. Making the menu the first screen has long been planned (over a year?). You can see the links to @shaunandrews original designs above.  Never a bad idea to revisit and rethink tho. 

> I'm concerned that presenting the user with a menu when they tap "Reader" could potentially have some negative side effects.

Well.. its less accurate to say that it will always be the first screen that a user sees. Rather its the first screen in the reader's navigation stack on an iPhone, and would be the side bar in a split screen on the iPad.  
On an iPhone, state restoration should ensure that when a user resumes the app they will always see the content they were last viewing rather than being always taken back to the menu.  
Also, the very first time the Reader accessed (new install, or after first sign-in) the plan is to mimic the trick we use in the My Sites tab when a user has only a single site and force push the Discover feed.

**Comment by aerych** [comment]
>  German has seemed to me to be a good benchmark when testing i18n concerns and horizontal width

Here's a iPhone 4s screenshot for German. Seems okay? 
![simulator screen shot jul 21 2016 2 20 17 pm](https://cloud.githubusercontent.com/assets/1435271/17035685/5e058a3c-4f4e-11e6-95b4-dc365e5a2a99.png)

**Comment by jancavan** [comment]
To me, it implies that Manage is associated with the arrow, that they both jump to the same screen. Especially also because both screens (Manage and Followed sites stream) slide from the right. Can Manage slide from the bottom at least?

**Comment by aerych** [comment]
Epic chat with @mattmiklic about the Manage button.  To summarize: 
- Having "Manage" as an accessory view seems a bit wonky and we don't do it anywhere else.
- If we move the Manage feature to the Followed Sites list it should still be intuitive to find from the Menu, even if its an extra tap.  Its also handy to folks browsing Followed Sites when its on that screen. 
- When a feature is accessed from an icon in the navbar, its implicit that you are existing the current navigation context and calls for a modal presentation, which isn't necessarily what we want.
- A modal presentation would hide the tab bar, removing the ability to tap the Reader tab to return to the Menu.
- We could show a Done button in a modally presented Manage feature, and continue to show a Done button as a user browsed through post lists, previewing tags, etc.  But it would likely be a bit hacky to implement and probably isn't a very good practice. 
- Another option is to display the Manage feature in a style similar to the "topic header" that is shown at the top of tag lists, and previewed sites.  This would keep the navigation horizontally flat, avoiding modals, and potentially hacky Done buttons.

We ended up agreeing that the header sounds like a nice compromise between what’s easiest for the user to find, and what’s implement-able without a lot of hackiness. So I'll whip up a version of one and we can see how it plays. 

@mattmiklic please make any corrections if there's something i missed.

**Comment by mattmiklic** [comment]
Good summary! My main concern was wanting to connect the place where you access the Manage screen as closely as possible to the place where you read the sites you're managing. I [sketched out](https://cloud.githubusercontent.com/assets/1396552/17041765/480ba3b0-4f76-11e6-821a-120a5610a309.jpg) the icon in toolbar/modal view idea, but after Eric explained the technical challenges in implementing that design, agree that putting in the header instead was the best balance of findability and ease of implementation.

**Comment by jancavan** [comment]
So the cog icon will be added to the Followed Sites screen like the [mockup above](https://github.com/wordpress-mobile/WordPress-iOS/issues/4094#issuecomment-234322539), correct? Just that it'll slide from the left instead of from the bottom?

I think that makes the most sense. My suggestion of sliding from the bottom was only because "Manage" was sitting next to the arrow and they both slide from the right even if they're two entirely different screens.

**Comment by aerych** [comment]
Here is a rough example of a stream header for Followed Sites. Tapping the header would open the Manage Sites screen. 
![simulator screen shot jul 25 2016 4 15 21 pm](https://cloud.githubusercontent.com/assets/1435271/17117773/5c5c42d8-5283-11e6-9f3f-9e6cc35e5ae5.png)

@jancavan @mattmiklic thoughts?
