### ISSUE TITLE
App crashes when changing post title after uploading a video

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#4098]
Reported by a user. Title basically has it. Steps to repro:

1. type in title
2. upload video
3. try to change title
4. 4-6 keystrokes later, app freezes
5. close app, reopen
6. app crashes

User followed up with:
> I saved it to draft and then tried to edit the title, and the same stuff happens. :)

/cc @SergioEstevao

**Comment by bummytime** [comment]
I should add I was able to repro this on my 6+ running 8.4.

**Comment by rachelmcr** [comment]
A fix was merged for this bug in #4116. I tested on the latest beta and confirmed it is no longer an issue. Closing as resolved.
