### ISSUE TITLE
"pod install" fails on "CrashlyticsLumberjack (2.0.1-beta)"

### ISSUE THREAD

**Issue by susered** [wordpress-mobile/WordPress-iOS#4107]
I could be executing something incorrectly, but I thought I put all the dependencies into place to execute a "pod install" command against the "develop" branch. However, I getting a CrashlyticsLumberJack dependencies error.

Any ideas?

$ xcodebuild -version
Xcode 6.2
Build version 6C131e

$ git show
commit f99ed547ad4ebdf5aef60279a164a5691729f6a9
Merge: 9bd1272 bf2ea08
Author: Diego Rey Mendez <diegoreymendez@users.noreply.github.com>
Date:   Sat Aug 1 15:17:39 2015 +0100

    Merge pull request #4072 from wordpress-mobile/issue/3902-theme-services-2
    
    Review of remote theme services

$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.

nothing to commit, working directory clean

$ git pull && pod install --verbose
Already up-to-date.
  Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  Already up-to-date.

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-WordPressTodayWidget`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-WordPressTest`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-UITests`: (``)

Finding Podfile changes
  - 1PasswordExtension
  - AFNetworking
  - AMPopTip
  - Automattic-Tracks-iOS
  - CocoaLumberjack
  - CrashlyticsLumberjack
  - DTCoreText
  - EmailChecker
  - Expecta
  - FormatterKit
  - Helpshift
  - HockeySDK
  - KIF/IdentifierTests
  - Lookback
  - MGImageUtilities
  - MRProgress
  - Mixpanel
  - NSLogger-CocoaLumberjack-connector
  - NSObject-SafeExpectations
  - NSURL+IDN
  - OCMock
  - OHHTTPStubs
  - Reachability
  - ReactiveCocoa
  - SVProgressHUD
  - Simperium
  - SocketRocket
  - Specta
  - UIDeviceIdentifier
  - WPMediaPicker
  - WordPress-AppbotX
  - WordPress-iOS-Editor
  - WordPress-iOS-Shared
  - WordPressApi
  - WordPressCom-Analytics-iOS
  - WordPressCom-Stats-iOS
  - google-plus-ios-sdk
  - wpxmlrpc

Fetching external sources
-> Pre-downloading: `Automattic-Tracks-iOS` from `https://github.com/Automattic/Automattic-Tracks-iOS.git`, tag `0.0.5`
  > Copying Automattic-Tracks-iOS from
  `/Users/ldb/Library/Caches/CocoaPods/Pods/External/Automattic-Tracks-iOS/f353f20fdc2dd7791377a9f9f681134d`
  to `Pods/Automattic-Tracks-iOS`
-> Fetching podspec for `EmailChecker` from `https://raw.github.com/wordpress-mobile/EmailChecker/develop/ios/EmailChecker.podspec`
-> Pre-downloading: `MGImageUtilities` from `git://github.com/wordpress-mobile/MGImageUtilities.git`, commit `e946cf3d97eb95372f4fc4478bf2e0099e73f4b0`
  > Copying MGImageUtilities from
  `/Users/ldb/Library/Caches/CocoaPods/Pods/External/MGImageUtilities/7aa858bd1d225d0aa82586c4cdf087d9`
  to `Pods/MGImageUtilities`
-> Pre-downloading: `NSLogger-CocoaLumberjack-connector` from `https://github.com/steipete/NSLogger-CocoaLumberjack-connector.git`, tag `1.5`
  > Copying NSLogger-CocoaLumberjack-connector from
  `/Users/ldb/Library/Caches/CocoaPods/Pods/External/NSLogger-CocoaLumberjack-connector/aeafc0dd8d65db43f8b30d3f7488f555`
  to `Pods/NSLogger-CocoaLumberjack-connector`
-> Pre-downloading: `SocketRocket` from `https://github.com/jleandroperez/SocketRocket.git`, commit `3ff6038ad95fb94fd9bd4021f5ecf07fc53a6927`
  > Copying SocketRocket from
  `/Users/ldb/Library/Caches/CocoaPods/Pods/External/SocketRocket/f594506bf803753d4191b6f9fab82211`
  to `Pods/SocketRocket`
-> Pre-downloading: `WordPress-AppbotX` from `https://github.com/wordpress-mobile/appbotx.git`, commit `303b8068530389ea87afde38b77466d685fe3210`
  > Copying WordPress-AppbotX from
  `/Users/ldb/Library/Caches/CocoaPods/Pods/External/WordPress-AppbotX/03531b728b72c0ff5850d19197531098`
  to `Pods/WordPress-AppbotX`
-> Pre-downloading: `WordPress-iOS-Editor` from `https://github.com/wordpress-mobile/WordPress-Editor-iOS.git`, commit `a983547b5724d5fc3b79865da83e81db2b0b9de4`
  > Copying WordPress-iOS-Editor from
  `/Users/ldb/Library/Caches/CocoaPods/Pods/External/WordPress-iOS-Editor/729a84d02df22210732c4c2241ce1668`
  to `Pods/WordPress-iOS-Editor`

Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `CrashlyticsLumberjack/Framework (= 2.0.1-beta)` required by `CrashlyticsLumberjack (2.0.1-beta)`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:388:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:56:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:535:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:533:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by sendhil** [comment]
We're currently having issues with CocoaPods 0.38 and most of us are still using 0.37.

**Comment by susered** [comment]
Much thanks ... I see 0.37.2 works well now ..
