### ISSUE TITLE
Normalize Top Paddings

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#4128]
#### Details:

Let's normalize the top padding for the following sections:
- [x] My Sites
- [x] Support
- [ ] Activity Logs
- [x] Editor > Site Picker
- [x] Editor > Categories
#### Notes:
- iPad devices should maintain the current 40pt top padding.
- iPhone devices should replicate the new **Settings UI** top padding (which is UITableView's standard for grouped tables).
- Since we're now moving towards UITableView's default top padding, let's analyze and nuke the `WPTableHeaderPadFrame` workaround we've got all over.
- Update **WPTableViewSectionHeaderFooterView** so that it matches the following mockup:

![iorz6rw2zs-3000x3000](https://cloud.githubusercontent.com/assets/1195260/9123568/bea21622-3c66-11e5-8e2c-0367fcf491a0.png)

@drw158 thanks for helping me out!

**Comment by hoverduck** [comment]
@jleandroperez - the only thing left on your list here is the Activity Logs section, but the padding on that looks ok to me.  Can you confirm whether that was done already and we can close this issue?

**Comment by jleandroperez** [comment]
@hoverduck confirming that this looks fixed (highly likely by @frosty or @kurzee's awesomeness)

Thanks for checking sir!!!
