### ISSUE TITLE
Add new content to reader when you follow someone new

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#413]
I'm not sure if it's really a bug but it's something that feels weird:

- I installed the app and logged in with a test user
- My reader had 2 posts, so I went for the friend finder
- I followed 5-6 people
- After dismissing the friend finder my reader still has 2 posts
- Pull to refresh brought new content

**Comment by aerych** [comment]
Closing since we've pulled the friend finder.  We'll revisit if/when a native friend finder implementation is rolled out.
