### ISSUE TITLE
App Crashes When Adding Image to a Post

### ISSUE THREAD

**Issue by BFTrick** [wordpress-mobile/WordPress-iOS#4130]
I have one post that's in a draft state on my [WordPress.com hosted site](http://patricks40khobby.com/). I tried adding a photo to the post. I see a spinning wheel and then it crashes.

At first I thought it had something to do with loading all of the images on my iPad but that doesn't seem to be it. I deleted all but ~20 of them so that's not it. And I only have another ~20 in the deleted folder.

Using: WordPress 5.3.1 from the app store
Device: [Apple iPad 2 MC770LL/A Tablet](http://www.amazon.com/Apple-iPad-MC770LL-Tablet-Generation/dp/B001I907I2)

Video reproducing the error: https://youtu.be/8pbNt1Sm4rM

**Comment by aerych** [comment]
Hi @BFTrick Can you confirm if this is still happening or if it has been resolved with version 5.4.1?

**Comment by BFTrick** [comment]
Negative. Just updated to 5.4.1. 

* Opened blog posts
* Clicked edit on a draft post
* Clicked the cursor inside the post
* Clicked on the media icon
* Crash :(

It's definitely trying to load the images. For a split second this screen comes up and then it crashes.

![2015-08-21 10 32 01](https://cloud.githubusercontent.com/assets/1065372/9413600/0a0f9be0-47f0-11e5-866c-9d8fbbe3b718.png)

**Comment by aerych** [comment]
Maybe handled in https://github.com/wordpress-mobile/WordPress-iOS/pull/4173 
Leaving open to confirm.

**Comment by SergioEstevao** [comment]
This should be fixed on 5.6, wait for it to be release on the AppStore to confirm it.

**Comment by rachelmcr** [comment]
@BFTrick Can you confirm if this issue is resolved with the latest release, or if it's still happening for you?

**Comment by BFTrick** [comment]
Confirmed. :)
