### ISSUE TITLE
Reader: Cells can get stuck in a pressed state.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4133]
Props @jleandroperez 

Steps to reproduce:

1. Launch the app
2. Tap over the Reader’s tab
3. Open the details for (any) post
4. Swipe back from the left edge of the screen (don’t just hit the Back button)

Sometimes the Reader’s card remains in pressed-down state and won’t accept touch interaction (if you try to scroll up / down, it’ll just swallow the touch events)

**Comment by aerych** [comment]
@jleandroperez try as I might I can't reproduce this with the new cards. I'm testing on an iPhone 6s.  
Are you able to repro?  If not I think we can close this one.

**Comment by jleandroperez** [comment]
@aerych just confirming that this is not happening anymore, with the latest Reader code.

Thank you sir!
