### ISSUE TITLE
Media problems with iCloud Photo Library 

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#4141]
I was trying to add an image to a post that was a bit old, so I started scrolling through my photos on the image picker but couldn't find it. The album selector said that my 'all photos' collection had about 400 items, but the photos app said 2000+. I noticed it had my latest photos then some really old ones that were on my iPad's camera roll. 
I noticed some other albums that showed a thumbnail but 0 images. 

I switched to the photos app, opened that album, and viewed one of the images. I noticed it had to download it from iCloud. When I switched back to the app the photo popped up, but then the app crashed.

I went back to the photos app to find the photo I originally wanted, made sure it was preloaded, and then it was available in the app.

**Comment by koke** [comment]
Short answer is that we should migrate to the `Photos` framework but it's iOS8 only. This might be related: https://stackoverflow.com/questions/26480526/alassetslibrary-assetforurl-always-returning-nil-for-photos-in-my-photo-stream

**Comment by SergioEstevao** [comment]
@koke waiting for us to drop iOS 7 support to implement this.
