### ISSUE TITLE
Posts list: show sticky posts at the top of the list for easy editing

### ISSUE THREAD

**Issue by lancewillett** [wordpress-mobile/WordPress-iOS#4155]
Suggested by Ryan Boren:

Posts list doesn’t show sticky posts, iOS app beta, iPhone 6+

This site has 23 posts and 7 stickies. Only 16 posts show in the app. I want to edit the two Bathroom Remodel posts at the top of the wp-admin list but can’t get at them in the app.

![ios-list](https://cloud.githubusercontent.com/assets/66797/9263981/cef000d2-41d6-11e5-8198-f2cfb8654db3.png)

![wpadmin-list](https://cloud.githubusercontent.com/assets/66797/9263992/e70f94e8-41d6-11e5-9c3f-32cdb9b3e2f8.png)

Possibly related to #3968.

**Comment by bummytime** [comment]
This is a pretty old issue, so providing an update. With the Calypso redesign, not moving sticky posts to the top of the list is consistent with the web:

<img width="446" alt="napkin 32 12-14-16 10 16 21 am" src="https://cloud.githubusercontent.com/assets/154014/21190366/2424a2ec-c1e7-11e6-9d26-2021ad02cc04.png">

However, we still don't have sticky post support at all really and it should be there. I am going to close this issue and redirect everyone to this one: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/197 for all things sticky. :-)

**Comment by shaheero** [comment]
+1
