### ISSUE TITLE
Remove Facebook from URL Schemes

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4161]
I'm noticing an issue once in a while when tapping on a WordPress.com publicized post in the Facebook iOS application. Instead of the URL loading in the browser, it's launching the WPiOS application and the app does nothing with it.

Since we're not using the Facebook SDK at this time, I suggest we remove the `fb*` URL Scheme from Info.Plist.

**Comment by m** [comment]
Wouldn't it be better to correctly handle these links, either by displaying in the Reader or launching a browser?

**Comment by astralbodies** [comment]
@m Ideally, yes. I wanted to eliminate the broken behavior before it affected more people. I'm not quite positive what's going on with the FB app integrating with ours. The URL sent to the WPiOS app was an authorize request into the Facebook SDK which we don't/haven't supported for some time. Something changed in those posts publicized to FB that's causing them to launch our app. I'm making an assumption it's deep linking, but I could be wrong.

It does warrant further digging into, but this issue was just to get rid of the stabby behavior until we can figure out what to do next :smile:
