### ISSUE TITLE
Unable to satisfy CrashlyticsLumberjack dependency

### ISSUE THREAD

**Issue by fatalaa** [wordpress-mobile/WordPress-iOS#4168]
After a fresh `git clone`I got the following error:

`[!] Unable to satisfy the following requirements:`
`- CrashlyticsLumberjack/Framework (= 2.0.1-beta) required by CrashlyticsLumberjack (2.0.1-beta)`

After setting CrashlyticsLumberjack's version to 2.0.0 from 2.0.1-beta, the problem disappeared.

Shall I make a PR about this?

**Comment by aerych** [comment]
There is a conflict with the current version of cocoapods. You should be able to avoid the error by using cocoapods version 0.37.2.
