### ISSUE TITLE
Can't run app on iPad 2 after update

### ISSUE THREAD

**Issue by korobochkin** [wordpress-mobile/WordPress-iOS#4178]
After latest app update from the App Store application crashes on startup. I use iPad 2 with iOS 8.4.1 (12H321). App version 5.4

**Comment by aerych** [comment]
Sorry @korobochkin, this one slipped by us.  Are you able to run the latest version, 5.6.1?

**Comment by korobochkin** [comment]
I have already installed iOS 9 on iPad 2 (iOS 9.1 13B143). WordPress App — 5.6.1. App crashes on startup as before. I see loading screen (launch image) and then app crashes.
P. S. Many apps which working great on iOS 8 after upgrade to iOS 9 crashes at first launch but secondary launch and well done. Ah. But WordPress app stop working on iOS 8.

**Comment by aerych** [comment]
Does the app continue to crash after deleting and installing a fresh copy from the app store?

**Comment by korobochkin** [comment]
After deleting and reinstalling the app from the App Store and... It's working! All tabs correctly working. Thank you! But it's weird that after reinstalling all my sites added previously in app still there.

**Comment by aerych** [comment]
> It's working!

Yay!!

> But it's weird that after reinstalling all my sites added previously in app still there

If you resynced from iTunes and have it set to back up your app data, that might be why. 

Again, sorry it took us so long to respond.  Just for a future note, you're likely to get a faster response on the support forum: http://ios.forums.wordpress.org 

Cheers!
