### ISSUE TITLE
Notifications: Wire Reader Browser

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#4181]
#### Steps:
1. Receive a New Follower notification
2. Tap over any of the User Rows

As a result, a WebView will be displayed. Let's, instead, push the native view (`ReaderBrowseSiteViewController`). Plus, the upcoming `Header` should also push the native Site Browser.

**Comment by roundhill** [comment]
Much needed, thank you sir!

**Comment by jleandroperez** [comment]
On the contrary, thanks for the feedback @roundhill, absolutely love the idea!
