### ISSUE TITLE
Post & Page Lists: It can be unclear which "undo" view is for which trashed post.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4185]
We support undoing multiple trashed posts, however the undo view does not provide any context about a post that was trashed.   We should at least show the title of the trashed post, but maybe some more details wouldn't hurt.  

cc @mnt and @adambbecker, We could use some designer input here.

![img_0127](https://cloud.githubusercontent.com/assets/1435271/9415848/a96f37c4-4807-11e5-8b1d-aed516259059.png)

**Comment by aerych** [comment]
Props @koke, who reported the issue

**Comment by mnt** [comment]
I wonder if, instead of the undo action being presented on a card in the list, these should be more like notices; temporary messages that go away. Moving something to the trash isn't a destructive action, so it's not important that the user is able to undo multiple move-to-trash actions from the post list. Just 2¢; @adambbecker may have alternative ideas.

**Comment by bummytime** [comment]
Just the friendly neighborhood groundskeeper passing through. Looks like this is still an issue:

<img width="364" alt="napkin 33 12-14-16 10 35 05 am" src="https://cloud.githubusercontent.com/assets/154014/21190889/0c3541da-c1e9-11e6-9b3b-f0ea21b62917.png">

@mattmiklic, I agree this is not a destructive issue and perhaps not really a priority. Any thoughts at looking at a temporary message option, closing this issue, or leaving it be for now?

**Comment by mattmiklic** [comment]
There might be some value in looking at a solution more similar to Calypso, where the post doesn't completely disappear, but fades out with the "moved to trash" message overlaid on top. Don't think it's a pressing issue though, at least given other priorities.

**Comment by kean** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/21724
