### ISSUE TITLE
Enable style

### ISSUE THREAD

**Issue by tinhbka** [wordpress-mobile/WordPress-iOS#4191]
if text body is nil, text style don't enable. Please check this issue!
eg: clear all element in body text then choose style bold, oop! style not working :(

**Comment by tinhbka** [comment]
did you testing ? please help!

**Comment by tommi** [comment]
I can reproduce this issue for bold and italic. Blockquotes work fine though. Seems like an issue of https://github.com/wordpress-mobile/WordPress-Editor-iOS

**Comment by tinhbka** [comment]
i'm trying fix but not work :(

**Comment by rachelmcr** [comment]
I opened a new issue for the iOS editor here: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/741

I am closing this issue, and you can follow along with that new issue. Thanks for the report!
