### ISSUE TITLE
Notifications: Updates from WordPress.com Description

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#4203]
Let's update the WordPress.com setting description as follows:

![kewhuhdt6z-3000x3000](https://cloud.githubusercontent.com/assets/1195260/9471682/df1906d4-4b27-11e5-984a-873767754102.png)

**Comment by drw158** [comment]
I have an idea for this one that would align it with Android. Mind holding off on this until I get a chance to post on this issue?

**Comment by jleandroperez** [comment]
Sure! thanks for checking Dave!

**Comment by drw158** [comment]
This one will probably be solved by #4241

**Comment by jleandroperez** [comment]
Closing this one, since `Updates from Wordpress.com` has been already renamed to `Emails from WordPress.com`.

Thanks Dave!
