### ISSUE TITLE
Editor - Animation is choppy when opening the editor first time

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#4210]
Because the editor is defaulting to preview mode and then we switch it to edit mode immediately, the animation is a little choppy. Perhaps we can remove the preview mode from the editor altogether?

**Comment by bummytime** [comment]
@SergioEstevao Ok to close this issue?

**Comment by bummytime** [comment]
Closing, no longer an issue because the visual editor is retired.
