### ISSUE TITLE
Title Field: Japanese Text Input Issue in HTML Mode

### ISSUE THREAD

**Issue by naokomc** [wordpress-mobile/WordPress-iOS#4213]
In the title field, if you press the Japanese keypad for turing a character into a "voiced consonant" while in HTML mode, the character turns into a black smiley ☻

![ios-ja](https://cloud.githubusercontent.com/assets/34067/9509844/76d815a0-4c9f-11e5-83a9-832557d030c0.png)

Steps to reproduce:

1. Add Japanese kana/flick Keyboard (Settings -> General -> Keyboards -> Add New Keyboard, then select Japanese -> Kana)
2.. Open WP for iOS app, and create a new post.
3. Switch to HTML mode.
4. While in the text field, tap the globe icon in the keypad.
5. Press "さ" (next to the delete key, third character in the top row)
6. Then press the key which looks like this -> ^_^ (next to the microphone, first in the bottom row)
7. You are suppose to see "ざ" but you get "さ☻"

If you repeat the steps 5-6 in normal (visual) mode, you will see a correct character "ざ".

This issue doesn't seem to effect other fields.

**Comment by rachelmcr** [comment]
Thanks for the clear steps! I tested and reproduced this issue on iPhone 6, iOS 9.1, app beta v. 5.9.0.20151216. For reference, the smiley face is U+263B.

**Comment by diegoreymendez** [comment]
@naokomc, @rachelmcr - I'm having some trouble reproducing this, as once I type the first character, the second one changes shape.  I'm attaching a video showing the problem - I'm pretty sure I must be missing something.

Here's [the video](https://cloudup.com/cILjidmsR5z).

**Comment by naokomc** [comment]
@diegoreymendez I am no longer seeing this bug anymore on the current beta build 6.3.0.20160524.
