### ISSUE TITLE
When updating your password, if you've reached the login limit the app will refuse good credentials.

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#422]
This is the service acting as expected but its a bad user experience.

- Change your password on your blog.
- Go in to the app and try to view posts, pages, comments. Just get the "can't sync" error a few times.
- Go to blog settings to edit your password.
- Misspell your password once or twice. (You have big thumbs on a tiny screen.)
- Type in the correct password and save.

DOH! Denied! 
This is because you've tried to access your blog with bad credentials too many times but the message the user sees doesn't say this.

Maybe we can improve the text of this error message to reflect this case.

**Comment by koke** [comment]
We don't use password-based authentication on wp.com anymore. Closing this
