### ISSUE TITLE
Post List: Maybe show the full date for scheduled posts

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4222]
There is a UX issue with scheduled posts reported by users via the App Store review, and the WPiOS forum. 
It can be helpful to see the exact date/time a scheduled post will be published vs the short date string we currently use.

**Comment by hoverduck** [comment]
Here's how it looks currently on two screens where adding the time would be beneficial:

Successfully Scheduled:
![screen shot 2017-01-24 at 1 47 00 pm](https://cloud.githubusercontent.com/assets/7233112/22261668/cb73d18e-e23b-11e6-9a6c-c84b6af82219.png)

Posts List:
![screen shot 2017-01-24 at 1 47 21 pm](https://cloud.githubusercontent.com/assets/7233112/22261663/c84671d8-e23b-11e6-93c7-357af665fe3c.png)
