### ISSUE TITLE
Handle Facebook auth requests for deep linking

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4228]
Related: #4161 

Mid-August 2015 the app started getting redirects on device from the Facebook iOS app when users were tapping on articles posted to WordPress.com. Intercepting these URL calls shows that FBiOS was sending an `/authorize` request to WPiOS which I assume requires the Facebook SDK in the WPiOS app to process. I do not actually know what the final call to WPiOS would have been since we do not integrate the FB SDK into the app any more.

The previous registered protocol was `fb249643311490://`. Ideally we'd like to see if providing the user a deeper experience with the Facebook app improves their user experience with WordPress.com. So this issue has a few parts:
1. Confirm the behavior identified in #4161 was related to deep linking. Figure out why this suddenly changed on Facebook's end. Potentially temporarily install the Facebook SDK and intercept all of the calls to trace what is actually happening.
2. Confirm that we have our Facebook application configured properly (developer.facebook.com) - initially when I poked around in our settings it felt like the iOS app may be configured wrong or not enough. I'm wondering if the iOS app actually needs its own Facebook app config instead of borrowing the one used for Publicized.
3. Investigate the deep linking capabilities from Facebook, see what we're already doing with the Reader (both @aerych and @nbradbury have indicated we do listen for `wordpress://` URLs and launch into a post even if its not on the device).

cc: @sendhil, @m, @aerych, @jkudish

**Comment by alexcurylo** [comment]
I'm adding Publicize as part of Calypso sharing in #4105 and having trouble getting Facebook to work with their keyring authentication through UIWebView, so borrowing the Publicize app config sounds like a great idea.

**Comment by jkudish** [comment]
Anything in particular i can help with here?

**Comment by astralbodies** [comment]
Nothing yet @jkudish just wanted to loop you in since the FB app was behaving poorly with the WPiOS app. :smile:

**Comment by aerych** [comment]
@astralbodies any follow up on this one?

**Comment by astralbodies** [comment]
Nope nothing yet @aerych - it sort of fell aside after priorities were refocused on feature parity with what's going on with .com.

**Comment by hoverduck** [comment]
@astralbodies there hasn't been any traffic on this issue in over a year...is it still relevant?

**Comment by astralbodies** [comment]
Lets just close it for now - I haven't heard much about it since I originally found it.
