### ISSUE TITLE
When marking a comment as spam, the interface shows them as deleted

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#4230]
I think this is a bit confusing, they maybe deleted also, but I think for the user it should show *mark as spam*
![ios simulator screen shot 1 sep 2015 11 46 51](https://cloud.githubusercontent.com/assets/651601/9602297/2a14cec6-509f-11e5-90b0-6d1ba74c2063.png)

**Comment by rachelmcr** [comment]
I came across this while testing today and was also confused by it — I actually selected Undo and then tried spamming it again because I thought I might have tapped on Trash by mistake.

Seen in WPiOS 6.3.0.20160603.1
