### ISSUE TITLE
Cannot clear parent category when adding a new category

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#4237]
As reported by a user:

> When you add a new category and select a parent category, there’s no way to de-select the parent category. You can choose a different parent category, but you can’t remove the parent category selection altogether. (You have to cancel out of the “Add New Category” screen completely and start over to make your new category a top-level category.)
>
> I found this while testing the Default Category setting in the new Blog Settings feature, but it also applies when adding a new category in the post editor.

**To Repro:**
1) Create a new category (in either the blog settings of new post screens)
2) Input the new category’s name and choose a parent category (Uncategorized in this case):

![2015-08-26-10-14-28](https://cloud.githubusercontent.com/assets/154014/9633535/0d9f734a-5153-11e5-8aef-0a01312c9807.png)

3) Tap on Parent Category again and you see the list of possible parent categories. “Uncategorized” doesn’t show that it’s selected:

![2015-08-26-10-14-24](https://cloud.githubusercontent.com/assets/154014/9633540/152f6c64-5153-11e5-9ce1-5b15ff968e1a.png)

4) Tapping on “< Add a Category" in the upper left cancels the action (the current parent category stays selected). Tapping on the current parent category reselects it. If there are multiple categories in the list you can switch which category is the parent by tapping on a different one, but there's no way to remove the parent category completely to make your new category a top-level category.

The only way to clear the parent category is to cancel out of the entire add category workflow.

**Comment by rachelmcr** [comment]
I tested again and confirmed this is still an issue in beta v. 5.9.0.20151216.

**Comment by itsaboutcode** [comment]
This issue still exist in 5.9.1 but seems to have been fixed by ticket #4844 with commit 5d656f7e13475e191618d0b0e0623af194b0f3ea. So it's time to close this ticket :)

**Comment by bummytime** [comment]
@itsaboutcode thanks for pointing this out! Closing this issue.
