### ISSUE TITLE
iOS 5.5 release missing logout for 

### ISSUE THREAD

**Issue by JasonSnow-Mad** [wordpress-mobile/WordPress-iOS#4239]
A user reported, and I was able to confirm, that there doesn't appear to be a way to remove self-hosted sites in the most recent 5.5 release for iOS. 

Did this feature get moved someone else, or did it accidentally get left out?

![img_0322](https://cloud.githubusercontent.com/assets/8810295/9651788/ec84ac3a-51c9-11e5-8697-f820d2e274ef.PNG)

**Comment by ashthemighty** [comment]
Confirmed that after extensive searching I have been unable to find any way to log out of my own WordPress.org sites.

**Comment by aerych** [comment]
@JasonSnow-Mad @ashthemighty  You should be able to log out of a self-hosted site via My Sites > `the blog name` > Settings > Remove Site.  However, if the self-hosted site is connected to Jetpack, and the wpcom account that is currently signed in, there will not be a remove site button. In this case you can hide the blog like a wpcom site.
