### ISSUE TITLE
Notifications Control Center: Stream Details Subtitle

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#4240]
The Stream Details view should have a subtitle, indicating what's the blog title.

Thanks @drw158 for the mockup!

![screen-shot-2015-09-02-at-11-48-59-am](https://cloud.githubusercontent.com/assets/1195260/9660426/f1cbee8a-522b-11e5-8a66-f344539228b2.png)

**Comment by drw158** [comment]
Do we have a subtitle anywhere else in the app? I thought we did, but I don’t see any.

-- 
Dave Whitley / Designer at Automattic

On September 3, 2015 at 9:08:08 AM, Jorge Leandro Perez (notifications@github.com) wrote:

The Stream Details view should have a subtitle, indicating what's the blog title.

Thanks @drw158 for the mockup!

**Comment by jleandroperez** [comment]
@drw158 yes sir! we added that for the new WebView (Site Title + Site URL)

**Comment by drw158** [comment]
Oh yea! That will be a good starting point. Looking at it now, the subtitle might be a tad too small.
