### ISSUE TITLE
Notifications Control Center: Stream Icons

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#4241]
Let's add a left icon to each one of the available streams, as follows:

Thanks @drw158 !

![screen shot 2015-08-17 at 11 58 28 am](https://cloud.githubusercontent.com/assets/1195260/9660474/2df1e824-522c-11e5-82ea-fc11821e49b7.png)

**Comment by drw158** [comment]
Perfect, I think this well be much clearer.

-- 
Dave Whitley / Designer at Automattic

On September 3, 2015 at 9:09:30 AM, Jorge Leandro Perez (notifications@github.com) wrote:

Let's add a left icon to each one of the available streams, as follows:

Thanks @drw158 !

**Comment by jleandroperez** [comment]
I'll proooooobably need to bother you with the icons Dave!

**Comment by drw158** [comment]
Can we do the pdf trick? Here are the icons @1x in pdf format:

https://cloudup.com/cv6DzHxvR5w

**Comment by jleandroperez** [comment]
Thank you Dave! will look into this for the next release, much appreciated!
