### ISSUE TITLE
deleteBackward ?

### ISSUE THREAD

**Issue by tinhbka** [wordpress-mobile/WordPress-iOS#4248]
Can us create delete funtion like deleteBackward of uitextview ? Please suggest me some solution!

**Comment by jleandroperez** [comment]
Hello there @tinhbka,

The main purpose of this repository is to track WordPress iOS's issues. Perhaps [stackoverflow.com](http://stackoverflow.com) would be a more appropriate spot to post iOS development questions.

Off the top of my head, perhaps this snippet would serve the `deleteBackward` mechanism you're after (assuming that you'd just like to delete the last inserted character):

```
UITextView *textView = ...;    // (dummy / sample code!)
NSString *currentText = textView.text;
if (currentText.length > 0) {
   textView.text = [currentText substringToIndex:(currentText.length - 1)];
}
```

Good luck there!
