### ISSUE TITLE
Asset request for themes

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#4255]
As part of the assets for the themes feature I'd need:

- The icon used [here](https://github.com/Automattic/calypso-pre-oss/issues/8682) in .png format (sizes 24px, 48px and 72px).  Also make sure the .pngs have the right icon color, to avoid runtime color conversions in code.  The background should be transparent.
- The background color name/code/hex used in the issue mentioned above, to replicate it under iOS.

That's it for now.  Thanks!

**Comment by folletto** [comment]
Heya! :)

I put all the assets in [this dropbox folder](https://www.dropbox.com/sh/edo1jx22fvnnw60/AADsSuVG7qiGVpwO2Ei8NW6Va?dl=0).

The background color is our _Gray Lighten 20_: `#c8d7e1`.

Preview:

![gridicons-themes-72-graylighten30](https://cloud.githubusercontent.com/assets/4389/9790930/9a460a38-57d0-11e5-9a21-8b655ca55a52.png)

**Comment by alexcurylo** [comment]
Closed by PR #4531.
