### ISSUE TITLE
Publishing: Review draft post saving logic. Ensure it is not deleted when publishing.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4262]
We have a [report in the forums](https://ios.forums.wordpress.org/topic/deletes-posts-error-occurred-during-publishing) where a draft post was published then failed to show up in the app.  The log shows a number of time out errors which are worth exploring.
Let's try to confirm the bug and fix.

**Comment by rachelmcr** [comment]
I reproduced this bug with the following steps:
1. In Settings > Developer > Network Link Conditioner on the device, enable the network link conditioner with a 100% Loss profile
2. Go to Blog Posts > Drafts and open a saved draft in the app
3. Edit the blog post
4. Go to the post settings and change the Status from Draft to Published
5. Go back to the editor, select Post, and wait for it to finish trying to publish the post

Result: I saw the "Error occurred during publishing" error (and I see timeout error in my logs). Although I could see my recent edits in the post preview in the Blog Posts list (still as a draft post), when I opened the editor my edits were gone. I also checked post revisions in WP Admin and my edits were not saved there, either.

Device: iPhone 6, iOS 9.2
App: beta 5.9.0.20151216

**Comment by diegoreymendez** [comment]
@rachelmcr - Can you re-test this with the latest in `release/6.0`?  I believe the edits being lost may have been fixed with [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/5009).

Of course if the connection is failing, the changes will only be stored locally, but at least they won't be lost unless discarded on purpose.

**Comment by rachelmcr** [comment]
The re-test should be with the latest in `release/6.1`, right? I re-tested with the latest from that branch and am still having trouble with this issue.

As long as I am on a bad connection (i.e. using a 100% Loss profile) I can open the post in the editor and see my local changes. However, there is no `local` flag on the post, and when I reconnect to the internet and refresh the post list, my changes are lost (overwritten with the version of the draft on the server).

**Comment by diegoreymendez** [comment]
> The re-test should be with the latest in release/6.1, right?

Nopes - I don't think this has been merged into 6.1 yet.  It's available in the latest `release/6.0` though.

**Comment by rachelmcr** [comment]
Hm, I had the same problem when I tried the steps in `release/6.0` at first, but I will test one more time to be sure.

**Comment by diegoreymendez** [comment]
Sorry @rachelmcr you're right.  It's 6.1 and I'm sleepy - I'll follow up.  Thanks!

**Comment by rachelmcr** [comment]
Sorry, I was mistaken! My `release/6.1` branch wasn't fully up to date. I just re-tested with the latest and the local changes are saved. My notes:

- After taking the steps above, the post appears in the Published filter in the app with a `local` flag.
- After reconnecting to the internet and refreshing the post list, the local changes remain in the app.
- Opening the editor in the app shows the local draft and prompts you to save or discard the local changes.

Given that, I think we can close this issue as resolved by the changes in that PR. Thanks!
