### ISSUE TITLE
Custom Publicize message is stripped on Publish

### ISSUE THREAD

**Issue by richardmtl** [wordpress-mobile/WordPress-iOS#4266]
Steps to reproduce:

1) On a Jetpack-powered site with Publicize active, write a post
2) Create a custom Publicize message
3) Save a draft
4) Edit the draft on the iOS app
5) Publish the post from the iOS app

Expected result: The Post will be Publicized to Facebook with the custom Publicize message.

Actual result: The Post is Publicized to Facebook with the full text of the Post (the custom message is not used).

This came up in 2333856-t

Tangentially-related to #2698

**Comment by rachelmcr** [comment]
I just tested this using a Jetpack-powered site and the steps above, and in the latest WordPress iOS beta I could not reproduce the issue. Each time I published a post, the post was publicized to Facebook with the custom publicize message as expected.

@richardmtl can you still reproduce this issue?

**Comment by richardmtl** [comment]
I can't reproduce this anymore; thanks for the nudge, @rachelmcr !
