### ISSUE TITLE
Confusing message when adding Jetpack blog connected to a different .com account

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#427]
Reported by @aerych 

Log in to the app with a .com account. 
Add a self-hosted blog with Jetpack installed and connected to a different .com account. 
When the blog is added, Jetpack is detected and the app tries to authenticate but the credentials are wrong and an error message is shown:
"This blog is not connected to that WordPress.com username."

As a new user, at this point I have no idea what has just happened. What is Jetpack (I might have forgotten I installed it), what WordPress.com user name is it talking about (I might not remember I have one). The Jetpack screen in the background will give some context but the error message is obscuring the helpful text when it appears. We could improve this message a bit. 

Tapping "Need Help?" on the alert just dismisses the alert, same as tapping "OK". Do we need to show a webview with an FAQ or could we just show a single "OK" button?

**Comment by koke** [comment]
#3507 made this better, and #3628 will kill that screen
