### ISSUE TITLE
Swift Compiler Error !

### ISSUE THREAD

**Issue by Eliothu** [wordpress-mobile/WordPress-iOS#4281]
When I Clone The develop branch in local, and pod install it. Then I  open 'WordPress.xcworkspace'  and run the project. Some issues appeared。

<img width="705" alt="error" src="https://cloud.githubusercontent.com/assets/12962550/9895057/96c0103e-5c5d-11e5-98e3-3c9c2c52c88c.png">
<img width="774" alt="2015-09-16 10 21 10" src="https://cloud.githubusercontent.com/assets/12962550/9895059/a76ffdd6-5c5d-11e5-8a7e-d7f5b648ba86.png">

I don't delete any file and can't find "WordPress-Swift.h" in the project.
Thanks a lot!

**Comment by aerych** [comment]
@Eliothu Are you still seeing compiler errors? If so please make sure you're running the latest version of Xcode.

**Comment by Eliothu** [comment]
thanks， run on the Xcode 7.0 is ok.
