### ISSUE TITLE
Update PostServiceRemoteXMLRPC to use wp calls instead of metaWebBlog

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#4284]
On PostServiceRemoteXMLRPC we have two methods: createPost and updatePost that are still using metaWebBlog. calls instead of the wp. calls.

**Comment by nheagy** [comment]
Looks related to #1385

**Comment by yaelirub** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/1385
All metaWebBlog methods should be removed
