### ISSUE TITLE
Today Widget is unstable in iOS 9

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4287]
The today widget isn't always displaying in iOS 9 - sometimes just the system-provided title bar, sometimes it disappears. It seems to work fine in iOS 8.

Also the text is still not fully tapable to launch into the app.

**Comment by astralbodies** [comment]
Turns out what is happening is a race condition. With the recent changes made to AccountService and BlogService the mergeBlogs code is being run in BlogService after (or in another thread) as AccountService's updateAccount. When a user first signs in the defaultBlog is being set in the AccountService (or in the create account view controller :cry:) but the sync blogs is happening at the same time. Default blog doesn't exist in mergeBlogs and the Today Widget is NEVER configured.

We need to shore up how we're syncing this data. I can't move the widget config logic to AccountService because the blog hasn't been synced yet and I need the blog's timezone. I can't keep it in BlogService because there isn't a guarantee that defaultBlog is set yet by AccountService. We should really update the facade used for login, account creation, blog/site creation to make sure they're called in order and not at the same time.

@sendhil I'm going to need your help with this one as I don't fully understand the facades we're using. I also think we need to heavily refactor the view controllers for the NUX and put ALL of that business logic into the account service or blog service. We're definitely duplicating logic there.

**Comment by sendhil** [comment]
@astralbodies didn't want this one to drop by the way side. We can always do a pair programming session at some point to try and wrangle this out.

**Comment by astralbodies** [comment]
@koke Do you have any thoughts on this with your recent AccountService work?

**Comment by koke** [comment]
My recent work was in AccountSettingsService, I don't have any particular insights on this issue
