### ISSUE TITLE
Reader: Add image preloading to the new list

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4288]
Title has it.  
Cells are handling image loading via an AFNetworking category on UIImageView.  We can probably leverage AFNetworking's cache and loading logic that the list can take advantage of by looking a head (and behind!) a few cells from the current offset.

**Comment by kean** [comment]
Implemented in https://github.com/wordpress-mobile/WordPress-iOS/pull/21470; targeting 23.7.

**Comment by aerych** [comment]
From 2015!   You're a hero @kean!

**Comment by kean** [comment]
Yes, but I closed the wrong ticket 😬 
I added prefetching to Site Media. Reader is coming next.
