### ISSUE TITLE
Reader: Updates to menu

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4289]
Update the menu's icon.  Maybe use a gear icon or a text label of some kind.
Change the tag icon in the menu's search bar to the outlined plus used for following.
Update the placeholder text in the menu's search bar to "Enter a URL or tag to follow"
Update the title in the menu navbar to not be specific to tags. Maybe say "topics" instead.

**Comment by aerych** [comment]
@shaunandrews, I'd prefer an icon of some kind for the menu vs text, but just "Menu" wouldn't be horrible. Any strong feelings either way?

Could you whip up 1x, 2x, and 3x versions of a plus-outline search bar icon?  For reference, here's the [current tag icon](https://github.com/wordpress-mobile/WordPress-iOS/tree/develop/WordPress/Resources/AppImages.xcassets/icon-reader-tag.imageset)

**Comment by shaunandrews** [comment]
Here's the plus-outline icon: https://cloudup.com/cIPG-1r9zHr

**Comment by aerych** [comment]
Thanks @shaunandrews.  I should have been more specific about the sizes.  They need to be 20px for the 1x image, 40px for the 2x image, and 60px for the 3x image. Sorry for the fuss.

**Comment by shaunandrews** [comment]
Here's the plus-outline icon at the sizes you mentioned: https://cloudup.com/c5tHg2bD2Xf

> Any strong feelings either way?

We're actually going to be dropping the gear icon on web soon, but it'll still be in use in the Android app. For now, I don't have a strong opinion. Eventually, I'd like to be able to lose that icon all together.
