### ISSUE TITLE
Determine if we're calling refreshMetadata too much, wrong places

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4291]
Dig through where we're calling `[WPAnalytics refreshMetadata]` to make sure we're not calling it too often or in the wrong places. We're noticing that some events like creating a WordPress.com account are coming through marked as anonymous when they should have a username by that time.

cc: @coreh

**Comment by rachelmcr** [comment]
Where we're calling `[WPAnalytics refreshMetadata]` currently:

1. BlogSyncFacade.m
https://github.com/wordpress-mobile/WordPress-iOS/blob/d29f4a01ee9e17f66f5eac8536e3c46cf640cb9d/WordPress/Classes/Services/BlogSyncFacade.m#L87

2. AccountService.m 
https://github.com/wordpress-mobile/WordPress-iOS/blob/4cb8d4d7ab580fcc4f2a87fa193b963590c0e7d5/WordPress/Classes/Services/AccountService.m#L117
and
https://github.com/wordpress-mobile/WordPress-iOS/blob/4cb8d4d7ab580fcc4f2a87fa193b963590c0e7d5/WordPress/Classes/Services/AccountService.m#L204

3. LoginViewModel.m 
https://github.com/wordpress-mobile/WordPress-iOS/blob/8f231977c4ebb0337ede7657a38bd64b90f0a288/WordPress/Classes/ViewRelated/NUX/LoginViewModel.m#L518

4. CreateNewBlogViewController.m 
https://github.com/wordpress-mobile/WordPress-iOS/blob/f7dc953e1f664973cfb8df4bedb060f7d05ee8c3/WordPress/Classes/ViewRelated/Blog/CreateNewBlog/CreateNewBlogViewController.m#L519

5. BlogService.m 
https://github.com/wordpress-mobile/WordPress-iOS/blob/d925cc31a27556267d73fc1a921e45787021eed5/WordPress/Classes/Services/BlogService.m#L499

6. CreateAccountAndBlogViewController.m 
https://github.com/wordpress-mobile/WordPress-iOS/blob/f7dc953e1f664973cfb8df4bedb060f7d05ee8c3/WordPress/Classes/ViewRelated/NUX/CreateAccountAndBlogViewController.m#L880

**Comment by astralbodies** [comment]
I'm closing this for now as it's less of an issue with Mixpanel removed. I want to revamp our analytics tracking anyway.
