### ISSUE TITLE
Core emojis displayed too large

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#4298]
Related to #4296 , when I visit the post from my _following_ list the emoji appears as an image (block element, much taller than line height).

If I go to the site feed and tap on the same post, it uses the system emoji, and it doesn't show up as a featured image.

![emoji-variants](https://cloud.githubusercontent.com/assets/8739/10039130/3e8b9876-61cf-11e5-979d-97ef414dbdfc.png)

Screens are from the branch at #4280

/cc @aerych

**Comment by aerych** [comment]
Very interesting.  First guess this is due to inconsistency between the content returned from the two endpoints.  Nice catch :)
