### ISSUE TITLE
Notifications Control Center: Implement Blog Search

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#4300]
Let's implement Blog Search, within the Notifications Control Center view. 
- Display a search bar (within the navigation bar)
- Remove the tableView grouping, when in search mode. 

Note: The placeholder should read _Search Sites_.

/cc @drw158

**Comment by designsimply** [comment]
Still a valid request. 

Here is a screenshot showing the current Notifications screen for reference:

<img src="https://user-images.githubusercontent.com/1119271/63216217-683c2680-c0ef-11e9-8080-9b578c5c6e17.PNG" width="270" alt="IMG_2945">
<sup>Tested with WP Internal 13.1.0.20190814 on iPhone 6S iOS 12.4.</sup>
