### ISSUE TITLE
Notifications: Native Stats not being opened

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#4313]
We've received a report indicating that the `Spike in Your Stats`'s `Your Stats` link is triggering a WebView.

Instead, we should be (already) opening the Native Stats. Let's further investigate what might be going on!

**Comment by koke** [comment]
This just happened to me. If it helps, it's a Jetpack site. I have another spike notification for a wp.com site that opens the native view.

**Comment by koke** [comment]
This seems to work for me, but I haven't considered all the edge cases

https://gist.github.com/koke/be449a0c94699c22dcd8

**Comment by jleandroperez** [comment]
@koke Stats (should) only work with WordPress.com blogs, as far as i know (cc'ing @astralbodies just in case).

Did you actually get a notification for a Self Hosted blog connected via Jetpack?

Thanks!

**Comment by koke** [comment]
Stats work perfectly on Jetpack sites as well :)
