### ISSUE TITLE
Notifications: Empty State

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#4322]
Whenever the user has no notifications, let's implement an "Empty State" mode.

Mockups below!

![empty-unread](https://cloud.githubusercontent.com/assets/1195260/10198150/2b687884-6771-11e5-85dc-cbd974051c26.png)
![no-blogs](https://cloud.githubusercontent.com/assets/1195260/10198149/2b67d406-6771-11e5-8f63-e8efa9ff7da3.png)

**Comment by elibud** [comment]
PR to follow once 
https://github.com/wordpress-mobile/WordPressCom-Analytics-iOS/pull/87
https://github.com/wordpress-mobile/WordPress-Shared-iOS/pull/118
are approved.
