### ISSUE TITLE
Reader: Crash previewing tags or sites after viewing post detail from post notification.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4324]
There is a situation where the reader can crash trying to preview a site or tag if a post detail has been viewed via a notification. 

To trigger the crash: 
- Go to Notifications and view the post detail for a notification. 
- Go to the reader and tap a site name or a tag to preview content. 

Boom.

**Comment by jleandroperez** [comment]
Looks good @aerych!

:shipit:
