### ISSUE TITLE
Blog List: Things are confusing when all blogs are hidden.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4328]
If a user hides all their wpcom blogs, and has no self-hosted blogs, the My Sites blog list can be a bit confusing with nothing to look at and a live edit button. This particular situation is a bit of an edge case but it might be nice to show a label specifying the number of hidden sites. 
![simulator screen shot oct 1 2015 10 00 14 am](https://cloud.githubusercontent.com/assets/1435271/10224675/b8262632-6824-11e5-9ea5-c707023d01fe.png)

**Comment by kwonye** [comment]
I agree. What do you think about not letting them hide the last-remaining blog?

**Comment by aerych** [comment]
I think if we allow hiding we should allow hiding them all. I think if we allow all but one its an opportunity to frustrate users.

Suppose someone tries hiding all of their blogs they get to the last one in the list and find that they can't. Maybe that's one they *really* want to hide. We've caused friction cos they can't immediately do what they are attempting, and now they have to choose a different one in the list to keep. Maybe there are no pleasing choices. 

Suppose we let a user hide all but the primary blog.  What if this is a user who created an account via the app and they just entered in something thoughtless for their blog (hey they just want the reader, right.. right... Buler?)  Maybe it turns out they actually want to blog and end up with several, except that first nonsense blog annoys them and they want to hide it but they can't.  (Granted this is a bit of a stretch and they could always rename or modify it in other ways to better suite them but maybe that's not clear to them either.)

Anyway that is more or less the concern I'd have hiding all but one blog.  Maybe we could tap @mnt or @drw158 for some UX consideration?

**Comment by drw158** [comment]
We should at least have a message here, maybe in the form of a table row + footer text. Something like "All of your sites are hidden. Tap Edit to unhide." The table row could have the number of sites hidden, like "21 hidden sites"
