### ISSUE TITLE
Smarter video upload quality

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#433]
Reported by @koke 

The app should make the user more aware if it's going to upload a really big file, and offer a smaller low quality version.

One posible way to do this:

If user is trying to upload a video over 3G and it's more than 20 MB, we ask:
>
The video you are trying to upload is probably going to take a long time to upload. Do you want to upload a lower quality version instead?

>Always / Only this time / No, thanks

Details to be discussed:
- Only 3g or always ask?
- Size limit should be similar to the app store download limit over 3G
- "Optimized" quality could be 720p or 480p

**Comment by SergioEstevao** [comment]
@kurzee any special reason to close this? I think it's still a valid thing to do :).

**Comment by kurzee** [comment]
@SergioEstevao still valid, we can reopen if you'd like. Just closing and cleaning up issues that haven't gone anywhere in years and labelling them with "Graveyard".
