### ISSUE TITLE
Issues with RTL languages iOS 9

### ISSUE THREAD

**Issue by rachelsquirrel** [wordpress-mobile/WordPress-iOS#4346]
A user has sent in some screenshots of the app in Hebrew. Some of the text is cut-off on the left side of the screen:

![cb11abb321ff5f25ef2009ab72351405a65edab2](https://cloud.githubusercontent.com/assets/7946521/10305677/89c14940-6c19-11e5-980a-2e0b6a0ca3d0.jpeg)

![146be7e2b67b756244bd1ab4686ac95ab79fc30b](https://cloud.githubusercontent.com/assets/7946521/10305680/8bd7817c-6c19-11e5-8755-7a0c2d146aeb.jpeg)

See helpshift issue 58745

**Comment by aerych** [comment]
cc @astralbodies

**Comment by rachelmcr** [comment]
I checked the stats in Hebrew in the latest 5.8 beta (iPhone 6, iOS 9.1) and the alignment is fixed there. Closing this issue as resolved.
