### ISSUE TITLE
Add split-screen multitasking support

### ISSUE THREAD

**Issue by rachelsquirrel** [wordpress-mobile/WordPress-iOS#4347]
A user would like the app to support iOS 9.0 multitasking support:
https://twitter.com/AfterPad/status/651190604085391360

**Comment by aerych** [comment]
Our current plan is to enable this for version 5.7 :)

**Comment by aerych** [comment]
Following up. It took a wee bit longer to get all the pieces in place so the new plan is to ship in 5.8.

**Comment by sendhil** [comment]
Closing this issue as it'll ship with 5.8.
