### ISSUE TITLE
Accessibility: Post Media Picker and VoiceOver

### ISSUE THREAD

**Issue by sandymcfadden** [wordpress-mobile/WordPress-iOS#4352]
When VoiceOver is enabled in iOS it makes it impossible to access any of the images in the media picker window. 
You can get to the list of images but as you scroll through it will only allow you to go to any videos which are present, and that is to land on the video length element and speaks how long it is. It's as though it can't see each image element.

**Comment by diegoreymendez** [comment]
@SergioEstevao - Was this issue fixed by the PR mentioned above?

**Comment by SergioEstevao** [comment]
Yes it was, I'm closing it.
