### ISSUE TITLE
writing settings require admin role

### ISSUE THREAD

**Issue by lcenvs** [wordpress-mobile/WordPress-iOS#4355]
I don't recall this in previous versions, but WP iOS v5.6.1 apparently requires admin role (vs. e.g. author role) for a given site's Configuration > Settings to include Writing (most significantly, Geotagging), and not just General. Rationale/solution?

**Comment by aerych** [comment]
Hi @lcenvs 
Only showing the Writing options to users with an Administrator user role matches the behavior in wp-admin.  However, the geolocation toggle isn't a site setting, but an app setting and should probably remain present.   Thanks for bringing it to our attention.

**Comment by aerych** [comment]
cc @bummytime & @diegoreymendez as this affects the publishing flow

**Comment by lcenvs** [comment]
Sure appreciate...geolocation is one of the most powerful features our students utilize in the mobile app, and restoring it to an app setting will allow them to set it once and use it successfully across their sites. (And yes, since we use a number of group sites students are often in author role, though they'd be admin role on their own sites.)

**Comment by aerych** [comment]
Self-assigning as a reminder to check up on this. Looks like @bagia might have a PR soon.

**Comment by aerych** [comment]
Closed in #4426, props @bagia
