### ISSUE TITLE
Error The required "client_id" parameter is missing.[invalid_client]

### ISSUE THREAD

**Issue by pengting** [wordpress-mobile/WordPress-iOS#4363]
run xcode

create account , show message 

Error The required "client_id" parameter is missing.[invalid_client]

**Comment by aerych** [comment]
Hi Patrick. 
Did you create your own app ID and secret and add them to `.wpcom_app_credentials`?

**Comment by pengting** [comment]
How to create ?  

https://developer.wordpress.com/apps/new/ ?

but ,i don't know Redirect URL and Javascript Origins ?

**Comment by aerych** [comment]
> but ,i don't know Redirect URL and Javascript Origins ?

It should be fine to enter the URL to your blog for the `Redirect URL` and `Javascript Origin`, tho I think `Javascript Origin` might be optional.

Just be sure when selecting the `Type` to choose `Native` not `Web`.

**Comment by pengting** [comment]
hi @aerych  ,

I create an app,modify file of WordPressComApiCredentials.m .

------------------------------------------------------------------------------------------------
import "WordPressComApiCredentials.h"

define WPCOM_API_CLIENT_ID @"42969"
define WPCOM_API_CLIENT_SECRET @"Vsm6U5uU0KZLjHW1pBczxMrdG9kdZF7MxAJk3mesvNh3W9owyIgyzuf0jK4NYwly"
----------------------------------------------------------------------------------------------------------------------------
After running or display an error message，


 Edit New issue
Error The required "client_id" parameter is missing.[invalid_client]

**Comment by aerych** [comment]
@pengting there shouldn't be a need to modify `WordPressComApiCredentials`. 
Have a look at the `Logging In` section of our [README.md](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/README.md) and make sure you've properly configured a `~/.wpcom_app_credentials` file.  You can find more info in the [handbook](https://make.wordpress.org/mobile/handbook/pathways/ios/tutorials-guides/#3-%C2%A0setup-wpcom_app_credentials).

**Comment by pengting** [comment]
Thank you  @aerych 
Run successful。

I have a question，I want to know how to display blog posts directly instead of first login.

**Comment by aerych** [comment]
> I have a question，I want to know how to display blog posts directly instead of first login

That depends on what you mean. Are you trying to have access to the posts in the Reader before signing in or are you trying to do something different.   In either case its going to require some customization

**Comment by aerych** [comment]
Closing this one. 
@pengting feel free to contact us in the #mobile WordPress.org slack channel. See http://chat.wordpress.org for more info.
