### ISSUE TITLE
Update to CocoaLumberjack 2.2.0

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4371]
We are getting podspec lint errors because of the issues with CocoaLumberjack 2.0.0. If we can't replace the logging stack with #3952 in short order, lets update to the latest CocoaLumberjack. This means going back on some of the changes to include ddLogLevel in the PCH file. This also means updating every. single. project. in the WPiOS ecosystem that we use in WPiOS. 

Stabby.

**Comment by koke** [comment]
It's happening, PRs coming

**Comment by astralbodies** [comment]
Awesome job, @koke!
