### ISSUE TITLE
Simplify removing a self-hosted site from the app

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4379]
Removing a self-hosted site currently requires a series of taps:
1. Go to the My Sites tab
2. Find the site and tap on it
3. Tap on the Settings
4. Scroll to the bottom of the settings and tap "Remove Site"

This is pretty hidden and, for me at least, fairly unintuitive. It would be great to improve/simplify this action. For example, my first inclination was to swipe on the site from the My Sites tab, or to tap on "Edit" in the top left there to remove it.

**Comment by hoverduck** [comment]
Same issue on Android - https://github.com/wordpress-mobile/WordPress-Android/issues/3313

**Comment by koke** [comment]
I think we used to have that behavior, but it was also confusing when there was a mix of wp.com sites (which you can't remove) and self hosted.

**Comment by rachelmcr** [comment]
Android is simplifying it with a sign out option that removes all sites (WordPress.com and self-hosted) at once:

> Now there is always a 'Disconnect/Sign Out/Logout' row that removes all sites. If the user is connected to a self-hosted site there will also be an option to 'Connect to WordPress.com' as there was before.

From https://github.com/wordpress-mobile/WordPress-Android/issues/3313#issuecomment-259858117
