### ISSUE TITLE
View Site not displaying website in logged-in state

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4381]
View Site should display all websites in a logged-in state. However, it is currently only displaying sites with a *.wordpress.com subdomain in a logged-in state. WordPress.com sites with a custom domain name and self-hosted sites display a logged out view.

Steps:
1. Launch WPiOS
2. Go to My Sites tab
3. Select any self-hosted site or WordPress.com site with a custom domain name
4. Tap on View Site

Result: The site is displayed with a logged-out view. See a similar past issue: #3461 

Tested on iPhone 6 running iOS 9.0.2 in WPiOS beta version 5.7.0.20151026.

Screenshot of my self-hosted (Jetpack) site after tapping View Site:

![2015-10-28 13 57 57](https://cloud.githubusercontent.com/assets/8658164/10790590/0f2e9574-7d7c-11e5-8b62-39fcc7ede7fb.png)

Screenshot of my WordPress.com site with a custom domain name:

![2015-10-27 21 18 26](https://cloud.githubusercontent.com/assets/8658164/10790604/1f3bf290-7d7c-11e5-8a5b-b98c34e3cb65.png)

**Comment by aerych** [comment]
The app does not store passwords for WPcom sites, or Jetpack connected sites. Instead it relies on the WPcom's REST API bearer token for authentication. This really limits available options to authenticate to sites with custom domains or Jetpack connected sites. There might be options for Jetpack sites using Single Sign On that we can explore but that's no help for the rest.  In any event it would probably be a step backward to store passwords just for the View Site feature.

@koke, you've spent a good deal of time dealing with Jetpack and authentication concerns. Any thoughts on this one?

**Comment by koke** [comment]
Custom domains should be working, at least mine is

![simulator screen shot 05 nov 2015 08 22 45](https://cloud.githubusercontent.com/assets/8739/10962207/ac71491a-8396-11e5-9d8c-9dac685cc24b.png)

As for Jetpack sites, there was a thread somewhere considering different options, but I think only for previews. 

I'm wondering if using the new Safari controller would help. Or since iOS9 has the handy "back button for apps", regular Safari. I wouldn't mind reducing the number of web views in the app and stop dealing with all these authentication quirks. 

Also, maybe logged out view site isn't such a bad idea, since the you can't tap on things that take you to the dashboard :wink: 

![screen shot 2015-11-05 at 08 34 51](https://cloud.githubusercontent.com/assets/8739/10962409/3f2a0390-8398-11e5-9436-8486fc6cb8d4.png)

**Comment by rachelmcr** [comment]
Hm, I'm not sure why my custom domains aren't working. I checked three different sites (two different domains and one subdomain) and they're all a logged-out view.

>Also, maybe logged out view site isn't such a bad idea, since the you can't tap on things that take you to the dashboard :wink:

Heh, I do agree it would cut down on confusion, but WordPress.com/Jetpack counts those logged-out views in the stats, which is annoying. (Also, since it's happening to me on WordPress.com sites, it prevents me from viewing private sites with custom domains unless I log in again there.)

**Comment by aerych** [comment]
> Custom domains should be working, at least mine is

@koke, I forget if UIWebView is sandboxed away from Safari or if they share cookies.  Could you have already been logged in via Safari?

**Comment by koke** [comment]
UIWebView is sandboxed, although something else in the app might have authenticated me. For instance, if I "View site" on a non-mapped domain it will authenticate me. Then if I "View Site" on a mapped domain, it won't, but the web view already has the cookies from the previous load

**Comment by rachelmcr** [comment]
I tested a site with a custom, mapped domain again in beta 5.8.0.20151124 and I get a logged-in view, so that's resolved for me now. The only remaining issue is for self-hosted sites (with and without Jetpack) getting a logged-out view.

This also came up in #2098 because you can't view the site and post comments without logging in again there.

**Comment by sendhil** [comment]
I wonder if we should just throw users to Safari for View Site as @koke suggested earlier and avoid some of these authentication issues since it's likely the user is logged into their site in Safari.

**Comment by aerych** [comment]
> it's likely the user is logged into their site in Safari

Is it really likely?  I'm never logged into wp on my phone...

**Comment by rachelmcr** [comment]
I'm pretty much never logged in to my self-hosted site on my phone, either. That said, if I knew the app opened my browser (instead of using an in-app browser) I'd probably choose to stay logged in there. (At least that way I'd be able to control the logged in/out state.)

**Comment by koke** [comment]
A couple thoughts:

- We can use the new Safari View Controller so we stay in the app but shares cookies with Safari
- I believe since iOS9 the app can share credentials with Safari, so we could pre-login the user

**Comment by koke** [comment]
> we could pre-login the user

To clarify, we don't store passwords for wp.com and Jetpack sites, so this could happen only on when they Login in the app, and the cookie would eventually expire if they don't use the site often in Safari

**Comment by jeremeylduvall** [comment]
@koke I'm currently experiencing a similar issue for both Jetpack sites and WP.com sites both with a custom domain and not. I'm logged into WordPress.com via both Safari and Chrome on my iPhone 6. However, in 6.1, if I navigate to (Site) -> Blog Posts -> View, it opens in a logged out view and counts towards my stats. 

> the cookie would eventually expire if they don't use the site often in Safari

I thought I understood this to mean logging out/in in Safari would fix the issue and reset the cookie, but that doesn't appear to work. Did I misinterpret that?

Raised in 100927-h for future reference.

**Comment by koke** [comment]
I think I was misunderstanding the feature when I wrote that. I think what we can do is add the username/password to Safari's AutoFill feature, but I don't think the app and Safari can share cookies.

**Comment by carinapilar** [comment]
I had an user with this problem and while testing I found that when you open the app and first open a site with custom domain, the bar doesn't show. But if you open a site with the free WordPress.com domain, which shows the bar, then the site with the custom domain again, it will show the bar in both of them. Ticket 2772112.

**Comment by starxedsteph** [comment]
I had a user report this issue in #2925630-t and is concerned that this has inflated her stats. The user site has a custom domain.

I tested with a site on my own account using a custom domain. I did not see the admin bar and saw views added to my sites as a logged out user.
After reading @carinapilar 's comment above, I tested viewing a site without a custom domain first which did allow me to subsequently preview my custom domain site with the admin bar as a logged in user.

**Comment by rachelmcr** [comment]
We have another report of this happening to a user in 166725-h. The user has a WordPress.com site with a custom domain name.

**Comment by druesome** [comment]
Another report from a biz 1:1 user: https://woothemes.zendesk.com/agent/tickets/657563

**Comment by elibud** [comment]
Assigning to @koke since it's fixed on his PR https://github.com/wordpress-mobile/WordPress-iOS/pull/7921
