### ISSUE TITLE
Where should "See all of your likers" lead?

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4383]
When I tap on "See all of your likers" notification I end up on a full-post view, with no full list of the likers. Where is that supposed to lead?

On the full post view, I ended up tapping on the star in hopes that my likers would appear. Instead, of course, I liked my own post and felt a bit foolish about that.

Notification:

![2015-10-27 20 40 39](https://cloud.githubusercontent.com/assets/8658164/10793823/70de71b4-7d8a-11e5-8925-8c2e357f51c2.png)

After tapping on "See all of your likers" (post content redacted):

![2015-10-27 20 40 42](https://cloud.githubusercontent.com/assets/8658164/10793912/c3339fca-7d8a-11e5-9efa-1a9ce4ddd1f3.png)

Tested on iPhone 6, iOS 9.0.2, WPiOS beta 5.7.0.20151026

**Comment by rachelmcr** [comment]
This is still an issue as of beta version 6.6.0.20161012. I am labelling this a bug since it doesn't look like the intended behavior and is confusing.

**Comment by elibud** [comment]
The same thing happens in Calypso: "See all your likers" from a notification takes you to the original post.

**Comment by catehstn** [comment]
The thing is, in Calypso - you can see all the likers on the post, which you can't do in the iThing view.

**Comment by elibud** [comment]
@catehstn Do you mean on the post stats? Or you can see all your likers somewhere else? Thx

**Comment by catehstn** [comment]
Ah I said Calypso but actually it's the same in the desktop reader view - you can only see how many, not who. But on the web I would end up on the post, not in the reader.

**Comment by elibud** [comment]
I am putting this on hold until we hear back from operation api, we need the Post Likes endpoint updated to support pagination and sorting by like time.

**Comment by elibud** [comment]
We are changing the footer to display "And XX more people" with no navigation.

**Comment by elibud** [comment]
We are trying to get this sorted server side, since all the Notifications text and actions come from there, stay tuned :)

**Comment by koke** [comment]
I've deployed the fix in r156388-wpcom
