### ISSUE TITLE
Notification email setting not accurate

### ISSUE THREAD

**Issue by drw158** [wordpress-mobile/WordPress-iOS#4385]
In Notification Settings (Me > Notification Settings > My Blog > Email)

I have all emails turned on. I tested this with some comments and I did not receive an email, even though they are turned on in the app.

I have a feeling it's because I have them turned off in wp-admin:

![screen shot 2015-10-28 at 2 42 49 pm](https://cloud.githubusercontent.com/assets/618551/10800865/44fc91c8-7d82-11e5-9289-314880ad65b1.png)

This is probably creating some confusion with users, especially since now you can't get to wp-admin via Calypso unless you know the url.

Update: I forgot that theses settings are also in Calypso:

![screen shot 2015-11-19 at 9 39 13 am](https://cloud.githubusercontent.com/assets/618551/11275061/6ff06b0e-8ea1-11e5-80f0-be23b5cfbc30.png)

**Comment by rodrigoi** [comment]
@drw158 those are indeed the settings that are preventing you from getting emails. Those settings are global for a site, affecting all users and stored as options, and the problem with integrating them into the notifications control center is that the settings we show there are user specific.

One way I think we could fix this is by adding a _Notifications_ tab to My Sites > Settings on Calypso/Native Apps, and disable the options accordingly on the control center. Maybe Add a warning with a link to site settings to tell the user why those settings are disabled.

For Calypso:
![screen shot 2015-11-02 at 12 06 45 pm](https://cloud.githubusercontent.com/assets/233601/10885086/4a4e7d4a-815a-11e5-8413-e408117d8605.png)

Also, there are settings that will have no effect on the control center, like reblog notification.

**Comment by drw158** [comment]
Eventually we should deprecate these email discussion settings in Calypso and move them to NCC. It will be a very bad UX to have the "same" setting in 2 different areas. As you mentioned, they are not technically the same, but the text does say "Email me whenever..." so it's very confusing.

I'm not sure of the implications of mapping these email settings to NCC though. I'm thinking that we should be able to just map them over directly, but probably not so simple :). If a site has multiple authors and one of the email discussion settings are checked, then map them to each user on the blog in NCC?

There will be some growing pains since we currently don't have an equivalent setting for comments held in moderation.

You suggestion for an alert message in NCC does sound like a good very short term solution though.

We should pull more eyes on this cc @roundhill

**Comment by hoverduck** [comment]
I confirmed that this is still an issue a year+ later.  Has there been any more thought given to how to consolidate these options in some way?

I wrote the corresponding issue on Android - https://github.com/wordpress-mobile/WordPress-Android/issues/5053

**Comment by drw158** [comment]
Perhaps this should be in the wp-calypso repo. Not sure why I added it in the iOS repo.

**Comment by elibud** [comment]
I'm closing this one, please move it over to Calypso if it's still relevant.
