### ISSUE TITLE
Inconsistent behavior for toggle labels

### ISSUE THREAD

**Issue by ranh** [wordpress-mobile/WordPress-iOS#4388]
On the Notification Settings screen under Me, toggle labels are interactive and can be tapped to toggle a setting. On other screens, toggle label are not interactive and a setting can only be toggle by tapping on the toggle itself.

To reproduce:

1. Go to Me > Notification Settings. Choose a site, choose a notification type, and tap on a label. The setting will be toggled. 
2. Go to Me > Account Settings. Tap on the label "Visual Editor". The setting is not toggled.
3. Go to My Sites, choose a site you own, and go to Settings. Tap on the label "Geotagging". The setting is not toggled. 

I tested this on 5.7.0.20151026

I recorded and uploaded a Lookback, "Recording 856", but I'm not quite sure where that goes?

**Comment by jleandroperez** [comment]
Closing this one since it's been already addressed by @koke 

(Thank you Jorge!)
