### ISSUE TITLE
Notification Settings: Switch Site Title with view title

### ISSUE THREAD

**Issue by drw158** [wordpress-mobile/WordPress-iOS#4390]
Current design:

![screen shot 2015-10-29 at 9 44 34 am](https://cloud.githubusercontent.com/assets/618551/10821759/00b61a02-7e22-11e5-9d1e-237e59299699.png)

I think it would make more sense if the Site Title was below the view title in the nav bar. The view title is the primary text and the site title is supplementary text. What do you think?

**Comment by jleandroperez** [comment]
@drw158 I think it'd be, perhaps, more consistent to move the Stream Name below. Reasons would be:

- You first tapped over the Site Name, not over the Stream Kind
- Although both fields are important, (imho) you first need to know which site is being edited, and only then which setting.

What do you think?
(Re: UI, perhaps the field that ends up going below can be moved to the Section Title area).

**Comment by drw158** [comment]
That makes sense. My thought is that the view shown above is identical to other views (push, email, tab). The only thing different is the little sub-title in each view. It's easy to not remember which delivery settings these settings apply to. I'm not married to this idea though.

**Comment by jleandroperez** [comment]
Oh i see!. We also have a _different_ titleView in the Reader's `Followed Topics` view (top left button), and in the WebView itself.

But i have no strong opinions whether we want to have this Title / Subtitle UX, or demote one of the two fields to the table itself. Absolutely your call @drw158!
