### ISSUE TITLE
Notification Settings: add footer text to reinforce context of the screen

### ISSUE THREAD

**Issue by davewhitley** [wordpress-mobile/WordPress-iOS#4391]
Got some feedback for this view:

![screen shot 2015-10-29 at 9 44 34 am](https://cloud.githubusercontent.com/assets/618551/10821831/7538cb90-7e22-11e5-9bd0-2fd10908e704.png)

>  What might help, I think, is some explanatory text below the list, like you used on the previous screen, to help reinforce the context of the settings that are currently being changed.

cc @jleandroperez

**Comment by designsimply** [comment]
Still a valid request.

Screenshot for reference:

<img src="https://user-images.githubusercontent.com/1119271/63216246-d54fbc00-c0ef-11e9-98d7-c5a49750195d.PNG" width="270" alt="IMG_2946">
<sup>"Push Notifications" screen in Profile > Notification Settings > $site, tested with WP Internal 13.1.0.20190814 on iPhone 6S iOS 12.4.</sup>

**Comment by kduncanwelke** [comment]
I'm going to try taking this one on. 👍🏻

**Comment by jleandroperez** [comment]
Thank you @kduncanwelke 😄
