### ISSUE TITLE
Generating Pods project error

### ISSUE THREAD

**Issue by liusongWtu** [wordpress-mobile/WordPress-iOS#4395]
The file reference for "WordPressCom-Stats-iOS.bundle" is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
![Uploading 1.png…]()

**Comment by aerych** [comment]
A temporary work around is to set an environment variable, 
`COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=true`

**Comment by liusongWtu** [comment]
Thanks,it works.in the terminal, type export COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=YES
