### ISSUE TITLE
Create a CONTRIBUTING guide

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4399]
Use WPAndroid as a guide. https://github.com/wordpress-mobile/WordPress-Android/blob/develop/CONTRIBUTING.md

**Comment by jleandroperez** [comment]
Closing this one since it's no longer valid. We've got a [CONTRIBUTING.md](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/CONTRIBUTING.md).

Thank you sir!
