### ISSUE TITLE
Create a CODESTYLE guide

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4400]
Use WPAndroid as a guide. https://github.com/wordpress-mobile/WordPress-Android/blob/develop/CODESTYLE.md

**Comment by sendhil** [comment]
@astralbodies we have https://lookback.io/watch/bo8AEgq3ADciAeZma ?

**Comment by astralbodies** [comment]
I'm wondering if that's not the URL you meant to paste @sendhil :smile:

**Comment by sendhil** [comment]
@astralbodies woops...

**Comment by sendhil** [comment]
@astralbodies this is the link - https://github.com/wordpress-mobile/WordPress-iOS/wiki/WordPress-for-iOS-Style-Guide
