### ISSUE TITLE
Move building & OAuth topics to README

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4401]
We're pulling the workspace setup out of the WordPress.org mobile developer handbook and putting it into the codebase. Use WPAndroid as an example. https://github.com/wordpress-mobile/WordPress-Android/blob/develop/README.md

**Comment by jleandroperez** [comment]
Closing this one since it no longer applies. README.md currently has build (+ credentials) instructions.
Thank you sir!
