### ISSUE TITLE
Reader: Inconsistent sharing options in Reader list and full post views

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4402]
In the Reader, there are two options sharing a post:
1. In the Reader list view, you can tap the 3 dots in the top right and select "Share"
2. In the full post view, you can tap the sharing icon in the top right

The resulting sharing options are not consistent. Most notable is that you can't share the post to WordPress unless you're in the full post view. Is that intentional? It can be confusing if you're looking for a way to share a post e.g. on your own blog and don't notice that the full post view gives you more sharing options.

Sharing options in Reader list view:

![2015-11-03 16 51 38](https://cloud.githubusercontent.com/assets/8658164/10914731/972ff4e4-824b-11e5-885a-62d90f239916.png)

Sharing options in full post view:

![2015-11-03 16 51 50](https://cloud.githubusercontent.com/assets/8658164/10914741/9f01caee-824b-11e5-8e09-9f1cb689abb4.png)

For comparison, the web Reader gives you the same three sharing options (WordPress, Twitter, Facebook) in both the list view and the full post view:

![screen shot 2015-11-03 at 4 55 57 pm](https://cloud.githubusercontent.com/assets/8658164/10914810/f2c4ed1e-824b-11e5-9eb9-d520dbb078f3.png)

Viewed on iPhone 6, iOS 9.1, WPiOS beta 5.7.0.20151102

**Comment by aerych** [comment]
> Is that intentional?

Nope! That's a bug!
