### ISSUE TITLE
Reader Tags: Empty slug string causes a crash when unfollowing a tag

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4404]
The user reports a crash when following these steps:
1. Open the Reader tab and tap Menu
2. Tap Edit
3. Tap red minus sign on a tag I'm following
4: Tap Unfollow

The app crashes on this line, due to a nil string for the slug: https://github.com/wordpress-mobile/WordPress-iOS/blob/c305af94f04076b08b81c6e0cfaf40dcb0cc53ee/WordPress/Classes/Services/ReaderTopicService.m#L234

I haven't been able to reproduce the crash, but we should handle the error better in cases where the slug is nil.

h/t @bummytime for the help debugging this issue

**Comment by bummytime** [comment]
:tada: :balloon:

**Comment by aerych** [comment]
Nice sleuth work.  I'm stumped how a slug could ever be nil in that context (I'll blame cosmic rays).
