### ISSUE TITLE
Following Sites: Show error when trying to follow a site without a valid feed

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4406]
If you try to follow a site by entering a URL that exists but doesn't have a valid feed to follow, the app silently fails to follow it. Examples: a non-existent *.wordpress.com subdomain or google.com.

Steps:
1. Open the Reader tab and tap Menu
2. In the "Enter a URL or a tag to follow" field, enter a non-existent *.wordpress.com address (for example, thisblogreallydoesnotexist.wordpress.com) or a site without a feed like google.com.
Result: The blog isn't not followed, but no message appears to explain what happened

For comparison, if you try to enter a URL that doesn't exist at all, you get this error:

>Could not Follow Site
>A server with the specified hostname could not be found.

From here: https://github.com/wordpress-mobile/WordPress-iOS/blob/4d63a17c9b1707d0369405eab79fdc7d65ef88ed/WordPress/Classes/ViewRelated/Reader/ReaderSubscriptionViewController.m#L249

It would be nice to have a similar error message for sites that exist but can't be followed. (This would be a good enhancement to go along with adding some animation around following/unfollowing blogs, per #2086, so users get some kind of feedback in all cases.)

Tested on iPhone 6, iOS 9.1, WPiOS beta 5.7.0.20151102

**Comment by aerych** [comment]
Thanks for testing this one.

> If you try to follow a site by entering a URL that exists but doesn't have a valid feed to follow, the app silently fails to follow it. Examples: a non-existent *.wordpress.com subdomain or google.com.

I wasn't able to reproduce the behavior described. Testing both non-existent wpcom sites and google.com both resulted in successfully following an actual site.  In the case of `google.com` there is actually a feed mapped to it.  In the case of random non-existent wpcom sites, a redirect to `en.blog` results in following `en.blog.wordpress.com/feed` (WordPress.com News). Granted, this is confusing and probably not the behavior we want.   We should address it at the API level where its occurring vs in the app. 

FWIW when I tried following `zombo.com` I saw a prompt with the following:
`Could not follow the site at the address specified.`

If you try following a site you're already following the app shows a simple confirmation toast where the web prompts that you were already following the site in question. #2173 addresses that issue for tags but we can expand it for sites as well. 

Following management in the app is due for an overhaul as a part of the menu refresh in #4094. This supersedes #2086.

Closing this one as the out standing concerns are accounted for in other issues.

**Comment by rachelmcr** [comment]
Well, don't I feel silly. :) Somehow I didn't catch the newly followed feeds after trying to follow those sites; will make a note to change how I test that kind of thing in the future to better catch that. Thanks for the clarification/followup!
