### ISSUE TITLE
Unfollow spinner does not dismiss

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#4413]
In the latest 5.7 internal beta, a user reported that the spinner which appears after unfollowing a site from the reader is never dismissed:

<img width="669" alt="napkin 17 11-03-15 7 12 39 pm" src="https://cloud.githubusercontent.com/assets/154014/10926760/d919a4a4-825f-11e5-8ced-a0f201c3373f.png">

I was able to repro this on my iPhone 6s+ running iOS 9.1.

**Comment by aerych** [comment]
Nice catch @bummytime
