### ISSUE TITLE
Let's remove the "brand new editor" dialog

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#4414]
...it's time.

<img width="286" alt="napkin 18 11-03-15 7 35 34 pm" src="https://cloud.githubusercontent.com/assets/154014/10927067/3aecfc88-8262-11e5-8894-22bdf2400700.png">

Ref: #3218 

/cc @meremagee @thianhlu

**Comment by thianhlu** [comment]
:+1:

**Comment by diegoreymendez** [comment]
Fixed in [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/4579).
