### ISSUE TITLE
Notifications: Option to mark all as read

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4418]
A user requests the option to mark all unread notifications as read.

Currently, you have to tap in to each notification to mark it as read, and there isn't a way to move directly from one notification to the next. (In the web browser, you can use the up and down arrow keys to move directly from one notification to another.) With multiple unread notifications, that means tapping in to each notification individually and tapping back to the full list to view the next one.

**Comment by rachelmcr** [comment]
A related issue that could also resolve this: https://github.com/wordpress-mobile/WordPress-iOS/issues/5025

**Comment by jleandroperez** [comment]
Closing in favor of #5025. Definitely better approach (IMHO!)
