### ISSUE TITLE
Notifications filter: Easy to lose track of just-read notifications from Unread filter

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4420]
A user noted that when you're using the Unread notifications filter, it's easy to lose track of notifications once you've read them since they disappear from the list immediately.

On the Notifications tab:
- Click on the unread filter
- Click on one of your unread notifications
- Click arrow to go back to list view
- The notification you just read is not there anymore (and hard to find again if you were looking for it).

For comparison, the web browser's notifications keep the same notifications in the Unread filter until you leave that view and come back to it.

Screenshots: https://cloudup.com/c8T7iYXPUCt

WPiOS beta 5.7.0.20151102

**Comment by hoverduck** [comment]
#bug-scrub

Confirmed this is still an issue with v6.8.0.20170112
