### ISSUE TITLE
Autocorrect suggestion overlaps help text in tagline settings

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#4429]
![img_1045](https://cloud.githubusercontent.com/assets/8739/10967601/f6ba370a-83bb-11e5-9d22-deeac57c7c0c.jpg)

cc @SergioEstevao

**Comment by hoverduck** [comment]
Closing, this no longer seems to be an issue:
<img width="229" alt="screen shot 2017-01-25 at 10 00 24 am" src="https://cloud.githubusercontent.com/assets/7233112/22295504/2b1e7450-e2e5-11e6-9cc8-95ffc47529c1.png">
