### ISSUE TITLE
Editor: Unsaved changes popup obscured by keyboard in HTML mode

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4430]
In HTML mode, “You have unsaved changes” pop-up is covered by keyboard

Environment:
Device: iPhone 6
OS: iOS 9.1
App: WP Internal latest version

Steps to replicate:
1. Edit a post
2. Click “HTML” on top right of keyboard. This switches to HTML mode
3. Type something into the content area
4. Hit back arrow on top right
5. The screen turns grey, the “You have unsaved changes” pop up appears but covered by the keyboard so can’t be actioned upon. If you switch to a taller keyboard type (e.g: the Emoji one), then the pop up is completely covered.

Screenshots:

Portrait view in HTML mode (keyboard entirely covers pop-up):

![2015-11-05 12 12 25](https://cloud.githubusercontent.com/assets/8658164/10968238/d0940bae-83b7-11e5-8f72-e1268943805a.png)

Landscape view in HTML code (keyboard mostly covers pop-up):

![2015-11-05 12 12 33](https://cloud.githubusercontent.com/assets/8658164/10968237/d093add0-83b7-11e5-956c-467f1c4a472e.png)

Portrait view in Visual mode (keyboard closes before pop-up appears):

![2015-11-05 12 12 50](https://cloud.githubusercontent.com/assets/8658164/10968239/d094c7ba-83b7-11e5-967d-57263df32119.png)

**Comment by bummytime** [comment]
@rachelmcr I am going to bounce this issue over to the Editor repo if you don't mind.

https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/733

Thanks!

**Comment by rachelmcr** [comment]
Aha, didn't see there was a separate repo. :) thanks!
