### ISSUE TITLE
Slightly different backgrounds on reader comments

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#4433]
The cell and table backgrounds are different:

![simulator screen shot 06 nov 2015 13 18 27](https://cloud.githubusercontent.com/assets/8739/10999964/555b94d2-849f-11e5-92b6-f1dca574813b.png)

It's hard to see it on a device, and only slightly more visible on a simulator. I guess my external monitor color is crappier than Apple displays ;)

![screen shot 2015-11-06 at 13 20 06](https://cloud.githubusercontent.com/assets/8739/11000014/8dfff242-849f-11e5-99c8-f36cbf6f17a8.png)

**Comment by aerych** [comment]
Will be resolved with #4034

**Comment by aerych** [comment]
Closed in #4706
