### ISSUE TITLE
Site Settings: "Hidden" privacy user hint grammar issue

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#4437]
Currently, in the privacy settings for a site, we display some helpful hints indicating what each setting means. However, the "Hidden" setting could be worded a bit better:

Current wording:

"Your site is visible to everyone, but asks to search engines to not index your site."

We should remove that extra "to" and swap the "not" and "to":

"Your site is visible to everyone, but asks search engines not to index your site."

Relevant code: https://github.com/wordpress-mobile/WordPress-iOS/blob/bb3ebc82ad757fec1e16a88c87409d48f4300d26/WordPress/Classes/ViewRelated/Blog/SiteSettingsViewController.m#L481

**Comment by aerych** [comment]
Seems like these three strings should match what is in wp-admin. 
@mattmiklic would you concur?

**Comment by mattmiklic** [comment]
> Your site is visible to everyone, but asks search engines not to index your site.

This matches the text that I included in the mockups for the section. The labels in wp-admin eiuldnt work very well for these secondary hints.

**Comment by mattmiklic** [comment]
Sorry. Commenting from a phone and accidentally closed this.

**Comment by aerych** [comment]
> The labels in wp-admin wouldn't work very well for these secondary hints.

Sounds good.  Thanks Matt
