### ISSUE TITLE
iPad Pro notification icon misaligned

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#4461]
Happens on both landscape and portrait mode

![img_0003](https://cloud.githubusercontent.com/assets/1158819/11189966/0d7524f2-8c48-11e5-8065-2068dd537202.jpg)

**Comment by bummytime** [comment]
Also just noticed this on my iPad Pro (landscape):

![screen shot 2015-11-17 at 2 34 51 pm](https://cloud.githubusercontent.com/assets/154014/11224028/98162ce6-8d38-11e5-8eab-dddc05971507.png)

:smile:

**Comment by pypt** [comment]
A quick and dirty fix would be to add two more ["horizontal spacing" exceptions to WPTabBarController](https://github.com/wordpress-mobile/WordPress-iOS/blob/3bd021020be8b57575bd80a074cf5ae31f95aa54/WordPress/Classes/ViewRelated/System/WPTabBarController.m#L44-L45) for the iPad Pro. After some experimentation, I've found out that the magic numbers are `236.0f` for portrait and `408.0f` for landscape. Before that, one would have to teach WordPress-Shared-iOS to recognize iPad Pro device model too.

A more permanent solution would be to replace stock UITabBar with some sort of a drop-in replacement which would allow one to manage badge view (position) without making any guesses / adjustments for new devices Apple releases, but I'm undecided whether such change would be justified in this case. What do you think?

**Comment by jleandroperez** [comment]
Closed via #4506
