### ISSUE TITLE
Rotating while searchController open results in incorrect size

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#4466]
@rachelsquirrel noted that the search bar is fine when one is holding the device in portrait mode. Then when the app is flipped to landscape and then back to portrait, the search bar moves up. Here are their screenshots after they turned their screens to landscape then back to portrait:

I have found out the Site Search also does this

![screen-shot-2015-11-11-at-11-53-03](https://cloud.githubusercontent.com/assets/1158819/11219204/10069680-8d0e-11e5-8ed3-01957306b858.png)

![img_3786](https://cloud.githubusercontent.com/assets/1158819/11219207/165452a2-8d0e-11e5-8fe7-10693034e9f7.png)

**Comment by aerych** [comment]
Hmm... maybe its time to take another stab at #4343

**Comment by kwonye** [comment]
> Hmm... maybe its time to take another stab at #4343

@aerych Haha, I was just thinking the same thing. I'll add that to my list of things to do. However I did do a quick fix that would resolve this for our users in the mean time.
