### ISSUE TITLE
My Sites: HTML entities visible in blog titles for self-hosted sites

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4472]
Guessing we're not correctly decoding the title from XML-RPC.  Same title displays correctly when the blog is connected to Jetpack and consumed via the REST API. 
![simulator screen shot nov 17 2015 3 24 51 pm](https://cloud.githubusercontent.com/assets/1435271/11225409/93598944-8d3f-11e5-8af8-6afa56b3cbfa.png)

**Comment by rachelmcr** [comment]
I confirmed this issue in beta v. 5.9.0.20160113.

When adding a new site, the title displayed correctly at first (in the list of sites and in the site settings). A moment after opening the site settings, however, the screen refreshed and the HTML entities appeared. I also see HTML entities in the site tagline.

**Comment by aerych** [comment]
This bug is annoying me so I shall squash it.
