### ISSUE TITLE
Site Settings: Self-hosted settings visible after signing into wpcom.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4473]
Maybe a bit of an edge case.
To reproduce:
- Sign into a Jetpack connected blog via the self-hosted sign-in form. 
- Navigate to its Site Settings screen.  Notice that screen name and password options are present. 
- Switch to the Me tab and sign in to WordPress.com using the credentials connected to the blog's Jetpack plugin. 
- Switch back to My Sites. Notice that the blog's settings still show the self-hosted option for screen name and password as well as the option to remove the self-hosted blog. 
- Tap the back button, then choose Settings again. 
Notice the available settings no longer include credentials or the sign out option.

**Comment by rachelmcr** [comment]
I confirmed this bug with the steps above in beta v. 5.9.0.20160113. I also confirmed that pulling down to refresh the settings didn't remove the username/password from the site's settings — they remained until I went back and reselected Settings.

**Comment by kurzee** [comment]
@aerych tested this and looks like this is resolved in your recent work via https://github.com/wordpress-mobile/WordPress-iOS/pull/4777, nice!

**Comment by aerych** [comment]
Yay for bonus fixes :)
