### ISSUE TITLE
Blog List: Tapping search shows an empty list when only a signle self-hosted blog is in the app.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4476]
Title has it.  Maybe don't show the search button when there is only a single blog.

### Single self-hosted site
![simulator screen shot nov 17 2015 4 59 48 pm](https://cloud.githubusercontent.com/assets/1435271/11227661/e8ee7218-8d4c-11e5-996f-d123e708fe8d.png)

### Empty list
![simulator screen shot nov 17 2015 4 59 49 pm](https://cloud.githubusercontent.com/assets/1435271/11227680/09e249fe-8d4d-11e5-893c-40151884960a.png)

**Comment by kwonye** [comment]
Not able to repro but hiding the button will make sure this never happens.

Worried there is something else going on however. Was it only when you had one site? Unable to repro.

**Comment by aerych** [comment]
Yeah, it was only when I had a single site.  I can still repro.  I thought maybe it could be because I was signing out, and then signing in with a single self-hosted site, but even force quitting and relaunching the search button still appears and I get an empty list.
