### ISSUE TITLE
If a Post has Zero Views, Stats Page Shows Period 1970 to 2015

### ISSUE THREAD

**Issue by kevmarsden** [wordpress-mobile/WordPress-iOS#4493]
If a post has zero views, the stats for an individual post shows the period 1970 - 2015.  The stats for an individual post can be found by navigating to **My Sites** > SELECT SITE > **Blog Posts** and then touching the **Stats** link.  

Here's a screenshot of that stats page:
![img_0070](https://cloud.githubusercontent.com/assets/2282189/11277027/77f20040-8e99-11e5-97dd-84186d4434d5.png)

Verified on 5.7 and Beta 5.8.02151117

**Comment by rachelmcr** [comment]
Thanks for the report! This is an API issue and is being tracked for iOS stats here: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/306

Closing this as a duplicate.
