### ISSUE TITLE
My Profile

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#4499]
Add a "My Profile" section inside "Me"

![me-ios-1](https://cloud.githubusercontent.com/assets/8739/11279548/92929812-8ef1-11e5-9b6b-fed014ee83be.png)

**Comment by diegoreymendez** [comment]
@koke, @jleandroperez - I added the 6.0 tag for now since I'm working on the release notes, but if this feature is removed from the 6.0 release please let me know.
