### ISSUE TITLE
Use of post action label "Bin" inconsistent

### ISSUE THREAD

**Issue by jancbeck** [wordpress-mobile/WordPress-iOS#4505]
![img_3102](https://cloud.githubusercontent.com/assets/865311/11293570/b3ee00a4-8f8d-11e5-9977-4a002f029466.jpg)

Down in the footer of the post card in the blog post list there are four available actions:
- Edit
- Preview
- Publish
- Bin

Three of them are verbs. The last one is a noun and it is also inconsistent with WPs normal use of the word "Trash" for this kind of action. 

Applies to v5.7 in the Appstore

**Comment by rachelmcr** [comment]
The term "Bin" (which is a verb as well as a noun) comes from the UK English translation of the app in GlotPress here:

https://translate.wordpress.org/projects/apps/ios/dev/en-gb/default?filters[status]=either&filters[original_id]=150401&filters[translation_id]=9078285

The best place to suggest a different translation (either the term "Trash" or another option) would be directly in GlotPress. It's also perhaps worth noting that this matches the main WordPress.org translation of "Trash" for UK English:

https://translate.wordpress.org/projects/wp/dev/en-gb/default?filters[status]=either&filters[original_id]=3215&filters[translation_id]=1154130

**Comment by jancbeck** [comment]
Changing my iPhones device language to "English (U.S.)" instead of "English" changed the string to "Trash". Thanks, I was assuming I was already using U.S.
