### ISSUE TITLE
Jetpack: Unclear error message when connecting from Stats to WordPress.com account with 2FA

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4521]
When I try to connect Jetpack to a WordPress.com account with 2FA from the Stats screen, it gives a generic error message:

> Invalid username or password

<img src="https://cloud.githubusercontent.com/assets/8658164/11424243/559ef430-9443-11e5-9c9b-cf3bdb80180f.png" width="50%" />

In the past, the app gave an explicit error message saying that the account has two step authentication enabled and needs an app-specific password (see #2172). The app should either provide a clear error message like that or include the option to enter a verification code, as it does on the main login screen or from the Me tab.

**Comment by astralbodies** [comment]
@jleandroperez Is there any support for 2FA on the Jetpack login screens? Is stats maybe using an old/outdated UI?

**Comment by jleandroperez** [comment]
@astralbodies [JetpackSettingsViewController](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Stats/JetpackSettingsViewController.m#L65) should have support for 2FA. Maybe it's an old VC?

**Comment by astralbodies** [comment]
I'll dig into this one further. Thanks @jleandroperez!

**Comment by jleandroperez** [comment]
Anytime @astralbodies! If anything, please, just let me know!

**Comment by diegoreymendez** [comment]
@astralbodies - We may need to update the 6.0 tag in this issue.

**Comment by astralbodies** [comment]
Marking as someday right now. @rachelmcr is that cool?

**Comment by rachelmcr** [comment]
Works for me. I don't think this is a high-frequency issue, so it'd be nice to fix it at some point but isn't critical right now.

**Comment by rachelmcr** [comment]
This came up with a user in 146898-h. They confirmed that the login details worked elsewhere and couldn't figure out based on the error in the app why their login details didn't work on the Stats login screen.

**Comment by bummytime** [comment]
Bump. I will look at this as part of #6389

**Comment by bummytime** [comment]
This was fixed in #6507
