### ISSUE TITLE
Multitasking: Unable to set featured image from multitask pane 

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#4525]
When editing a post from the multitask pane, if you attempt to set a featured image it's impossible to dismiss the media selection window.  Clicking either Cancel or Done does nothing, but if you open the app to full screen, the image has been successfully selected.

Using iPad Air 2, iOS 9.1

**Comment by sendhil** [comment]
cc @diegoreymendez
