### ISSUE TITLE
Feature Request: Add access to media library separate from editor

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4528]
A couple users have requested a way to access and upload images to their site's media library, separate from the editor. The Android app has this in the Media section for each site, where you can browse and upload to the media library directly.

This would allow users to quickly upload images from their mobile device, and then create a post or page with them later (either through the app or in a browser). The use cases described:
- Uploading images from a mobile device, and composing the posts on a computer later using those photos.
- Uploading images from a mobile device in order to create posts with image galleries (would be resolved by https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/300)

This was previously mentioned in https://github.com/wordpress-mobile/WordPress-iOS/issues/3456#issuecomment-110808927 (now closed).

**Comment by rachelmcr** [comment]
Another user left an app review (3 stars) mentioning that they'd like the ability to upload media for later use. Access to the media library separate from the editor would make it easy to upload media like that.

**Comment by SergioEstevao** [comment]
@rachelmcr I would love to do this but it's not our top priorities. Correct @astralbodies ?

**Comment by rachelmcr** [comment]
That's cool — I'm just trying to track the requests for it so we can see how commonly it's requested. It's fine if it's a "maybe someday" enhancement. :)

**Comment by rachelmcr** [comment]
This was requested again in the forum:

https://ios.forums.wordpress.org/topic/image-upload-feature-request

**Comment by rachelmcr** [comment]
A user sent us feedback requesting this feature:

> es wäre gut, wenn man schon gemachte bilder vom handy in die mediathek hochladen könnte

Translation:

> if would be good if you could upload photos you had already taken from the mobile phone to the media library

**Comment by frosty** [comment]
This has been resolved by the release of the new Media Library on iOS. refs https://github.com/wordpress-mobile/WordPress-iOS/pull/7290
