### ISSUE TITLE
Hide link to wp-admin for new users on WordPress.com sites

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#4532]
New users on WordPress.com do not have a wp-admin link available (only for WordPress.com sites).

Requirements

1. New users should not see wp-admin item in "My Sites" on WordPress.com sites
2. Old users should see wp-admin item in "My Sites" on WordPress.com sites
3. New users should see wp-admin item in "My Sites" on self-hosted sites
4. Old users should see wp-admin item in "My Sites" on self-hosted sites

**Comment by apeatling** [comment]
Old vs New cut off is 2015-09-07 00:00:00
