### ISSUE TITLE
Notifications: "No unread notifications" message can overlap filter bar

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4536]
When the rating prompt ("What do you think about WordPress?") is on the notifications tab, the "No unread notifications" message overlaps the notifications filter bar in landscape mode:

![2015-12-01 14 48 29](https://cloud.githubusercontent.com/assets/8658164/11503986/0116acb8-983b-11e5-9b55-bd540c0fbcbf.png)

It's fine in portrait mode, and when the rating prompt is dismissed.

Seen on iPhone 6, iOS 9.1, app beta 5.8.0.20151124.

**Comment by jleandroperez** [comment]
Thank you @rachelmcr!!
