### ISSUE TITLE
Reader: Improve failed loading post error message on detail

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4566]
The post detail shows a generic "Error Loading Post" message when a post fails to load.  We could make a few changes to the failure block in `WordPressComAPI HTTPRequestOperationWithRequest:success:failure:` and include some additional information in the `NSError userInfo` dictionary to improve error message displayed.  For example, including the http status code would let us specify a post failed to load because it was private in the case of a 403 error.

**Comment by yaelirub** [comment]
Closing as duplicate of #13525
