### ISSUE TITLE
Feature Request: Allow 'Share' from other apps

### ISSUE THREAD

**Issue by Ipstenu** [wordpress-mobile/WordPress-iOS#4567]
I like to write posts in byword. Using that, I can share my post to other apps and mail them or, in the case of Working Copy, send the content into a post there.

It would be incredible if I could do that with the iOS app. Write, share, pick the blog, have it prefill the content, save.

**Comment by aerych** [comment]
Its on the radar :)  See https://github.com/wordpress-mobile/WordPress-iOS/issues/2231
