### ISSUE TITLE
Stats: formatting problems for referrers and posts lists

### ISSUE THREAD

**Issue by gibrown** [wordpress-mobile/WordPress-iOS#4568]
A couple of cases where the text runs off the screen in stats. This is on iOS 9.1 on an iPhone 5S with version 5.7 of the app.

![2015-12-15 08 17 35](https://cloud.githubusercontent.com/assets/820871/11818092/6fa34ee8-a326-11e5-839a-febe9eccf50b.png)

![2015-12-15 08 16 43](https://cloud.githubusercontent.com/assets/820871/11818097/73d49d0a-a326-11e5-9184-f7e866ca21d2.png)

**Comment by JasonSnow-Mad** [comment]
Also seeing this with on Insights page on an iPhone 5s. iOS 9.2, WordPress App 5.8. Specific test case was in Portuguese:

![portuguese_app_image](https://cloud.githubusercontent.com/assets/8810295/12126907/fe7db026-b3c1-11e5-83fc-23f54227ce45.png)

**Comment by astralbodies** [comment]
Oof - thanks for the report. I'm hoping to get to all of these issues this week as part of the maintenance rotation for stats. @JasonSnow-Mad can you confirm its happening on WPiOS 5.8?

**Comment by astralbodies** [comment]
@gibrown Can you see if this is still happening in WPiOS 5.9?

**Comment by gibrown** [comment]
@astralbodies all looks good on 5.9. Thanks!
