### ISSUE TITLE
Disable WhatsNew for New Editor

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4573]
I think the editor has been around enough where we don't need to pop up what's new for it. I know we're seeing it a lot because we uninstall and reinstall a bunch more than regular users would. But I think the editor is good enough to not have to point out that our old editor sucked to new users, right?

@sendhil @diegoreymendez

**Comment by diegoreymendez** [comment]
Sounds reasonable to me.

**Comment by diegoreymendez** [comment]
Closing since this is a duplicate of [this issue](https://github.com/wordpress-mobile/WordPress-iOS/issues/4414).
