### ISSUE TITLE
Media: Media picker jumps back to the top

### ISSUE THREAD

**Issue by johanlavenius** [wordpress-mobile/WordPress-iOS#4575]
When trying to add an image with the mediapicker on my ipad it keeps jumping to the top. When scrolling down images is first a little blurry and then at the moment they get sharp the picker jumps to the top.

Using iCloud photo library with about 12k images and videos
Cannot reproduce this on my iPhone
Both updated to 5.8

**Comment by diegoreymendez** [comment]
@SergioEstevao, @johanlavenius - Has this been released in 6.1?  Shall we close it, or re-tag it?

**Comment by SergioEstevao** [comment]
@diegoreymendez this is sorted out in the 6.1version of the app. So when that it's released it can get closed down.

**Comment by diegoreymendez** [comment]
Sorry I'm a bit confused.  If the PR has been merged and everything is fine, can't this be closed right away? (to keep consistent with how we handle other issues)

**Comment by SergioEstevao** [comment]
Ok for me then.
