### ISSUE TITLE
Remove the legacy editor.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#4580]
The visual editor has been around for a while now, and it feels like it should be stable enough to remove the legacy editor from the code entirely.

This would represent a nice cleanup for our codebase.

Asking for a second opinion from: @thianhlu, @meremagee, @bummytime, @sendhil.

**Comment by SergioEstevao** [comment]
I asked about this before in the editor channel, and the answer at the time was that we wanted to keep it because off accessibility on the new editor. It looks that this old editor works a lot o better if our users need to use the accessibility features on iOS. @astralbodies do you confirm?

**Comment by astralbodies** [comment]
@SergioEstevao is right - we need to keep that editor around for accessibility at a minimum. Until we come up with a native editor I think we're sort of stuck with it.

**Comment by diegoreymendez** [comment]
Removed the milestone for the time being since there's a dependency.

**Comment by diegoreymendez** [comment]
@astralbodies - Is there an easy-to-identify list of features we're missing in the new editor?  If the list is not too big I can try tackling the issues.

**Comment by sendhil** [comment]
what @astralbodies said

**Comment by astralbodies** [comment]
@diegoreymendez I don't have a list of features we're missing other than VoiceOver support :smile:

**Comment by diegoreymendez** [comment]
@astralbodies - More info about why this is not possible yet can be found in the discussion of [this issue](https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/688).

I'd suggest to keep this issue alive, so that any attempt to remove the old editor comes up with this information.

**Comment by diegoreymendez** [comment]
I'm dissociating this issue from my account for the time being, since it's not possible to implement this.

**Comment by jleandroperez** [comment]
Closed via #8234. Wooo!!
