### ISSUE TITLE
Images upload in random order (since 5.8)

### ISSUE THREAD

**Issue by versluis** [wordpress-mobile/WordPress-iOS#4584]
I've noticed that since the 5.8 update, images upload slightly faster than before, but not in the order they were selected in. Confirmed on both iPhone and iPad under iOS 9.2. Version 5.7 did not suffer from this.

**Comment by rachelmcr** [comment]
I tested in the latest beta and confirmed that when selecting multiple images to upload at the same time, the images are not uploaded in the order in which they were selected. (They also aren't necessarily uploaded in the order that they were taken, or in a consistent order when uploading the same images, either, so I'm not sure how the order is being determined.)

Device: iPhone 6, iOS 9.2
App: beta 5.9.0.20151216

**Comment by ChrissiePollock** [comment]
Might be a new instance of this issue in internal reference #186141-h

**Comment by ChrissiePollock** [comment]
Another instance (internal ref. #187652-h)
