### ISSUE TITLE
Featured image detail bottom toolbar has old app style

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4596]
Title has it. We need to update that guy. 

![simulator screen shot dec 18 2015 11 10 52 am](https://cloud.githubusercontent.com/assets/1435271/11902526/1d41068c-a578-11e5-97c2-e081272a0eaf.png)

**Comment by SergioEstevao** [comment]
@mattmiklic do you mind if I move the trash icon to the right of the navigation bar? or do you want to do the same has here: https://github.com/wordpress-mobile/WordPress-iOS/issues/4597

**Comment by SergioEstevao** [comment]
@mattmiklic does this look right to you?
<img width="423" alt="screen shot 2016-02-09 at 22 59 01" src="https://cloud.githubusercontent.com/assets/651601/12933616/efc2cdde-cf80-11e5-9844-db2be20d1c85.png">

**Comment by mattmiklic** [comment]
Looks good on size -- could it maybe go a bit more to the right? Maybe about 10px?

**Comment by SergioEstevao** [comment]
@mattmiklic This is the default spacing iOS uses, let's see if I can nudge it.

**Comment by SergioEstevao** [comment]
@mattmiklic  looks better?

<img width="423" alt="screen shot 2016-02-10 at 00 24 18" src="https://cloud.githubusercontent.com/assets/651601/12935310/c7cbb51e-cf8c-11e5-8258-03f2afde2bb0.png">

**Comment by mattmiklic** [comment]
Yup! That looks better.
