### ISSUE TITLE
Reader - "0 words" label on photo post

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-iOS#4599]
We should remove the label "0 words" on those posts that only contain pictures/videos.
The Web and the Android version of Reader already does this.

Mobile:
![file 19-12-15 09 28 53](https://cloud.githubusercontent.com/assets/518232/11912437/c604783e-a63c-11e5-9b60-ec6f6c1ca7e7.png)

Web:
![screen shot 2015-12-19 at 10 36 49](https://cloud.githubusercontent.com/assets/518232/11912440/ced896e8-a63c-11e5-9ecd-bc6933d1d64c.png)

**Comment by aerych** [comment]
Nice catch :)

**Comment by aerych** [comment]
We're going to drop the word count with the upcoming card refresh in #6070, so I'm going to mark this one closed.
