### ISSUE TITLE
Insights in Stats Crashes with French Locales

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4602]
There is a translation error in a string used in the Insights screen. This is causing a crash for French users of the application when the screen is shown. It doesn't crash in every case but for some users its consistent. 

Crash reports: http://crashes.to/s/66bf19ed103

**Comment by astralbodies** [comment]
Closed inadvertently by a previous link made by @koke on #4605

**Comment by astralbodies** [comment]
PRs were closed - the translation will naturally fix things in 5.9.

**Comment by astralbodies** [comment]
@sendhil Can you close this issue when you update translations for 5.9?

**Comment by sendhil** [comment]
@astralbodies  - sure.

**Comment by sendhil** [comment]
Closing as 5.9 is off to the app store.
