### ISSUE TITLE
Discussion Settings: Refresh on viewWillAppear

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#4615]
As per @diegoreymendez's comments on #4583:

1. Make sure that "Comment author must fill out name and e-mail" is checked.
2. Open the site settings in the mobile app.
3. Open the site settings in calypso.
4. Go back one level in the mobile app, without changing anything.
5. Uncheck "Comment author must fill out name and e-mail" in Calypso and save the settings.
6. Open the site settings in the mobile app again.

Expected behaviour: the site settings in the mobile app should reflect the latest changes.
Current behaviour: it doesn't.

(Thanks Diego!)

**Comment by rachelmcr** [comment]
Tested and confirmed the bug with the steps above, in beta 5.9.0.20160105.
