### ISSUE TITLE
WordPress 4.4 post date is incorrect

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#4616]
There is a bug in WordPress 4.4 that changed the `post_date` from local time to gmt time. https://core.trac.wordpress.org/ticket/35053

This results in the post not posting at the correct time. The fix will be in 4.4.1, but 4.4 will always have this issue. We'll need a special case for self-hosted sites on 4.4

**Comment by aerych** [comment]
I'm not sure we need to patch this.  I think the better way to handle it would be to encourage users to upgrade to 4.4.1.  My two cents.

**Comment by rachelmcr** [comment]
>I'm not sure we need to patch this.

Agreed. From a support perspective, I can't find any reports of issues from users with WordPress 4.4 and if it comes up in the future we can encourage users to upgrade. (Current version is 4.5.2.)

I'm closing this issue; please reopen if you think a fix is needed for this.
