### ISSUE TITLE
PostService sends blogID=0 for Jetpack sites connected to a secondary account

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#4618]
In #4275 we changed the remotes to stop passing managed objects and we now pass blog IDs.

In this edge case `blog.blogID = 0`, which wasn't a problem for XML-RPC, but since the site is connected to Jetpack it will use REST.

To reproduce:
- Sign in to the app with a WordPress.com account
- Add a Jetpack site connected to a different WordPress.com account
- Go to stats on the Jetpack site and configure the second WordPress.com account
- Try to refresh posts on the Jetpack site
- Get a `Unknown blog [unknown_blog]` error

/cc @SergioEstevao

**Comment by koke** [comment]
I'm not sure what's the best solution without a deep refactor of how we store things. I'm thinking about changing `blogID` to always represent the wp.com ID of a blog (since we never really use the self hosted ID), so as a quick fix I'd override `-[Blog blogID]` with something like this:

```
- (NSNumber *)blogID
{
    NSNumber *blogID = [self primitiveValueForKey:@"blogID"];
    if ([blogID integerValue] > 0) {
        return blogID;
    }
    if (self.jetpack.siteID) {
        [self setPrimitiveValue:self.jetpack.siteID forKey:@"blogID"];
        return self.jetpack.siteID;
    }
    return nil;
}
```

**Comment by SergioEstevao** [comment]
@koke this looks the simpler way to updated it. You want to submit a PR with it?

**Comment by koke** [comment]
On a second thought, I'm not happy with this solution. I think this new `blogID` is just a different implementation of `dotComID` and I'd rather use that for clarity. I'll prepare a PR
