### ISSUE TITLE
Re-order modules on Stats Insights

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPress-iOS#4622]
The modules on Insights should be re-ordered. To match that of Calypso, the new order is now:

1. Latest Post Summary
2. Today's Stats
3. All-time numbers
4. Most popular day and hour

/cc @astralbodies

**Comment by astralbodies** [comment]
Moving this issue to the stats repo - https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/372
