### ISSUE TITLE
Tapping "add link" on legacy editor causes immediate-ish crash

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4624]
Example crash: http://crashes.to/s/c09f4352d50

There is some autolayout demon causing a crash when someone attempts to add a link to the editor when the legacy one is turned on. Its affecting people with VoiceOver so we should probably address this soon.

cc: @diegoreymendez, @bummytime

**Comment by astralbodies** [comment]
cc: @JasonSnow-Mad

**Comment by diegoreymendez** [comment]
@astralbodies - I'm not sure the bug I fixed is the same as the crash log you posted, as the stack trace I was getting was entirely different.  Let's keep our eyes open for any other bugs.

**Comment by diegoreymendez** [comment]
Fixed.
