### ISSUE TITLE
Add site button missing after first login

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#4647]
To reproduce:
1. Launch the app from a fresh install
2. Sign in to a WordPress.com account
3. Navigate to My Sites if necessary

There should be an add site (+) button on the top right corner, but it's not there until the app is relaunched

**Comment by kwonye** [comment]
Deemed a blocker by @aerych (and I agree)

**Comment by frosty** [comment]
Closed by #4670.
