### ISSUE TITLE
My Sites: Bad UX when logged in on an account with no blogs. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4664]
To reproduce:
- Create a new WordPress.com account (or use an existing one) and delete all your blogs. (You'll loose all your content so don't test with an account you care about.) 
- Sign into the app and visit the My Sites tab. 
- Notice the screen is blank.  
- Now tap the middle tab on the tab bar to launch the editor. 
- Notice you're prompted to create a new account. 

We should probably show a call to action on the My Sites tab and show an option to create a blog. 
We should probably do the same when tapping on the editor's tab. 

![simulator screen shot jan 12 2016 11 30 28 am](https://cloud.githubusercontent.com/assets/1435271/12271449/c189795c-b920-11e5-8127-eea046328b4d.png)

**Comment by rachelmcr** [comment]
I tested in beta v. 6.1.0.20160331 and there's a small improvement in that you can tap the + in the top right to add a site:

![2016-04-04 12 39 37](https://cloud.githubusercontent.com/assets/8658164/14264211/cef1ad3c-fa8c-11e5-9aef-d81d6270b163.png)

However, tapping the editor is still a poor experience as it brings up a self-hosted login screen:

![2016-04-04 12 39 46](https://cloud.githubusercontent.com/assets/8658164/14264216/d5d23770-fa8c-11e5-85e3-7d8d8f6a05ed.png)

For comparison, here's the call to action in the Android app when you don't have any blogs:

![2016-04-04 21 43 13](https://cloud.githubusercontent.com/assets/8658164/14264234/e4a64372-fa8c-11e5-93ae-974241f1fe0f.png)

**Comment by aerych** [comment]
Drake!! 
WPiOS needs it some Drake.

**Comment by hoverduck** [comment]
Confirmed this is still an issue with v6.6, although now the editor redirects to the general login screen, not specifically the self-hosted one

**Comment by koke** [comment]
> Create a new WordPress.com account (or use an existing one) and delete all your blogs

Alternatively, you can sign up for just an account at https://wordpress.com/start/account/user

**Comment by elibud** [comment]
@frosty had already taken care of this one, the UI will be updated a tiny bit once https://github.com/wordpress-mobile/WordPress-Shared-iOS/pull/118 is approved.

**Comment by elibud** [comment]
![simulator screen shot mar 23 2017 10 18 11](https://cloud.githubusercontent.com/assets/5558824/24252533/7b9499c4-0fbc-11e7-818e-18a2ecce176d.png)
