### ISSUE TITLE
Theme Search: Empty Screen After Searching and then Navigating Away and Back

### ISSUE THREAD

**Issue by kevmarsden** [wordpress-mobile/WordPress-iOS#4677]
The screen is empty after searching for a theme and then navigate away from and then back to the My Sites area.  

To recreate follow these steps:
1. Navigate to **My Sites** > **Themes**
2. Touch the search icon
3. Collapse the keyboard
4. Touch **Reader**, **Me**, or **Notifications** icons
5. Touch the **My Sites** icon again

Here's a screenshot of the screen after returning to **My Sites**:

![img_0072](https://cloud.githubusercontent.com/assets/2282189/12315703/fe6438cc-ba32-11e5-816a-48bdc8cd1f30.png)

Tested on an iPad Mini MD528LL/A 
App Version: 5.9.0.20160113

**Comment by sendhil** [comment]
cc @alexcurylo

**Comment by frosty** [comment]
Fwiw, this looks to only be an issue with 5.9 (not develop).

**Comment by alexcurylo** [comment]
This and many other problems were resolved in #4623 by adopting WPSearchController. When we can require 9.1, [UISearchContainerViewController](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UISearchContainerViewController_class/index.html) addresses many of the issues with replacing it.

**Comment by frosty** [comment]
Closing this issue as it seems to have been resolved.
