### ISSUE TITLE
Themes: Closing the customizer can result in the Calypso Reader appearing unexpectedly

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4679]
If you open a theme details page, you can then open the customizer. Closing the customizer from there brings you back to the Reader instead of the theme search.

Steps to reproduce:
1. From My Sites, tap a site.
2. Tap Themes.
3. You see the current theme info. Tap Details.
4. Tap Customize. (Near the bottom of the details screen in phone portrait mode, or top right in landscape mode)
5. Customizer loads. Tap X in upper left.
6. You are now looking at the Reader inside the theme details flow.

Raised by Adam during beta testing on iPhone 5 and confirmed on iPhone 6, beta v. 5.9.0.20161113.

**Comment by aheckler** [comment]
@rachelmcr:

> Raised by Adam during beta testing on iPhone 5

I'm actually using a 6. Do I have some info wrong somewhere? HockeyApp screwup?

**Comment by rachelmcr** [comment]
Oof, I think that was a brain glitch on my part. Sorry!
