### ISSUE TITLE
Theme Search: Extra padding above search bar after changing device orientation

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4682]
After changing from landscape to portrait orientation during a theme search, I noticed that extra padding was added to the top of the app:

Beginning search (before rotating):
![2016-01-14 00 23 07](https://cloud.githubusercontent.com/assets/8658164/12333148/665bfd90-baea-11e5-8414-1478533f2fbe.png)

Landscape:
![2016-01-14 00 23 09](https://cloud.githubusercontent.com/assets/8658164/12333149/665c3f26-baea-11e5-9b91-9dfe394e651a.png)

Portrait again (extra padding appears):
![2016-01-14 00 23 12](https://cloud.githubusercontent.com/assets/8658164/12333147/665b1768-baea-11e5-8a15-409c2344c431.png)

Tested on iPhone 6, iOS 9.2, app beta v. 5.9.0.20160113

**Comment by alexcurylo** [comment]
Thanks Rachel! This was addressed in #4623 after being noted during review #4581 so it'll be sorted next cycle.

**Comment by rachelmcr** [comment]
Aha, thanks for the update!
