### ISSUE TITLE
Settings: Discussion settings > Paging is missing the first/last page setting

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4684]
The paging settings in Calypso include the option to choose between showing the first or last page of comments by default:

<img width="688" alt="screen shot 2016-01-14 at 7 08 21 pm" src="https://cloud.githubusercontent.com/assets/8658164/12334522/5c39ab3e-baf2-11e5-98d3-451e21d7c6c7.png">

The app's discussion settings can turn paging on/off and choose the number of comments per page, but it's missing that "first"/"last" setting:

![2016-01-14 19 06 30](https://cloud.githubusercontent.com/assets/8658164/12334554/7ca1b51a-baf2-11e5-9d76-7f919c38ad07.png)

Tested on iPhone 6, iOS 9.2, app beta v. 5.9.0.20160113.

cc: @jleandroperez

**Comment by jleandroperez** [comment]
(Sorry about the late reply!). Thanks Rachel, we'll add the missing setting!
