### ISSUE TITLE
Remove unused image assets.

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#4700]
This week I've been working on replacing the existing icons in the app with <a href="https://github.com/Automattic/wp-calypso/blob/a7478174b0441760c332fcb4b8c454f5b8d73dfc/docs/icons.md">Gridicons</a>. In order to do this, I've audited the assets in  `AppImages.xcassets` to discover where in the code each image is currently being used.

The following assets appear to be unused and can be safely deleted.

- action-icon-followed
- action-icon-replied
- action-icon-success
- blueArrow (part of EGORefreshTableHeaderView, which seems unused)
- date_picker_selected
- date_picker_unselected
- default-identicon
- doneButton
- icon-check-small-blue
- icon-check-small-white
- icon-check
- icon-left-chevron
- icon-media-edit-grab
- icon-media-multiselect-deselect
- icon-reader-visit-highlight
- icon-reader-visit
- icon-reader-x-post
- icon-themes-sort
- icon-toolbar-share
- icon-whats-new
- keyboardButton
- keyboardClose
- logo_wpcom
- media_checkbox_empty
- media_checkbox_filled
- media_image
- movie
- NNGPlusActivity
- NNInstapaperActivity
- NNPocketActivity
- NNReadabilityActivity
- note_header_shadow
- notifications-more
- reader-postaction-comment-active
- reader-postaction-comment-blue
- reader-postaction-comment
- reader-postaction-like-active
- reader-postaction-like-blue
- reader-postaction-like
- reader-postaction-reblog-active
- reader-postaction-reblog-blue
- reader-postaction-reblog-done
- reader-postaction-reblog
- reader-postaction-tag
- redoDisabled
- Safari
- sync
- transparent-point
- ui-line-dark
- ui-line
- UIButtonBarTrash
- undoDisabled
- uploading_spin_blue
- uploading_spin_red
- video_play
- welcome_bg
- welcome_button_bg_full_highlighted
- welcome_button_bg_full
- welcome_button_bg
- wp_vid_placeholder

These assets have generic names, which made it difficult for me to determine whether they are being used or not. I *don't believe* that they are, however.

- approve
- attachment
- autosave
- background
- blockquote
- bold
- down
- help
- italic
- left
- link
- list
- lock
- next
- photos
- preview
- read
- redo
- right
- settings
- stats
- unapprove
- undo
- up
- write

If anyone has any suggestions on how to thoroughly search for the generically-named images, or knows of any reason why we might need to keep some of the images I believe are being unused, please let me know.

**Comment by aerych** [comment]
Bah! Unintentionally closed this.  Mea culpa
