### ISSUE TITLE
Today widget needs additional layout fine-tuning

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4707]
Before PR #4686 was merged there were some issues discovered with the alignment and top/bottom spacing of the widget. Spend some time and see if that layout glitchiness can be fixed. For details regarding the glitches, review the mentioned PR.

**Comment by kwonye** [comment]
Also on iOS 10, the label height does not seem to respect the label text height

![simulator screen shot sep 30 2016 2 52 18 pm](https://cloud.githubusercontent.com/assets/1158819/19008093/bd04dbbc-871d-11e6-8916-2b510c8954b7.png)
