### ISSUE TITLE
Reader Comments: Glitching text layout in certain cells.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4710]
Title has it .

**Comment by aerych** [comment]
Renamed the title as this was *not* due to the refactor for 6.0, and is reproducible in version 5.8. 

As far as I can see only a single comment on a certain private blog triggers this but it does so consistently. The cell is sizing correctly, but the text is not properly rendered to its layer, almost like the layer was not correctly size when the text was rendered.  
This might be a won't-fix as we very badly want to switch to TextKit for our text rendering, and doing so would most likely fix this issue.

**Comment by rachelmcr** [comment]
If it's limited so far to a single case, and would most likely be fixed by switching to TextKit for text rendering, I agree with the idea of a won't-fix. (We could always reopen if we uncovered more cases where it happens.)

**Comment by aerych** [comment]
Let's keep this open for a bit. I'll hack on it a bit more when I have a bit of time.
