### ISSUE TITLE
Update All-time to match other modules

### ISSUE THREAD

**Issue by jancavan** [wordpress-mobile/WordPress-iOS#4716]
This is related to: https://github.com/Automattic/wp-calypso/pull/2220

The All-time module has been updated to make use of the same styling as the rest of the tab modules. Part of the reason for this change was also because All-time has been moved to the bottom of the page so it doesn't really need additional custom styling to make it slightly prominent so this needs to be updated on iOS as well:

1)
**Currently on the iPhone:**
![all-time-ios](https://cloud.githubusercontent.com/assets/4924246/12469376/258d75cc-bfa0-11e5-9d0a-5560ce9bc0bf.jpg)

**On Calypso:**
![screenshot 2016-01-20 18 01 11](https://cloud.githubusercontent.com/assets/4924246/12469354/f9459594-bf9f-11e5-9a04-0df508363955.png)

2)
**Currently on the iPad / wider screens:**
![screenshot 2016-01-20 18 04 38](https://cloud.githubusercontent.com/assets/4924246/12469418/7143785e-bfa0-11e5-91f9-b6a5ce626988.png)

**On Calypso wider viewports:**
![screenshot 2016-01-20 18 06 45](https://cloud.githubusercontent.com/assets/4924246/12469442/9bb221ee-bfa0-11e5-8fa6-23c385f297fd.png)

For item 2, we basically just need the borders between each data set to go all the way from top to bottom.

/cc @astralbodies

**Comment by astralbodies** [comment]
Moving this issue over to the stats repo - https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/378
