### ISSUE TITLE
Comments: Make views opaque to improve scrolling

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4725]
While doing some testing in the comments list I noticed a slight stutter.  It seems we have a fair amount of transparencies in the comment list according to the blended layers tool.  Let's make these opaque and try to get scrolling a bit smoother. 
![simulator screen shot jan 22 2016 10 21 37 am](https://cloud.githubusercontent.com/assets/1435271/12516288/4fb8d94c-c0f2-11e5-974f-7be44cc4e013.png)

**Comment by diegoreymendez** [comment]
@jleandroperez - We may need to update the 6.0 tag.

**Comment by astralbodies** [comment]
@jleandroperez I'm moving this to Someday.
