### ISSUE TITLE
Plans: Show plan details

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#4745]
Display feature details for a selected Plan

## Mockups

![plans_flow_i2](https://cloud.githubusercontent.com/assets/4780/12746346/21791112-c996-11e5-90c0-9d9353759f01.png)

**Comment by frosty** [comment]
Uploaded updated mockup.

**Comment by frosty** [comment]
Picking up both of these subtasks as they'll be easiest to handle together.

**Comment by koke** [comment]
Split the second task into #4799. This was fixed by #4782
