### ISSUE TITLE
Notification settings list should be ordered after priority

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#476]
Reported by @isaackeyet 

The Manage Notifications screen has on/off toggles for each type of notification, but they seem randomly placed. I propose an order based on notification significance:

1 Comments
2 Follows
3 Likes
4 Reblogs
5 Achievements

**Comment by jleandroperez** [comment]
I'm closing this since we're entirely rebuilding the Notification Settings section of the app (Ref: #3807)
