### ISSUE TITLE
Site Settings not updated after connecting to WordPress.com account.

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#4768]
Issue discovered via @aerych in https://github.com/wordpress-mobile/WordPress-iOS/pull/4767

- Start with a fresh install and sign into a self-hosted blog that is connected to Jetpack.
- Go to settings and confirm that there are options under This Device for geotagging, default post format and default category.
- Go to the Me tab and sign into the wpcom account that Jetpack is connected to.
- Switch back to the My Sites tab. It should still be showing the settings screen, however the options on the screen have not updated to reflect a site with a REST API connection. The options for default post format and default category are missing from the Writing section and the Remove Site option is still visible.
- Tap the back button to return to the site detail.
- Tap to view settings again. Everything is fixed and appears as it should.

**Comment by aerych** [comment]
Thanks for opening this one.  Here are some screen shots for posterity:

## Self-hosted (Normal)
![simulator screen shot feb 3 2016 7 40 52 pm](https://cloud.githubusercontent.com/assets/1435271/12803647/9db105fc-cab1-11e5-87f5-6206a2eab2ea.png)

## After signing into wpcom (Broken)
![simulator screen shot feb 3 2016 7 41 15 pm](https://cloud.githubusercontent.com/assets/1435271/12803651/b4135b88-cab1-11e5-95d8-319e352d75db.png)

## After refreshing (Fixed)
![simulator screen shot feb 3 2016 7 41 34 pm](https://cloud.githubusercontent.com/assets/1435271/12803653/bb164dbe-cab1-11e5-9618-e18a0b578f7a.png)

**Comment by aerych** [comment]
I can repro this one so I might as well patch it.  :)

**Comment by kurzee** [comment]
@aerych great! Tag me in the PR for it 😃
