### ISSUE TITLE
Get rid of default AFNetworking "expected status (200-299)" errors

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#480]
Reported by @koke 

By default, AFNetworking returns a generic error for non-success HTTP codes:

>Expected status code in (200-299), got 404

Which is not very user friendly. We should translate those into more human-readable errors. Maybe look at the copy for NSURL* errors

**Comment by astralbodies** [comment]
@SergioEstevao Do you think this is still an issue after the login improvements we made in Feb/Mar?

**Comment by SergioEstevao** [comment]
@astralbodies I think we sorted this kind of errors with more user friendly messages with the health check related changes.

**Comment by astralbodies** [comment]
@SergioEstevao That's what I thought too. I'm going to close this issue because of age and related improvements.
