### ISSUE TITLE
Fix deprecation warnings for Helpshift 5.3.0

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#4814]
Instructions here: https://developers.helpshift.com/ios/upgrade-4x/#api-changes

**Comment by diegoreymendez** [comment]
@kwonye - Pinging you since this is tagged 6.0.

**Comment by kwonye** [comment]
Thanks @diegoreymendez, looks like this wasn't closed correctly. All issues related to this are merged.

Closing.
