### ISSUE TITLE
Make image size settings more user friendly

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#4819]
Instead of showing pixel size on media settings what about showing something more user friendly like  Mega Pixel sizes (1MP, 2MP, 3MP...) or generic sizes like Apple does:

![img_7497](https://cloud.githubusercontent.com/assets/651601/12975093/e4d10568-d0b0-11e5-991b-d67cd28ecd2f.PNG)

**Comment by koke** [comment]
We already tried an [Optimized/Full Size setting](https://github.com/wordpress-mobile/WordPress-iOS/issues/1685). It turns out, [users wanted the selector back](https://github.com/wordpress-mobile/WordPress-iOS/pull/2585).

cc @aerych

**Comment by bummytime** [comment]
Closing this one via https://github.com/wordpress-mobile/WordPress-iOS/pull/7704
