### ISSUE TITLE
Account Settings: Validate URL provided for my site

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4821]
Provide a URL validation routine for this field:

![2016-02-11_10-11-06](https://cloud.githubusercontent.com/assets/373903/12981803/d8b1f426-d0a7-11e5-94f1-6d1b883433b7.jpg)

You could use NSURLComponents or something alike to validate the URL.

**Comment by jleandroperez** [comment]
@astralbodies this could get troublesome with the new TLD's. I'll take a peek!

**Comment by astralbodies** [comment]
@jleandroperez Dig into the Calypso web code if that feature already exists and see just how much validation is being done. Simpler the better.

**Comment by jleandroperez** [comment]
Closing this one since Calypso doesn't really validate anything (at least not, as per the current date).

Thanks!
