### ISSUE TITLE
Account Settings: Change e-mail address

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4823]
Add an option to change the user's e-mail address on this screen.

![2016-02-11_10-11-06](https://cloud.githubusercontent.com/assets/373903/12981803/d8b1f426-d0a7-11e5-94f1-6d1b883433b7.jpg)

Additional requirements:
1. Validate e-mail address so it's not possible to submit junk through to the API.
2. If the API doesn't like the e-mail address be sure to display an error.
3. E-mail address changes require validation through a link click. Requests to change address can be canceled. Example:

![2016-03-23_13-08-36](https://cloud.githubusercontent.com/assets/373903/13995728/6b24f3a6-f0f8-11e5-9e82-de28714775c5.png)

**Comment by difficultmass** [comment]
I had a little play with this to see how it might work and managed to get it to a state where the server is refusing the client application permission to change a user's e-mail address. I guess therefore that this means it'll need some adjustment within the server to support this. I'm also guessing that there isn't currently a permission that the app can request to get write-access to the user's email when they link their account to the app.

Anyway, the commit is [here](https://github.com/difficultmass/WordPress-iOS/commit/cf51734200692219a0a47547fe3275160488d31a) and if you'd like me to create a pull request, please just let me know; if nothing else, maybe it'll save you some time at some point in the future. 

Cheers!

**Comment by astralbodies** [comment]
@difficultmass What endpoint were you hitting to change the e-mail address?

**Comment by difficultmass** [comment]
@astralbodies It's using the built in account setting update mechanic and resolves to the **https://public-api.wordpress.com/rest/v1.1/me/settings** API with a parameter dictionary that contains (in this case) :
{
    "user_email" = "new@email.address";
}

The error received is:

> Error saving account settings change Error Domain=com.wordpress.api Code=0 "Your client is not permitted to set the user's email." UserInfo={WordPressComApiErrorCodeKey=unauthorized, NSLocalizedDescription=Your client is not permitted to set the user's email.}

**Comment by astralbodies** [comment]
Okay I bet this is due to restrictions in the OAuth setup for developer-generated bearer tokens. If you want to turn this into a PR I'd be more than happy to review it!

**Comment by difficultmass** [comment]
Awesome! I've updated with develop (there were a few things to fix) and re-tested as much as I can. The pull request is [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/4984).
