### ISSUE TITLE
My Sites: Clarify the offline error message when creating a new WordPress.com site

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4835]
We should clarify the message you get when you try to create a WordPress.com site while offline. Right now, you get a generic message:

> Error

![2016-02-16 14 53 51](https://cloud.githubusercontent.com/assets/8658164/13079738/9295eaf0-d4bd-11e5-8e6d-8946e00d5136.png)

For comparison, when you try to add a self-hosted site while offline, you get this error message:

> No Connection
> The internet connection appears to be offline.

![2016-02-16 14 52 15](https://cloud.githubusercontent.com/assets/8658164/13079723/8a746d56-d4bd-11e5-8887-95008ad302c8.png)

We should use the same error message (preferably the second one, since it's clearer) and the same styling in both cases.

Related issue about offline errors: https://github.com/wordpress-mobile/WordPress-iOS/issues/3546

Raised by Adam in beta testing.

**Comment by sendhil** [comment]
Woops...

**Comment by bummytime** [comment]
@rachelmcr Looks like the latest in `develop` has a standardized error screen as part of the NUX efforts. Would you still like to leave this issue open?

![2016-12-14 09 42 27](https://cloud.githubusercontent.com/assets/154014/21188875/653fddf0-c1e2-11e6-9972-27907d05b4af.png)

**Comment by rachelmcr** [comment]
The updated, standardized error screen looks good to me! I confirmed I see it in both places mentioned above (creating a WordPress.com site and adding a self-hosted site) so I'll close this issue as resolved.
