### ISSUE TITLE
Delete Site: Clarify "Delete Site" prompt in final step

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#4836]
In the current beta (v. 6.0.0.20160208), when you tap on Delete Site to delete a site, a prompt appears with this confirmation message:

>Delete Site
>Enter the primary domain to confirm
>thesitebeingdeleted.wordpress.com

The term "primary domain" can be confusing, especially if the site never had a custom domain on it (so the concept of a "primary" domain isn't relevant or familiar to the user). In Calypso, the confirmation prompt uses this language:

>Confirm Delete Site
>Please type in thesitebeingdeleted.wordpress.com in the field below to confirm. Your site will then be gone forever.

![screen shot 2016-02-16 at 3 16 27 pm](https://cloud.githubusercontent.com/assets/8658164/13080370/48c744c0-d4c0-11e5-9d57-6862d33580d9.png)

Could we copy that language in the app? (We could shorten it to just the first sentence if the whole message is too long.)

cc @alexcurylo

**Comment by alexcurylo** [comment]
Sorted for next build, thanks @rachelmcr!
