### ISSUE TITLE
Errors connecting to self-hosted multi-site authenticated by Active Directory

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#484]
Reported by @roundhill 

There's been a few reports of the app not allowing a user to use one username with multiple sites on a WP multi-site install.

I don't have a MU site so couldn't try to reproduce.
## 

Update: The issue is that the MU site utilizes Active Directory to authorize users.

**Comment by jleandroperez** [comment]
Using MU setup on my end. Can't repro. Please, feel free to reopen if needed.

Thanks!
