### ISSUE TITLE
Notification dot needs to be updated to match new tab bar design.

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#4845]
When the tab bar was updated with gridicons and the labels were removed, I don't think the notification dot was updated to match. Currently it sits a bit high, and looks small in proportion to the dot. I think we should aim to match the design of the notification dot in Calypso:

<img src="https://cloud.githubusercontent.com/assets/1396552/13125586/60249b5c-d594-11e5-8347-3f44f333222c.png" width="59" height="55">

Before & After:

![before-after](https://cloud.githubusercontent.com/assets/1396552/13125588/62589338-d594-11e5-9d18-8fa365a8b0e9.png)

The dot is 14px, including a 2px white border (10px not counting the border). The dot fill is `jazzyOrange`. Here is how it sits in relation to `icon-tab-notifications`:

![measure](https://cloud.githubusercontent.com/assets/1396552/13125574/4c92e940-d594-11e5-9b7d-0ad07911203b.png)

Thanks to @rickybanister for reporting this issue.

**Comment by rickybanister** [comment]
What is that funky artifacting surrounding the old dot?

**Comment by mattmiklic** [comment]
Good question -- it looks like the white outline is being painted on top of the orange dot, but we're still seeing some orange subpixels peeking out around the edges. Maybe a developer can shed some light into why that's happening and how we can fix it.

**Comment by drw158** [comment]
I think the dot could probably move to the right a little bit on both platforms.

**Comment by mattmiklic** [comment]
Made a quick comparison of the design shown above (with the dot inset to the right 1px) with 2px–5px. @drw158 do you have a favorite? I think 2 or 3 could work; 2 seems slightly better to me but it's subjective.

![bells](https://cloud.githubusercontent.com/assets/1396552/13608186/a6e34808-e521-11e5-9144-14f09c6ca8ce.png)

**Comment by drw158** [comment]
Yep, it's subjective, but I agree that 2 and 3 feel the best, imo.

**Comment by alexcurylo** [comment]
@mattmiklic The funky artifacting is because the image is masking an orange background via corner radius. Drawing a circle shape directly would eliminate that no doubt; I'll take a stab at it.

**Comment by mattmiklic** [comment]
> The funky artifacting is because the image is masking an orange background via corner radius. Drawing a circle shape directly would eliminate that no doubt; I'll take a stab at it.

Awesome! :+1:
