### ISSUE TITLE
Photos not added to posts as media attachments?

### ISSUE THREAD

**Issue by dlnorman** [wordpress-mobile/WordPress-iOS#4855]
After the last iOS app update, it looks like photos uploaded with posts created in the iOS app do not get attached as media to the published post. They do get added to the media library, and the image is published as expected, but the media item is not connected to the post as seen in the Media item's "Uploaded to:" field (it's blank for media items uploaded from the app on my phone, but if I add it through the web interface, it's properly associated with a blog post)

**Comment by rachelmcr** [comment]
Thanks for the report! We have had a couple reports of this over time and are tracking it in this open issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/1402

I'm going to close this issue and move your comments there. If you can add any details about your site (what version of WordPress you have on your site, any plugins active there, etc.) that might help our investigation.
