### ISSUE TITLE
Crash when adding media that's not photo/video

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#4857]
It seems to be caused because we're passing a `nil` filename to `-[MediaService urlForMediaWithFilename:andExtension:]`

To reproduce:
- Drag an audio file to your Photos library on Mac
- Wait for it to sync to your iPhone
- Open the editor, add media, and try to add the audio

Other issues that I found while testing this:

- When it was syncing, a photo was already available in the picker but `PHAssetResource.assetResourcesForAsset(_)` was returning an empty array. The photo was "added" to the editor but all you see is an empty square.
- New photos don't appear on the picker until I open the Photos app. Not sure if this has to be like this, or we're not using the Photos framework correctly.

From crashlytics: http://crashes.to/s/c932161db72
cc @SergioEstevao

**Comment by koke** [comment]
On top of that, you can also drag PDFs to your Photos library on Mac, and they'll be available with an empty resource array (also crashing)

**Comment by koke** [comment]
Possible fix: https://gist.github.com/koke/7bf4898eba625109136e

**Comment by SergioEstevao** [comment]
@koke I think I will change the WPMediaPicker to not even show the assets on the picker.

Regarding the new photos issues, are you referring to photos you take with your camera? or photos that are synced from a iCloud Photo album?

**Comment by koke** [comment]
Sorry, I meant synced photos. I imported them on my mac and they didn't appear on the iPhone until I launched Photos

**Comment by SergioEstevao** [comment]
@koke You connect a cable to sync? or just using iCloud?

**Comment by SergioEstevao** [comment]
@koke can you test doing the same add try to use another app media picker (for example Slack) and see if they show up?

**Comment by koke** [comment]
> can you test doing the same add try to use another app media picker

Interesting, I tried both Slack and Messages and it didn't sync. Then I tried the media picker in WhatsApp and it worked.
