### ISSUE TITLE
Gravatars caching oddly in Notifications

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4858]
Scrolling around in the notifications screen in develop I'm noticing that the gravatars aren't being cached properly. Table view cell reuse seems to be not working right and gravatars from other rows end up showing on the wrong rows. Here's a video to demonstrate:

https://cloudup.com/cT53tcP9bTG
I keep scrolling back up to the top to show how where my face originally was there it gets swapped out with other gravatars depending on how far I scroll down.

cc: @jleandroperez

**Comment by jleandroperez** [comment]
Thanks sir! Will debug this one!
