### ISSUE TITLE
Build fails with spaces in project path

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#486]
If the local development path contains spaces, the build fails due to the generation of the WP.com credentials file. Fix for the build script is attached

**Comment by rachelmcr** [comment]
@sendhil this is still listed in the 4.6 milestone. Should we move it to Pending/Someday?

**Comment by sendhil** [comment]
@rachelmcr yea - lets move it.

**Comment by kurzee** [comment]
Closing, unless this is still a thing @sendhil
