### ISSUE TITLE
3D Touch with multiple sites

### ISSUE THREAD

**Issue by chantalcoolsma** [wordpress-mobile/WordPress-iOS#4865]
Just noticed WordPress for iOS has 3D Touch. Nice. However it only shows actions for the first site. I use the app for multiple wordpress.com, self hosted and Rosetta sites. I can't find settings for those 3D Touch actions.

Any idea?

**Comment by sendhil** [comment]
@kwonye - ?

**Comment by kwonye** [comment]
Thanks @chantalcoolsma for the nice words!

The 3D Touch actions are only available for your last selected site. Everytime you go into a different site in the Site picker, the 3d touch shortcuts change to reflect that.

**Comment by chantalcoolsma** [comment]
@kwonye Thanks. Didn't know that.
