### ISSUE TITLE
WordPressShare: Shared Metadata

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#4873]
- [x] Share OAuth Token upon login / launch
- [x] Share Primary Site Name / SiteID
- [x] Listen to Account Changes and update shared metadata
- [x] Remove credentials/configuration upon logout

Ref. #2231

**Comment by astralbodies** [comment]
I have the OAuth bearer token, primary site ID and site name being persisted. Still need to get the account change thing to work and to handle when a primary site isn't available.

**Comment by astralbodies** [comment]
Done
