### ISSUE TITLE
Reader: Crash when tapping a comment avatar when the author's url is nil

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4878]
To reproduce: 
- Open the reader and view a post with several comments. 
- Tap on the author's avatar in one of the comments. 
- If the author's URL is nil the app will crash. 

We need to be checking for a nil URL before attempting to show the WPWebViewController.

**Comment by rachelmcr** [comment]
This was fixed in #4960. Closing.
