### ISSUE TITLE
Crash on site settings: missing language_id

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#4886]
When there's a refresh of `BlogSettings` in my self hosted site, core data fails to validate because `language_id` is `nil`.

This is also a problem because the settings methods in `BlogService` call `-[NSManagedObjectContext save:]` directly and don't do any error handling. So it doesn't really save, and other than printing an error to the console, there's no error handling. Then, when any other operation (like syncing posts) tries to save, Core Data still fails to validate and it crashes.

I can reproduce on a few test blogs on `develop` (not on internal)
To reproduce:
- Add a self hosted blog
- Refresh posts and make sure it works
- Go to site settings and make sure they refresh
- Go back to posts and refresh them
- :boom: 

cc @jleandroperez

**Comment by koke** [comment]
Dupe of #4881

**Comment by jleandroperez** [comment]
@koke thanks for catching this!!
