### ISSUE TITLE
My Profile and Account Settings show wrong value after change

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#4888]
We've discussed this problem before but I don't think there was an issue created for it.

To reproduce:
- Go to Me
- Go to My Profile or Account Settings
- Tap on one of the fields
- Edit it
- Go back

The table shows the old value. If you change it again, the table shows the previous change.

There's a race condition: when the `SettingsTextViewController` is dismissed, the value changes. The service applies the change locally and saves immediately, then queues a change request. When Profile/Settings appears again it triggers a remote refresh, which brings back the old value. When the change request completes, it doesn't update the local value. 

cc @jleandroperez

**Comment by jleandroperez** [comment]
Thanks for filing this @koke. It's a pity we couldn't hang out @Mobile Meetup, this needs a networking layer solution, definitely.
