### ISSUE TITLE
Retire Open Sans in favor of system fonts.

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#4895]
We're about ready to make the change from Open Sans to system fonts for UI text in Calypso. Opening this issue to start thinking through what we'll need to change on iOS to match.

I think that everywhere we're using Open Sans, we should be able to simply use SF at the same size and weight. No change should be made to the text that's set in Merriweather, our serif typeface.

Ref: https://github.com/Automattic/wp-calypso/pull/3016

**Comment by koke** [comment]
Once #4931 is merged, we should completely remove Open Sans from WordPressShared. Since it won't be used anymore, there's no point in including the font files in the app.
