### ISSUE TITLE
Editor: Problems loading images in the editor when a site has enabled basic http auth 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4901]
As reported in the forums: https://ios.forums.wordpress.org/topic/upload-images-failed?replies=24#post-14483

> No pics gets loaded in previous posts and the visual editor loads to full and then nothing happens
> Yes I'm using basic http auth, as I've always done, nothing has changed there 😀
...and yes the loading works if I disable it... 

Let's investigate and see if we can reproduce and fix.

**Comment by neuhaus** [comment]
I'm also affected by this issue.

When connecting to the password protected blog on my host I get a popup asking for the HTTP auth credentials and I can post articles.

However when I try to add a picture to the article, I get the error message "Request-Body ausgelastet" (my iOS is set to German), and in the Apache access.log I see that the client sends the POST request without auth headers and gets a 401 response from the website. It does NOT try to repeat the request with the correct known credentials.

**Comment by neuhaus** [comment]
This issue is still present in the 6.5.0 beta

A POST request is sent to xmlrpc.php with missing credentials (despite other requests with correct credentials before that) and the server responds with a 401 unauthorized response. There is no new request by the client after that.

**Comment by astralbodies** [comment]
@SergioEstevao Do you have time to investigate this one?

**Comment by neuhaus** [comment]
I just tested it with the latest Wordpress 6.5.0.3 (in TestFlight) and it fixes this issue.
Great job, thanks!
🍰

**Comment by SergioEstevao** [comment]
@neuhaus we didn't do any specific to fix the issue, however there where some changes on the way uploads are done that could have indirectly influenced your issue. If you detect problems in the future please contact us again.

**Comment by neuhaus** [comment]
OK for now I think you can close this bug.
