### ISSUE TITLE
Edits made offline to a post started online are lost upon reconnect

### ISSUE THREAD

**Issue by ned21** [wordpress-mobile/WordPress-iOS#4904]
Steps to reproduce:

1. While online start a new post. Insert some text and then exit the editor, saving the draft.
2. Put the iOS device into airplane mode.
3. Touch "Edit" next to the draft and make some changes to the original text and add new text. 
4. Exit the editor and select "update draft"
5. Without leaving the app, take the iOS device out of airplane mode.
6. Ensure you are viewing "Drafts" and pull down to refresh the post listings.
7. Touch "Edit" next to the draft, changes made while in airplane mode have been lost, replaced with the content from the server.

Wordpress App version: 5.9.1
iOS version: 9.2.1
Wordpress blog: self-hosted, 4.4.2

**Comment by astralbodies** [comment]
Thanks for the heads up @ned21 - I'm going to see if I can get this on escalated.

**Comment by diegoreymendez** [comment]
Fixed.
