### ISSUE TITLE
Add ability to edit excerpt

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#491]
Reported by user

Currently there's no way to edit the custom excerpt, which means if you want to use one (and we are for the optimal SEO, right?), you have to save as draft, upload to the web, adjust the date (see [trac ticket](http://ios.trac.wordpress.org/ticket/1651)) and then edit the excerpt as desired.

**Comment by michaelnordmeyer** [comment]
Why is this closed? Does nobody use excerpts? I'm definitely missing them.

**Comment by kurzee** [comment]
Hi @michaelnordmeyer! I'm reopening this one was we might have an opportunity coming up to implement support for excerpts on iOS. Thanks for commenting!

**Comment by kurzee** [comment]
@michaelnordmeyer good news! We've merged in the Excerpts suppport in #6458, courtesy of @elibud. This will land in version 7.0, probably a couple weeks.
