### ISSUE TITLE
Accounts: Jetpack accounts not being cleaned up?

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4915]
I noticed a situation where even though I was supposedly logged out of the app (no default wpcom account and no blogs) a call to `AccountService numberOfAccounts` was not returning zero. It turns out there was still a WPAccount lingering in core data.  This account in question is used to connect a self-hosted site to Jetpack. 

Theory: I was already logged into wpcom when I added a self-hosted blog that was connected to Jetpack via a different wpcom account. Then I signed into that wpcom account when prompted to view stats for the self-hosted blog.  Later I removed the self-hosted blog and then signed out of wpcom.  The result is the account used for Jetpack stats was orphaned. 
Needs testing to confirm.

**Comment by koke** [comment]
I believe this will be fixed as part of #5334
