### ISSUE TITLE
Stats: Jetpack connection screen can have wonky layout on the iPad.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#4929]
Title has it. See attached. Reproducible by rotating the app while the keyboard is up.  Tested on an iPad Mini

![img_0005](https://cloud.githubusercontent.com/assets/1435271/13616107/0ebba634-e53e-11e5-9f75-6855317aca7e.PNG)

![img_0006](https://cloud.githubusercontent.com/assets/1435271/13616112/127e8426-e53e-11e5-90e7-e2c66da89f40.PNG)

![img_0007](https://cloud.githubusercontent.com/assets/1435271/13616117/165ac0fa-e53e-11e5-956c-2d5d2129a134.PNG)

**Comment by amigoni** [comment]
Been working on this issue for a couple of days. I refactored the screen using Storyboard and Autolayout  to make it "future proof". Was a bit challenging but all seems to be working perfectly.

**Comment by bummytime** [comment]
So testing this out more on the iPad Mini, it looks like the layout issues are mostly resolved on 10.0, 10.1, and 10.2 sans the Jetpack logo issue noted above. I will post a PR to address that.

**Comment by bummytime** [comment]
I did catch another issue when rotating the device with the soft keyboard up and then dismissing it:

<img width="1024" alt="screen shot 2017-01-09 at 10 15 12 am" src="https://cloud.githubusercontent.com/assets/154014/21773469/d89e5930-d654-11e6-86f6-1006f2d419f9.png">

The login form can be pulled down below the bottom screen edge. Doesn't happen 100% of the time, but enough to warrant a fix.

**Comment by bummytime** [comment]
Closing this in favor of #6389 — the team agreed to completely refactor this screen.
