### ISSUE TITLE
Show site name in publication notification

### ISSUE THREAD

**Issue by ryanboren** [wordpress-mobile/WordPress-iOS#4941]
After publishing, you are taken back to your calling context with a confirmation notification briefly overlaid.

Screenshot of version 6.0.0.201602259e60575 on an iPhone 6+:

![Publication notification on iPhone 6 plus](https://cloud.githubusercontent.com/assets/2047747/13675461/5701c652-e6a7-11e5-8ca5-1ac5a314fef9.PNG)

I have multiple sites. I'm anxious about publishing to the wrong site. I don't want to misdirect a private post to a public blog or have to clean up mis-posts to social media sites hooked up via Publicize.

The pencil icon can launch you into the editor from any calling context. From the reader, from the site list, or even from the posts list for a site other than the one you just posted to. Returning to these contexts after publishing casts doubt on the publication destination and increases anxiety.

Putting the target site name in the publication notification would save me some post publish anxiety and avoid the anxiety flow of navigating to the target site to verify the post went where intended.

**Comment by rachelmcr** [comment]
This issue is resolved in https://github.com/wordpress-mobile/WordPress-iOS/pull/6232 (which adds a post-post screen that includes the site name).
