### ISSUE TITLE
3D Touch shortcuts crash on an account with no blogs

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#4954]
To reproduce:

1. Sign in to the app with a WordPress.com account that has no blogs
2. Go back to the home screen, tap to show 3D Touch shortcuts, select anything other than Notifications
3. :bomb: 

I don't have a 3D Touch enabled phone but @diegoreymendez tested it
> New post crashes the app for me
> Same for everything except notifications

I discovered this while writing #4953, in this piece of code:

```swift
    public func loggedInShortcutArray() -> [UIApplicationShortcutItem] {
        var defaultBlogName: String?
        if blogService.blogCountForAllAccounts() > 1 {
            defaultBlogName = blogService.lastUsedOrFirstBlog()?.settings.name
        }
```

As I had to deal with the possibility of `lastUsedOrFirstBlog` being optional, I noticed that this might still be called if logged in, but with a blog count of 0. In that case, we still add blog-related shortcuts that won't work.

cc @kwonye

**Comment by kwonye** [comment]
Thanks @koke! That's a test case I didn't forsee. I'll make the changes.

**Comment by sendhil** [comment]
@kwonye I'm taking care of this and will cherry-pick your fixes from `release/5.9.1` into `release/6.1`

**Comment by kwonye** [comment]
@sendhil thanks but there is additional code that has to check for no blogs. (Just did it) PR upcoming.

**Comment by sendhil** [comment]
@kwonye Ahhh.  Can you submit it to 6.0 as well.
