### ISSUE TITLE
WPWebViewController not following 301 redirects properly

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#4983]
### Expected behavior
When visiting a url like https://astralbodiesnet.files.wordpress.com/2014/02/2014-02-10_12-44-50.png it should just load.

### Actual behavior
The web view is being redirected to wordpress.com/wp-login.php with a 403 error.

### Steps to reproduce the behavior
1. Log into the app and view stats for a frequently viewed site.
2. Find the clicks section and look for `WordPress.com Media`.
3. Expand that section and try tapping on any file URL.
4. User is presented with a 403 Forbidden Screen.

##### Tested on iPhone 6s Plus & Simulator, iOS 9.2.1

cc: @jleandroperez

**Comment by jerrysarcastic** [comment]
I had a user report that they are still having this issue, and see a 403 error when clicking on their media URL in stats.  I also tested this and confirmed I am seeing the same issue, using the steps above.  iOS 9.3.1/WP 6.1

Reported in: https://automattic.helpshift.com/admin/issue/101971/

**Comment by astralbodies** [comment]
@jerrysarcastic can you try with the latest internal beta? It looks like this fix is in 6.2.

**Comment by jleandroperez** [comment]
Stepping by to confirm that indeed, the fix is in 6.2.
