### ISSUE TITLE
Notifications: after clicking Unread tab in notifications view, can't access any other notifications

### ISSUE THREAD

**Issue by lancewillett** [wordpress-mobile/WordPress-iOS#4986]
### Expected behavior
I'd expect to be able to switch back to All, Comments, Likes, etc — via the tabs at the top of notifications view.

### Actual behavior
After clicking the Unread tab once, I lose the tabs and can't see anything besides "No unread notifications" warning.
![img_4501](https://cloud.githubusercontent.com/assets/66797/13937050/6ea56c6a-ef7f-11e5-9b90-c7e7b859a4b6.PNG)

### Steps to reproduce the behavior
Update to 6.1 beta, and click post a new comment on a test blog with a different user. Open iOS app, and click the notifications icon in bottom right (should show an orange dot).

Then, click the Unread tab in notifications view.

##### Tested on [device], iOS [version]
iPhone 6+, iOS 9.2.1

WordPress app version 6.1.0.20160318

##### Misc

Note: I also sent in a lookback with a video.

**Comment by lancewillett** [comment]
By force-quitting the app (swipe up in the app switcher in iOS) I was able to re-open the app and see the notifications tabs again.

**Comment by rachelmcr** [comment]
I tested and confirmed this issue on my iPhone 6, iOS 9.2.1, app v. 6.1.0.20160318.

**Comment by frosty** [comment]
I've just replicated this as well, but with the Follows tab. It looks like it happens on any tab where you have no results (I have Unread notifications, but I don't have any Follows).
