### ISSUE TITLE
xcodebuild not showing tests as they run

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#5004]
It seems something changed in Xcode 7.3 as `xcodebuild` is not showing which tests are being executed, only an uninformative TESTS SUCCEEDED/FAILED at the end.

I've found a [related radar](http://www.openradar.me/24184959) although it only mentions UI tests.

I've tried running the test suite in the stats repo and xcodebuild correctly shows all the test cases, so there must be something with our project.

**Comment by koke** [comment]
Filed rdar://25409441

**Comment by steipete** [comment]
Wanted to dupe but it's not on openradar. (http://www.quickradar.com/ is amazing and makes this easy!)

**Comment by koke** [comment]
http://openradar.appspot.com/25409441 :smile:

**Comment by dflems** [comment]
@steipete @koke: I'm having the same issue. The tests are running but the output on a per-test level is missing when using `xcodebuild`. Have either of you found a solution or a minimal way to reproduce this issue?

**Comment by koke** [comment]
I just noticed that this seemed to have fixed itself on Travis builds a couple weeks ago, so I did a little bit of `git bisect`:

```
51a07be525f2623253c87cce1d8423aa8bf76096 is the first bad commit
commit 51a07be525f2623253c87cce1d8423aa8bf76096
Author: Jorge Bernal <jbernal@gmail.com>
Date:   Thu Apr 7 17:18:35 2016 +0200

    Update Nimble to 4.0.0
```

@steipete @dflems do any of you use Nimble?

**Comment by steipete** [comment]
No - we've seen this in combination with xctool, and since we dropped that and went back to xcpretty for our CI things are better than ever. We're using the set of `XCT*` with some custom extensions, mostly so we have an easier time starting individual tests without the need of running the whole test suite at least once.
