### ISSUE TITLE
Me tab shows e-mail on initial sign-in then .com username after relaunch

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5005]
### Expected behavior
When signing in with an e-mail address instead of a username, the username should eventually replace the header on the Me tab when sync completes.

### Actual behavior
The e-mail address of the user remains on the screen until the app is force-quit and restarted.

### Steps to reproduce the behavior
1. Sign in with a WordPress.com account using the e-mail address as the login.
2. View the Me tab. You'll see the e-mail address.
3. Force-quit the app. Relaunch.
4. View the Me tab. The WordPress.com username is now showing.

![img_9605](https://cloud.githubusercontent.com/assets/373903/13985130/e68f174a-f0c8-11e5-91f3-5d0fd322d358.png)

![img_9606](https://cloud.githubusercontent.com/assets/373903/13985137/f316e9ca-f0c8-11e5-87a8-9985cdf4513b.png)

**Comment by frosty** [comment]
@astralbodies Could you confirm if this is still an issue for you? I just followed your steps (logging in with an email address) and I see the username when I visit the Me tab. Thanks!

**Comment by astralbodies** [comment]
I think this may have been resolved with @aerych's login flow changes. I'll close it for now! 👍

**Comment by aerych** [comment]
> I think this may have been resolved with @aerych's login flow changes.

The new flow waits until blog and account information have been synced before its complete.  The old flow would asynchronously sync blog and account info, completing early, hence the bug.  
Its probably not worth it to patch the old login controller at this point.
