### ISSUE TITLE
Post Slug Editing

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#501]
I think it'd be a good idea to let the author pick his own slug when posting (assuming permalinks is switched on). I don't like the automatic way.

**Comment by rachelmcr** [comment]
+1 to slug editing. This was recently noted by @m.

Here's the current slug editing option in the Calypso editor, after saving a draft:

![screen shot 2017-04-03 at 12 24 16 pm](https://cloud.githubusercontent.com/assets/8658164/24607204/7f770694-1868-11e7-8d29-81df6de0f12f.png)
![screen shot 2017-04-03 at 12 24 24 pm](https://cloud.githubusercontent.com/assets/8658164/24607218/929471c6-1868-11e7-895b-94647bcbd5a8.png)
