### ISSUE TITLE
Site shown duplicate

### ISSUE THREAD

**Issue by chantalcoolsma** [wordpress-mobile/WordPress-iOS#5016]
When I want to switch a site on one of my iOS devices, one site is shown twice:

![img_0714](https://cloud.githubusercontent.com/assets/867632/14017637/34b40a42-f1c9-11e5-95c5-63bec957c5d1.jpg)

When I choose to edit sites, that site is only showing once:

![img_0715](https://cloud.githubusercontent.com/assets/867632/14017646/46c36980-f1c9-11e5-9158-5628f0da305e.jpg)

I checked my sites using wordpress.com, but overthere it is only listed once.

Any idea what is happening?

##### Tested on iPad mini & iPhone 6s, iOS 9.3

**Comment by chantalcoolsma** [comment]
Additional info:

When I deactivate that one site in the app and tap on "Done" one of those duplicates is still shown.

I am completely puzzled.

**Comment by astralbodies** [comment]
Did this happen only upon installing the 6.0 release?

**Comment by chantalcoolsma** [comment]
No I am seeing this for a while now.

**Comment by chantalcoolsma** [comment]
When I turn it off in the app, it is also gone from my sites on wordpress.com. Don't know if this is an issue in the app or an issue on wordpress.com.

**Comment by astralbodies** [comment]
I think its related to something funky with your Jetpack site setup possibly. If you have the time can try disconnecting from WordPress.com and logging back in?

**Comment by chantalcoolsma** [comment]
When I disconnect the site from Jetpack, only one is shown. Could it be that this is a site I added manually in the app in the past?

**Comment by chantalcoolsma** [comment]
Deleted that site from the app. Connected to Jetpack again. Now it is shown only once. Solved :-)

**Comment by astralbodies** [comment]
Woohoo - I figured it was the self-hosted site causing the dupe. @koke didn't you solve this scenario when a site transitions to Jetpack?

**Comment by chantalcoolsma** [comment]
There is no indication which one is added als self-hosted and which one connect through Jetpack.

**Comment by koke** [comment]
@astralbodies sites _should_ be de-duplicated when adding the WordPress.com account, but I've seen that fail sometimes, and I don't know why yet.
