### ISSUE TITLE
Use reachability to avoid timeouts

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#502]
Reported by @koke 

When the blog host can't be reached, some actions (like moderating comments), just lock the app for a long time until the request times out

We should use reachability features to check if the host is alive before sending requests

To reproduce, you can install and configure a local wordpress in your workstation and then change your ip

Trac thread [here](http://ios.trac.wordpress.org/ticket/567)

**Comment by koke** [comment]
Actually, I learned recently that Apple advises against this. Reachability shouldn't prevent a connection, it should be used for errors and retry when an attempt fails. Closing this for now, as the related changes are part of a larger network architecture discussion.
