### ISSUE TITLE
Autofill login: Prompt shows even when passwords are intentionally not saved in Safari

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5021]
### Expected behavior
If I have chosen not to save passwords in Safari, I would expect the prompt to not appear when I log in to the app, or to be able to permanently dismiss the prompt so it doesn't appear a second time.

### Actual behavior
If I have chosen not to save passwords in Safari, the prompt appears with a "Passwords not saved" item:

![2016-03-25 00 15 41](https://cloud.githubusercontent.com/assets/8658164/14060815/b115dc7e-f367-11e5-9c85-dba06e6f5140.png)

I can select that item and get this pre-filled in the login form:

![2016-03-25 00 16 05](https://cloud.githubusercontent.com/assets/8658164/14060816/bec82bba-f367-11e5-9846-9ca9e3e21274.png)

I can't permanently dismiss the prompt, so this appears every time I try to log in.

### Steps to reproduce the behavior

1. Open Settings > Safari > Autofill > Enable Names and Passwords if needed.
2. In Safari, log in to WordPress.com at wordpress.com/wp-login.php. When prompted to save the password, choose "Never for This Website." [Note: I haven't yet found a way to undo this selection without resetting the device, so be aware that this is a very persistent setting. Future passwords for the site will have to be entered manually in the Settings app.]
3. Open the WordPress app. Result: The item "Passwords not saved" will appear in the prompt.
4. Select the "Passwords not saved" item or tap "OK." Result: "Passwords not saved" appears in the username field, and a single character is shown in the password field.

##### Tested on iPhone 6, iOS 9.3, app beta v. 6.1.0.20160318

**Comment by kurzee** [comment]
This is tricky as the API Apple provides to grab the credentials is fairly limited. We can't check to see if any saved passwords exist without the user seeing the prompt.

Going to think about this one and see if I can come up with a way to keep the prompt from showing. Otherwise we'll have to have a button of some kind.

**Comment by rachelmcr** [comment]
I tested in another app (Pinterest) and had the same issue there. If this is an API limitation, it's probably ok to leave it as-is for v1 and consider other options to address this edge case in a future version (as discussed in https://github.com/wordpress-mobile/WordPress-iOS/pull/4916).

**Comment by kurzee** [comment]
@rachelmcr I'd agree it's OK to leave it as v1 for now. We can also revisit once @aerych pushes out the new magic links login flow, which may change things for auto-fill in general.

**Comment by kurzee** [comment]
Quick update on this. As mentioned above, reproducing this error by choosing "Never for This Website." when prompted to save the password in Safari seems to create an actual saved password entry in the keychain as "Passwords not saved" and a 1-char password.

Once a user has chosen this option, the prompt will always show, which seems like an oversight by Apple and there's nothing we can do to detect or prevent the prompt from showing in this case. We'll have to keep an eye out for a bug fix from Apple.

**Temporary Fix**
For a user to reverse their decision to "Never for This Website" remember passwords and resolve the prompt they would have to:

1. Manually enter the username and password on Safari for wordpress.com/wp-login.php
2. Hit the "Passwords" button on the tool bar.
3. Select "Save This Password".
4. Prompt will now present correctly and without the "Passwords Not Saved" entry.

_* Manually adding a password under Settings > Safari > Passwords would still show the "Passwords Not Saved" entry but would allow the user to select the manually added entry. Only the steps above seem to remove the empty entry._

@rachelmcr please note the fix above as some users may have this case occurring upon release.

**Comment by rachelmcr** [comment]
Ah, thanks for finding that temporary fix! I'll make sure Happiness Engineers are aware of it in case this comes up in support requests.
