### ISSUE TITLE
Autofill login: No autofill prompt on the Stats login screen for Jetpack sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5022]
Is it possible to get the autofill prompt on the login screen that appears in the Stats section for self-hosted Jetpack sites?
### Expected behavior

If I have a self-hosted Jetpack site in the app, and I'm not logged in to WordPress.com, I get a login screen when I try to view the site's stats. I expect an autofill login prompt on that login screen, since it's a WordPress.com login.
### Actual behavior

No autofill prompt appears. I only get this login screen:

![2016-03-26 15 49 43](https://cloud.githubusercontent.com/assets/8658164/14060930/cfc254ec-f36a-11e5-9a9c-0ab32cf54b85.png)
### Steps to reproduce the behavior
1. Open the WordPress app, disconnect from WordPress.com if needed, and add a self-hosted site with Jetpack installed.
2. Go to My Sites > select the Jetpack site > Stats

Result: A WordPress.com login screen appears but no autofill prompt appears.

**Comment by kurzee** [comment]
This would be a great addition.

**Comment by kurzee** [comment]
Holding off on this one for now.

@astralbodies any thoughts on adding the Safari AutoFill to this login?

**Comment by astralbodies** [comment]
@kurzee We could add it to this screen but it may be a bit wonky for the user. I want to say that login gets its username pre-filled based upon the .com username its connected to fetched in the blog's options. If we prepopulate the username I'd want the user to still get that hint if we show the Safari autofill so they choose the right .com account to log in with.

**Comment by kurzee** [comment]
@astralbodies one thing we can actually do with the shared credentials API is only ask for saved password for a given username. In that scenario, the prompt would never show unless the given username has a saved password to use.

**Comment by astralbodies** [comment]
@kurzee That might work then. The only complication I could see is when the login is username vs. e-mail address. The blog options should only ever have .com username but the saved credentials from Safari could be e-mail address.

**Comment by kurzee** [comment]
@astralbodies in that case only the username would be passed in and no passwords would be detected, so no prompt would show. I'll play with it a bit and see if it can be an unobtrusive addition. Unfortunately though, the shared credential functions are fairly limited.

**Comment by elibud** [comment]
I think we want to go this way here: https://github.com/wordpress-mobile/WordPress-iOS/issues/7633#issuecomment-337273030

**Comment by elibud** [comment]
@aerych is this fixed by your latest changes?

**Comment by aerych** [comment]
I think so.  #8355 switches things to use the new flow which includes support for 1password. 
I think we can close this one.
