### ISSUE TITLE
Plans: Implement full transaction processing

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#5033]
Some things that we still have to implement:

- [x] Don't allow a second purchase while there's a purchase in progress #5183
- [x] Store pending payment information on disk
- [x] Deal with non-successful transactions, including deferred

**Comment by frosty** [comment]
Moved `Figure out how to handle a purchase missing/receipt refresh` to #5035.

**Comment by frosty** [comment]
Closed by #5232.
