### ISSUE TITLE
Reader: menu item to unfollow a site says "Follow Site"

### ISSUE THREAD

**Issue by lancewillett** [wordpress-mobile/WordPress-iOS#5040]
### Expected behavior
When viewing blog posts in Reader and using the `...` menu at the top right of each post, I expect to be able to tap the dots and click "Unfollow Site" from the menu that comes up from the bottom of the app screen.

### Actual behavior
The first menu item says `Follow Site` instead of `Unfollow Site`. It's backwards... I'm already following the site!

<img src="https://cloud.githubusercontent.com/assets/66797/14083651/af722e1c-f4cb-11e5-8f1f-0e78d5b33106.jpg" width="480" />

<img src="https://cloud.githubusercontent.com/assets/66797/14083654/b39691ae-f4cb-11e5-881d-9aa69faee110.jpg" width="480" />

### Steps to reproduce the behavior
1. Log in to 6.1 iOS beta.
2. Go to Reader.
3. Click the ... menu for any post.
4. View the first link in the menu.

##### Tested on [device], iOS [version]

WPiOS 6.1 beta, iOS 9.3 (iPhone 6+)

<img src="https://cloud.githubusercontent.com/assets/66797/14083661/baef5a44-f4cb-11e5-8a16-6d65cbac5a9a.jpg" width="480" />

##### Screenshots / Notes

Mobile web (Safari on same device), Safari 9.0.3 on OS X 10.11.3 desktop, and WP Desktop app for OS X all work correctly:

<img width="487" alt="ios-iphone6plus-safari-2" src="https://cloud.githubusercontent.com/assets/66797/14083667/c4eb2cf8-f4cb-11e5-8390-4a1797bbebc6.png">

<img width="487" alt="ios-iphone6plus-safari" src="https://cloud.githubusercontent.com/assets/66797/14083670/c4ef28ee-f4cb-11e5-9a07-e598ee02fba0.png">

![safari-wpcalypso-index](https://cloud.githubusercontent.com/assets/66797/14083668/c4ec0fec-f4cb-11e5-9c33-6694c85de93e.png)

![safari-wpcalypso](https://cloud.githubusercontent.com/assets/66797/14083669/c4ee4924-f4cb-11e5-8dc5-c4371d147721.png)

![wp-desktop](https://cloud.githubusercontent.com/assets/66797/14083671/c4f02e24-f4cb-11e5-8a8a-7c62d4c41ccd.png)

**Comment by aerych** [comment]
This is looking like an API issue.  Give this a try:

- Sign in to WordPress.com in a browser and navigate to the REST API Console at: https://developer.wordpress.com/docs/api/console/
- In the console, type `/v1.1/read/following/` for the endpoint (or select it from the list) and run the query. 
- Inspect the results returned.  Notice that for each post the value of `is_following` is `true`.
- Now type `/v1.2/read/following/` for the endpoint.  This is the endpoint used by the iOS and Android apps. 
- Run the query and inspect the results. 
- Notice that for each post the value of `is_following` is `false`.  

I've pinged the reader team and we'll get it sorted.  Thanks for the heads up @lancewillett :)
