### ISSUE TITLE
NUX: Duplicate log in bug

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#5042]
As seen in https://github.com/wordpress-mobile/WordPress-iOS/issues/5023, if we ever create a bug or a case in which a user can authenticate a WP.com account while still authenticated as another account, the previous account sticks around with a strange multi-account bug. In fact, this can be repeated with multiple accounts if a bug allows it.

### Steps to reproduce the behavior
Run a branch without the fix in https://github.com/wordpress-mobile/WordPress-iOS/commit/5ecb470fc8728ce898f8af7594df67df869cc3b7, or comment the diff out to reproduce:

1. Authenticate as a WordPress.com account if needed.
2. Go to the site list and hit the **+** button to **Add a Self-Hosted Site**.
3. Upon viewing the LoginViewController you will be prompted to use your WordPress.com saved passwords. (If saved)
4. Select a saved password.
5. The form will auto-fill and auto-select the authentication method as a WP.com sign in.
6. Upon signing in, you will still be authenticated as the previous account, but both account sites will shows up under your sites list.

NOTE: See additional testing below https://github.com/wordpress-mobile/WordPress-iOS/issues/5042#issuecomment-204492230

This would need to be patched with an implementation removing any previously authenticated account. This currently happens if the user follows the usual flow of disconnecting a current account and then authenticating as a new account.

@aerych Do you think this should be patched? Or, should the current implementation remain since there is currently no intentional method for a user to authenticate twice?

**Comment by aerych** [comment]
I think its less a concern after 5ecb470 but it would be nice to make things a bit more bullet proof.

**Comment by kurzee** [comment]
Similar issue here: https://github.com/wordpress-mobile/WordPress-iOS/issues/3401

**Comment by rachelmcr** [comment]
I found a case where this is still possible:

1. Log in to the WordPress app with a WordPress.com account
2. Go to the site list and hit the + button to Add a Self-Hosted Site
3. Log in with a different WordPress.com username, password, and site URL

Result: You are logged in and the second account's sites appear in the site list (and you can manage the sites as that account) but you are also still authenticated as the previous account.

If you go to the Me tab and disconnect from WordPress.com, it only disconnects you from the first WordPress.com account. The second account's sites are still there if you log in again.

**Comment by kurzee** [comment]
@rachelmcr The fix for that one was in the 6.1 branch and not yet in develop. Are you using the develop branch or an internal build?

**Comment by rachelmcr** [comment]
I'm using the latest 6.1.0.20160331 beta, but I can also check develop. This is different from the issue in #5023 (which is fixed in this beta) in that it involves logging in manually using the self-hosted login form (whereas the previous issue with auto-fill also auto-selected the WP.com login form).

**Comment by rachelmcr** [comment]
Er, I misread your comment about develop. I am not using the develop branch; I'm using the 6.1.0.20160331 beta build.

**Comment by kurzee** [comment]
Opening a separate issue for this one.

**Comment by kurzee** [comment]
Continuing the issue here, this requires the larger refactor alluded to in https://github.com/wordpress-mobile/WordPress-iOS/pull/5044

**Comment by kurzee** [comment]
Issue is resolved in #5155
