### ISSUE TITLE
Reader: Occasionally, on the iPad the list of posts shows a post card full width.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5082]
Title has it.  There doesn't seem to be any rhyme or reason to it and its not reproducible on demand.

**Comment by kurzee** [comment]
Reproduced this issue on develop, today. Occurred while continually switching between multitasking sizes and full screen, while looking for bugs.

**Comment by aerych** [comment]
Steps to reproduce (cheers @kurzee!!)

- Delete the app, reinstall.
- Let the Reader load.
- While it’s fetching posts, move to another tab.
- Let it reader sync finish.
- Go back to the reader tab.

If that reader section/list already had cached posts, it won’t reproduce.
So you can go through the menu items and as long as it has to do a blanket fetch, leave the tab, go back

Our hypothesis of the bug:
- the cells are being dequeued as the tableView tries to estimate row height
- since the tableView is not in a window, the dequeued cells are not set with the correct trait collection for the iPad
- when the tableView is finally moved to a window the trait collection and constraints are not updated

So the root problem seems that the wrong trait collection is applied to the cell the first time its rendered, and is not updated for subsequent renders.
