### ISSUE TITLE
Themes: Current Theme header area is not localized

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5092]
In a site's Themes section, the Current Theme header area is not localized:
- The string "Current Theme" is not available in GlotPress for translation
- The translated strings for "Customize," "Details," and "Support" in GlotPress are not used in this header area in the app

### Steps to reproduce the behavior

1. Go to iOS Settings > General > Language & Region > iPhone Language > select Español (Spanish)
2. Open the WordPress app and go the My Sites tab
3. Select a site and go to Themes ("Temas" in Spanish)

Result: The strings "Current Theme," "Customize," "Details," and "Support" are all in English in the header in the Themes section.

### Screenshot

![2016-04-05 17 38 16](https://cloud.githubusercontent.com/assets/8658164/14298995/0721f616-fb56-11e5-9935-9855fd5328fe.png)

**Comment by sendhil** [comment]
Addressed in https://github.com/wordpress-mobile/WordPress-iOS/pull/5102
