### ISSUE TITLE
Start Over: Prefill contact form body to help users who want to start over

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5131]
Currently, the "Start Over" option in site settings leads to a Helpshift contact form with a blank conversation (just the regular conversation prompt):
1. Go to My Site tab and select a WordPress.com site
2. Select Settings
3. Select Start Over
4. Select Contact Support

The name and email fields are filled in, but the conversation only includes the "How can we help?" prompt. We could use the `conversationPrefillText` option to prefill some of that conversation to help users who want to start over.

Reference: https://developers.helpshift.com/ios/sdk-configuration/#conversationPrefillText

**Comment by rachelmcr** [comment]
A screenshot of the "Contact Support" screen in this section, as of now:

![2016-04-12 11 49 42](https://cloud.githubusercontent.com/assets/8658164/14469514/9db2bd6e-00aa-11e6-977d-a913bd1d9b72.png)

Note that the name and email are prefilled, but were blacked out in the screenshot.

**Comment by kwonye** [comment]
We are modifying this by sending users to either a pre-filled email form if they are a paid customer or a webview to https://en.support.wordpress.com/empty-site/ if they are a free customer.
