### ISSUE TITLE
Self-Hosted Login Flow: Check for and sanitize common site URL endings for self-hosted sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5134]
Users with self-hosted sites sometimes try to log in with URLs for their site's login page or dashboard, instead of the home page:
- yourgroovydomain.com/wp-admin
- yourgroovydomain.com/wp-login.php

Currently, it looks like [we assume that the user gave their home page URL](https://github.com/wordpress-mobile/WordPress-API-iOS/blob/develop/Pod/WordPressXMLRPCApi.m#L160) in the self-hosted login form, so attempting to log in with those other URLs results in the error, "Unable to find a WordPress site at that URL."

Can we detect and strip the `/wp-admin` and `/wp-login.php` endings from a site URL as part of the login flow?

For comparison, the Android app removes those from the site URL during login: https://github.com/wordpress-mobile/WordPress-Android/blob/2b4104c0edbf34cdf3339dba34edd6fa104fbc60/WordPress/src/future/res/PluginsCheckerWPOrg.java#L163

cc @SergioEstevao 

h/t Amy for noting that this is coming up regularly in Helpshift issues

**Comment by aerych** [comment]
> Can we detect and strip the /wp-admin and /wp-login.php endings from a site URL as part of the login flow?

Interesting!  We have code that is supposed to [check for and remove these](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/NUX/LoginViewModel.m#L166) but it looks like it isn't being called. 

I'm glad you brought this up.  I did a quick check of the sign in refactor that's in the works and it looks like this is something over looked there as well. [Fixed now](https://github.com/wordpress-mobile/WordPress-iOS/pull/5126/commits/0917dfcee57ba92ad7a321ef74ed381222ea42c9). :)

**Comment by rachelmcr** [comment]
Thanks for adding that fix! I missed the logic in `LoginViewModel.m` when I was looking earlier.

**Comment by aerych** [comment]
Reopened for a little bit.  I've fixed things in the refactored branch but let's also fix the old code since we're looking into doing some A/B testing of the refactor.
