### ISSUE TITLE
Jetpack: Add support for detecting connection status.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5139]
Jetpack is getting some handy API for detecting connection status slated for the v4.1 plugin release.  Let's take advantage of this to do some smarter checking for self-hosted blogs.  When connecting to Jetpack from Stats or Notifications let's let the user know if Jetpack is not installed, or installed and disconnected, or installed but having problems and provide them proper guidance.

**Comment by elibud** [comment]
@koke is this ok to close?

**Comment by koke** [comment]
I think the issue suggests further improvements on status detection, but we can probably close it for now, since we have a generic "set up" prompt and the new flow will take care of the rest.
