### ISSUE TITLE
Jetpack / Stats: Tweak our Jetpack check to determine if the plugin is installed but not connected to wpcom. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5154]
If a self-hosted user has Jetpack installed, the first time they visit the Stats feature they are prompted for their wpcom credentials, even when the plugin is _not_ connected to wpcom. This can be a bit confusing to the user.  They'll get an error saying that their plugin is not connected to the wpcom credentails they endered, which is true but it would be better to let them know they need to go to their wp-admin and connect the plugin. 
When a Jetpack plugin is installed and active, but not connected to wpcom, the blog's options should contain keys for the `jetpack_version` indicating the plugin is installed, and for `jetpack_client_id` which should be false/0.  Let's check for this case and provide better instructions to our user to get them connected.

**Comment by aerych** [comment]
A semi-related Android issue that prompted this ticket.
https://github.com/wordpress-mobile/WordPress-Android/issues/3941

**Comment by elibud** [comment]
@koke is this ok to close?

**Comment by koke** [comment]
Yep, I tweaked the detection a while back, now it's checking if it's connected instead of just installed.
