### ISSUE TITLE
Duplicated symbol isViewHorizontallyCompact

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#5157]
[This method](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Extensions/UIViewController+Helpers.swift#L18) and [this method](https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/blob/develop/WordPressCom-Stats-iOS/UI/UIViewController+SizeClass.h#L5) should be unified in WPiOS Shared, since they're going to cause collisions if both files are included.

This issue was first spotted in [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/5156/files).

/cc @jleandroperez, @astralbodies

**Comment by jleandroperez** [comment]
Housekeeping! Closed via #5158.
