### ISSUE TITLE
Default site gets lost somehow

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5172]
### Expected behavior
Default site should be shown at all times.

### Actual behavior
Between app upgrade or refreshes of the internal beta somehow the default site is not set. Refreshing does not restore it. Logging out and back in does not restore it.

### Steps to reproduce the behavior
I can't nail down the behavior unfortunately.
![img_9812](https://cloud.githubusercontent.com/assets/373903/14675305/007cbbf6-06ce-11e6-8e61-af7f1c1bf831.jpg)

cc: @jleandroperez

**Comment by jleandroperez** [comment]
Closing for now as Cannot Repro. Been trying to force this scenario and... no luck so far.

Let's keep an eye open. Thanks @astralbodies !!!
