### ISSUE TITLE
Inform VoiceOver users of legacy editor

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5179]
Consider providing an alert to users with VoiceOver enabled regarding the availability of the legacy editor which performs significantly better with VO. We could also default the visual editor to off for initial installs of the app if VoiceOver is on.

**Comment by koke** [comment]
Does this still make sense with Aztec?

**Comment by jleandroperez** [comment]
Nope, it doesn't. Closing this one: Aztec on by default is around the corner!

Thanks everyone!
