### ISSUE TITLE
Share Extension: Provide feedback after sharing

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5190]
A common request for the share extension is some kind of feedback after sharing, to confirm if the share worked:

From @alisterscott:

> There’s no feedback after tapping ‘Post’ – I didn’t know whether it had posted or not (it hadn’t) – Tumblr has a progress bar at the top but even theirs disappears very quickly – a subtle tick overlay or something would be nice

From @lancewillett 

> Like Alister, I wanted to have feedback on the screen after the share — did it work? where did it end up?

I also looked for feedback and found myself going to the app to make sure it worked. This felt especially important when I was sharing as a draft, to relieve any anxiety about the post accidentally publishing, and to make sure I shared to the correct site.
##### Tested on WPiOS 6.2.0.20160419

cc @astralbodies

**Comment by astralbodies** [comment]
Also cc: @jleandroperez on this.

Regarding feedback - I think we're going to want to do some sort of synchronous UI blocking while the upload is happening which allows us to indicate failure or not. This will most likely require custom UI and not using Apple's fairly limited share UI.

**Comment by astralbodies** [comment]
Just confirming that this will require a fully custom UI to do it properly. Tapping the Post button is an immediate dismissal of the `SLComposeServiceViewController` UI and we have no real opportunity to override that behavior without hacking or swizzling.

**Comment by bummytime** [comment]
Closing. Addressed in #8581
