### ISSUE TITLE
Share Extension: Empty text box on share screen

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5191]
@alisterscott reported that the text box (title/content) on the share screen can appear entirely empty when sharing from an embedded browser in another app. I reproduced that issue when sharing from the embedded browser in Twitter.

### Expected behavior

- Tap a link in another iOS app that opens in an embedded browser (not Safari)
- Share the link to the WordPress app
- The share screen appears with the text box pre-filled with content

### Actual behavior

- Tap a link in another iOS app that opens in an embedded browser (not Safari)
- Share the link to the WordPress app
- The share screen appears with the text box blank

(Sharing the same link from Safari pre-fills the text box as expected.)

##### Post shared from Twitter embedded browser

![2016-04-23 13 58 31](https://cloud.githubusercontent.com/assets/8658164/14763229/7ff95826-095d-11e6-8ae2-c49feb90aabe.png)

##### Post shared from Safari

![2016-04-23 13 58 18](https://cloud.githubusercontent.com/assets/8658164/14763166/8dfd582a-095b-11e6-8612-8b7439b751ee.png)

##### Tested on WPiOS 6.2.0.20160419

**Comment by rachelmcr** [comment]
This also happens when sharing from the WPiOS Reader:

- Open the WordPress app and go to the Reader
- Select the ... menu on a post
- Select Share
- Select the WordPress app as the sharing target
- The share screen appears with the text box blank

**Comment by rachelmcr** [comment]
I also found that if I left the text box blank, I could still select Post in the top right but the post was never published on my selected blog.

**Comment by astralbodies** [comment]
What we're going to do is always show the URL from the shared content in the text box instead of appending it to the post body after tapping Post behind the scenes. I filed #5224 to handle sharing from web pages (Safari and also embedded web views in apps).

**Comment by jleandroperez** [comment]
Fixed via #5233
