### ISSUE TITLE
Share Extension: Jetpack site icons in site list appear larger than WordPress.com site icons

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5192]
In the site list on the share screen, the site icons for Jetpack-connected sites appear larger than WordPress.com site icons. h/t @lancewillett for the original report.

### Steps to reproduce

- In the WordPress app, make sure you are logged in to an account with both a WordPress.com and Jetpack-connected site
- In another app (e.g. Safari) open a page and select the Share icon
- Select WordPress as the sharing target
- On the sharing screen, select "Post to:" to view the site list
- Result: The site icon for the Jetpack-connected site is larger than the site icon for WordPress.com sites

### Screenshot

All sites in the list are WordPress.com sites, except "Happy Photos" which is a Jetpack-connected site:

![2016-04-23 14 20 23](https://cloud.githubusercontent.com/assets/8658164/14763268/b757bf96-095e-11e6-88af-b11e965b3d4d.png)

##### Tested on iPhone 6 and iPhone 6+, iOS 9.3.1, WPiOS 6.2.0.20160419

**Comment by jleandroperez** [comment]
Fixed via #5222. Thanks Rachel!!
