### ISSUE TITLE
Consider disabling Crashlytics on TestFlight binaries

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5193]
It might be useful to fully rely upon Apple crash reports for TestFlight. I'm not sure if Crashlytics interferes or not but it might be worth using only their reporting tool. The downside, however, is that we can't use the same binary to submit to the App Store.

Any thoughts @sendhil, @kwonye?

**Comment by kwonye** [comment]
What big benefit would this give us?

As much as I love first-party tools, splitting crash reports to two different places seems like a lot more work for people grooming bugs.

**Comment by astralbodies** [comment]
Only benefit I can think of is a single place for crashes for review during the TestFlight process - crashes don't get mixed in with production things. We don't get user analytics though so if we want to contact a specific user we can't with Apple.

I think I just talked myself out of this issue. 🐼
