### ISSUE TITLE
Share Extension: Shared post doesn't always include link to original

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5198]
### Expected behavior

I expect the shared post to always include a link to what I am sharing.
### Actual behavior

The shared post sometimes only includes text, and no link. For example:
- When sharing from the WordPress app
- When text is highlighted and then shared
##### Sharing from the WordPress app:
1. Open the WordPress app and go to the Reader tab
2. In the stream of posts, tap the ... menu at the top right of a post
3. Select Share
4. Select the WordPress app as the sharing target
5. Note that the sharing screen has no text in it, so add text (such as the title of the post you are sharing)
6. Select the blog and post status, and then tap Post in the top right

Result: The published or draft post appears on the blog with the text you entered on the sharing screen, but there is no link to the post. (I tried selecting a different app as the sharing target, to compare, and the correct link was shared as expected.)
##### Sharing selected text:
1. Open Safari and visit a link you want to share.
2. Tap and hold to highlight text you want to share
3. Select Share from the pop-up menu
4. Select the WordPress app as the sharing target
5. Note that the sharing screen has the text you higlighted
6. Select the blog and post status, and then tap Post in the top right

Result: The published or draft post appears on the blog with the text you highlighted, but there is no link to the post. If you highlight text and then use the Safari sharing icon (at the bottom of the screen) instead of "Share" in the pop-up menu above the highlighted text, the shared post includes a link to the post — but the text you highlighted isn't included.
##### Tested on iPhone 6, iOS 9.3.1, WPiOS 6.2.0.20160419

Also reported by @lancewillett on iPhone 6+, iOS 9.3.1, WPiOS 6.2.0.20160419

**Comment by rachelmcr** [comment]
Other apps where I experienced this issue (shared from the app and my resulting post had no link back to the original):

- Pocket
- Guardian
- NextDraft
- Feedly
- Kindle

**Comment by hoverduck** [comment]
I tested this and found slightly different behavior now when sharing from the Reader -> WordPress.  The share extension popup isn't empty as stated in Step 5 above, but has the URL being shared....so at least that's something, but then when I Post it I end up with a post title that looks like

`<a href="http://longreads.com/2017/01/25/blithe-euphoric-grateful-and-over/">http://longreads.com/2017/01/25/blithe-euphoric-grateful-and-over/</a>`

On the web that looks ok, as it's just a link to the article, but on the Posts List page on mobile you see the full HTML tags.
