### ISSUE TITLE
Share Extension: Sharing highlighted/selected text does not work as expected

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5200]
### Expected behavior

When I highlight text and share it, I expect:
- The title of the post I publish to be the title of the page the text is from (e.g. the title of the original blog post or news article I'm sharing from) or a clear way to add my own title
- The highlighted text to be in the body of the post I publish
- A link back to the source of the text
### Actual behavior

When I highlight text and share it:
- The title isn't included on the sharing screen, but the text I highlighted is. I interpreted this to mean that the title would be auto-added to my shared post. Instead, the text I highlighted became the post title.
- There was nothing in the body of the post - no text and no link back to the source (as noted in #5198)
### Steps to reproduce the behavior
1. Open a link in Safari, e.g. a blog post or a news article.
2. Tap and hold to select text, and highlight a section of text to share.
3. In the pop-up above the highlighted text, tap "Share..."
4. Select the WordPress app as the sharing target.
5. In the sharing screen, note that the highlighted text is in the sharing screen. Select the desired blog and post status, and tap on Post in the top right.

Result: The highlighted text is the post title, and there is no text or link in the body of the post.
##### Screenshots

https://cloudup.com/c1jw7TrEpfp

**Comment by astralbodies** [comment]
Default behavior for tapping share on a selected chunk of text does not include the original reference URL or web page URL. See below:
![img_9846](https://cloud.githubusercontent.com/assets/373903/14831528/c7b91b46-0bbb-11e6-967c-dd14fa3f9275.PNG)

That being said, we're going to plan to add a pre-share JavaScript file to extract things like post title, selected text and any other bits relevant to the sharing experience. Will log another issue for this feature and link to this one.

**Comment by rachelmcr** [comment]
If we can extract the post title, that'd be great. Without it, I find that the UI isn't enough to prompt me to add my own title.

A couple things I found that Evernote does well in this case:
- It looks like it uses only the first sentence as the note title (even if the selected text is longer)
- It also adds the selected text in the note body

**Comment by bummytime** [comment]
I am going to close this issue because of the updates in #8263 as well the upcoming UI updates in the [app extension project](https://github.com/wordpress-mobile/WordPress-iOS/projects/11).
