### ISSUE TITLE
Stats: Some cells under Insights > Followers will highlight when tapped, some will not.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5209]
In the example, Starrlet highlights when tapped (and several others) but the cells for Siemon and Jorge do not.  Maybe a cell reuse issue? 

![simulator screen shot apr 25 2016 7 52 42 pm](https://cloud.githubusercontent.com/assets/1435271/14803503/a994e786-0b1f-11e6-966e-4ff143707322.png)

**Comment by ScoutHarris** [comment]
This will be addressed with the Stats Refresh [project](https://github.com/wordpress-mobile/WordPress-iOS/projects/13).
