### ISSUE TITLE
Stats: Insights > Posting Activity responds to taps.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5210]
On the stats screen,  select Insights and scroll down to Posting Activity.  
Tapping the title will launch the detail for the posting activity. 
I'm not sure if the bug is the title cell responds to taps or if it just doesn't have the correct style (blue text) to match the other tappable title cells.

**Comment by ScoutHarris** [comment]
This will be addressed with the Stats Refresh [project](https://github.com/wordpress-mobile/WordPress-iOS/projects/13).
