### ISSUE TITLE
Stats: Abrupt/jarring transition the first time refreshing.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5211]
View stats for a post / page. 
When the detail loads the refresh does not have a smooth transition.  Subsequent pull-to-refresh gestures do have a smooth transition.   See the demo: 
https://cloudup.com/cpa2sPzz3Jl

**Comment by ScoutHarris** [comment]
Closing this as the UI is being replaced with Stats Refresh.
