### ISSUE TITLE
Stats: Latest Post Summary rows needs a disclosure icon when they push a new controller

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5213]
Title has it. 
The styling is a bit confusing.  In the example, the Views cell cell detail text is blue like a link, which suggests that it might open a new screen, however other cases where we push a new controller we show a disclosure icon.  What's more, the Comment cell has the blue icon, but does not respond to taps. 

![simulator screen shot apr 25 2016 8 12 19 pm](https://cloud.githubusercontent.com/assets/1435271/14803780/4c4d4340-0b22-11e6-9265-084266ed8180.png)

**Comment by ScoutHarris** [comment]
Resolved with Stats Refresh.
