### ISSUE TITLE
Site title in editor compressed a little tight

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5228]
The editor window seems to be compressing the site title a bit much - the full title of this site is The Dangling Pointer. While it's enough text to figure out which site I'm using, its a bit weird.

![simulator screen shot apr 27 2016 7 22 37 am](https://cloud.githubusercontent.com/assets/373903/14852902/b4777634-0c4e-11e6-9bfc-e70ae41e1334.png)
##### Tested on iPhone 6s Plus Simulator, iOS 9.3, WPiOS develop / 6.3

cc: @diegoreymendez

**Comment by ScoutHarris** [comment]
Not a problem anymore:
<img width="371" alt="site_title" src="https://user-images.githubusercontent.com/1816888/38118564-c2be113c-3378-11e8-815d-aacad1a63a95.png">
