### ISSUE TITLE
Default site not being selected with new login flow

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5229]
### Expected behavior
After signing in, the default site should be listed first.

### Actual behavior
The default site is not being stored. The Share extension & Today extension are not fully configured either. Possible breakage from login changes?

### Steps to reproduce the behavior
1. Log into the app.
2. No default site selected.

cc: @jleandroperez @aerych

**Comment by aerych** [comment]
I think I've spotted the problem. Let's treat this as a bugfix for 6.2 since that's where its introduced.
