### ISSUE TITLE
Notifications: Enlarge gravatars when tapped and link to user's blog url

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#523]
Reported by @roundhill  

- I keep wanting to click on the small Gravatar and get a larger image. Especially true with new followers.
- With followers, clicking the image takes me to their blog. With replies, clicking the image actually doesn’t do anything.

**Comment by jleandroperez** [comment]
Closing as won't fix, since the interface has been redesigned since this issue was filed.
Back then, the Gravatars, at least, doubled the current size. Plus, replies now contain a header that lead you to the source blog.
