### ISSUE TITLE
Remove `PageListCell` protocol.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#5236]
We're using a `PageListCell` protocol, for no clear advantage [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/5182/files#diff-c22650934e60fe70ee14761402220bf4R341).

Remove it and use a `UITableViewCell` subclass instead.

Also make sure to improve [this method](https://github.com/wordpress-mobile/WordPress-iOS/pull/5182/files#diff-c22650934e60fe70ee14761402220bf4R331) once done.

Props to @jleandroperez

**Comment by jleandroperez** [comment]
Thanks for filing this one Diego!
