### ISSUE TITLE
Migrate Code using NSURLConnection to NSURLSession

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#5245]
This issue serves as master issue to track all related issues to move from NSURLConnection to NSURLSession.

Here is a list of classes to migrate:

- [x] Migrate WordPressComOAuthClient - https://github.com/wordpress-mobile/WordPress-iOS/pull/5247
- [x] Migrate WordPressComAPI
- [x] Migrate WPXMLRPCClient
- [x] Migrate PrivateSiteURLProtocol - https://github.com/wordpress-mobile/WordPress-iOS/pull/5274

**Comment by astralbodies** [comment]
Closing this task.
