### ISSUE TITLE
Remove unnecessary log output.

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#5259]
#### Steps:
1. Launch WPiOS
2. Open `My Sites` > `Blog`
3. Open Pages / Posts. Change the filters, Open the Search Bar

As a result, the following legend will be printed in the console: 
```
No instructions, do nothing
```

#### Notes:
~~I've found the following Stats that lack Mixpanel Properties (and thus, the events are not properly tracked:~~
~~- WPAnalyticsStatPostListStatusFilterChanged~~
~~- WPAnalyticsStatPostListSearchOpened~~
~~- WPAnalyticsStatPostListLoadedMore~~

~~Please, *note* that the events posted are the same for `Pages` and `Posts`. This is because they both share a common superclass, `AbstractPostListViewController`.~~ (see reply by @diegoreymendez below).

**Comment by diegoreymendez** [comment]
> Please, note that the events posted are the same for Pages and Posts. This is because they both share a common superclass, AbstractPostListViewController.

That's a design decision for the time being.  See [this ticket](https://github.com/wordpress-mobile/WordPressCom-Analytics-iOS/issues/66).

**Comment by jleandroperez** [comment]
Thanks Diego!

**Comment by diegoreymendez** [comment]
Edited the title and striked out some of the description in order to better reflect the current status of this ticket.
