### ISSUE TITLE
Editor: Prompted for unsaved changes after setting permissions when prompted

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5264]
There is some bad UX when a user enables permissions for photos and the camera.  

To reproduce on a device: 
- Open Settings > Privacy and disable permission to the WordPress app for Photos and Camera.
- Launch the app and create a new post. 
- Try to add media. 
- You are prompted to give the app permission. 
- Tap to Open Settings
- Update permissions, then return to the app. 
- The app relaunches (because it received a sigkill when permissions where changed). 
- The user is back on the open editor (it would be better if it was the image picker). 
- The user is prompted about unsaved changes. 

Seems like this will (hopefully) just happen once assuming the user grants permission. 
### Prompt to grant permission:

![img_4624](https://cloud.githubusercontent.com/assets/1435271/14960830/31d766d2-105c-11e6-8294-a2942b90d220.PNG)
### Set permissions and return to app

![img_4625](https://cloud.githubusercontent.com/assets/1435271/14960843/48b795d4-105c-11e6-89eb-99418005c6f7.PNG)
### App relaunches

![img_4627](https://cloud.githubusercontent.com/assets/1435271/14960847/4ff9781c-105c-11e6-9e6d-e50a7ab6e7f6.PNG)
### Prompted about unsaved changes, no image picker shown

![img_4628](https://cloud.githubusercontent.com/assets/1435271/14960855/5bc6413e-105c-11e6-92b6-110d565ae8d8.PNG)

**Comment by rachelmcr** [comment]
I retested this on my iPhone XS, iOS 12.0.1, WPiOS 11.0.0.20181010 and I no longer see the unsaved changes prompt. I'm not returned to the image picker, but I don't think that's worth keeping this issue open (it's perhaps something we could revisit when next working on the editor/media flow).
