### ISSUE TITLE
Share Extension: Add window title to share UI

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5283]
Add "WordPress" to the window title of the built-in share UI.

Example:

![2016-05-04_09-32-06](https://cloud.githubusercontent.com/assets/373903/15017417/1c5071ca-11db-11e6-8410-ddac05843631.png)

**Comment by hoverduck** [comment]
Should've been auto-closed by GitHub when #5284 was merged...
