### ISSUE TITLE
Blog Post List image hides on rotation

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5293]
### Expected behavior
The feather & ink well image remains visible after a rotation.

### Actual behavior
When rotating to landscape the ink well image disappears - but then reappears after a forced refresh.

### Steps to reproduce the behavior
1. View blog posts for a site with none in portrait.
2. Rotate to landscape. Notice the ink well image disappears.
3. Pull to force a refresh. Notice the ink well image reappears.

##### Tested on 6s Plus Simulator, iOS 9.3, WPiOS develop/6.3

![img_9894](https://cloud.githubusercontent.com/assets/373903/15026270/3a842c22-1203-11e6-83fb-272aa485db26.PNG)
![img_9895](https://cloud.githubusercontent.com/assets/373903/15026272/3a928894-1203-11e6-8d29-bfe9753c906c.PNG)
![img_9896](https://cloud.githubusercontent.com/assets/373903/15026271/3a91a3f2-1203-11e6-9d45-50ed9ce68cea.PNG)

cc: @diegoreymendez & @aerych

**Comment by aerych** [comment]
The icon is intended to be hidden in landscape orientation on the iPhone.  See: https://github.com/wordpress-mobile/WordPress-Shared-iOS/blob/develop/WordPress-iOS-Shared/Core/WPNoResultsView.m#L226

Its reappearing after a refresh is the actual bug ;)
