### ISSUE TITLE
Split ManagedPerson and Person

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#5307]
```
Lets make sure to get that MO class outside of the struct source file in another PR.
```

**Comment by astralbodies** [comment]
Cool if you're going to extract the MO from the struct Swift file take a look at ManagedAccountSettings.swift and ManagedAccountSettings+CoreDataProperties.swift.

**Comment by jleandroperez** [comment]
Good call, thanks!
