### ISSUE TITLE
Remove MyProfile & AccountSettings Feature Flags

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5317]
After 6.3 is released, remove the feature flag enums for MyProfile and AccountSettings as they are no longer needed.

**Comment by astralbodies** [comment]
@jleandroperez Are we okay to remove People Management as a flag as well?

**Comment by jleandroperez** [comment]
@astralbodies good to go sir! it's been a while since People Management has been wrapped up.

Thanks for checking!!
