### ISSUE TITLE
Media: Reports of duplicated photos in the image picker

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5323]
As [reported in the forums](https://ios.forums.wordpress.org/topic/cant-view-media-library-self-hosted-site?replies=15#post-14659):

> Every time I go to the media library, not only does it still keep pictures I deleted but they're tripling up.. I checked the status of the pictures on the web interface and it's all good there.
> [...]
> After deleting the Wordpress app, I reinstalled it, logged in via wordpress.com to access my self hosted site, and now the media library is behaving (no triplications). Until I go back in to the media library and the pictures duplicate. I tap on Cancel and enter the media library again to find they've tripled again. 

Theory: Media ids can be wrongly parsed and then we get media duplication

cc @SergioEstevao

**Comment by bummytime** [comment]
I am closing this for now due to the fixes coming in #8105.
