### ISSUE TITLE
Eliminate distinction between a blog's account and jetpackAccount.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#5334]
Eliminate the distinction between a blog's `account` and `jetpackAccount` properties, since both are `WPAccount` objects, and they can't exist in parallel.

**Comment by diegoreymendez** [comment]
@koke - A few questions that'll help me solve this issue:

I'm having some trouble understanding what's going on [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Services/BlogService.m#L631).

From the comments:

```
If that's the case, this method will take the blog and transfer it to the account.
```

I would have expected `jetpackAccount` to be set in this scenario.  Can you clarify a bit to me how Jetpack sites are currently stored?  Thanks!

**Comment by koke** [comment]
Back in the day, we stored self hosted credentials in `WPAccount` as well, so a self hosted blog connected to Jetpack would have an `account` and a `jetpackAccount`.

Currently, jetpackAccount is set when you connect a self hosted to Jetpack from Stats. (see JetpackService)

If there's no other account in the app, the newly created account becomes the default account and it triggers a blog list sync, which should include the recently connected self hosted. Then `migrateRemoteJetpackBlog` tries to match the remote list with the existing blogs.

If there's a match, we clear `jetpackAccount` and set `account`. This is consistent with what would happen if we logged in directly to wordpress.com.

I know it doesn't make much sense 😞

**Comment by diegoreymendez** [comment]
> Back in the day, we stored self hosted credentials in WPAccount as well, so a self hosted blog connected to Jetpack would have an account and a jetpackAccount.

My biggest concern with the changes I want to do, would be if there's a chance we may currently have both `account` and `jetpackAccount` set.

Would it be safe to consider it no longer possible to have both simultaneously?

> Currently, jetpackAccount is set when you connect a self hosted to Jetpack from Stats. (see JetpackService)

My plan is to keep a similar logic, but when opening stats, instead of loading the account into jetpackAccount, I'd load it directly into `account` instead.

Any downsides you can think of for doing this?

> If there's no other account in the app, the newly created account becomes the default account and it triggers a blog list sync, which should include the recently connected self hosted. Then migrateRemoteJetpackBlog tries to match the remote list with the existing blogs.
>
> If there's a match, we clear jetpackAccount and set account. This is consistent with what would happen if we logged in directly to wordpress.com.

I'm not sure if this is correct but after the changes in my previous comment, this step may not be necessary anymore?

> I know it doesn't make much sense 😞

No worries.  All apps have legacy code... I just want to see if it's possible for us to simplify this logic without me breaking a lot of important code.

In order to do this right I'll need to rely on the knowledge you have, if you don't mind me sharing my thoughts and asking quesitons.

**Comment by koke** [comment]
> My biggest concern is if there's a chance we may currently have both account and jetpackAccount set.

I can't guarantee 100%, but IIRC that has never been a valid state.

> My plan is to keep a similar logic, but when opening stats, instead of loading the account into jetpackAccount, I'd load it directly into account instead

I think that should work

>> If there's no other account in the app, the newly created account becomes the default account and it triggers a blog list sync, which should include the recently connected self hosted. Then migrateRemoteJetpackBlog tries to match the remote list with the existing blogs.
>> If there's a match, we clear jetpackAccount and set account. This is consistent with what would happen if we logged in directly to wordpress.com.
> I'm not sure if this is correct but after the changes in my previous comment, this step may not be necessary anymore?

I think `migrateRemoteJetpackBlog` is still useful because you might have several self hosted blogs added to the app all connected to the same wp.com account. Whenever you add that wp.com account to the app, syncBlogs will get all those blogs again and they need to be migrated to use REST.

> ...if you don't mind me sharing my thoughts and asking questions.

Definitely, ask all the questions you have 😄

**Comment by diegoreymendez** [comment]
I'm removing myself from this issue for now as I can't tackle it for the time being.  Leaving it open due to the information available in it.
