### ISSUE TITLE
The js method ZSSEditor.undo and ZSSEditor.redo not work in iphone devices

### ISSUE THREAD

**Issue by xineason** [wordpress-mobile/WordPress-iOS#5339]
The js method ZSSEditor.undo and ZSSEditor.redo not work in iphone devices
iphone devices version :9.3
xcode:7.3
how support "redo" and  "undo" ?

## WPEditorView.m -> ##
```
- (void)undo
{
    [self.webView stringByEvaluatingJavaScriptFromString:@"ZSSEditor.undo();"];
	
    [self callDelegateEditorTextDidChange];
}
```

**Comment by rachelmcr** [comment]
There is an open issue for adding undo/redo functionality in the WordPress Editor repo: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/496

I am closing this issue since this is included in that issue.
