### ISSUE TITLE
Backdated drafts are published instead with the current date/time

### ISSUE THREAD

**Issue by sandymcfadden** [wordpress-mobile/WordPress-iOS#5350]
### Expected behavior
If you change the publish date on a post and publish it that it will use that as the published date.

### Actual behavior
Instead it will use the original creation date of the draft post as the published date.

### Steps to reproduce the behavior
- Create a post
- Save it as a draft
- Change the date on the post and update
- Change the status to publish and publish post
- View post on site and see the original creation date as the published date.

##### Tested on iPhone 6, iOS 9.3.1, WPiOS 6.1

Video of this happening
https://cloudup.com/cm6ym99KQN2

**Comment by rachelmcr** [comment]
A few notes:

- This only happens for backdated drafts (not for scheduled drafts)
- This happens both when you save the draft before publishing (the steps above) and if you set the date and publish status at the same time
- The post is published with the current date/time (not the original creation date)

Related issue with scheduled drafts: https://github.com/wordpress-mobile/WordPress-ios/issues/3973

cc @aerych as you're familiar with the scheduled drafts issue.

**Comment by aerych** [comment]
Currently the app assumes *all* drafts should be published immediately, with the current date and time.  This is why a backdated publish date is ignored. 

To fix the bug, I think we can update things like so: 
* start storing a post's `date_modified`
* refactor the "publish immediately" behavior to set the post's `date_modified` to match a the post's `date_created_gmt`. Currently the app sets `date_created_gmt` to nil as a way to indicate the post should "publish immediately", then sets the `create_date_gmt` to the current date when publishing. Some testing of the xml-rpc api and the wpcom rest api suggests they will *both* respect a matching `date_modified` and `date_created_gmt` as meaning "publish immediately"
* remove the code that sets a draft post's `date_created_gmt` to the current date when pubilshing

I believe this preserves the publishing logic for scheduled posts that are updated to "publish immediately", and draft posts that are backdated. 

Patch forthcoming.

**Comment by MarcoZehe** [comment]
I am seeing a similar issue when updating an existing post from the current iOS app. It gets today's date and time instead of keeping the original one, and even the permalink gets updated. The Options screen, however, shows the original publishing date and time. Is this already a known issue? My search didn't find it, only this one. Would appreciate any pointers!
