### ISSUE TITLE
NUX: Remove the old NUX code and slightly refactor the new NUX code

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5355]
Once we're done A/B testing the new sign in flow it and making any necessary tweaks it will be time to remove the old `LoginViewController` and friends. 

Things to remove: 
- [x] Remove the Optimizely A/B test.
- [x] ReactiveCocoa Pod
- [x] LoginViewController
- [x] CreateAccountAndBlogViewController
- [x] LoginViewModel
- [ ] WPWalkthroughOverlayView
- [ ] WPNuxMainButton
- [ ] WPNuxSecondaryButton

Additionally:
- [ ] Rename `LoginFields` to something along the lines of `NUXSharedState` to be more descriptive of its new role. Update `loginFields` instances accordingly.
- [ ] The `SigninWPComSyncHandler` protocol extension can be expanded to assume more of the logic in the self-hosted, wpcom, and 2fa signin controllers. 

If needed: 
- [ ] Refactor `CreateNewBlogViewController`. Either separate it from the NUX experience or bring it into the fold.  Either way it needs to stop using the deprecated NUX assets. 
- [x] Remove the Optimizely pod if we're have no future plans to use it.

**Comment by koke** [comment]
@aerych I think part of this is done, but not sure how much.

**Comment by aerych** [comment]
@koke Thanks for the ping. I'd forgotten about this one.  I've marked off the tasks completed in https://github.com/wordpress-mobile/WordPress-iOS/pull/5984 
CreateNewBlogController needs to be updated before we can nuke some of the other classes.

**Comment by nheagy** [comment]
Would be great to finish this sometime after #8439 to nail down this code to be nice.

**Comment by kean** [comment]
Closing as obsolete.
