### ISSUE TITLE
Treat nil/empty responses as error conditions

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5383]
Sometimes PHP likes to return HTTP 200 empty responses when there is a PHP fatal error. Yay PHP.

https://bugs.php.net/bug.php?id=50921

We should comb through every endpoint in the app and make sure if any of these responses coming back are nil or empty strings to treat them as a server error. There's probably a more elegant way to handle this with our AFNetworking stack. Unless an endpoint can provide an empty response and it be considered a legal response, treat it almost like a 500 error. 

This probably only affects the RESTful endpoint calls as XML-RPC would be malformed otherwise.

This is being super defensive about an obscure API bug. It will, however, prevent issues with the app assuming a valid response and then nullifying important data in Core Data and a crash during save.

**Comment by SergioEstevao** [comment]
@astralbodies I will add some tests my new stack on AFNetworking to see what happens when you answer with empty string and/or nils. Do you have any other sample outputs from the server that I can use on the tests?

**Comment by astralbodies** [comment]
@SergioEstevao Just one during that outage on WordPress.com:

Request:
```
GET /rest/v1.1/me/sites HTTP/1.1
Authorization: Bearer xxx
Host: public-api.wordpress.com
Connection: close
User-Agent: Paw/2.3.3 (Macintosh; OS X/10.11.4) GCDHTTPRequest
```
and the Response:
```
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 11 May 2016 17:09:43 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
X-Prefork: 1
X-hacker: Oh, Awesome: Opossum
Expires: Wed, 11 Jan 1984 05:00:00 GMT
Cache-Control: no-cache, must-revalidate, max-age=0
Pragma: no-cache
X-ac: 2.ord _dca
Strict-Transport-Security: max-age=15552000
```

**Comment by SergioEstevao** [comment]
The WordPressRestAPi class already considers this an error situation.
