### ISSUE TITLE
Add an error message if user disables Facebook/Twitter access through the Settings App

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#540]
If a user previously enabled Facebook or Twitter support in the app and then disables it through the Settings app, attempting to use the friend finder again doesn't display an error messages and the attempt to search for friends fails. We should add an error message indicating to the user what is happening and ask them to re-enable the permission.

**Comment by aerych** [comment]
Gonna close this since after #3600 there should be nothing left in the app using Twitter or Facebook accounts.
