### ISSUE TITLE
Add Share Icon to Full View/Preview Screen

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5425]
The app has two ways to preview a post, and the share icon is only available on one of them (as of #5079). This causes confusion if someone tries to share a post from the other preview screen.

### Expected behavior

No matter how you view or preview a post from the Blog Posts list, you will see the share icon.

### Actual behavior

You only see the share icon if you tap the post card on the Blog Posts list to preview.

### Steps to reproduce the behavior

1. Go to My Sites > Select a site > Blog Posts
2. Tap on a post card in the list, e.g. https://cloudup.com/cUImpD56JMd
3. Result: You see the Preview screen with the share icon in the top right: https://cloudup.com/cIq2ME81EjJ
4. Go back to the Blog Posts list
5. Tap on the "View" (published posts) or "Preview" (draft/scheduled posts) link at the bottom of the post card, e.g. https://cloudup.com/cbT75rpRYfD
6. Result: You see a Preview of the post on the site, with no share icon: https://cloudup.com/c38cQ6C1Uou

##### Tested on iPhone 6, iOS 9.3.2, WPiOS 6.2

Reported: https://ios.forums.wordpress.org/topic/sharing-from-preview-in-v62?replies=1

cc @diegoreymendez @mattmiklic

**Comment by mattmiklic** [comment]
I think this one could be fixed pretty easily by adding the Share icon to the toolbar when the user is in the Preview screen. There's currently no icons on the right of that toolbar, so I think it should be pretty simple to add.
