### ISSUE TITLE
Replying to a pending comment from Notifications implicitly approves it, while replying from comments does not

### ISSUE THREAD

**Issue by pivotal-rebecca** [wordpress-mobile/WordPress-iOS#543]
I'm not sure what the intended behaviour is, but this is what happens:

##### Replying via notifications screen
1. Leave a sketchy comment on some blog you own
2. In the app, receive the notification of a comment. Visit comments for that blog if desired, and confirm that it's pending moderation.
3. Tap the notification and reply, from Notifications
4. Visit the blog, and notice that the comment is now showing up, approved. Go to comments and refresh and the comment is approved as well.

##### Replying via the comment from Comments
1. Step 1 as above
2. Step 2 as above, but visit <the blog> -> Comments
3. Verify it's pending moderation
4. Enter the comment and reply
5. Go back, and refresh the website/comment screen, and it's still pending moderation.

**Comment by jleandroperez** [comment]
I'm closing this since it's not happening anymore. Tested on WPiOS 4.8.
