### ISSUE TITLE
Signup: Improve email validation on signup

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5458]
### Expected behavior

I expect any invalid email patterns to be blocked from signing up.

### Actual behavior

These invalid email patterns are accepted in the signup form:

- Invalid IP format: email@111.222.333.4444 (Result: account is created with email address email@111.222.333.4444)
- Two @ signs: email@example@example.com (Result: account is created with email address email@exampleexample.com)

### Steps to reproduce the behavior

1. Open the WordPress app (log out of WordPress.com account if needed)
2. Select Create Account on the login screen
3. Enter an email address with each of the invalid email patterns above
4. Fill out the rest of the signup form with valid details (username, password, site address)
5. Tap "Create Account"

I also tested these patterns in the Calypso web signup form at https://wordpress.com/start/account/user and they were caught as invalid (could not sign up).

##### Tested on iPhone 6, iOS 9.3.2, WPiOS 6.3.0.20160524

**Comment by aerych** [comment]
At one point we were using regex to validate email,  `^[^@\\s]+@[^@.\\s]+\\.[^@\\s]+$` or the slightly more forgiving `"^[^@\\s]+@[^@\\s]+$"`.  While they both validate @koke raised some concerns in an other [email related PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/5087).  You can see the old comments for context. 
Just FYI for the extra context and why the current validation is very permissive.

**Comment by rachelmcr** [comment]
Thanks for that context. I don't think there's a ton to be gained by adding this validation, so making it low priority or wontfix is totally fine from my perspective.

I'm more interested in the second pattern (two @ signs), since it seems more likely than the first and could be entered by someone not paying attention and double-entering the domain. That said, also not terribly likely and easier to correct now that users can update their email address within the app. :)

**Comment by nheagy** [comment]
I agree that the client-side email validation has to be quite permissive. I mentioned that current behavior may be inconsistent to the API team, so for now I'm closing this as wontfix.
