### ISSUE TITLE
Signup: Lost connection during signup results in error screen with no explanation

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5462]
### Expected behavior

I expect the error overlay during signup/login to always include a message explaining the error.

### Actual behavior

If you lose your internet connection or can't connect to WordPress.com, a plain error screen is shown:

![2016-05-27 16 24 55](https://cloud.githubusercontent.com/assets/8658164/15612663/9f6b3bcc-2427-11e6-82bd-4ed55babf4f3.png)

Errors in the app log around that signup attempt:
```
2016/05/27 16:17:49:751  Reachability - Internet - WiFi: N  WWAN: Y
2016/05/27 16:17:49:864  Failed creating user: (null)
2016/05/27 16:17:49:932  <WordPressAppDelegate: 0x124e525c0> applicationDidBecomeActive:
2016/05/27 16:17:50:639  Reachability - Internet - WiFi: N  WWAN: N
2016/05/27 16:18:26:307  <WordPressAppDelegate: 0x124e525c0> applicationWillResignActive:
2016/05/27 16:18:27:424  <WordPressAppDelegate: 0x124e525c0> applicationDidBecomeActive:
2016/05/27 16:18:42:502  TracksService Error while remote calling: Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={NSUnderlyingError=0x1264c3a50 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=8, _kCFStreamErrorDomainKey=12}}, NSErrorFailingURLStringKey=https://public-api.wordpress.com/rest/v1.1/tracks/record, NSErrorFailingURLKey=https://public-api.wordpress.com/rest/v1.1/tracks/record, _kCFStreamErrorDomainKey=12, _kCFStreamErrorCodeKey=8, NSLocalizedDescription=The Internet connection appears to be offline.}
```

This is especially problematic because closing the error screen returns you to the create account screen, but your account may have actually been created before the connection dropped. (In that case, trying to sign up again returns the error "Sorry, that site is reserved!")

### Steps to reproduce the behavior

1. Open the WordPress app (and log out if you are logged in to WordPress.com)
2. Select "Create Account" on the login screen
3. Enter a valid email, username, password, and site address for a new account
5. Tap the "Create Account" button
5. Disable your internet connection while the progress bar is still spinning (e.g. by enabling airplane mode)

Result: An error screen appears with "Error" and no additional information.

##### Tested on iPhone 6, iOS 9.3.2, WPiOS 6.3.0.20160524

**Comment by aerych** [comment]
Wow. That's horrible.

**Comment by aerych** [comment]
I noticed the sign up form in the example is the old sign up form.  This issue should be resolved with the new form. 
![simulator screen shot jun 2 2016 11 51 18 am](https://cloud.githubusercontent.com/assets/1435271/15753392/695f07da-28b8-11e6-9be1-d05c5f9b2848.png)

**Comment by nheagy** [comment]
The new form is live, and thus this issue is fixed 🎉
