### ISSUE TITLE
Launch "View Site" in device browser (e.g. Safari) instead of in-app browser

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5475]
Currently, the app's admin and site links behave differently: 
- "View Admin" launches WP Admin in the device browser
- "View Site" launches the in-app browser
#### The problem:

This leads to confusion when users navigate from "View Site" to other in-app browser views (including Calypso and WP Admin) and things don't work as expected. Some things are broken, and others don't work as well as features we have already implemented in the app itself.
#### Possible solution:

By changing "View Site" to also launch in the device browser, we can cut down on that confusion (and other effects like negative app reviews). It will also eliminate the current frustration when "View Site" doesn't authenticate properly and leads to a logged-out view (e.g. #4381).

We could also add contextual cues in the app to items that launch outside the app, similar to the icon Calypso uses to identify external links:
 <img width="32" alt="screen shot 2016-05-31 at 2 08 52 pm" src="https://cloud.githubusercontent.com/assets/8658164/15675306/48bf7ff8-2739-11e6-9381-d0ceb68f49ca.png">
#### Potential downsides:
- If the user isn't already logged in to the site in their browser, the visit to their site will be counted in their stats
- Users may be frustrated/confused about where they landed, having to log in again, getting back to the app (although cues like Safari's "Back to X" button will help identify what's happening and make it easy to get back to the app)
#### Other alternatives:
- @frosty suggested we could switch from our custom browser to Apple's Safari View Controller, with the theory that user's may be used to it from other apps and it could cut down on the confusion from our own in-app browser.
- We could limit users to the main page of the site by disabling links similar to when you preview a post in the app, so it's impossible to navigate to WP Admin or Calypso in the in-app browser. (Also likely has high potential for confusion/frustration.)

**Comment by charliescheer** [comment]
If we add the ability to open the site in a browser as opposed to the in app browser, I had a user requesting that they be able to set what their preferred default browser is, chrome, safari etc.

**Comment by thehenrybyrd** [comment]
This came up in #1663519-zen, where the user was confused about the editor behavior. 
This happened because they went to My Site > View Site (in-app browser) and then clicked "edit" on one of their posts. This opened the web editor (Calypso in Safari), which looks different from the app's editor.
We've clarified what's happening for this user, but I do think clearer messaging around when we're taking folks out of the app would be excellent.

**Comment by rachelmcr** [comment]
This came up again in a user reported issue with Gutenberg (internal ref: 1892303-zen). The user reported a problem where they couldn't scroll down in the editor to manage the block controls (text alignment on a paragraph block).

The user had gone to My Site > View Site to open the in-app browser, and from there opened Gutenberg web and couldn't scroll down to the block controls in the block they wanted to edit. Although Gutenberg mobile doesn't yet support the block controls this user needed, the current behavior definitely caused confusion and prevented the user from being able to do what they intended.

**Comment by designsimply** [comment]
<blockquote>The user had gone to My Site > View Site to open the in-app browser, and from there opened Gutenberg web and couldn't scroll down to the block controls in the block they wanted to edit. </blockquote>

Now that we hide unnecessary overlays within the mobile app (https://github.com/Automattic/wp-calypso/issues/31161), this is improved. The only way I could find to get into the confusing state  was the route @thehenrybyrd noted for 1663519-zen where the user went to My Site > View Site (in-app browser) and then clicked "edit" on one of their posts. I tested and confirmed I could do that for a WordPress.com and a self-hosted site but not for a Jetpack site.

<img src="https://user-images.githubusercontent.com/1119271/56176249-b9a89d80-5fb7-11e9-8ef4-393a6b781cac.PNG" width="270" alt="IMG_2547">
<p style="clear:both;"><sup>Tested with WP Internal 12.2.0.20190412 on iPhone 6S iOS 12.2 on a WordPress.com Premium site `madefortesting0313.com`.</sup></p>

**Comment by shiki** [comment]
@rachelmcr @designsimply I need your advice on this. I was about to work on changing WPAndroid to use an **internal browser** as part of wordpress-mobile/WordPress-Android#9625. Luckily, I saw this issue. 

As it is right now, the _View Site_ button behaves differently between the 2 platforms:

- Android shows an external browser
- iOS shows an internal browser (without Calypso UI)

Which one is correct? 🤔

**Comment by rachelmcr** [comment]
@shiki Android was changed to use an external browser in 2016 to resolve the parallel issue to this one: https://github.com/wordpress-mobile/WordPress-Android/issues/4140

iOS wasn't changed at that time, so I think it's worth a discussion about which behavior is preferable. The Calypso changes may make it preferable to use an in-app browser in Android again, now that the original reasons for linking to the system browser are mostly resolved. I think it's worth getting some design input on which way to go.

**Comment by mattmiklic** [comment]
@rachelmcr did we find that either external browsers or internal webviews have an impact on support requests? That feels like the primary concern from a design standpoint, doing whatever leads to less confusion and people getting stuck. My hunch would be to advocate for an internal browser/webview with all of the links that lead into the web admin turned off, as Sheri [mentioned](https://github.com/wordpress-mobile/WordPress-iOS/issues/5475#issuecomment-483480741) here. If we're able to hide those confusing links (including the Edit link she mentioned) and keep the user within the app, my hypothesis would be that that would lead to less confusion.

**Comment by rachelmcr** [comment]
@mattmiklic We get support requests either way, but the recent changes to removes routes leading to the web admin will hopefully cut down on support requests related to internal webviews. There are some other areas of the app where internal webviews have other issues, but in the case of the "View Site" link I think the Edit link is the last piece we'd need to solve.

We haven't done anything to address support requests related to external browsers (authentication is the main one I'm aware of, since the user has to log in again to be authenticated in the browser) so my inclination is also to keep the user within the app.

My suggestion then is for @shiki to go ahead and change WPAndroid back to using an internal browser for the "View Site", to match the WPiOS behavior, and we can work on changes to resolve the remaining issue with the Edit link. (I could imagine either a backend change to remove that Edit link in app webviews or having the app intercept that link and redirecting it to the app editor.)

**Comment by shiki** [comment]
Thank you, @rachelmcr and @mattmiklic. Some else will take over this issue. We'll proceed with changing WPAndroid to use an internal browser for _View Site_.

**Comment by diegoreymendez** [comment]
From my understanding this issue is no longer a requirement, but just to confirm: can we close this issue @rachelmcr ?

**Comment by thehenrybyrd** [comment]
This came up again in #2056460-zen, with another user getting into Calypso within the in-app browser. It makes for a very confusing editing experience.

**Comment by rachelmcr** [comment]
@thehenrybyrd Do you know what steps the user you talked to used to get into Calypso? As far as I know the only remaining way to get into Calypso from this in-app browser is using the "Edit" link on a post or page, but I'd like to know if there are other routes we haven't considered.

> From my understanding this issue is no longer a requirement, but just to confirm: can we close this issue @rachelmcr ?

I missed this question earlier, sorry! I agree this is no longer a requirement. The current plan is to keep the in-app browser, rather than launching "View Site" in a device browser, and focus on removing any unexpected routes into the admin area from within the in-app browser.

Given that we don't plan to make any further changes to the app behavior for now, I'm going to close this issue. For the remaining issue with the Edit link I've opened an enhancement issue on the WordPress.com side, internal ref 8149-wpcom (and we can open new issues for anything else that comes up with either WordPress.com or self-hosted app users).

**Comment by thehenrybyrd** [comment]
@rachelmcr I'm really not sure how they got there, and unfortunately this user was already frustrated and confused so we weren't able to get them to duplicate for us. I would guess they pressed "Edit" from a post or page though, as you suggest.
