### ISSUE TITLE
The Seach Bar on Post List and Blog List goes out of screen on Compact IPad mode

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#5481]
### Expected behavior

The search bar should stay always inside the screen

### Actual behavior

On the smaller iPad multitask mode the search bar gets out of the screen
<img width="624" alt="screen shot 2016-05-31 at 12 54 25" src="https://cloud.githubusercontent.com/assets/651601/15690570/047957c2-277c-11e6-93a0-cb324c231a83.png">

**Comment by aerych** [comment]
Fixed in #5482
