### ISSUE TITLE
User Content Not Visible in Visual Editor

### ISSUE THREAD

**Issue by dcoleonline** [wordpress-mobile/WordPress-iOS#5496]
### Expected behavior
The content should be visible and editable when the visual editor is enabled.

### Actual behavior
The content is not visible in the visual editor. You have to disable the visual editor in order to see the content.

### Steps to reproduce the behavior
Create a new post using the content here:
https://gist.github.com/dcoleonline/50d3fcb8c3f893bae2ef0fa4ffb828fc

#### Screenshot of Visual Editor Off
![img_0562](https://cloud.githubusercontent.com/assets/3505172/15751038/4aecb734-28ae-11e6-98d2-f9f4bb6a34ef.PNG)

#### Screenshots of Visual Editor On (visual and html views)

![img_0564](https://cloud.githubusercontent.com/assets/3505172/15751079/63f4cd3e-28ae-11e6-9d6c-682630993357.PNG)
![img_0563](https://cloud.githubusercontent.com/assets/3505172/15751080/64040984-28ae-11e6-88a0-61670d518c35.PNG)

**Comment by frosty** [comment]
@dcoleonline Thanks for the report! Can I ask how you created the post in the first place? Through the app? (if so, which editor?) or via the web? I can't seem to recreate the issue at the moment.

**Comment by dcoleonline** [comment]
@frosty: The user has been using an iPad to create their content on https://deduncan920wordpresscom.wordpress.com. I'll have to ask which editor they used, but my thought at the moment is likely they were using the visual editor, as I believe that's the default. I'll reply when I've got confirmation from them.

**Comment by frosty** [comment]
@dcoleonline: After some digging, I was able to narrow down the part of the post that was causing the issue. It turns out there's an invisible 'line separator' character before the final ampersand here:

```
We stopped at a little hole in the wall for lunch ($4 for boiled chicken, rice and a pop). &nbsp;We would never have gone there on our own - our tour guide, a local gal, suggested it. &nbsp;
```

I've just pushed a PR to the editor to fix this (https://github.com/wordpress-mobile/WordPress-Editor-iOS/pull/827), but for now the user could simple delete the last part of that sentence and re-write it. Thanks again for the report!

**Comment by dcoleonline** [comment]
@frosty The user confirmed they're using the visual editor, but there's some odd HTML being added to their posts, so I'm thinking they copy/pasted from somewhere:

`<span id="selectionBoundary_1464840817294_20216714264824986" class="rangySelectionBoundary" style="line-height: 0; display: none;"></span>`

I asked for more specifics about their editing process and will update with that information. Also I updated their Brunei post so they can edit it using the visual editor again, and let the user know.
