### ISSUE TITLE
Reader: Layout of reblogged posts needs improvements

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5511]
I believe this is an old glitch but I couldn't find the issue for it. 
![reblogged-post-layout](https://cloud.githubusercontent.com/assets/1435271/15827025/810e0ace-2bcf-11e6-985d-293fe3e1a50d.png)

**Comment by aerych** [comment]
Refs #2199

**Comment by yaelirub** [comment]
Closing this in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/2199 that might be closed as well
