### ISSUE TITLE
Me: WordPress.com Profile About Me field behaves weird

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5526]
### Expected behavior
Appending text to the contents of the About Me field should perform properly - resizing, etc.

### Actual behavior
> When I edit my profile and type text at the end of the existing text in the About Me field, letters do not appear.

### Steps to reproduce the behavior
> Tapping Return makes the text appear and adds the crlf. If I then delete everything I typed, typing in the field behaves normally.

##### Tested on iPhone8,1, iOS 9.3.2, WPiOS 6.3.0.1 (TestFlight)

cc: @jleandroperez

**Comment by jleandroperez** [comment]
Reproduced on the actual device. (Can't trigger this bug on the simulator!)

**Comment by jleandroperez** [comment]
#### Update:
This is happening on the 6s (not the 5s), and i've managed to repro on the simulator as well. Will have a fix shortly!

Thanks!
