### ISSUE TITLE
Comments: Extra HTML tags added after adding or editing comments

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5530]
### Expected behavior

I expect that when editing comments (either in the site's Comments section or in a notification) the only changes to the comment will be my explicit edits.
### Actual behavior

When I edit comments in the site's Comments section, extra `p` and `br` tags are added around the edited comment.

Note: Edits made to a comment from the comment notification do not have this issue. Even when you view the edited comment in the site's Comments section, the extra tags don't appear there.
### Steps to reproduce the behavior
1. Open the WordPress app
2. Go to My Site and select a site
3. Select Comments
4. Select a comment on the site
5. Tap Edit in the top right
6. Make a change to the comment
7. Tap Save in the top right

Result: You see your change in the comment view, but after the app finishes processing the change, extra HTML tags appear around the edited comment.

Comment before editing:

![2016-06-08 11 32 33](https://cloud.githubusercontent.com/assets/8658164/15891551/061a44e6-2d6d-11e6-85c0-d333ba62b171.png)

Comment immediately after editing:

![2016-06-08 11 32 46](https://cloud.githubusercontent.com/assets/8658164/15891554/08f32692-2d6d-11e6-9fa8-e64618be3bff.png)

Comment after edits were saved/uploaded:

![2016-06-08 11 32 48](https://cloud.githubusercontent.com/assets/8658164/15891557/0c7822c2-2d6d-11e6-97f6-06c15c816dbe.png)

**Comment by lancewillett** [comment]
I saw this today in testing — but not with editing, with a *new* comment.

Using iOS app version 6.5.020161012

![1 - app version](https://cloud.githubusercontent.com/assets/66797/19358551/2408b646-912b-11e6-90c1-b9db7e465e50.jpg)

#### Steps to repeat

1. Using the iOS app, selected a site from My Sites and clicked "Comments" in navigation list within the "Publish" section.
2. Clicked into a comment, and added a reply there.

![2 - replied to a comment](https://cloud.githubusercontent.com/assets/66797/19358549/2407d00a-912b-11e6-9c7b-c5ae36efa515.jpg)

3. The comment itself looks OK once you are back in the main list.
![3 - looks ok back in comment list](https://cloud.githubusercontent.com/assets/66797/19358547/240776a0-912b-11e6-8dcc-378400d4e74e.jpg)

4. This is the same comment, on the site's frontend notifications list.

![4 - same comment in frontend notifications](https://cloud.githubusercontent.com/assets/66797/19358546/24070238-912b-11e6-8b95-a2a183b1721f.jpg)

5. I tried another comment from the iOS app again.
![5 - tried another comment from inside ios app](https://cloud.githubusercontent.com/assets/66797/19358550/24087212-912b-11e6-977b-b7d0a2c2a786.jpg)

6. Just after posting it, you can see the HTML tags are visible.
![6 - just after post it has extra html tags](https://cloud.githubusercontent.com/assets/66797/19358548/240777ea-912b-11e6-9e7b-17e2ede32404.jpg)

7. In the comments list, I pulled down to refresh — and it looks OK now.
![7 - after refreshing comment list in the app looks ok](https://cloud.githubusercontent.com/assets/66797/19358552/24188184-912b-11e6-9022-be24fe9694a5.jpg)

**Comment by knightjoel** [comment]
I've been seeing the same behavior as @lancewillett with new comments. The main list of comments in the app looks ok (although it does not show line breaks in the comment excerpt, but at least there are no HTML tags):

![1](https://cloud.githubusercontent.com/assets/17298529/21557630/831d5f76-cdec-11e6-8488-91ddb73ddff4.png)

But when opening the comment, HTML tags are shown:

![2](https://cloud.githubusercontent.com/assets/17298529/21557642/a0b9f8aa-cdec-11e6-8482-d917fc6b4fd6.png)

Looking through a dozen or so random comments on my blog, the only tags which the app is showing is the `<br />` tag. This is all with v6.7 of the app.



.joel

**Comment by knightjoel** [comment]
Digging into the code, I see that the Comment model actually inserts `<br />` tags in place of line breaks before a comment's content is displayed. I do not understand why.

It appears the display of comments could be fixed by removing said line.

https://github.com/knightjoel/WordPress-iOS/commit/e9a8df435507c04225c5f4637e1a632002e199ba

I'm not certain how or if this would break writing/editing comments.
