### ISSUE TITLE
My Sites:Preload site content when user navigates to the my sites page

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#5537]
When the user navigates to the my sites page and taps on any item for the first time the item should open to pre loaded content. To respect cellular data usage we should probably only do this on wifi.

**Comment by apeatling** [comment]
This should also happen for the reader. I should be able to open any of the five main sections, and not have to wait for it to load.

**Comment by nheagy** [comment]
Just putting in a checklist here as I work through the chunks of this. Can we make a new issue for the reader part?

- [ ] Preload stats - #5537
- [ ] Preload blog posts
- [ ] Preload pages
- [ ] Preload comments

**Comment by koke** [comment]
Copying my comment from #6010:

My main concern if we start preloading content is that we should make sure to prioritize and not duplicate requests:

- Do not duplicate: if I go to blog details and immediately go to comments (or any other preloaded section), it's going to fire two requests to sync comments.
- Prioritize: preloading requests should not block the network for other requests. (See [previous conversation](https://github.com/wordpress-mobile/WordPress-iOS/pull/4001#issuecomment-120965315)). 
- I'd also say don't preload if the latest sync was recent enough. If I go to view comments (which syncs when it load) and go back, there's no need to "preload" comments again.

**Comment by sendhil** [comment]
So – I think preloading of comments is fine for now even with the duplicate requests. We aren't going to be able to deal with the problem of duplicate requests, cancellation, prioritization, etc. at the present moment until we re-think and re-work our networking stack which still needs to be discussed and is outside the bounds of this PR I think. Given this only fires off on WiFi which for most people is decently fast I think we can re-visit this issue in the future(very near I think as I'd like to see us take ideas from https://github.com/wordpress-mobile/WordPress-FluxC-Android and adapt them into iOS).
