### ISSUE TITLE
When user taps for details on a comment notification we should scroll them down to their actual comment instead

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#5540]
### Expected behavior

When a user opens up a comment notification and then taps on the detail button to load all the corresponding comments we should like the web scroll down to the corresponding comment.
### Actual behavior

Right now tapping on the detail button will load the comments but hang out at the top.
### Steps to reproduce the behavior
1. Open comment notification.
2. Tap on detail button at the top

**Comment by rachelmcr** [comment]
This was raised twice recently. Once in internal feedback (ref: p4a5px-1Pr-p2) and also in this comment:

https://en.blog.wordpress.com/2017/06/29/five-tricks/#comment-261324

**Comment by rachelmcr** [comment]
This came up again via in-app feedback (ref: 203363-h):

> Notifications are really clumsy in display, I would have expected a clear notification like in Facebook: person A commented on item A which could have been a hyperlink which when clicked should directly lead to my blog page where cursor or screen shown should have been the specific comment.

**Comment by designsimply** [comment]
Closed https://github.com/wordpress-mobile/WordPress-iOS/issues/11818 as a duplicate.

**Comment by designsimply** [comment]
Added this to `Prioritized iOS` in the Groundskeeping project.

**Comment by designsimply** [comment]
Leaving in Groundskeeping but removing the `[Pri] High` label at this time because other high priority issues are currently taking precedence.

**Comment by guarani** [comment]
Closed https://github.com/wordpress-mobile/WordPress-iOS/issues/15487 as a duplicate.
