### ISSUE TITLE
App crashes on splash screen during a slow launch

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5568]
### Expected behavior

I expect the app to open in a reasonable amount of time every time I open the app.
### Actual behavior

The app sometimes "crashes" while launching the app. It displays the splash screen for a long time and the app closes. This isn't a "real" crash — the crash logs include this exception note: `SIMULATED (this is NOT a crash)` — but it feels like a crash as a user. The application specific information in the crash log says, for example:

> org.wordpress.internal failed to scene-create after 18.59s (launch took 1.41s of total time limit 20.00s)

Another beta tester (Alex) has also seen this crash, and both of us noted that the app crashes 2-4 times in a row and after that it opens and works as expected. It also seems to happen after the app hasn't been used for a while.

I first noticed this crash while on a data connection on June 6 (using WPiOS beta 6.3.0.20160603.1). Alex noticed it while on flaky wifi with a vpn connection. This may be a factor in the crash, although I later saw the crash while on reliable wifi at home.

One time when the app crashed twice in a row on the splash screen, I checked the app logs (after I opened the app successfully on the third attempt) and I saw these entries between the time when I tried to launch the app and when it crashed:

```
2016/06/07 08:40:09:377 User-Agent set to: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Mobile/13F69 wp-iphone/6.3.0.20160603.1
2016/06/07 08:40:09:475 MediaService cleanUnusedMediaFileFromTmpDir
2016/06/07 08:40:09:513 deletePostsWithNoTopic, deleting topicless post: (entity: ReaderPost; id: 0xd000000011a8000c <x-coredata://A38807F9-A66C-455D-9051-D5BC903DF76B/ReaderPost/p1130> ; data: )
2016/06/07 08:40:09:515 deletePostsWithNoTopic, deleting topicless post: (entity: ReaderPost; id: 0xd00000001300000c <x-coredata://A38807F9-A66C-455D-9051-D5BC903DF76B/ReaderPost/p1216> ; data: )
2016/06/07 08:40:10:164 didFinishLaunchingWithOptions state: 1
```
### Steps to reproduce the behavior

I don't yet have reliable steps to reproduce this crash. It seems similar to #5566 (in that the app freezes and crashes while trying to re-launch it) but the crash happens on the splash screen instead of the editor.

**Comment by jleandroperez** [comment]
Closing for now. We haven't seen this one in a bit.

If needed, please, reopen. Thanks!
