### ISSUE TITLE
App crashes on launch on iOS 10

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#5570]
### Expected behavior

Until the final release of iOS 10 this fall, we'll likely have real users on the iOS 10 public beta who might want to use WPiOS. The app should at the very least run without crashing.

### Actual behavior

The app currently crashes on launch when run on iOS 10 (built against the iOS 9 SDK). 

### Steps to reproduce the behavior

Install the latest internal build / `develop` on a device running iOS 10. The app crashes on launch.

##### Tested on iPad Pro 9.7, iOS 10, WPiOS 6.3 / `develop`

**Comment by sendhil** [comment]
This is resolved in #5573.
