### ISSUE TITLE
Native Editor Master Issue

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#5578]
This issue serves as the master issue for a visual editor refresh that will shift from a hybrid approach to a native approach. The goal of this refresh is to create a first class editor experience by considering how a native editor environment might look and work, and determine if it is feasible. Look at ways to dramatically enhance the editor experience on tablets (multitasking, split view, external keyboard).

**Comment by astralbodies** [comment]
I'm closing this master issue in favor of project https://github.com/wordpress-mobile/WordPress-iOS/projects/5
