### ISSUE TITLE
iOS 10 Widget Support

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#5580]
iOS 10 added a lot of enhancements to Notifications that we should try to take advantage of. Let's explore creating a widget(or expanding the current Today widget) to best utilize these new enhancements.

**Comment by kwonye** [comment]
Also make sure all other widget issues are solved, including:

#3291
#2598
#4707
#4687
#3445
#2746
#2598

**Comment by ChrissiePollock** [comment]
More input:

> In iOS 10 beta 5 the super awesome handy Notification Center widget doesn't work. I removed and readied it, reinstalled the app, and reset all settings. None of that worked. Sooooooo yeah. Also, I love that the Mac app scales. I keep the stats up in a small vertical window. Very nice! A widget for Mac with the day's stats would be cool too. ;) <3

**Comment by kwonye** [comment]
Thanks for the report @ChrissiePollock. I'm looking into it, but iOS 10 is not gonna be prioritized until it is released.

**Comment by ChrissiePollock** [comment]
Any update on this? I have someone else asking, and when I add the widget, the screen is blank, even after I tap "today" and "use this site" from the stats portion of the app.

**Comment by kwonye** [comment]
@ChrissiePollock sorry about the delay. The next update will have it fixed (the first update since iOS 10 got released)

**Comment by jleandroperez** [comment]
Closing this one as duplicate of #5893.

Thanks everyone!

**Comment by kwonye** [comment]
@jleandroperez thanks for deleting as this was fixed, but I don't think it's a duplicate of #5893? It's about widgets, not notifications.

Just did notice Sendhil may have had a typo and said "notification" in the first part, that's why 😛

**Comment by jleandroperez** [comment]
Ahhhh you're right, sorry, my bad!!. Still, it'd probably be best to just open a new issue, whenever an enhancement over the Today widget (or a new thing) gets creen light.

Thanks for the feedback Will!
