### ISSUE TITLE
Analytics Audit

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#5581]
Let's perform an Analytics Audit as it's been a while. We should check for redundant events, consistency, and add in any missing events.

**Comment by kwonye** [comment]
Also, can we add Helpshift auditing to this please? I know there are a lot of things we can send as Helpshift metadata to help out our Happiness Engineers cc @rachelmcr

**Comment by bummytime** [comment]
Marking this as complete.

cc @sendhil
