### ISSUE TITLE
Reader: related posts

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-iOS#5592]
The Calypso Reader recently added a "related posts" feature which lists two posts related to the current one at the bottom of the detail view. This should be added to the mobile readers.

[Related Android issue](https://github.com/wordpress-mobile/WordPress-Android/issues/4259)

**Comment by nbradbury** [comment]
The endpoint for this is already available: `/read/sites/:site/posts/:post/related`

**Comment by gibrown** [comment]
An additional detail here is that the endpoint has traintracks info and it would be good to get those events firing for related posts per #5817 

Also, the traintracks render event should only fire when the related posts actually get shown on the screen.

**Comment by aerych** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/6358
