### ISSUE TITLE
iPad Refresh: Normalize modal presentation styles

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#5599]
We should audit the app to check whether we are presenting views in the correct manner on iPad – popovers vs form modals vs full screen modals vs pushed onto the navigation stack.

For example, the People filter picker should probably be a popover:

![simulator screen shot 23 jun 2016 14 15 13](https://cloud.githubusercontent.com/assets/4780/16304395/1a800dc6-394d-11e6-874b-c529ba899185.png)

### Current Issues

- [x] People / Filters: Should be a popover at all size classes (see also #3748)
- [x] Posts / Pages / Filters: Should use a popover at all size classes (see also #3748)
- [x] Small popovers like the above don't need navigation bars
- [x] Settings > Default Category > Add a category could be a modal
- [x] Post Settings > Set Featured Image could be a modal
- [x] Post Settings > Set Location could be a modal
- [ ] ~~Post Settings menu could either be a popover, a modal, or 'something else' (a sidebar that slides in from the right?)~~ Going to hold on this one for now.
- The whole notification section could do with a re-think regarding iPad support (particularly editing and replying to comments feels odd), but I'll leave that for another issue. We'll have to coordinate with @jleandroperez and the Notifications refresh (#5577).

**Comment by kurzee** [comment]
@frosty one area that might take advantage of a modal presentation is the `NotificationDetailsViewController` currently being pushed onto the navigation stack of the notifications tab. This view generally has little content and looks awkward on iPad full-screen.

**Comment by frosty** [comment]
@kurzee You're probably right here. I think the whole notifications section needs a big overhaul for iPad. However, we should probably wait to make any navigational changes here and see what @mattmiklic has in mind.

**Comment by jleandroperez** [comment]
@frosty at your service sir!

**Comment by frosty** [comment]
Closing this for now as #5599 covered all the low hanging fruit. Any other changes in this area will come as part of our [iPad design refresh](https://github.com/wordpress-mobile/WordPress-iOS/issues/5576).
