### ISSUE TITLE
Reader: View Likes for a post

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#5611]
It would be nice to be able to view a list of who liked a post, like you can on the web. Perhaps a long press or 3D Touch on the likes icon for a post?

**Comment by aerych** [comment]
And perhaps link to the primary blog of the user who liked. :) 

Fwiw, we don't currently support showing a list of who liked a post in the web reader. (We did that for a while but eventually removed the feature due to a perceived low end-user value.) That said, I see no reason why we couldn't do something like this in the app provided it doesn't compete with web parity.

**Comment by frosty** [comment]
> Fwiw, we don't currently support showing a list of who liked a post in the web reader

Huh, you're right. How weird, that I could've sworn we did and it was something I used regularly.

**Comment by rachelmcr** [comment]
Android does this by displaying the Gravatars of users who liked the post at the bottom of the post:

![2016-07-04 16 04 41](https://cloud.githubusercontent.com/assets/8658164/16566062/8de88c24-4209-11e6-9396-18406b07bed8.png)

Tapping on that row of Gravatars takes you to a list of the "likers":

![2016-07-04 16 02 56](https://cloud.githubusercontent.com/assets/8658164/16566125/fa0f8d44-4209-11e6-865b-7f60a0969477.png)

**Comment by rachelmcr** [comment]
Calypso web now (as of https://github.com/Automattic/wp-calypso/pull/24612) displays a popover in the Reader post detail view to see a list of the likers:

![image](https://user-images.githubusercontent.com/8658164/45204085-dc870c80-b286-11e8-9ad2-9970221d242a.png)

**Comment by thehenrybyrd** [comment]
This came up in #zen-1888950 - this user, like @frosty, remembers having and using such a feature previously.
Looks like this has come up before, as well: https://github.com/wordpress-mobile/WordPress-iOS/issues/4383

Would be nice to have!

**Comment by kean** [comment]
It does in the details; closing.
