### ISSUE TITLE
Analytics: Miscounting Signouts.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5615]
While doing some work on A/B testing I noticed that we're bumping `WPAnalyticsStatLogout` from three different places. 

The `ContextManager` [#](https://github.com/wordpress-mobile/WordPress-iOS/blob/6.2/WordPress/Classes/Utility/ContextManager.m#L223) 
The `BlogListViewController` [#](https://github.com/wordpress-mobile/WordPress-iOS/blob/6.2/WordPress/Classes/ViewRelated/Blog/BlogListViewController.m#L233)
The `WordPressAppDelegate` [#](https://github.com/wordpress-mobile/WordPress-iOS/blob/6.2/WordPress/Classes/System/WordPressAppDelegate.m#L980)

It looks like there are situations where the stat is being bumped at the wrong time. For instance, the instance in `BlogListViewController` is being bumped when the app is launched from a fresh start.  

Let's determine the correct behavior for bumping this stat and fix as a part of the upcoming audit. 
cc @kwonye, @sendhil

**Comment by kwonye** [comment]
Great looking out!
