### ISSUE TITLE
Reader: Minor image related glitch when rotating the post list

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5623]
Props @kurzee for the find. 
There is a minor UI glitch related to featured images that can sometimes be triggered when rotating the post list.  In certain situations it seems that the following occurs: 
- a cell is dequeued and assigned a post with a featured image. 
- the request to fetch the featured image starts
- the cell is scrolled away
- the cell is dequeued again and assigned a different post with no featured image
- the request to fetch the featured image completes and the (now hidden) imageView is assigned the image.

When this happen the cell in question has an image view with a zero height, so the loaded image isn't visible. However, the cell's geometry is alter during rotation in such a way as to allow for a glimpse of the loaded image. 

As far as bugs go its pretty minor, however configuring a cell with a new post should cancel any pending image loads so it would be nice to fix for that reason alone.

**Comment by hoverduck** [comment]
@aerych - This seems like another (more impactful) case of this issue.  But let me know if you think it's different enough and I'll move it to its own issue.

https://lookback.io/watch/GdkEEGgpA8rNoGfnN

**Comment by aerych** [comment]
Thanks @hoverduck. I think its likely the behavior in the lookback has the same root cause so just a note here is good.
