### ISSUE TITLE
Reader: Unfollowing a feed via a post menu fails if the siteURL doesn't match the feedURL.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5633]
This is a tricky bit with posts from external feeds.  The url we're storing for the siteURL doesn't always match the actual feedURL.  When this happens (examples: mashable, arstechnica) an unfollow performed via the "followed sites" post list will appear to succeed yet the feed is still being followed.

**Comment by ScoutHarris** [comment]
I was able to follow and unfollow arstechnica.com and cnn.com from Manage > Followed Sites. This looks to be resolved. (WPiOS 16.7)
