### ISSUE TITLE
iPad Refresh: Resolve unsatisfiable constraint with CircularImageView

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#5638]
Console warnings present when opening a split-view multitasking state on iPad for just about any usage of `CircularImageView.swift`.

Particularly, the Notifications tab presents this warnings, as do Comments.
### Steps to reproduce the behavior
1. Build and run the app on the simulator or device.
2. Navigate to the Notifications tab.
3. Minimize the app, or go to the home screen.
4. Open another app, such as Safari.
5. Slide from the right to open the most-narrow multi-tasking size with WordPress-iOS.
6. The Notifications tab should present as previously seen in full-screen.
7. The unsatisfied constraint warnings appear in the console.

Note: This only occurs with the most-narrow multi-tasking size, and not any other sizes. Likely because the constraint constant tolerances are too large or not adjusting.

**Comment by koke** [comment]
I just tried this and can't reproduce. Can you verify if this is still an issue?

**Comment by kurzee** [comment]
This no longer reproduces, all good.
