### ISSUE TITLE
Remove use of WPTableViewSectionHeaderFooterView in Plans.

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#5643]
Currently the Plans implementation has a peculiar use of `WPTableViewSectionHeaderFooterView` within: https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Plans/PlanListViewController.swift#L23

Moving forward with the deprecation of `WPTableViewSectionHeaderFooterView`, which is currently staged in the working branches of [feature/readability](https://github.com/wordpress-mobile/WordPress-iOS/tree/feature/readability) and [feature/shared-readability](https://github.com/wordpress-mobile/WordPress-Shared-iOS/tree/feature/shared-readability), the footer usage within `PlansListViewController` linked above will have to change, or be removed altogether.

**Comment by kurzee** [comment]
@frosty can you take a look at the usage mentioned above? If Plans is being scrapped altogether I suppose we can ignore it for now, if not, it would help a ton if we could refactor away from `WPTableViewSectionHeaderFooterView` to go along with the work on [feature/readability](https://github.com/wordpress-mobile/WordPress-iOS/tree/feature/readability).

**Comment by frosty** [comment]
@kurzee So that usage of `WPTableSectionHeaderFooterView` was because we wanted the footer view to be tappable, to take the user to our terms and conditions. Since we're dropping purchasing for the time being (but keeping plans) we can take this out. I'll get on it now!

**Comment by frosty** [comment]
I've updated this in a local branch (I've also updated the footer text to match Android) – two questions for you, @kurzee:

1) The appearance of a standard footer view (even when configured with `WPStyleGuide`) looks different to `WPTableSectionHeaderFooterView`. Are you aware of this / is this okay? Looks like the header padding is different too. See:

![footerchange](https://cloud.githubusercontent.com/assets/4780/16517378/f6cb2d7e-3f74-11e6-81bc-68efb56d4b4e.png)

2) As I said, I have these changes locally at the moment – do you want me to commit straight to `feature/readability`, or shall I open a PR targeting that branch?

**Comment by kurzee** [comment]
Thanks @frosty! The padding should now be using the default iOS setup and font size when returned via `tableView(tableView: UITableView, titleForFooterInSection section: Int)`.

Can you push your local branch and I can take a look? You could merge it into `feature/readability` if you'd like, as we will probably be pushing it there anyways.

**Comment by frosty** [comment]
Here you go: https://github.com/wordpress-mobile/WordPress-iOS/tree/feature/readability-plans

Because the view controller uses `ImmuTable`, there is some extra configuration going on with the header and footer, FYI: https://github.com/wordpress-mobile/WordPress-iOS/blob/feature/readability-plans/WordPress/Classes/Utility/ImmuTable+WordPress.swift

**Comment by kurzee** [comment]
@frosty thanks! We'll roll with the default padding behavior for now.

Merged into https://github.com/wordpress-mobile/WordPress-iOS/tree/feature/readability
