### ISSUE TITLE
Editor: Some images are set with a 0 width, height and so do not appear.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5652]
As [reported in the forum](https://ios.forums.wordpress.org/topic/cant-upload-photos-1?replies=6#post-14744):

> One thing I've noticed after uploading an image from with the app - I'll login, via web browser, click on the post I just made and look at it in Text View. Here I can see the the width and height values are set to "0". When I change those values to anything but "0", and Save, the image will then display properly in the post. 

I'm not sure the exact steps to reproduce, but it looks like the `onerror` callback defined in `ZSSEditor.replaceLocalImageWithRemoteImage` could result in an image with a zero width and zero height being passed to `ZSSEditor.markImageUploadDone`. It would probably make sense to check for non zero values before constructing the width and height attrs in `ZSSEditor.markImageUploadDone`.

**Comment by bummytime** [comment]
Closing this since the old visual editor is retired and I am unable to repro. 🎉
