### ISSUE TITLE
People: Pull to refresh user list does not remove users who were deleted

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5675]
### Expected behavior

While viewing the list of users on a site, pulling down should refresh the list of users:
- Add new users who were added to the site
- Remove users who were deleted from the site
- Update user details (display name, role, etc.)
### Actual behavior

Pulling down to refresh works to see new users added to the site and update existing user details. However, it does not remove users who were deleted from the site.
### Steps to reproduce the behavior
1. With a site that has multiple users, go to My Site > People in the app
2. Make sure you are viewing the list of users on the site in the app
3. In a web browser, go to https://wordpress.com/people/team
4. Select a user and remove them from the site
5. In the app, pull down to refresh

Expected: The deleted user is removed from the user list
Actual: The deleted user remains in the list, and:
- If you tap on that deleted user, you can still view the user details.
- Trying to change the user's role results in an error.
- If you try to remove the user again in the app you are returned to the user list and the deleted user is still there.

**Comment by hoverduck** [comment]
Note that while pulling to refresh doesn't remove the user, navigating to another section and back does accurately refresh the list.

**Comment by rachelmcr** [comment]
This came up again in a user report (p4a5px-2jh-p2) and the fix mentioned above (navigating to another section and back) no longer works. Even after logging out of the app and logging in again, the deleted user remains on the site.

**Comment by SiobhyB** [comment]
This came up again in 1677309-z.
