### ISSUE TITLE
Reader Search: Can't fully scroll or clear saved searches in landscape view on iPhone

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5679]
### Expected behavior

When searching the Reader, I expect to be able to view all saved searches and clear them regardless of whether I'm holding my phone in portrait or landscape.

### Actual behavior

If I rotate my phone to landscape view, I can't scroll to the bottom of my saved searches or get to the "Clear search history" link because my keyboard is in the way:

![2016-07-08 17 32 05](https://cloud.githubusercontent.com/assets/8658164/16694471/61361922-4532-11e6-9c24-0d277661d9e3.png)

If I dismiss my keyboard, the search field loses focus:

![2016-07-08 17 32 09](https://cloud.githubusercontent.com/assets/8658164/16694472/63c6fa26-4532-11e6-95c0-c656786617ab.png)

Portrait view for comparison:

![2016-07-08 17 28 34](https://cloud.githubusercontent.com/assets/8658164/16694475/6b43ba50-4532-11e6-9f3b-7817211779c2.png)

### Steps to reproduce the behavior

1. On an iPhone in portrait view, open the Reader in the app
2. Tap the search icon to start searching
3. Do at least 5 searches (to fill the search history list)
4. Tap the search field as if starting a new search, and note that you can see all of your previous searches and a "Clear search history" link at the bottom of the list
5. Rotate your phone to landscape view and note that the bottom of the list and "Clear search history" link are hidden under your keyboard
6. Dismiss the keyboard and note that the search field loses focus and the past searches disappear.

**Comment by aerych** [comment]
Good catch!
