### ISSUE TITLE
Share Extension: Change action to "Save" for drafts

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#5680]
### Expected behavior

From Photos, I went to share an image to my WordPress.com site, but I wanted to set it up as a draft first instead of publishing it right away. I changed the status to Draft, and I expected the action to change to "Save" or something other than "Post."
### Actual behavior

The action stayed as "Post," which made me very uneasy. It actually did save it as a draft, but I was very hesitant.
### Steps to reproduce the behavior
1. Open Photos on your device.
2. Click on a photo and use the Share option
3. Select "WordPress"
4. Change the "Post Status" to "Draft." The action will still say "Post."

![img_3248](https://cloud.githubusercontent.com/assets/7240478/16701822/9659baae-451f-11e6-99b7-c23d4afa2e44.jpg)

**Comment by elibud** [comment]
Currently we are using Apple's UI for the Share Extension and we have no control over the two buttons at the top. Similar to https://github.com/wordpress-mobile/WordPress-iOS/issues/5190
