### ISSUE TITLE
Share Extension: Automatically scroll me up when typing in landscape

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#5681]
### Expected behavior

I was using the Share extension in landscape mode. The landscape orientation on an iPhone 6 means that I can actually scroll down a bit so that the first line of text in the post is out of view. I expected that if I started typing though, the app would automatically jump me up.
### Actual behavior

I couldn't see the first line I was typing.
### Steps to reproduce the behavior
1. Open up the Photos app
2. Use the Share extension to share to the WordPress app
3. Turn your device to landscape mode.
4. Without typing anything, use your finger to scroll down so that the top line is out of view.
5. Start typing. You will still be adding text to the top line, but you can't see it until you scroll up. I thought it would auto-scroll me.

Here's a screencast:

https://cloudup.com/cPYy9P3jzXI

Here's a screencast of the expected behavior on Facebook sharing:

https://cloudup.com/cyJP5juy2et

**Comment by yaelirub** [comment]
Sharing through the app doesn't look like the described anymore and the app automatically jumps to the title when typing. Closing this. Please reopen if necessary
