### ISSUE TITLE
Sharing: Requires two toggles to activate/deactivate a sharing button

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#5682]
### Expected behavior

I turned on the Facebook sharing button on my self-hosted site, and I wanted to actually toggle that button off. I toggled on the "Edit sharing buttons" option. The Facebook button was correctly toggled on. I thought I could just click the toggle to turn off the Facebook sharing icon.
### Actual behavior

I clicked the toggle to turn it off, but it immediately switched back on. It only turned "off" after the second time toggling it.

The same behavior exists for turning services on (it requires two toggles).
### Steps to reproduce the behavior
1. Open up the sharing settings for a Jetpack site
2. Click "Manage" to change the sharing buttons
3. Toggle on "Sharing Buttons" to edit the selected services
4. Either A) try to toggle on a non-selected button or B) try to toggle off a selected button. The toggle will immediately reset to the previous value and require two toggles.

Screencast:

https://cloudup.com/c2SagJboyRI

**Comment by hoverduck** [comment]
It looks like this is a timing issue when first opening the page.  If you watch closely in this GIF you can see the screen pulse slightly just a second or two after toggling "Edit sharing buttons", which seems to indicate when it's refreshed the settings from the web.  If you toggle any service before that happens, then they're reset to the previous setting when the refresh is complete.

![ios-toggle-sharing](https://cloud.githubusercontent.com/assets/7233112/22336077/06d42b88-e3af-11e6-9fb0-149cd1452ebf.gif)
