### ISSUE TITLE
Blog list filter audit

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#5685]
Every place there is a blog list, there should be a filter.

**Comment by koke** [comment]
Can you explain what you mean by filter? If it's search, I think we already show it both on the my sites list and the blog selector. Is there any other blog list I'm missing? Or was this resolved already?

**Comment by kwonye** [comment]
Yes, I meant search, sorry. I haven't done a full audit of the entire app so I trust your judgement there.

If there is a search in every place where sites are listed, feel free to close, thanks!

**Comment by koke** [comment]
The only place I see it missing is the Share extension, but that's tracked in #5779. \o/
