### ISSUE TITLE
Share Extension: Image is not added to post for Jetpack-linked site

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5688]
### Expected behavior

I expect to be able to share an image to WordPress.com and Jetpack-linked sites with the WordPress share extension.

### Actual behavior

I can share an image to WordPress.com sites, but when I share it to Jetpack-linked sites the image is uploaded to the media library and attached to the post, but not inserted into the body of the post.

This results in two issues:
- If I don't add any text in the sharing prompt, no post is created (because there is no content in the post) but the image is uploaded to the site's media library
- If I add text in the sharing prompt, it creates a post with that text and an image format, and the image is uploaded to the site's media library, but there is no image in the post itself

### Steps to reproduce the behavior

1. Open the Photos app
2. Select a photo and tap the sharing icon
3. Select the WordPress app as the sharing target
4. Select to post to a self-hosted Jetpack-linked site
5. Without adding any text, select "Post" to publish the post. Result: No post is created, but the photo is uploaded to the site's media library
6. Repeat the steps above, but add text in the sharing prompt before publishing the post. Result: A post is created with that text, but the photo isn't added to the post.

**Comment by rachelmcr** [comment]
@jleandroperez I just want to make sure this issue is on your radar, since it's a big one for media in the share extension.

**Comment by jleandroperez** [comment]
Hi there @rachelmcr !!

Thanks **SO MUCH** for bringing this one to our attention!. I've been tracking this down for the past few days, down to the WordPress.com API (which we've just patched + deployed).

Should be good now (with the current build), no need to further patch the client.

You rock!!!
