### ISSUE TITLE
Jetpack/Stats: Install Jetpack button leads to authentication error

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5692]
### Expected behavior

When I tap the "Install Jetpack" button on the Stats screen (for a self-hosted site), I expect to be taken to my site's WP Admin dashboard where I can install Jetpack.
### Actual behavior

I am taken to my self-hosted site's login screen, with an authentication error:

> ERROR: The password you entered for the username [self-hosted username] is incorrect. Lost your password?
### Steps to reproduce the behavior
1. Add a self-hosted site without Jetpack to the app
2. Go to My Sites > Stats
3. Tap the "Install Jetpack" button on the Stats screen

Result: The WP Admin login screen appears with your self-hosted site's username and a password error.
### Screenshots

https://cloudup.com/csNM1lm78dE

**Comment by rachelmcr** [comment]
I tested with the same site in the stable 6.3 release and confirmed the same behavior occurs there, so this isn't a new issue in 6.4.

**Comment by hoverduck** [comment]
@rachelmcr - I just tried this in the latest internal build and wasn't able to reproduce (I was logged into wp-admin and able to install Jetpack).  Can you give it another try?

**Comment by rachelmcr** [comment]
I can't reproduce this anymore, either; closing the issue.
