### ISSUE TITLE
Plans: Add Google Analytics to Business plan description

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5694]
### Expected behavior

I expect to see the full list of Business plan upgrades, as listed here:

https://wordpress.com/pricing/
### Actual behavior

The list of upgrades in the Business plan is missing Google Analytics:

![Business plan](https://cldup.com/V__6ViatIU.thumb.png)
### Steps to reproduce the behavior
1. Go to My Sites > Plans in the app
2. Select Business

**Comment by hoverduck** [comment]
I can see the features listed for the Business plan now.  Closing.
