### ISSUE TITLE
Menus: Swipe to delete menu items

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5698]
### Expected behavior

I expect to be able to swipe left to delete menu items in a custom menu. (This is especially reinforced by the ability to swipe left to delete elsewhere in the app, e.g. comments.)
### Actual behavior

I have to tap on a menu item and then tap the trash icon to delete it from the menu.

Jeremey also tested deleting menu items and noted that the trash icon appears for new menu items as you create them, too:

> I also found it weird that the “Delete” icon is present when you’re adding a new menu item. I expected “Cancel” to be there to stop my action, but since I haven’t actually created the item yet, “Delete” feels weird. I thought “Delete” would only show up when I clicked on existing items.
### Screenshots

![Custom menu](https://cldup.com/iq092TY75s.thumb.png)

![Delete menu item](https://cldup.com/5-ywAQLmMQ.thumb.png)
##### Tested on iPhone 6, iOS 9.3.2, WPiOS 6.4.0.20160707.1

h/t Jeremey for also testing this and contributing to this feedback

**Comment by hoverduck** [comment]
To further confuse things if I do try to swipe, the menu items are instead nested beneath the previous entry.  I think that interaction makes sense when dragging items around via the hamburger icon on the right, but outside of that it's a little disorienting.

![ios-menus-swipe](https://cloud.githubusercontent.com/assets/7233112/22347595/81bfa9b8-e3d6-11e6-8004-1c63b8dc2aae.gif)
