### ISSUE TITLE
3D Touch New Photo Post uses photo "default"

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#5701]
Per @p3ob7o

"Allow user to define what a “default” photo post is on their blog as that’s not a notion that exists in WordPress per se : in my case for instance: set image format, add “photo” category. Others may have “set photo as featured image”, etc."

Details, additional info has to be hashed out, but should be do-able.

**Comment by kwonye** [comment]
SImilar to #5700

**Comment by yaelirub** [comment]
Closing as this is not worked on / or planned  for 3-4 years. Please reopen if necessary
