### ISSUE TITLE
Stats: Slight discrepancy in block title positioning

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#5712]
### Expected behavior

I was viewing the various blocks on the Stats page in the app for my WordPress.com site. I expected the titles of those blocks (Latest Post Summary, Today's Stats, Most popular day and hour) to be aligned.
### Actual behavior

Everything up to Posting Activity is pushed nearly flush to the left. Starting at Comments, the title text is pushed a tiny bit farther to the right. It's pretty tiny, but it doesn't appear to be lined up consistently.

<img width="415" alt="screen shot 2016-07-13 at 09 31 19" src="https://cloud.githubusercontent.com/assets/7240478/16809293/fd316374-48dc-11e6-9c81-0bd29bd2714e.png">

**Comment by mattmiklic** [comment]
Good catch!

- Everything on the Daily/Monthly/Yearly pages looks good, the title is consistent with the text in each card.
- The "Latest Post Summary," "Today's Stats," "All-time posts, views, and visitors," "Most popular day and hour," and "Posting Activity" headers all need to be updated to match the others.
