### ISSUE TITLE
Resolve (if possible) Bitcode Mach-O Binary Issues

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5715]
When submitting a binary to Apple (since roughly around WWDC 2016 in June) we fail iTunes Connect validation because some of our compiled frameworks do not have Bitcode enabled. A valid bitcode enabled iOS app requires all included frameworks and static libraries to have Bitcode enabled.

![2016-07-14_08-02-42](https://cloud.githubusercontent.com/assets/373903/16840275/5a227d4a-4999-11e6-874d-4a93836c6958.png)

A temporary solution is to uncheck "Include Bitcode" in the iTC binary uploader from Xcode.

However at some point in the future Apple will be requiring Bitcode for iOS apps much like they already do for watchOS and tvOS apps.

Figure out the right way to enable Bitcode on all of our pods (if possible) and eliminate any pods where Bitcode is preventing an upload.

Related: https://forums.developer.apple.com/thread/48071
Related: https://stackoverflow.com/questions/37613550/xcode-error-itms-90635-invalid-mach-o-in-bundle-submitting-to-app-store/37624641#37624641

**Comment by jleandroperez** [comment]
@astralbodies is this one still relevant?

**Comment by astralbodies** [comment]
I think eventually we'll need to get Bitcode working - right now we're not uploading it when we submit to Apple. We may be able to close this issue for the meantime.

**Comment by jleandroperez** [comment]
Closing for now then, thanks!
