### ISSUE TITLE
Self hosted sites show as out of date

### ISSUE THREAD

**Issue by Tarendai** [wordpress-mobile/WordPress-iOS#5732]
### Expected behavior

When I tap on a site I expect to be shown the sites screen

### Actual behavior

It shows the screen then a modal pops up indicating the site is on v3.6 and 4.0 is needed. The site in question is on the latest version ( 4.5.3 ) at the time of writing

### Steps to reproduce the behavior

Use the latest test version and select a self hosted site in the my sites section

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 6, iOS 9.3.2, WPiOS 6.4

**Comment by aerych** [comment]
cc @astralbodies, @SergioEstevao

**Comment by aerych** [comment]
Related:  A similar issue was [reported in the iOS forums](https://ios.forums.wordpress.org/topic/wordpress-version-too-old-warning).  The report in the forum mentions the issue affects the 6.2 client when signing into a multisite running WP 4.5.2.

**Comment by Tarendai** [comment]
I can verify it's a multisite installation being used

**Comment by aerych** [comment]
@Tarendai, it would be helpful to know what the blog in question returns for the `version` key from the wp.getOptions XML-RPC endpoint.

**Comment by aerych** [comment]
I've been unable to reproduce the error on my test blog running the 4.6 alpha. I'm not seeing anything in core trac that suggests it was a recognized bug and patched so I assume there is some x-factor I'm missing. 

@Tarendai can you still reproduce the error?

**Comment by aerych** [comment]
Did a bit more testing on @Tarendai's blog (many thanks sir!) but neither of us are able to repro the error now.
Hard to say for sure but maybe this was a temporary conflict with a plugin that has since been updated? 
I'm not quite ready to write it off so leaving the issue open (for now) in case we learn new details or catch it happening again.

**Comment by aerych** [comment]
I've seen this twice on my test blog this morning.  Its a self-hosted multi-site blog connected to Jetpack.

**Comment by aerych** [comment]
Okay. I've been able to reproduce this in the Simulator and did some debugging.
The app is sending a query to the WPcom REST API's `/v1.1/sites/%s` endpoint to get blog options.  The options returned do *not* include the `software_version` item.  When the results are passed to `[RemoteBlogOptionsHelper mapOptionsFromResponse:]` a *default* `software_version` key is added to the options dictionary with a value of `3.6`.  

This appears to be an API side bug that we can address there.  That said, the 3.6 default doesn't make much sense to me.
