### ISSUE TITLE
Nonexistent site claims I have no internet connection

### ISSUE THREAD

**Issue by tomjn** [wordpress-mobile/WordPress-iOS#5733]
I used to have a site that I connected to Jetpack which has long since gone. It still appears in my .com interface with a warning that it's unreachable. Here I attempted to load it in the new WP 6.4 app
### Expected behavior

A notice that the site is unreachable
### Actual behavior

A notice that my device has no internet connection
### Steps to reproduce the behavior

Load a self hosted Jetpack site in the app that has been taken down or offline
##### Tested on [device], iOS [version], WPiOS [version]

iPhone 6, iOS 9.3.2, WPiOS 6.4

**Comment by aerych** [comment]
cc @astralbodies, @SergioEstevao

**Comment by hoverduck** [comment]
Closing...as of right now I get a reasonable error message saying that the Jetpack site is inaccessible.  But in testing I did come across a new error - https://github.com/wordpress-mobile/WordPress-iOS/issues/6479
