### ISSUE TITLE
I cannot connect my Wordpress using IOS or Android. Its and error and message is : We are not able to login into your wordpress.

### ISSUE THREAD

**Issue by formulamasa** [wordpress-mobile/WordPress-iOS#5741]
Someone can help me how to allowed my wordpress to login using IOS and Android. Thanks

**Comment by rachelmcr** [comment]
Please go to the Me tab (the person icon in the app's navigation bar), tap "Help & Support," and tap "Contact us" to contact our support team. That way they can gather more information about your WordPress and help you log in.
