### ISSUE TITLE
iPad Splitview Master Issue

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#5743]
This issue serves to organise our splitviewification of the app. We'll begin converting the various sections of the app to use split views, with the following assumptions:
- Using native `UISplitViewController`, as it'll take care of most adaptability cases for us (and is highly configurable these days)
- Looking to system apps and Calypso for guidance
- Keeping top level navigation for a specific section in the left pane, and subsequent navigation through the right pane.
- This is a first pass, and whatever we do we should end up with a better iPad experience than we currently have. Once we've introduced split views to the app, we can refine the experience later.

We'll transition each section individually (as we'll be keeping the tab bar and switch between each one as we currently do):
### Progress
- [x] My Sites
- [x] Reader
- [x] Me
- [x] Notifications (Wrapping up)
- [ ] Editor
### Issues / Queries

We'll fill this out if / when we hit specific problem areas.

**Comment by kurzee** [comment]
@frosty can probably close this one out shortly

**Comment by frosty** [comment]
@nheagy Yeah, as good as can be for now – I'll close it 👍
