### ISSUE TITLE
Posts: New draft posts not saved as local draft if the device is offline

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5745]
### Expected behavior

If my device is offline (no internet connection), and I try to create and save a new post as a draft, I expect the app to save the new post as a local draft.
### Actual behavior

If my device is offline, and I try to create and save a new post as a draft, the post is not saved at all.
### Steps to reproduce the behavior
1. Disconnect the device from the internet (e.g. put it in airplane mode)
2. Open the editor to start a new post
3. Enter some text in the new post
4. Tap to exit the editor and select "Save Draft" or go to the post settings, change Status to "Draft" and tap Save in the editor

Result: The editor closes, the error message "Error occurred during saving" appears, and the draft is completely gone (not saved as a draft under any post filter).

**Comment by jeffpaul** [comment]
I've actually seen this work as expected and save a local copy to my device (AT&T MN592LL/A iPhone 7 Plus running iOS version 10.1.1 (14B100) and WPiOS version 6.7). Are you still seeing the issue on your end @rachelmcr?

**Comment by rachelmcr** [comment]
Thanks for the nudge! I re-tested in the latest 6.8 beta and can confirm that the post is now saved as a local draft, as expected. Closing the issue as resolved.
