### ISSUE TITLE
Blog Posts/Pages: App crashes if you try to delete a post from the trash while offline

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5746]
### Expected behavior

If my device is offline (no internet connection), and I try to delete a post or page, I expect to get an error about having no internet connection.
### Actual behavior

If my device is offline, and I try to delete a post or page, the app crashes.
### Steps to reproduce the behavior
1. Make sure you have at least one blog post or page in your site's trash
2. Disconnect your device from the internet (e.g. enable airplane mode)
3. Go to your site > Blog Posts or Pages > Trash filter
4. Permanently delete a post or page

Result: The app crashes

**Comment by bummytime** [comment]
Closing this issue...retested in the latest internal (8.1.20170724) and no connection dialog appears as expected:

<img width="190" alt="napkin 44 07-26-17 1 05 45 pm" src="https://user-images.githubusercontent.com/154014/28636309-5c0c7af0-7203-11e7-9fc8-7a464bd31427.png">
