### ISSUE TITLE
My Sites: Layout glitch on login screen when an error occurs while adding a self-hosted site

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5747]
### Expected behavior

While adding a self-hosted site to the app, I expect the cancel link (on the login screen) to stay the same before and after an error occurs.

### Actual behavior

If an error occurs while adding a self-hosted site to the app, the login screen layout glitches and a back arrow overlaps the Cancel link on the login screen.

![2016-07-20 16 35 59](https://cloud.githubusercontent.com/assets/8658164/16993171/8af74802-4ea2-11e6-8e44-6223fb7f1226.png)

### Steps to reproduce the behavior

1. Go to the My Sites tab in the app
2. Tap the arrow in the top right and select "Add self-hosted site"
3. Do something to bring up an error overlay, e.g. try to log in while offline, or enter invalid credentials
4. Dismiss the error overlay

Result: You will see a back arrow added to the login screen, overlapping the Cancel button

**Comment by aerych** [comment]
Facinating
