### ISSUE TITLE
Ensure that all site selections in the app have a filter just like WordPress.com

### ISSUE THREAD

**Issue by sendhil** [wordpress-mobile/WordPress-iOS#5757]
![simulator screen shot jul 20 2016 6 53 25 pm](https://cloud.githubusercontent.com/assets/437043/17008982/47ead188-4eab-11e6-995b-e7d8f43f9958.png)

vs

![simulator screen shot jul 20 2016 6 54 38 pm](https://cloud.githubusercontent.com/assets/437043/17042287/2208e0a2-4f61-11e6-9339-016c2147cc57.png)

**Comment by astralbodies** [comment]
@sendhil Your second screenshot never finished uploading 😢

**Comment by sendhil** [comment]
Woops...

**Comment by sendhil** [comment]
Fixed!

**Comment by astralbodies** [comment]
@jleandroperez Something easy enough to add to the share extension maybe?

**Comment by jleandroperez** [comment]
@astralbodies sure thing! filed a specific issue for the Share Extension: #5779.
