### ISSUE TITLE
Plans: Improve the error message if the user is offline

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5758]
### Expected behavior

If the app can't load the Plans screen because the device is offline, I expect an error message that clearly explains that.

For example, this is the on-screen error on the Stats screen if the device is offline:

> No Connection
> An active internet connection is required to view stats
### Actual behavior

If I'm offline, I get a generic "oops" error message:

> Oops
> There was an error loading plans
> Contact support
### Steps to reproduce the behavior
1. Disable the device's internet connection (e.g. enable airplane mode)
2. Go to My Site > Plans
#### Screenshots

Error message on the Plans screen:

![2016-07-20 16 36 25](https://cloud.githubusercontent.com/assets/8658164/17016996/da15b330-4f31-11e6-9ffb-28e6a274034c.png)

Error message on the Stats screen:

![2016-07-20 16 36 14](https://cloud.githubusercontent.com/assets/8658164/17017004/e2b969a0-4f31-11e6-9b23-1c80a3ce0cdb.png)

**Comment by hoverduck** [comment]
Closing, this has been fixed
