### ISSUE TITLE
Reader: Post detail shows a trailing slash after the site domain

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5766]
Props @ebinnion for the report.
Example:
![simulator screen shot jul 21 2016 3 45 58 pm](https://cloud.githubusercontent.com/assets/1435271/17038218/4b9673e6-4f5a-11e6-8042-09003f9dc3be.png)

**Comment by ScoutHarris** [comment]
This has been fixed. No "/" appears.
