### ISSUE TITLE
Geolocation can be lost when editing a draft post

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5774]
As [reported in the forums](https://ios.forums.wordpress.org/topic/porblems-with-set-location?replies=1).

> I have a problem with Geo Locations in the Wordpress for iOS Version 6.3.1 on iOS 9.3.3
> 
> Editing a Blog Post in Status Draft, I open der Options Dialog and push 'Set Location', all works fine. The client found my current location, show a local map, the Address of the location and the right coordinates.
> 
> Then I push Done and go back to the Post and Save it. If I open it again for editing it shows in the Options Dialog the location 'North Atlantic Ocean' with the coordinates 0 North an 0 East.
> Where is my location gone? 

I was able to reproduce a similar issue via the following steps:
- In the app, start a new post.
- Enter a title and a line of content. 
- Open post settings.  
- Set the status to "Draft"
- Add my current location. 
- Notice that post settings displays a map of my current location. 
- Save the draft post. 
- Edit the post again.
- Open post settings. 
- Notice that post settings no longer displays a map as location information is not present in the draft.

**Comment by ChrissiePollock** [comment]
Similar issue on #129728-h 

> Offline Recording of Location is not possible as it becomes updated when reopening an article.

>

**Comment by ScoutHarris** [comment]
This is resolved. The draft post now retains the location.
