### ISSUE TITLE
Share Extension: Search Filter

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#5779]
#### Details:

As part of #5757, let's implement `UISearchController` in the Share Extension's Blogs Picker.

cc @astralbodies 

Open Safari > any website
Open the Share Sheet > WordPress
You should have the Share Extension Onscreen
Press Next (top right)
Blog Picker onscreen - This is where we'd want to add the UISearchController

**Comment by yaelirub** [comment]
Close as won't fix - no user requests and rarely used feature
