### ISSUE TITLE
Posts List: no results view covered by header with search

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#5803]
On iPhone 4S, the new inline search bar creates space that now overlaps `WPNoResultsView` a bit in `AbstractPostListViewController` (Blog Posts).

This could be something not necessarily worth solving, particularly because iOS 10 drops support for 3.5 inch screens.

![simulator screen shot jul 28 2016 3 18 32 pm](https://cloud.githubusercontent.com/assets/1873422/17228091/334ca238-54d7-11e6-949c-1982f30d87d5.png)

**Comment by aerych** [comment]
Dup of https://github.com/wordpress-mobile/WordPress-iOS/issues/5765 :)

**Comment by kurzee** [comment]
Ahhhh, whoops! Thanks @aerych!
