### ISSUE TITLE
Fix the spacing around the preview link

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5804]
### Expected behavior

We removed the preview eye icon in #5772, so I expect to see a Preview link evenly spaced with other elements in the editor.

### Actual behavior

The spacing around the Preview link is wonky.

Editing a draft, the cog icon is closer to the Preview link than the Update link:

![2016-07-28 20 58 10](https://cloud.githubusercontent.com/assets/8658164/17250473/6cb90668-559c-11e6-86cf-8238556a7481.png)

Uploading media in a saved draft, same issue with the cog icon and I noticed that the uploading spinner overlaps the "Uploading" text (not sure if that's related to this Preview link change):

![2016-07-28 20 58 33](https://cloud.githubusercontent.com/assets/8658164/17250483/763d2458-559c-11e6-83e0-ef4314d923d8.png)

On the preview screen when you tap the post card in the post list, the Preview link is closer to the Edit link than to the Share icon:

![2016-07-28 21 36 49](https://cloud.githubusercontent.com/assets/8658164/17250490/7b99e5f8-559c-11e6-9992-12f637c7b8f6.png)

cc @kwonye 

##### Tested on iPhone 6, iOS 9.3.3, WPiOS 6.4.0.20160728

**Comment by kwonye** [comment]
![2016-07-28 21 36 49](https://cloud.githubusercontent.com/assets/8658164/17250490/7b99e5f8-559c-11e6-9992-12f637c7b8f6.png)

@rachelmcr can you tell me how you got to this screen please?

**Comment by aerych** [comment]
@kwonye, current release/6.4 branch.  I can repro just by uploading an image. 

![simulator screen shot aug 2 2016 2 54 56 pm](https://cloud.githubusercontent.com/assets/1435271/17343002/3f146a22-58c1-11e6-8e3e-8a8521362495.png)

cc @sendhil, blocker perhaps?

**Comment by kwonye** [comment]
Thanks @aerych I'm working on it right now. Will have a patch up later today 👍

**Comment by rachelmcr** [comment]
@kwonye To get to that screen, I opened the Blog Posts section for a site and tapped on a post's card (e.g. on the featured image, the title, or the excerpt for the post in the list of posts). That opens the preview screen from that screenshot.

**Comment by astralbodies** [comment]
@kwonye Did this get patched? I can move it to 6.6 otherwise.

**Comment by kwonye** [comment]
It did, thanks @astralbodies. Closing.

**Comment by kwonye** [comment]
Better implementation done immediately after with #5849
