### ISSUE TITLE
Post deletion / undoing in offline mode is not working right

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#5811]
### Expected behavior

Deleting posts, and undoing the deletion (with no connection) should result in the post being "restored" locally.
### Actual behavior

There's a combination of steps in which the post may end showing up as deleted, even though it's not.
### Steps to reproduce the behavior
1. Open the app and go to the list of posts for any blog.
2. Set up link conditioner for 100% loss.
3. Delete a post, and undo the deletion right afterwards.
4. The post should be restored... now wait until the initial request times out.
5. Voila - the post will show up as deleted.
### Technical information

This is caused by the user being able to delete a post (tap Trash) and restore it (tap undo) even if there's no connection.

The sequence goes like this:
- When the user taps "Trash" a post deletion request is sent [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift#L820).
- When the user taps "Undo" a post restore request is sent [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Post/AbstractPostListViewController.swift#L855).
- (Remember there's no connection)
- The first request fails and [this](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Services/PostService.m#L318) closure is executed restoring the post.
- The second request fails and [this](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Services/PostService.m#L387) closure is executed showing the post as deleted (even though it isn't).

Part of the problem is [this property](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Models/AbstractPost.h#L49), which works fine for a single request, but fails to store proper history when several requests are chained.
##### Tested on the Simulator, iOS 9.3 iPhone 5, WPiOS 6.4

/fyi @sendhil, @aerych (check out the tech section if you can, I believe we may need to block multiple requests at the GUI level).

**Comment by kean** [comment]
Fixed in the scope of https://github.com/wordpress-mobile/WordPress-iOS/pull/21907 and https://github.com/wordpress-mobile/WordPress-iOS/pull/21724. Post deletion now works the same way as all other actions on posts: with no optimistic UI. And there the "Undo" was also removed to simplify the screen, as practically nobody was using it.
