### ISSUE TITLE
Plans: Personal plan is missing an icon and listed out of order

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5813]
### Expected behavior

I expect the Personal plan to appear between the Free and Premium plans, with its own icon

### Actual behavior

In the Plans section, the Personal plan appears at the end of the list of plans (below Business) without an icon:

![2016-08-01 11 13 06](https://cloud.githubusercontent.com/assets/8658164/17291001/4a64a4d4-57d9-11e6-999d-d6208756bf9b.png)
![2016-08-01 11 13 10](https://cloud.githubusercontent.com/assets/8658164/17291002/4a6869c0-57d9-11e6-908d-861190572316.png)

cc @frosty

**Comment by rachelmcr** [comment]
Pen icon I see for the Personal plan in Calypso web:

<img width="699" alt="screen shot 2016-08-01 at 11 17 30 am" src="https://cloud.githubusercontent.com/assets/8658164/17291064/a5ecbecc-57d9-11e6-85b4-597b3d2ef9c6.png">

**Comment by kwonye** [comment]
Order fixed by @frosty 

Icon fixed by @rodrigoi

![img_5110](https://cloud.githubusercontent.com/assets/1158819/17447139/71041d2c-5b12-11e6-8404-f95e9a2d95b1.PNG)
