### ISSUE TITLE
Only show ReplyView in CommentViewController if the post allows comments

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#5815]
### Expected behavior

When a post does not allow comments, there should not be a reply textview.
### Actual behavior

A post that does not allow comments shows the reply textview, where you can type and attempt to submit a response, only to get an error message back.
### Steps to reproduce the behavior
1. Open a post that has comments but does not allow comments anymore
2. See that there is a textview for responding to the post

**Comment by hoverduck** [comment]
@kwonye - Is this bug referring to a post in the Reader, or from the Comments page on My Sites?

If it's the Reader, it looks like it's fixed.  I don't have an option to reply to a post that has comments disabled.

If it's the Comments page, I'm able to select a comment and post a reply, but I'm just given a generic error message:
![ios-comments-reply](https://cloud.githubusercontent.com/assets/7233112/22348393/7ac2af9a-e3d9-11e6-8d6c-de8801c77a87.gif)

**Comment by kwonye** [comment]
@hoverduck that latter one is the issue I'm talking about. Thanks for the gif!

**Comment by ScoutHarris** [comment]
This is still an issue, but a bit different. The reply is actually successful, no error is shown.

- Comment on a post.
- Disable commenting on the post.
- Go to My Site > Comments.
- Tap a comment on the closed post.
- Enter a reply.
- `Reply Sent!` toast message is displayed.
- The reply appears in the Comments list.
