### ISSUE TITLE
Search: Pages search bar vanishes when double-tapping

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#5819]
### Expected behavior

The search bar sticks around. 🗿 
### Actual behavior

The search bar disappears. 👻 
### Steps to reproduce the behavior
1. Open iPhone or iPad.
2. Select "Pages".
3. After the view loads, double-tap quickly on the search bar.
4. The search bar is gone! 😨

Note: This can be a bit fickle and may not reproduce if the timing is off. I also can't seem to reproduce this on any other view controller using the search controller, only the Pages list. Lord knows why.

![pages-search-whoa](https://cloud.githubusercontent.com/assets/1873422/17310996/a2c770dc-580d-11e6-9ea4-479ccdd96ba0.gif)

**Comment by hoverduck** [comment]
@kurzee - I can't reproduce this...is it still a problem for you?

**Comment by kurzee** [comment]
@hoverduck this is resolved! Thanks for checking!
