### ISSUE TITLE
Sharing: Sharing option is missing for Jetpack connected multisite blogs. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5825]
Related to the same API issue that we discovered in #5732.  

The `/v1.1/sites/site` end point does not return the blog options dictionary (tho interestingly the `/v1.1/me/sites` does). The result is the Sharing feature is momentarily visible on the blog details screen, but then is quickly hidden when the detail screen queries for updated blog options and finds none.

This is an issue that needs to be resolved on the API side of things.  Logging here so we remember to follow up.

**Comment by elibud** [comment]
@aerych I've just verified and this doesn't seem to be an issue anymore, can you please double check for me? Thanks :)

**Comment by aerych** [comment]
I double checked the api endpoints and did a quick test in the client for paranoia.  Agree that this looks resolved.  Let's close it :)
