### ISSUE TITLE
Typo in WordPress/Classes/ViewRelated/Menus/MenusViewController.m

### ISSUE THREAD

**Issue by pixolin** [wordpress-mobile/WordPress-iOS#5833]
### Expected behavior
use the word **please** instead of **pealse**, please.

### Actual behavior
uses the word **pealse**

### Steps to reproduce the behavior
Umm …

##### Tested on [device], iOS [version], WPiOS [version]
Nope. Found it during translation on translate.wordpress.org.

**Comment by rachelmcr** [comment]
Resolved in https://github.com/wordpress-mobile/WordPress-iOS/pull/5835
