### ISSUE TITLE
A few strange iPad Pro screenshots to investigate

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#5842]
We should investigate the following screenshots to figure out whether there's something we can do to improve these scenarios.

All of them came up after installing WPiOS for the first time in my iPad Pro (with 1Password just recently installed too).

![img_0002](https://cloud.githubusercontent.com/assets/1836005/17442383/ee17446c-5b0b-11e6-8534-15720dbd10a9.PNG)
![img_0003](https://cloud.githubusercontent.com/assets/1836005/17442381/ee159ef0-5b0b-11e6-9f9a-45c120ba30bf.PNG)
![img_0004](https://cloud.githubusercontent.com/assets/1836005/17442382/ee16d55e-5b0b-11e6-815e-b2f8d667ac72.PNG)

**Comment by kurzee** [comment]
Added to the iPad refresh master list, we'll take a look!

**Comment by diegoreymendez** [comment]
Thanks @kurzee!

**Comment by kurzee** [comment]
@diegoreymendez we just took a look at this and it all appears resolved! I think? Maybe we missing something? Feel free to reopen if there's anything else.
