### ISSUE TITLE
Login screen at "Connect to WordPress.com" does not respond to reserved usernames

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5843]
### Expected behavior

If I try to log in to WordPress.com with a reserved username ([in the reservedUserNames array](https://github.com/wordpress-mobile/WordPress-iOS/blob/7094df5d484ade221f7a49c29b8de274c1273840/WordPress/Classes/ViewRelated/NUX/LoginViewModel.m#L177)), I expect the app to return an error explaining it isn't a valid username or prompt me to log in to a self-hosted site instead.
### Actual behavior

If I already have a self-hosted site added to the app, and I try to log in with the "Connect to WordPress.com" login on the Me tab, I can enter a reserved username (admin, administrator, root) but when I tap the "Next" button, nothing happens. The app does not respond or give an error.

In contrast, the app responds as expected on the main login screen (if I haven't added any sites to the app yet) by turning into a self-hosted login form.
### Steps to reproduce the behavior
1. Open the app and add a self-hosted site
2. Go to the Me tab
3. Tap "Connect to WordPress.com"
4. Enter a reserved username (admin, administrator, or root)
5. Tap "Next"

Result: Nothing happens.

**Comment by aerych** [comment]
Fixed in https://github.com/wordpress-mobile/WordPress-iOS/pull/6128
