### ISSUE TITLE
NUX: Offer suggestions for username/site address when the first choice is already taken

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5845]
When a user creates a new account, we offer a fairly unhelpful error message if the username or site address is already taken:

Username isn't available:

> Sorry, we can't log you in.
> Sorry, that username already exists!

Site address isn't available:

> Sorry, we can't log you in.
> Sorry, that site already exists!

It would be great to offer suggestions to users when their first choice isn't available, so they don't have to repeatedly enter their choices and potentially continue to run into that error. Not being able to find an available username or site address is very discouraging and can lead users to abandon the signup.
##### Tested on iPhone 6, iOS 9.3.3, WPiOS 6.4.0.20160804

Related Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/4485

**Comment by rachelmcr** [comment]
### Screenshot from the app signup

![2016-08-08 18 04 26](https://cloud.githubusercontent.com/assets/8658164/17488955/a3e4c2b8-5d93-11e6-9236-e4db9e4fe367.png)

### Screenshot from web signup

![screen shot 2016-08-08 at 6 06 08 pm](https://cloud.githubusercontent.com/assets/8658164/17488903/64ba7c2c-5d93-11e6-83e1-01c813094afe.png)

**Comment by nheagy** [comment]
This should be fixed by the time #8110 is done 🤞

**Comment by elibud** [comment]
Closing as the new flow is ready :)
