### ISSUE TITLE
invalid client_id

### ISSUE THREAD

**Issue by RuofeiLv** [wordpress-mobile/WordPress-iOS#5856]
there is no .wpcom_app_credentials on root folder, so I create one downloaded from official template, and i fill with the WPCOM_APP_ID and WPCOM_APP_SECRET that show below 

WPCOM_APP_ID=xxxxx
WPCOM_APP_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
and put it on root folder.then i run the project and create an account and get a error message says that the required client_id is missing, and then i fill the macro

#define WPCOM_API_CLIENT_ID @""
#define WPCOM_API_CLIENT_SECRET @""

in the ApiCredential.m, the error message now become the client_id is invalid
i am sure that the WPCOM_APP_ID and WPCOM_APP_SECRET is correct and the type is native.

Could u help solve this problem？ thank you very much

**Comment by aerych** [comment]
Hi @RuofeiLv, 
I edited your issue to remove your app ID and app secret. These are things you really don't want to share publicly. 

> there is no .wpcom_app_credentials on root folder, so I create one downloaded from official template

The `.wpcom_app_credentials` file needs to be placed in your home folder.  If you open up a terminal type `cd ~` to switch to your home folder.  Then you can type `open .` to open that folder in Finder if you're not too comfortable with the command line.

**Comment by RuofeiLv** [comment]
Yes, i did put .wpcom_app_credentials file on my home folder before. and i saw the issue #5503, there is a workaround say 
**Edit "Generate API credentials" on "Build Phases" and replace $WPCOM_CONFIG to ~/.wpcom_app_credentials**
then the ApiCredentials.m in Derived Sources did appear the client and secret. But the problem still exist. When i ceate an account, the error message is invalid client_id.
