### ISSUE TITLE
Still have problem in Authentication

### ISSUE THREAD

**Issue by RuofeiLv** [wordpress-mobile/WordPress-iOS#5863]
### Expected behavior
Create account successfully

### Actual behavior
Error message: invalid client_id
### Steps to reproduce the behavior
Yes, i did put .wpcom_app_credentials file on my home folder before. and i saw the issue #5503, there is a workaround say 
Edit "Generate API credentials" on "Build Phases" and replace $WPCOM_CONFIG to ~/.wpcom_app_credentials
then the ApiCredentials.m in Derived Sources did appear the client and secret. But the problem still exist. When i ceate an account, the error message is invalid client_id.

##### Tested on [device], iOS [version], WPiOS [version]
Tested on Simulator (x86_64), iPhone OS 9.3,WordPress for iOS 6.4 (6.4.0.0)
 Launching WordPress for iOS 6.4 (6.4.0.0)...

**Comment by aerych** [comment]
Creating a new WordPress.com account is an example of a feature that uses one or more [undocumented WordPress.co REST API](https://developer.wordpress.com/docs/api/) endpoints. WordPress.com requires that a client ID to be white listed before it can access certain endpoints.

For this reason you should expect features that rely on non-public WordPress.com REST API endpoints to be unavailable or not work as expected, even though you have correctly configured your `.wpcom_app_credentials`.

Generally, the app should function as expected with self-hosted WordPress.com sites via the core WordPress XML-RPC API.

**Comment by aerych** [comment]
If you'd like to chat with other folks working on the app we invite you to [join the WordPress Slack](https://make.wordpress.org/chat/).  You can find us in the #mobile channel.
