### ISSUE TITLE
iPad Pro Full Sized Keyboard Support

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#5870]
A user wrote in about WPiOS lacking support for the full keyboard on iPad Pro. Not entirely familiar with the changes there but we should do a refresher of our keyboard/textfield support options on iPad since bumping to iOS9+.

**Comment by richiwalt** [comment]
Note: it *may* be working for the smaller 9.7" iPad Pro (a standard size screen ) ... But definitely not for the Larger 12.9" iPad Pro.   (I'm the user)

**Comment by kurzee** [comment]
Hi @richiwalt! Thanks for commenting!

Looking at iPad Pro support, I'm able to pull up the keyboard for the editor with copy/paste/B/I/U shortcuts available. (Screenshot below)

Were those the particular shortcuts you were expecting? If you have shortcuts enabled in Settings, but are still unable to see those shortcuts on the keyboard in-app, then I'd say we definitely have a bug on our hands. 🤔

![simulator screen shot aug 17 2016 8 19 11 pm](https://cloud.githubusercontent.com/assets/1873422/17759001/81abce08-64b9-11e6-99e8-f1d20521c6b2.png)

**Comment by richiwalt** [comment]
We definitely have a bug on our hands then.  In iOS settings for keyboard, I have everything turned on.  All Other apps use a full keyboard.   I have a basic keyboard ... Latest version of the WordPress app too.   This is a larger 12.9" first iPad Pro.

**Comment by richiwalt** [comment]
[http://www.richimages.net/Penmanship/IMG_1754.PNG](url)

**Comment by richiwalt** [comment]
Apparently, I do not know how to post n image to this forum

**Comment by richiwalt** [comment]
![image](https://cloud.githubusercontent.com/assets/10684805/17759668/e805eefe-64be-11e6-9c1c-5e445beda1ea.png)

**Comment by kurzee** [comment]
Ah perfect, thanks for the screenshots!

So, if you swipe up on the small white line in the top center of the keyboard, above the 7, what appears underneath? @richiwalt

**Comment by richiwalt** [comment]
![image](https://cloud.githubusercontent.com/assets/10684805/17759717/6bed4ffa-64bf-11e6-87b8-f5fc31bd4574.jpg)

**Comment by richiwalt** [comment]
Good grief ... That's all there was to it ?   Yep ... All those wonderful tools are there that I've been looking for all this time.   A, I'm feeling pretty silly.   B, perhaps it wasn't as noticeable as it could have been.   Why do we need to slide this up a bit on a very large screen iPad Pro ?   On a mini, I would understand a bit more (screen is much smaller).  

Chalk this one up to user-error.   But really , update where one doesn't need to slide that extra bit up on the larger pro.

**Comment by kurzee** [comment]
🎉

Unfortunately, we can't really touch the keyboard mechanics there as it's all owned by iOS. However, I would agree this is one of those areas where the iPad Pro should probably just default to using more screen space. 😄 

Glad we were able to figure it out, let us know if you find any other issues on the iPad Pro!

**Comment by richiwalt** [comment]
Yep ...I am glad to now know how to get to those handy keys.
