### ISSUE TITLE
Reader: UI freezes when parsing some newly synced remote content.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5878]
Props @kurzee for the find. 
It seems certain newly synced content ends up blocking the UI when its being parsed.  The block is happening in `NSString+Helpers stringByReplacingHTMLEmoticonsWithEmoji`.  And I've triggered it with [this post](https://confessionsfromageekmind.com/2016/07/22/star-wars-celebration-europe-2016/) and I can reproduce the issue in the liked feed by liking that specific post.

**Comment by lancewillett** [comment]
Hi @aerych — I'd had a crash from Reader on a post with many images in it, and trying again today with new beta build 6.5.20160927 — the crash happens consistently still. :/

**Comment by aerych** [comment]
Thanks @lancewillett. I'll see what I can do to get it sorted.

**Comment by aerych** [comment]
Dug in to Lance's report a bit more, and I think this is a separate issue after all. 
The crash Lance is seeing is happening on the post detail screen. Image parsing shouldn't be a factor at this point (tho the list might still be syncing) but if the problem was with the sync he should be seeing crashes just in the list and not waiting til he reaches the detail. 

The images we're loading in the detail are quite large and there are quite a few of them.  This, plus the fact that the crash seems to be tied to this specific post, make me think its possible the app is being ejected due to memory pressure.  Also, we don't see any crash reports in hockey app which would expected for oom errors.

Closing this issue in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/6040
