### ISSUE TITLE
Empty primary site field in Account Settings

### ISSUE THREAD

**Issue by oguzkocer** [wordpress-mobile/WordPress-iOS#5884]
### Expected behavior

I expect "Primary Site" field to be always filled with either the blog name or the url.
### Actual behavior

If the blog name is empty for a site, "Primary Site" field would be empty.
### Steps to reproduce the behavior

Remove the name of a blog and navigate to "Account Settings" screen.
##### Tested on [device], iOS [version], WPiOS [version]

Should be the same for all device and versions (tested on a branch)

/cc @jleandroperez

**Comment by designsimply** [comment]
Tested and confirmed using 11.9 and WP Internal 12.0.0.20190311 on iPhone 6S iOS 12.1.4.

<img src="https://user-images.githubusercontent.com/1119271/54242237-7b681c00-44e9-11e9-973a-8b7cd3b88b75.PNG" width="270" alt="IMG_2085">
