### ISSUE TITLE
List of non-localizable strings

### ISSUE THREAD

**Issue by isaackeyet** [wordpress-mobile/WordPress-iOS#59]
Went through what I think is most of the app, but please have a look at the Crash Report screen as well. These strings really should be translateable since it makes the app broken if you don't know English -- and look funny either way.

Set up:
"This account has two step authentication enabled. Please configure an application-specific password to use with this application."

Old set up (add blogs): All strings as far as I can tell -- both for the old set up if you don't have any blogs (display intro text, logo, etc) and if you already have blogs in there (only 3 buttons and 2 descriptions).

About:"WordPress for iOS", "Publisher", "Copyright", "Terms of Service", "Privacy Policy"

Notification settings: all the main toggles, "Follows", "Achievements", "Comments", etc

Post Editor: Settings: "Format" and all post formats, "Set Featured Image"

Media: long strings uploading message are cut off (only one line here) and there's really no way around a long string in at least swedish.

Notifications: 
Overview: all the text in the actual notifications, but maybe this can only be done WPcom side?
Comment: "Tap to reply", "Replying...", "Reply"
Lists: "These people liked your post:", "This person liked your post:", "to see them all, visit the post.", "x people liked it so far. Nice!", re-blogs and follow lists are out of order too, e.g. "view all followers"

Reader:
Overview: "on X" ("on BlogNameHere")
Commenting: "on X" ("on BlogNameHere" in navbar), "to X" ("to UserNameHere" in navbar), "Comment" button needs to be a new string since it's a verb here, not a noun - which are different strings in non-english languages.
Friend Finder: all of it, but I'm guessing this is because it's not native and should be fixed with the code clean up and refactoring -- ?

**Comment by koke** [comment]
These all look either translated or gone
