### ISSUE TITLE
My Sites: Add popover does not block Edit button

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5903]
Minor bug.
To reproduce:
On the iPad, go to the My Sites list. 
Tap on the + button to display the popover. 
Tap on the Edit button. 

Note that the popover does disappear but the view also switches into edit mode.  This is really minor as far as a bug goes, and a user might see this as perfectly normal behavior. However, the popover should probably intercept completely the tap on the edit button.

**Comment by yaelirub** [comment]
Closing this as "wont fix" really minor issue with no user reports. Please reopen if necessary
