### ISSUE TITLE
Categories: List does not show newly added categories on the iPad.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5905]
Seems to work correctly on an iPhone. 

To reproduce on an iPad:
- Edit a post.
- Open the menu choose options then categories.
- Tap to add a new category, enter some text then save. 
- Notice the the category does not appear in the list. 
- Tap to add another category.
- Tap to choose a parent.
- Notice that the category that you _just_ created is present in the list of potential parents categories.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/9000
