### ISSUE TITLE
Themes: Activating a new theme via a search does not update what was shown as the current theme.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5907]
To reproduce: 
- Navigate to the Themes feature
- Note the name shown for the Current Theme
- Search for "Twenty"
- Activate the Twenty Sixteen or Twenty Fifteen theme
- Back on the main list of themes, notice that the name shown for the Current Theme has not been updated.

**Comment by hoverduck** [comment]
Closing, this no longer seems to be an issue
![ios-5907](https://cloud.githubusercontent.com/assets/7233112/22349404/8ba5d266-e3dd-11e6-9b6b-02426a98a10a.gif)
