### ISSUE TITLE
Reader: Cancelling/adding an empty tag yields an error.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5908]
To reproduce:
- Go to the Reader tab.
- In the menu, tap "Add a Tag"
- Do not type any text. 
- Tap Cancel or Done (on the keyboard)
- The modal dismisses and an alert appears saying "Could Not Follow Tag". 

if the tag is empty we shouldn't be trying to follow.

**Comment by rachelmcr** [comment]
The same error occurs if you enter an invalid character such as a space, or if you enter one or more symbols like `&` or `$`.

**Comment by aerych** [comment]
> The same error occurs if you enter an invalid character such as a space, or if you enter one or more symbols like & or $.

Addressed in #5930

**Comment by kurzee** [comment]
Reopening as this was not resolved in https://github.com/wordpress-mobile/WordPress-iOS/pull/5930

**Comment by aerych** [comment]
#5930 was never intended to address this issue.  The comment above "Addressed in #5930" only refers to the issue with & and $ characters. 

This issue was addressed in #5929 :).  Can you still reproduce it in release/6.5 or was there just some branch confusion going on?

**Comment by kurzee** [comment]
@aerych tested now on `release/6.5`, all resolved! I think I misread what was going on and never saw #5929. This can be closed.

**Comment by aerych** [comment]
Thanks @kurzee !!
