### ISSUE TITLE
Posts List: Load more can be triggered even when there is no more content. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5910]
Probably minor.
To reproduce: 
- Go to the posts list and scroll all the way down to the last post. You should see the "W" footer.
- Scroll back up a bit, then scroll back down.
- The list will try to load more posts again, even though it has already reached the end of its content. 

Once we know there are no more posts we probably shouldn't try loading more again.

**Comment by aerych** [comment]
I should add this was on a self-hosted site syncing via xmlrpc. I'm not able to repro on a wpcom site using the REST API.

**Comment by hoverduck** [comment]
@aerych - This is another one I'm unable to reproduce.  I tried with a self-hosted site with ~60 posts in the list so I got a couple of reloads while scrolling, but still nothing after hitting the bottom and going back up.

**Comment by aerych** [comment]
I'm also unable to repro.  Let's assume it was resolved at some point and we can reopen if needed. 
Thanks @hoverduck !!
