### ISSUE TITLE
Blogs: A self-hosted blog record not converted when signed into wpcom connected to Jetpack

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5911]
To reproduce:
- First, sign in to a self-hosted site connected to Jetpack via the self-hosted sign in form. Do not take the extra step of switching to stats or notifications and connecting Jetpack. 
- Confirm you only have this one blog in the app. 
- Switch to the Me tab and sign into the wpcom account that is connected to Jetpack on the self-hosted site.
- Switch back to the blog list.  Notice that you see all of your wpcom blogs including a wpcom flavor of the self-hosted blog (courtesy of Jetpack) however the original self-hosted record is also present, creating a "duplicate" in the list.  

I thought we had an issue open for this but I can't find it.  Close this if it turns out its a dup.

**Comment by rachelmcr** [comment]
This is also a problem in another scenario:

1. Sign in to a WordPress.com account.
2. Add a self-hosted site that has Jetpack connected to a different WordPress.com account as a regular self-hosted site.
3. In the Stats section for that site, log in to the WordPress.com account linked to that site.
4. Switch to the Me tab and note that you're now logged in to the new WordPress.com account (not the one you originally logged in to).
5. Switch back to the blog list. Note that you see all of your wpcom blogs including a wpcom flavor of the self-hosted blog, but the original self-hosted record is also present, creating a "duplicate" in the list.

**Comment by koke** [comment]
Here's what I know so far: a self hosted site is added to the app, then Jetpack is connected* and `syncBlogs` brings the REST variant of the site. We currently try to de-duplicate blogs via their `xmlrpc` property, but sometimes there isn't an exact match. I think the most common cause is one being `http` and the other `https`, but there might be another slight differences in the URL.

* There are some variations: login from stats, jetpack connected on web to an account already present on app.

To solve this, we need to do a better job at de-duplicating sites, but it's hard to get it right. We'll consider two sites to be duplicate if they live at the same URL and with the same user account. This sounds simple, but it's not:
- From the `me/sites` response there's no way to obtain the local user account.
- While there might be a canonical URL (`HOME`), a site might be accessed through different URLs (http/https, www/non-www, different case), so the app's xmlrpc endpoint might not match exactly the one Jetpack knows.
