### ISSUE TITLE
Sharing Button Mgt: Odd visual artifact next to reorder controls. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5912]
Not too sure what's going on with this.  There is a thin vertical line that sometimes appears next to the reorder controls after dragging (or starting to drag) a row.  The placement varies and it can move around a bit.  I can reproduce it on the iPhone as well. 

Example:
![img_0024](https://cloud.githubusercontent.com/assets/1435271/18020751/c197271a-6ba8-11e6-95e5-b33535ecd00e.PNG)

**Comment by yaelirub** [comment]
Closing as no fix ( I couldn't reproduce) please reopen if necessary
