### ISSUE TITLE
Notifications: Section header can appear too wide

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5913]
To reproduce: 
- Be signed into a wpcom account and be showing a section header in the Notifications screen. 
- Confirm the header is the correct width. 
- Switch to the Me tab and sign out of the app. 
- Sign back into the app with the same account. 
- Switch to the Notifications tab. 
- Notice the section header is full width.

cc @jleandroperez 

![img_0025](https://cloud.githubusercontent.com/assets/1435271/18020999/17e32bea-6baa-11e6-9b41-f7cfde3094f1.PNG)

**Comment by jleandroperez** [comment]
Thanks for filing this one Eric!!

**Comment by aerych** [comment]
@jleandroperez did fix this one?

**Comment by jleandroperez** [comment]
@aerych couldn't get to it, yet, but i'm moving this issue up my punch list. Will get to it tomorrow, apologies about the delay!

**Comment by hoverduck** [comment]
This was fixed with #5990
