### ISSUE TITLE
Account Settings: Cells show disclosure icons yet tapping launches new controllers modally

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5914]
Minor. 
To reproduce: 
- Go to Me > Account Settings
- Notice several rows show disclosure indicator for their accessory view. 
- Tap any of these rows.
- Notice that a new controller is presented as a modal.

Since the cells are showing disclosure indicators, and for consistency with other settings screens, we should probably just push the new controllers on to the regular navigation stack, vs. a modal.

**Comment by yaelirub** [comment]
Currently the only thing opens as a modal is Primary site. The rest are pushed. Closing as this is super minor and won't fix. Please reopen if necessary
