### ISSUE TITLE
cannot parse response

### ISSUE THREAD

**Issue by bigtan** [wordpress-mobile/WordPress-iOS#5922]
### Expected behavior
cannot login self-hosted site through wordpress-ios, but it is normal through wordpress-android

### Actual behavior
when I tried to login my self-hosted site, it fails, and report that cannot parse response and try to treat the root url as an xmlrpc and cannot parse response again.

### Steps to reproduce the behavior
1. install the latest wordpress-ios version in ipad mini 2
2. try to login an self-hosted site with correct username and password
3. fail

**Comment by aerych** [comment]
Hi @bigtan, thanks for the report.  WordPress for Android and WordPress for iOS parse XML-RPC responses in different ways.  Parsing tries to be robust but unexpected markup or formatting in the XML-RPC response can still be a problem for one or both of the apps. 

I can sign in to my self-hosted test blog without errors, so I'd want to see the XML-RPC response from the affected blog to better understand what's happening. 

Could you provide the URL of the blog you've tested? 
Could you provide a copy of the XML-RPC response being returned from the blog.  You can use the tool at http://xmlrpc.eritreo.it if you like.

**Comment by bigtan** [comment]
[full log.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/442602/full.log.zip)

There is a offline version of the reported log in the zip file.

**Comment by aerych** [comment]
@bigtan, Thanks for sharing the log.  I've removed the link because the log you shared included your username and password for every XML-RPC request contained in the log.  You might want to change your password now.

**Comment by bigtan** [comment]
@aerych thanks, I will change it right now.

**Comment by aerych** [comment]
The blog in question is at estan.cn.  Checkign https://estan.cn/xmlrpc.php in a browser shows the expected "XML-RPC server accepts POST requests only" message.  A quick test with XML-RPC client and Charles Proxy shows that at least some requests (e.g. `system.listMethods`) return a zero length response / 301 redirect.  A quick test in the app shows the same result. Example:
```
HTTP/1.1 301 Moved Permanently
Alt-Svc: quic=":80"; ma=2592000; v="34,33,32"
Alternate-Protocol: 80:quic
Location: https://estan.cn/xmlrpc.php
Server: Caddy
Date: Mon, 29 Aug 2016 14:54:39 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8
```

The issue appears to be server related.  I'd guess either a plugin on the blog or some server setting is responsible.  In any event we wouldn't consider this a bug in the app. 

@bigtan, you might try temporarily disabling plugins and switching to a default theme to see if one or the other is causing a conflict.  https://apps.wordpress.com/support/#faq-ios-3 
You might also contact your web host explain, the HTTP 301 response and ask if they are blocking some XML-RPC requests and what the criteria is.

**Comment by bigtan** [comment]
Hi @aerych 
I think i know where the problem is. My site will redirect all http requests to https, but according to the response. It is in port 80, so  it must be a http request. I just enter the site url in https form, is it expected that all request should go through https scheme?

**Comment by aerych** [comment]
I would recommend all requests, and particularly XML-RPC requests since they contain your username and password, be sent via https.
