### ISSUE TITLE
Reader: Adding a tag with non-Latin characters returns an error

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5927]
### Expected behavior

I expect to be able to add tags in non-Latin languages such as Japanese and Arabic.

Example tags in the web reader:
https://wordpress.com/tag/%D8%B3%D9%84%D8%A7%D9%85
https://wordpress.com/tag/%E7%A7%81

### Actual behavior

Trying to follow a non-Latin tag such as `سلام` or `私` returns an error:

> Could Not Follow Tag
> unsupported URL

### Steps to reproduce the behavior

1. Open the Reader tab
2. In the menu, tap "Add a Tag"
3. Enter a tag with non-Latin characters (either all non-Latin characters or a mix)
4. Tap "Add Tag"
5. An alert message appears with the error "Could Not Follow Tag" and "unsupported URL"

**Comment by kurzee** [comment]
Closing, resolved in https://github.com/wordpress-mobile/WordPress-iOS/pull/5930
