### ISSUE TITLE
Blog Posts: Inconsistent layout for links under each post on iPhone

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5941]
### Expected behavior

On my iPhone 6, I expect to see four links under each post in my Blog Posts list. For example, in my list of published posts, I should have these four links: Edit, View, Stats, Trash.

I expect either to see all four links side-by-side, or to see two links at a time with a "More" link to switch between the first two (Edit and View) and the second two (Stats and Trash).

Prior to the 6.5 beta, I saw the four links side-by-side in landscape view, and two links at a time in portrait view.

### Actual behavior

In the 6.5 beta, if I rotate my phone from landscape view to portrait view, I get all four links side-by-side. Sometimes I end up with some posts showing the links like that, and other posts in the same list showing two links at a time.

#### Screenshot

![2016-08-29 21 02 50](https://cloud.githubusercontent.com/assets/8658164/18095484/0b585544-6ecf-11e6-97a4-8502125677e7.png)

### Steps to reproduce the behavior

1. On an iPhone, in portrait view, open the app and go to the My Sites tab
2. Select a site and open the Blog Posts
3. Check the links under each post (should be two links + a more link)
4. Rotate the phone to landscape view
5. Check the links under each post (should be four links side-by-side)
6. Rotate the phone back to portrait view

Result: The four links stay side-by-side instead of switching back to two link + a more link

##### Tested on iPhone 6, iOS 9.3.5, WPiOS 6.5.0.20160826 (also tested on release version 6.4 and confirmed I don't see the issue there)

**Comment by aerych** [comment]
Dup of #5915
