### ISSUE TITLE
Update to HelpShift 5.7.1

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5944]
When a user is replying to an existing conversation in iOS the “Send” link disappears off the screen when the reply gets really long. HelpShift 5.7.0 fixes this according to them. 5.7.1 is the latest version, so update to that.

cc: @rachelmcr

**Comment by rachelmcr** [comment]
I confirmed that in the new build the "Send" link no longer disappears for long replies. However, this seems to uncover a new problem:

- I tested by starting a new support message, replying once from the support end, and then sending my latest activity logs as a reply from the app
- The reply was successfully received on the support end
- On the user's end, though, the app froze (showing just a blue bubble with no text where my reply with my logs should have been)
- I force closed the app and tried to reopen the conversation, and the app froze again and then closed itself
- I tried one more time to open the app and open the conversation. There was a lot of lag and the conversation eventually closed itself (returning to the "Help & Support" screen) without ever loading my long reply

Now, even though the support conversation is closed in Helpshift (from the support end) whenever I tap on "Contact us" the app freezes and closes itself.

Tested on iPhone 6, iOS 9.3.5, WPiOS 6.5.0.20160901

**Comment by astralbodies** [comment]
OMG, helpshift!! I'll see if there are any known issues. This is probably worse than a missing send button. Do you have a running dialog with their support team?

**Comment by astralbodies** [comment]
I'll see if I can replicate the issue - the crash reports are not coming through to HockeyApp.

**Comment by astralbodies** [comment]
@rachelmcr I was able to replicate the blue box thing with pasting in a ton of text. Can't get the simulator to freeze though. Definitely a Helpshift bug.

**Comment by aerych** [comment]
Fixed in #5945, closing
