### ISSUE TITLE
Reader: Clarify "Manage Sites" section

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5951]
@alisterscott raised a couple points of confusion about the "Manage Sites" section in the Reader:

#### 1. The name "Manage Sites" is unclear:

> I was also thinking “Manage Sites” sounds like managing your own sites, should it be something like “Manage Followed Sites”?

"Manage Followed Sites" is also the title for the [corresponding page in Calypso](https://wordpress.com/following/edit).

#### 2. There isn't a loading screen, which can be confusing/scary:

> I have done some testing on both iPad and iPhone. With the new “Manage Sites” screen I noticed it took about 10 seconds to load for me, and during this time I saw a message saying “No Sites”

> https://cloudup.com/cG6VOekI7dx

> This made me slightly worried until they did appear – could we show a loading icon or something else?

##### Tested in WPiOS 6.5.0.20160901

**Comment by lancewillett** [comment]
+1 — I noticed this confusion myself in testing 6.5 beta on iPad.

**Comment by aerych** [comment]
> "Manage Followed Sites" is also the title for the corresponding page in Calypso.

I think we can be more consistent with the web and add a bit of clarity if we change the stream header and screen title to "Manage" and change the section title to "Followed Sites".  On the manage screen, the back button already reads "Followed Sites" providing context for the "Manage" so adding that to the title seems redundant.

![simulator screen shot sep 9 2016 1 45 52 pm](https://cloud.githubusercontent.com/assets/1435271/18398846/1e09a572-7694-11e6-8f43-09607e12de16.png)

![simulator screen shot sep 9 2016 1 45 56 pm](https://cloud.githubusercontent.com/assets/1435271/18398855/2998ca1c-7694-11e6-9a30-a64c70bcf6f9.png)

cc @fraying @jancavan @mattmiklic

**Comment by jancavan** [comment]
@aerych Sounds good. Unrelated to the bug: I noticed that in smaller screens (the emulator is an iPhone 5), "Followed Sites" is too long that it moves the Manage heading off-center. Should this be truncated?

![screenshot 2016-09-13 12 04 36](https://cloud.githubusercontent.com/assets/4924246/18487462/404d6c4a-79aa-11e6-8d8b-a3bd01acc85d.png)

**Comment by aerych** [comment]
Ick.  That's the native behavior but its not very good.  The text does truncates eventually but the nav bar tries to show as much text as it can without truncating.  
I'll open a separate issue for it.
