### ISSUE TITLE
Preview: crash when clicking iOS share icon in post preview

### ISSUE THREAD

**Issue by lancewillett** [wordpress-mobile/WordPress-iOS#5952]
### Expected behavior
When previewing a post, I'd expect to be able to click the iOS share icon at the top right to open the preview in mobile Safari.

I'd expect the overlay to look something like this:
![img_0118](https://cloud.githubusercontent.com/assets/66797/18283947/b2856e22-741c-11e6-990f-60032c175c0f.jpg)

Where the menu options to open the current preview are available to click.

### Actual behavior
The app crashes. (I sent crash reports in via WP Internal app.)

![preview-crash](https://cloud.githubusercontent.com/assets/66797/18284077/53b9cbc6-741d-11e6-9f20-6a05a98a87dc.png)

### Steps to reproduce the behavior
I was able to crash the app in iPad using these steps:

1. Go to My Sites, select a site
2. Go to Blog Posts list
3. Click an already published post, enter editor view by clicking the post
4. In top editor toolbar, click ... then Preview
5. In preview, click the "sharing" icon (box with arrow in the top of it) — I'd expect this to open an iOS sharing menu
6. Crash :/

I can repeat this each time I do the same steps.

##### Tested on [device], iOS [version], WPiOS [version]
Tested with app version 6.5.0.20160901 on an iPad Mini 3.0 (iOS v9.3.5) in both portrait and landscape mode.

##### Video
https://cloudup.com/cZ_2IZ89lpz

This crash did not happen with same WP app version testing on an iPhone 6+ (iOS v9.3.5).

**Comment by diegoreymendez** [comment]
@lancewillett - This fix will be made available in the next internal release of WPiOS.

Thanks for the report!

**Comment by lancewillett** [comment]
Yay, thank you. Confirmed fixed after retesting with the same steps above using app version 6.5.0.20160920

![img_0004](https://cloud.githubusercontent.com/assets/66797/18892093/ffbc9408-84bc-11e6-9038-2b9ec0182b91.PNG)
