### ISSUE TITLE
Reader: Show footer bar after 'natural' scroll to bottom

### ISSUE THREAD

**Issue by roundhill** [wordpress-mobile/WordPress-iOS#5964]
When scrolling in the reader, I usually have to give the view another flick to show the comment bar when I've reached the bottom.

**Current Behavior**
1) Load a reader post detail view.
2) Do a large flick to scroll to the bottom of the post.
3) Observe that the footer bar doesn't appear, you need to flick one more time.

**Expected behavior**
1) Load a reader post detail view.
2) Do a large flick to scroll to the bottom of the post.
3) The comment bar appears, and all is well in the world.

cc @aerych

**Comment by aerych** [comment]
Thanks @roundhill !
