### ISSUE TITLE
Aztec doesn’t handle post lifecycle properly / edits not seen

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#5970]
#5961 exhibited some strange issues where edits to an existing post didn’t always trigger the discard functionality. Determine the actual cause which probably a missing method call in the new Aztec controller. Use this to help feed into #5963 to centralize the post creation/revision logic.

cc: @diegoreymendez

**Comment by astralbodies** [comment]
@jleandroperez I think you resolved this?

**Comment by jleandroperez** [comment]
@astralbodies can't recall working on anything related to this one!

**Comment by astralbodies** [comment]
Don't believe this is an issue any longer.
