### ISSUE TITLE
Reader: Long post titles cut off in detail view

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#5994]
### Expected behavior

I expect long post titles to be visible in full or cut off with an ellipsis or other sign indicating that the title was shortened.

### Actual behavior

In the post detail view, titles longer than four lines are cut off without any explanation.

### Screenshots

Post list view (full title):
![img_6611](https://cloud.githubusercontent.com/assets/8658164/18848422/389e5bb8-8426-11e6-806d-b733a3f62d80.PNG)

Post detail view (cut off):
![img_6612](https://cloud.githubusercontent.com/assets/8658164/18848423/38c47028-8426-11e6-9caa-a210fb4fc1e0.PNG)

Post detail view in Calypso Reader (full title):
![img_6614](https://cloud.githubusercontent.com/assets/8658164/18848424/38c4af84-8426-11e6-8667-14edcdf79f5c.PNG)

**Comment by aerych** [comment]
@kurzee, would it be convenient to squash this one with the readability / iPad UI refresh?  Its a super small tweak.  The title label in the ReaderDetailViewController storyboard is currently set to 4 lines. If we set that to 0 we should be golden.

**Comment by kurzee** [comment]
@aerych this a great candidate for the readability changes. I'll add it there as `0` lines.

>kinda weird that the label wasn't showing an ellipsis in the screenshot in the description.

I believe that one is a bug I've solved that also occurred with the summary label in which the label's height ends up being set with a fractional `frame.size.height` value, so the text drawing is cut off prematurely.

**Comment by kurzee** [comment]
@aerych should we also not limit the summary label, as well?

**Comment by aerych** [comment]
> I believe that one is a bug I've solved that also occurred with the summary label

You rock!

> should we also not limit the summary label, as well

Thanks for checking!  We want to keep the summary in the post cards limited to 3 lines.  At least until the upcoming card UI refresh.

**Comment by aerych** [comment]
@kurzee  I switched the assignee to you :)   Cheers!!
