### ISSUE TITLE
Notifications: Support tap to dismiss comment reply

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#5999]
Right now there is no way to dismiss the keyboard after tapping into the comment reply field.  In the Reader comments, tapping anywhere outside the field will dismiss the keyboard. Let's do the same with comments in Notifications.

**Comment by jleandroperez** [comment]
@aerych sir, we've implemented the Interactive Dismissal gesture. #5767

(Swiping downwards with the keyboard open, within Notifications, should dismiss it interactively).

Is this issue still valid?

**Comment by aerych** [comment]
Oh nice!  I didn't know we did that. 
This makes me wonder if the other places we've implemented a tap to dismiss should be redone as a swipe down to dismiss. 
Let's close this one and think about it.

**Comment by jleandroperez** [comment]
Thanks for checking @aerych!

Implementation should be [very very very easy](https://github.com/wordpress-mobile/WordPress-iOS/pull/5767/files#diff-997458fe1dca4157c06b9bc6ac85d43aR199).

Already wired in Comments and Notifications, but i definitely missed the reader!

**Comment by aerych** [comment]
Oh I was actually thinking about NUX :D
