### ISSUE TITLE
Posts/Pages: Improve how we determine oldest date for the filter.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6000]
We recently had a user report that several pages were missing from the app. I had a look around both in the app and in the REST API. I chased a few dead ends both in the app and the API until in the app I noticed the missing pages are present for the briefest moment then vanish. It was especially pronounced when I set the iOS Simulator to use Slow Animations (Simulator > Debug > Slow Animations) then view the Page list.

So why did it happen? 

The full list of pages was appearing courtesy of the page sync performed via the blog detail controller.  However, the subsequent sync on the page list does a bit of extra work by storing the oldest create date (taken from the last returned page as they are sorted newest to oldest), and using that to filter results from Core Data. 

In this particular case, the REST API was _not_ returning pages ordered newest to oldest. For the blog in question, all pages were returned with their date offset set as `+08:00` _except_ for one post which had an offset of "+00:00".  If you ignore the offset the dates appeared to be sorted correctly, however when the offset was considered (as it should be) then the last page returned was actually younger than the three preceding pages.  The result was the page list's fetch request used the younger date and did not get three of the pages in its result set.

Strictly speaking, this seems to be an API bug in that pages/posts are not being returned in the order expected. However the app could also be a bit smarter and ensure that its actually preserving the date of the oldest page/post. 

Let's improve the logic there a bit for paranoia and a failsafe. 

cc @kurzee cos you're more familiar with how the paging code works than I am.

**Comment by kurzee** [comment]
Thanks for digging into this @aerych!

>However the app could also be a bit smarter and ensure that its actually preserving the date of the oldest page/post.

I think that hits the spot so we don't lean to heavily on the API results. I'll take a shot at it.
