### ISSUE TITLE
Update SVProgressHUD

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#6002]
On iPad, when multitasking, the HUD appears in the center of the _screen_ rather than in the center of the app. This means that depending on the multitasking configuration, the HUD is either partially or completely obscured by the other app being displayed.

I noticed this issue using the Delete Site feature in site settings – a confirmation HUD appears during the process, but in 1/2 multitasking you only see half of it.

![simulator screen shot 27 sep 2016 13 13 07](https://cloud.githubusercontent.com/assets/4780/18872844/5a86c6d2-84b4-11e6-88bc-06e9653f176c.png)

We're currently using version 1.1.3 of SVProgressHUD, and the latest version is 2.0.3. We should try updating to see if this fixes the issue.

**Comment by jleandroperez** [comment]
Closed via #6698
