### ISSUE TITLE
Pop gesture disabled when navigation hidden in Reader detail

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#6007]
### Steps to reproduce the behavior

1. Go to a reader article
2. Start scrolling down until the navigation hides
3. Try to drag from the left border of the screen to go back

Some ideas for solutions here: http://stackoverflow.com/questions/24710258/no-swipe-back-when-hiding-navigation-bar-in-uinavigationcontroller

**Comment by aerych** [comment]
Right now we don't have really have a good way to address this without doing something hacky. 

Closing for now.  We can revisit if Apple gives us new options in a future SDK update.
