### ISSUE TITLE
iPad NUX: Orientation Changes

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#6014]
Looks our NUX views are experiencing issues with orientation changes on iPad.

Props to @rachelmcr for posting a Lookback with issues primarily around our previous NUX layout. However, we still have a couple of minor issues with the new NUX layout.
1. Enter a username to log in.
2. On the username and password fields layout, activating the keyboard and rotating to landscape covers the "add a self-hosted WordPress site" button text, underneath the "Lost your password?" text.

![img_0051](https://cloud.githubusercontent.com/assets/1873422/18890570/4f07defa-84c7-11e6-9942-ef212aeca1a7.PNG)
1. When creating a site, activate the keyboard from one of the fields.
2. When in landscape orientation, the keyboard covers the "Create Account" button. Although it can indeed be activate from pressing "Done" on the last field's keyboard input.

![img_0050](https://cloud.githubusercontent.com/assets/1873422/18890569/4f07e5f8-84c7-11e6-9fa2-6d17bf0ff02e.PNG)
##### Tested on [device], iOS [version], WPiOS [version]

iPad Mini 4,  iOS 9.3.5, latest from develop

**Comment by kurzee** [comment]
@aerych are either of the cases of intentional with the new NUX?

**Comment by aerych** [comment]
There were some trade offs made when space got tight.  Hiding the primary button behind the keyboard was one, as the keyboard's Done button would perform the same function.  We also did allow the links to be hidden in certain situations, particularly on the smaller iPhone models. 

More background here: https://github.com/wordpress-mobile/WordPress-iOS/issues/4912

**Comment by kurzee** [comment]
Thanks @aerych, I'll keep this open for now as we'll take a second look at iPad and see if we can open it up a bit without swaying from the original discussion.

**Comment by kurzee** [comment]
Offloading this from the iPad refresh, probably best handled by the upcoming NUX work.

**Comment by aerych** [comment]
Closing. No longer applicable in the new login flow.
