### ISSUE TITLE
Reword 'Disconnect' to 'Logout'

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#6016]
The wording of the button, along with the pop up warning “Disconnecting your account will remove all of ___’s WordPress.com data from this device.” is unnecessarily nerve-wrecking.

Why can't it just be "Log out" along with a nicer message since the data is backed up on WordPress.com anyways?

**Comment by kwonye** [comment]
Found out it's just in case there are local drafts/changes that are not in the server yet. We can initiate a sync if there are and not show a pop up if there isn't.

**Comment by rachelmcr** [comment]
Related Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/4573

As I mentioned there, for reference, there's some past discussion about the terminology (connect/disconnect v. log in/out) in this PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/3273

**Comment by jleandroperez** [comment]
Closing this one since as WPiOS 8.6 the Logout button is no longer displayed as **Disconnect**.

Thanks everyone!
