### ISSUE TITLE
Posts/Pages: The copy option from the share activity should just copy the URL, not the title.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6020]
Currently if you view a post detail, tap the share button and choose the `copy` option from the share activity the copied text is the post title followed by the URL.  Probably in this case it would be better to just copy the URL. 

I haven't checked how much customization we have here or how this sort of change would impact other options.

**Comment by msdesign21** [comment]
This would be an awesome trash day pickup! Very frustrating when trying to share/copy a link on mobile to have to remove this other text first.

**Comment by elibud** [comment]
I'm trying to replicate this and I'm failing :( @msdesign21 can you let me know step by step how are you getting a Title + URL when you tap on copy?

**Comment by msdesign21** [comment]
@elibud you need to "Visit" a site (view from the front end) in order for this to happen. We fixed it up in all other places. 

I list an example here: https://mobilerequests.wordpress.com/2017/09/05/copy-link-needs-update-on-front-end-site-share/

Confirmed it happens with non-p2 sites as well.

**Comment by elibud** [comment]
Thanks @msdesign21 I'll look into this.

**Comment by aerych** [comment]
@msdesign21 I removed the p2 link for paranoia.

**Comment by elibud** [comment]
@msdesign21 it's fixed, it will be available in version 8.5 of WordPress iOS
