### ISSUE TITLE
Posting: Prompt to resolve publicize issues before publishing.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6021]
A nice feature in wp-admin is a notice shown when a user's publicize connection has a problem, prompting them to resolve the issue before publishing.   It would be nice to include something like this when publishing in the app if we detect a connection issue.

<img width="292" alt="screen shot 2016-09-28 at 7 18 10 pm" src="https://cloud.githubusercontent.com/assets/1435271/18936823/525f2c7c-85b0-11e6-99b3-11c8c3fba4b9.png">

**Comment by rachelmcr** [comment]
This was resolved recently, now that publicize connections are included in post options. Dupe issue about it: https://github.com/wordpress-mobile/WordPress-iOS/issues/6837
