### ISSUE TITLE
Can't dismiss popup notification as keyboard is overlapping

### ISSUE THREAD

**Issue by cecilerainon** [wordpress-mobile/WordPress-iOS#6029]
I opened the app after typing a post earlier in the day and got stuck with a popup notification (telling me that my local draft hadn't been saved) and the keyboard overlapping.

**Expected behavior**
I was expecting to open the app and continue typing my post. Or, since the notification has to be there, I was expecting the popup notification to be above the keyboard so I could close it and continue typing my post.

**Actual behavior**
I opened the app, a local draft pop up notification and the draft editor opened at the same time, making the app unusable because I couldn't hide the keyboard to dismiss the notification.
I had to shut down the app and re-launch it to get unstuck, and as a result, lost my draft. 

**Steps to reproduce the behavior** (I haven't been able to reproduce it, but it did happen and I did lose my content...)
- Create new post
- Type some content
- Get your local draft _not_ to be saved (I don't know how to reproduce that)
- Reopen the app and have the keyboard displayed over the notification

*Tested on iPhone 7+, iOS 10.1, WPiOS Internal 6.5.0.20160927

![iphone](https://cloud.githubusercontent.com/assets/16645645/19041513/ad8a260c-8988-11e6-98bb-6848bb2ab061.png)

**Comment by aerych** [comment]
Nice catch!
Guessing we need to update which view controller is acting as the display context for the alert.

**Comment by aerych** [comment]
Hmm... Can't repro on a 7plus simulator running iOS 10.0.  
@cecilerainon you were running the 10.1 beta yah? Can you still reproduce this?  Wondering if it was a weird fluke or possibly some weirdness in the beta.

**Comment by aerych** [comment]
As reported by @kwonye: in #6041 

### Steps to reproduce the behavior
1. Open the editor
2. Type some words
3. Exit the app until it reaches a timeout (approx 10 min)
4. Return to the app

You'll see this and can't click the dialog and exit:

![img_0361](https://cloud.githubusercontent.com/assets/1158819/19096069/9edafa02-8a4e-11e6-8d6c-475040c36ed1.PNG)


##### Tested on iPhone 7, iOS 10.0.2, WPiOS 6.5

**Comment by cecilerainon** [comment]
@aerych Yes, it was on iOS 10.1. I haven't been able to reproduce it but it looks like Will found the secret recipe! :)

**Comment by aerych** [comment]
Closing in favor of #6202 as it has a pull request :)
