### ISSUE TITLE
Posts: Post summary is longer after trashing and restoring.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6034]
Originally reported by @rachelmcr 

> I tried trashing a post on my wp.com test blog and then restoring it. The restore worked, but I noticed that the excerpt I saw after the post was restored was different (longer).
> 
> Before trashing the post:
> ![2015-06-03-16-02-25](https://cloud.githubusercontent.com/assets/1435271/19056729/aedd4478-8990-11e6-9c79-3774510867d6.png)
> 
> After restoring the post:
> ![2015-06-03-16-02-37](https://cloud.githubusercontent.com/assets/1435271/19056731/b22e1c9c-8990-11e6-8d64-8e6beab74a0e.png)
> 
> When I returned to that screen later, the excerpt was back to the same one I saw at first.

**Comment by hoverduck** [comment]
Here's a GIF showing it in action.  If you move quickly you see that the longer excerpt is shown after the post's status is updated to lose the Trashed tag.  Refreshing the list then shows the shorter one again.

![ios-6034](https://cloud.githubusercontent.com/assets/7233112/22377524/4ed639f4-e480-11e6-8b2f-2cab7827ec27.gif)

**Comment by yaelirub** [comment]
Tested and doesn't seem like an issue anymore. 
Closing this. Please open if necessary
