### ISSUE TITLE
Posts: Allow trashed posts to be previewed.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6037]
Currently, if you tap on a trashed post in the post list you can see the tap animation (probably a minor bug tbh), but you can't view the post's content. This is consistent with the web experience, but it might be nice if a user could view the full post content for extra context before restoring a trashed post.

**Comment by thehenrybyrd** [comment]
This would be super nice, I've always wished we could preview posts before restoring them in the web interface, too. Would be awesome to have in mobile.

**Comment by kean** [comment]
Implemented in https://github.com/wordpress-mobile/WordPress-iOS/pull/23142
