### ISSUE TITLE
Maybe support sharing via long press in more places. 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6038]
This comes from a user feature request forwarded by @amylaneio 

> Make it possible to choose my preferred browser. On ios the puffin-browser works fine in combination with this app; chrome and safari doesn’t especially using several plugins.

It might be interesting to present a share activity in response to a long press in more places through out the app. Examples include links in the reader, a post preview, comements... a site's View Site and Dashboard options, etc.

**Comment by rachelmcr** [comment]
If we present a share activity in response to a long press, especially for links in the Reader, it'd also be nice to include something like Safari's long press menu that shows you the URL you selected:

![2017-07-24 11 43 51](https://user-images.githubusercontent.com/8658164/28519978-a1cd3c2c-7065-11e7-9e03-af9419b0dcd2.png)

That way you can preview the URL you're visiting before you tap on it. This was requested by an internal user (ref: 207189-h).
