### ISSUE TITLE
Pages: Editor button and placeholder text for pages should be page centric

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6039]
Originally reported by: Enej. 

> While trying to create a new page via the mobile app I came across [the page editor]. Which seems fine but the `Share your story here…` part though me off. I was thinking that I was in the create a new post screen also the greyed out `Post` button didn’t help the situation.

Commented by Thianh:

> Yeah we didn’t have anything specific for Pages. We can definitely change it to something page specific. Maybe something explicit like “Create your page here…”

**Comment by bysl** [comment]
While working on the iOS editor refresh, I some UI text was not consistent. The current plan is to match Calypso's language (and possibly revisit in the future), thus the ideal fix would be:

Default text:
`Share your story here...` becomes [blank]

Main action:
`Post` becomes `Publish`

These changes would address the Pages editing context too.

Related `Post Title` discussion: https://github.com/wordpress-mobile/WordPress-iOS/issues/6051

**Comment by rachelmcr** [comment]
Gutenberg should resolve this, as it uses the more neutral prompt "Start writing or press + to add content" for both posts and pages.
