### ISSUE TITLE
Editor: Inactivity causes app to show dialog that is un-clickable

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#6041]
### Steps to reproduce the behavior
1. Open the editor
2. Type some words
3. Exit the app until it reaches a timeout (approx 10 min)
4. Return to the app

You'll see this and can't click the dialog and exit:

![img_0361](https://cloud.githubusercontent.com/assets/1158819/19096069/9edafa02-8a4e-11e6-8d6c-475040c36ed1.PNG)

**Comment by aerych** [comment]
Dup of #6029 but with some nice details.  I'm going to merge this into #6029 since it was first.
