### ISSUE TITLE
Some toolbar buttons in the in-app browser are difficult to see

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6043]
To reproduce, visit a web page that has a `select` element.  Tap to view the options in the native control. Notice that the buttons in the toolbar don't have much contrast.  Let's use either a darker tint for the buttons or for the toolbar.  cc @mattmiklic 

![simulator screen shot oct 5 2016 1 29 58 pm](https://cloud.githubusercontent.com/assets/1435271/19126450/9e279360-8b00-11e6-9423-ffe0a3bd4b6c.png)

**Comment by mattmiklic** [comment]
+1, would just go with dark grey here, or if the text in this picker has to use system colors, the same one used for "select…" in the screenshot above.

**Comment by kean** [comment]
We've removed nearly all global appearance overrides in one of the previous releases, and this light gray bar item color is no longer a thing, so it no longer reproduces.

<img width="470" alt="Screenshot 2024-11-20 at 1 50 13 PM" src="https://github.com/user-attachments/assets/aa247e83-34c1-46a8-a9b6-5867e7b5496d">
