### ISSUE TITLE
Have a more user-friendly experience when there are no sites

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#6044]
Per @roundhill 

When a user has no sites, this is what the user sees:

![img_0146](https://cloud.githubusercontent.com/assets/1158819/19129512/72ca42ca-8afc-11e6-81a1-1e4f8ac5a1f1.png)

On Android, it looks like this:

![screenshot_20161005-130347](https://cloud.githubusercontent.com/assets/1158819/19129520/7a2622dc-8afc-11e6-9365-a4a01d74a0f7.png)

Let's make iOS friendlier like Android

**Comment by aerych** [comment]
Dup of https://github.com/wordpress-mobile/WordPress-iOS/issues/4664 :)

**Comment by kwonye** [comment]
If I do this again, I owe you ice cream.

Sorry, and thanks :(

**Comment by aerych** [comment]
Make it gelato and all is forgiven.
