### ISSUE TITLE
Stats: Show media file name under Clicks > Media

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6045]
Reported by @rachelsquirrel 

>  A user on Twitter would like the “Clicks” section in the stats to show the file name rather than the URL. They want to be able to see what users have clicked on without having to click the URL themselves.

Twitter conversation:
https://twitter.com/MrsLamp88/status/651724967185285120

In the android app, rather than truncating the URL we let the line wrap so the filename is shown.  Maybe do this on iOS as well.  A quick check shows stats on web also truncates the line so we can considet updating there as well.

**Comment by ScoutHarris** [comment]
> Show media file name under Clicks > Media

I'm not sure what this means, I don't see a Media section under Clicks. Maybe it doesn't exist anymore. I'm gonna go ahead and close this.
