### ISSUE TITLE
Reader: Update no recent posts message

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6048]
We should probably show drake when there are no posts in a stream

<img width="729" alt="screen shot 2016-10-06 at 1 40 16 pm" src="https://cloud.githubusercontent.com/assets/1435271/19165754/b05ffbf6-8bca-11e6-8ce4-4399016059b2.png">

**Comment by bummytime** [comment]
@mattmiklic and/or @folletto ...currently we have this:

![screen shot 2018-02-02 at 4 46 19 pm](https://user-images.githubusercontent.com/154014/35758270-b9c455e8-0838-11e8-91c5-fee903de7a1e.png)

Would y'all like drake (or something else) on there?

**Comment by mattmiklic** [comment]
I'm working on all the empty-content states this and next week; so a new design using our updated brand illustration style is on the way.

**Comment by folletto** [comment]
Sideways to Matt's comment: Drake shouln't be used anymore as we now have a different illustration set.

And in the few instances where Drake should be used, she should be updated to this version:
https://github.com/Automattic/wp-calypso/blob/master/public/images/illustrations/no-themes-drake.svg

Note also that ideally Drake should show up only in the "no themes" case.

**Comment by rachelmcr** [comment]
I confirmed that we currently have an updated empty state for this screen:

![2019-01-17 18 12 24](https://user-images.githubusercontent.com/8658164/51339364-2cbb7a00-1a84-11e9-81ee-034275db5a87.png)
