### ISSUE TITLE
Posts: Prompt to confirm before deleting permanently.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6049]
For consistency with the web, in the post list trash filter, prompt the user to confirm before deleting a post permanently.

**Comment by elibud** [comment]
![simulator screen shot may 16 2017 17 21 51](https://cloud.githubusercontent.com/assets/5558824/26126500/2fe64962-3a5c-11e7-9a6d-d4f8c1a4c3ff.png)

The alert was already added.
