### ISSUE TITLE
Posting: Scheduled posts with a draft status show wrong "last-modified" date

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6050]
To reproduce: 
- Create a new post
- Add a title and some text
- Go to options and set the status to draft.
- Change the date to something in the future. 
- Tap the save/publish button. 
  The post card shows a last modified date that's in the future. It should show the date of the last save.

**Comment by annezazu** [comment]
199073-h

**Comment by rachelmcr** [comment]
I can no longer reproduce this issue. When I save a scheduled post with a draft status, it shows the correct last modified date (the last save) and not the future scheduled date.

Tested with iPhone XS, iOS 12.0.1, WPiOS 11.0.0.20181010
