### ISSUE TITLE
Editor: Make "Post Title" placeholder a friendlier call to action

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6051]
Originally requested by @mjangda 
"Post Title" is rather cold and mechanical.  Maybe we could use a friendlier placeholder here.

**Comment by mattmiklic** [comment]
Discussed this a bit and we've decided to match Calypso's language everywhere it makes sense; which would mean "Title" as the placeholder for this field. We may revisit the idea of a friendlier/more engaging label if/when we revisit the posting experience, maybe post-Aztec.

**Comment by bummytime** [comment]
@mattmiklic is this still an issue?

**Comment by mattmiklic** [comment]
I think the main thing with anything more specific than "Post Title" is optimizing for some users and not all ("share your story" is blog-centric; anything more corporate is too business-centric) -- I'm guessing we should aim to match whatever Gutenberg does here but cc:ing @iamthomasbishop since this is in his domain.

**Comment by iamthomasbishop** [comment]
I think if we are going to change this _now_, I'd prefer to match Gutenberg, because that's probably what we'll end up doing in the end. Right now, their placeholder reads "Add Title". I'd either go that route or spice it up by adding "a" in between: "Add a Title" 😄 It's neutral but not as cold.

**Comment by mattmiklic** [comment]
So spicy! 🔥 I like "Add a Title".

**Comment by yaelirub** [comment]
Currently showing "Add title" for block editor and "Title" for classic editor. 
Can we close this issue?

**Comment by iamthomasbishop** [comment]
@yaelirub We can probably close this one.
