### ISSUE TITLE
Signin: Support Touch ID for signin.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6054]
Title has it.

**Comment by rachelmcr** [comment]
A user sent feedback requesting this feature:

> 希望可以有密码锁、用指纹解锁。 

Translation:

> Hope to have a password lock, use the fingerprint to unlock.

Ref: AppbotX 27015

**Comment by koke** [comment]
@aerych I don't understand what this is. How would Touch ID do anything if we don't have credentials? Unless this is about #65

**Comment by aerych** [comment]
It *might* have been about a passcode lock, but I don't recall the context now. :/  
Let's just close it.
