### ISSUE TITLE
Editor: Aborting media upload can leave progress html in the source.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6055]
As [reported in the forums](https://ios.forums.wordpress.org/topic/stopping-image-upload-results-in-strange-images-in-the-post?replies=2):

> sometimes a photoupload in the app lasts very long. If I abort the upload, everything seems fine in the app. Only the text is displayed in the message field. After publication of this post some strange html-code appears in the post:
> 
> `<span id="E6A521E3-D0A9-458C-8421-B0E1C6C1CB72" class="img_container"><progress id="progress_E6A521E3-D0A9-458C-8421-B0E1C6C1CB72" value="0" class="wp_media_indicator failed"></progress></span>`
> 
> You can see it here: http://hsv24.mopo.de/2016/10/02/ersatzspieler-sind-auf-dem-platz.html

**Comment by SergioEstevao** [comment]
Fixed by #6082
