### ISSUE TITLE
Notifications: Links in comment notifications are not tappable.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6056]
Title has it.  Originally reported by @astralbodies 
Opening this issue to track, however @jleandroperez I know you were getting with @dmsnell about this.  Please close if its already been addressed (and in which case I apologize for the noise!)

**Comment by jleandroperez** [comment]
Thanks for filing this one @aerych. No progress on my side (yet), but will pick it up in the next Notifications sprint.
