### ISSUE TITLE
Batch media upload crashes in older devices

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#6059]
Steve reports:

> [...]if I try add multiple images at once, the app will also freeze up, sometimes displaying a ‘failed to export media’, cocoa error, and sometimes just crashing outright.

I've tested on an iPad mini, and adding 3+ pictures at once to a post gets the app killed for using too much memory.

**Comment by koke** [comment]
I've done some profiling on this, and I think there's something we didn't consider here. If you look at `MediaService`, it uses a serial queue for resizing/exporting. However, the real work isn't performed in those operations.

When using the Photos framework, this operation ends up calling `PHImageManager.requestImageForAsset(asset:targetSize:contentMode:options:resultHandler:)`, which is asynchronous. So the image requests are serialized, but the real work is concurrent. In my profiling I see three bitmap images being created (at 46 MB each) before the app gets killed.

/cc @SergioEstevao

**Comment by SergioEstevao** [comment]
@koke we can change that request to be synchronous like we do for thumbs. I thought the ImageManager was smart enough to not overload the system, but it looks it isn't.

**Comment by koke** [comment]
Another thing worth exploring: for original size uploads, see if we can strip the geolocation exif directly in the file instead of loading the image in memory.
