### ISSUE TITLE
Reader: Support animated gifs in the reader's post list, post detail, and comments

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6062]
@SergioEstevao recently added support for animated gifs to the sites post list via the FLAnimatedImage library.  Now let's add support to the reader. 
- Reader Cards:  Rather than supporting different featured media views, maybe have just one view that can show a static featured image, an animated gif, and in the future a video thumbnail or gallery.
- Reader Detail  and Comments: Probably we can update WPRichTextImage to display either a static image or an animated gif and kill two birds with one patch.

**Comment by bummytime** [comment]
Just an update to this issue. @etoledom and I have already implemented & merged part of the list above ☝️ into `develop` (for 10.1 release):

* #9261 Reader post list gif support
* #9322 gif support for reader detail -> featured images **+** gif support in the reader detail preview screen (in `WPImageViewController` which now can be used to support gifs elsewhere too)

The content portion of reader detail (#9253) is in progress right now.

>  Rather than supporting different featured media views, maybe have just one view that can show a static featured image, an animated gif,

✅ 🎉 — see `CachedAnimatedImageView`

At this point, I will open another issue for reader comments and close this one.
