### ISSUE TITLE
Notifications: "Like" should not be an option for comments on Jetpack sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6069]
### Expected behavior

Jetpack does not currently support Comment Likes, so it doesn't make sense for "Like" to be an action on comment notifications for Jetpack sites.
### Actual behavior

In comment notifications, there is an option to "Like" a comment on a Jetpack site.

Comment notification (on the Notifications tab):

![2016-10-12 14 51 49](https://cloud.githubusercontent.com/assets/8658164/19313424/4c4aa206-908e-11e6-8fd6-6646c1776b24.png)

In contrast, the Comments section for the same Jetpack site does not have the "Like" option:

![2016-10-12 14 52 19](https://cloud.githubusercontent.com/assets/8658164/19313404/3ceaf7e8-908e-11e6-96e5-1f3774005e4e.png)
### Steps to reproduce the behavior
1. On a Jetpack site, make sure the site is set to approve incoming comments
2. From another account, make a comment on the site to trigger a notification
3. Check the notification and confirm it shows the "Like" action
##### Tested on iPhone 6, iOS 10.0.1, WPiOS 6.6.0.20161012

Originally reported for Android: https://github.com/wordpress-mobile/WordPress-Android/issues/4642

**Comment by elibud** [comment]
The same issue is present when navigating to a comment thread.
![simulator screen shot apr 10 2017 10 14 33](https://cloud.githubusercontent.com/assets/5558824/24863282/96a7279a-1dd6-11e7-838b-967fe46a5e25.png)

**Comment by elibud** [comment]
@rachelmcr Likes are coming to Jetpack, so we are going to have to work the other way around this and make sure we support them everywhere. 

https://github.com/wordpress-mobile/WordPress-iOS/issues/7006
