### ISSUE TITLE
Reader: Refresh card UI 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6070]
There are five card types coming to the web. 
- Default (text and 1-3 images)
- Text (text with no images)
- Photo (1 or more images and under 130 characters of text)
- Gallery (text and 4 or more images)
- Video (text and video)

Update the cards in the iOS reader to match.  Specific details to follow.

Related [Android issue](https://github.com/wordpress-mobile/WordPress-Android/issues/4776).

**Comment by yaelirub** [comment]
We're working on a revamp of Reader card UI as part of Reader Improvements according to new designs.
Closing this issue
