### ISSUE TITLE
Reader: Update reader post detail with new author info treatment

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6071]
Pending the final go ahead, on large screens we'll start showing author info in a sticky view to the left of the content. 

Example:
<img width="255" alt="screen shot 2016-10-12 at 2 22 09 pm" src="https://cloud.githubusercontent.com/assets/1435271/19324511/98c57c20-9087-11e6-8368-77e0568bfddb.png">

**Comment by yaelirub** [comment]
We're updating Reader layout and post details as part of Reader Improvements, according to new designs. Closing this
