### ISSUE TITLE
Notifications: Quick actions Approve/Like don't give any indication of success or failure

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6072]
### Steps to reproduce the behavior

Expand the push notification of a comment with Approve or Like options, and select that button
### Expected behavior

Some indication that the action succeeded or failed
### Actual behavior

The comment is Approved or Liked, but the user has to open the app to confirm that.

**Comment by hoverduck** [comment]
No, it's still a problem 7.3.0.20170327.  I just tested both approving and liking a comment via the quick action buttons and neither gave me any feedback that anything happened, it just faded away.  The app icon still shows an unread badge for new notifications, and I confirmed on the web that the comments were approved and liked, but that's not reflected in the notifications panel of the app.  Pull-refreshing the list still shows un-approved and un-liked.

This is on an iPad Air 2, iOS 10.2.1

**Comment by elibud** [comment]
Got it @hoverduck thanks a lot for clarifying, I had never used those before so I had misinterpreted the issue. I will look into this.

**Comment by elibud** [comment]
The notification being dismissed is all the feedback we can give that the action was requested. However I did notice some inconsistencies in how the quick actions taken are updated in the app, still investigating that part.

**Comment by elibud** [comment]
This one is pending on an update to our Push Notification server.
