### ISSUE TITLE
Notifications: Reply quick action should open the keyboard

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6073]
### Steps to reproduce the behavior

Expand the push notification of a comment with the Reply action, and select that button
### Expected behavior

To immediately be able to reply to the comment
### Actual behavior

The app opens to the comment, but I still have to tap the Reply button there to open the keyboard and start a response

https://cloudup.com/cnDhWDK7p3s

**Comment by jleandroperez** [comment]
Closing in favor of @2036

We'll be implementing, soon, the ability to reply to comments right from the notification itself (without requiring you to navigate to the associated comment).

Thanks @hoverduck!!
