### ISSUE TITLE
Reader: Be consistent in either showing or hiding the comments button for Jetpack powered sites.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6087]
Current the reader may or may not show a comment's button in the post cards and post detail for Jetpack powered sites depending on the REST API endpoint being called (e.g. `/read/following` vs `/read/sites/`).  Additionally, the web currently does _not_ show a comment button for Jetpack powered blogs. 

Let's choose to either show or hide and be consistent about it.

**Comment by astralbodies** [comment]
@aerych Is this still an issue? I see it's assigned to 6.7 so I didn't want to move it if it was fixed in #6077.

**Comment by aerych** [comment]
Still an issue.

**Comment by elibud** [comment]
Will be addressed as part of https://github.com/wordpress-mobile/WordPress-iOS/issues/7006

**Comment by elibud** [comment]
Reopening as we still need to check the endpoints for consistency: e.g. `/read/following` vs `/read/sites/`

**Comment by elibud** [comment]
As discussed with @aerych this doesn't look like an issue anymore, so we are closing it for now.
