### ISSUE TITLE
Notifications Refresh Design

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#6093]
It's about time to look at what we can improve with notifications.

With iOS 10, we have a ton of new things we can do inside a [notification](https://developer.apple.com/ios/human-interface-guidelines/features/notifications/).

Example:
![](https://developer.apple.com/ios/human-interface-guidelines/images/whatsnew_notifications_2x.png)

Here's what notifications looks like right now on iOS: https://cloudup.com/cI50iTMX-Mj

Ideas:
- Expanded notifications to show comment details for iOS 10
- Allow responses for comments
- Show media if available in notification [example](http://willowtreeapps.com/wp-content/uploads/2016/06/blog-post-image-1_iOS10-rich-notifications_WE.png)

These are all the new "features" I can think of. @jleandroperez please add any you can think!

Also, here are web notifications so that we can keep them consistent https://cloudup.com/cmHKG-EptZE

**Comment by kwonye** [comment]
Android here: https://github.com/wordpress-mobile/WordPress-Android/issues/4665

**Comment by frosty** [comment]
> * Expanded notifications to show comment details for iOS 10
* Allow responses for comments
* Show media if available in notification example

A big +1 to all of these!

It'd be good if we can also consider the best way to present notifications within the WPiOS app on iPad. With our upcoming split view changes, we're probably going to go for a simple v1 which just shows the list of notifications on the left, and the content on the right. But it'd be interesting if we could explore other ways to present this.

I quickly put a split view into the app (with some obvious visual issues) to see how it feels, and it's better than I perhaps expected it to be: https://cloudup.com/cntaXhUo2rT

I also had a quick play with putting all notifications into a popover instead (@jleandroperez suggested this idea a while ago). It fits some of the content well, as it's usually small snippets of content (we display them in a narrow area on .com too), but a few areas such as viewing full blog posts and replying to comments feel a little off. Here's some screenshots: https://cloudup.com/csL1mjAYjfU

**Comment by jleandroperez** [comment]
@frosty thank you for trying out the Popover alternative, muuuuuuuuuch appreciated!!!

**Comment by jleandroperez** [comment]
Closing this one. We've implemented (not long ago!) inline replies right from the notification.

As per the remaining items, #5893 is meant to implement an extension (and fine tune the way notifications are displayed).

Thanks everyone!
