### ISSUE TITLE
Contact form malformatted from Notifications prompt

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6108]
### Steps to reproduce the behavior

1) From the Notifications page (specifically seen on the Unread tab) open and close several notifications to acknowledge them
2) At some point you get a prompt at the top of the page asking about your satisfaction
3) Go through the prompts to provide feedback

The contact form that opens is different from the one in the Me -> Support page, and the "How can we help?" prompt is squashed after the keyboard opens:

![ipad-screenshot-feedback](https://cloud.githubusercontent.com/assets/7233112/19600836/bf6c7326-9774-11e6-8ed1-c261046fff9b.jpg)

**Comment by jleandroperez** [comment]
Closing as cannot repro. iPad Air 2 / iOS 11.2 / WPiOS "Develop" (AKA Mark 9.2).

This is handled by the Helpshift library, got definitely fixed in an update.
Thanks sir!
