### ISSUE TITLE
Share extension fails silently

### ISSUE THREAD

**Issue by jancbeck** [wordpress-mobile/WordPress-iOS#6111]
### Expected behavior

I often bookmark links while browsing the web in mobile Safari by pushing them to my blog as a draft article. When I hit the share action menu from Safari to save a link to blog about later, I want to get feedback if that didn't work so I do not find out a week later after saving multiple links that they are all lost.
### Actual behavior

The sharing fails silently if the iOS WordPress could not communicate to my server.
### Steps to reproduce the behavior
1. Have a self hosted jetpack-powered WordPress blog
2. Have the WordPress App fail to connect to your server ([this issue](https://wordpress.org/support/topic/jetpack-site-is-inaccessiblenot-able-to-register-for-wordpress-app/))
3. talk with Jetpack support, reinstall Jetpack, reinstall WordPress app
4. Wait a couple of weeks for the error to return
5. Share a link from within Safari with WordPress app

**Comment by rachelmcr** [comment]
Thank you for the feedback! We have an open issue about adding success/failure feedback for the share extension here: https://github.com/wordpress-mobile/WordPress-iOS/issues/5190

I'm going to go ahead and close this issue, since we're tracking this as an enhancement there.
