### ISSUE TITLE
Correctly guess when the user wants to sign in to a self-hosted site

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#6112]
There's (at most) one user in the world that has the username "admin" or "administrator" or "user" in WordPress.com. So let's be smart and create a dictionary of usernames that automatically trigger the self-hosted sign in form.

(thanks to @aforcier for the idea) cc @aerych

Please make sure to keep the list in-sync somehow with https://github.com/wordpress-mobile/WordPress-Android/issues/4684

**Comment by aerych** [comment]
We already have this. :)
See: 
https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/NUX/SigninHelpers.swift#L210
https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/NUX/SigninEmailViewController.swift#L290

**Comment by aerych** [comment]
Reopening.  To add "User" to our list of reserved names.
