### ISSUE TITLE
Posts are published immediately when dateCreated matches dateModified

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#6113]
In `PostServiceRemoteREST`, this block of code creates an issue:

```
    if ([post.date isEqualToDate:post.dateModified]) {
        // publish immediately when date created matches date modified
        parameters[@"date"] = [[NSDate date] WordPressComJSONString];
    } else if (post.date) {
        parameters[@"date"] = [post.date WordPressComJSONString];
    } else if (existingPost) {
        // safety net. An existing post with no create date should publish immediately
        parameters[@"date"] = [[NSDate date] WordPressComJSONString];
    }
```

https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Networking/PostServiceRemoteREST.m#L375

The first condition, `if ([post.date isEqualToDate:post.dateModified])`, creates an issue where if an older post is slightly modified without the `dateModified` changing, and the user hits the "Update" button, the condition passes and the `date` parameter is set as the current date. This ends up changing the post to have been "published immediately" and appear as a new post in their post list, losing the original created date.
## Steps:
1. Find an older post in **Blog Posts**.
2. Edit that post.
3. Select the post options.
4. Add a tag to that post, go back.
5. Hit "Update" to update the post with the new tag you just set.
6. The post's created date has now been updated to the current date and lost its original date.

@aerych looks like you made the change last, can you take a peak and perhaps tweak it just a bit? There may be something else going on that expected the `post.date` to be == `post.dateModified` that you might be familiar with.

**Comment by kurzee** [comment]
Also likely the cause of https://github.com/wordpress-mobile/WordPress-ios/issues/3973#issuecomment-245332447

**Comment by aerych** [comment]
I think we probably need to move most of these `status` changes into the model and out of the service and network layers, with the exception of a few special cases like e.g. `future` not being recognized as a valid status by the API. 

Probably this conditional ```
if ([post.date isEqualToDate:post.dateModified]) {
        // publish immediately when date created matches date modified
        parameters[@"date"] = [[NSDate date] WordPressComJSONString];
```
should only apply to posts with a `draft` or `pending` status, (or newly created posts with a publish status but that have yet to actually be published) and the best place to do that might be in the model.

Our `status` code is still a mess tho less than it used to be (which is a scary thing to say).  This would be a good opportunity to try to simplify things some.  cc @diegoreymendez cos I know you have some interest here.  

I can tackle this but I have other things on my plate at the moment and it will be a little bit before I could give this proper attention.  I can loop back later unless someone want's to pick up the baton.

**Comment by kurzee** [comment]
@aerych thanks for taking a peak, I'll try to put together a quick patch for this one. It won't be pretty, but as you said, our current `status` work is a mess.

**Comment by aerych** [comment]
Sounds good. Ping me for the PR, I'd be happy to give it a look. :)

**Comment by diegoreymendez** [comment]
@aerych - I totally second the idea of simplifying our data model.  Right now it feels like we have to do a lot of condition checking to know what the post status is.

Thanks for suggesting it here @aerych.  Let me know if I can be of help @kurzee.
