### ISSUE TITLE
Posts: Post author filters (only me/everyone) do not work without a manual refresh

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6119]
### Expected behavior

I expect my posts list to update immediately when I switch between the "Only Me" and "Everyone" filters.
### Actual behavior

Nothing changes when I switch between the "Only Me" and "Everyone" filters. The list of posts only updates when I pull to refresh the list manually.
### Steps to reproduce the behavior
1. On a site with multiple authors, publish 1 post each from two different authors.
2. Open the app and view the Blog Posts list (I started on the "Only Me" filter)
3. Tap "Everyone" to switch to that filter. Result: The posts list doesn't change.
4. Pull to refresh the list. Result: Posts from other authors appear.
5. Tap "Only Me" to switch back to that filter. Result: The posts list doesn't change.
6. Pull to refresh the list. Result: Posts from other authors are removed.
#### Screencast

https://cloudup.com/clSky4edS8d

**Comment by kurzee** [comment]
@nheagy can you take a peak at this one? Probably another edge case from https://github.com/wordpress-mobile/WordPress-iOS/pull/5959

**Comment by kurzee** [comment]
This will be resolved in https://github.com/wordpress-mobile/WordPress-iOS/pull/6161
