### ISSUE TITLE
Edit "More" in iOS App Won't Save Changes

### ISSUE THREAD

**Issue by ChrissiePollock** [wordpress-mobile/WordPress-iOS#6136]
### Expected behavior

Changes made to add or remove items from the More Button would save.
### Actual behavior

The changes are not saved.
### Steps to reproduce the behavior
- Go to Sharing>Manage>"More" Button>Toggle the Edit More Button to show it's in edit mode (blue showing)
- Note that Pocket is not activated under the More button:
- Activate Pocket
- Go back to Sharing
- Go back to the "More" Button and note that Pocket is still not activated
##### Tested on [device], iOS [version], WPiOS [version]

iOS - SE v10.0.2 WPiOS 6.5

![a before editing](https://cloud.githubusercontent.com/assets/2545184/19840545/819cfb0e-9ece-11e6-863e-db0c667bb9fa.PNG)
![b showing changes](https://cloud.githubusercontent.com/assets/2545184/19840547/81a58b48-9ece-11e6-9fab-335b0dbd94fa.PNG)
![c refreshing](https://cloud.githubusercontent.com/assets/2545184/19840546/81a37c2c-9ece-11e6-884a-fa6c0c3ae13b.PNG)
![d no changes showing](https://cloud.githubusercontent.com/assets/2545184/19840548/81ab033e-9ece-11e6-8f11-b347ee17249d.PNG)

**Comment by rachelmcr** [comment]
@ChrissiePollock Can you try these steps?

1. Go to Sharing>Manage>"More" Button>Toggle the Edit More Button to show it's in edit mode (blue showing)
2. Note that Pocket is not activated under the More button:
3. Activate Pocket
4. Toggle the Edit More Button to turn off edit mode (blue not showing)
5. Go back to Sharing
6. Go back to the "More" Button

In my testing, changes to both the Sharing Buttons and the "More" Button are saved if you toggle off the Edit status after you make the changes.

That said, this is unclear in the UI — we should try to fix it so changes are saved no matter what or clarify how this is meant to work.
