### ISSUE TITLE
Posts/Pages: Preloading breaks inital sync and paging.

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#6151]
The preloading logic that occurs on `BlogDetailsViewController` breaks the expected syncing/paging on `AbstractPostListViewController`.

It breaks in the following ways:

- Interferes with the expected initial sync on `AbstractPostListViewController`.
  - For site's that have multiple authors, the "Only Me" auto-selection on "Blog Posts" will likely be missing posts if the "Everyone" section has a lot more posts. This is due to the fact that preloading synced posts for "Everyone", not the expected "Only Me" section the user sees first.
- Breaks the paging logic for `AbstractPostListViewController`.
  - The paging logic expects that the initial sync of `AbstractPostListViewController` will set an `oldestPostDate` for whatever was initially synced. Since preloading and quickly viewing "Blog Posts" will avoid the initial sync, the `oldestPostDate` is never set and paging results will be incorrect.

Not sure of a fix on this one, but it might be best to go ahead and disable preloading for `release/6.7` and come up with solutions separately for `6.8`.

@nheagy any thoughts on this one?

**Comment by kurzee** [comment]
Somewhat related, although a separate solution required: https://github.com/wordpress-mobile/WordPress-iOS/issues/6000

**Comment by kurzee** [comment]
Note: I'm thinking `AbstractPostListViewController` is probably on the more "broken" side of things and should be able to handle this scenario.

**Comment by nheagy** [comment]
> preloading synced posts for "Everyone", not the expected "Only Me" section the user sees first.

Preloading is supposed to sync whatever the user will see first. It pulls this from the `PostListFilterSettings` here:

https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Blog/BlogDetailsViewController.m#L666

Is that not the right behavior?

Also, seems like the preload should set `oldestPostDate` correctly. I had wanted the loading code used by both preloading and the posts list to be moved somewhere outside of the two VCs, but that looked like a nightmare. However, without that, there may be functionality that doesn't exist in both locations. 🤔 😢

**Comment by kurzee** [comment]
>Preloading is supposed to sync whatever the user will see first. It pulls this from the PostListFilterSettings here:
>
>Is that not the right behavior?

Yep that's the right behavior! I think something else is actually causing the initial "Only Me" sync to not load or refresh the table correctly, not clear yet.

**Comment by kean** [comment]
Preloading has been disabled a long time ago and was ultimately removed in https://github.com/wordpress-mobile/WordPress-iOS/pull/21861. I think it's safe to close this one.
