### ISSUE TITLE
Reader tab bar item is not localized

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#6154]
https://github.com/wordpress-mobile/WordPress-iOS/blob/d2616bb9f358b77540fd61096ea7f941b88c8c54/WordPress/Classes/ViewRelated/System/WPTabBarController.m#L232

```objc
    _readerNavigationController.tabBarItem.accessibilityIdentifier = @"Reader";
    _readerNavigationController.tabBarItem.title = @"Reader";
```

**Comment by frosty** [comment]
Closed by #6156.
