### ISSUE TITLE
Me: Help & Support Page formatting issue in portrait orientation (iPad)

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6157]
The text beneath the `Contact Us` button is overlapping the button itself when in portrait orientation:
![img_0054](https://cloud.githubusercontent.com/assets/7233112/19978694/2b32cbba-a1ce-11e6-848e-df373a7a8e9f.png)

For contrast, here it is in landscape:
![img_0055](https://cloud.githubusercontent.com/assets/7233112/19978715/374cba6e-a1ce-11e6-8e2b-7f3abcde7d51.png)

**Comment by astralbodies** [comment]
@frosty Heads up 😄

**Comment by frosty** [comment]
Thanks @astralbodies – although this _might_ be more up @kurzee's street. Any ideas, Brent?

**Comment by kurzee** [comment]
Thanks @frosty, @astralbodies.

I can't seem to get this to reproduce @hoverduck. Does it break for you every time? Any particular steps? I've tried both iOS 10 and iOS 10.1.

**Comment by hoverduck** [comment]
Yeah, it happens every time.  No particular steps, I just open the Me tab and tap "Help & Support".  I've tried with multiple accounts, and even installed the latest WP Alpha from BuddyBuild on `release/6.7` (build 929) and still see it.

FWIW, this is on a real device, iPad Air 2, not a simulator

**Comment by kurzee** [comment]
@hoverduck this is very strange, can't reproduce on my iPad Mini, iOS 10.0.2. This _feels_ like an iOS issue as we aren't doing anything custom here. @hoverduck can you try updating to iOS 10.1.1 and see if the issue still occurs on your device?

@frosty can you try peaking at this view on your iPad Pro?

**Comment by frosty** [comment]
@kurzee I can recreate this on my iPad Pro. Can I do something to help debug it?

**Comment by kurzee** [comment]
@frosty hmmm, I'd be curious if "Notification Settings" displays the same layout issue if you have a chance to take a peak. It's definitely a broken `UITableViewHeaderFooterView` not using the right height.

We don't do a hard `tableView.reloadData()` on `SupportViewController`, so perhaps we just need to add that on `viewDidLoad`.

**Comment by frosty** [comment]
**Notification Settings** does not appear to suffer from the same issue. A `reloadData()` in `viewDidLoad` doesn't seem to fix the problem either.

**Comment by frosty** [comment]
@kurzee I took another look, and it seems like the problem is due to the footer heights being calculated based on the original / default font size rather than our custom font. I suspect that by the time `willDisplayFooterView:` is called, the heights have already been calculated. 

The reason this particular footer displays incorrectly is because the number of lines in the label differ between the original font and our custom font. The other label on this screen has the same number of lines in both fonts.

I think the only ways to tackle this would be to manually calculate the heights (in `heightForFooterInSection:`) or use a custom footer view – but I imagine we don't want to go back down that road?

**Comment by kurzee** [comment]
>The reason this particular footer displays incorrectly is because the number of lines in the label differ between the original font and our custom font. The other label on this screen has the same number of lines in both fonts.

Makes perfect sense.

>Or of course, we could use the default font size, and just apply our custom color to it.

That's probably the way to go, 100%. Let me play with a bit and see if I can't make the custom font work.

**Comment by kurzee** [comment]
Thanks @frosty!!

**Comment by kurzee** [comment]
Ref: https://github.com/wordpress-mobile/WordPress-Shared-iOS/pull/110
