### ISSUE TITLE
Visual issue when moving around in split-screen

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6158]
1) Open another app, such as Safari, then swipe in from the right and open WordPress
2) Navigate to My Sites and select Switch Sites
3) Before selecting a new site, move to another section of the app, like Me or Reader
4) Now expand WordPress to be the primary app, full-screen
5) Navigate back to My Sites and see that the mask overlaying the right panel is only as wide as the split-screen allowed it to be, and it's not re-rendered.

![img_0056](https://cloud.githubusercontent.com/assets/7233112/19979820/3201f6b0-a1d2-11e6-961d-bba33727f697.PNG)

**Comment by frosty** [comment]
Thanks for this, @hoverduck!
