### ISSUE TITLE
Unable to test the app after following the setup instructions in the readme

### ISSUE THREAD

**Issue by jeamesbone** [wordpress-mobile/WordPress-iOS#6162]
### Expected behavior
After following the setup instructions in the README, I should be able to test the app on the iOS simulator.

### Actual behavior
The app crashes due to missing helpshift credentials

### Steps to reproduce the behaviour
Follow the setup instructions in the README and then launch an iOS simulator

##### Tested on [device], iOS [version], WPiOS [version]
N/A

### Workaround
Comment out `[HelpshiftUtils setup];` in the app delegate.

**Comment by sendhil** [comment]
Nice catch.
