### ISSUE TITLE
Notifications: Improve Sync

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#6174]
As per @koke 's suggestion, let's revisit the NotificationsSyncService.sync helper:

```
In essence, you have two sets of objects that you have to reconcile, but since replacing the local with the remote every time is a problem you have to calculate a series of operations to apply on the original set. This could be core data updates, or mapping changed attributes to DOM changes.

The problem I noticed in this particular code is that you have 5 nested callbacks and it wasn't obvious at first why the local operations weren't synchronous.

What I'd suggest is a more generic `diff` algorithm that:
1. Fetches the pairs `(id, hash)` for all local notes
2. Compares the local set to the remote set in one pass, returning separate sets of `deleted`, `updated`, and `inserted` notes.
3. Deletes the missing notes
4. Fires the request to load all the updated/inserted notes.

You can see we have a similar thing going on for [mergeBlogs](https://github.com/wordpress-mobile/WordPress-iOS/blob/c93e0211000bc6fdd1acb215875be16b955b467c/WordPress/Classes/Services/BlogService.m#L570). I'd love to just have a `Dictionary.diff` method.
```

**Comment by koke** [comment]
As we're doing this, it would be very interesting to identify other spots in the app where we have a similar pattern. I know `BlogService.mergeBlogs` but I'm guessing there will be more.

**Comment by koke** [comment]
I'm not too sure about naming it `diff` or this particular algorithm/data structures, but here's the basic idea for a generic approach:

```swift
extension Dictionary where Key: Comparable, Value: Equatable {
    typealias Diff = (insertions: [(Key, Value)], updates: [(Key, Value)], removals: [Key])

    func diff(_ other: [Key: Value]) -> Diff {
        let existingKeys = Set(keys)
        let otherKeys = Set(other.keys)
        let insertedKeys = otherKeys.subtracting(existingKeys)
        let removedKeys = existingKeys.subtracting(otherKeys)
        let updatedKeys = existingKeys.intersection(otherKeys)
        let insertedPairs = other.filter({ insertedKeys.contains($0.key) })
        let updatedPairs = other.filter({ updatedKeys.contains($0.key) })
            .filter({ (key: Key, value: Value) in value != self[key] })
        return (
            insertions: insertedPairs,
            updates: updatedPairs,
            removals: Array(removedKeys)
        )
    }
}
```

Thoughts?

**Comment by jleandroperez** [comment]
Not sure about this generic approach, to be honest. Feels like the only spot in which we would use this... is just Notifications right?.

(So maybe it can live as a simple helper method in the service).

**Comment by koke** [comment]
> Feels like the only spot in which we would use this... is just Notifications right?.

No, the idea behind this is that we do something very similar in other places.

Some places I know of that look similar:

- `NotificationsSyncService.sync`
- `- [BlogService mergeBlogs:withAccount:]`
- `- [MediaService mergeMedia:forBlog:completionHandler:]`
- `- [PostCategoryService mergeCategories:forBlog:completionHandler:]`
- `- [PostService mergePosts:ofType:withStatuses:byAuthor:forBlog:purgeExisting:completionHandler:]`
- I had to solve a similar thing in Aztec recently where you'd need to extract a calculate the differences between two sets of attributes and transform those into DOM change operations, so this is not just for network sync

**Comment by koke** [comment]
I haven't tested it but I thin the code would be something like [this gist](https://gist.github.com/koke/c564c688fd93503b8d560fe8c2a9375a). The previous version was fine, but we don't really want to diff dictionaries, but arrays. Or not even that, as ideally we don't want to fetch all the core data entities just to match their id/hash.

I think there's room for reuse/improvement in that area, but I'm going to close this since we have a ton of things that are more important.

**Comment by jleandroperez** [comment]
Acknowledged. Thanks for seeing into this @koke!
