### ISSUE TITLE
My Sites: Stats cell highlighted on iPhone after opening site dashboard/wp admin link

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6176]
### Expected behavior

On the My Sites tab, when I have a splitview (on iPad) I expect to see a cell in the sidebar highlighted when I'm viewing that section.

However, I don't expect to see those cells stay highlighted on the iPhone since there isn't a splitview. I only expect to see a cell highlighted when I tap on it to open that section.

### Actual behavior

On the iPad, after I tap "Dashboard" or "WP Admin" (and the link opens in Safari), when I come back to the app I am on the Stats section with the Stats cell highlighted and stats showing in the splitview. (This is expected on devices where the splitview is visible.)

On the iPhone, after I tap "Dashboard" or "WP Admin" (and the link opens in Safari), when I come back to the app I am on the site's menu with the Stats cell highlighted — this is unexpected, since I am viewing the site's menu and don't expect any cells to be highlighted.

### Steps to reproduce the behavior

1. On an iPhone, open the app
2. Go to the My Sites tab and select a site
3. Tap "Dashboard" or "WP Admin" for that site
4. After the link opens in Safari, return to the app

Result: The Stats cell is highlighted in the site's menu

#### Screenshot

![2016-11-07 02 35 53](https://cloud.githubusercontent.com/assets/8658164/20101880/d299e2aa-a591-11e6-8a75-bd468725cc13.png)

##### Tested on iPhone 6, iOS 10.0.1, WPiOS 6.7.0.20161102

**Comment by cezarsignori** [comment]
The idea is to show what is selected while in split-mode. The iPhone selects the Stats row while in Portrait mode because once you rotate the device to Landscape, that's the row which is going to be selected. But I agree it would be better to reflect that only when the user actually rotates the device. After all, nothing is selected until then.

I will look into this.
