### ISSUE TITLE
iOS: Beta crashes on rotation

### ISSUE THREAD

**Issue by ebinnion** [wordpress-mobile/WordPress-iOS#6193]
### Expected behavior

Rotating device does not crash iOS beta.

### Actual behavior
Rotating device from multiple views crashes the app.

### Steps to reproduce the behavior

- Open beta in portrait orientation
- Go to notifications
- Rotate phone to landscape orientation
- Observe app crashes

##### Tested on [iPhone 6s plus], iOS [10.0.2], WPiOS [6.7.0.20161102]

This could be because of my iOS version. I'll retest after updating.

**Comment by rachelmcr** [comment]
I tested this on my iPhone 6, iOS 10.0.2, WPiOS 6.7.0.20161102, and couldn't reproduce the crash on any of the main tabs in the app.

**Comment by ebinnion** [comment]
I can't reproduce after updating iOS, so I'll close this.
