### ISSUE TITLE
Grammatical errors in Context: 6.7-whats-new in the release notes and Apple Store description

### ISSUE THREAD

**Issue by phsab** [wordpress-mobile/WordPress-iOS#6194]
While translating the following text from 'What's new' in the release notes and Apple Store description, I found a few errors in the original text:

[original]
• This is one for our iPad fans. We've been busy updating the app to make better use of screen space and we're very please to reveal the new iPad layout for the My Sites tab, and for the Me tab. The other tabs need a bit more work before they are ready, but we just couldn't wait to share.• We hate to say things like 'various reader improvements' in our release notes, but, honestly, that's exactly what we did. We made various reader improvements. They lay the foundation for the reader's updated iPad layout. Coming soon!

[suggested]
• This is one **is** for our iPad fans. We've been busy updating the app to make better use of screen space and we're very **pleased** to reveal the new iPad layout for the My Sites tab, and for the Me tab. The other tabs need a bit more work before they are ready, but we just couldn't wait to share.• We hate to say things like 'various reader improvements' in our release notes, but, honestly, that's exactly what we did. We made various reader improvements. They lay the foundation for the reader's updated iPad layout. Coming soon!

**Comment by astralbodies** [comment]
Thanks @phsab I'll let @sendhil know!
