### ISSUE TITLE
Migrate ServiceRemote Classes to Swift 2.3

### ISSUE THREAD

**Issue by Ecarrion** [wordpress-mobile/WordPress-iOS#6195]
ServiceRemote classes are written in Objective-C, the goal is migrate them to Swift 2.3.
For this we will follow a 4 step plan:

- [ ] Write missing tests 
- [ ] Migrate existing code
- [ ] Perform minor architectural improvements
- [ ] Migrate existing tests

**Comment by jleandroperez** [comment]
Closing this one since... we're in Swift 4, and it'd be best to address this a case by case.

Thanks everyone!
