### ISSUE TITLE
Unsaved changes alert obscured by keyboard

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#6202]
When the app is killed off in the background (to clear out memory) while you're editing a post, an 'unsaved changes' dialog is shown when you return to the app.

Unfortunately, this dialog is obscured by the keyboard (focus is on the title field), and can't easily be dismissed.

![img_4943](https://cloud.githubusercontent.com/assets/4780/20357136/aa07ad0c-ac1e-11e6-93e6-3d19a6ee7a89.PNG)

**Comment by frosty** [comment]
Partially related: #3737

**Comment by aerych** [comment]
Dup of https://github.com/wordpress-mobile/WordPress-iOS/issues/6029 :)

**Comment by frosty** [comment]
Wups, thanks! I searched, but clearly used the wrong words :)

**Comment by aerych** [comment]
Honestly it was the screenshot that caught my eye.  Words are hard. :)

**Comment by frosty** [comment]
Fixed by #6203.
