### ISSUE TITLE
Reader: PostCard FeaturedImageViews may lose their heights on rotation

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#6210]
### Steps to reproduce the behavior

1. Open Discover on iOS 10, iPad, portrait orientation.
2. After images load, rotate to landscape.
3. Notice the featuredImageView's frame height has shrunken from the expected height.
4. Recycle the cell and notice the height is as expected.
5. May require a second rotation to trigger the issue.

![reader-refresh-landscape-issue](https://cloud.githubusercontent.com/assets/1873422/20445126/715ab13a-ad99-11e6-94e4-511009bbccab.gif)

This is essentially due to the cell/tableView autosizing not accommodating for the full expected height of the imageView. Might be caused by the pesky `999` height constraint priority, but using `1000` instead causes other subviews of the cell to break in height. So really, on iOS 10, we need sort of layout pass or calculation to occur on device orientation, trait collection, or frame changes.

##### Tested on [device], iOS [version], WPiOS [version]
iOS 10 only, does not reproduce on iOS 9. iPad.

**Comment by aerych** [comment]
Can you still repro this one @kurzee?  I'm not having any luck when I try.

Assuming resolved. If it turns out we can repro then we can reopen.

**Comment by kurzee** [comment]
Retested, all good on this one!

**Comment by aerych** [comment]
Thanks for checking!
