### ISSUE TITLE
Notifications: Duplicate Notifications on 6.7

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#6213]
#Whilst using the latest 6.7 release over the weekend, I noticed that my Notifications section included a number of duplicated notifications: two notifications (one mention, one '10 likes') had repeated 3x each:

![img_4947](https://cloud.githubusercontent.com/assets/4780/20481217/f7d6f192-afdd-11e6-9866-7dd3a46c87e8.png)

I viewed one of the mention comments at the bottom, and the app then marked **two** of them as being read:

![img_4948](https://cloud.githubusercontent.com/assets/4780/20481226/03cc8002-afde-11e6-8457-ae7538e4ea75.png)

I was using my iPhone 7, which is on the latest version of iOS.

cc @jleandroperez

**Comment by rachelmcr** [comment]
I also saw duplicate notifications over the weekend in the latest 6.7 beta. I confirmed that the duplicate only appeared in the iOS app; the Android app and web only showed a single notification.

Duplicate in the iOS app:

![2016-11-20 16 07 22](https://cloud.githubusercontent.com/assets/8658164/20482256/9cbcd3c0-afe3-11e6-9781-b555c1cf08cf.png)


Single notification on the web:

![2016-11-20 16 07 15](https://cloud.githubusercontent.com/assets/8658164/20482257/9fc23f4c-afe3-11e6-9b0c-9a54424c2fc0.png)


The app logs also showed only one push notification:

```
2016/11/20 13:31:58:794  Reachability - Internet - WiFi: N  WWAN: Y
2016/11/20 13:31:58:810  <WordPressAppDelegate: 0x1702a2520> application:didReceiveRemoteNotification:fetchCompletionHandler:
2016/11/20 13:31:58:852  Received push notification:
Payload: {
    aps =     {
        alert = "November 20: Your best day for likes on [redacted]";
        badge = 1;
        "content-available" = 1;
        sound = "n.caf";
    };
    blog = 112950019;
    "blog_id" = 112950019;
    "note_id" = 2704373327;
    type = c;
}
2016/11/20 13:31:58:853  Current Application state: 2
2016/11/20 13:31:58:922  Running Notifications Background Fetch...
2016/11/20 13:31:58:954  <WordPressAppDelegate: 0x1702a2520> application:didReceiveRemoteNotification:fetchCompletionHandler:
2016/11/20 13:31:58:955  Received push notification:
Payload: {
    aps =     {
        alert = "[redacted] and 10 others liked your post [redacted]";
        badge = 2;
        "content-available" = 1;
        sound = "n.caf";
    };
    blog = 112950019;
    "blog_id" = 112950019;
    "note_id" = 2703557571;
    type = c;
}
2016/11/20 13:31:58:955  Current Application state: 2
2016/11/20 13:31:58:972  Running Notifications Background Fetch...
2016/11/20 13:32:03:663  Finished Notifications Background Fetch!
2016/11/20 13:32:04:643  Finished Notifications Background Fetch!
```

**Comment by jleandroperez** [comment]
Thanks @rachelmcr, those logs were extremely helpful!!!

Will have this fixed ASAP!

**Comment by jleandroperez** [comment]
Updating the tag to 6.8 since this is happening with a build cut off from Develop!
