### ISSUE TITLE
Site Picker: Sort recently used sites to the top of the site list

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6217]
In Calypso web, if you have 15 or more sites, there is a "recent sites" group that appears at the top of the site picker (see https://github.com/Automattic/wp-calypso/pull/2742) to keep you from having to scroll every time to find recently used sites.

This shows your most recently used sites at the top of your site list, with other sites shown alphabetically beneath it:

![screen shot 2016-11-21 at 4 16 37 pm](https://cloud.githubusercontent.com/assets/8658164/20490516/279778a2-b006-11e6-8943-22bb19c0761e.png)

We could do the same in the app, showing the three most recently used sites at the top of the site list. Currently, we show the primary site at the top of the list with other sites listed alphabetically beneath that:

![2016-11-21 16 20 11](https://cloud.githubusercontent.com/assets/8658164/20490620/80303904-b006-11e6-9b97-e2607715a3f4.png)

h/t Ryan for [raising this issue](https://test.wordpress.com/2016/11/10/session-notes-back-buttons-hidden-sites-touch-image-flow-notifications-site-switching-flow-keyboard-flow-media-section-desktop-first/).

##### Tested on iPhone 6, iOS 10.1.1, WPiOS 6.7.0.20161115

**Comment by koke** [comment]
There has been recent talk about that being a problem in calypso because it creates some accessibility users and, as @folletto put it:

> because “variable position” UIs basically deny the ability for a user to build up memory

Perhaps we should revisit #571 instead and allow manual sorting, or wait for the conclusions on calypso.

I'm not sure I'd label this "Broken Window" though, other than because it's inconsistent with calypso.

**Comment by koke** [comment]
It seems there are no plans to remove recent sites from calypso, so this is good to go. If possible, a site that appears on recent sites should also appear in the list with every site.

**Comment by mtias** [comment]
We store recent sites as user settings, so we could potentially show the same sites and sync between mobile and Calypso.

**Comment by koke** [comment]
That's good to know, thanks. Somehow I had assumed those would be stored per client.
