### ISSUE TITLE
Change New Post button accessibility label to Write

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#6222]
We are transitioning to "Write" as the verb for the new post button in the tab bar. Update the accessibility label accordingly. No plans yet to visually change the UI based upon this label on larger screens as of yet.

Related Android Issue: https://github.com/wordpress-mobile/WordPress-Android/issues/4815

**Comment by catehstn** [comment]
Looks like this was fixed in #4815, closing.
