### ISSUE TITLE
Site Settings: Number picker doesn't appear in discussion settings

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6226]
### Expected behavior

In the site's Discussion settings, under settings like Close Commenting, Paging, and Links in comments, there should be a number picker that scrolls to choose a number.

### Actual behavior

When you open the setting, the picker doesn't appear:

![photo 22-11-2016 18 13 12](https://cloud.githubusercontent.com/assets/8658164/20570218/abb4e6a2-b19a-11e6-96d9-c67f5258fb6e.png)

In the latest 6.7 TestFlight beta on my iPad mini, the picker loads if you rotate the device and stays visible when you rotate back.

However, in version 6.7.0.20161115 on my iPhone 6 the picker never appears even after rotating the device.

### Steps to reproduce the behavior

1. Open the My Sites tab in the app
2. Open a site's Settings
3. Open the Discussion settings
4. Open a setting with a picker, e.g. Paging

Result: The toggle and "Comments per page" settings appear, but the picker does not.

##### Tested on iPad mini, iOS 10.1, WPiOS 6.7 TestFlight beta and iPhone 6, iOS 10.1.1, WPiOS 6.7.0.20161115

**Comment by SergioEstevao** [comment]
@frosty could this be a similar issue as the date picker on post settings?

**Comment by michalkosmowski** [comment]
Hey @frosty, I looked at this one briefly and noticed that `contentView` of `PickerTableViewCell` has 0 height. Pinning top & bottom edges to the cell itself helped. Are you close with the fix or could I make a PR with it?
