### ISSUE TITLE
Site Settings: Crash after creating a new WordPress.com site on an account with no sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6227]
### Expected behavior

I expect to be able to create a new WordPress.com site while logged in to any WordPress.com account.

### Actual behavior

If I am logged in to a WordPress.com with no sites, and I try to create a new site, the app crashes. (The new site is created and appears when I reopen the app.)

The app logs show this after the new blog was created:

```
2016/11/23 17:12:11:817  <BlogService: 0x17420a650> syncBlogsForAccount:success:failure:
2016/11/23 17:12:12:045  Error: The Default Blog could not be loaded
2016/11/23 17:12:28:980  Loading Stats for the following blog: [redacted blog address]
2016/11/23 17:12:29:016  <BlogService: 0x1742063f0> syncBlogsForAccount:success:failure:
```

### Steps to reproduce the behavior

1. Log in to a WordPress.com account without any sites (or delete any sites on the account)
2. Open the My Sites tab
3. Create a new WordPress.com site

Result: After the site is created, it starts to load on the My Sites tab and then the app crashes.

**Comment by bummytime** [comment]
@rachelmcr I am going to close this issue for now. I attempted to repro a few times using the latest `develop` build and was not able to see the crash.
