### ISSUE TITLE
Jetpack: Share Extension not configured after logging into .com

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#6239]
### Expected behavior
When a user connects to WordPress.com for their self-hosted site the share and today extensions should be configured.

### Actual behavior
Haven't actually confirmed this yet but I believe that the shared keychain is not configured with the OAuth bearer token in this scenario.

### Steps to reproduce the behavior
1. Log in with a self-hosted username, password, and URL for a site that has Jetpack enabled and configured.
2. Get prompted to connect to WordPress.com because of Jetpack. Log in.
3. After logging in, exit and try the share extension and today extension. Both should be configured.

**Comment by rachelmcr** [comment]
I tested this with a fresh install of WPiOS 6.8 on my iPhone 6, iOS 10.2.1 using the steps above. After adding my self-hosted site and logging in to WordPress.com through the site's Stats section, both the share extension and the today extension worked as expected.

Closing as this does not seem to be an issue; please reopen if I missed something.
