### ISSUE TITLE
Share Extension: Allow Any Attachment

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#6246]
As of now, only Media Attachments are supported in the Share Extension. Let's enhance this, and add support for any file type.

This would prove useful when dealing with Apps like `iCloud Drive` / `Dropbox`. 

Android version of this issue [available here.](https://github.com/wordpress-mobile/WordPress-Android/issues/4842)

**Comment by rachelmcr** [comment]
An iOS user sent us feedback requesting support for audio files in particular. (Ref: AppbotX 26923)

**Comment by rachelmcr** [comment]
An iOS user (with a WordPress.com plan) requested audio upload support, mentioning that this was why they upgraded their site's plan. Internal ref: 184694-h

**Comment by rachelmcr** [comment]
A user asked in support about how to upload audio files (internal ref: 200755-h).

**Comment by annacmc** [comment]
An iOS user (WordPress.com paid plan) wanted to share Voice Recording audio, they were happy to share via voice recording or via iCloud. (ref: 2538352-zd)

**Comment by reginabally** [comment]
Another request in 4011472-zd-woothemes.
