### ISSUE TITLE
Media: Add accessibly sized images to the media picker flow

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6264]
It would be great to rework our media picker flow to include accessibly sized images. One option might be to add a step where the image you tap on is viewable at a larger size, and you can confirm that is the image you want to use.

Ryan raised this issue [here](https://test.wordpress.com/2016/12/01/session-notes-overflow-reflow-embeds-image-selection-double-notifications-tab-titles-working-with-text/):

> Wishing our image pickers had accessibly sized images like Telegram. This is media flow I can see and use.

### Screenshots from Telegram's flow:

![image](https://cloud.githubusercontent.com/assets/8658164/20834565/0bc27830-b88e-11e6-8e9b-33249120eaf6.png)

![image](https://cloud.githubusercontent.com/assets/8658164/20834573/1279b274-b88e-11e6-8086-a27f3ad24372.png)

![image](https://cloud.githubusercontent.com/assets/8658164/20834578/154ae3b0-b88e-11e6-9722-dbebb8aca90a.png)

![image](https://cloud.githubusercontent.com/assets/8658164/20834579/1889e42c-b88e-11e6-9726-fca2572dc590.png)

![image](https://cloud.githubusercontent.com/assets/8658164/20834583/1ca82e4c-b88e-11e6-8628-fcd86213fa67.png)

### Screenshots from our current flow:

![2016-12-02 12 53 07](https://cloud.githubusercontent.com/assets/8658164/20834717/a101bb5e-b88e-11e6-987c-f870c8ac9b9b.png)

![2016-12-02 12 53 13](https://cloud.githubusercontent.com/assets/8658164/20834718/a101c2de-b88e-11e6-9a4b-36378eb48621.png)

![2016-12-02 12 53 17](https://cloud.githubusercontent.com/assets/8658164/20834720/a1023c64-b88e-11e6-90a9-f406cd255c00.png)

![2016-12-02 12 53 25](https://cloud.githubusercontent.com/assets/8658164/20834719/a1021e32-b88e-11e6-926b-8b3a25d342be.png)

##### Tested on iPhone 6, iOS 10.1.1, WPiOS 6.8.0.20161129

**Comment by SergioEstevao** [comment]
@rachelmcr I think this was solved in the 7.0 release? you can now force touch or long press to see full screen preview of the image.

**Comment by rachelmcr** [comment]
Cool! I wonder if there's a way to make that feature more discoverable (I wouldn't think to long press without being prompted to try it) but I'll close this issue as it's now resolved. :)

**Comment by SergioEstevao** [comment]
In the near future we can try an approach similar to Telegraph. I think this will be part of the scope of the media project.
