### ISSUE TITLE
Add Publicize to Post Edit options

### ISSUE THREAD

**Issue by kristarella** [wordpress-mobile/WordPress-iOS#6268]
Enabling some WordPress.com/Jetpack features in the post options would be nice in general. This one was specifically requested by a WordPress.com customer.

### Expected behavior

Be able to select which connected Publicize networks receive post upon publishing in the post options panel.

### Actual behavior

No such option

**Comment by kristarella** [comment]
This is a feature request. Seems I'm not able to add the relevant labels.

**Comment by rachelmcr** [comment]
This was also mentioned by a user in 148558-h who was looking for the per-post sharing settings that exist in the web editor.

Related issue: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/298

**Comment by rachelmcr** [comment]
This feature was added, coming in version 7.1 (in beta). Dupe issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/2698
