### ISSUE TITLE
Me: App doesn't load Gravatar when account email includes capital letters

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6270]
### Expected behavior

I expect to always be able to upload and see my account's Gravatar on the Me tab when logged in.

### Actual behavior

If my account email includes capital letters, I can upload a new Gravatar (and it appears on Gravatar.com) but if I close the app and reopen it, the Gravatar is gone.

### Steps to reproduce the behavior

1. While logged out of the WordPress app, select "Create a site"
2. Create a new account and site, using an email address with capital letters
3. On the Me tab, add a new Gravatar
4. Confirm the Gravatar is added and appears on the Me tab
5. Swipe to close the app
6. Reopen the app. Result: The Gravatar is no longer there
7. Update the account's email address to replace the capital letters with all lowercase letters
8. Reopen the app. Result: The Gravatar you uploaded previously appears

##### Tested on iPhone 6, iOS 10.1.1, WPiOS 6.8.0.20161129

**Comment by rachelmcr** [comment]
User reports:

- 148168-h
- 141244-h

**Comment by astralbodies** [comment]
Turns out we're not consistently following three rules for creating Gravatar hashes in our app:
1. Trim leading and trailing whitespace from an email address
2. Force all characters to lower-case
3. md5 hash the final string

Fix any image views that load Gravatars and also the service to update the Gravatar.

**Comment by astralbodies** [comment]
Closed with f022173.
