### ISSUE TITLE
Reader: Figure tags can include unwanted paragraphs

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6280]
It looks like images with captions are presented with figure tags that can sometimes include a nested empty paragraph above and blow the image and caption.  It probably doesn't make sense to remove all empty paragraph tags (sometimes the formatting might be desired by the author) but this is a case where we probably should.  Let's do the r&d and add this rule to the rich text formatter.

**Comment by yaelirub** [comment]
We're transitioning to using Webview for post rendering which is meant to solve rendering issues similar to this. Closing this. Please reopen if necessary
