### ISSUE TITLE
Reader: Sometimes the detail loads with its content already scrolled.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6288]
Title has it. 
Props to @rachelmcr and @dougaitken for the report.   Its not something that always happens, but only with certain posts.  Doug found one on a private site that seems to exhibit the behavior consistently.

**Comment by kurzee** [comment]
@aerych can probably close this one if you want

**Comment by aerych** [comment]
Let's keep it open until we roll out another beta. I wasn't able to reproduce this myself and I want to make sure those who were seeing it before aren't seeing it after the patch.

**Comment by dougaitken** [comment]
As a note. I'm on latest build, I believe (6.8.0.20161205) and still having this issue. It _seems_ to be mainly on long form posts, support rotation recaps, product overviews and such. 
Some other posts I click into from Reader, and it will start with the author name being the highest on the screen - cutting off the title. I can so Lookback if needed, and I don't have Extra Debug enabled yet

**Comment by aerych** [comment]
> As a note. I'm on latest build, I believe (6.8.0.20161205) and still having this issue

Hey @dougaitken :)  We haven't made a new beta available with this patch yet, but one should be coming soon.  Thanks for following up!

**Comment by kathrynwp** [comment]
I'm also having this issue on iPad / iOS10.1.1 / 6.8.0.20161205. I can't find any rhyme or reason to it, and posts start at different places - sometimes just a line down, sometimes three, and sometimes several paragraphs down the page.

Looking forward to the next version, and just let me know if I can do anything else. Thanks!

**Comment by aerych** [comment]
No new reports since the release of 6.8.0.20161216.  Optimistically closing for now but we can revisit if needed.

**Comment by kathrynwp** [comment]
@aerych Unfortunately this is still happening for me with 6.8.0.20161216.

**Comment by kathrynwp** [comment]
It definitely seems to affect longer posts that take up more than a full screen's height in my iPad mini. Shorter posts seem unaffected; they open at the top, as expected.

**Comment by aerych** [comment]
Bummer. :/ 
@kathrynwp Could you share a link to an example post? If its on a private blog maybe ping me on slack.

**Comment by kathrynwp** [comment]
@aerych I'm no longer experiencing this issue with the new build! (6.8.20161221)

**Comment by aerych** [comment]
Yay!!!

**Comment by aerych** [comment]
Closing now that the fix is confirmed in the wild :)

**Comment by kathrynwp** [comment]
@aerych I'm experiencing this glitch again as of version 6.9.0.20170207 

Here's an example thread:

https://crossedeyesanddottedtees.wordpress.com/2017/02/07/delicious-delis-of-montreal/

Opens in the Reader at "for this quintessential deli..."

iPad retina / iOS 10.2.1

**Comment by aerych** [comment]
@kathrynwp Thanks for the heads up.  It looks like another change we made caused this one to creep back up.  We'll get it patched (hopefully for good!)

**Comment by aerych** [comment]
Patched again in #6633
