### ISSUE TITLE
WPTableImageSource: fetchImageForURL Assertion

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#6289]
### Details:
1. Log into a dotcom account
2. Open a Kudos Notification. This should push `ReaderDetailsViewController`

As a result, you'll get an assertion in `WPTableImageSource: fetchImageForURL`.

--

<img width="1220" alt="screen shot 2016-12-06 at 13 57 09" src="https://cloud.githubusercontent.com/assets/1195260/20935180/787573b6-bbbc-11e6-92b4-35ee634d558a.png">

**Comment by aerych** [comment]
Confirmed, this is the same as #6284

**Comment by jleandroperez** [comment]
Thank you @aerych!!

**Comment by aerych** [comment]
Thank YOU! :)
