### ISSUE TITLE
Notifications: Likes are not being persisted

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#6290]
### Steps:
1. Log into a dotcom account
2. Locate a Comment-Y Notification, and open it
3. Press `Like`
4. Relaunch the app
5. Reopen the same comment as in step 2

As a result, the Notification will not remain in Liked state. Note that opening the actual comment will display the proper `Like` status.

Thanks @dmsnell for finding this one!!

**Comment by jleandroperez** [comment]
By all means @koke, please, let me know if i can help with the debugging session.

Thanks **A LOT** ❤️

**Comment by koke** [comment]
Liking a comment performs the API request, but the state is only stored locally in memory (`block.setOverrideValue(true, forAction: .Like)`) so it doesn't persist between launches. I think PingHub should fix this in #6331

**Comment by dmsnell** [comment]
@koke if it's not being persisted in the app, how will Pinghub fix it?

**Comment by koke** [comment]
I was assuming liking the comment would update the note in the server and generate a push ping, but maybe it won't?

**Comment by dmsnell** [comment]
> I was assuming liking the comment would update the note in the server and generate a push ping, but maybe it won't?

the behavior I have seen is that the app updates locally as expected after liking a note. it also updates the server as expected. _however_, once the app restarts it has the wrong state. there won't be a Pinghub notification after the app boots to say, "by the way, fix your data"

**Comment by koke** [comment]
Here's the interesting bit about this. I was trying to reproduce and compare with Calypso and what's going on here is that the backend won't recalculate the note hashes until something requests the body.

So:

1. App sends the comment Like to the API, and persist the like locally (although memory only)
2. App gets killed
3. Relaunch app, forces a notes sync, all hashes look similar, no notes are updated.

PingHub won't help here, as it doesn't push updates when action status changes.

**Comment by dmsnell** [comment]
Interesting. If this is the cause then we must be missing the hook on the backend for something like `wpl_comment_add` or whatever it's named. I'll try and look and see.

In general, when some piece of content is changed the note gets regenerated automatically, or _should_.

**Comment by jleandroperez** [comment]
Closing this one as dupe of #6744 (addressed via #6871, but a backend side fix is currently in the works).

Thanks!
