### ISSUE TITLE
Reader Detail: backgrounding/foregrounding changes the scroll offset

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#6293]
1. Open Reader, select a post.
2. Background the app.
3. Foreground the app.
4. Notice the scroll offset changed by itself.

![reader-detail-foregrounding](https://cloud.githubusercontent.com/assets/1873422/20941097/a00bd19c-bbba-11e6-9641-e7cf58711843.gif)

cc @aerych

**Comment by aerych** [comment]
Potentially related to #6288

**Comment by kurzee** [comment]
@aerych yep, that looks like the exact issue.
