### ISSUE TITLE
View Post in post-post doesn't show live preview for self-hosted sites

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#6307]
As pointed out by @rachelmcr, the post-post's 'View Post' button only shows the in-app generated preview for self-hosted sites. Ideally this would show a live preview if publishing has succeeded.

![post-preview-self-hosted](https://cloud.githubusercontent.com/assets/517257/21012720/fef651e2-bd1c-11e6-88b1-ce1106fe6462.gif)

### Analysis

Because the XMLRPC api doesn't return a `permalink` from post creation, there isn't one available when the post-post is shown. There are two probable ways to fix it:

1. Update the post from post-post, which will fetch the `permalink` (as well as all other remote data about the post).
2. Change `PostPreviewViewController` to construct a url of the form `http://example.com/?p=$post_id`, as suggested by @koke

**Comment by koke** [comment]
3. Call `wp.getPost` after creating/updating a post with XML-RPC ;)

https://github.com/wordpress-mobile/WordPress-iOS/blob/0c9f61f5dcbcdeb39e49cc4477ff49ea04cc8db2/WordPress/Classes/Networking/PostServiceRemoteXMLRPC.m#L94
