### ISSUE TITLE
Activity Logs helper text overlaps with the Activity Logs label

### ISSUE THREAD

**Issue by jeffpaul** [wordpress-mobile/WordPress-iOS#6311]
### Expected behavior
The Activity Logs helper text ("The Extra Debug feature includes additional information in activity logs, and can help us troubleshoot issues with the app.") should appear below the white-background Activity Logs label section and within the light-blue-background section.

### Actual behavior
The Activity Logs help text appears too high and overlaps with the white-background Activity Logs label section.
![img_1517](https://cloud.githubusercontent.com/assets/2818133/21030141/a4bd1bde-bd62-11e6-9c23-a150462e6b1b.jpg)

### Steps to reproduce the behavior
1) Write a post while in airplane mode.
2) Click the "Update" link/button.
3) Wait for "Error occurred during saving" overlay to disappear.
4) Click "Need Help?" in the "Unable to Sync" modal.
5) View "Actual behavior" as noted above.
Note: you can also navigate here by clicking "Me" in the bottom nav, then "Help & Support".

##### Tested on [device], iOS [version], WPiOS [version]
AT&T MN592LL/A iPhone 7 Plus running iOS version 10.1.1 (14B100) and WPiOS version 6.7

**Comment by elibud** [comment]
No longer an issue on version 7.3

**Comment by jeffpaul** [comment]
I can confirm that this appears to be resolved as well on AT&T MN592LL/A iPhone 7 Plus running iOS version 10.2.1 (12D27) and WPiOS version 7.2.

**Comment by elibud** [comment]
Excellent, thanks a lot @jeffpaul :)
