### ISSUE TITLE
Offline saving causes double error messages

### ISSUE THREAD

**Issue by jeffpaul** [wordpress-mobile/WordPress-iOS#6315]
### Expected behavior
Saving a post while offline would only throw a single error/warning message noting the user that the post won't sync to the server until they're back online.

### Actual behavior
Two error/warning messages are displayed which delays the user unnecessarily.

### Steps to reproduce the behavior
1. Write a post while in airplane mode.
2. Click the "Update" link/button.
3. View the "Error occurred during saving" overlay, wait for it to disappear.
4. View the "Unable to Sync" modal.
It seems that only one of these two errors/warnings are necessary.
![img_1515](https://cloud.githubusercontent.com/assets/2818133/21032807/a0ca2864-bd71-11e6-9124-29ccd8dfe7c8.jpg)
![img_1516](https://cloud.githubusercontent.com/assets/2818133/21032811/a7bae672-bd71-11e6-8635-c5ad128f263a.jpg)

##### Tested on [device], iOS [version], WPiOS [version]
AT&T MN592LL/A iPhone 7 Plus running iOS version 10.1.1 (14B100) and WPiOS version 6.7

**Comment by bummytime** [comment]
I attempted to repro this issue using the latest `develop` branch on both iOS 10:

![test](https://user-images.githubusercontent.com/154014/35757109-52da90e0-0833-11e8-9b09-820aed975b8c.gif)

...and iOS 11:

![test2](https://user-images.githubusercontent.com/154014/35757116-593958f4-0833-11e8-8ab7-07a8bdc585fa.gif)

In both situations, the HUD appeared as expected and the "Unable to Sync" alert did not. The only way to get the unable to Sync alert to appear was to activate pull to refresh on the posts list screen.

Marking as resolved.
