### ISSUE TITLE
Incorrect FAQs case useage (i.e., faqs instead of FAQs)

### ISSUE THREAD

**Issue by jeffpaul** [wordpress-mobile/WordPress-iOS#6316]
### Expected behavior
References to acronym for Frequently Asked Questions appears as "FAQs".
_Tangential question: why not have FAQs stored locally on the device/app so that they can be referenced offline? If there are "too many", then is there a subset that would best apply for offline users?_

### Actual behavior
Messagebox displays text as "faqs" (i.e., in lowercase instead of mixedcase).

### Steps to reproduce the behavior
1. Attempt to save a post while in iOS airplane mode (or otherwise offline).
2. Get "Unable to Sync" messagebox.
3. Click "Need Help?" messagebox option button.
4. Click "WordPress Help Center" link on "Support" screen.
5. Get to "Help" screen with "No FAQs found" in "FAQ" section.
6. See "Could not fetch faqs" messagebox.
![img_1518](https://cloud.githubusercontent.com/assets/2818133/21085448/ecbcfdc4-bfd7-11e6-80ec-49c6b99ebb39.jpg)

##### Tested on [device], iOS [version], WPiOS [version]
AT&T MN592LL/A iPhone 7 Plus running iOS version 10.1.1 (14B100) and WPiOS version 6.7

**Comment by ablyx** [comment]
Hi, do you mind reproducing this bug again? I followed your steps multiple times but I couldn't reproduce the faqs. Instead, I was able to load the FAQ list.

**Comment by jeffpaul** [comment]
FYI my device is now iOS version 10.2 (14C92), but other version details are the same.

For step 1, you'll need to go to Options on a post to change the status to draft and then you'll get the save option. From there the steps are correct and I'm still able to see the "faqs" message. Reminder, you need to be offline/airplane mode to see this happen.

**Comment by bummytime** [comment]
Text has been fixed:

![img_6134](https://user-images.githubusercontent.com/154014/32669038-dae1ace2-c604-11e7-99d8-970faa31932c.PNG)
