### ISSUE TITLE
Posting: Scheduled posts with a draft status show "Publish Now"

### ISSUE THREAD

**Issue by isocialtish** [wordpress-mobile/WordPress-iOS#6326]
### Expected Behavior,
After setting options and picking a date to schedule the post in the future, when I navigate back to the post it should say "Schedule Post", when you click this option- the post is scheduled.

### Actual behavior
After setting options and picking a date to schedule the post in the future, when I navigate back to the post it says "Publish Now" when I click this option, my post is posted right away.

### Steps to reproduce the behavior
Create a new post
Add a title and text
Go to options and set the status to draft.
Change the date to something in the future.
Tap the back button
Click on the 3 dots in the upper right corner 
You'll see the option to "Publish Now"- which publishes the post now and doesn't schedule the post.

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 7, iOS 10.1.1, WPiOS 6.8.0.20161205

**Comment by rachelmcr** [comment]
In the web editor, once you choose a future date for the post it isn't possible to publish the post immediately. You can only keep it as a saved draft or schedule the post for the set publish date.

We should either offer a "Schedule Now" quick action or just remove that "Publish Now" action from the action sheet. (When the status is set to Scheduled instead of Draft, that action doesn't appear on the action sheet at all.)

cc @frosty

**Comment by frosty** [comment]
Thanks for the clarification on this @rachelmcr. I _think_ it probably makes most sense to offer a Schedule Now quick action in this situation – the point of the quick action is generally to move the post to / from a draft state without needing to delve into Post Settings.

**Comment by rachelmcr** [comment]
Agreed. In that case it probably makes sense to have a Schedule Now quick action both when the status is Draft with a future publish date, and when the status is Scheduled.

**Comment by elibud** [comment]
@rachelmcr:

We should also remove the "Publish" action for the post lists for Scheduled posts, does that make sense?

Do you imagine the "Schedule Now" action taking you to the Post Option screen? If so, I think we can probably omit it, since you can already navigate there by tapping Options.

**Comment by elibud** [comment]
This one is waiting on a resolution on: https://github.com/wordpress-mobile/WordPress-iOS/pull/7113

**Comment by designsimply** [comment]
Tested and confirmed using the steps provided that the "Publish Now" was removed from the quick action menu after saving a draft with a future publish date:

<img alt="img_1253" src="https://cloud.githubusercontent.com/assets/1119271/26462582/9c4c22f0-413e-11e7-9491-0d2304943977.PNG" width="270" />

Tested with iPhone 6S, iOS 10.3.2, WPiOS 7.7.0.20170522.
