### ISSUE TITLE
Notifications badge inside app doesn't match outside

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#6330]
### Expected behavior
When I've received a push notification and there is a badge count on the app icon, I expect to see the orange dot inside the app on the notifications tab given that the notifications tab wasn't in focus when the state of the UI was archived.

### Actual behavior
The orange dot does not show up on the notifications tab after launching the app.

### Steps to reproduce the behavior
1. Put the app on the My Sites tab.
2. Exit the app. (you might have to force memory pressure to engage state restoration)
3. Let a push notification come through. The app icon should show a count.
4. Launch the app. You should still be in My Sites. The notification tab won't have an orange dot.

##### Tested on iPhone 7 Plus, iOS 10.2, WPiOS 6.8 internal beta

cc: @koke

**Comment by designsimply** [comment]
Tested and confirmed today with iPhone 6S, iOS 10.3.1, WPiOS 7.5.0.20170425.

**Comment by ScoutHarris** [comment]
Tested on 10.4. The notification indicator now works as expected.


<img width="300" alt="notif" src="https://user-images.githubusercontent.com/1816888/41628146-7e160d2a-73e0-11e8-95f7-45e4bb6ee00c.png">
