### ISSUE TITLE
"Site Detail" title in Reader Stream Detail is different than on Android where it's "Reader Blog"

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#6333]
Change it so it matches Android

**Comment by aerych** [comment]
I think both apps are doing it wrong :)
Rather than "Reader Blog" or "Site Title" both apps should probably show the title of the site itself for consistency with Calypso.

Thoughts?

**Comment by aerych** [comment]
Also cc @nbradbury

**Comment by kwonye** [comment]
@aerych totally agree. I'll change it on both 🙇

**Comment by kwonye** [comment]
Actually, before I do, I'm going to wait for @nbradbury's response in case he wants to veto.

**Comment by nbradbury** [comment]
I was about to say we should show the site title, just as we do on the web :)

**Comment by kwonye** [comment]
Both judges have spoken. It shall be done.

![giphy](https://cloud.githubusercontent.com/assets/1158819/21271148/9acdf122-c36e-11e6-9db8-f16ade10aa6b.gif)
