### ISSUE TITLE
RTL support in Stats Widget

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-iOS#6335]
Contacted by a user, the title on this screen should read RTL:

![7804e1bc9292000614670761deaa4ea91a6c773f](https://cloud.githubusercontent.com/assets/40213/21214093/e582c9a8-c298-11e6-9a2e-311975c0e900.jpeg)

**Comment by koke** [comment]
@astralbodies I've tried fixing this setting natural textAlignment for all the labels, but I have no idea why the stack view isn't flipping the views, and I'm getting no changes at all. Any insights?
![simulator screen shot 2 feb 2017 13 12 28](https://cloud.githubusercontent.com/assets/8739/22548949/43ab69d2-e949-11e6-822f-dc9072471880.png)

**Comment by astralbodies** [comment]
That's a good question. I suspect the translations/strings aren't being read by the target properly. Visitors and Views should be translated but the string is only in the main target bundle. We may just want to share the strings resource file between all the targets given how we translate things.

I bet those strings will still be in English in any language you choose. 😔

**Comment by koke** [comment]
> I bet those strings will still be in English in any language you choose. 😔

That sounds right, I have my phone in Spanish and it's the only widget in English

**Comment by koke** [comment]
Fixed in #6679
