### ISSUE TITLE
Reader Comments: `<pre>` tags with unexpected spacing

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#6346]
### Expected behavior

Not sure if this is particularly related to `<pre>` tags, but notice the vertical spacing difference between a Reader comment with a block of pre text:

iOS

![simulator screen shot dec 18 2016 3 59 13 pm](https://cloud.githubusercontent.com/assets/1873422/21296909/e76826e6-c53b-11e6-915d-edfe75ba99b3.png)

Web:

<img width="258" alt="screen shot 2016-12-18 at 4 06 31 pm" src="https://cloud.githubusercontent.com/assets/1873422/21296914/f761adce-c53b-11e6-8c16-0ce8a1efd424.png">

https://kurzee.wordpress.com/2016/12/01/new-post-with-comments/

Note: a `<blockquote>` renders as expected.

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 6 Plus simulator, iOS 10.2, both `develop` and `issues/filter-new-lines` branch from https://github.com/wordpress-mobile/WordPress-iOS/pull/6337

**Comment by aerych** [comment]
Guessing paragraph spacing gets set to 0 for pre tags just like it does for lists and blockquotes.  If so we can just add padding like we do for the others.
