### ISSUE TITLE
Clean up blog selector

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#635]
It appears `BlogSelectorViewController` and `ReaderUsersBlogsViewController` do the same job. Pick one and trash the other.

Since there's no more quick photo, there's probably more unused classes related to that.

**Comment by rachelmcr** [comment]
I looked for references to each and couldn't find `ReaderUsersBlogsViewController` anywhere in the code anymore. Is there other cleanup to be done or can this issue be closed now?

**Comment by koke** [comment]
Seems fixed, thanks
