### ISSUE TITLE
Identify failed signups in Helpshift

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6361]
We need add a tag to our Helpshift implementation to identify signup errors. Let's use this tag: `origin:signup-error`

At the moment signup errors and issues are not tagged or otherwise identified in Helpshift. Instead, they show up identical to login errors (with `Source: Failed login` metadata). A separate tag will help us differentiate between signup errors and login errors for better support and issue tracking.

#### Related issues
Related Android issue: https://github.com/wordpress-mobile/WordPress-Android/issues/4911
See also this issue for related Helpshift improvements (for login errors): https://github.com/wordpress-mobile/WordPress-iOS/issues/5308

cc @bummytime (I opened this as a separate issue, but we can merge it with the work in #5308 if you think it can all be done at once.)

**Comment by nheagy** [comment]
## TODO:

- [ ]  Add `origin:signup-error` tag

**Comment by nheagy** [comment]
Fixed in #6469
