### ISSUE TITLE
View tags in page options

### ISSUE THREAD

**Issue by catehstn** [wordpress-mobile/WordPress-iOS#6366]
### Expected behavior

Clicking on page options shows tags.

### Actual behavior

Tags are missing in page options.

### Steps to reproduce the behavior

Go to a page, and select options. Tags are not visible.

##### Tested on [device], iOS [version], WPiOS [version]

iPad, 10.2, WP 6.7

**Comment by rachelmcr** [comment]
See related discussion for supported page tags in Calypso: https://github.com/Automattic/wp-calypso/issues/6934#issuecomment-234089452

**Comment by designsimply** [comment]
I tested this today with WPiOS 13.4 and found this request is still valid.

Testing steps:

1. Go to My Site > Themes.
1. Activate a theme that supports pages as part of the Featured Content area, such as [Sketch](https://theme.wordpress.com/themes/sketch/).
1. Go to Blog Posts > More > Posts Settings.
1. Look for the option to view and modify tags for the page.

**Result:** cannot edit tags for pages on sites using a theme which has added support for tagging pages.

**Note:** I verified that I was able to edit tags for pages on the same site using Calypso. ([screenshot](https://user-images.githubusercontent.com/1119271/67596101-38c81c80-f725-11e9-8600-eb489cf6b388.png))

<img src="https://user-images.githubusercontent.com/1119271/67596134-4b425600-f725-11e9-8ab3-459ddd10e5c4.PNG" width="270" alt="IMG_2974 1">
<sup>Tested with WPiOS 13.5.0.0 beta (TestFlight) on iPhone 6S iOS 13.1.2 using the `Sketch` theme on a WordPress.com Free site `madefortesting426.wordpress.com`.</sup>

**Comment by rachelmcr** [comment]
@designsimply Since pages don't support tags by default, what do you think of closing this issue and tracking it as part of the larger issue https://github.com/wordpress-mobile/WordPress-iOS/issues/500 for supporting custom post types, taxonomies, & fields?

**Comment by yaelirub** [comment]
Hey @rachelmcr , I'm cleaning up issues backlog as part of my hack week project, your suggestion sounds good to me. Closing this as it referenced in the issue you linked and could be handled as part of it
