### ISSUE TITLE
Keyboard blocks unsaved changes message, requires force close to resume post

### ISSUE THREAD

**Issue by kriskarkoski** [wordpress-mobile/WordPress-iOS#6367]
### Expected behavior

Leaving the app and returning should allow you to continue/resume posting

### Actual behavior

Returning to the app shows an "Unsaved changes" message, but the keyboard overlaps it and there is no option to close it. As far as I have found the only way to resume the post is to double-click home, force close the app, then return and open the saved draft.

### Steps to reproduce the behavior

1. Leave the app while writing a post
2. Return to the app
3. See the "Unsaved changes" message in the background with the keyboard overlapping it and no way to continue writing or using the app

##### Tested on iPhone 6, iOS 10.0.2, WPiOS 6.7

![img_7034](https://cloud.githubusercontent.com/assets/1900444/21487624/a76fad1e-cb9b-11e6-80ed-f080f8c5ca77.PNG)

![img_7033](https://cloud.githubusercontent.com/assets/1900444/21487625/ad340808-cb9b-11e6-8d20-519cc29355ee.PNG)

The second screenshot shows that you can continue typing in the title field while experiencing this issue, but can't move to another field, collapse the keyboard, or take action on the message.

cc @lizkarkoski who experienced this issue as well and provided the screenshots

**Comment by lizkarkoski** [comment]
A new report via Twitter: https://twitter.com/user/status/821430000234745857
