### ISSUE TITLE
Media inserted into a draft not attached when published

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#6372]
### Expected behavior
All images inserted into a post using the media button will be attached to the post after publishing.

### Actual behavior
If the post is saved as a draft and then later published the images are never attached.

### Steps to reproduce the behavior
1. Create a new post.
2. Attach images.
3. Save as draft.
4. Exit out of post, re-edit.
5. Publish post.
View images on wp-admin and find them not attached to any post.

**Comment by astralbodies** [comment]
Verified this is happening.

**Comment by rachelmcr** [comment]
Fixed in #6405. Closing.
