### ISSUE TITLE
Nighttime Mode

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6373]
Staring at bright screens contributes to eye strain, and more so when there is limited environmental light.  We can help make the app friendlier to use in low-light environments by providing an optional dark color scheme for the UI.

- [ ] Devise a common approach to UI styling.  Right now we have a mix of UIAppearance API, values set in storyboards and xibs, and values set via code, some ad hoc but mostly via WPStyleGuide.  We need a single approach that can be implemented globally, and supports multiple themes.
- [ ] Make sure *ALL* UI respects a common UI styling approach.
- [ ] Add setting to toggle between the light and dark styles. 
- [ ] Ensure views respect the currently selected theme when they are created.
- [ ] Re-style any existing views when the setting is changed.

A couple of related libraries that might be good for inspiration:
[Simplenote for iOS](https://github.com/Automattic/simplenote-ios) currently uses [DB5](https://github.com/brentsimmons/DB5)
[DKNightVersion](https://github.com/Draveness/DKNightVersion) shows up in a quick google search.

**Comment by SiobhyB** [comment]
Requested in a five star review:

> This really needs a dark/night mode! I do a lot of writing at night and it would be really helpful. Other than that, the app works great.

**Comment by charliescheer** [comment]
#1883355-zen  A request from a user for dark mode

**Comment by rfaile313** [comment]
User request for dark mode in 2256257-zen

**Comment by kean** [comment]
Closed by https://github.com/wordpress-mobile/WordPress-iOS/issues/12320
