### ISSUE TITLE
Year row is not visible in scheduled post date picker.

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-iOS#6386]
We got a question from a users about how to change the year of a scheduled post. Currently, if you scroll the date row long enough the year will change, but this is a bit confusing - I originally thought that you can't do it at all. Not sure how date picker works in iOS (you can chose year in Calypso and Android app), but maybe this is something we could improve at some point.

**Comment by designsimply** [comment]
Tested and confirmed that it's not easy to schedule a post in the distant future or tell which year you are currently in using the build in datepicker. The following screenshot shows a post scheduled for 2029:

<img src="https://user-images.githubusercontent.com/1119271/37371069-c64a8418-26d3-11e8-969d-4ea56f081c99.PNG" width="270">
<sup>Tested with iPhone 6S, iOS 11.2.6, WPiOS 9.6.0.20180312.</sup>

**Comment by designsimply** [comment]
@annacmc would it be possible for you to get an idea of how often this comes up in support for us? If it's common and you can find a few examples to include for reference, that'd be nice to have for this case.

**Comment by annacmc** [comment]
Sure @designsimply I've had a hunt through Zendesk as well as asked around and have not been able to find any cases of this coming up in support for us.

**Comment by bjtitus** [comment]
With the new Post Scheduling Enhancement (https://github.com/wordpress-mobile/WordPress-iOS/issues/12686) calendar UI this issue should be resolved.
