### ISSUE TITLE
Posting: Make it harder to accidentially publish an incomplete post

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6397]
A user has shared their frustration regarding accidentally published posts and asks if there could be an "Are you sure?" prompt to help prevent premature publishing.

What could we do to help avoid accidentally publishing an incomplete post?

**Comment by rachelmcr** [comment]
An alternative to a confirmation prompt could be the option to undo a published post before it goes out to email followers/publicize connections. There's a suggestion for that kind of "undo" feature in Calypso here: https://github.com/Automattic/wp-calypso/issues/4562

**Comment by ChrissiePollock** [comment]
Brought up again in #238472-h

**Comment by oguzkocer** [comment]
I'd love to see a confirmation with a way to disable it for future and a way to reset it in Settings. So, it'd be like:

* Are you sure?
1. Yes
2. Cancel
3. Yes and never ask again

_Following this one to open a similar issue on Android when we decide how to tackle it_

**Comment by rachelmcr** [comment]
Calypso now has a publish confirmation that could be used for inspiration.

After you select `Publish` on a post, you get this publish confirmation sidebar (with the option to disable it at the bottom of the sidebar):

<img width="1415" alt="screenshot 2017-11-14 10 26 33" src="https://user-images.githubusercontent.com/8658164/32775106-6ad58688-c926-11e7-92c4-2eea8af3d56d.png">

You can also enable/disable the publish confirmation in your site's Writing settings:

<img width="744" alt="screenshot 2017-11-14 10 26 55" src="https://user-images.githubusercontent.com/8658164/32775151-8b2998ca-c926-11e7-89b6-a35eb3e5072c.png">

**Comment by ChrissiePollock** [comment]
Brought up again in #238848-h.

**Comment by iamthomasbishop** [comment]
I'm starting to work on adding a confirmation step to the new writing flow - similar to Calypso - but for now, I could see an action sheet as confirmation being an okay option until we get there. Here's what it would look like:

<img width="1506" alt="screenshot 2017-12-06 11 47 24" src="https://user-images.githubusercontent.com/1200432/33676469-6d226058-da7b-11e7-83fd-8c675d538d40.png">

Above:
1. Editor
2. When user taps on Publish
3. (For reference) when user taps on `•••`

Thoughts?

// cc @folletto @mattmiklic

**Comment by alisterscott** [comment]
I'd love to see this - the pre-publish confirmation in Calypso results in a less anxiety inducing publishing experience - especially since email notifications can't be undone for a new post
