### ISSUE TITLE
Tracking WPAnalyticsStatLogout event in too many places & inconsistently

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#6399]
### Expected behavior
`WPAnalyticsStatLogout` analytics event only fired when user logs themselves out of WordPress.com.

### Actual behavior
The `WPAnalyticsStatLogout` event is being fired from multiple places and inconsistently. Launching the app and logging in with a self-hosted account will fire that event every single time the app is launched because of code in BlogListViewController.

Places firing the event:
1. BlogListViewController in maybeShowNUX. There are some fundamental issues with causing the NUX to get shown here that may have to get resolved as well. At a minimum do not fire the logged out event here.
2. ContextManager when a migration fails and a user's data is lost.
3. When the default account change notification is received in WordPressAppDelegate and the user isn't logged in.

### Steps to reproduce the behavior
1. Set a breakpoint in either Tracker (WPAnalyticsTrackerAutomatticTracks) in the switch statement mapping the WPAnalytics enum to the Tracks event for `WPAnalyticsStatLogout`.
2. Log in as self-hosted.
3. Log out is fired.
4. Kill the app & restart.
5. Log out is fired.

##### Tested on Simulator, iOS 10.2, WPiOS develop/6.9

cc: @frosty (for split view concerns), @koke (for original BlogListViewController mods)

**Comment by ScoutHarris** [comment]
`WPAnalyticsStatLogout` is now only called in `WordPressAppDelegate:trackLogoutIfNeeded`. In addition, the login/out stats have received considerable attention from @elibud . I feel quite sure if there was still an issue we'd know about it. 😉
