### ISSUE TITLE
Command-M Keyboard shortcut does not bring up Media picker

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#6428]
### Expected behavior
Hitting Command-M on an external keyboard brings up the add media window.

### Actual behavior
Hitting Command-M does nothing.

### Steps to reproduce the behavior
1. Hit command-M on an external keyboard.

**Comment by frosty** [comment]
Closing, as this has been replaced by Cmd+Opt+M and works for me as expected in Aztec and the hybrid editor.
