### ISSUE TITLE
"True" support for RTL languages

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6432]
### Expected behavior

The app should be fully RTL when the device language is set to an RTL language.

### Actual behavior

The layout is generally reversed but not all elements (e.g. label alignment, swiping direction) is reversed as expected.

### Steps to reproduce the behavior

In the Settings app > General > Language & Region > iPhone Language set the language to an RTL language (e.g. Hebrew, Arabic).

In the app, compare the RTL text alignment, swiping, animations with the LTR layout and behavior. For example, the labels on the `/me` tab are still left aligned:

![2017-01-18 13 45 43](https://cloud.githubusercontent.com/assets/8658164/22085061/65b92f82-dd87-11e6-9d64-c90ad21cc64c.png)
![2017-01-18 14 00 01](https://cloud.githubusercontent.com/assets/8658164/22085063/66f23466-dd87-11e6-8b33-5670eb4336af.png)

##### Tested on iPhone 6, iOS 10.1.1, WPiOS 6.8.0.20170112

Related Android Issue: https://github.com/wordpress-mobile/WordPress-Android/issues/2278

**Comment by aerych** [comment]
Just documenting a few things I noticed while testing #6548 that we can come back to in another pass.

Categories:
![simulator screen shot feb 2 2017 5 33 56 pm](https://cloud.githubusercontent.com/assets/1435271/22596194/32dc5308-e9f0-11e6-8df8-c99f0f0c87f2.png)

Many text fields still type from L to R.  This one is in the geolocation feature.
![simulator screen shot feb 2 2017 5 35 35 pm](https://cloud.githubusercontent.com/assets/1435271/22596202/380b0d60-e9f0-11e6-9395-df4df179378b.png)

This one is in the comment Reply/Edit
![simulator screen shot feb 2 2017 5 36 59 pm](https://cloud.githubusercontent.com/assets/1435271/22596205/3a9cc47e-e9f0-11e6-8aca-5ba573db6992.png)

This one is in the Menu feature
![simulator screen shot feb 2 2017 5 38 58 pm](https://cloud.githubusercontent.com/assets/1435271/22596213/3fb68a26-e9f0-11e6-92b9-739696adffda.png)

Some headers in the reader remain left aligned.
![simulator screen shot feb 2 2017 5 43 34 pm](https://cloud.githubusercontent.com/assets/1435271/22596217/42e98626-e9f0-11e6-8796-d9cf1ba84ada.png)

Follow button in the reader cards
![simulator screen shot feb 2 2017 5 43 43 pm](https://cloud.githubusercontent.com/assets/1435271/22596223/470b4b68-e9f0-11e6-88d4-e2de1c4fdc86.png)

Our rich content view remains left aligned
![simulator screen shot feb 2 2017 5 45 51 pm](https://cloud.githubusercontent.com/assets/1435271/22596226/491fd36a-e9f0-11e6-96c9-64f34eb9653e.png)

The album picker is very rough.
![simulator screen shot feb 2 2017 5 47 47 pm](https://cloud.githubusercontent.com/assets/1435271/22596227/4acdd7a2-e9f0-11e6-934c-fc490c6f537b.png)

**Comment by koke** [comment]
> Many text fields still type from L to R

I think at least some of those worked right when you had a rtl keyboard selected

**Comment by rachelmcr** [comment]
I can confirm that most text fields type R to L using an RTL keyboard (e.g. Arabic, Hebrew) with an RTL device language. The exception I noticed was in comment replies (noted below).

I'll note few things I'm still seeing that aren't mentioned already, to keep track. For the most part, these are minor display issues — the changes so far already make a huge difference!

The comment reply placeholder text is still left-aligned (seen on both comment notifications and in the Reader), and the cursor appears on the left edge:

![2017-02-08 19 18 27](https://cloud.githubusercontent.com/assets/8658164/22754668/456c79ca-ee38-11e6-817a-03374ea15a9c.png)

It would also be great to have a little more padding at the bottom of the navigation bar — in Arabic the descenders are right at the bottom of the screen and the dots are almost not visible on the My Sites label.

The box-and-arrow icon to indicate links that leave the app, e.g. on the My Sites > Dashboard link, is still pointing to the right (should point to the left):

![2017-02-08 19 20 57](https://cloud.githubusercontent.com/assets/8658164/22754863/dcd0d05e-ee38-11e6-9783-b991ddc8aebd.png)

Labels in site stats (e.g. titles in the Posts & Pages module, usernames in Comments and Followers modules, country names in the Countries module) are aligned to the left instead of right:

![screen shot 2017-02-08 at 8 02 22 pm](https://cloud.githubusercontent.com/assets/8658164/22755086/90d66316-ee39-11e6-9038-f8fbdeb469c9.png)

In the Blog Posts list, there isn't as much padding as I'd expect between the ellipsis and the "More" label:

![screen shot 2017-02-08 at 8 05 07 pm](https://cloud.githubusercontent.com/assets/8658164/22755181/f4d7422c-ee39-11e6-8110-ad9cf2e5ccd2.png)

And the "Back" arrow (after tapping more) is pointed left instead of right:

![2017-02-08 19 22 54](https://cloud.githubusercontent.com/assets/8658164/22755204/0f479b3e-ee3a-11e6-9325-3da8d0675117.png)

In the editor's post options, the "Comma separated" placeholder on the Tags field has more left padding than expected:

![screen shot 2017-02-08 at 8 07 40 pm](https://cloud.githubusercontent.com/assets/8658164/22755264/52e34122-ee3a-11e6-9449-ae52675be161.png)

In the Comments or comment notifications, if a commenter's display name is in English it appears to the left of the "on [Post Title]: [Comment]" text. Note these two comments (in the Comments section) from different commenters:

![2017-02-08 19 27 41](https://cloud.githubusercontent.com/assets/8658164/22755406/f1fad194-ee3a-11e6-90d0-935bd4755252.png)

I'm still seeing display names and usernames aligned left in the People section. I'm not sure if it's because I have users with a mix of RTL and LTR display names:

![2017-02-08 19 28 43](https://cloud.githubusercontent.com/assets/8658164/22755531/71e0cf08-ee3b-11e6-8bae-04889e6498b7.png)

**Comment by koke** [comment]
> I'll note few things I'm still seeing that aren't mentioned already, to keep track

Most of these are being addressed in #6615

> Labels in site stats (e.g. titles in the Posts & Pages module, usernames in Comments and Followers modules, country names in the Countries module) are aligned to the left instead of right

Since I was using a test blog with no real traffic, I missed that :( Stats live in a different repo, so that'll need a separate PR.

> In the editor's post options, the "Comma separated" placeholder on the Tags field has more left padding than expected

It looks like `WPTextFieldTableViewCell` uses some custom margin code, but that's also [on a separate repo](https://github.com/wordpress-mobile/WordPress-Shared-iOS/blob/ccd24c8cba02ad393ceafad44b079314e2831382/WordPress-iOS-Shared/Core/WPTextFieldTableViewCell.m#L56)

> In the Comments or comment notifications, if a commenter's display name is in English it appears to the left of the "on [Post Title]: [Comment]" text

I don't see any special code that does this. My guess is that iOS would guess the direction of the sentence based on the first characters.

Looking at the [Localization Guide](https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/SupportingRight-To-LeftLanguages/SupportingRight-To-LeftLanguages.html#//apple_ref/doc/uid/10000171i-CH17-SW10):

> For text and controls, use natural writing direction that determines the writing direction at runtime by examining the first few characters of text to be displayed.

**Comment by koke** [comment]
> For text and controls, use natural writing direction that determines the writing direction at runtime by examining the first few characters of text to be displayed.

This would also mean that in theory that second comment with an Arabic display name would display right to left on an LTR interface 😮 

The right way is to:

>  insert a right-to-left mark (RLM) character, U+200F, before the variable for right-to-left languages, or a left-to-right mark (LRM) character, U+200E, before the variable for strings for left-to-right languages. Use this technique for left-to-right localizations even if you don’t have localizations for right-to-left languages

TIL

**Comment by koke** [comment]
This seems to fix it: 641938f80

![simulator screen shot 9 feb 2017 09 11 46](https://cloud.githubusercontent.com/assets/8739/22774535/d9835f6a-eea7-11e6-9f4a-1ce75eb8d5d3.png)

There might be more places like that though, where we have user generated content at the start of a string

**Comment by koke** [comment]
I've reverted the changes, as it's way trickier than it seemed at first. If you forced RTL on the whole thing, line wraps could happen at odd places:

![simulator screen shot 9 feb 2017 09 29 56](https://cloud.githubusercontent.com/assets/8739/22775329/7532cc04-eeab-11e6-8c5c-1028bb28a18d.png)

I don't even know how to type BiDi, but I think it should be `Comment :Post on Author`.

Until we figure this out, I'd rather have the text in the wrong direction than wrongly split into pieces.

**Comment by koke** [comment]
For reference, all the other strings that start with a variable:

```
$ iconv -f utf-16 -t utf-8  < WordPress/Resources/ar.lproj/Localizable.strings | grep '^"%'
"%1$@ on %2$@" = "%1$@ في %2$@";
"%1$@ on %2$@: %3$@" = "%1$@ في %2$@: %3$@";
"%@ followers" = "%@ followers";
"%@ of views" = "%@ من المشاهدات";
"%@ views" = "%@ مشاهدة (مشاهدات)";
"%@ views per visitor" = "%@ مشاهدة (مشاهدات) لكل زائر";
"%@ visitors" = "%@ زائر (زائرين)";
"%d days" = "%d من الأيام";
"%d hours" = "%d من الساعات";
"%d months" = "%d من الشهور";
"%d years" = "%d من السنوات";
"%id" = "%iي";
"%ih" = "%iسا";
"%im" = "%im";
```

**Comment by catehstn** [comment]
YES! <3
