### ISSUE TITLE
Post-post shows html in post title

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#6435]
It seems that WordPress supports html in post titles, but the post-post screen is displaying it as source. This should probably be stripped before displaying.

![img_6715](https://cloud.githubusercontent.com/assets/517257/22089170/2a754458-dd9e-11e6-9271-9f0cf55ed2d0.PNG)

**Comment by ablyx** [comment]
I would like to work on this! Using regex to strip the html tags should be good enough right?

**Comment by nheagy** [comment]
@ablyx you're definitely welcome to take a crack at this 😄 Regex is likely overkill; we present the title with HTML stripped in a few places already, so it'd be best to use existing methods.
