### ISSUE TITLE
Post-post buttons animate in every time it appears

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#6436]
When you tap on view post and preview is shown (BTW, title says "Preview"), then dismiss the preview, the buttons animate back in.

In slow motion:

![post-post-buttons-preview](https://cloud.githubusercontent.com/assets/8739/22104984/22905e40-de42-11e6-84f8-7dc340325d96.gif)

**Comment by frosty** [comment]
I also think they shouldn't re-animate when returning from a full screen share action like Messages or Mail. I guess it's the same root cause – `viewWillAppear:` is doing the animation every time it's called.

**Comment by mattmiklic** [comment]
> I also think they shouldn't re-animate when returning from a full screen share action like Messages or Mail

Agreed. I love the animation when the screen first appears, but it feels repetitive and slow to see it a second time for the same screen.

**Comment by nheagy** [comment]
Ok! I concede defeat!

Will aim to get this changed in 7.0 :D

**Comment by astralbodies** [comment]
Moved this to 7.3. @nheagy is this still on your radar?

**Comment by astralbodies** [comment]
@nheagy @koke  Is this still an issue?

**Comment by koke** [comment]
I can still reproduce on the latest internal (8.0.0.20170712)
