### ISSUE TITLE
Editor: using iOS 'Look up' hides the keyboard when resuming

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-iOS#6442]
cc @rachelmcr: I only see this behaviour on the beta app not the app store app, so it's possibly a regression introduced recently?

### Expected behavior

1. Open editor on iOS
2. Select a word
3. Choose "Look up"
4. Choose "Done"
5. Editor resumes and keyboard shown

### Actual behavior

Keyboard is not displayed and I need to close the post to be able to see the keyboard again

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 7 Plus 10.2 6.8.0 20170112 

### Movie

See: https://cloudup.com/chwLWs1NWSY

**Comment by rachelmcr** [comment]
I tested in the app store version (6.7) and the latest beta (6.8.0.20170112), and as you mentioned I only see this in the beta. @SergioEstevao do you have an idea where this regression could come from?

**Comment by ScoutHarris** [comment]
Tested on 10.3. The expected behavior has been resurrected.
