### ISSUE TITLE
Adding blockquote as first line on new post doesn't work

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-iOS#6443]
### Expected behavior

Can insert a quote on first line of new post

### Actual behavior

Can't do this. The quote button simply doesn't do anything?

### Steps to reproduce the behavior

1. Start a new post
2. Tap the quote icon

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 7 Plus 10.2 6.8.0 20170112

(This also happens in the App Store version so not a new bug)

### Video

https://cloudup.com/c7rWRyo9Mr4

**Comment by rachelmcr** [comment]
This is a known issue in the visual editor — you can't format text at the very beginning of a post: https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/754

Closing this as a duplicate. (As a side note, we will also be reviewing open visual editor issues like this when the Aztec editor launches, to see which issues persist there.)
