### ISSUE TITLE
Customizer: Trying to upload media (e.g. site logo or header image) closes the customizer

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6452]
### Expected behavior

I expect to be able to upload media in the customizer, for example:

1. Go to a site's Themes section
2. Open the customizer
3. Open the Site Identity section
4. Tap "Select logo"
5. On the "Upload Files" tab tap "Select Files"
6. Select a media source such as "Photo Library" and select an image to upload

### Actual behavior

When I tap on a media source (any source) the customizer closes and I am taken back to the Themes screen.

### Steps to reproduce the behavior

You can reproduce the behavior with the steps listed above, or with another media upload in the customizer such as a custom header image.

##### Tested on iPhone 6, iOS 10.1.1, WPiOS 6.8.0.20170112

**Comment by rachelmcr** [comment]
Users are also reporting this issue, e.g. 159668-h and 157538-h.

**Comment by bummytime** [comment]
Hi @rachelmcr! I just tried to repro this issue on the latest internal (iPhone 7+) and I'm having issues getting it to fail. Any advice? I am going to look at some older devices as well to see if that is a factor.

**Comment by rachelmcr** [comment]
Well, look at that! I can't reproduce the issue on my iPhone 6, latest internal beta, so something must have fixed it. I'll close this issue but keep an eye on it to make sure it doesn't come back.

**Comment by frosty** [comment]
I can't recreate it myself, but we've had another report of this: 222674-h
