### ISSUE TITLE
Reader: Error unfollowing a site that has been deleted

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6457]
To reproduce:

1. Create a new wpcom blog.
2. Follow the blog
3. In your Reader's following stream, confirm that posts from the blog appear.
4. Delete the wpcom blog.
5. Go to the Reader's Manage Sites screen and try to unfollow the delete blog. 

You'll see an error message stating that API requests have been disabled for that site, and the site is not removed from your following list.

I tried to reproduce this in the web reader and was able to successfully unfollow the site.  This suggests we need to update which endpoints the app calls to unfollow a site.

cc @nbradbury as this might be present in the Android reader as well.

**Comment by nbradbury** [comment]
I discussed this with the reader squad and the proposed solution is for the backend to treat unfollowing a deleted site as a successful unfollow.

However, I think this uncovers an issue in the iOS app. If we call v1.1 `sites/{site}/follows/mine/delete` on a deleted site, we get a 403 response code. I think the iOS app interprets this as meaning API requests have been disabled, hence the error message.

Note that the v1.2 endpoint returns a 404.

**Comment by aerych** [comment]
Related: https://github.com/wordpress-mobile/WordPress-Android/pull/5112
