### ISSUE TITLE
Reader: Follower count on site details screen doesn't refresh

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6467]
### Expected behavior

I expect the follower count on the site details screen to refresh when someone follows/unfollows the site. I also expect to be able to force the count to refresh by pulling to refresh the screen.

### Actual behavior

The follower count on the site details screen does not refresh (it seems to be cached from the first view in the app). While troubleshooting with a user, the user saw a very old follower count for their site; when I viewed the site in my app I saw the latest follower count. Pulling to refresh the screen did not update the count for the user.

### Steps to reproduce the behavior

1. Open the Reader tab.
2. Open the Followed Sites screen.
3. Tap a site title to view its Site Details screen.
4. Using another account (e.g. in a web browser), follow or unfollow the site to change its follower count.
5. Pull to refresh the screen in the app. Result: The count doesn't change.
6. Go back to the Followed Sites screen and then reopen the Site Details screen. Result: The count doesn't change.
7. Go back to the Followed Sites screen and/or the Reader menu screen, pull to refresh, and then reopen the Site Details screen. Result: The count doesn't change.

cc @aerych 

##### Tested on iPhone 6, iOS 10.1.1, WPiOS 6.8.0.20170112

**Comment by rachelmcr** [comment]
Screenshot of the Site Details screen with the unchanging follower count:

![2017-01-25 11 16 40](https://cloud.githubusercontent.com/assets/8658164/22288859/b5747ae0-e2f0-11e6-80fc-f54b886598d0.png)

Updated follower count in the same site's stats screen:

![2017-01-25 11 16 31](https://cloud.githubusercontent.com/assets/8658164/22288877/c2a6dff0-e2f0-11e6-97a9-f21640fae9d0.png)

**Comment by rachelmcr** [comment]
This issue was reported again by a user in support. Internal ref: 181792-h

**Comment by SiobhyB** [comment]
This came up again in an app review: p4a5px-29a-p2

**Comment by ezebecke** [comment]
I had a user with this issue. ref: 4658491-h
They were able to see the correct sats after logging out and then back again.
