### ISSUE TITLE
Comments: Edit button does nothing!

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6470]
### Expected behavior
To be able to edit the comment

### Actual behavior
Nothing!

### Steps to reproduce the behavior
Navigate to the Comments section of My Sites and select a comment.  Try to click the Edit button at the bottom right of the card.  The Edit button at the top right of the screen works fine.

![ios-edit-comment](https://cloud.githubusercontent.com/assets/7233112/22309123/e5c7ba3c-e317-11e6-9c02-00a98d7ac44c.gif)
(note that I clicked the Spam button just to demonstrate that the card itself was responsive)

**Comment by rachelmcr** [comment]
I can confirm this issue. The "Edit" icon works as expected from the Notifications screen, but the same "Edit" icon does nothing from the Comments section of My Sites. (The "Edit" link in the top right does work.)

Tested on iPhone 6, iOS 10.2.1, WPiOS 6.9.0.20170124
