### ISSUE TITLE
Notifications: "Be the first to leave a comment" persists after comments load from a notification

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6472]
### Expected behavior

When I get a comment notification, I can tap the post title to view all the comments on that post.

### Actual behavior

After I tap the post title, I see a "Fetching comments..." message on the screen. That message disappears when the comment load, but a message "Be the first to leave a comment" also appears over the comments and persists on the screen even when I scroll. (This does not happen when I load the comments from the Reader.)

Comment notification:

![2017-01-26 10 51 49](https://cloud.githubusercontent.com/assets/8658164/22328752/cc49d02e-e3b5-11e6-8613-1ed4964b9c6e.png)

Comments with persistent message:

![2017-01-26 10 51 52](https://cloud.githubusercontent.com/assets/8658164/22328775/e206338a-e3b5-11e6-96fb-fb0b473b5ed8.png)

### Steps to reproduce the behavior

1. Open the Notifications tab.
2. Tap on a comment notification.
3. Tap on the post title at the top of the notification.
4. Wait for the comments to load and note the message that loads overtop the comments.

cc @aerych / @jleandroperez

##### Tested on iPhone 6, iOS 10.2.1, WPiOS 6.9.0.20170124

**Comment by aerych** [comment]
Fixed in #6472

**Comment by jleandroperez** [comment]
Thanks for patching this @aerych!!
