### ISSUE TITLE
Draft pages missing

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#6476]
A user reports that all draft pages are missing from the app. After looking at the logs and some investigation we have this:

```
CoreData: error: (NSFetchedResultsController) The fetched object at index 2 has an out of order section name 'last week. Objects must be sorted by section name'
2017-01-26 17:07:42:492 WordPress[2148:4614655] Error fetching posts after updating the fetch request predicate: Error Domain=NSCocoaErrorDomain Code=134060 "(null)" UserInfo={reason=The fetched object at index 2 has an out of order section name 'last week. Objects must be sorted by section name'}
```

In other words, the `sortDescriptiors` and `sectionNameKeyPath` of a `NSFetchedResultsController` need to be based on the same field. This is the case, most of the times, but for drafts we are using `dateModified` instead of `date_created_gmt`, which is what we are using to build the section labels.

### Steps to reproduce the behavior

What you need to do is get into a state where there is a conflict between the section name and the sorting:

- Page A (Today)
- Page B (Last week)
- Page C (Today)

Section name is based on the date you specify for the page, and sort order is based on the actual date when you made the last change, so try this in a browser:

1. Create a draft page (Page A), set the date to 1 hour ago
1. Create a draft page (Page B), set the date to 10 days ago
1. Create a draft page (Page C), set the date to 2 hours ago
1. Open the app and go to the pages list, switch to drafts
1. Pull to refresh, the list should be empty

Note that if you edit Page B and save it, pages will appear again, but the sections will have the wrong order.

![simulator screen shot 26 jan 2017 17 19 18](https://cloud.githubusercontent.com/assets/8739/22339817/96e9298a-e3eb-11e6-957c-68ba790a7358.png)

**Comment by aerych** [comment]
Nice find!
