### ISSUE TITLE
Reader: New slide-out behaviour causes motion sickness

### ISSUE THREAD

**Issue by kathrynwp** [wordpress-mobile/WordPress-iOS#6478]
As of the most recent beta update, there's now a fixed left-hand column with Streams, Teams, Lists, Tags, with posts in a separate column to the right. When you select a post to read in the right-hand column, the new left-hand column slides to the left, disappearing off-screen.

This new behaviour immediately started giving me motion sickness after just opening just two posts. Is there a way to turn this off and return to the previous view **without** a fixed left column, or otherwise reduce the motion effect?

Tested on iPad mini retina, iOS 10.2.1, WPiOS - not sure where to find the version number now that it's been removed from the icon on my home screen.

**Comment by koke** [comment]
I recall an old thread comparing different options for the presentation, and this was the less terrible of the options. Perhaps we should consider presenting articles modally.

Or if this is still considered the "best" approach, we could check if the user has "Reduced Motion" enabled, and present reader posts without animation:

https://developer.apple.com/reference/uikit/1615133-uiaccessibilityisreducemotionena
https://support.apple.com/en-us/HT202655

cc @frosty

**Comment by frosty** [comment]
Great idea, checking for reduced motion @koke. @kathrynwp do you currently make use of that setting? (it disables things like the app switching animations in the OS itself)

**Comment by kathrynwp** [comment]
Yep, I have "Reduce Motion" set to On already.

**Comment by koke** [comment]
I have to add though that while I don't get motion sickness (and wouldn't turn on reduce motion), I find the current animation _distracting_ at the very least, and I'd love to find a subtler transition for everyone.

What if we could animate the existing post card to a full screen view? I'm thinking of how Photos presents pictures, or the folders animation in the home screen.
