### ISSUE TITLE
Posting with no internet connection pretends to work

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6479]
### Expected behavior
To be unable to publish a post when there's no network connection to the site

### Actual behavior
1) Start writing a post
2) Disable your network connection (airplane mode)
3) Click Post

You get a brief error message saying that an "Error occurred during publishing", but you're still left on the post-post success page that says "<Post title> Published just now on <Site Name>" with options to share/edit/view.  This makes it very confusing and I'm not sure if the post actually went through or not.

Note that this isn't just a case of verifying that the network is active, because I first observed it by attempting to publish to a Jetpack site that WPcom believes is connected, but the site itself is down.

**Comment by koke** [comment]
👍 I experienced this yesterday and it felt really wrong. Perhaps we could reuse the post-post screen to explain what happened.

**Comment by elibud** [comment]
Fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/7007
