### ISSUE TITLE
Jetpack: Sign-in stats page has formatting problems in landscape

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6481]
### Steps to reproduce the behavior
0) With an iPad in landscape orientation - 
1) Login to a self-hosted site that is connected to wpcom via Jetpack
2) Navigate to My Sites -> Stats
3) The wpcom username should be pre-populated in the login field...delete it
4) Close the keyboard
5) Observe the Verification Code field ghosting behind the Save button.  The wpcom account in question here does have 2FA turned on, so that may also be a prerequisite but I'm not sure

![803709216_18302357484379705120](https://cloud.githubusercontent.com/assets/7233112/22346571/953556d6-e3d2-11e6-80d6-43f216ad36ca.jpg)

The field doesn't show up in portrait orientation.  I'm not sure if it shows up on iPhone or not.

**Comment by elibud** [comment]
This also happens with the IPhone 6 on landscape mode.

**Comment by elibud** [comment]
@aerych Do you think it makes sense to re-use the login in flow here? Thx

**Comment by aerych** [comment]
@elibud Eventually. It wasn't in scope for the recent work but it would be nice to have consistent login across the app. 
Opening https://github.com/wordpress-mobile/WordPress-iOS/issues/7633 so we don't forget.

**Comment by elibud** [comment]
This was fixed on https://github.com/wordpress-mobile/WordPress-iOS/pull/6507 by @bummytime
