### ISSUE TITLE
Stats: Inconsistent pull-refresh capability

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6482]
### Steps to reproduce the behavior
1) Disable your internet connection
2) Navigate to My Sites -> Stats
3) Enable your internet connection

Pull-refresh doesn't work from here, so the only way I'm able to tell the app "I fixed my connection" is to navigate to another section and back.

Conversely:
1) With the network connected, navigate to My Sites -> Stats
2) Disable the connection
3) Pull-refresh

This appears to work, but I have to assume that it's silently failing since there's no network.  I do like that it continues to show the cached data rather than wipe it out for the "No Connection" screen, but I'd like an error message to let me know that the data is stale.

**Comment by koke** [comment]
#6489 takes care of the first part. The second I'll leave for the upcoming networking improvements, as it's something that needs to be improved across the app.
