### ISSUE TITLE
SplitView/Notifications: Disappearing navigation items

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#6494]
Needed for `release/6.9`:

It looks like the `UINavigationController+SplitViewFullScreen.swift` extension with `pushFullscreenViewController` ends up hiding the navigation items for the Notifications tab and selections. I suppose it's not supposed to since it's not actually in a splitView like the other tabs.

@frosty I tinkered with this a bit to try and find an easy fix, but I think it's probably best for you to figure out the real issue going on here, since you're _very_ familiar with the code 😉 .

![screen shot 2017-01-28 at 1 44 42 am](https://cloud.githubusercontent.com/assets/1873422/22395167/619d2ed2-e4fb-11e6-971b-55c8a0efcaa9.png)

### Steps to reproduce the behavior
1. Open up notifications on either `develop` or `release/6.9`.
2. Start selecting notifications. Notice the navigation items disappear and never return.
3. Interestingly, you can still tap and use the faded out navigation items.

##### Tested on [device], iOS [version], WPiOS [version]
iPad - `release/6.9` and `develop`.

**Comment by frosty** [comment]
Fixed by #6498
