### ISSUE TITLE
Move to CocoaPods 1.2.0

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#6496]
CocoaPods 1.2.0 is out. Let's update the project and find all the fun stuff to fix. 😄

**Comment by astralbodies** [comment]
Tried integrating 1.2.0 today and there's a bug with how it handles inherit search paths for our test target and causes the test build to fail.

https://github.com/CocoaPods/CocoaPods/pull/6437

That's merged to master and should resolve the problem. When a new CocoaPods version is cut, lets give it a try.

**Comment by Coeur** [comment]
@astralbodies please check the regression consequences on #5514.

**Comment by astralbodies** [comment]
I'm moving forward with CocoaPods 1.2.1 but am removing Helpshift and Lookback as pods and manually including. There must be a bug in CocoaPods with how framework search paths are derived still with projects that include a precompiled library.

**Comment by Coeur** [comment]
@astralbodies did you create a Minimal, Complete, and Verifiable example (MCVE) with either Helpshift or Lookback for CocoaPods team to investigate?
