### ISSUE TITLE
Reader: Gap at top of post details

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-iOS#6499]
Scrolling down a post shows a gap at the top of the screen. 
![img_2681](https://cloud.githubusercontent.com/assets/518232/22424721/1b304354-e6f8-11e6-8147-a3eadd9a7ce7.png)

### Steps to reproduce the behavior
- Open the Reader
- Tap on an article
- Scroll down the post a bit

**Comment by aerych** [comment]
The gap is actually the status bar. For some reason the status bar text color now remains white rather than shifting to black when we hide the navigation bar.  Not sure where the regression is but we'll get it sorted.

**Comment by aerych** [comment]
Closed in #6530
