### ISSUE TITLE
Passcode lock

### ISSUE THREAD

**Issue by isaackeyet** [wordpress-mobile/WordPress-iOS#65]
Title has it: a way to set a PIN or passphrase for the entire app effectively locking in any sensitive information (since all credentials are stored within the app).

Should probably be put on the shortlist.

**Comment by koke** [comment]
I don't think this is happening in the near future. Closing for now, and we can reopen if we change our minds about it.

**Comment by jeherve** [comment]
Another request for such a feature in 267943-h.

> Is there a way to turn on a passcode for the iphone x or face recognition to lock the app?

**Comment by rachelmcr** [comment]
We had another request for this in https://github.com/wordpress-mobile/WordPress-iOS/issues/10741. From that issue:

> This is an additional security layer to prevent somebody from posting potentially liable content if he/she gains access to the device.

**Comment by charliescheer** [comment]
another request 1736652-zen

**Comment by charliescheer** [comment]
I received another request for this in 2031288-zen

**Comment by designsimply** [comment]
A new request for a Touch ID or passcode unlock was posted at #12531.

**Comment by erricgunawan** [comment]
Another request from 2520814-zen

> Please add Face ID security to your app for opening to use or even add to when posting to the site along with a proper log. I just saw a friend that let another borrow his phone and the dude went right on his site a made a post without him knowing about it. Dumb mistake on his part which is why you should never let anyone borrow the phone when their battery is dead.
