### ISSUE TITLE
Reader: Swipe back from post details to list doesn't work

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-iOS#6500]
I think that it used to be possible to swipe from the reader post detail back to the list, and the same from comments to the post detail. 
it doesn’t appear to be working any longer.

**Comment by rachelmcr** [comment]
I confirmed that I can swipe back from the reader post detail back to the list, and from comments to the post detail/post list in the stable 6.8 version, but not in the 6.9.0.20170124 beta.

Possibly a side effect of the new Reader splitview layout? cc @frosty 

##### Tested on my iPhone 6 on iOS 10.2.1.

**Comment by frosty** [comment]
Thanks @rachelmcr and @daniloercoli. Looking into this now.
