### ISSUE TITLE
Hide the masterbar in web views.

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#6504]
When clicking "View Site", "View Post", or any other link that opens my wpcom site in a web view, Calypso's masterbar is visible. Because the icons are the same as the ones on our tab bar, the user could easily accidentally navigate to other parts of Calypso, causing significant confusion. For new users, the guided overlays that appear on the web could increase the chances that these accidental clicks happen.

We can append a query string to links that open webviews to hide the Calypso masterbar. It's as follows: `?preview=true&iframe=true` (thanks @folletto) ([Calypso ref](https://github.com/Automattic/wp-calypso/blob/47f1a198578f9827f73e42539baa4f112de1fac4/client/my-sites/themes/helpers.js#L20))

In my testing, I think adding this query string will both hide the masterbar, and prevent the guided overlay for new users from appearing, when in a web view. We'd want to test this with existing and new accounts to make sure it resolves the issue completely.

I haven't looked at what the situation is with self-hosted, non-Jetpack sites; we need to figure out if they see the core adminbar or not, and whether there's anything we can do about those cases.

**Comment by ScoutHarris** [comment]
> I haven't looked at what the situation is with self-hosted, non-Jetpack sites; we need to figure out if they see the core adminbar or not, and whether there's anything we can do about those cases.

Self-hosted (no JP) do still show this:

<img width="563" alt="self_hosted_bar" src="https://user-images.githubusercontent.com/1816888/40999755-097f9a48-68c9-11e8-99dd-eb0a1f32662a.png">

@mattmiklic @aerych @elibud - any suggestions on who to ask about how to hide this bar? Thank you!

**Comment by folletto** [comment]
A way — but it's very wonky — could be to inject a JS on the page that does the hiding... I know, _shivers._

Otherwise it needs to be something that gets merged into Core I think, as if it's the `no-JP` condition we have no way to add extra code.

**Comment by elibud** [comment]
Lets fix it for .com only for now then, thanks for reaching out @ScoutHarris
