### ISSUE TITLE
Stats: The "View All" item doesn't appear at the bottom of lists

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-iOS#6505]
The `View All` link/item that should be available at the bottom of lists with 10+ items is not there anymore.

### Steps to reproduce the behavior
- Open the Stats section of a blog with traffic. 
- Check the `Posts and Pages` section.
- The `View All` item is not available at the bottom of the list.

**Comment by astralbodies** [comment]
Looks like the iOS app never had **View All** on posts & pages. I think on Android you ask the API for 11 top posts and if there are 10 or less, no view all. More than 10, only show 10, but then show a view all link.

That sound right @daniloercoli?

**Comment by daniloercoli** [comment]
>  I think on Android you ask the API for 11 top posts and if there are 10 or less, no view all. More than 10, only show 10, but then show a view all link.

Right!

**Comment by rwaynick** [comment]
In #167964-hc user claims that in the Stats there was a View All link for Posts & Pages on iOS (iPhone).

**Comment by astralbodies** [comment]
@rwaynick Can you confirm with them that they mean in the app and not the mobile web? Quite honestly looking at the codebase there's no way that section supported paging ever. That being said I plan on adding support for it; just a matter of priority. 😄

**Comment by rwaynick** [comment]
@astralbodies I asked for clarification in ticket 3073446. Thanks!

**Comment by rachelmcr** [comment]
We also have a recent iOS review that mentions the "view all" link missing from stats:

> 統計情報の投稿とページのところの、「すべて表示」がなくなったので、もとにもどしてほしい。

Translated:

> Of the place of the posts and pages of statistics, since the "View All" is gone, I want you to return to the original.

I looked in the stats repo and I see at least a couple mentions of a "view all" view so I think it did exist before, for example: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/178

I'm increasing the priority on this issue since it's affecting our app rating.

**Comment by rachelmcr** [comment]
Looks like "View All" was originally implemented here: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/pull/149

**Comment by astralbodies** [comment]
I'm flummoxed! I wonder if the API changed in a way that made how this originally worked break. I'll look at the code again to figure out what happened!

**Comment by astralbodies** [comment]
API fix to be applied shortly (within the next day). Thanks for reporting this and I apologize for my confusion in understanding the issue fully (and finding the right code)!
