### ISSUE TITLE
Reader: Add search to followed sites screen

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6508]
Make the followed sites list searchable to more easily filter a long list. 
See https://github.com/wordpress-mobile/WordPress-Android/pull/5082 for the Android implementation.

**Comment by kean** [comment]
Done

<img width="320" alt="Screenshot 2024-11-15 at 9 51 14 AM" src="https://github.com/user-attachments/assets/65df7022-a03e-4f80-9b53-127a7c26b258">
