### ISSUE TITLE
Reader Comments: There is sometimes a brief delay before the no results view is hidden

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6528]
See https://github.com/wordpress-mobile/WordPress-iOS/pull/6516 for additional background. 

There can be a brief moment where the ReaderCommentViewController's list of comments is overlapped by the noResultsView, before the noResultsView is hidden.  It looks like the cause is due to a slight bit of latency after refreshing the tableView (which executes an updated NSFetchRequest).

As a bit of polish let's make sure there is no overlap.

**Comment by elibud** [comment]
Hey @aerych I'm trying to tackle this one as part of Trash Day but I can't replicate. Do you have any specific steps? Maybe a big number of comments in the post? Thx

**Comment by aerych** [comment]
No specific steps other than it being the first time the comments are fetched.  Setting the simulator to slow animations might help but I'm not sure.  Anyway, iirc it was a very very subtle thing.  I'd almost forgotten about it.  If we can't repro I'd say just close the issue.

**Comment by elibud** [comment]
Nope even with slow animations I can't see it, closing it as Won't Fix AKA 'We have bigger fish to fry'
