### ISSUE TITLE
Reader menu isn't localized

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#6532]
I switched my phone language back to Spanish, and noticed that the reader menu was still in English. I changed my account language to Spanish (from the web, since you can't do it in the app) and they still show up in English.

It looks like Calypso is [hardcoding](https://github.com/Automattic/wp-calypso/blob/12e8d2031dae64e8ced5268c79f2c39b274f647d/client/reader/controller.js#L167) the default sections.

Even if I pass `?locale=es` to the API request, the default sections come back untranslated.

![screen shot 2017-02-01 at 09 14 36](https://cloud.githubusercontent.com/assets/8739/22499504/80a519a4-e85f-11e6-99f6-ac13ddfc9831.png)

**Comment by koke** [comment]
Also I just noticed that in the web, Discover is missing if you have a non-English account language, but the API doesn't seem to reflect that.

**Comment by elibud** [comment]
Fixed by @koke via r155152-wpcom
