### ISSUE TITLE
Stats Widget: Site Selection Bug

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-iOS#6538]
A user reported that the site they selected to view in their iOS stats widget (in the notification center) keeps switching back to a different site. 

### Steps to reproduce the behavior
- Open Stats for a non-primary site on your account.
- Tap “Today” and select “Use this site.”
- Open your notification center and confirm this site shows up in the stats widget.
- Swipe to close the WordPress app.
- Open the WordPress app again.
- Open the notification center and watch as the site in the widget switches back to your primary site.

**Comment by rachelmcr** [comment]
This came up in app feedback recently:

> Le Widget n'arrête pas de changer de site pour revenir à un que j'ai enlevé de ma liste ici.
>
>C'est assez pénible.

Translation:

> The Widget does not stop changing site to return to one that I removed from my list here.
>
>It's pretty painful.

Internal ref: AppbotX 28530

**Comment by frosty** [comment]
Another report of this one:

> WordPress iOS Notification Center “Today” stats not sticking with selected website. Within a few hours, iPhone will revert to showing stats for another website.

Internal ref: 233937-h

**Comment by SiobhyB** [comment]
Another report:

> But everyday the WordPress App changes the Website to another Website.

Internal ref: 286253-h

**Comment by SiobhyB** [comment]
We received another report of the widget switching to an account's primary site rather than the site that was selected in 1369192-z.

**Comment by pmciano** [comment]
Another report 1443370-zen
