### ISSUE TITLE
App stops responding if post-post sharing to Messages is cancelled

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#6544]
App locking up, likely due to post-post's hidden presenter not being dismissed.

Reported in 6.9 beta.

### To reproduce:
1. Create a new post
2. Tap Share from the post-post screen
3. Tap Message in the share sheet
4. Without sending a message, tap Cancel

### Result:

The app no longer responds.

**Comment by koke** [comment]
Dupe of #6446?

**Comment by nheagy** [comment]
@koke absolutely is. Wasn't sure the best thing to do, so I closed that one…
