### ISSUE TITLE
Phantom Post on posts list screen

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-iOS#6550]
A user reported a phantom post showing up in the posts list on some of their sites.
It shows up with `(no title)` and no content at the top of the posts list, but only on some of their sites.
The phantom post appears at the top of the list of posts even before the posts list loads. There is a spinner underneath it, and then the rest of the posts load.

![2017-02-01-18-22-28](https://cloud.githubusercontent.com/assets/518232/22551304/965c33f4-e954-11e6-9d2f-c9410a1e40aa.png)

##### Tested on iPhone 6, WPiOS 6.9.0.20170130 and iPad mini, WPiOS 6.9 TestFlight beta.

The user don’t see the problem in the 6.8 app store version.

**Comment by rachelmcr** [comment]
We have another report of a phantom post:

>I accidentally created a post on the wrong blog (IIRC on iOS), and then deleted it (IIRC on Android). This created a phantom empty post (only visible on iOS) that continued showing up in my list of posts even when I had published other ones.

**Comment by rachelmcr** [comment]
We had another report of phantom posts. The user repeatedly started new drafts and each time tried to discard the previous attempts, but those attempts resulted in phantom posts instead of being discarded.

**Comment by rachelmcr** [comment]
We haven't had any recent reports of these phantom posts. I'm closing the issue, but please reopen if we receive more reports or if you think it merits further investigation.
