### ISSUE TITLE
Reader: When syncing menu, add a check to purge old default topics

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6556]
In cases where the app has not been updated in a long time (several versions) there is a case where the reader can show duplicates of certain default topics, e.g. following, and likes.  This happens when the v1.2 version of the menu is synced with the updated endpoint paths.  Rather than updating the existing v1.1 topics, new entries are created for the v1.2 topics. 

When syncing the menu, check for any stale default topics cached in the app but not returned from the menu endpoint, then remove any that are found.

**Comment by catehstn** [comment]
How important is this? This seems like something that should be fixed by versioning APIs, not in the app (which the people experiencing this issue are unlikely to download anyway).

1. Why is this targeting 6.9? I don't think we should patch this fix in.
2. Do we have data on app updates? How many people are on which version? Esp. interested in more regular users.

**Comment by aerych** [comment]
> How important is this?

Its a lower priority.

> This seems like something that should be fixed by versioning APIs

Nah.  This is a client-side issue with the way the app is caching content.  Not really something to do with the API itself.

> Why is this targeting 6.9? I don't think we should patch this fix in.

It should be a small patch for a minor bug, so it seems reasonable to include in 6.9. 

> Do we have data on app updates? How many people are on which version? Esp. interested in more regular users

I'm not sure I understand.

**Comment by aerych** [comment]
Took a look at this, and its a bit of a mystery.
From the behavior we've seen, my expectation was our topic sync/merge code was overlooking the older v1.1 default topics due to the difference in paths between v1.1 and v1.2 endpoints. However, looking as far back as release/5.1 the merge code appears to account for this.  
A performed a quick test in release/6.9 by pointing the reader at the v1.1 menu endpoint, syncing, then switching to the 1.2 endpoint and syncing again.  There were no duplicated topics after switching back to v1.2 and the older topics (like Freshly Pressed) were cleaned up as expected.
Something else is going on.  Since this is only affecting a handful of folks so far (as far as we know)  let's put this issue on the back burner for now and revisit the next time we receive a report of it occurring.  Hopefully we'll be able to gain some new insights.
