### ISSUE TITLE
Publish button from main Blog Posts list date triggers incorrect publish time/date

### ISSUE THREAD

**Issue by gracie** [wordpress-mobile/WordPress-iOS#6558]
### Steps to reproduce the behavior
1. In the WordPress App, go to My Sites > Blog Post on a WordPress.com or a self-hosted site.
2. Click the Blog Posts tab.
3. From this tab, find an unpublished draft from the list. Don't click edit - stay in the main list.
4. Click Publish from this list view

In screenshot: Testing with post titled "Testing Vimeo Auto Play":
![preprepublish](https://cloud.githubusercontent.com/assets/21203710/22529530/c61f53f0-e8a5-11e6-8d83-9819c66b2538.png)

### Expected behavior
See the publish date as the current date, and the timestamp as the current time.

### Actual behavior
The publish date and time stamp reflect when the post was created or last revised.

![postpublish](https://cloud.githubusercontent.com/assets/21203710/22529535/ca9dd73a-e8a5-11e6-9784-10f44315912e.png)

##### Tested on:
- iPad Mini - iOS 9.3.5, WordPress App 6.8.
- iPhone 5s iOS 10.2, WordPress App 6.8

Reported in 3037463-t

**Comment by rachelmcr** [comment]
Thanks for the report! This looks like the same issue we're working on in https://github.com/wordpress-mobile/WordPress-iOS/issues/3516 so I'm going to close this since we're tracking it there.
