### ISSUE TITLE
Me - Security: Add the ability to change WordPress.com password

### ISSUE THREAD

**Issue by daniloercoli** [wordpress-mobile/WordPress-iOS#6561]
We've received reports from users that want to change their wpcom passwords within the app.

Updating the user’s current WordPress.com password makes sense, it's a nice feature to have in the app, and it's important for mobile-only users – although I’d offer up that most people (if they’re seriously mobile-only) probably don’t even know what their current password is.

***Make sure to ask for the current/previous password before changing it with the new one***.

Android side: https://github.com/wordpress-mobile/WordPress-Android/issues/5107

**Comment by rachelmcr** [comment]
Added in https://github.com/wordpress-mobile/WordPress-iOS/pull/10773.
