### ISSUE TITLE
Reader Comments: Timestamp labels are cropped vertically

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#6567]
When viewing comments in the Reader, any descenders on the timestamp label are cropped off:

![img_0111](https://cloud.githubusercontent.com/assets/4780/22591082/8d64adce-ea0a-11e6-84b6-19a87f66b4f4.PNG)

##### Tested on iPad Pro 9.7", iOS 10.3 (beta), WPiOS 6.9.0.20170203

cc @aerych

**Comment by aerych** [comment]
Nice catch!

**Comment by aerych** [comment]
Closed in #6575
