### ISSUE TITLE
Notifications: Add more detail to expanded notifications

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6571]
Here's a mockup of a potential new design for expanded notifications, with Reply/Like/Approve/Unapprove buttons.  Note that this excludes Trash and Spam, which are destructive and can be reached by tapping the notification to open the app. We should get data on which actions are most-used, we might decide to include a different set here based on that.

Here's some discussion around the Android implementation: https://github.com/wordpress-mobile/WordPress-Android/issues/4031

![image](https://cloud.githubusercontent.com/assets/7233112/22605779/5d725084-ea1f-11e6-92e2-f6e56694cdc8.png)

cc: @mattmiklic

**Comment by negna1** [comment]
if this issue is still open i would like to work on that

**Comment by jkmassel** [comment]
We've had this for a while – closing.
