### ISSUE TITLE
Notifications: Add ability to reply to comments directly from the notification

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6572]
Here's a mockup of a potential new design for adding the ability to reply to a comment notification from the notification itself, like in Messages.

![image](https://cloud.githubusercontent.com/assets/7233112/22605932/f9774d54-ea1f-11e6-9243-dfdca8ab2093.png)

cc: @mattmiklic

**Comment by jblz** [comment]
@kwonye and I tested this (on 10.6 -- I need to update!) and it seems it's working:

![ios-reply-to-comment-notifications0](https://user-images.githubusercontent.com/1587282/49700167-e3ccf780-fba0-11e8-9e14-88c3ee7ecd60.jpg)
![ios-reply-to-comment-notifications1](https://user-images.githubusercontent.com/1587282/49700170-e4fe2480-fba0-11e8-8234-635b23532535.jpg)


...should this issue be closed?

**Comment by kwonye** [comment]
Yes, thanks for testing!
