### ISSUE TITLE
Themes: Enable Themes section for Jetpack-connected sites & AT Business sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6588]
### Expected behavior

All WordPress.com or Jetpack-connected sites should have a themes section (to match Calypso). Jetpack-connected sites & Business sites that have been automatically transferred should display themes available for those sites.

### Actual behavior

Currently, only WordPress.com sites have a Themes section.

**Comment by elibud** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/7468
