### ISSUE TITLE
Primary domain URL doesn't update

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#6592]
When changing the primary domain for a site, the app isn't updating to display the new URL.

Logging out and then in again will force showing the new URL, but future changes will once again be ignored.

**Comment by charliescheer** [comment]
I checked this issue out just now and if you swipe down on the site picker the domain is updating.

We can probably close this issue.

**Comment by thehenrybyrd** [comment]
Can also confirm in 18.2 that the primary domain updates when changed, with either pull-to-refresh or navigating elsewhere and then back to My Site. Closing this issue.
