### ISSUE TITLE
Post Options: Improve UI of the tag field

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6611]
### Expected behavior
To receive feedback on the tags I'm creating

### Actual behavior
The tags field is a little confusing, and offers no feedback as to whether I have the format correct. Confusingly, it doesn’t show spaces typed at the end of the text until I type another non-space character.

### Steps to reproduce the behavior
1) Create a new post
2) Open the Options page
3) Begin typing in the Tags field, including spaces

This shows that spaces don't show up until another non-space character is typed:
![ios-tag-ui](https://cloud.githubusercontent.com/assets/7233112/22743756/2d564176-ede9-11e6-9aee-ea563ba38ac3.gif)

It would nice to mimic the Calypso web feature of marking tags once they're added.  It also provides auto-complete for existing tag names.  You can't see it in this animation, but the tags are transformed once you type a comma.

![ios-tag-calypso](https://cloud.githubusercontent.com/assets/7233112/22743898/9ca93ea2-ede9-11e6-8428-2de6feccca20.gif)

**Comment by rachelmcr** [comment]
A user shared feedback that they use the web editor to add tags and categories because the tag field in the app is hard to use, especially because the lack of autocomplete results in similar but not matching tags.

I agree that it would be great to have better feedback about whether I formatted the list of tags correctly, and have an autocomplete feature (which is currently part of the Android app).

**Comment by rachelmcr** [comment]
Tags came up again in an app review (4 stars):

> Works well but lacks some functionality from the browser version that is too important to leave out. For instance - having to type out tags with no suggestions.

**Comment by rachelmcr** [comment]
And from a recent 3-star review:

> Disappointed that I can't access pre-existing tags when I post.

**Comment by rachelmcr** [comment]
Another user requested auto-complete for tags in the editor. (Ref: Appbotx 27871)
