### ISSUE TITLE
Reader: Better handling of Gravatars and Blavatars

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6618]
As part of the reader UI refresh, we want to improve the handing of gravatars and blavatars. 

When a post has a gravatar but no blavatar, we'll show just the round gravatar.
![gravblav-grav](https://cloud.githubusercontent.com/assets/1435271/22761495/962bc586-ee20-11e6-909c-e6511a84b2e3.jpeg)

When a post has a blavatar but no gravatar, we'll show the square blavatar.
![gravblav-blav](https://cloud.githubusercontent.com/assets/1435271/22761500/9925870e-ee20-11e6-9088-c53572ff4b36.jpeg)

When a post has both a blavatar and gravatar, we'll show both icons, with the gravatar overlapping the blavatar.
![gravblav-both](https://cloud.githubusercontent.com/assets/1435271/22761504/9d91b966-ee20-11e6-83cf-5e254164a4fc.jpeg)

We'll do this for both cards and post detail.

**Comment by designsimply** [comment]
The Reader detail screen was updated as part of the Reader Improvements project that shipped in July 2020 in WPiOS 15.2.

<sup>(internal reference: pbArwn-gP-p2)</sup>

Here are some current screenshots of the Reader detail screen for reference:

Site icon and user icon both set|Only user icon set|Only site icon set|Neither site nor user icon set
---|---|---|---
![IMG_4572](https://user-images.githubusercontent.com/1119271/91601190-7047bc80-e926-11ea-9593-926603ec3b9f.png)|![IMG_4573](https://user-images.githubusercontent.com/1119271/91601272-92d9d580-e926-11ea-84a6-f9acfc3d3d85.png)|![IMG_4577](https://user-images.githubusercontent.com/1119271/91602371-79d22400-e928-11ea-9b17-04c904a1c538.png)|![IMG_4579](https://user-images.githubusercontent.com/1119271/91602952-5cea2080-e929-11ea-845e-2e277d7a8d55.png)

<p style="clear:both;"><sup>Tested with WPiOS 15.6.0.1 TestFlight beta on iPhone 11 iOS 13.6.1.</sup></p>

On the Reader main stream, only the site icon displays and only if it is set.

<img src="https://user-images.githubusercontent.com/1119271/91603282-f580a080-e929-11ea-8a89-b8a8c74d6762.png" width="270" alt="IMG_4580">

<p style="clear:both;"><sup>Tested with WPiOS 15.6.0.1 TestFlight beta on iPhone 11 iOS 13.6.1.</sup></p>
