### ISSUE TITLE
Reader: Add in-stream recommendations.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6620]
As part of the reader refresh, we want to begin displaying recommendations mixed among the posts in a user's following stream, and potentially other streams in the future.  Recommended posts are presented as any of the refreshed card styles and include a follow button.  

Details on frequency of presentation tbd.

### Examples
Calypso: 
<img width="534" alt="screen shot 2017-02-08 at 5 13 29 pm" src="https://cloud.githubusercontent.com/assets/1435271/22761948/8ed87dfe-ee22-11e6-90c6-b82b268b9eb5.png">

**Comment by jkmassel** [comment]
We have this now with the webview-based reader
