### ISSUE TITLE
Aztec: Verify Post Password functionality

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#6631]
In `WPPostViewController` (and the legacy VC) there's some code referring to post password and the original post upon an "autosave". Verify post passwords work correctly without any of this code. Make sure to include publishing a post with a password then going back and removing it.

**Comment by jleandroperez** [comment]
Verified to be working smoothly. Specific steps:

```
1. Launched Aztec
2. Tapped the top right icon (...), and opened the Options Interface
3. Updated Visibility to Password Protected
4. Established a password (in the new field that showed up)
5. Uploaded the post
6. Verified that the post indeed, showed up as Password Protected for dotcom users
7. Reopened the post, and removed the password via Options
8. Verified that the post became immediately visible to dotcom users
```

Note that, due to webserver caching, once step 7 is complete, it may take a couple minutes before the post is *publicly* visible (that is, to non WordPress.com users).

Thanks sir!!

**Comment by jleandroperez** [comment]
+ Verified to be working on my self hosted site as well.
