### ISSUE TITLE
Aztec: Remove the wonk from dismissal of editor window.

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#6637]
The post-post window is getting dismissed improperly. Remove the wonk and reduce the bork.

Also check functionality for switching to the post list view if appropriate - it may be handled already.

**Comment by jleandroperez** [comment]
Closing this one since there's no longer any weirdness between Post Post and Aztec.

I'm filing #6682 to address Aztec's <> Post Post Keyboard weirdness.
