### ISSUE TITLE
Improve activity logs

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#6641]
Over time, we've accumulated a lot of debugging info in the logs, that's rarely relevant when it comes to helping users. A good example of this was #6599 

Some things I'd like to see:

- Remove any logging that's not helpful anymore.
- Log every relevant navigation change. This might be better achieved by just logging whatever WPAnalytics tracks.
- Avoid line breaks (when dumping dictionaries or core data objects) so logs can be processed

**Comment by astralbodies** [comment]
We could always treat the lowest level of logging as stuff that doesn't even show up in the text file. That way we don't *have* to remove anything immediately but make sure anything important is at the right level.

**Comment by koke** [comment]
I was going to agree and switch stuff from info to debug, but then I think all that info is probably just noise as well for developers, unless you are working on that specific thing.

One thing I've experimented with, and I like, is having command line debug flags, as the one for PingHub in #6357. If you are working on PingHub you get all the verbose state changes, otherwise you can develop without a million entries in the console.
