### ISSUE TITLE
Sharing: share title to Twitter

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#6661]
Currently when sharing a post to twitter, the title isn't included, just the URL. Ideally the title would be pre-filled (and possibly an image included, see #6660).

![img_6915](https://cloud.githubusercontent.com/assets/517257/22894465/ae567e00-f1de-11e6-8344-bf398bb3720c.PNG)

**Comment by kean** [comment]
RIP
