### ISSUE TITLE
Notifications: adjust alignment of up/down navigation icons

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#6662]
In #6581 up/down arrows were added to notification detail screens for the purpose of fast-switching between notifications.

In the current implementation the icons are spaced pretty far apart. I've checked how iOS Mail treats its back/forward arrows when viewing a message detail, and I've adopted their spacing here.

Mockup:

![group 2](https://cloud.githubusercontent.com/assets/1396552/22899467/ed93998a-f1f8-11e6-8471-10f4b0c32074.png)

- On top is the current implementation
- Second is my proposed change
- Third shows the icon boundaries (24px square) and the recommended spacing between icons (12px).
- The space between icons shouldn't be tappable, so users are less likely to accidentally tap the wrong one.

@koke if you have a chance could you take a look here and see if you need anything else from me to make this change?

**Comment by mattmiklic** [comment]
One more change not in the mockup: Can we swap the order, so up is first? My reasoning here is that down goes forward, up goes back. So right now they're the exact opposite of the order of the icons in Mail. Users used to those would be confused by the current order.

Also, since users are likely to see the first in a list but unlikely to see the last notification (unless they're a new user), this makes it more likely that the disabled button won't be the one on the outside, which is the easiest to tap.

**Comment by koke** [comment]
> Can we swap the order, so up is first? My reasoning here is that down goes forward, up goes back. So right now they're the exact opposite of the order of the icons in Mail. Users used to those would be confused by the current order.

🤔 I see the opposite. For me in Mail, left (down) is older, right (up) is newer. If I open my newest email:

![screen shot 2017-02-14 at 09 30 00](https://cloud.githubusercontent.com/assets/8739/22921024/3f09ad6e-f298-11e6-8c11-3dd09d7095fb.png)

Calypso has down on the right though, so that'd be a good reason to change it as well.

**Comment by mattmiklic** [comment]
Oh, good catch. Maybe that's a sign that we picked the better direction with up/down, because Mail's arrows work exactly the opposite of the way I'd expect them to.

> Calypso has down on the right though, so that'd be a good reason to change it as well.

Sounds like a plan. 👍

**Comment by frosty** [comment]
One other good reason to change this: Mail in iOS 10.3 (currently in beta) appears to have changed the left / right arrows to up / down, and they have up on the left:

![fullsizerender 4](https://cloud.githubusercontent.com/assets/4780/23063872/bf0e06cc-f504-11e6-9a1b-cdc77b394d20.jpg)

**Comment by mattmiklic** [comment]
> One other good reason to change this: 

Nice! Also, wow, it took them a while to make that change.

**Comment by elibud** [comment]
Hey @mattmiklic it looks like all the changes you requested were already taken care of. Can you confirm? Thanks
![simulator screen shot sep 5 2017 14 53 24](https://user-images.githubusercontent.com/5558824/30075129-44637964-924a-11e7-9b01-7e9a01d5316e.png)

**Comment by mattmiklic** [comment]
Yup, that looks good now. 👍

**Comment by elibud** [comment]
Someone must have taken care of it :)
