### ISSUE TITLE
Notifications: pasting an image URL into a comment

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#6672]
When commenting on a post, or in reply to a comment, if a user adds a URL to an image of some sort, the image is displayed along with the comment on the web.

However, for the user who receives the notification of the comment and views it within the app, particularly the `NotificationDetailsViewController`, neither the image URL text or the image are displayed in the comment's body.

### Steps to reproduce the behavior
1. Log into an account with Notifications.
2. On the web, comment as another user on a post for the user logged in to receive notifications.
3. In the comment, include some text and also a URL for an image on the web.
4. Notice the comment on the web shows the image, sans the URL text.
5. Open the comment notification in the app, notice only the text of the post is visible, no image and no URL text.

cc @jleandroperez

**Comment by jleandroperez** [comment]
It's either a rendering issue (Notification.Range processing glitch), or the backend is not properly encoding the link in the Notifications data format. Nice catch @kurzee!!

cc @koke

**Comment by aerych** [comment]
Tested this by pasting a url into a comment, then checking the notification I received.  The image was rendered as expected. 
Closing. :)
