### ISSUE TITLE
Reader: Fix spacing on Polldaddy embeds

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#6685]
As reported by a user. Currently in the reader, Polldaddy embeds are transformed into links because of inline JS:

<img width="225" alt="napkin 38 02-15-17 2 49 54 pm" src="https://cloud.githubusercontent.com/assets/154014/22994910/43834b42-f38e-11e6-8ffc-8fb7d503c590.png">

It would be nice to clean up the spacing around these links (e.g. a bit of regex during the content ingestion).

**Comment by koke** [comment]
We should fix this on the API side, as it's not specific to the app. Here's calypso for the same post:

<img width="742" alt="screen shot 2017-03-23 at 09 55 32" src="https://cloud.githubusercontent.com/assets/8739/24239623/f0c8b9ea-0fae-11e7-9371-15bc46d34c8a.png">

I mentioned it to Donncha and he was going to look into the shortcode output.
