### ISSUE TITLE
Standardize the toolbar with Android.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#6688]
- [ ] Review Action(s) order
- [ ] Ship Page Gridicon
- [x] Support More Action
- [ ] Support Page Action

**Comment by jleandroperez** [comment]
Thanks for patching this one @diegoreymendez!!

:shipit:

**Comment by jleandroperez** [comment]
**Update:**

- [ ] Once merged, let's integrate the [latest Aztec's Format Bar](https://github.com/wordpress-mobile/WordPress-Aztec-iOS/pull/354).
- [ ] Review the color scheme to be used.
- [ ] Make sure to wire the Peek Animation
- [ ] Review the Actions that must be added (Page / More)

**Comment by diegoreymendez** [comment]
Any PRs merged for this issue @jleandroperez ?

**Comment by diegoreymendez** [comment]
@jleandroperez - I believe this one may be closed already.  Can you confirm?

**Comment by diegoreymendez** [comment]
This issue is no longer necessary as @iamthomasbishop is designing and @frosty is implementing the [new format bar for iOS](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/501).
