### ISSUE TITLE
Reader Detail: layout not updating after restoring from portrait to landscape

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#6702]
As seen in https://github.com/wordpress-mobile/WordPress-iOS/pull/6681#issuecomment-280249528, the split-view makes this more prominent.

After the split-view gets merged in, we would need a patch to fix whatever layout or update is caused in that particular scenario, for `ReaderDetailViewController`.

1. Open Notifications tab in portrait orientation.
2. Select a notification that will lead to a user's site, such as a comment.
3. Select the header or user cell to load that user's site.
4. The posts should load, select a post to load the Reader detail.
5. Background the app to preserve state, kill the app.
6. Rotate the device or simulator to landscape.
7. Relaunch the app.
8. If the state restores the reader detail post, notice the narrow content that restored as if it was in portrait orientation.

![simulator screen shot feb 16 2017 12 55 13 am](https://cloud.githubusercontent.com/assets/1873422/23011021/1e33f0e8-f3e4-11e6-8a6b-dea23c13a7f5.png)

cc @aerych

**Comment by hoverduck** [comment]
Related, but I'm not sure if it could use a standalone issue - here's a video provided by a user showing them read a post in portrait orientation and scroll down several paragraphs, then rotate to landscape and it retains their position in the post.  But when they rotate back to portrait they're returned to the top of the post.

https://cloudup.com/cyvOpiJqJDw

I was unable to reproduce with my iPad or iOS simulator on the latest build, but wanted to make sure it was noted somewhere.  Originally reported on iPhone 7 iOS 10.2.1

**Comment by kurzee** [comment]
>... But when they rotate back to portrait they're returned to the top of the post.

@aerych looks like another form of https://github.com/wordpress-mobile/WordPress-iOS/issues/6288

**Comment by leandroalonso** [comment]
Doesn't seem to be happening anymore after the recent changes on Reader Detail.
