### ISSUE TITLE
Preview: Tapping "Done" freezes the app

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6705]
### Expected behavior

I expect to tap "Done" in a post preview to close the preview and return to what I was doing before.

### Actual behavior

Tapping "Done" in a post preview (from within the editor) closes the preview, and I am returned to an unresponsive post list where the app is completely frozen. I have to force-close the app, which loses any unsaved drafts/changes.

This happens in both the beta and the production version of the app, so it isn't related to Aztec.

I also noticed that if I tap "Preview" from the posts list, the preview doesn't have a "Done" option — it only has a back option. The preview from within the editor has both. The view from the post-post screen only has the "Done" option. @nheagy could the "Done" that appears when you preview from within the editor be an unintentional addition from post-post that isn't supposed to appear on regular post previews?

### Steps to reproduce the behavior

1. Open the posts list on a site.
2. Tap "Edit" or tap the post card to open a post in the editor.
3. Tap the "..." menu in the top right and preview the post.
4. Tap "Done" in the top right to close the post preview.

Result: The preview closes and I am back on the posts list with an unresponsive app.

##### Tested on iPhone 6, iOS 10.2.1, WPiOS 7.0.0.20170214 and 6.9 (app store version)

**Comment by diegoreymendez** [comment]
Ping @jleandroperez to follow up on this blocking issue.  Thanks!
