### ISSUE TITLE
Publish button is disabled after interacting with "Tap for options" while media is uploading

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6707]
If you tap on the "Tap for options" overlay while an image is still uploading, the Publish button stays disabled even after the image finishes uploading.

### Steps to reproduce the behavior

In the Aztec editor:

1. Start uploading an image.
1. Tap on the image while it is still uploading.
1. Tap again to bring up the action menu (still uploading).
1. Dismiss the action menu, or open the image details and then close them.
1. Wait for the image to finish uploading.

Result: The overlay disappears but the Publish button stays inactive.

I tried switching to HTML view, opening the post options, and previewing the post, but the Publish button never activated. I had to make a change to the post title or content to get the publish button to activate so I could publish the post.

##### Tested on iPhone 6, iOS 10.2.1, WPiOS 7.0.0.20170214

cc @SergioEstevao

**Comment by astralbodies** [comment]
@rachelmcr Do you mind re-testing this? I can't seem to reproduce it and it may have been resolved.

**Comment by rachelmcr** [comment]
Thanks for the nudge! I re-tested in 7.1.0.20170301 and it's resolved there. Closing.
