### ISSUE TITLE
Reader: Prioritize first image when choosing image to feature

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6714]
For posts that do not specify a featured image, update the way a featurable image is selected from the content.   Ignore the attachments dictionary and the `featured_media` field and only consdier the images included in the post content.  
Choose the first image in the post content that is an acceptable size.

**Comment by elibud** [comment]
@aerych just to double check, we don't want to search for an image on the `featured_media` field or the `attachments`  even if we didn't find an image on the `post_contents`?

**Comment by aerych** [comment]
> we don't want to search for an image on the featured_media field or the attachments even if we didn't find an image on the post_contents

Correct.  We want to completely ignore the `featured_media` and `attachments` fields, and just look at what's identified in `featured_image`, or if empty, what's present in the post's content.

**Comment by aerych** [comment]
> we don't want to search for an image on the featured_media field or the attachments even if we didn't find an image on the post_contents

Correct.  We want to completely ignore the `featured_media` and `attachments` fields, and just look at what's identified in `featured_image`, or if empty, what's present in the post's content.
