### ISSUE TITLE
Crash trying to view post via a "like" notification after the post is deleted.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#6739]
To reproduce:

On the web:
- Create a new post with one account.
- Like that post from another account so that the first account receives a like notification. 
- Delete the post.

In the app: 
- View Notifications
- View the like notification. 
- Tap to view the post for the like notification. 
- Shed tears of frustration as the app crashes in response to your folly.

The REST API is calling the `/v1.2/read/sites/%d/posts/%d/?meta=site` end point.  The endpoint is returning an HTTP 200 status code so the failure condition is not being met, but the body of the response is:
```
{
    error = 404;
    message = "Post not found";
}
```

I'm not sure if this is a recent change to the API or if this behavior has always been there.  Either way we'll need to patch it.  Maybe not critical as this is a bit of an edge case.

**Comment by bummytime** [comment]
Retested this issue and it no longer crashes, therefore I'll close it for now. The endpoint is now returning an HTTP 404 (as it should) with the following body:

`{"error":"unknown_post","message":"Unknown post"}`

And the app handles it as expected:

![screen shot 2017-07-26 at 4 58 37 pm](https://user-images.githubusercontent.com/154014/28645865-a4efc36e-7224-11e7-8028-ac62705355a1.png)
