### ISSUE TITLE
Add an automated transfer tag to Helpshift metadata

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-iOS#6742]
To help troubleshoot some problems.

Equivalent wpandroid patch: https://github.com/wordpress-mobile/WordPress-Android/pull/5243

**Comment by ScoutHarris** [comment]
During the Zendesk implementation, we discussed and implemented HE desired tags. I'm closing this. If the HEs need additional tags, we can open ZD related tickets.
