### ISSUE TITLE
Likes are no longer working.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#6744]
### Expected behavior

Liking a post from the list of notifications should work.

### Actual behavior

It looks like it works, but if you go to that post using your browser you'll find it didnt' really work.  Another way to see it fail is by closing the app and reopening it.  You'll notice the like is gone.

### Steps to reproduce the behavior

Launch the app.  Go to your list of notifications.  Like a post.

/cc @jleandroperez since you're the notifications VC expert.
/cc @rachelmcr to keep you posted.

**Comment by jleandroperez** [comment]
cc @koke (Will definitely have more bandwith to address this next week!)

**Comment by jleandroperez** [comment]
Tested Liking / Unliking both, Posts and Comments, accessed via the Notifications List.

Cannot reproduce the issue on my end. @diegoreymendez can you confirm please if this is still an issue?

Thanks!

**Comment by diegoreymendez** [comment]
@jleandroperez - Still reproduceable here.

I've tried with both an old internal release and the latest code from develop.  Here's [a video showing the problem](https://cloudup.com/c9W3n2eIhHA).

If you need me to help you with testing, contact me via DM and I'll assist.

**Comment by astralbodies** [comment]
@diegoreymendez @jleandroperez Did this get resolved?

**Comment by jleandroperez** [comment]
@astralbodies nope, sorry, i've been unable to get to this one (yet)!!

As far as i can tell, from what i've tested, likes are working fine (at least on my end). Diego sent me a video with the issue, in which he:

- Unlikes a comment notification
- Kills wpios
- Relaunches the app
- Reopens the unliked notification

And, as a result, the "Unlike" OP is not reflected in the Notification onscreen. Sounds like the entity is either not properly getting updated, or we've got a timming issue.

cc @koke

**Comment by diegoreymendez** [comment]
Since it's so easy for me to reproduce locally @jleandroperez, let me know if you want to do a video session to help you debug this thing.  It sounds obscure enough that it may make sense to try it out.
