### ISSUE TITLE
Reader: Unfollowed sites on Web are not disappearing in the Manage screen

### ISSUE THREAD

**Issue by codestor4** [wordpress-mobile/WordPress-iOS#6752]
### Expected behavior

If I unfollow a site on web, it is removed from my following > manage screen. And when I go to my iOS app Reader > Followed sites > Manage, the unfollowed site should be removed from this screen as well.

### Actual behavior

If I unfollow a site on web, it is removed from my following > manage screen. 

But when I visit iOS app Reader > Followed sites > Manage, I still see the unfollowed site.

### Steps to reproduce the behavior

Go to https://wordpress.com/following/edit

while that is open on your desktop, go to iOS app Reader > Followed sites > Manage

Check if both lists match. If yes, do the following -

Unfollow a site on the web. Refresh the page and you'll notice the site is removed.

Refresh iOS app, you will see the site still exists here.

##### Tested on [device], iOS [version], WPiOS [version]

Tested this on my iPhone 6
iOS version 10.2.1
WPiOS version 6.9

This has been reported by the user. 
I've tested and found the same. 
This has also been tested by Elisa Budelli.

**Comment by rachelmcr** [comment]
We have another report of this issue from support. (Internal ref: 188939-h)
