### ISSUE TITLE
Feature Request: Support custom taxonomies

### ISSUE THREAD

**Issue by dartiss** [wordpress-mobile/WordPress-iOS#6753]
A VIP client has noticed that our desktop app supports their custom taxonomies but the mobile (certainly iOS, anyway) doesn't.

Is this something that could be considered as a feature?

Ticket is #62793-z

**Comment by rachelmcr** [comment]
This came up again in an app review for version 9.8:

> Cannot manage custom taxonomies on posts.

**Comment by rachelmcr** [comment]
I'm going to go ahead and fold this in to https://github.com/wordpress-mobile/WordPress-iOS/issues/500, which covers custom post types and fields. The team will likely consider all of these holistically for planning.
