### ISSUE TITLE
Missing "Save Draft" option when exiting the editor

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#6760]
This was originally reported by @rachelmcr [here](https://github.com/wordpress-mobile/WordPress-Aztec-iOS/issues/295).  I moved it here for organizational purposes.

### Expected behavior

In the visual editor, there is an option to save your new post as a draft when you exit the editor (in the action sheet that comes up when you tap the "x" in the top left):

![2017-02-17 10 22 27](https://cloud.githubusercontent.com/assets/8658164/23074205/0a1da728-f530-11e6-8d2c-c1877486a941.png)

### Actual behavior

In Aztec, there is only the option to discard or continue editing, no option to save the draft:

![2017-02-17 10 22 44](https://cloud.githubusercontent.com/assets/8658164/23074209/0db2669e-f530-11e6-995d-2fbc669754e0.png)

Tested on iPhone 6, iOS 10.2.1, WPiOS 7.0.0.20170214

**Comment by astralbodies** [comment]
Closing as it looks like it was resolved.
