### ISSUE TITLE
Page Options: Location setting silently fails

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6763]
### Expected behavior
To be able to set the location attribute of a page (as opposed to a post)

### Actual behavior
The location selector opens, but then doesn't retain the setting once I tap Done

### Steps to reproduce the behavior
1) Create a new page
2) Open the Options panel
3) Tap Set Location
4) Choose a location via search
5) Tap Done

When editing a Post, at this point the map of the chosen location appears in the Options panel.  But when editing a Page it just silently closes, and re-opening Set Location shows the same default it did before.

If you set the location via Calypso web, then open the page in the app the location still doesn't show up.

**Comment by koke** [comment]
I'm not seeing the Location section in page options and can't find any recent changes about that. Can you confirm if it appears for you? Tested on 7.1 and develop

**Comment by hoverduck** [comment]
Yes, it still shows up for me, but only when using Aztec.  Do you have that turned on?

**Comment by koke** [comment]
Oh gotcha, it seems Aztec is just showing the post options screen for pages, so this should be an easy fix \o/

**Comment by koke** [comment]
Fixed in #6888
