### ISSUE TITLE
Page Options: Unable to update Excerpt

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6764]
### Expected behavior
To be able to supply an excerpt of my page content

### Actual behavior
I can set the excerpt, and it appears to work, but on reloading the Options panel it's no longer there

### Steps to reproduce the behavior
1) Create a new page
2) Open the Options panel
3) Set an excerpt
4) Exit out of Options
5) Re-open options and try to view your excerpt - it's empty

If you set the excerpt via Calypso web first it does appear in the app, but updates fail to save

##### Tested on iPad Air 2, iOS 10.2.1, WPiOS 7.0.0.20170223

**Comment by michaelnordmeyer** [comment]
I can't replicate this behavior using the released 7.0 version, but I'm running 10.3 public beta 3.

I also added excerpts to existing drafts without any problems. I used WordPress for iOS and my self-hosted WordPress 4.7.2 without Jetpack to verify the persistence of the excerpts.

**Comment by michaelnordmeyer** [comment]
Oops, sorry. I used the post editor. The page editor doesn't have an excerpt field in options. Again, 7.0 App Store version, but since today on 10.3 public beta 4.

**Comment by hoverduck** [comment]
Ah!  It's apparently only available when using the new native Aztec editor, enabled in the App Settings page.  I'll add that label now.
