### ISSUE TITLE
Switching sites from Page Editor incorrectly publishes Posts

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#6765]
First reported by @hoverduck [here](https://github.com/wordpress-mobile/WordPress-Aztec-iOS/issues/323).

1) Create a new Page (not post)
2) Use the site selector at the top of the editor to change sites

Note that now the button at the upper right says "Post" instead of "Publish".  Clicking that will publish the content as a Post on the selected site instead of a Page.

I was unable to reproduce this on the legacy editor, so I'm assuming it's an Aztec initial state issue

##### Tested on iPad Air 2, iOS 10.2.1, WPiOS 7.0.0.20170223

**Comment by jleandroperez** [comment]
Cannot repro in Develop!! @astralbodies can you confirm if you've already addressed this one?

Thanks!!

**Comment by astralbodies** [comment]
If it's saying Post that's the hybrid editor coming up... Hmmmm. I have not fixed this so it may have been a symptom of something else happening?

**Comment by jleandroperez** [comment]
**Update:** the Navbar's label, in develop, reads correctly. However, pressing it effectively uploads a `Post` instead of a `Page`. Addressed in #6821.

Thanks everyone!
