### ISSUE TITLE
A scheduled post still shows up in scheduled posts after it's published

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-iOS#6784]
### Expected behavior

A previously scheduled post does not show up in "scheduled list" after it's published.

### Actual behavior

A previously scheduled post shows up in "scheduled list" even after it's published.

![image](https://cloud.githubusercontent.com/assets/1522856/23403692/870f68be-fdb1-11e6-98d0-7d35ff7c24cc.png)

### Steps to reproduce the behavior

Open up scheduled posts after the post has been published, have to pull down to refresh to see it update.

**Comment by catehstn** [comment]
Other way around: scheduled post shows up in "scheduled" after it is published. I think the main issue is that the posts list doesn't refresh on load.

**Comment by 0nko** [comment]
Updated, thanks :).

**Comment by Linzarnishwe6** [comment]
I've added you to my whitelist on BitBounce!
[image: BitBounce]



Hello!

I’ve signed up for a cryptocurrency spam solution called BitBounce and I
added you to my “whitelist”. That means you can email me and your emails
will come through.

For people who aren’t on my whilelist, I’m charging $0.05 in Credo for
their email to get to my inbox. A cleaner inbox and more money? Win! You
should check it out!

*Sign up for BitBounce and earn 1 complimentary Credo.*
<https://bitbounce.com?ref=bitbounce>

Unsubscribe
<https://bitbounce.com/unsubscribe_from_whitelist_email_notifications/1199177803>
from Linzarni Shwe's whitelist notification emails.



*BitBounce* <https://bitbounce.com?ref=bitbounce> is powered by the *Credo*
<https://bitbounce.com/credo> cryptocurrency

*I’m from a business* —  what are my *delivery options*
<https://business.bitbounce.com>

BitBounce and Credo are transacted through *CredoEx*
<https://credoex.com?ref=bitbounce>
Made by Turing Technology Inc. in San Mateo, California *Sign Up for
BitBounce* <https://bitbounce.com?ref=bitbounce>
