### ISSUE TITLE
Australian Flag Missing in Apps Stats

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-iOS#6789]
The Australian flag doesn't show up in the app stats. 

![image](https://cloud.githubusercontent.com/assets/1522856/23450463/9f334f82-fe5b-11e6-9656-f6090acdac97.png)

**Comment by koke** [comment]
We've talked about using Emoji flags instead of loading them from Gravatar, which should be easy since we already have the country code

**Comment by koke** [comment]
A little snippet to turn a country code into the relevant emoji flag:

```swift
func emojiFlag(country: String) -> String {
    let base : UInt32 = 127397
    return country
        .uppercased()
        .unicodeScalars
        .flatMap({
            String(UnicodeScalar(base + $0.value)!)
        })
        .joined()
}
```

**Comment by elibud** [comment]
The Netherlands and Montenegro flags are missing too.
