### ISSUE TITLE
Editor: keyboard shortcuts are unpredictable

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#6793]
A user submitted some feedback:

On the current Hybrid editor:
- Using the iPad undo shortcut does nothing.
- Using the blockquote shortcut can blockquote the entire post.
- Also related https://github.com/wordpress-mobile/WordPress-iOS/issues/6428

**Comment by rachelmcr** [comment]
I tested in Aztec (on iPhone XS, iOS 12.0.1, WPiOS 11.0.0.20181010) and the undo shortcut and blockquote shortcut both work as expected, as do the other shortcuts I tested. Closing as resolved with Aztec.
