### ISSUE TITLE
Site icon disappearing for Jetpack sites

### ISSUE THREAD

**Issue by 0nko** [wordpress-mobile/WordPress-iOS#6802]
No icon appears for the Jetpack sites in the My Sites picker, or when the site is selected. When the site is viewed and the view is closed, the site icon appears. The site icon persists until the app syncs with the site again. It keeps happening event after reinstalling the app.

WordPress.com sites work as expected, with the site icon persisting.

Tested on iPhone 6S Plus, iOS 10.2.1, WPiOS 6.8

**Comment by jeremeylduvall** [comment]
Confirmed this issue as well. I have several Jetpack sites all displaying a site icon on WordPress.com but not in the iOS app.

Tested on iPhone 6, iOS 10.2.1, WPiOS 7.1.0

**Comment by jenhooks** [comment]
Also confirmed. 3087728-t

**Comment by rachelmcr** [comment]
A user reported this issue again in a recent support ticket. Internal ref: 184881-h
