### ISSUE TITLE
Move Crash Reporting for Internal Beta to Crashlytics

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#6814]
I'm considering using Fabric/Crashlytics for the internal beta crash reports rather than using HockeyApp. We can continue to use HockeyApp for deployment. 

Thoughts? @koke @kurzee @aerych

**Comment by kurzee** [comment]
With filtering by version on Fabric working pretty well, I think it'd be great to have it all in one spot 👍

**Comment by aerych** [comment]
I think I would miss our slack integration with hockeyapp for crashes.  Its pretty convenient to skim the back chat for new reports, but no objection as longs as we stay on top of them with fabric.

**Comment by koke** [comment]
Fabric also has a Slack integration (which is disabled right now). I don't have a preference, but I agree that might be best to have a single place to look at crashes.
