### ISSUE TITLE
Publicize: Switch back to default message with empty custom message

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#6815]
### Expected behavior
If you do not enter a custom message in the Publicize field, it uses the title of the post. If I want to use a custom message though, I can type that in. Let's say I type that in and then decide later I would rather use the default. I would expect that if I erased all of my content in the message, it would revert back to the default Publicize message (post title).

### Actual behavior
If you remove all text from the custom message field and then exit the screen, the text reappears as if you didn't delete it.

### Steps to reproduce the behavior
1. Start a new post. Give the post a title like "Test."
2. Go into Options. Under Sharing -> Message, you'll see the post title as the custom message.
3. Open up the message field and type in some different text.
4. Click the back arrow to return to the main Options screen.
5. Go back into the message field and erase all of the text.
6. Click the back arrow to return to the main Options screen again. The custom message will still be there.

If the field is left empty, defaulting back to the title seems like a safe bet versus keeping the deleted text.

**Comment by koke** [comment]
cc @elibud
