### ISSUE TITLE
Sharing to WhatsApp from the app is not working

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#6820]
### Expected behavior
Tapping on the WhatsApp icon successfully triggers a URL share on WhatsApp

### Actual behavior
An error is displayed

### Steps to reproduce the behavior
1 - Go to the Reader
2 - Select a Post that has sharing to WhatsApp enabled (at the bottom of the post, not from the sharing icon on the top right corner that triggers the OS sharing)
3 - Select WhatsApp
4 - An error is displayed: **The URL can't be shown**

**Comment by koke** [comment]
I've seen a few workarounds [here](http://stackoverflow.com/questions/4299403/how-to-handle-app-urls-in-a-uiwebview), but I wonder if it's time to switch to SFSafari​View​Controller
