### ISSUE TITLE
Add link to premium themes selector in Themes section in app

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-iOS#6825]
Currently the apps only offer free themes. We want to let our users know there are premium themes they can obtain in the web.

This is how the Android counterpart looks, mimicking the Plans section. Can we make it the same on iOS? cc @bysl

![screenshot_20170306-160334](https://cloud.githubusercontent.com/assets/6597771/23656097/0981a82e-0317-11e7-85c5-0ed149f77055.png)

**Comment by designsimply** [comment]
@mzorz I checked on this today and cannot see a premium themes link in either platform. Is this still a wanted updated?

## iOS

<img src="https://user-images.githubusercontent.com/1119271/66084703-8689a480-e52c-11e9-92a6-1575c66d6b4f.PNG" width="270" alt="IMG_3125">
<sup>Tested with WPiOS 13.3.0.0 (TestFlight) on iPhone 6S iOS 13.1.2.</sup>

## Android

<img src="https://user-images.githubusercontent.com/1119271/66084736-97d2b100-e52c-11e9-8a96-0fdb9c73fc7c.png" width="270" alt="Screenshot_20191002-141459">
<sup>Tested with WPAndroid alpha-190 (13.3 alpha) on Pixel 3 Android 10.</sup>

**Comment by mzorz** [comment]
I think we can safely close this issue - thanks for bringing it up @designsimply!
