### ISSUE TITLE
Notifications: App review request is too persistent (especially for beta testers)

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6826]
At least for beta testers, the prompt on the Notifications tab to review the app ("What do you think about WordPress?") is too persistent/naggy.

I'm not sure exactly what actions trigger the prompt, but it would be good to decrease the frequency for beta testers in particular. For example, if a new app version triggers the prompt, could we limit that to each major release so it doesn't reappear every time there's a new beta release between major versions?

(Issue raised by @m.)

### Screenshot

![2017-03-07 13 14 24](https://cloud.githubusercontent.com/assets/8658164/23658137/3b3aeb24-0339-11e7-91ad-cf4a8aed2053.png)

**Comment by koke** [comment]
Maybe we should just disable it completely on internal/beta builds.
