### ISSUE TITLE
Notifications: Implement soft-ask for permissions

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6828]
### Expected behavior
To be able to configure the app to send the user notifications at any time

### Actual behavior
The prompt is only given once, and if denied, we can never ask again.  Implementing a soft-ask ahead of time will allow the user to change their mind later.

**Comment by astralbodies** [comment]
Helpshift also needs permission to send push notifications (it's borrowing our certificate to send them). So also make the soft ask relevant if they ask for support and push needs to be enabled.

**Comment by ScoutHarris** [comment]
Prime For Push! Done!
