### ISSUE TITLE
New site icons not appearing for WordPress.com sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6844]
### Expected behavior

I expect a site icon that I add to a WordPress.com site in the settings at https://wordpress.com/settings/general or in the site's customizer to appear in the app dashboard next to the site title/address.

### Actual behavior

If I add a site icon to a WordPress.com site with one of the methods above, the site icon placeholder is never replaced with the new site icon. (This is an issue even after the site icon has been in place for weeks, not just new site icons.)

![2017-03-08 17 48 52](https://cloud.githubusercontent.com/assets/8658164/23716310/a9ea5066-0427-11e7-9b93-3279e8fad0ed.png)

However, WordPress.com sites that have a blavatar that was uploaded in the WP Admin dashboard (before that option was replaced with a link to the customizer) do display a site icon.

This is possibly related to https://github.com/wordpress-mobile/WordPress-iOS/issues/6802, but unlike in that issue, in this case the site icon never appears (even after tapping View Site in the app).

### Steps to reproduce the behavior

1. In a web browser, add a site icon to a WordPress.com site (in the general settings or in the customizer).
2. Open the My Sites tab in the app and select that site.

Result: The site icon never appears.

**Comment by koke** [comment]
Quick update: it seems like fixing wp.com site icons would be easy but while testing this I noticed that site icons for private sites and self-hosted won't work that easily, so I'm looking into that.
