### ISSUE TITLE
MediaLibrary: crash supporting all types of media

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#6852]
Didn't find this one in https://github.com/wordpress-mobile/WordPress-iOS/pull/6842

When selecting an item in my video library that's not a image/video, such as a PDF, a crash occurs in `MediaItemViewController`:

<img width="1292" alt="screen shot 2017-03-09 at 2 03 44 pm" src="https://cloud.githubusercontent.com/assets/1873422/23768732/931e1d62-04d2-11e7-845d-341abe5cd8f2.png">

Also of interest, we only show images and videos when viewing the media collection from the Editor. Perhaps in the future we could support all types as on the web.

cc @frosty

**Comment by frosty** [comment]
Didn't mean to close this, Safari jumped down the page as I went to tap in the comment field!

Thanks for catching this one, I didn't think non-images or videos should be showing up, so I'll check. I definitely think we should support other file types (Android does to some extent), but figured that could be for a future phase.
