### ISSUE TITLE
WPVideo embeds don't show up in posts list

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6864]
### Expected behavior
To see a thumbnail of the video clip from my post

### Actual behavior
The embed is completely absent from the excerpt shown on the post card

### Steps to reproduce the behavior
1) Create a new post with a wpvideo embed, publish
2) Look at the post in the Posts List

![image](https://cloud.githubusercontent.com/assets/7233112/23862313/0fc819b8-07e3-11e7-88a0-482341da0cb5.png)

Note that nothing at all is displayed, whereas Android at least shows a `[wpvideo]` placeholder (https://github.com/wordpress-mobile/WordPress-Android/issues/5370)

**Comment by designsimply** [comment]
Tested and confirmed that videos added in the block editor still don't show in cards for posts in the Post List expanded view. 

<img src="https://user-images.githubusercontent.com/1119271/66085163-b5ece100-e52d-11e9-9b6a-b2095ce0ae0f.PNG" width="200" alt="IMG_3129"> <img src="https://user-images.githubusercontent.com/1119271/66085161-b5ece100-e52d-11e9-800a-83f9c86e81dd.PNG" width="200" alt="IMG_3127"> <img src="https://user-images.githubusercontent.com/1119271/66085162-b5ece100-e52d-11e9-85a2-0567d21701eb.PNG" width="200" alt="IMG_3128"> 
<sup>Tested with WPiOS 13.3.0.0 (TestFlight) on iPhone 6S iOS 13.1.2 on a Jetpack site using the block editor to add a video in a block.</sup>

@oguzkocer or @malinajirka I noticed that Calypso doesn't show a poster image or video thumbnail for posts with videos in the Post List either. Is this something we'd like to add to the app?

<img width="1280" alt="Screen Shot 2019-10-02 at Oct 2 4 08 13 PM" src="https://user-images.githubusercontent.com/1119271/66085717-40821000-e52f-11e9-8ffe-4eadf22f3a90.png">

**Comment by malinajirka** [comment]
>@malinajirka I noticed that Calypso doesn't show a poster image or video thumbnail for posts with videos in the Post List either. Is this something we'd like to add to the app?

I'm not sure about iOS, but it might be a bit tricky on Android. It might have a performance impact even if we started manually caching the thumbnails. Imo a good solution would be to start sending the thumbnail url from the server - but that wouldn't work on self-hosted sites. Moreover it probably wouldn't be worth the effort.

**Comment by oguzkocer** [comment]
@designsimply I unfortunately don't know the design or implementation implications for this. I am happy to look into it, but I just don't have an immediate answer. Let me know if you want me to do that.

**Comment by designsimply** [comment]
Closing for now as there haven't been any user reports recorded here. Happy to re-open and re-assess if it comes up again in the future.
