### ISSUE TITLE
Post Editing: Hide keyboard via swiping down

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6865]
It would be nice to be able to hide the keyboard by swiping down, like in iMessages, so I have more screen space for the post itself.  In particular this would make editing a post with a picture/video easier, as it gives you more space to insert the cursor following the media.

**Comment by frosty** [comment]
I'm going to close this issue because this is now possible in Aztec. There is however currently an open issue where the app freezes up when hiding the keyboard in this way: https://github.com/wordpress-mobile/WordPress-iOS/issues/8715
