### ISSUE TITLE
UX: Present a unified error state when WP.com auth is bad

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#687]
If WP.com authentication is bad (i.e. OAuth2 token is missing or is invalid) present a persistent error message in the various places that will fail.
- Reader
- Notification settings
- Individual blogs
- App Settings (when a WP.com site exists and no valid WP.com sign in)

At the moment we present a login box for WP.com when the Blog screen tries loading and it fails.  We do not present a login box anywhere else like in the areas listed above.  If the user chooses to tap cancel, the persistent error display should indicate the section they're in doesn't work without a valid WP.com login.

**Comment by SergioEstevao** [comment]
@koke @astralbodies is this sorted out already? Or still pending?

**Comment by koke** [comment]
Pending. Just yesterday I saw the reader silently failing to get Freshly Pressed stuff after I revoked the app connection
