### ISSUE TITLE
Tags/Categories: Add support for category/tag management

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6873]
Currently, the only way to manage categories and tags in the app is to add or remove them from individual posts in the post options (in the editor). Users regularly request a way to manage (edit/delete) categories and tags outside of the editor.

Calypso currently has category/tag management in the site's General Settings: https://wordpress.com/settings/writing

<img width="736" alt="screen shot 2017-03-14 at 10 09 15 am" src="https://cloud.githubusercontent.com/assets/8658164/23895685/82cac102-089e-11e7-9851-2e1594cceac3.png">

You can add a new category/tag, and edit, delete, set as default, and view posts using each category or tag:

![screen shot 2017-03-14 at 10 13 35 am](https://cloud.githubusercontent.com/assets/8658164/23895827/16d0bb40-089f-11e7-8f6a-3e76ce9db280.png)

It would be nice to have similar category/tag management in the app.

##### Tested on iPhone 6, iOS 10.2.1, WPiOS 7.2.0.20170313.

**Comment by rachelmcr** [comment]
Example app review from a user requesting this feature:

>The interface is pretty good, but the only way to edit categories/tags is to open up a post and do so from within that interface. It's not intuitive if you just want to jam away on adding/editing a bunch of categories/tags.
>I want a stand-alone category/tags interface similar to the one seen in the admin panel as if I was accessing it from my browser. If the app had a categories/tags interface I would give this app 4 or 5 stars.

**Comment by kurzee** [comment]
Related: https://github.com/wordpress-mobile/WordPress-iOS/pull/6862

**Comment by rachelmcr** [comment]
This came up again in user feedback (Internal ref: AppbotX 28306):

>There is no way i can change and rename my cathegories.

**Comment by sarahblackstock** [comment]
App review requesting more category management options: 

>when you make subcategories there is no way to delete them?? or change or edit any categories.

**Comment by elibud** [comment]
This has been implemented by @ctarda and is shipping on version 9.2.
