### ISSUE TITLE
Notifications: Comment notifications no longer shown if the user replied

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6885]
### Expected behavior

I expect comment notifications to include an arrow on the notification in the notifications list if I have already replied to the comment:

![2017-03-16 10 34 11](https://cloud.githubusercontent.com/assets/8658164/23992326/5dd56e8c-0a34-11e7-8336-be0dccd52a94.png)

And the notification detail should include text saying that I replied:

![2017-03-16 10 21 43](https://cloud.githubusercontent.com/assets/8658164/23992201/f4b5fb92-0a33-11e7-825d-1998589fba0e.png)

### Actual behavior

I can still see that on older notifications in my notifications list, but if I reply to a comment now on the notifications tab it doesn't add the arrow or text telling me that I replied:

![2017-03-16 10 37 00](https://cloud.githubusercontent.com/assets/8658164/23992484/0a8afe6c-0a35-11e7-9e6f-0afb1f03153f.png)

![2017-03-16 10 33 48](https://cloud.githubusercontent.com/assets/8658164/23992299/48e0f230-0a34-11e7-827b-ae3d88bd5461.png)

### Steps to reproduce the behavior

1. Open the Notifications tab.
2. Find a comment notification.
3. Open the notification detail and reply to the comment.
4. Note that there is a "Reply Sent!" message.
5. Check the notification list and the notification detail for the arrow/text noting that you replied to the comment. They don't appear.

**Comment by koke** [comment]
This might be fixed by #6871, I'll test while reviewing that one

**Comment by koke** [comment]
Will be fixed when merging #6871
