### ISSUE TITLE
Posts List: The "No posts" message briefly displayed before loading posts

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6906]
### Steps to reproduce the behavior
1) Create a new WordPress.com site
2) Navigate to the Posts List
3) Observe the "No posts yet" message briefly appear before "Fetching posts" and finally the default "First post"

By comparison, Android goes directly to the "Fetching posts" message.

**Comment by koke** [comment]
To clarify on this, I think we should never present a "You have no X" until we have successfully asked the API and got to results. Otherwise this could lead to a "OMG, where are my posts" panic moment.

This can also happen (IIRC) the first time you visit any site after log in, or when offline.

**Comment by koke** [comment]
Related #1148
