### ISSUE TITLE
Improve Helpshift tags to identify more paid upgrades

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6909]
We currently tag Helpshift issues with the WordPress.com/Jetpack plan on each site the user has in the app (https://github.com/wordpress-mobile/WordPress-iOS/pull/6061). We use those tags to identify users with paid upgrades for priority support. However, this excludes users with paid upgrades but no plans, e.g. custom domains.

We should identify WordPress.com accounts/sites with any paid upgrade (not just plans) and add a tag to those Helpshift conversations to identify the upgrade.

**Comment by rachelmcr** [comment]
@koke Since you implemented the previous tagging, do you think this is something you could look into? There's also a matching issue for Android: https://github.com/wordpress-mobile/WordPress-Android/issues/5469

**Comment by ScoutHarris** [comment]
During the Zendesk implementation, we discussed and implemented HE desired tags. I'm closing this. If the HEs need additional tags, we can open ZD related tickets.
