### ISSUE TITLE
Media: Add support for RAW image uploads

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#6934]
### Expected behavior
To be able to upload images in RAW format.

### Actual behavior
The upload window closes with no error.

This came from a user report, and they indicate that the Android app is able to upload RAW images without issue.  Although I wasn't able to get a RAW image on my iOS device to reproduce the problem, so I imagine there could be another root cause like file size.

**Comment by astralbodies** [comment]
I don't think WordPress.com supports RAW images nor does WP Core.

**Comment by sarahblackstock** [comment]
If RAW images aren't supported, the user mentioned an error message indicating the problem (file type or size) would be appreciated. I had another similar request for this today as well.
