### ISSUE TITLE
Drop AppBotX in favor of iOS 10.3 SKStoreReviewController.requestReview()

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#6935]
Let's remove the AppBotX component and use the iOS feature to prompt users to provide feedback. We'll need to replicate AppBotX's occasional reminder system we use in notifications. requestReview has it's own throttling according to Apple so I'm not sure what the best approach is. Regardless we want to drop using AppBotX since it's a sunset-ish product.

**Comment by rachelmcr** [comment]
We can also direct critical feedback directly to Helpshift, where we can provide support. If we tag these issues with a unique tag for Helpshift we can set up automations to handle them differently from standard support requests.
