### ISSUE TITLE
Sharing: Can't finish or cancel reconnecting a broken publicize connection

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6959]
### Expected behavior

I expect to be able to reconnect a broken publicize connection (either from My Sites > Sharing or in the editor's post options), as described in https://github.com/wordpress-mobile/WordPress-iOS/pull/6912.

### Actual behavior

I get stuck using either method to reconnect the broken publicize connection, [as reported here](https://make.wordpress.org/mobile/2017/03/28/call-for-testing-wordpress-for-ios-7-3/#comment-19301):

> When I tapped the error symbol to fix the connection, I was prompted to log in and authorize each account. After entering login details, the next screen got stuck—both times—and the X at the top left was unresponsive. I had to close and re-open the app to return to the posts and I lost content (I hadn’t saved the posts I was working on) in both cases.

Screenshots: https://cloudup.com/cvBIZk8BpFU (white screens are the stuck screens)

h/t @designsimply for the report & screenshots!

cc @koke 

##### Tested on iPhone 6, iOS 10.3, WPiOS 7.3.0.20170327

**Comment by koke** [comment]
When I was working on #6912 I recall having trouble with reconnect in general: from the editor, from Sharing, and even from calypso. The next day it was working again, so I assumed there was something broken in the backend that got fixed.

**Comment by rachelmcr** [comment]
We have another report of the app freezing up while reconnecting a broken publicize connection. Once again, a draft was lost because the app was unresponsive and had to be restarted.

Internal ref: p4k3M4-2jq-p2

**Comment by elibud** [comment]
We have an internal report:

WordPress freezes when I try to connect to Facebook.
I clicked on settings, sharing, re-connect to Facebook. I did 2-step verification. The page starts to load, but never finish.

cc: @astralbodies

**Comment by elibud** [comment]
I can't finish the reconnection process on Calypso either, I've reported this to the API team, lets see what we hear back.
