### ISSUE TITLE
Media: asynchronous publishing + media uploads

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#6968]
- [x] Separate the responsibility of MediaService: 
  - [x] API remote requests
  - [x] Creating Media models
  - [x] File system operations
  - [x] PHAsset handling
  - [x] UIImage fetching and resizing
  - [x] Convert to Swift along the way.
- [x] More unit tests.
- [ ] Adopt UIApplication background tasking for media creation and uploading via beginBackgroundTaskWithExpirationHandler so uploads actually continue if you background the app.
- [ ] Maybe use local notifications to notify the user a post finished uploading/posting while backgrounded.
- [ ] Implement NSNotifications for media operations so other view controllers can react to media uploading changes:
  - [ ] Media created.
  - [ ] Media upload started
  - [ ] Media upload progress changed.
  - [ ] Media upload progress ended.
  - [ ] Media upload error.
  - [ ] Media upload completed.
- [ ] Decouple the code ownership between the editor view controllers and media operations. There’s a lot of code duplication between the legacy, visual and aztec view controllers.
- [ ] Maybe some type of datasource handler in between media services and editor view controllers for actually inserting the uploaded media into a post once an editor has been dismissed.
- [ ] New UX for showing upload and posting progress once the editor has been dismissed. Also ability to present errors within this UX and encourage a retry. (status bar)
- [ ] Yay now we’re async. 🎉

**Comment by kurzee** [comment]
https://github.com/wordpress-mobile/WordPress-iOS/pull/6923

**Comment by kurzee** [comment]
MediaService: Cleanup part 2, cacheing, URLs, and tests: https://github.com/wordpress-mobile/WordPress-iOS/pull/6966

**Comment by frosty** [comment]
Going to close this now, as it catered for the initial MediaService updating just fine but we now know a bit more about how we're going to implement the remaining changes, so I'll open separate items for those.
