### ISSUE TITLE
People: Add filter for email followers

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6969]
### Expected behavior

In the People section, I expect to see Users (members of the site), Followers (WordPress.com followers), and Email Followers (non-WordPress.com email subscribers), similar to what appears at https://wordpress.com/people in Calypso.

### Actual behavior

The app only has sections for Users and Followers. Email followers only appear in the Followers module in Stats, not in the People section.

##### Tested on iPhone 6, iOS 10.3, WPiOS 7.3.0.20170327

**Comment by rachelmcr** [comment]
A user recently contacted us in support trying to find their list of followers and was confused about how to find their list of email followers. Internal ref: 184953-h

**Comment by rachelmcr** [comment]
This came up again in app feedback (Internal ref: AppbotX 29225):

>It would be nice to see my email subscribers

**Comment by SiobhyB** [comment]
This came up again in 254370-h as a user is receiving a lot of spam followers, and they're not able to remove them from within the app.

**Comment by oguzkocer** [comment]
Another user requested in 278970-h. This feature is available on Android, so we should be able to easily add this on iOS as well. It might be a good fit for no-dead-ends project. /cc @elibud & @aerych

**Comment by SiobhyB** [comment]
This caused some confusion again in 1279931-z. The user was expecting a lot more followers than they saw in the People section of the app.

**Comment by oguzkocer** [comment]
> The user was expecting a lot more followers than they saw in the People section of the app.

@SiobhyB Previously I had a user who had a plugin for email followers, separately from our own email followers feature. That was why their numbers didn't match up. Is it possible that it might be the case for that user as well?

**Comment by SiobhyB** [comment]
@oguzkocer: That's not the case here, no. It's a WordPress.com site and the number of Email Followers matches up to what they were expecting to see.

**Comment by SiobhyB** [comment]
This caused some confusion again in 1666349-z. The user was missing their email-only followers and wasn't sure how to view them from within the app.

**Comment by thehenrybyrd** [comment]
Some confusion over this in 1924880-z. Explained that the iOS app currently doesn't display email followers.

**Comment by thehenrybyrd** [comment]
Another in 1961950-z.

**Comment by mlaetitia** [comment]
Also reported here: 2061774-h

**Comment by rachelmcr** [comment]
Given the number of reports of confusion over this, I'm removing the low priority label here.

**Comment by tmmbecker** [comment]
2264895-zen

**Comment by thehenrybyrd** [comment]
This came up recently as I was helping someone manage their followers, and had to direct them to a web browser for managing email followers.

**Comment by kspilarski** [comment]
Same case for 2719422-zd. They are using WordPress iOS app (version 14) for the iPad and iPhone, and can only see Team and Followers tab. Email Followers and Invites can only be seen in Calypso.

**Comment by reginabally** [comment]
4310761-zd-woothemes

**Comment by ScoutHarris** [comment]
iOS uses `/sites/$site/follows/` to fetch Followers, which does not provide an option for _email_ followers. Android uses the Stats endpoint to get followers and email followers, `/sites/$site/stats/followers`. To note, that endpoint is also is used in `StatsEmailFollowersInsight` to display email followers in stats. Android does use `/sites/$site/follows/` to fetch the other types as iOS does.

**Comment by wargcm** [comment]
These are the tasks I'm thinking are necessary for this change:

- [x] Add `getEmailFollowers` API call to `PeopleServiceRemote` in WordPressKit 
  - wordpress-mobile/WordPressKit-iOS#477
  - wordpress-mobile/WordPressKit-iOS#480
- [x] Add `loadEmailFollowersPage` to `PeopleService` in WordPress 
  - #17830
  - #17854
- [x] Add email filter UI and service call to `PeopleViewController` in WordPress
  - #17830
  - #17854
