### ISSUE TITLE
Media Picker: Slow to load for large iCloud libraries

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#6971]
We've had reports that the media picker can be extremely slow to load for users with a lot of iCloud photos – in one case, up to 10 seconds for the initial load, and 13 seconds to show the dropdown selector. Also, if an image hasn't yet been fetched from iCloud, it can take a long time to insert into a post (with no visual indication in the post body of anything happening) or in some cases crash completely.

**Comment by SergioEstevao** [comment]
@frosty do you think we can close this one?

**Comment by frosty** [comment]
I think so, it's so much faster for me now. We can always re-open if we get more reports.
