### ISSUE TITLE
Use images to badge notifications icon

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#6972]
We've got a couple of reports of the orange notification dot appearing in the wrong place. Instead of fixing the positioning logic, let's use two different images for the tab bar item.

![2017-04-02-19-04-03](https://cloud.githubusercontent.com/assets/8739/24707046/68715084-1a12-11e7-8a70-daa35fdfb330.png)

![img_1151-copy](https://cloud.githubusercontent.com/assets/8739/24707048/6a9f6f08-1a12-11e7-9555-17f7eb9c784a.png)

**Comment by elibud** [comment]
If we change the current behavior to use an image we'll lose the nice animation we have when you get a new notification while the app is open. I'm going to try to track the bug instead. 
@rachelmcr @hoverduck Do you know where the reports came from? Thx

**Comment by rachelmcr** [comment]
Both reports were internal (I was one of the reporters) using the internal beta. I'll ping you with more details from my end. :)
