### ISSUE TITLE
Reader missing avatars

### ISSUE THREAD

**Issue by fraying** [wordpress-mobile/WordPress-iOS#6980]
Avatars (gravatars and blavatars) are missing from Reader in iOS.

For example, Grist has no blavatar in stream:

![img_7617](https://cloud.githubusercontent.com/assets/24388/24726864/b605afe8-1a08-11e7-8ae1-d1181c4a0c2f.PNG)

And no blavatar in the topmost spot on fullpost (article) view:

![img_7618](https://cloud.githubusercontent.com/assets/24388/24726921/e1f6963a-1a08-11e7-900a-b207e736b733.PNG)

But it DOES have a blavatar on the site (feed) view:

![img_7616](https://cloud.githubusercontent.com/assets/24388/24726944/f8fc3a92-1a08-11e7-94f4-5da59858bd8a.PNG)

So, whatever bug is happening, it's not happening on the site (feed) view.

**Comment by catehstn** [comment]
@koke I thought you or @elibud had fixed something like this? But I can't find an issue. Maybe I'm thinking off #6320

**Comment by koke** [comment]
I don't recall doing anything related to reader avatars recently, @elibud worked on #6897 for the People section

**Comment by elibud** [comment]
Sent this over to the Reader team as it looks like the root cause is an issue with the endpoint not returning the correct data in the meta field.

**Comment by fraying** [comment]
Got it! Thanks, @elibud.
