### ISSUE TITLE
Bug: Unwanted Empty List Tags

### ISSUE THREAD

**Issue by michaelpiercy** [wordpress-mobile/WordPress-iOS#6981]
### Expected behavior
Convert a list type from Unordered to Ordered and vice-versa with no additional lists created.

### Actual behavior
List type converts but also creates empty list tags appended after original list.

### Steps to reproduce
1. Open blank editor
2. Create an ordered list item by selecting the Numbered List icon and type some text.
3. Convert the list type to Unordered List by selecting Bulletted List icon.
4. Check the source code by selecting Code View icon.
5. Repeat steps 3 and 4 alternating between converting to Ordered List and Unordered List and be sure to check the source code in between for exact results.

##### Tested on iPad Pro, iOS 10.2.1, WPiOS 7.3.0.1
![img_0780](https://cloud.githubusercontent.com/assets/1282071/24731750/f5ec0f66-1a63-11e7-9853-a7acb5bfabf2.PNG)

**Comment by jleandroperez** [comment]
Closing this one since it's not an actual Aztec bug, but a Hybrid editor issue.

@michaelpiercy if possible, please, try out the new editor. We'll be replacing the Visual Editor + "Plain" editor soon.

Thanks!
