### ISSUE TITLE
Media Library: Stronger message when deleting items

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#6990]
### Expected behavior
When deleting items from the Media Library, if those items were used in a Post or Page, deleting them has the unwanted consequence of ruining the aforementioned item.
We should strongly warn users about this, since it is a recurrent issue on support that they don't consider it when deleting items, for example, because they are running out of space. 

Something among this lines is what's being considered for Calypso:

_Are you sure you want to delete this item [these items]? It [They] will be permanently removed from all other locations where it [they] currently appears [appear]._

### Actual behavior
![simulator screen shot apr 7 2017 11 38 27](https://cloud.githubusercontent.com/assets/5558824/24805052/d0bd6914-1b86-11e7-9dd7-d6b8b2a96d22.png)

### Steps to reproduce the behavior
Go to the Media Library and delete on or multiple items.

##### Tested on Simulator, iOS 10.3, WPiOS 7.3 (DEV)

**Comment by SergioEstevao** [comment]
@bummytime something to consider on your refactor of the media settings screen.

**Comment by bummytime** [comment]
Yeps! This was definitely considered in the redesign that @iamthomasbishop did. As of right now, it will look something like this:

<img width="435" alt="screen shot 2017-11-07 at 8 59 43 am" src="https://user-images.githubusercontent.com/154014/32500198-4205c0ba-c39a-11e7-87a2-f75b89b12780.png">

**Comment by diegoreymendez** [comment]
Clearing the milestone as the issue missed the 9.0 deadline.
