### ISSUE TITLE
Posts are lost if published while offline

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#6999]
### Expected behavior

If I am offline when I publish a post (either in airplane mode or with a flaky connection) I expect the app to save the post as a local draft.

### Actual behavior

The post-post screen appears (which is confusing as the post wasn't successfully published) and I see the error "Error occurred during publishing." When I dismiss the post-post screen, I can't find the post saved anywhere in the app. It's completely lost.

### Steps to reproduce the behavior

1. Go offline (e.g. put the device in airplane mode with wifi off).
2. Start a new post with a title and content.
3. Tap Post.
4. After the post-post screen and error appear, tap "Done" to return to the post list.
5. Check each post status filter (Published, Draft, etc.).

Result: The post is completely gone.

(Tested with both the Visual and Aztec editors and confirmed the same behavior.)

##### Tested on iPhone 6, iOS 10.3, WPiOS 7.3.0.20170405

**Comment by rachelmcr** [comment]
Screenshot from immediately after publishing:

![2017-04-10 17 32 19](https://cloud.githubusercontent.com/assets/8658164/24872170/4f36db56-1e14-11e7-8df8-d603116f19f4.png)

**Comment by rachelmcr** [comment]
This also occurs if you save a draft with the following steps:

1. Go offline (e.g. put the device in airplane mode with wifi off).
2. Start a new post with a title and content.
3. Tap the X to close the editor.
4. Select "Save Draft."

The error "Error occurred during saving" pops up and the draft doesn't appear in the post list.

**Comment by SergioEstevao** [comment]
Investigated this a bit further and the posts are actually there but on the bottom of the list.
The reason for this is because the post is not created on the server the date is set to nil, and our ordering system makes them to go to the end. 
I'm considering to mark them with the current date and make appear on the top.

The Post after screen also needs to be updated to reflect error scenarios, when error is detected what should we do?
 - Not show this screen at all, and go back to the list and just see the notification message.
 - Change this screen to reflect the error?

**Comment by rachelmcr** [comment]
> I'm considering to mark them with the current date and make appear on the top.

I agree with that approach. I completely missed them and didn't think to scroll to the bottom of the list to check.

> The Post after screen also needs to be updated to reflect error scenarios, when error is detected what should we do?

Is it possible to stay in the editor when this error occurs, but only show the error (not the post-post screen)? That way the user stays in the same context they were in before the error occurred, and can check their connection and re-try publishing right away.

If that isn't an option, I think not showing the post-post screen and going back to the list with the error message is probably better than trying to change the post-post screen to reflect the error.

**Comment by SergioEstevao** [comment]
@rachelmcr the solution I implemented is the following: If the post fails and it's a brand new post we show an error message to the user, and convert the post to a local draft.

**Comment by rachelmcr** [comment]
Sounds good to me!
