### ISSUE TITLE
Aztec: Add accessibility identifiers for header options

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#7005]
This is a followup to the accessibility information added in https://github.com/wordpress-mobile/WordPress-iOS/pull/6967. The accessibility identifiers for the header options in the toolbar (e.g. `format_toolbar_toggle_h1`) need to be added to the header picker so they can be used in UI tests.

(Currently, tests rely on the text such as `Heading 1`. Making the accessibility identifiers available will allow tests to run in any language, regardless of the translated string for each option.)

cc @SergioEstevao

**Comment by diegoreymendez** [comment]
Considering there's a PR for this, I'm closing the issue.
