### ISSUE TITLE
Once Jetpack comment likes are launched make sure they are supported in the app

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7006]
### Expected behavior
All application sections with comments should support Likes for Jetpack sites once that feature is implemented server side.

### Actual behavior
At least on `CommentViewController` Likes are not displayed for Jetpack sites.
`cell.isLikeEnabled = [self.comment.blog supports:BlogFeatureCommentLikes];`

**Comment by elibud** [comment]
We should work on this one for 7.7 since Likes on Jetpack are expected to be implemented in the next two weeks or so.

**Comment by aerych** [comment]
Related https://github.com/wordpress-mobile/WordPress-iOS/issues/6087
