### ISSUE TITLE
Unknown HTML: Editing Support

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7010]
Once https://github.com/wordpress-mobile/WordPress-Aztec-iOS/issues/411 is implemented, we should implement the UI for unknown HTML editing support in WPiOS as well.

**Comment by jleandroperez** [comment]
We've brought this in via #7382. Closing since it's already done!

**Comment by diegoreymendez** [comment]
@jleandroperez - Remember to verify the milestone when closing issues.  Assigning to 7.9.
