### ISSUE TITLE
i18n: Reader menu items are not localized

### ISSUE THREAD

**Issue by eduardozulian** [wordpress-mobile/WordPress-iOS#7016]
Might be totally unrelated, but the Android App had a similar issue. Looks like [those strings were hardcoded](https://github.com/wordpress-mobile/WordPress-Android/issues/5240#issuecomment-281900731).

### Expected behavior

The Reader section should load a full translation.

### Actual behavior

Currently, it's a mix of localized and unlocalized strings. Checked with both Brazilian Portuguese and Spanish.

### Steps to reproduce the behavior
1. Switch the phone to a language different than English.
2. Open the WordPress app
3. Click on Reader
4. Check the menu items

### Screenshot

![wpcomappsignup](https://cloud.githubusercontent.com/assets/1136160/24933854/38edad1e-1ede-11e7-96b9-0393830c7b03.png)

**Comment by elibud** [comment]
I am checking to see if we can get this fixed on the API side.

**Comment by elibud** [comment]
Fixed by @koke via https://wpcom.trac.automattic.com/changeset/155152
