### ISSUE TITLE
Refactor No Results view to use auto layout

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7018]
We should also add the ability to limit the number of lines in the message limit to avoid situations like this:

![img_3134](https://cloud.githubusercontent.com/assets/4780/24958389/0ab11e82-1f87-11e7-9729-02e3ae28af4b.png)

**Comment by ScoutHarris** [comment]
This will be addressed with https://github.com/wordpress-mobile/WordPress-iOS/issues/9504.
