### ISSUE TITLE
Aztec Editor: Ordered Lists don't publish as ordered lists

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-iOS#7031]
Adding an ordered list via the Aztec editor shows the correct list but on publish the list is removed

### Expected behavior

Ordered list published

### Actual behavior

List removed

### Steps to reproduce the behavior

Start new post with ordered list, publish, view published

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 7 Plus, 10.3.1 WPiOS 7.4.0.20170411

Screenshot

![publish - 1](https://cloud.githubusercontent.com/assets/128826/25031140/04fc8408-210e-11e7-85e0-e0bb3162c447.jpg)

Resulting Post:

<img width="850" alt="screen shot 2017-04-14 at 12 28 26 pm" src="https://cloud.githubusercontent.com/assets/128826/25031131/ef99e326-210d-11e7-863b-d89d45c37ec7.png">

https://testsiteonlyforjuiced.wordpress.com/2017/04/14/test-bullets-2/

**Comment by diegoreymendez** [comment]
This was fixed in the latest closed beta.
