### ISSUE TITLE
Aztec Editor: Blockquotes show quoted when actually escaped

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-iOS#7032]
### Steps to reproduce the behavior

1. Start a new post
2. Enter a block quote with two lines
3. Turn off block quote
4. Switch to html view and back

### Expected behavior

Blockquote remains

### Actual behavior

Second line is not a blockquote

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 7 Plus, 10.3.1 WPiOS 7.4.0.20170411

**Video:**

https://cloudup.com/c0hxzLc2TRR

**Comment by jleandroperez** [comment]
Closing this one since it's not happening anymore. Tested on iPhone 7 / WPiOS 8.3

Thanks for the report @alisterscott !!
