### ISSUE TITLE
"See all of your likes" goes to post view instead of likes.

### ISSUE THREAD

**Issue by catehstn** [wordpress-mobile/WordPress-iOS#7036]
![img_8212](https://cloud.githubusercontent.com/assets/6810182/25086063/572eeeb8-235d-11e7-951c-0cd3294179bb.PNG)
![img_8213](https://cloud.githubusercontent.com/assets/6810182/25086066/59b8672c-235d-11e7-93c1-5cb12af4d810.PNG)

### Expected behavior
Tapping on "see all your likes" takes you to a view of all people who have liked a post.

### Actual behavior
Tapping on "see all your likes" takes you to the reader view (where there is no way to see all likes).

### Steps to reproduce the behavior
Need a post with sufficient likes that this view appears (I cannot repro it on most of my blog posts). "See all of your likes" then appears at the bottom of the likes notification view.

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 7, iOS 10, 7.3.

Reported by @m

**Comment by koke** [comment]
Dupe #4383
