### ISSUE TITLE
Email follower "View All" list limited to 20 results

### ISSUE THREAD

**Issue by ChrisHardie** [wordpress-mobile/WordPress-iOS#7037]
### Expected behavior

In visiting Stats -> Insights -> Followers (Email) -> View All for a WordPress.com site active in the iOS app, I expect to see the full list of email followers/subscribers for the site. On a site I help manage for a family member, the count would be 59. This matches up with the label at the top of the list, "Total Email Followers: 59", and the results available via wp-admin.

### Actual behavior

I only see the 20 most recent email followers with no pagination or option to view the full list. 

### Steps to reproduce the behavior

Visiting Stats -> Insights -> Followers (Email) -> View All for a WordPress.com site.

##### Tested on iPhone 6, iOS 10.3.1, WPiOS internal 7.4.0.20170414. Also reproduced on an iPhone 6S with the release version of the app.

**Comment by designsimply** [comment]
Tested and confirmed using the following testing steps:

1. Go to Stats > Insights > Followers > View All.
1. Try to view more than the latest twenty followers.

<strong>Result:</strong> cannot see more than 20 listed, cannot scroll to see more.

<strong>Video:</strong> [31s](https://cloudup.com/cZv4gpatDua)

<img alt="screen shot 2017-07-12 at wed jul 12 4 48 51 pm" src="https://user-images.githubusercontent.com/1119271/28143353-5566ee06-6722-11e7-9ea1-d537ad20189c.png" width="270" />
<sup>Tested with iPhone 6S, iOS 10.3.2, WPiOS WP Internal 8.0.0.20170712.</sup>

**Comment by frosty** [comment]
Stats will be refreshed in the near future by the NoDeadEnds project, so this may get addressed as part of that.

**Comment by ScoutHarris** [comment]
This will be addressed with the Stats Refresh [project](https://github.com/wordpress-mobile/WordPress-iOS/projects/13).
