### ISSUE TITLE
Reader Detail: Some images load with a 0,0 size.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#7048]
Originally reported by @chrissiepollock 

> User doesn’t see images from https://1969chriscraftroamer46.wordpress.com/2017/04/13/1969-chris-craft-roamer-46-refit-cutting-and-fitting-the-v-berth-starboard-side-mahogany-panel/.
> This happens with other posts from this site as well. It does not happen with other sites I check

I notice that the images are loaded but have a 0,0 size.  I'm inclined to chalk this glitch up to issues animating and/or correctly updating the content insets of the textview, but I can't say for sure without digging deeper.

To reproduce:
1. follow the user's site or like one of the posts
2. view posts from the site in the reader detail. 
3. scroll down and notice that there is space available for the images but the images are not shown. 
4. rotate the device and back
5. note that images are now visible.

**Comment by rachelmcr** [comment]
Another user sent in app feedback reporting what sounds like the same issue:

> There is an issue loading photos in the app when viewing blogs. Sometimes the pictures do not appear. However if you turn phone to landscape then back they then appear.

Let me know if you'd like me to contact this user for more details. (Internal ref: AppbotX 29242)

**Comment by rachelmcr** [comment]
Another user reported similar feedback:

> Les photos des articles des autres personnes ne se chargent pas sur l'application. Ca laisse des espaces blancs. 

Translation:

> Photos of other people's articles do not load on the application. It leaves white spaces. 

Internal ref: AppbotX 29608

Reported on iPhone 5s, iOS 10.3.2, WPiOS 7.8.1

**Comment by rachelmcr** [comment]
I believe this user's feedback may be the same issue:

> photos often don't show up in posts in Reader (which means I have to make the effort of going to my computer, which basically negates the point of the smartphone app!) 

Internal ref: AppbotX 29592

Reported on iPhone 5s, iOS 10.2.1, WPiOS 7.8
