### ISSUE TITLE
Reader Detail: Switch layout to a UITableView

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#7055]
The current iteration of the reader detail relies on setting and updating a UITextView's contentInset property to mimic readable content margins. This allows for swipe gestures in the margins to be detected and keeps the scroll bar flush right with the screen, and seemed to work well when first deployed. 

Since then we've encountered a number of issues that can be attributed to how and when contentInsets are updated during a layout cycle, and glitches seemed to have increased since displaying the reader in a UISplitView due to how it changed the layout cycle.  See #7048 #6867 #6702 for some examples.

I've chatted on and off with @frosty @kurzee and @koke about the pros and cons of using a [UITableView](https://github.com/wordpress-mobile/WordPress-iOS/issues/6040#issuecomment-276126916) for the reader detail as a way of resolving some of the layout issues we're seeing.  The consensus is it *seems* like a reasonable solution. 

The idea is to present UITextView's for individual paragraphs (and possibly embeds) in individual UITableViewCells.  The UITextView's in the cells will not scroll and therefore will be sized to match their content height.  Reusing cells means that the detail would no longer attempt to load *every* image included in a post, thus resolving #6040. 

Recommending we prioritize this over any other UI changes to the reader detail.

**Comment by aerych** [comment]
I should add this would be rather similar to how comments are displayed in the reader, so we have prior art in a sense.

**Comment by koke** [comment]
@aerych how much effort do you think this is? I'm wondering if it could fit in a week's work or it has to be part of a larger project

**Comment by aerych** [comment]
A week's effort wouldn't surprise me.

**Comment by leandroalonso** [comment]
Reader Detail now uses web view, closing this issue.
