### ISSUE TITLE
Improve Reader iPad splitview UX

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7069]
There's some inconsistency around when the iPad splitview sidebar is displayed in the Reader, and we've also had some reports that it often needlessly takes up screen space. We currently hide it any time you push into a full post view, and for any subsequent navigation down from that post. Ideally, to be consistent with Calypso, we should modify the behaviour slightly:

* Remove the sidebar when viewing comments for a post. Currently if you tap into comments from a stream, we don't hide.
* Show (or re-show) the sidebar if you navigate into a stream.

I'm not entirely sure how well this will play with push and pop navigation, so we may need to experiment.

Alternatively (or in addition), we should add the ability for the user to manually show and hide the sidebar whenever they like.

Possibly related: https://github.com/wordpress-mobile/WordPress-iOS/issues/6738

**Comment by aerych** [comment]
Keep https://github.com/wordpress-mobile/WordPress-iOS/issues/7055 in mind when looking at this one.

**Comment by kean** [comment]
It doesn't seem to be relevant anymore. In 25.4, the sidebar behaves according to the standard system behavior. It is hidden automatically in portrait. In landscape, it's always shown only when there is enough space.
