### ISSUE TITLE
Media: Present media from other sources (Dropbox, Google, etc)

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7081]
It would be nice to allow users to import images from other apps / services, using `UIDocumentMenuViewController`. For example:

![dv0iq](https://cloud.githubusercontent.com/assets/4780/25411045/4d2aebcc-2a12-11e7-8fb5-713ab2228b89.png)

**Comment by sarahblackstock** [comment]
User requested ability to add images from Google Photos. 

internal ref: #197733-h

**Comment by sarahblackstock** [comment]
App reviewer requested ability to add images from other sources: 

>still can't load media from sources other than Photos, so the app still fails short of the web interface and the desktop application.

**Comment by frosty** [comment]
Just some more info for when we come to implement this:

With iOS 11, `UIDocumentMenuViewController` has been deprecated in favour of `UIDocumentPickerViewController`. We should probably just use the document picker when we implement this.

We're also currently only interested with importing files into WPiOS, not exporting them.

Editor-wise, I think we can keep this to Aztec-only, and add a new option to the formatting bar when it's in 'media insertion' mode. The icon would then simply present the document picker, upload and insert the item when selected. cc @iamthomasbishop, as he's responsible for the formatting bar's design. Current state of the bar, for reference:

<img width="555" alt="29455178-125e2a22-8408-11e7-8e0b-c44e7313e0a3" src="https://user-images.githubusercontent.com/4780/30721002-cf12feac-9f21-11e7-9bbb-929c4e2ad219.png">

If it's easier for a first step, we could add this support to the standalone Media Library section of the app first, and then the editor later.

We should probably also begin with just image and video filetypes, and then add other filetypes as a later step.

**Comment by sarahblackstock** [comment]
From a recent support message: 
>I want to add images not in my media library but on a Dropbox account or any other server. The app does not offer me the option to navigate to the third party folders.
Since navigating to third party folders has been vastly improved in iOS 11, I was wondering if this option will be available in a future version of the app as well.

internal ref: #226946-h

**Comment by frosty** [comment]
@sarahblackstock Thanks – we've started working on this now!

**Comment by kwonye** [comment]
@frosty is this feature "done"? Should we close this out?

**Comment by frosty** [comment]
@kwonye I think we can close this out for now. There are a few future improvements we may want to add to the feature, but we could open other issues for those:

* Support other filetypes (currently only images + videos)
* Support importing multiple files at once
