### ISSUE TITLE
Slug not pre filled for drafts

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7083]
When a Post is saved for the first time the slug field should be pre-populated with the `other_URLs.suggested_slug` field.
Also, we can display a hint with the lowercase post title before the post is saved (to hint what the slug will probably be)

**Comment by elibud** [comment]
@rachelmcr I think we should only populate the slug field once the draft is saved. The reason for that is the following: 

There are some modifications done to the post title to create the slug, the easy to see ones like replacing spaces by dashes and some more complex ones like removing stars and ampersands. For example the title 'f***&perfect' will become the slug 'fperfect' I don't want to replicate the server side logic on the app and I don't want to show an incorrect slug to our users.

On Calypso it seems like the slug is always populated because it uses the autosave feature, and once we integrate that on iOS we will get the same behavior. For now though we will only have a slug after the post is saved server side (for drafts I will use the suggested_slug field). 

It is still an improvement on how I originally implemented it though :)

**Comment by rachelmcr** [comment]
>I don't want to replicate the server side logic on the app and I don't want to show an incorrect slug to our users.

Very good points. Populating the slug when the draft is saved sounds good to me. :)
