### ISSUE TITLE
Create our own dismissible HUD

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7087]
As discussed here: https://github.com/wordpress-mobile/WordPress-iOS/pull/7059 we want to have our own dismissible HUD.
We can base our work on the existing SVProgressHUD + its dismissible category. The main behaviour we want to add is having touches on the screen, outside the HUD to:
1. Dismiss the HUD
2. Affect the appropriate underlying view

Other nice to haves would be:
- Different default colors for success and error messages
- Different default display times for success and error messages

@koke @frosty

**Comment by catehstn** [comment]
I'm not sure taps should affect the underlying view. IMO a tap should only do one thing - in this case, dismiss the HUD. Adding design review tag.

**Comment by elibud** [comment]
Yeah, I am not 100% sold on that either, extending the iOS view model the touches should go through in the transparent area, however I am not sure that's what users expect. 
@koke do you want to add more on this since you originally requested the feature?
Lets also see what design has to say.

**Comment by koke** [comment]
My annoyance comes when you do something like saving a draft from the ... menu, which doesn't dismiss the editor and you get this:

![simulator screen shot 28 apr 2017 15 38 33](https://cloud.githubusercontent.com/assets/8739/25531108/efed5c7e-2c28-11e7-9975-617378f41fee.png)

And that stays there blocking the screen for like 5 seconds. Tap to dismiss is obviously much better than what we have now, but the HUD to me feels more of a toast/push notification thing. There's no blurring or dimming of the background which implies taps would go through.

As I wrote that, what this probably means is that the HUD wasn't the right UI for this to begin with: we have the "saving" HUD blocking the UI with a transparent style that also implies I should be able to tap through.

But the more I think about it, I just want to get rid of the HUD completely: if you save a draft let's have a non-blocking indicator to let you know that it's saving, but that shouldn't prevent you to keep writing or closing the editor (specially when saving takes 5 seconds).

**Comment by elibud** [comment]
> But the more I think about it, I just want to get rid of the HUD completely: if you save a draft let's have a non-blocking indicator to let you know that it's saving, but that shouldn't prevent you to keep writing or closing the editor (specially when saving takes 5 seconds).

+1

**Comment by frosty** [comment]
+1, and +1 for touches not passing through – I think they should dismiss the HUD.

Also, I'd class the '5 seconds' thing there as a bug. SVProgressHUD changed its behaviour with its 2.0 release which made these HUDs appear for longer than they used to. I've tweaked it in a few places to show for a minimum of 1 second, but we should fix these others too.

**Comment by shubh10** [comment]
Try this HUD library for iOS in swift https://github.com/shubh10/JustHUD
