### ISSUE TITLE
Jumbled Tagline Text on iOS

### ISSUE THREAD

**Issue by geekinthegirl** [wordpress-mobile/WordPress-iOS#7105]
### Expected behavior
Site's tagline should appear as a normal sentence, with no text overlapping.

### Actual behavior
Tagline text is jumbled in iOS, making it unreadable.

### Steps to reproduce the behavior
Colleagues with iOS devices were unable to reproduce this behaviour. User sent this screenshot of what they're able to see: 
![zpqrhx4](https://cloud.githubusercontent.com/assets/22247240/25563809/b82fea12-2d9b-11e7-8ac8-ffdac1249bca.png)

The mobile preview in the Customizer looks similar:
<img width="1440" alt="screen shot 2017-04-30 at 11 55 23" src="https://cloud.githubusercontent.com/assets/22247240/25563822/0ea987c2-2d9c-11e7-933b-351dd47b6523.png">

However for comparison, the text looks fine on my own Android device: 
![screenshot_20170430-111156](https://cloud.githubusercontent.com/assets/22247240/25563825/23ce7d2e-2d9c-11e7-888f-a2e2d9e9ed64.png)

**Comment by catehstn** [comment]
Checked with @kathrynwp - this is a bug in the minileven theme, which can be turned off as the theme being used is responsive.

Closing this as not the right repo.
