### ISSUE TITLE
Aztec: Post format toolbar should be disabled while in post title field

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7107]
### Expected behavior
Toolbar buttons for formatting shouldn't be enabled when editing the post title.

### Actual behavior
Buttons for post formatting are enabled while in the post title field. Tapping them affects the post content.

### Steps to reproduce the behavior
1. Create a new post in Aztec.
2. Put some text into the post content area.
3. Tap back into the post title.
4. Notice the buttons are still enabled. Tapping one of them will alter contents of the post body.

##### Tested on unknown, iOS 10, WPiOS 7.5

Internal reference: `p4a5px-1J0-p2`

**Comment by jleandroperez** [comment]
Closing this one as cannot repro. TEsted on WPiOS 8.3 / iPhone 7 / iOS 10,

Thanks Aaron!
