### ISSUE TITLE
Editing menus removes CSS classes

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7108]
### Expected behavior
Editing a menu will retain any custom CSS associated with it.

### Actual behavior
CSS is wiped when editing a menu item.

### Steps to reproduce the behavior
1. Open a menu item that has CSS defined already.
2. Edit the menu item.
3. Save the changes.
4. CSS styles are now gone.

##### Tested on unknown; WP core 4.7.4

Internal reference: `p4a5px-1J5-p2`
cc: @kurzee

**Comment by kurzee** [comment]
Looks like we just need to carry over the `classes` array of strings when fetching/updating a Menu. Will work this in soon.
