### ISSUE TITLE
Aztec: Carriage returns removed

### ISSUE THREAD

**Issue by michaelpiercy** [wordpress-mobile/WordPress-iOS#7109]
### Expected behavior
Carriage returns of existing post to remain intact.

### Actual behavior
After turning on Aztec editor, carriage returns of posts are removed.

### Steps to reproduce the behavior
Write a post in normal editor.
Turn on Aztec editor.
Edit previous post.
Carriage returns are gone.

##### Tested on iPad Pro, iOS 10.2.1, WPiOS 7.5.0.1
![img_0816](https://cloud.githubusercontent.com/assets/1282071/25592801/095557ee-2eb2-11e7-9688-b4a059b5c5b3.PNG)
![img_0817](https://cloud.githubusercontent.com/assets/1282071/25592804/097a9996-2eb2-11e7-8877-34b093308699.PNG)
![img_0818](https://cloud.githubusercontent.com/assets/1282071/25592802/09729502-2eb2-11e7-83a5-255d7898ec29.PNG)

**Comment by rachelmcr** [comment]
Possibly related to https://github.com/wordpress-mobile/AztecEditor-iOS/issues/274. This should be mostly solved, although there are related issues being tracked in https://github.com/wordpress-mobile/AztecEditor-iOS/issues/64 and https://github.com/wordpress-mobile/AztecEditor-iOS/issues/547. Closing this as those issues are tracking further work on paragraphs in Aztec.
