### ISSUE TITLE
Typo in /WordPress/WordPressApi/WordPressOrgXMLRPCApi.swift

### ISSUE THREAD

**Issue by DiegoRBaquero** [wordpress-mobile/WordPress-iOS#7110]
Hello,

Just wanted to let you guys know there's a typo in here: https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/WordPressApi/WordPressOrgXMLRPCApi.swift#L182

The function should be named `createProgressForTask` not `createProgresForTask`

Cheers.

**Comment by rachelmcr** [comment]
Thanks for the report! Closing as resolved in https://github.com/wordpress-mobile/WordPress-iOS/pull/7282.
