### ISSUE TITLE
Notifications: if you mark all as read in the app, messages still show up as unread on a desktop browser

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#7111]
Reported by @jessefriedman at p1493652120946802-slack-automattic

<blockquote>can anyone else confirm a problem where the latest WPiOS app isn't clearing notifications from WordPress.com? In other words when I "mark it read" in the app, all notifications are still unread on .com</blockquote>

Steps to reproduce:

1. Launch WPiOS and open the Notifications tab.
1. Send the app to background.
1. Open the System Settings, and bump up the date +1 day.
1. With the app in background, receive a new notification.
1. View notifications until Unread notifications have all been viewed.
1. Go to https://wordpress.com/ using a desktop browser and check to see if the notifications are still marked as unread.

<strong>Result:</strong> everything marked as read in the WPiOS app, but the orange bell clanger notifier still indicating there are unread messages.

<img alt="img_1171" src="https://cloud.githubusercontent.com/assets/1119271/25598422/3ae2544e-2e92-11e7-8961-e455dfcf9fed.PNG" width="300" />
<sup>Tested with iPhone 6S, iOS 10.3.1, WPiOS 7.5.0.20170501</sup>

![screen shot 2017-05-01 at mon may 1 5 00 16 pm](https://cloud.githubusercontent.com/assets/1119271/25598427/4156f9c4-2e92-11e7-8193-dfa883f18c22.png)
<sup>Seen at https://wordpress.com/ using Firefox 53.0 on Mac OS X 10.12.4.</sup>

More screenshots: https://cloudup.com/c9wE8gOo2nX

**Comment by ScoutHarris** [comment]
I wasn't able to repro this. Reading notifications in the app now updates the notifications in the browser.
