### ISSUE TITLE
HTML Entities in My Profile fields

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#7114]
### Expected behavior

I expect to be able to enter special characters like `&` in the My Profile fields.

### Actual behavior

Characters like `&` entered in the First Name, Last Name, and Display Name fields are converted into HTML entities after the changes are saved. Those HTML entities then also show up in other places in the app (e.g. the author name in the Reader).

### Steps to reproduce the behavior

1. Open Me > My Profile in the app.
2. In the Display Name field, enter a special character like `&`.
3. Go back to My Profile and note that you see the correct character.
4. Go back to Me and reopen My Profile.

Result: The character is now encoded as an HTML entity.

![2017-05-04 11 42 27](https://cloud.githubusercontent.com/assets/8658164/25700652/81fb28d0-30c0-11e7-807e-49e380a239c5.png)

##### Tested on iPhone 6, iOS 10.3.1, WPiOS 7.5.0.20170501

**Comment by ChrissiePollock** [comment]
Asked about again in internal issue #193428-h

**Comment by ChrissiePollock** [comment]
Brought up in #238570-h

**Comment by SiobhyB** [comment]
This was brought up again in 266785-h and I was able to replicate by adding a **&** symbol to my display name.

**Comment by nellofn** [comment]
A user reported this issue on 276697-h, and I was able to replicate it by adding the "&" on my display name.

If I add the symbol through the app, and go back to my display name, it will show correctly. However, the character is no longer converted after I close / re-open the app.

Tested in iOS 9.7.2

**Comment by nellofn** [comment]
I did a test in release 9.8, and the special character is no longer encoded as an HTML entity.

**Comment by koke** [comment]
It looks like #8951 took care of this one
