### ISSUE TITLE
Share Extension: Shared images not always attached

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#7124]
### Expected behavior

A user reported that the YouVersion app is no longer sharing an image to the WordPress app. YouVersion has a daily bible verse along with an image, and you can share the image (along with a link to the verse). This works correctly when sharing to other apps (e.g. Twitter, Facebook, Instagram).

### Actual behavior

Sharing the image worked until a couple weeks ago (the image was correctly uploaded as inserted into the post as a gallery) but it now only shares a link instead of attaching the image with it.

@koke Could one of the changes you made to the share extension in version 7.4 have affected this sharing behavior?

### Steps to reproduce the behavior

1. Install the YouVersion app and create an account.
2. Look for the "Verse of the day" on the Home tab.
3. Tap on "View All" on that card to go to the Verse of the day section.
4. Tap on "Image" at the top to switch to image verses.
5. Tap the share icon and select WordPress as a sharing target.

Result: Only the link is shared, no image is included. (Sharing to other apps shares the image as expected.)

##### Tested on iPhone 6, iOS 10.3.1, WPiOS 7.4

**Comment by koke** [comment]
Tested on develop, and the share extension is picking up the image (but only the image), probably fixed by #7067.

So far we only extract one of the types of data passed, but I agree it'd be better to allow images AND (text OR url)

**Comment by designsimply** [comment]
Tested and confirmed the fix using iPhone 6S, iOS 10.3.2, WPiOS 7.7.0.20170522. Posting some screenshots for reference:

<img alt="img_1237" src="https://cloud.githubusercontent.com/assets/1119271/26427896/08d9a7b0-409c-11e7-8feb-2187fefe95c4.PNG" width="200" /> <img alt="img_1238" src="https://cloud.githubusercontent.com/assets/1119271/26427898/08e409b2-409c-11e7-8229-99c55993cbd5.PNG" width="200" /> <img alt="img_1242" src="https://cloud.githubusercontent.com/assets/1119271/26427894/08d50200-409c-11e7-8e69-0f28e692cdf4.PNG" width="200" /> <img alt="img_1240" src="https://cloud.githubusercontent.com/assets/1119271/26427895/08d552dc-409c-11e7-8a2d-0d5cdee9e7ef.PNG" width="200" /> <img alt="img_1243" src="https://cloud.githubusercontent.com/assets/1119271/26427893/08d49a90-409c-11e7-864f-2072c9262b6b.PNG" width="200" /> <img alt="img_1244" src="https://cloud.githubusercontent.com/assets/1119271/26427897/08db5222-409c-11e7-9a7a-f9a19d7c0cae.PNG" width="200" />
