### ISSUE TITLE
Image location

### ISSUE THREAD

**Issue by huanghualove** [wordpress-mobile/WordPress-iOS#7131]
If i just insert the picture, then this time the picture position is reversed position? How to solve it, big god

**Comment by elibud** [comment]
Hi @huanghualove, can you give us steps to reproduce the problem and a screenshot of the final result? Thanks

**Comment by huanghualove** [comment]
First I inserted the picture of the first flower, and then after I inserted the second Anthony photo, it was reasonable to say that the photo of the flower should be above, Anthony should be below. But the display is the opposite position.
![wechatimg216](https://user-images.githubusercontent.com/16163662/31707414-d6b78616-b41e-11e7-921f-b987c1a96a82.jpeg)

**Comment by elibud** [comment]
Which application are you using there? That doesn't look like the WordPress iOS app.

**Comment by elibud** [comment]
Closing until we hear back from the user.
