### ISSUE TITLE
Row added for new page in Pages List shows `(no title)` until screen is refreshed

### ISSUE THREAD

**Issue by tonyr59h** [wordpress-mobile/WordPress-iOS#7148]
### Expected behavior
Creating a new page should add a row with the correct page title.

### Actual behavior
Adding a row inserts a new row with `(no title)` as the title string.

[Here](https://cldup.com/mHy2eJtgWf.PNG) is the list after adding a page titled `Portfolio`.
[Here](https://cldup.com/mxP0AQU_bA.PNG) is the list after going to the Comments screen then back to `Pages`.

Subsequent pages added while the text is still `(no title)` do not show up in the list until leaving the screen.

Pages added after refreshing the screen are added correctly.

And I don't know if it's of any consequence but the `Today` section is at the bottom of the list while it shows `(no title)` but when you refresh it's at the top of the list.

### Steps to reproduce the behavior
* Add a new page with a title; see that the new row has no title set
* Add a new page with a different title; see that no new row is added to the list
* Leave the page list and return; see that both pages are in the list and the titles are correct

**Comment by elibud** [comment]
This one's awful, thanks for reporting @tonyr59h
