### ISSUE TITLE
Inconsistency between images displayed on Reader and on Post List

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7154]
### Expected behavior
For the same post we should display the same image on both Reader and Post list.

### Actual behavior
On PostService.m we are using:
```[DisplayableImageHelper searchPostContentForAttachmentIdsInGalleries:post.content]```
On ReaderPostServiceRemote.m we are using:
```editorial.image``` and if that is not present
```[DisplayableImageHelper searchPostContentForImageToDisplay:content]```

**Comment by elibud** [comment]
@aerych I don't think we should be looking at Gelleries right?

**Comment by aerych** [comment]
I've been testing this branch in the simulator on and off all morning. Just taking a general survey of features and so far I'm not seeing anything out of place.  All tests pass.  Everything seems solid :)
Nice work!   :shipit: from me.
