### ISSUE TITLE
Posts & Pages: Include a link to the post or page

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7159]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/442

Currently, tapping on a post title leads to the detailed stats for that post:

![2017-03-27 11 14 58](https://cloud.githubusercontent.com/assets/8658164/24366661/62a5e65e-12df-11e7-94a8-393f7390d9ae.png)

![2017-03-27 11 15 05](https://cloud.githubusercontent.com/assets/8658164/24366539/04caf3a8-12df-11e7-92b5-bfd723d47249.png)

A user sent in feedback requesting a link from stats to the post itself, to view it. This is similar to the arrow next to the post title on the web, which opens the post:

<img width="481" alt="screen shot 2017-03-27 at 11 12 22 am" src="https://cloud.githubusercontent.com/assets/8658164/24366374/8cf49cee-12de-11e7-8022-708becd8f7ed.png">

Requested in AppbotX 27228. Current behavior tested in beta version 7.2.0.20170317.

**Comment by ScoutHarris** [comment]
New design coming with the Stats Refresh [project](https://github.com/wordpress-mobile/WordPress-iOS/projects/13).
