### ISSUE TITLE
Consider firing view lifecycle methods with segmented control changes

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7161]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/412

Currently viewDidAppear (& other view lifecycle methods) are not fired off when the segmented control changes which segment is selected. This could lead to some unexpected behavior if the user is hanging out on the screen for a while and update methods aren't fired. Its probably a small use case and could be argued either direction.

Contemplate the implications of the change and determine if it should be done. If so, do it. 😄

**Comment by ScoutHarris** [comment]
This will be addressed with the Stats Refresh [project](https://github.com/wordpress-mobile/WordPress-iOS/projects/13).
