### ISSUE TITLE
Insights: Posting Activity section not optimized for VoiceOver

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7162]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/409

VoiceOver doesn't do well with the Posting Activity stats section. A few observations:
- On the main Insights tab, the calendar button only has the spoken label "button" with no other details.
- On the Posting Activity detail page, individual days in the calendar (including days with posts) only have the spoken label "button."
- If you select a day, it speaks "selected" but gives no indication of the date or number of posts on that day. You have to move back to the label at the top of the screen to get that information.
- The "Less posts" and "More posts" labels at the bottom of the screen are spoken but it's unclear what they refer to without more context.

**Comment by shiki** [comment]
@ScoutHarris Based on your comment on https://github.com/wordpress-mobile/WordPress-iOS/issues/7186#issuecomment-509447553, do you think this should this be closed as well? I'm not sure if this is still relevant considering this issue was created in 2017.

**Comment by ScoutHarris** [comment]
Hey @shiki . Thanks for noticing this one. Yea, this one can be closed as Posting Activity is noted on https://github.com/wordpress-mobile/WordPress-iOS/issues/11995.
