### ISSUE TITLE
Split apart Storyboard cells into XIBs

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7164]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/402

Because of the reuse of cells amongst three different view controllers, split them into XIBs. This also means not using segues.

**Comment by ScoutHarris** [comment]
This will be addressed with the Stats Refresh [project](https://github.com/wordpress-mobile/WordPress-iOS/projects/13).
