### ISSUE TITLE
Improve UIImage template loading (reduce code)

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7166]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/350

https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/pull/349#discussion_r44709584
h/t: @jleandroperez

**Comment by ScoutHarris** [comment]
This will be addressed with the Stats Refresh [project](https://github.com/wordpress-mobile/WordPress-iOS/projects/13).
