### ISSUE TITLE
Support RTL languages properly

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7167]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/331

Related issue: https://github.com/wordpress-mobile/WordPress-iOS/issues/4346

Fix the stats screens to support RTL properly.

**Comment by designsimply** [comment]
I checked the stats in Hebrew in the latest 13.5 beta (iPhone 6S, iOS 13.1.3) and RTL looks good on the screens I spot checked (except some of the arrows may be pointing the wrong way). Closing this issue as resolved but with a note to ask for help checking on the arrows. cc @yaelirub 

<img src="https://user-images.githubusercontent.com/1119271/67725808-3d9d0280-f9a9-11e9-9168-8e1c78904385.PNG" width="200" alt="IMG_3010 1"> <img src="https://user-images.githubusercontent.com/1119271/67726018-1561d380-f9aa-11e9-889d-7b05e5adc5a3.PNG" width="200" alt="IMG_3009 1"> <img src="https://user-images.githubusercontent.com/1119271/67726035-29a5d080-f9aa-11e9-9513-97535643e92a.PNG" width="200" alt="IMG_3008 1"> <img src="https://user-images.githubusercontent.com/1119271/67726103-5d80f600-f9aa-11e9-8e79-a875248b5527.PNG" width="200" alt="IMG_3007 1"> <img src="https://user-images.githubusercontent.com/1119271/67726111-61ad1380-f9aa-11e9-9492-52a8d53bb4ae.PNG" width="200" alt="IMG_3006 1"> <img src="https://user-images.githubusercontent.com/1119271/67726126-6d003f00-f9aa-11e9-85d0-01f2d0a8b589.PNG" width="200" alt="IMG_3003 1">

**Comment by designsimply** [comment]
Following up to note I found that the arrows are indeed skewampus and are on the list to be fixed in Stats Refresh v2 via https://github.com/wordpress-mobile/WordPress-iOS/issues/11767.

**Comment by ScoutHarris** [comment]
> skewampus

Best. Word. Ever. 😜
