### ISSUE TITLE
Post title in details could look prettier

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7168]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/321

Comment from a PR: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/pull/315#issuecomment-142093518

Make the text in the post details screen (and other screens) look nicer when its in the nav bar. It should be multiple lines or at least a smaller font.

Thanks @jleandroperez!

**Comment by ScoutHarris** [comment]
Addressed in Stats Refresh.
