### ISSUE TITLE
Possible crash in bad connection scenario

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7170]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/312

Crash: http://crashes.to/s/17d597fd68a

Dig further into this issue but it appears there is a crash when an error condition is returned from some of the remote calls. It is quite possible the error object is not being interrogated at the local service level causing a crash when a nil object is added to a collection.

Verify, repair.

**Comment by rachelmcr** [comment]
Closing as we don't have any recent reports of this crash.
