### ISSUE TITLE
Post Details - Numbers in right hand column don't align all the time

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7172]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/305

Title has it.

![2015-09-01_06-57-45](https://cloud.githubusercontent.com/assets/373903/9603576/2ba6c9f6-5077-11e5-87f2-60a442f8c228.png)

**Comment by ScoutHarris** [comment]
Addressed with Stats Refresh.
