### ISSUE TITLE
Post Details - Recent Weeks shows dates before post date

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7173]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/304

In this example the post was made in August yet in Recent Weeks its showing weeks before the post was made. I believe this is an API issue.

![2015-09-01_06-57-45](https://cloud.githubusercontent.com/assets/373903/9603543/e989f7e6-5076-11e5-8ba2-bbf3e40bb27a.png)

**Comment by ScoutHarris** [comment]
Addressed with Stats Refresh.
