### ISSUE TITLE
Insights All-Time should get different layout for narrow screen

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7174]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/301

![ios simulator screen shot aug 26 2015 7 29 35 pm](https://cloud.githubusercontent.com/assets/373903/9509773/2e69c5fa-4c29-11e5-9bd9-4dbbe72af819.png)

**Comment by ScoutHarris** [comment]
Negated with Stats Refresh.
