### ISSUE TITLE
Insights Most Popular should get different layout for narrow screen

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7175]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/300

![ios simulator screen shot aug 26 2015 7 29 32 pm](https://cloud.githubusercontent.com/assets/373903/9509766/129f9282-4c29-11e5-99c1-7da968d50046.png)

**Comment by ScoutHarris** [comment]
New design coming with the Stats Refresh [project](https://github.com/wordpress-mobile/WordPress-iOS/projects/13).
