### ISSUE TITLE
View All crash with table animation error

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7176]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/278

Crash: http://crashes.to/s/63bdcdb177b

Appears that there is a sporadic crash in the view all view that is caused by an incorrect row count after an update is performed. Make sure all row adds/deletes are wrapped in the proper method calls to prevent this from happening.

**Comment by rachelmcr** [comment]
Closing as we don't have any recent reports of this crash.
