### ISSUE TITLE
Bringing back the app to foreground causes the reset of the last selected bar (and the reload of Stats data)

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7180]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/252

If you bring the app back to foreground, you will see the "old bar" already selected in the graph, and a  refresh of data is called automatically. Then the selected bar in the graph will be switched to the first bar when the network response arrives from the server.

It'a a kind of weird, especially on slow mobile network connections, where you have the possibility of seeing the Stats screen already filled for a long time, and even scroll it. Then everything changes under your eyes when the response arrives.

**Comment by ScoutHarris** [comment]
This is negated by Stats Refresh.
