### ISSUE TITLE
Followers module has incorrect values for the "Since" column

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7181]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/251

![screen shot 2015-05-05 at 15 20 30](https://cloud.githubusercontent.com/assets/518232/7473377/0947e942-f33b-11e4-80ea-b2e3135f9633.png)

Web version:
![screen shot 2015-05-05 at 15 27 14](https://cloud.githubusercontent.com/assets/518232/7473416/4f28a32a-f33b-11e4-8e51-8fca3675e5e4.png)

**Comment by ScoutHarris** [comment]
This is addressed with Stats Refresh.
