### ISSUE TITLE
Stats: Jetpack user info is unavailable so we need a better solution for what to display for the Authors module for Jetpack sites

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7182]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/249

Related: https://github.com/wordpress-mobile/WordPress-Android/issues/2605

Jetpack sites don't really have any data for the authors module. Either hide the entire module or provide a consistent message that's not just an empty row.

cc: @daniloercoli

**Comment by designsimply** [comment]
I tested with WPiOS 13.6.0.2 beta (TestFlight) today and found that the Stats > Days > Authors module doesn't show the names of authors with email addresses that aren't associated with a WordPress.com account, but the authors module also isn't just blank.

<img src="https://user-images.githubusercontent.com/1119271/68966697-efa33f80-079b-11ea-92f1-e138c0f284da.PNG" width="270" alt="IMG_3062 1">
<sup>Tested with WPiOS 13.6.0.2 TestFlight beta on iPhone 6S iOS 13.2.2.</sup>
