### ISSUE TITLE
Stats: detect OAuth2 token status and display the 'not loaded' view with a more specific message

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7183]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/248

When an OAuth2 token is revoked, show something more useful than unable to retrieve in each section.

<img src="https://cloud.githubusercontent.com/assets/373903/7411853/b819d3ba-ef01-11e4-8f33-d729a1ed3f78.png" width="270" alt="ios_simulator_screen_shot_30_apr_2015_13 21 53">

**Comment by designsimply** [comment]
I tried the following steps:

1. Log in to the app.
1. On the web, log in to WordPress.com as the same user.
1. Go to https://wordpress.com/me/security/connected-applications
1. Click "Disconnect" for "WordPress for iOS".
1. Go back to the app and browse through a few Stats screens.

**Result:** the Insights screen shows "An error occurred." The Days screen was cached and continued to show the same data. The Weeks/Months/Years screens were not cached and displayed a "Stats not loaded" message. At this point, I am technically logged out with the token having been revoked, and if I try to change to any other screen in the app I am prompted to log in again.

<img src="https://user-images.githubusercontent.com/1119271/68969222-b40b7400-07a1-11ea-91ab-3381c3b2919e.PNG" width="200" alt="IMG_3063 1"> <img src="https://user-images.githubusercontent.com/1119271/68969223-b40b7400-07a1-11ea-84a6-655ddd9f9aac.PNG" width="200" alt="IMG_3064 1"> <img src="https://user-images.githubusercontent.com/1119271/68969224-b40b7400-07a1-11ea-8273-ccacedc33ed9.PNG" width="200" alt="IMG_3065 1">
<sup>Tested with WPiOS 13.6.0.2 TestFlight beta on iPhone 6S iOS 13.2.2.</sup>

@ScoutHarris one potential improvement we could make would be to also show the "Stats not loaded" message on the Insights screen too. Do you think that's a change worth making? I think the improvements with the Stats Refresh project are already really good here.

**Comment by ScoutHarris** [comment]
Hey @designsimply .

> one potential improvement we could make would be to also show the "Stats not loaded" message on the Insights screen too. 

I think it would if Insights isn't cached. Or at least it's supposed to. 😄  But generally speaking, it's clear we need to handle this scenario better, for both Insights and Periods. I assume we can detect the OAuth2 token status, allowing us to display the 'not loaded' view with a more specific message.

**Comment by irfano** [comment]
This issue is still up-to-date.
