### ISSUE TITLE
Add UI tests for Stats

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7184]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/237

All the functionality of the stats screen could be tested using UI testing made available on Xcode 7.

The work for doing this could also help improving/increase the accessibility labels on the component.

**Comment by designsimply** [comment]
I checked https://github.com/wordpress-mobile/WordPress-iOS/tree/develop/WordPress/WordPressTest and didn't spot any tests for Stats so this issue is still valid. 😁

**Comment by designsimply** [comment]
@rachelmcr would you like to keep this issue open? I feel other tests are more important at the moment and UI tests for Stats would be more difficult because of how dynamic they have become after the Stats Refresh project.

**Comment by rachelmcr** [comment]
I would leave this up to the team to decide. The framework is there for anyone to develop more UI tests if they'll help mitigate risk/increase confidence. If there are tests that would be beneficial for a particular part of the app, but aren't needed for every PR merge, we could run them in a separate test plan with different timing.

I'm not sure I understand the concern about Stats being more dynamic — we mock network requests so the data itself will be consistent in the tests, and the UI behavior itself should be reliable/consistent. That said, this is certainly an old issue and if there isn't the need for UI tests at this point then I'm fine with closing the issue.

**Comment by designsimply** [comment]
> If there are tests that would be beneficial for a particular part of the app, but aren't needed for every PR merge, we could run them in a separate test plan with different timing.

I like this idea very much.
