### ISSUE TITLE
Improve caching of Stats information

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7185]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/236

At the moment when the users are offline they cannot see any stats information even if they just synced the information minutes ago.

An improved cache mechanism that allows the information to be saved and maybe some UI to inform the user the last time the information was synced.

**Comment by ScoutHarris** [comment]
Totally done in Stats Refresh!
