### ISSUE TITLE
Give VoiceOver clue when stats starts and finishes loading

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7186]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/235

**Comment by ScoutHarris** [comment]
Related: https://github.com/wordpress-mobile/WordPress-iOS/issues/7162

**Comment by ScoutHarris** [comment]
Closing in favor of #11995 .
