### ISSUE TITLE
Refactor table view controllers to reduce code duplication

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7188]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/223

The Storyboard architecture worked great for a single table view controller when the reinvention started for stats. Now that there are two additional view controllers which share cell designs there is a lot of duplicated code for selection, unfolding of nested cells, and rendering logic. Refactor the project so the code is reused for cell rendering (move configureCell\* code into a subclass for the cells). Cell designs will have to stay in the Storyboard for now.

There are also a ton of constant values that should be abstracted to actual constants from the cell subclasses that don't yet exist.

**Comment by ScoutHarris** [comment]
This will be addressed with the Stats Refresh [project](https://github.com/wordpress-mobile/WordPress-iOS/projects/13).
