### ISSUE TITLE
Add comment followers total to Comments section

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7192]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/155

![2015-02-04_10-19-32](https://cloud.githubusercontent.com/assets/373903/6044183/64422702-ac57-11e4-8c3a-d479eef39599.png)

**Comment by ScoutHarris** [comment]
New design coming with Stats Refresh [project](https://github.com/wordpress-mobile/WordPress-iOS/projects/13).
