### ISSUE TITLE
Navbar improvements

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7193]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/142

- Move the UISegmentedControl into the navbar
- Provide a scroll-up behavior that hides most of the navbar

**Comment by ScoutHarris** [comment]
This will be addressed with the Stats Refresh [project](https://github.com/wordpress-mobile/WordPress-iOS/projects/13).
