### ISSUE TITLE
Auto-fetch new data if time period has elapsed

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7195]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/111

Refetch the currently selected stats if a time period has elapsed. Perhaps ALWAYS refetch when viewDidAppear happens and let the new caching mechanism from #15 make it a quick update.

**Comment by ScoutHarris** [comment]
Addressed with Stats Refresh.
