### ISSUE TITLE
Animate bar value changes

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7199]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/77

When the values change behind the bar graph (new unit selected, stat type changed or possibly data refreshes due to an interval of time passing) animate the change.  This means the graph has to be refreshed differently than relying upon `UICollectionViewController`'s reload method (I believe).

**Comment by ScoutHarris** [comment]
Negated by Stats Refresh.
