### ISSUE TITLE
Action buttons for follow & spam

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7200]
Original issue: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/73

Web stats have buttons for following someone, marking a comment or follower as spam, etc.  Come up with the right solution for iOS for these scenarios (most likely an action sheet) and a hint that the actions exist.

**Comment by designsimply** [comment]
I checked web stats and did not see the option to mark a comment or follower as spam (maybe I've missed it?) but I did see the option to follow users listed in either the Followers or the Comments cards. ([36s](https://cloudup.com/cjVbnBZfSSj))

![comments-card-calypso-stats](https://user-images.githubusercontent.com/1119271/68964852-9e914c80-0797-11ea-88b3-7fc48e15f6f0.png)
<sup>Tested with Chrome 78.0.3904.97 on macOS 10.14.6.</sup>

**Comment by designsimply** [comment]
Closing as won't fix with an ask to create a new issue if this comes up again.
