### ISSUE TITLE
TabBar: Notification badge misplaced

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#7204]
At least one report of the notification badge being misplaced, this one courtesy of Beau. 
iPhone 7+ WPiOS v 7.6

![img_2670](https://cloud.githubusercontent.com/assets/1435271/26217901/bc99a8d6-3bce-11e7-845b-7eed3fdb9ef2.png)

**Comment by elibud** [comment]
I couldn't replicate this one, will have to keep trying.

**Comment by catehstn** [comment]
Is it time to just... have two images? ;)

**Comment by elibud** [comment]
@catehstn @maxme OK I give up, two images it is! That indicator just won't stay still.

@mattmiklic can we get the image `icon-tab-notifications` with a notification indicator on it? Let me know if you need me to send it over.

**Comment by mattmiklic** [comment]
> can we get the image icon-tab-notifications with a notification indicator on it? Let me know if you need me to send it over.

Sure thing. This should do the trick.

[icon-tab-notifications-new.pdf](https://github.com/wordpress-mobile/WordPress-iOS/files/1026828/icon-tab-notifications-new.pdf)

**Comment by elibud** [comment]
https://github.com/wordpress-mobile/WordPress-iOS/issues/7246
