### ISSUE TITLE
NUX: weird navbar and unrecoverable bug after log out crash

### ISSUE THREAD

**Issue by kurzee** [wordpress-mobile/WordPress-iOS#7207]
As mentioned previously and seen in https://github.com/wordpress-mobile/WordPress-iOS/issues/7206, _something_ is amiss with our NUX screens when that crash occurs.

The most important part, though, is that this cannot be recovered from by a user, without reinstalling the app.

@nheagy @aerych while vague and without steps to reproduce, can you dive into this a bit and see if we can't make sure something is not amiss here? To avoid users being locked out without reinstalling.

![img_3068](https://cloud.githubusercontent.com/assets/1873422/26224412/887cb80a-3c22-11e7-98a0-6f12e5d1f876.PNG)

**Comment by aerych** [comment]
Heya @kurzee.   So, the above screen shot shows what would appear consistently when launching the app following the crash, even after a force quit > relaunch?  Did I understand that correctly?

**Comment by kurzee** [comment]
>the above screen shot shows what would appear consistently when launching the app following the crash, even after a force quit > relaunch? Did I understand that correctly?

@aerych yep! However, I've been unable to reproduce it since.

**Comment by elibud** [comment]
This is probably good to close with the new flow, what do you think @aerych ?

**Comment by aerych** [comment]
Fo' sho'

**Comment by elibud** [comment]
Thank you, I hate having 500 issues or more 😝
