### ISSUE TITLE
Broken HTML after applying styles.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7208]
As reported by @rachelmcr:

> I saw some odd behavior while formatting text in the latest iOS beta.
> 
> First, I noticed that if select the “Paragraph” text style, it appears smaller than other text in the editor. I typed the two paragraphs in this screenshot and then applied the paragraph style to the second paragraph:
> 
> ![img_8421](https://cloud.githubusercontent.com/assets/1836005/26250229/ce9c74bc-3c7f-11e7-8ebc-177156288f07.png)
> 
> Then, I tried applying multiple styles to text. If I type the text, select it, and then apply styles, it works as expected. But if I select the styles and then type the text, every letter gets the HTML for those styles separately. Here’s what I saw in HTML view:
> 
> ![img_8422](https://cloud.githubusercontent.com/assets/1836005/26250266/dc152bfc-3c7f-11e7-98c6-7debdca1c0ca.png)

**Comment by jleandroperez** [comment]
@diegoreymendez can we close this one?. (Way TOO much has been changed since May 19th!)

**Comment by jleandroperez** [comment]
Closing this one. Fragmentation has been already adressed in [Beta 5](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/567), which made it's way into WPiOS 8.0
