### ISSUE TITLE
Review toolbar button sizes in Aztec.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7209]
The toolbar buttons sizes in Aztec may be too small.  Some users are reporting having to tap multiple times to make them activate.

As reported by @rachelmcr:

> As a side note, I also found that at times I had to tap the formatting buttons repeatedly to enable/disable them. This might just be me missing the button target areas, but it was very noticeable. (I’m using an iPhone 6.)

**Comment by jleandroperez** [comment]
Closed in Aztec [via this PR](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/486)
