### ISSUE TITLE
Upload Media button doesn't work with empty media library

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#7231]
### Expected behavior
To be able to upload media

### Actual behavior
There's no response

### Steps to reproduce the behavior
Open a site with no media and try to click the Upload Media button

![image](https://cloud.githubusercontent.com/assets/7233112/26418105/0744db9e-4089-11e7-8e40-e329da586765.png)

**Comment by kurzee** [comment]
This is internal only, coming in https://github.com/wordpress-mobile/WordPress-iOS/pull/7225
