### ISSUE TITLE
Unable to connect to Google+

### ISSUE THREAD

**Issue by hoverduck** [wordpress-mobile/WordPress-iOS#7235]
### Expected behavior
To be able to connect my blog to Google+

### Actual behavior
I receive a 403 OAuth2 error stating that webviews are not allowed to make connections

### Steps to reproduce the behavior
1) Navigate to site Sharing
2) Click Google+, Connect

![image](https://cloud.githubusercontent.com/assets/7233112/26422648/ab5a8d32-4098-11e7-8eaf-dbfab1c3e539.png)

**Comment by SiobhyB** [comment]
Also reported by a user in 3231460-t.
