### ISSUE TITLE
Replace remote switch for Helpshift

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7245]
Related: #7211

Helpshift used to be able to be turned on & off by a Mixpanel tweak using their A/B test feature. Consider going back to something like the simple feedback JSON pull from the .org servers originally used for the feedback UI in settings. See #337 for the original usage/implementation.

**Comment by ScoutHarris** [comment]
@astralbodies , @elibud - this shouldn't be needed anymore since we're replacing Helpshift with Zendesk so I'm closing this. Of course, if you disagree, feel free to re-open.
