### ISSUE TITLE
Detect and automatically remove duplicate tags

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#7252]
The app currently allows me to insert duplicate tags into the tag field. I don't seem to get any indicator that I've already entered a particular tag.

### Expected behavior
I expected the duplicate tag would get automatically removed. This would mimic how Calypso currently behaves. Here's a GIF of the Calypso flow:

![tags](https://cloud.githubusercontent.com/assets/7240478/26512605/89783d26-4224-11e7-948c-2790d70743db.gif)

### Actual behavior
I'm able to enter the same tag twice in a comma separated list.
![img_3992](https://cloud.githubusercontent.com/assets/7240478/26512655/be2f45dc-4224-11e7-90f2-d5c1e716aa1a.PNG)

### Steps to reproduce the behavior
In the tag field for a new post, type a tag and either select it from the existing list or enter a comment to start a new tag. Then, type the same tag over again.

##### Tested on iPhone 6, iOS 10.3.2, WPiOS 7.7.0.20170522

**Comment by catehstn** [comment]
@koke IMO this is not a launch blocker but I would like to see it fixed sooner rather than later. What do you think?

**Comment by koke** [comment]
I noticed that while testing, and even saw the calypso version, but to me it feels odd to have the tag disappear after you type it. What happened is less obvious if the duplicates aren't next to each other.
