### ISSUE TITLE
Deleting earlier tags on post is unpredictable

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#7254]
When adding tags to a post, if I tap the cursor up to a previous post and try to delete it, the app actually deletes all tags up until where my cursor currently is in the list. This is unpredictable because I expected it to delete the tag where my cursor was, not the tags leading up to my cursor.

### Steps to reproduce the behavior
1. Start a new post and in the post options, enter a list of tags on the post.
2. Tap the screen to move the cursor "back" in the list so it's just after an existing tag that you want to delete.
3. Press the delete key.

Here's an example where I have "Run, Burpee, Double Under, Ruck, Push-up, Wall Ball" in the list of tags. I put the cursor right after "Burpee," and I expected the delete key to delete that tag. Instead, it deletes "Double Under, Ruck, Push-up, Wall Ball".

![delete](https://cloud.githubusercontent.com/assets/7240478/26513027/9389139c-4226-11e7-9a43-367b3952af82.gif)

**Comment by catehstn** [comment]
@koke - is this a launch blocker for tag autocompletion?

**Comment by koke** [comment]
I'm not sure, but maybe. It doesn't look like it'd happen to often, but it seems pretty bad when it does

**Comment by elibud** [comment]
@jeremeylduvall can you please test this with the latest internal version of the app and let us know if it's ok now? Thanks

**Comment by jeremeylduvall** [comment]
@elibud yep! This seems much better to me. Thank you!
