### ISSUE TITLE
Add Optimize Images setting, matching WPAndroid

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7262]
We've [tried it](https://github.com/wordpress-mobile/WordPress-iOS/issues/1685) in a slightly different way in the past, but ended up [reverting](https://github.com/wordpress-mobile/WordPress-iOS/pull/2585). Let's now add an Optimize Images setting, but still allow users to take control over image size and quality, ala WPAndroid:

![optimize](https://cloud.githubusercontent.com/assets/4780/26602202/9c855e86-457a-11e7-9356-80887cdeb15a.png)

See also https://github.com/wordpress-mobile/WordPress-iOS/issues/4819 and https://github.com/wordpress-mobile/WordPress-iOS/issues/6671

**Comment by kwonye** [comment]
Closed with #7664
