### ISSUE TITLE
Editor / Media: Scroll position jumps when tapping an image

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7263]
### Expected behavior

When you tap an image in the editor, the scroll position shouldn't change. Or, the scroll position might change slightly to better center the selected image.

### Actual behavior

When you tap an image in the editor, the scroll position jumps so that the selected image is usually offscreen.

![editor-jumping](https://cloud.githubusercontent.com/assets/4780/26624738/ae5f5476-45e9-11e7-8551-165d7feba876.gif)

### Steps to reproduce the behavior

* Insert 3 or 4 images into the editor so that the content can scroll. 
* Tap an image.
* You should notice that the image is immediately scrolled offscreen.

This appears to affect both the hybrid editor and Aztec.

**Comment by bummytime** [comment]
Ref: #7792

**Comment by SergioEstevao** [comment]
We are no longer using the hybrid editor so closing  this and looking to #7792 instead.
