### ISSUE TITLE
Refactor EditPostViewController

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#7283]
One of the things I didn't address in #7271 is that the post filter switch is visible while the editor is being presented. This is because the post list presents EditPostViewController (without animation), which contains an empty PostPostViewController, then EditPostViewController animates the actual editor.

I don't think this UI hierarchy is ideal, and I want to explore having EditPostViewController replace it's child VC (with a custom transition) instead of presenting another VC.

**Comment by designsimply** [comment]
@koke @maxme is this issue still high priority? Does it still need work beyond what was done in #7299?

**Comment by koke** [comment]
I don’t think it’s high priority but the issue is still happening:

> I can see the filter changing from Published to Drafts while the Editor is being presented

**Comment by designsimply** [comment]
We decided to remove the site switcher in the editor in the WPiOS app because it's a source of issues for developers and a source of confusion for our users. See https://github.com/wordpress-mobile/WordPress-iOS/issues/14744.

<sup>(internal reference: p9ugOq-1fv-p2)</sup>
