### ISSUE TITLE
Media: images uploaded via Media in WPiOS look squished in the app not on the web

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#7338]
Steps to reproduce:

1. Go to Media > "+" in WPiOS 7.8.20170605 and upload any image (the problem is easy to spot if the image has something circle-shaped in it).
1. Go to Media > Add New in a desktop browser and upload the same image there.

<strong>Result:</strong> the image uploaded via the app looks squished in the app but looks fine on the web.

In this screenshot from the app, only the image uploaded <em>using</em> the app looks squished:

<img alt="img_1259" src="https://user-images.githubusercontent.com/1119271/26851971-d52721bc-4ac9-11e7-9ba2-d9c4765e1d6b.PNG" width="270" />
<sup>Seen at Media in WPiOS 7.8.20170605 on iPhone 6S, iOS 10.3.2.</sup>

Both images look fine when viewed on the web:

![screen shot 2017-06-06 at tue jun 6 11 19 17 am](https://user-images.githubusercontent.com/1119271/26851997-e951f72a-4ac9-11e7-9ca2-8620716b62c0.png)
<sup>Seen at https://wordpress.com/media/design5279.wordpress.com using Firefox 53.0.3 on Mac OS X 10.12.5.</sup>

Tested with iPhone 6S, iOS 10.3.2, WPiOS 7.8.0.20170605.

**Comment by kurzee** [comment]
Thanks @designsimply! We're working on this particular fix now actually, coming soon as a larger change.

**Comment by frosty** [comment]
This should be resolved now we've moved over to our new media exporting code.
