### ISSUE TITLE
Editor: Difficult to discern between HTML and Visual mode

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#7341]
In the new editor toolbar, it's difficult to distinguish when you're in HTML versus Visual mode. Here are two ways I distinguished this previously in WP iOS version 7.7:

- Font was different between the two editors
- `<>` tags were highlighted in the toolbar

<img width="1479" alt="screen shot 2017-06-06 at 21 08 39" src="https://user-images.githubusercontent.com/7240478/26860659-581f0274-4afc-11e7-9bff-90be73b96236.png">

With the new toolbar in WPiOS 7.8.0.20170605, it's pretty tricky to distinguish as the fonts are the same and the `<>` icon isn't highlighted. The only way to tell from what I can see is the shade of grey present in the other toolbar icons. It took me awhile to figure out which one I was using when I opened a new post.

<img width="1466" alt="screen shot 2017-06-06 at 21 11 35" src="https://user-images.githubusercontent.com/7240478/26860740-d30c6d32-4afc-11e7-8e9b-00b70246245a.png">

Highlighting the `<>` tags would make a big difference IMHO.

**Comment by diegoreymendez** [comment]
I agree.  Ping @iamthomasbishop.

**Comment by iamthomasbishop** [comment]
@jeremeylduvall Thanks for pointing this out! The screenshots you shared aren't using the latest editor (Aztec beta), and while this is _a little_ better in Aztec, there are a couple things that should be improved (in Aztec):

* The HTML button (when active) should be using the recently-changed active style (#663) which is HEX #0087BE.
* The HTML code itself should use a monospace font like Menlo or SF Mono (if available/free to use)
