### ISSUE TITLE
XCode 9 + Swift 4

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7343]
Do the necessary updates to:

1. Run our project on XCode 9
2. Migrate to Swift 4

**Comment by elibud** [comment]
https://github.com/wordpress-mobile/WordPress-iOS/pull/7905

**Comment by elibud** [comment]
@jleandroperez since you are tackling the Swift 4 migration I've added you to this task. Feel free to close it when that's done. Thanks

**Comment by jleandroperez** [comment]
Thank you Elisa, we'll get it done soon 🔥

**Comment by elibud** [comment]
You are amazing my friend @jleandroperez

**Comment by jleandroperez** [comment]
@elibud : hug :
