### ISSUE TITLE
Site Icon: Updating icon always creates new media item even if existing item is sized properly

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#7344]
### Expected behavior
If I try to change the site icon on my site through the app and I select the existing site icon to use, I expect that new icon to be used and no additional media items to get added to my library.

### Actual behavior
An additional media item gets added every time regardless of whether the existing item I select is already resized appropriately or not.

I understand that when I choose a blavatar, some resizing of the image might be necessary. Therefore, if I select a brand new image as the site icon, I expect a new version of the photo with the proper dimensions to get uploaded to my media library. However, once the image is appropriately sized, I don't expect the image to get duplicated.

### Steps to reproduce the behavior
1. Within the app, click on the site icon and select "Change Site Icon"
2. Select an existing item in your media library. The item should be set as your site icon.
3. Change the site icon again. You'll notice that a version of your current site icon has been added as the most recent version in your media library.
4. Select that newest, resized option in your media library. You're effectively setting the current icon as the site icon again.
5. Open your media library again. You'll see a duplicate of the resized image added to your media library.

It feels excessive that we're saving this additional version of the image if the image is already formatted correctly.

### GIF

http://cld.wthms.co/2evaIm (Too big for GitHub)

##### Tested on iPhone 6, iOS 10.3.2, WPiOS 7.8.0.20170605

**Comment by elibud** [comment]
Thanks for reporting this @jeremeylduvall it will be fixed on 7.9. 
As a nice side effect, after the fix is done, when selecting existing media updating the icon is much faster :)
