### ISSUE TITLE
Adding a site icon to a private site doesn’t work

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7345]
Reported by @rachelmcr 

Adding a site icon to a private site doesn’t work (tested on multiple sites). After adding the icon, the placeholder still appears (no errors in the app log that I saw). Completely closing the app and reopening it shows a grey square instead of the placeholder:

**Comment by elibud** [comment]
The image request is failing with a `403 Forbidden Error`, this is because we are trying to load the image with an unauthenticated request and the site is private. 
@koke looked into this as part of https://github.com/wordpress-mobile/WordPress-iOS/pull/6900 and the decision was wait for our upcoming network improvements. 
@astralbodies @bummytime is ☝️ kind of problem something we have specific plans to address?

**Comment by elibud** [comment]
@koke do you think it makes sense to disable site icon editing for private sites?

**Comment by bummytime** [comment]
Hiya @elibud! I think in general, this type of issue is something we would like to address however the time frame is a little up in the air atm.

**Comment by koke** [comment]
If we're certain it's going to fail, then maybe it's better to disable it, but we should make it work eventually.

Maybe I'm forgetting the details, but I'm now wondering if we can detect that the site is private and the site icon URL belongs to the site `mysite.files.wordpress.com`, then we should be able to set the image with a custom URLRequest that had the auth token? Kind of like what `PrivateSiteURLProtocol` but without needing a custom protocol
