### ISSUE TITLE
Changing orientation in media selector breaks layout

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#7349]
### Expected behavior
If I'm in portrait mode when I open the media selector then switch to landscape when selecting an image, I expect landscape mode to work correctly when I return to the app.

### Actual behavior
There's a dark square of the app that's unavailable when you return to the app.

### Steps to reproduce the behavior
1. Have your iPhone in portrait mode.
2. Click on Media -> + to select a media item to add.
3. Rotate your phone to landscape mode.
4. Press cancel to return to the app.

This is a bit more noticeable if you do it when trying to change the site icon (portrait mode -> change site icon -> switch to landscape while selecting media -> cancel to return to the app) since the dark square within the app isn't clickable.

### GIF
Sorry this GIF is a bit subpar! Licecap doesn't really handle rotating your phone while it records GIFs very well :)
![landscape](https://user-images.githubusercontent.com/7240478/26901667-d5d7d3de-4b93-11e7-8e5a-5b0f2200c4b5.gif)

**Comment by rachelmcr** [comment]
I tested this on my iPhone 6, iOS 10.3.3, WPiOS 8.2.0.20170802 and couldn't reproduce the issue as described. @jeremeylduvall is this still an issue for you?

**Comment by jeremeylduvall** [comment]
Working great for me now! I'll close the issue. Thanks for following up.
