### ISSUE TITLE
Enable Jetpack from the app

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7355]
To enable Jetpack for one of my self hosted sites I started by adding the site to the app, I then tapped on Stats->Install Jetpack, that installed the plugin but did not activate it. From here I had no choice but to go to wp-admin->Safari->enter my credentials, and here I was finally able to activate it.
That is 3 times I had to enter my password, and one time I had to enter my self-hosted site address. 

Can we do better than this? 
Is there any way we can activate Jetpack from within the app?

**Comment by elibud** [comment]
@koke this one will be tackled in your upcoming work right? I think it's OK to close.

**Comment by koke** [comment]
Yep, the new connect flow would take care of this
