### ISSUE TITLE
Duplicate self-hosted site after enabling Jetpack

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7356]
### Expected behavior
When I enable Jetpack on a self-hosted site previously added to the app I expect to see only one instance of the site in the app.

### Actual behavior
I get two instances of the site on the site list, one corresponding to the original self-hosted non JP site and one for the same site with JP enabled.

### Steps to reproduce the behavior
1. Add a self hosted site (non Jetpack) to the app.
2. Enable Jetpack on the site.
3. Refresh your site list, you will see two instances of the same site.

**Comment by aerych** [comment]
Related / dup of https://github.com/wordpress-mobile/WordPress-iOS/issues/7339

**Comment by elibud** [comment]
Related / dup of https://github.com/wordpress-mobile/WordPress-iOS/issues/5911

**Comment by koke** [comment]
Closing in favor of #5911
