### ISSUE TITLE
Hybrid editor crashing on iOS 11 beta

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#7373]
The hybrid editor is crashing in iOS 11 beta. Exception happens in `WebCore` with a stack trace like:

```Crashed: com.apple.main-thread
0  WebCore                        0x1a4c555b0 WebCore::Document::updateStyleIfNeeded() + 16
1  WebCore                        0x1a4c5f484 WebCore::FrameView::updateLayoutAndStyleIfNeededRecursive() + 64
2  WebCore                        0x1a4c5f484 WebCore::FrameView::updateLayoutAndStyleIfNeededRecursive() + 64
…
19 GraphicsServices               0x19860bf94 GSEventRunModal + 100
20 UIKit                          0x18ed9e86c UIApplicationMain + 208
21 WordPress                      0x10224db78 main (main.m:11)
```

I spent time trying to narrow down the cause, but was unable to get very far. Let's hope this is fixed in a future release of iOS 11. For now, I've logged an issue with Apple's bug reporter.

**Comment by nheagy** [comment]
Created radar #32770322 for anyone able to view those ;)

**Comment by jleandroperez** [comment]
Closing this one, since the Hybrid was recently removed.

Thanks Nate!
