### ISSUE TITLE
Post list: Posts published from app appear different than those published elsewhere

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#7379]
### Expected behavior
I expected that the posts would appear similar regardless of where they were published from.

### Actual behavior
I noticed that line breaks do not appear correctly in the post list when the posts are published from the app. They do appear correct for posts published elsewhere (I tried a desktop browser).

### Steps to reproduce the behavior
1. Create a test post with content on multiple lines with extra lines in between the text.
2. Publish the post.
3. View the post in the post list.
4. Create a similar post via a desktop browser spanning multiple lines.
5. View both posts in the post list in the app and notice the disparity.

### Screenshots
In this screenshot, you can see the second post with no spacing shown in the post list (compared to the actual post on the right). The top post, on the other hand, was published from a desktop.

<img width="1480" alt="screen shot 2017-06-15 at 09 48 21" src="https://user-images.githubusercontent.com/7240478/27189836-cd1d9266-51af-11e7-91cc-42387eba236a.png">

Potentially related: #7109, #6944

**Comment by jleandroperez** [comment]
Closing this one since it's been addressed via #7668 (shipped in WPiOS 8.3).

Thanks Jeremey!!
