### ISSUE TITLE
Comment likes don't stick on Jetpack sites

### ISSUE THREAD

**Issue by maxme** [wordpress-mobile/WordPress-iOS#7389]
I'm pretty sure it's an API issue (missing like status from the network response).

Steps to repro:
1. Pick Jetpack site
2. Go to the comments screen
3. Open a comment detail
4. Like it
5. Back to the comments screen: refresh comments
6. Open previous comment, notice your like is not there anymore 😿 

Demo video of the issue: https://cloudup.com/ciGWpCCQFxN

cc @elibud

**Comment by maxme** [comment]
note: same issue in wpandroid

**Comment by rachelmcr** [comment]
Comment likes are not yet a Jetpack feature: https://github.com/Automattic/jetpack/issues/3224

**Comment by elibud** [comment]
Not working after installing JP 5.1

**Comment by elibud** [comment]
Update: the likes are being recorded (I can see them on wp-admin) but the `v1.1/sites/SITE_ID/comments` endpoint is not returning the field `i_like` for JP sites.
