### ISSUE TITLE
Add settings option to edit Gravatar and Site Icon

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7404]
Currently tapping on your gravatar or your site icon is the only way to edit them. We want to add a more explicit option.

From @mattmiklic: a discrete option in profile settings / site settings for profile photo and site icon is probably the way to go.

cc: @tonyr59h

**Comment by tonyr59h** [comment]
Some mockups from @mattmiklic:

![](https://cldup.com/QXLy7s_VGy.png)

**Comment by mindgraffiti** [comment]
Reopening - site settings icon feature not yet implemented. (Me > My Profile photo feature is done.)

**Comment by designsimply** [comment]
Tested with WP Internal 12.0.0.20190320 on iPhone 6S iOS 12.1.4 and found that Site Icon is still missing from the top of the Settings screen as indicated in the designs provided.

<img src="https://user-images.githubusercontent.com/1119271/54794164-a51cf380-4c0b-11e9-8b64-b1135b8f686a.PNG" width="270" alt="IMG_2172">
<sup>WordPress.com Free, `madefortesting190318.wordpress.com`</sup>

However, I did noticed that I could change the Site Icon via the top of the Site Switcher screen on a WordPress.com or Jetpack site.

<img src="https://user-images.githubusercontent.com/1119271/54794235-09d84e00-4c0c-11e9-86cb-283246c37068.PNG" width="270" alt="IMG_2173">
<sup>WordPress.com Free, `madefortesting190318.wordpress.com`</sup>

I couldn't change the Site Icon from the top of the Site Switcher screen for a self-hosted site though.

<img src="https://user-images.githubusercontent.com/1119271/54794278-3c824680-4c0c-11e9-9146-a122b1c8f1d9.PNG" width="270" alt="IMG_2171">
<sup>Self-hosted WordPress 5.1.1, `tasteless-petrel.jurassic.ninja`</sup>

**Comment by designsimply** [comment]
During the Information Architecture project, the site icon was added to the My Site (blog details) screen very prominently at the top. See designs at https://github.com/wordpress-mobile/WordPress-iOS/pull/13373.

<sup>(internal reference/master thread: pauD4L-8W-p2)</sup>

Current screenshots for reference:

My Site|Site Settings
---|---
<img src="https://user-images.githubusercontent.com/1119271/91599281-450f9e00-e923-11ea-801f-1f1ca7a7e7ba.png" width="270" alt="IMG_3829">|<img src="https://user-images.githubusercontent.com/1119271/91599278-43de7100-e923-11ea-8d14-cda8a1540e0b.png" width="270" alt="IMG_3830">

@mattmiklic I think the "Change Site Icon" option on the My Site screen is good enough and we don't also need to add it to the Site Settings screen. If you agree, could you close this issue with a note?

**Comment by kean** [comment]
This is now taken care of by the [Gravatar](https://github.com/Automattic/Gravatar-SDK-iOS) framework.
