### ISSUE TITLE
Notifications: Labels are cut-off not displaying in full 

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-iOS#7451]
### Expected behavior

To see notifications labels eg. "OLDER THAN A MONTH" in full

### Actual behavior

Labels are cut-off/not displaying vertically in full

### Steps to reproduce the behavior

Open WPiOS and open notifications and scroll until you see a section label

##### Tested on [device], iOS [version], WPiOS [version]

Apple iPhone 7+ iOS 10.3.2 WPiOS 7.9.0.20170627 (also in App Store version)

![label - 1](https://user-images.githubusercontent.com/128826/27616887-3e3c6f12-5bf6-11e7-90fb-032d1819cff8.jpg)

**Comment by elibud** [comment]
I was able to replicate, this happens when Accessibility->Larger Text is moved to the minimum.
