### ISSUE TITLE
Login prematurely allows non-valid emails to click "next"

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#7453]
When typing out my email, I noticed the "next" button was enabled before my email was valid. Shouldn't we wait until it's valid? That's what we do in the current version of login.

Clicking "next" fails (obviously)

![simulator screen shot jun 26 2017 11 52 54 am](https://user-images.githubusercontent.com/1158819/27628072-3cebc5a2-5bee-11e7-93bf-414e578e3120.png)
![simulator screen shot jun 26 2017 11 53 06 am](https://user-images.githubusercontent.com/1158819/27628073-3d12ea92-5bee-11e7-8086-13cfa2571753.png)

**Comment by kwonye** [comment]
@aerych just assigning you since you're leading this. Feel free to send to anyone else 👍

**Comment by aerych** [comment]
I think we can tweak our email check based on the `is_email` check in `wp-includes/formatting.php`. Since this is client side validation I think checking for length, @ sign, and allowed characters in the local, and domain portions of the address should be sufficient for most cases.
