### ISSUE TITLE
Jetpack Plugin Support

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7471]
We want to add Jetpack Plugin Support to the apps with the following functionality:

- Browse Plugins
- Activate/Deactivate a Plugin
- Turn on/off autoupdate for a Plugin
- Update a Plugin

**Comment by elibud** [comment]
@koke assigning this one over since this is what you are working on, right?

**Comment by ithinker143** [comment]
[ApplicationShortcutsUsingUIApplicationShortcutItem.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/1584774/ApplicationShortcutsUsingUIApplicationShortcutItem.zip)
