### ISSUE TITLE
Jetpack Settings: Disconnect

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7473]
### Expected behavior
To be able to disconnect Jetpack from a self hosted site.

### Actual behavior
There's no option to do that in the app.

**Comment by koke** [comment]
Related: #7261

**Comment by elibud** [comment]
@koke @aerych Do you know if there is a way for us to know if a site was added through a WP.com account or via self-hosted credential? Thx

**Comment by aerych** [comment]
Well... even if the site was originally added as self-hosted, once wpcom credentials are provided to connect to Jetpack we more or less trade the XMLRPC version of the site for the REST API version.  Not sure how useful it will be to know which way a site was added in this case.

Of course we can still identify Jetpack sites via `Blog.jetpack`

Not sure if this is helpful 😬

**Comment by elibud** [comment]
Yes it is, thanks @aerych, it's a very good point. So once you disconnect the site will be gone from the app, we just have to provide a really nice and big warning @mattmiklic

**Comment by koke** [comment]
Not sure if it's the right check, but if it was manually added it'll have the username/password set

**Comment by aerych** [comment]
Oh you're right.  I thought we were clearing the credentials but I just tested and confirmed they are retained after making the connection. 

We probably *should* clear them 🤔

**Comment by elibud** [comment]
Initial development only implementation merged, we will wait for a full feature design to implement the user facing one.
cc: @mattmiklic

**Comment by elibud** [comment]
I am closing this one as we have not received any user requests for the feature.
