### ISSUE TITLE
Landing page says "Create a site" instead of "Create account"

### ISSUE THREAD

**Issue by vikramvi** [wordpress-mobile/WordPress-iOS#7475]
### Expected behavior
1. This issue is found while comparing against Android App
2. The landing page bottom link should be "Create account" as tapping on it takes user to Account Creation page and not site creation

### Actual behavior
1. Currently button name is "Create a site" which is not correct

**Comment by rachelmcr** [comment]
Thanks for the report! I'm closing this issue as version 8.1 introduced a new login flow (with a new landing page). This new login flow includes the button "Create a WordPress site" for signup, which will also be introduced on Android.
