### ISSUE TITLE
iOS app does not show true state of blogs

### ISSUE THREAD

**Issue by abunur** [wordpress-mobile/WordPress-iOS#7486]
### Expected behavior
iOS app should show the same state as seen in a web browser.  For example, if a blog has ten draft pages, these should all appear in the iOS app.

### Actual behavior
iOS app is showing "you don't have any posts yet"

### Steps to reproduce the behavior
Create several draft Pages on a Wordpress site.  Attempt to view via the iOS app.

##### Tested on [device], iOS [version], WPiOS [version]
iPad Pro (9.7 Inch), iOS 11 Beta 2, current store release of WPiOS (4.5)
![img_1635](https://user-images.githubusercontent.com/4803881/27765864-1928854c-5e8c-11e7-8ffb-ab0ebcd02e9b.PNG)
![img_1634](https://user-images.githubusercontent.com/4803881/27765865-192cc436-5e8c-11e7-9f6a-564ec0db736b.PNG)

Note after using WPiOS for a short time on iOS 11 Beta 2 the app crashed.  App crash report submitted.

**Comment by abunur** [comment]
Also it's telling me there is no media on my blog (when there is plenty), and if I try to upload a media item from my phone it throws an error.

**Comment by rachelmcr** [comment]
@abunur This can happen if the app is unable to connect with your site for some reason. As a first step, you can use our XML-RPC validator to check your site for errors:

http://xmlrpc.eritreo.it/

If that doesn't help you resolve the issue, please go to the Me > Help & Support > Contact us in the app to get in touch with our support team directly for assistance.
