### ISSUE TITLE
Aztec: Uploading media on a slow connection offers a bad UX.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7505]
As reported by one of our testers:

> Slow Connection = Retrying uploads. This is the number 1 issue that discourages me from using the app. On a desktop, when using wp-admin, I grab all my photos and upload them at once. My home internet upload speed is usually just shy of 1 mbps. On my laptop, using wp-admin, they just slowing work away until they are all uploaded. On the app, I pick the photos I want in my post and click upload, and most of them error out, giving me the retry option. Is there any ability to improve this experience for so many of us without fast upload capability? Could they automatically keep trying? Longer timeout?

We need to find ways to make this experience more enjoyable.

Feel free to discuss in this issue.

**Comment by SergioEstevao** [comment]
We could implement a three retry policy.

But to avoid bandwidth waste and costs we should probably should check for the following:

- is the connection being made on Wifi or cellular network (3g 4g)
- what kind of error we are getting ( if it's timeout it's ok to retry, but if it's offline or server error maybe not).

**Comment by diegoreymendez** [comment]
@SergioEstevao - Three observations from my end:

- Three retries sounds standard and good good.
- Also what about checking connectivity, and retrying automatically when we get the connectivity back?
- Lastly, I think it'd be nice to have UI support to "Retry All".
