### ISSUE TITLE
Notification for setting up Business 1 on 1 does not have a link to be be able to schedule the chat

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#7511]
### Expected behavior
When a user purchases a business subscription and then opens the app, they receive a notification to alert them that they can setup a "30 minute orientation" with us.  From that notification they should be able to click on a link to schedule the chat

### Actual behavior
The notification does not have a link for the user to click on, so they are invited to schedule a chat but not told how.

### Steps to reproduce the behavior
1. upgrade to business
2. Go to notifications and click on the "let us personally help you ....."
3. once looking at the notification there is no where else to go.

##### Tested on [device], iOS [version], WPiOS [version]
iPad mini 3
iOS 10.3.1
WPiOS 7.8.1

![img_0039](https://user-images.githubusercontent.com/22015538/27934235-197b5536-6262-11e7-823c-e9aed799a262.PNG)

**Comment by jleandroperez** [comment]
Closed via #8088. Thanks sir!
