### ISSUE TITLE
Aztec announcement title should wrap multiple lines

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7513]
### Expected behavior

The title on the Aztec announcement UI should wrap multiple lines.

### Actual behavior

The title gets truncated if the text is too large (small device maybe, or larger dynamic type).

![img_1149](https://user-images.githubusercontent.com/4780/27952512-6d1f653a-6300-11e7-839f-9db50a13a77c.PNG)

**Comment by diegoreymendez** [comment]
Remeber to tag as "aztec".
