### ISSUE TITLE
Title field height inconsistency moving from portrait to landscape

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#7515]
This is a small bug. When you have a long title field that wraps onto two lines in portrait mode then rotate to landscape, there will be an extra line in the title field that's unnecessary. If you type any key, it will get removed.

### Expected behavior
I expected the number of lines to automatically adapt to the new screen width.

### Actual behavior
An extra line still appeared that wasn't necessary.

### Steps to reproduce the behavior
1. Create a new post in Portrait mode.
2. Type "Testing out a long title here" in the title field. It should wrap to two lines in portrait mode.
3. Rotate to landscape mode. The title should now fit on one line, but there will be an extra line.
4. Press any key on your keyboard. Title field will contract to one line.

![img_4093](https://user-images.githubusercontent.com/7240478/27962366-f1ae4a4e-62ee-11e7-9748-f8c8fba000e1.PNG)
![img_4094](https://user-images.githubusercontent.com/7240478/27962365-f1ae1bc8-62ee-11e7-8cfd-77db67958be7.PNG)

**Comment by elibud** [comment]
@diegoreymendez do you want to move this over to Aztec?

**Comment by diegoreymendez** [comment]
@elibud - It's actually not necessary, as the title field is almost entirely managed by WPiOS.  I'm labelling this as "aztec" though.

Thanks for the ping, though.

**Comment by diegoreymendez** [comment]
Fixed.  Will be available in WPiOS 8.0.
