### ISSUE TITLE
Possible to upload videos on a Personal plan

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#7516]
### Expected behavior
On a Personal plan site, I shouldn't be able to upload videos since VideoPress support starts on Premium+. Here's the error I receive on a desktop:

<img width="500" alt="screen shot 2017-07-07 at 8 36 08 am" src="https://user-images.githubusercontent.com/7240478/27962521-68d3fad8-62ef-11e7-989c-2f99b9664bdb.png">

I expected to see the same error on mobile.

### Actual behavior
On the mobile app though, I can record and upload a video to a Personal plan site.

### Steps to reproduce the behavior
1. Start a new post on a Personal plan site.
2. Click on the + icon to add media.
3. Click on the camera icon to upload a new photo/video.
4. Choose video. Record a video and upload it to the post. You won't receive an error.

##### Tested on iPhone 6, iOS 10.3.2, WPiOS 8.0

**Comment by rachelmcr** [comment]
This is expected behavior. Videos can be uploaded to any site, regardless of plan, through the app.
