### ISSUE TITLE
Add support for sticky posts

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7525]
Spawned by [this issue](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/592).

We need to add support for sticky posts in our posts list.

**Comment by sarahblackstock** [comment]
Request for sticky setting in support. 
internal ref: #220343-h

**Comment by sarahblackstock** [comment]
Would love to see this added. In support, outside of the standard request from a user looking how to sticky a post, we encounter people who are confused when they choose a new theme that starts out with a sticky post and they can't figure out how to change/remove it in the app. ("Why won't my new post go to the top?" is the basic question around this problem. It's not clear what is happening if you're new to WP/the theme.)

**Comment by sarahblackstock** [comment]
New blogger using the app confused by a theme that came with a sticky post and unable to find a way to un-sticky it (or even realize what was going on without help from support, since there are no sticky settings showing in the app). 

> When I go onto the website it’s not in the order I posted it. 

internal ref: #252775-h

**Comment by rachelmcr** [comment]
Closing since sticky support was added in https://github.com/wordpress-mobile/WordPress-iOS/pull/10077 (released in 10.9).
