### ISSUE TITLE
Remove failed media when switching to HTML

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#7528]
### Expected behavior

When switching to HTML mode in Aztec, if the post has failed media the user should get an alert that the media will be removed.

### Actual behavior

The user is allowed to switch to HTML mode when failed media is on the post. This converts the media to empty video tags, that could be saved to the post.

### Steps to reproduce the behavior

- Activate Aztec
- Start a new post
- Add a media object
- Make it fail the upload process (turn network off)
- Switch to HTML
- Check that the media element shows with empty source.

##### Tested on iPhone 7, iOS 10, WPiOS 8.0

**Comment by diegoreymendez** [comment]
Fixed.
