### ISSUE TITLE
Uploaded images missing attributes

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7537]
Originally reported by @elibud in https://github.com/wordpress-mobile/AztecEditor-iOS/issues/603

### Expected behavior
When I create a post and upload an image to it, I expect that image to be displayed on the post list and on reader, both on the apps and on the web.

### Actual behavior
The post doesn't display an image in the following places:
- Reader iOS
- Post List iOS
- Post List Calypso

The reason behind this seems to be that the uploaded image is missing the `width` attribute. As a reference here's how an image uploaded via the Hybrid editor looks like:
`<a href="https://elibudandpets.files.wordpress.com/2017/07/img_6963.jpg"><img class="alignnone size-full wp-image-169" src="https://elibudandpets.files.wordpress.com/2017/07/img_6963.jpg" alt="" width="1600" height="1070" /></a>`
And here's one uploaded with Aztec:
`<img src="https://elibudandpets.files.wordpress.com/2017/07/img_6966.jpg">`

### Steps to reproduce the behavior
Create a new post, upload an image, check the post on Reader and the site's Post List.

##### Tested on IPhone 7, iOS 10.3, Aztec beta 6

**Comment by elibud** [comment]
@SergioEstevao This is good to close, right?

**Comment by SergioEstevao** [comment]
Yes

Enviado do meu iPhone

No dia 31 de jul de 2017, às 12:40, Elisa Budelli <notifications@github.com> escreveu:
