### ISSUE TITLE
Design adjustments for login prologue

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#7547]
Comparison of current implementation of prologue to design:

<img width="1229" alt="screen shot 2017-07-13 at 1 14 52 pm" src="https://user-images.githubusercontent.com/1396552/28178698-59d4192c-67cd-11e7-8bee-8f69b6ef5b7c.png">

Notes:

- Let's make the left/right margin on the text 10% of the screen width -- this translates to ~41px on the Plus-sized screens shown here. This should reduce to 32px on the SE-sized screens, I think.
- Text should be `Title 3` in size; medium weight.
- Reduce the animation height slightly, to add more whitespace above/below the text.
- Add a shadow to the background behind the buttons.
- Can we set the status bar color to white? Or is black/white chosen automatically by the system based on background color?
- Set the animations to only play once each time they appear.

I've updated the Stats and Notifications animations so that they look right when they don't repeat.

Stats: https://cldup.com/PltMKRa9hz.json
Notifications: https://cldup.com/OE-Exjq1Gm.json

**Comment by nheagy** [comment]
Adding some earlier design feedback for reference. Thanks @mattmiklic!

<img width="1201" alt="email" src="https://user-images.githubusercontent.com/517257/28180365-25df99f8-67c2-11e7-8979-f3df8a816714.png">
<img width="1284" alt="passwordinstead" src="https://user-images.githubusercontent.com/517257/28180453-6266b1b8-67c2-11e7-9ce6-82d0871ea1f9.png">
