### ISSUE TITLE
Check width of title in fancy alert view

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#7548]
In the fancy alert view that displays the new site address help screen, the title is wrapping to two lines on my iPhone 7 Plus, even when there's sufficient room for it to display on one line. Check that the width/padding/margin matches that of the body text below.

![img_2653](https://user-images.githubusercontent.com/1396552/28180260-981cd5e8-67d2-11e7-8ba1-7864bb80407d.PNG)

**Comment by nheagy** [comment]
Ok, I found two problems with this:
1. Seems like the merge didn't work out on `develop`, Xcode complains about an internal inconsistency and opens the storyboard without the constraint I had added
2. My fix appears to suck anyway, as it breaks the Aztec alert.

I'm going on vacation, maybe @frosty wants to tackle this?
