### ISSUE TITLE
Design and implement a browsing/discovery experience

### ISSUE THREAD

**Issue by mikejohnstn** [wordpress-mobile/WordPress-iOS#755]
What happens when you tap a tag? And then tap another tag from within a tag? How do you go back and forth? What about tapping a tag from within the detail view? How do you follow and unfollow tags? How can you discover new tags to follow besides seeing them in your post list?

These are some of the questions that need answering, and then implementing. UX design could start at any time @hugobaeta.

**Comment by aerych** [comment]
Closing. This is superseded by more recent wpcom design decisions.
