### ISSUE TITLE
Notification navbar gets hidden sometimes

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#7553]
Unfortunately there's no consistent repro step, but one possible situation may be the user is in the reader with no nav bar (it collapses to full screen mode when scrolling down) and the user closes the app and opens a notification.

<img width="813" alt="screen shot 2017-07-13 at 6 26 09 pm" src="https://user-images.githubusercontent.com/1158819/28194383-c48f7344-67f8-11e7-959d-e7546b396b88.png">

**Comment by simonwheatley** [comment]
Perhaps related: https://github.com/wordpress-mobile/WordPress-iOS/issues/6976

**Comment by kwonye** [comment]
Closing this issue and re-opened #6976 as that has more history.
