### ISSUE TITLE
New Login: Password box not cleared if username changed

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7557]
### Expected behavior
If I enter the wrong (but a valid) username (actually e-mail address), try to log in, fails, and go back to change the address the previously entered password should be empty.

### Actual behavior
In this scenario the password persists - but we should probably wipe the password and force the user to re-enter otherwise they might think it got auto-filled.

### Steps to reproduce the behavior
1. Start with the app in a logged-out state.
2. Enter an e-mail address for a valid account.
3. Skip the magic link step.
4. Enter an incorrect password.
5. Go back and edit the e-mail address to another valid account.
6. Skip the magic link step.
7. See the previous password still populated in the password field.

cc: @nheagy

**Comment by nheagy** [comment]
I think you're right, it should be fixed.

We'll have to take some care with the implementation: we want to wipe the password on the email entry screen, when the email is changed. We _don't_ want to wipe it when the password screen appears, as that screen is sometimes shown after using 1password or safari to use saved credentials.

**Comment by aerych** [comment]
We could probably just reset (relevant) login fields when a vc appears.
