### ISSUE TITLE
RTL support on Aztec

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7560]
Currently it doesn't look like the Aztec editor is supporting RTL languages. 
As a reference see the Hybrid Editor vs Aztec:

![hybrid](https://user-images.githubusercontent.com/5558824/28222042-2311a20e-689c-11e7-88d8-f1463e911735.png)|![aztec](https://user-images.githubusercontent.com/5558824/28222040-22dd09a4-689c-11e7-97d7-71c398d73d7a.png)

**Comment by SergioEstevao** [comment]
Solved in 8.1
