### ISSUE TITLE
Reader: Follow buttons appear in the logged out reader

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#7579]
Sign into the app with a self-hosted account and be signed out of wpcom. 
Visit the reader and view a tag list, I looked at sports-gaming.
Notice that the post cards show a follow button.
Tapping the button shows an error that there was a problem following the site. 
View a detail and tap the menu button. 
Notice that there is an option to follow the site. 

Probably the following feature should not be presented to a signed out user.

**Comment by catehstn** [comment]
I think we want the follow to prompt the sign in, and if that is successful follow the site.

My understanding is this is the plan for the web.

**Comment by ChrissiePollock** [comment]
This is brought up in the internal issue #206206-h
