### ISSUE TITLE
Reader: Site header layout is off a bit.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#7580]
Reader > Followed Sites > Manage > ma.tt 
Notice that the site info view (tagline + follower count) has too little top padding and too much bottom padding.
![simulator screen shot jul 18 2017 2 00 06 pm](https://user-images.githubusercontent.com/1435271/28334801-e3e1b60e-6bc1-11e7-8b56-b8f2de949f92.png)

**Comment by elibud** [comment]
Closing in favor of: https://github.com/wordpress-mobile/WordPress-iOS/issues/8855
