### ISSUE TITLE
Improve RTL in auth flow

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#7584]
I was testing RTL for #7575 and noticed several things on login that could be improved for RTL languages (tested with Hebrew as the simulator language).

The animations show left aligned text and stats from left to right.

<img src="https://user-images.githubusercontent.com/8739/28424013-dfa89be6-6d6c-11e7-80a5-fc0d836c1ac9.png" width="270" alt="simulator screen shot 20 jul 2017 16 55 07"> <img src="https://user-images.githubusercontent.com/8739/28424016-dff3bbf8-6d6c-11e7-81ff-60434d0557bb.png" width="270" alt="simulator screen shot 20 jul 2017 16 55 16"> <img src="https://user-images.githubusercontent.com/8739/28424014-dfd72f4c-6d6c-11e7-881b-1ba58a70eb9e.png" width="270" alt="simulator screen shot 20 jul 2017 16 55 21"> <img src="https://user-images.githubusercontent.com/8739/28424015-dfebac88-6d6c-11e7-95a1-76e585b3f98f.png" width="270" alt="simulator screen shot 20 jul 2017 16 55 27">

The email address field defaults to the Hebrew keyboard. I'm not sure if that's right.

<img src="https://user-images.githubusercontent.com/8739/28424052-f174be2c-6d6c-11e7-9f52-1d7e386e3a21.png" width="270" alt="simulator screen shot 20 jul 2017 16 56 12">

If email/password are restricted to latin characters, the email label/icon should be LTR here:

<img src="https://user-images.githubusercontent.com/8739/28424126-1e917eea-6d6d-11e7-804b-cad4c662d01b.png" width="270" alt="simulator screen shot 20 jul 2017 16 56 38">

In the self hosted login, both the username and password fields have the proper direction and keyboard:

<img src="https://user-images.githubusercontent.com/8739/28424160-33d695e2-6d6d-11e7-8eb2-0e4a6abfb4d3.png" width="270" alt="simulator screen shot 20 jul 2017 16 57 51">

**Comment by designsimply** [comment]
RTL in the pre-login screens now looks correct to me.

<img src="https://user-images.githubusercontent.com/1119271/70014691-9c214780-1538-11ea-9196-a059239f1a3c.PNG" width="270" alt="IMG_3149">

> The email address field defaults to the Hebrew keyboard. I'm not sure if that's right.

Is it possible this is a function of which keyboard you last selected, and not a matter of which one the app forces as default? In my test, it seemed to be whatever the most recently selected keyboard was each time I went back to the main login screen and tapped Log In again.

Other notes: the spacing between the 1Password icon and the text is too small and should the icon also be LTR if the keyboard defaults to LTR for that field?

<img src="https://user-images.githubusercontent.com/1119271/70014937-3b463f00-1539-11ea-922a-928d7aa2e48c.PNG" width="270" alt="IMG_3152">

> If email/password are restricted to latin characters, the email label/icon should be LTR.

The email and password are both RTL. Should the email be LTR but the password remain RTL?

<img src="https://user-images.githubusercontent.com/1119271/70015253-0be40200-153a-11ea-9d01-ea423b423a49.PNG" width="270" alt="IMG_3151">

**Comment by mindgraffiti** [comment]
Added to UL&S as the new screens need verified for RTL as well.

**Comment by mindgraffiti** [comment]
Here are the pieces that need attention in the Unified Login & Signup UI:

| `TextLinkButtonTableViewCell` |  Login Epilogue: display name + username |
| --- | --- |
| Tested on 15.7 | with Arabic localization |
| <a href="https://user-images.githubusercontent.com/1062444/92946748-ac961500-f41c-11ea-9898-d10149d29f70.png"><img src="https://user-images.githubusercontent.com/1062444/92946748-ac961500-f41c-11ea-9898-d10149d29f70.png" width="350" /></a> | <a href="https://user-images.githubusercontent.com/1062444/92946474-55904000-f41c-11ea-8ef5-bf4dc5e451e6.png"><img src="https://user-images.githubusercontent.com/1062444/92946474-55904000-f41c-11ea-8ef5-bf4dc5e451e6.png" width="350" /></a> |

**Comment by mindgraffiti** [comment]
Fixed in #464 and https://github.com/wordpress-mobile/WordPress-iOS/pull/14921
