### ISSUE TITLE
Post-Post screen appears after saving post as pending review

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#7600]
### Expected behavior

I expect when I save a post as "pending review" the editor will close and show my list of draft posts (like when I close a saved draft)

### Actual behavior

When I save a post as "pending review" I get a spinner that says "Publishing..." and then the post-post screen telling me my post was "Published just now on" the site. This is anxiety-inducing when I don't mean to publish the post, and misleading if I forgot that I had set the post to pending review (or if I'm a contributor and don't realize my post isn't published).

### Steps to reproduce the behavior

1. On a site where you are a Contributor, start a new post. (Contributors can't publish their posts; they have to be saved pending review for an admin to publish.)
2. Add content and tap "Publish."

Result: The post-post screen appears, but the post is not published.

Also:

1. Start a new post on any site.
2. Open the post options.
3. Set the Status to Pending review.
4. Add content and tap "Publish."

Same results as above.

##### Tested on iPhone 6, iOS 10.3.3, WPiOS 8.1.20170721

Originally reported during pre-launch testing, but it looks like this didn't get fixed or logged at that point. (Internal ref: p77Llu-2Al-p2) Also reported by a user: https://twitter.com/claireyjenna/status/889408195583770625

**Comment by SiobhyB** [comment]
This also came up in 278467-h and I can confirm there's still a problem in my testing. 

As a Contributor, after a tap the option to "Submit for Review" in the app, it doesn't actually get set a "Pending Review". Instead, you're given a prompt to publish the post and it's saved as a draft. You have to then tap the "Publish" option to set it as "Pending Review", which is not intuitive.

**Comment by frosty** [comment]
Related to this, I think the confusing text in the confirmation prompt should be fixed by https://github.com/wordpress-mobile/WordPress-iOS/pull/9239

**Comment by SiobhyB** [comment]
Issue in Android too: https://github.com/wordpress-mobile/WordPress-Android/issues/7698

**Comment by rachelmcr** [comment]
I can confirm that the original issue is resolved. I've opened a new issue for the problem mentioned in https://github.com/wordpress-mobile/WordPress-iOS/issues/7600#issuecomment-385938355 with posts not getting set as "pending review."
