### ISSUE TITLE
Aztec: Toolbar Covers Text in Landscape View

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#7605]
### Expected behavior
Users should be able to scroll to the main TextView's Area

### Actual behavior
It's impossible to move past the Title Field. See pictures below.

![horizontal-no-keypad](https://user-images.githubusercontent.com/1195260/28574989-f5f70448-7125-11e7-92fa-6d42e8b499f6.png)

![horizontal-with-keypad](https://user-images.githubusercontent.com/1195260/28574996-fe253ca2-7125-11e7-90ea-07cf36890aab.png)

### Steps to reproduce the behavior
1. Launch Aztec
2. Open an existing post / edit a new one
3. Attempt to edit the post's body

As a result, it won't be possible to edit the main area.

**Comment by elibud** [comment]
@jleandroperez @diegoreymendez this doesn't seem to be an issue with the latest version of the app, I'm closing it, please reopen if appropriate.
