### ISSUE TITLE
Posts List: certain posts with an image don't show the image

### ISSUE THREAD

**Issue by lancewillett** [wordpress-mobile/WordPress-iOS#7612]
### Expected behavior
When viewing my posts list I'd expect to see a photo in the post preview card when I added a photo to that post.

### Actual behavior
Just the title shows, no image. This seems to be related to posts made with the native app Aztec editor only — posts published with visual editor, or Calypso web editor appear as expected.

![img_0050](https://user-images.githubusercontent.com/66797/28632566-dbc8f5ca-71e5-11e7-8997-f6fba273a663.PNG)

Tree, Cabury All Day, Capp Art by Liam are photo posts I made via my Android phone with Aztec editor.

### Steps to reproduce the behavior
1. My Sites, click Blog Posts for a site.
2. View the posts list for a post you've published with an image, via Aztec editors.

##### Tested on [device], iOS [version], WPiOS [version]
iPad Mini, iOS 10.3.2, v8.1.0.20170724

Possibly related: https://github.com/Automattic/wp-calypso/issues/12609

**Comment by jleandroperez** [comment]
Closing this one as cannot repro. Tested on WPiOS 8.3

Thanks for the report @lancewillett!
