### ISSUE TITLE
Reader: certain posts with an image don't show the image

### ISSUE THREAD

**Issue by lancewillett** [wordpress-mobile/WordPress-iOS#7613]
Similar to https://github.com/wordpress-mobile/WordPress-iOS/issues/7612 but in Reader, not posts list.

### Expected behavior
When viewing Reader I'd expect to see a photo in the post preview card when the post in question contains an image.

### Actual behavior
Just the title shows, no image. This seems to be related to posts made with the native app Aztec editor only — posts published with visual editor, or Calypso web editor appear as expected.

![img_0051](https://user-images.githubusercontent.com/66797/28632699-3e9e399e-71e6-11e7-99fe-83d3280ec48d.PNG)

Tree, Cabury All Day, Capp Art by Liam are photo posts I made via my Android phone with Aztec editor.

### Steps to reproduce the behavior
1. Reader, look at a site like lance.blog or photo.cate.blog
2. View the posts list for a post you've published with an image, via Aztec editors.
3. You'll see some posts missing an image.

##### Tested on [device], iOS [version], WPiOS [version]
iPad Mini, iOS 10.3.2, v8.1.0.20170724

Possibly related: https://github.com/Automattic/wp-calypso/issues/12609

**Comment by catehstn** [comment]
As it's showing up in two places I think this may relate to media being added - @SergioEstevao do you ave time to take a look please?

**Comment by lancewillett** [comment]
Tracking Calypso related issue here: https://github.com/Automattic/wp-calypso/issues/12609

**Comment by lancewillett** [comment]
Saw this again today, in iOS app reader, with a recent @catehstn photoblog post, "View from the Eiffel Tower":

![img_0083](https://user-images.githubusercontent.com/66797/28996087-75fc166c-79ad-11e7-866e-eddd1f465245.PNG)

**Comment by SergioEstevao** [comment]
Version 8.2 of the app should solve this for new posts done in Aztec. To fix this on older posts we need to set the featured image on the posts or reinsert the image on the editor.

Enviado do meu iPhone

No dia 5 de ago de 2017, às 15:13, Lance Willett <notifications@github.com> escreveu:

**Comment by lancewillett** [comment]
@SergioEstevao Yay! Testing this out again.

Kris K. published another photo post (using Aztec with iOS app).

![2017-08-15 10 11 31](https://user-images.githubusercontent.com/66797/29326978-6d7f4462-81a2-11e7-97a6-bbeb3b5ccba5.png)

Confirmed the image now appears on my iPad in version 8.3.0.20170815.
