### ISSUE TITLE
Aztec: Cursor is wrong size without text entered in body

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#7614]
Picture says it:

![2017-07-26_19-03-30](https://user-images.githubusercontent.com/373903/28648693-304f6c60-7235-11e7-8a1e-d3516f54e078.png)

cc: @jleandroperez @SergioEstevao

**Comment by jleandroperez** [comment]
Closing as cannot repro on WPiOS 8.4 (develop branch actually!). 

Tested on iOS 10.3 / iPhone 7. Thanks Aaron!
