### ISSUE TITLE
Login: Support iOS 11's password autofill for login fields

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7615]
In iOS 11, there's a new password autofill feature for login text fields. It _should_ be as simple as setting the correct `UITextContentType` value on the text fields, as we already have associated domains set up for wordpress.com.

<img width="454" alt="screen shot 2017-07-27 at 12 23 04" src="https://user-images.githubusercontent.com/4780/28668127-63db1f5c-72c6-11e7-8bbf-2b3c5e408976.png">

More information available here: https://developer.apple.com/videos/play/wwdc2017/206/

**Comment by nheagy** [comment]
It seems like there's no API to query if a password exists already? I'm wondering because it would be nice to use this instead of the magic link flow if there is a saved password. Showing it on the password screens is still an improvement, and _probably_ all we can do?
