### ISSUE TITLE
Login: Update the stats screen's Jetpack login to use the wpcom login flow.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#7633]
Connecting to Jetpack via the stats screen uses a custom login form.  Let's update this to have a consistent login experience within the app... potentially by using the wpcom login flow similar to the Android app's approach.

**Comment by elibud** [comment]
@nheagy @aerych is this something you may have availability to tackle soon? Or maybe work with @koke or me to make this update?

**Comment by aerych** [comment]
We're going to see if we have the bandwidth to include this with the upcoming sign up work.

**Comment by diegoreymendez** [comment]
Clearing the milestone as the issue missed the 9.0 deadline.
