### ISSUE TITLE
WPWebViewController: Navigation bar buttons are invisible

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7639]
### Expected behavior

When I open a web view controller in the app, I should see a close button on the left, and a share button on the right.

### Actual behavior

Both buttons are still there, but invisible.

![10803b0d-0a22-461b-abaf-64c6b813d33a](https://user-images.githubusercontent.com/4780/28836343-6a993d7e-76e0-11e7-990d-79647b470027.PNG)

### Steps to reproduce the behavior

* Open the app and log in
* Tap "View Site"
* Observe the lack of buttons in the navigation bar

**Comment by alisterscott** [comment]
Just noticed this opening an image from a post - came to report and found this. Thanks.

**Comment by elibud** [comment]
I'll push a new version of 8.2 later today.
