### ISSUE TITLE
Reader post detail should show the RSS excerpt (if any) for Jetpack sites

### ISSUE THREAD

**Issue by nbradbury** [wordpress-mobile/WordPress-iOS#7673]
Calypso applies a special treatment for Jetpack posts from sites that have RSS excerpts enabled. It only shows the excerpt and the featured image, if any, and shows a notice Visit SITE_NAME for the full post..

Example of this kind of post: https://wordpress.com/read/blogs/67272686/posts/7751

Related Android issue [here](https://github.com/wordpress-mobile/WordPress-Android/issues/6409)

**Comment by designsimply** [comment]
I tested that only excerpts are shown in the Reader for Jetpack blogs that have selected the "Summary" setting at WP Admin > Settings > Reading > "For each article in a feed, show". I think this is working as expected. 

<img src="https://user-images.githubusercontent.com/1119271/66168073-68d64100-e5f9-11e9-82c9-c934b59ab1f5.PNG" width="270" alt="IMG_3133">
<sup>Tested with WP Internal 13.3.20191001 (HockeyApp) WPiOS 13.3.0.0 (TestFlight) on iPhone 6S iOS 13.1.2.</sup>
