### ISSUE TITLE
Link to Full Image Not Working in Beta Editor

### ISSUE THREAD

**Issue by williambacky** [wordpress-mobile/WordPress-iOS#7677]
### Expected behavior
Link to the full image

### Actual behavior
Does not link to the new image

### Steps to reproduce the behavior
use the beta editor

##### Tested on [device], iOS [version], WPiOS [version]
latest released non beta iOS 10.3.3

**Comment by jleandroperez** [comment]
We're replicating the same behavior as WordPress.com / the Hybrid editor, which do not automatically link to the full size image.

Closing this one as won't fix, thanks for the feedback!
