### ISSUE TITLE
Allow Media Search From Post

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#7680]
From a user:

`
Feedback: In iOS app could be usefull to search media by title also when i add a photo directly when i’m writing a post, and not only when i’m in “Media” tab
`

**Comment by jleandroperez** [comment]
@SergioEstevao can you confirm if this is already being addressed elsewhere (or if we need to move this ticket to another repository?).

Thanks in advance!

(and thanks Rachel for the intel!)

**Comment by frosty** [comment]
@jleandroperez No, this isn’t being addressed currently. Search is currently only in the Media section of the app, but not in the picker in the editor.

**Comment by jleandroperez** [comment]
Thanks @frosty, leaving this issue open then!
