### ISSUE TITLE
People: List standard roles separate from custom roles in invites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#7682]
### Expected behavior

When inviting a new user to a site, I expected to see standard roles (Admin, Editor, Author, Contributor) listed together, and then custom roles, with Follower listed at the end, as in the Calypso People section. Here's a screenshot from the Calypso invites for a site with the WooCommerce plugin:

![screen shot 2017-08-14 at 6 30 29 pm](https://user-images.githubusercontent.com/8658164/29283480-ca7feb0a-811e-11e7-8257-c5585d0abfef.png)

### Actual behavior

Currently, the roles are mixed together and it's kind of hard to grok which roles do what:

![2017-08-14 17 54 21](https://user-images.githubusercontent.com/8658164/29283497-d9187894-811e-11e7-8606-67e10eae074c.png)

If possible, it would be great to list the user roles similar to Calypso, with standard user roles all listed together.

### Steps to reproduce the behavior

1. Add custom roles to a site (e.g. by installing the WooCommerce plugin).
2. Go to My Sites > People in the app and tap +.
3. On the invite screen, select "Role" to see the list of roles.
4. Compare this to the roles listed at https://wordpress.com/people on the "Invite User" screen.

##### Tested on iPhone 6, iOS 10.3.3, WPiOS 8.3.0.20170814

**Comment by elibud** [comment]
@koke

**Comment by koke** [comment]
Thanks for the report. This was the original intention as I purposefully stored the order in which roles were returned from the API. I've confirmed that the order isn't respected either in the Add New or Edit views. I'll investigate what's going on
