### ISSUE TITLE
Aztec: Problem with post title when switching between visual and HTML modes

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#7683]
### Expected behavior

I expect that with the changes in https://github.com/wordpress-mobile/WordPress-iOS/issues/7671 I will see Calypso-style spacing in HTML mode in Aztec.

### Actual behavior

When I switch between visual and HTML modes, the post title gets messed up.

In HTML mode, the first line of text in the post body overlaps the post title field:

![2017-08-14 18 20 03](https://user-images.githubusercontent.com/8658164/29283757-fb4aca74-811f-11e7-924a-27f958ec9bca.png)

When I switch back to visual mode, the post title sometimes is moved up on screen so the top is cut off. In this screenshot, there is extra space at the top of the post body that shouldn't be there, and the top of the title is cut off (it isn't possible to scroll up to see the rest of it):

![2017-08-14 18 23 18](https://user-images.githubusercontent.com/8658164/29283797-1cf0ea8c-8120-11e7-8dfd-63ee6e3b8fb3.png)

### Steps to reproduce the behavior

1. In Aztec, add content with multiple paragraphs.
2. Switch to HTML mode; note that the first line of the post body overlaps with the title field.
3. Switch back to visual mode; note that the title field is moved up on the screen (only seems to happen the first time I switch back).

##### Tested on iPhone 6, iOS 10.3.3, WPiOS 8.3.0.20170814

**Comment by elibud** [comment]
From my testing this is fixed on version 8.5, @rachelmcr can you please verify? Thanks

**Comment by rachelmcr** [comment]
Yes, I tested again and I'm no longer seeing this issue. Thanks for checking!
