### ISSUE TITLE
Media / Editor: Allow inserting links to documents from Media Library

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7689]
If the user has documents in their media library (PDFs, etc), we could allow selecting them from the media picker and insert them as links. The flow would be:

Editor > Add Media > Choose Media Library > Select a PDF > Tap "Insert" > A link is added into the editor, using the title of the document as the link text

**Comment by bummytime** [comment]
@frosty @SergioEstevao @iamthomasbishop 

Do y’all have any thoughts on the UX for inserting multiple documents from the media lib? At first I assumed maybe the insert link dialog could be leveraged and it works when selecting a single document:

![pdf_links](https://user-images.githubusercontent.com/154014/30917970-d5765182-a362-11e7-8441-e471188bf8c3.gif)

...but quickly realized it gets tricky when a user selects multiple non-image/video assets.

I am assuming we should just automagically insert the link sans-dialog, but wanted to get your thoughts on this.

**Comment by frosty** [comment]
Hmm, good point @bummytime! Right, I think perhaps in the case of multiple links, we should just insert them all into the post on their own lines. The user can always edit the links afterwards. If just a single document is selected, we could show the alert in that situation?

**Comment by SergioEstevao** [comment]
I will skip the dialog always, I don’t think it helps at all.

Enviado do meu iPhone

No dia 27 de set de 2017, às 15:16, Matt Bumgardner <notifications@github.com> escreveu:

**Comment by bummytime** [comment]
@SergioEstevao I think you are right — the dialog is just getting in the way.

**Comment by iamthomasbishop** [comment]
Maybe a wider project, but can't we get other media types to act similarly to how they do in Calypso? For example, if you choose an audio clip to add and insert it into the canvas, it forms a shortcode which embeds a player on the post/page. This is closer to what I'd expect as a user.

**Comment by bummytime** [comment]
@iamthomasbishop I agree that following Calypso would be preferred for audio:

<img width="768" alt="screen shot 2017-09-27 at 2 28 44 pm" src="https://user-images.githubusercontent.com/154014/30933449-39485bd8-a390-11e7-854f-799c3fe8b722.png">

...which we can extend Aztec to do. However, as you mentioned, I think that is a separate issue outside of this one (I'll create the issue and link to this one). For PDF's and other docs it appears we are just creating an `<a>` link, so for now I will do that.

**Comment by SergioEstevao** [comment]
@bummytime I agree with you let's keep audio in a separate issue. We should be able to implement it similar to what we did for video.
