### ISSUE TITLE
Preview - Featured Image is not visible

### ISSUE THREAD

**Issue by ashlives** [wordpress-mobile/WordPress-iOS#7693]
### Expected behavior
Feature Image for the Blog Post should be visible when previewing the post.

### Actual behavior
Feature Image added by user is not visible when Previewing the Blog Post.
<img src="https://user-images.githubusercontent.com/16035416/29355336-4c951fdc-828e-11e7-9e44-dbf0dd1a90fb.PNG" width="200" height="400" /> <img src="https://user-images.githubusercontent.com/16035416/29355337-4c962968-828e-11e7-813a-c45c06545ebc.PNG" width="200" height="400" /> <img src="https://user-images.githubusercontent.com/16035416/29355338-4c9818ae-828e-11e7-9693-d4be36bd99f3.PNG" width="200" height="400" />

### Steps to reproduce the behavior
1. Launch the WordPress app
2. Navigate to Blog Posts under Publish
3. Tap on an existing blog post which contains a featured image
4. Tap on '...' and select Preview

##### Tested on [device], iOS [version], WPiOS [version]
Device: iPhone 5s, 10.3.3, WPiOS 8.3 (8.3.0.2)

**Comment by rachelmcr** [comment]
Related: https://github.com/wordpress-mobile/WordPress-iOS/issues/5686

**Comment by elibud** [comment]
Until a post is not saved server side the image is not available for the post preview, this will be solved once we implement autosaving.

**Comment by koke** [comment]
There were a bunch of similar issues related to previews, I did some cleanup and created a master issue with specific steps. Closing this in favor of #9282.
