### ISSUE TITLE
Notifications: Comment labels shift when a comment is approved

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#7696]
### Details:
We got a user report from a user, indicating since the buttons do shift whenever you toggle from Unapproved to Approved, he accidentally trashed a comment.

Let's analyze if we should either:

A. Lock the width to the maximum required (and thus, prevent the shift)
B. (OR) Lower the font's point size

![pic21](https://user-images.githubusercontent.com/1195260/29376782-13dbe098-8290-11e7-8ad6-ba3173a3cc8f.png)

**Comment by elibud** [comment]
Looking at the screenshot it seems like this person is using a bigger text size on accessibility. Lowering the normal font point might solve the problem at one size but not the next one. Also IIRC we have a similar problem in languages where Approved/Unapproved are a longer words.
I think locking the width of the buttons so they all have the same size is the better option here.
