### ISSUE TITLE
Caption shortcode support.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7715]
## Description

We need Aztec to support the `caption` shortcode.  Extensive details can be found in the original issue [here](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/281).

## Details

This issue depends on another one from Aztec: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/723.

In terms of WPiOS the work that needs to be done is to convert caption shortcodes to `figure` + `figcaption` tags.

[Here's an example](https://www.w3schools.com/tags/tag_figcaption.asp) showing standard figcaption usage.

```html
<figure>
  <img src="img_pulpit.jpg" alt="The Pulpit Rock" width="304" height="228">
  <figcaption>Fig1. - A view of the pulpit rock in Norway.</figcaption>
</figure>
```

**Comment by sarahblackstock** [comment]
Support request for option to add caption to images. (On iOS 11, so possibly not able to use the older editor without other issues popping up.)

internal ref: #238613-h

**Comment by jklausa** [comment]
I've also got a user asking about adding captions to images in Aztec.

ref: #239528-h

**Comment by sarahblackstock** [comment]
Have personally seen 5+ requests for ability to add captions in this editor this week. 

Most recent, internal ref: #239621-h

**Comment by diegoreymendez** [comment]
Thanks @jklausa and @sarahblackstock.

Considering the amount of interest, we'll try to focus on this for the next release.

**Comment by diegoreymendez** [comment]
Fyi @maxme, @SergioEstevao, @jleandroperez ^

**Comment by diegoreymendez** [comment]
Even though 9.2 has entered code freeze, we'll try to add this feature before the release.

**Comment by krutidugade** [comment]
Update - User unable to add caption to images from iOS device
https://mc.a8c.com/support-stats/happychat/transcript.php?id=1061377
We told the user it will be soon fixed in next release which is why user enquired again about it

**Comment by diegoreymendez** [comment]
@krutidugade - The feature is delayed due to complications.  We'll report it here as soon as there are news.

**Comment by diegoreymendez** [comment]
This feature has been merged into the library in https://github.com/wordpress-mobile/AztecEditor-iOS/pull/910 and will be integrated into WPiOS shortly.
