### ISSUE TITLE
Fix list format-bar-item accessibility label

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7742]
### Expected behavior

When tapping on the "List Style" button with VoiceOver turned on, we'd expect to hear "Select list style" as the accessibility label for the button (or something equivalent).

### Actual behavior

VoiceOver reads "Toggle Unordered List Style", which doesn't properly describe what the button does.

### Technical Information

It seems we may need to define a [new identifier](https://github.com/wordpress-mobile/WordPress-iOS/blob/ab61a5c3851a0fbc531aff5aeef1aa684d9d56fe/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L2136) for the list style selection button.
Make sure creating and using a new identifier doesn't break the list selection process.

### Steps to reproduce the behavior

Turn on VoiceOver.
Launch the App.
Enable Aztec.
Start a new post.
Tap on the list selection button in the format bar.

##### Tested on iPhone 7, iOS 10.3.3 (14G60), WPiOS 8.5 (`develop`).

**Comment by frosty** [comment]
Thanks, @diegoreymendez! Good catch!
