### ISSUE TITLE
New Media Picker: Camera option in the media picker doesn't work from all album views

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#7757]
There are issues with the camera option in several places within the app, but I included them all in this issue since they all relate to the same underlying problem with the new media picker.

### Expected behavior

With the new media picker, when I am using the hybrid editor changing my site icon or Gravatar, I expect to see a camera option so I can take a photo or video from within the app. I expect to have that photo automatically added to the my post or be selected for the site icon/Gravatar, or at least be able to see that photo in the picker so I can select it.

### Actual behavior

The camera option in the media picker doesn't work from all album views:

- If I am in the Camera Roll album, after I take a photo/video I see the new photo appear in the Camera Roll, and it's selected so I can use it.
- If I am in the WordPress Media Library album, after I take a photo/video I see the new photo appear in the Media Library album automatically. If I select and add it from there, it is then uploaded and I can use it. If I cancel the process, the photo still appears in my media library in the app but it isn't actually uploaded. (Going to the Media section and selecting the photo results in errors because it isn't actually uploaded to the site's media library but it still appears there.)
- If I am in a different device album, after I take a photo/video nothing appears in my selected album. I have to go back and switch to the Camera Roll to find the new photo/video. This is especially confusing in the Gravatar flow, where the Selfie album is auto-selected but taking a selfie doesn't automatically show the new selfie in that album, so I have to go to the Camera Roll to find and select it as my new Gravatar.

### Steps to reproduce the behavior

**Gravatar flow:**

1. Go to the Me tab.
2. Tap on your Gravatar to change it.
3. You should be taken to the Selfie album on your device. Select the camera option at the top of the screen.
4. Take a selfie with the device camera and select "Use Photo" to use it.

Result: You are taken back to the Selfie album but the new photo doesn't appear.

**Media Library flow:**

1. In Me > App Settings choose "Visual" (the hybrid editor) as your editor.
2. Start a new post.
3. Select the add media button in the toolbar.
4. Choose "WordPress Media" from the Albums list.
5. Tap the camera icon at the top of the WordPress Media album.
6. Take a photo and select "Use Photo." Note that this photo now appears in the WordPress Media album.
7. Tap "Albums" to go back (don't add the photo to your post).
8. Tap "Cancel" to cancel adding media to your post, and then tap the X to close the editor.
9. Open your site's My Sites > Media section.
10. Note that the photo you just took is visible in your media library. Tap on it.

Result: You see the photo details as if it had been uploaded to your site's media library, but the options at the top of the screen (Cancel/Save) aren't the expected ones. Tapping "Cancel" doesn't do anything and tapping "Save" results in the error "Unable to save media item." If you check your media library from a browser you'll see that the photo is not uploaded there.

**Other device album flow:**

1. In Me > App Settings choose "Visual" (the hybrid editor) as your editor.
2. Start a new post.
3. Select the add media button in the toolbar.
4. Select an album other than "Camera Roll" from the list. (For example, the "Favorites" album.)
5. Tap the camera icon at the top of the WordPress Media album.
6. Take a photo and select "Use Photo." Note that the photo doesn't appear anywhere in your selected album.
7. Tap "Albums" to go back.
8. Select the "Camera Roll" album. Note that your photo appears here and you can now select it to add it to your post.

##### Tested on iPhone 6, iOS 10.3.3, WPiOS 8.4.0.20170828

**Comment by SergioEstevao** [comment]
@rachelmcr thanks for the report, I will split this in three tickets because they are three different issues.

**Comment by rachelmcr** [comment]
I confirmed that these issues also exist with the previous media picker in 8.3. This is the first time I noticed these issues — I think because the previous media picker auto-selects the Camera Roll album (so if I take a photo with the camera option I'm usually already in the Camera Roll album), whereas the new media picker takes me to the Albums list where I can choose any album before trying to take a picture.

It seems like we should not offer the camera option if the user is in an album other than the Camera Roll, or perhaps we should automatically switch them to the Camera Roll album after taking a picture so they can easily find and select/insert the new photo.

**Comment by SergioEstevao** [comment]
Create a sub issue related to this: #7760

**Comment by SergioEstevao** [comment]
So the main issue here is that photos taken while inside one of the Apple Automatic albums: Favourites, Selfies, Panoramas, cannot be added automatically added to the album, the system needs to do it before we can see them.

One possible solution is to remove the camera preview/capture options from all albums except the Camera Roll. 

What do you think @rachelmcr @frosty @iamthomasbishop ?

**Comment by frosty** [comment]
@SergioEstevao Yeah, I'm wondering if that's going to be the best option. The only question is whether that's going to be discoverable enough for users. Or perhaps, we still show the capture cell everywhere but automatically switch the user to the Camera Roll / All Photos album if they choose it and take a picture.

**Comment by SergioEstevao** [comment]
Ok, I dig it a bit more, and found some bugs on the current implementation of the picker.

When we have the single selection mode active, no notifications of selection where being send, so when we took an photo it was not automatic closing the picker.

This applies to the Gravatar and Site picker, so after I fix this when you take an photo there it will automatically selected and close the picker and avoid this issue altogether.

I still can go the Camera Roll for the multiple selection mode.

**Comment by iamthomasbishop** [comment]
@SergioEstevao @frosty 

In terms of gravatar flow, I'm wondering if we simplify the process like so:

1. User taps gravatar to edit
2. Selfies album shows with camera block like current
3. Camera pops up
4. Cancel button exits, or user takes photo
5. When user takes photo, they can tap `Retake` (goes back to Camera default) or `Use Photo`
6. If user taps `Use Photo`, we should simply go to the `Resize & Crop` screen where they can go back or tap `Use`.

Does this make sense?

**Comment by SergioEstevao** [comment]
It's being done here.
