### ISSUE TITLE
Jetpack Themes: Can't activate a WordPress.com theme

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#7758]
### Expected behavior

In the Themes section on a Jetpack site, I expect to be able to activate a new theme.

### Actual behavior

On any Jetpack site (including Atomic sites), I can only activate themes that are already uploaded to my site, listed in the "Uploaded Themes" section. If I scroll down to the "WordPress.com Themes" section and try to activate one of those themes, I get an error:

> Activation Error
> The specific theme was not found.

![2017-08-29 18 46 55](https://user-images.githubusercontent.com/8658164/29869981-4128b60a-8d7d-11e7-9615-e2b22f5aac94.png)

### Steps to reproduce the behavior

1. In My Sites, select a Jetpack site.
2. Open the Themes section.
3. Scroll down to the "WordPress.com Themes" section.
4. Tap the ... menu for a WordPress.com theme and select "Activate."

Result: You get an activation error and the theme is not activated.

**Comment by elibud** [comment]
@rachelmcr This is extremely strange since we tested this scenario thoughtfully. Activating a theme requires to first upload it to your site, and I can see you were on a 3G connection. Can you check this again on Wi-Fi? Thanks

**Comment by rachelmcr** [comment]
My screenshot was from testing on 3G, but I tested again on WiFi and reproduced the issue before reporting it. I checked my app logs to see if they contain more clues but I don't see anything there besides the error was displayed on-screen:

```
2017/08/30 13:34:57:816 Error activating theme Optional("independent-publisher-2"): Optional("The specified theme was not found.")
```

I then tested with the same WordPress.com theme and the same Jetpack site at https://wordpress.com/themes in a web browser and confirmed that I could successfully activate the theme from there, so this seems to be app specific.

Is there anything else I could check for you?

**Comment by elibud** [comment]
Can you check several different themes and let me know if none of them work? I just tested on my sandbox and it worked correctly.

**Comment by elibud** [comment]
@rachelmcr I think your site is possessed by the devil ;)
I just invited you to my sandbox and I've uninstalled all themes var the current one there. When you have a few minutes please try to activate a couple of themes on that one. Thanks a lot.

**Comment by rachelmcr** [comment]
Unfortunately I run into the same error trying to activate various themes on your sandbox (as well as other tests sites I have). I also tested from a second device (iPad Mini) with the same results.

**Comment by elibud** [comment]
Thanks @rachelmcr I'll keep digging.

**Comment by hoverduck** [comment]
Tested on my iPad Air 2 with two different accounts and sites (on different hosts as well) and had the same result as @rachelmcr, `The specified theme was not found`

**Comment by hoverduck** [comment]
Got it!

The feature only works if you have SSO enabled.  If this isn't checked, you get the error:

![image](https://user-images.githubusercontent.com/7233112/30166280-d9fe6080-93b0-11e7-8c60-ab210603bac2.png)

**Comment by elibud** [comment]
Thanks @hoverduck, this is becoming really mysterious.

@frosty since you were the reviewer of the PR, can you check that you can activate a WordPress.com theme that you have not previously installed on your site? I want to see if we can find a pattern between who is this working for and who it isn't.

**Comment by hoverduck** [comment]
A different side of the same problem, if I choose "Try & Customize" for a wpcom theme I'm then prompted to login via the web.  Once I log in I get the error `The theme directory "apostrophe-2-wpcom" does not exist` (for the given theme name)

**Comment by elibud** [comment]
That's a different issue @hoverduck https://github.com/wordpress-mobile/WordPress-iOS/issues/7794 I'll fix it.

**Comment by elibud** [comment]
Updating here too, it's the same issue, the theme fails to install so we can't try it on the Jetpack site.

**Comment by frosty** [comment]
@elibud fwiw, I just tested activating a number of different themes (that weren't already installed) on my Jetpack site, and they all worked just fine.

**Comment by elibud** [comment]
Thanks @frosty I thought I was going crazy.

**Comment by elibud** [comment]
@rachelmcr @hoverduck I've just invited you to a test site, when you have some time please let me know if you can activate themes there. There are no themes currently installed. Thanks

**Comment by rachelmcr** [comment]
I accepted the invitation and tried activating several themes on that site (Karuna, Cubic, Sela) and got the same error each time. Each time I went to My Sites > Themes in the app, tapped the ellipsis icon on a theme, and selected "Activate" from the menu.

I then tried the following steps:

1. I selected "Try & Customize" instead of "Activate" and was sent to a login screen for the test site.
2. I selected a different (WordPress.com) site and selected "Try & Customize" for a theme to make sure I was authenticated there. (I was.)
3. I went back to Themes on the test site and tried "Try & Customize" again, but was again presented with the site's login screen.
4. I selected "Details" for a theme and confirmed that I got a logged-in view of the theme details page.
5. I selected "Activate" in the top right corner of the theme details screen and got the same error.
6. I opened the theme details again and selected the "Activate this design" button (in the webview) and it worked.

This is consistent with my previous experience, where I can activate themes from the web (it worked in the webview in the app) but I can't activate themes using the app's native features.

**Comment by elibud** [comment]
Ok here we go again, I've created a branch with specific logging for this issue and I've made a tiny change that I doubt will have any effect, here's the branch: https://github.com/wordpress-mobile/WordPress-iOS/pull/7804
What I need from you angels @rachelmcr and @hoverduck is that you install the build from that branch and try to activate themes once again. When it fails please send me the application logs through Helpshift and ping me. Of course, no hurries.
Thanks a million for all your help on this, unfortunately I can't do anything else than to bug you two since I can't replicate on my side and neither can @frosty

**Comment by elibud** [comment]
The error we are getting from the backend is a `403`, we will have to investigate more along with the Jetpack team.

**Comment by elibud** [comment]
@rachelmcr @hoverduck: a fix has been deployed for this one, can you please try again and let us know how it goes?
Thanks a million

**Comment by rachelmcr** [comment]
Woohoo! I tried again and confirmed that both "Activate" and "Try & Customize" work as expected now. Thanks for digging in to this one. :)

**Comment by elibud** [comment]
oh my goodness!!!!!!!!! thanks a lot, I'm going to re-enable it in prod builds :)
@oskosk did all the heavy lifting on this one, thanks again Oscar!
