### ISSUE TITLE
Jetpack Themes: Customize leads to a login screen

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#7759]
### Expected behavior

I expect that when I go to Themes > Customize I will end up in the site's customizer.

### Actual behavior

On a Jetpack site (including Atomic sites), when I go to Themes > Customize I end up on my site's login screen. If WordPress.com SSO is activated on my site, when I select "Log in with WordPress.com" I end up on the WordPress.com login screen, even though I'm already logged in to the app. I shouldn't have to log in to my site again when I'm already logged in to it via my WordPress.com account in the app, and I especially shouldn't have to log in to WordPress.com again.

This also happens when you select "Try & Customize" on a theme that isn't currently activated.

### Steps to reproduce the behavior

1. In My Sites, select a Jetpack site.
2. Open the Themes section.
3. Select "Customize" (under Current Theme).
4. If you see the "Log in with WordPress.com" option, select it.

Result: You're always taken to a login screen.

**Comment by elibud** [comment]
@rachelmcr I got the same behavior on the app that we currently have on the web. This is displayed:

<img width="394" alt="login" src="https://user-images.githubusercontent.com/5558824/29926409-c9d97162-8e39-11e7-9da1-cf51b0b31784.png">

But if you tap login it automatically logs you in and takes you to the customize screen. Did the app made you enter your credentials? If not I think it's OK to close this one as once its sorted server side it will be good for us too.

**Comment by rachelmcr** [comment]
Ah, this is related to the same authentication issue as https://github.com/wordpress-mobile/WordPress-iOS/issues/7761.

The app asks me to enter my WordPress.com credentials — it doesn't recognize the account I'm logged in to in the app. This happens when I log in to my WordPress.com account and go straight to my Jetpack site to open the customizer.

If I select a WordPress.com site first, instead, the app authenticates the view. Then, if I switch to a Jetpack site I stay authenticated and don't have to enter my WordPress.com credentials again. (This only works if you have both a WordPress.com and a Jetpack site, and use them in this order.)

**Comment by elibud** [comment]
Thanks @rachelmcr brilliant! I can replicate the problem now, I have no idea what's going on though :(

**Comment by elibud** [comment]
This one will be fixed once tackle: https://github.com/wordpress-mobile/WordPress-iOS/issues/7778

**Comment by elibud** [comment]
With the work @koke did on https://github.com/wordpress-mobile/WordPress-iOS/pull/7906 for SSO enabled sites users can now authenticate with one click, which is the best we can do right now. Users without SSO will have to inevitably enter their credentials.
