### ISSUE TITLE
Local Media Library photos are not accessible on the Media Library.

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#7760]
### Expected behavior

If I am in the WordPress Media Library album, after I take a photo/video I see the new photo appear in the Media Library album automatically. If I select and add it from there, it is then uploaded and I can use it. If I cancel the process, the photo still appears in my media library in the app but it isn't actually uploaded. (Going to the Media section and selecting the photo results in errors because it isn't actually uploaded to the site's media library but it still appears there.)

### Steps to reproduce the behavior

**Media Library flow:**

1. In Me > App Settings choose "Visual" (the hybrid editor) as your editor.
2. Start a new post.
3. Select the add media button in the toolbar.
4. Choose "WordPress Media" from the Albums list.
5. Tap the camera icon at the top of the WordPress Media album.
6. Take a photo and select "Use Photo." Note that this photo now appears in the WordPress Media album.
7. Tap "Albums" to go back (don't add the photo to your post).
8. Tap "Cancel" to cancel adding media to your post, and then tap the X to close the editor.
9. Open your site's My Sites > Media section.
10. Note that the photo you just took is visible in your media library. Tap on it.

##### Tested on iPhone 6, iOS 10.3.3, WPiOS 8.4.0.20170828

**Comment by elibud** [comment]
Is the crash fixed? Can we close this issue or should we move it to milestone 8.6?

**Comment by frosty** [comment]
I don’t think this should be possible now due to the changes we made to the hybrid editor. Capturing an image now always inserts it into the post.

**Comment by elibud** [comment]
Ok, I'm closing it then, @SergioEstevao @frosty please reopen if necessary.
