### ISSUE TITLE
Jetpack Themes: Details can lead to a logged out theme details page and possible activation issues

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#7761]
### Expected behavior

I expect that when I view a theme's details, I'll see a logged-in view (when the details are for a WordPress.com theme).

### Actual behavior

When I have a WordPress.com site selected and I view a theme's details, I see a logged-in view. I can select "Activate" in the top right to activate the theme, but I can also select "Activate this design" on the details page to activate it on my site.

When I have a Jetpack site selected and I view a WordPress.com theme's details, I sometimes see a logged-out view. (This seems to happen, for example, right after logging in to a WordPress.com account with a Jetpack site. If I open the Details section for a theme on a WordPress.com site in the app, and then do the same on a Jetpack site, I am authenticated and get a logged-in view.) Instead of "Activate this design" on the Details page I see "Pick this design," which leads to a signup flow instead of activating the design on my selected Jetpack site.

### Steps to reproduce the behavior

1. Log out of the app and log in again.
2. Go to My Sites and select a Jetpack site.
3. Open the Themes section.
4. Scroll down to "WordPress.com Themes" and tap the ... menu on a WordPress.com theme, and then select Details.
5. Note that you are seeing a logged out view, and select "Pick this design" on the details page.

Result: You are taken to a signup flow instead of activating the theme on your site.

##### Tested on iPhone 6, iOS 10.3.3, WPiOS 8.4.0.20170828

**Comment by elibud** [comment]
This one will be fixed once tackle: https://github.com/wordpress-mobile/WordPress-iOS/issues/7778

**Comment by elibud** [comment]
With the work @koke did on https://github.com/wordpress-mobile/WordPress-iOS/pull/7906 for SSO enabled sites users can now authenticate with one click, which is the best we can do right now. Users without SSO will have to inevitably enter their credentials.
