### ISSUE TITLE
Me: Crash when selecting Log In > Create a WordPress Site from within the app

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#7762]
### Expected behavior

When I am already logged in to a self-hosted site, but not a WordPress.com account, I expect to be able to log in to or create a new WordPress.com account on the Me tab.

### Actual behavior

When I select "Log In" on the Me tab, and then select "Create a WordPress site" (to create a new WordPress.com account/site), the app crashes.

### Steps to reproduce the behavior

0. Start logged out of the app.
1. Add a self-hosted site (no Jetpack) to the app.
2. Go to the Me tab and tap "Log In" under WordPress.com Account.
3. Select "Create a WordPress site."

Result: The app crashes.

##### Tested on iPhone 6, iOS 10.3.3, WPiOS 8.4.0.20170828

Also tested on 8.3 release and there is no crash there.

**Comment by elibud** [comment]
@rachelmcr this is fixed on 8.3 and we pushed the change to 8.4 after the build went out, that's why you got the crash. Closing as it has already been addressed: https://github.com/wordpress-mobile/WordPress-iOS/issues/7743
