### ISSUE TITLE
Improve WPWebViewController to use WP.com credentials when triggered for auth on Jetpack sites

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7778]
For Jetpack sites with SSO enabled, if the user is logged in into the app with WP.com credentials, we should be able to log the user into the theme customizer and other web views without requiring the user to re-enter their credentials.

**Comment by elibud** [comment]
@koke we can close this one, right?

**Comment by koke** [comment]
Yes! 😁
