### ISSUE TITLE
Migrate WPWebViewController to WKWebView

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7781]
The logic on `WPWebViewController` is not very clear, and we would need to add some fixes to it to support https://github.com/wordpress-mobile/WordPress-iOS/issues/7759 and https://github.com/wordpress-mobile/WordPress-iOS/issues/7761, as specified in https://github.com/wordpress-mobile/WordPress-iOS/issues/7778
However, considering https://github.com/wordpress-mobile/WordPress-iOS/issues/6371 and the future, it seems more reasonable to re-write it as a WKWebView in Swift (careful: due to the bug mentioned on https://github.com/wordpress-mobile/WordPress-iOS/issues/6371 we may only be able to use it on clients on iOS 11 and over)

cc: @koke

**Comment by koke** [comment]
Another related issue: #4381
