### ISSUE TITLE
iPhone X: New Post button in landscape tab bar is too small

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7816]
The New Post button in the center of the main tab bar looks far too small on a landscape iPhone X:

![simulator screen shot - iphone x - 2017-09-13 at 16 26 34](https://user-images.githubusercontent.com/4780/30697260-41cb6af2-9ed6-11e7-9b02-e94cc022a24a.png)

The horizontal spacing also looks off, likely due to the hidden title.

**Comment by frosty** [comment]
So a bit more on this... I just took a bunch of screenshots on a range of simulators:

![tab-bars](https://user-images.githubusercontent.com/4780/30872139-ffa956d4-a2e0-11e7-9e40-d000f7bc2d4c.png)

Clearly we have lots of problems and inconsistencies. As I see it, we have a couple of issues:

* In landscape, particularly on the X and non-Plus phones, the tab bar items get resized pretty small. This makes the icon on our normal New Post button quite hard to see.
* Our previous 'hack' for hiding the title of the buttons now only really works on portrait on the phones, and iPad when multitasking. The other views are problematic because the titles are now displayed to the side of the icon instead of underneath. Previously we just had to move the title down out of view, and the image down a little so it's centered vertically. In these new landscape versions, we'd also have to move the image across horizontally, to make up for the space left by the label. But calculating how much to move over feels like it's going to be super hacky.

Here's what I propose we do, but I'd like to get feedback on the best approach:

* In portrait on phones, we can keep the current appearance, if we want to.
* In landscape on phones, and on iPads, we should reintroduce the title for the New Post / Write button at all times. This will mean we don't have to hack around the positioning, and things will be more consistent. It may help with discoverability too, as we know some users have had issues finding how to create a new post.
* We'll need to re-evaluate the icon we use (or, the way it's presented) for New Post when in landscape on a phone, as that icon gets super tiny. Perhaps we just use the standard gridicon (the same size as the other icons in the bar) when in landscape. Or perhaps we just need to make that icon larger.
* Doing much more custom is somewhat problematic, as there's no way to distinguish which style of presentation the tab bar is currently using, as far as I can tell. We only know the device orientation / current screen dimensions, and not which layout the tab bar is using.

Pinging @folletto @mattmiklic for thoughts!

**Comment by mattmiklic** [comment]
> In portrait on phones, we can keep the current appearance, if we want to.
> In landscape on phones, and on iPads, we should reintroduce the title for the New Post / Write button at all times.
> Perhaps we just use the standard gridicon (the same size as the other icons in the bar) when in landscape.

All of these sound like good ideas to me. We may want to try to make the Write option stand out more on Landscape somehow, but just doing what you've outlined above would be a clear improvement over what we see currently.

**Comment by frosty** [comment]
Marking as resolved for now, although we may want to revisit the landscape appearance in the future.
