### ISSUE TITLE
iPhone X: Hybrid editor toolbar item positioning is incorrect

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7818]
On iPhone X, the positioning of items in the hybrid editor's formatting toolbar appears to be incorrect. The items look lower and closer together than I'd expect:

<img width="389" alt="screen shot 2017-09-13 at 16 28 42" src="https://user-images.githubusercontent.com/4780/30697775-feff0c40-9ed7-11e7-9af6-0389b2594b09.png">

**Comment by SergioEstevao** [comment]
Fixed in 8.6 by this: https://github.com/wordpress-mobile/WordPress-iOS/pull/8003
