### ISSUE TITLE
iPhone X: Search bar layout issues

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7819]
In both the Posts list and Blog List, there are layout issues around the use of search bars on iPhone X:

![rectangle](https://user-images.githubusercontent.com/4780/30698300-6c4de996-9ed9-11e7-9c05-51130b5cd9ce.png)

![rectangle copy](https://user-images.githubusercontent.com/4780/30698301-6eaad9a6-9ed9-11e7-8084-67a2c2ef0a64.png)

Both of these use similar implementations so I imagine the same fix will apply to both. We should also check any other areas of the app that use search bars.

**Comment by frosty** [comment]
Added iOS 11 tag - this isn't just iPhone X specific, but affects all iOS 11 devices.

**Comment by ScoutHarris** [comment]
@frosty - it looks like #8007 fixed this. Should this be closed?

**Comment by frosty** [comment]
@ScoutHarris – I noticed there's still an issue on the blog selector view controller, so I'll leave it open for now :) But thank you for checking and reminding me!

**Comment by SergioEstevao** [comment]
@frosty is this still an issue?

**Comment by frosty** [comment]
@SergioEstevao I'm pretty sure there are still some issues in the blog / site picker in the editor. When you activate the search bar the spacing below it is wrong, and when you cancel the search bar the space above it is wrong.

**Comment by frosty** [comment]
Just a note that now we’ve bumped our minimum OS version to iOS 11, it’s possible we could reinvestigate iOS 11’s searchbar-contained-within-a-navigation-bar UI style. Might help with these issues, but I’m not sure it will be an easy implementation.

**Comment by jkmassel** [comment]
This is no longer an issue in the current version of the app.

Closing.
