### ISSUE TITLE
iPhone X: Aztec edge inset issues in landscape

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7821]
On iPhone X, in landscape, Aztec has numerous issue with edge insets, where the 'notch' overlaps content:

![simulator screen shot - iphone x - 2017-09-13 at 16 29 45](https://user-images.githubusercontent.com/4780/30698847-0ce148f2-9edb-11e7-916f-e1ca3b8e763e.png)

- [x] Text view
- [x] Title view
- [x] Format bar

We should switch to using `safeAreaInsets` / `safeAreaLayoutGuide` where appropriate (using `if #available(iOS 11.0)`) to avoid these unsafe areas of the screen.

**Comment by elibud** [comment]
😢
