### ISSUE TITLE
Notifications: URLs not linked in notifications

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#7833]
### Expected behavior

I expect URLs to be linked (tappable) everywhere they appear.

### Actual behavior

In comment notifications, URLs are not linked/tappable.

If you go to My Sites > Comments to find the same comment in the app, the URL is linked/tappable there, as well as in the comments section on the post in the Reader view.

### Steps to reproduce the behavior

1. From another account, submit a comment that includes a bare URL.
2. In the app, open the comment notification.

Result: The bare URL appears but is not linked/tappable.

### Screenshots

Unlinked URL in comment notification:

![2017-09-25 11 53 03](https://user-images.githubusercontent.com/8658164/30805431-4835802e-a1e9-11e7-929a-8c6e8be03826.png)

Linked URL in My Sites > Comments:

![2017-09-25 11 54 04](https://user-images.githubusercontent.com/8658164/30805426-45cd2dc8-a1e9-11e7-960b-cd6d45bbad59.png)

Linked URL in Reader view:

![2017-09-25 11 54 36](https://user-images.githubusercontent.com/8658164/30805397-1a8d9e22-a1e9-11e7-929b-48776e15110b.png)

##### Tested on iPhone 6, iOS 11.0, WPiOS 8.4.0.20170918

**Comment by jleandroperez** [comment]
Closed via #8088. Thanks Rachel!
