### ISSUE TITLE
Media: synchronize ALT field with remote.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7837]
In order to properly load the ALT field for our media, we need to:

1. Modify `RemoteMedia` to be able to store the `alt` text.
2. Modify `Media` to also be able to store the `alt` text.
3. Modify `MediaServiceRemoteREST.m` and `MediaServiceRemoteXMLRPC.m` to keep the `alt` field synchronized with our remote.
4. Add or modify the appropriate unit tests to make sure our services handle the `alt` field correctly.

**Comment by bummytime** [comment]
It shouldn't impact work for this task, but just referencing #7596 for whenever work begins on that.
