### ISSUE TITLE
Aztec: Erratical behavior with headers in iOS 11.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7840]
The header format bar option behaves erratically when using iOS 11.

**Steps to reproduce:**

- Simply make sure you run the "Visual 2.0" editor under iOS 11, and select any header style.
- The header button will not always refresh correctly.

Fyi @frosty 
Props to @elibud for finding this issue.

**Comment by jleandroperez** [comment]
We've addressed a number of issues related to this: [1](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/748) + [2](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/747) + [3](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/749).

Closing this one, everything should be good now!

**Comment by diegoreymendez** [comment]
Tagging as 8.5.1 since that's where this fixes were released.
