### ISSUE TITLE
A8C Reader: Error when viewing cross posts to a site you are not a registered user

### ISSUE THREAD

**Issue by aaronyan** [wordpress-mobile/WordPress-iOS#7842]
On mobile devices, if you click on a cross post that comes from a private site where you are not a registered user, the post cannot be retrieved. This problem will only happen for Automatticians (specifically in the a8c stream). The error can be produced on multiple operating systems (both iOS and Android).

Also posted to WordPress-Andrid issues https://github.com/wordpress-mobile/WordPress-Android/issues/6659.

**Comment by aerych** [comment]
Thanks for the report @aaronyan.  We've made a conscious choice to limit enhancements to the reader that only affect a8cs. 
Closing.
