### ISSUE TITLE
Reader: Grey border appears above/below comment section in Reader

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#7845]
### Expected behavior

I expect the comments section in the Reader to have a solid white background.

### Actual behavior

There is a grey top and bottom border on the comment section in the Reader:

![2017-09-26 08 47 05](https://user-images.githubusercontent.com/8658164/30856869-a96676be-a2b1-11e7-8372-0143fa5f9c90.png)

### Steps to reproduce the behavior

1. Open the Reader in the WP 8.5 beta app.
2. Find a post with comments and open the comment section.

##### Tested on iPhone 6, iOS 11.0, WPiOS 8.5.0.20170925

**Comment by frosty** [comment]
Fixed by #7847
