### ISSUE TITLE
iOS 11: Table View scroll offset changes while appearing

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#7849]
There's an odd effect happening whenever a table view is loaded. It seems like it starts slightly scrolled down, then animates to the right position, as the view is pushed. This gets annoying pretty quickly as you navigate through a few pages.

![ios11-table-jump](https://user-images.githubusercontent.com/8739/30863328-12573bd0-a2d1-11e7-9f58-46431f198bc3.gif)

**Comment by frosty** [comment]
It seems to be a general iOS 11 issue with scrollviews and opaque nav bars: http://www.openradar.me/34465226

**Comment by frosty** [comment]
I don't see this happening any more on newer versions of iOS.
