### ISSUE TITLE
Duplicate notifications in internal build

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-iOS#7853]
@astralbodies reported duplicate notification in the internal app build

<img width="884" alt="notifi" src="https://user-images.githubusercontent.com/728822/30895549-eb10d940-a385-11e7-8482-715b9429501c.png">

**Comment by elibud** [comment]
@astralbodies are you still seeing this or was it a one off?

**Comment by astralbodies** [comment]
It only happened that once so the condition isn't easy to reproduce and hasn't happened again yet.

**Comment by elibud** [comment]
I'm going to close this one then, thanks.
