### ISSUE TITLE
Aztec: Post title field is not scrolled automatticaly when typing long titles

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-iOS#7876]
Steps to reproduce:

> 1. Write a new post
> 2. Start typing a long title, to the point where it overflows and does not fit in screen
> 3. You will see that after a certain point, text is being typed but the editor is stuck to the top of the page and does not scroll automatically as we type more text.

> In the screenshot you can see, I’ve typed more text but the editor continues to show me first word of the title (akaka..) and hides the most recent word I’m typing.
> Solution: It should scroll as we type!

![img_0018](https://user-images.githubusercontent.com/728822/30996215-19e84ef4-a4fa-11e7-8d85-432a531ff599.png)

**Comment by designsimply** [comment]
Tested and confirmed that the title area is inaccessible and cannot be scrolled to if it is longer than can appear in the visible space allotted on screen for the title.

<img src="https://user-images.githubusercontent.com/1119271/70093744-4e5f1a80-15de-11ea-8d4e-ac3030532d52.PNG" width="270" alt="IMG_3160">
<sup>Tested with WP Internal 13.8.0.20191202 MS App Center beta on iPhone 6S iOS 13.2.3.</sup>

**Comment by designsimply** [comment]
In further testing, I found that this problem does not happen in the block editor. 

Closing in favor of https://github.com/wordpress-mobile/AztecEditor-iOS/issues/872.
