### ISSUE TITLE
Long site/url interfering with action buttons in Editor

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#7878]
### Expected behavior
If I had a long site title or URL (in the case of an empty site title), I would expect to still see the publish button in portrait mode in the Editor.

### Actual behavior
The Publish button is either not available or overrun with text.

### Steps to reproduce the behavior
1. Set a long site title (I used "This is a long site title I mean who would write something...")
2. Open the editor

Neither the "X" to exit the editor or the Publish action are available:

<img width="757" alt="screen shot 2017-09-29 at 10 30 54" src="https://user-images.githubusercontent.com/7240478/31025819-4f251294-a501-11e7-89d5-d601b21d6658.png">

**Comment by elibud** [comment]
Pinging @diegoreymendez @jleandroperez @SergioEstevao

**Comment by sarahblackstock** [comment]
Users in app support reporting inability to publish, due to not seeing the buttons. Am instructing them to rotate their phone to see them in landscape for now, until this can be updated.

internal ref: #230701-h & #230449-h

**Comment by elibud** [comment]
Thanks @sarahblackstock we are pushing a new release later today so the fix should be available for users updating their app tomorrow.

**Comment by sarahblackstock** [comment]
Awesome, @elibud! Thanks. :D

**Comment by elibud** [comment]
Version 8.5.2 submitted to the AppStore, should be available for download tomorrow.
