### ISSUE TITLE
Small unexpected jumps when opening new media picker in Editor

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#7880]
This might be related to #7710, and it might be the expected occurrence, but it felt a bit weird to me.

### Expected behavior
If I have an image in a post already and I open the media picker to add another, I expected it to fluidly open without adjusting the editor.

### Actual behavior
The editor has a slight jump.

### Steps to reproduce the behavior
1. Open a new post.
2. Add an image from the media picker.
3. Add some text.
4. Click the + icon to add another image.

You should see a slight jump.

![jumpyjump](https://user-images.githubusercontent.com/7240478/31025952-c6123896-a501-11e7-9dd3-10e1d89d97df.gif)

**Comment by kean** [comment]
The UI has changed, so this issue is now obsolete.
