### ISSUE TITLE
Header partially reverses style when deleting up to a space and typing again

### ISSUE THREAD

**Issue by folletto** [wordpress-mobile/WordPress-iOS#7907]
![img_aa437a403935-1](https://user-images.githubusercontent.com/4389/31186365-59764c6c-a926-11e7-84e1-0b772fe57d5c.jpeg)

1. Edit a post
2. Go on new line (empty)
3. Header → H1
4. Type "One two"
5. Delete " two", space included
6. Type " three"

Sometimes after this the cursor tends to stay "tall" even if the paragraph reverted to default, but I can't reproduce this reliably.

Tested on iPhone 6, 8.5.0.20170929

**Comment by jleandroperez** [comment]
Fixed via [this](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/752) and [this](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/7670) Aztec PR's.

Thank you @folletto!!
