### ISSUE TITLE
Gap above input views when using hardware keyboard w/ iPhone X

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#7916]
Note: We've decided to hold off working on this bug until we have iPhone X devices, just in case keyboard handling behaves any differently there vs the simulator. We also figure that a) the number of people who actually own iPhone Xs + b) the number of people who connect a hardware keyboard to their phone will be suitably small this this bug will affect very few people.

On iPhone X, with a hardware keyboard connected, if you tap a button that displays an input view (+, H, or list) the input view is displayed with a gap at the top:

![input-view-x](https://user-images.githubusercontent.com/4780/31278907-d9abdebe-aa9e-11e7-91b3-083ad987b6b9.png)

Using the view inspector, the toolbar appears to be the correct height, but the input view's superview has an extra view at the top taking up that space.

<img width="650" alt="input-view-x2" src="https://user-images.githubusercontent.com/4780/31280417-349f29e8-aaa4-11e7-8eea-60f8c0181569.png">

**Comment by rachelmcr** [comment]
We received an internal report of the same issue on iPhone X (internal ref: p4a5px-25N-p2).

**Comment by SergioEstevao** [comment]
@frosty is this still an issue?

**Comment by frosty** [comment]
Just tested this in the simulator, and I think it looks okay now.
