### ISSUE TITLE
Magnifier issues in the post editor.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7931]
Es reported by a user:

> in the iOS where there is editable text you should be able to hold a finger on the text and the magnification loupe appears just above your finger. You then drag so the insertion point moves between letters. However holding on text does nothing until you remove the finger from the screen, the magnification loupe appears for a split second after the finger is removed and the black horizontal menu options appear.

Additional info by our internal user:

> I tested this on my iPhone and was able to replicate what they are describing. Steps to reproduce:
> 1. While editing a post tap and hold onto some text
> 2. After a few second remove your finger from the screen
> 3. For a quick moment the magnifier will appear, and then disappear being replaced by the menu bar.
>
> I switched to the old editor and the magnifier does work there. So the problem seems isolated to Aztec.
>
> iOS – 11.0.2
> WordPress – 8.4
> editor – Visual 2.0

**Comment by jleandroperez** [comment]
Closing in favor of [this Aztec Issue](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/765), since the fix needs to be placed in Aztec's codebase.

Thanks Diego!
