### ISSUE TITLE
Break + Non breaking space being stripped from the post contents.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7932]
As reported by @rachelmcr:

> iOS: Some HTML tags are removed when the post is updated
>
> Steps to reproduce:
>
> 1. Use the Visual 2.0 editor.
> 2. Create a post and in HTML and type:
> `<br>&nbsp;`
> 3. Update the post. The HTML disappears.

I've tested this in Calypso too, and it seems it's also stripping the content.  This is leading me to believe the problem may be introduced by the code [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessorIn.swift#L15) or [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Aztec/Processors/CalypsoProcessorOut.swift#L16), since it's logic we borrowed from the backend.

PS: while we can try to fix this in our end, we can't ensure the same logic isn't run in the backend, or in Calypso.

**Comment by catehstn** [comment]
This came up in support. Example:

`<a href="https://itunes.apple.com/us/app/wordpress/id335703880?mt=8" style="display:inline-block;overflow:hidden;background:url(https://linkmaker.itunes.apple.com/assets/shared/badges/en-us/appstore-lrg.svg) no-repeat;width:135px;height:40px;background-size:contain;"></a>`

Note: this also disappears in Calypso / WP Admin. I wonder if it would be covered by embed support?

**Comment by salty-horse** [comment]
The `<a>` tag above renders if the tag has content, such as `&nbsp`

**Comment by sarahblackstock** [comment]
The same user from this original report came back since they are no longer able to switch editors in the app but are still having this problem. 

> Hard to blog when I lose my html code between saves.

Said the issue is the same as when they originally reported it. (There are screenshots in the issue in case those would be helpful to share somewhere.)

internal ref: #222357-h

**Comment by diegoreymendez** [comment]
@catehstn - I believe we should discuss that one separately as there's a specific reason for that issue you're seeing.

The reason why we're losing those `<a>` tags is that they're empty until / unless you parse the CSS, for which we have very limited support right now.

I'd need @maxme to take a look at this from the product owner's perspective to decide if we want to extend our CSS support.

**Comment by SiobhyB** [comment]
This also came up in 247417-h. In that ticket, the user provided an example of a post in that ticket. I was able to replicate the problem by copying/pasting the post to my test site in a web browser then opening it up within the app. The <p> tags were automatically stripped out.

**Comment by catehstn** [comment]
Agree, I don't think we need to support empty HTML tags (as neither Calypso nor WP-Admin do either).

**Comment by PatrikHax** [comment]
Why can you not just have the function where you can choose if you want HTML or not when opening the app? It worked fine for several years but has now been broken for several months now.. :)

**Comment by catehstn** [comment]
@PatrikHax We deprecated the old editor, and replaced it with a shiny new one, that is a much better experience for the **vast majority** of users. We're learning about quirks of the legacy editors that people relied on, and it would be helpful for us to understand what problems this change has caused for you so we can triage and address those directly, rather than supporting workarounds.

**Comment by SiobhyB** [comment]
This came up again in 264972-h. The user in that tickets would prefer to see the full HTML that they've entered, rather than seeing the p tags stripped out.

**Comment by diegoreymendez** [comment]
It seems a lot of different requests are popping up in this issue.  Let's make sure that requests posted here refer to the issue initially reported (`<p>&nbsp;` being removed) (not just any tag being lost or removed).

I'll edit the title to make sure this issue is a bit less generic.

@SiobhyB - As for the P tags being removed, I agree with the user.  Unfortunately the stripping is by design and will not change unless the core editor changes that behavior.

**Comment by salty-horse** [comment]
Should a new bug be opened for empty elements being removed?

**Comment by diegoreymendez** [comment]
@salty-horse - This issue's initial description doesn't really mention empty elements.  The discussion that followed did.  Opening a new issue would help us focus the discussion a bit more.

**Comment by diegoreymendez** [comment]
Small update: some of the recent issues with paragraphs being merged together will be solved by this PR: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1006

**Comment by rachelmcr** [comment]
We took another look at this issue, related to some recent changes and with an eye toward Gutenberg. While this is still not resolved, it may not be an issue once Gutenberg fully launches.

Gutenberg includes a `spacer` block to add empty space between elements — that should remove the need to use `<br>&nbsp;` to create empty space in posts.

**Comment by diegoreymendez** [comment]
Part of this issue was fixed by https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1082

Non breaking spaces are no longer removed.  The line breaks are a different story, but a new issue can be opened if necessary.  Closing for now.
