### ISSUE TITLE
Featured image stopped working

### ISSUE THREAD

**Issue by snoopas** [wordpress-mobile/WordPress-iOS#7943]
### Expected behavior
For several years and up to few iOS versions ago, I could create a post on iOS, insert a pic and thanks to a plugin on the server side, that post would be published automatically with the image as feature image.
For info: when I do create post with browser and insert pic, the system does automatically use the pic as feature image.

### Actual behavior
The iOS app sends the post and says everything is fine. However, when connecting to the site, there is not feature image. I need to get into backend and set the pic as feature image and finally, update.

### Steps to reproduce the behavior
Check above.

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 7, 11.0.2, latest WPiOS

**Comment by elibud** [comment]
Hi @snoopas can you let us know which version of the editor are you using? 
You can see that on Me->App Settings->Editor And also, which plugin was turning the post image into the featured image?
Thanks

**Comment by snoopas** [comment]
Hello,

Thanks for taking care of this, it is driving me nuts:-)

I’m using “Visual”… do you want me to try another mode?

Cheers,

**Comment by elibud** [comment]
Can you please try our new editor, Visual 2.0? Also, by any chance do you remember approximately when did it stop working?
Thanks

**Comment by snoopas** [comment]
hello,

so it did not work with visual 2.0. app posts and says all is ok but on the website, the image doesn’t appear. i need to log into my server, edit the post, add feature image and update post.

it stopped working something like one month ago…

let me know if we want me to test something else or even make a movie of something in particular.

cheers,

**Comment by elibud** [comment]
Can you let me know which plugin are you using on your site to process the posts? Thanks

**Comment by snoopas** [comment]
plugin is this one:



and for information, this is the code within “edit” (that i never modified):

<?php
/*
* Plugin Name: Easy Add Thumbnail
* Plugin URI: http://wordpress.org/extend/plugins/easy-add-thumbnail/
* Description: Checks if you defined the featured image, and if not it sets the featured image to the first uploaded image into that post. So easy like that...
* Author: Samuel Aguilera
* Version: 1.1.1
* Author URI: http://www.samuelaguilera.com
* Requires at least: 3.7
*/

/*
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License version 3 as published by
the Free Software Foundation.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

if ( function_exists( 'add_theme_support' ) ) {

add_theme_support( 'post-thumbnails' ); // This should be in your theme. But we add this here because this way we can have featured images before swicth to a theme that supports them.
      
function easy_add_thumbnail($post) {
          
    $already_has_thumb = has_post_thumbnail();
    $post_type = get_post_type( $post->ID );    
    $exclude_types = array('');
    $exclude_types = apply_filters( 'eat_exclude_types', $exclude_types );

    // do nothing if the post has already a featured image set
    if ( $already_has_thumb ) {
    	return;
    }

	// do the job if the post is not from an excluded type			           
    if ( ! in_array( $post_type, $exclude_types ) )  {

        // get first attached image
        $attached_image = get_children( "order=ASC&post_parent=$post->ID&post_type=attachment&post_mime_type=image&numberposts=1" );

	    if ( $attached_image ) {

	        $attachment_values = array_values( $attached_image );
	        // add attachment ID                                            
	        add_post_meta( $post->ID, '_thumbnail_id', $attachment_values[0]->ID, true );                                 
	                        
	    }
                           
                         
    }

}

// set featured image before post is displayed (for old posts)
add_action('the_post', 'easy_add_thumbnail');
 
// hooks added to set the thumbnail when publishing too
add_action('new_to_publish', 'easy_add_thumbnail');
add_action('draft_to_publish', 'easy_add_thumbnail');
add_action('pending_to_publish', 'easy_add_thumbnail');
add_action('future_to_publish', 'easy_add_thumbnail');

}

?>

let me know if you need something else…

cheers,

**Comment by elibud** [comment]
Hey @snoopas can you let me know the url of your site? Also, have you recently connected the site via Jetpack in the app?

**Comment by snoopas** [comment]
Sure, here it goes:

www.snoop-adventures.com <http://www.snoop-adventures.com/>

As you can see, it is not a critical “content” but I’m missing that feature a lot.

That said, yes, Jetpack was always connected (since 4 or more years).

Let me know if you need some additional info.

Cheers,

**Comment by elibud** [comment]
Thanks, I need one more piece of info from you. On the app, are you logged in with your self hosted site credentials or with your WordPress.com credentials? You can check this by going to the Me tab and seeing if you have the option to Log In there.

**Comment by elibud** [comment]
@frosty @SergioEstevao handing over this issue after some investigation. So far all my testing indicates that we are not setting up the `post_ID` value on `Media` objects, and this seems to come back to the new `MediaService` changes.
If you compare `MediaService` vs `MediaService+Legacy` you can see that in the first one all media objects are created using the method `makeMediaWithBlog` but in the second one we use `makeMediaWithBlog` and `makeMediaWithPost` depending on the context, thus inserting the media in the post correctly. The fix should not be too complicated and I'm happy to help reviewing it and testing it but right now I don't have the context on this one to properly fix it in a reasonable timeframe.

**Comment by elibud** [comment]
Internal ref p2-p3hLNG-10y

**Comment by snoopas** [comment]
Thanks for the follow up Elisa.

Let me know if you want me to test anything… i also have a testflight account so if you want me to test a build, more than happy to join.

Cheers,

**Comment by elibud** [comment]
@snoopas we think this is a server side issue right now and the corresponding team is investigating, we'll keep you updated.

**Comment by snoopas** [comment]
Fine then, let me know how it goes.
Thanks for the support.
Cheers,

**Comment by elibud** [comment]
Hi @snoopas this has been fixed and it's going to be released on the next version of Jetpack, which is scheduled to go out on the second week of November. Thanks a lot for the report and all your help troubleshooting.

**Comment by snoopas** [comment]
oh that’s a good news!
thanks all for the efforts!
