### ISSUE TITLE
Unselected Notification Shows Placeholder UI

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#7985]
### Expected behavior
Reported by @astralbodies 
The placeholder notificaiton UI shouldn't be displayed when there's no notification populating it.

### Actual behavior
I launched my iPad Pro and went to the notifications tab and saw this placeholder UI. I think maybe a no-longer-existing notification was previously selected and when it wasn’t in the store the nil UI showed up?

![img_0043](https://user-images.githubusercontent.com/5558824/31626212-46590766-b27f-11e7-8e18-a7dad68581c8.jpg)

### Steps to reproduce the behavior
Unknown

##### Tested on IPad Pro, iOS 11, WPiOS 8.5

**Comment by elibud** [comment]
Hey @astralbodies any other clue on this one? I've tried deleting the selected notification outside of the app, then going back in and couldn't replicate it.

**Comment by astralbodies** [comment]
@elibud Do you know where the last selected notification is stored? Is it only part of the state restoration API data model? If it is you could put a crap notification ID into state restoration and then it should replicate this.

**Comment by elibud** [comment]
It is stored under `Restoration.noteIdKey` so this sounds like a good idea @astralbodies I will try it.

**Comment by elibud** [comment]
For non existing notifications the controller works correctly, displaying the last one. It's all properly handled in `extension NotificationDetailsViewController: UIViewControllerRestoration`

**Comment by elibud** [comment]
By looking at the code and doing some testing the only way I think this can happen is if a notification was initially delivered without all its data populated and it was cached like that. It might've been caused by an unreliable internet connection, unfortunately I have not been able to replicate the issue.
@astralbodies are you ok to close this one at least until we get another report with more clues?

**Comment by astralbodies** [comment]
@elibud Yup go for it! Thanks for trying 😄
