### ISSUE TITLE
Fix line / paragraph spacing

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#7998]
This is a sister issue to [this Aztec issue](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/547).

We should basically review line and paragraph spacing to synchronize it with Calypso.

**Comment by ChrissiePollock** [comment]
Another report #233370-h

**Comment by diegoreymendez** [comment]
Resolved in 8.6, in [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/8016).
