### ISSUE TITLE
Reader icon in main navigation is incorrectly sized

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#8005]
I noticed that the Reader icon is currently appearing too large. I'm not sure where the icon comes from, but the [source file in gridicons](https://github.com/Automattic/gridicons/tree/master/sources/svg-32) is correct. Let me know if I can help with converting it, etc.

<img width="699" alt="screen shot 2017-10-17 at 5 36 11 pm" src="https://user-images.githubusercontent.com/1396552/31692736-15214538-b369-11e7-98df-2a44a60074b2.png">

Blue is the current screenshot of the app; red is the correct size for the icon.

**Comment by elibud** [comment]
It looks like https://github.com/Automattic/gridicons/tree/master/sources/svg-32 was updated but we did not update on our side: https://github.com/wordpress-mobile/WordPress-iOS/tree/develop/WordPress/Resources/AppImages.xcassets/icon-tab-reader.imageset
We should probably update all of them. @frosty do you have instructions on how to do that? 

Thanks

**Comment by frosty** [comment]
So for some reason for the tab bar icons the PNGs are included with the app, at 32x32px, instead of using Gridicons to generate them. I guess we can probably switch them over. I'm happy to take a look.

**Comment by elibud** [comment]
Great, thanks a lot @frosty, really appreciate it.

**Comment by frosty** [comment]
@mattmiklic I'm going to drop the updated `svg-32` icons (converted to PDFs) into the app instead of using the Gridicons framework for these. Because the framework just scales the icons, and 32px isn't a multiple of 24px (it's 1/3 bigger), it results in a blurry image:

<img width="1265" alt="screen shot 2017-10-19 at 10 31 26" src="https://user-images.githubusercontent.com/4780/31764309-b4654c52-b4b8-11e7-874e-25f30c66220a.png">

**Comment by frosty** [comment]
@mattmiklic I've updated the Reader icon, but I've noticed that this now means it's smaller than all the other icons? Presumably I should update those too? If so, we'll need a copy of the notifications icon with the orange dot baked in, too. Would you be able to sort that out?

![icon-height](https://user-images.githubusercontent.com/4780/31764958-b5a83028-b4ba-11e7-826c-afd2496e5136.png)

**Comment by frosty** [comment]
@mattmiklic One more for you – I noticed that the icons currently used for the unselected state on the tab bar aren't being dynamically coloured at runtime. Instead, the colours are baked into the images.

I'm going to update things to use a named colour – could you clarify what they _should_ be? There's currently code in place to set them to `grey`, but that looks darker than the existing icons.

**Comment by mattmiklic** [comment]
Thanks @frosty! The icons in their unselected state should be `greyLighten10`.
