### ISSUE TITLE
How to show tableview when user taps searchbar Swift

### ISSUE THREAD

**Issue by Giggs123** [wordpress-mobile/WordPress-iOS#8026]
I spent a lot of time in order to find a solution but I didn't found it so I ask here for help me.

I have a ViewController with a button, when I press this button the searchController appears with a searchBar, when I start to type a letter in searchBar so the tableView of the tableViewController appears above the main view and below the searchController. But there's no result appears on the cell of the tableView because the cellForRowAt indexPath method isn't called.

The following code is for the ViewController :

`class ViewController: UIViewController, UISearchControllerDelegate, UISearchBarDelegate {

    var tableViewSearch: TableViewController!

    lazy var searchController: UISearchController = {
        let sc = UISearchController(searchResultsController: self.tableViewSearch)
        sc.searchResultsUpdater = self.tableViewSearch
        sc.delegate = self
        sc.searchBar.delegate = self
        return sc
    }()

    override func viewDidAppear(_ animated: Bool) {
        tableViewSearch = TableViewController()
    }

    @IBAction func searchWithAddress(_ sender: AnyObject) { // Ce qui affiche le SearchController
        self.present(searchController, animated: true, completion: nil)
    }
    }`

The following code is the TableViewController :

`        class TableViewController: UITableViewController, UISearchResultsUpdating {

          var userTab = [String]()
          var filteredUsers = [String]()
          var searchController: UISearchController!
          var resultsController = UITableViewController()
          var name: String!
          var ref: DatabaseReference!

    override func viewDidLoad() {
        super.viewDidLoad()
        self.resultsController.tableView.delegate = self
        self.resultsController.tableView.dataSource = self
        ref = Database.database().reference()

        ref.child("users").queryOrdered(byChild: "pseudo").observeSingleEvent(of: .value, with: { (snapshot) in
            self.userTab = []
                for child in snapshot.children { // Je récupère les pseudos de mes utilisateurs dans ma base de données puis je les place dans un tableau
                    let userSnap = child as! DataSnapshot
                    let uid = userSnap.key
                    let userDict = userSnap.value as! [String: AnyObject]
                    let pseudo = userDict["pseudo"] as! String
                    self.userTab.append(pseudo)
                    self.resultsController.tableView.reloadData()
                    continue
                }
            }
        })
    }

    func updateSearchResults(for searchController: UISearchController) {
        print("updateSearchResults")
        self.filteredUsers = self.userTab.filter { (user:String) -> Bool in
            if user.lowercased().contains(searchController.searchBar.text!.lowercased()) {
                return true
            } else {
                return false
            }
        }
        self.resultsController.tableView.reloadData()
    }

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if segue.identifier == "userProfil" {
            let userViewController = segue.destination as! UserViewController // Pour afficher le profil d'un utilisateur
            userViewController.pseudo = self.name!
        }
    }

    // Le nombre de ligne n'est pas égal à 0
    override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if tableView == self.tableView {
            return self.userTab.count
        } else {
            return self.filteredUsers.count
        }
    }

    // Cette méthode n'est jamais appelée
    override func tableView(_ tableView: UITableView!, cellForRowAt indexPath: IndexPath!) -> UITableViewCell {
        print("cellForRowAt") // This line is never printed on the console
        let cell = UITableViewCell()
        if tableView == self.tableView {
            cell.textLabel?.text = self.userTab[indexPath.row]
        } else {
            cell.textLabel?.text = self.filteredUsers[indexPath.row]
        }
        return cell
    }

    override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let post = filteredUsers[indexPath.row] as! String
        self.name = post
        performSegue(withIdentifier: "userProfil", sender: nil)
    }
    }`

Why the cellForRowAt indexPath method isn't called?
What's wrong in my code ?
How can I fix it?

**Comment by frosty** [comment]
Hey @Giggs123!

I think the best place to get some help for your question would be to post it to https://stackoverflow.com. It'll get seen by a lot more people who are there to answer questions just like this. I hope you find a solution!

**Comment by Giggs123** [comment]
I already posted it on stackoverflow but no one can't help me
