### ISSUE TITLE
Comments: No Comment Option Visible For .org sites in reader

### ISSUE THREAD

**Issue by harishankerr** [wordpress-mobile/WordPress-iOS#8027]
### Expected behavior

The comment button should display for posts from all sites in the reader (while viewing the same on the iOS App) - irrespective of the fact that the site is a Jetpack site, or a WordPress.com site. 

### Actual behavior

The comment button is missing on Jetpack sites, while browsing the same in the reader. However, while looking at WP.com sites in the reader, the comment button is present. Here's a screenshot that explains the issue better:

![http://cld.wthms.co/L88jEd](http://cld.wthms.co/L88jEd+) 
Full Size: http://cld.wthms.co/L88jEd

### Steps to reproduce the behavior

1. Follow a Jetpack site, and a site hosted on WordPress.com (with posts that are published recently to ensure that they are available in the reader).
2. Log in to WordPress.com from a desktop browser and proceed to the reader.
3. Compare buttons in the post from the Self Hosted site (linked through Jetpack), and the WP.com site - you will notice that the comment, like, and share buttons are available in both posts. 
![http://cld.wthms.co/PKaGSg](http://cld.wthms.co/PKaGSg+) 
Full Size: http://cld.wthms.co/PKaGSg
4. Now, open the WordPress.com iOS App, and ensure that you are logged in using the same ID, where you followed both the blogs (WP.com and self hosted).
5. Proceed to the `Reader`, and try viewing posts from the self hosted blog (Jetpack), and the one running on WordPress.com.
6. You will notice that the blog running on self hosted WordPress lacks a comment button this time.

![http://cld.wthms.co/L88jEd](http://cld.wthms.co/L88jEd+) 
Full Size: http://cld.wthms.co/L88jEd

##### Tested on iPhone 6S, iOS 10.3.3, WPiOS 8.5.2

**Comment by elibud** [comment]
Thanks for the detailed report @harishankerr. We already have a solution for this one [here](https://github.com/wordpress-mobile/WordPress-iOS/pull/7662/) and we are tracking the original issue [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/7660), so I'm closing this one.

**Comment by harishankerr** [comment]
Awesome - I did look for a replicated version of this issue before posting the same, but couldn't find the same. Guess I used the wrong tag (I searched using `comments` as a tag). 

Thanks for the prompt reply, and for the fix, @elibud! I appreciate it! 💯

**Comment by elibud** [comment]
@harishankerr we will be releasing a new internal version tomorrow with this feature on, please test it out if you have the time. Thank you :)
