### ISSUE TITLE
Jetpack Sites Plugin Browsing

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#8042]
Add native support for plugins browsing in the app. Design coming soon.

- [x] Update the plugin details screen to use the new design
- [x] Add version detail pop-up on the plugin detail screen
- [x] Add ratings view to the plugin detail screen
- [x] Plugin browsing endpoint
- [x] Create main page for Plugin Browser with Installed, Featured, Popular, New sections
- [x] Create a list view for all of the section above
- [x] Update the plugin details screen to support installing new plugins
- [x] Plugin search endpoint
- [x] Support searching for plugins
- [x] Add automanaged icon to automanaged plugins
- [ ] Add persistence

**Comment by jklausa** [comment]
Designs: https://betterjetpackxp.wordpress.com/2017/12/12/plugin-directory-design-i4/
