### ISSUE TITLE
Photos sharing extension

### ISSUE THREAD

**Issue by eliorivero** [wordpress-mobile/WordPress-iOS#8050]
When using the sharing extension that publishes to a WordPress site, it would be nice to have the ability to change how the image is related to the post.

### Expected behavior
- image is set as a Featured Image, that is, it's uploaded as an attachment and its attachment id is stored in `_thumbnail_id`

### Actual behavior
- image is uploaded but inserted as content

### Steps to reproduce the behavior
- go to Photos, share an image with the WordPress sharing extension

<img src="https://user-images.githubusercontent.com/1041600/31999898-4388f6fc-b96b-11e7-8f7b-f133115b346c.png" width=400/>

**Comment by bummytime** [comment]
Closing this in favor of #9070 and/or #8143
