### ISSUE TITLE
Tags don't load on .org sites

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#8053]
On the post options --> tags screen, the current tags are not loading for .org sites. .Com sites work as expected.

<img width="350" alt="tags" src="https://user-images.githubusercontent.com/154014/32012881-ff2d20c8-b97e-11e7-9105-b2c4903bdc36.png">

**Comment by elibud** [comment]
@koke would you mind taking a look at this one?
