### ISSUE TITLE
Writing links or image on HTML mode in Aztec uses smart quotes and then duplicates

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#8060]
### Expected behavior

- When writing content in HTML mode in Aztec smarquotes shouldn't be used

### Actual behavior

- Every time a quote is written is replaced by the smart quote characters
- Then when switching from visual and back duplicates the quote

### Steps to reproduce the behavior

- Start a new post using Aztec
- Switch to HTML mode
- Add a link `<a href="www.apple.com">Apple</a>` on html mode
- Switch to visual and then back to HTML
- See the quotes duplicated.

**Comment by happychait** [comment]
I just had a customer in 29975937-hc who is using Aztec editor in the HTML mode of their iOS app and reported this issue.

Looks like it resurfaced.
