### ISSUE TITLE
Login: Reuse one set of google keys in the app credentials file.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#8062]
In our app credential files, we currently include Google ID and Scheme keys for development/production builds, internal builds, and alpha builds.  Let's tweak this so there is only one ID and Scheme key and just update the values used for the respective build. 

h/t @SergioEstevao 
cc @nheagy

**Comment by SergioEstevao** [comment]
Yeah I agree that is the way to do it @aerych , we already have a configuration file for each type of build we just need to have one set of keys for each configuration file.

**Comment by diegoreymendez** [comment]
Just a reminder: if this is changes, remember to reflect those changes in the corresponding .plist files.

**Comment by diegoreymendez** [comment]
Moving to 8.9 temporarily following the PR, to move ahead with 8.8's code freeze.

Please feel free to retarget for 8.8 if appropriate, and sorry for the inconvenience.
