### ISSUE TITLE
Site list flashes briefly on fresh login

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#8065]
I think #3120 might be back or still occurring on fresh loads of the app.

### Expected behavior
I expected to only see the login screens when I open the app for the first time.

### Actual behavior
If I load the app fresh (or double click the home button, close the app, then open it again), I see a brief screen of "You don't have any WordPress.com sites."

Here's a GIF of the login:

![flash](https://user-images.githubusercontent.com/7240478/32107511-0a2cdf2c-baec-11e7-8d0a-4c2718b077e0.gif)

Screenshot of the page:

<img width="746" alt="screen shot 2017-10-27 at 7 47 51 am" src="https://user-images.githubusercontent.com/7240478/32107524-11ead05c-baec-11e7-98f0-aa93556b61de.png">

**Comment by elibud** [comment]
Hi @jeremeylduvall thanks a lot for reporting this, a new internal build is on its way.

**Comment by elibud** [comment]
Sorry updated the wrong issue
