### ISSUE TITLE
Crash: Google login link crashes the app consistently

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#8066]
I was looking to test out the Google login, but it crashes the app every time I click on it.

### Expected behavior
To open my browser so I can login

### Actual behavior
The app crashes. I tried removing and re-downloading the beta app as well, but that didn't seem to help.

### Steps to reproduce the behavior
1. Download the beta app.
2. Open beta app and click "Log In"
3. Click "Log in with Google."
4. 💥

### GIF

![crash](https://user-images.githubusercontent.com/7240478/32107753-c8d4bc1a-baec-11e7-825a-2d19ccfb5b77.gif)

**Comment by elibud** [comment]
Hi @jeremeylduvall thanks a lot for reporting this, a new internal build is on its way.
