### ISSUE TITLE
Changing orientation in media importer causes odd media panel height on returning to editor

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#8067]
This is a bit of an edge case, but if you change the orientation while in the media selector, the app returns to the editor with a different media panel height.

### Expected behavior
I expected the behavior to be the same regardless of whether I changed the orientation while selecting media from other apps.

### Steps to reproduce the behavior
1. Start in landscape mode in the editor.
2. Use the + icon to open up the media picker
3. Use the ellipses icon to open up the file selector.
4. Hit cancel to return to the editor. Note the height of the media panel when you return.
5. Keep the iPhone in portrait mode.
6. Click the + icon again and use the ellipses to open the file selector.
7. Rotate the phone to landscape while in the file selector.
8. Hit cancel to return to the editor.

You'll notice that the media panel is at two different heights. The squished height is the result of rotating the phone while in the media selector.

**Initial**
![img_4244](https://user-images.githubusercontent.com/7240478/32108264-5f369b0a-baee-11e7-9aaf-1a71625ccb83.png)

**Squished**
![img_4243](https://user-images.githubusercontent.com/7240478/32108270-661f80da-baee-11e7-9c8b-50592f71397a.png)

**Comment by elibud** [comment]
@SergioEstevao @frosty can take a look at this one? Thx

**Comment by frosty** [comment]
@bummytime Will this be related to the keyboard height changes we made?

**Comment by bummytime** [comment]
@frosty It totally is. This is prolly using the sizing logic from #7768 — specifically [this](https://github.com/wordpress-mobile/WordPress-iOS/blob/c3cc4181b704ffda71276963e56143daad7a0b53/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L2606) where we are using a default height in landscape because the calculated size is too small. 

This is a valid issue, nice find @jeremeylduvall!

**Comment by bummytime** [comment]
Also just noticed this which is probably related:

![keyboard_bug](https://user-images.githubusercontent.com/154014/33719656-18137e1a-db27-11e7-8e03-a1dae0665a77.gif)

**To repro:** 
1. Start a post in portrait
2. Add a media item to the content body, in the media picker select the ellipsis to bring up the file picker.
3. Leaving the file picker up, rotate to landscape.
4. Tap cancel.
5. See the picker reappear taking up the entire screen.

We probably need to re-look at the keyboard frame calcs from #7768 _or_ at least have a maximum size sanity check along side the minimum size check that is there now.
