### ISSUE TITLE
Media overlay icon is not removed when another media item is selected

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#8068]
The pencil icon from the overlay is sticking around after another media attachment is selected within the editor.  This issue does not occur within the Aztec demo. 

![media_overlay_issue_8 7](https://user-images.githubusercontent.com/154014/32118643-09a53df2-bb18-11e7-81bf-da86d8bdcf5f.gif)

Occurs on both iOS 10 & 11, device and sim.

**Comment by jleandroperez** [comment]
Closed via #8070 by @bummytime
