### ISSUE TITLE
Login: Required "client_id" parameter is missing for Saved Password login

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8072]
### Expected behavior

I expect to be able to log in to the app with a Safari Saved Password.

### Actual behavior

When I try to log in with a saved password, I get the error `The required "client_id" parameter is missing`. (This is in the latest WP Internal beta.)

### Steps to reproduce the behavior

0. Ensure you have WordPress.com credentials saved in your Safari saved passwords.
1. Open the app (logged out) and select "Log In."
2. Select a saved password to log in.
3. Use Touch ID to fill the password when prompted.
4. Result: The error appears. Dismissing the error leads to a login screen with the username prefilled and an empty password field.

##### Tested on iPhone 6, iOS 11.0.3, WPiOS 8.7.0.20171023

**Comment by elibud** [comment]
Hi @rachelmcr can you please update the internal version of the app directly from Hockey App? We pushed a new version out on Friday, but for some reason the prompt to update doesn't seem to be displaying correctly for all users. I think what you reported here is sorted on that version.

cc: @diegoreymendez @frosty @nheagy

**Comment by rachelmcr** [comment]
Ah yeah, I thought there was a new version but when I didn't see the prompt to update I thought I was mistaken. I updated directly from Hockey App to version 8.7.0.20171027 and this issue is resolved there. Thanks!
