### ISSUE TITLE
Login: Canceling the Google/WordPress.com account connection leads to unresponsive screen

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8073]
### Expected behavior

I expect that if I cancel out of the Google login flow I can continue using the regular WordPress.com login flow instead.

### Actual behavior

If I start to log in with a Google account that isn't yet connected to a WordPress.com account, and I cancel the process when the WordPress app asks me to enter my account password (to connect the two accounts), I am taken back to the WordPress.com login screen but it is unresponsive.

### Steps to reproduce the behavior

1. Open the app (logged out) and select "Log In."
2. Select "Log in with Google."
3. Log in to Google using a Google account that is not yet connected to a WordPress.com account (but where the email address matches an existing WordPress.com account).
4. On the WordPress app screen that says, "To proceed with this Google account, please first log in with your WordPress.com password," tap the Back button in the top left.
5. Result: You are taken back to the initial WordPress.com login screen with your Google email address filled in and the screen is unresponsive.

### Screenshots

After logging in to Google:

![2017-10-30 16 11 14](https://user-images.githubusercontent.com/8658164/32185835-430dbf9c-bd98-11e7-8829-9d5a78258793.png)

After tapping Back:

![2017-10-30 16 13 46](https://user-images.githubusercontent.com/8658164/32185852-4ab36198-bd98-11e7-8560-431cd54aea7f.png)

##### Tested on iPhone 6, iOS 11.0.3, WPiOS 8.7.0.20171027

**Comment by aerych** [comment]
Fixed in #8075
