### ISSUE TITLE
Update individual media settings to new design

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#8081]
The individual media settings detail screen is getting a new design:

## Settings From Editor

<img width="1209" alt="screen shot 2017-10-31 at 5 08 29 pm" src="https://user-images.githubusercontent.com/154014/32251250-31de3be0-be5e-11e7-9f98-2d89e897a3ae.png">

1. Media detail
2. Image size settings
3. Image alignment settings
4. Full-screen image preview

## Settings From Media Library

<img width="1539" alt="screen shot 2017-10-31 at 5 08 41 pm" src="https://user-images.githubusercontent.com/154014/32251264-4430d6f4-be5e-11e7-95b2-e8f3349e1b07.png">

1. Media Library
2. Media detail
3. Delete confirmation alert
4. Deleting progress alert
5. Deleted success alert

## Other Media Types

<img width="1050" alt="screen shot 2017-10-31 at 5 02 36 pm" src="https://user-images.githubusercontent.com/154014/32251300-6fcb6c66-be5e-11e7-9e55-bbfc822ba3da.png">

Other media types share the same layout as images, but there are a couple differences:
- Video and Audio items’ detail pages have `gridicons-play` on their previews
- Docs have `gridicons-pages` on the preview

## Media Settings Fields

Fields are slightly different for each media type, and coming from the Editor should contain additional Customize fields.

## Fields
There are 3 types of fields:

- Customize: fields that contain info customizable to a post or page they’re in (on images, think “alignment” “size” etc.)
- File Details: fields that are editable like Title, Caption, etc.
- Metadata: fields that are not editable like file URL, file type, etc.

## Copying URL
The user should have the ability to copy a media item’s URL by tapping the [Copy] button provided in the URL table row cell under metadata. Note that the URL is truncated in the middle of the file name.

<img width="895" alt="screen shot 2017-10-31 at 5 12 52 pm" src="https://user-images.githubusercontent.com/154014/32251382-c91ae1ca-be5e-11e7-973a-957d41f984ec.png">

Ref #8063

**Comment by KokkieH** [comment]
We've had someone in the [WordPress.com forums](https://en.forums.wordpress.com/topic/tapping-pic-to-see-uncompressed-version/#add-note) looking for the ability to copy the URL in order to hyperlink the image.

**Comment by kean** [comment]
Obsolete – this screen was reimplemented in one of the previous versions.
