### ISSUE TITLE
App crashes when keychain data is lost

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#8098]
When keychain data is lost for a logged-in account (say, when setting up a new phone from backup) the app first show a password screen, then afterward crash on launch.

![image uploaded from ios](https://user-images.githubusercontent.com/517257/32381390-2cd9acc6-c078-11e7-8965-657630aff856.png)

Without investigation I suspect there are two fundamental problems:
1. When the password prompt is shown, it's not properly saving the password. This may be caused by changes in the new login flow.
2. Fundamentally, the app should not crash when keychain data is missing.

**Comment by dougaitken** [comment]
Finally got a video os this happening. Oddly apparently user could log into the app after reinstalling, and then this happened "the next day".

screencast (thankyou iOS 11!!!) http://cld.wthms.co/U4GMex

that dialog is dismissing itself, you can't hit cancel or delete fast enough. 

I've enabled extra debug on the app for if this happens again.

**Comment by dartiss** [comment]
@dougaitken - had this exact scenario happen to me yesterday. Captured a video of it.

Had got a new phone and restored from iCloud. Launching WordPress app for the first time presented the above screen. No login showing and wouldn't accept my password. Couldn't move to other screens.

Had to re-install from scratch to get it to work.

Of all the apps I'm running, this was the only one that had any issues after the restore. Give me a shout if you need to know any more.

**Comment by nheagy** [comment]
More info in #8262

**Comment by bummytime** [comment]
Fixed in #8281
