### ISSUE TITLE
Login using 1Password is sometimes failing.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#8102]
**Steps to reproduce:**

1. Log out from the app if you're logged in.
2. Tap in the 1Password icon to select your credentials.

Expected result: the login field is populated, and the App logs you in.
Actual result: Some of the times nothing happens, and the credentials are not populating the fields.

Tested in 8.7

Ping @aerych, @nheagy

**Comment by aerych** [comment]
Heya @diegoreymendez 
I tried to reproduce this on an iPhone 6s, iOS 11.0.3.
1Password is configured with my test account, but with a username not a password.
For the test I’m tapping the 1Password button on the email screen’s textfield.
Everything seems to be working for me when I try. 5/5.
Maybe we're doing something different or have a different setup?

**Comment by aerych** [comment]
Tested this again, this time with iOS 11.1.1 and the latest `develop` branch.  Same results, successful 5/5.

**Comment by diegoreymendez** [comment]
@aerych - I'll try to repro on my device tomorrow and see if I spot any extra bit of info... or even try to debug myself.  Just hold on a bit longer before closing.

I wouldn't be surprised to see this fixed from 1P's side in the current version.

**Comment by aerych** [comment]
Thanks @diegoreymendez.  I wouldn't close until we all agreed it was no longer an issue.  Just because I haven't been able to repro doesn't mean the bug doesn't exist. :)

**Comment by elibud** [comment]
Maybe 2FA has something to do with it? I've just tried this and it worked fine with a 2FA enabled account on prod.

**Comment by diegoreymendez** [comment]
Fyi @aerych - I couldn't reproduce this problem in our last 8.7 release.  I can only reproduce it reliably in our latest 8.8 internal.

**Comment by diegoreymendez** [comment]
I noticed while testing this that after tapping on my login item in 1Password, it would close almost immediately.  This led me to consider that maybe the 1Password extension was crashing, and our fields weren't getting filled because of it.

From the notes of the latest version of 1Password for iOS:

```
We eliminated a crash that would occur when using the 1Password Extension to fill credentials in Safari and third party apps.
```

After updating, all is working fine.

**Comment by aerych** [comment]
Thanks @diegoreymendez  :)
