### ISSUE TITLE
Themes: isAdmin has been removed, removing the ability to remove themes option for non-admins

### ISSUE THREAD

**Issue by pivotal-rebecca** [wordpress-mobile/WordPress-iOS#811]
This commit (https://github.com/wordpress-mobile/WordPress-iOS/commit/6a49522394c9b717477d0b957f1917e623155a57) that removes isAdmin, 

We used isAdmin in order to tell if the user had the permission to change the blogs' themes: https://github.com/wordpress-mobile/WordPress-iOS/blob/feature/ios7-themes/WordPress/Classes/BlogDetailsViewController.m#L265 which toggles the visibility of the themes option. The purpose is to prevent non admins from attempting to change themes, and receiving an error messages.

There are two options I can see now: 
1. Make the admin status of a blog accessible somehow again 
2. Remove the conditional showing of themes, and if the user tries to access the option, they will get an error message (403, I believe)

**Comment by rachelmcr** [comment]
I checked the new Themes browser being developed for 5.8, and the Themes section only shows to admin users. As an author, editor, or contributor on a site I'm unable to view that section. Closing this issue.
