### ISSUE TITLE
Themes: Themes section missing from My Sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8114]
### Expected behavior

I expect to see a Themes section for WordPress.com and Jetpack sites under My Sites.

### Actual behavior

There is no Themes section for WordPress.com sites.

### Screenshots

Current behavior in 8.7:

![2017-11-08 13 12 23](https://user-images.githubusercontent.com/8658164/32550933-bc30c3ca-c486-11e7-8914-c4685e133f4a.png)

Missing section in 8.8 beta:

![2017-11-08 13 12 09](https://user-images.githubusercontent.com/8658164/32550942-c3f5559e-c486-11e7-8166-7e1a47eef174.png)

##### Tested on iPhone 6, iOS 11.1, WPiOS 8.7 & 8.8.0.20171106

**Comment by ScoutHarris** [comment]
Fixed with #8115
