### ISSUE TITLE
First View/Preview of a post results in Calypso Reader being loaded

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#8117]
<img width="666" alt="napkin 56 11-08-17 11 13 14 am" src="https://user-images.githubusercontent.com/154014/32563396-c687c9be-c476-11e7-8863-212f8c2a95ff.png">

### Expected behavior
On a .com login when previewing or viewing a post, the internal browser should launch and show the post.

### Actual behavior
The first time a post is viewed/previewed after launching (not resuming) the iOS app, the user is sent to Calypso Reader instead of the post in question. If the internal browser is closed and relaunched, the preview works as expected. The correct preview URL appears to be used.

This happens consistently after initial launch of the app — observed anywhere a post can be viewed/previewed:

* My Sites > Blog Posts > View a post
* Editor > … menu > Preview
* Post-publish screen > View Post

**Note:** This does not appear to be an issue when "View Site" is launched from the Site Settings screen.

Demo video of it here: https://cloudup.com/cA8OEK3cmGO

### Steps to reproduce the behavior

1. Launch WPiOS (make sure you are not resuming it) with a .com login
2. Navigate to the post list and tap view
3. See the internal browser launch with the Calypso Reader visible
4. Close the internal browser
5. Redo step 2 ^
6. See the internal browser launch with the post visible

**Comment by koke** [comment]
This was fixed in #8128 but it didn't auto close
