### ISSUE TITLE
Reader: rename "Posts I Like" to "My Likes" 

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#8129]
When selecting a stream in the Reader, the label for liked posts is currently "Posts I Like." This should be updated to "My Likes" to match the Reader on the web.

**Comment by aerych** [comment]
Related: https://github.com/wordpress-mobile/WordPress-Android/issues/6848

**Comment by aerych** [comment]
@mattmiklic  In this case we're showing the title that's passed down from the REST API.  We'll make the change there.

**Comment by aerych** [comment]
Deployed.
