### ISSUE TITLE
Incorrect Error Message when using 2FA and 1password

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#8130]
First off, let me say this is a pretty edge case scenario, but it is something I keep running up against.  Essentially what happens is if you are trying to log into a WordPress.com account on iOS and are using 1password, if you fail to log in correctly the first time (you are offline, or you choose the wrong login from 1pass) when you get to the 2FA page you will be presented with an error message that represents the original failure to login, even though you have successfully gotten to the 2fa page.  

I've managed to make this happen in the two ways mentioned before, being offline when starting the login process or choosing the wrong username/password from 1pass.  In the end you are still able to login, but the error message that appears should not be appearing.

### Steps to reproduce the behavior
1.  Go to the log in page with an account that has 2FA and 1password.
2. Click on the 1Password icon in the email field
3. Choose the a different login then the one that is actually the correct wpcom username/password, so that you fail to be able to authenticate into WordPress.com
4. Now choose the correct login

You will be taken to the 2FA screen and see this error message.
![img_0068](https://user-images.githubusercontent.com/22015538/32693095-e2e2bf7a-c6e1-11e7-91c7-e84ad9d8f906.png)

To reproduce this error message the other way I mentioned follow these steps

1. Remove your iOS device from the internet
2.  Go to the log in page with an account that has 2FA and 1password.
3. Click on the 1Password icon in the email field
4. Select your WordPress.com login (this works with the correct or incorrect login)
5. Reconnect to the internet
6. Now choose your login again

You should see this error, even though you are online now.
![img_0069](https://user-images.githubusercontent.com/22015538/32693150-014e497e-c6e3-11e7-85cd-d418463bad37.png)

**Comment by aerych** [comment]
In the first scenario, it sounds like we should probably be resetting any credentials previously stored in `LoginFields` when the 1Password feature is used. @nheagy does this sound right to you? 


In the second scenario.... how long between reconnecting to the internet and retrying?   I'm not sure if it matters but just trying to account for the variables.   Seems like `Reachability` would just detect the change when it happened but maybe there's something more that needs to be done.

**Comment by charliescheer** [comment]
Pretty quickly.  When I first found the second error I was in airplane mode when I tried to login, and and disabled airplane mode with out exiting the app and the error appeared.
I have made a video of how I am able to replicate the problem.  

https://charlietestsiteblog.files.wordpress.com/2017/12/screenrecording_12-06-2017-13-35-51.mp4
