### ISSUE TITLE
Display a warning about breaking permalinks when changing post dates

### ISSUE THREAD

**Issue by jklausa** [wordpress-mobile/WordPress-iOS#8133]
While doing my support rotation, a user came in with a question on how to change a date for a published post.

I tried doing it in Calypso, and it popped up this helpful message: 
<img width="734" alt="screen shot 2017-11-13 at 13 19 28" src="https://user-images.githubusercontent.com/1594081/32725418-4fba64c4-c875-11e7-8baa-ef34d688f612.png">

(alt-text: "Are you sure about that? If you change the date, existing links to your post will stop working.")

We currently don't have anything like this in the iOS app and it seems super counter-intuitive that just a date change would break the permalinks.

**Comment by rachelmcr** [comment]
> With wpcom sites now, the permalink updates, but a redirect is created that will take you from the old address to the new one.

I confirmed that this redirect works on all site types (WordPress.com, Jetpack, self-hosted) when I change the post date — it was implemented in this core changeset: https://core.trac.wordpress.org/changeset/42589

Closing as resolved.
