### ISSUE TITLE
Share Extension: Modular Site Picker - Tags Module

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#8141]
<img width="292" alt="screen shot 2017-11-14 at 8 33 05 am" src="https://user-images.githubusercontent.com/154014/32785178-784a04ca-c916-11e7-9856-dec64cd1229b.png">

* Allow the user to enter tags (follow tags UI from post options)
* Fetch existing tags for site from server (synchronously)

Depends on: #8139

**Comment by bummytime** [comment]
@folletto Quick question re: tags. Since tags on sites can differ, would you expect the tags to get cleared when a customer switches sites:

![tags](https://user-images.githubusercontent.com/154014/36343796-2c033f40-13d6-11e8-8557-1162eb9679de.gif)

**Comment by bummytime** [comment]
Also @folletto, is this the look and feel you were going for in your design?

![tags2](https://user-images.githubusercontent.com/154014/36343958-d8b23a50-13d8-11e8-8326-b9be63b6950f.gif)

**Comment by folletto** [comment]
> Quick question re: tags. Since tags on sites can differ, would you expect the tags to get cleared when a customer switches sites:

Good question. 

I'd go back to the definition of tags as meta-data that is associated with the content, not made to map an existing ontology (which would be "Categories").

I'd thus make the tag persist across site changes.

> is this the look and feel you were going for in your design?

That's excellent.

One TINY change, but only if it's not too much work: would be possible to switch from the lighter gray to the normal text dark gray when there are tags?

As in:

* "Add tags" — light gray (as you did)
* (any tag) — dark text gray (same gray as "Tags" on the left)

**Comment by bummytime** [comment]
@folletto Thanks for the feedback. All of that ☝️ is doable!
