### ISSUE TITLE
Share Extension: Modular Site Picker - Categories

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#8142]
<img width="293" alt="screen shot 2017-11-14 at 8 34 09 am" src="https://user-images.githubusercontent.com/154014/32785226-9eee1648-c916-11e7-9286-096809620b1f.png">

* Allow the user assign category for a post (follow site categories UI in site settings)
* Fetch existing categories for site from server (synchronously) 

Depends on: #8139

**Comment by bummytime** [comment]
@folletto Here's a WIP view showing the default category loading for a selected site:

![cats](https://user-images.githubusercontent.com/154014/36506933-af6cfb42-171d-11e8-8a63-cda3fc1a01b1.gif)

Misc comments/questions for ya:

* As you can see when changing the selected site, the category cell temporarily clears because 2 separate network calls are needed to fetch the default category ID and then list of site categories. Obviously we can cache these, but I wanted to show you what first load looks like.

* The accessory chevron is hidden when there is only a single category for a given site (per the designs in i3).

* Did you want to make use of placeholder text here (e.g. "Loading...")?

* Any other thoughts?

**Comment by bummytime** [comment]
@folletto Here is the spinner:

![cats2](https://user-images.githubusercontent.com/154014/36543832-8b3a6b28-17aa-11e8-90f5-1f75e4fdffee.gif)


I think it looks good. :-)

**Comment by folletto** [comment]
Good one! Let's do it! 👍
