### ISSUE TITLE
Action Extension: Save as Draft

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#8145]
<img width="428" alt="napkin 58 11-14-17 8 40 31 am" src="https://user-images.githubusercontent.com/154014/32785683-bbc19ec4-c917-11e7-9a21-d1acf43e5fe7.png">

* Opens **Modular Site Picker** UI directly
* Supports text & media

Depends on: #8139

**Comment by bummytime** [comment]
@folletto For the action extension, using the existing app icon yields this:

<img width="79" alt="screen shot 2018-02-07 at 2 36 25 pm" src="https://user-images.githubusercontent.com/154014/35940487-f71943a6-0c14-11e8-8460-adac53f47e4f.png">

because of an auto-applied mask iOS does on action icons. Could you whip up a new icon image for me following [Apple's recommendation](https://developer.apple.com/ios/human-interface-guidelines/extensions/sharing-and-actions/):

> Use a template image for an action extension icon. A template image uses a mask to create an icon. Use black and white with appropriate transparency and antialiasing, and don’t include a drop shadow. Template images should be centered in an area measuring about 70px × 70px.

Thank you! :-)

**Comment by bummytime** [comment]
@folletto my bad...forgot you were afk. @iamthomasbishop was able to get me the icons. :-)

<img width="320" alt="screen shot 2018-02-10 at 8 23 13 am" src="https://user-images.githubusercontent.com/154014/36063006-a24fd018-0e3c-11e8-85b2-b9d20c4a63f0.png">

**Comment by folletto** [comment]
That's perfect, thank you!
