### ISSUE TITLE
WebKitViewController always redirects to WordPress.com if original URL had encoding in query string

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#8149]
Refs p4a5px-24g-p2 (h/t @ChrissiePollock)
A user reported that while using the reader, tapping on links in an embedded tweet would open WordPress.com instead of Twitter.

I was able to reproduce this by following the `twitter` tag and searching for an embedded tweet to test with. I tapped on the date stamp expecting to view the tweet but instead was taken to WordPress.com in the in-app browser.

After a bit of investigation it looks like the URL for the tweet has an encoded caret in its query string.  This is causing `WebViewAuthenticator.interceptRedirect` to return `nil` because the value of `redirect` can not resolve to a `URL` in this step: 

```let redirectUrl = URL(string: redirect) else```

cc @koke because you're probably the most familiar with the web view auth code at this point.

**Comment by koke** [comment]
😩 I'm starting to regret the new redirect system

**Comment by koke** [comment]
😩 I'm starting to regret the new redirect system
