### ISSUE TITLE
Incorrect background color on Search field

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#8153]
### Expected behavior
The search field on the Help section should have a white background.

### Actual behavior
![image uploaded from ios 1](https://user-images.githubusercontent.com/5558824/32808926-afa8db64-c973-11e7-9d74-3f2f689ea98f.png)

### Steps to reproduce the behavior
Me->Help & Support->WordPress Help Center

**Comment by elibud** [comment]
@frosty did you work on something related to this or am I imagining things?

**Comment by frosty** [comment]
This looks like it's using the new `UINavigationController`-owned search bars. I did look briefly into converting our other search bars, but there were some appearance issues – exactly as you show here.

There were two main 'fixes' for that background, but neither is ideal:

* Set the search field's first subview's background colour to white (or whatever we want). I think it also needs to be given a corner radius, and set to clip to bounds. I'm not even sure this is possible in this situation though, as it's presented entirely by Helpshift?
* Use UIAppearance to configure `setSearchFieldBackgroundImage:forState:` – it needs to be set to a custom image with rounded corners. We'd ideally want to do `whenContainedInInstancesOfClasses` and find some way to limit it only to these search bars so we don't affect all our existing one.

It also looks like that search bar is translucent, as there's a slight difference in the main background colour between it and the navigation bar, too. I imagine we can change that in `HelpshiftCustomConfig.plist`. 

I checked Helpshift's documentation, and there doesn't seem to be much extra configuration available for the search bar: https://developers.helpshift.com/ios/design/#attributes-search-bar

**Comment by elibud** [comment]
Thank you @frosty I'm going to contact their support.

**Comment by elibud** [comment]
@frosty what do you think of this as a temporary solution? At least you can see what you are typing.

![simulator screen shot - iphone 8 - 2017-11-15 at 11 08 47](https://user-images.githubusercontent.com/5558824/32840386-3c5e19c0-c9f6-11e7-8f90-44cb01f480c9.png)

**Comment by frosty** [comment]
Hmm... how did you get that appearance?

**Comment by elibud** [comment]
`HelpshiftCustomConfig.plist` add 
`<key>Background color</key>
 <string></string>
 <string>FFFFFF</string>
`
