### ISSUE TITLE
Question: How to use it in Swift instead of Objective-C

### ISSUE THREAD

**Issue by magonicolas** [wordpress-mobile/WordPress-iOS#8164]
### Expected behavior
See code example fro swift

### Actual behavior
Seeing just an Objective-C example

How can I see documentation on how to use or test this app using swift instead of Objective C?

**Comment by elibud** [comment]
Hi @magonicolas this app is build using both Swift and Objective-C, we are migrating all the Objective-C code to Swift as we go. I'm not sure what you mean by this:

> how to use or test this app using swift instead of Objective C?

Can you clarify?

Thanks
