### ISSUE TITLE
Password field on Post Settings is too short.

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#8175]
### Expected behavior

The password cell should have the same height as other cells

### Actual behavior

Password insertion cell too short:

<img width="545" alt="screen shot 2017-11-16 at 10 57 57" src="https://user-images.githubusercontent.com/651601/32887967-9e7c431c-cabd-11e7-8551-8a4d2a9163c4.png">

### Steps to reproduce the behavior

- Edit a post
- Go to post settings
- Change the Privacy setting of the post to Password Protected
- See the size of the password field.

**Comment by elibud** [comment]
Duplicated of: https://github.com/wordpress-mobile/WordPress-iOS/issues/8077
