### ISSUE TITLE
Add gridicons needed for the Activity Log

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#8185]
We need the following gridicons added to the project and @frosty graciously volunteered to do it, so here's the list we need:

gridicons-checkmark
gridicons-comment
gridicons-lock
gridicons-my-sites
gridicons-notice
gridicons-notice-outline
gridicons-plugins
gridicons-pages
gridicons-posts
gridicons-themes
gridicons-user
gridicons-cog
gridicons-domains
gridicons-history
gridicons-image
gridicons-logout
gridicons-mail
gridicons-menu
gridicons-notice-outline
gridicons-share
gridicons-shipping
gridicons-trash

Jetpack logo (not sure where this comes from) -> @mattmiklic any idea?

**Comment by frosty** [comment]
So all of these are already in the Gridicons framework, unless they've been updated very recently and need changing? Two slight differences to be aware of: there's no `logout` gridicon, but there is `signOut`, and for iOS we have a special `shareIOS` version of the `share` icon.

**Comment by frosty** [comment]
Oh, apart from the Jetpack logo – but I don't think that's available as a Gridicon. I guess we can just drop that in as an image?

**Comment by elibud** [comment]
Thanks a lot @frosty I think I'm covered then.
