### ISSUE TITLE
Site Icon Does not Appear in Notifications

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#8190]
I came across this problem in this helpshift issue https://automattic.helpshift.com/admin/issue/239158/
The user had noticed that when they were looking at the notifications for their site that the icon for their site did not appear.  I have only been able to find one section of the notifications where this happens, and that is in list of new followers, but I checked Android and the problem seems to be limited to iOS.

![screen shot 2017-11-17 at 15 29 55](https://user-images.githubusercontent.com/22015538/32971862-7c336354-cbac-11e7-8d76-10325523a39b.png)

(in the image all of the user gravatar images appear but the site icon does not)

### Steps to reproduce the behavior
1. In iOS go to the notifications with a set site icon
2. In the notifications find a notification about new followers and tap on it
3. In the expanded view of the notification there wont be a site icon for the site.

WordPress 8.7
iOS 11.1
Editor 2.0

**Comment by diegoreymendez** [comment]
Clearing the milestone as this issue missed the deadline for 9.0.
