### ISSUE TITLE
Crash: Cannot upload media with Jetpack and IndieAuth plugin installed

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#8198]
On a .org WordPress site with the Jetpack and [IndieAuth](https://wordpress.org/plugins/indieauth/) plugins installed, we are unable to create/upload new media via the [Media Library](https://github.com/wordpress-mobile/WordPress-iOS/blob/3e9181ac6dd3800f242f6241a60f1cd49386a59c/WordPress/Classes/ViewRelated/Media/MediaLibraryViewController.swift#L627) and also [when editing a post](https://github.com/wordpress-mobile/WordPress-iOS/blob/3e9181ac6dd3800f242f6241a60f1cd49386a59c/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L2780). When the app POSTs to:

`https://public-api.wordpress.com/rest/v1.1/sites/*/media/new?locale=en` 

a `400` is returned from the server with the following response body:

```
{
	"error": 403,
	"message": "Forbidden"
}
```

You **can** upload media successfully (`200` response from the same endpoint 👆) if you either:
1) Disable IndieAuth and leave Jetpack activated
2) Disable Jetpack and leave IndieAuth activated

### Steps to reproduce the behavior
1) On a .org WordPress install, install Jetpack and activate it.
2) Next install [IndieAuth](https://wordpress.org/plugins/indieauth/) and activate it
3) Run the latest WPiOS build and attempt to upload media via the Media Lib or within Aztec.
4) See the app crash hard when the server returns a 400 (403) and we don't handle it well.

**Comment by bummytime** [comment]
Also, I should note you **are** able to create posts without attached media when both Jetpack and IndieAuth are installed & activated.

**Comment by bummytime** [comment]
One more thing...having this plugin installed also causes Calypso to fail media uploads as well:

<img width="675" alt="screen shot 2017-11-20 at 2 15 02 pm" src="https://user-images.githubusercontent.com/154014/33039351-4d7004ac-cdfd-11e7-908e-e8db32fd6402.png">

**Comment by annezazu** [comment]
After chatting with @jeherve about this, it seems the issue likely has to do with the plugin hooking into `authenticate` thus overwriting all authenticated requests WordPress.com makes to the site. 

Calling on the plugin author @pfefferle to jump in here with some thoughts about what might be blocking this from working so we can come up with a solution :)

**Comment by bummytime** [comment]
Thanks @annezazu. For now, on the WPiOS side, we should definitely handle this 400 error in a better manner.
