### ISSUE TITLE
Reader: Jetpack comments don't load in followed sites feed

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8219]
### Expected behavior

I expect that when a post on a Jetpack site has comments, I will be able to tap the comments icon in the Reader to view existing comments on the post.

### Actual behavior

When I am viewing a site's feed, I can tap the comments icon to view existing comments on the post.

When I am viewing the Followed Sites feed, I can see the comments icon and comment count on the post, but when I tap the comments icon the comment don't load.

### Steps to reproduce the behavior

1. Open the Reader's Followed Sites feed in the app.
2. Find a post from a Jetpack site with comments on it.
3. Tap the comments icon. Result: You see the prompt "Be the first to leave a comment."
4. Go back to the Followed Sites feed.
5. Tap the Jetpack site's title at the top of the feed to open the site detail in the Reader.
6. Find the same post and tap the comments icon. Result: The comments load.

### Screenshots

Example from ma.tt (same behavior observed on other Jetpack sites).

Post in Followed Sites feed, no comments load:

![2017-11-23 09 52 52](https://user-images.githubusercontent.com/8658164/33168314-75013dc8-d038-11e7-863b-2c8b94d5b33f.png)
![2017-11-23 09 52 56](https://user-images.githubusercontent.com/8658164/33168319-764429c0-d038-11e7-8491-92655e7d6812.png)

Post in site detail feed, comments load:

![2017-11-23 09 53 08](https://user-images.githubusercontent.com/8658164/33168344-8ba1016c-d038-11e7-9e5a-0f93adcd9d6e.png)
![2017-11-23 09 53 13](https://user-images.githubusercontent.com/8658164/33168346-8bf050fa-d038-11e7-8014-cd9d06a0413c.png)

**Comment by designsimply** [comment]
Tested and confirmed using iPhone 6S with iOS 11.1.2 and WPiOS 8.9.0.20171122, however, I believe the fix may not have been included for 8.9.0.20171122 and that I should test again with a later beta or after the release.

**Comment by diegoreymendez** [comment]
A new build is out (8.9.0.20171129), which includes this fix.
