### ISSUE TITLE
Notifications: Magic link login notification is missing links on mobile

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8221]
### Expected behavior

I expect all links in notifications to work the same on web and in the app.

### Actual behavior

In the app, the links are missing from the notification you get after logging in to an account via a magic link on the web.

### Steps to reproduce the behavior

1. In a browser, start logged out here: https://wordpress.com/log-in
2. Select the "Email me a login link" option and follow instructions to log in with the magic link.
3. Check your notifications in a browser.
4. Open the "Account login with an e-mail link" notification and note the two links to account settings and contacting support.
5. Open the same notification in the app and note that the text is there but the links are missing.

### Screenshots

Web notification with links "Review your account settings" and "contact us":

![screenshot 2017-11-23 12 59 22](https://user-images.githubusercontent.com/8658164/33174177-c3314f90-d04e-11e7-8a06-c29c059b2d78.png)

Same notification in the app, missing links:

![2017-11-23 12 58 54](https://user-images.githubusercontent.com/8658164/33174198-d8c76c54-d04e-11e7-919b-2896e68449c2.png)

##### Tested on iPhone 6, iOS 11.1.1, WPiOS 8.9.0.20171122

**Comment by ScoutHarris** [comment]
This has been fixed:

![notification](https://user-images.githubusercontent.com/1816888/38061173-82fef6b0-32ab-11e8-83ec-505adc0b0ba4.png)
