### ISSUE TITLE
Pages: Confusion about how to edit a page

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8224]
### Expected behavior

While editing multiple pages, I kept expecting to tap the ellipsis next to a page and select "Edit" to edit it.

Calypso offers both options — select the page title to open in the editor or open the ellipsis menu and select "Edit."

### Actual behavior

There is no option in the ellipsis menu to edit a page, so I had to back out and be confident that tapping the page title would open it in the editor. I repeatedly did this wrong, despite having just gone through the same steps with another page.

### Screenshots

Calypso:

![2017-11-23 15 48 39](https://user-images.githubusercontent.com/8658164/33180816-f47b4f4e-d065-11e7-96f3-2a7707b2609e.png)

App:

![2017-11-23 15 18 04](https://user-images.githubusercontent.com/8658164/33180822-f69a8754-d065-11e7-94b4-9ab92c700657.png)

##### Tested on iPhone 6, iOS 11.1.1, WPiOS 8.9.0.20171122

**Comment by elibud** [comment]
Tagging as Broken Window so we can easily find this kind of issues while on Groundskeeper or while working on general improvements.

**Comment by elibud** [comment]
We will be addressing this issue during the upcoming page improvements.

**Comment by thehenrybyrd** [comment]
I'm still seeing this in My Sites > Site Pages in the app (though now there's an extra option, "set parent"):
![img_58438030c0c3-1](https://user-images.githubusercontent.com/15107387/50382778-febe6200-069e-11e9-9748-d931b5895067.jpeg)

Tested on iPhone SE, iOS 12.1, WPiOS 11.5 (internal beta)

**Comment by rachelmcr** [comment]
This confusion came up again with a user in 2053985-zen. The user looked for the Edit option in the ellipsis menu and couldn't find how to edit a page:

> When I click on the three dots beside any of my pages, I do not see an edit option. As is supported in the screenshot, I see ‘View, Set Parent (by the way, what does this mean?), Move to Draft, Move to Trash.’ Where is the edit feature?
