### ISSUE TITLE
Editor: Unable to add category from post options

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#8227]
### Expected behavior

The category is successfully created and assigned.

### Actual behavior

"Title missing" validation shows up

![img_2115](https://user-images.githubusercontent.com/5654161/33194365-2866f4ec-d102-11e7-857e-02f0daedbd28.PNG)

### Steps to reproduce the behavior

In post editor:
- Open post options > Categories > Add ("+")
- Set any category title
- [Optional] set any parent category
- Try to save new category

**Comment by ChrissiePollock** [comment]
Brought up again in #244854-h.

**Comment by pmciano** [comment]
Reported 245545-h

**Comment by charliescheer** [comment]
reported in 245811-h as well

**Comment by elibud** [comment]
@koke can you take a quick look at this one?

**Comment by koke** [comment]
It’s a duplicate of #8294, that has a fix ready to merge

**Comment by brbrr** [comment]
Forgot to add bug label, sorry :(
