### ISSUE TITLE
During call, splash screen WordPress Logo messed up.

### ISSUE THREAD

**Issue by iamchetanp** [wordpress-mobile/WordPress-iOS#8231]
### Expected behavior
=> WordPress Logo should be show proper in splash screen during call.

### Actual behavior
=> WordPress Logo is getting messed up on splash screen during call. I have attached screenshot.

##### Tested on [device], iOS [version], WPiOS [version]

Device: iPhone 6S Plus
iOs Version: 11.1.1
App Version: 8.8

![image uploaded from ios](https://user-images.githubusercontent.com/16279742/33239073-6bc0a318-d2c0-11e7-8be7-efe1f7723a6f.png)

**Comment by jleandroperez** [comment]
Although this issue (initially) seems like a missing constraint, i'm afraid it's not:

1. Reproduced in iOS 11.2
2. Constraints are effectively okay
3. Appears to be a missing redraw call. Problem is: at this point we can't run any code!

Definitely a SDK bug. Adding the low priority label!

**Comment by suyogyashukla** [comment]
+1 - happens on iOS 12.1.1 iPhone 7.
