### ISSUE TITLE
Feature: Tag Settings 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#8232]
Sharing here some design inspiration by @mattmiklic.  Original at p9c7Jx-do-p2.

> I’ve been working on a native Tags settings design for iOS and Android. To refresh, this is what the UI looks like on mobile web in Calypso:
> <img width="1194" alt="tag-settings-calypso" src="https://user-images.githubusercontent.com/1435271/33246329-572eae60-d2e1-11e7-888d-5a535ba3141d.png">
>
> Here’s how I’ve translated that to native 
>
> ![tag-settings-native](https://user-images.githubusercontent.com/1435271/33246332-638e8310-d2e1-11e7-97d7-eaab150b696d.png)
>
> Notes:
> - The basic flow remains the same.
> - I’ve eliminated the folder icons as they seemed to only be decorative, without offering any real benefit.
> - The circled number that denotes the number of posts is tappable. On iOS this would work similarly to a detail disclosure button. On Android it would be a supplemental action. Tapping the number opens the list of posts using the existing post list. Tapping anywhere outside the circled number opens the edit view. This behavior is in line with the OS specs for disclosure buttons & supplemental actions.
> - Rather than show a 0 on every tag that doesn’t have any posts associated with it, I’m proposing that we just not show a number for those tags. The repeating 0 seems like it doesn’t really add much value.
> - Tapping the trash icon on the detail view opens an alert confirming the deletion; the message and button options should be the same as Calypso. If feasible, on iOS, we can add a swipe-left gesture on the tags list to reveal a “Delete” option.
> - The search form for iOS shown here is different from what we’ve used in the past. But this matches the new pattern in iOS 11 for a combined toolbar + search field. When this is being implemented I can flesh out the details on color, etc. as needed.
> - I didn’t include a detailed view of search results; I can if needed, but I assume they’ll be mostly self-explanatory

**Comment by ctarda** [comment]
Hi @aerych ! 👋 

Upon first inspection, this is, roughly, what I think needs to be done: (fair warning, wall of words incoming)

- Update PostTag model object: add an optional description, update core data model, probably add a migration.
- Update PostTagService: add a method to it's API to delete tags (i.e. deleteTag:forPost:)
- PostTagPickerViewController: add deletion (implementing the relevant methods in PostTagPickerDataSource), add the search bar, and navigate to PostTagDetails.
- PostTagDetails: a new VC that contains the Tag editing UI. I might try to pass to it whatever needs to be added to the navigation bar (either the delete button or nothing), so I can use it for both editing and creating new tags, but still haven't thought that out well.

My first question would be: what am I missing? 😛 

My second question would be: at the moment, in the current version of the app in production, tapping a tag assigns said tag to the post. However, it looks like, as part of this story, that behaviour is expected to change a little bit, and we'd need to navigate to the PostTagDetails view. How should we assign tags to posts?

Third and last question (for now) would be: editing tags is not possible for all user roles. I was thinking that, for those roles that can not edit tags, we should just not show them the PostTagDetails, and we wouldn't need to display any warning or alert (if they can not do edit tags, they probably don't need to know that editing tags is a possibility). Is that the right way to do it?

Sorry for the long question(s)! 

I'll walk away now... 🚶

**Comment by aerych** [comment]
Howdy @ctarda :) 
Great questions!

> Update PostTag model object: [...]

👍 

> Update PostTagService: [...]

👍 

> PostTagPickerViewController: [...]

Probably not. I think there were some important details missing from the description that would affect the need for this. I'll clarify below.

> PostTagDetails: [...]

👍 

> in the current version of the app in production, tapping a tag assigns said tag to the post. However, it looks like, as part of this story, that behaviour is expected to change a little bit, and we'd need to navigate to the PostTagDetails view. How should we assign tags to posts?

Right! This is something that's not very clear from the description and I did a poor job explaining it when we were chatting. Mea Culpa.  We like the feature to be consistent with the flow in Calypso (WordPress.com) so tag settings would be accessed from the `My SItes` > `Site Detail` > `Settings` screen, under the `Writing` section, as opposed to the existing tag selection screen available from the editor. Here's an example of the screen in the app.

![simulator screen shot - iphone 6s - 2017-11-27 at 22 54 09](https://user-images.githubusercontent.com/1435271/33301806-f29ca480-d3c5-11e7-9e46-07af8e6d9493.png)

You can find an example of the web version of the screen at https://wordpress.com/settings/writing/[YOUR SUBDOMAIN].wordpress.com

> Third and last question (for now) would be: editing tags is not possible for all user roles. I was thinking that, for those roles that can not edit tags, we should just not show them the PostTagDetails, and we wouldn't need to display any warning or alert (if they can not do edit tags, they probably don't need to know that editing tags is a possibility). Is that the right way to do it?

This sounds reasonable, but I'd suggest creating a test user on WordPress.com to see how this situation is handled on the web. :)

Hope this helps!

**Comment by ctarda** [comment]
Ooooooooh, of course! Sorry for the misunderstanding, I am not sure what made assume what I assumed 😊

Thanks for the clarification!

**Comment by ctarda** [comment]
There seems to be a little bit of a difficult solution when it comes to the search bar.

I have been playing with this for a few hours, and I can't seem to get it to work any better, but any pointers are more than welcome.

If I add the search controller to the navigation bar, using iOS 11's APIs, the system will also make the refresh control part of the navigation bar. And then, Really Ugly Things ™️  happen when pulling down to refresh (basically, the background of the refreshcontrol will be gray, the rest of the navigation bar, including the search bar, will be blue) You can see this in action in [this commit](https://github.com/wordpress-mobile/WordPress-iOS/pull/8248/commits/ec685b778b21c80d7f38ea411a89dd3a13afd0d9)

The navigation bar would look good if we set `prefersLargeTitles = true`, but then it will be inconsistent with the rest of the app.

Now, if I set the search bar as table view header, as [I did in this commit](https://github.com/wordpress-mobile/WordPress-iOS/pull/8248/commits/190cb211ad0bfd8abad57a0870db96e8291007e3), everything looks okay and the refresh control will not be part of the navigation bar. Which is not what's specified in the design.

I am still trying to make option A work (search bar as part of the navigation bar) but I would appreciate any pointers 😊

**Comment by aerych** [comment]
Heya @ctarda :)  
I'm digging that you tried the implementation both ways and then linked to the commits.  Thanks for that! 
I think it would be nice to just move forward with the search bar as a table view header.  This is an approach is at least consistent with other search bars in the app (the post list for example).  Getting search controllers and search bars to do *exactly* what we want has been a real challenge at times (as both me and @frosty can attest).

**Comment by mattmiklic** [comment]
> This is an approach is at least consistent with other search bars in the app (the post list for example). Getting search controllers and search bars to do exactly what we want has been a real challenge at times

This seems like the right way to go. We re-used a template that came from Apple for the design, but it sounds like it's tricky or not possible to implement the design exactly the way the template suggests. It seems like it'd be better to aim for consistency with other search bars in the app for now.

**Comment by ctarda** [comment]
Hi @mattmiklic 👋  Thanks for clarifying!

**Comment by ctarda** [comment]
👋  @aerych @mattmiklic 

One more question: tapping the badge number opens the posts list. I assume it should be filtered to contain only the posts tagged with the selected tag. Is that correct?

Also, if that's the case, should we indicate in the UI that the post list is filtered? I checked the behaviour on the web, and there is nothing really indicating that the list is filtered, but I thought I should ask. 😊

**Comment by mattmiklic** [comment]
> One more question: tapping the badge number opens the posts list. I assume it should be filtered to contain only the posts tagged with the selected tag. Is that correct?

Yep, that's correct!

> Also, if that's the case, should we indicate in the UI that the post list is filtered? I checked the behaviour on the web, and there is nothing really indicating that the list is filtered, but I thought I should ask. 😊

Good question, I didn't think about this when designing these screens. I think the simplest thing to do here would be to show the list of posts with the tag as the title in the navigation bar. No ability to do further filtering from this screen; they can navigate back to the Blog Posts screen to do that. @aerych does that sound right to you?

**Comment by aerych** [comment]
> No ability to do further filtering from this screen; they can navigate back to the Blog Posts screen to do that.

@mattmiklic I agree no further filtering by tag, but we'd want to keep the post status filters and the author filter.

**Comment by mattmiklic** [comment]
Makes sense, those could go in the same dropdown menu we use on the regular Blog Posts screen.

**Comment by aerych** [comment]
> regular Blog Posts screen

I might have missed something. I thought the idea was to link to the existing list of blog posts just filtered for the tag but otherwise retaining its normal functionality and feature set.  Did you have something different in mind?

**Comment by mattmiklic** [comment]
That's what I had in mind too -- by "regular blog posts screen" I meant the standard screen showing _all_ blog posts. Other than being filtered by a tag, I see this one working exactly the same way.

**Comment by aerych** [comment]
Actually... let's hold off on showing the post list for now and just make the badges decorative. 

To properly show the post list we'd also need to write the logic to ensure posts for the specific tag are synced to the app.  Being able sync posts out of order and not impact the list has proven to be a bit tricky in the past and I think it would be best if we handled it as a separate task. 

Being able to list, display, add, edit, and delete tags should be sufficient to land this feature. :)
