### ISSUE TITLE
Notifications: opening a post mention notification shows no way to exit

### ISSUE THREAD

**Issue by mzorz** [wordpress-mobile/WordPress-iOS#8245]
### Expected behavior
Starting the app from a mention notification should show a way to navigate back to the app

### Actual behavior
The post is shown in full, without giving the user the ability to navigate out of the Post view.

<img width="483" alt="screen shot 2017-11-29 at 11 25 20 am" src="https://user-images.githubusercontent.com/6597771/33380043-93e50d22-d4f8-11e7-959f-d663ac07df35.png">

### Steps to reproduce the behavior
N/A

**Comment by jleandroperez** [comment]
Closing as a duplicate of #6976.

Thanks everyone!!
