### ISSUE TITLE
Aztec: Media upload not canceled after deleting the media

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#8257]
### Expected behavior

Media upload should stop when deleting media icon which wasn't uploaded yet

### Actual behavior

Media upload indicator remains spinning. It blocks to publish/update the post. going back will discard all changes

### Steps to reproduce the behavior

- Make sure you on weak connection(or just be fast)
- Start new blog post
- insert any photo from your camera roll
- delete it before it partially uploaded (before you can see actual image)
- Media upload will remain spinning

##### Tested on iPhone SE, iOS 11.2, WPiOS 8.9.0.20171129

![img_2267](https://user-images.githubusercontent.com/5654161/33548965-9232bac0-d91b-11e7-83fb-a44670884542.PNG)

**Comment by SergioEstevao** [comment]
This is fixed.
