### ISSUE TITLE
Aztec: App crash when returning back from "add media" screens

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#8290]
### Steps to reproduce the behavior
- Start new blog post
- add a photo from camera (📷  icon) (or add or open/close media or open/close WP media)
- App will crash when tapping on "Use Photo"

##### Tested on iPhone SE, iOS 11.2, WPiOS 9.0.0.20171205

[crash-log.txt](https://github.com/wordpress-mobile/WordPress-iOS/files/1541993/crash-log.txt)

![screenrecording_12-08-2017 15-28-36](https://user-images.githubusercontent.com/5654161/33758235-0fd9b7fa-dc30-11e7-9b53-ad676f79f844.gif)

**Comment by jklausa** [comment]
Took a look at it, and this was fixed in #8273, but isn't in the Hockey build yet.
