### ISSUE TITLE
Make the blogs list sortable

### ISSUE THREAD

**Issue by isaackeyet** [wordpress-mobile/WordPress-iOS#83]
I'd like to see the blog list sortable: a-z, z-a and by order added ascending/descending. Maybe as an app level setting.

Originally reported by @aerych 

---

Changed 4 months ago by maxday
Attachment patch.diff​ added
http://ios.trac.wordpress.org/attachment/ticket/1344/patch.diff
---

comment:2 Changed 4 months ago by maxday

Here is the new feature, I'm not very familiar with the xcdatamodel files, so feel free to comment 

---

comment:3 Changed 3 months ago by koke

Hey, sorry it took so long to look into this. Thanks for taking the time to do this
I've tested the patch and it's not working for me: I can reposition a blog, but as soon as my finger leaves the screen it goes back to it's original location
Some comments about the code:
There's no need to change the sort descriptors in WordPressComApi.m
For the sidebar and settings, I'd keep blogName as a secondary sort descriptor, so if the user hasn't manually reordered the blogs they still show alphabetically. Actually I'd add a +[Blog fetchRequestForSortedBlogsWithContext:] method, since it's used in at least 4 places.
I think the code would be much simpler if you don't actually store the new sortOrder until the user taps Done and stops editing. See ​http://stackoverflow.com/questions/2360938/uitableview-core-data-reordering for an example
The core data model wasn't included in the patch as it's a binary file. If you change it, you'll need to attach it separately. To test the patch I assumed you just added a Int16 sortOrder attribute to blog
Also, check out ​https://github.com/wordpress-mobile/WordPress-iOS/wiki/WordPress-for-iOS-Style-Guide
I see a bunch of spaces in the wrong places

---

patch: http://ios.trac.wordpress.org/attachment/ticket/1344/patch.diff

**Comment by tommi** [comment]
@aerych I'm suggesting to close this issue. Having so many blogs on a mobile that you would want to have sorting sounds like a rare case.

**Comment by aerych** [comment]
> sounds like a rare case

You'd be surprised :)

**Comment by tommi** [comment]
Heh, statistics on that?

**Comment by isaackeyet** [comment]
@aerych I second closing, as long as there's a search function. :)

**Comment by aerych** [comment]
+1 for search

**Comment by a4jp-com** [comment]
+1 for a search and sort button for posts and pages.

**Comment by koke** [comment]
#1885 it is then :wink:
