### ISSUE TITLE
App Settings: Wrong layout/link for Usage Statistics descriptive text

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8302]
### Expected behavior

I expect all descriptive text in the app to wrap and be linked to relevant details.

### Actual behavior

The descriptive text under App Settings > Usage Statistics runs off the edge of the screen and links to make.wordpress.org information about Aztec.

### Steps to reproduce the behavior

1. Open the Me tab.
2. Open the App Settings section.
3. Scroll down to Usage Statistics. Note the descriptive text doesn't fit on the screen.
4. Tap on the descriptive text. Note that it opens an unrelated link (about Aztec).

![2017-12-11 15 27 11](https://user-images.githubusercontent.com/8658164/33838734-4625b0de-de88-11e7-8da9-fcaa68307663.png)

##### Tested on iPhone 6, iOS 11.1.1, WPiOS 9.0.0.20171205

**Comment by ScoutHarris** [comment]
This is fixed. The text now wraps and is no longer a link.

<img width="373" alt="stats" src="https://user-images.githubusercontent.com/1816888/38058610-bbd9c920-32a0-11e8-8c4a-885cfac7ef93.png">
