### ISSUE TITLE
Fix "into" vs "in to" spelling on login page

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#8313]
Very small tweak that I noticed yesterday while logging in to the app.

We have two different versions of "into" on the login page used in the same way. I believe they should both be "in to." Either way, they should be consistent. 

<img width="743" alt="screen shot 2017-12-12 at 9 53 37 am" src="https://user-images.githubusercontent.com/7240478/33897498-de178148-df22-11e7-8239-2e4c0eb3045d.png">

##### Tested on iPhone 6, iOS 11.2, WPiOS 9.0

**Comment by elibud** [comment]
Thanks for the report @jeremeylduvall, @aerych sending your way for triage.
