### ISSUE TITLE
Modularize the link dialog.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#8322]
### Description:

Modularize the code to show the link dialog, so that it can be reused from our future Gutenberg VC.

The end solution must exist in a class of its own and provide an interface to interact with it in a generic way.

For reference, see [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L1778).

This issue is a child of: https://github.com/wordpress-mobile/WordPress-iOS/issues/8321

**Comment by diegoreymendez** [comment]
@koke - I'm not sure this is really necessary anymore, and an opinion from the Gutenberg perspective could help clarify.

At the time this issue was created, I considered the linking flow would be native.

**Comment by koke** [comment]
I think not. Closing for now, but @etoledom can you confirm that's right?

**Comment by etoledom** [comment]
I agree that it's not needed anymore. 👍
