### ISSUE TITLE
Modularize the blog picker.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#8325]
### Description:

Modularize the code to handle the blog picker, so that it can be reused from our future Gutenberg VC.

The end solution must exist in a class of its own and provide an interface to interact with it in a generic way.

For reference, see [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L1236).

This issue is a child of: https://github.com/wordpress-mobile/WordPress-iOS/issues/8321

**Comment by designsimply** [comment]
@diegoreymendez is modularizing the code that handles the blog picker still needed?

**Comment by diegoreymendez** [comment]
@designsimply - Closing this issue as this was created before Gutenberg was in my mind.
