### ISSUE TITLE
Modularize media insertion.

### ISSUE THREAD

**Issue by diegoreymendez** [wordpress-mobile/WordPress-iOS#8326]
### Description:

Modularize media insertion.

The logic in [this method](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L2667), [this method](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L2699), [this method](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L2710), [this method](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L2730) and [this method](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L2749) should not fall within the responsibilities of the VC, but instead be part of an external module taking care of that specific logic.

Evaluate options to move this code.

This issue is a child of https://github.com/wordpress-mobile/WordPress-iOS/issues/8321.

/fyi @SergioEstevao

**Comment by SergioEstevao** [comment]
This code was now mainly moved to the MediaCoordinator so I think this issue can be closed.
