### ISSUE TITLE
Media title is not always centered

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#8330]
When the media library appears, the title briefly appears to the right then moves to the center. If you tap on Edit then cancel, the title is stuck to the right.

![screen shot 2017-12-14 at 10 12 13](https://user-images.githubusercontent.com/8739/33984409-c8e254ec-e0b7-11e7-966e-6e73ad3e2f32.png)

##### Tested on iPhone 8, iOS 11.2, WPiOS develop (e8b3e7780a375a0b9e70e8e81ced3b32912ef64c)

**Comment by ScoutHarris** [comment]
Testing with WPiOS 12.4 on iPhone X and 8, in English and Spanish. I'm unable to reproduce this.
