### ISSUE TITLE
Following buttons/status not syncing

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#8352]
When you are looking at the manage sites section of the reader, if you select one of the followed sites and you see the entire list of post, there are 2 different options on that page to unfollow or follow a site, the following icon at the top and the icon next to each post.  If you tap on one of these the other does not stay in sync with it so you can end up with the posts saying that the site is unfollowed, but the site title saying it is followed.  

![screen shot 2017-12-15 at 21 42 39](https://user-images.githubusercontent.com/22015538/34067355-fd8c8954-e1e0-11e7-86c9-fdf695b1cb09.png)

To reproduce this issue
1. Go to the Reader > Followed Sites > Manage > One of your managed sites
2. Tap on the follow either by a post or by the title.  
3. The one you tap on will change but the others will not.

Iphone 6s and iPad mini 3
WordPress9
iOs 11.2

**Comment by elibud** [comment]
@jleandroperez I think the more ugly part of this one is fixed as part of https://github.com/wordpress-mobile/WordPress-iOS/pull/8815 however I don't think we can really fix cells getting out of sync with actions performed in the reader, what do you think?
