### ISSUE TITLE
Text running off screen

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#8353]
Just a quick thing I noticed, if you are in the app settings on a smaller screen sized iPhone the text "Automatically send usage statistics to help us improve WordPress" runs off the page.

![screen shot 2017-12-15 at 21 38 50](https://user-images.githubusercontent.com/22015538/34067382-d20c2ea0-e1e1-11e7-9a6b-f7af3419369d.png)

iPhone 6s  (was fine on my iPad mini)
WordPress 9
iOs 11.2

**Comment by elibud** [comment]
Fixed by @diegoreymendez here https://github.com/wordpress-mobile/WordPress-iOS/pull/8375 Thanks for the report @charliescheer
