### ISSUE TITLE
Overlapping comment box on P2s

### ISSUE THREAD

**Issue by thebud15** [wordpress-mobile/WordPress-iOS#8357]
### Expected behavior: 

Making a comment on a blog post should be contained within a box for commenting, that should not overlap to content above it.

### Actual behavior: 

When making a comment on a blog post (specifically the one calling for testing of 9.0), I noticed an error. I went to My Sites, searched for an internal P2 to which I have Super Admin access. I clicked "View Site" and went to make a comment on a post. It caused the text box to begin above where my Gravatar name/info were to appear nearly invisible, and the comment I wrote began to overlap where it shouldn't have. 

### Steps to reproduce the behavior: 

I was able to replicate this on other P2 themed blogs using the same steps as described above ("My Sites" > choose a P2 > "View Site" > comment on a blog post.

##### Tested on iPhone 7, iOS 11.2.1, WPiOS 9.0

![fullsizeoutput_1fd9](https://user-images.githubusercontent.com/29046778/34091323-cac6eb44-e371-11e7-8ba5-0126ee466f25.jpeg)

**Comment by elibud** [comment]
Yes this is an issue with how p2s display in Safari on iOS, not specific to the mobile apps. @rachelmcr do you know where would be the best place to report this one? Thanks

**Comment by rachelmcr** [comment]
Since it's a theme issue, it can be reported directly as a theme bug. I've moved it to an internal report (4946-wpcom-themes).
