### ISSUE TITLE
Stats: Unable to read dates in daily stats view

### ISSUE THREAD

**Issue by sarahblackstock** [wordpress-mobile/WordPress-iOS#8369]
The dates on the daily view in stats are not readable enough to determine which day is which, unless the screen is viewed in landscape. In landscape, instead of De..., it switches to Dec 16.

Example:
![ebef9e292274692a529383a850565bd7b05003ab](https://user-images.githubusercontent.com/9643246/34219279-44475a3e-e576-11e7-9d9c-ae77718ef60d.png)

User saw this on iPhone 5s in v9.0. (Able to reproduce on a 6s in v8.9.)

internal ref: #247367-h

**Comment by ScoutHarris** [comment]
@elibud - I'm assuming this will be addressed with the 'Full Stats Refresh' project?

**Comment by elibud** [comment]
@ScoutHarris yup :)

**Comment by ScoutHarris** [comment]
Closing this since, as mentioned, it will be resolved with Stats Refresh.
