### ISSUE TITLE
CSS revisions page renders weirdly in the app and slider dosn't work

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#8383]
Hey y'all, while testing last night while poking around I ended up on the CSS revisions page while on my iPhone, and I noticed a few things.  The first was that the area where the CSS should be appearing is being squeezed into a tiny box which makes reading the CSS very difficult.  I wasn't able to check this on a bigger screen, so it may just be for the smaller iOS models.
To see this go to:
1. In the iOS app on a site with CSS access go to My Site > Theme > Customize > CSS > CSS Revisions
2. There is a box near the bottom of the page that should display the current revision and it is shrunk fairly small.

![screen shot 2017-12-22 at 12 01 58](https://user-images.githubusercontent.com/22015538/34309657-64c23f90-e710-11e7-8a1f-7d25671a2f9a.png)

The other thing I noticed is if you select one of the revisions that appears in the history, when you go to the restore page, if you tap and slide on the slider that appears there, the slider button can be selected but it will not slide.

To test this:
1. From the CSS revisions page choose one of the revisions listed on the right.
2. You will be taken to the CSS restore page and there will be a slider across the top to choose the different versions.
3. tap and drag on that slider but it will not move.

![screen shot 2017-12-22 at 12 02 24](https://user-images.githubusercontent.com/22015538/34309670-8288eab0-e710-11e7-8428-e1dec7ea6655.png)

iPhone 6s
iOs 11.1
WordPress 9.1

**Comment by rachelmcr** [comment]
@charliescheer These are web views, rather than part of the native app. Do you have the same problem if you use Safari instead of the app?

**Comment by charliescheer** [comment]
Ah, you are correct.  I tried out the same views/problems in safari and the results are exactly the same.  The squeezed text and the in ability to use the slider on the revision page.  The app is displaying the page the same as a web browser would.  Should I close the issue, or move it to another repository?

**Comment by rachelmcr** [comment]
I'll close this issue as it's not an app bug. CSS revisions are part of WordPress.com/Jetpack, so if the issue also exists in Jetpack you can report it in the [Jetpack repo](https://github.com/Automattic/jetpack) and otherwise report it to a WordPress.com repo.

That said the WP Admin screen looks like it is based on the post/page revisions that are part of Core WordPress, so that might require an upstream fix in core (with a bug report to Core Trac if the same issue exists in post/page revisions).
