### ISSUE TITLE
Images not resizing in wp-admin edit when changed from the app.

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#8384]
When I was poking around 9.1 I was working with a post that I already had some images in that were set to full size.  While messing around with those images I changed the size on one from Full size to thumbnail.  It appeared correctly in the app and I updated the post.  From there if I went to wp-admin and edited the post the image was still displaying as full size, however what was sort of odd is if you like at the settings for that image it will be displayed as the changed size, and on the actual published post it shows correctly as well, but for some reason it doesn't update in the edit view.

To reproduce:
1. In the app open up an existing post that has an image in it.
2. Tap on that image and in it's settings change the size of the image and update the post.
3. Go to wp-admin > Posts and edit the post you updated.
4. the image size will not update unless changed in wp-admin.
 

After changing the size of the image to Thumbnail from the app, in wp-admin I am still seeing this
![screen shot on 2017-12-22 at 12_23_45](https://user-images.githubusercontent.com/22015538/34310176-21a1d1a0-e713-11e7-9d64-e60855f375ed.png)

But if I edit that image it shows as thumbnail
![screen shot 2017-12-22 at 12 24 02](https://user-images.githubusercontent.com/22015538/34310180-2ad56b4c-e713-11e7-98ff-fb5b84ac1fa4.png)

WordPress 9.1
iOS 11.1
iPhone 6s

**Comment by elibud** [comment]
@charliescheer I think this is some caching issue on wp-admin side of things, did you try refreshing the posts?

**Comment by charliescheer** [comment]
I thought so too at first, but I tried to refresh, force refresh and open in an incognito window and the result stayed the same that the image would not appear the correct size till I changed the size in the wp-admin image editing.

**Comment by elibud** [comment]
Thanks @charliescheer, that's supper odd. Pinging @kwonye  as he will know who to assign this one to.

**Comment by jleandroperez** [comment]
### Update:
This is not precisely a bug: Aztec isn't serializing, explicitly, the `width` and `height` attributes. Instead, only the CSS class is added.

Nevertheless, since the fix involves adding (standard html) fields, i've filed [this issue in the Aztec's repository](https://github.com/wordpress-mobile/AztecEditor-iOS/issues/883).

**Comment by jleandroperez** [comment]
### Update Mark II:
This issue has been addressed via [this Aztec Issue](https://github.com/wordpress-mobile/AztecEditor-iOS/pull/884). Should be fixed (probably) in WPiOS 9.2.

I'll keep the issue open for verification purposes. Thanks all!
