### ISSUE TITLE
Reader: missing image in stream when image has no WP class name attributes

### ISSUE THREAD

**Issue by lancewillett** [wordpress-mobile/WordPress-iOS#8393]
### Expected behavior
I'd expect to see images in the Reader stream, especially for photo blogs.

### Actual behavior
Missing the image.

Here's the source code for this particular blog post.

```
<div>

<img style="max-width: 600px;" src="https://b19y.files.wordpress.com/2017/12/977d8-25017105_138648596841514_72137175486955520_n.jpg" />
<div>Lap dog
#goldendoodle</div>
</div>
```

Note it's missing the WP class names. Could be Aztec editor? Ben L posted it "via the ifttt applet".

### Steps to reproduce the behavior
Web, front-end: https://b19y.blog/2017/12/23/2483/

![screen shot 2017-12-29 at 11 35 41](https://user-images.githubusercontent.com/66797/34444646-cc4a5ff4-ec8c-11e7-995e-dbe5956c551c.png)

WP.com Reader (Calypso web): https://wordpress.com/read/feeds/58928981

![screen shot 2017-12-29 at 11 35 33](https://user-images.githubusercontent.com/66797/34444651-cf92d984-ec8c-11e7-9c89-52a50c8e8c75.png)

WP iOS app version 9.1 (alpha 2017-12-28)

![ben-lowery-reader-image](https://user-images.githubusercontent.com/66797/34444658-da52154c-ec8c-11e7-804f-1a078c4bbdf7.jpeg)

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 8, iOS 11.2.1, latest 9.1 alpha build

**Comment by elibud** [comment]
@nbradbury I'm thinking about inspecting the post `featured_media` after inspecting the `featured_image` field and before looking for an image in the content, what do you think?
