### ISSUE TITLE
Link to blog site that no longer exists causes app crash

### ISSUE THREAD

**Issue by pookzilla** [wordpress-mobile/WordPress-iOS#8395]
### Expected behavior

App can handle this misconfigured instance

### Actual behavior

App crashes immediately after login due to missing jetpack version. This missing value is interpreted as a NSCFBoolean rather than a NSString and attempts to invoke compare:options fails with an invalid selector exception.

### Steps to reproduce the behavior
Link to a blog that no longer exists and launch the app. After login app will crash. Subsequent app starts will immediately fail as this bad state is restored from backing store.

##### Tested on latest code on iOS simulator

> 2017-12-30 12:09:08.495966-0500 WordPress[14218:321186] -[__NSCFBoolean compare:options:]: unrecognized selector sent to instance 0x1161785f0
2017-12-30 12:09:08.537184-0500 WordPress[14218:321186] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFBoolean compare:options:]: unrecognized selector sent to instance 0x1161785f0'
*** First throw call stack:
(
	0   CoreFoundation                      0x0000000115eae12b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000011542bf41 objc_exception_throw + 48
	2   CoreFoundation                      0x0000000115f2f024 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000115e30f78 ___forwarding___ + 1432
	4   CoreFoundation                      0x0000000115e30958 _CF_forwarding_prep_0 + 120
	5   WordPress                           0x000000010a6c4f6e -[Blog supportsPluginManagement] + 206
	6   WordPress                           0x000000010a6c478b -[Blog supports:] + 379
	7   WordPress                           0x000000010a71b33d -[BlogDetailsViewController configurationSectionViewModel] + 1613
	8   WordPress                           0x000000010a718821 -[BlogDetailsViewController configureTableViewData] + 545
	9   WordPress                           0x000000010a717ca3 -[BlogDetailsViewController viewWillAppear:] + 275
	10  UIKit                               0x000000010edf3150 -[UIViewController _setViewAppearState:isAnimating:] + 444
	11  UIKit                               0x000000010edf39e5 -[UIViewController __viewWillAppear:] + 147
	12  UIKit                               0x000000010ee355c2 -[UINavigationController _startTransition:fromViewController:toViewController:] + 803
	13  UIKit                               0x000000010ee3644f -[UINavigationController _startDeferredTransitionIfNeeded:] + 841
	14  UIKit                               0x000000010ee376d3 -[UINavigationController __viewWillLayoutSubviews] + 150
	15  UIKit                               0x000000010f0924e2 -[UILayoutContainerView layoutSubviews] + 231
	16  UIKit                               0x000000010ed16a6d -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1439
	17  QuartzCore                          0x000000010e86f61c -[CALayer layoutSublayers] + 159
	18  QuartzCore                          0x000000010e8737ad _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 401
	19  QuartzCore                          0x000000010e7fa86c _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 364
	20  QuartzCore                          0x000000010e827946 _ZN2CA11Transaction6commitEv + 500
	21  UIKit                               0x000000010ec6f167 _afterCACommitHandler + 272
	22  CoreFoundation                      0x0000000115e50c07 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 23
	23  CoreFoundation                      0x0000000115e50b5e __CFRunLoopDoObservers + 430
	24  CoreFoundation                      0x0000000115e35124 __CFRunLoopRun + 1572
	25  CoreFoundation                      0x0000000115e34889 CFRunLoopRunSpecific + 409
	26  GraphicsServices                    0x00000001197389c6 GSEventRunModal + 62
	27  UIKit                               0x000000010ec455d6 UIApplicationMain + 159
	28  WordPress                           0x000000010a644f40 main + 144
	29  libdyld.dylib                       0x000000011708dd81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by pookzilla** [comment]
Simple fix to get app back to a functional state is to update Blog.m:658 to `_jetpack.version = [[self getOptionValue:@"jetpack_version"] stringValue];` - the app will then launch and the missing blog will appear. Unclear what the right answer here is tho - the blog is clearly unusable in the state and actions on it will cause the app to crash in other ways. Looking at the code for BlogService + Blog it doesn't appear there is currently a place where sanity checks are performed on content obtained from the remote service.

**Comment by bummytime** [comment]
Closing this. Fixed in #8464.
