### ISSUE TITLE
Editor: Post formats unavailable for Jetpack sites

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8396]
### Expected behavior

In the editor post options, I expect to be able to select a post format for all sites that use them.

### Actual behavior

I can select post formats for WordPress.com Simple sites and self-hosted non-Jetpack sites. For any sites using Jetpack, though, I see "Unavailable" in the Post Formats section in the editor.

### Steps to reproduce the behavior

1. Open the editor for a Jetpack site.
2. Open the post options section.
3. Scroll to Post Formats and try to select a post format.

Result: The Post Formats section says "Unavailable" and tapping it does nothing.

![2018-01-02 10 53 37](https://user-images.githubusercontent.com/8658164/34492198-2cf08a14-efac-11e7-99f9-24bd985ed355.png)

##### Tested on iPhone 6, iOS 11.2.1, WPiOS 9.1.0.20171228

**Comment by elibud** [comment]
Hey @rachelmcr, have you checked that post formats are available for that site in Calypso? Can you please let me know which Theme is the site on? I checked this with a couple of my Jetpack sites and it was working correctly. 
Thanks

**Comment by rachelmcr** [comment]
Hm, this must have been a temporary issue of some sort (perhaps an API issue), as post formats are now working on my active Jetpack sites again. I'll watch out for this in case it recurs but I'll close this issue for now.

**Comment by elibud** [comment]
Thanks for double checking @rachelmcr :)
