### ISSUE TITLE
Notifications: pingbacks notification not linked

### ISSUE THREAD

**Issue by dougaitken** [wordpress-mobile/WordPress-iOS#8410]
### Expected behavior

I received a ping showing `...linked to your posts...` and clicking on that first notification would let me navigate to that pingback directly.

### Actual behavior

Clicking into notification, I need to click what looks like a link straight to my post, but brings up a "Comments" screen.

### Steps to reproduce the behavior

The middle step seems superfluous.

<img src="https://user-images.githubusercontent.com/1119271/70126174-b42ac100-1635-11ea-8cba-805d9c5c086d.jpeg" width="200" alt="http://cld.wthms.co/KlPkzZ"> <img src="https://user-images.githubusercontent.com/1119271/70126179-b725b180-1635-11ea-902e-7f7d5b261a31.jpeg" width="200" alt="http://cld.wthms.co/8gwDI2"> <img src="https://user-images.githubusercontent.com/1119271/70126184-bb51cf00-1635-11ea-9d48-1a0db5e7d737.jpeg" width="200" alt="http://cld.wthms.co/mxMWGi">

**Comment by aerych** [comment]
Tested this again with test blogs and two different users.  The link was clickable and there was an option to view the source post.  Seems resolved now so closing. 
![IMG_2320](https://user-images.githubusercontent.com/1435271/114762745-aad05f00-9d27-11eb-9f13-7661d08cf69d.PNG)
