### ISSUE TITLE
Media toolbar moves up after close without selection

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#8413]
### Expected behavior

On an iPhone X the Media toolbar should always be on top of the media items

### Actual behavior

Media toolbar moves up and leaves a gap between the toolbar and the media items.

<img width="545" alt="screen shot 2018-01-09 at 13 01 56" src="https://user-images.githubusercontent.com/651601/34722287-20eb13aa-f53e-11e7-8fc7-7e9a6295932a.png">

### Steps to reproduce the behavior

- Start the app
- Start a new post using Aztec
- Tap on the + button to add media
- Tap on the icon to show the media library full screen
- Tap on cancel
- See the gap between the media toolbar and the media items

**Comment by SergioEstevao** [comment]
@bummytime and/or @frosty could this be related to our code for detection of keyboard screen size?

**Comment by bummytime** [comment]
@SergioEstevao it's possible. Let me take a look.

**Comment by bummytime** [comment]
@SergioEstevao Still investigating this, but in the sim not using the picker, I was able to repro the gap by initially loading a draft post in Aztec:

![simulator screen shot - iphone x - 2018-01-09 at 08 31 36](https://user-images.githubusercontent.com/154014/34725911-0cb0d6c0-f518-11e7-846a-27f1e482c962.png)

(The `inputAccessoryView` snaps back in place when you select the main content area.)

I also noticed in the sim that dismissing/activating the soft keyboard a few times can also cause the gap to appear:

![simulator screen shot - iphone x - 2018-01-09 at 08 32 44](https://user-images.githubusercontent.com/154014/34726141-cbb6674c-f518-11e7-8ebf-1df4ede82a04.png)

**Comment by bummytime** [comment]
Also, looks like this issue is only affecting the iPhone X.
