### ISSUE TITLE
Show a notice if plugin modification fails

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#8423]
When you're in airplane mode and try to disable a plugin, the toggle reverts back to enabled without giving any information to the user.

We should show notices for PluginStore errors where we aren't yet

**Comment by koke** [comment]
The new Notice UI was initially meant for notices on plugin updates, since it's a longer operation. @mattmiklic are you OK with using that UI for other errors, or should we use an alert?

**Comment by mattmiklic** [comment]
@koke This is the new in-app notification style that we designed for async and plugin update notifications right? Yeah, I think those would work well for this kind of error, when we just want to tell the user that they're offline so something couldn't happen.
