### ISSUE TITLE
Site Creation > Suggested Domains: handle no suggestions failure.

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#8429]
### Expected behavior
- Initial search: 
    - A message should be displayed.
    - The search bar should be displayed.
- Secondary search:
    - A message should be displayed.
    - The previous search results should be cleared.

### Actual behavior
- When fetching suggested domains, if it fails the view simply does nothing. There is no indication to the user what happened. 
- If it is the initial search, the search bar is not present for the user to search again.
![initial_search](https://user-images.githubusercontent.com/1816888/34840743-23e035c8-f6c3-11e7-857f-03808121b9ad.png)

- If it is a secondary search, the previous results are still displayed.
![secondary_search](https://user-images.githubusercontent.com/1816888/34840755-30a27992-f6c3-11e7-840a-c76566d2aede.png)

### Steps to reproduce the behavior
Enter a site title that results in no suggestions, either on the Site Details page or in the Domain search bar. (Currently, Japanese text returns no suggestions.)

**Comment by folletto** [comment]
> Enter a site title that results in no suggestions

Ok this is very very bad and shouldn't ever happen... :( 

I guess however that regardless, we should account as a safety measure on client side that it COULD happen.

Let's go for a message:

"No available site addresses with that name, maybe try another one?"

Simple text in the same format as the one above ("Pick and available...").

> A message should be displayed.

If there's a proper error, maybe:

1. First try automatically 5 seconds later, hoping it's a glitch
2. Then visualize the same screen as the "Whops" one — maybe with a different copy?
