### ISSUE TITLE
Editor: Images that have been resized don't center correctly

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#8442]
### Expected behavior

If I set an image to be a "Thumbnail" size then center it, I expect the image to appear centered when I view it on a post or page. This would also match up to how the image appears within the editor. 

Here's an example of an image that I centered within the editor: 

![img_2cca6b7b756e-1](https://user-images.githubusercontent.com/2998162/34919164-e4c6a80e-f956-11e7-9819-86b1f1f14d80.jpeg)

### Actual behavior

The image is not correctly centred when viewed on a post or page. 

The image from the first screenshot appears aligned to the left when viewed:

<img width="869" alt="screen shot 2018-01-14 at 18 32 26" src="https://user-images.githubusercontent.com/2998162/34919298-5400993a-f959-11e7-9f8c-c1a658b9f703.png">

### Steps to reproduce the behavior

1. Navigate to the new post editor within the app.
2. Insert an image by tapping the + sign and then selecting an image.
3. Tap on image within the editor and then "Edit".
4. Select "Size" and then choose any size other than "Full Size".
5. Select "Alignment" and then choose "Center".

##### Tested on an iPad Mini, iOS 11.2.2, WPiOS 9.0

Reported in 252806-h

**Comment by SiobhyB** [comment]
Another report in 253356-h.

**Comment by elibud** [comment]
@diegoreymendez pinging you on this one, may be you want it on the Aztec repo?

**Comment by designsimply** [comment]
Tested and confirmed using the steps provided. 

Screenshots of the thumbnail image appearing centered in the Aztec editor:

<img alt="img_1774" src="https://user-images.githubusercontent.com/1119271/35015859-1e0e5952-facb-11e7-8f26-15b9b3fea324.PNG" width="200" /> <img alt="img_1775" src="https://user-images.githubusercontent.com/1119271/35015858-1de60ce0-facb-11e7-9afa-8edba120b982.PNG" width="200" /> <img alt="img_1776" src="https://user-images.githubusercontent.com/1119271/35015857-1dd0b372-facb-11e7-81f5-2575f14082cf.PNG" width="200" />

Screenshot of how the post looks after publishing and viewing in Safari on iOS:

<img alt="img_1777" src="https://user-images.githubusercontent.com/1119271/35015855-1dba4164-facb-11e7-9aaf-20555d8ce8db.PNG" width="200" />

Tested with iPhone 6S, iOS 11.2.1, WPiOS 9.1.

**Comment by designsimply** [comment]
Reported a very similar issue at https://github.com/wordpress-mobile/AztecEditor-iOS/issues/890

**Comment by diegoreymendez** [comment]
Closed the issue in the Aztec repo, since this problem is WP-specific.

**Comment by diegoreymendez** [comment]
Ping @SergioEstevao ^
