### ISSUE TITLE
Update UIDeviceIdentifier dependency

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#8445]
We're using a really old version of UIDeviceIdentifier that doesn't include the newer models. The author [recommends](https://github.com/squarefrog/UIDeviceIdentifier/issues/32#issuecomment-354085319) pointing the pod directly to master:

```ruby
pod 'UIDeviceIdentifier', :git => 'https://github.com/squarefrog/UIDeviceIdentifier.git'
```

We'll have to update Automattic-Tracks-iOS first, since it's also pinned to 0.4

**Comment by designsimply** [comment]
@koke is this still needed?

**Comment by koke** [comment]
It seems like we're using the latest version now 👌
