### ISSUE TITLE
Notify the user clearly when they are out of storage to upload media

### ISSUE THREAD

**Issue by kwonye** [wordpress-mobile/WordPress-iOS#8450]
Currently when the user has run out of storage in their plan, we simply show an error message.

Suggestion from @sarahblackstock: 

> The error does not directly tell them they’re out of space. Would it be possible to make it do that? Something that tells them they’re at 3 out of 3GB or directs them to buy a plan to add more could help them understand what the problem is right away.

cc @elibud

**Comment by sarahblackstock** [comment]
+1 

User confused about "media failed" notice when trying to upload. Their site was out of storage space.
internal ref: #257011-h

**Comment by elibud** [comment]
Thanks @sarahblackstock this one is on our list for NoDeadEnds, we'll make it a priority to help with support volume.

**Comment by eduardozulian** [comment]
We got another probably request on 938051-zen. The user would love to see their current available storage (like we do show in Calypso or WP Admin) when they browser their dashboard via app.

**Comment by kwonye** [comment]
![simulator screen shot - iphone x - 2018-02-23 at 13 37 22](https://user-images.githubusercontent.com/1158819/36701998-362b3b54-1b0a-11e8-9dc8-530730d51c22.png)

Just for documentation purposes we do say why the upload failed if they select the box. I don't like how hidden it is though.

**Comment by elibud** [comment]
@SylvesterWilmott FYI. maybe we can think of a way for displaying the available space to the user?

@kwonye do you know if there's any way of seeing the available space  if you are uploading directly on the editor?

**Comment by kwonye** [comment]
@elibud there is not. That’s something @frosty made a good suggestion about which is showing it wherever the user uploads media (media library/picker/etc)

**Comment by frosty** [comment]
Calypso displays this in the media library:

<img width="206" alt="screen shot 2018-02-28 at 09 00 33" src="https://user-images.githubusercontent.com/4780/36778843-e74e2b6a-1c65-11e8-8b9b-5f2c7a22ee80.png">

I wonder if we could add something similar at the bottom of our media library, or even in the media picker somewhere.

**Comment by SergioEstevao** [comment]
This was solved by #8819 #8851 and #8834
