### ISSUE TITLE
9.0 - Cannot View Plugins through Mobile APP

### ISSUE THREAD

**Issue by dmkjr** [wordpress-mobile/WordPress-iOS#8451]
### Expected behavior
Find a button to view plugins per the latest release.

### Actual behavior
N/A

### Steps to reproduce the behavior
I cannot find where plugins will be listed inside the mobile app.

##### Tested on [device], iOS [version], WPiOS [version]
9.1

**Comment by elibud** [comment]
Hi there, you should find the button at the end of your Site settings:

![simulator screen shot - iphone 8 - 2018-01-15 at 21 30 35](https://user-images.githubusercontent.com/5558824/34966553-5e5570c6-fa3b-11e7-9229-e26ad721c89f.png)

Also, please make sure you are running the latest version of Jetpack. If you are still having issues please let me know your site's URL and I can a look.

**Comment by dmkjr** [comment]
Hello.  Thanks for the reply.  It was not there originally.  I removed the application and reinstalled.  I saw the "Plugins" section afterwards.  Thanks!

**Comment by elibud** [comment]
Awesome, thanks for letting us know.
