### ISSUE TITLE
Switch site make app crash

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#8452]
### Expected behavior

When I press "Switch Site" app did not crash and shows me a list of my sites.

### Actual behavior

App crashes when opening "My Sites" screen

### Steps to reproduce the behavior

When logged in - click on "Switch site". the app will crash. Tested on latest `develop` (515b3bc) using test user

Crash log:  https://pastebin.com/a2NhxPA7

##### Tested on iPhone 8 Plus Simulator, iOS [11.2], WPiOS [515b3bc]

![screencast 2018-01-15 22-14-52](https://user-images.githubusercontent.com/5654161/34974597-cc51cbc2-fa42-11e7-98ad-99b7a3b6c4c6.gif)

Discovered by UI test (but it wasn't clear from test failure report)

**Comment by elibud** [comment]
Hey @brbrr can you please include a video of the crash? I'm not getting it on `develop`. Thank you

**Comment by ScoutHarris** [comment]
@elibud , @brbrr - this is the same as #8441 . It is fixed, pending review, here https://github.com/wordpress-mobile/WordPress-iOS/pull/8449. Until then, you can work around this by disabling the siteCreation Feature Flag.

**Comment by elibud** [comment]
Great, thanks @ScoutHarris, assigning this ticket over to you so you can close it once that's merged.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/8449.
