### ISSUE TITLE
Stats: Posts & Pages: Inconsistency when tapping post/page titles

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#8453]
### Expected behavior

I expected for the app to act consistently whenever I clicked on a post or page title within the stats.

### Actual behavior

Depending on where I'm viewing the post or page title within stats section, the app sometimes takes me to more detailed stats and sometimes takes me to a preview of that post/page.

### Steps to reproduce the behavior

1. Navigate to the Stats section of the app.

2. Tap the "Months" or "Years" tab, and make sure that the "View All" button is visible in the "Posts & Pages" module.

3. Tap on the very first post or page in the "Posts & Pages" module. You'll see that you're taken to more detailed stats on that post or page. For example, this is what I saw when tapping "Home page/Archives" from the above screenshot:

![img_2d650c2c015a-1](https://user-images.githubusercontent.com/2998162/34986866-1aa5f6b8-fab1-11e7-8876-f8b5767f3baa.jpeg)

4. Navigate back and then select the "View All" button at the bottom of the "Posts & Pages" module. The list of posts and pages will expand. 

![img_cb34f7efc6f9-1](https://user-images.githubusercontent.com/2998162/34986701-7479cd5a-fab0-11e7-941f-8edb468e1666.jpeg)

5. Tap on the very first post or page in the list again. You'll see that you're now taken to a preview of that post or page. This is what I saw when tapping "Home page/Archives" again:

![img_0fbb8e79b4f0-1](https://user-images.githubusercontent.com/2998162/34987038-bb38d550-fab1-11e7-9be7-e5411b0ddc69.jpeg)

Reported in 253625-h. Possibly related to the request in #7159 too.

##### Tested on iPad Mini, iOS 11.2.2, WPiOS 9.0.1

**Comment by eurello** [comment]
Some related feedback from a customer on this: 

> In the android app, if I viewed my daily stats, I could tap on a post title 
and it would take me to the stats page on just that post. If I tapped on the 
title again from that page, it would take me directly back to that post. The IOS 
app will not do this. There seems to be no link directly back to that post from 
the stats page. Very frustrating.

The customer would like for the link back to the post to be available from the stats area on the iOS app, as it is in the Android app. 

#1902265-zen

**Comment by ScoutHarris** [comment]
@SiobhyB , @eurello - thank you for this information.

The initial issue @SiobhyB posted will be corrected with the Stats Refresh project - selecting a Post/Page from either view will now show the Post Stats view.

@eurello - the feedback you provided is _not_ in the current design for Stats Refresh. Would you mind creating a separate issue for this, and I'll follow up on it?

Thank you!

**Comment by eurello** [comment]
Sure - done! #11344

**Comment by ScoutHarris** [comment]
@eurello - thank you!
