### ISSUE TITLE
Notifications: New Post Notification doesn't display all notification content

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8461]
### Expected behavior

When I get a new post notification, I expect the notification detail to be the same in Calypso and the app. Example of what appears in Calypso for a post with text and a captioned image:

![screenshot-2018-01-16-10-14-22](https://user-images.githubusercontent.com/8658164/35049859-3e4d5bc2-fb99-11e7-96ac-2c77256e15c4.png)

### Actual behavior

Some of the content doesn't show up in the iOS app notification. Here's the same notification in the app, note the text is missing:

![image](https://user-images.githubusercontent.com/8658164/35049883-4e7e4858-fb99-11e7-9861-426157c4a3de.png)

I also don't see the option to like the post from the notification in the app.

### Steps to reproduce the behavior

1. Enable new post notifications on a site — currently possible at https://wpcalypso.wordpress.com/following/manage (internal ref: p5PDj3-4mp-p2)
2. Publish a post on that site including text and a captioned image
3. Check your notifications in Calypso and the app

**Comment by lancewillett** [comment]
I ran into this today, too — when using the WordPress for iOS app on a personal blog. App version 9.2.

<img src="https://user-images.githubusercontent.com/66797/35303246-7fa6fb96-004e-11e8-88e8-a901ec3a2548.png" width="480" />

<img src="https://user-images.githubusercontent.com/66797/35303257-8a362e6a-004e-11e8-9133-86569977bad1.png" width="480" />

**Comment by catehstn** [comment]
This feature shipped without mobile support. I think we are adding as part of #nodeadends (@elibud ?)

**Comment by elibud** [comment]
We are adding support to configure notifications for new posts but I wasn't aware that the existing delivered notification was not working, I will look into it.
@theck13 I'm pretty sure this is not a problem on Android but can you please double check it? Thx

**Comment by theck13** [comment]
It's not a problem on Android.

![notification](https://user-images.githubusercontent.com/3827611/38040799-8874af38-326d-11e8-97fb-0eadbe0ffe90.png)
