### ISSUE TITLE
Tags: Possible to rename a tag to match an existing tag

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#8470]
Since I'm familiar with how tags work on WordPress.com, I know that if I give a tag the same name as another existing tag, I'll get a `-2` added to the end. With the current iOS app, it's not clear that's happening so if I had a long list of tags and didn't know that, I could get a bit confused.

### Steps to reproduce the behavior
1. Create two tags. I used "Run" and "Running."
2. In the iOS app, go to Settings -> Tags.
3. Change the name of "Run" to "Running" (match existing tag)

### Expected behavior
I expected either to be warned about the duplicate tag or have some indicator that the tag is a duplicate of an existing tag. In this case, I only have two tags so it's pretty evident, but with a long list, that wouldn't be the case.

### Actual behavior
No notice or warning.

![img_4364-1](https://user-images.githubusercontent.com/7240478/35161102-6af933a8-fcfc-11e7-920b-04303cd5333c.jpg)

**Comment by designsimply** [comment]
Tested with iPhone 6S, iOS 11.2.2, WPiOS 9.2.0.20180117 and confirmed that I am able to create what looks like duplicate tags in the app.

<img src="https://user-images.githubusercontent.com/1119271/35172295-e53e52d2-fd1b-11e7-8e07-7ec2a3eb91a2.PNG" width="270">

Note: I cannot see the same duplicate tag in a browser after saving it in the app.

![screen shot 2018-01-19 at fri jan 19 1 26 22 pm](https://user-images.githubusercontent.com/1119271/35172409-6d130536-fd1c-11e7-9885-1a70459b2f3f.png)
<sup>Seen at https://wordpress.com/settings/taxonomies/post_tag/design5279.wordpress.com using Safari 11.0.2 on macOS 10.13.2.</sup>
