### ISSUE TITLE
Tags: Prevent empty tag name

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#8472]
### Expected behavior
When I'm editing a tag, I expect to receive an error if I try to change the tag to have just a space for the tag name. This would match the current behavior in Calypso:

![screen-shot-2018-01-19-at-7-21-02-am](https://user-images.githubusercontent.com/7240478/35161318-1251df60-fcfd-11e7-994a-80038900c257.jpg)

### Actual behavior
I can enter a tag name with just a space.

### Steps to reproduce the behavior
1. Create a new tag with the name "Test."
2. Go to edit the tag.
3. Change the tag name to just a space.
4. Click "< Tags" to return to the previous screen.

Notice that the tag name was saved with an empty space.

**Comment by elibud** [comment]
Fixed here: https://github.com/wordpress-mobile/WordPress-iOS/issues/8473
