### ISSUE TITLE
Tags: Cursor position off between title and description fields

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#8474]
This is a super duper minor nitpick, but when I’m creating a tag, the cursor in the tag title field seems to start even with the field title of “Tag.” The description field feels like it almost has a space before the cursor.

![bwcmot-1](https://user-images.githubusercontent.com/7240478/35161470-94e61e50-fcfd-11e7-8084-59c4116a18e3.jpg)

**Comment by jeremeylduvall** [comment]
Similarly, when I tap into a tag description field, double tap on a word, and use the highlight controls (the little dots) to highlight more/less text, the top one can appear cut off (almost like a z-index issue). I only bring this up because I did some quick testing, and it doesn’t look like it happens elsewhere.

![img_4368](https://user-images.githubusercontent.com/7240478/35161639-044766fa-fcfe-11e7-87e0-4a75a48733bb.jpg)

**Comment by elibud** [comment]
@frosty  maybe you can help me on this one? I can see that we are using the [`readableContentGuide`](https://github.com/wordpress-mobile/WordPress-iOS/blob/360ba662ba1cce3a9a203ae4ee0b3f3458e3b79d/WordPress/Classes/ViewRelated/Blog/SiteManagement/SettingsTitleSubtitleController.swift#L157) here, so this might be an OS bug? Meaning, the margins are fine, however the highlight controls shouldn't be cropped, right?

**Comment by frosty** [comment]
@elibud The leading padding can be removed by adjusting some of the insets on the text view (I can push up a PR for this). I'm not sure about the selection handle – I'm not seeing that behaviour on my device.

**Comment by elibud** [comment]
@frosty but do we want to update the insets? I feel like if we are using the default ones we should continue to as that would make the app more consistent.
I'm not seeing the cropping issue on my IPhoneX either, so I'll definitely blame that on the OS. @jeremeylduvall you should get an IPhoneX ;)

**Comment by frosty** [comment]
I think for this screen it's okay to adjust the margins. By default, a text view has more padding than a text field, so if we want them to line up we'll need to adjust something.

**Comment by elibud** [comment]
Would you mind taking care of that @frosty I'm swamped with other tag issues that need to be fixed before we release `9.2`. Thanks

**Comment by frosty** [comment]
@elibud Sure thing. Do we want it fixed for 9.2?

**Comment by elibud** [comment]
9.3 is fine for this one, thank you.
