### ISSUE TITLE
build with iPhone7 

### ISSUE THREAD

**Issue by flatworld21** [wordpress-mobile/WordPress-iOS#8476]
### Expected behavior
build successful

### Actual behavior
Code Signing Error: No profile for team 'PZYM8XX95Q' matching 'WPiOS Development Profile' found:  Xcode couldn't find any provisioning profiles matching 'PZYM8XX95Q/WPiOS Development Profile'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'

### Steps to reproduce the behavior
 build and select my own iPhone 7

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 7

**Comment by jleandroperez** [comment]
Hello there @flatworld21,

I'm afraid this issue is caused by missing Provisioning Profiles (on your end), that would allow you to run the app on your own device. [You can learn more about it here](https://developer.apple.com/support/code-signing/).

Cheers!
