### ISSUE TITLE
Tags: refreshing an empty tag search results in the "No Tags Yet" screen

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#8478]
Steps to reproduce:

1. Start from a site that has a lot of tags saved (there are 176 tags on the site I tested).
1. Go to WPiOS > Settings > Tags.
1. Search for a non-existent tag.
1. While the empty search is still showing, wwipe down to refresh the page.

<strong>Result:</strong> I see a message that says "No Tags Yet Would you like to create one?" even though the site has several tags. I expected that either the empty search result would remain or that I the whole tags page would refresh and I would see the entire tag list.

<img src="https://user-images.githubusercontent.com/1119271/35172877-426fc326-fd1e-11e7-8126-9d3e35c42457.PNG" width="270">

**Comment by elibud** [comment]
@designsimply can you make a quick gif about this one? I'm not being able to replicate it. Thank you

**Comment by elibud** [comment]
@koke made us a video :)

[tags-refresh-bug.mp4.zip](https://github.com/wordpress-mobile/WordPress-iOS/files/1655914/tags-refresh-bug.mp4.zip)

I'm going to leave this one for the next groundskeeping rotation as it not a high priority at all.
