### ISSUE TITLE
Tags: tag counts do not update

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#8479]
Steps to reproduce:

1. Go to WPiOS > Settings > Tags.
1. Create and save a new tag.
1. Create and publish a new post with the app using the tag created in step 2.
1. Create and publish a new post from a browser using the tag created in step 2.
1. Go to WPiOS > Settings > Tags and check the count next to the tag created in step 2.

<strong>Result:</strong> after creating a new tag and publishing posts using that tag, the tag count is not updated in the app. I tried restarting the app and the count still wasn't updated.

<img src="https://user-images.githubusercontent.com/1119271/35173275-b20f178a-fd1f-11e7-917d-2f12ad0ab6fc.PNG" width="270">

![screen shot 2018-01-19 at fri jan 19 1 48 59 pm](https://user-images.githubusercontent.com/1119271/35173267-abff6dae-fd1f-11e7-8882-255a7a7b8eca.png)
<sup>Seen at https://wordpress.com/settings/taxonomies/post_tag/design5279.wordpress.com using Safari 11.0.2 on macOS 10.13.2.</sup>

**Comment by elibud** [comment]
Hey @designsimply I'm trying to replicate this one but it's consistently working for me on .com and Jetpack sites. Can you try and double check in case it was a momentary glitch on the API? Thanks

**Comment by designsimply** [comment]
I re-tested and the tag count did update this time if I created a post from within the app, but the count did not update if I created a post on WordPress.com (as you noted in your last comment).

Video: [1m52s](https://cloudup.com/cwmm-V87kIt)
<sup>Tested with iPhone 6S, iOS 11.2.2, WPiOS 9.2.0.20180117.</sup>

**Comment by elibud** [comment]
Last round of testing by @designsimply was successful, closing this one.
