### ISSUE TITLE
API: Follow requests pass source in POST Body JSON instead of Query string

### ISSUE THREAD

**Issue by westi** [wordpress-mobile/WordPress-iOS#8483]
### Expected behavior
Follows from the App are correctly attributed to ios instead on unknown

### Actual behavior

The code here: https://github.com/wordpress-mobile/WordPress-iOS/blob/15fa82b48ccf9e7eb5002e9654edf1d5138dca2a/WordPressKit/WordPressKit/ReaderSiteServiceRemote.m#L44
Passes the source as a Parameter which ends up in the POST body as JSON.

The API is defined as accepting source in the query string.

### Steps to reproduce the behavior
Follow a site in the App

##### Tested on [device], iOS [version], WPiOS [version]

WordPress/9.1 (iPhone; iOS 11.2.2; and by @nheagy in the emulator.

**Comment by Rhetorical** [comment]
@westi, I Wanted to see if you could answer a question for me on this, the API for `follow` has the `source` in the Query Parameters. Wouldn't that mean that the source would end up in the POST and not the query string?

https://developer.wordpress.com/docs/api/1.1/post/sites/%24site/follows/new/

**Comment by westi** [comment]
@Rhetorical yes - the source should be in the Query String, but currently it ends up in the POST body.

**Comment by Rhetorical** [comment]
@westi, it's a POST method though, wouldn't that mean that all query parameters would be in the POST body? The API call doesn't have any Method Param for `source`.

**Comment by westi** [comment]
While is it a POST method, you can POST to a url with a query string included which is why we need to specify the source in the url that we POST to
