### ISSUE TITLE
Editor: Exiting post options while featured image is uploading removes image from post

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8509]
### Expected behavior

I expect that once I select a featured image in the post options, that image will be set as the featured image on my post.

### Actual behavior

If I select a featured image for my post, but tap the "Back" button to leave the post options before the image finishes uploading, the image is uploaded to my media library but isn't set as the featured image on my post.

It's only set as the featured image if I wait in the post options until the upload finishes, and there's no warning when I leave the post options that this will cause any problems.

### Steps to reproduce the behavior

1. Start a new post.
2. Optional: Add post content and save the post as a draft.
3. Open the post options.
4. Select "Set Featured Image" and choose an image to upload from your device.
5. Before the image finishes uploading, tap the Back button.
6. Open the post options again.

Result: There is no featured image set in the options.

**Comment by SergioEstevao** [comment]
Solved on version 9.9
