### ISSUE TITLE
Feature Request:  Ability to be able to select a different language in the iOS app then the device language

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#8512]
I had a user in Helpshift request the ability to be able choose a different language in the app then what the OS is set to. I know this is possible currently in Android, but I don’t think it is in iOS.

In this case they were specifically asking to change the language because of a few translation problems they had discovered.  

As a note this is not a frequently asked for feature, so I have set to low priority.

**Comment by elibud** [comment]
Hey @charliescheer yes definitely not something on the roadmap, technically it's complicated and it would benefit a very small number of users. If they've had issues with translations, we can invite them to contribute at [Translate WordPress for iOS](https://translate.wordpress.org/projects/apps/ios), what do you think?

**Comment by charliescheer** [comment]
I agree, I spoke with the a18s about it and they told me how to push the user in the direction of assisting us with the translations.  So for now going that route is certainly easiest.  If I start seeing more requests for this I will add them to the comments on this issue

**Comment by elibud** [comment]
I'm closing this one for now as we won't implement it any time soon, it's way too complicated and non-standard practice in iOS. If we receive more requests feel free to re open it.
