### ISSUE TITLE
Gravars in Managed Followed Sites in Reader

### ISSUE THREAD

**Issue by catehstn** [wordpress-mobile/WordPress-iOS#8513]
### Expected behavior
Sites show their actual gravatar.

### Actual behavior
When scrolling, sometimes the wrong gravatar shows up next to the site name.

### Steps to reproduce the behavior
Follow lots of sites.
Open up manage followed sites.
Scroll around (slower connection may help).

##### Tested on [device], iOS [version], WPiOS [version]
iOS, latest version.

I suspect we just need to nil out the image when re-using tableview cells. Reported by @m.

**Comment by elibud** [comment]
@bummytime can you take this one in your upcoming Groundskeeping rotation? Ping me if I can help.

**Comment by catehstn** [comment]
![20180124213333-2f36201a79 gif-2-mp4 com](https://user-images.githubusercontent.com/6810182/35350292-646215d6-0135-11e8-924e-d7792eab5174.gif)

**Comment by bummytime** [comment]
@elibud Yep! On it.
