### ISSUE TITLE
Better error message when trying to follow a site which has already been followed.

### ISSUE THREAD

**Issue by catehstn** [wordpress-mobile/WordPress-iOS#8514]
### Expected behavior
Unobtrusive alert saying that a site has already been followed.

### Actual behavior
Scary modal error message.

### Steps to reproduce the behavior
Try to follow a site that has already been followed.

##### Tested on [device], iOS [version], WPiOS [version]
iOS, current.

Reported by @m.

![image uploaded from ios](https://user-images.githubusercontent.com/6810182/35349909-30f31782-0134-11e8-94f0-f9c4a82cac3a.png)

**Comment by elibud** [comment]
I think the new notices @frosty has been working on might be a great fit for this one. @frosty what do you think?

**Comment by frosty** [comment]
@elibud Yes, definitely – I have a branch ready to go to use Notices here, and just need to get something else merged first.
