### ISSUE TITLE
My Sites: when all sites are hidden, the search bar is displayed.

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#8522]
### Expected behavior
When all sites are hidden, the search bar should not be displayed as it does nothing.

### Actual behavior

When all sites are hidden, the search bar is displayed.

![hidden_sites](https://user-images.githubusercontent.com/1816888/35411187-0f331df8-01d5-11e8-8a67-0e001be36270.png)

### Steps to reproduce the behavior
Hide all sites on an account.

##### Tested on [device], iOS [version], WPiOS [version]
All.

**Comment by ScoutHarris** [comment]
FYI @folletto since we discussed this.

**Comment by folletto** [comment]
Thank you for tracking this! :)
