### ISSUE TITLE
Bug: Erratic behavior when attempting to change site title or tagline

### ISSUE THREAD

**Issue by jeffgolenski** [wordpress-mobile/WordPress-iOS#8584]
**Expected behavior**

WordPress.com OR Jetpack site: Expected to navigate to Themes > Customize > Site Identity > and be able to change the tagline and site title. 

**Actual behavior**

When I navigate to Site Identity the behavior is fairly erratic and unpredictable. Makes it nearly impossible edit the site title or tagline. When I tap on each input field, the text cursor blinks randomly around the app. Sometimes I tap on the tagline input and type and it changes the title, and vice versa.

I was able to duplicate this bug for a WordPress.com site and a Jetpack self-hosted site. 

This screen recording will show you!

https://cloudup.com/cYx7bZnda2K

**Steps to reproduce the behavior**

* Select a WordPress.com OR Jetpack site from within ios app
* Navigate to Themes > Customize > Site Identity
* Attempt to change the title or tagline

**Tested on**

Device: iphone 8+
iOS: 11.1.1
WordPress App: iOS 9.2.1

**Comment by iamthomasbishop** [comment]
From the original request thread, I wondered:

> ...if this is due to web view jankiness? I’ve seen all kinds of input/form weirdness on iOS 11 as of late, similar to what the example above looks like. As a test, I went to the Customizer => Site Identity in iOS 11.2.5 Safari, and I’m seeing similar weirdness with misplaced cursor.

**Comment by rachelmcr** [comment]
Yeah, it sounds a lot like this issue: https://bugs.webkit.org/show_bug.cgi?id=176896

There are comments there that this is fixed in iOS 11.3, so fingers crossed?

**Comment by ScoutHarris** [comment]
It does appear to be fixed in iOS 11.

iPhone:
- 11.2: confirmed jankiness.
- 11.3: no jankiness.

iPad:
Wasn't an issue. Tested on 11.2 and 11.3, this issue was never present. 

As such, I'm closing this.
