### ISSUE TITLE
Enhancement request: Resizing multiple images

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#8587]
We received feedback in p77Llu-9N5-p2 that it was tricky for people to set a default size for multiple images in the app.

If, for example, a user would like to set all of their images to "medium" then they'd need to take the following steps for every single image:

1. Tap on image within the page/post editor.
2. Tap on Settings.
3. Tap on Size > Medium.

It would be handy if there was a way for users to set a default size for all images on their site.

**Comment by SergioEstevao** [comment]
@folletto should add this to site settings? or app settings?

**Comment by folletto** [comment]
If I'm not mistaken WordPress Core simply remembers the latest setting. If the latest image was inserted medium, the next one is inserted medium.

Would that be doable?
