### ISSUE TITLE
Cannot compose offline with images

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#8588]
This issue was previously closed in #1630 as it was moved to a new repo (which is not used). I'm starting a fresh issue as it came up in a round-up of feedback in p77Llu-9N5-p2.

### Expected behavior

For images that are uploaded to a post or page while offline to be saved to the post when the device is back online.

### Actual behavior

Any images that are uploaded to a post or page while offline are removed when you attempt to update the post. You can, however, manually tap on each image to retry the upload.

### Steps to reproduce the behavior

1. Turn WiFi off on device.
2. Navigate to My Sites > Blog Posts and either create a new post or edit an existing one.
3. Upload multiple images and enter some text.
4. Turn WiFi back on on device.
5. Navigate to post to "Update". You'll then see an error alerting you to the fact that your images will be lost.

**Comment by SiobhyB** [comment]
This came up in 1270552-z. The person contacting us is on a trail, with little access to Internet. They'd like to be able to compose posts and upload images to those posts while offline and on the trail.

**Comment by SiobhyB** [comment]
This came up again in 1436691-z. The person contacting us is a cyclist, who travels a lot and would like to be able to edit posts offline.

**Comment by SiobhyB** [comment]
This was also requested in 1631743-z.

**Comment by SiobhyB** [comment]
Another request for this to be improved in 1819047-zen.

**Comment by SergioEstevao** [comment]
With the latest offline work, this was fixed and now images are uploaded/retried when the device is back online.
