### ISSUE TITLE
Login: Small typo in "not a WordPress site" error message

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#8597]
`We're sure this is a great site -- but it's not a WordPress site, so you can't connect it to with this app.`

The `it` and `to` after `connect` need to be swapped around so it reads as follows: `We're sure this is a great site -- but it's not a WordPress site, so you can't connect to it with this app.`

### Steps to reproduce the behavior

1. Open the WordPress app. If you're logged into a site, log out so that you're taken to the login screen.
2. Tap the "Log in to your site by entering your site address instead." option to the lower left of the screen.
3. Enter the URL to a non-WordPress site and tap "Next".

Screenshot:

![033bb6d965c6b484e2c6222dcc4283f60629fefc](https://user-images.githubusercontent.com/2998162/36019792-4a5fb838-0d78-11e8-879d-77c8a7a4c144.png)
 
##### Tested on iPad Mini, iOS 11.2.5, WP 9.2.

**Comment by rachelmcr** [comment]
While we're at it, could we change the double hyphen `--` to an em dash `—`?
