### ISSUE TITLE
Jetpack site remains on my sites list after disconnection

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#8605]
### Expected behavior

After site was disconnected I can not see it in my site list anymore

### Actual behavior

Jetpack site remains on my sites list after disconnection. After re-login – that site disappears from the list, so it seems just cache error.

### Steps to reproduce the behavior

1. Connect any Jetpack site (e.g. created with jurassic.ninja)
2. Disconnect that site
3. Check your sites list

##### Tested on iPhone SE, iOS 11, WPiOS 9.3.0.20180201

![disconnected_site_dvd](https://user-images.githubusercontent.com/5654161/36088141-77108bb8-1008-11e8-9941-85cf906d7547.gif)

**Comment by elibud** [comment]
I'm thinking that now that we have the new connection flow we could display an alert on sites that have Jetpack disconnected and prompt a connection flow, @koke what do you think?

**Comment by koke** [comment]
Confirmed. I think if the site was disconnected from the web it should disappear from the app. When we allow disconnecting from the app, it would offer the option to reauthenticate (if it was using REST, we don't have the password for XML-RPC) and keep the site or remove it.
