### ISSUE TITLE
Draft Extension: Fix presentation on iPads

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#8646]
The draft action extension is not presenting well on iPads:

<img width="1130" alt="screen shot 2018-02-19 at 8 42 22 am" src="https://user-images.githubusercontent.com/154014/36383583-31af6202-1552-11e8-9dbf-2d8a1cf29ef3.png">

1. The white background from `MainDraftActionViewController` is visible on the iPad and should be set to `.clear` (**Note:** it is still needed on the regular width size class because of the host app's view being removed from the view hierarchy when the action extension is displayed)

2. For extra credit, figure out why the VCs presentation is not expanding like it does on the share extension:

<img width="1092" alt="screen shot 2018-02-19 at 9 01 36 am" src="https://user-images.githubusercontent.com/154014/36384027-839f0210-1553-11e8-8da1-e28df8ef9340.png">

**Comment by frosty** [comment]
I've spent a bit of time looking into this, and I can't see an easy fix – the easiest option would be to remove our custom presentation entirely, and go fullscreen at compact width, which is what iOS wants to do.

The ideal fix would be to detect the size class and drop the padding in the `ExtensionPresentationController` only for regular width – but I can't see any way to detect the size class of the host app. The extension itself always reports compact, so we can't tell when it's open in a narrow split vs wide split or full width.

The other option would be to simply remove the presentation padding _entirely_ on iPad – that would mean we go 'full screen' when the app is opened in a narrow split, but I don't think it looks too bad. Particularly with the rounded corners:

![simulator screen shot - ipad pro 9 7-inch - 2018-02-19 at 17 03 21](https://user-images.githubusercontent.com/4780/36389526-31148c1a-1597-11e8-8e25-fdd458e6b525.png)

**Comment by bummytime** [comment]
@frosty is the full screen option something you are proposing for just the drafts extension?

**Comment by bummytime** [comment]
@frosty it does afaik. @folletto do you have any thoughts on the full screen option for drafts? ☝️

**Comment by folletto** [comment]
Thanks for the ping.

I think the latest suggestion above seems the best balance given the issue at hand. It actually seems something we would aim for, so that's good.
