### ISSUE TITLE
Login email entry screen breaks down with large text on small screens

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#8674]
iPhone SE with large fonts really blows this screen up.

![36422986-f5e72b08-161c-11e8-95c7-fc8e59375a5b](https://user-images.githubusercontent.com/517257/36492797-97a57982-16f3-11e8-8bec-3450dbdc7b35.png)
![36422234-fc26780a-1619-11e8-967b-265944777b11](https://user-images.githubusercontent.com/517257/36492800-9a239446-16f3-11e8-8199-38474c518602.png)

Note: this is not included in the current 9.5 signup UI refresh.

**Comment by ctarda** [comment]
Fixed as part of PR #8909
