### ISSUE TITLE
Jetpack: Cancelling connection flow after WordPress.com login leads to broken Notifications tab

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8690]
### Expected behavior

I expect that if I cancel the Jetpack connection flow I can continue using the app. If I successfully logged in to WordPress.com the notifications tab should start working even if I didn't approve the Jetpack connection on my self-hosted site.

### Actual behavior

If I cancel the Jetpack connection flow instead of approving it, the Notifications tab ends up in this broken state with the notifications tabs and dividers appearing over the Jetpack login prompt:

![2018-02-22 15 39 13](https://user-images.githubusercontent.com/8658164/36548079-3d825840-17e7-11e8-958c-fc5da63c54c5.png)

This is also visible for a moment right after completing the full connection flow, until the tab refreshes. However, refreshing the tab manually doesn't resolve the issue when I cancel the connection flow.

### Steps to reproduce the behavior

0. If you are logged in to WordPress.com in the app, log out first.
1. Log in to a self-hosted site in the app.
2. Open the Notifications tab.
3. Select "Set up Jetpack."
4. Follow the on-screen instructions if needed to install and activate Jetpack.
5. Log in to WordPress.com when prompted.
6. On the screen asking you to approve the connection, cancel it instead.

##### Tested on iPhone 6, iOS 11.2.6, WPiOS 9.4.0.20180221

**Comment by elibud** [comment]
I'll look into this, thanks for the report @rachelmcr
