### ISSUE TITLE
Keyboard can not closed, App  will die.

### ISSUE THREAD

**Issue by CivelXu** [wordpress-mobile/WordPress-iOS#8715]
### Expected behavior
Keyboard can closed
### Actual behavior
APP will be stuck and need to be closed manually
### Steps to reproduce the behavior
At the edit text interface, input a large number of text, then slide textview. From top to bottom, the keyboard will slowly downwards. When the slide reaches the bottom, the keyboard will be stuck and cannot be retracted. APP will also be unable to operate and manually shut down.
##### Tested on [device], iOS [version], WPiOS [version]
iPhone X , IOS 11, App Store  New version

**Comment by catehstn** [comment]
Hi, can you elaborate on this a bit more, perhaps include a video? It's not clear what the problem is, which makes it hard to reproduce (or fix). Thank you!

**Comment by CivelXu** [comment]
![img_1258](https://user-images.githubusercontent.com/19768199/39295730-bf42c6ec-4971-11e8-9733-6af8401c0de4.PNG)
Look  at this  picture;
APP will die; When scrollview keyboard down
Test By iPhone X  iOS 11  the laster wordpress version

**Comment by frosty** [comment]
Thanks for the update – I can confirm that I can recreate this:

* Add more than a screen's worth of text to a post
* Drag down the screen to hide the keyboard
* Once the keyboard disappears, the app freezes

Technically: it looks as though something in `updateForSafeAreaInsets` in `Aztec/FormatBar.swift` is causing the `safeAreaInsets` to constantly toggle between `0`, `3`, and `6` when the keyboard is hidden in this way.
