### ISSUE TITLE
Crash on Jetpack sites with VideoPress (Atomic or other third party)

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#8727]
### Expected behavior

Uploading videos to an Jetpack site that has VideoPress active and then publish of the post where the video is attached should work correctly.

### Actual behavior

When uploading larges video to a site sometime after the upload completes and the publish button is pressed the publish action fails and then pressing publish again makes the app crash

### Steps to reproduce the behaviour

- Create a new post on a Jetpack site with VideoPress active
- Add a new video to it (preferably a large one, more than 100Mb size)
- Expect for the upload to finish
- The moment the upload finish, tap on Publish on the post
- See if an error message shows up
- Tap Publish again, see the app crash

**Comment by dbtlr** [comment]
It takes time for an upload to actually complete. It runs in a background job and can take upwards of 5 minutes to be processed by our servers and for the data to be sent back down to the Jetpack site. There needs to be some way of looking at these items and taking into account that they are in a "processing" status. VideoPress will eventually update that status, however, until that happens the media items are not usable.
