### ISSUE TITLE
Plugin List:  On a slower device, if you tap on a plugin multiple times it loads multiple times

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#8741]
I was messing around with the new plugin management section of the iOS app, and I noticed that if my app waited for a few seconds (my iPad mini is getting on in years) and I tapped on the same plugin a few times the app would try to load the page several times once it caught up.

Check out this video of that happening:

http://cld.wthms.co/oE91vB

In this video, from the plugin list I tapped on Yoast three times, once the Yoast page actually loads, it tries to load 2 more times.

1. In the app go to the plugins directory.
2. Tap on a plugin multiple times before the directory disappears.
3. Wait for a few seconds, and the view will try to load multiple times.

<s>It does seem like this may be a device speed issue, but I'm not completely sure.  I was not able to replicate the problem on my iPhone.</s>  I went to work on something else slightly later and was able to make replicate on my iPhone as well

Problem occurred on iPad Mini 3, WordPress 9.5, iOS 11.2.2
iPhone 6s, WordPress 9.5, iOS11.2.2

**Comment by elibud** [comment]
😱 @jklausa can you take a look at this one please?

**Comment by jklausa** [comment]
On it

**Comment by jklausa** [comment]
Done by #8887

**Comment by jklausa** [comment]
Fixed by #8943.
