### ISSUE TITLE
Signup: Redirect to login flow when email is already being used

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8748]
### Expected behavior

If my email address is already used on WordPress.com, and I try to sign up for an account with that email, I should be redirected to the login flow. This is how the Android signup flow works. (Internal ref: p5T066-Bj-p2)

### Actual behavior

After entering an email address that is already used on WordPress.com, I get this error:

> Sorry, that email address is already being used!

### Steps to reproduce the behavior

1. Select the signup option in the app.
2. Sign up with email.
3. Enter an email address that's already used on WordPress.com and submit it.

##### Tested on iPhone 6, iOS 11.2.6, WPiOS 9.5.0.20180227

**Comment by rachelmcr** [comment]
Note that this is also an issue for the "Sign up with Google" option, if the email address is already linked to an account:

1. Select the signup option in the app.
2. Sign up with Google.
3. Log in to a Google account with an email address already linked to a WordPress.com account.

Expected: You are redirected to the login flow.
Actual: You complete the signup flow without any indication that you are actually logging in to an existing account (it goes through the "New Account" screen and everything as if it were a new account).

**Comment by nheagy** [comment]
Just thinking: would there be value in doing the opposite for login: if their email isn't found in the system, moving them to signup? Or is the chance for typos too high?

**Comment by rachelmcr** [comment]
>Just thinking: would there be value in doing the opposite for login: if their email isn't found in the system, moving them to signup? Or is the chance for typos too high?

We shouldn't auto-redirect them to signup, because if they're entering their email in the WordPress.com login form it could be a typo or a self-hosted site. But we do have something like this in the Google login flow, where signup is one of the suggested options:

![2018-03-01 11 06 32](https://user-images.githubusercontent.com/8658164/36841583-ad4ff1f6-1d40-11e8-8d74-83577a01f2d2.png)

**Comment by nheagy** [comment]
@rachelmcr aha! I really like the idea of reusing the Google error screen options.

Now it seems obvious I've taken this on a tangent. @elibud do you think email-not-found errors are a dead end we should investigate?

**Comment by elibud** [comment]
Lets track it and see? If many users fall down this path we can try to figure out a way to help them.

**Comment by folletto** [comment]
Aside: now that both login and signup have been completed, we should think on how to converge them (i.e. social signups shouldn't differentiate signup and login, some alignment such as the above, and cross-links where necessary).
