### ISSUE TITLE
Signup: Display Name isn't saved after navigating to Change Username screen

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8749]
### Expected behavior

If I change my Display Name on the New Account screen during signup, that change will be saved.

### Actual behavior

If I change my Display Name during signup, and then tap on Username to change it, when I go back to the New Account screen my Display Name change is lost (the name is reverted to the default).

### Steps to reproduce the behavior

1. Select the Signup button.
2. Select "Sign up with email."
3. Enter a new email address and tap "Next."
4. Open the mail app and tap the button in the magic link email.
5. On the New Account screen, change your Display Name.
6. Tap on Username to open the Change Username screen.
7. Tap "Back" (you don't have to make any username changes).

Result: The Display Name is reset to the default; the previous changes weren't saved.

##### Tested on iPhone 6, iOS 11.2.6, WPiOS 9.5.0.20180227

**Comment by etoledom** [comment]
Fixed in #8773
