### ISSUE TITLE
Plugins: Jetpack on Pressable site marked as inactive

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#8755]
### Expected behavior

Jetpack plugin marked as activated

### Actual behavior

Jetpack plugin marked as inactive

### Steps to reproduce the behavior

Open "Manage Plugins" on your Pressable site

##### Tested on iPhone SE, iOS 11.2.5, WPiOS 9.5.0.20180227

![img_6a8b8d82edfc-1](https://user-images.githubusercontent.com/5654161/36788245-bc0db286-1cbf-11e8-8a48-2c37e9ae80ad.jpeg)

**Comment by elibud** [comment]
@jklausa incoming 🚀

**Comment by jklausa** [comment]
Note: Jetpack is showing as disabled because the Jetpack **Beta** is enabled. We'll figure out what's the best way to handle this in the UI.

**Comment by brbrr** [comment]
I wasn't able to reproduce it with new pressable sites.

**Comment by jklausa** [comment]
This was fixed by #8780.
