### ISSUE TITLE
Plugins: VaultPress on Atomic site marked as inactive

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8772]
This case is somewhat similar to https://github.com/wordpress-mobile/WordPress-iOS/issues/8755 but specific to Atomic sites.

### Expected behavior

Clear status for all plugins, including plugins like VaultPress that are managed for me on Atomic sites. For example, Calypso shows this status:

> Auto-managed on this site

### Actual behavior

The VaultPress plugin is marked as inactive and I can't change it. The most confusing case for me was VaultPress, but other plugins that are managed for me on Atomic sites (Jetpack, Akismet) can be potentially confusing because I don't have any controls for them.

### Steps to reproduce the behavior

1. Select an Atomic site in the app.
2. Open the plugins section.
3. View the status and details for Atomic managed plugins (Jetpack, Akismet, VaultPress).

### Screenshots

Plugins in the app:

![2018-03-01 11 38 31](https://user-images.githubusercontent.com/8658164/36843701-a21eca58-1d47-11e8-8905-8600ea283c8b.png)

Plugins in Calypso:

![screenshot 2018-03-01 11 39 32](https://user-images.githubusercontent.com/8658164/36843745-ca6e15b8-1d47-11e8-9a09-160244f203ed.png)

##### Tested on iPhone 6, iOS 11.2.6, WPiOS 9.5.0.20180227

**Comment by elibud** [comment]
@jklausa please take a look at this one. Thanks
