### ISSUE TITLE
Sing Up hanging with already linked account

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#8775]
### Expected behavior
Be automatically logged in if the user chose to sign up with an already used account.

### Actual behavior
When trying to sign up(iOS) using Google account which already used – I get stuck on “Waiting for Google to complete” screen. I would expect to redirect back to the welcome screen.

![screenrecording_02-28-2018-14-13-152](https://user-images.githubusercontent.com/5558824/36845480-a71e1750-1d35-11e8-9d09-e41cba14e641.gif)

**Comment by elibud** [comment]
@brbrr Can you please check if you can replicate this one? It might've been a glitch with Google since it's now working correctly for me.

**Comment by etoledom** [comment]
@elibud It just happened to me too. I will see if I can get any insight.

**Comment by etoledom** [comment]
This is very interesting:

When an account exists, the `createWPComeUserWithGoogle` returns an error.

In the error handler, there is the display error logic, and that's it.
I don't see any logic that could automatically log in the user.

[Here](https://github.com/wordpress-mobile/WordPress-iOS/blob/839c547e1af7ba6f4d5c7744a309701276ee09b1/WordPress/Classes/ViewRelated/NUX/SignupGoogleViewController.swift#L76)
```
}) { [weak self] (error) in
    SVProgressHUD.dismiss()
    WPAnalytics.track(.signupSocialFailure)
    guard let error = error else {
        self?.navigationController?.popViewController(animated: true)
        return
    }
    self?.displayError(error as NSError, sourceTag: .wpComSignup)
}
```

So if I may ask, where and how does it work for you? 
That's the mystery I'm seeing now 😆

**Comment by elibud** [comment]
Well, is not failing for me, I was just debugging and it takes the first path:

```
service.createWPComeUserWithGoogle(token: token, success: { [weak self] in 
    // IT GOES HERE
     SVProgressHUD.dismiss()
     self?.performSegue(withIdentifier: .showSignupEpilogue, sender: self)
     WPAnalytics.track(.signupSocialSuccess)
}) { [weak self] (error) in
    // NOT HERE
    SVProgressHUD.dismiss()
    WPAnalytics.track(.signupSocialFailure)
    guard let error = error else {
         self?.navigationController?.popViewController(animated: true)
         return
    }
    self?.displayError(error as NSError, sourceTag: .wpComSignup)
}
```

Here's the gif:

![success](https://user-images.githubusercontent.com/5558824/36858156-2b4d9b2c-1d59-11e8-8a51-6f48bfb48a25.gif)


Are you doing anything differently @etoledom?

**Comment by etoledom** [comment]
There is another interesting thing there!

I have one google account that jumps **always** to the 'New account' screen, and another google account that always fails.

The only difference is that the one that jumps to the 'New account' screen, I created it through this path, while the one that get stuck is an old account.

If you notice, your account also jumps to the 'New account' screen. Maybe that's the bug? 🐛

**Comment by elibud** [comment]
I actually thought that going to that epilogue screen was harmless, but now that I think about it it's a serious problem because it allows users to change their username which they should only be able to do once in their lifetime. I can see, however, that as a response of the `createWPComAccount` method the account we receive a field called `created_account` with value 0 for an existing Google account, so we may be able to use that to differentiate between an existing and a new account and act accordingly.

**Comment by nheagy** [comment]
> it allows users to change their username which they should only be able to do once in their lifetime

atm in developer builds this can be done endlessly on the Me tab 😜

**Comment by elibud** [comment]
🤦‍♀️

**Comment by brbrr** [comment]
I was able to reproduce this issue with 2 of my accounts. I think I know what the problem I experiencing - both emails are linked to WP.com account (which means I can (and should) use email option instead. 

used email: `wpnativee2etest@gmail.com`
