### ISSUE TITLE
Create New Site layout issue

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#8776]
On iPhone SE “Next” Button in “Create new site” screen overlaps some of the text:

![img_2827](https://user-images.githubusercontent.com/5558824/36845609-38f3e060-1d36-11e8-9152-f9b0e8827e9e.png)

**Comment by folletto** [comment]
We reviewed this and we have two options, of which we'd like to consider for now the one that is more technically simple and maintainable:

* (A) When the page height is taller than the visible area (i.e. it goes below the Next button) we detach the Next button and put it "on" the page (i.e. scrolling with it)
* (B) We add a fixed background below "Next" like a toolbar. Caveat: this has to be flexible to adapt the potential text on the left of the button.

Which one is more technically feasible?


## Rationale

We reviewed different options in the discussion that reached the conclusion above. We explored:

1. It's like a "FAB", so it can float. It's not an issue, we keep it.
2. We add a "rectangle" below the "Next" button so it cuts text.
3. below a threshold (TBD) we detach "Next" and attach it to the page, as there's already a "Next" on the keyboard, and the other next would become accessible by scrolling.
4. Put the "Next" button on the navigation bar at the top (by @hypest) 

@mattmiklic also noted that "this resolution will continue to decline in popularity" to frame properly the extent of the issue. Also, as noted by @iamthomasbishop this is impacted not just by screen size, but also by typography size settings.

Thomas also provided a mock of an approach discussed for variable font size that matches (2) above:

![image_uploaded_from_ios](https://user-images.githubusercontent.com/4389/37208743-60efde38-239a-11e8-8716-76d1302d243b.jpg)

And he pointed out that iOS already have "Done" on keyboard toolbars (`inputAccessoryView`):

![screen shot 2018-03-09 at 13 05 11](https://user-images.githubusercontent.com/4389/37208791-850a1838-239a-11e8-9ce6-fc9e341d198a.png)

The agreement is that we should find a solution that is technically simple to maintain, but at the same time solves the issue. Other solutions exist, but would require a larger refactoring of the bottom/top navigation UI.

**Comment by folletto** [comment]
I added "Needs Code Review" as there's no specific "Needs Technical Assessment" label.

**Comment by designsimply** [comment]
I tested this in 11.8 and 12.0-beta with iPhone 6S iOS 12.1.4 and used Settings > General > Accessibility > Larger Text to simulate a case where the button might overlap and found it appears option B has been used where the bottom right button is in a fixed position with no text wrapping.

<img src="https://user-images.githubusercontent.com/1119271/54238712-d1839200-44de-11e9-97ff-3dff9ae19c19.PNG" width="270" alt="IMG_2081">

Here are some extra screenshots from WPiOS 11.8 (left) WP Internal 12.0.0.20190311 (right) on iPhone 6S iOS 12.1.4 for reference (there are no overlaps but you can see how the overall design has changed).

<img src="https://user-images.githubusercontent.com/1119271/54238554-689c1a00-44de-11e9-82ca-59fcd03c911f.PNG" width="270" alt="IMG_2075">   <img src="https://user-images.githubusercontent.com/1119271/54238305-b3696200-44dd-11e9-8087-a61f7d9ff584.PNG" width="270" alt="IMG_2077">

I am adding this issue to the `Site Creation : iOS` project for a quick check on iPhone SE to confirm no further action is needed. Please close this issue if that's the case or comment noting what still needs to be done if changes are still needed.

**Comment by elibud** [comment]
@ctarda @stevebaranski can one of you please take a look at this one?

**Comment by stevebaranski** [comment]
@designsimply thanks for surfacing this. 

The original issue was reported against the "circa 2018" Site Creation flow shortly after it was deployed last year. 

The screenshots [here](https://github.com/wordpress-mobile/WordPress-iOS/issues/8776#issuecomment-472199477) juxtapose that experience with the new Site Creation flow rolled out in v11.9. The step depicted in the flow was implemented as Option B describes (i.e., with `NUXButton`).

I believe it can be closed; I will do that (& remove the label) as requested.

**Comment by nheagy** [comment]
The problem still occurs on login screens:

![Simulator Screen Shot - iPhone SE - 2019-03-13 at 10 34 38](https://user-images.githubusercontent.com/517257/54301208-b9ae1b80-457b-11e9-8db1-406848b204d6.png)

At the time this issue was made, both login and site creation used the same base UI. Now that they've diverged, the fix for this issue should be ported back to login screens as well.

@designsimply should we create a new issue to track that, or reopen this one?

**Comment by stevebaranski** [comment]
@nheagy to be filed against `WordPressAuthenticator`, yes?

**Comment by nheagy** [comment]
@stevebaranski I prefer to log UX issues on the app(s) vs. the pods, where I feel they get lost. But I defer to @designsimply’s judgement.

**Comment by designsimply** [comment]
> @designsimply should we create a new issue to track that, or reopen this one?

A new issue with the designs copied over would be great! @nheagy, I agree about filing on the app repos for the reason you mentioned.

**Comment by designsimply** [comment]
To close the loop here, I found an earlier report of the problem with the login screen at #8790 and reopened it.
