### ISSUE TITLE
App crashing when you search for short username in email signup flow

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#8777]
![screenrecording_02-28-2018-15-51-30](https://user-images.githubusercontent.com/5558824/36845696-7d7615e6-1d36-11e8-8047-d954425bf80b.gif)

**Comment by koke** [comment]
Crashing on `SignupUsernameTableViewController.startSearch(for:)` when it calls `reloadSection`:
```Invalid update: invalid number of rows in section 1.  The number of rows contained in an existing section after the update (0) must be equal to the number of rows contained in that section before the update (1), plus or minus the number of rows inserted or deleted from that section (0 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).```

You can also test by going to Me > Account Settings > Username, which is quicker than sign up

**Comment by etoledom** [comment]
Thanks @koke for the tip!

We are removing the textfield when there are 0 suggestions:

```
override func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
...
    case Sections.searchField.rawValue:
        return suggestions.count > 0 ? 1 : 0
```

By returning 1 (always show the search field) the problem seems to be solved. But was there any special reason for removing the Search field? @elibud @nheagy

**Comment by elibud** [comment]
Thank you both for looking into this @koke and @etoledom, lets wait until we hear back from @nheagy to make a decision.

**Comment by etoledom** [comment]
One more detail:

If you have a short Display name and you want to change your Username, there is no Search field to look for a new one. This also happen if we fix the crash with a fast `.reloadData()`.

![artboard](https://user-images.githubusercontent.com/9772967/36850084-8b151dc4-1d44-11e8-8981-1858811e917e.png)

**Comment by nheagy** [comment]
FWIW I think y'all really nailed the problem and I approve of @etoledom's fix 😀
