### ISSUE TITLE
Login Layout Issue

### ISSUE THREAD

**Issue by jorgecasariego** [wordpress-mobile/WordPress-iOS#8790]
### Expected behavior
 "Next" button is below the text "Log in by entering your site"

### Actual behavior
"Next" button overlap the text "Log in by entering your site"

<img src="https://user-images.githubusercontent.com/2581647/36901703-d9dca248-1e06-11e8-8557-3e91fb3158b0.png" width="270" alt="simulator screen shot - iphone se - 2018-03-02 at 10 45 29">

### Steps to reproduce the behavior
1. Tap Log In in the first screen
2. Tap to write an email address

**Comment by elibud** [comment]
@kwonye  @etoledom I believe you are already tracking this issue as part of BetterTogether, is that correct?

**Comment by etoledom** [comment]
Yes! @ctarda is tackling this kind of issues in the login flow.
But this fix (afaik) wasn't considered to be part of the 9.5 release.

This is also related to #8674

**Comment by elibud** [comment]
Yes that's ok, we are fine addressing this in 9.6, closing as we are already tracking this.

**Comment by designsimply** [comment]
Re-opening because the "Next" button overlapping some of the text was found to still be happening on iPhone SE as of Mar 13, 2019. See https://github.com/wordpress-mobile/WordPress-iOS/issues/8776#issuecomment-472528744.

**Comment by designsimply** [comment]
Also noting that a design was provided and is already implemented in the "Create New Site" screens. #8776 includes some discussion about the designs and more detail.

![Screen Shot 2019-03-18 at 12 43 35 PM](https://user-images.githubusercontent.com/1119271/54555074-94564e80-497b-11e9-8f97-cd9075aa6ce2.png)

<img src="https://user-images.githubusercontent.com/1119271/54239374-a0a45c80-44e0-11e9-9146-365e268be485.png" height="480" alt="IMG_2081">

**Comment by kean** [comment]
Closing as obsolete.
