### ISSUE TITLE
Posts accidentally deleted

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#8798]
### Expected behavior

Not to be able to accidentally delete a post.

### Actual behavior

There's no action sheet or blocking action that makes deleting posts accidentally hard.

### Steps to reproduce the behavior

Delete a post ;)

**Comment by elibud** [comment]
X referencing https://github.com/wordpress-mobile/WordPress-iOS/pull/8806 as we may want to follow the direction set there for iPad actions

**Comment by iamthomasbishop** [comment]
After thinking about this a bit, I think the right option here is an alert. It's slightly more aggressive, which I think is appropriate considering the context. Here's what it would look like:

![screenshot 2018-03-05 15 20 24](https://user-images.githubusercontent.com/1200432/37000487-3017d6da-2089-11e8-8223-9c5862f197d4.png)
