### ISSUE TITLE
String Issues - Spelling [sitle & Succesfully] Punctuation consistency [...]

### ISSUE THREAD

**Issue by garrett-eclipse** [wordpress-mobile/WordPress-iOS#8831]
### Expected behavior

Correct Spelling and Consistent Punctuation

### Actual behavior

Incorrect Spelling and mix of three periods (...) instead of the ellipsis character (…)

### Steps to reproduce the behavior

Find the invalid waiting strings here;
'sitle' - https://translate.wordpress.org/projects/apps/ios/dev/en-ca/default?filters%5Boriginal_id%5D=5728991
'Succesfully' - https://translate.wordpress.org/projects/apps/ios/dev/en-ca/default?filters%5Boriginal_id%5D=5728987
three periods (...) instead of the ellipsis character (…);
https://translate.wordpress.org/projects/apps/ios/dev/en-ca/default?filters%5Boriginal_id%5D=5728986
https://translate.wordpress.org/projects/apps/ios/dev/en-ca/default?filters%5Boriginal_id%5D=19291

##### Tested on translate.wordpress.org

**Comment by rachelmcr** [comment]
Thanks for the report and the PR! :)

**Comment by garrett-eclipse** [comment]
No worries @rachelmcr I put a few questions on the PR to finalize before it can be merged

**Comment by elibud** [comment]
cc: @nheagy @ScoutHarris @folletto

**Comment by ScoutHarris** [comment]
To note, "sitle" has been fixed on #8839.
