### ISSUE TITLE
Email Signup: epilogue and username changer views should not rotate on iPhone

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#8833]
### Expected behavior
Email Signup: epilogue and username changer views should not rotate on iPhone.

### Actual behavior
Email Signup: epilogue and username changer views do rotate on iPhone.

### Steps to reproduce the behavior
- Sign up with email. 
- Get a magic link email. 
- Click the link in the email to display the epilogue.
- Rotate the phone. The view rotates.
- Click the Username field.
- Rotate the phone. The view rotates.

This is not an issue with Google signup.

NOTE: Related to #8752. The views should not rotate, preventing that from even being an issue. However, I cannot figure out why the views _are_ rotating. @kwonye 's fix for #8752 is good to have regardless, so we'll go with that for now.

Research notes: I can see that `NUXViewController.supportedInterfaceOrientations` is being called when you select to open the app from the link. However, it is _not_ being called thereafter. It should be called when the device is rotated. I was able to see this in other View Controllers that inherit from `NUXViewController`.

**Comment by ScoutHarris** [comment]
@nheagy when you have a moment - could you look at this and maybe provide some thoughts?

**Comment by nheagy** [comment]
The problem is that somehow the `SignupEpilogueViewController` is being shown inside a regular `UINavigationController` instead of one of the NUX-based subclasses (`NUXNavigationViewController`, or `Login*`, or `Signup*` all of which have similar implementations).

I haven't yet figured out how.

**Comment by ScoutHarris** [comment]
Fixed with https://github.com/wordpress-mobile/WordPress-iOS/pull/8853.
