### ISSUE TITLE
Typo in original string

### ISSUE THREAD

**Issue by chantalcoolsma** [wordpress-mobile/WordPress-iOS#8858]
I noticed a typo in this original string:

https://translate.wordpress.org/projects/apps/ios/dev/nl/default?filters%5Boriginal_id%5D=5728991

“The site _sitle_ is missing.” should be “The site **title** is missing.”

**Comment by elibud** [comment]
Thanks for the report @chantalcoolsma it's been fixed here: https://github.com/wordpress-mobile/WordPress-iOS/pull/8839/files
