### ISSUE TITLE
Signup username changer: nav bar is transparent

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#8865]
### Expected behavior
Nav bar should be blue.

### Actual behavior
Nav bar is transparent.

### Steps to reproduce the behavior
Signup. On the epilogue, select the username to display the username changer view. Notice the nav bar is transparent.

<img width="560" alt="username_nav_bar" src="https://user-images.githubusercontent.com/1816888/37209161-63ad995a-2361-11e8-9146-f1175fd3b8bc.png">

**Comment by ScoutHarris** [comment]
Sorry @nheagy I didn't get a chance to look at this one. Maybe you can?

**Comment by brbrr** [comment]
I've run into this issue too. Besides transparency - nav bar looks not high enough:

![screenrecording_03-12-2018 16-09-57](https://user-images.githubusercontent.com/5654161/37277603-c7e10642-2617-11e8-885e-1e09de8c4f30.gif)

**Comment by elibud** [comment]
Fixed here: https://github.com/wordpress-mobile/WordPress-iOS/pull/8874
