### ISSUE TITLE
Enable format bar buttons in HTML editing mode

### ISSUE THREAD

**Issue by salty-horse** [wordpress-mobile/WordPress-iOS#8879]
This is a feature request.

##### Tested on WPiOS 9.4 (latest)

When entering HTML editing mode, the format bar remains visible, but only the button to toggle off the HTML mode is active.

The rest of the icons (bold, italics, etc) are disabled.

This is unfortunate, as the icons are already visible on screen, and the requested functionality is simple, and keeps the behavior of the [legacy editor](https://github.com/wordpress-mobile/WordPress-Editor-iOS/blob/develop/Classes/WPLegacyEditorViewController.m#L494): wrap the selected text (if any) with an html tag.

It would be nice if the "insert link" and "insert media" buttons also worked. :)

From discussions I understand that some of the rationale behind disabling the toolbar buttons is to avoid confusing users that may have entered HTML mode accidentally. If that's the case, I don't think it's a good reason to disable the buttons. A warning message before entering HTML mode should be enough. Disabling the simple formatting options hurts no-one but users who DO wish to edit HTML and have to manually type the tags, which isn't a good experience on a touchscreen keyboard.

**Comment by rachelmcr** [comment]
Thanks for the feature request! This is being tracked in the Aztec (rich text editor) repo here: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/643
