### ISSUE TITLE
Signup username changer: Selected name didn't show as selected

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#8880]
### Expected behavior

When I select not default username - it will be preselected when I open username changer once again

### Actual behavior

The default username is marked as selected with both check mark and header text ("Your current username is ...")

### Steps to reproduce the behavior

1. Start signup with Email
2. Proceed to username changer screen
3. Try to change username and re-visit username changer

##### Tested on iPhone SE, iOS 11.2.6, WPiOS 9.5.0.20180308

![screenrecording_03-12-2018 16-12-20](https://user-images.githubusercontent.com/5654161/37277326-f5ddaf2e-2616-11e8-900f-e5e8f6bdf13b.gif)

**Comment by elibud** [comment]
Fixed here: https://github.com/wordpress-mobile/WordPress-iOS/pull/8867
