### ISSUE TITLE
Site Creation and Signup: add WPAnalytics tracks

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#8883]
We need to add any missing WPAnalytics tracks for the new Site Creation and Signup flows.

As discussed with @hypest , iOS should sync our tracks with Android's, listed in the 'Tracks Mobile Events' spreadsheet:

After investigation with @theck13 these are the changes to be made:
- [x] Add parameter to `account_created` to track source email vs. social
  - [x] Do the same for login
- [x] Add `signup_button_tapped` to prologue
- [x] Add `signup_google_button_tapped` and `signup_email_button_tapped` to method selection sheet
- [x] Add `signup_terms_of_service_tapped` to method selection sheet
- [x] Add `signup_cancelled` for when method sheet is dismissed
- [x] Remove `login_social_button_click` from Google screen when signing up (covered by `signup_google_button_tapped`)
- [x] Replace `account_created` with `signup_social_to_login` when a Google signup uses existing account
- [x] Replace `account_created` with `signup_email_to_login` when a Google signup uses existing account
- [x] Add `signup_social_button_failure` for when Google signup is cancelled within Google UI
- [x] Change `signup_magic_link_open_email_client_viewed` to trigger when button pressed, not when VC is viewed (may only be when no email clients are present)
- [x] Add `signup_epilogue_viewed` when signup epilogue appears
  - *Add the following with a parameter for social vs. email*
  - [x] Add `signup_epilogue_unchanged` when no changes were made
  - [x] Add `signup_epilogue_update_display_name_succeeded` when display name changes succede
  - [x] Add `signup_epilogue_update_display_name_failed` when display name changes fail
  - [x] Add `signup_epilogue_update_username_failed` 
  - [x] Add `signup_epilogue_update_username_succeeded`
  - [x] Add `signup_epilogue_update_password_failed`
  - [x] Add `signup_epilogue_username_tapped` for when username is tapped 
  - [x] Add `signup_epilogue_username_suggestions_failed` for when username suggestion API fails

**Comment by nheagy** [comment]
Can I get a review on the checklist of changes? cc: @theck13 @SylvesterWilmott @ScoutHarris @elibud

**Comment by elibud** [comment]
LGTM
