### ISSUE TITLE
Push notifications cleared when seen on the web can be confusing

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#8898]
Currently, the moment you open the notifications panel on the web or other device, it marks notifications as *seen* even if they're still *unread*. When this happens, WordPress.com sends a push notification to reset the badge count, and all the existing push notifications are removed from notification center.

Part of the problem is that there is a disconnect between the orange dot on the bell meaning there are unseen notifications, and the app badge having an actual unread count, but only if there are unseen notifications.

But also, we're using the legacy push notifications API, and there have been several changes to the notifications API, that we might be able to sync the badge on "seen", but only delete push notifications if they are actually read.

**Comment by designsimply** [comment]
I tested with WPiOS 13.3.0.0 (TestFlight) on iPhone 6S iOS 13.1.2 and found that push notifications appeared only briefly in the notifications center regardless of whether I opened the notifications panel the web or another device. Once I opened the notifications panel on the web, it did seem to clear the badge count after a minute or so.

How can I check if we're using the legacy push notifications API?

**Comment by koke** [comment]
> How can I check if we're using the legacy push notifications API?

That's what the push notification server is using. I don't think it's the cause of the issues, but I think I mentioned it because using the new API might allows us to be smarter about them. Although I haven't fully read the documentation, so I could be wrong.

> push notifications appeared only briefly in the notifications center regardless of whether I opened the notifications panel the web or another device

That sounds like a new, much worse, issue 😞 I tested with WPiOS 13.3.0.0 (TestFlight) on iPhone XS iOS 13.1.1 and couldn't reproduce. Are you sure you had nothing else open in that account?

**Comment by aerych** [comment]
From a quick test this appears to be resolved.  I currently have two unread notifications and if I open the panel on the web these are not immediately marked as read.  The also continue to show unread in the app. 
Closing but feel free to reopen if I've misunderstood or you can reproduce with different steps.
