### ISSUE TITLE
How to build this project

### ISSUE THREAD

**Issue by versluis** [wordpress-mobile/WordPress-iOS#89]
Hi there,

I've been trying to run WordPress for iOS on my local system, hoping I could learn from it. But sadly I seem to fail at the first hurdle: when I build the project (in either Xcode 4 or 5) all I get is the following error message:

clang: error: no such file or directory: '/tmp/WordPress.build/WordPressComApiCredentials.m'
clang: error: no input files
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

This happens regardless if I open the project or the workspace file. I know my way around Xcode and have managed to release several paid apps on the app store, yet I can't run an open source project... that's depressing! Also I've never heard of CLANG.

Is there a guide that explains what I'm doing wrong?

**Comment by phamdacloc** [comment]
In the interest of generating .wpcom_app_credentials file. How exactly do I go about obtaining the:
WPCOM_APP_ID=
WPCOM_APP_SECRET=

Do I have to contact Wordpress.com to buy the ID/Secret?  I'd like to run the self-hosted site on my device using this source code.
Thanks.

**Comment by phamdacloc** [comment]
Nevermind. This link shows how to get the ID/Secret.
