### ISSUE TITLE
Posts List: "More" menu tap flips back to default after refreshing that page and navigating away and back again

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#8904]
Steps to reproduce:

1. Open a Jetpack-connected site using the WPiOS app (I used WPiOS 9.6.0.20180312).
1. Go to My Sites > {any Jetpack site} > Blog Posts.
1. Refresh that view.
1. Go back to My Sites > {any Jetpack site} > Blog Posts.
1. Tap the "More" link below any post.

<strong>Result:</strong> the "More" menu temporarily shows the "Stats" and "Trash" options but then flips back to default on it's own. Note that this only happens after a refresh then browsing away and back again (which may be grounds to close this as an edge case).

<strong>Video:</strong> [1m49s](https://cloudup.com/czwl8GYmHKg)

Tested with 4 separate sites using iPhone 6S, iOS 11.2.6, WPiOS 9.6.0.20180312:

1. http://alittletestblog.com/ running WordPress 5.0-alpha-42762 and Jetpack 5.8 on WP Engine.
1. http://madefortesting.com/ running WordPress 4.9.4 and Jetpack 5.9 on Bluehost.
1. https://design5279.wordpress.com/ on WordPress.com (Business)
1. https://convenient-cuban.jurassic.ninja/ running WordPress 4.9.4 and Jetpack 5.9 on Jurassic Ninja.

**Comment by designsimply** [comment]
Tested and confirmed it's still happening in WP Internal 12.0.0.20190320 on iPhone 6S iOS 12.1.4. I am still feeling it's pretty edge case though.

**Comment by rachelmcr** [comment]
I confirmed that with the new posts list design, this is no longer an issue. The "More" menu opens an action sheet instead of flipping the menu on the post card, and the action sheet remains open even in the scenario documented in the original issue. (Tested on iPhone XS, iOS 12.3.1, WPiOS 13.1.0.20190814.)
