### ISSUE TITLE
Extensions: UI wierdness if primary site is hidden in main app

### ISSUE THREAD

**Issue by bummytime** [wordpress-mobile/WordPress-iOS#8919]
I found an issue in the share and draft extensions: if the primary site is hidden when `ShareModularViewController` loads, the primary site's categories still load while no site is pre-selected in the site picker (the primary site is not visible in this list). If the user taps save or publish, the post will still make it to the primary site.

<img width="300" alt="napkin 65 03-16-18 9 26 03 am" src="https://user-images.githubusercontent.com/154014/37526056-74c98e10-28fc-11e8-8421-cd2346baa41f.png">

In this situation we should probably either:
1) Just show the hidden primary site anyway, ignoring visibility
**_- or -_**
2. Pre-select the first site on the picker list and load it's data (keeping the primary site hidden)

@folletto do you have a quick opinion here?

**Comment by folletto** [comment]
> Just show the hidden primary site anyway, ignoring visibility

Let's do this. 

Rationale:

1. It's aligned with Calypso, where "hidden" sites are still searchable, and can still be selected
2. It matches the intent of what a Primary site is.

Also: feels like a bug that a primary site can be made hidden, but that's a broader discussion to have.
