### ISSUE TITLE
Media: library shows "Fetching media&hellip;" instead of ellipsis 

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-iOS#8931]
### Expected behavior

Message should show "Fetching media&hellip;"

### Actual behavior

Messages shows "Fetching media`&hellip;`"

![fullsizeoutput_109e5](https://user-images.githubusercontent.com/128826/37688197-7cf1d1fa-2cea-11e8-8e6f-3e79848f50bf.jpeg)

### Steps to reproduce the behavior

1. Start a new post
2. Insert photo
3. Choose media library

##### Tested on [device], iOS [version], WPiOS [version]

iPhone 7+, 11.2.6, 9.6.0 20180316

Also saw on App Store version 9.5

**Comment by frosty** [comment]
This looks to be an issue with the Australian translations of some of our loading strings. They include the HTML entity code for an ellipsis, but we don't process / parse HTML entities in these labels. I've suggested alternative translations that revert back to `...`

**Comment by frosty** [comment]
Alternative translations have been approved, so these should make their way into the app soon. I'm going to close this, and make a note to test in the next WPiOS release (10.0).

**Comment by frosty** [comment]
I just checked with 10.0, and it looks as though this is fixed 👍

**Comment by alisterscott** [comment]
Thanks @frosty confirmed fixed 🎉
