### ISSUE TITLE
Enhancement: Alert when user tries to add media but their storage is full

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#8934]
Currently when a WPCOM user hits the limit on the amount of storage they have on their site, there is no warning or notification.  So when they try to continue adding images to their site in the app they receive an error telling them the file can't but uploaded, but it doesn't tell them why.  This has cause a good handful of issues before where a user is trying to upload images but can't.
It would be great if when a user maxes out their storage, they received a notification to inform them they have used all of their available storage and will need to upgrade to continue adding more content.
If it could also notify them when they try to add images later, to remind them that the problem is they have used all available storage on their site that would be awesome as well.

**Comment by frosty** [comment]
@charliescheer Thanks for the report – this should actually be resolved in 9.6, thanks to @SergioEstevao: https://github.com/wordpress-mobile/WordPress-iOS/pull/8834

**Comment by charliescheer** [comment]
Awesome! Thanks!
