### ISSUE TITLE
Enable signup during Jetpack setup

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#8949]
Allow users to signup for a WordPress.com account when connecting a self-hosted site with Jetpack.

**Design:**

![jetpack-connection-flow](https://user-images.githubusercontent.com/517257/37933449-7a7599b2-3108-11e8-8b24-971bfaefc4d6.jpg)

**Comment by aerych** [comment]
Looks like this was fixed in #9064
