### ISSUE TITLE
Signup: Can't cancel a username change after selecting a different username

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8962]
### Expected behavior

I expect that when I sign up and look at my options to change a username, the username I have selected before I go back is the one I'll end up with.

### Actual behavior

If I select a different username and then select my original username again, I end up with the different username instead.

### Steps to reproduce the behavior

1. Sign up for a new account in the app.
2. On the epilogue screen, select your username to go to the Change Username screen.
3. Note that your original username is first on the list with a checkmark by it.
4. Select another username from the list. Note that it has a checkmark by it.
5. Select your original username again. Note that it has a checkmark by it.
6. Select the "Back" button to go back to the epilogue screen.

Expected: I'll see my original username on the epilogue screen.
Actual: The other username I selected is shown (and is the username I see on the Me screen after completing signup).

##### Tested on iPhone 6, iOS 11.2.6, WPiOS 9.7.0.20180316

**Comment by ScoutHarris** [comment]
Fixed on https://github.com/wordpress-mobile/WordPress-iOS/pull/8966.
