### ISSUE TITLE
Signup: Posts list on a new account doesn't show the site icon/title/author on each post

### ISSUE THREAD

**Issue by rachelmcr** [wordpress-mobile/WordPress-iOS#8963]
### Expected behavior

I expect each post in the posts list to include the site icon, site title, and author display name at the top of each post in the posts list. Here's how it looks on an existing test account:

![2018-03-27 15 50 32](https://user-images.githubusercontent.com/8658164/37976545-a3a49bc2-31d9-11e8-968f-d46e8de27ddb.png)

### Actual behavior

When I sign up for a new account in the app and create a new site, the site icon, site title, and author display name don't appear at the top of each post in the posts list. Instead, there's a blank space:

![2018-03-27 15 43 39](https://user-images.githubusercontent.com/8658164/37976548-a5b92658-31d9-11e8-91e7-5d0ff3ff4b05.png)

That space persists even if I have multiple sites on my account and after setting a site icon on the site.

### Steps to reproduce the behavior

1. Create a new account in the app.
2. Create a new site for your new account.
3. Visit the posts list and note the blank space above the default post.

##### Tested on iPhone 6, iOS 11.2.6, WPiOS 9.7.0.20180316

**Comment by elibud** [comment]
@ScoutHarris can you take a look at this one please?

@rachelmcr does this get fixed the next time you open the app?

**Comment by rachelmcr** [comment]
>does this get fixed the next time you open the app?

Nope. I tried restarting the app and I tried logging out and back in to the new account, and nothing fixed it for me.

**Comment by ScoutHarris** [comment]
Fixed on https://github.com/wordpress-mobile/WordPress-iOS/pull/8965
