### ISSUE TITLE
Menus: Edit icon appears on top of shortened text

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#8981]
### Expected behavior

`Edit` icon sits near an editable text

Discovered while tesing https://github.com/wordpress-mobile/WordPress-iOS/pull/8886

### Actual behavior

`Edit` button appears just above '...' in a shortened text. After editing a text - `edit` icon appears on expected position

### Steps to reproduce the behavior

- In Settings app enable "Larger font" in Accessibility and set the largest font size
- Make sure your menu name is long enough. "Default menu" works in my case.
- Select Menus, and check the menu name

##### Tested on iPhone SE, iOS 11.2.6, WPiOS 9.7.0.20170316

![img_5acbd8fe5898-1](https://user-images.githubusercontent.com/5654161/38052920-4b7a04ac-32db-11e8-9aea-ec5b84f5c4e7.jpeg)

**Comment by ScoutHarris** [comment]
Tested on 10.3 & develop. The placement looks ok now.

![edit_icon](https://user-images.githubusercontent.com/1816888/41564334-b3a6e47c-730f-11e8-80bd-67a82b5107dd.png)
