### ISSUE TITLE
Aztec: New Private post is published as a Public post

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#8989]
### Expected behavior

If I set a post's visibility as Private and then publish it, I expect it to be published as a Private post.

### Actual behavior

When published, my new post is Public instead of Private!

### Steps to reproduce the behavior

* Open the editor to create a new post
* Navigate to `...` -> Post Settings -> Visibility -> Choose `Private`
* Back in the editor, tap Publish, and then confirm the public
* Check the published post (either in the app or a browser). It will be public, instead of private.

**Comment by diegoreymendez** [comment]
Fixed an released in 9.7.1.
