### ISSUE TITLE
Sing up for WordPress.com Button not translating with interface language.

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#8992]
I was poking about the newest version of the iOS app and I noticed if I sign all the way out of the app 
the "Sign up for WordPress.com" button does not translate to the same language as the interface, it stays in English.

I checked this on my iPhone in French, German and Dutch, and the effect was the same
<img src='http://cld.wthms.co/YfXsHp+'>

I checked with @elibud and she says that the translations are there, and they should be changing, but it isn't.

WordPress iOS 9.7 and 9.5
iOS 11.2.6

To reproduce:  
1. Set your device to a language that is not English
2. Log completely out of the app.
3. The sign up button should still be in English

**Comment by elibud** [comment]
@charliescheer I just double checked this, even though we have translations for Spanish and Italian in iOS (the two I checked), we don't have them for French, German and Dutch, so it's not a programmatic error but a missing strings one. The good news is that the French one was recently added so it will be available once 9.7 is out.
