### ISSUE TITLE
Editor: App crashes when dismissing action sheet for a second time

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/WordPress-iOS#8995]
### Expected behavior
The action sheet dismiss without crashing the app

### Actual behavior
![crash](https://user-images.githubusercontent.com/9772967/38109943-34ff500c-3370-11e8-8123-1acce3881605.gif)

### Steps to reproduce the behavior

They are shown in the gif. The media picker needs to be present for this issue to happen.

**Comment by etoledom** [comment]
This happens with **any** action sheet that is presented when the `WPInputMediaPickerViewController` is present, even when selecting an image in the editor.

And this happens (basically) because `viewWillDisappear` and `viewDidAppear` are not called when presenting the action sheet.

A fast fix can be to `closeMediaPickerInputViewController()` every time we present an action sheet.
The downside of this is that the user will come back to the keyboard instead of the picker when dismissing the action sheet. I think it also loses the first responder (coming back to the title)

Another option is to call `rememberFirstResponder()` before presenting the action sheet, and calling `restoreFirstResponder()` on every action of the action sheet.
The downside of this is that it seems to be more error prone when adding new actions or action sheets.

Any thought @diegoreymendez @SergioEstevao ?

**Comment by elibud** [comment]
Is this good to close?

**Comment by jklausa** [comment]
Not yet. I was playing with this earlier and I think I have a working fix, but needs more testing.

**Comment by diegoreymendez** [comment]
@etoledom - Unfortunately, I'm not very familiar with the media code, so I defer to @SergioEstevao for this one.

**Comment by jleandroperez** [comment]
Taking a look at this one (on groundskeeping!)
