### ISSUE TITLE
Changing system text size cancels login

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#9007]
Changing the system text size while in the login process will cancel it.

To recreate:
- Start loggin in to wpcom from the Me tab
- Switch to Settings.app and change the font size
- Switch back to WordPress and the login process is cancelled

![type-cancelling-login](https://user-images.githubusercontent.com/517257/38147231-26a3873a-3406-11e8-97a1-48f0188ebf92.gif)

Tested on `9.6` and `develop`, so I'm not sure how old this is.

Not sure what's going on here. Any thoughts @ctarda or @etoledom?

**Comment by etoledom** [comment]
Interesting, good catch!

I don't recall testing that situation in particular but I can reproduce it too. I'll take a look.
