### ISSUE TITLE
Post/Page Options: Allow users to change the post/page author

### ISSUE THREAD

**Issue by lizkarkoski** [wordpress-mobile/WordPress-iOS#9015]
Feature request brought via Twitter to add the "change author" functionality to the iOS app. 

Tweet: https://twitter.com/WegrynENT/status/979936474090082304

version 9.6

**Comment by rachelmcr** [comment]
See also past requests in this issue (from the old editor): https://github.com/wordpress-mobile/WordPress-Editor-iOS/issues/632

It also came up in an app review for version 9.8.

**Comment by SiobhyB** [comment]
This came up in a recent review:

> While this app is a lifesaver and easy to use for the most part, I'm continually frustrated by how many features from the main site are missing. For instance, there doesn't seem to be any way to assign authorship to a blog post in the app.

**Comment by KokkieH** [comment]
Another in https://twitter.com/ChristianBlogR/status/1157245753196236800

**Comment by thehenrybyrd** [comment]
Another request for this in #2871252-zen

**Comment by thehenrybyrd** [comment]
Another in #3825927-zen

**Comment by twstokes** [comment]
I'm game to take it! 👋

**Comment by twstokes** [comment]
Hey @guarani 👋 , I didn't automatically close this with the final PR. Would you mind closing it if it's the appropriate time to do so? Thank you!

**Comment by guarani** [comment]
Thanks for catching this, closing now (noting that https://github.com/wordpress-mobile/WordPress-iOS/pull/16281 is the PR that shipped this feature).
