### ISSUE TITLE
App opens, notifies user about crash, and then crashes. Recurs after reinstall.

### ISSUE THREAD

**Issue by pauljacobson** [wordpress-mobile/WordPress-iOS#9016]
### Expected behavior

The app should open as expected. If the app crashes, it should reopen after sending a crash report.

### Actual behavior

Information from user in 1048410-zen:

>The wordpress app opens for a second, pops up this message ‘the app has crashed, send crash report’ and shuts down on its down. I have to uninstall and reinstall everytime and it works fine for a day and then the same problem occurs.

### Steps to reproduce the behavior

Not tested independently. I don't have an iOS device to test this on.

##### Tested on [device], iOS [version], WPiOS [version]

The user is using an iPhone 6, iOS version 11.2.6.

**Comment by jleandroperez** [comment]
I've tried replicating this (by introducing a crash, in a release build). The Fabric.framework (crash reporting tool we use) is behaving well.

Major suspect of this is #9367, which has been released as part of WPiOS 10.0.

Closing as cannot repro. If needed, please, feel free to reopen (and please include the WPiOS version).

Thanks for helping us out!!!
