### ISSUE TITLE
Nuke WPAuthTokenIssueSolver (if possible!)

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#9063]
### Details:
`WPAuthTokenIssueSolver` was introduced few years ago, and appears to be broken (#9042, see the comment at the bottom!).

Let's analyze if it's still relevant and:

- If possible, delete the whole class!
- If not possible, let's get it patched up, since the UI looks broken.

H/t @etoledom (thank you sir!!)

**Comment by rachelmcr** [comment]
This came up again in https://github.com/wordpress-mobile/WordPress-iOS/issues/12583 and I'm going to close this issue in favor of that one, since there is discussion and proposed designs on that issue.
