### ISSUE TITLE
Logged-out view of Notifications isn't helpful enough

### ISSUE THREAD

**Issue by mikejohnstn** [wordpress-mobile/WordPress-iOS#907]
The Notifications view you see when logged out should say something specifically about Notifications, not a general "Jetpack is great" message which is confusing. Notifications are a great mobile feature and are worth talking about specifically. People may not know Jetpack, but they know the value of being notified when their blog has activity.

The screen should also have a button that allows you to install Jetpack (with sensible defaults) with a minimum amount of fuss.

Then, after Jetpack is up and running, we should make sure at least one notification shows up here (even if that's a notification that says Jetpack was installed and they'll now get notifications for their blog).

Current view (Learn More button sends you to a very web-centric list):
![screen shot 2013-12-19 at 12 55 59 pm](https://f.cloud.github.com/assets/515035/1786199/cfbb40b4-68f0-11e3-8d0c-c2560a65efa1.png)

**Comment by jleandroperez** [comment]
Closing this in favor of #1651. This issue has been already resolved in Stats, let's make the UX consistent all over!.
