### ISSUE TITLE
Bug: Photo size setting ignored

### ISSUE THREAD

**Issue by gryden1976** [wordpress-mobile/WordPress-iOS#9080]
When uploading a photo I want it to be uploaded in full size, the setting in the app is set to "Full size".

After installing 9.6 images no longer uploads in full size. I have not changed any settings in the app.

Tested on iPhone X, iOS 11.3, WPiOS 9.6.1

**Comment by gryden1976** [comment]
Same behaviour in 9.7

**Comment by gryden1976** [comment]
Bug seems to be resolved in 9.7.2

**Comment by gryden1976** [comment]
This issue needs to be reopened, its seems that photos in landscape format still uploads resized. Photos in portrait format upload in full size.

Tested on iPhone X, iOS 11.3, WPiOS 9.9

**Comment by elibud** [comment]
Lets keep this one closed and keep track of the problem in https://github.com/wordpress-mobile/WordPress-iOS/issues/9375
