### ISSUE TITLE
Possible site addresses are not appearing when creating a new site if the app is in Russian

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9088]
I received a report from a user who was having trouble making a new site.  If the language of the app is set to Russian, and you start walking through the steps to create a new site, when you get to the final page, where you enter in the site address, no options appear for you to choose from.  Even if you type into the text field no options appear, so you are unable to complete the steps and start your new site.

I tried this with a handful of languages, French, English, and Chinese, and it worked fine for all of them, the problem seemed to be isolated to just Russian.

EDIT:  I was thinking about this later and I realized when I tested Chinese, the iOS simplified keyboard using the same characters as English to present you with possible Chinese characters.  If you choose the Chinese characters for your site title the same problem happens.  So it looks like this issue is not isolated to russian, but to languages using a different character set.

To reproduce:
1. Change the language of your iOS device to Russian
2. Go to My Site > Switch Site, click on the + and choose a new WordPress.com site.
3. Walk through all of the steps.  
4.  On the last page you will not be given any options to pick a site address
<img src='http://cld.wthms.co/DXpSsr+'>

WordPress 9.6.1 iOS 11.2.6 iPhone 6s

**Comment by nheagy** [comment]
This was fixed in 9.7: https://github.com/wordpress-mobile/WordPress-iOS/issues/8429

I assume the user hasn't updated yet.

**Comment by charliescheer** [comment]
Awesome!  I took a look around for another issue like this, and didn't find it.  Thanks @nheagy
