### ISSUE TITLE
People Management: Error when attempting to invite a Follower or Viewer to a free site

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#9094]
### Expected behavior

I expected to be able to send invitations to people to view my <strike>private</strike> free WordPress.com site.

### Actual behavior

An error message pops up to inform me that "There has been an unexpected error while sending your invitation".

Screenshot:

![2f6c0050-74ac-4937-b469-a081550d5a7f 1](https://user-images.githubusercontent.com/2998162/38634307-12f9ea9a-3dba-11e8-8aec-a4fa25c98c31.png)

### Steps to reproduce the behavior

1. Navigate to My Sites and select any free WordPress.com site <strike>that you've set to private</strike> from the site picker.
2. Tap on "People" from the sidebar.
3. Select the + icon to the upper right of the screen and invite someone to be a a Follower or Viewer. 

##### Tested on iPad Mini, iOS 11.3, WPiOS 9.6.1

Reported in 273217-h

**Comment by SiobhyB** [comment]
Update: I'd assumed this was an issue with private sites only as I'd been unable to reproduce on my main, public site. 278632-h clued me into the fact that this was an issue with public sites too. I seem to only be able to replicate on sites with a free WordPress.com site address, I can't replicate the error for sites that use a custom domain.

**Comment by SiobhyB** [comment]
This is also an issue for Jetpack sites: 279506-h.

**Comment by SiobhyB** [comment]
This came up again in 282041-h.

**Comment by SiobhyB** [comment]
There's also an issue with invitations in Calypso at the moment: https://github.com/Automattic/wp-calypso/issues/24886

**Comment by westi** [comment]
These are caused by false positives in anti-bot protections and not bugs in the App.
