### ISSUE TITLE
Update notification icons to use Gridicons

### ISSUE THREAD

**Issue by mattmiklic** [wordpress-mobile/WordPress-iOS#9100]
In Notifications, we're still using the old Noticons icon font for our icons. We should update these to use Gridicons instead.

![gridicons-ios](https://user-images.githubusercontent.com/1396552/38645545-662dc91e-3db2-11e8-84c1-d8de10ac1b52.png)

**Comment by designsimply** [comment]
Tested and confirmed this is still an issue in WP Internal 12.2.0.20190412 on iPhone 6S iOS 12.2.

<img src="https://user-images.githubusercontent.com/1119271/56068279-79d58200-5d3b-11e9-8f04-7c04640d1518.PNG" width="270" alt="IMG_2509">

**Comment by aerych** [comment]
Still an issue.

**Comment by kean** [comment]
The screen was redesigned in 24.4 – closing.
