### ISSUE TITLE
Images sometimes keep local path when using the share extension

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#9118]
### Expected behavior

When using the share extension to publish a new blog post, the URL/path for any images should be updated to reference the media library.

### Actual behavior

We've had some reports of the path for images not being correctly updated and, instead, using the local path. For example:

`<img class="size-full" src="///private/var/mobile/Containers/Shared/AppGroup/96730DD9-EE6B-4D3D-A5F6-28F2CEC8BAD6/Media/image_544973529814609.jpg" />`

The image is correctly uploaded to the media library but the path is not correctly updated within the post.

### Steps to reproduce the behavior

1. Open the Photos app.
2. Tap "Select" in top right corner.
3. Choose 2 images.
4. Tap share/action button.
5. Tap WordPress icon.
6. Fill in title/body.
7. Hit next and complete publish.
8. Look at the HTML for any images in your new post.

##### Reported in 274774-h. Tested on iPhone X, iOS 11.3, WPiOS 9.6.1

Neither @bummytime or myself have been able to replicate but making a note here for further investigation.

**Comment by ChrisHardie** [comment]
This happened to me today, WP app version 12.3 on iPhone XR with iOS 12.2. Shared an image from the Photos app to the WP iOS app using the share extension. Resulting new post body displayed:

```<img src="///private/var/mobile/Containers/Shared/AppGroup/EE17DDDF-965B-410A-AB3B-70E0CA75575F/Media/image_1B6F0D17-69D0-4228-9932-EB44C538D0D3.IMG_0661.JPG" class="size-full">```

**Comment by elibud** [comment]
Thanks for the report @ChrisHardie 

@nheagy can you please take a look at this?

**Comment by nheagy** [comment]
@elibud @ChrisHardie I already have an open PR to address this issue: #11581

**Comment by elibud** [comment]
Thanks @nheagy assigning over to you then.

**Comment by elibud** [comment]
https://github.com/wordpress-mobile/WordPress-iOS/pull/11740 was merged to address this issue, please reopen if we get more reports.

**Comment by scottlee** [comment]
I'm still experiencing this issue. Steps to reproduce are the same as mentioned above. 

Did a fresh self-hosted install on a VPS, not customizations just to test. 
WP: 5.5.3
Jetpack: 9.1
iOS: 14.1
WP app: 16.0
