### ISSUE TITLE
Media Library: Allow document types to be selected in the document picker

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#9129]
The Media Library section of the app allows a user to import files from other apps using `UIDocumentPickerViewController`. Currently this support is limited to only image or video file types.

We should extend this feature by allowing the selection of other file types.

* For self-hosted sites, we should allow all file types supported by a default WordPress installation: https://codex.wordpress.org/Uploading_Files
* For WordPress.com sites, we should allow all of the file types supported by WordPress.com. Note that some of these file types are only available if the user has a paid plan on their site, so we should check for this within the app too: https://en.support.wordpress.com/accepted-filetypes/

This issue will likely require changes in a couple of places:

* The `UIDocumentPickerViewController` configuration, to allow other file types
* `MediaURLExporter` to accept other file types

**Comment by a8c-sab-trial** [comment]
@frosty I have submitted [a draft PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/9161) that adds support for this behavior. I'd like to seek your input on it, with the following callouts:

- _Hound_ found a few lifting violations. Curiously, I did not see these when I built the project, but I have resolved those by amending the commit. I'll do better next time. :)
- I asked via Slack about how to identify a plan; I received advice to consider `Blog`, which includes properties for `isHostedAtWPcom` & `hasPaidPlan`. Later I found `allowedFileTypes`, which seems to be closer to what we need in this case.
- These file types had to be passed down through a couple of layers to `MediaURLExporter`. I tried to control visibility and follow existing precedents.
- While testing with "other" file types, I noted an error in the console:
```
2018-04-22 13:45:36:332 WordPress[13420:9865192] Error occurred exporting placeholder thumbnail: Error Domain=WordPress.MediaThumbnailExporter.ThumbnailExportError Code=0 "(null)"
```
Do you have any suggestions about how we might improve thumbnail handling?
- Finally, I noted that for a WP-hosted free plan, the following was returned:
```
value = (
        jpg,
        jpeg,
        png,
        gif,
        pdf,
        doc,
        ppt,
        odt,
        pptx,
        docx,
        pps,
        ppsx,
        xls,
        xlsx,
        key
);
```
The presence of `key` (for Keynote) was unexpected, as it differs from [this reference](https://en.support.wordpress.com/accepted-filetypes/). Interesting enough, attempting to upload a Keynote file evinced the following server-generated error:
```
2018-04-22 12:17:25:668 WordPress[4264:9741967] 🔵 Tracked: media_service_upload_failed, properties: {
    "error_code" = 3;
    "error_description" = "Error Domain=WordPressKit.WordPressComRestApiError Code=3 \"Sorry, this file type is not permitted for security reasons.\" UserInfo={WordPressComRestApiErrorCodeKey=upload_error, WordPressComRestApiErrorMessageKey=Sorry, this file type is not permitted for security reasons., NSLocalizedDescription=Sorry, this file type is not permitted for security reasons.}";
    "error_domain" = "WordPressKit.WordPressComRestApiError";
}
```
This leads me to suspect a potential bug.

I suspect [9131](https://github.com/wordpress-mobile/WordPress-iOS/issues/9131) should be fairly straightforward, once we agree on the solution here.

Please let me know if there's anything else I might have overlooked. I appreciate your input!

**Comment by a8c-sab-trial** [comment]
Thanks for indulging the questions & providing the insight!

- The project `README.md` suggests that `SwiftLint runs automatically when you build the project`; would it be out of line for me to submit a PR that clarifies that?
- I updated the PR to move the `Blog` extension into a standalone file. It also transitions to a broader set of UTI types that should work for self-hosted sites or in the event that `allowedFileExtensions` was empty for another reason. Please let me know if it works okay for you.
- The amended PR commit reflects the change you suggested for thumbnails.

I was happy with how this change turned out. I look forward to your feedback.

**Comment by frosty** [comment]
Definitely feel free to go ahead and submit a PR to fix `README.md` – good catch!

**Comment by a8c-sab-trial** [comment]
I submitted [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/9181) to address the `README` discrepancy discussed herein.
