### ISSUE TITLE
Aztec: Enable multiple selection for document picker

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#9130]
The media picker toolbar in Aztec allows a user to import files from other apps using `UIDocumentPickerViewController`. Currently this support is limited to selecting a single image / video at a time.

We should extend this feature by enabling multiple selection within the document picker.

Note that in there past there may have been an issue with this feature not working correctly, but as far as I'm aware it should be possible now.

**Comment by a8c-sab-trial** [comment]
@frosty I have addressed this issue with [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/9151). It's worth noting that this resolution is subject to the same constraints noted in Issue [9128](https://github.com/wordpress-mobile/WordPress-iOS/issues/9128).
