### ISSUE TITLE
Aztec: Allow document types to be selected in the document picker

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#9131]
In #9129, we're adding support for other document types to our use of `UIDocumentPickerViewController` in the Media Library.

We should also replicate this functionality for the document picker integration in Aztec. There may be an opportunity here to extract some helper class / methods and share code between these two places.

**Comment by a8c-sab-trial** [comment]
While there is admittedly some [ongoing discussion](https://github.com/wordpress-mobile/WordPress-iOS/issues/9129) about thumbnails and supporting additional document types, I wanted to solicit your thoughts about desired behavior when choosing to add one of these document types here.

- I believe that the extension of `allowedTypeIdentifiers` (added to `MediaLibraryViewController` via #9129) can be promoted to `Wordpress\Classes\Models\Blog`. This will allow us to reuse it [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/9d9ee981a75d6389c7e774060bbb20d75161373c/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L2139).
- Once that's complete, is it safe to assume that handling of selected media will be covered elsewhere? Looking at [`AztecPostViewController.insert(exportableAsset:source:attachment:)`](https://github.com/wordpress-mobile/WordPress-iOS/blob/9d9ee981a75d6389c7e774060bbb20d75161373c/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L2779-L2790), it appears that will be tantamount to a no-op.

**Comment by frosty** [comment]
* I agree, we should promote `allowedTypeIdentifiers`, as it'll be useful in a couple of places.
* Currently Aztec supports inserting non image or video media that's already in your media library. This is eventually done in `AztecPostViewController.insertRemoteSiteMediaLibrary(media:)`, which inserts a link to the media. I think we should do this same thing if a non image or video document is selected from the document picker.

**Comment by a8c-sab-trial** [comment]
Thanks to feedback from @frosty & @SergioEstevao, I have modified the original PR.
