### ISSUE TITLE
Refactor WPAnalyticsStat to simplify analytics related to media uploads

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#9138]
There's a lot of duplication both in `WPAnalyticsTrackerAutomatticTracks.m` and `WPAppAnalytics+Media.swift`. Perhaps we could do the following:

Remove all the special cases from the WPAnalyticsStat enum, so we're only left with:
- WPAnalyticsStatEditorAddedPhoto
- WPAnalyticsStatEditorAddedVideo
- WPAnalyticsStatMediaLibraryAddedPhoto
- WPAnalyticsStatMediaLibraryAddedVideo

This would greatly simplify the switch in eventForMediaType.
Then set the via property directly in properties(for media:) in MediaAnalyticsInfo, based on the origin property. We could add a var to the MediaSource enum which returns the correct value to put in the properties dictionary.

**Comment by etoledom** [comment]
Closed via #9125
