### ISSUE TITLE
Stock Photos: previews look very pixelated

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#9172]
Steps to reproduce:

1. Go to My Sites > Blog Posts > +.
1. In the body of the post, go to Add Media > {ellipsis menu} > Free Photo Library.
1. Enter a search term.
1. Tap to select any photo.
1. Tap the "Preview" option at bottom left.

### Expected behavior

I expected to see accurate, high quality previews of stock photos.

### Actual behavior

Stock photo previews look extremely pixelated. Once inserted, the images look great.

<img src="https://user-images.githubusercontent.com/1119271/39159972-fb9eba04-4725-11e8-902e-67be2a68e9e6.PNG" width="270"> <img src="https://user-images.githubusercontent.com/1119271/39159976-fecf6282-4725-11e8-839a-187baa96228a.PNG" width="270">

**Comment by brbrr** [comment]
Confirming same behavior on iPhone SE

**Comment by ctarda** [comment]
Implemented in [this PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/9189)
