### ISSUE TITLE
Stock Photos: Pull-down (Refresh) behavior isn't matching rest of the App

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#9174]
### Expected behavior

Pull-down behavior is in line with rest of the app

### Actual behavior

Pull-down (Refresh) behavior isn't matching behavior on other screens (i.e. Posts list)

### Steps to reproduce the behavior

1. Go to My Sites > Blog Posts > +.
2. In the body of the post, go to Add Media > {ellipsis menu} > Free Photo Library.
3. Enter a search term.
4. Pull-down to the bottom of the screen

![screenrecording_04-24-2018 13-50-38](https://user-images.githubusercontent.com/5654161/39183648-6798efa6-47c9-11e8-91c4-3a02ad65a6f7.gif)

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by jkmassel** [comment]
This screen is now presented in a modal, so pulling to refresh would dismiss the list.

Closing because it's no longer applicable.
