### ISSUE TITLE
Stock Photos: No loading indicator when searching

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#9176]
### Expected behavior

Loading indicator is shown when sending a search request

### Actual behavior

It is not clearly visible that search is underway. Loading indicator is missing

### Steps to reproduce the behavior

1. Go to My Sites > Blog Posts > +.
1. In the body of the post, go to Add Media > {ellipsis menu} > Free Photo Library.
1. Enter a search term.

##### Tested on iPhone SE, iOS 11.3, WPiOS 9.9.0.20180423

**Comment by etoledom** [comment]
Fixed in #9196
Thank you @brbrr for highlighting this!
