### ISSUE TITLE
Stock Photos: "X" and Cancel buttons have similar behavior

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#9177]
<img width="331" alt="img_4d328e177043-1 jpeg 2018-04-24 13-38-33" src="https://user-images.githubusercontent.com/5654161/39184822-94fd9736-47cd-11e8-8344-27cad583e1af.png">

Buttons 2 & 3 have similar behavior - clearing search field and remove search results. I find this confusing, and I think one of these buttons is redundant.

### Expected behavior

There is only 1 button which can clear the search field and remove results. 

### Actual behavior

There are 2 buttons which have basically the same behavior

### Steps to reproduce the behavior

1. Go to My Sites > Blog Posts > +.
1. In the body of the post, go to Add Media > {ellipsis menu} > Free Photo Library.
1. Enter a search term.

**Comment by etoledom** [comment]
Hey @brbrr , thanks for noticing this!

There is one particular difference in the behavior of those two buttons:

- The `Cancel` button will finish the searching session, hiding the keyboard. This is intended to be used when the user doesn't want to search any more.

- The `x` button is intended to clear the searching phrase, without finishing the search session. The keyboard will remain visible. This is intended to be used when the user wants to start searching for a different phrase and its needed to clear completely the previous phrase.

This behavior is also present in the Media Library search bar, and in general in most (if not all) the system search bars.

**Comment by iamthomasbishop** [comment]
The `cancel` button in the top navigation bar should say `Close`, not `Cancel`. I should've caught this during Design Review, my bad!

![stock photos](https://user-images.githubusercontent.com/1200432/39210025-25cc9d62-47cd-11e8-8dbc-b6691ef40782.jpg)

**Comment by etoledom** [comment]
The original issue, we decided that it's expected behavior.
The issue mentioned by @iamthomasbishop was solved in #9190.
