### ISSUE TITLE
Stock Photos: Search results are shuffling when typing

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#9178]
This is an edge case when you start typing before search results completely loaded. The results get shuffled every time new char is typed. 

### Steps to reproduce the behavior

1. Go to My Sites > Blog Posts > +.
1. In the body of the post, go to Add Media > {ellipsis menu} > Free Photo Library.
1. Enter a search term.
1. Right after image frames are shown start typing

![screenrecording_04-24-2018 10-49-31](https://user-images.githubusercontent.com/5654161/39187629-7e4571c2-47d6-11e8-9ac2-2331f267dc96.gif)

**Comment by etoledom** [comment]
Fixed in #9195
