### ISSUE TITLE
Sign up: default username unexpectedly selected

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#9179]
### Expected behavior

Tapping on selected username will not select default username

### Actual behavior

When tapped on selected (not default) username - default username got selected

### Steps to reproduce the behavior

1. Start Sign up process, proceed to username/password screen
2. change username to some custom value & go Back
3. go to "change username" screen once again & tap on pre-selected username
4. go Back. Default username would be selected. 

##### Tested on iPhone SE, iOS 11.3, WPiOS 9.9.0.20180423

![screenrecording_04-24-2018 16-19-43](https://user-images.githubusercontent.com/5654161/39190065-79951f32-47dc-11e8-9806-48c90d36c758.gif)

**Comment by elibud** [comment]
@nheagy can you look into this one please and fix it on the frozen branch?

**Comment by diegoreymendez** [comment]
Removed milestone since this didn't make the 9.9 cut.

**Comment by nheagy** [comment]
Sorry, I didn't notice that github didn't close this one. The fix PR was merged into 9.9 a week ago ✅
