### ISSUE TITLE
Stock Photos Design Review Notes

### ISSUE THREAD

**Issue by iamthomasbishop** [wordpress-mobile/WordPress-iOS#9186]
A couple minor things I found as I was going through the latest beta that includes Stock Photos (in addition to the things that have already been filed by others: https://github.com/wordpress-mobile/WordPress-iOS/issues?q=is%3Aopen+is%3Aissue+label%3A%22Stock+Photos%22) for Design Review:

* On the action sheet you see when tapping `+` on the top navigation bar, you see an option that says `Photo Library` which allows to choose media from your device. This can be confusing as it's right next to our feature `Free Photo Library`. This `Photo Library` label should instead read `Choose from My Device`. Example: https://cloudup.com/cspxJnomKvq

* The actions/links on the Free Photo Library action bar should be set in `wordPressBlue`. Example: https://cloudup.com/c0UGYGl2kzU

**Comment by etoledom** [comment]
Fixed in #9187
Thanks @iamthomasbishop !
