### ISSUE TITLE
Improve dynamic type in Stats sections

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/WordPress-iOS#9200]
### Expected behavior

`Stats` section adjust to text size changes.

### Actual behavior

The `Stats` section has a fixed text size, and it won't adjust to user text size changes.

### Steps to reproduce the behavior

- Open the Stats section in the WPiOS app.
- Change text size in the iOS settings to a big one. (Display & Brightness -> Text Size).
- Check the Stats section again.
- Text sizes in this section are the same even after reloading it or restarting the app.

**Comment by ScoutHarris** [comment]
Closing in favor of https://github.com/wordpress-mobile/WordPress-iOS/issues/10845.
