### ISSUE TITLE
Improve dynamic type in Notification Details

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/WordPress-iOS#9201]
### Expected behavior

`Notification Details` sections adjust to text size changes.

### Actual behavior

The `Notification Details` sections has a fixed text size, and it won't adjust to user text size changes.
The `detail` view depends on the type of notification, but many of them won't adjust to font size changes.

#### Notes

Implementing dynamic types in the notifications section introduced some bugs in iOS 10. The recommendation is to fix this after **iOS 10** is no longer supported.

### Steps to reproduce the behavior

- Open the Notification section in the WPiOS app.
- Open a notification that is shown natively (not a web view), and is not a reader. (i.e. Likes or Mentions)
- Change text size in the iOS settings to a big one. (Display & Brightness -> Text Size).
- Check that notification detail again.
- Text sizes in this section are the same even after reloading it or restarting the app.

**Comment by aerych** [comment]
This is still an issue. :)

**Comment by jkmassel** [comment]
This is resolved – notifications currently respect dynamic type settings
