### ISSUE TITLE
Toolbar cover textview input

### ISSUE THREAD

**Issue by CivelXu** [wordpress-mobile/WordPress-iOS#9208]
### Expected behavior

Editor page,Toolbar cover textview input

### Actual behavior

textview will not be covered 

### Steps to reproduce the behavior

When select Heading font type or List type;
the toolbar will change frame;

when we selected and continue to edit text;
the textview will be covered

![img_1257](https://user-images.githubusercontent.com/19768199/39296198-d9a76e42-4972-11e8-8d75-67c4bffe4d93.PNG)

##### Tested on [iPhone X], iOS [11], WPiOS [AppStore laster version]

**Comment by rachelmcr** [comment]
We had another report that looks like this issue, on Twitter: https://twitter.com/ljpuk/status/1068016163182034944

It's also compounded by this issue with the toolbar: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/1067
