### ISSUE TITLE
Hide Stock Photos option for non-Jetpack sites

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#9234]
### Expected behavior

The "Free Photo Library" option to add photos from the stock photos library shouldn't be shown to self-hosted non-Jetpack sites, as it relies on wpcom APIs.

### Actual behavior

The "Free Photo Library" option is shown both in the Media Library (under the + button) and in the editor (under + and then `...` in the formatting bar). If you attempt to use this for a non-Jetpack site, any searches you make return no results.

**Comment by etoledom** [comment]
Fixed in #9238
Thanks for reporting this! 🙂
