### ISSUE TITLE
Jetpack login prompt stays above Notifications after logging in

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#9235]
### Expected behavior

When I sign into Jetpack, I should no longer see the sign in prompt in the Notifications screen.

### Actual Behavior

I signed into Jetpack and the sign in prompt was still visible in the Notifications screen, but the notifications loaded in underneath it. When I scrolled, I was able to see the notifications underneath.

![simulator screen shot - iphone 8 - 2018-05-01 at 13 40 56](https://user-images.githubusercontent.com/4780/39473158-4e63adb0-4d45-11e8-8033-940f3ea47cfe.png)

### Steps to reproduce

* With a fresh install, add a self-hosted site that has Jetpack installed / connected
* Check that the Notifications section shows the sign in prompt
* Go to Stats for your site, and choose Log In
* Log in to your connected wpcom account
* After connecting, you should be able to view stats
* Switch back to Notifications, and you should still see the login prompt
* Scroll the notifications screen, and you should see notifications underneath

**Comment by nheagy** [comment]
I did some testing, and this one has existed since at least `9.6` 😬

**Comment by frosty** [comment]
Wow!
