### ISSUE TITLE
iOS: “Maximum allowed is Zero KB” errors

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#9237]
We’ve had some reports from iOS users, on version 9.8 of the mobile app, who are seeing an “Media filesize (XX KB) is too large to upload. Maximum allowed is Zero KB” error when they attempt to upload media to their site. Here’s a screenshot of what that looks like:

![zero-kb](https://user-images.githubusercontent.com/651601/39481890-ec22b144-4d64-11e8-9c56-5108df029537.png)

This error seems to pop up no matter the size of an image and seems to only be affecting some Jetpack and Atomic users

**Comment by nellofn** [comment]
Reported here as well: 278672-h

**Comment by lijingyu85** [comment]
Same here, the upload works on the web UI but only occurs at IOS client.

**Comment by tdkn** [comment]
Same issue here.
When I **DISABLE** Jetpack plugin, works fine 🤔

**Comment by diegoreymendez** [comment]
Removed milestone since this didn't make the 9.9 cut.

**Comment by SergioEstevao** [comment]
Diego if you see the PR above this was solved and merged on 9.9

**Comment by diegoreymendez** [comment]
The release manager can't assume the PR solves an open issue, because it may just be a partial fix.  Keep in mind that on top of dealing with inconsistencies such as these ones, we have to go through all of the issues in each release to write the release notes.

**Comment by SiobhyB** [comment]
This came up again in 278836-h and seems to be affecting a fair amount of users.

**Comment by nellofn** [comment]
Another one came in here 279753-h

**Comment by diegoreymendez** [comment]
@SiobhyB, @nellofn - If possible when reporting occurrences of issues, I think we should add some details here (such as the version of the app used, device, and any important highlights).

Mostly to encourage openness (since it's an open source project) but also to make the interaction easier for us.

**Comment by nellofn** [comment]
Here's another one 279897-h.

WPiOS: **9.8**
iPhone **7** 
iOS: **11.3.1**

No further details provided other than the same occurrence of the error.

**Comment by elibud** [comment]
@nellofn it looks like a fix was released on 9.9, can you ask the user to update the app and try again?
@SergioEstevao did you write the same fix for Android?

**Comment by nellofn** [comment]
@elibud Sure, I will contact the users, ask to update and report back to confirm.

**Comment by diegoreymendez** [comment]
Thanks, @nellofn!
