### ISSUE TITLE
Difficulty recognizing some urls with special characters during login

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9251]
I came across this issue recently when a user trying to connect to their self hosted site that had the character ä in it.  It seems that because of the umlaut the WordPress app was not able to recognize the url as valid.  

Normally when this has happened before there was an alternative URL that could be used to access the site, but in this case that didn't work either.  The site address was http://Ärtze-Tegel.de/  and the alternative address is http://xn--rzte-tegel-p5a.de/  

I poked about at this for a while and was unable to figure out what was stoping those addresses from being recognized in the app.

**Comment by nheagy** [comment]
I looked into this, and it seems our `IDN` support is probably broken. The root problem seems to be that `NSURL` still doesn't support `IDN` domains, causing the domain check to fail at `URL(string: resultURLString)` in `WordPressOrgXMLRPCValidator.swift`.

A quick fix would be to remove the call to `idnEncodedURL` in `WordPressAuthenticator`. Once we're not storying the encoded URLs, we'd have to be sure to encode them anytime they're displayed in the UI.

**Comment by nellofn** [comment]
Another user reported this issue as well on 280045-h.

Here's the provided address:

www.teekränzchen.de  (http://www.xn--teekrnzchen-p8a.de.)

Model: **iPhone 7**
WPiOS: **9.8**
iOS: **11.3.1**

**Comment by nellofn** [comment]
Adding another one that came up here 281685-h in case it could be useful for more testing:

http://Электрикворонежа.рф
http://xn--80adibfjnbfzkavey6o.xn--p1ai/

**Comment by charliescheer** [comment]
I found another one as well:
http://xn--yoga-ji9g301c.com/
http://yoga教室.com

**Comment by elibud** [comment]
@nheagy assigning over as discussed.

**Comment by elibud** [comment]
@nellofn @charliescheer @SiobhyB can we reach out the affected users and tell them to join the beta program (https://wordpress-ios-testflight.herokuapp.com) and try again? If they don't want to join the program the app update will be available in two weeks. We might have to email them since I don't expect they would've kept the app installed if they were not able to add their site to it.

**Comment by SiobhyB** [comment]
I've followed up with the ones I could from this thread and also the dupe issue I created at https://github.com/wordpress-mobile/WordPress-iOS/issues/9269. I haven't emailed but can do if the follow ups don't succeed.
