### ISSUE TITLE
Stats don't appear immediately after Jetpack login

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#9256]
Similar to #9235. After logging in to Jetpack from the Stats screen, the Jetpack login prompt doesn't go away. Ideally the screen would refresh and show some Stats 😀

**Comment by designsimply** [comment]
I ran across this issue while beta testing version 12.6. I was prompted to log in again after logging in, going to Stats, tapping Jetpack Install, then tapping "Approve". ([33s](https://cloudup.com/c274PuUrms3)) 

However, when I tried replicating the same issue a second time, I did not see the problem. ([36s](https://cloudup.com/c36gFP5EZLk))

**Comment by designsimply** [comment]
I tested this with 13.6.0.1 and can no longer reproduce. Closing.
