### ISSUE TITLE
Self-hosted address login glitch

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/WordPress-iOS#9270]
When I add my testing self-hosted site and continue, then I go back, add a second site url and continue, the next page keeps looking like I entered with the previous site.

There's an screenshot to explain it better.

![issue](https://user-images.githubusercontent.com/9772967/39626619-12df71ee-4f79-11e8-93da-89373dda8a43.png)

* This apparently happens when the first site is connected to JetPack and the second is not.

**Comment by joashrajin** [comment]
I can confirm that this issue no longer appears in JP 22.4 + WPM 22.4:

https://github.com/wordpress-mobile/WordPress-iOS/assets/16253818/28d003fe-9b84-4fd2-947f-81865fd7ccac
