### ISSUE TITLE
Automatically save drafts before preview

### ISSUE THREAD

**Issue by koke** [wordpress-mobile/WordPress-iOS#9286]
When a user is editing a draft, tapping on preview should save the post and then load the preview from the site, instead of showing a fake preview.

This might require adding a loading UI to show while the post is saving.

**Comment by yaelirub** [comment]
Hey @koke , just wanted to confirm that this is still a wanted/ needed behavior?

**Comment by yaelirub** [comment]
As @rachelmcr pointed out. This functionality seems to be lacking. Not working as expected so Im reopening.

The first issue is for new posts; is that outside the scope of your intended changes? When I create a new post and preview it, the draft isn’t autosaved:

Start a new post.
Enter a title and post content.
Preview the post.
Result: I see a local preview.
The second issue is for existing drafts. When I edit an existing draft, I get the remote preview but it doesn’t show my latest changes to the post. (I just see a remote preview of the draft as it was before I edited it.) That seems to be what the “after” GIF in your PR is showing, too.

Open an existing draft.
Make changes to the post.
Preview the post.
Result: I see a remote preview of the post before I made my changes.
Exit the preview.
Exit the editor.
Result: I get a prompt to update the draft or discard my changes. Discarding my changes loses all my changes from when I first opened the existing draft (step 1).

**Comment by yaelirub** [comment]
Update:
#10787 PR was merged with the intention of being included in 11.7 release. 
Bugs reveled in @rachelmcr's tests resulted in creating a fix #10915 . The fix provided caused more issues and after a long discussion we have decided to revert back to before #10787 .
revert commit - https://github.com/wordpress-mobile/WordPress-iOS/commit/847a4db771c1b0da06af5ecad9ee8a00a36a5bbb

This issue remains open and will have a following PR .
