### ISSUE TITLE
Aztec: inserting multiple documents with doc picker results in an awkward layout with no spaces between links

### ISSUE THREAD

**Issue by designsimply** [wordpress-mobile/WordPress-iOS#9293]
### Expected behavior

After inserting multiple documents at once, I expected links to documents to be on separate lines or have spaces between each one.

### Actual behavior

Links to documents are in one line with no spaces if you insert multiple documents at a time.

### Steps to reproduce the behavior

1. Go to My Sites > Blog Posts > +.
1. Go to "Add Media" > {ellipsis menu} > Other Apps in the editor toolbar.
1. Select Locations > iCloud Drive and tap "Select."
1. Select multiple documents and then tap "Open."
1. Check to see if the formatting of the links that were inserted appear as expected.

Result: the links have no spaces or line breaks between them.

<img src="https://user-images.githubusercontent.com/1119271/39730950-ca8eede2-5221-11e8-9d31-34e989b098c5.PNG" width="270">

**Comment by a8c-sab-trial** [comment]
@designsimply : thanks for raising this! I agree that there is room for improvement.

@frosty / @SergioEstevao : I'm happy to tidy this up. 

*All three* : it seems like the leading contenders for a delimiter in this case are either a space (perhaps via `&nbsp`) or line separator (`<br />`). Do you have a preference for one of these, or perhaps something else entirely?

Personally I think the line break is most appropriate, but I'm happy to defer to the group. In either case, once we reach consensus, I can address this right away.

**Comment by frosty** [comment]
Personally I'd go for line break too – I feel like on separate lines is how I'd be more likely to want these to display, and it makes it easier to distinguish between the links.

**Comment by SergioEstevao** [comment]
I agree that we should improve this, but just want to say that Calypso does exactly the same. We should also open a ticket in Calypso.

**Comment by a8c-sab-trial** [comment]
Thanks for calling this out @SergioEstevao. To confirm, are you referring to the Calypso processing initiated [here](https://github.com/wordpress-mobile/WordPress-iOS/blob/9457e6fd2b7e5c224e4139de0a683ace92a34474/WordPress/Classes/ViewRelated/Aztec/ViewControllers/AztecPostViewController.swift#L58)?

**Comment by a8c-sab-trial** [comment]
I have submitted this [draft PR](https://github.com/wordpress-mobile/WordPress-iOS/pull/9307) for consideration.

**Comment by SergioEstevao** [comment]
No, I'm just saying that if you use WordPress.com on the web ( Calypso
editor) the end result of inserting three documents it's a big line with
all links one after the other...
