### ISSUE TITLE
Notifications: Event avatars are mixed up sometimes

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#9296]
### Expected behavior

Every event has its own related avatar

### Actual behavior

Sometimes, avatar from the latest event replaces avatar of some previous events

### Steps to reproduce the behavior

1. Receive some notifications
2. Open Notifications tab to review them

##### Tested on iPhone SE, iOS 11.3, WPiOS 10.0.20180507

<img width="650" alt="img_23b2e3c8d959-1" src="https://user-images.githubusercontent.com/5654161/39754607-68697560-52cb-11e8-86be-715d6dc8c50c.png">

**Comment by alisterscott** [comment]
I noticed this on the App Store version 9.9:

![notifications_-_1](https://user-images.githubusercontent.com/128826/40030257-e7a8092a-582c-11e8-8967-07bcced4eacc.png)
