### ISSUE TITLE
Media Upload: App crash when dismissing unsupported file modal

### ISSUE THREAD

**Issue by brbrr** [wordpress-mobile/WordPress-iOS#9298]
### Expected behavior

No crash

### Actual behavior

App crashes when dismissing modal of unsupported file

### Steps to reproduce the behavior

1. Open post editor
1. Navigate to  `+` (Add Content) : `...` (Other apps)
1. Add any unsupported file format (e.g. `.zip` file)
1. Tap on file thumbnail, dismiss it.
1. Tap on file thumbnail, dismiss it once again
1. App will crash

##### Tested on iPhone SE, iOS 11.3, WPiOS 10.0.20180507

![screenrecording_05-08-2018 15-03-44](https://user-images.githubusercontent.com/5654161/39757068-5b980bb8-52d4-11e8-9ad8-53230460e47e.gif)

**Comment by etoledom** [comment]
Thanks for reporting this @brbrr 

I think this crash is the same than this one: #8995
It also happens with supported media file (as a normal image).

The key is to present and dismissing an action sheet two times when the media picker is present.

**Comment by frosty** [comment]
@etoledom I think you're correct, particularly based on the GIF here it shows that exact behaviour. Let's close this one in favor of the original issue, so we're just tracking in one place.

Thanks for the report, @brbrr!
