### ISSUE TITLE
Loading Post animation runs only once

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#9304]
### Expected behavior
Reported by @m: When we are loading a post the animation should loop until the post is displayed.

### Actual behavior
The animation runs only once.

### Steps to reproduce the behavior
1. Simulate limited connectivity.
2. Go to notifications.
3. Select a post notification.
3. 
![loadingpost](https://user-images.githubusercontent.com/5558824/39763513-4ec25cc8-52ab-11e8-8f22-b09bdf120310.gif)

**Comment by ScoutHarris** [comment]
@elibud - next week I'm going to start https://github.com/wordpress-mobile/WordPress-iOS/issues/9504. I'll address it with that project.

**Comment by elibud** [comment]
Great, thank you @ScoutHarris
