### ISSUE TITLE
Multiple offline alerts

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#9305]
### Expected behavior
I should only see an `Unable to Sync` alert if I manually trigger a reload while offline.

### Actual behavior
On the notifications screen, if I navigate to a notification detail and back while offline  I get one alert each time I go back to the list.

### Steps to reproduce the behavior
1. Load notifications.
2. Turn on Airplane mode.
3. Navigate to one notification detail.
4. Navigate back to the list and see the alert.

**Comment by loremattei** [comment]
Hey Cesar! Just a heads up that 10.1 has been just frozen. Please, be sure to target the _release_ branch if you want this one to be shipped with that version!

**Comment by ctarda** [comment]
Fixed in PR #9461
