### ISSUE TITLE
One gif image could load and animate in two different cells at the same time

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/WordPress-iOS#9309]
In the Reader posts list, and under very specific circumstances, a gif image could start loading on more than one cell at the same time.

### Expected behavior

To see the correct image in the corresponding cell.

### Actual behavior

Sometimes a gif is shown animating in two cells at the same time:

[Video here](https://cloudup.com/cPbFvpInVy2)

### Steps to reproduce the behavior

This is very tricky:

1. The duplicated gif has to take some noticeable amount of time to download (non-cached).
2. When the cell of that gif appears, it has to be in an index path that triggers the load of the next posts page. 
3. The next cell has to have a static image and it needs to be loaded from cache. (or to load faster than the gif)
4. The gif has to appear faster than the next page.
5. When the next page finishes loading, it triggers a table refresh
6. **Sometimes** UIKit flips the cells it uses to show the same indexPath, so if that happens, the previous gif cell is now the next image cell, and the image cell is now the gif cell
- And one important detail: The table **has** to be scrolling when the next page reload happens.

In the video it is possible to see from the second 10:
- The gif appears.
- Start scrolling down.
- Next page appears (Scroll indicators grow).
- The static gif means that it is loading from cache (probably in both cells).
- When that loading from cache finishes, it start animating in both cells.

I think that the key is to scroll at the right moment, between the gif finish loading (it appears) and the next page load.

cc @bummytime

**Comment by bummytime** [comment]
Nice sleuthing @etoledom 🕵️ 🕵️‍♀️  !

**Comment by rachelmcr** [comment]
I encountered this today in the Reader in this scenario (slightly different from the one above):

* A gif appears as the featured image in the top post in the feed.
* I pull to refresh the feed.
* A new post loads at the top of the feed with the same gif.

(Seen on iPhone XS, iOS 13.3.1, WPiOS 14.2.0.20200218)

**Comment by rezzap** [comment]
I experience this issue quite regularly under the same circumstances @rachelmcr mentions above. It happens every time the top post in my reader feed has a gif and I pull down to refresh. 

iPhone X, iOS 13.3.1, WPiOS 14.3 (though it's been happening for quite some time and through updates)

Since it was such a good screenshot, I'll add it! 
<img width="392" alt="Image 2020-03-21 at 8 53 44 pm" src="https://user-images.githubusercontent.com/10325627/77236456-8d79a180-6bb6-11ea-9948-82d77fde0a37.png">

**Comment by leandroalonso** [comment]
Given how old the issue is and the fact we haven't heard complaints about it I'm closing it for now.
