### ISSUE TITLE
Async Posting: When offline, queue posts to upload later

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#9319]
When publishing posts while offline, we currently attempt to upload them but they instantly fail and become 'upload failed' drafts:

<img src="https://user-images.githubusercontent.com/1119271/39736515-88829d1a-523d-11e8-9307-7e6214765fd9.PNG" width="270">

As a future enhancement, we could make the following changes to this behaviour:

* Don't attempt an upload if we know we have no connectivity
* Queue uploads for later when we have no connections
* Only attempt the upload when a connection returns

**Comment by rajatjindal** [comment]
Hi @frosty

I am running into similar issue

When i wrote some drafts when i was flying , i thought they will sync up automatically once i am online

But they are now stuck forever as failed upload, even if i have connectivity it does not work

Is there a compatibility matrix with wordpress version this app support? I think i am running the latest version

**Comment by SiobhyB** [comment]
We also received a request for improved offline editing in 1436691-z:

> Your app is nice and could be "nearly" perfect. But it is not. The problem with your app is that you can't save a post locally and upload it when one has a stable (WiFi) connection. The result: I stopped posting.

**Comment by kean** [comment]
The sync implementation was reworked in the scope of pcdRpT-6vS-p2: 
- Drafts sync automatically 
- If offline, the list displays an "offline changes" indicator and retries instantly when the connection is established
- If there is a data conflict, it kicks off a new conflict resolution dialog
