### ISSUE TITLE
Access to help when app is offline

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9347]
Hey y'all,
I was working on a plane the other day and I ended up going into the WordPress app while in airplane mode and I noticed something that seemed a little odd to me.  The alert message that appears when the app is offline still offers a way to get to support and create a new issue.  
<img src='http://cld.wthms.co/8fh0Zq+'>

I find that a little odd because if you're offline you can submit an issue to helpshift anyways, and if the problem the user is having is that they aren't connected to the internet, should we be offering access to help?  Should we remove the need help button on this alert?

To replicate:
1. Go into airplane mode
2. Go to a page that needs to ping a server, like notifications
3. alert appears.

Thanks!!

**Comment by elibud** [comment]
Hey @ScoutHarris can you look into this please? Thx
