### ISSUE TITLE
Feature Request: Ability to select multiple posts at once

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9348]
I create a lot of posts especially while testing the apps.  This ends up creating a situation where every so often I need to go in and delete a bunch of posts at once.  In the app currently to delete posts you have to do it individually and hit confirm on the alert that appears, so it is a very slow process to remove multiple posts at once.

It would be great if there was a way to select and delete multiple posts at once similar to the way the messages app does if you click on edit.  It's possible to select and then delete multiple messages at once.

**Comment by designsimply** [comment]
A bulk delete option in the app sounds like a reasonable request to me because a lot of apps have something like this in general. Let's leave this open for now, and it would be good to get another opinion as well.

**Comment by dangermattic** [comment]
Thanks for reporting! 👍

**Comment by kean** [comment]
We're not planning to add multi-select for posts as they require you to be more intentional than other types of content.
