### ISSUE TITLE
Unify Image loading indicator styles.

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/WordPress-iOS#9357]
### Expected behavior

The image loading indicator style should be the same everywhere in the app.

Something similar to the one in the Media Picker:

![img_2649](https://user-images.githubusercontent.com/9772967/39998531-5e5e80dc-5754-11e8-9022-333dfb361385.png)

### Actual behavior

There are different loading styles in different parts of the app:

![loading](https://user-images.githubusercontent.com/9772967/39998545-667a1f06-5754-11e8-883f-d30e03b4ad10.png)

**Comment by etoledom** [comment]
@iamthomasbishop - Could you please give us the design to use for the loading indicator when there is a white background?

Thank you!

**Comment by iamthomasbishop** [comment]
@etoledom Looking at the original designs that @folletto did for async, I believe there is a semi-transparent backdrop - perhaps `darkGrey` at 80% opacity (I'm not 100% sure if that matches what was implemented in the end, but the mock you placed above looks like it has slightly less opacity - 40%? Let's match that for now for consistency.

**Comment by folletto** [comment]
Please also note that the one in the screenshot is a _determinate_ loader: it shows progress of the upload.

The others are iOS platform standard _indeterminate_ loaders, so they behave a bit differently. There's however an indeterminate state in the same code right before it determines the upload progress length, you should be able to pick that, even if it probably needs some tweaking (i.e. a bit slower in all the UIs, but if it's being abstracted as a component so we can reuse the same code we can tweak later).

---

As a broader note the plan I had in mind was somehow the reverse. When I updated the Calypso one (see https://github.com/Automattic/wp-calypso/pull/22603#issuecomment-367071287) I made it in a way that was compatible with the _determinate_ loader above: as you can see the "partial ring" structure is the same, it just adds an inner one.

So, ideally:

1. On white, it should be identical to the Calypso one
2. When it converts to a determinate loader, it loses the inner ring (or... maybe not now that I think of it? might be interesting to see how it looks if we keep it while the outer rings fills up) and gains the darker ring track
3. On dark, it converts to a "white" version like the above.

**Comment by etoledom** [comment]
@folletto - I find using the same loader design than Calypso great! But tweaking the design at that level or creating a new one is out of scope of the `Gif support` project. The name of this issue might not have been the best, sorry for that!

Is it possible (for now) to use the same loader than is used in the media cells (in the `indeterminate` state), just tweaking the colors? Something like @iamthomasbishop mentioned.

This is how it looks using it with the colors as they are now:
- The background is `darkGrey` opaque.
- In the media cell, when there is an image underneath, the opacity changes to 50%

![loader](https://user-images.githubusercontent.com/9772967/40176200-8e40883a-59a8-11e8-9925-853a2f138292.gif)

**Comment by folletto** [comment]
> I find using the same loader design than Calypso great! But tweaking the design at that level or creating a new one is out of scope of the Gif support project. The name of this issue might not have been the best, sorry for that!

Sure, I wasn't sure on the degree of complexity – I rely on your judgement for that. :D 
I thought it was just helpful to mention it, as I think it wasn't something I wrote down anywhere before.

> Is it possible (for now) to use the same loader than is used in the media cells (in the indeterminate state), just tweaking the colors?

Yes absolutely, that's what I meant with "you should be able to pick that", sorry if it wasn't clear enough!

As for the colors, I'll refine then what Thomas hinted above:

* Color: `$blue-medium` (matching Calypso)
* Background go full transparent (because it's on a full color background, and it's white).

![screen shot 2018-05-17 at 13 17 03](https://user-images.githubusercontent.com/4389/40176835-9dfaa662-59d4-11e8-916b-31149e12c8bf.png)

Would be difficult to slow down a bit the animation of that indeterminate spinner?

**Comment by etoledom** [comment]
> Would be difficult to slow down a bit the animation of that indeterminate spinner?

No problem! It will be quite easy to tweak 🎉

This would be with the mentioned colors and the speed slowed down in a factor of 0.7:

![loader_5](https://user-images.githubusercontent.com/9772967/40178487-985ddae6-59af-11e8-978c-83e5d020a87f.gif)

**And one more question:**

When I open an image from the Media Library, and expand the image to full screen, it shows a black screen with a big system loading indicator:

![img_2751](https://user-images.githubusercontent.com/9772967/40178978-05e16adc-59b1-11e8-979e-1d08cde30af8.PNG)

Should we:
- Use this new loader on white?
- Change the background to white and the loader `$blue-medium` (as the rest)?
- Keep it as it is?
- Try any other option? 😆

Thank you @folletto !

**Comment by folletto** [comment]
> speed slowed down with a factor of 0.7 (1 being the previous "default" speed):

As far as gifs go, that seems a better speed to me 👍 

> Use this new loader on white?

In general, I'd try to standardize the loader used. Ideally should also be a single "call", so when we update the spinner, it gets updated everywhere.

But:

>  Change the background to white and the loader $blue-medium (as the rest)?

No, as the full screen view is meant to be "black" as "off", so the image is seen fully and crisply without other colors and luminosity to interfere.

So if we use the spinner above here, should be the version "on dark", so to mean, white-filled. :)
