### ISSUE TITLE
Geo location is not displayed in post settings

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9372]
I was working on an issue the other day where a user was having trouble with the geolocation in the app for posts.  They had reported that they were setting the geo location for their post and updating the post, then once they returned to the settings for the post the location data would be lost.

I poked about this for a little bit and I was able to replicate the problem, it seems that the geo location is still set correctly for the post when visited it in a web browser, and the app still knows that there is a location set for the post, but it displays at coords 0,0 instead of the correct location.

When the location was first set:
<img src='http://cld.wthms.co/GTG84Z+' >

After leaving the settings, updating and returning to the settings:
<img src='http://cld.wthms.co/GJmKFv+' >

To reproduce:
1. Edit or start a new post and go into the post settings.
2. Add a location to the post.
3. Exit the settings, update the draft or post
4. return to the post settings and the location will not show correctly.

iOS 11.3
WordPress 10
iPhone 6s

**Comment by SergioEstevao** [comment]
@charliescheer can you add me to the test site where you saw this happening? I just tested with a WP.com, Atomic site, and self-hosted and couldn't reproduce in any of them.

**Comment by charliescheer** [comment]
I tried this problem on my wpcom (non AT site) and on one of my .org pressable sites and had the same experience.  I have gone ahead and added you to the .com site, you should see that invitation soon.

For clarity (and to make sure I'm not losing my mind) I created a video of what I am seeing.  That can be found here http://cld.wthms.co/Fr6JYl

**Comment by SergioEstevao** [comment]
@charliescheer I found the reason of our different test results, believe it or not it's related to the language setting on the device. 

So if the language set on the device uses by default a decimal separator that is not a `.` the parsing will fail and show a zero.

Will do a PR soon to fix this.

**Comment by charliescheer** [comment]
HA!  That always seems to be the way when something strange like this goes down, that being in not english causes the problem

**Comment by ymichel** [comment]
Hi folks, 
As I raised this ticket, I‘m wonderering when the fix will be available as a rolled out WP-app.
Can you drop be a few lines?
THX.
Yann

**Comment by SergioEstevao** [comment]
Hi @ymichel , it's fixed at it will be merged in on release 10.2, thanks again for the report.

**Comment by jklausa** [comment]
@ymichel 10.2 should be out in few weeks — around June 18th.

**Comment by ymichel** [comment]
Any need for Beta testing?
