### ISSUE TITLE
Photos are wrongly resized

### ISSUE THREAD

**Issue by gryden1976** [wordpress-mobile/WordPress-iOS#9375]
When uploading a photo I want it to be uploaded in full size, the setting in the app is set to "Full size".

It seems that photos in landscape orientation are resized to a smaller size. Photos in portrait orientation upload in full size as they should.

Tested on iPhone X, iOS 11.3.1, WPiOS 9.9

**Comment by elibud** [comment]
@frosty can you please look into this? Thank you

**Comment by frosty** [comment]
@gryden1976 Hi! Thanks for the bug report. I've tested uploading landscape images to a range of sites, and I'm unable to recreate the issue. Can I ask what sort of site you're uploading to? Is it self hosted (with or without Jetpack), or WordPress.com? Are you simply uploading images from your device's media library?

Would you be able to tell me what resolution your photos are being uploaded at?

**Comment by gryden1976** [comment]
This is embarrassing, but I think I've made a mistake in reporting this as a bug. 

When you ask if I used Jetpack (I don't), self hosted (yes) and so on, I had a look at my plugins and updated those. That made the problem go away.

I'm so sorry for causing unnecessary work. The problem was me, I'm the bug.

**Comment by frosty** [comment]
Haha, that's okay! I'm glad you got it resolved! 👍
