### ISSUE TITLE
Free Plan shows wrong Space description 

### ISSUE THREAD

**Issue by nellofn** [wordpress-mobile/WordPress-iOS#9377]
A user contacted us (280872-h) asking as to whether or not they could add music files to their site under a Free plan, given that the Plans description screen on both Android (9.9) and iOS (9.9) displays a wrong “Space” description. Likewise, it says video files can be uploaded which isn't accurate either.

![img_ac9d95521042-1](https://user-images.githubusercontent.com/17755234/40118240-5d7f4b80-58e7-11e8-95a6-03df05286e9e.jpeg)

The plan description on the Pricing page says:

**> Ample storage space to upload images and documents to your website.**

##### 
Tested on iPhone 7 Plus, iOS 11.3, WPiOS 9.9

**Comment by ScoutHarris** [comment]
This is coming from the `/plans/features/` endpoint. @aerych , @elibud any thoughts on who to ping to get that information updated?

**Comment by planarvoid** [comment]
The list with the issues is on this ticket #6074. We should fix the data coming from the endpoint @ScoutHarris

**Comment by aerych** [comment]
Closing now that we're using the new end point
