### ISSUE TITLE
Feature request: Add support for following posts in the app

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#9378]
Requested by @kathrynwp

**Comment by kathrynwp** [comment]
Thanks for logging the request! As I said on the Android issue, it would be great to be able to **follow by email** from the app in addition to any "follow conversation in reader" option - that would make it a seamless experience.

**Comment by elibud** [comment]
Definitely not Stale, we just never been able to prioritize this one. Adding the "Needs Design" label.

**Comment by designsimply** [comment]
This came up again in some internal feedback.

> This is looking great. There’s one feature I’ve been wanting on Reader for a long time which is the ability to follow a post comments from Reader (both the card and the full post view), wdyt?

<sup>(internal reference: pbArwn-gP-p2#comment-422 h/t @elibud cc @mbshakti )</sup>

**Comment by iamthomasbishop** [comment]
From the users’ perspective, I think the simplest option would be to just add a button to the navigation bar on the Comments view. This could be a text label which would change between “Follow” and “Following” depending on the current state. Alternatively, we could use an icon, but I think a text label would be clearer. 

Obviously there is likely some additional logic that would need to be considered during implementation, but from the user’s perspective I would expect that trigger to be placed in the navigation bar. Like this:

![image](https://user-images.githubusercontent.com/1200432/81955912-4c0edc80-95d0-11ea-8b7c-5d9b7a82497c.jpeg)

**Comment by elibud** [comment]
@aerych this one is done, right?

**Comment by aerych** [comment]
It is indeed.
