### ISSUE TITLE
Zendesk Mobile: add tracks

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#9394]
1. Replicate tracks used by Helpshift.
2. Add more if needed.

**Existing tracks, to be reused in ZD:**
"support_received_response_from_support"
"support_opened"

**Existing tracks, not to be used in ZD:**
"support_opened_helpshift_screen" (replace with 3 "support_*_viewed" listed below)
"support_user_accepted_the_solution" (action not available in ZD)
"support_user_rejected_the_solution" (action not available in ZD)
"support_user_reviewed_the_app" (action not available in ZD)
"support_user_sent_screenshot" (replace with "support_user_attached_file")
"support_user_replied_to_helpshift" (replace with "support_user_replied_to_ticket")

**New tracks:**
"support_help_center_viewed" (replaces "support_opened_helpshift_screen")
"support_new_request_viewed" (replaces "support_opened_helpshift_screen")
"support_ticket_list_viewed" (replaces "support_opened_helpshift_screen")
"support_new_request_created"
"support_new_request_failed"
"support_new_request_file_attached" (replaces "support_user_sent_screenshot")
"support_new_request_file_attachment_failed"
"support_ticket_user_replied" (replaces "support_user_replied_to_helpshift")
"support_ticket_user_reply_failed"
"support_ticket_list_view_failed"
"support_ticket_user_viewed"
"support_ticket_view_failed"
"support_help_center_user_searched"

**Comment by elibud** [comment]
LGTM, so excited to have this so close to completion!

**Comment by oguzkocer** [comment]
Looks good!

**Comment by aerych** [comment]
Looks good but I think we should tweak to match tracks naming conventions.  I'll send you a link.

**Comment by ScoutHarris** [comment]
@aerych - how's this?

"support_help_center_viewed"
"support_new_request_viewed"
"support_ticket_list_viewed"
"support_new_request_user_attached_file"
"support_new_request_file_attachment_failed"
"support_ticket_user_replied"
"support_ticket_user_reply_failed"
"support_ticket_list_view_failed"
"support_ticket_user_viewed"
"support_ticket_view_failed"
"support_ticket_attachment_user_deleted"
"support_ticket_attachment_user_delete_failed"
"support_help_center_user_searched"

**Comment by aerych** [comment]
We chatted about "support_new_request_user_attached_file" to  "support_new_request_attached_attached". 
After that good to go :)

**Comment by ScoutHarris** [comment]
Thanks! Final list added to description.

**Comment by ScoutHarris** [comment]
Removed these since ZD is not sending the notifications for them correctly:
"support_ticket_attachment_user_deleted"
"support_ticket_attachment_user_delete_failed"

**Comment by oguzkocer** [comment]
@ScoutHarris @aerych I was just checking the support events on the iOS code and found that the Helpshift specific events were still there: https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Utility/Analytics/WPAnalyticsTrackerAutomatticTracks.m#L1302

Is there a reason we still keep them in the code?

**Comment by ScoutHarris** [comment]
@oguzkocer I have outstanding PRs to remove those.
