### ISSUE TITLE
Notification Settings from WordPress Email page do not update until that page is closed in the app

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9432]
Hey y'all,  I was testing WPiOS 10.1 and I stumbled across this behavior, I'm not sure if it is intentional or not, but I wanted to write it up just incase.

If you go to Me > Notification Settings and and start making changes to your settings they reflect in your WordPress.com account notification settings right away.  However if you go to Me > Notification Settings > WordPress Emails and make changes to those settings they do not update until you leave the WordPress email page in the app.  Is this on purpose?  

To replicate this behavior:
1. Go to Me > Notification Settings > WordPress email in WPiOS
2. Open https://wordpress.com/me/notifications/updates and make sure the settings in the app and in the browser match.
3. Make a change to your settings in the app, but do not navigate away from that page in the app
4. Reload your web browser to see if the setting has changed (it shouldn't have)
5. Navigate away from the WordPress Email settings page in the app and reload your browser again.  The setting should be up to date now.

When I tried this same behavior on other settings pages I the settings would change in the browser as soon as you made in the change in the app, no needed to change pages in the app.  

WordPress 10.1
iOS 11.3
iPhone 6s

**Comment by frosty** [comment]
@charliescheer I just looked into this, and I think it's intentional – each of those settings are all configured by the same endpoint, so in waiting for the user to navigate away from the screen it can be done in a single call. I guess this also prevents the chance of multiple requests conflicting with one another. I'll close this for now.
