### ISSUE TITLE
setup default url

### ISSUE THREAD

**Issue by copyyour** [wordpress-mobile/WordPress-iOS#9438]
Hello everyone, I want to compile my WordPress website directly to app, and open is my default WordPress, and do not need users to enter the web site, do not know to modify those places? Thank you

**Comment by designsimply** [comment]
I believe you are asking for help using your self-hosted WordPress site on the existing WordPress for iOS app:

> To access a site that is self-hosted, from the Log in section, when you first open the app, click on the link that says “Log into your site by entering your site address instead.” From that option enter your site address, and then your username and password for your site.

If you are asking how to turn your WordPress site into an app directly, that is outside the scope of this forum and you may want to start with a Google search for "[compile WordPress website to app](https://www.google.com/search?q=compile+wordpress+website+to+app)" which appears to have several related plugin results that may help you.
