### ISSUE TITLE
Broken Localizations

### ISSUE THREAD

**Issue by jleandroperez** [wordpress-mobile/WordPress-iOS#9441]
### Details:
Our LocalizedStrings Exporter is breaking [here:](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/ViewRelated/Notifications/Controllers/NotificationSiteSubscriptionViewController.swift?utf8=✓#L38)

```
Firenze-Pro:WordPress-iOS lantean$ python Scripts/localize.py 
Bad entry in file ./Classes/ViewRelated/Notifications/Controllers/NotificationSiteSubscriptionViewController.swift (line = 39): Argument is not a literal string.
```

Breaking change is:

```
NSLocalizedString(title, comment: "The title will be displayed by the row cell")
```

cc @danielebogo

**Comment by elibud** [comment]
Note: this should be fixed on `release/10.1`
