### ISSUE TITLE
Reader Save for Later: Save button sometimes disappears

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#9454]
Originally reported by @etoledom in https://github.com/wordpress-mobile/WordPress-iOS/pull/9408.

Sometimes when scrolling through a stream in the Reader, the new Save Post button sometimes just disappears when the cell is reused:

![](https://user-images.githubusercontent.com/9772967/40487334-db70d978-5f31-11e8-8093-df2a914c22bf.gif)

Probably related, in some situations the button also disappears after tapping on it:

![](https://user-images.githubusercontent.com/9772967/40487338-de14342c-5f31-11e8-94d9-a73fa1d2fb09.gif)

I think this is probably the same underlying case, as the cell is reloaded when the button is selected.

**Comment by echbee** [comment]
@ctarda Sorry I wasn't aware that you self-assigned this issue when I started to investigate it.

**Comment by ctarda** [comment]
@echbee No worries! Thanks for taking care of it! I am going to re-assign it to you
