### ISSUE TITLE
Gutenberg posts not displaying properly on reader and notification details

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#9470]
### Expected behavior
Gutenberg posts should display properly on Reader and Notification details.

### Actual behavior
Every line break seems to be (at least) doubled.

### Steps to reproduce the behavior
Follow any blog that composes posts in Gutenberg, then go to Reader->Post detail or Notification->Detail
 
![image uploaded from ios 4](https://user-images.githubusercontent.com/5558824/40555182-a2eb3d3a-601e-11e8-92d7-8225aa5a6a0e.png)

**Comment by elibud** [comment]
@aerych related to what you were mentioning about changing Reader to use a `UITableView` to display posts?

**Comment by aerych** [comment]
Probably not.  I haven't looked to see what its doing but my expectation is there is a bunch of new mark-up in Gutenberg posts that needs to be parsed and filtered out.

**Comment by elibud** [comment]
@aerych I would like to fix this one before we freeze 10.2, I pushed a fix on this branch: https://github.com/wordpress-mobile/WordPress-iOS/tree/try/fix-gutenberg-posts-on-reader but it might not be the way to do it given the rest of the processing that happens on `WPRichTextFormatter`. Would you mind taking a look and suggesting an approach if that one is not appropriate?
Thanks

**Comment by elibud** [comment]
yeah I figured there was a smarter way to go about it, thanks for taking over 😃
