### ISSUE TITLE
Extreme Notification Spam

### ISSUE THREAD

**Issue by tomjn** [wordpress-mobile/WordPress-iOS#9473]
I'm getting the same notification over and over and over and over again

### Expected behavior

A post went up on a social site I have, so I got a notification for a 4 day streak

### Actual behavior

i got the notification, then again, then again, repeatedly:

![img_2125](https://user-images.githubusercontent.com/58855/40586974-3dea447c-61c1-11e8-9bb1-6cac7effea94.PNG)

### Steps to reproduce the behavior

Trigger a post streak notification

##### Tested on [device], iOS [version], WPiOS [version]

iPhone X, latest iOS, latest app version acordding to testflight

---- 

As an aside, creating this issue was very difficult, there's no way to create bugs or file them from the app ( there used to be ), I'm on conference wifi, and ended up on the main WP github, I could really have done with a report bug button in the app to take me to the right location. I had to tether my macbook and load up a full browser

**Comment by elibud** [comment]
@charliescheer I haven't seen any other report for this one, if you can't reproduce let's close it.

**Comment by tomjn** [comment]
I haven't noticed this happening recently, I'll close it out

**Comment by charliescheer** [comment]
@elibud funny this comes up actually.  Recently I have seen 1 report of a similar issue to this.  We'd been trying to hunt down what was causing the repetitive notifications and hadn't been able to replicate the issue.  I will see if I can find it.

However, I have only ever seen 1 report of this problem, so it may be best to just leave it as is.  If I can find the issue I'll link it here

**Comment by charliescheer** [comment]
Here is the recent report of this that I saw.  2061302-zen

There isn't too much info there. I have asked for more info from the user, but haven't heard back.  I still think we can leave this closed for now as there are very few reports

**Comment by michaeldcain** [comment]
I've been getting double notifications on all comments, likes, and posts for most of the day. This is in the latest iOS production app with iOS 12.3.1.

Let me know if I can provide any additional information.

![IMG_0459](https://user-images.githubusercontent.com/942359/59127498-cdc4a780-8935-11e9-8f8e-7a66a333c12a.png)

Reported here: p1559931305000700-slack-mobile-support

**Comment by designsimply** [comment]
@michaeldcain in your case the push notification duplicates come in pairs and not over and over and over right? Do you have two separate versions of the app installed (one production and one development) by chance, and if so, could notifications be enabled for both?

Aside: your case might also be possibly (deceptively?) related to https://github.com/wordpress-mobile/WordPress-iOS/issues/11847.
