### ISSUE TITLE
Some icons deeds to be flipped on RTL layout.

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/WordPress-iOS#9478]
Some icons that should be flipped in RTL layout.

![artboard](https://user-images.githubusercontent.com/9772967/40616159-f4a7b956-6257-11e8-8b9d-5c728937c479.png)
![artboard 2](https://user-images.githubusercontent.com/9772967/40616218-3ac3f99a-6258-11e8-800f-20ace2f5e6f6.png)
![artboard 3](https://user-images.githubusercontent.com/9772967/40616182-0ef780de-6258-11e8-9608-976262383a43.png)
![artboard 4](https://user-images.githubusercontent.com/9772967/40616456-1ade5ac0-6259-11e8-910d-2b514964fb36.png)

**Comment by etoledom** [comment]
Hey @iamthomasbishop:
While working on this issue, I ran into a problem with one of the assets:

![img_2959](https://user-images.githubusercontent.com/9772967/40989006-2c858726-68b2-11e8-8deb-18cc8df1e4b4.png)

Sadly, we can not simply flip that icon, since the numbers get written backwards. I checked some Apple apps and they just keep the numbers written in the right direction (I was worried about the numeric system)

![img_2960](https://user-images.githubusercontent.com/9772967/40989401-45f6903c-68b3-11e8-959b-8738df12d933.png)

Could you please give me a hand with this? :)
Ideally would be to have the specific icon for RTL layout with the numbers in the right direction.

Thank you!

**Comment by iamthomasbishop** [comment]
Great catch - I will create a new gridicons icon for this!
