### ISSUE TITLE
Make pingback notifications easier to moderate

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#9479]
When a comment arrives for moderation, all the info you need to take action is right there on the screen. However when a pingback arrives you need to visit the site before deciding what to do. Currently this is possible but quite obscure. @mattmiklic can we design a more appropriate interface for it?

cc: @kwonye this one seems like a good candidate for the upcoming notification improvements.

Reported by @m

**Comment by folletto** [comment]
Here's a i1 design exploration:

![blueprint-pingback-i1](https://user-images.githubusercontent.com/4389/40782392-06a6f3fc-64d7-11e8-8ffb-10d364d6f43f.png)

Note that I went for a "minimal" approach here, as changing more than this will start cascading down (notifications are based on old standards, if we use new ones sizes, spacings, and some patterns are off and should be fixed too).

So, I tried to strike a balance here and reuse the most, while still clarifying the "Open" action.

**Comment by mattmiklic** [comment]
I think this looks sharp, @folletto, agreed about the desire for a minimal approach to fix the problem at hand without introducing more work. 

It seems like the new Material Design standards for buttons would allow us to include the external icon for Android too, but I don't think it's 100% necessary, so I'd be fine with shipping this as-is. Just wanted to mention it in case the icon would help on Android.

**Comment by koke** [comment]
I took a quick look at this one, and either I missed something or there's nothing in the note contents to differentiate a pingback from a regular comment, so we'll need some tweaks to the backend 😟

**Comment by planarvoid** [comment]
afaik the only thing we can use is the `metadata url`. It's however possible it is used in other notification/comment types.

**Comment by jleandroperez** [comment]
@koke @elibud i'm not happy nor proud about this, but turns out, there effectively is a way to detect a Pingback Notification.

Pingback Notifications (appear) to have a specific "Subject Ranges" signature: `[site, post]`.
I'm pasting below the algorithm to detect this (Swift), along with the actual Json we're talkin' about.

I'll always *ALWAYS* be against ducktyping (As documented in [#1](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Models/Notifications/Notification.swift#L161) and [#2](https://github.com/wordpress-mobile/WordPress-iOS/blob/develop/WordPress/Classes/Models/Notifications/NotificationRange.swift#L60).

But since we need this implemented for yesterday, let's give it a green light, and pray for forgiveness.

@planarvoid i know you were after something like this, cc'ing you in case you're still working on it!




```
extension Notification {

    var isPingback: Bool {
        guard let subjectRanges = subjectBlock?.ranges, subjectRanges.count == 2 else {
            return false
        }

        return subjectRanges.first?.kind == .Site && subjectRanges?.last.kind == .Post
    }
}
```


---

```
      "subject": [
        {
          "text": "Pingback? \u2013 Lalala linked to your post Post Post.",
          "ranges": [
            {
              "type": "site",
              "indices": [
                0,
                18
              ],
              "url": "https:\/\/lalalantean.wordpress.com\/2018\/06\/04\/pingback-2\/"
            },
            {
              "type": "post",
              "indices": [
                39,
                48
              ],
              "url": "https:\/\/lanteanar.wordpress.com\/2018\/05\/09\/post-post-2\/",
              "site_id": 56127862,
              "id": 236
            }
          ]
        }
      ],
```

**Comment by elibud** [comment]
@apeatling looping you in since this is something we'll want to address on the Calypso side of things too.  I'm not sure if you have someone on your team that could fix it on the backend?

**Comment by apeatling** [comment]
Added to the list of notifications fixes for the next round.

**Comment by elibud** [comment]
Thanks @apeatling  can you keep us in the loop when it's worked on?

**Comment by jleandroperez** [comment]
@apeatling +1 do you  happen to have a link to the master issue (if any?). The gravatar URL is broken (in Pingback Notifications), and i'm afraid that one requires a backend fix.

Thanks Andy!

**Comment by gwwar** [comment]
@elibud @jleandroperez @folletto would it be possible to update the summary with the before/after?

Depending on what was actually worked on I feel that we should have probably updated the note itself so all clients (mobile/calypso/iframe standalone) could benefit.

cc @dmsnell

**Comment by folletto** [comment]
> Depending on what was actually worked on I feel that we should have probably updated the note itself so all clients (mobile/calypso/iframe standalone) could benefit.

Note that this is a specific request for mobile where it wasn't clear that the notice was tappable — it added a new block not existing elsewhere, so it doesn't create a mismatch. 
The same issue didn't come up on web as far as I know, so I'm not sure if the same problem exists on web. If there's evidence, we can consider it.

Note also that given the way the API payload is shaped the above is structurally an hack, so I'd avoid to replicate it on other platforms unless necessary. Broader redesigns I think would be welcome, but given the current structure of the API payload I think it's also necessary an API redesign too.

Before state, from https://github.com/wordpress-mobile/WordPress-iOS/issues/9480#issuecomment-392929534: 

![img_1752](https://user-images.githubusercontent.com/1396552/40683206-d41fa7ac-635b-11e8-8af8-28d7d99de1c3.PNG)

**Comment by jleandroperez** [comment]
@folletto thank you sir!. Nevertheless, we could probably align *everything* with an improved backend payload.

For the record, this is the way this looks now:

![41056517-cdc668ec-699a-11e8-87fa-63a1dcb912da-2](https://user-images.githubusercontent.com/1195260/41241623-cb0a7ce2-6d73-11e8-93c2-ff2dd6bd0d81.png)


@gwwar (If) we were updating the backend, we could remove the local patch. Which would make me extremely happy. (Thank you!!)

**Comment by gwwar** [comment]
@jleandroperez could you paste a before/after example of the data change you'd like to see with the note? Are you thinking of adding an additive property that notes the Comment type? We currently have 3 (comments, pingbacks, and trackbacks). I can follow up with an issue in our Notifications repo

See this post p7jreA-TT-p2 for more context between comment types.

**Comment by jleandroperez** [comment]
@gwwar

**Comment by jleandroperez** [comment]
@gwwar sorry, i've just sent... by accident an empty comment!. Of course!. What we roughly added in PR #9533 looks like this:

```
    {
      "text": "Read the source post",
      "ranges": [
        {
          "type": "noticon",
          "indices": [
            0,
            0
          ],
          "value": "\uf442"
        },
        {
          "type": "",
          "indices": [
            0,
            20
          ],
          "url": "https:\/\/link-to-the-source.blog\/sarasonia.html"
        }
      ]
    },
```

That's a new Block, to be added in the Pingback Notification's Body. 

Full JSON sample files ([Pristine + Patched available here](https://cloudup.com/cSwCG_zzn4J)).

Thank you SOOOO MUCH!!!
