### ISSUE TITLE
Improve labeling of "Clear media cache" button

### ISSUE THREAD

**Issue by khaykov** [wordpress-mobile/WordPress-iOS#9485]
In the app settings, implication and labeling of "Clear media cache" button are not too clear.
Some users are confused about what effect this button will have on their website and assume that it will delete everything.

**Comment by iamthomasbishop** [comment]
How does something like this look and sound?

`Free up storage space on this device by clearing your temporary media files. This will not affect media on your site.`

It looks like this:

<img width="487" alt="screenshot 2018-06-12 11 09 01" src="https://user-images.githubusercontent.com/1200432/41302793-0b1922c6-6e31-11e8-8c5c-103fca2171c8.png">

**Comment by iamthomasbishop** [comment]
> Think it would help if the button become more verbose like Clear Local Media Cache or Clear Media Cache from this Device or would that just introduce more confusion?

I think so. Perhaps `Clear Device Media Cache`? Might be worth tagging this issue as `needs copy review` once we're ready for a final review.

**Comment by frosty** [comment]
Thanks both!
