### ISSUE TITLE
Question: taking CoreData operations off main thread

### ISSUE THREAD

**Issue by saraseif** [wordpress-mobile/WordPress-iOS#9490]
Hello guys!

According to best practices, it is better to do Coredata related operations in the background, not to cause any possible performance drops, or UI blocks. 

I feel like you are doing some database access in the main thread:
1. Class: AztecPostViewController, function:displaySwitchSiteAlert, is calling displayBlogSelector which is fetching an object from mainContext
2. Class: PageListViewController, function: handleMenuAction, is calling draftPage which is doing database operations

Don't you think it would be better to take these operations off the main thread?

**Comment by kwonye** [comment]
Thanks for the feedback, @saraseif! From what I understand there's nothing explicitly wrong with implementing Core Data in the [main thread](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreData/Concurrency.html#//apple_ref/doc/uid/TP40001075-CH24-SW2)

@diegoreymendez @astralbodies any insights?

**Comment by astralbodies** [comment]
Fetching and storing objects from the main context for use in the main UI thread is perfectly safe unless of course the operation itself is a complex one - then an asynchronous approach might be warranted. Typically if the operation is complex or if the object graph is deep it can be offloaded to a background queue. In a number of cases within the app I'm sure there are slight performance gains that can be made by doing this but there's a trade off of having to transfer the data to a thread-safe model to be used by the UI. Creating a draft in PageListViewController should be a lightweight operation. The writer context is on a background queue so the creation of the object is quick and the actual storage to disk is non-blocking.

If you do end up finding a pinch point in the app that you can see performance degradation, please let us know by opening a PR or an issue! I'm sure there are improvements that can be made with massive post data (like editing an existing huge post) that would tend to be an edge case but would illuminate potential bottlenecks. 

@diegoreymendez might have some additional insights into the Aztec-specific side of persistence.

**Comment by diegoreymendez** [comment]
In my opinion it's not a matter of whether to do it or not, but more about deciding when to do it.

I tend to agree that the way in which we're currently persisting data in Aztec could use some improvements.  Moving CoreData operations to a background thread _could be_ one of those improvements as it would allow us not to lock the main thread.  Another improvement would be to avoid saving on each keystroke.

But before moving forward with something like that we have to evaluate how moving that operation to the background (ie: making it asynchronous) would impact the rest of the code.

The truth is that the VC should be able to handle it just fine, but we still have to be mindful of the current state of the code.

**Comment by designsimply** [comment]
Hi! I'm cleaning up old issues and it looks like the discussion here hasn't had any new activity and the question was more or less answered saying it's okay to do Coredata related operations in the foreground as long as it's mindful and also because the cost of switching something like that can be high given the current stats of a codebase (this was my interpretation so please do correct me if any of it sounds off!).

I'm closing this issue as a question answered and with noting that if this comes back up again then we can loop back to the discussion here at that time.
