### ISSUE TITLE
Page can not scroll if title is too large.

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9507]
Hey y'all.  I was alerted to this problem while working on this <a href="https://automattic.helpshift.com/admin/issue/284133/">issue</a>

In iOS if you are creating a title and the title stretches to being larger then the edit window (so it covers the entire page beyond the toolbar and keyboard) you can not swipe down to continue to edit the rest of the page.  It seems like this is probably not an issue with most languages, but in the case of a pictorial language like Japanese, if the characters are set large and they write a long title it could happen.  Is there a way to make the title scrollable?

<img src='http://cld.wthms.co/ozVOPi+'>
In this image if you try to swipe the page will not move.

To replicate:
1. Start a new post
2. Give the post a ridiculously long title so it fills the screen
3. try to swipe up or down, you will not be able to swipe

WordPress 10.0.2
iOS 11.3
iPhone 6s

**Comment by rachelmcr** [comment]
Thanks for the report and details! We have an existing report of this open in https://github.com/wordpress-mobile/AztecEditor-iOS/issues/872 in the Aztec repo, so I'm going to close this to avoid having duplicates open.
