### ISSUE TITLE
Blog post: bullet points are sometimes blue

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#9525]
### Expected behavior
All bullet points should be black.

### Actual behavior
If the line starts with a URL the bullet point is blue (the URL color).

### Steps to reproduce the behavior
- Go to Notifications, select a Notification, then select a Post with a list.
- Notice the items that start with  URL have a blue bullet point, while the others are black. In a browser, all are black. (example post: p77Llu-apb-p2)

![list_bullets](https://user-images.githubusercontent.com/1816888/40995758-44d4ec9e-68bd-11e8-97bd-9fa75131a8d1.png)

**Comment by rachelmcr** [comment]
This came up again in an internal report (p4a5px-2v3-p2).

**Comment by designsimply** [comment]
This came up again in another internal report, and this should be prioritized in upcoming Reader improvements—we need to make sure the vast majority of user created content is properly displayed in the apps.

<p style="clear:both;"><sub>(internal reference: p4a5px-2wF-p2 h/t @elibud)</sub></p>
