### ISSUE TITLE
Undeclared Type 'Codable'

### ISSUE THREAD

**Issue by Stackflood** [wordpress-mobile/WordPress-iOS#9528]
I am using Wordpress iOS release 8.6 with XCode 8.2.1 and swift 3.0.1. On building the project, I am getting these errors in Attribute.swift file : 

use of undeclared type 'Codable'
...                                     'Decoder'
...                                     'Codingkey'
...                                     'Encoder'
...                                     'JsonDecoder'
...                                     'JsonEncoder'

In CSSAttribute.swift
...                                     'Codable'

**Comment by frosty** [comment]
So `Codable` / `Decodable` and their associated types are features of Swift 4, so they won't be available if you're on Swift 3. I think release 8.6 was around the time we started transitioning over to Xcode 9 and Swift 4, so perhaps you're using a commit that has some of the newer features.

Is there a specific reason you're using an older release and not the latest?

**Comment by Stackflood** [comment]
Thanks for the quick reply. Right now, I am using iOS on a VM machine, so, this is the best configuration I can get as of now. Can you please tell me the release which will work without any issues with the present configurations : XCode 8.2.1 and Swift 3.0.1 ? Do you think of any other issues I may face related to the project being run on a VM ?

P.S : You may also update the Release notes on the 8.6 Release page so that other mayn't face the same issue. It says : "At the moment WordPress for iOS requires Swift 3.0 and Xcode 8.2 or newer. Previous versions of Xcode can be downloaded from Apple."

https://github.com/wordpress-mobile/WordPress-iOS/tree/8.6

**Comment by Stackflood** [comment]
Any suggestions ?

**Comment by frosty** [comment]
Apologies for the delay responding to you. I couldn't easily tell you which release would work with that configuration, as support for that setup was dropped quite some time ago. I'd probably suggest working backwards through the releases – did you try 8.5?

In general, if possible, I'd recommend just working with the latest version of WordPress for iOS, using Xcode 9 and Swift 4. We can't really guarantee that older versions will continue to build or work, and you'll miss out on newer enhancements and features. Also, if you were considering contributing to the codebase (which we always welcome!), it would be extremely difficult for us to incorporate changes made to a much older version of the code, as it's constantly changing. A class you modify in a 7 month old release of the app may not even exist in the latest version, or may have significant changes.
