### ISSUE TITLE
iOS10: Navigation buttons not appearing in WebViews

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#9572]
### Expected behavior
Navigation buttons appear.

### Actual behavior
On iOS10, when a WebView is displayed, the navigation buttons do not display. They are there and work, you just can't see them. They display fine on iOS11.

### Steps to reproduce the behavior
On iOS10, launch a WebView. (ex: Site > View Site, Me > App Settings > Privacy Settings > any URL)

iOS10:
![view_site_10](https://user-images.githubusercontent.com/1816888/41259121-a9517e40-6d8f-11e8-8aa1-5154349f1f86.png)

iOS11:
![view_site_11](https://user-images.githubusercontent.com/1816888/41259196-f9cb8726-6d8f-11e8-8852-bc9b6522e07d.png)

**Comment by designsimply** [comment]
I tested with iOS 12.2 today and confirmed the Webview navigation buttons are there as expected. 

<img src="https://user-images.githubusercontent.com/1119271/56178786-b6fe7600-5fc0-11e9-9e51-c089281c47f6.PNG" width="270" alt="IMG_2565">

**Comment by designsimply** [comment]
@ScoutHarris do we still need to work on this for iOS 10?

**Comment by ScoutHarris** [comment]
Hey @designsimply . Since we've dropped support for iOS10, you are correct, we can ignore this. And closing.
