### ISSUE TITLE
Share Extension shows in password manager activity sheet

### ISSUE THREAD

**Issue by frosty** [wordpress-mobile/WordPress-iOS#9574]
### Expected behavior

When I tap the password manager button on the login screen, I should just see the password managers I have installed, such as 1Password.

### Actual behavior

The WordPress Share and Draft extensions are also showing in the action sheet:

![img_d91d3dd5a798-1](https://user-images.githubusercontent.com/4780/41301962-312a2124-6e61-11e8-84cc-4d97d3af301b.jpeg)

##### Tested on iPhone X, iOS 11.4, WPiOS `develop` (10.2)

cc @bummytime

**Comment by bummytime** [comment]
This is most likely occurring because of the work done in #9543. We will need to tweak the `NSExtensionActivationRule` logic a tad.

**Comment by bummytime** [comment]
Fixed in #9624
