### ISSUE TITLE
Post authoring: the Excerpt field should be a multiline field

### ISSUE THREAD

**Issue by eliorivero** [wordpress-mobile/WordPress-iOS#9579]
When you edit the entry settings, you can edit the Excerpt. When it's blank, it looks like a single line field so I was worried I wouldn't be able to enter a proper excerpt. However, I continued writing and it transformed into a multiline field.

This is very confusing on a first look and doesn't match user expectations. It should be a multiline field.

**Comment by elibud** [comment]
Thanks for the report @eliorivero
