### ISSUE TITLE
Share & Draft extensions do not attach images to posts

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#9581]
### Expected behavior

When uploading an image to WordPress and inserting the URL into the post the media item also is attached to the post behind the scenes. 

### Actual behavior

When using the share or draft extension the media items are not formally attached to the post.

### Steps to reproduce the behavior

1. Select an image from your camera roll.
2. Share the image and select the Share extension or Draft extension.
3. Upload to a new post.
4. Visit wp-admin on the site.
5. Find the image in the media library.
6. See that there is no "Uploaded To" item with a link to the post.

##### Tested on iPhone X, iOS 11.4, WPiOS 10.2.0

cc: @bummytime

**Comment by bummytime** [comment]
@astralbodies this should have been addressed in #9526. Did you see this behavior on the latest in `develop`?

**Comment by astralbodies** [comment]
Derrrrrrrrrp I totally missed #9070. Thanks for the bonk on the head @bummytime!
