### ISSUE TITLE
Previews reload after scrolling

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#9584]
### Expected behavior
Preview that are alredy loaded should not be lost while scrolling.

### Actual behavior
![video](https://user-images.githubusercontent.com/4836764/41421283-be02dece-6ff6-11e8-82b2-cc7830598ff8.gif)

Feedback from TF. I was not able to reproduce it on my devices.

##### Tested on iPhone10,6, iOS 11.4, WPiOS 10.2.0.0

**Comment by ScoutHarris** [comment]
I'm unable to repro this on 10.2, 10.3, or develop.
