### ISSUE TITLE
Modernize the push notification sound

### ISSUE THREAD

**Issue by astralbodies** [wordpress-mobile/WordPress-iOS#9594]
It's 2018 and the push notification sound from 2009 is ... well ... dated.

Find something pleasant that isn't piercing and sounds like it wasn't recorded through a coffee can.

**Comment by loremattei** [comment]
I'm removing the milestone from this one since I'm closing 10.3 and the conversation in the PR.

**Comment by astralbodies** [comment]
Closing for now.
