### ISSUE TITLE
Empty sites screen text is cramped in some cases

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#9606]
Sometimes the empty sites screen has cramped/cutoff text. Appears more common on the iPhone 8 Plus.

<img width="309" alt="bildschirmfoto 2018-06-16 um 21 03 07" src="https://user-images.githubusercontent.com/517257/41556712-cb84cef4-72f8-11e8-93b5-b41ad1a367ba.png">

**Comment by ScoutHarris** [comment]
I'll look at this as part of https://github.com/wordpress-mobile/WordPress-iOS/issues/9504

**Comment by ScoutHarris** [comment]
The NoResultsView has gone through several iterations, and in the final version I have not seen the cramped labels happen. 

![nrv_portrait](https://user-images.githubusercontent.com/1816888/44611673-ce81b800-a7bf-11e8-9a97-4794bfe0ff14.png)

![nrv_landscape](https://user-images.githubusercontent.com/1816888/44611677-d2153f00-a7bf-11e8-8855-d37c217869a2.png)
