### ISSUE TITLE
Switch Sites : UI weirdness when hiding/displaying sites

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9616]
While poking around the iOS app today, I ended up on the Switch Site > Edit page to enable one of my other sites that I had hidden.  When I enabled that site I noticed that the enable/disable button for one of the other sites in the list was being effected as well.  The other site did not get activated, but the slider for the button changed color to a dark grey instead of the light grey that would indicate hidden.  As I continued to toggle on and off the site I wanted to display the dark grey was moving from one site to another.

See <a href="http://cld.wthms.co/0AQ28j">video</a>

To Reproduce:
1. Go to My Site > Switch Site > Edit
2. Find a site that is currently hidden and start to toggle it
3. A dark grey should appear in another one of your sites, and move to a new location each time you toggle the site

WordPress 10.3
iOS 11.4
iPhone 6s

**Comment by kean** [comment]
This feature (hiding sites) was removed. Closing as obsolete.
