### ISSUE TITLE
Login: When the 1Password button is pressed the option to Share as draft appears

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9617]
I'm not sure if this is an error or not, but it seemed odd so I thought I would mention it.
While logging in to my account today I clicked on the 1password option, when the iOS sharing options appears a choice to select 1Password appeared, but so did the option to share to WP as draft.  Should that be appearing?  
<img src='http://cld.wthms.co/lzxF8U+'>

To Reproduce:
1. Log out of the WordPress app, and then click on the Login button
2. Select the 1password button in the login field
3. You should see the options above.

WordPress 10.3
iOS 11.4
iPhone 6s

**Comment by bummytime** [comment]
@charliescheer Thank you for this issue. I am going to close this one in favor of the previously filed issue: #9574
