### ISSUE TITLE
Login: Error says log in with username instead of email

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#9618]
In certain (probably rare) circumstances, a user logging into wpcom with their email address might encounter an error prompting them to "log in using your WordPress.com username instead of your email address".  Since we don't allow a username login in the wpcom flow, its not obvious to a user what to do next.  

We should be checking for `email_login_not_allowed` for the type of error and perhaps send the user to the self-hosted flow with the site set to "wordpress.com".

**Comment by aerych** [comment]
Related Android issue https://github.com/wordpress-mobile/WordPress-Android/issues/7922

**Comment by pinarol** [comment]
Here is how I reproduced it maybe it might help on testing. I changed my email address in my WP.com account settings and when try to login with my old email I get this error all the time.

**Comment by mindgraffiti** [comment]
More background in comments p77Llu-b5Q-p2

**Comment by SiobhyB** [comment]
This caused some confusion again in 1585388-z.

**Comment by aerych** [comment]
Candidate fix in https://github.com/wordpress-mobile/WordPressAuthenticator-iOS/pull/42

**Comment by aerych** [comment]
Fixed in wordpress-mobile/WordPressAuthenticator-iOS#42
