### ISSUE TITLE
Using non-standard iOS localizations

### ISSUE THREAD

**Issue by vestimir** [wordpress-mobile/WordPress-iOS#962]
It would be great if there’s an option to override the default iOS language in the app. The default behavior would be to use the system language, but if you set another language in the WordPress.app preferences (like Bulgarian, which isn’t available right now in the Settings.app) to load this language bundle instead. 

The preferred languages of the OS can be accessed via 
[[NSUserDefaults standardUserDefaults] objectForKey:@"AppleLanguages"] which returns a NSArray. Upon app initialization we can add a check to see if such key already exists in the app preferences and load it, or if it isn’t to set it to the default OS language. 

Are you OK with this change, so I can make more research and send a pull request?

**Comment by akerbeltz** [comment]
Has there been any movement on this? For locales like Gaelic (gd), this is pretty much a make or break issue as they are generally not supported by iOS.
