### ISSUE TITLE
Associate a custom domain to a site with a business plan 

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#9630]
Many of business sites don't have a custom domain associated even though it's free with their plan. We want to prompt and allow users that have already bought a business plan to associate a custom domain to their site.

**Be sure to check Zeplin for the final designs as it has changed from the design shown here.** 

The attached designs show the entire automated transfer flow. We want to implement the five screens illustrating domain registration, plus the dialog that is the entry point to the flow. After completing the domain flow the user should be returned to the plugin installation flow.
![at_ios_i31](https://user-images.githubusercontent.com/1435271/41723572-16940844-7531-11e8-894b-23f3db51ddf6.jpg)

**Comment by ScoutHarris** [comment]
@SylvesterWilmott - on the initial Register Domain view, is it meant to pre-populate suggestions? If so, I'm assuming based on the Site Title? If the site doesn't have a title, then use...?

![initial_view](https://user-images.githubusercontent.com/1816888/42779937-10dd74b2-88ff-11e8-98db-661a0efee3e5.png)

**Comment by ScoutHarris** [comment]
Hey @SylvesterWilmott. I was looking at the nav bar buttons in the domain registration part. I was wondering if we could emulate what the site creation flow does.

On the initial screen, the Cancel button is on the left, and a Help button is on the right.

<img width="429" alt="initial_view" src="https://user-images.githubusercontent.com/1816888/42785887-45e777ea-8911-11e8-9f8e-23b0ec94f94a.png">

After that, a Back button is on the left, with the Help still on the right.

<img width="430" alt="second_view" src="https://user-images.githubusercontent.com/1816888/42785912-5bfe99be-8911-11e8-80a4-71a706e5ab5f.png">


I think it's a bit inconsistent to have the Cancel on the right. Also, I think it would be nice to provide access to support if they need it.

What do you think?

**Comment by SylvesterWilmott** [comment]
@ScoutHarris thanks for the feedback

The suggestions on the screen you mentioned is based on site title, yes. If there isn't a site title we can use the existing site URL to generate suggestions ie. https://`keyword`.wordpress.com

>On the initial screen, the Cancel button is on the left, and a Help button is on the right.

Good catch! I've updated the designs for that in Zeplin and agreed on the Help button.

**Comment by ScoutHarris** [comment]
Thanks @SylvesterWilmott !

**Comment by ScoutHarris** [comment]
Conversation about registering custom domains: https://wp.me/p9xubY-iH-p2

**Comment by frosty** [comment]
This has now been implemented.
