### ISSUE TITLE
Replace UIWebView with WKWebView

### ISSUE THREAD

**Issue by nheagy** [wordpress-mobile/WordPress-iOS#9633]
Seems like it's time to fully excise UIWebView from the codebase:

https://twitter.com/bradeeoh/status/1009302764722184192

https://developer.apple.com/documentation/uikit/uiwebview?changes=_6

As the tweet points out, Apple is looking for feedback on any remaining issues with migrating away from UIWebView, so if we find we should [log bugs with apple](http://bugreporter.apple.com).

cc: @kwonye

**Comment by koke** [comment]
I'm not sure if there's more but the thing holding us back that I'm aware of is authentication support.

We've switched to WebKit in a bunch of places already but only for iOS 11+ devices, since that's when WebKit introduced support to look at the cookies (there were some other issues on iOS 10 IIRC). Because of this, fully dropping UIWebView is conditioned to dropping support for iOS 10.

**Comment by prathap2626** [comment]
What is the alternative for UIWebView in iOS 12.0?

**Comment by stevebaranski** [comment]
Greetings @prathap2626! Apple recommends the use of [`WKWebView`](https://developer.apple.com/documentation/webkit/wkwebview).

**Comment by yangkunlll** [comment]
We have a iOS web application that uses remotely served images.

The images are served with a Cache-Control header: 'Cache-Control': 'max-age=31536000'.

Prior to iOS 12, the images were fetched once and cached during the usage of the app. After upgrading to iOS 12, the cache stopped working and images are always fetched from the server. We use UIWebView (we have not yet migrated to WKWebView).

It does not happen in Safari on iOS 12.

I cannot find any clue to why this suddenly no longer working. Does anyone have a clue?

**Comment by frosty** [comment]
This would also be great for Marzipan – at least at the moment, it doesn't include `UIWebView`.

**Comment by designsimply** [comment]
Noting that this is probably worth somebody investigating again so I'm adding it to the next Groundskeeping rotation for a check. "I don’t think the switch should take too long, it’s more about feasibility / investigation maybe."

**Comment by diegoreymendez** [comment]
@designsimply - Removed from Groundskeeping and mover to a mini-project board.

**Comment by koke** [comment]
It’s official now:

> The App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020.

https://developer.apple.com/news/?id=12232019b
