### ISSUE TITLE
Crash while dragging menu item

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#9634]
TestFlight User feedback:
App crashes while dragging Facebook sharing button.

![2coix0](https://user-images.githubusercontent.com/4836764/41764448-6fb2d20e-7601-11e8-832f-95c946c9a00e.gif)

585bd4330aeb16625b4da39e-fabric

**Comment by rachelmcr** [comment]
Closing as it looks like this one was resolved — we only have one report in the last 90 days, and that was on 11.0.0.2.
