### ISSUE TITLE
save_post Action Doesn't Fire from iOS app

### ISSUE THREAD

**Issue by mikedunn1** [wordpress-mobile/WordPress-iOS#9636]
### Expected behavior
Functions in functions.php utilizing the "save_post" action should execute when publishing/updating post in iOS app.

### Actual behavior
save_post action does not execute at all. Publishing/updating the same posts in wp-admin does trigger the action.

### Steps to reproduce the behavior
Publish or update post in iOS app.

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 8, iOS 11.4, WPiOS 10.2

**Comment by aerych** [comment]
Hi @mikedunn1.  Can you provide us with a little more information? 

What was the URL of the site you tested with?

Is this behavior seen on a self-hosted site or a WordPress.com hosted site? (Different APIs are used.)

If this behavior was a self-hosted site, and Jetpack is either not installed or is not connected in the app, did you check if the the `save_post` action is executed via `metaWeblog.newPost` and `metaWeblog.editPost` on your test blog?

**Comment by rachelmcr** [comment]
I'm closing this issue as we're missing details needed for further investigation. @mikedunn1 if this is still a problem for you, please let us know the details requested above and we can reopen this issue.
