### ISSUE TITLE
Crash: Making changes after password change prompts app to crash

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#9641]
If you're logged into the iOS app and change your password (from a web browser) the app will crash when you attempt to make changes to your sites.

Reported in 1239943-z.

5b2797236007d59fcd2612e0-fabric.

### Expected behavior

I expected to receive a warning that the password has changed and given the chance to log back in.

### Actual behavior

The app crashes if you attempt to make changes to a site after the password has been changed in a web browser.

### Steps to reproduce the behavior

1. Log into your WordPress.com account via the iOS app.
2. Log into your WordPress.com account via a web browser.
3. Navigate to Me > Security in the browser and update the password on file for your account.
4. Head back to the app. Navigate to My Site then attempt to make a change to one of your sites.

##### Tested on iPad Mini, iOS 11.4, WPiOS 10.2

**Comment by SiobhyB** [comment]
I tested in 10.4 and can confirm a password change no longer results in a crash. I'm able to publish and edit posts via the app after the change, though. Shouldn't I be logged out or prompted to confirm the new password?

**Comment by nheagy** [comment]
Thanks @SiobhyB! I think this is intentional behaviour.

Closing because the crash is gone 🎉
