### ISSUE TITLE
Add Option to Close Account in Settings

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#9643]
As per this documentation, it's now possible for users to close their accounts via their Account Settings in a web browser:

https://en.support.wordpress.com/close-account/

Questions around account deletion often come up in mobile support, so it'd be handy for users to be able to access this setting directly from the app.

**Comment by designsimply** [comment]
This came up today in an app store review:

<blockquote> am totally BLIND and there is NO WAY to DELETE WordPress Account in the app! Contacting Support is IMPOSSIBLE!</blockquote>

<p style="clear:both;"><sub>(internal reference: p1563664437001300-slack-cellular-happiness, p77Llu-bQ6-p2#comment-1307)</sub></p>
