### ISSUE TITLE
iOS: Improve the discoverability of stock images

### ISSUE THREAD

**Issue by nozomimimi** [wordpress-mobile/WordPress-iOS#9647]
### Expected behavior
Make the stock photos easier to find.

### Actual behavior
It's hard to find now unless you know it exists and specifically look for it.

Currently, you need to go to "+ (add media)" inside the editor, -> tap on the "..." icon -> then select "Free Photo Library".

cc: @kwonye

**Comment by ctarda** [comment]
This looks great, @nozomimimi ! My only concern would be that scrolling horizontally when VoiceOver is active and the height of the scrollable are is narrow, is not a very intuitive operation. Users would need to scroll with three fingers on a narrow area.

**Comment by nozomimimi** [comment]
Thank you for the feedback, @ctarda! :)
I iterated the design a bit and here's the i2. It should solve the concern you expressed, I believe.

![ios_free_photo_discoverability_improvement_i2](https://user-images.githubusercontent.com/36741426/42475948-f2efa116-83d4-11e8-9810-b0c1ac46a90e.jpg)

**Comment by ctarda** [comment]
Thanks @nozomimimi !

**Comment by jkmassel** [comment]
Given the rollout of Gutenberg, I'm comfortable closing this one.
