### ISSUE TITLE
iOS: “Comments” screen inside the “Publish” section doesn’t have filter

### ISSUE THREAD

**Issue by nozomimimi** [wordpress-mobile/WordPress-iOS#9659]
### Expected behavior
In the iOS app, “Comments” screen inside the “Publish” section doesn’t have filter unlike Android (Android has All, Pending, Approved, Trashed, Spam - see the image below) This leads to unrecoverable comments, so we should add this filters/tabs to iOS.

[![https://gyazo.com/9e92aee6b8518cbc7a8bb9158bee2a84](https://i.gyazo.com/9e92aee6b8518cbc7a8bb9158bee2a84.png)](https://gyazo.com/9e92aee6b8518cbc7a8bb9158bee2a84)

**Comment by nozomimimi** [comment]
![comments_filter_on_ios_i1](https://user-images.githubusercontent.com/36741426/43105323-bdcf4210-8ed4-11e8-9317-e9b8614520d0.jpg)

**Comment by nozomimimi** [comment]
![comments_filter_on_ios_i1](https://user-images.githubusercontent.com/36741426/43106554-6c50aa64-8ed9-11e8-9cff-93cead359aec.jpg)

**Comment by thehenrybyrd** [comment]
Another request for this is #2282635-zen.

**Comment by mdrockwell** [comment]
Another request: 3813364-zen

**Comment by ScoutHarris** [comment]
Filters added with https://github.com/wordpress-mobile/WordPress-iOS/issues/15955.
