### ISSUE TITLE
iOS: Add “media type tab” to Media browser

### ISSUE THREAD

**Issue by nozomimimi** [wordpress-mobile/WordPress-iOS#9660]
### Expected behavior
Android has "All, Images, Documents, Videos, Audio" on the Media screen (see image below), but this doesn't exist on iOS app. We should add this to iOS app too.

[![https://gyazo.com/73bb4d4f3cc001b974239cea403cd541](https://i.gyazo.com/73bb4d4f3cc001b974239cea403cd541.png)](https://gyazo.com/73bb4d4f3cc001b974239cea403cd541)

**Comment by nozomimimi** [comment]
![media_filter_on_ios_i1](https://user-images.githubusercontent.com/36741426/43106585-855c26be-8ed9-11e8-81ff-c25329ee12c5.jpg)

**Comment by elibud** [comment]
@jklausa if you are not actively working on this one can you please unassigned it?

**Comment by jklausa** [comment]
done!

**Comment by kean** [comment]
It was added 23.2 – closing.
