### ISSUE TITLE
Login with no connection: improve messaging

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#9664]
### Expected behavior
When attempting to log in when in airplane mode, I expect the displayed message to be helpful. 😄 

### Actual behavior
When attempting to log in when in airplane mode, the displayed message is raw, and does not indicate the problem.

### Steps to reproduce the behavior
- Log out of the app if necessary.
- Put device in airplane mode.
- Launch the app and select Log In.
- Enter email address, and select Next.
- This alert appears:

<img width="300" alt="login_alert" src="https://user-images.githubusercontent.com/1816888/42058393-89a62de2-7add-11e8-9eac-42f1b1f16ca2.png">

**Comment by rachelmcr** [comment]
I confirmed we now show a more helpful error message:

> The internet connection appears to be offline

<img src="https://user-images.githubusercontent.com/8658164/90147967-b6275100-dd7a-11ea-94f5-634627fb685b.PNG" width="300px">

Closing as resolved!
