### ISSUE TITLE
Truncated “post list selector” text on iPad

### ISSUE THREAD

**Issue by etoledom** [wordpress-mobile/WordPress-iOS#9677]
### Expected behavior

The text shows completely (not truncated) on the post list selector.

### Actual behavior
The text gets truncated:
![bc18f041-935f-493b-a039-716347e09cb2](https://user-images.githubusercontent.com/9772967/42119471-5a50d814-7bda-11e8-928c-193a835f5f69.jpeg)

### Steps to reproduce the behavior

1. Run the app on an iPad.
2. Select a multi-user blog.
3. Go to post list.
4. The selector at the top will have the text truncated.

**Comment by frosty** [comment]
@etoledom Are you able to confirm whether you're still seeing this as an issue? I can't seem to recreate it now. Thanks!

**Comment by etoledom** [comment]
You are right!
I tested it again and it seems to be fixed 🤷‍♂️

![img_3d945fa06a32-1](https://user-images.githubusercontent.com/9772967/45429817-69143f00-b67a-11e8-8e25-1d15019edd5b.jpeg)

**Comment by frosty** [comment]
Great! Thanks for checking!
