### ISSUE TITLE
build failures - Unexpected platform condition (expected 'os', 'arch', or 'swift')

### ISSUE THREAD

**Issue by vikramvi** [wordpress-mobile/WordPress-iOS#9683]
### Expected behavior
1. Should be able to launch app on simulator

### Actual behavior
1. Not able to build successfully as getting below error

Unexpected platform condition (expected 'os', 'arch', or 'swift')

in file UIDevice+Helpers.swift

### Steps to reproduce the behavior
1. Has got latest code base
2. Ran commands `rake dependencies` and `pod install` successfully
3. Try to build the project

##### Tested on [device], iOS [version], WPiOS [version]
1. Mac OS : 10.12.6
2. XCode : 9.2

<img width="1439" alt="screen shot 2018-07-02 at 4 35 48 pm" src="https://user-images.githubusercontent.com/308490/42170167-0a4cea5e-7e16-11e8-81a1-f04206cdde8d.png">

**Comment by jklausa** [comment]
Hey there @vikramvi!

The README file seems to be a bit outdated — the app must be build with at least Xcode 9.3 (and we're currently shipping the app using Xcode 9.4.1). Try updating your Xcode :)

**Comment by vikramvi** [comment]
@jklausa thanks for info, can you please re-open ticket so that we can get README updated as well :)

**Comment by jklausa** [comment]
@vikramvi Hey, I opened a PR with updated docs already :) #9684

**Comment by vikramvi** [comment]
verified working with XCode 9.4
