### ISSUE TITLE
Done button layout

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#9691]
Testflight Feedback:
The button Done is unusually high up on the iPhone X, very different for the standard iOS UI on iPhone X Making it harder to reach but also harder to tap. Also tapping on it doesn’t always work with a non mental effort quick kind of tap gesture

![image1](https://user-images.githubusercontent.com/4836764/42220115-671c5306-7ece-11e8-8a2a-7d080ba9bd2c.png)

**Comment by rachelmcr** [comment]
I just ran into this myself on the iPhone XS. It was very hard to tap the Done button (took me half a dozen tries) and at first I thought the button itself was broken.
