### ISSUE TITLE
Site List: Constrain label width on iPad screens.

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#9707]
On an iPad, the call to action shown on an empty site list runs across the screen.  It would be a nice bit of polish to constrain its width a bit. 

![simulator screen shot - ipad pro 9 7-inch - 2018-07-05 at 12 30 29](https://user-images.githubusercontent.com/1435271/42338655-286df190-8050-11e8-8400-dab85bce426c.png)

**Comment by folletto** [comment]
Yes. That component (is it a component right?) should be restrained to max 384pt (iPhone 8+ max width minus padding).

![screen shot 2018-07-06 at 11 14 26](https://user-images.githubusercontent.com/4389/42373749-c5f73ff8-810d-11e8-8533-cbf320f41a5c.png)

**Comment by ScoutHarris** [comment]
The layout was updated with the Actionable Empty States project. It now looks like this - 

![my_sites_portrait](https://user-images.githubusercontent.com/1816888/50718789-7ce01880-1050-11e9-9329-a0804aab9686.png)

![my_sites_landscape](https://user-images.githubusercontent.com/1816888/50718794-80739f80-1050-11e9-87d6-05cbb1d029fe.png)
