### ISSUE TITLE
Login: Hide Sites section header when there are no sites to show

### ISSUE THREAD

**Issue by aerych** [wordpress-mobile/WordPress-iOS#9708]
When logging in to an account with 0 sites the login epilogue still shows a sites section header.  It looks a bit odd.  We could probably hide this when there are no sites, or maybe show an improved call to action instead. 

![simulator screen shot - ipad pro 9 7-inch - 2018-07-05 at 12 30 17](https://user-images.githubusercontent.com/1435271/42338817-ac8e376e-8050-11e8-92eb-56b9aa69c58c.png)

**Comment by folletto** [comment]
Well spotted. 

I'd start by:

1. Removing the label
2. Making sure that clicking "Continue" opens "My Site" which should already contain the call to action.
