### ISSUE TITLE
Paragraph formatting lost when saving drafts

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#9712]
Multiple paragraphs merge into one big chunk of text when saving drafts in the editor

### Steps to reproduce the behavior
1. Start a new post, with multiple paragraphs:
![img_2788](https://user-images.githubusercontent.com/4836764/42364791-bd032ed6-80fc-11e8-9711-497a681402fd.PNG)

2. Save as draft
3. This is how the post is updated when saving completes:
![img_2789](https://user-images.githubusercontent.com/4836764/42364846-e7e7c850-80fc-11e8-9375-0b7a23d594cb.PNG)

##### Tested on iPhone 7, iOS 11.4, WPiOS 10.4.0.0

**Comment by SiobhyB** [comment]
This came up in 1257890-z.

**Comment by SiobhyB** [comment]
Another one in 1258495-z:

> when I compose a new post in the app, after I save it or update it, it losses my paragraph breaks, so that when I preview the post, it comes out as one long paragraph. What’s going on there? I have to go back and re-insert the paragraph breaks manually before publishing.

**Comment by SiobhyB** [comment]
This came up again in 1260306-z.

**Comment by SiobhyB** [comment]
Noting another (so I can follow up with the user): 1260555-z

**Comment by diegoreymendez** [comment]
The fix is coming up.

That said, since we'll be closing these issues soon let's gather all feedback in the original issue here: https://github.com/wordpress-mobile/WordPress-iOS/issues/9712.
