### ISSUE TITLE
Site list in "My Sites" not stuck to top after viewing all sites

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#9725]
### Expected behavior
If I'm viewing "My Sites," I expect the list to be stuck to the top of the screen at all times.

### Actual behavior
If I go to "Edit" to select some additional sites and scroll down then return to the My Sites list, I get some inadvertent padding at the top of the site list.

### Steps to reproduce the behavior
1. Start on the My Sites screen.
2. Click "Edit" to view all sites and select some additional ones. Scroll down the list a bit.
3. Click "Done" to return to the My Sites list.

You'll notice a padding that's only apparent if you scroll down after clicking "Edit."

**Before**
![img_0540](https://user-images.githubusercontent.com/7240478/42461780-90f690d0-835e-11e8-8084-ffeb3bd4bc30.png)

**After steps above**
![img_0539](https://user-images.githubusercontent.com/7240478/42461786-95198eb0-835e-11e8-8500-39d86e5e6d1b.png)

**Comment by kean** [comment]
Closing as obsolete.
