### ISSUE TITLE
Reader: images appear extra large for particular post

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-iOS#9734]
### Expected behavior

Images appear normal as per Calypso: https://wordpress.com/read/feeds/25801/posts/1918614050

### Actual behavior

Images appear extra large and can't see them as they are too large

### Steps to reproduce the behavior

Follow this feed: https://wordpress.com/read/feeds/25801
Open this post in the reader in WPiOS: https://wordpress.com/read/feeds/25801/posts/1918614050

##### Tested on iPhone 7 plus, iOS 11.4, WPiOS 10.2 and WPiOS 10.4 (both show the same behaviour)

![ios - 1](https://user-images.githubusercontent.com/128826/42497752-a59c5db6-846d-11e8-89b2-8196033602d9.jpg)

**Comment by designsimply** [comment]
Tested with WP Internal 12.8.0.20190709.2 on iPhone 6S iOS 12.3.1 and found that gallery images are still displayed too large for the allotted space in the Reader.

<img src="https://user-images.githubusercontent.com/1119271/61080122-938d7080-a3e1-11e9-84e0-f145444602ad.PNG" width="270" alt="IMG_2908">

<sup>(more images: https://cloudup.com/cwKqmR2VUeJ)</sup>
