### ISSUE TITLE
[Extract notifications] Document the adopted solution, and how it can be extended with new content types / actions

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#9754]
`FormattableContent` comes to replace `NotificationBlock`, with the same core but with the promise of reusability and extensibility.

This issue is to document how does it work and how to extend its functionality in the future.

**Comment by loremattei** [comment]
Moving to 11.0 as 10.8 has been released and 10.9 frozen.

**Comment by ctarda** [comment]
This should have been closed, as it was published during the 10.9 release cycle. Closing it now
