### ISSUE TITLE
Refresh visual representation of notification after approving / unapproving a comment

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#9770]
As mentioned in PR #9765, it seems like approving / unapproving a comment does not trigger a refresh of the cell in the `NotificationsViewController`

**Comment by ctarda** [comment]
This seems to happen in production (v 10.4.0.2) so it might make sense to diff against `develop`

**Comment by aerych** [comment]
Resolved in https://github.com/wordpress-mobile/WordPress-iOS/pull/9771
