### ISSUE TITLE
Post Publish Confirmation Screen Buttons are missing outlines/formatting

### ISSUE THREAD

**Issue by alisterscott** [wordpress-mobile/WordPress-iOS#9786]
### Expected behavior

As per App Store app:

![app store - 1](https://user-images.githubusercontent.com/128826/42802339-fd7eaf20-89e5-11e8-8f6f-701832f927c8.jpg)

### Actual behavior

![post post publish - 1](https://user-images.githubusercontent.com/128826/42802352-03ff3e96-89e6-11e8-9de9-537c49bda51a.jpg)

### Steps to reproduce the behavior

1. Open WPiOS Beta
2. Publish a post
3. View the post publish screen

**Comment by loremattei** [comment]
Closing it as it has been fixed in #9788.
