### ISSUE TITLE
App Settings: Remove geolocation label trimmed

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#9815]
In the Spanish localisation, and therefore it is safe to assume that this might be an issue in other localisations as well, the "Remove Location From Media" label in App Settings is trimmed and therefore there is no clear indication of what that toggle is for

### Expected behavior
One possibility might be navigating to another screen when tapping that label, so that the actual switch to toggle it on/off does not overlap the label.

### Actual behavior
![img_e68d9ca32b2a-1](https://user-images.githubusercontent.com/2722505/42983231-28730c4c-8c18-11e8-99a0-9fa85d9a248f.jpeg)

There is not enough room for the label to clarify what the switch is for.

### Steps to reproduce the behavior
- Switch the system language to Spanish (I assume this might be similar in German)
- Navigate to Me > App Settings

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPhone 7s Plus, iOS 11.4.1, WPiOS 10.4

**Comment by elibud** [comment]
![Simulator Screen Shot - iPhone X - 2020-06-08 at 17 50 05](https://user-images.githubusercontent.com/5558824/84079172-8772b000-a9b0-11ea-85db-19e47641209d.png)

No longer an issue.
