### ISSUE TITLE
Notification Settings for Followed Sites: localised labels trimmed

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#9816]
In the Notification Settings for Followed Sites view, the labels "Email me new posts" and "Email me new comments" are clipped in the Spanish localisation (and it is safe to assume this would happen in other languages as well)

### Expected behavior
The labels should be completely visible

### Actual behavior
![img_16c2a95761d4-1](https://user-images.githubusercontent.com/2722505/42983707-b4ec3174-8c1a-11e8-882a-a28b8e8abacb.jpeg)

The labels "Email me new posts" and "Email me new comments" are clipped.

### Steps to reproduce the behavior
- Set device's language to Spanish
- Navigate to Me > Notifications > Tap a "Followed site"

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPhone 7s Plus, iOS 11.4.1, WPiOS 10.4

**Comment by elibud** [comment]
Adding to HackWeek issues on the Groundskeeping project.

**Comment by erricgunawan** [comment]
There's also trimmed label in Android Indonesian version, under the **Notification Settings** > _Notify me on pending drafts_

![screenshot](http://cld.wthms.co/hQ9f1Q+)
