### ISSUE TITLE
Statistics - Insights: labels clipped in Spanish localisation

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#9817]
Some labels in the Spanish localisation of the Insights tab are clipped. It is safe to assume that this would happen in other locales as well.

### Expected behavior
Labels should not be clipped. 

### Actual behavior
![img_3f922a144d68-1](https://user-images.githubusercontent.com/2722505/42984139-a5168cf6-8c1d-11e8-9a91-9621445e6121.jpeg)

Notice how the "All time posts, views, and visitors" and the "BEST VIEWS EVER" labels are clipped.

### Steps to reproduce the behavior
- Set the device locale to Spanish
- Navigate to My Sites > Tap a site > Stats > Insights

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPhone 7sPlus, iOS 11.4.1, WPiOS 10.4

**Comment by elibud** [comment]
We are doing a full refresh of stats as part of the NoDeadEnds project, so it's probably safe to tackle this issues as part of that. Ping @SylvesterWilmott @aerych.

**Comment by elibud** [comment]
Fixed as part of Stats Refresh.
