### ISSUE TITLE
Activity log: Events not localised

### ISSUE THREAD

**Issue by ctarda** [wordpress-mobile/WordPress-iOS#9818]
The description of the events in the activity log is not localised.

### Expected behavior
The description of the events in the activity log should be localised according to the system's locale

### Actual behavior
The description of the events remains in English
![img_2915](https://user-images.githubusercontent.com/2722505/42984477-4937a7ec-8c1f-11e8-88a8-6b7cc8c51b37.PNG)
![img_0fed3bdaedf3-1](https://user-images.githubusercontent.com/2722505/42984480-4dc24fa6-8c1f-11e8-9fa7-e3f090ca292c.jpeg)

### Steps to reproduce the behavior
- Switch the device to a locale other than English
- Navigate to My Sites > Tap on a site > Activity

##### Tested on [device], iOS [version], WPiOS [version]
Tested on iPhone 7sPlus, iOS 11.4.1, WPiOS 10.4

**Comment by jklausa** [comment]
@elibud it looks like the AL stuff itself isn't localised too well — here's what I see in calypso when I change my language to German:
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/1594081/43019591-d25a839e-8c5d-11e8-923b-3762fac6511a.png"> and in the app:
![simulator screen shot - iphone x - 2018-07-20 at 20 45 38](https://user-images.githubusercontent.com/1594081/43019623-e3c80796-8c5d-11e8-8a2c-4149f8c5a284.png)

**Comment by elibud** [comment]
I wonder why our dates are not localized, can you double check that? Also, lets ping the AL team to figure out if they have plans for localization please.

**Comment by jklausa** [comment]
Dates are localized by the system, not by backend, that's why they're in english :) I'll reach out ot AL folks!

**Comment by elibud** [comment]
I thought you were showing a screenshot of your phone in German 🤦‍♀️

**Comment by jklausa** [comment]
Haha, no — I just changed the language in Calypso and the same stuff in AL changed on Calypso and WPiOS. We have quite a few places in the app where you can get into this weird state with mixed languages because of that — some text coming from the API and respecting the WPCom setting, and some things being localized "locally".

**Comment by elibud** [comment]
All endpoints should respect the `locale` param, can we make a list of the ones which don't and ping the appropriate teams to get them fixed?

**Comment by rachelmcr** [comment]
These strings are translatable; they just don't have translations yet. For example, the string `Website address (home url) set to "%1$s"` is not translated to Spanish: https://translate.wordpress.com/projects/wpcom/es/default/?filters%5Boriginal_id%5D=241463
