### ISSUE TITLE
Tranlation string are not approved after 10 months

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#9822]
I translated these [strings](https://translate.wordpress.org/projects/apps/ios/dev/pt/default?filters%5Bterm%5D=Excerpt&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc) for the app almost a year ago but still they are not approved. How to make this go forward?

**Comment by elibud** [comment]
@akirk can you help us with this one?

**Comment by akirk** [comment]
I've pinged the [GTE Pedro Mendonça](https://make.wordpress.org/polyglots/teams/?locale=pt_PT) about this, hope to get them approved soon.

**Comment by akirk** [comment]
@SergioEstevao your translations are now approved, we can close this. Sergio will actually try to get PTE rights for pt-pt on translate.wordpress.org
