### ISSUE TITLE
Plan: Some of the plan descriptions are not translated

### ISSUE THREAD

**Issue by SergioEstevao** [wordpress-mobile/WordPress-iOS#9823]
On the plan screen in Portuguese (PT-PT) localization some of strings are not translated.

<img width="487" alt="screen shot 2018-07-20 at 15 00 00" src="https://user-images.githubusercontent.com/651601/43006441-a02ce540-8c2d-11e8-8ca8-a1f0e0843247.png">

I believe this strings are server side.

**Comment by elibud** [comment]
@akirk can you help us with this one? Thx

**Comment by akirk** [comment]
@erricgunawan This should be translated by now, we received the translation for it just today: [Date added: 2018-07-24 07:54:11 GMT](https://translate.wordpress.com/projects/wpcom/id/default?filters%5Bterm%5D=Upload%20up%20to%203GB)

**Comment by akirk** [comment]
@SergioEstevao We only translate to PT-BR. If you could/want to help with PT-PT translations for this page it can be done here: https://translate.wordpress.com/projects/wpcom/pt/default?filters%5Bterm%5D=store-product-list&filters%5Buser_login%5D=&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Bview%5D=&filter=Filter&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Comment by erricgunawan** [comment]
Thanks @akirk! I checked and confirmed it's translated now.

**Comment by elibud** [comment]
@akirk 

> We only translate to PT-BR

But we are getting mixed strings for PT-PT with some of the text being translated and some of it not. Maybe the translations are also missing in PT-BR?

**Comment by elibud** [comment]
@SergioEstevao can you confirm PT looks good and if so close this one?

**Comment by elibud** [comment]
@aerych this one should be good to close now, right?

**Comment by aerych** [comment]
For sure.  Closing.
