### ISSUE TITLE
TOS page linked in the app in not localised

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#9824]
The TOS page we link from the App (Me -> App Settings -> WordPress for iOS -> Terms of Service) is not localised. 
Since translated versions of the page exist for some languages, we should use those where possible.

**Comment by akirk** [comment]
We can do a link like https://wordpress.com/tos/?lang=

What are common language slugs in iOS? On WordPress.com we currently have these defined:
- French `fr`
- Spanish `es`
- German `de`
- Italian `it`
- Hebrew `he`
- Russian `ru`
- Japanese `ja`
- Brazilian Portuguese `pt-br`
- Dutch `nl`
- Korean `ko`
- Turkish `tr`
- Indonesian `id`
- Chinese (China) `zh-cn`
- Chinese (Taiwan) `zh-tw`
- Arabic `ar`
- Swedish `sv`

If different ones are used in the app we'll need to do some rewriting, so it would be great if you could  list out/compare them with the ones used in iOS.

**Comment by ctarda** [comment]
Hi @akirk 👋 

This is what we have at the moment on iOS:
- Danish `da`
- German `de`
- UK English `en-GB`
- English `en`
- Spanish `es`
- Finnish `fi`
- French `fr`
- Italian `it`
- Japanese `ja`
- Korean `ko`
- Norwegian bokmål `nb`
- Dutch `nl`
- Polish `pl`
- Portuguese `pt`
- Russian `ru`
- Swedish `sv`
- Turkish `tr`
- Chinese simplified `zh-Hans`
- Chinese traditional `zh-Hant`

**Comment by akirk** [comment]
Thanks @ctarda, this is quite helpful. Did you maybe forget Brazilian Portuguese here or don't we have that?

**Comment by ctarda** [comment]
🙇 @akirk Damn, nice catch! The `pt` localisation we have is actually `pt_BR`. I'll update the original comment

**Comment by aforcier** [comment]
@ctarda Just noting that thanks to @akirk the ToS URL now accepts a locale param with the format e.g. https://wordpress.com/tos/?locale=zh_CN (https://github.com/wordpress-mobile/WordPress-Android/issues/8068#issuecomment-487036939). This should be more accurate than mapping language codes to subdomains.

**Comment by ctarda** [comment]
@akirk @aforcier I have been looking into this today, and it seems like everything redirects to https://en.wordpress.com/tos/?locale=LAN_CODE. For example. https://wordpress.com/tos/?locale=zh_CN redirects to https://en.wordpress.com/tos/?locale=zh_CN

**Comment by ctarda** [comment]
@aforcier In any case, I implemented the changes that would be necessary to pass `locale=xx_XX` as a query string parameter, removing the subdomain as a draft PR (#11610 ) in case you want to grab the code while I am offline. I'll keep an eye on the discussion here anyway in case we can submit a proper PR

**Comment by aforcier** [comment]
@ctarda unfortunately the server-side patch is temporarily reverted as it caused some issues with Google login. Having the changes ready is great though, as soon as a new patch is deployed we can test and ship 👍 Thanks @ctarda!

**Comment by loremattei** [comment]
@aforcier I may be wrong here, but I think that the patch was not reverted, but changed in order to make it not apply to /wp-login.php.

**Comment by aforcier** [comment]
@loremattei ah - you're right @loremattei, but perhaps something else has changed or the emergency fix is more expansive than we realize, since it doesn't look like the redirect is working at all for the ToS page at the moment.

**Comment by aforcier** [comment]
> perhaps something else has changed or the emergency fix is more expansive than we realize

Confirmed with @akirk it's the latter and the logic is always skipped now - when @akirk has an updated patch he'll let us know and we should be able to proceed.

**Comment by akirk** [comment]
I have applied an updated patch server-side, so the redirect works again (plus hopefully no longer interferes with login).

**Comment by ctarda** [comment]
Thanks @akirk The PR is up: #11610

**Comment by aforcier** [comment]
Thanks @akirk!
