### ISSUE TITLE
"Menus" header not centered on site with long site title

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#9831]
### Expected behavior
When I'm on the "Menus" section of my website, I expect the header "Menus" to be centered, which would match the behavior on other screens like "Site Pages," for example.

### Actual behavior
"Menus" header is pushed to the right if you have a long site title.

<img width="773" alt="t1ueky" src="https://user-images.githubusercontent.com/7240478/43100875-ede61952-8e83-11e8-8b78-38f87b4703bd.png">

**Comment by ScoutHarris** [comment]
This is no longer an issue as the Back button label is now 'Back', instead of the site name.

<img width="350" alt="menu_view" src="https://user-images.githubusercontent.com/1816888/56834110-c0dc7080-682d-11e9-9316-a00123fad641.png">
