### ISSUE TITLE
Menus: Don't display Save dialogue if content is unchanged

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#9832]
### Expected behavior
If I change content within the Menus section for my site but then change it back to the original value, I don't expect to see the Save button (since there's nothing to save).

### Actual behavior
The save button still appears.

### Steps to reproduce the behavior
1. Visit the Menus section in the app.
2. Change the menu in use for a section of your site to a different menu. Save button will appear in the top right-hand corner.
3. Change it back to the original menu. Save button is still present even though nothing is really set to save.

**Comment by designsimply** [comment]
Re-tested with WPiOS 15.4.0.3 TestFlight beta on iPhone 11 iOS 13.6 and confirmed that if I go to My Site > Menus, change the menu, then change the menu back to the originally selected one I can still see the options to Save or Discard in the header. ([57s](https://cloudup.com/crzrbP7koKX))
