### ISSUE TITLE
Menus: Long title disrupts trash/edit icon

### ISSUE THREAD

**Issue by jeremeylduvall** [wordpress-mobile/WordPress-iOS#9833]
If I’m editing a menu item with a regular length title (like “Default Menu”) and then switch the dropdown on the menu I’m currently using/editing, the menu title field stays in edit mode (which is awesome), but the “Done” and pencil icon are both present/overlap if the new menu has a long title.

### Steps to reproduce the behavior
1. In the menus section of the app, click on the menu title of a menu with a short name (like "Default Menu")
2. Click the selector to change the menu in use. The title field should stay in edit mode (awesome!). Select a menu with a long title. The pencil icon and done link will overlap.

Video: https://cld.wthms.co/Pdqk6y

### Screenshot

<img width="380" alt="awyxco" src="https://user-images.githubusercontent.com/7240478/43102754-383d8f12-8e89-11e8-8839-7057b0c422b4.png">

##### Tested on iPhone 8 Plus, iOS 11.4, WPiOS 10.4

**Comment by ScoutHarris** [comment]
It looks like this view has changed and thus the issue negated, as the pencil icon no longer shows in edit mode.

<img width="350" alt="edit_menu" src="https://user-images.githubusercontent.com/1816888/56833966-5fb49d00-682d-11e9-91f8-d00d721f19ec.png">
