### ISSUE TITLE
Images don't wrap text properly

### ISSUE THREAD

**Issue by Piyopiyo-Kitsune** [wordpress-mobile/WordPress-iOS#9854]
### Issue

When an image is inserted into a page/post, made smaller, and then left aligned there is still space to the right and text cannot be added to the right of the image. Text can also not be added to the left of a right-aligned image. It appears that the image will continue to take up the whole line.

### Expected behavior
Text can be wrapped around a left or right aligned image

### Actual behavior
The image takes up the complete line.

### Steps to reproduce the behavior
1. Create a post or page
2. Add media
3. Adjust the image sizing to medium or thumbnail
4. Left or right align the image
5. Try typing to the right or left of the aligned image

##### Tested on [device], iOS [version], WPiOS [version]
iPad Model A1822 iOS 11.4.1 WPiOS 10.4

##### Video
https://cloudup.com/cd72ztdSKmU

**Comment by tomnnancy** [comment]
Awaiting an outcome for the above mentioned concerns. I use my iPad for work/travel and was wondering if you have a fix or an estimation for the correction of this problem.

**Comment by rachelmcr** [comment]
I'm closing this issue, since we're tracking it in https://github.com/wordpress-mobile/AztecEditor-iOS/issues/1047 where the changes would have to be made. Please follow that issue for further updates. Thanks for raising this!
