### ISSUE TITLE
Plans Page Sometimes Doesn't Load

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9856]
I have seen a handful of questions over the last month or two where users are going to the Plans section of the app, and they are coming across an error message instead.  This has been happening infrequently enough that I have not been able to figure out what links the issues, but I have seen it a handful of times. 
What I have noticed so far is that this problem seems to be only iOS, and happens to WPCOM users.  When the WPCOM users go to My Site > Plans they see this page 
<img src='http://cld.wthms.co/UF26Bq+'>

The most recent issue I came across with this problem was 1300122-zd-woothemes
The user was using WordPress 10.4.1
iOS 11.4.1
and had a premium plan on their site.

I first brought this up here p4a5px-2eR-p2 and @ScoutHarris found in the logs that noActivePlan is coming up in the logs when the user visits that page, which is causing the error, but we couldn't figure out why the user was showing up as having no plan.

I don't have a to replicate, cause I can't replicate it...  With previous issues I have had users reinstall the app, and reconnect, but that did not fix the problem.

**Comment by ScoutHarris** [comment]
More technical information -

`PlanServiceRemote:mapPlansResponse` is looking for the `current_plan` flag on the plans. For this customer at least, that flag is not present in the API response, thus this check is failing:
```
    guard let activePlan = parsedResponse.0 else {
        throw PlanServiceRemote.ResponseError.noActivePlan
    }
```

**Comment by aerych** [comment]
Dug into this a bit more. The user is on a two year premium plan (id 1023) which is not one of the four plan types returned by the v1.2/sites/%s/plans endpoint.

I think this explains why the current plan flag is missing. The implementation of the plans feature in the mobile apps is very old and probably did not anticipate more than the four plan types it shows.

We’ll probably need to update the apps to fix the issue. I don’t think there’s anything server-side we can do to resolve this particular situation.

**Comment by charliescheer** [comment]
That would make sense, I started seeing reports of this around the time that the 2 year plans rolled out.  Good find!
