### ISSUE TITLE
Content is being added to unordered lists when it shouldn't be.

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9857]
I came across this problem in this issue https://woothemes.zendesk.com/agent/tickets/1282721

What is happening is, if you create an ordered list in the iOS app, and then hit enter twice to exit that list, and then continue writing more content, then if you save that post as a draft, the content that came after the ordered list will appear in an unordered list.  If you then return to edit the post, the unordered list does not appear in the WYSWIG editor.  

I created a quick screen grab of this problem in action
http://cld.wthms.co/UTUCS6

The steps to reproduce:
1.While editing a post, tap on the list button and choose Ordered List
2.Create your ordered list, and when finished hitting the return key twice to exit
3.Continue working on your post, but now every time you hit enter the new line is added to an unordered list?
4.Save as draft 
5. Navigate to drafts section and click “Preview”

iPhone 6s
WordPress 10.4
iOS 11.4.1

**Comment by diegoreymendez** [comment]
Aztec issue for this WP issue: https://github.com/wordpress-mobile/AztecEditor-iOS/issues/1012

This one will be closed once integrated into WPiOS.

**Comment by diegoreymendez** [comment]
PR is up here: https://github.com/wordpress-mobile/AztecEditor-iOS/pull/1013 and waiting for review.
