### ISSUE TITLE
[Media] Can't set featured image in iOS-App

### ISSUE THREAD

**Issue by M1g4** [wordpress-mobile/WordPress-iOS#9871]
### Expected behavior
I'd like to set any given image as the featured image of a post within the Wordpress iOS-app. 

### Actual behavior
There is an error message stating somehting like "The attempt to upload your media encountered a problem. Try again later." (I use the German translation so I'm not sure how the message reads exactly.)

Android devices work perfectly fine, only the iOS app is affected.

### Additional info that might be helpful
We took a look into our server-logs. When using an Android phone to set a featured image, the log shows that the app uses a POST-request to communicate with the xmlrpc.php. 
`www.******.de:80 **.***.**.** - - [30/Jul/2018:14:43:36 +0200] "POST /xmlrpc.php HTTP/1.1" 200 929 "-" "Mozilla/5.0 (Linux; Android 7.0; VTR-L09 Build/HUAWEIVTR-L09; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.87 Mobile Safari/537.36 wp-android/10.4" runtime=232997 php_memory=33030144
www.******.de:80 **.***.**.** - - [30/Jul/2018:14:43:36 +0200] "POST /xmlrpc.php HTTP/1.1" 200 483 "-" "Mozilla/5.0 (Linux; Android 7.0; VTR-L09 Build/HUAWEIVTR-L09; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.87 Mobile Safari/537.36 wp-android/10.4" runtime=251514 php_memory=33030144
www.******.de:80 **.***.**.** - - [30/Jul/2018:14:43:36 +0200] "POST /xmlrpc.php HTTP/1.1" 200 483 "-" "Mozilla/5.0 (Linux; Android 7.0; VTR-L09 Build/HUAWEIVTR-L09; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.87 Mobile Safari/537.36 wp-android/10.4" runtime=278549 php_memory=33030144`

When I use the iPhone, the app tries to use a GET request which causes an error 405, method not allowed.
`www.******.de:80 **.***.**.**- - [30/Jul/2018:14:40:39 +0200] "GET /xmlrpc.php HTTP/1.1" 405 203 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15G77 wp-iphone/10.4.1" runtime=323805 php_memory=32768000
www.******.de:80 **.***.**.** - - [30/Jul/2018:14:40:39 +0200] "GET /xmlrpc.php HTTP/1.1" 405 203 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15G77 wp-iphone/10.4.1" runtime=390992 php_memory=32768000
www.******.de:80 **.***.**.** - - [30/Jul/2018:14:40:39 +0200] "GET /xmlrpc.php HTTP/1.1" 405 203 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15G77 wp-iphone/10.4.1" runtime=362954 php_memory=32768000`

##### Tested on [device], iOS [version], WPiOS [version]
iPhone 7+, iOS 11.4.1, Wordpress 10.4.1
Huawei P10, Android 7.0, Wordpress 10.4
Wordpress 9.6 on the server

**Comment by elibud** [comment]
@designsimply can you check if this one is still an issue?

**Comment by ceyhun** [comment]
I was not able reproduce this.

<p style="clear:both;"><sup>Tested with iPhone 11 Pro, iOS 14.4, WPiOS 17.0.0.20210329</sup></p>
