### ISSUE TITLE
Localized Terms of Service Text Cut off in French

### ISSUE THREAD

**Issue by emilyaudela** [wordpress-mobile/WordPress-iOS#9873]
In the Login sceen, when clicking the "Sign up for WordPress.com" button, the following screen includes the text "By signing up, you agree to our _Terms of Service_.". In French, the "Terms of Service" text is missing, so it reads "En vous inscrivant, vous acceptez les ".

![screen shot on 2018-07-30 at 09 37 06](https://user-images.githubusercontent.com/36699353/43407496-2698ac94-93dc-11e8-95fc-06f183c51f1a.png)

**Expected behavior**
The text with the link should be completely visible.

**Steps to reproduce the behavior**
* Change the app to French
* Under the "Me" tab, select "Sign In" (Connectez-vous) and then tap the "Sign up for WordPress.com" 
 ("Se connecter à WordPress.com") button.

Tested on [device], iOS [version], WPiOS [version]

**Comment by pinarol** [comment]
couldn't reproduce the issue with iPhone 5s in the latest develop branch, I think this had been already fixed.

<img width="325" alt="screen shot 2019-01-09 at 11 58 03" src="https://user-images.githubusercontent.com/5032900/50888128-ff2c5c00-1405-11e9-90f6-318f09f4aab8.png">
