### ISSUE TITLE
Reader: Improve how quotes are displayed in posts

### ISSUE THREAD

**Issue by elibud** [wordpress-mobile/WordPress-iOS#9881]
### Expected behavior
Quotes on a Gutenberg post should display correctly on Reader.

### Actual behavior
They don't look like quotes at all.

![img_1255](https://user-images.githubusercontent.com/5558824/43466176-52497af6-94b5-11e8-9b57-e62c3013a5d3.jpg)

### Steps to reproduce the behavior
Check out a post with quotes on reader.

**Comment by koke** [comment]
I'm not entirely sure what's wrong with them. I looked at a non-Gutenberg post to compare and it seems similar to this:

![img_a295d4a03c01-1](https://user-images.githubusercontent.com/8739/44770564-b9fb4200-ab68-11e8-9fc3-2e27ef3e4575.jpeg)

Do we have a design of how they should look like?

**Comment by elibud** [comment]
Well, it is very possible that I've lost my mind, but I was pretty sure they used to look closer to Android, with a line on the side.

![screenshot_20180730-205111](https://user-images.githubusercontent.com/5558824/44808576-f9468480-aba2-11e8-89ed-62de8f42966c.png)

That being said, this is clearly not a Gutenberg problem, thanks for checking it out @koke. Let's get a Design Review and take it from there. @SylvesterWilmott @iamthomasbishop how do you think quotes should look in Reader, both iOS and Android?

**Comment by koke** [comment]
That seems to match what calypso is doing
![3dbbbef5-5678-4cec-a3f7-17995876b981](https://user-images.githubusercontent.com/8739/44899936-886aae00-ad03-11e8-84e7-aab8d149d69f.png)

**Comment by iamthomasbishop** [comment]
Design decision time: let's match calypso styling for now, but narrow the spacing between the vertical line and content.

<img width="840" alt="screenshot 2018-09-17 11 05 03" src="https://user-images.githubusercontent.com/1200432/45635027-8d509100-ba69-11e8-87de-0bd67fd14e39.png">

The vertical border is `#e9eff3` aka `greyLighten30` on Calypso, so we can match that.

Text color is `#4f748e`, aka `greyDarken20`.

**Comment by aerych** [comment]
You ask for a tricky thing. :)

The web, and the Android reader (@nbradbury can correct me if I'm wrong) achieve the vertical border by defining it in CSS.  Something like `border-left:3px solid #e9eff3`.  There is limited HTML and CSS support available in TextKit when configuring an NSAttributedString with an `NSAttributedString.DocumentType.html` document type (as we do).  Unfortunately `blockquotes` are barely supported (we can set the color via CSS but have to manually apply indentation) and borders are not supported at all.  

If we're unable to define the define the border as an attribute on the NSAttributeString, we could try composing it with some special handling in a NSLayoutManagerDelegate.  We could add a custom attribute for blockquotes, get the range of that attribute, calculate the CGRect that text range will be drawn in then clear/draw the border in a separate drawing context anytime the NSTextContainer's geometry changes.   Its a bit hacky and I'm inclined to say its not worth the effort. 

Maybe @diegoreymendez knows of a different trick?

**Comment by aerych** [comment]
Aztec has [a solution](https://github.com/wordpress-mobile/AztecEditor-iOS/blob/35312f4211b5af60c5fb3a5592605069b8c4446c/Aztec/Classes/TextKit/LayoutManager.swift) to this puzzle that @diegoreymendez shared with me -- a custom NSLayoutManager (not a delegate) to draw the background of the block quote.

**Comment by jklausa** [comment]
I fell like I might be over my head on this but I'll try tackling this.

**Comment by jklausa** [comment]
The code for this is atrocious for now, but I think we're getting somewhere :)

![Simulator Screen Shot - iPhone Xs Max - 2019-04-03 at 06 21 22](https://user-images.githubusercontent.com/1594081/55452631-bcc78500-55d8-11e9-8c12-815b0cbfcd27.png)

**Comment by elibud** [comment]
Looking good @jklausa, does the same atrocious code work for the post body?

**Comment by diegoreymendez** [comment]
Looking good!
