### ISSUE TITLE
Some Plan Descriptions Not Translated - Canadian French

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9884]
If you visit the plans page while the device is set to Canadian French only the description of the Personal plan is translated into French from English (note: this is not a problem with French)

<img src='http://cld.wthms.co/LHKFnp+'>

<img src='http://cld.wthms.co/VRKPsP+'>

**Comment by rachelmcr** [comment]
Thanks for the report, @charliescheer. It looks like the plan strings aren't all translated for Canadian French, for example:

https://translate.wordpress.com/projects/wpcom/fr-ca/default/?filters%5Boriginal_id%5D=171670

Those strings will need to be translated in the WordPress.com project, first. If the translated strings still don't show up after those translations are approved and deployed, we can reopen this issue for further investigation.
