### ISSUE TITLE
Translation - Sharing page not handling special characters Canadian French

### ISSUE THREAD

**Issue by charliescheer** [wordpress-mobile/WordPress-iOS#9885]
If you go to the Sharing > Management page while set to Canadian French (is fine in French)

There seems to be an issue handling special characters.  If you look on the "libellé" section it shows Partager&nbsp:: instead of Partager :

<img src='http://cld.wthms.co/P27QXf+'>

**Comment by rachelmcr** [comment]
It looks like this default sharing label comes from [this WordPress.com translation](https://translate.wordpress.com/projects/wpcom/fr-ca/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=23737&filters%5Btranslation_id%5D=2314178). One fix in the app could be to process any HTML entities like this, but I don't see any reason for an encoded non-breaking space in this string, so I'd suggest fixing the translation itself.

**Comment by rachelmcr** [comment]
You can see the [FR translation here ](https://translate.wordpress.com/projects/wpcom/fr/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=23737&filters%5Btranslation_id%5D=7235796) for an option that doesn't include the HTML entity.
