### ISSUE TITLE
Media Library: 'you have no media' appears just before the media does.

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#9922]
### Expected behavior
After the media is loaded, the view should go from 'fetching media' to displaying the media.  

### Actual behavior
After the media is loaded, 'you have no media' displays for a split second, then the media is displayed.

### Steps to reproduce the behavior
- A slow internet connection may be required.
- Also, a fresh install may be required as the media seems to cache.
- Go to Media Library on a site with media.
- See the view go from 'fetching media' >  'you have no media' > actual media display.

This is caused by `pickerDataSource.numberOfAssets()` being 0 when `mediaPickerControllerDidEndLoadingData` is called from the `MediaPicker` pod. It does eventually updates to the correct number. However, this is resulting in the NoResultsView showing the view for no media for a split second until `numberOfAssets` is updated.

![no_media_message](https://user-images.githubusercontent.com/1816888/43731853-137c3ba8-996d-11e8-9fa6-b33d7903720b.gif)

**Comment by kean** [comment]
The fix will ship when https://github.com/wordpress-mobile/WordPress-iOS/issues/21457 is released.
