### ISSUE TITLE
<pre> tags added around unordered lists in some cases

### ISSUE THREAD

**Issue by SiobhyB** [wordpress-mobile/WordPress-iOS#9928]
### Expected behavior

After creating an unordered list within the app, I expected to be able to view a neat list with bullet points at the start of each line.

### Actual behavior

`<pre>` tags are added around certain points in the unordered list, which makes the list's underlying HTML visible.

For example, in the following screenshot, a `<pre>` tag was added just after the "Five" list item:

<img width="783" alt="screen shot 2018-08-07 at 15 27 29" src="https://user-images.githubusercontent.com/2998162/43782105-6de34818-9a56-11e8-83dc-9f25d916afc9.png">

### Steps to reproduce the behavior

1. Navigate to My Site > Blog Posts and edit an existing post.
2. Use the app's built list icon to create a new unordered list.
3. Add multiple list items. 

This can be tricky to replicate but seems to happen when there's a mix of one word, multiple words, etc. I also had success replicating by adding some empty list items at random.

Copying the following list is a good step to replicating, also:

```
One
Two
Three
S T E P O N E:<
One. Two. Three.
S T E P T W O:
Four. Five.
D O N E!!!
```
##### Tested on iPad Mini, iOS 11.4.1, WPiOS 10.5

This was reported to us in 1274385-z

**Comment by ceyhun** [comment]
I was not able reproduce this. I tried manually typing the list items mentioned in the issue and also randomly adding some empty list items.

<p style="clear:both;"><sup>Tested with iPhone 11 Pro, iOS 14.4, WPiOS 17.0.0.20210329</sup></p>

**Comment by ceyhun** [comment]
Closing this as non reproducible but, please feel free to reopen if it still occurs, thanks!
