### ISSUE TITLE
Multiple translations for a string 

### ISSUE THREAD

**Issue by loremattei** [wordpress-mobile/WordPress-iOS#9948]
Looking at the localisation of the app, we found that sometimes, in some languages, one string may require different translations, depending on the context.
Since the string id used by the translation system is the string itself, it seems not possible to have multiple translations for a single string.

**Comment by ctarda** [comment]
Thanks for reporting this @loremattei . 

I think you mentioned "Me" in Italian (which also makes sense in Spanish), but if you have any other specific examples of an specific string (or strings) that you would like to see specialised in an specific language, that'd be very helpful.

**Comment by AliSoftware** [comment]
Just randomly found this old issue, so noting that this will very soon be (finally!) fixed by item [i8] of internal project paaHJt-2Ib-p2 — which means we should remember to close it when this project officially lands

**Comment by AliSoftware** [comment]
Closing this now that the new localization tooling allows using an arbitrary key which can be something different from the English copy / default value for the string.

See paNNhX-nP-p2 for more details
