### ISSUE TITLE
Rich Notifications : Restrict notification service extension modifications to supported notification types

### ISSUE THREAD

**Issue by stevebaranski** [wordpress-mobile/WordPress-iOS#9971]
As discussed in the PR for [9968](https://github.com/wordpress-mobile/WordPress-iOS/pull/9968), the service extension should guard on supported notification types. For the initial release, this will be limited to `comment` types.

This change depends on D17104-code, which implements a new `note_type` field in the payload.

**Comment by stevebaranski** [comment]
@frosty can you help confirm the valid values that will occupy the `note_type` field?

**Comment by elibud** [comment]
@stevebaranski is this one ready to be closed?

**Comment by stevebaranski** [comment]
Yes @elibud - I'll tidy this up now.
