### ISSUE TITLE
Site Pages and Posts: no results view displays before loading view

### ISSUE THREAD

**Issue by ScoutHarris** [wordpress-mobile/WordPress-iOS#9993]
### Expected behavior
On a slow network, when selecting Site Pages or Blog Posts, the loading view should show first.

### Actual behavior
On a slow network, when selecting Site Pages or Blog Posts, the "you don't have any xxx" view displays first, then the loading view, then the final view.

I'm noting both Site Pages and Blog Posts here because their logic and behavior is the same. 

Because `syncHelper.isSyncing` is `false` initially, the no results view displays immediately. Of course when it updates to `true`, _then_ the loading view is displayed.

### Steps to reproduce the behavior
- On a slow network, select either Site Pages or Blog Posts.
- Notice the views displayed:

![nrv](https://user-images.githubusercontent.com/1816888/44177512-853cb480-a0ab-11e8-81be-12f65422ab4d.gif)

**Comment by designsimply** [comment]
I tested from a slow connection and found that I didn't see the no results view before the loading view when opening the posts list using WP Internal 13.1.0.20190814 on iPhone 6S iOS 12.4. ([1m27s](https://cloudup.com/coqj4I0j8Qi)) 

I believe this was fixed when the posts list was revamped in 12.9 (see https://github.com/wordpress-mobile/WordPress-iOS/pull/12087).

<img src="https://user-images.githubusercontent.com/1119271/63185714-fd6bec00-c017-11e9-9ad8-c4e225e4c6c3.PNG" width="270" alt="IMG_2934"> <img src="https://user-images.githubusercontent.com/1119271/63186277-4bcdba80-c019-11e9-86b7-c65fd6f101bc.jpg" width="270" alt="fetching-pages">
<sup>Tested with WP Internal 13.1.0.20190814 on iPhone 6S iOS 12.4.</sup>
